### ISSUE TITLE
Transparent background not working on catppuccin theme.

### ISSUE THREAD

**Issue by sravanpannala** [AstroNvim/AstroNvim#1001]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v1.9.0-77-gaf1d706

### Neovim version (>= 0.7)

NVIM v0.7.2

### Operating system/version

Arch Linux

### Describe the bug

Transparent background not working on catppuccin theme.

There is no documentation on transparent background in astronvim.
I'm using catppuccin theme according to the example in the documentation.
I've also followed the example in catppuccin gihub repo to enable transparent background but it doesn't work.

### Steps to Reproduce

1. In `~/.config/nvim/lua/user/init.lua`. enable catppuccin transparency in config.
```
local config = {

  -- Set colorscheme
  -- colorscheme = "default",
  plugins = {
    init = {
      { "catppuccin/nvim",
        as = "catppuccin",
        config = function() 
          require("catppuccin").setup({
            transparent_background = true,
          }) 
        end,
      },
    },
  },
  options = {
    g = {
      catppuccin_flavour = "mocha",
    },
  },
  colorscheme = "catppuccin",
}
return config
```

### Expected behavior

I expect the background to be transparent but it isn't.

### Screenshots

![image](https://user-images.githubusercontent.com/57152030/192122064-117bd5b3-888b-4715-96a5-04541033090d.png)

**Comment by sravanpannala** [comment]
I tried `:PackerClean`, and then the transparent background is working. Don't know what happened.

**Comment by mehalter** [comment]
Awesome, glad to hear this is resolved
