### ISSUE TITLE
Add GitHub Copilot Integration

### ISSUE THREAD

**Issue by JulianCologne** [AstroNvim/AstroNvim#1005]
### Is your feature related to a problem?

Coming from VSCode I really like AstroNvim's batteries included out of the box experience!!
The only thing I am personally missing is GitHub Copilot integration.
As a nvim and lua beginner I tried to add it myself with moderate success. It kind of works but there seems to be a collision with the completion key mapping and some visuals of the linter overlap.
Also, I love tools that work perfectly out of the box and have great default values and I don't have to fiddle with additional settings or integrations (only copilot missing for me).

### Describe the new feature

Integration of GitHub Copilot into AstroNvim by default that can optionally be activated by the user and works as expected! 
<3

**Comment by mehalter** [comment]
We are not going to add this because it leverages non-open source services to AstroNvim. If you need help getting it working, I would recommend checking out the Discord server as I know there are at least a few folks there that are using Copilot with AstroNvim.

**Comment by marlls1989** [comment]
At least put a pointer to a solution. It is not trivial finding a way to integrate copilot into astronvim, this is a deal breaker for me.

**Comment by mehalter** [comment]
@marlls1989 check out AstroCommunity: https://github.com/AstroNvim/astrocommunity

There is a plugin pack for adding Copilot and integrating the key bindings with nvim-cmp: https://github.com/AstroNvim/astrocommunity/blob/main/lua/astrocommunity/completion/copilot-lua-cmp/copilot-lua-cmp.lua
