### ISSUE TITLE
How do I uninstall AstroNvim?

### ISSUE THREAD

**Issue by usmanity** [AstroNvim/AstroNvim#1006]
### Question

I am unsure how to uninstall AstroNvim from my mac setup, can someone please provide instructions on how to properly uninstall all components associated with AstroNvim?

### User Configuration

My config is unmodified from the base AstroNvim setup.

**Comment by convers39** [comment]
```bash
rm -rf ~/.config/nvim
rm -rf ~/.cache/nvim
rm -rf ~/.local/share/nvim
```

Remove these folders or use `mv` to make a backup.

**Comment by mehalter** [comment]
Thanks for the detailed response @convers39 !

**Comment by usmanity** [comment]
thank you both!
