### ISSUE TITLE
How do you disable autocompletion for brackets, quotes, etc.?

### ISSUE THREAD

**Issue by tillfalko** [AstroNvim/AstroNvim#1007]
### Question

I have done my best looking through the documentation of Astronvim and the Plugins listed in an attempt to find an option to disable this behavior, but I could not find it.

**Comment by mehalter** [comment]
You should be able to do something like this in your `user/init.lua` file to disable the `nvim-autopairs` plugin and remove it:

```lua
return {
  plugins = {
    init = {
      ["windwp/nvim-autopairs"] = { disable = true },
    },
    treesitter = {
      autopairs = { enable = false },
    },
  },
}
```

Also AstroNvim 2.0 is right around the corner, in the next couple weeks as Neovim 0.8 releases to stable and we finish testing the new implementations. This will come with an ability to disable autopairs on startup as well as a new user experience keybinding menu that will let you toggle it on and off on demand. :)

**Comment by tillfalko** [comment]
Thanks, for the response.
The suggested solution did not work for me, but knowing that the plugin is called nvim-autopairs helped me a lot.

The solution that worked was adding
```lua
require('nvim-autopairs').disable(),
```
to my init.lua.

I'm looking forward to 2.0 :)

**Comment by oryband** [comment]
solution https://github.com/AstroNvim/AstroNvim/issues/1574#issuecomment-1427023701
