### ISSUE TITLE
issue with the default user/init.lua file

### ISSUE THREAD

**Issue by azinsharaf** [AstroNvim/AstroNvim#1010]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

1.9.2-3

### Neovim version (>= 0.7)

NVIM v0.8.0-dev-1182-gd84abfeb1

### Operating system/version

WSL 1 (Ubuntu 20.04)

### Describe the bug

Astronvim works fine as a new install but as soon as i create the `user` folder and copy the default `init.lua` file in it then Astronvim opens with `stylua` and `prettier` errors: 
 
![image](https://user-images.githubusercontent.com/10101468/192599112-3443a5f4-ecd6-4b56-bcaf-75e2ce4b04d3.png)

PackerUpdate, PackerSync & AstroUpdate didn't fix the issue. 
When I remove `user` folder the error disappears. 

### Steps to Reproduce

- install the latest nightly `Neovim`
- copy the `user_example` folder as `user` folder
- launch astronvim

### Expected behavior

no error

**Comment by mehalter** [comment]
If you run `:Mason` and check what the installation error is? I should also just remove the default stylers and stuff because it's been a pretty bad practice anyway.

**Comment by azinsharaf** [comment]
no error in Mason
![image](https://user-images.githubusercontent.com/10101468/192605315-bd1127c6-9465-4883-8619-3afa047ad718.png)
and it shows `stylua` is available (not installed)

**Comment by mehalter** [comment]
What happens when you try to install `stylua`

**Comment by azinsharaf** [comment]
installing `stylua` works with `{ "JohnnyMorganz/StyLua" },` in plugins.init table. But still not showing up as Installed in Mason.

**Comment by mehalter** [comment]
@azinsharaf that isn't a vim plugin, so it's just going to copy that information into your plugin install folder and then nothing is going to happen.

**Comment by mehalter** [comment]
stylua is a normal command line tool, so it is not installed through packer or anything. Mason is a package installer not a vim plugin installer.
