### ISSUE TITLE
How to change the color of the indentation line?

### ISSUE THREAD

**Issue by nappalm** [AstroNvim/AstroNvim#1012]
### Question

![image](https://user-images.githubusercontent.com/35016608/192646176-77835231-f85f-49e4-82f3-bd3000ae368c.png)

Is it possible to change the white line to transparent?

### User Configuration

Default configuration

**Comment by mehalter** [comment]
You can do this a couple ways, you can either override the highlight groups to make it transparent, or you can just set the character to a space.

Here is a minimal `user/init.lua` file that just overrides `indent_blankline` setup to make the grey lines transparent:

```lua
return {
  plugins = {
    indent_blankline = {
      char = " ",
    },
  },
}
```
