### ISSUE TITLE
warning: multiple different client offset_encodings detected for buffer, this is not supported yet

### ISSUE THREAD

**Issue by jiriks74** [AstroNvim/AstroNvim#1013]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

Version: v1.9.2-4-g294e996

### Neovim version (>= 0.7)

NVIM v0.7.2

### Operating system/version

ArchLinux

### Describe the bug

An error of unknown cause (couldn't find anything, I just started using NeoVim and AstroVim) keeps popping up on every keypress in insert mode to an extent where most of the code is unreadable

### Steps to Reproduce

1. Make a new install of AstroVim
2. Open a C++ project
3. Open a .cpp file
4. Let LSP install clangd
5. Try to type anything
6. Error pops up

### Expected behavior

No error popping up

### Screenshots

![image](https://user-images.githubusercontent.com/54378412/193055525-91a99c8a-49e3-40b5-b1a0-f974d43ec735.png)

**Comment by mehalter** [comment]
You can customize your `clangd` LSP server settings to specify what offset encoding you would like to use. `clangd` supports multiple offset encodings. Here is an example `user/init.lua` file:

```lua
return {
  lsp = {
    ["server-settings"] = {
      clangd = {
        capabilities = { offsetEncoding = "utf-8" },
      },
    },
  },
}
```

**Comment by edassis** [comment]
Hi, I'm migrating for version 3.0, how can I apply this solution in the new architecture?

I tried to place the recommended snippet under the `lsp` table in _init.lua_, but without success (I'm using the [user configuration template](https://github.com/AstroNvim/user_example)):

```lua
    lsp = {
      -- ...
      -- enable servers that you already have installed without mason
      servers = {
        -- "pyright"
      },
      -- Add overrides for LSP server settings, the keys are the name of the server
      ["server-settings"] = {
        clangd = {
          capabilities = { offsetEncoding = "utf-8" },
        },
      },
    },
```

**Comment by jiriks74** [comment]
@edassis 
Minimal AstroNvim config for v3 I use
```lua
local config = {
  lsp = {
	config = {
      clangd = {
        capabilities = { offsetEncoding = "utf-8" }
      }
    }
  }
}
```

**Comment by TahaBinhuraib** [comment]
@jiriks74 Which file did you add this to? I added it to my lsp.lua but it didnt work

**Comment by jiriks74** [comment]
> @jiriks74 Which file did you add this to? I added it to my lsp.lua but it didnt work

`init.lua`
It's a minimal config you'll have to find the LSP config section and add the clangd section in there

**Comment by TahaBinhuraib** [comment]
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/69626776/228834397-ffaf5fb3-a622-4f1b-b3e2-43128882c240.png">

**Comment by matyle** [comment]
insert still have this warning

**Comment by matyle** [comment]
> insert still have this warning

insert still have this warning

**Comment by matyle** [comment]
> You can customize your `clangd` LSP server settings to specify what offset encoding you would like to use. `clangd` supports multiple offset encodings. Here is an example `user/init.lua` file:
> 
> ```lua
> return {
>   lsp = {
>     ["server-settings"] = {
>       clangd = {
>         capabilities = { offsetEncoding = "utf-8" },
>       },
>     },
>   },
> }
> ```

insert still have this warning

**Comment by matyle** [comment]
> > I tried adding this in the main init.lua
> 
> Please read the documentation available at [astronvim.com](https://astronvim.com)
> 
> Do not touch the `init.lua` in the root directory, you are supposed to modify the user config. The relevant section in the user's `init.lu` should look like this after edits:
> 
> ![image](https://user-images.githubusercontent.com/54378412/228880338-ffe1a57b-b217-4fb4-a6e9-715dfeea2b01.png)

when you insert still have this warning

**Comment by matyle** [comment]
> @edassis Minimal AstroNvim config for v3 I use
> 
> ```lua
> local config = {
>   lsp = {
>     config = {
>       clangd = {
>         capabilities = { offsetEncoding = "utf-8" }
>       }
>     }
>   }
> }
> ```

this is right

**Comment by 0xricksanchez** [comment]
```lua
--- user/init.lua
return {
  lsp = {
    config = {
      clangd = {
        capabilities = { offsetEncoding = "utf-8" }
      },
    },
  },
  --- plugin section
  plugins = {},
  --- other user config options
}
```

**Comment by gui-bo** [comment]
I am having  the same problem. Could someone please tell me which file i have to change. I don't have a user/init.lua. I looked at the documentation, but didn't find anything

**Comment by gui-bo** [comment]
Thank you! 
I have already changed the file `lua/plugins/astrolsp.lua` and uncommented the line:
`clangd = { capabilities = { offsetEncoding = "utf-8" } },`
But still have the problem.

Am I missing something?

**Comment by mehalter** [comment]
you should share your configuration or at least the entire `lua/plugins/astrolsp.lua` file to show exactly what you have and maybe we can identify what mistake was made

**Comment by gui-bo** [comment]
```
if true then return {} end -- WARN: REMOVE THIS LINE TO ACTIVATE THIS FILE

-- AstroLSP allows you to customize the features in AstroNvim's LSP configuration engine
-- Configuration documentation can be found with `:h astrolsp`
-- NOTE: We highly recommend setting up the Lua Language Server (`:LspInstall lua_ls`)
--       as this provides autocomplete and documentation while editing

---@type LazySpec
return {
  "AstroNvim/astrolsp",
  ---@type AstroLSPOpts
  opts = {
    -- Configuration table of features provided by AstroLSP
    features = {
      autoformat = true, -- enable or disable auto formatting on start
      codelens = true, -- enable/disable codelens refresh on start
      inlay_hints = false, -- enable/disable inlay hints on start
      semantic_tokens = true, -- enable/disable semantic token highlighting
    },
    -- customize lsp formatting options
    formatting = {
      -- control auto formatting on save
      format_on_save = {
        enabled = true, -- enable or disable format on save globally
        allow_filetypes = { -- enable format on save for specified filetypes only
          -- "go",
        },
        ignore_filetypes = { -- disable format on save for specified filetypes
          -- "python",
        },
      },
      disabled = { -- disable formatting capabilities for the listed language servers
        -- disable lua_ls formatting capability if you want to use StyLua to format your lua code
        -- "lua_ls",
      },
      timeout_ms = 1000, -- default format timeout
      -- filter = function(client) -- fully override the default formatting function
      --   return true
      -- end
    },
    -- enable servers that you already have installed without mason
    servers = {
      -- "pyright"
    },
    -- customize language server configuration options passed to `lspconfig`
    ---@diagnostic disable: missing-fields
    config = {
      clangd = { capabilities = { offsetEncoding = "utf-8" } },
    },
    -- customize how language servers are attached
    handlers = {
      -- a function without a key is simply the default handler, functions take two parameters, the server name and the configured options table for that server
      -- function(server, opts) require("lspconfig")[server].setup(opts) end

      -- the key is the server that is being setup with `lspconfig`
      -- rust_analyzer = false, -- setting a handler to false will disable the set up of that language server
      -- pyright = function(_, opts) require("lspconfig").pyright.setup(opts) end -- or a custom handler function can be passed
    },
    -- Configure buffer local auto commands to add when attaching a language server
    autocmds = {
      -- first key is the `augroup` to add the auto commands to (:h augroup)
      lsp_document_highlight = {
        -- Optional condition to create/delete auto command group
        -- can either be a string of a client capability or a function of `fun(client, bufnr): boolean`
        -- condition will be resolved for each client on each execution and if it ever fails for all clients,
        -- the auto commands will be deleted for that buffer
        cond = "textDocument/documentHighlight",
        -- cond = function(client, bufnr) return client.name == "lua_ls" end,
        -- list of auto commands to set
        {
          -- events to trigger
          event = { "CursorHold", "CursorHoldI" },
          -- the rest of the autocmd options (:h nvim_create_autocmd)
          desc = "Document Highlighting",
          callback = function() vim.lsp.buf.document_highlight() end,
        },
        {
          event = { "CursorMoved", "CursorMovedI", "BufLeave" },
          desc = "Document Highlighting Clear",
          callback = function() vim.lsp.buf.clear_references() end,
        },
      },
    },
    -- mappings to be set up on attaching of a language server
    mappings = {
      n = {
        gl = { function() vim.diagnostic.open_float() end, desc = "Hover diagnostics" },
        -- a `cond` key can provided as the string of a server capability to be required to attach, or a function with `client` and `bufnr` parameters from the `on_attach` that returns a boolean
        -- gD = {
        --   function() vim.lsp.buf.declaration() end,
        --   desc = "Declaration of current symbol",
        --   cond = "textDocument/declaration",
        -- },
        -- ["<Leader>uY"] = {
        --   function() require("astrolsp.toggles").buffer_semantic_tokens() end,
        --   desc = "Toggle LSP semantic highlight (buffer)",
        --   cond = function(client) return client.server_capabilities.semanticTokensProvider and vim.lsp.semantic_tokens end,
        -- },
      },
    },
    -- A custom `on_attach` function to be run after the default `on_attach` function
    -- takes two parameters `client` and `bufnr`  (`:h lspconfig-setup`)
    on_attach = function(client, bufnr)
      -- this would disable semanticTokensProvider for all clients
      -- client.server_capabilities.semanticTokensProvider = nil
    end,
  },
}
```

**Comment by mehalter** [comment]
@gui-bo that is what I expected, take a close look at the entire file 😄

**Comment by gui-bo** [comment]
I see it know. I am so sorry for wasting your time. Thank you!!

**Comment by mehalter** [comment]
No problem! Glad you got it situated. I'll mark these last few comments off topic just to not distract anyone else who might stumble into this issue
