### ISSUE TITLE
How do I remove a default key binding?

### ISSUE THREAD

**Issue by DeeGeeMan** [AstroNvim/AstroNvim#1015]
### Question

What is the best way to remove the default 'jj' key binding?

**Comment by mehalter** [comment]
There are a few things. One thing is any mapping defined in the `core/mappings.lua` file can be disabled in your `user/init.lua` file in the `mappings` table by setting the mapping key to `false`. For example:

```lua
return {
  mappings = {
    n = {
      ["<leader>w"] = false,
    }
  }
}
```

This is a simple `user/init.lua` file that will just disable the default `<leader>w` binding in normal mode for saving.

For the `jj` binding, this is actually provided by the plugin [better-escape.nvim](https://github.com/max397574/better-escape.nvim) which does some fancy stuff under the food to make bindings for escape more responsive and nicer. It by default provides 2 mappings, `jk` and `jj` for escape. If you just want to disable `jj` then you can configure the `setup` of this plugin like this:

```lua
return {
  plugins = {
    better_escape = {
      mapping = { "jk" },
    }
  }
}
```

or if you don't want `jk` or `jj` as bindings to escape, you can simply disable the plugin all together:

```lua
return {
  plugins = {
    init = {
      ["max397574/better-escape.nvim"] = { disable = true },
    },
  },
}
```

(After disabling plugins, make sure to restart and run `:PackerSync` to have packer refresh and uninstall the plugin.
