### ISSUE TITLE
integrate cmake4vim

### ISSUE THREAD

**Issue by Lishen1** [AstroNvim/AstroNvim#1016]
### Describe the new feature

without include paths form cmake, code highlighting doesn't work correctly. So, i think integrating https://github.com/ilyachur/cmake4vim can make code highlighting and autocompletion much better

**Comment by mehalter** [comment]
This is a much older approach to doing this. AstroNvim relies more on the native LSP and treesitter functionality for far superior auto completion and syntax tree based highlighting. You can do this by installing the `cmake` treesitter parser and language server. `:TSInstall cmake` and `:LspInstall cmake`.

You can also have these things automatically install in your `user/init.lua` file:

```lua
return {
  plugins = {
    ["mason-lspconfig"] = {
      ensure_installed = {
        "cmake",
      },
    },
    treesitter = {
      ensure_installed = {
        "cmake",
      },
    },
  },
}
```

And these things will automatically install when you open AstroNvim.

Examples with both running:

![2022-09-29_17:42:04_screenshot](https://user-images.githubusercontent.com/1591837/193147397-a3e532fc-db9a-4739-ad32-fa231ab5b3cf.png)
