### ISSUE TITLE
Holding 'j' to scroll down is slow

### ISSUE THREAD

**Issue by DeeGeeMan** [AstroNvim/AstroNvim#1017]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v1.9.2

### Neovim version (>= 0.7)

NVIM v0.7.2

### Operating system/version

macOS 12.6

### Describe the bug

Using `j` to scroll down in a terminal application (e.g. `<leader>tl` for lazygit), it doesn't display the highlighted row during the scrolling process.  However, I don't see the same problem with 'k' to scroll up the list.   This is a problem in every teminal application I used within **AstroNvim** so far.

Btw, `j` works as expected in native `nvim`.

### Steps to Reproduce

1. open the default `init.lua` file
2. type `<leader>tl`
3.  tab to the **Commits** section
4.  hold `j` to scroll down to the bottom
5.  hold `k` to scroll up to the top

### Expected behavior

The `j` scrolling should be just as fast as `k`.

### Additional Context

Uploading scrolling-issue2.mov…

**Comment by mehalter** [comment]
This is coming from the smooth scrolling plugin that comes pre-installed in AstroNvim. It is one of the first things I disabled because it seems so silly to me. I am pushing to remove it in `v2`. In the mean time you  can just disabled it in your `user/init.lua` file. Here is a minimal `user/init.lua` file as an example:

```lua
return {
  plugins = {
    init = {
      ["declancm/cinnamon.nvim"] = { disable = true },
    },
  },
}
```

Just make sure to restart and do a `:PackerSync` to have packer remove the plugin.

**Comment by DeeGeeMan** [comment]
applying the changes above didn't resolve the problem.

**Comment by mehalter** [comment]
Sorry about that, I'll take a deeper look soon and see if I can replicate it

**Comment by mehalter** [comment]
Ah @DeeGeeMan this is because of a really bad default binding that AstroNvim has. I would recommend using the following settings on AstroNvim v1.X:

```lua
return {
  mappings = {
    t = {
      ["<esc>"] = false,
      ["jk"] = false,
    },
  },
}
```

These bindings will be removed in AstroNvim v2.0

**Comment by DeeGeeMan** [comment]
Thanks!...adding just `["jk"] = false` worked for me.

**Comment by liocer** [comment]
Yay, I hated that plugin. So glad it's gone from latest release
