### ISSUE TITLE
It treats all code file types as plain text

### ISSUE THREAD

**Issue by chettoy** [AstroNvim/AstroNvim#1023]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v1.10.0

### Neovim version (>= 0.7)

NVIM v0.8.0

### Operating system/version

ArchLinux

### Describe the bug

After running `git pull` in `.config/nvim` and executing `:PackerSync`, I opened a python file and found that code highlighting and LSP no longer worked.
The `:LspInfo` does not seem to show that the file type is detected.
So I tried a fresh install of neovim and AstroNvim using ArchLinux docker and the same thing happened.
I'm not sure if it's a bug or just because I'm not doing it right.

### Steps to Reproduce

1. run a new archlinux docker: `docker run -it --rm archlinux bash`
2. install AstroNvim
```
pacman -Syu && pacman -S neovim git python nodejs npm
git clone https://github.com/AstroNvim/AstroNvim ~/.config/nvim
nvim +PackerSync
```
3. `:TSInstall python` and `:LspInstall pyright` then edit a python file
4.  highlight and LSP not work as the screenshot shows below

### Expected behavior

Installed syntax highlighting and LSP working properly

### Screenshots

![astro_1](https://user-images.githubusercontent.com/42088051/193407369-3aab23e7-d760-45d2-9e53-0b8594f10448.png)

**Comment by mehalter** [comment]
Stable AstroNvim does not currently support Neovim 0.8. Please check out the discussion page for the announcement of AstroNvim v2.0 nightly that is currently opt in which provides Neovim 0.8 support.
