### ISSUE TITLE
Potential AstroNvim v2.0 Issues

### ISSUE THREAD

**Issue by krishnakumarg1984** [AstroNvim/AstroNvim#1024]
### Checklist

- [ ] Status bar (heirline) automatically moves to top when entering the help menu. To reproduce, remove `~/.local/share/nvim` and `~/.local/state/nvim` and do a fresh installation of AstroNvim nightly. At the initial greeter buffer, do `:h 'option'` for example, and the help buffer opens with the status bar on the top (without the user explicitly requesting such a changed placement vs the usual bottom placement).
  - I can replicate this. It's only in a specific case with Alpha because we disable the statusline on the dashboard. I will need to ponder this and see if there's a nice way to fix it or if it's not super necessary in this instance. This could also be very easily fixed by just dropping the dashboard from the default configuration which I would be partial to.
  - For now I'm just going to leave this as is while I focus on other things. This is a very minor edge case and does not provide any issues in the functionality. If someone comes up with a better solution before I do then I would happily accept a PR. For now there are bigger fish to fry
- [ ] ~~Help buffers' rendering is messed up. There are run-on characters and the spacing between concealed words are non-existent. There are other rendering issues too. None of these problems occur in barebones nvim 0.8.~~
  - Not an issue with AstroNvim out of the box or anything. This is an issue with the treesitter parser.
- [ ] ~~Treesitter gets loaded on the help buffer even when its install is explicitly prevented in the configuration (and the highlight module for help is additionally turned off). The status bar and checkhealth indicates that the help parser is loaded. Furthermore, the set of available `:TS[Buf]Disable[All] [module]` has no effect.~~
  - This is a misunderstanding of how to disable treesitter things. Please refer to the docs more and better understand how to configure it. Also not a bug with AstroNvim
- [X] There is a typo in  `Toggle color highligts    Space + uC` mentioned in the migration guide
- [ ] ~~The mapping for :Gitsigns next_hunk also does not work, although the command itself works~~
  - Cannot replicate. both `<leader>gj` and `<leader>gk` work as intended.
- [X] The toggle diagnostics menu could additionally have a close semantic sibling with a keymap `<leader>uD` where the `D` emphasises that all diagnostics including those in the status line shall be disabled.  Currently, `<leader>ud` disables diagnostics in the buffer, but leaves the signs in the status line untouched.
  - After playing with it. I'm just making `<leader>ud` control the statusline elements as well rather than having two bindings. I'm not sure if I'm going to stick with this. But I don't like the multiple bindings approach for this.
- [x] When cancelling out with `<Esc>` or `<C-]`, the indent prompt invoked by the toggle indent menu changes the indent value to 8 (maybe neovim default value?). The expected behaviour is that upon cancelling out of the menu, it should preserve the existing value (i.e. the value prior to entering the menu).
- [ ] ~~The `<leader>un` mapping for changing line numbering cycles through a bunch of permutations/combinations for the line number and relativenumber options. Instead, this should adhere to the same style i.e. prompt the user for values as the indent setting.  It is confusing when one menu item in the UI menu behaves differently than the very next one.~~
  - I disagree with this one. I am going to leave this the same.

**Comment by mehalter** [comment]
Thanks for the list of possible bugs! I was able to replicate and verify a couple of them and fixed those ones. Others I have verified as either not an actual problem or just intended behavior. It would be a good idea if you are having some of these other bugs to see what's happening in your user configuration to see what could be causing them. Anything that is striked out was unable to be replicated in a fresh installation of AstroNvim or stemmed from a misunderstanding of Treesitter options and parsers.
