### ISSUE TITLE
i can't see the bufferline

### ISSUE THREAD

**Issue by CMOISDEAD** [AstroNvim/AstroNvim#1025]
### Question

I'm migrating my configuration to AstroNvim nightly, but I can't get the bufferline to appear
![1664638814 screensht](https://user-images.githubusercontent.com/51010598/193417185-b5e3fd45-7982-48eb-b0c1-1f886525b159.png)

Thanks :)

**Comment by mehalter** [comment]
Can you please share your user configuration

**Comment by CMOISDEAD** [comment]
> Can you please share your user configuration

I clone your repository 
https://code.mehalter.com/projects/68/files
I have not touched anything related to the bufferline

**Comment by mehalter** [comment]
How recently have you updated that repo? Things have changed there.

**Comment by CMOISDEAD** [comment]
about 3 hours ago, i clone your repository and change astronvim to nigthly

**Comment by mehalter** [comment]
I'm not sure, I can't replicate this with my config 😂 I would recommend starting from a fresh install and building your user configuration f
The way you want it to be

**Comment by CMOISDEAD** [comment]
It's not that bad 😄 the bufs section in neotree works great i think i could use it, thanks ❤️

**Comment by CMOISDEAD** [comment]
apparently the error only happens if you have alpha.nvim enabled, it can be fixed by editing the file `lua/core/autocmds.lua` in the line 39 or more recommended by changing the value of vim.opt.showtabline by 2 😃

**Comment by opchav** [comment]
Thanks @CMOISDEAD! If anyone is wondering where to do that... it's in your user config `nvim/lua/user/init.lua`

```lua
  -- set vim options here (vim.<first_key>.<second_key> =  value)
  options = {
    opt = {
      relativenumber = true, -- sets vim.opt.relativenumber
      showtabline = 2,
    },
    ...
  },
...
```
