### ISSUE TITLE
accessing client.resolved capabilities is deprecated error

### ISSUE THREAD

**Issue by Perlten** [AstroNvim/AstroNvim#1026]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v1.10.0

### Neovim version (>= 0.7)

NVIM 8.0

### Operating system/version

Linux arch

### Describe the bug

Since I updated to neovim 8.0, I get the message every time I open neovim 

accessing client.resolved capabilities is deprecated

Looking around, I found a potential solution
https://github.com/neovim/neovim/issues/14090#issuecomment-1113956767

resolved_capabilities is only to be found in 5 places in the codebase (two of them as comments)
Two of them inside lua/user_example/init.lua
and the rest inside  lua/configs/lsp/handlers.lua

changing resolved_capabilities  to server_capabilities removes the messages however have not tested it thoroughly enough to say that it does not break other aspects of the system

### Steps to Reproduce

Open any file in neovim

Wait 1-2 seconds

The message pops up as a notification

### Expected behavior

Not to show the before-mentioned message

**Comment by mehalter** [comment]
AstroNvim <2.0 does not support Neovim 0.8. please see the announcement in the discussions.

**Comment by SuperNici** [comment]
Would it make sense to provide one of those floating notifications if astro nvim detects that the neovim version is unsupported?

**Comment by SuperNici** [comment]
Ah thats already the case. I downgraded to 7.2 and it showed me this popup. 

![2022-10-13T11:01:59,826170902+02:00](https://user-images.githubusercontent.com/51826257/195553063-f3f0d379-e8e1-4d14-b837-6f2b4d8b6900.png)

**Comment by mehalter** [comment]
@SuperNici yeah we have added this recently. You need to use Neovim v0.8 with the latest release of AstroNvim :)
