### ISSUE TITLE
No colour scheme and syntax highlighting in any language

### ISSUE THREAD

**Issue by BL4CK-R34P3R** [AstroNvim/AstroNvim#1028]
After upgrading neovim to latest neovim 8 no more color scheme or syntax highlighting

**Comment by azinsharaf** [comment]
same here.

**Comment by purung** [comment]
Same issue.  

```
set: filetype=rust
```

Manually setting the language worked. Patching the underlying issue would certainly be nice though.

**Comment by samirqlvdev** [comment]
same problem on new installed macOS Monterey, nvim brew version

**Comment by Daegalus** [comment]
I was just trying to get a fresh neovim setup to give it a go as an ide for weaker machines I have, and spent the last hour thinking i broke something. Hopefully this is an easy to fix one.

**Comment by BL4CK-R34P3R** [comment]
> Same issue.  
> 
> ```
> :set filetype=rust
> ```
> 
> Manually setting the language worked. Patching the underlying issue would certainly be nice though.

> Thanks  for temp fix

**Comment by BL4CK-R34P3R** [comment]
> I was just trying to get a fresh neovim setup to give it a go as an ide for weaker machines I have, and spent the last hour thinking i broke something. Hopefully this is an easy to fix one.

> Recheck the changes you made

**Comment by chettoy** [comment]
Check this out #1023

**Comment by benvds** [comment]
Remove the filetype options to fix this. See: https://github.com/AstroNvim/AstroNvim/pull/1030

**Comment by BL4CK-R34P3R** [comment]
Thanks
