### ISSUE TITLE
attempt to index field 'DiagnosticError' (a nil value)

### ISSUE THREAD

**Issue by YangtseSu** [AstroNvim/AstroNvim#1029]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v1.10.0-63-g7cd7fc4

### Neovim version (>= 0.7)

NVIM v0.8.0

### Operating system/version

Archlinux/rolling

### Describe the bug

Use the default user_eaxmple/init.lua
```
Error detected while processing VimEnter Autocommands for "*":
Error executing lua callback: /home/yangtse/.config/nvim/lua/user/init.lua:42: attempt to index field 'DiagnosticError' (a nil value)
stack traceback:
        /home/yangtse/.config/nvim/lua/user/init.lua:42: in function 'overrides'
        /home/yangtse/.config/nvim/lua/core/utils/init.lua:76: in function 'func_or_extend'
        /home/yangtse/.config/nvim/lua/core/utils/init.lua:279: in function 'user_plugin_opts'
        /home/yangtse/.config/nvim/lua/core/autocmds.lua:111: in function </home/yangtse/.config/nvim/lua/core/autocmds.lua:109>
```

### Steps to Reproduce

1. install nvim astronvim
2. cp user_eaxmple/init.lua to user
3. change branch to nightly
4. PackerSync

### Expected behavior

......

**Comment by mehalter** [comment]
Fixed in latest push to `nightly`
