### ISSUE TITLE
When autocompleting how do I show the name of the reason why it's being autocompleted?

### ISSUE THREAD

**Issue by Kreijstal** [AstroNvim/AstroNvim#1031]
### Question

in astrovim I get
![image](https://user-images.githubusercontent.com/2415206/193447375-2dc32d70-1513-49e5-94ce-beb5c51d3c8e.png)

in this native nvim using plug with no other configuration I get things such as `[LSP]` and `Operator` having more information about the autocomplete
![image](https://user-images.githubusercontent.com/2415206/193448006-ef3a9b2d-d7f2-458d-9e2b-c1f47d928cb5.png)

my question is how can I make this show up on astrovim as well?

Thank you.

**Comment by mehalter** [comment]
By default AstroNvim provides menu appearance of `cmp` with `lspkind` and their built in format to get the nice symbols in the completion. Check out this wiki entry in `nvim-cmp` for how to modify the `format` function in the `cmp` setup to make it look however you want to: https://github.com/hrsh7th/nvim-cmp/wiki/Menu-Appearance

You can override the format function in your `user/init.lua` function by overriding `cmp`. Something like this:

```lua
return {
  plugins = {
    cmp = {
      formatting = {
        format = function(entry, vim_item)
          -- custom format function would go here
          --
          -- this is the default:
          -- astronvim.lspkind helps us get the config table from the plugin setup rather than re-defining it here
          return require("lspkind").cmp_format(astronvim.lspkind)(entry, vim_item)
        end,
      },
    },
  },
}
```
