### ISSUE TITLE
git_diff component has extra spacing

### ISSUE THREAD

**Issue by tomKPZ** [AstroNvim/AstroNvim#1033]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v1.10.0-65-gdcede98

### Neovim version (>= 0.7)

NVIM v0.8.0

### Operating system/version

Arch Linux

### Describe the bug

When there's no git diff, the statusline component has unnecessary spacing.

### Steps to Reproduce

Use this config to move the breadcrumbs from the winbar to the statusline:

```
local config = {
  plugins = {
    heirline = function(config)
      -- Add breadcrumbs to statusline.
      table.insert(config[1], 6, astronvim.status.component.breadcrumbs())
      -- Disable the winbar.
      config[2] = nil
      return config
    end,
  },
}

return config
```

### Expected behavior

The spacing between "nightly" and "lua" is the same as the spacing between "lua" and "condition".

### Screenshots

<img width="312" alt="Screenshot 2022-10-02 152734" src="https://user-images.githubusercontent.com/9124077/193479107-c70d2d95-510a-4d68-a713-cc1c35fa496b.png">

**Comment by mehalter** [comment]
Thanks for this report! I have pushed a fix :)

**Comment by mehalter** [comment]
![2022-10-03_18:30:11_screenshot](https://user-images.githubusercontent.com/1591837/193697408-12197818-791e-47a1-88ba-273e2864a88c.png)
