### ISSUE TITLE
Cannot remove keymapping for { and }

### ISSUE THREAD

**Issue by dohsimpson** [AstroNvim/AstroNvim#1041]
### Question

I tried to remove the default mapping for { and }, which are mapped to Aerial. But with no luck.

### Expected behaviours

`{` and `}` in normal mode are no longer mapped to Aerial keys. `:nmap {` should show no mapping

### Actual behaviours

`:nmap {` shows `n  {           *@<Cmd>AerialPrev<CR>`

### User Configuration

```
local config = {
  mappings = {
    n = {
      ["{"] = false,
      ["}"] = false,
    }
  }
}

return config
```

**Comment by matiasg** [comment]
I have the same problem, trying to remove `<C-F>` and `<C-B>`
A minimal `user/init.lua` file:
```
local config = {
  mappings = {
    n = {
      ["<C-F>"] = false,
      ["<C-B>"] = false,
    },
  },
}

return config
```
But still `<C-F>` is mapped to `<Cmd>lua Scroll('<C-F>', 1, 1)<CR>`

**Comment by mehalter** [comment]
@dohsimpson the bindings here are being set by Aerial, you can disable them by overriding the aerial setup. Here is an example, minimal `user/init.lua` file:

```lua
return {
  plugins = {
    aerial = {
      default_bindings = false
    }
  }
}
```

**Comment by dohsimpson** [comment]
Hi @mehalter , thanks for the quick reply. Unfortunately I tried the setting you posted but it was not working still, the keys are still being binded. Also, I could be wrong on this, but I think the keybindings for `{` and `}` are actually set in `lua/configs/aerial.lua` file, instead of by aerial.

**Comment by dohsimpson** [comment]
Figured out how to do this. AstroNVim's Aerial keymaps are defined in `lua/configs/aerial.lua` in the on_attach function, which can be overriden in `user/init.lua` like below:

```
return {
  plugins = {
    ["aerial"] = function(config)
      config.on_attach = function(bufnr) end
    end,
  }
}
```

This will disable `{` and `}` and `[[` and `]]`

**Comment by dohsimpson** [comment]
The reason they cannot be overriden with a global keymap disable is because they are set as buffer keymap on buffer attach, therefore every time a buffer is attached, those keymaps are mapped to that buffer
