### ISSUE TITLE
Quick Qsn ( I am big noob please don't laugh)

### ISSUE THREAD

**Issue by nickholden-ui** [AstroNvim/AstroNvim#1042]
### Question

How do I add the markdown-preview plugin?

I've updated the plugin.lua file and run packer-install but the ":MarkdownPreview" command doesn't work

What am I missing?

Cheers

**Comment by natematykiewicz** [comment]
In my ` ~/.config/nvim/lua/user/init.lua` I have:

```lua
  plugins = {
    init = {
      ["iamcco/markdown-preview.nvim"] = {
        run = function() vim.fn["mkdp#util#install"]() end,
      },
    }
  }
```

**Comment by mehalter** [comment]
Thanks for a nice reply @natematykiewicz !
