### ISSUE TITLE
Elixir maps (%{}) in pattern match error in heirline config.

### ISSUE THREAD

**Issue by cfbender** [AstroNvim/AstroNvim#1043]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v1.10.0-71-gde74668 (nightly)

### Neovim version (>= 0.7)

NVIM 0.8.0

### Operating system/version

macOS 12.6

### Describe the bug

When looking at at file that contains some elixir map in a match for a  function declaration:

```elixir
def test(%{"test" => test}) do
	test
end
````

I get an error:
```
E15: Invalid expression: "test" => test
```

This also happens with something like
```elixir
def test(%{test: test}) do
	test
end
````

where I get: 
```
E121: Undefined variable: test
```

and when I hammer it enough it comes out as this:
![image](https://user-images.githubusercontent.com/50554676/194111949-60516c01-a392-43c1-a593-e005e36ba0fb.png)

(excuse the screenshot, it's all I could grab of the issue)

It seems there is something that is not properly escaping string to heirline. I have narrowed it down to the `breadcrumbs` provider, and have a fully working config by overriding heirline in the meantime as follows (just removing the breadcrumbs provider):
```lua
  plugins = {
    heirline = function(config)
      config[2] = {
        fallthrough = false,
        {
          condition = function()
            return astronvim.status.condition.buffer_matches {
              buftype = { "terminal", "prompt", "nofile", "help", "quickfix" },
              filetype = { "NvimTree", "neo-tree", "dashboard", "Outline", "aerial" },
            }
          end,
          init = function() vim.opt_local.winbar = nil end,
        },
        {
          astronvim.status.component.file_info {
            file_icon = { highlight = false },
            hl = { fg = "winbarnc_fg", bg = "winbarnc_bg" },
            surround = false,
          },
        },
      return config
    end,
  },
```

### Steps to Reproduce

1. Install elixir-ls
2. Write the function definition into some test.ex:
```elixir
def test(%{"test" => test}) do
	test
end
````
3. Move the cursor over the first line of the function declaration

### Expected behavior

The editor does not error on evaluating the string

### Additional Context

See https://github.com/rebelot/heirline.nvim/issues/68 for discussion on problem with heirline config

**Comment by mehalter** [comment]
@cfbender thanks so much for this report and the discussion on the Heirline issues! I have just pushed a change to escape the text in the breadcrumbs, could you give it a try to see if it resolves the issue? :D

**Comment by cfbender** [comment]
Looks like that did it! 
![image](https://user-images.githubusercontent.com/50554676/194145248-5a5219ef-6e2d-468e-b52e-c5ad93260395.png)

Thanks so much! Love the project you've put together here - thanks for the speedy response!

Closed by https://github.com/AstroNvim/AstroNvim/commit/ac3fcc2ea27b9a832e523c82e1655ae6a7232f43
