### ISSUE TITLE
Lua errors when starting NeoVim

### ISSUE THREAD

**Issue by jiro-too** [AstroNvim/AstroNvim#1044]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

Does not work due to lua errors

### Neovim version (>= 0.7)

0.8.0-r1

### Operating system/version

Gentoo GNU/Linux

### Describe the bug

Greeted with multiple Lua errors starting NeoVim. (Screenshots attached)

This issue is occurring after updating the system so I suspect it has something to do with the nvim package itself.

### Steps to Reproduce

1. Open a terminal emulator.
2. Type `nvim`

### Expected behavior

NeoVim is supposed to start and work normally.

### Screenshots

![image](https://user-images.githubusercontent.com/66298183/194210455-867054d4-5358-43e9-bef0-5c938e8a4574.png)

Trying to run `:PackerSync`
![image](https://user-images.githubusercontent.com/66298183/194210520-f714e555-60d2-44b9-bd4b-0ba29a1c6f07.png)

**Comment by dcbuild3r** [comment]
Experiencing the same issues

**Comment by gvlatko** [comment]
Current stable version (v1.10) is for Neovim 0.7.

**Comment by kormosi** [comment]
To all the beautiful people maintaining great project:

I, too, experience this issue. 

Currently checked-out on `main:`

`392b92d\ [6 days ago] (HEAD -> main, tag: ls, origin/main, origin/HEAD)\ chore(snapshot): update packer_snapshot\ [Micah Halter]#`

**Comment by PaulKushch** [comment]
I started getting `Error in packer_compiled: ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:139: Vim(packadd):bufdelete.nvim is only availabl
e for Neovim versions 0.8 and above
Please check your config for correctness` when try pressing `Leader + c` after updated Astronvim. 

Use nvim v 0.7.2

**Comment by jiro-too** [comment]
Update: AstroNvim loads without errors now, however syntax highlighting and LSP (with autocompletion and everything seems to not work)

**Comment by mehalter** [comment]
@jiro-too AstroNvim v2 was released yesterday. Could you try updating and see if that resolves. It sounds like #1028 now

**Comment by kormosi** [comment]
@mehalter I've updated to AstroNvim v2 as per the installation instructions, yet I'm getting this error:
![image](https://user-images.githubusercontent.com/53222723/194825595-549a571b-b432-4f27-91fc-72476c4327b4.png)


Then, after pressing enter for a couple of times, I get:
![image](https://user-images.githubusercontent.com/53222723/194825290-119a3f63-db9f-4495-b89d-775dfacbc3ce.png)


my nvim build:
```
$ nvim --version                                                                                                                                                                 -- INSERT --
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by mehalter** [comment]
@kormosi have you done a `:PackerSync` successfully after updating? if the errors are getting in the way you can also force this by starting neovim with `nvim +PackerSync`

**Comment by kormosi** [comment]
`nvim +PackerSync` first yields:
![image](https://user-images.githubusercontent.com/53222723/194882951-9b61a7e8-316e-4e5a-92ae-f225a439e69a.png)

Then, upon pressing enter, the same error, as above:
![image](https://user-images.githubusercontent.com/53222723/194883097-7e69aebe-6a44-478a-a5d2-a9b2dd0b0a66.png)

Running `:PackerSync` is also impossible due to errors.

I'm currently on this commit:
`0882a17\ [11 hours ago] (HEAD -> main, tag: v2.0.2, origin/main, origin/HEAD)\ fix(mappings): revert c-n toggleterm commit as it broke critical default functionality\ [Micah Halter]#`

**Comment by mehalter** [comment]
Could you try clearing your `~/.local/share/nvim` and `~/.cache/nvim` folder and then seeing if the error persists @kormosi ? You can backup these folders just in case you want them back with

```sh
cd ~/.local/share
mv nvim nvim.bak
cd ~/.cache
mv nvim nvim.bak
```

Then try running `nvim +PackerSync` @kormosi

**Comment by kormosi** [comment]
@mehalter thank you, the problem has been resolved by removing `~/.local/share/nvim` and `~/.cache/nvim` directories.

**Comment by neobats** [comment]
I had the same issue and clearing my `~/.local/share/nvim` and `~/.cache/nvim` worked too!

**Comment by mehalter** [comment]
I believe this issue has been resolved from the latest comments. If anyone is still running into this issue and clearing the cache and data folders does not help please let me know. Sometimes between versions especially because there are such breaking changes the caches and data folders can get borked.
