### ISSUE TITLE
can not get highlight

### ISSUE THREAD

**Issue by TOLIE-OFFICIAL** [AstroNvim/AstroNvim#1047]
### Question

AstroNvim version: latest
NVIM version：NVIM v0.8.0
System：archcraft 5.19.13-arch1-1

I'm new to AstroNvim;

just runed the commend in the README file;
and : TSInstalled javascript

I  can't get my code highlighted. and I get a warning "highlight group "Normal" has no background highlight…"; i searched that in stackoverflow,but get nothing; did i miss something?

![error shot](https://user-images.githubusercontent.com/90889293/194567807-8d9e000e-2424-4648-8c77-79fdb90d1085.png)

### User Configuration

change nothing

**Comment by mehalter** [comment]
Duplicate #1028
