### ISSUE TITLE
Statusline configuration

### ISSUE THREAD

**Issue by alex289** [AstroNvim/AstroNvim#1049]
### Question

Hey, I already had this question in #867: How to add the word of the current mode in the status line. With the release of AstroNvim 2.0.0 in which it migrates from Feline to Heirline it doesn't work. How is it done with this Plugin?

Thanks a lot :D

**Comment by mehalter** [comment]
Check out the documentation for migration as well as the new statusline: https://astronvim.github.io/Recipes/status#default-statusline-with-mode-text

**Comment by alex289** [comment]
Oh I didn't see this. Thanks a lot. Love the new update
