### ISSUE TITLE
Unable to configure gruvbox.nvim custom theme

### ISSUE THREAD

**Issue by maxbrunet** [AstroNvim/AstroNvim#1050]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v1.10.0 / v2.0.0

### Neovim version (>= 0.7)

0.7.0 / 0.8.0

### Operating system/version

NixOS 22.05

### Describe the bug

I am basically facing ellisonleao/gruvbox.nvim#119 and trying to invert the colors now that the `inverse` setting is available

I follow the documented recipe, but it does not work for the [Gruvbox colorscheme](https://github.com/ellisonleao/gruvbox.nvim#configuration):

https://astronvim.github.io/Recipes/colorscheme

I have not been able to find a workaround. Happy to open an issue upstream if the plugin is incorrect or does not follow some pattern.

Tried with AstroNvim 1.10.0 / Neovim 0.7 and AstroNvim 2.0.0 / Neovim 0.8.

Thank you in advance for the help!

### Steps to Reproduce

1. Use the following config as `user/init.lua`:

```lua
return {
  colorscheme = "gruvbox",

  plugins = {
    init = {
      {
        "ellisonleao/gruvbox.nvim",
        as = "gruvbox",
        config = function()
          require("gruvbox").setup {
            inverse = false
          }
        end,
      },
    },
  },
}
```

2. Ensure you have the plugin installed with `nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'`
3. Start `nvim`, the statusline will be using the inverted theme (light) instead of the regular one (dark)

### Expected behavior

Gruvbox config is applied -> the status line uses the dark theme

**Comment by mehalter** [comment]
@maxbrunet this is a limitation of `gruvbox.nvim` AstroNvim sets the `colorscheme` near the beginning of setting things up. This is relatively standard and works with *most* themes. It looks like `gruvbox.nvim` has a notice on their README:

```
-- setup must be called before loading the colorscheme
```

So when you are doing your setup call, you just need to make sure to call the colorscheme setting yourself manually rather than using the `colorscheme` setting in our config:

```lua
return {
  plugins = {
    init = {
      {
        "ellisonleao/gruvbox.nvim",
        as = "gruvbox",
        config = function()
          require("gruvbox").setup {
            inverse = false
          }
          vim.cmd.colorscheme("gruvbox")
        end,
      },
    },
  },
}
```

**Comment by mehalter** [comment]
Actually, I just tested this and it makes no difference. From what I can tell I can't get the settings for gruvbox to do anything (with or without AstroNvim.

**Comment by maxbrunet** [comment]
> It looks like `gruvbox.nvim` has a notice on their README

Yes, I did try it too without success as I was not sure if AstroNvim do it for me or not

> Actually, I just tested this and it makes no difference. From what I can tell I can't get the settings for gruvbox to do anything (with or without AstroNvim.

Thank you so much for taking the time to look into this! I will reach out upstream
