### ISSUE TITLE
astrov2.0 how to escape insert mode in toggleterm

### ISSUE THREAD

**Issue by ACupofAir** [AstroNvim/AstroNvim#1053]
### Question

* the question is the title
* astronvim v2.0
* neovim 8.0

**Comment by mehalter** [comment]
You can use the default way of doing this which is `<ctrl-\><ctrl-n>` or map it to something else in your personal config

**Comment by ACupofAir** [comment]
> You can use the default way of doing this which is `<ctrl-\><ctrl-n>` or map it to something else in your personal config

THX, but is there a way just type `<ctrl-\> `to hide the terminal. Now when I type `<ctrl-\>`, the powershell will just type `^\` on the terminal.

**Comment by mehalter** [comment]
This binding was changed in v2 because it overrides such important default functionality. Please check the migration guide in the docs. This was changed to F7 for toggling the terminal
