### ISSUE TITLE
Multiple toggleterm sessions doesn't work with v2.0

### ISSUE THREAD

**Issue by vtvz** [AstroNvim/AstroNvim#1055]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.0.0

### Neovim version (>= 0.7)

NVIM v0.8.0

### Operating system/version

Manjaro Linux 22.0.0

### Describe the bug

In the previous version, I could use `n<C-\>` keystroke where `n` is a number to open multiple terminal sessions. Now this functionality broke. `n<C-'>` open the same session

### Steps to Reproduce

1. Open neovim with astronvim v2
2. Press `Ctrl+'`
3. Write something
4. Press `2` `Ctrl+'`
5. See your writings

### Expected behavior

Have a different terminal session

### Additional Context

This user config does the trick:
```lua
{
  plugins = {
    toggleterm = {
      open_mapping = [[<c-'>]],
    }
  }
}
```

but feels like it's the unintended behaviour

**Comment by mehalter** [comment]
Thanks for this report! I will investigate because this definitely is a necessity

**Comment by Suntechnick** [comment]
Not sure if that's related to this issue, but it seems that new terminal mapping `<c-'>` is not working on Windows. And if I remap it to the older `<c-\\>`  keymap I'm getting the same problem as in this issue.

**Comment by mehalter** [comment]
Fixed in new release. It turns out most terminal emulators do not support ctrl key codes for non alphabetic characters. So I have added `<ctrl-n>` as a binding to be used which is unbound in normal mode

**Comment by mehalter** [comment]
I'm pushing updates to the documentation now

**Comment by YangtseSu** [comment]
Reopen.

**Comment by mehalter** [comment]
Just to clarify this does work for very modern terminal emulators with good terminal keymapping detection. Neovim supports these `<c-'>` bindings but not all terminal emulators are built to capture them to pass them to terminal applications.

Reopening until we can find a more compatible binding that doesn't interfere with other stuff

**Comment by YangtseSu** [comment]
gnome terminal ❌
alacritty ❌
wezterm ✔️
foot ✔️
kitty ✔️

**Comment by mehalter** [comment]
Fixed in v2.1.0

**Comment by earlyaugust2** [comment]
Hi @mehalter, I believe this should be reopened. Running v2.1.1 `F7` works for toggling "one" session but attempting to toggle multiple sessions doesn't work, at least for me (using kitty). For example, you should be able to press `F7` to toggle a terminal session, leave/close it, and then press `2` `F7` to toggle a completely different instance, and so on. However, `2` `F7` opens the original one. As does `3` `F7` and so on. Thank you for all your hard work! I appreciate it!

**Comment by mehalter** [comment]
I cannot replicate this @earlyaugust2 I am also using kitty and the code seems to work

https://asciinema.org/a/7Zag4hfa9I8dDiRbWh0gCBgLY

**Comment by mehalter** [comment]
@earlyaugust2 forgot to @ you just in case you don't get notified

**Comment by archite** [comment]
This restores it for me with iTerm:

```lua
diff --git a/lua/core/mappings.lua b/lua/core/mappings.lua
index 2c83a7b..0600e39 100644
--- a/lua/core/mappings.lua
+++ b/lua/core/mappings.lua
@@ -185,7 +185,7 @@ if is_available "toggleterm.nvim" then
   maps.n["<leader>tf"] = { "<cmd>ToggleTerm direction=float<cr>", desc = "ToggleTerm float" }
   maps.n["<leader>th"] = { "<cmd>ToggleTerm size=10 direction=horizontal<cr>", desc = "ToggleTerm horizontal split" }
   maps.n["<leader>tv"] = { "<cmd>ToggleTerm size=80 direction=vertical<cr>", desc = "ToggleTerm vertical split" }
-  maps.n["<F7>"] = { "<cmd>ToggleTerm<cr>", desc = "Toggle terminal" }
+  maps.n["<F7>"] = { '<cmd>execute v:count . "ToggleTerm"<cr>', desc = "Toggle terminal" }
   maps.t["<F7>"] = maps.n["<F7>"]
   maps.n["<C-'>"] = maps.n["<F7>"]
   maps.t["<C-'>"] = maps.n["<F7>"]
```

Of course, that's not the biggest issue for me as the change in muscle memory.

**Comment by earlyaugust2** [comment]
> @earlyaugust2 forgot to @ you just in case you don't get notified

It magically seems to be working for me now. Thanks for the reply

**Comment by vtvz** [comment]
@mehalter it broke again :man_shrugging:

**Comment by mehalter** [comment]
@vtvz the mapping we use for this is `<F7>` out of the box due to terminal compatibility. Not all terminals support mapping `<C-'>` so it is not up for consideration for a default for this operation and is up to the user to set it to get the multiple terminal session support
