### ISSUE TITLE
Prettierd not connecting to custom config.

### ISSUE THREAD

**Issue by fdsa789** [AstroNvim/AstroNvim#1057]
### Question

Trying to add my custom prettier setting, but seem its not loading configs.
I followed [this example](https://github.com/datamonsterr/astronvim_config/blob/main/plugins/null-ls.lua) posted in [Black Belt Example User Configs](https://astronvim.github.io/Recipes/black_belt) in docs.

My directory are like this and null-ls configs are under `nvim/user/plugins/null-ls.lua` and path to `.prettierrc.json` is correct. AstorNvim version is 1.10.0.

 Thanks!

```md
nvim
├── colors
└── lua
    ├── configs
    │   └── lsp
    │       └── server-settings
    ├── core
    │   └── utils
    ├── default_theme
    │   └── plugins
    └── user
        └── plugins
```

### User Configuration

`nvim/user/plugins/null-ls.lua`

```lua
return function(config)
  -- https://github.com/jose-elias-alvarez/null-ls.nvim
  local null_ls = require "null-ls"
  local formatting = null_ls.builtins.formatting
  config.sources = {
    formatting.stylua,
    formatting.black,
    formatting.prettierd.with {
      env = {
        PRETTIERD_DEFAULT_CONFIG = vim.fn.expand "~/.config/.prettierrc.json",
      },
    },
    formatting.shfmt,
  }
  config.on_attach = function(client)
    if client.server_capabilities.documentFormattingProvider then
      vim.api.nvim_create_augroup("format_on_save", { clear = true })
      vim.api.nvim_create_autocmd("BufWritePre", {
        desc = "Auto format before save",
        group = "format_on_save",
        pattern = "<buffer>",
        callback = function()
          vim.lsp.buf.formatting_sync { async = true }
        end,
      })
    end
  end
  return config
end
```

`nvim/user/init.lua`

```lua
-- All other entries override the require("<key>").setup({...}) call for default plugins
["null-ls"] = function(config) -- overrides `require("null-ls").setup(config)`
  -- config variable is the default configuration table for the setup functino call
  -- local null_ls = require "null-ls"

  -- Check supported formatters and linters
  -- https://github.com/jose-elias-alvarez/null-ls.nvim/tree/main/lua/null-ls/builtins/formatting
  -- https://github.com/jose-elias-alvarez/null-ls.nvim/tree/main/lua/null-ls/builtins/diagnostics
  config.sources = {
    -- Set a formatter
    -- null_ls.builtins.formatting.stylua,
    -- null_ls.builtins.formatting.prettier,
  }
  -- set up null-ls's on_attach function
  -- NOTE: You can uncomment this on attach function to enable format on save
  -- config.on_attach = function(client)
  --   if client.resolved_capabilities.document_formatting then
  --     vim.api.nvim_create_autocmd("BufWritePre", {
  --       desc = "Auto format before save",
  --       pattern = "<buffer>",
  --       callback = vim.lsp.buf.formatting_sync,
  --     })
  --   end
  -- end
  return config -- return final config table to use in require("null-ls").setup(config)
end,
```

**Comment by mehalter** [comment]
Hm I'm not sure what's wrong with this. I also use the same notation and don't have any problems with it. Sorry I can't provide any guidance :( I would recommend maybe joining the Discord and asking questions there to see if other community members have run into this

**Comment by gigo6000** [comment]
where should the `.prettierrc` file be located? I usually have one per project, it was working fine like that with `vim-prettier`, but now is not working with Neovim (Astro Nvim) not sure if I need modify the `null-ls` config

**Comment by gigo6000** [comment]
NVM, actually is loading the config, but it's ignore all the options for the import order plugin:
```json
singleQuote: false
importOrder: ['^@core/(.*)$', '^@server/(.*)$', '^@ui/(.*)$', '^[./]']
importOrderSeparation: true
importOrderSortSpecifiers: true
```

Strange because it works find if run the binary in the terminal.

**Comment by mehalter** [comment]
@gigo6000 did you install prettier from Mason? Or setting it up manually with null ls? My guess is you are using mason and that installation doesn't have the plugin available

**Comment by gigo6000** [comment]
@mehalter I installed prettier globally via `yarn`. But that was actually the issue, for some reason it's not seeing the plugin like that, I had to actually install the packages in the project:
```
npm install prettier @trivago/prettier-plugin-sort-imports --save-dev

**Comment by gigo6000** [comment]
@mehalter you were right, it was using the Mason binary. I had no idea Mason was doing that 🙄. I uninstalled the Mason package and also the local packages and it's working fine now with the global binary. Thanks so much for your help!
