### ISSUE TITLE
`PackerSync` fails to install `smart-splits.nvim`

### ISSUE THREAD

**Issue by vijaynandwani** [AstroNvim/AstroNvim#1058]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

Version: v2.0.0

### Neovim version (>= 0.7)

NVIM v0.8.0

### Operating system/version

macOS 11.6

### Describe the bug

`:PackerSync` is unable to install the `smart-splits.nvim` plugin. It shows the following error:

```
✗ Failed to update mrjones2014/smart-splits.nvim  
  Errors: 
  remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
  fatal: invalid reference: 57dc849 
  remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
  fatal: invalid reference: 57dc849
  621814e
```

### Steps to Reproduce

1. Setup latest AstroNvim v2.0.0 with Neovim 0.8
2. Run `:PackerSync`

### Expected behavior

It should install the latest `smart-splits.nvim` version.

**Comment by d1y** [comment]
same question

**Comment by MedoAngel** [comment]
same here

**Comment by talk2drys** [comment]
Same issue, here is screen shot of the error on a fresh installation after running `:PackerSync`. neovim version 0.8
![image](https://user-images.githubusercontent.com/32944188/194755371-c213c36a-6453-46e2-b687-6233ba012cbf.png)
