### ISSUE TITLE
Bdelete command described as "close window"

### ISSUE THREAD

**Issue by chikcne** [AstroNvim/AstroNvim#1059]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.0.0

### Neovim version (>= 0.7)

NVIM v0.8.0-1210-gd367ed9b2

### Operating system/version

Ubuntu 22.04.1

### Describe the bug

`<leader>+c` closes the buffer via `:Bdelete` and with `bufdelete.nvim` the window does not get closed by design, which is fine except the description for the key is "Close window" rather than "Close buffer". Not really sure if this was intentional to make it simplified, but I find it is confusing even for me, a neovim newbie, because in AstroNvim buffers are more like tabs anyway (via `bufferline.nvim`) than windows so at the very least `close tab` sounds better, even if it goes against nvim standards.

While we're on this, `<leader>+q` is labelled as just `quit`, which is vague and is the *actual* close window.

### Steps to Reproduce

1. Hit `<leader>-c`

### Expected behavior

The window should close via calling `:q` or similar.

**Comment by mehalter** [comment]
Fixed in new release
