### ISSUE TITLE
Help with Flutter-Tools and Rust-Tools Configuration with Astrovim

### ISSUE THREAD

**Issue by talk2drys** [AstroNvim/AstroNvim#1073]
### Question

Please I am not sure what I am missing, I have tried following other people configurations for flutter-tools and rust-tools, but when opening rust or flutter these language servers would not attach to the buffer. if I remove them from skip_server and add them to the server, it seems to work but then the `rust-tools` or `flutter-tools` are not in charge and their configuration would not apply.

here is a screenshot with the current config for Dart same thing for Rust
![image](https://user-images.githubusercontent.com/32944188/194971170-495f2aca-6bd7-4f78-8f8b-8e930ed33a98.png)

but if I remove dartls from `skip_server` language server will attach to the buffer
![image](https://user-images.githubusercontent.com/32944188/194971266-b63b5781-6116-4a1f-98b7-df2ad3435d05.png)

now that i have `dartls` removed from `skip_server` it is working. 
![image](https://user-images.githubusercontent.com/32944188/194971488-07494881-2cb0-4413-ac78-c286c841349c.png)

But then the flutter-tools configuration and command are not applied. same issue with rust tools
![image](https://user-images.githubusercontent.com/32944188/194971651-2b01e115-4e1c-4953-8c86-6b72dfcfaf73.png)

Please I just need someone to point me in the right direction

### User Configuration

Here is the link to my full configuration
[Astrovim User Configuration](https://github.com/talk2drys/astrovim_user_config)

**Comment by talk2drys** [comment]
Update: Now I have both language servers attached, I updated the config as indicated below and most importantly I ran `PackerSync` which got both language servers working

skip_server.lua
```
return {
    "dartls",
    "rust_analyzer"
}
```

server.lua
```
return {
    "dartls",               -- Dart
    "rust_analyzer",        -- Rust
  }
```
```

**Comment by talk2drys** [comment]
One more thing, i cant get my on_attach to working, instead of define a new one, I want to use the built in on_attach from astrovim so my keymaps can be the same

for flutter-tools
![image](https://user-images.githubusercontent.com/32944188/194993707-8649acf9-bcb8-40f1-96e2-d995804d9db7.png)

rust
![image](https://user-images.githubusercontent.com/32944188/194993780-88cc9981-1d09-41ec-a054-7f647eb61cc4.png)

when I open the files, I can see `dartls` or `rust_analyzer` attached but my keymaps seem not to be set, here is an example. this is the screenshot after pressing <space>l. I was expecting the see f for formatting etc
![image](https://user-images.githubusercontent.com/32944188/194994048-21b4dbc8-4183-4994-8d7d-fb776b13342d.png)


Also If is enter shift K for hover doc, I see this instead

![image](https://user-images.githubusercontent.com/32944188/194994213-e107945b-b9f9-4159-8963-f928f640f57e.png)

**Comment by mehalter** [comment]
@talk2drys are you following the details described in the documentation?

https://astronvim.github.io/Recipes/advanced_lsp#lsp-specific-plugins

**Comment by talk2drys** [comment]
@mehalter so I made the below changes, relaunched and everything are working fine. Although I see this error at the beginning, not sure what is means analysis and keymaps working fine

![image](https://user-images.githubusercontent.com/32944188/195001237-3cad3daa-2a70-4c0e-b955-e658b7adfa09.png)

working fine even with the notification at the top right

![image](https://user-images.githubusercontent.com/32944188/195003243-9e60daaa-15cf-4830-a22f-fae523c1a828.png)

here is proof they keymap are attaching

![image](https://user-images.githubusercontent.com/32944188/195003401-317e50ce-dab5-486f-9ba7-2025d9fb2703.png)

**Comment by talk2drys** [comment]
@mehalter But what i can't figure out is what is the difference between using this

```lua
config = function()
            -- require("flutter-tools").setup(require "flutter-tools")
            require("flutter-tools").setup {
                lsp = astronvim.lsp.server_settings "dartls",
            }
        end,
```

and this one

```lua
        config = function()
            require("flutter-tools").setup(require "flutter-tools")
        end,
```

then flutter-tools.lua

```lua
return {
  ui = {

    border = "rounded",

    notification_style = "plugin",
  },
  decorations = {
    statusline = {

      app_version = true,

      device = false,
    },
  },
  widget_guides = {
    enabled = true,
  },
  closing_tags = {
    highlight = "ErrorMsg", 
    prefix = ">",
    enabled = true, 
  },
  fvm = false,
  dev_log = {
    enabled = true,
    open_cmd = "tabedit",
  },
  dev_tools = {
    autostart = false,
    auto_open_browser = false,
  },
  outline = {
    open_cmd = "30vnew",
    auto_open = false, 
  },
  lsp = {
    color = { 
      enabled = false, 
      background = false, 
      foreground = false,
      virtual_text = true,
      virtual_text_str = "■",
    },
    on_attach = astronvim.lsp and astronvim.lsp.on_attach or nil,
    settings = {
      showTodos = true,
      completeFunctionCalls = true,
      renameFilesWithClasses = "prompt", -- "always"
      enableSnippets = true,
    },
  },
}
```

**Comment by mehalter** [comment]
There are a few differences here.

1. you need to make sure you are doing `require("user.flutter-tools")` or else you will not be sourcing the correct file I imagine unless you didn't put `flutter-tools.lua` in your `user/` directory.
2. We set more than just the `on_attach` function when you get all of the settings with the `server_settings` call. We set capabilities, etc. and you can use the `lsp.server-settings.dartls` table to set the things like `showTodos` and such.

```lua
return {
  lsp = {
    skip_setup = { "dartls" }, -- skip lsp setup because flutter-tools will do it itself
    ["server-settings"] = {
      dartls = {
        -- any changes you want to make to the LSP setup, for example
        color = {
          enabled = false,
          background = false,
          foreground = false,
          virtual_text = true,
          virtual_text_str = "■",
        },
        settings = {
          showTodos = true,
          completeFunctionCalls = true,
          renameFilesWithClasses = "prompt", -- "always"
          enableSnippets = true,
        },
      },
    },
  },
  plugins = {
    init = {
      {
        "akinsho/flutter-tools.nvim",
        requires = "nvim-lua/plenary.nvim",
        after = "mason-lspconfig.nvim", -- make sure to load after mason-lspconfig
        config = function()
          require("flutter-tools").setup {
            ui = {
              border = "rounded",
              notification_style = "plugin",
            },
            decorations = {
              statusline = {
                app_version = true,
                device = false,
              },
            },
            widget_guides = {
              enabled = true,
            },
            closing_tags = {
              highlight = "ErrorMsg",
              prefix = ">",
              enabled = true,
            },
            fvm = false,
            dev_log = {
              enabled = true,
              open_cmd = "tabedit",
            },
            dev_tools = {
              autostart = false,
              auto_open_browser = false,
            },
            outline = {
              open_cmd = "30vnew",
              auto_open = false,
            },
            lsp = astronvim.lsp.server_settings "dartls", -- get the server settings and built in capabilities/on_attach
          }
        end,
      },
    },
    ["mason-lspconfig"] = {
      ensure_installed = { "dartls" }, -- install dartls
    },
  },
}
```

---

You also could split it up like you said with a `requires` and do something like this:

`user/init.lua`:

```lua
return {
  lsp = {
    skip_setup = { "dartls" }, -- skip lsp setup because flutter-tools will do it itself
    ["server-settings"] = {
      dartls = {
        -- any changes you want to make to the LSP setup, for example
        color = {
          enabled = false,
          background = false,
          foreground = false,
          virtual_text = true,
          virtual_text_str = "■",
        },
        settings = {
          showTodos = true,
          completeFunctionCalls = true,
          renameFilesWithClasses = "prompt", -- "always"
          enableSnippets = true,
        },
      },
    },
  },
  plugins = {
    init = {
      {
        "akinsho/flutter-tools.nvim",
        requires = "nvim-lua/plenary.nvim",
        after = "mason-lspconfig.nvim", -- make sure to load after mason-lspconfig
        config = function() require("flutter-tools").setup(require "user.flutter-tools") end,
      },
    },
    ["mason-lspconfig"] = {
      ensure_installed = { "dartls" }, -- install dartls
    },
  },
}
```

and `user/flutter-tools.lua`:

```lua
return {
  ui = {
    border = "rounded",
    notification_style = "plugin",
  },
  decorations = {
    statusline = {
      app_version = true,
      device = false,
    },
  },
  widget_guides = {
    enabled = true,
  },
  closing_tags = {
    highlight = "ErrorMsg",
    prefix = ">",
    enabled = true,
  },
  fvm = false,
  dev_log = {
    enabled = true,
    open_cmd = "tabedit",
  },
  dev_tools = {
    autostart = false,
    auto_open_browser = false,
  },
  outline = {
    open_cmd = "30vnew",
    auto_open = false,
  },
  lsp = astronvim.lsp.server_settings "dartls", -- get the server settings and built in capabilities/on_attach
}
```

**Comment by talk2drys** [comment]
Thanks, you are right,  following the solution you provided flutter now working 100% fine and rust-tool works language server attaching but seems the keymap is not attaching, this is happening even though I am using the exact config as indicated in the Advance LSP Section for  `rust-tools`. the picture below shows that rust_analyzer is attached and analyzing code but not LSP keymap. please sorry if i am missing something obvious but I am not familiar with Lua and the vim API.

![image](https://user-images.githubusercontent.com/32944188/195504367-21471bac-1bd2-4d95-bc2c-6ea37181ebee.png)

here is a screenshot of my rust-tool config located in plugin/init.lua file

![image](https://user-images.githubusercontent.com/32944188/195504598-1eb4955c-3614-40b9-8316-766437cb5754.png)

**Comment by mehalter** [comment]
@talk2drys do you sync your user configuration to a repository that you can link me? I do see some things that look wrong. For the rust tools stuff, I would njust make sure to triple check that your code matches what is in the docs. Stuff like skipping the setup and everything.

Glad to hear the flutter tools stuff is resolved. Im going to go ahead and close this issue.

**Comment by talk2drys** [comment]
@mehalter thanks for the help, was gonna update you that now rust-tools is also working fine, the only thing I did was to run PackerSync, not sure why I did not work the first time I did it after configuring flutter-tools. 

Thanks again for the assistance

here is my  [astro vim user config](https://github.com/talk2drys/astrovim_user_config) for anyone who needs example configuration

**Comment by LinuCC** [comment]
For anyone having a problem with setting up flutter-tools after upgrading to AstroNvim v3, I was able to make it work again by replacing

```
            lsp = astronvim.lsp.server_settings "dartls",
```

with 

```
            lsp = require('astronvim.utils.lsp').config("dartls"),
```

**Comment by alepop** [comment]
For whom who interested, you now can use `dart` pack from `AstroNvim/astrocommunity` plugin to setup `flutter-tools`.
```lua
return {
  -- Add the community repository of plugin specifications
  "AstroNvim/astrocommunity",
  { import = "astrocommunity.pack.dart" },
  -- Configure flutter-tools
  { "akinsho/flutter-tools.nvim", 
    opts = {
      ...
    }
  }
}
```
