### ISSUE TITLE
How do I change the seperator color (or remove it) for NeoTree and other ui plugins?

### ISSUE THREAD

**Issue by ChrisMGeo** [AstroNvim/AstroNvim#1075]
### Question

I'm wondering if the grey-white line shown in the image below, between the file and neo-tree, can be changed to another color or no color, as I prefer the UI being mostly one color.
![image](https://user-images.githubusercontent.com/44679968/194979630-fb28b774-1dfc-4d4b-8606-c2a1fc2e0c9c.png)

**Comment by mehalter** [comment]
Check out the `WinSeparator` highlight group.
