### ISSUE TITLE
add macro recording indicator to statusline if `cmdheight=0`

### ISSUE THREAD

**Issue by rbutera** [AstroNvim/AstroNvim#1077]
### Is your feature related to a problem?

With cmdheight=0 it is hard to see if you are recording a macro.

### Describe the new feature

If `cmdheight=0` then the statusline should display, for example, `@q` if recording to buffer `q`.

### Additional context

Thanks @mehalter

**Comment by mehalter** [comment]
This has been added to the latest nightly!

**Comment by rbutera** [comment]
sweet!

**Comment by A-Lamia** [comment]
Is this still working on 2.65, or was there a regression ?

**Comment by mehalter** [comment]
@A-Lamia none of the files related to the statusline have changed in the new version and I can confirm it still works as intended

**Comment by A-Lamia** [comment]
@mehalter Interesting, i had to delete all my cache when moving to 2.65 and now it is not showing anymore, i also had to manually compile fzf-native
