### ISSUE TITLE
How do I edit html-lsp options ?

### ISSUE THREAD

**Issue by Tim4c** [AstroNvim/AstroNvim#1079]
### Question

<img width="932" alt="ScreenShot 2022-10-11 at 11 05 21" src="https://user-images.githubusercontent.com/9990855/195049088-9ad186d7-9ac6-4edc-9e7e-709558adb912.png">

I guess I must create a file html.lsp in .config/nvim/user/lsp/server-settings/
But then...?
Thanks for you help.

**Comment by mehalter** [comment]
Basically the table provided in `lsp.server-settings.X` will override the table passed into `lspconfig[X].setup({...})` So settings for language servers go under a `settings` table in this `lspconfig` `setup` call and then the setting names you see above are the table entries. For example, here is a minimal `user/init.lua` file that just sets a couple settings:

```lua
return {
  lsp = {
    ["server-settings"] = {
      html = {
        settings = {
          html = {
            autoClosingTags = true,
            format = {
              templating = false,
            },
          },
        },
      },
    },
  },
}
```

if you want to separate out the files, you can put this in the file `~/.config/nvim/user/lsp/server-settings/html.lua`:

```lua
return {
  settings = {
    html = {
      autoClosingTags = true,
      format = {
        templating = false,
      },
    },
  },
}
```

**Comment by Tim4c** [comment]
Thanks a lot !
