### ISSUE TITLE
Warning: vim.lsp.buf.range_code_action() is deprecated

### ISSUE THREAD

**Issue by smarquez1** [AstroNvim/AstroNvim#1082]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.1.1

### Neovim version (>= 0.7)

0.8

### Operating system/version

macs 12.6

### Describe the bug

https://github.com/AstroNvim/AstroNvim/blob/main/lua/core/utils/lsp.lua#L118

### Steps to Reproduce

1. Open a file with an installed lsp formatter
2. press `<leader>lf` on visual mode
3. see deprecation warning

### Expected behavior

AstronVim should use `vim.lsp.buf.format()` passing a range

### Screenshots

<img width="720" alt="Captura de Pantalla 2022-10-11 a la(s) 16 03 46" src="https://user-images.githubusercontent.com/4602587/195179093-ba979460-0d8b-41a2-b9fd-102eaeeab4f2.png">

### Additional Context

I can't create a PR with a solution since I don't know how to get the currently selected range to pass to the `format` function. If anyone can provide that, It'd make things easier

**Comment by mehalter** [comment]
@smarquez1 resolved in the newest push to `nightly`. Will be released on stable in the coming days. Thanks for reporting!

**Comment by mehalter** [comment]
https://github.com/AstroNvim/AstroNvim/commit/e9d8c69073a968a3d2667043137a2d757c05a6d8

here is the resolution commit

**Comment by mehalter** [comment]
Also to respond to what you said before, basically the `format()` function resolves the mode by itself. If you are currently in visual mode then the range defaults to the current selection. In any other mode the range defaults to the entire file. You can specify a range if you want to manually as another option, but we do not need to do this

**Comment by smarquez1** [comment]
Thanks @mehalter !
