### ISSUE TITLE
Clangd cannot be downloaded

### ISSUE THREAD

**Issue by kbpoyo** [AstroNvim/AstroNvim#1087]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.10

### Neovim version (>= 0.7)

0.8

### Operating system/version

Ubuntu 22.04

### Describe the bug

The plugin clangd download path is incorrect and cannot be downloaded

### Steps to Reproduce

1. Go to nvim
2.  do (: LspInstall clangd)
3. the clangd cannot be downloaded

### Expected behavior

the clangd can be downloaded

### Screenshots

![image](https://user-images.githubusercontent.com/86943232/195310222-172b2399-cf9e-4d44-9088-4de277951290.png)
![image](https://user-images.githubusercontent.com/86943232/195310414-9f7d0c30-19c6-4c2f-9728-c82ed1fa26b1.png)

**Comment by mehalter** [comment]
I just tested the path in the screenshot that you sent from Mason that shows the download location and it is the current path. I typed it in manually and it installed. I also tested installation with Mason and it worked just fine. Also for future reference, this is not a plugin maintained by us. If there i a problem with the download path please open an issue with [mason.nvim](https://github.com/williamboman/mason.nvim)
