### ISSUE TITLE
Enabling "typeCheckingMode" for pyright

### ISSUE THREAD

**Issue by Noxdor** [AstroNvim/AstroNvim#1088]
### Question

I was trying to enable the type checking for pyright and realized, that this feature is manually disabled in AstroNvim in `lua/configs/server-settings/pyright.lua`. I would be first of all curious to why that is / why there are specific changes to the 4 lsps contained in that folder, but my main question is:
How do I enable this from my `user` directory (by not changing it in the `server-settings` folder)?
I tried it like this:
```lua
  ["server-settings"] = {
    python = {
      analysis = {
        typeCheckingMode = "on",
      },
    },
  },
```

but it doesn't work, I must be miss understanding something. If I change this equivalently in the `server-settings` folder, it works though.

### User Configuration

```lua
return {
  luasnip = {
    vscode_snippet_paths = {
      "./lua/user/snippets",
    },
  },
  plugins = {
    init = {
      {
        "IndianBoy42/tree-sitter-just",
        config = function()
          require("tree-sitter-just").setup {}
        end
      },
    },
  },
  updater = {
    branch = "nightly",
  },
  mappings = {
    n = {
      ["<leader>tt"] = { function() astronvim.toggle_term_cmd "btop" end, desc = "ToggleTerm btop" }
    }
  },
  ["server-settings"] = {
    python = {
      analysis = {
        typeCheckingMode = "on",
      },
    },
  },
}
```

**Comment by mehalter** [comment]
Here i the code you are looking for:

```lua
return {
  luasnip = {
    vscode_snippet_paths = {
      "./lua/user/snippets",
    },
  },
  plugins = {
    init = {
      {
        "IndianBoy42/tree-sitter-just",
        config = function() require("tree-sitter-just").setup {} end,
      },
    },
  },
  updater = {
    branch = "nightly",
  },
  mappings = {
    n = {
      ["<leader>tt"] = { function() astronvim.toggle_term_cmd "btop" end, desc = "ToggleTerm btop" },
    },
  },
  ["server-settings"] = {
    pyright = {
      settings = {
        python = {
          analysis = {
            typeCheckingMode = "on",
          },
        },
      },
    },
  },
}
```

**Comment by Noxdor** [comment]
I personally am not a big fan of this either, since it took me now a good while to figure out why pyright wouldn't check for types while mypy would 😂 Specially for pyright, which is advertised as a type checking lsp, it is very confusing and frustrating to install it and realise it doesn't do what you exactly chose it for. I don't know how much computation is saves with this, but I would say if you realise it causes too much trouble, you can still deactivate it manually.
Regarding the API, it really doesn't. If a user realises he is getting type checked all of a sudden even though he doesn't want that, then there is the easy way to switch that off in the user init right? I really don't see any problem with removing this from the interior settings since it appears to me it's easier to manually switch off than on.

**Comment by mehalter** [comment]
Okie doke, I just pushed a commit to nightly that removes the `pyright` and the `rust_analyzer` settings because those ones seem to serve no purpose to AstroNvim in particular.

**Comment by Noxdor** [comment]
Is it possible you just removed it? 😂 Just updated AstroNvim and the two files are gone 😂
