### ISSUE TITLE
which-key plugin

### ISSUE THREAD

**Issue by azinsharaf** [AstroNvim/AstroNvim#1091]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.2.0

### Neovim version (>= 0.7)

0.8.0

### Operating system/version

Windows 11

### Describe the bug

in the default `user/init.lua` (copy of `user_example`) in the `["which-key"]` we have ` ["b"] = { name = "Buffer" },` but `which-key` shows `+prefix` instead of `Buffer`. 
Am I missing anything?

![image](https://user-images.githubusercontent.com/10101468/195425843-626a9eeb-6cf9-433a-b107-ee7747250a3a.png)

### Steps to Reproduce

see above

### Expected behavior

b ---> Buffer

**Comment by mehalter** [comment]
I cannot replicate this. With a fresh installation of AstroNvim and then copying the `user_example/init.lua` to `user/init.lua` I see the appropriate item:

![2022-10-13_10:01:21_screenshot](https://user-images.githubusercontent.com/1591837/195618169-5b4c9202-7636-4f96-93fd-cb8430656beb.png)

**Comment by f73** [comment]
@azinsharaf 

I was able to fix it by renaming `register_mappings` to `register`

Whole block:

```
["which-key"] = {
    -- Add bindings which show up as group name
    register = {
      -- first key is the mode, n == normal mode
      n = {
        -- second key is the prefix, <leader> prefixes
        ["<leader>"] = {
          -- third key is the key to bring up next level and its displayed
          -- group name in which-key top level menu
          ["b"] = { name = "Buffer" },
        },
      },
```

**Comment by azinsharaf** [comment]
exactly! I compared my `init.lua` file with the one in `user_example` and noticed I was using `register_mapping` (probably came from an older astrnvim version). Thanks.

**Comment by mehalter** [comment]
@azinsharaf please make sure to follow the migration guide when updating from v1 to v2 https://astronvim.github.io/Configuration/v2_migration
