### ISSUE TITLE
docs: fix code snippet on disabling format on save

### ISSUE THREAD

**Issue by Clumsy-Coder** [AstroNvim/AstroNvim#1092]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.2.0

### Neovim version (>= 0.7)

0.8.0

### Operating system/version

macOS 10.15.7

### Describe the bug

Incorrect code snippet for disabling format on save

code snippet on https://astronvim.github.io/Recipes/advanced_lsp#disable-auto-format-on-save

### Steps to Reproduce

1. Go to https://astronvim.github.io/Recipes/advanced_lsp#disable-auto-format-on-save
2. check code snippet

### Expected behavior

1. Go to https://astronvim.github.io/Recipes/advanced_lsp#disable-auto-format-on-save
2. check code snippet
```lua
return {
  lsp = {
    on_attach = function(client, bufnr)
      if client.server_capabilities.documentFormattingProvider then
        vim.api.nvim_del_augroup_by_name "auto_format_" .. bufnr
      end
    end,
  },
}
```

### Screenshots

![image](https://user-images.githubusercontent.com/19594044/195465705-0d2a2a30-6f66-48a5-8283-9fd72ecbb8be.png)

### Additional Context

This is needed because of the code changes made in commit https://github.com/AstroNvim/AstroNvim/commit/65c16e3c61b657354c2fd67b9274145dc63efb8d

**Comment by mehalter** [comment]
Thanks for catching this! I just pushed a fix to resolve this. Also for future reference, feel free to open up issues on the docs directly since this isn't really a bug in AstroNvim: https://github.com/AstroNvim/astronvim.github.io
