### ISSUE TITLE
Document heirline colors overrides in example config

### ISSUE THREAD

**Issue by JCallicoat** [AstroNvim/AstroNvim#1109]
### Is your feature related to a problem?

I had been disabling heirline and reinstalling feline with my own config from `plugins.init`, but I had some time and decided to bite the bullet and port my config to heirline. I was looking at the default config in `heirline.lua` and saw colors could be overriden and so I started by creating `user/plugins/heirline.lua` and added:

```lua
return {
    colors = {
      bg = "NONE",
      section_bg = "NONE",
      winbar_bg = "NONE",
      winbarnc_bg = "NONE",
    },
}
```

It took me an embarrassingly long time and some debug `vim.pretty_print` to notice it was looking for `heirline.colors` *not* `plugins.heirline.colors`. Given the way the plugin options are overridden this makes sense but was confusing at first. After adding the below to `user/init.lua` everything worked.

```lua
  heirline = {
    colors = {
      bg = "NONE",
      section_bg = "NONE",
      winbar_bg = "NONE",
      winbarnc_bg = "NONE",
    },
  },
```

An example of `heirline.colors` in the example `init.lua` would be helpful to let people know it's possible to override them, and to show the correct place for it. I know the switch to heirline is pretty new and documenting stuff like this might be on the radar, but just raising an issue in case it's not.

### Describe the new feature

Provide an example of `heirline.colors` in example user config.

**Comment by mehalter** [comment]
I believe this is pretty well documented in the documentation and explained in quite detail. I'm not sure if you missed the documentation or didn't check it. Could you take a look here and tell me what you think. 

https://astronvim.github.io/Recipes/status#basic-options

This is also shown in the table of all user options: https://astronvim.github.io/Configuration/config_options

**Comment by JCallicoat** [comment]
Oh that is perfect, I missed that completely. Also these docs look really really good! I have been following along with the git commit log (since it was AstroVim ;) and the example user config and your big PRs but I hadn't checked the docs in a while, this is really great. I am going to have a read through them!

**Comment by mehalter** [comment]
Awesome! I'm glad you like the docs they have had a lot of work done on them and lots of recipes are commonly asked questions ! If you have any suggestions or edits you can also open issues on the documentation repo as well
