### ISSUE TITLE
UI doesn't update unless keys are pressed

### ISSUE THREAD

**Issue by the10thWiz** [AstroNvim/AstroNvim#1110]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.2.2

### Neovim version (>= 0.7)

NVIM v0.8.0-1210-gd367ed9b2

### Operating system/version

Windows 11 / WSL

### Describe the bug

Floating windows only update when another action is taken. This primarily effects pop-up notification windows, since they appear with partial opacity, and get more opaque over time. However, this animation only steps forward when another action is taken, e.g. moving the cursor.

Prior to running `PackerSync` & `AstroUpdate` this also affects the cursor leaving command mode.

EDIT: command mode was affected prior to update, not in neovide specifically

### Steps to Reproduce

1. Edit a file
2. Trigger a floating window, e.g. attempting to format a file that doesn't have a formatter isntalled
3. Step animation by moving the cursor with the hjkl keys

### Expected behavior

I would expect the animation to step even if the user isn't doing anything

**Comment by mehalter** [comment]
Hm I cannot replicate this at all. Also are you on an unreleased version of Neovim 0.8? Maybe try running the stable release and see if that was a bug that was fixed in the old nightly

**Comment by the10thWiz** [comment]
It looks like that was the issue. After switching to [https://github.com/neovim/neovim/releases/tag/stable], it appears to be fixed.
