### ISSUE TITLE
Better user configuration for heirline components

### ISSUE THREAD

**Issue by JCallicoat** [AstroNvim/AstroNvim#1111]
### Is your feature related to a problem?

I am porting my old feline config over to heirline and the way the components are overridden with positional table elements makes it a bit painful for customizing them. I may very well be doing something wrong or there is a better way to do it, but this is what I am running into right now.

The default heirline components are in this table:

https://github.com/AstroNvim/AstroNvim/blob/fa82ff92b438d764f2ed683cca2ec7e95e7ffb72/lua/configs/heirline.lua#L70-L86

In order to change or disable a component you need to construct a table of the same length with the component(s) you want to override at the correct index(es) and pass `nil` to keep the default component for the other indexes.

For example, to change the file info to hide the type and show the name and modified you need something like this in `user/plugins/heirline.lua`:

```lua
return {
  {
    nil, -- mode
    nil, -- git_branch
    astronvim.status.component.file_info(
      astronvim.is_available("bufferline.nvim")
          and { filetype = false, filename = { padding = { right = 1 } }, file_modified = {} }
        or nil
    ),
  },
}
```

Or to change the mode components, something like:

```lua
return {
  {
    mycomponent,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    myothercomponent,
  },
}
```

Or to disable a component you have to pass an empty table at the right index:

```lua
return {
  {
    nil,
    {}, -- disable git_status component
  }
}
```

This is pretty painful and also fragile if the indexes ever change in the default config. It also makes it a pain to insert a new component since it will just override whatever component was originally at that index.

I'm not sure of a good solution for this. I was thinking maybe have a new table like `plugins.heirline.components` that could just entirely replace the default components, but I think the way `user_plugin_opts` recursively  merges tables the same issue would still be there just under the new table. Then I was thinking maybe have named keys for the default components that users can either override to change default components or set to `nil` or `{}` to disable and then the rest of the table be positional elements that are additional user components?

### Describe the new feature

Provide a better way to customize heirline components.

**Comment by mehalter** [comment]
Have you taken a look at the documentation on how to customize the statusline? I would recommend starting there: https://astronvim.github.io/Recipes/status

This is definitely a tricky situation because merging array like tables in Lua is weird and there's no good way to customize the statusline without array like tables. Please check out the docs on customizing the statusline and what you think of it. The API we developed happened over ~5 months and I am not sure if there's a better way to do it without adding in limitations rather than full extensibility

**Comment by JCallicoat** [comment]
I completely had not seen all the new docs and recipes, I am going to have a full read and play with things some more. I'll going to go ahead and close this issue and if I am still finding it hard I will open a new issue with a better understanding of the recommended ways to customize it. Thanks for all your work on this project, it's literally the best version of any editor I have used.
