### ISSUE TITLE
python and btop toggle term failed to launch (w/fix)

### ISSUE THREAD

**Issue by convers39** [AstroNvim/AstroNvim#1113]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.2.2

### Neovim version (>= 0.7)

0.8

### Operating system/version

macOS 12.5

### Describe the bug

with default mapping in `core/mappings.lua` as below:

```lua
-- Terminal
if is_available "toggleterm.nvim" then
  local toggle_term_cmd = astronvim.toggle_term_cmd
  -- ...
  maps.n["<leader>tt"] = { function() toggle_term_cmd "btm" end, desc = "ToggleTerm btm" }
  maps.n["<leader>tp"] = { function() toggle_term_cmd "python" end, desc = "ToggleTerm python" }
end
```

The argument `btm` and `python` just failed to launch the terminal.

Changing to `btop` and `python3` fixed the issue. 

```lua
  maps.n["<leader>tt"] = { function() toggle_term_cmd "btop" end, desc = "ToggleTerm btm" }
  maps.n["<leader>tp"] = { function() toggle_term_cmd "python3" end, desc = "ToggleTerm python" }
```

BTW alias seems not to work, I tried with `py` which is set as an alias but failed to launch.

Not sure if this is a universal issue.

### Steps to Reproduce

leader tp -> show nothing
leader tt -> show nothing

### Expected behavior

Launch python and btop with toggleterm.

### Screenshots

<img width="821" alt="image" src="https://user-images.githubusercontent.com/42597395/195976744-04f795fe-32c1-4a4e-9189-61b86d24b87b.png">

**Comment by mehalter** [comment]
These are just recommended applications. And you are not required to use them. They are shown in the optional dependencies. Feel free to override these mappings in your user configuration if you want to change which terminal application they open. They are designed to be applications that are both the most widely used as well as cross platform to reach all users
