### ISSUE TITLE
Hiding winbar

### ISSUE THREAD

**Issue by aliaksandr-s** [AstroNvim/AstroNvim#1115]
### Question

Just installed AstroNvim and trying to do some configurations.
Currently struggling with hiding the winbar. Is there a way to hide it completely?
Tried to edit `options` in `user/init.lua` but it didn't work

```lua
  options = {
    opt = {
      winbar = nil,
    },
    opt_local = {
      winbar = nil,
    },
  },

```

**Comment by mehalter** [comment]
https://astronvim.github.io/Recipes/disable_winbar
