### ISSUE TITLE
Error when writing a rust file (likely formatting/LSP)

### ISSUE THREAD

**Issue by GMFranceschini** [AstroNvim/AstroNvim#1116]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.2.2

### Neovim version (>= 0.7)

NVIM 0.8.0

### Operating system/version

Ubuntu 22.04

### Describe the bug

When writing a rust file, I obtain the following error:

```
Error detected while processing BufWritePre Autocommands for "<buffer=1>":
Error executing lua callback: /home/gianma/.config/nvim/lua/core/utils/lsp.lua:130: attempt to call field 'format' (a nil value)
```
Line 130 of lsp.lua is:

```
callback = function() vim.lsp.buf.format(astronvim.default_tbl({ bufnr = bufnr }, astronvim.lsp.format_opts)) end,
```

`rust-analyzer` is installed.

### Steps to Reproduce

1. Open a rust project
2. Modify the file
3. Save with `:w`

### Expected behavior

No error is encountered.

### Additional Context

EDIT: it also happens with other types of files (like ".R"), but not with all of them (not Python, for example). I installed the language server for all of those languages.

**Comment by mehalter** [comment]
@GMFranceschini I have tested this some more and cannot replicate. The error you are getting also has something to do with `format` being `nil`. This should never be the case. Even if you just open a neovim with no config `nvim -u NONE` and run `:lua print(vim.lsp.buf.format)` it will show that it is a function and not `nil`. I would recommend trying to refresh your `data` and `cache` folders:

```
mv ~/.local/share/nvim ~/.local/share/nvim.bak
mv ~/.cache/nvim ~/.cache/nvim.bak
nvim +PackerSync
```

**Comment by GMFranceschini** [comment]
That worked once again! Thank you, it seems that clearing the cache resolves multiple problems; I will do that before submitting any further issues!

**Comment by GMFranceschini** [comment]
I tested precisely what you suggested:

```
nvim -u NONE
:lua print(vim.lsp.buf.format)
```

And I do obtain `nil` as a result. 
Removing `data` and `cache` worked simply because the Lsp was gone. So, this has nothing to do with my config at this point but with neovim itself.  I will seek help in the `neovim` repo.

```

nvim --version
NVIM v0.8.0-1210-gd367ed9b2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az505-656

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info

```

**Comment by mehalter** [comment]
Oh that's very very strange 🤔

**Comment by GMFranceschini** [comment]
Ok, I understood my mistake. When installing `neovim` from the precompiled tar, I moved the executable to `/usr/bin/`. This caused the issue; executing `nvim` from the proper folder resulted in no error. 
Honestly, I don't understand why this is the case, but I hope this could be useful for reference.
