### ISSUE TITLE
OS USES ON SCREENSHOTS

### ISSUE THREAD

**Issue by MostafaMohamed2002** [AstroNvim/AstroNvim#1119]
### Question

can someone tell me what's the os uses on screenshots ?

**Comment by mehalter** [comment]
@kabinspace can answer this morning depth, but it's Arch Linux with a window manager and custom theming for the bar across the top and everything

**Comment by mehalter** [comment]
I guess the easiest thing is to share his dotfiles: https://github.com/kabinspace/dotfiles

This shows the programs he uses and the configuration files as well
