### ISSUE TITLE
Heirline only works for a brief moment after performing the initial `+PackerSync` run

### ISSUE THREAD

**Issue by NINNiT** [AstroNvim/AstroNvim#1122]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.2.2

### Neovim version (>= 0.7)

NVIM v0.8.0

### Operating system/version

ArchLinux

### Describe the bug

Hi, I'm experiencing a weird bug:

After the initial `+PackerSync` run, heirline works for a brief moment. As soon as i exit the packer window and/or restart neovim, heirline is gone and neovim is defaulting to its default statusbar. 

Compiled Lua in `./local/share/nvim/packer_compiled.lua`:
```
  ["heirline.nvim"] = {
    config = { "\27LJ\2\n0\0\0\3\0\2\0\0046\0\0\0'\2\1\0B\0\2\1K\0\1\0\21configs.heirline\frequire\0" },
    loaded = true,
    path = "/home/<redacted>/.local/share/nvim/site/pack/packer/start/heirline.nvim",
    url = "https://github.com/rebelot/heirline.nvim"
  },
```
Furthermore, above `path` contains heirline files. 

I've tested it using various different terminals (with TrueColor support). I've also tested various different NerdFont-patched fonts.
However, it could still be that the problem is on my end - are there any other files (besides `~/.local/share/nvim` and `~/.config/nvim`) that could interfere/override something?

Thanks!  

### Steps to Reproduce

1. Delete `~/.local/share/nvim`
2. Run `nvim +PackerSync`
(Or completely reinstalling and deleting config in `~/.config/nvim)`
3. Heirline is showing when packer has finished syncing
4. As soon as i quit the packer process (`q`), restart neovim or perform another `+PackerSync` run,  heirline is missing and neovim is defaulting to the standard neovim statusbar

### Expected behavior

Heirline should work, even after restarting neovim. 

### Screenshots

![image](https://user-images.githubusercontent.com/1691878/196262717-345bcf34-6b4a-4d9e-baf6-a5767ad81c64.png)

### Additional Context

I'm not using any user-defined configuration.

**Comment by mehalter** [comment]
@NINNiT I cannot reproduce this. Could you please also try deleting your `~/.cache/nvim` folder to see if anything is getting cached? The weird thing here is that the screenshot you are showing is not the default Neovim statusline. This is a custom statusline coming from somewhere (I'm not sure where or why it's coming up on your config). You should make sure you aren't adding this anywhere in your runtime path. This would cause the overwriting of the statusline we are setting after the loading and cause the beahvior you are describing.

**Comment by mehalter** [comment]
![2022-10-17_15:50:24_screenshot](https://user-images.githubusercontent.com/1591837/196269776-53a2fb27-1f93-455f-80e8-af0face476d6.png)


Just for referehce, this is the default neovim statusline

**Comment by mehalter** [comment]
It could also be that you have a different statusline plugin in your plugin list that is getting installed when you do the packersync. Maybe feling/lualine/etc. That seems to make the most sense since it works on a fresh install and then shows up after you install all of your plugins

**Comment by NINNiT** [comment]
Thanks @mehalter, you brought me onto the right track!
