### ISSUE TITLE
integrating tmux and astronvim

### ISSUE THREAD

**Issue by azinsharaf** [AstroNvim/AstroNvim#1126]
### Question

How can I disable non-default plugins temporarily without commenting out them in `user/init.lua`?

**Comment by mehalter** [comment]
temporarily? I'm not sure, some plugins have the ability to toggle them with commands or APIs. It would be up to the plugin to provide this type of functionality

**Comment by mehalter** [comment]
commenting them out will uninstall them

**Comment by azinsharaf** [comment]
yeah so commenting out was not a good idea. 
Do you have any non-default plugin example that has this capability?

**Comment by mehalter** [comment]
I'm not sure off the top of my head. What plugin are you trying to disable temporarily?

**Comment by azinsharaf** [comment]
i ma trying to configure [vim-tmux-navigator](https://github.com/christoomey/vim-tmux-navigator#tmux) but don't work as expected.

**Comment by mehalter** [comment]
@azinsharaf have you tried this without this plugin. We have `smart-splits` which has its own tmux navigation with `c-h/j/k/l`. Try uninstalling the plugin and see if it just works out of the box with AstroNvim :)

**Comment by azinsharaf** [comment]
ok, things are getting interesting! Now I am using `smart-splits` out of the box and based on its document I integrated it with `tmux` using `TPM`. (link : https://github.com/mrjones2014/smart-splits.nvim#tmux-integration). It means I didn't install `vim-tmux-navigator` in `astronvim`. I just added its `TPM` part into `tmux.conf`. 
So `ctrl hjkl` works in `tmux` but doesn't work between neovim panes. Not sure if you can reproduce it or it is the plugins issue not Astronvim issue.

this is my layout:
upper left: neovim buffer
lower left: neovim buffer
upper right: tmux
lower right: tmux

**Comment by mehalter** [comment]
This would be an issue with the plugin. It seems like your tmux config isn't passing the binding through to Neovim if you are in a Neovim pane. I personally use the bindings described rather than the tpm plugin. But yeah this would fall under issues with the plugins and unrelated to the AstroNvim stuff. Hopefully you can get it working though!

**Comment by kaka-ruto** [comment]
For anyone who finds themselves here, you would need to add these lines to your tmux config (and remove any conflicting ones)
From https://github.com/mrjones2014/smart-splits.nvim#tmux
```
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n C-h if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n C-j if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n C-k if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n C-l if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'

bind-key -n M-h if-shell "$is_vim" 'send-keys M-h' 'resize-pane -L 3'
bind-key -n M-j if-shell "$is_vim" 'send-keys M-j' 'resize-pane -D 3'
bind-key -n M-k if-shell "$is_vim" 'send-keys M-k' 'resize-pane -U 3'
bind-key -n M-l if-shell "$is_vim" 'send-keys M-l' 'resize-pane -R 3'

tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l
```
