### ISSUE TITLE
Highlights not working when i change computer

### ISSUE THREAD

**Issue by nappalm** [AstroNvim/AstroNvim#1127]
### Question

This is possibly not the right place to post this, but I have the following problem.

I have changed my computer, I am using windows. 

In my previous computer I see that "language features" were initialized
![image](https://user-images.githubusercontent.com/35016608/196578066-85acfd71-2556-4126-bc23-1f490a0caefc.png)

In my current computer no, the highlight doesn't even work:
![image](https://user-images.githubusercontent.com/35016608/196578117-3373ec0b-d85f-4db5-ba77-ec1aef6435cb.png)

Does anyone know what may be missing from the install?

for TS: typescript, tsx lua javascript
for LSP: cssmodules_ls, eslint, tsserver, tailwindcss

### User Configuration

https://github.com/nappalm/nvim-config/tree/main/nvim

**Comment by mehalter** [comment]
What version of Neovim and AstroNvim are you using?

**Comment by nappalm** [comment]
> What version of Neovim and AstroNvim are you using?
NVIM v0.8.0-1210-gd367ed9b2

The command to display the versions does not work for me ` :AstroVersion`

**Comment by mehalter** [comment]
It sounds like you may have an older version of AstroNvim. Have you updated in a while? If you do update to v2.0 which adds Neovim 0.8 support you will need to do the migration guide to update your user configuration. But that is probably the reason you do not have highlighting, older versions of AstroNvim do not support Neovim 0.8

**Comment by mehalter** [comment]
I also see that you have forked AstroNvim rather than doing the user configuration path. This is an unsupported use case and will keep you from being able to receive updates

**Comment by nappalm** [comment]
> I also see that you have forked AstroNvim rather than doing the user configuration path. This is an unsupported use case and will keep you from being able to receive updates

They are newbie configurations, sorry. I'll make that adjustment soon.
I have seen that the version of AstroNvim is: 1.9.2

**Comment by mehalter** [comment]
Ok cool, yeah you will need to update to the v2 of AstroNvim to get Neovim 0.8 support. Also v2 comes with checks to make sure you are using a supported version of Neovim and will alert you if you are not which can be helpful in the future for stuff like this :)
