### ISSUE TITLE
Investigate telescope-fzf-native.nvim windows support 

### ISSUE THREAD

**Issue by jayp0521** [AstroNvim/AstroNvim#1128]
### Question

https://github.com/AstroNvim/AstroNvim/blob/893665a969129eb528e54b7e4bee1e6c952d6d25/lua/core/plugins.lua#L181-L186

I don't really know this plugin too well, but it seems as if `run` is missing in packer.nvim for it?

https://github.com/nvim-telescope/telescope-fzf-native.nvim#packernvim

**Comment by jayp0521** [comment]
at least for the windows side, this seems true

**Comment by jayp0521** [comment]
I think cmake &| make should be listed as a requirement as well. My installation seemed to be missing this

**Comment by mehalter** [comment]
It looks like fzf native has been working on windows support. The main funkiness we do here is for windows we actually don't use `fzf-native`, instead we have it install https://github.com/nvim-telescope/telescope-fzy-native.nvim

Which doesn't require building for Windows as it ships with a prebuilt binary. It is less performant though. Maybe we should look into improving this to use the new `fzf-native` windows support 🤔

**Comment by jayp0521** [comment]
oohhh right. yes, sorry. slipped out of my brain

**Comment by mehalter** [comment]
Thanks for the heads up for the new additions to fzf native! I am going to reword this issue title and convert this to an enhancement so we can keep discussion here as I test this a bit more over the coming days :)

**Comment by mehalter** [comment]
@jayp0521 do you use AstroNvim on windows? If you do, could you test the latest commit on `nightly`? This moves windows to also using `telescope-fzf-native`

**Comment by jayp0521** [comment]
Sorry, I do not. Thanks for it!

**Comment by koslak** [comment]
Hi, for those who are facing this issue on Windows, what is happening is that the _telescope-fzf-native.nvim_ plugin is not being built. You can check this by doing this:

1. Open a CMD window and go to the plugin's folder:

`> cd %AppData%\..\Local\nvim-data\site\pack\packer\opt\telescope-fzf-native.nvim`

2. Go to the `build` folder and then you will see that is empty. 

**The following are the steps that I did to make it work:** 

1. Open a CMD window and go to the plugin's folder:

`> cd %AppData%\..\Local\nvim-data\site\pack\packer\opt\telescope-fzf-native.nvim`

2. Run the following command (make sure you have the dependencies installed (like cmake) to build this plugin):

`> cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release && cmake --build build --config Release && cmake --install build --prefix build`

**Note:** The instruction above is from the Github repository: [telescope-fzf-native.nvim github](https://github.com/nvim-telescope/telescope-fzf-native.nvim#cmake-windows-linux-macos).

3. Make sure the plugin was built. Go to the folder:

`> cd %AppData%\..\Local\nvim-data\site\pack\packer\opt\telescope-fzf-native.nvim\build\Release`
`> dir`

and now you should see the following files: 

```
24-Feb-23  11:27 PM    <DIR>          .
24-Feb-23  11:27 PM    <DIR>          ..
24-Feb-23  11:27 PM             2,796 fzf.exp
24-Feb-23  11:27 PM             4,620 fzf.lib
24-Feb-23  11:27 PM            22,016 libfzf.dll
               3 File(s)         29,432 bytes
```

4. Now open Nvim and run the command `:PackerSync`
