### ISSUE TITLE
installing vim-ionide

### ISSUE THREAD

**Issue by ShalokShalom** [AstroNvim/AstroNvim#1130]
### Question

Both `LspInstall ionide` and `LspInstall ionide-vim` tell me that such a server does not exist. 
Is there a search option? 

### User Configuration

https://github.com/ionide/Ionide-vim

**Comment by mehalter** [comment]
Yeah you can use `:Mason` or `<leader>uP` to open the installer window and search the available packages. It looks like `ionide` is not supported. Also the link you sent shows you need to install it as a plugin with a run command added so you will need to add this to your user configuration in the `plugins.init` table

**Comment by ShalokShalom** [comment]
Thanks

You mean not supported by AstroVim?

**Comment by mehalter** [comment]
It's not supported to be installed with Mason. Mason installs external packages. The link you sent is a Neovim plugin, so you need to install it like a plugin. This is fully supported by AstroNvim :) you just need to make a user configuration file to modify what plugins are available. Check out the documentation website for how to do this: https://astronvim.github.io/Configuration/basic_configuration

**Comment by mehalter** [comment]
A minimal `user/init.lua` file that adds this plugin would just be this:

```lua
return {
  plugins = {
    init = {
      { "ionide/Ionide-vim" },
    },
  },
}
```
