### ISSUE TITLE
Unexpected scroll of the greeter/dashboard

### ISSUE THREAD

**Issue by haoyun** [AstroNvim/AstroNvim#1137]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.3.0

### Neovim version (>= 0.8)

NVIM v0.8.0

### Operating system/version

Fedora release 36 (Thirty Six) x86_64

### Describe the bug

unexpected screen scroll

### Steps to Reproduce

1. start nvim
```
$ nvim
```
2. press `j`

### Expected behavior

only the cursor moves one line down, but the dashboard should stay fixed.

### Additional Context

comment out 
```
    {
      condition = function()
        return astronvim.status.condition.buffer_matches {
          buftype = { "terminal", "prompt", "nofile", "help", "quickfix" },
          filetype = { "NvimTree", "neo-tree", "dashboard", "Outline", "aerial" },
        }
      end,
      init = function() vim.opt_local.winbar = nil end,
    },
```
in `lua/configs/heirline.lua` solves the problem. I am not familiar with the configuration of `heirline`, so I can't give a fix.

**Comment by mehalter** [comment]
Fixed in `nightly`
