### ISSUE TITLE
aerial plugin update issue

### ISSUE THREAD

**Issue by azinsharaf** [AstroNvim/AstroNvim#1141]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.4.0

### Neovim version (>= 0.8)

0.8.0

### Operating system/version

Windows 11

### Describe the bug

It is a while that `aerial` plugin can't be updated. Is it a known issue and reproducible by others?

![image](https://user-images.githubusercontent.com/10101468/197018998-af74cff0-9766-4f00-ab7b-5271d4d3bd6f.png)

### Steps to Reproduce

:Packersync

### Expected behavior

updating aerial

**Comment by mehalter** [comment]
It looks like for some reason the clone of aerial that you have has gotten corrupted somehow maybe with a rebase with aerial or them changing tracked files.

The best way to get around this when plugin authors make weird changes to their git history/tracking is to go and manually fix the git clone or uninstall and reinstall the plugin.

```sh
rm -rf ~/.local/share/nvim/site/pack/packer/opt/aerial.nvim
nvim +PackerSync
```
