### ISSUE TITLE
Pass colorscheme attributes to Heirline

### ISSUE THREAD

**Issue by maxbrunet** [AstroNvim/AstroNvim#1147]
### Is your feature related to a problem?

Colorscheme may set highlight attributes in addition to `fg`/`bg` colors (ellisonleao/gruvbox.nvim#119 / #1050)

With `gruvbox` for example `:highlight StatusLine` outputs:

```
StatusLine     xxx cterm=reverse gui=reverse guifg=#504945 guibg=#ebdbb2
```

### Describe the new feature

* Retrieve and return attributes in `astronvim.get_hlgroup()`
* Apply attributes to Heirline groups along side `fg` and `bg`

### Additional context

Attributes like `cterm=reverse` are discarded by `astronvim.get_hlgroup()`, and thus, not passed to Heirline

https://github.com/AstroNvim/AstroNvim/blob/5288bad46858f15f2290aeb3d09c8bd8e58b7882/lua/configs/heirline.lua#L5-L66

https://github.com/AstroNvim/AstroNvim/blob/5288bad46858f15f2290aeb3d09c8bd8e58b7882/lua/core/utils/init.lua#L103-L113

Heirline seems to have some support for them:

https://github.com/rebelot/heirline.nvim/blob/9d0add99b8bdfdc8a734165a26a5fbc05bd6bcbe/lua/heirline/highlights.lua#L38-L49

See also [`:help inverse`](https://neovim.io/doc/user/syntax.html#inverse)

**Comment by mehalter** [comment]
for now @maxbrunet I have come up with a little bandaid that should resolve your issues with `gruvbox` hopefully 🤞🏼 I am getting the full highlight group for the `StatusLine`/`WinBar`/`WinBarNC` so it should hopefully fix your issue for now. I am still going to try and resolve this with Heirline and get a much better fix put together.

**Comment by maxbrunet** [comment]
Hey @mehalter, thank you for taking a look at this, I've tried the `nightly` branch, here's what it looks like:

![image](https://user-images.githubusercontent.com/32458727/197250181-5dec09ec-7567-4058-9477-26e6c4b1e08d.png)

No hurry though, I've been reviewing my config in the past couple days and removing the few hacky or sub-optimal settings, but overall it works great, mainly thanks to you!

Currently, I have simply hard-coded the colors:
https://github.com/maxbrunet/dotfiles/blob/3b82239c8c8ab6c9d9a747e73ce32ab57e03c196/.config/astronvim/lua/user/init.lua#L16-L26

**Comment by mehalter** [comment]
@maxbrunet a new change has come out with Heirline, could you test the latest with the `nightly` channel and see if you get the same result as the screenshot you sent? I am planning on reworking the statusline stuff to use highlight groups more properly now that the upstream highlight group support has been fixed.

**Comment by maxbrunet** [comment]
Thank you for the update, now I get that:

![image](https://user-images.githubusercontent.com/32458727/197618028-2b8748ad-0614-4d30-929b-0d9355cb9a59.png)

And the hard-coded workaround does not work anymore:

![image](https://user-images.githubusercontent.com/32458727/197619948-efa8a79c-25a4-448d-8b21-f001abbd8608.png)

**Comment by mehalter** [comment]
@maxbrunet I have gone ahead and reverted the heirline changes that I have made because it caused a bunch of instability :/ I will need to think about if there is a really nice way to do this without causing a bunch of breaking changes. I might have to push this down the road a bit to get a good solution together.

One thing you can do which would be a really nice way to resolve this one theme issue is something like this in your `user/init.lua` file:

```lua
return {
  highlights = {
    gruvbox = {
      StatusLine = { fg = "#ebdbb2", bg = "#504945" },
    },
  },
}
```

this will override the hlgroup directly in the theme that you are trying to use rather than overriding the Heirline colors directly. This is a cleaner solution to hardcoding those one sets of colors and also lets you use other themes without getting stuck with static colors in Heirline. :)

**Comment by maxbrunet** [comment]
> I have gone ahead and reverted the heirline changes that I have made because it caused a bunch of instability :/

No problem :+1:

> this will override the hlgroup directly in the theme that you are trying to use rather than overriding the Heirline colors directly. This is a cleaner solution to hardcoding those one sets of colors and also lets you use other themes without getting stuck with static colors in Heirline. :)

Thank you for the suggestion, yes, that would be a nicer workaround, unfortunately, it seems Heirline gets the group before the override happens, I had to keep my old workaround for the `section_` fg/bg and override this line for `fg`/`bg`:

https://github.com/AstroNvim/AstroNvim/blob/c69d25a22538c64651d9a018f0fa945616975d45/lua/configs/heirline.lua#L72

```lua
  plugins = {
    heirline = function(config)
      config[1] = vim.tbl_deep_extend("force", config[1], {
        hl = { fg = "#ebdbb2", bg = "#504945" },
      })
      return config
    end,
  }
```

It seems to be redundant with these lines and might even make them ineffective:

https://github.com/AstroNvim/AstroNvim/blob/c69d25a22538c64651d9a018f0fa945616975d45/lua/configs/heirline.lua#L26-L27

**Comment by mehalter** [comment]
Oh hm that's a good point, I will investigate this to see if I can fix the ordering... Not sure if you can add priority to autocmds

**Comment by mehalter** [comment]
@maxbrunet I believe I have solved this issue now :) Could you try pulling the latest nightly and see if the nicer work around is working now?

**Comment by maxbrunet** [comment]
Same result as before :(

**Comment by mehalter** [comment]
![2022-10-26_14:20:43_screenshot](https://user-images.githubusercontent.com/1591837/198105515-2ff4e6fd-edc2-4c1f-9f2e-6c7516704d8f.png)


hm @maxbrunet I also can't replicate with gruvbox directly either

**Comment by maxbrunet** [comment]
:confused: With 63aa352f6b2d519f92917a75d33dcafff1de8c9b and minimal config:

```lua
return {
  colorscheme = "gruvbox",

  highlights = {
    gruvbox = {
      StatusLine = { fg = "#ebdbb2", bg = "#504945" },
    },
  },

  plugins = {
    init = {
      ["ellisonleao/gruvbox.nvim"] = { version = "1.0.0" },
    },
  },
}
```

The highlight group is overridden: 

```
:highlight StatusLine
StatusLine     xxx guifg=#ebdbb2 guibg=#504945
```

But:

![image](https://user-images.githubusercontent.com/32458727/198110550-c83b7539-02b4-4f80-b865-d9f0e3cbc5be.png)

**Comment by maxbrunet** [comment]
Working around nicely :grin:, thank you!

**Comment by ZhaoZuohong** [comment]
> 

This works for me!

**Comment by ZhaoZuohong** [comment]
> ```lua
>   highlights = {
>     gruvbox = {
>       StatusLine = { fg = "#ebdbb2", bg = "#504945" },
>     },
>   },
> ```

This works for me!

**Comment by mehalter** [comment]
@maxbrunet to get the proper fix for this is going to be a super heavy lift with stuff that will need to be improved not only in AstroNvim but also with Heirline. I don't have time to do this restructuring at the moment and also don't want to introduce breaking changes. I think for now I'm going to close this as unplanned and leave it on the back burner for the moment especially since we do have a pretty nice work around that can be applied on a per theme basis.
