### ISSUE TITLE
Error on reload when updating AstroNvim

### ISSUE THREAD

**Issue by rikyborg** [AstroNvim/AstroNvim#1149]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.3.0

### Neovim version (>= 0.8)

NVIM v0.8.0-1210-gd367ed9b2

### Operating system/version

Ubuntu 22.04.1 LTS

### Describe the bug

When updating AstroNvim (with `<leader>pA`), I get the following error:

```
Update available to v2.4.2
Updating requires a restart, continue?
(y/n) y




AstroNvim updated successfully to v2.4.2!
AstroNvim will now sync packer and quit.

Changelog:
[5288bad] fix(ui): show changed status for toggling autoformatting and tabline
[a4292d2] fix(lsp): fix formatting whitelist
[f5200f4] chore(snapshot): update packer_snapshot
[ecf7383] fix(autocmds): fix winbar showing up in alpha at start
[a68e569] fix(default_theme): match cmp completion with aerial
[3847fb9] fix(default_theme): fix aerial highlights
[304e3e2] chore(utils): add missing doc string for default_tbl
[71d85c7] feat(lsp): support format_on_save whitelist
[77d488d] chore(mappings): make spell and paste bindings more natural
[b7f0cec] chore(telescope): remove redefined default config values
[8265f87] chore(plugins): add windows support for telescope-fzf-native
[f6a6738] feat: add signs/icons for nvim-dap for those who use it

Failed to load core.options

vim/_meta.lua:0: E21: Cannot make changes, 'modifiable' is off
Press ENTER or type command to continue
```

The above output was when updating from v2.3.0 to v2.4.2. I got a very similar problem when updating from v1.9.2 to v2.3.0.

After I hit `ENTER`, PackerSync runs and nvim exits. When starting nvim again, everything seems to work well and AstroNvim is up to date.

### Steps to Reproduce

1. Start `nvim`
2. Run `:AstroUpdate`

### Expected behavior

Update AstroNvim without errors.

**Comment by mehalter** [comment]
I just want to confirm that I can replicate this. I'm not completely sure why it happens yet sadly. It seems to be coming form the reload function after the upgrade is complete, but weirdly I can't replicate it doing a reload without an update. Luckily it seems to be mainly just cosmetic and ugly and doesn't affect the functionality. But definitely is on my todo list to fix ASAP. Sorry!

**Comment by mehalter** [comment]
Ay! @rikyborg I figured out a fix for this finally! I have it currently in the `nightly` channel!

**Comment by rikyborg** [comment]
Great!

And in general, thanks for the good work, I really enjoy AstroNvim! It's already great out of the box, and still very easy to customize further.

**Comment by mehalter** [comment]
Thanks so much! Glad you are enjoying it 🤩
