### ISSUE TITLE
`.` doesn't work as expected on a visual selection

### ISSUE THREAD

**Issue by llimllib** [AstroNvim/AstroNvim#1151]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

Version: v2.4.2

### Neovim version (>= 0.8)

0.8.0

### Operating system/version

macOS 12.6

### Describe the bug

in default vim: `<shift-v>jjj<esc>>...` will select three lines, indent them once (`>`), then indent them three more times (`...`)

in astrovim, the `.` character does not repeat the indent. I don't know how to investigate what the mapping is that takes precendence, or I'd look into it myself.

### Steps to Reproduce

1. Open a textfile with no config: `nvim -u NONE`
2. select a few lines in visual line mode
3. type `>...`
4. note that your lines have indented four times
5. try the same thing in astrovim, note that they have not

### Expected behavior

the `.` key repeats an indentation in visual line mode

**Comment by mehalter** [comment]
@llimllib we have actually remapped the visual mode `>` to make more sense. You can keep pressing `>` to keep indenting which you cannot do with a stock version of Neovim. so instead of `>...` you can just do `>>>>`. If you would like to remove this remapping you can do this in your `user/init.lua` file:

```lua
return {
  mappings = {
    v = {
      ["<"] = false,
      [">"] = false,
    },
  },
}
```

**Comment by llimllib** [comment]
That doesn't explain why `.` doesn't repeat the action? This is hardwired into my fingers from decades of use!

**Comment by llimllib** [comment]
(i.e. it seems to me that the proper behavior would be that _both_ `>>>` and `>..` indent three times)

**Comment by mehalter** [comment]
sadly I don't think there is a binding to do this. `.` repeats the previous command in normal mode. The way we have `>` set up to be able to continuously do `>` is that it keeps you in visual mode after `>` so the `.` operator is not valid until you leave visual mode. Once you leave visual mode there is no selection to continue doing `>`. By staying in visual mode it also allows you to do `<` immediately after you do `>` if you change you mind about the indenting. Not sure if there is a good solution for enabling both of these things out of the box. Let me know if you have any ideas though :) It would be nice to have `>>>` and `>..` working but I'm not sure how to do it with the changing of modes and `.` becoming available if that makes any sense

**Comment by llimllib** [comment]
hmph, thanks for the update. Sounds dumb, but I think this tanks astronvim for me; thanks for the quick responses.

for what it's worth, disabling the indent and dedent mappings also did not work - they function as before even with the mapping you gave in your comment.

**Comment by mehalter** [comment]
I'm sorry that this tanks your opinions of AstroNvim. Also could you please share what you currently have in your `user/init.lua` file and I can help debug what's happening and why that code snippet didn't work? :)

**Comment by llimllib** [comment]
Apologies, I should clarify that my opinion of AstroNvim is still quite high! It just doesn't work for me I don't think, which is fine, it should be opinionated and I can see the viewpoint from which that change makes sense.

I don't mean to hate on your work at all, and apologies if I gave that impression.

> I can help debug what's happening and why that code snippet didn't work?

I appreciate the offer! But I just wanted to report it - I want back to my previous config

**Comment by mehalter** [comment]
Ok no problem :) yeah it's tough managing an opinionated configuration which is why we have taken the route of making it easy to change the opinions on the user side since not many people will be happy with anything 100% out of the box.

**Comment by mehalter** [comment]
For reference, I also disable these `>` and `<` bindings along with many other default bindings to make the setup fit my own workflow :joy: If you are interested to see the level of customization, you can take a peek at my config here: https://code.mehalter.com/projects/68
