### ISSUE TITLE
Start LSP server on BufEnter

### ISSUE THREAD

**Issue by maxbrunet** [AstroNvim/AstroNvim#1153]
### Is your feature related to a problem?

When opening a file (`BufEnter` event if I'm correct) the LSP server is not started, meaning features like GoTo, Aerial, diagnostics, document highlights... are not available without going into insert mode first (`InsertEnter` event if I'm correct again) (and often existing to normal mode immediately)

### Describe the new feature

Start LSP server on BufEnter

### Additional context

I have tried to figure out where it was configured, if AstroNvim has an opinion or if it is the default from a plugin, but without success sorry.

I think it was not the case in AstroNvim v1.

**Comment by mehalter** [comment]
I can't replicate this behavior @maxbrunet it should be starting when the file is loaded

**Comment by maxbrunet** [comment]
Here is a minimal config if that helps to reproduce:

```lua
return {
  lsp = {
    servers = {
      "pylsp",
    },
  },
}
```

I checked `mason-lspconfig` and it is not affected, this starts as soon as the file is opened:

```lua
return {
  plugins = {
    ["mason-lspconfig"] = { 
      ensure_installed = { "pylsp" },
    },
  }
}
```

(`null-ls` is fine too if you wonder)

**Comment by mehalter** [comment]
Ah I see I see, I can replicate this. I will need to investigate this to see why this is happening. It seems to be because of our `vim.schedule` call. I'll try to get a good fix together for this :)

**Comment by mehalter** [comment]
@maxbrunet could you test out the latest `nightly`?

**Comment by mehalter** [comment]
I ended up just removing the scheduling of the LSP setup. I have tested it in several different situations and I'm pretty sure it's working fully. I'm not sure why we added this which makes me worried I'm not thinking about some edge case 🤔 We will see as people use `nightly`. Hopefully this doesn't cause a big mess :joy:

**Comment by maxbrunet** [comment]
Working well, thank you!

**Comment by maxbrunet** [comment]
@mehalter It seems this has regressed in 2.7.0 (including 2.7.3), LSP does not start when opening the file

**Comment by mehalter** [comment]
Can you make sure you have updated to 2.7.3 and have run packersync, this Should be resolved in 2.7.3. there was a bug with this in 2.7.0

**Comment by mehalter** [comment]
This Shou be resolved when we call filetype on LSP loading

**Comment by maxbrunet** [comment]
Yes, I have seen the related commits, but 2.7.3 with PackerSync done and Lua cache cleared, it does not start without going into insert mode. 2.6.5 is the latest that has it working for me

**Comment by mehalter** [comment]
Hm @maxbrunet I cannot seem to replicate this with AstroNvim and pylsp 🤔

**Comment by maxbrunet** [comment]
I have cleaned up everything and reinstalled from scratch with the minimal config, no luck, it starts on insert :confused:

```lua
return {
  lsp = {
    servers = {
      "pylsp",
    },
  },
}
```

```console
$ nvim --version
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/gy83kq8263p3ym4s62l5fx9jf1ic06zs-neovim-unwrapped-0.8.0/share/nvim
"

Run :checkhealth for more info
```

**Comment by mehalter** [comment]
Hm I can't seem to replicate, I just pushed to `nightly` kinda shooting in the dark but it might solve the problem. Could you see if that resolves it?

**Comment by maxbrunet** [comment]
Yup, nice shot, it works! :grinning:

**Comment by mehalter** [comment]
wow, nice! Sorry for the minor regression! 😅

**Comment by maxbrunet** [comment]
No worries, thank you!
