### ISSUE TITLE
Key mapping issues

### ISSUE THREAD

**Issue by DeeGeeMan** [AstroNvim/AstroNvim#1154]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.3.0

### Neovim version (>= 0.8)

NVIM v0.8.0

### Operating system/version

macOS 12.6

### Describe the bug

I am unable to remap the default `<leader>d` in my `mappings.lua` file when calling `vim.keymap.set`.  

### Steps to Reproduce

mapping the following in your `mappings.lua` file...

```
local map = vim.keymap.set
map("n", "<leader>d", '"*d', { desc = "Delete to clipboard" })
```

### Expected behavior

I should see my new mapping when displaying the list of actions by hitting the `<leader>` key.  However, it works if I call ` vim.api.nvim_set_keymap("n", "<leader>d", '"*d', { desc = "Delete to clipboard" })`.   

It looks like this is only a problem when remapping existing keys in AstroVim via `vim.keymap.set`.

**Comment by DeeGeeMan** [comment]
I've misspoke, `vim.api.nvim_set_keymap` doesn't work either. ☹️

**Comment by mehalter** [comment]
Please check the documentation on this: https://astronvim.github.io/Configuration/basic_configuration

Notice the mappings table, your `mappings.lua` file should look something like this:

```lua
return {
  n = {
    ["<leader>d"] = { "*d", desc = "Delete to clipboard" },
  }
}
```

This will overwrite the internal mapping before it ever gets set :)

**Comment by DeeGeeMan** [comment]
I saw one of the examples in the[ Black Belt Example User Configs](https://astronvim.github.io/Recipes/black_belt) from **thieung**.

**Comment by mehalter** [comment]
@DeeGeeMan @thieung is doing something different. They are calling that from their `polish` function in the file `init.lua`

**Comment by DeeGeeMan** [comment]
Ok, I will do the same...thanks!

**Comment by mehalter** [comment]
I'm not sure if I would recommend this because it will mean that `user.mappings` will be ran twice. Once when we do the mapping stuff and it will provide no overriding, then the mappings will get overridden by the default mappings and then it will run again when the polish function goes and it will set the mappings again. This is optimizing a pretty minute amount of time, but it will be redundant

**Comment by DeeGeeMan** [comment]
Still doesn't work. 😞

**Comment by mehalter** [comment]
:( if you can share your user configuration I can take a look and see where things are going wrong next week and help out :) is there a reason you don't want to use the `mappings.lua` table structure? This will be the most performant and optimized way to change and add mappings

**Comment by DeeGeeMan** [comment]
I can if can use a `for..loop` in a function to replace the following...
```	["<leader>1"] = { "<cmd>BufferLineGoToBuffer 1<cr>", desc = "Select butter 1" },
	["<leader>2"] = { "<cmd>BufferLineGoToBuffer 2<cr>", desc = "Select butter 2" },
	["<leader>3"] = { "<cmd>BufferLineGoToBuffer 3<cr>", desc = "Select butter 3" },
	["<leader>4"] = { "<cmd>BufferLineGoToBuffer 4<cr>", desc = "Select butter 4" },
	["<leader>5"] = { "<cmd>BufferLineGoToBuffer 5<cr>", desc = "Select butter 5" },
	["<leader>6"] = { "<cmd>BufferLineGoToBuffer 6<cr>", desc = "Select butter 6" },
	["<leader>7"] = { "<cmd>BufferLineGoToBuffer 7<cr>", desc = "Select butter 7" },
	["<leader>8"] = { "<cmd>BufferLineGoToBuffer 8<cr>", desc = "Select butter 8" },
	["<leader>9"] = { "<cmd>BufferLineGoToBuffer 9<cr>", desc = "Select butter 9" },
```

**Comment by mehalter** [comment]
Yeah you can :) I can help you out on Monday. I'm heading out of town today for the weekend and will not be by a computer. What you are looking for is this: https://astronvim.github.io/Configuration/override_formats#override-function

**Comment by DeeGeeMan** [comment]
I also like defining the same mapping in tow different modes...

Example:
`map({ "n", "v" }, "j", "gj", { desc = "Nagivate down" })`

**Comment by DeeGeeMan** [comment]
To get it working in the `polish.lua` file, I have to define the mapping directly...

Works:
```
local map = vim.keymap.set

return function()
	map("n", "<leader>d", '"*d', { desc = "Delete to clipboard" })
	require("user.file-types")
end
```

Doesn't work:
```
return function()
	require("user.mappings")
	require("user.file-types")
end
```

**Comment by DeeGeeMan** [comment]
I just realized I can use `[""]` for `map` mode.

```
...
  [""] = {
    [";"] = { ":" },
    ["jh"] = { "^", desc = "First non-blank line" },
    ["jl"] = { "g_", desc = "End of line" },
  },
}
```

**Comment by DeeGeeMan** [comment]
Here is my attempt to get it working as a function that works...
```
return {
	n = (function()
		local n = {
			-- Delete/Cut actions
			d = { '"_d', desc = "Delete with no register" },
			x = { '"_x', desc = "Cut with no register" },
			D = { '"_D', desc = "Delete line with no register" },
			...
		}
		--Tab navigation
		local index = 1
		for i = 1, 9 do
			n["<leader>" .. i] = { "<cmd>BufferLineGoToBuffer " .. i .. "<cr>", desc = "Select butter " .. i }
			index = index + i
		end
		return n
	end)(),
```

**Comment by ywpkwon** [comment]
@mehalter I wanted to override `H` and `L` as below. (origianally `previous buffer` and `next buffer`, respectively.). But I think there's randomness which one runs later.

When I launch `nvim` one time, `H` and `L` works as I want. Next time, `H` and `L` shows original behavior. I also verified one time `H` does `previous buffer`, but `L` does `end of line`. ...:open_mouth: !?

I'm not sure how much this is relevant to the original posting. Can you check regard to this matter?
 
```lua
  mappings = {
    n = {
      -- second key is the lefthand side of the map
      -- mappings seen under group name "Buffer"
      ["<leader>bb"] = { "<cmd>tabnew<cr>", desc = "New tab" },
      ["<leader>bc"] = { "<cmd>BufferLinePickClose<cr>", desc = "Pick to close" },
      ["<leader>bj"] = { "<cmd>BufferLinePick<cr>", desc = "Pick to jump" },
      ["<leader>bt"] = { "<cmd>BufferLineSortByTabs<cr>", desc = "Sort by tabs" },

      [";"] = { ":", desc = ":" }, -- let's try to switch ; and :
      [":"] = { ";", desc = ";" }, -- let's try to switch ; and :
      ["H"] = { "^", desc = "beginning of line" },
      ["L"] = { "$", desc = "end of line" },
    },
    v = {
      [";"] = { ":", desc = ":" }, -- let's try to switch ; and :
      [":"] = { ";", desc = ";" }, -- let's try to switch ; and :
      ["H"] = { "^", desc = "beginning of line" },
      ["L"] = { "$", desc = "end of line" },
    },
```
