### ISSUE TITLE
windows run error after update

### ISSUE THREAD

**Issue by acfuns** [AstroNvim/AstroNvim#1156]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.4.2

### Neovim version (>= 0.8)

NVIM 0.8 stable

### Operating system/version

windows11 22H

### Describe the bug

![image](https://user-images.githubusercontent.com/55129666/197331402-9cf34945-7459-468d-85d6-b616bb7c7219.png)

### Steps to Reproduce

1. git download on windows11
2. <leader>+ff

### Expected behavior

no error

### Screenshots

![image](https://user-images.githubusercontent.com/55129666/197331402-9cf34945-7459-468d-85d6-b616bb7c7219.png)

**Comment by acfuns** [comment]
But I use *make* build telescope-fzf-nalive.nvim, it works. I think *cmake* build maybe error.

**Comment by mehalter** [comment]
Thanks for reporting this, I have resolved this in the latest nightly :)
