### ISSUE TITLE
how to highlight cursorline with desired transparent color?

### ISSUE THREAD

**Issue by ttnsgn** [AstroNvim/AstroNvim#1157]
### Question

Wanna to set highlighted cursorline with desired color (transparent color will be nicer) here is my so not-worked user config 

> return {
>   default_theme = {
>     highlights = function(hi)
>       local C = require "default_theme.colors"
>       hi.Normal = { bg = C.none, ctermbg = C.none }
>       hi.CursorColumn = { cterm = {}, ctermbg = C.none, ctermfg = C.none }
>       hi.CursorLine = { cterm = {}, ctermbg = C.grey, ctermfg = C.none }
>       hi.CursorLineNr = { cterm = {}, ctermbg = C.none, ctermfg = C.none }
>       hi.LineNr = {}
>       hi.SignColumn = {}
>       hi.StatusLine = {}
>       hi.NeoTreeNormal = { bg = C.none, ctermbg = C.none }
>       hi.NeoTreeNormalNC = { bg = C.none, ctermbg = C.none }
>       return hi
>     end,
>   },
> }
> 

I got error 
`.config/nvim/lua/core/bootstrap.lua:4: Vim:E5113: Error while calling lua chunk: /home/tatan/.config/nvim/lua/default_theme/init.lua:45: '#5c6370
' is not a valid color`

**Comment by kabinspace** [comment]
which AstroNvim version are you on? your `user/init.lua` API looks outdated

**Comment by ttnsgn** [comment]
> which AstroNvim version are you on? your `user/init.lua` API looks outdated

version v2.4.2

**Comment by kabinspace** [comment]
have you checked the latest `user/init.lua`? changing theme is different in the updated `user/init.lua`

**Comment by mehalter** [comment]
@kabinspace the API the user is using is still valid and there are reasons to use one or the other. I won't be at a computer until tomorrow, but just heads up the `default_theme.highlights` table is totally valid.

**Comment by kabinspace** [comment]
@mehalter ahh, i see. i thought it got deprecated with 2.0

**Comment by kabinspace** [comment]
@ttnsgn could you try this instead
```lua
return {
	default_theme = {
		highlights = function(hi)
			local C = require("default_theme.colors")
			hi.Normal = { fg = C.none, bg = C.none }
			hi.CursorColumn = { fg = C.none, bg = C.none }
			hi.CursorLine = { fg = C.none, bg = C.none }
			hi.CursorLineNr = { fg = C.none, bg = C.none }
			hi.LineNr = { fg = C.none, bg = C.none }
			hi.SignColumn = { fg = C.none, bg = C.none }
			hi.StatusLine = { fg = C.none, bg = C.none }
			hi.NeoTreeNormal = { fg = C.none, bg = C.none }
			hi.NeoTreeNormalNC = { fg = C.none, bg = C.none }
			return hi
		end,
	},
}
```

**Comment by mehalter** [comment]
yeah `ctermfg` and `ctermbg` is  a bit different in colors than `fg` and `bg`. Also this is a duplicate I believe of #8. I am going to close this in favor of keeping conversation together for the same issue. Please check out that issue and see if it resolves your problems. If not, feel free to comment on that issue for discussion
