### ISSUE TITLE
Failed to load parser when using eslint_d after updating Astronvim

### ISSUE THREAD

**Issue by PaulKushch** [AstroNvim/AstroNvim#1160]
### Question

I just updated stable version to `v.2.4.2`.

And I started getting this error for all imports with `eslint_d` version `12.2.1` (in tsx/js files):

![image](https://user-images.githubusercontent.com/5386035/197363733-0dd1829c-86fe-40a8-9ac0-3d6f1a15b334.png)

Anyone else having the same issue and maybe some solution?

Best regards

**Comment by mehalter** [comment]
I haven't run into this before and can't seem to replicate it. It might be a good idea to join the AstroNvim discord to see if other people in the community have had similar problems like this.
