### ISSUE TITLE
Terraform hcl files

### ISSUE THREAD

**Issue by queue-tip** [AstroNvim/AstroNvim#1162]
### Question

What enables treesitter for a given file? It's probably a coincidence, but ever since the update to the highlight groups in `nvim-treesitter` `terraform` files no longer have syntax highlighting. Treesitter isn't even enabled for those buffers.

Reinstalling the `hcl` parser for treesitter while I'm in the buffer immediately starts treesitter as expected, and then things look fine. Can anyone give me an idea of where I should start looking for possible config problems?

**Comment by mehalter** [comment]
@queue-tip could you try refreshing your installation files and reinstalling everything to see if it could be something in your cache?

```sh
mv ~/.local/share/nvim ~/.local/share/nvim.bak
mv ~/.cache/nvim ~/.cache/nvim.bak
nvim +PackerSync
```

**Comment by queue-tip** [comment]
That's a great suggestion. It came back when I refreshed the install. Then I removed my user settings, refreshed, and added the hcl parser to treesitter and it works as expected.

It's definitely an issue in a recent change I made to my config. I'll find it. Thanks for the tip!
