### ISSUE TITLE
how to install/uninstall plugins?

### ISSUE THREAD

**Issue by leozhang1** [AstroNvim/AstroNvim#1164]
### Question

astrovim provides a bunch of plugins that are really nice for getting me started but can you please show me step by step by how to add and remove plugins? I don't have a user folder. I have a user_example folder. I have no clue what to do so please inform me as if I am in a complete newbie.

any help is appreciated.

**Comment by mehalter** [comment]
Have you had a chance to read through the documentation? :)

https://astronvim.github.io/Configuration/manage_user_config

**Comment by kabinspace** [comment]
To install plugins you have to add it in [this](https://github.com/AstroNvim/AstroNvim/blob/5288bad46858f15f2290aeb3d09c8bd8e58b7882/lua/user_example/init.lua#L221) section. which would be like `{ "andweeb/presence.nvim" }` and do `:PackerInstall` and to uninstall the plugin you can remove the line that you just added and do `:PackerClean`. I would strongly recommend to learn some basic lua else it's going to be very hard to operate astronvim.

**Comment by leozhang1** [comment]
> To install plugins you have to add it in [this](https://github.com/AstroNvim/AstroNvim/blob/5288bad46858f15f2290aeb3d09c8bd8e58b7882/lua/user_example/init.lua#L221) section. which would be like `{ "andweeb/presence.nvim" }` and do `:PackerInstall` and to uninstall the plugin you can remove the line that you just added and do `:PackerClean`. I would strongly recommend to learn some basic lua else it's going to be very hard to operate astronvim.

Okay thanks for the tip. I made a folder called user copied from user_example like the documentation said. I was able to set relative number to false and it worked. No more relative numbers. Okay. I will look into learning some lua.

**Comment by leozhang1** [comment]
> Have you had a chance to read through the documentation? :)
> 
> https://astronvim.github.io/Configuration/manage_user_config

Thank you. Just did!

**Comment by dimitarvp** [comment]
Reading those docs and various GitHub issues and PRs didn't help me with Selene. I uninstall it and it gets installed right back after I restart my Neovim. :(

Any idea how do we make sure a plugin stays uninstalled?
