### ISSUE TITLE
Issues loading descriptions for Comment.nvim

### ISSUE THREAD

**Issue by simgre** [AstroNvim/AstroNvim#1166]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.4.2

### Neovim version (>= 0.8)

NVIM 0.8.0

### Operating system/version

EndeavourOS Linux

### Describe the bug

The description for Comment.nvim on a fresh install is not loading until the keys are pressed for the first time.

Picture showing the issue as well as mappings.lua:
![2022-10-23T19:59:21,316843651+02:00](https://user-images.githubusercontent.com/18512096/197408068-7ec8d548-871b-4f5f-b73d-6998a57cfeed.png)

### Steps to Reproduce

1. Fresh install AstroNvim
2. Press g

### Expected behavior

Tooltips for all the commands showing up.

**Comment by mehalter** [comment]
Resolved this in the latest `nightly` :)

**Comment by mehalter** [comment]
Should be released to the stable channel sometime this week as we wrap up other stuff that needs to be pushed out as well. Thanks for reporting this!

**Comment by simgre** [comment]
Lovely! Thank you for maintaining this project!
