### ISSUE TITLE
:vsplit crashes nvim

### ISSUE THREAD

**Issue by TheButlah** [AstroNvim/AstroNvim#1169]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.4.2

### Neovim version (>= 0.8)

NVIM v0.8.0

### Operating system/version

macOS 12.6

### Describe the bug

Attempting to `:vsplit` when nerd-tree is the only window causes nvim to crash

### Steps to Reproduce

1. Open `nvim`
2. Go to some directory, ex: `:e ~/.config`. This opens neo-tree in the full window.
3. Try to do a vertical split: `:vsplit`
4. nvim exits unexpectedly

### Expected behavior

`neo-tree` should split vertically, or maybe nothing should happen - but it should not just exit.

### Screenshots

https://user-images.githubusercontent.com/6969415/197540950-29032742-cf55-4420-a763-8410e68a6222.mov

**Comment by mehalter** [comment]
This is coming from an autocmd that we have that tries to auto quit if the last window is only sidebars. Most users want this behavior because they don't treat `neo-tree` and `aerial` as their own windows, but "temp" windows. This can be disabled in your user config by removing the autocommand:

```lua
return {
  polish = function()
    vim.api.nvim_del_augroup_by_name("auto_quit")
  end
}
```

Hopefully this helps point you in the right direction :)

**Comment by TheButlah** [comment]
> they don't treat neo-tree and aerial as their own windows, but "temp" windows

Makes sense, I think!

> This is coming from an autocmd that we have that tries to auto quit if the last window is only sidebars

This I don't understand - when doing a vsplit surely there should be a new window now. So why would the auto quit happen? There would be 2 windows - one is a "temp window" (the file tree) and one is a real window.

**Comment by mehalter** [comment]
@TheButlah I have improved this auto command to resolve this issue on `nightly` :) Should be merged to stable sometime this week!

**Comment by TheButlah** [comment]
(commit is 585a8b52903cedd1bfc76c832cbb07042181d497)
