### ISSUE TITLE
[Curiosity] Redefine Emmet-vim trigger key (and similar things)

### ISSUE THREAD

**Issue by maxdevjs** [AstroNvim/AstroNvim#1172]
### Question

> Testing `AstroNvim` and looks great :smile: 

I did redefine the [Emmet-vim](https://github.com/mattn/emmet-vim) trigger key 
adding to `$XDG_CONFIG_HOME/astronvim/lua/user/init.lua`:

```lua
  polish = function()
    -- Redefine Emmet-vim trigger key
    vim.g.user_emmet_leader_key = '<C-E>'
```
Is this the correct way to do it? If so, there are alternatives that I should be aware of?

**Comment by mehalter** [comment]
That is definitely a completely valid way to do this. You can also do this with the `options` table:

```lua
return {
  options = {
    g = {
      user_emmet_leader_key = '<C-E>'
    }
  }
}
```
