### ISSUE TITLE
Select first item on autocompletion list

### ISSUE THREAD

**Issue by LuisA92** [AstroNvim/AstroNvim#1173]
### Question

Hello, 

I just installed AstroNvim and I noticed that the first word on the autocompletion list is not automatically selected. I have to tab to the item and then press enter to select it. 

Is there any way to change this behavior? 

I tried changing the behavior by using `completeopt = {"menu","noinsert"}` and `preselect = cmp.PreslectMode.None` but the behavior remains unchanged.

**Comment by kabinspace** [comment]
This would automatically select your first item from the menu
```lua
return {
  completion = {
    completeopt = {
    "menu, menuone, noinsert"
    },
  },
}
```

**Comment by LuisA92** [comment]
@kabinspace I found 'completeopt` under `options.lua` and I tried using 'completeopt = "menu,menuone,noinsert"` but it did not work. 

I added  

``` lua
cmp.setup {
  completion = {
    completeopt = 'menu,menuone,noinsert'
  }
}
```
to `cmp.lua` and now the first item is highlighted.

**Comment by kabinspace** [comment]
yes, you were supposed to add that for `cmp` not for `options`

**Comment by LuisA92** [comment]
@kabinspace Great, thank you!
