### ISSUE TITLE
How to disable friendly-snippets

### ISSUE THREAD

**Issue by rokonio** [AstroNvim/AstroNvim#1175]
### Question

When disabling friendly-snippets, LuaSnip craches:
![image](https://user-images.githubusercontent.com/61879190/197816674-e43d7556-b845-4537-a9e8-578afb1f6fd3.png)

**Comment by mehalter** [comment]
You will want to make sure to disable the lazy loading that we have in `LuaSnip`:

```lua
return {
  plugins = {
    init = {
      ["rafamadriz/friendly-snippets"] = { disable = true },
      ["L3MON4D3/LuaSnip"] = { wants = {} },
    },
  },
}
```
