### ISSUE TITLE
Bindings for moving between git, buf, and files in explorer? #328

### ISSUE THREAD

**Issue by patrickphat** [AstroNvim/AstroNvim#1179]
### Question

<img width="287" alt="image" src="https://user-images.githubusercontent.com/45748186/197872035-24503ee0-35e3-418a-bf7e-8fbae9d4a0d5.png">
What are the shortcuts to move between "files", "git" , and "buf" in explorer? I don't seem to find where the key bindings for this set up

Thanks guys!

**Comment by mehalter** [comment]
Neo-tree has a default set of bindings. You can check them in their documentation or `?` key in the tree. The binding you are link for us `>` and `<`
