### ISSUE TITLE
Deprecated configuration option in treesitter

### ISSUE THREAD

**Issue by kunzaatko** [AstroNvim/AstroNvim#1180]
### Question

In `configs/treesitter.lua`, there is a setting  `autopairs = { enable = true },`. Is this some kind of relict of some old configuration? I didn't find anything about this setting in the treesitter help and nvim-autopairs plugin.

**Comment by mehalter** [comment]
Thanks for pointing this out! It looks like it was deprecated at some point. I made a push to `nightly` that removes this :)

**Comment by kunzaatko** [comment]
Great, thanks for the clarification!
