### ISSUE TITLE
how to change theme to astrovim

### ISSUE THREAD

**Issue by leozhang1** [AstroNvim/AstroNvim#1182]
### Question

in ~/.config/nvim/lua/user/init.lua, theres a colorscheme key/value pair, but I am not sure what themes are available out of the box and how to add new themes to astrovim. The docs aren't clear about this :https://astronvim.github.io/Recipes/colorscheme

Also please don't close my issue when I still need help. Keep it open. I will close it. Thanks.

**Comment by mehalter** [comment]
The only theme out of the box is the default theme. Any other theme will need to be installed as a plugin in the `plugins.init` table as shown in the docs. And the value is defined by that plugin/theme.

**Comment by kabinspace** [comment]
[docs](https://astronvim.github.io/Recipes/colorscheme) clearly show how to add a new theme. In this case, the doc is showing how to install and use [catpuccin](https://github.com/catppuccin/nvim) theme. And as for the out-of-the-box theme, there is only one theme which is called `default_theme` based on onedark color palette.

**Comment by leozhang1** [comment]
okay thanks everyone. I will check it out and play around with it.
