### ISSUE TITLE
remap with nowait still wait for timeoutlen.

### ISSUE THREAD

**Issue by nikolasetiawan** [AstroNvim/AstroNvim#1190]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.4.2

### Neovim version (>= 0.8)

0.8.0

### Operating system/version

macOS 12.6.1

### Describe the bug

Not entirely sure if this issue can be fixed in AstroNvim since it might be caused by some of the default plugins. But, when a new keymap with nowait is set, the keypress still has a delay of timeoutlen.

My initial guess is that it is related to which-key bug: https://github.com/folke/which-key.nvim/issues/312

but I tried to disable which-key by setting
```lua
                ["which-key"] = {
                        disable = true
                },
```
in the plugin table. But the behavior is still there.

I'm quite stuck and am hoping that you might be able to shed a light 🙏.

Feel free to close this thread if you think that it has nothing to do with AstroNvim.

### Steps to Reproduce

1. Fresh installation Astronvim
2. create mappings.lua
```lua
return {
  n = {
    ["]"] = { "<cmd>BufferLineCycleNext<cr>", desc = "Go to next tab", silent = true, nowait = true },
  }
}
```
3. press ]

OR

1. Fresh installation Astronvim
2. Enter nvim, :nnoremap <nowait> ] <cmd>BufferLineCycleNext<cr>
3. press ]

### Expected behavior

nowait respected

**Comment by mehalter** [comment]
Hm, this does look like  a bug with `which-key` which sadly we won't be able to resolve here. One thing I can point you in the direction in is that when you go to disable `which-key` you are disabling the plugin, so you need to use the full definition:

```lua
  ["folke/which-key.nvim"] = { disable = true }
```

**Comment by nikolasetiawan** [comment]
Alright, thank you. Unfortunately disabling which key does not fix it for some reason. But I'll try to find some other workarounds.
