### ISSUE TITLE
Intellisense problem with C based project (clangd help)

### ISSUE THREAD

**Issue by ASoldo** [AstroNvim/AstroNvim#1191]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

Version: v2.4.2 

### Neovim version (>= 0.8)

NVIM v0.8.0-1210-gd367ed9b2 Build type: Release LuaJIT 2.1.0-beta3 Compiled by runner@fv-az505-656

### Operating system/version

Linux Mint 20.3 Cinnamon

### Describe the bug

Hi, I started working with some C based project and when I clone the repo it has a bunch of warnings and errors. I have installed clangd for TS and it works fine, but that community told me that I need to configure my clangd lsp to include this 
```
root_dir = root_pattern("compile_commands.json", "compile_flags.txt", ".git"),
```
but I'm not sure where or how to setup clangd options. I am able to build the project and it works fine, but I'm unable to work with it.
Can someone help me with this?

![image](https://user-images.githubusercontent.com/1175537/198156486-c807cc85-595e-4f6e-92d2-a36fbbf1bb0c.png)
This is how it looks like. Thank you!

### Steps to Reproduce

1. clone repository - https://github.com/flipperdevices/flipperzero-firmware
2. open any .c file with nvim (astro nvim)

### Expected behavior

Open any .c file in https://github.com/flipperdevices/flipperzero-firmware repo with nvim (astro nvim) without errors (intellisense warnings and errors)

**Comment by mehalter** [comment]
You could also ask on r/neovim, but you just need to make sure  to ask in terms of configuring `clangd` and not in terms of "configuring clangd in AstroNvim" because people tend to get annoyed when they think they are debugging problems in a preconfiguration even if it isn't one.

**Comment by mehalter** [comment]
It looks like this reddit thread is a continuation of this and has gotten some much better answers than I can provide: https://www.reddit.com/r/neovim/comments/yepjau/astronvim_c_based_project_lsp_issue_clangdhelp/

**Comment by ASoldo** [comment]
That's me! :D but don't worry I found your answer useful.
