### ISSUE TITLE
C-* shortcuts on tmux

### ISSUE THREAD

**Issue by Rawnly** [AstroNvim/AstroNvim#1195]
### Question

Hello, I recently switched from iTerm2 to Alacritty + tmux setup, but I lost some keybindings somehow, `C-'`and `C-^` aren't recognized by neovim anymore. Initially I thought it was an Alacritty problem, but with iTerm + tmux is the same. 

I tried a workaround adding the following to `~/.tmux.conf`
```conf
bind-key -n "C-'" send-key "C-'"
```

but isn't recognized at all :/
### Versions
- neovim 0.8 
- astronvim 2.0

**Comment by mehalter** [comment]
@Rawnly what is the value of $TERM environment variable when you start tmux? This is probably related to your $TERM variable and how that sets the current terminal capabilities. Would be my guess at least. This would probably be a better question to ask on the tmux repo

**Comment by Rawnly** [comment]
It's `screen-256color` yeah maybe is more a tmux related issue 😅

**Comment by mehalter** [comment]
I can take a look at the `screen-256color` term capabilities later today, but I'm pretty sure that will probably be the culprit

**Comment by Rawnly** [comment]
Yeah i'm pretty sure is a conf problem, anyway setting `xterm-256color` seems to be the same 🙃

**Comment by mehalter** [comment]
I checked and I am able to replicate that `tmux` is not registering/detecting `ctrl-'`, I'm not sure how to change this or if this is just a limitation of `tmux` in general. I am going to go ahead and close this since it is separate from AstroNvim.
