### ISSUE TITLE
How to include stuff from .vimrc?

### ISSUE THREAD

**Issue by ipsod** [AstroNvim/AstroNvim#1196]
### Question

Hi.  I'm trying to switch to using AstroNvim, but I keep running into things that I already have working in my old .vimrc, and I don't really have time to rewrite the whole thing in Lua right now.

I don't understand vimscript or Lua very well.  Is there a recommended way to include parts of my .vimrc to make the transition easier?

**Comment by mehalter** [comment]
You could just put the contents of your `.vimrc` into your `user/init.lua` file in the `polish` function that runs last. You basically just want to add a `vim.cmd` block in the function. Something like this:

```lua
return {
  polish = function()
    vim.cmd [[
        set spell
        set number
    ]]
  end,
}
```

**Comment by ipsod** [comment]
Thanks! I'll give it a try.
