### ISSUE TITLE
Lsp timeout

### ISSUE THREAD

**Issue by marciordj** [AstroNvim/AstroNvim#1197]
### Question

![image](https://user-images.githubusercontent.com/54960643/198457028-898fb19a-96c5-4b39-953d-66c933619b73.png)

I'm having this problem with lsp, I read about setting the timeout to 5000 that would work, but it's slow to save. Is there any alternative other than increasing the timeout time?

**Comment by johnsiras** [comment]
I have the same problem here but the warning will also remove after a few ms and saving it again.

**Comment by mehalter** [comment]
@marciordj hm I don't think there is another option here. If your language server is slow at formatting you might want to disable formatting on save and just format with `<leader>lf`. That way the slow formatting of the LSP doesn't slow down your saving

**Comment by marciordj** [comment]
> @marciordj hm I don't think there is another option here. If your language server is slow at formatting you might want to disable formatting on save and just format with `<leader>lf`. That way the slow formatting of the LSP doesn't slow down your saving

i'm using eslint, is he that slow ? is there any alternative for it ?

**Comment by notrodans** [comment]
add `async = true` to formatting config

**Comment by marchellodev** [comment]
@notrodans's solution worked for me!
