### ISSUE TITLE
toggle-term shortcut <C-'> seems to be broken

### ISSUE THREAD

**Issue by ipsod** [AstroNvim/AstroNvim#1200]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

Version: v2.4.2

### Neovim version (>= 0.8)

NVIM v0.8.0-1210-gd367ed9b2

### Operating system/version

Linux Mint 20.2

### Describe the bug

Toggle term shortcuts for n=`<C-'>` and t=`<C-'>` don't work for me.  n=`<C-'>` shows up in keymap search for "toggleterm", and the `<F7>` shortcut works both in normal and terminal mode.

When I push `<C-'>`, it behaves as though I've only pushed `'` (launches a list of bookmarks).

### Steps to Reproduce

hit `<C-'>` in normal mode

### Expected behavior

toggle term launches

### Additional Context

my init.lua:

        -- UFO setup
        -- local ftMap = {
        --         python = 'treesitter',
        -- }
        -- require('ufo').setup({
        --         provider_selector = function(bufnr, filetype, buftype)
        --                 return ftMap[filetype]
        --         end
        -- })
        -- Option 2: nvim lsp as LSP client
        -- Tell the server the capability of foldingRange,
        -- Neovim hasn't added foldingRange to default capabilities, users must add it manually
        local capabilities = vim.lsp.protocol.make_client_capabilities()
        capabilities.textDocument.foldingRange = {
                dynamicRegistration = false,
                lineFoldingOnly = true
        }
        local language_servers = {} -- like {'gopls', 'clangd'}
        for _, ls in ipairs(language_servers) do
                require('lspconfig')[ls].setup({
                        capabilities = capabilities,
                        other_fields = ...
                })
        end
        require('ufo').setup()
        --

        --              AstroNvim Configuration Table
        -- All configuration changes should go inside of the table below

        -- You can think of a Lua "table" as a dictionary like data structure the
        -- normal format is "key = value". These also handle array like data structures
        -- where a value with no key simply has an implicit numeric key
        local config = {

                -- Configure AstroNvim updates
                updater = {
                        remote = "origin", -- remote to use
                        channel = "nightly", -- "stable" or "nightly"
                        version = "latest", -- "latest", tag name, or regex search like "v1.*" to only do updates before v2 (STABLE ONLY)
                        branch = "main", -- branch name (NIGHTLY ONLY)
                        commit = nil, -- commit hash (NIGHTLY ONLY)
                        pin_plugins = nil, -- nil, true, false (nil will pin plugins on stable only)
                        skip_prompts = false, -- skip prompts about breaking changes
                        show_changelog = true, -- show the changelog after performing an update
                        auto_reload = false, -- automatically reload and sync packer after a successful update
                        auto_quit = false, -- automatically quit the current session after a successful update
                        -- remotes = { -- easily add new remotes to track
                        --   ["remote_name"] = "https://remote_url.come/repo.git", -- full remote url
                        --   ["remote2"] = "github_user/repo", -- GitHub user/repo shortcut,
                        --   ["remote3"] = "github_user", -- GitHub user assume AstroNvim fork
                        -- },
                },

                -- Set colorscheme to use
                colorscheme = "default_theme",

                -- Add highlight groups in any theme
                highlights = {
                        -- init = { -- this table overrides highlights in all themes
                        --   Normal = { bg = "#000000" },
                        -- }
                        -- duskfox = { -- a table of overrides/changes to the duskfox theme
                        --   Normal = { bg = "#000000" },
                        -- },
                },

                -- set vim options here (vim.<first_key>.<second_key> =  value)
                options = {
                        opt = {
                                -- set to true or false etc.
                                relativenumber = true, -- sets vim.opt.relativenumber
                                number = true, -- sets vim.opt.number
                                spell = false, -- sets vim.opt.spell
                                signcolumn = "auto", -- sets vim.opt.signcolumn to auto
                                wrap = false, -- sets vim.opt.wrap

                                foldenable = false,
                                foldexpr = "nvim_treesitter#foldexpr()", -- set Treesitter based folding
                                foldmethod = "expr",
                        },
                        g = {
                                mapleader = " ", -- sets vim.g.mapleader
                                autoformat_enabled = true, -- enable or disable auto formatting at start (lsp.formatting.format_on_save must be enabled)
                                cmp_enabled = true, -- enable completion at start
                                autopairs_enabled = true, -- enable autopairs at start
                                diagnostics_enabled = true, -- enable diagnostics at start
                                status_diagnostics_enabled = true, -- enable diagnostics in statusline
                                icons_enabled = true, -- disable icons in the UI (disable if no nerd font is available, requires :PackerSync after changing)
                        },
                },
                -- If you need more control, you can use the function()...end notation
                -- options = function(local_vim)
                --   local_vim.opt.relativenumber = true
                --   local_vim.g.mapleader = " "
                --   local_vim.opt.whichwrap = vim.opt.whichwrap - { 'b', 's' } -- removing option from list
                --   local_vim.opt.shortmess = vim.opt.shortmess + { I = true } -- add to option list
                --
                --   return local_vim
                -- end,

                -- Set dashboard header
                header = {
                        " █████  ███████ ████████ ██████   ██████",
                        "██   ██ ██         ██    ██   ██ ██    ██",
                        "███████ ███████    ██    ██████  ██    ██",
                        "██   ██      ██    ██    ██   ██ ██    ██",
                        "██   ██ ███████    ██    ██   ██  ██████",
                        " ",
                        "    ███    ██ ██    ██ ██ ███    ███",
                        "    ████   ██ ██    ██ ██ ████  ████",
                        "    ██ ██  ██ ██    ██ ██ ██ ████ ██",
                        "    ██  ██ ██  ██  ██  ██ ██  ██  ██",
                        "    ██   ████   ████   ██ ██      ██",
                },

                -- Default theme configuration
                default_theme = {
                        -- Modify the color palette for the default theme
                        colors = {
                                fg = "#abb2bf",
                                bg = "#1e222a",
                        },
                        highlights = function(hl) -- or a function that returns a new table of colors to set
                                local C = require "default_theme.colors"

                                hl.Normal = { fg = C.fg, bg = C.bg }

                                -- New approach instead of diagnostic_style
                                hl.DiagnosticError.italic = true
                                hl.DiagnosticHint.italic = true
                                hl.DiagnosticInfo.italic = true
                                hl.DiagnosticWarn.italic = true

                                return hl
                        end,
                        -- enable or disable highlighting for extra plugins
                        plugins = {
                                beacon = false,
                                bufferline = true,
                                cmp = true,
                                dashboard = true,
                                highlighturl = true,
                                hop = false,
                                indent_blankline = true,
                                lightspeed = false,
                                ["neo-tree"] = true,
                                notify = true,
                                ["nvim-tree"] = false,
                                ["nvim-web-devicons"] = true,
                                rainbow = true,
                                symbols_outline = false,
                                telescope = true,
                                treesitter = true,
                                vimwiki = false,
                                ["which-key"] = true,
                                aerial = {
                                        close_behavior = "global",
                                        backends = { "lsp" }, -- { "lsp", "treesitter", "markdown" },
                                        min_width = 28,
                                        show_guides = true,
                                        filter_kind = {
                                                "Array",
                                                "Boolean",
                                                "Class",
                                                "Constant",
                                                "Constructor",
                                                "Enum",
                                                "EnumMember",
                                                "Event",
                                                "Field",
                                                "File",
                                                "Function",
                                                "Interface",
                                                "Key",
                                                "Method",
                                                "Module",
                                                "Namespace",
                                                "Null",
                                                "Number",
                                                "Object",
                                                "Operator",
                                                "Package",
                                                "Property",
                                                "String",
                                                "Struct",
                                                "TypeParameter",
                                                "Variable",
                                        },
                                        icons = {
                                                Array = "",
                                                Boolean = "⊨",
                                                Class = "",
                                                Constant = "",
                                                Constructor = "",
                                                Key = "",
                                                Function = "",
                                                Method = "ƒ",
                                                Namespace = "",
                                                Null = "NULL",
                                                Number = "#",
                                                Object = "⦿",
                                                Property = "",
                                                TypeParameter = "𝙏",
                                                Variable = "",
                                                Enum = "ℰ",
                                                Package = "",
                                                EnumMember = "",
                                                File = "",
                                                Module = "",
                                                Field = "",
                                                Interface = "ﰮ",
                                                String = "𝓐",
                                                Struct = "𝓢",
                                                Event = "",
                                                Operator = "+",
                                        },
                                        guides = {
                                                mid_item = "├ ",
                                                last_item = "└ ",
                                                nested_top = "│ ",
                                                whitespace = "  ",
                                        },
                                        on_attach = function(bufnr)
                                                -- Jump forwards/backwards with '{' and '}'
                                                vim.keymap.set("n", "{", "<cmd>AerialPrev<cr>",
                                                        { buffer = bufnr, desc = "Jump backwards in Aerial" })
                                                vim.keymap.set("n", "}", "<cmd>AerialNext<cr>",
                                                        { buffer = bufnr, desc = "Jump forwards in Aerial" })
                                                -- Jump up the tree with '[[' or ']]'
                                                vim.keymap.set("n", "[[", "<cmd>AerialPrevUp<cr>",
                                                        { buffer = bufnr, desc = "Jump up and backwards in Aerial" })
                                                vim.keymap.set("n", "]]", "<cmd>AerialNextUp<cr>",
                                                        { buffer = bufnr, desc = "Jump up and forwards in Aerial" })
                                        end,
                                },
                        },
                },

                -- Diagnostics configuration (for vim.diagnostics.config({...})) when diagnostics are on
                diagnostics = {
                        virtual_text = true,
                        underline = true,
                },

                -- Extend LSP configuration
                lsp = {
                        -- enable servers that you already have installed without mason
                        servers = {
                                -- "pyright"
                        },
                        formatting = {
                                -- control auto formatting on save
                                format_on_save = {
                                        enabled = true, -- enable or disable format on save globally
                                        allow_filetypes = { -- enable format on save for specified filetypes only
                                                -- "go",
                                        },
                                        ignore_filetypes = { -- disable format on save for specified filetypes
                                                -- "python",
                                        },
                                },
                                disabled = { -- disable formatting capabilities for the listed language servers
                                        -- "sumneko_lua",
                                },
                                timeout_ms = 1000, -- default format timeout
                                -- filter = function(client) -- fully override the default formatting function
                                --   return true
                                -- end
                        },
                        -- easily add or disable built in mappings added during LSP attaching
                        mappings = {
                                n = {
                                        -- ["<leader>lf"] = false -- disable formatting keymap
                                },
                        },
                        -- add to the global LSP on_attach function
                        -- on_attach = function(client, bufnr)
                        -- end,

                        -- override the mason server-registration function
                        -- server_registration = function(server, opts)
                        --   require("lspconfig")[server].setup(opts)
                        -- end,

                        -- Add overrides for LSP server settings, the keys are the name of the server
                        ["server-settings"] = {
                                -- example for addings schemas to yamlls
                                -- yamlls = { -- override table for require("lspconfig").yamlls.setup({...})
                                --   settings = {
                                --     yaml = {
                                --       schemas = {
                                --         ["http://json.schemastore.org/github-workflow"] = ".github/workflows/*.{yml,yaml}",
                                --         ["http://json.schemastore.org/github-action"] = ".github/action.{yml,yaml}",
                                --         ["http://json.schemastore.org/ansible-stable-2.9"] = "roles/tasks/*.{yml,yaml}",
                                --       },
                                --     },
                                --   },
                                -- },
                        },
                },

                -- Mapping data with "desc" stored directly by vim.keymap.set().
                --
                -- Please use this mappings table to set keyboard mapping since this is the
                -- lower level configuration and more robust one. (which-key will
                -- automatically pick-up stored data by this setting.)
                mappings = {
                        -- first key is the mode
                        n = {
                                -- second key is the lefthand side of the map
                                -- mappings seen under group name "Buffer"
                                ["<leader>bb"] = { "<cmd>tabnew<cr>", desc = "New tab" },
                                ["<leader>bc"] = { "<cmd>BufferLinePickClose<cr>", desc = "Pick to close" },
                                ["<leader>bj"] = { "<cmd>BufferLinePick<cr>", desc = "Pick to jump" },
                                ["<leader>bt"] = { "<cmd>BufferLineSortByTabs<cr>", desc = "Sort by tabs" },
                                ["<leader>a"] = { "<cmd>AerialToggle<cr>", desc = "Aerial Toggle" },

                                ["<leader>fed"] = { "<cmd>edit /home/zero/.config/nvim/lua/user/init.lua<CR>",
                                        desc = "nvim config" },
                                ["<leader>fez"] = { "<cmd>edit /home/zero/.zshrc<CR>", desc = "zsh config" },
                                ["<A-o>"] = { 'viiy:@"<cr>', desc = "nvim execute indented" },

                                -- quick save
                                -- ["<C-s>"] = { ":w!<cr>", desc = "Save File" },  -- change description but the same command
                        },
                        t = {
                                -- setting a mapping to false will disable it
                                -- ["<esc>"] = false,
                        },
                },

                -- Configure plugins
                plugins = {
                        init = {

                                ["akinsho/bufferline.nvim"] = { disable = true },
                                { "kazhala/close-buffers.nvim" },
                                -- { "stevearc/aerial.nvim" },
                                -- { "Konfekt/FastFold" },
                                -- { "kalekundert/vim-coiled-snake" },
                                -- { "tmhedberg/SimpylFold" },
                                ['kevinhwang91/nvim-ufo'] = { requires = 'kevinhwang91/promise-async' },
                                -- ['nvim-treesitter/nvim-treesitter'] = { run = ':TSUpdate' },

                                -- { "michaeljsmith/vim-indent-object" },
                                -- You can disable default plugins as follows:
                                -- ["goolord/alpha-nvim"] = { disable = true },

                                -- You can also add new plugins here as well:
                                -- Add plugins, the packer syntax without the "use"
                                -- { "andweeb/presence.nvim" },
                                -- {
                                --   "ray-x/lsp_signature.nvim",
                                --   event = "BufRead",
                                --   config = function()
                                --     require("lsp_signature").setup()
                                --   end,
                                -- },

                                -- We also support a key value style plugin definition similar to NvChad:
                                -- ["ray-x/lsp_signature.nvim"] = {
                                --   event = "BufRead",
                                --   config = function()
                                --     require("lsp_signature").setup()
                                --   end,
                                -- },
                        },
                        -- All other entries override the require("<key>").setup({...}) call for default plugins
                        ["null-ls"] = function(config) -- overrides `require("null-ls").setup(config)`
                                -- config variable is the default configuration table for the setup function call
                                -- local null_ls = require "null-ls"

                                -- Check supported formatters and linters
                                -- https://github.com/jose-elias-alvarez/null-ls.nvim/tree/main/lua/null-ls/builtins/formatting
                                -- https://github.com/jose-elias-alvarez/null-ls.nvim/tree/main/lua/null-ls/builtins/diagnostics
                                config.sources = {
                                        -- Set a formatter
                                        -- null_ls.builtins.formatting.stylua,
                                        -- null_ls.builtins.formatting.prettier,
                                }
                                return config -- return final config table
                        end,
                        treesitter = { -- overrides `require("treesitter").setup(...)`
                                -- ensure_installed = { "lua" },
                        },
                        -- use mason-lspconfig to configure LSP installations
                        ["mason-lspconfig"] = { -- overrides `require("mason-lspconfig").setup(...)`
                                -- ensure_installed = { "sumneko_lua" },
                        },
                        -- use mason-null-ls to configure Formatters/Linter installation for null-ls sources
                        ["mason-null-ls"] = { -- overrides `require("mason-null-ls").setup(...)`
                                -- ensure_installed = { "prettier", "stylua" },
                        },
                },

                -- LuaSnip Options
                luasnip = {
                        -- Add paths for including more VS Code style snippets in luasnip
                        vscode_snippet_paths = {},
                        -- Extend filetypes
                        filetype_extend = {
                                -- javascript = { "javascriptreact" },
                        },
                },

                -- CMP Source Priorities
                -- modify here the priorities of default cmp sources
                -- higher value == higher priority
                -- The value can also be set to a boolean for disabling default sources:
                -- false == disabled
                -- true == 1000
                cmp = {
                        source_priority = {
                                nvim_lsp = 1000,
                                luasnip = 750,
                                buffer = 500,
                                path = 250,
                        },
                },

                -- Modify which-key registration (Use this with mappings table in the above.)
                ["which-key"] = {
                        -- Add bindings which show up as group name
                        register = {
                                -- first key is the mode, n == normal mode
                                n = {
                                        -- second key is the prefix, <leader> prefixes
                                        ["<leader>"] = {
                                                -- third key is the key to bring up next level and its displayed
                                                -- group name in which-key top level menu
                                                ["b"] = { name = "Buffer" },
                                        },
                                },
                        },
                },

                -- This function is run last and is a good place to configuring
                -- augroups/autocommands and custom filetypes also this just pure lua so
                -- anything that doesn't fit in the normal config locations above can go here
                polish = function()
                        -- Set up custom filetypes
                        -- vim.filetype.add {
                        --   extension = {
                        --     foo = "fooscript",
                        --   },
                        --   filename = {
                        --     ["Foofile"] = "fooscript",
                        --   },
                        --   pattern = {
                        --     ["~/%.config/foo/.*"] = "fooscript",
                        --   },
                        -- }
                end,
        }

        -- You probably also want to set a keymap to toggle aerial

        return config

**Comment by mehalter** [comment]
What terminal are you using? Have you verified that it supports `C-'` keymap?

**Comment by ipsod** [comment]
I've tried it in `gnome-terminal` and `kitty`.  I didn't think to verify.  Would I do that by hitting `ctrl+v`, then the shortcut, in the terminal?  If so, then no, neither of these seem to support `<c-'>`

**Comment by mehalter** [comment]
Yeah it looks like your terminals probably don't support detecting that key. Not many do, it's a weird legacy terminal compatibility type thing. That's the main reason we set up F7 and put that mainly in the docs since that has full compatibility across terminals. Sadly we can't do much about it :(

**Comment by ipsod** [comment]
Ok.  Which terminal does work?  I'm not too invested in either of these.  Sorry if this is documented - I did try to look, but gave up after several minutes.

**Comment by marchellodev** [comment]
@ipsod I am using [foot](https://codeberg.org/dnkl/foot), it is great, but it's only available on wayland. You can also try wezterm or alacritty, they are great as well.

**Comment by ipsod** [comment]
@marchellodev 

Thank you!  I've switched to wezterm, and like it.  Also, in getting that set up, I found this page, which has a lot more information about all of this:  https://sw.kovidgoyal.net/kitty/keyboard-protocol/

**Comment by SunHuawei** [comment]
The default terminal on Ubuntu 22.04 has the same issue. I probably try wezterm too.

**Comment by archite** [comment]
iterm2 also has this issue but it's not all the time. I've found that leaving the window for a period of time and then coming back, it stops working. Every time I wish I had kept track of what I did. I'll try harder and update thread.

**Comment by ipsod** [comment]
Reopening because of active discussion.  Not sure if that's appropriate.  Feel free to close.

**Comment by mehalter** [comment]
Sure we can leave it open a bit if people want it. I changed it to a question since it's not a bug

**Comment by archite** [comment]
Resizing the terminal window breaks the shortcut every time for me.

**Comment by archite** [comment]
[CSI u](https://iterm2.com/documentation-csiu.html) appears to fix it for me. Checking more.

**Comment by archite** [comment]
This appears to be a togglerterm issue as I can reproduce outside of this framework.

**Comment by archite** [comment]
I'm thinking this might be a nevoim issue. Replacing `<C-'>` with `<C-\\>` does not suffer from this issue. I've found a few issues for neovim which may be related but it's hard to nail down being such an esoteric issue. 

Regardless, this is definitely not an AstroNvim issue.

**Comment by mehalter** [comment]
Yeah @archite this will be something that will boil down to terminal capabilities and compatibilities

**Comment by ipsod** [comment]
@mehalter 

Perhaps worth documenting, though, somewhere on a page about keyboard mapping?  Maybe something like "Different terminal emulators support different keyboard shortcuts, and some are much more robust than the common OS defaults.  Read more here: https://sw.kovidgoyal.net/kitty/keyboard-protocol/ "  (or your preferred source)
