### ISSUE TITLE
External Plugin!

### ISSUE THREAD

**Issue by AlphaVCat** [AstroNvim/AstroNvim#1201]
### Question

Can we use any external Plugin like: `https://github.com/shime/vim-livedown` in AstroNvim, if yes please guide me how? And if not please add this! ;)

**Comment by marchellodev** [comment]
It's quite easy to do - you have to create a config file, add the plugin in the `plugins` section and run `:PackerUpdate`.

It's all in the docs: https://astronvim.github.io/Configuration/manage_user_config

**Comment by AlphaVCat** [comment]
Thank you very much! :)
