### ISSUE TITLE
Confirmation alert after using EasyMotion

### ISSUE THREAD

**Issue by RicardoCMiguel** [AstroNvim/AstroNvim#1207]
### After using EasyMotion, a confirmation prompt appears to make the jump to the selected word

![Captura de tela de 2022-10-29 22-11-58](https://user-images.githubusercontent.com/83841643/198858233-cb8dd2a7-dbee-4108-a75f-2cf72c6f5863.png)

Is there any setting to disable this warning? in the previous version of Astrovim this alert appeared when I deleted a file or tried to exit without saving the changes, after I updated this warning started to appear and ends up being annoying

**Comment by Dominux** [comment]
Same question here

**Comment by mehalter** [comment]
This is because of `cmdheight = 0` and plugins printing to the cmd line. You can fix this by adding back the `cmdheight` if you would like. Not sure if there are other ways to avoid this. 

```lua
return {
  options = {
    opt = {
      cmdheight = 1,
    },
  },
}
```
