### ISSUE TITLE
Mappings for htop and ncdu are wrong

### ISSUE THREAD

**Issue by devdanej** [AstroNvim/AstroNvim#1209]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.4.0

### Neovim version (>= 0.8)

0.8.0

### Operating system/version

macos 12.6

### Describe the bug

The key mappings for htop and ncdu have a typo in the tmux command execution function

```lua
  maps.n["<leader>tu"] = { function() toggle_term_cmd "gdu" end, desc = "ToggleTerm gdu" }
  maps.n["<leader>tt"] = { function() toggle_term_cmd "btm" end, desc = "ToggleTerm btm" }
```
Instead change to:

```lua
	maps.n["<leader>tu"] = {
		function()
			toggle_term_cmd("ncdu")
		end,
		desc = "ToggleTerm ncdu",
	}
	maps.n["<leader>tt"] = {
		function()
			toggle_term_cmd("htop")
		end,
		desc = "ToggleTerm htop",
	}
```

### Steps to Reproduce

1. Install `htop` and `ncdu` on your OS
2. Execute `<leader>tt` to execute `htop`
3. Execute `<leader>tu` to execute `ncdu`

### Expected behavior

When executing
* <leader>tt` -> `htop` should launch within the nvim editor
* `<leader>tu` -> `ncdu` should launch within the nvim editor

**Comment by mehalter** [comment]
These are not typos. Those are the expected terminal applications as indicated by the README, documentation, and the keymap text itself. These were changed in v2 as described in the migration guide because ncdu and htop are not cross platform and these are.
