### ISSUE TITLE
Support for images and pdf

### ISSUE THREAD

**Issue by bihari123** [AstroNvim/AstroNvim#1215]
### Is your feature related to a problem?

Can't see the images and the pdf in nvim

### Describe the new feature

plz add "telescope-media-files.nvim" to let user view images

**Comment by mehalter** [comment]
This can be added in your `user/init.lua` file. I don't think this needs to be upstream into AstroNvim. Here is an example `user/init.lua` file that will add this:

```lua
return {
  plugins = {
    init = {
      ["nvim-telescope/telescope-media-files.nvim"] = {
        after = "telescope.nvim",
        config = function() require("telescope").load_extension "media_files" end,
      },
    },
  },
}
```

**Comment by brioglade** [comment]
It still can't see the images and the pdf in nvim.

**Comment by bihari123** [comment]
Did you do a :Packer Sync?

**Comment by bihari123** [comment]
same here
