### ISSUE TITLE
Color scheme not working properly in Neovim 0.8

### ISSUE THREAD

**Issue by bihari123** [AstroNvim/AstroNvim#1216]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.5.0

### Neovim version (>= 0.8)

0.8

### Operating system/version

debian11

### Describe the bug

default color scheme is not working properly 

### Steps to Reproduce

start nvim and open any file( i am using golang)

### Expected behavior

In earlier versions , we see distinguishing colors for the various components. Like functions and methods. But not now

**Comment by mehalter** [comment]
Can you please share more details? This is not reproducible. Did you upgrade recently to AstroNvim v2 and from Neovim 0.7 -> Neovim 0.8. you might need to clear your data and cache folders and rebuild them:

```sh
mv ~/.local/share/nvim ~/.local/share/nvim.bak
mv ~/.cache/nvim ~/.cache/nvim.bak
nvim +PackerSync
```

**Comment by mehalter** [comment]
Unable to replicate this and haven't heard from the original user. I'll go ahead and close this.
