### ISSUE TITLE
Getting error popup on accessing any file on fresh installation of Astrovim

### ISSUE THREAD

**Issue by ep4sh** [AstroNvim/AstroNvim#1217]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

(shows nothing looks like doesnt work)

### Neovim version (>= 0.8)

0.8

### Operating system/version

macos 12.6

### Describe the bug

I've done with fresh installation, everything was done step by step according to the docs.

On accessing any file I'm getting a strange error:

Text:
```
[null-ls] failed to run generator: ...m/site/pack/packer/opt/null-ls.nvim/lua/null-ls/loop.lua:165: command ec is not executable (make sure it's installed and on your $PATH)
```

btw, I have an issue with icons (they are missing), despite the nerdfonts are installed with brew --cask, but it's another issue.

### Steps to Reproduce

cd /tmp
nvim .

### Expected behavior

No popup, no error

### Screenshots

picture:
<img width="1792" alt="Screenshot 2022-11-01 at 15 09 57" src="https://user-images.githubusercontent.com/19505042/199229885-7012f7db-cbbf-4117-bef0-f4e39ed2490e.png">

**Comment by mehalter** [comment]
I'm  not sure what would be causing this bug. I would recommend reaching out  to the `null-ls` repository (https://github.com/jose-elias-alvarez/null-ls.nvim) and opening up an issue to start debugging where this could be coming from. I did a quick search in their issues and didn't see anything.

Also just a comment on the nerd fonts, I would say to make sure that after you install the nerd font that you want to use you should make sure you are setting the font to actually be used in the terminal emulator that you are using.

**Comment by ep4sh** [comment]
Thank you very much, Micah @mehalter ! I'll try with fonts.
I was able to remove noisy popup, removing the `editorconfig-checker` linter.
