### ISSUE TITLE
Add Aerial toogle  menu 

### ISSUE THREAD

**Issue by pietryszak** [AstroNvim/AstroNvim#1220]
### Describe the new feature

A good idea is to add Aerial toggle like a explorer toogle to menu. Maybe with space  next  a  - like a aerial
![image](https://user-images.githubusercontent.com/45850093/199309731-e16ff88e-f60b-47c8-8443-9383bbfbe78e.png)

**Comment by mehalter** [comment]
This is under `<leader>lS` for the language symbols

![2022-11-01_14:36:08_screenshot](https://user-images.githubusercontent.com/1591837/199311628-0c3b9001-fd7c-4e7d-ad22-d1c42b34a72e.png)

https://astronvim.github.io/Basic%20Usage/mappings#lsp-mappings

**Comment by pietryszak** [comment]
@mehalter I mean AerialOpen command do add it to left of window
![image](https://user-images.githubusercontent.com/45850093/199312290-e2d4d5e9-c126-412c-9475-58fdbb159841.png)

**Comment by mehalter** [comment]
I believe you are pressing `<leader>ls` which will search the document symbols in telescope. It is `<leader>lS` (with a capital) to show the Aerial symbol outline :)

**Comment by mehalter** [comment]
Here is a recording of this: https://asciinema.org/a/sUrz8Z4Z0b1TkWY7AcoPwL6Sh

**Comment by pietryszak** [comment]
> Here is a recording of this: https://asciinema.org/a/sUrz8Z4Z0b1TkWY7AcoPwL6Sh

Yes, true. Thank you for your response. Everything works like I expected. 
BTW, great job :) I switch from vi > vim > neovim > own neovim with plugins > spacevim > lunar vim > astro vim
And I stay because with astro I just add gruvbox theme and all other things Is super :)
Or maybe is same kind to change color sheme to gruvbox without plugin. I need to check :)

**Comment by mehalter** [comment]
Thanks for the kind words! ❤️ Also yeah, for custom colorschemes you need to install them as plugins
