### ISSUE TITLE
TSUpdate requires tree-sitter-cli

### ISSUE THREAD

**Issue by 02strich** [AstroNvim/AstroNvim#1221]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.5.0

### Neovim version (>= 0.8)

v0.8.0

### Operating system/version

macOS 13.0

### Describe the bug

When going through the basic setup section, the `TSInstall` command requires the tree-sitter-cli to be installed to run, which is not mentioned in the readme.

### Steps to Reproduce

1. Fresh install of NeoVim and AstroVim
2. Run `:TSInstall python`

### Expected behavior

The readme mentions that the CLI needs to be installed so it is not a surprise

### Additional Context

I am not 100% certain that this is expected so wanted to ask here first before sending a PR

**Comment by mehalter** [comment]
Ah thanks for reporting this! I think this is typically handled by package managers installing treesitter as a dependency when installing Neovim, but I can definitely see how this can be missed. I have made a push to the `nightly` branch to add this to the README. I'll get this merged sometime in the next day or two after a bug fix gets verified. Thanks again!

**Comment by 02strich** [comment]
Thank you!
