### ISSUE TITLE
WhichKey and neo-tree warning when changing window

### ISSUE THREAD

**Issue by cusxio** [AstroNvim/AstroNvim#1223]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.5.0

### Neovim version (>= 0.8)

NVIM v0.8.0

### Operating system/version

macOS 12.6

## Error

> Your <leader> key for "n" mode in buf 21 is currently mapped to "nil". WhichKey automatically creates triggers, so please remove the mapping

## Current Behaviour

When changing focus between a `neo-tree` buffer and a file buffer, the error above appears

### Steps to Reproduce

1. Open `neo-tree` panel
2. Move back and forth between `neo-tree` buffer and a random file buffer with `Ctrl-w-l` or `Ctrl-w-h`
3. The error above will appear

### Expected behavior

There should be no warnings when changing which buffer is being focused

### Screenshots

![CleanShot 2022-11-02 at 09 05 02](https://user-images.githubusercontent.com/6487613/199370683-ccf0f818-5f52-49f6-80c0-eb6cd7fd7463.gif)

**Comment by CMOISDEAD** [comment]
i have the same issue :(

**Comment by mehalter** [comment]
I am investigating this and will hopefully have a good fix in the coming days.

**Comment by breenbo** [comment]
Thanks, same here, and it's a little bit annoying to be honest :-).

Thanks for your great work.

**Comment by mehalter** [comment]
https://github.com/folke/which-key.nvim/issues/357

this is the issue I am waiting to receive feedback from. In the meantime, the default bindings for changing windows in AstroNvim are `^h`, `^j`, `^k`, `^l`. This uses a plugin with better logic for moving between windows and also does not trigger that warning.

**Comment by mehalter** [comment]
You could also disable the `<space>` mapping in `neo-tree` in your `user/init.lua` file:

```lua
return {
  plugins = {
    ["neo-tree"] = {
      window = {
        mappings = {
          ["<space>"] = false,
        },
      },
    },
  },
}
```

**Comment by breenbo** [comment]
Thanks for this quick answer.
Your work is really awesome, I've completely wiped out Webstorm for Neovim for my daily pro IDE, so awesome better performance, thanks to you :-)

**Comment by mehalter** [comment]
I haven't heard from the `which-key` folks yet. I am going to go ahead and remove the `space` mapping by default to avoid the leader key conflict there. Just pushed a commit to `nightly` to resolve this.

**Comment by grififth** [comment]
> You could also disable the `<space>` mapping in `neo-tree` in your `user/init.lua` file:
> 
> ```lua
> return {
>   plugins = {
>     ["neo-tree"] = {
>       window = {
>         mappings = {
>           ["<space>"] = false,
>         },
>       },
>     },
>   },
> }
> ```

How would one replicate this in a non AstroNvim setup?
