### ISSUE TITLE
`cmp` dropdown options are of messy order, ft. `rust-analyzer` and `pyright`

### ISSUE THREAD

**Issue by HymanZHAN** [AstroNvim/AstroNvim#1225]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.5.0

### Neovim version (>= 0.8)

v0.8.0-1210-gd367ed9b2

### Operating system/version

Windows 10 & Ubuntu 22.04.1

### Describe the bug

When using `rust-analyzer`, the order of `cmp` completion options is not the same as that in VS Code.
In NeoVim, snippets come on top, while the appropriate (more ergonomic and convenient) order would be that methods come first.

A similar ordering issue can be spotted in Python files as well, but on Windows only.

I am not sure which plugin is causing the problem, so I am asking for your help. Any insight would be much appreciated. 🙏

### Steps to Reproduce

1. `LspInstall rust_analyzer`
2. `cargo new test_proj`
3. `nvim test_proj`
4. Start editing.

### Expected behavior

In the completion dropdown, methods should come before snippets.

### Screenshots

- Rust

![image](https://user-images.githubusercontent.com/26806995/199408588-a801966e-08fa-4d04-b5ae-56cbc2c3f3d0.png)

![image](https://user-images.githubusercontent.com/26806995/199411512-2b1f43ce-ca46-4906-b82b-5aff3e89f65c.png)

- Python

![image](https://user-images.githubusercontent.com/26806995/199409671-bd826391-d174-4ac5-bae9-496c150386e0.png)

![image](https://user-images.githubusercontent.com/26806995/199409704-e48f9ba1-60cf-4999-90b9-86aaed8d5966.png)

### Additional Context

The `rust-analyzer` used in NeoVim was installed with mason, but the version is the same as the one used in VS Code.

**Comment by HymanZHAN** [comment]
As a side note, if you could help configure away the text description like "Method" and "Snippet" on Windows, I am all ears. 🧏‍♂️

**Comment by jayp0521** [comment]
https://github.com/AstroNvim/AstroNvim/blob/3745ab81370b1bccefc5d3956eb3dfaf00488f52/lua/core/utils/init.lua#L317-L322 these are the default priorities. overriding can be done like this, https://github.com/AstroNvim/AstroNvim/blob/bc33207244189b2ad9f8f8c534c4915abc706e8a/lua/user_example/init.lua#L288-L295

i think this is what you want. could be wrong

**Comment by jayp0521** [comment]
> 
As a side note, if you could help configure away the text description like "Method" and "Snippet" on Windows, I am all ears. 🧏‍♂️

checkout how to change:
https://github.com/onsails/lspkind.nvim

**Comment by mehalter** [comment]
Thanks @jayp0521 for commenting about the `cmp` completion priority. Just to add there are also documentation pages on this: https://astronvim.github.io/Recipes/cmp

**Comment by HymanZHAN** [comment]
Thanks for the input, folks. Unfortunately, that's not what I want. 😥 

 ![image](https://user-images.githubusercontent.com/26806995/199408588-a801966e-08fa-4d04-b5ae-56cbc2c3f3d0.png)

In this screenshot above, the snippets are actually provided by `rust-analyzer`, not luasnip. This is my first time encountering these "famous" postfix snippets that `rust-analyzer` implements, as in VS Code they are hidden down at the bottom.

I did some digging [here ](https://github.com/hrsh7th/nvim-cmp/issues/381) and [here](https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/config/compare.lua#L50), and noticed that `cmp` will always prioritize snippets from the same source. So I came up with something like this:

```lua
cmp = function(opts)
      local cmp = require "cmp"
      local luasnip = require "luasnip"
      local types = require "cmp.types"

      -- make cmp sorting more ergonomic
      local function has_dot_before()
        local line, col = unpack(vim.api.nvim_win_get_cursor(0))
        return col ~= 0 and vim.api.nvim_buf_get_lines(0, line - 1, line, true)[1]:sub(col, col) == "."
      end

      local function kind_compare(entry1, entry2)
        -- always put text at the end
        local kind1 = entry1:get_kind()
        kind1 = kind1 == types.lsp.CompletionItemKind.Text and 100 or kind1
        local kind2 = entry2:get_kind()
        kind2 = kind2 == types.lsp.CompletionItemKind.Text and 100 or kind2

        -- custom orders for different scenarios
        if kind1 ~= kind2 then
          -- prioritize field -> property -> method, if cmp is triggered by dot (.)
          if has_dot_before() then
            if kind1 == types.lsp.CompletionItemKind.Field then return true end
            if kind2 == types.lsp.CompletionItemKind.Field then return false end

            if kind1 == types.lsp.CompletionItemKind.Property then return true end
            if kind2 == types.lsp.CompletionItemKind.Property then return false end

            if kind1 == types.lsp.CompletionItemKind.Method then return true end
            if kind2 == types.lsp.CompletionItemKind.Method then return false end
          else
            -- prioritize variable -> snippet
            if kind1 == types.lsp.CompletionItemKind.Variable then return true end
            if kind2 == types.lsp.CompletionItemKind.Variable then return false end

            if kind1 == types.lsp.CompletionItemKind.Snippet then return true end
            if kind2 == types.lsp.CompletionItemKind.Snippet then return false end
          end

          local diff = kind1 - kind2
          if diff < 0 then
            return true
          elseif diff > 0 then
            return false
          end
        end
      end

      opts.sorting = {
        comparators = {
          cmp.config.compare.offset,
          cmp.config.compare.exact,
          cmp.config.compare.score,
          kind_compare,
          cmp.config.compare.sort_text,
          cmp.config.compare.length,
          cmp.config.compare.order,
        },
      }

      -- avoid jumping back when a snippet hasn't been finished yet
      luasnip.config.setup {
        region_check_events = "CursorHold,InsertLeave,InsertEnter",
        delete_check_events = "TextChanged,InsertEnter",
      }

      opts.mapping["<Tab>"] = cmp.mapping(function(fallback)
        if cmp.visible() then
          cmp.select_next_item()
        elseif luasnip.expandable() then
          luasnip.expand()
        elseif luasnip.expand_or_jumpable() then
          luasnip.expand_or_jump()
        else
          fallback()
        end
      end, { "i", "s" })

      return opts
    end,
  },
```
This kinda works, but I am not sure if it's worth it. For some reason (I am a complete Lua newbie), there is always a "flash" when I type out variables:

![cmp with rust-analyzer](https://user-images.githubusercontent.com/26806995/199650245-f2ffba4c-703a-4947-8533-f04fe7f0b8fc.gif)

I also found that the postfix snippets feature in `rust-analyzer` could be disabled, and I will probably go with that as I was never aware of their existence, let alone using them.

> > > As a side note, if you could help configure away the text description like "Method" and "Snippet" on Windows, I am all ears. 🧏‍♂️
> > 
> > 
> > checkout how to change: https://github.com/onsails/lspkind.nvim
> 
> this didn't annoy me until you pointed it out, so here you go: [jayp0521/dotfiles@ad249ee](https://github.com/jayp0521/dotfiles/commit/ad249ee881a206d43bf3735d83532ba314e1b328)

Thanks! I will give it a try.

**Comment by HymanZHAN** [comment]
Ok I experimented a bit more and decided to settle on disabling the postfix snippets of `rust-analyzer` and using `cmp`'s default sorting algorithm. For future reference, you can configure `rust-analyzer` as such:

```lua
  -- config > lsp > ["server-settings"]
  ["server-settings"] = {
      rust_analyzer = {
        settings = {
          ["rust-analyzer"] = {
            completion = {
              postfix = {
                enable = false,
              },
            },
          },
        },
      },
    },
  },
```
Closing this issue as this is mainly a `nvim-cmp` issue. Thx!
