### ISSUE TITLE
Tab Line Startup

### ISSUE THREAD

**Issue by demiancodes** [AstroNvim/AstroNvim#1226]
### Question

I believe that my tab line never appeared in startup the first day or two I installed AstroNvim. Now it launches every time. Is there a way to disable it on startup. Not disable it entirely, but only on startup. Partial fix of course is "Space + ut" mapping but I'd rather have something more permanent.

**Comment by mehalter** [comment]
These dashboard fixes have been fixed in the latest release of AstroNvim, could you see if this answers the question you had? :)

**Comment by mehalter** [comment]
I believe this has been resolved. Please let me know if it isn't @demiancodes and I can happily re open this!
