### ISSUE TITLE
Config crashes

### ISSUE THREAD

**Issue by paintmeyellow** [AstroNvim/AstroNvim#1229]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.5.1

### Neovim version (>= 0.8)

NVIM 0.8.0

### Operating system/version

Ubuntu 20.04

### Describe the bug

Something wrong with config I guess. 
I'm using default btw. Just copied user_example into user folder.

### Steps to Reproduce

1. `:TSUpdate`
<img src="https://user-images.githubusercontent.com/24860764/199551320-e745354a-9d44-401e-8af0-6e7fab36678f.png" width="400px">

2. `:AstroReload`
<img src="https://user-images.githubusercontent.com/24860764/199551686-fad99516-b887-4081-95d0-345f1fda9f0a.png" width="400px">

3. `:TSUpdate`
<img src="https://user-images.githubusercontent.com/24860764/199552403-d6e7947d-2035-49db-839c-1d2ebe5927a8.png" width="900px">

### Expected behavior

Absence of errors

**Comment by mehalter** [comment]
Thanks for reporting this @paintmeyellow ! I just released v2.5.3 which contains a patch for this.
