### ISSUE TITLE
How can I choose a Python version?

### ISSUE THREAD

**Issue by rozhelluk** [AstroNvim/AstroNvim#1232]
### Question

I have two versions of Python installed on my system: 3.10.7 and 3.11.0
The <leader>tp key combination launches the Python version 3.10.7 console. I'd like to have Python 3.11.0 console running.
I can create a python -> python3.11 symlink, but it would be better if I could control this in the init.lua config file.
Could you tell me how to do it?
Thank you for your attention.

**Comment by jayp0521** [comment]
unsure if you tried looking through the guide to understand how astronvim works.

you can replace this [mapping](https://github.com/AstroNvim/AstroNvim/blob/ed8a9d87c2f83fbb9aef80487ae307dde3ebbf6e/lua/core/mappings.lua#L189) with `maps.n["<leader>tp"] = { function() toggle_term_cmd "python3.11" end, desc = "ToggleTerm python" }` and I think it should work. untested

**Comment by jayp0521** [comment]
https://astronvim.github.io/Configuration/basic_configuration

guide on how to override mappings above

example of me doing it as well https://github.com/jayp0521/dotfiles/blob/main/shell/.config/nvim/lua/user/mappings.lua

**Comment by rozhelluk** [comment]
> you can replace this [mapping](https://github.com/AstroNvim/AstroNvim/blob/ed8a9d87c2f83fbb9aef80487ae307dde3ebbf6e/lua/core/mappings.lua#L189) with `maps.n["<leader>tp"] = { function() toggle_term_cmd "python3.11" end, desc = "ToggleTerm python" }` and I think it should work. untested

This will work, but I don't want to "get into" the git repository, because after the update my changes will be lost (probably).

**Comment by mehalter** [comment]
@rozhelluk during the updates for AstroNvim we do not talk the `user` folder and have that on the `.gitignore`. So your user configuration will never be over written or lost during the update as long as you configure everything from a `user/` folder as described in the docs

**Comment by mehalter** [comment]
https://astronvim.github.io/Configuration/manage_user_config

**Comment by rozhelluk** [comment]
@mehalter @jayp0521 
I read ~/.config/nvim/lua/core/mappings.lua and ~/.config/nvim/lua/core/utils/init.lua and wrote the following code in my init.lua configuration file:
```lua
local config = {
  mappings = {
    n = {
      ["<leader>tp"] = {
        function() astronvim.toggle_term_cmd "python3.11" end,
        desc = "ToggleTerm python",
      },
    },
  },
}
return config
```
I don't know if I did it right, but it just works.
