### ISSUE TITLE
Overriding plugins not supported with table style

### ISSUE THREAD

**Issue by jayp0521** [AstroNvim/AstroNvim#1234]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

I looked at the code :)

### Neovim version (>= 0.8)

0.8.0

### Operating system/version

arch latest

### Describe the bug

https://github.com/AstroNvim/AstroNvim/blob/main/lua/user_example/init.lua#L222-L240

astronvim officially supports 2 ways of writing plugins as shown above. all plugins in astronvim are defined with key value style, https://github.com/AstroNvim/AstroNvim/blob/main/lua/core/plugins.lua#L270.

when plugins are defined in table style. `vim.tbl_deep_extend` does not work, because astronvim is key value, and user plugin is table style

### Steps to Reproduce

`user.plugins.init`

`{ "rafamadriz/friendly-snippets", opt = false}`

this won't override `opt = true`

### Expected behavior

`opt = false` should happen

### Additional Context

https://github.com/AstroNvim/AstroNvim/blob/main/lua/core/plugins.lua#L271

this should be done on both "plugins.init" and `astro_plugins` before combining them

**Comment by jayp0521** [comment]
I can help with this if you agree it is a bug

**Comment by mehalter** [comment]
This Should be overriden with keys:

```lua
["rafamadriz/friendly-snippets"] = { opt = false}
```

**Comment by jayp0521** [comment]
I mean I know how to override, but this isn't documented anywhere. It should either be fixed or written in the docs to only use key value style for best compatibility

**Comment by jayp0521** [comment]
@mehalter
