### ISSUE TITLE
<lead> ff ignore plugin SimpylFold but directly open file with nvim SimpylFold works.

### ISSUE THREAD

**Issue by laowalter** [AstroNvim/AstroNvim#1235]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.5.0

### Neovim version (>= 0.8)

NVIM v0.8.0

### Operating system/version

Gentoo Base System release 2.8

### Describe the bug

With the following custom config, SimpylFold works when nvim open a file, but if from <leader>ff find a file, and open it, SimpylFold is ignored.

file:  /usr/plugins/init.lua 
```
return {
  { "tmhedberg/SimpylFold" },
}
```

### Steps to Reproduce

file:  /usr/plugins/init.lua 
```
return {
  { "tmhedberg/SimpylFold" },
}
```
with <lead> ff to open a file.

### Expected behavior

Just dont ignore SimpylFold with <leader> ff.

**Comment by mehalter** [comment]
I believe this is related to the Python treesitter parser and filetype detection for some reason. I am getting the same behavior with treesitter based folds in Python as well. I can't replicate in any other filetypes which leads me to believe it's related to the python parser.
