### ISSUE TITLE
Disable notifications from UI

### ISSUE THREAD

**Issue by work-leonid** [AstroNvim/AstroNvim#1236]
### Is your feature related to a problem?

Add the ability to turn off these notifications from the UI. Sometimes you need them, but it would be great if you could turn them off without editing config file

<img width="455" alt="image" src="https://user-images.githubusercontent.com/8654430/199678630-42f27fc9-d3ef-4137-a682-0194ae09913e.png">

### Describe the new feature

Add the ability to turn notifications off from this menu.

<img width="883" alt="image" src="https://user-images.githubusercontent.com/8654430/199678816-d498793e-ee69-43ad-9cc9-5b03cbf71e40.png">

**Comment by mehalter** [comment]
Ah, this is a good point. I will add a UI toggle for UI toggle notifications!

**Comment by mehalter** [comment]
@work-leonid I just pushed a commit to `nightly`, could you please set your `updater` table in your `user/init.lua` file to this:

```lua
updater = { channel = "nightly" }
```

And run `:AstroUpdate` and restart? Make sure that you remove `branch = "main"`

and see what you think? I bound it to `<leader>uN` figured the capital `N` would make it less prone to an accidental disable. This also adds `vim.g.ui_notifications_enabled` option where you can make them silenced by default as well

**Comment by work-leonid** [comment]
I'm sorry I didn't answer right away. I can't check out what you've done yet. Need a few days. 
I really appreciate what you are doing, thank you so much! ❤️
