### ISSUE TITLE
Telescope checkhealth and ripgrep don't work

### ISSUE THREAD

**Issue by Dominux** [AstroNvim/AstroNvim#1243]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.5.0

### Neovim version (>= 0.8)

NVIM v0.8.0

### Operating system/version

Manjaro Linux x86_64

### Describe the bug

1. command `:checkhealth telescope` gives the next result:
     ```
    - ERROR: No healthcheck found for "telescope" plugin.
    ```
   And `:checkhealth` autocompletion list doesn't show the "telescope" variant
2. live grep telescope search doesn't work after installing [ripgrep](https://github.com/BurntSushi/ripgrep). On `<leader>fw` I see only blank telescope windows, in the left right of which I can write my regex, but others show nothing. It shows only stack traceback

### Steps to Reproduce

1. Run `:checkhealth telescope`
2. Click `<leader>fw` and start typing

### Expected behavior

1. Checkhealth of the telescope plugin
2. Working find and replace for words in the whole project

### Screenshots

1. ![image](https://user-images.githubusercontent.com/55978340/199818963-97c1cfe3-d5b4-4f8c-9a12-6fec84dae90a.png)

2. ![image](https://user-images.githubusercontent.com/55978340/199819272-a28f723e-7171-41ed-b338-105cf2fdfd66.png)

### Additional Context

Since I installed it from [aur](https://aur.archlinux.org/packages/astronvim) AstroUpdate doesn't work, but as you could notice I use fresh version of Astronvim

**Comment by mehalter** [comment]
To improve startup time we use lazy loading for telescope. So when you just start Neovim, telescope is not a loaded plugin so no  health checks have been registered. The easiest way to start Telescope is by running `:Telescope` and then you can do `:checkhealth telescope`. It should look something like this:

![2022-11-04_09:00:55_screenshot](https://user-images.githubusercontent.com/1591837/199978783-984eeef9-e6f7-4fc0-9d8b-8e6ddf7aa710.png)

**Comment by Dominux** [comment]
@mehalter, thank u, it really works!

But the bug with not working ripgrep still remains:

Here I got it installed:
![image](https://user-images.githubusercontent.com/55978340/199981729-66768d4e-836e-4916-abcc-655e60929703.png)

But in checkhealth it shows that I didn't
![image](https://user-images.githubusercontent.com/55978340/199981885-863cab5f-d3cd-4d31-8d3d-f24fad0c21b3.png)

And it's displayed among installed ones (`:PackerStatus`):
![image](https://user-images.githubusercontent.com/55978340/199982389-af6e558b-0a97-4313-bbc3-99518b2d3154.png)

**Comment by mehalter** [comment]
Please check the link I have provided in the README and the documentation: https://github.com/BurntSushi/ripgrep

`ripgrep` is *not* a neovim plugin. It is a binary that needs to be installed to your machine. I would recommend reading the documentation on that page for how to install: https://github.com/BurntSushi/ripgrep#installation

**Comment by Dominux** [comment]
Thanks for ur help, I had no idea what to do for a week

Now I can finally start using my astronvim setup like I do in vscode

**Comment by eerison** [comment]
> To improve startup time we use lazy loading for telescope. So when you just start Neovim, telescope is not a loaded plugin so no health checks have been registered. The easiest way to start Telescope is by running `:Telescope` and then you can do `:checkhealth telescope`. It should look something like this:
> 
> ![2022-11-04_09:00:55_screenshot](https://user-images.githubusercontent.com/1591837/199978783-984eeef9-e6f7-4fc0-9d8b-8e6ddf7aa710.png)

this was really helpful thank you <3
