### ISSUE TITLE
Change Gitsigns blame line text color in AstroVim config

### ISSUE THREAD

**Issue by Baregamyan** [AstroNvim/AstroNvim#1244]
### Question

Hi, everyone! 

Is there any chance to change Gitsigns blame line text color in AstroVim config ? 

Kinda: 
```
gitsigns = {
      current_line_blame = true,
      current_line_blame_opts = {
          color = '#FFF',
      },
    },
```

Thank you!

**Comment by mehalter** [comment]
Not sure, probably worth asking on the [gitsigns.nvim](https://github.com/lewis6991/gitsigns.nvim) repo. I believe it uses virtual text so maybe you just change the virtual text highlight groups but I'm not sure.
