### ISSUE TITLE
PackerSync not completing

### ISSUE THREAD

**Issue by mmrath** [AstroNvim/AstroNvim#1245]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

Version: v2.5.4

### Neovim version (>= 0.8)

NVIM v0.8.0

### Operating system/version

macOS 12.6

### Describe the bug

This is probably just related to the user config I am using (link below)

https://code.mehalter.com/projects/68

Packer appears not complete ever. Always saying `syncing 10 / 84 plugins` not sure why 10 and the repos it is stuck is not always same.

I have run the following before running `:PackerSync` and also tried `:PackerSync` few times after nvim restart.
`rm -rf ~/.local/share/nvim ~/.cache/nvim`

### Steps to Reproduce

https://code.mehalter.com/projects/68

### Expected behavior

Hoping that packer will say all installed. 

### Screenshots

<img width="1153" alt="Screen Shot 2022-11-04 at 9 02 42 am" src="https://user-images.githubusercontent.com/115767/199844192-cc978ac9-3d0a-444d-84fd-77d634aff66e.png">

**Comment by mehalter** [comment]
I'm not sure, I don't consider this a bug in AstroNvim. I would not recommend you use my config, there are a lot of things specific to what I do on my computer that probably won't fit nicely just anywhere. It is a good place for guidance to see how to  configure things, but it is not supported as a drop in configuration.
