### ISSUE TITLE
`winbar_bg` is not a valid color

### ISSUE THREAD

**Issue by jayp0521** [AstroNvim/AstroNvim#1246]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.5.4

### Neovim version (>= 0.8)

0.8.0

### Operating system/version

arch latest

### Describe the bug

After this [commit](https://github.com/AstroNvim/AstroNvim/commit/f2349c532c7ab9c95b5f11d340b385c1c86743e9), it seems like my neovim setup has stopped working. I reverted the commit locally and everything seems to be working fine again

### Steps to Reproduce

get latest astronvim

configuration:

https://github.com/jayp0521/dotfiles/tree/main/shell/.config/nvim/lua/user

unsure if the issue is my configuration, but the latest commit seems to break something for me

### Expected behavior

Astronvim works fine

### Screenshots

![image](https://user-images.githubusercontent.com/36803168/199857911-98d26edd-10ba-472f-b13f-25a719e3d915.png)

![image](https://user-images.githubusercontent.com/36803168/199857938-a7ddbb57-9fba-484a-a97f-e402fa4f5d05.png)

**Comment by mehalter** [comment]
@jayp0521 what colorscheme are you using?

**Comment by jayp0521** [comment]
`catppuccin`

**Comment by jayp0521** [comment]
if this helps. I did try nuking: `.cache/nvim and `.local/share/nvim`
```
				require("catppuccin").setup({
					dim_inactive = {
						enabled = false,
						shade = "dark",
						percentage = 0.15,
					},
					compile = {
						enabled = true,
						path = vim.fn.stdpath("cache") .. "/catppuccin",
					},
					term_colors = true,
					transparent_background = true,
					integrations = {
						neotree = {
							enabled = true,
							show_root = false,
							transparent_panel = true,
						},
						hop = true,
						ts_rainbow = true,
						which_key = true,
						dap = {
							enabled = true,
							enable_ui = true,
						},
						aerial = true,
						treesitter_context = true,
						notify = true,
						gitsigns = true,
						cmp = true,
						telescope = true,
						treesitter = true,
						nvimtree = true,
						native_lsp = {
							enabled = true,
						},
					},
				})
```

**Comment by mehalter** [comment]
Hm I have to look into this again in the next week. This commit was in particular to *fix* catppuccin support actually 😂 so I spent today actually using only catppuccin so I'm pretty sure it works 🤔 but I'll keep checking in the next week or so. Not sure if I'll be able to replicate.

**Comment by mehalter** [comment]
Ah your catppuccin config will be useful in this process

**Comment by jayp0521** [comment]
you'll be able to replicate with my dotfiles. I tried on 2 different computers already

**Comment by mehalter** [comment]
Don't worry, I won't mess with installing your entire dotfiles. I will just try your catppuccin config and that should be enough to replicate. This is purely a colorscheme thing

**Comment by jayp0521** [comment]
https://github.com/jayp0521/dotfiles/blob/main/shell/.config/nvim/lua/user/theme.lua

I also have the old guidance for https://astronvim.github.io/Recipes/telescope_theme. the new way doesn't seem to work for me, in case that is related

**Comment by convers39** [comment]
same issue after updating to the latest

<img width="1505" alt="image" src="https://user-images.githubusercontent.com/42597395/199876704-9d594231-32e2-4d09-b197-142e4bd38ef9.png">

**Comment by jayp0521** [comment]
> same issue after updating to the latest
> 
> <img alt="image" width="1505" src="https://user-images.githubusercontent.com/42597395/199876704-9d594231-32e2-4d09-b197-142e4bd38ef9.png">

your theme seems to be different. what are you using?

**Comment by convers39** [comment]
I am using everforest, it does not seem to be a theme-specific issue..

@mehalter Is there any way to roll back to a previous version? I try with git checkout commit hash and rerun packer sync, but the issue still appears.

**Comment by mehalter** [comment]
Yeah I see what's going on, this is what happens when the background is `nil` to be transparent, need to figure out how to do this in `Heirline` correctly
