### ISSUE TITLE
Dedicated function to install packages

### ISSUE THREAD

**Issue by Montana** [AstroNvim/AstroNvim#1254]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

NVIM v0.8.0

### Neovim version (>= 0.8)

NVIM v0.8.0

### Operating system/version

macOS 13.0

### Describe the bug

I was thinking why not use `pcall` so users can have a function as an installer. Think the hurdle here is `async`, but a sample would be something like this: 

```javascript
local PackageInstaller = package:GetPackage("PackageService"):GetPackageService("MyPackageService")
local success, response --Don't need to define yet
local count = 0 --1

while not success do --2
    if count >= 1 then
        warn("Retrying, count:", count, "\nError:", response) --3
        wait(7) --4
    end

    success, response = pcall(DataStore.GetAsync, DataStore, "key") --5
    count = count + 1 --6
end
```
As it stands, is there a way to install outside packages, like `Coc.nvim`? I really appreciate it and I hope my advice isn't taken as criticism as you folks have built a great thing for everybody.

Cheers,
Montana Mendy

### Steps to Reproduce

Try to install a package. 

### Expected behavior

Install 3rd party packages.

**Comment by mehalter** [comment]
AstroNvim uses [Mason](https://github.com/williamboman/mason.nvim) for installing external packages. You can use `:Mason` or `<leader>pI` to open the installer. This will let you install linters/formatters/language servers/debugger adapters. Currently AstroNvim will automatically set up language servers, linters, and formatters that are installed with Mason. AstroNvim currently doesn't have debugger support out of the box yet, but that will be coming in the coming months.
