### ISSUE TITLE
NvimTree instead of NeoTree

### ISSUE THREAD

**Issue by IcyKit** [AstroNvim/AstroNvim#1257]
### Question

How can I use NvimTree instead of NeoTree? 

As I understood, NvimTree already installed in AstroNvim.

**Comment by mehalter** [comment]
NvimTree is not in AstroNvim by default, you will need to disable nthe neo-tree plugin in your `plugins.init` table, add NvimTree, and then add the mappings you want to control NvimTree

**Comment by IcyKit** [comment]
> NvimTree is not in AstroNvim by default, you will need to disable nthe neo-tree plugin in your `plugins.init` table, add NvimTree, and then add the mappings you want to control NvimTree

Thanks!
