### ISSUE TITLE
Can't update AstroVim with detached HEAD

### ISSUE THREAD

**Issue by Kindlewing** [AstroNvim/AstroNvim#1258]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.6.1

### Neovim version (>= 0.8)

NVIM v0.8.0

### Operating system/version

Arch Linux

### Describe the bug

Error checking out branch: origin/main

### Steps to Reproduce

1. run :PackerSync
2. run :AstroUpdate
3. restart AstroVim

### Expected behavior

AstroVim updates successfully

**Comment by mehalter** [comment]
What do you get if you run `git status` in the `~/.config/nvim` folder?

**Comment by Kindlewing** [comment]
`On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    lua/user_example/init.lua

no changes added to commit (use "git add" and/or "git commit -a")`

**Comment by mehalter** [comment]
I noticed you have made some changes (deleting the `user_example/init.lua` file) but I'm not sure if this would be causing it...

What do you get if you run `git checkout origin/main` and `git rev-parse --abbrev-ref HEAD`?

**Comment by Kindlewing** [comment]
I just get `HEAD`

**Comment by mehalter** [comment]
What do you get when you run the `checkout` command?

**Comment by mehalter** [comment]
It looks like your clone has found itself in a detached HEAD state. Could you try running:

```sh
git fetch origin
git reset --hard origin/master
```

And see if the command `git rev-parse --abbrev-ref HEAD` returns `main`? Once it returns `main` instead of `HEAD`, the updater should work as intended
