### ISSUE TITLE
`wl-clipboard` stopped working

### ISSUE THREAD

**Issue by Grafcube** [AstroNvim/AstroNvim#1264]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.6.1

### Neovim version (>= 0.8)

NVIM v0.8.0

### Operating system/version

Arch Linux

### Describe the bug

`wl-clipboard` stops working correctly on Gnome 43. If I yank something soon after opening nvim or neovide, it works. But after a few seconds, nothing is written to the system clipboard and I can't even use whatever I just yanked. This does not happen with `nvim -u NORC` or the same thing with neovide after setting `clipboard=unnamedplus`.

### Steps to Reproduce

1. Open neovim.
2. Wait a few seconds.
3. Yank something.

### Expected behavior

Text is copied to system clipboard.

### Screenshots

When I yank something, I get this notification in Gnome: 

![image](https://user-images.githubusercontent.com/34889224/200221532-f3666319-4f70-45c4-92de-c482032236d2.png)

### Additional Context

This only started happening recently. I don't know if it has anything to do with the fact that I very recently updated to Gnome 43 since for the past 2 weeks I've been using KDE Plasma and I was using Gnome 42 before that. [Here is my AstroNvim config](https://gitlab.com/Grafcube/dotfiles/-/tree/040ca904247e0cdb897994c0ae4f88f85b73aa6b/dot_config/nvim/lua/user).

**Comment by mehalter** [comment]
I'm not sure about this. We aren't doing anything special with the clipboard, we are just setting `clipboard = unnamedplus`. Are you sure this doesn't happen without AstroNvim when you do set `clipboard` to be `unnamedplus`?

**Comment by Grafcube** [comment]
Yes I confirmed that it works as expected with plain nvim. There seems to be a slight delay though, it works if I yank immediately after launching neovim.

**Comment by mehalter** [comment]
Hm, not sure where to start debugging this if I'm honest. Since AstroNvim doesn't use any plugins that affect the clipboard and has no automations or anything that affect it 🤔

**Comment by Grafcube** [comment]
It still seems related to AstroNvim because of my test with NORC but if it helps, the problem disappeared after I installed this Gnome extension [Noannoyance](https://extensions.gnome.org/extension/2182/noannoyance/). Based on this, my guess is that something changed about the way Gnome handles focus stealing that affects wl-clipboard in certain situations. Beyond that I'm not sure how to debug this either.

**Comment by mehalter** [comment]
That makes me more confident that this is unrelated to AstroNvim since we also have nothing related to focus stealing or window focusing in AstroNvim either

**Comment by mehalter** [comment]
Ah I just noticed you mentioned Neovide. Can you verify of the clipboard works as intended or not when using AstroNvim in the terminal? Also trying Neovide without AstroNvim and with the clipboard set to `unnamedplus`. It seems like the Neovim GUI is the highest probability at being at fault since that will affect how the clipboard and window focusing is handled

**Comment by Grafcube** [comment]
Yes I tested norc with both terminal and neovide. I'd have to agree that this doesn't seem like an issue with AstroNvim. I opened the issue because this was the only common point with the problem. The extension has solved the problem for me but I'm hesitant to close the issue since it's not a real solution. But since I haven't seen any mention of this anywhere else it could also just be some strange combination of factors from my own config.

**Comment by mehalter** [comment]
@Grafcube can you replicate the bug with a fresh AstroNvim install without your user configuration?

**Comment by Grafcube** [comment]
While testing the fresh install I discovered what might be the actual problem. This only occurs when the window is fullscreen regardless of whether I'm using neovide or the terminal and also with the example config. But strangely, it doesn't happen with norc even in fullscreen.

**Comment by mehalter** [comment]
Hm as you get closer and closer to figuring it out I become more and more confident it's unrelated to our config 😂 please let me know if you continue to figure out what might be causing it!

**Comment by Grafcube** [comment]
It seems like this has something to do with wl-clipboard trying to grab focus to copy clipboard contents. Either way it definitely seems like it's not an issue with AstroNvim. The extension solved my problem anyway so I'm closing the issue. Thanks for the help (even though this was the wrong place to open an issue). Maybe this will be solved in the future when Wayland gets better™.
