### ISSUE TITLE
`search word` not working without ripgrep

### ISSUE THREAD

**Issue by AlphaVCat** [AstroNvim/AstroNvim#1265]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.6.1

### Neovim version (>= 0.8)

NVIM v0.8.0-1

### Operating system/version

Ubuntu 22.10

### Describe the bug

Searching words in all files are not working!  I'm searching a word in file with this cmnd `<leader>fw` but is not showing any output or any file! **MAPPING CONFIG**:
```bash
if is_available "telescope.nvim" then
  maps.n["<leader>fw"] = { function() require("telescope.builtin").live_grep() end, desc = "Search words" }
  maps.n["<leader>fW"] = {
    function()
      require("telescope.builtin").live_grep {
        additional_args = function(args) return vim.list_extend(args, { "--hidden", "--no-ignore" }) end,
      }
    end,
    desc = "Search words in all files"
```

See Image:

### Steps to Reproduce

1. Nvim file.ext
2. Space/Leader + fw
3. Type any word you want to find in the file/files!
4. Nothing shows

### Expected behavior

Shows all the matching words in all files!

### Screenshots

![search](https://user-images.githubusercontent.com/114478214/200236251-5205827f-92ce-4f4c-b961-c353c49e9e65.jpg)

**Comment by mehalter** [comment]
Do you have `ripgrep` installed and verify that you have access to the command `rg` on the command line?

**Comment by AlphaVCat** [comment]
Thanks It's worked! `ripgrep` is missing!

SEE:

![worked](https://user-images.githubusercontent.com/114478214/200550617-245a6a86-9783-4fd0-b797-f0904df274a9.jpg)
