### ISSUE TITLE
Installing themes on Astrovim

### ISSUE THREAD

**Issue by SamueleSamarxhiu** [AstroNvim/AstroNvim#1267]
### Question

Hi I wanted to ask how am I supposed to install themes on astrovim as I am new to it. I wanted to install precisely this theme: https://github.com/FrenzyExists/aquarium-vim, before using astrovim I was using just neovim with the Plug Manager and I didnt do a backup of all my config init.vim file. I was just wondering is there a way to install external packages such as this theme and apply it to astrovim ??

**Comment by mehalter** [comment]
Here are the docs for setting up a user configuration file for AstroNvim: https://astronvim.github.io/Configuration/manage_user_config

And here are the docs for installing a custom colorscheme from an external plugin: https://astronvim.github.io/Recipes/colorscheme
