### ISSUE TITLE
Lazygit and Toggleterm conflicts

### ISSUE THREAD

**Issue by vtvz** [AstroNvim/AstroNvim#1275]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.6.2

### Neovim version (>= 0.8)

NVIM v0.8.0

### Operating system/version

Manjaro Linux 22.0.0

### Describe the bug

Lazygit conflicts with regularly opened terminals. "Steps to Reproduce" will give more info

### Steps to Reproduce

- Open `nvim`
- Open lazygit `<leader>-gg`
- Close lazygit `q`
- Open terminal `<C-'>`
- Do something `htop`
- Close terminal `<C-'>`
- Open lazygit `<leader>-gg`
- Close lazygit `q`
- Open terminal `<C-'>`
- Session lost

### Expected behavior

Session of previously opened terminal should be preserved 

### Additional Context

I understand why this happens. If I use something like `:echo bufname()` it shows me similar to `term://~/fork//13812:/usr/bin/zsh;#toggleterm#1` for lazygit **and** terminal. I tried using this in my user config:

```lua
  mappings = {
    n = {
      ["<leader>gg"] = {
        function()
          astronvim.toggle_term_cmd({ cmd = "lazygit", hidden = true, count = 150 })
        end,
        desc = "ToggleTerm lazygit",
      },
```

and it helps.

I guess similar approach can be used in `lua/core/mappings.lua`:

```lua
if is_available "toggleterm.nvim" then
  local toggle_term_cmd = astronvim.toggle_term_cmd
  maps.n["<leader>gg"] =
    { function() toggle_term_cmd { cmd = "lazygit", hidden = true, count = 150 } end, desc = "ToggleTerm lazygit" }
```

or modify `astronvim.toggle_term_cmd` somehow in `lua/core/utils/init.lua` eg:

```lua
function astronvim.toggle_term_cmd(term_details)
  -- if a command string is provided, create a basic table for Terminal:new() options
  if type(term_details) == "string" then term_details = { cmd = term_details, hidden = true } end
  -- use the command as the key for the table
  local term_key = term_details.cmd
  -- set the count in the term details

    term_details.count = 150 + vim.v.count
    term_key = term_key .. vim.v.count
```

I can make PR but I'm not sure about implementation

**Comment by mehalter** [comment]
Ah, thanks for catching this! I will put together a fix! :D

**Comment by mehalter** [comment]
@vtvz I pushed a commit to the `nightly` channel with the fix you described. I am going to look to see if there are better approaches and I'll let you know! Ideally I would like the `<C-'>/`F7` binding to toggle any open terminal away if it's open so that's definitely something I'm going to try and improve as well.

**Comment by mehalter** [comment]
@vtvz I think I have completely fixed this and greatly improved how the terminal applications work ! Check out the latest nightly and see what you think!

**Comment by vtvz** [comment]
@mehalter hmmm... I face the same issue again with the latest version...

**Comment by vtvz** [comment]
Without custom mapping
```lua
  mappings = {
    n = {
      ["<leader>gg"] = {
        function()
          astronvim.toggle_term_cmd({ cmd = "lazygit", hidden = true, count = 150 })
        end,
        desc = "ToggleTerm lazygit",
      },
```
Still opens terminals with the same id
![term](https://user-images.githubusercontent.com/11929252/201337827-58593bc5-1d6f-4982-82aa-7f09f40d78ee.png)
![lazygit](https://user-images.githubusercontent.com/11929252/201337960-2b1621bc-7005-4a3b-a6cd-44532e76cef0.png)

**Comment by mehalter** [comment]
You shouldn't get conflict behavior though because of `hidden=true` . Can you still replicate the original bug you reported? In my testing I cannot

**Comment by mehalter** [comment]
Also can you verify what version of AstroNvim you are using now? The latest version of AstroNvim does not set the `count` at all, so if there are count conflicts this would be a bug with toggleterm assigning the terminal counts

**Comment by vtvz** [comment]
So... Here is my [screen record](https://youtu.be/J8sYYEHU4NQ) with keys typed

**Comment by mehalter** [comment]
ah I see I see, I misunderstood how the `count` variable works. Hm, I suppose we do probably need to give these things like some garbage count. Could you check out the latest `nightly` and see if that resolves it?
