### ISSUE TITLE
Disable default plugins

### ISSUE THREAD

**Issue by trankchung** [AstroNvim/AstroNvim#1276]
### Question

Is there a way to disable default plugins such as toggleterm? I checked the source code but don't see a way to. Thanks.

**Comment by mehalter** [comment]
Check the `user_example`: https://github.com/AstroNvim/AstroNvim/blob/d92c03dcc6bf68f2ce395322a5478066da672ce6/lua/user_example/init.lua#L220-L221

Here is an example with ToggleTerm:

```lua
return {
  plugins = {
    init = {
      ["akinsho/toggleterm.nvim"] = { disable = true },
    },
  },
}
```

Then just make sure that you do a `:PackerSync` anytime you edit the `plugins.init` table and it will remove the plugin.

**Comment by trankchung** [comment]
Thanks for the quick reply, @mehalter. I love AstroNvim.

**Comment by alr86** [comment]
It's deprecated, now you can disable default plugins with following command

lua/plugins/disabled.lua :
```
return {
  { "goolord/alpha-nvim", enabled = false },
}
```
Reference: https://docs.astronvim.com/configuration/customizing_plugins/#disabling-plugins
