### ISSUE TITLE
Curly Brace incorrect space.

### ISSUE THREAD

**Issue by A-Lamia** [AstroNvim/AstroNvim#1278]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

V2.6.2-3-g1e29035

### Neovim version (>= 0.8)

v0.8

### Operating system/version

Windows 10

### Describe the bug

Closing curly brace has a tab space when entering.

### Steps to Reproduce

1. create curly brace.
2. press enter when carrot is in between. 

### Expected behavior

For there to be no tab space.

### Screenshots

Current:
![image](https://user-images.githubusercontent.com/6450181/200724765-9dfb96e8-63ed-4a13-8f79-af2b538bf401.png)

Desired:
![image](https://user-images.githubusercontent.com/6450181/200724743-d4ac2dcb-ea54-4a7d-8200-11a76265837e.png)

### Additional Context

This is something that happened within a week or so.

**Comment by Yakov-Varnaev** [comment]
+ 1 Have same issue with python
<img width="333" alt="image" src="https://user-images.githubusercontent.com/73383566/200756591-2641c2d3-6415-47e6-93dd-474b7aa8fc77.png">

**Comment by mehalter** [comment]
What filetype is this?

**Comment by A-Lamia** [comment]
Powershell, Some one before commented they had the same issue with python parenthesis and showed images of the same issues but deleted there post not sure why. 

If he figured out the issue would have been nice if he left an other comment :)

**Comment by mehalter** [comment]
`nvim-autopairs` is what we are using here that is handling this. Typically it relies on treesitter to figure out indentation and stuff and powershell is a good example where there is not currently a supported treesitter parser for neovim 🤔 . There definitely are ways to configure this but I'm not super adept at this. You might want to ask on the `nvim-autopairs` repo (https://github.com/windwp/nvim-autopairs) and see if they can help you configure it correctly. If you get a good solution I would love to potentially add it to AstroNvim!

**Comment by A-Lamia** [comment]
That's confusing according to nvim-autopairs it doesn't have anything to do with the indent.

> 
> 1.If you report a bug about indent. Please remember that plugin doesn't do anything about indent.
>   It just trigger the indent of your vim config so if you have wrong indent config then it will do wrong indent.
>   You can check by select a block of code and press `==`
> 2. provide result of command `:verbose imap <cr>`.

**Comment by A-Lamia** [comment]
Seems this issue may be a little more complicated it happens in default nvim and vim, and may have something to do with indent settings I'm not 100% sure yet.

**Comment by mehalter** [comment]
I'm not sure what we will be able to do in this situation :/ especially if it's present in stock Neovim/vim

**Comment by A-Lamia** [comment]
yep I think this can be closed seeing as it's an issue that has nothing to do with this project, I'll do a little more research and see if i can find a fix if i can ill leave a comment on this issue.

**Comment by mehalter** [comment]
Awesome, thanks so much! I'll also take a look in my free time and see if I can help out
