### ISSUE TITLE
Code Folding

### ISSUE THREAD

**Issue by IcyKit** [AstroNvim/AstroNvim#1279]
### Question

Are there any ways or default plugins to fold code in AstroVim?

**Comment by i-am-the-slime** [comment]
Creepy, I've been trying this for two hours as well. I need the LSP version of this:
https://github.com/kevinhwang91/nvim-ufo

But I'm struggling.

**Comment by mehalter** [comment]
@IcyKit I personally just use the built in treesitter folding capabilities. You just need to set this in your config:

```lua
return {
  options = {
    opt = {
      foldexpr = "nvim_treesitter#foldexpr()", -- set Treesitter based folding
      foldmethod = "expr",
    },
  },
}
```

This will automatically fold the code when you open it, I'm not a huge fan of this so I also add `foldenable = false` and then I don't open up a folded piece of code but can fold things away as needed:

```lua
return {
  options = {
    opt = {
      foldenable = false,
      foldexpr = "nvim_treesitter#foldexpr()", -- set Treesitter based folding
      foldmethod = "expr",
    },
  },
}
```

**Comment by mehalter** [comment]
Here is a recording of me doing a few different filetype folding with this method: https://asciinema.org/a/dyXmLBZG50u3E26VJ1iz0gKqP

**Comment by IcyKit** [comment]
Oh, I just tried nvim-ufo and it is working perfectly! Thanks for your answer!

**Comment by i-am-the-slime** [comment]
@mehalter could you share where to add the relevant config for the LSP config?

**Comment by mehalter** [comment]
@i-am-the-slime the code blocks I sent are entire `user/init.lua` files.

**Comment by i-am-the-slime** [comment]
@mehalter thanks, but there's no treesitter grammar for the language I use, so I'd like to use the folding stuff from ufo for the lsp. I did this in `~/.config/astronvim/lua/user/init.lua` but no luck:


```lua 
  lsp = {
    -- add capabilities (from plugins (such as ufo))
    capabilities = {
      textDocument = {
        foldingRange = {
          dynamicRegistration = false,
          lineFoldingOnly = true
        },
        },
    },
    
    -- add to the global LSP on_attach function
    on_attach = { function(client, bufnr)
      require('ufo').setup()
    end} ,
}
```

**Comment by mehalter** [comment]
This is quite close. The main thing is the `on_attach` shouldn't be a table:

```lua
  lsp = {
    -- add capabilities (from plugins (such as ufo))
    capabilities = {
      textDocument = {
        foldingRange = {
          dynamicRegistration = false,
          lineFoldingOnly = true
        },
        },
    },
    
    -- add to the global LSP on_attach function
    on_attach = function(client, bufnr)
      require('ufo').setup()
    end ,
}
```

**Comment by i-am-the-slime** [comment]
Thanks that makes a lot of sense, I've only been fiddling with Lua since the day before yesterday and assumed `{` was for blocks and some kind of objects.

Finally got it to work, thanks so much. 
Sending a lot of love for the help!

**Comment by victororlyk** [comment]
i don't know why but when i put 
```
                        smartindent = true,
                        foldexpr = "nvim_treesitter#foldexpr()", -- set Treesitter based folding
                        foldmethod = "expr",
```  
I am not able to fold with error `No fold found`
but when i do `:set foldmethod = indent` it just works

here is my full config https://github.com/victororlyk/astronvim_config/blob/main/init.lua
