### ISSUE TITLE
mason-lspconfig `automatic_installation` configuration  takes not effect

### ISSUE THREAD

**Issue by ypli0629** [AstroNvim/AstroNvim#1282]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.6.3

### Neovim version (>= 0.8)

NVIM v0.8.0

### Operating system/version

macOS 13.0

### Describe the bug

mason-lspconfig `automatic_installation` configuration  takes not effect

### Steps to Reproduce

["mason-lspconfig"] = {
  automatic_installation = true
}

### Expected behavior

auto install lsp servers

**Comment by jayp0521** [comment]
This works fine for me

https://github.com/jayp0521/dotfiles/blob/main/shell/.config/nvim/lua/user/lsp/servers.lua

https://github.com/jayp0521/dotfiles/blob/main/shell/.config/nvim/lua/user/plugins/mason-lspconfig.lua

I have to run `:AstroReload` before it took affect though

**Comment by mehalter** [comment]
Yeah this is mainly because we load `mason-lspconfig` after `lspconfig`. Not sure the best way to separate this out. I'll give it a think though

**Comment by mehalter** [comment]
@jayp0521 makes sense that it works when you `:AstroReload` because it resources the `servers.lua` file again and the `mason-lspconfig` plugin is already running

**Comment by jayp0521** [comment]
you should be able to take advantage of
```
    require("mason-lspconfig").setup_handlers {
        -- The first entry (without a key) will be the default handler
        -- and will be called for each installed server that doesn't have
        -- a dedicated handler.
        function (server_name) -- default handler (optional)
            require("lspconfig")[server_name].setup {}
        end,
        -- Next, you can provide a dedicated handler for specific servers.
        -- For example, a handler override for the `rust_analyzer`:
        ["rust_analyzer"] = function ()
            require("rust-tools").setup {}
        end
    }
```

**Comment by mehalter** [comment]
Setup handlers will not be triggered or relevant to automatically installing the language servers.

**Comment by jayp0521** [comment]
> Setup handlers will not be triggered or relevant to automatically installing the language servers.

That is correct. I meant you can take `servers.lua` and pass it into `ensure_installed` instead. Then use `setup_handlers` if you need to so it takes over setting up the `lsp`

**Comment by mehalter** [comment]
Yeah the main thing is we want to have a level of separation for users that have language servers installed locally and don't want to use mason for some

**Comment by mehalter** [comment]
@ypli0629 I will say I do think it's slightly better practice in AstroNvim to separate the list of mason-lspconfig ensure installed and the `lsp.servers` list to know which ones are being installed and which ones are provided locally

**Comment by mehalter** [comment]
I also just realized, the user might think that `automatic_installation` might be automatically installing servers when you load filetypes. Which I just want to clarify it won't do, it only automatically installs language servers that are set up with lspconfig

**Comment by ypli0629** [comment]
> I also just realized, the user might think that `automatic_installation` might be automatically installing servers when you load filetypes. Which I just want to clarify it won't do, it only automatically installs language servers that are set up with lspconfig

I setup lspconfig server after `mason-lspconfig`, but it also seem to take no effect. when I place some log code into [https://github.com/williamboman/mason-lspconfig.nvim/blob/main/lua/mason-lspconfig/lspconfig_hook.lua#L57](https://github.com/williamboman/mason-lspconfig.nvim/blob/main/lua/mason-lspconfig/lspconfig_hook.lua#L57), it only print the server name which have been installed , I can't figure out what cause this.

**Comment by mehalter** [comment]
How are you setting up the server with `lspconfig`

**Comment by mehalter** [comment]
I have fixed the ordering of setting up servers defined in `lsp.servers` to happen after `mason-lspconfig` if it is available on `nightly`. I think I can go ahead and close this now.
