### ISSUE TITLE
How to see LSP Code Lenses?

### ISSUE THREAD

**Issue by i-am-the-slime** [AstroNvim/AstroNvim#1284]
### Question

I found [this](https://github.com/neovim/neovim/pull/13165/files#diff-6b5f3071d65558aab177912061ac6a2f5312660655a449276c83697686f28e72R1583-R1594) as a reference on how to do this.

Now I tried to add this in my config as below but it doesn't show anything

### User Configuration

```lua
  polish = function()

    -- Insert copilot suggestion on Control + Enter
    local copilot_options = { silent = true, expr = true, script = true }
    vim.api.nvim_set_keymap("i", "<C-cr>", "copilot#Accept(<Tab>)", copilot_options)

-- 👇🏾👇🏾👇🏾
    vim.api.nvim_create_augroup("code_lens_", {})
    vim.api.nvim_create_autocmd(
        { "BufEnter", "CursorHold", "InsertLeave" },
        { callback = function() vim.lsp.codelens.refresh() end,
          group = "code_lens_",
          pattern = "*.purs",
        }
    )
    -- Set up custom filetypes
    -- vim.filetype.add {
    --   extension = {
    --     foo = "fooscript",
    --   },
    --   filename = {
    --     ["Foofile"] = "fooscript",
    --   },
    --   pattern = {
    --     ["~/%.config/foo/.*"] = "fooscript",
    --   },
    -- }

  end,
```

**Comment by i-am-the-slime** [comment]
Okay it was the pattern. What's the right syntax for it?

**Comment by i-am-the-slime** [comment]
Also it only seems to trigger on `BufEnter`

**Comment by mehalter** [comment]
@i-am-the-slime I believe the way you would want to do this is to build it into your own custom `lsp.on_attach` function. Here is an example that will create auto commands for all buffers with a language server client that supports codelens:

```lua
return {
  lsp = {
    on_attach = function(client, bufnr)
      if client.server_capabilities.codeLensProvider then
        vim.api.nvim_create_autocmd(
          { "BufEnter", "CursorHold", "InsertLeave" },
          { callback = function() vim.lsp.codelens.refresh() end, buffer = bufnr }
        )
      end
    end,
  },
}
```

I have tested this and it works great. Also just a heads up I am investigating getting code lens integrated with AstroNvim out of the box, but haven't had time to finalize it. Just as a preview as to what's to come :) Until I get the time, this should do automatic codelens refreshing!

One way to test this is to add a `vim.notify` call to see when it refreshes:

```lua
return {
  lsp = {
    on_attach = function(client, bufnr)
      if client.server_capabilities.codeLensProvider then
        vim.api.nvim_create_autocmd({ "BufEnter", "CursorHold", "InsertLeave" }, {
          callback = function()
            vim.notify "CodeLens Refresed"
            vim.lsp.codelens.refresh()
          end,
          buffer = bufnr,
        })
      end
    end,
  },
}
```

**Comment by i-am-the-slime** [comment]
Yes, that works much better, thanks. The comment on the `polish` function said it would be a good idea to put autocommands there and I was afraid that `onAttach` might leak creating new autocommands on every lsp "attaching" to a buffer.

**Comment by mehalter** [comment]
ah true true @i-am-the-slime , another way you could do this is that you could do this:

```lua
return {
  lsp = {
    on_attach = function(client, bufnr)
      if client.server_capabilities.codeLensProvider then
        local group_name = "codelens_" .. bufnr
        vim.api.nvim_create_augroup(group_name, { clear = true })
        vim.api.nvim_create_autocmd({ "BufEnter", "CursorHold", "InsertLeave" }, {
          group = group_name,
          callback = function() vim.lsp.codelens.refresh() end,
          buffer = bufnr,
        })
      end
    end,
  },
}
```

This will basically recreate the autocmd for each buffer whenever a codelens capable lsp attaches, but it will clear the group each time it creates it so you will only have one autocmd per buffer. Basically just dynamically creates the group names to use the buffer number to make sure there are no collisions
