### ISSUE TITLE
disable format_on_save on a per file basis

### ISSUE THREAD

**Issue by dohsimpson** [AstroNvim/AstroNvim#1286]
### Question

Is it possible to disable format_on_save for a particular file? For example, by putting a vim line at the bottom, like this:

![image](https://user-images.githubusercontent.com/5865309/201130971-2328c3e8-22c6-48f2-86ad-9aad55cac79b.png)

Thanks!

**Comment by mehalter** [comment]
Hm, we don't have this as a feature currently for the line definition. One thing we do have is a UI toggle for the auto formatting. So if a language server is attached and is doing auto formatting you can do `<leader>uf` to disable the auto formatting on save

**Comment by mehalter** [comment]
this can also be controlled through our Lua API with `astronvim.ui.toggle_autoformat()` or in the editor with `:lua astronvim.ui.toggle_autoformat()`.

You can also add the option:

```lua
return {
  options = {
    g = {
      autoformat_enabled = false, -- enable or disable auto formatting at start (lsp.formatting.format_on_save must be enabled)
    },
  },
}
```

to disable the autoformatting on save by default on start and then you can use `<leader>uf` to enable/disable it

**Comment by mehalter** [comment]
Awesome! Post back if you find a good solution for your setup!

**Comment by dohsimpson** [comment]
Using a modeline to set auto formating doesn't seem possible, because modeline only supports options for `set`, (e.g. `set et`).

But I did solve my problem by configuring my formatter (shfmt), which was behaving un-desirably, by adding command line argument to it.

example:

```
plugins.init = {
  ["null-ls"] = function(config)
    local null_ls = require "null-ls"
    config.sources = {
      null_ls.builtins.formatting.shfmt.with {
        filetypes = { "sh", "zsh" },
        extra_args = { "-i", "2", "--bn", "--ci", "--kp", "--sr" },
      },
    }
}
```
