### ISSUE TITLE
Javascript/Tsypscript

### ISSUE THREAD

**Issue by itsOdell** [AstroNvim/AstroNvim#1287]
### Question

Hello there! This is an amazing project but I have yet to use it. This would be my first vim experience so I wanted to ask a question: will the config be automatically be ready for javassctipt/ttypescript? like code completions, auto suggestions, error and stuff like that.

Have a great day man!

**Comment by itsOdell** [comment]
and if not, how can I configure it to work?

**Comment by mehalter** [comment]
It will not. The config will not automatically install language servers or anything out of the box. The main thing you probably want to do is decide what language server you want to use (probably `tsserver`) and what formatters (probably `prettier`)

Installing highlighting parsers (same for any language that is supported): `:TSInstall javascript typescript`

Installing `tsserver`: `:LspInstall tsserver`

Install `prettier`: `:NullLsInstall prettier`

All of these can also be set up in a User configuration file to be automatically installed with a simple configuration like this:

```lua
return {
  plugins = {
    treesitter = {
      ensure_installed = { "javascript", "typescript" },
    },
    ["mason-null-ls"] = {
      ensure_installed = { "prettier" },
    },
    ["mason-lspconfig"] = {
      ensure_installed = { "tsserver" },
    },
  },
}
```

This would get you the basic javascript/typescript support. I would recommend checking out the docs to see how to use AstroNvim:

- Getting Started Guide: https://astronvim.github.io/
- Basic Walkthrough: https://astronvim.github.io/Basic%20Usage/walkthrough
- Setting Up a User Configuration: https://astronvim.github.io/Configuration/basic_configuration

**Comment by mehalter** [comment]
Once you get the treesitter parsers, language servers, and formatters installed (this is a similar process for any language you might want to use) then the editor is good to go for that language! We don't install any out of the box just because everyone has different needs and we don't want to force people to install unnecessary stuff onto their system

**Comment by mehalter** [comment]
You can also browse the available language servers and things that you can install with AstroNvim by running `:Mason` or the keybinding `<leader>pI` to open a graphical browser for packages (our leader key is `<space>`)
