### ISSUE TITLE
PackerSync Broken

### ISSUE THREAD

**Issue by N8Brooks** [AstroNvim/AstroNvim#1295]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.6.5

### Neovim version (>= 0.8)

0.8.0

### Operating system/version

Ubuntu 20

### Describe the bug

Running `nvim +PackerSync` began failing at: [this commit](https://github.com/AstroNvim/AstroNvim/commit/00a703c96ecbb1ae3c8483fdc9919898a214fa06) for me.

It gives the following output, however, I remember it looking a little different initially. Something about `autocmd` or something.

```
Error detected while processing command line:
E492: Not an editor command: PackerSync
Press ENTER or type command to continue
```

### Steps to Reproduce

`nvim +PackerSync`

### Expected behavior

PackerSync should do what PackerSync normally does.

### Additional Context

Installed neovim by moving the 0.8.0 [stable] appimage to /usr/bin/nvim.

**Comment by mehalter** [comment]
Please see #1294

**Comment by N8Brooks** [comment]
Thanks
