### ISSUE TITLE
How do I disable the infurating automatic insert of `()` after importing a function?

### ISSUE THREAD

**Issue by i-am-the-slime** [AstroNvim/AstroNvim#1296]
### Question

I think this is `funcParensDisabled` from `nvim-autopairs` but I don't know where to enable this.
I use purescript and you apply functions with space (` `) rather than `()` so it's very annoying to have to delete the parens again.

**Comment by mehalter** [comment]
I'm not sure @i-am-the-slime, I don't know all the ins/outs of configuring `nvim-autopairs. I noticed that you did open an issue on the `nvim-autopairs` repo. That's definitely a better place to put it. Hopefully they provide some documentation!

**Comment by oryband** [comment]
solution https://github.com/AstroNvim/AstroNvim/issues/1574#issuecomment-1427023701
