### ISSUE TITLE
`:PackerSync E492: Not an editor command: PackerSync`

### ISSUE THREAD

**Issue by laurazard** [AstroNvim/AstroNvim#1299]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.6.5

### Neovim version (>= 0.8)

NVIM v0.8.0

### Operating system/version

13.0

### Describe the bug

Since the last AstroNvim version, running `:PackerSync`, `:PackerClean`, etc. (any of the `Packer` commands) results in a
```
E492: Not an editor command: Packer[xxx]
```
error message.

I suspect this is related to the changes in https://github.com/AstroNvim/AstroNvim/commit/00a703c96ecbb1ae3c8483fdc9919898a214fa06

### Steps to Reproduce

1. Update to AstroNvim `v2.6.5`
2. Try to run `:PackerSync:

### Expected behavior

Packer runs and attempts to update the configured plugins

**Comment by mehalter** [comment]
Please see #1294
