### ISSUE TITLE
What plugin / setting is creating this UI element when bufferline is disabled?

### ISSUE THREAD

**Issue by alexandersix** [AstroNvim/AstroNvim#1302]
### Question

Hello! I'm trying to figure out what plugin/settings that I have to edit in order to change the background color of this UI element (`~/d/a/init.lua`). Since the latest update, it has become bright pink (I've highlighted it in the screenshot below to make it readable).

I've poured over the documentation, but I may have just missed something. It seems like this shows up even in the vanilla AstroNvim install when the bufferline is disabled, but I'm not sure what plugin is creating it.

Thanks for pointing me in the right direction!

<img width="1174" alt="image" src="https://user-images.githubusercontent.com/11881203/201544890-9ff94e5e-a1a0-41c2-b604-e1f87441c59d.png">

**Comment by mehalter** [comment]
@alexandersix this is because we are  setting `showtabline=2`, you just want to add to your options, `showtabline=0`:

```lua
return {
  options = {
    opt = {
      showtabline = 0,
    },
  },
}
```

**Comment by alexandersix** [comment]
Ah, TABLINE! The one place I didn't look. Really appreciate it!
