### ISSUE TITLE
Disable mappings so that they do not appear on which-key

### ISSUE THREAD

**Issue by axdank** [AstroNvim/AstroNvim#1303]
### Question

I would like to know how to have the mappings without them appearing in which-keys. 

`mappings.lua`
![imagen](https://user-images.githubusercontent.com/55039048/201545467-379019ca-e301-4506-83f1-aa91c1711b30.png)

`which-key.lua`
![imagen](https://user-images.githubusercontent.com/55039048/201545495-2854a965-0adf-4963-886c-6b3d8953034e.png)

I do not want the `r` option and the `dap` option to be displayed when `d` is ungrouped.
![imagen](https://user-images.githubusercontent.com/55039048/201545562-93ff7f60-b449-4f35-9ac7-afc1c876042e.png)

after pressing `r`
![imagen](https://user-images.githubusercontent.com/55039048/201545576-1aa6378c-084d-4e6e-8934-7387705a38ae.png)

after pressing `d`
![imagen](https://user-images.githubusercontent.com/55039048/201545583-1bc55f39-6eda-42bf-b102-6ea6e8a3d346.png)

I would like to have the mappings but without them being loaded in `which-key`

**Comment by mehalter** [comment]
we currently have `which-key` filling in everything that is available. The easeiest way would be to remove the `desc` parts which will cause `which-key` to not fill them. Another way would be to set the registration of those keys in `which-key` to the value `"which_key_ignore"` (Check out the `which-key` docs here: https://github.com/folke/which-key.nvim#%EF%B8%8F-mappings)

**Comment by kaka-ruto** [comment]
I was trying to disable a command mode keymap from appearing on which-key but it is not working.

I have the following on my `mappings.lua`

```
  c = {
    -- Alternate files
    ["AL"] = { [[:Other]], noremap = true, silent = true },
  },
```

I want whenever I type :AL in command mode, it maps to :Other, without opening up which-key. When it opens up which-key, it obscures other commands that start with :A but are not on which-key

I tried to let which-key ignore this mapping but it does something weird, it doesn't show up on which-key, but the moment I press :A, it blinks for a sec and enters another command mode, and then typing out L and enters gets me a `Not an editor command` error

`core.lua` has the following

```
  {
    "folke/which-key.nvim",
    config = function(plugin, opts)
      require "plugins.configs.which-key" (plugin, opts) -- include the default astronvim config that calls the setup call
      -- Add bindings which show up as group name
      local wk = require "which-key"
      wk.register({
        AL = "which_key_ignore",
      }, { mode = "c" })
    end,
  },
```
