### ISSUE TITLE
How to hide some code?

### ISSUE THREAD

**Issue by hitfm00** [AstroNvim/AstroNvim#1306]
### Question

For example I have this code and want to hide like in vscode just click to the arrow in the left of the code.
I tried `<space> + z + a `but it doesn't work

<img width="1021" alt="Снимок экрана 2022-11-14 в 02 23 54" src="https://user-images.githubusercontent.com/21322208/201552622-b299435e-8c97-4d64-b785-89af81a4e170.png">

**Comment by i-am-the-slime** [comment]
just z a?

**Comment by mehalter** [comment]
Look into folding:

https://vim.fandom.com/wiki/Folding

https://www.jmaguire.tech/posts/treesitter_folding/

https://github.com/kevinhwang91/nvim-ufo
