### ISSUE TITLE
How to do column selection in turbovnc

### ISSUE THREAD

**Issue by laowalter** [AstroNvim/AstroNvim#1307]
### Question

I can use Ctrl+v in termical, but in my vnc enviroment, Ctrl+v is set to paste. I have did lots of search, cost muc time,  still have no idea. coz using AstroNvim,  just ask this, thanks for your help!

**Comment by mehalter** [comment]
This will be up to your terminal emulator. TurboVNC will get getting and devouring the keypress before it gets to any terminal application. You'll have to see if you can configure TurboVNC to remove or change this binding
