### ISSUE TITLE
Lazy git doesn't work, flashes open for a micro second then quits

### ISSUE THREAD

**Issue by algoflows** [AstroNvim/AstroNvim#1312]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.6.5

### Neovim version (>= 0.8)

0.8

### Operating system/version

macOS Monterey 12.6.1 (21G217)

### Describe the bug

Lazy git doesn't work, it flashes open for a micro second then closes.

When using both <leader> tl or <leader> gg lazy git doens't open

### Steps to Reproduce

- Open any project
- Make changes to a file
- <leader> tl or <leader> gg
- fails to open lazy git

### Expected behavior

opens lazy git when using leader and lazy git commands

### Screenshots

can't take a screenshot the action happens so quickly, lazy git borders are seen for a nano second and then it auto quits.

**Comment by mehalter** [comment]
@algoflows do you have lazygit installed and have verified that it's in your path?

**Comment by mehalter** [comment]
if you open a terminal in AstroNvim with something like `:term` and then run `lazygit` what do you get?

**Comment by algoflows** [comment]
Sorry everyone thanks for help, didint have lazygit installed. New to vim here . Thanks for all the responses.
