### ISSUE TITLE
Colorscheme not working

### ISSUE THREAD

**Issue by abrausch** [AstroNvim/AstroNvim#1313]
### Question

Hi, I have a problem changing the colorscheme. 
I have the attache config.
I also changed the bootstrap.lua to get more information. 
I changed it to:
```lua
astronvim.initialize_packer()

local colorscheme = astronvim.user_plugin_opts("colorscheme", nil, false)
print("xxxx")
print(colorscheme)
print(vim.tbl_contains(vim.fn.getcompletion("", "color"), colorscheme) and colorscheme or "default_theme")
print("xxxx")
vim.cmd.colorscheme(vim.tbl_contains(vim.fn.getcompletion("", "color"), colorscheme) and colorscheme or "default_theme")
````

The output is:
xxxx
tokyonight
default_theme
xxxx

Could you point me to my error?

Thanks in advance 
Alex

### User Configuration

```lua
local config = {

    -- Set colorscheme
    colorscheme = "tokyonight",
    plugins = {
        init = {
            {
                "folke/tokyonight.nvim",
                as = "tokyonight",
                config = function()
                    require("tokyonight").setup {}
                end
            }
        }
    }
}
return config
```

**Comment by mehalter** [comment]
@abrausch have you run packersync to install tokyonight?

**Comment by mehalter** [comment]
@abrausch I just tested the code that you sent and it works perfectly. Just make sure that you run `:PackerSync` any time you modify the `plugins.init` table so that packer can  recompile it's file and the plugins install/remove that need to.
