### ISSUE TITLE
Lost Packer after update to `2.6.5`

### ISSUE THREAD

**Issue by badjr13** [AstroNvim/AstroNvim#1314]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.6.5

### Neovim version (>= 0.8)

NVIM v0.8.0

### Operating system/version

Ubuntu 22.04.1 LTS

### Describe the bug

I updated `AstroVim` yesterday to `2.6.5` and lost `Packer` during the update. After running `AstroUpdate` and restarting `nvim`, I no longer have access to any `Packer` commands.

I had to check `:PackerSync` in the checklist above or else I could not submit the issue, but it is inaccurate to say that I have run `:PackerSync` as I am not able to currently.

### Steps to Reproduce

1 - `nvim`
2 - `:AstroUpdate`
3 - Restart `nvim`
4 - I went to run `:PackerSync` and I get the following
```
:PackerSync
E492: Not an editor command: PackerSync
Press ENTER or type command to continue
```

### Expected behavior

I should have access to `Packer` and should be able to complete my update by running `:PackerSync`. I also tried using the keyboard shortcut, `SPC p s` provided by `AstroVim` to run the sync which leads to the same error  message.

### Additional Context

I love using vim but I am not heavily invested in configuring it myself, that's why I gravitated toward AstroVim. I'm a developer but don't have a ton of free time to spend looking into this fix, however, if a contributor is able to identify the problem and point me in the right direction, I may be able to open up a PR for it.

**Comment by mehalter** [comment]
Duplicate #1294

**Comment by badjr13** [comment]
Sorry about that. Forgot to check the closed issues.

**Comment by mehalter** [comment]
No problem! Glad you got it back up and running!  For important issues, I will pin them, so they will still show up at the top of the issues page even if you are just in the open issues.
