### ISSUE TITLE
How to hide the diagnostic hints in a open buffer?

### ISSUE THREAD

**Issue by DeeGeeMan** [AstroNvim/AstroNvim#1315]
### Question

Is there a way to hide the diagnostic hints in the open buffer?  My buffer lights up like a Christmas tree when there are a lot of issues detected.

Example:
![image](https://user-images.githubusercontent.com/21670040/201958408-7ace0121-585f-42a7-b5e6-272602f57012.png)

**Comment by mehalter** [comment]
@DeeGeeMan you can do this in your `diagnostics` table in `user/init.lua`. This lets you customize the `vim.diagnostic.config` call, you can see all available options in `:h vim.diagnostic.config`. Here is a minimal `user/init.lua` file that just removes the virtual text from the diagnostics:

```lua
return {
  diagnostics = {
    virtual_text = false,
  },
}
```

**Comment by DeeGeeMan** [comment]
I couldn't get it to work in the folder structure below...

![image](https://user-images.githubusercontent.com/21670040/201964886-8de2798b-c8b1-475b-b176-ecf50bf73312.png)

**Comment by mehalter** [comment]
It should just go into `user/diagnostics.lua` as described here: https://astronvim.github.io/Configuration/config_options

**Comment by DeeGeeMan** [comment]
Thanks!
