### ISSUE TITLE
Vimwiki colors for list and tags are being set to orange (fg and bg) 

### ISSUE THREAD

**Issue by ecaneteok** [AstroNvim/AstroNvim#1317]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.6.0

### Neovim version (>= 0.8)

NVIM 0.8

### Operating system/version

Ubuntu 22.04

### Describe the bug

Hi,
Vimwiki colors for list and tags are being set to orange (fg and bg) so when building a task list in vimwiki it is being shown like a orange square, the checkbox and background cannot be differentiated.
I've tried to customize the colors from the user\init.lua config file without success.
What are the steps to customize colors for plugins like Vimwiki from user configuration file?
Is there a command that need to be run after the change in the config file to see color changes reflected?

Thanks in advance.
Emiliano Cañete

### Steps to Reproduce

1- MakeVimWikiDiary
2- Type "* [ ] This is a test"
3- An orange square is going to be shown instead of "* [ ]"

### Expected behavior

A colorized tag "* [ ] " needs to be shown.

**Comment by mehalter** [comment]
I cannot replicate the behavior you are describing

![2022-11-15_15:07:29_screenshot](https://user-images.githubusercontent.com/1591837/202015324-f03888f0-7397-4d5b-90c5-c2b934bba60c.png)

**Comment by ecaneteok** [comment]
Hi ,
I've attached below an screenshot and my user/init.lua config file.

Thanks in advance.
Emiliano Cañete

![Vimwiki_Screenshot 2022-11-15 203619](https://user-images.githubusercontent.com/45297666/202047401-b42a3c55-68f9-451f-9a50-d67253524516.jpg)
[init.lua.txt](https://github.com/AstroNvim/AstroNvim/files/10016893/init.lua.txt)

**Comment by mehalter** [comment]
@ecaneteok what terminal are you using? It looks like it probably doesn't support true colors

**Comment by ecaneteok** [comment]
I am using Windows Terminal app on Windows 10. Thanks

**Comment by mehalter** [comment]
@ecaneteok could you run this in your terminal and see what the output is?

```sh
awk 'BEGIN{
    s="/\\/\\/\\/\\/\\"; s=s s s s s s s s;
    for (colnum = 0; colnum<77; colnum++) {
        r = 255-(colnum*255/76);
        g = (colnum*510/76);
        b = (colnum*255/76);
        if (g>255) g = 510-g;
        printf "\033[48;2;%d;%d;%dm", r,g,b;
        printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
        printf "%s\033[0m", substr(s,colnum+1,1);
    }
    printf "\n";
}'
```

**Comment by mehalter** [comment]
Also could you please provide a screenshot of the output of the command?

**Comment by ecaneteok** [comment]
Here is the output:
![Color Test Screenshot 2022-11-15 212220](https://user-images.githubusercontent.com/45297666/202052944-d772dd62-5bc3-483f-a29b-4a780edaa650.jpg)

Also, I found this color config in ~/.config/nvim/lua/default_theme/plugins/vimwiki.lua file,I am not sure if it is related to the issue.
![Vimwiki Screenshot 2022-11-15 211636](https://user-images.githubusercontent.com/45297666/202052299-23b56872-0e2a-45a7-a20f-00c3ab737d7c.jpg)
Thanks

**Comment by mehalter** [comment]
oh interesting, I wonder why this was done and why it didn't show up when I tested it 🤔  I will change this! Thanks for investigating!

**Comment by mehalter** [comment]
I went ahead and fixed this in `nightly` :) Could you try the `nightly` branch and see if that resolves it?

**Comment by ecaneteok** [comment]
Awesome! Yes sure, I am going to try the nightly branch then!
Another questions: 
Is there a way to override that configuration from /user/init.lua ? Could you please provide an example?
Is there a command that needs to be run after change the color configs?

Thanks for your quick response!

**Comment by mehalter** [comment]
@ecaneteok there isn't, just need to pull and restart
