### ISSUE TITLE
non-default plugins don't load after upgrade

### ISSUE THREAD

**Issue by azinsharaf** [AstroNvim/AstroNvim#1319]
### Question

I did a fresh install for 2.6.5 version (with stable channel) and I noticed that all the non-default plugins under `plugins / init` table doesn't load. Any idea what i am missing?

**Comment by mehalter** [comment]
@azinsharaf did you follow #1294?

**Comment by azinsharaf** [comment]
it works now after a complete fresh reinstall. thanks!
