### ISSUE TITLE
How to disable cmdline-window on "q:" ?

### ISSUE THREAD

**Issue by gzzinx** [AstroNvim/AstroNvim#1320]
### Question

Is there way to disable a [cmdline-window opening](https://vimhelp.org/cmdline.txt.html?#cmdline-window) on "q:" chord?
I've found this [stackoverflow answer](https://stackoverflow.com/questions/50521331/how-to-disable-command-history-q-in-vim) and I've tried insert 
```
                vim.cmd([[
                nnoremap q: <nop>
                ]])
```
in polish() function and also `["q:"] = false,` in `mappings.n` and it both doesnt' work.

**Comment by mehalter** [comment]
Could you try `["q:"] = "<nop>"` in your `mappings.n` table?

**Comment by mehalter** [comment]
The `false` will let you remove our default mappings. To remove core Neovim mappings you will need to map them to `"<nop>"

**Comment by gzzinx** [comment]
@mehalter  No, it doesn't work :( Keeps triggering

**Comment by mehalter** [comment]
ah maybe it needs to be capitalized. I can confirm that this minimal `user/init.lua` disables the menu:

```lua
return {
  mappings = {
    n = {
      ["q:"] = "<Nop>",
    },
  },
}
```

**Comment by gzzinx** [comment]
To be clear, it doesn't work completely.
It disables triggering only for instant pressing `q:`, but if you press `q` and then press `:` after even 0.5 sec delay it stll triggers the cmdline-window. I've checked it in multiple distros in docker and VM.
Maybe there is a way to disable it totally?

**Comment by mehalter** [comment]
I'm not sure :/ might be a question for r/Neovim

**Comment by mehalter** [comment]
There are probably some options that need to be passed to the keymap set function that will handle the case maybe?

**Comment by gzzinx** [comment]
It works really strange. I've tried to do this in clear neovim with [this guide](https://blog.devgenius.io/create-custom-keymaps-in-neovim-with-lua-d1167de0f2c2) and it does the same in clear neovim. Disables cmdline-window opening for fast pressing `q:` but doesn't disable for `q-delay-:`. 
```
function map(mode, lhs, rhs, opts)
    local options = { noremap = true }
    if opts then
        options = vim.tbl_extend("force", options, opts)
    end
    vim.api.nvim_set_keymap(mode, lhs, rhs, options)
end

map("n", "q:", "<Nop>")
map("i", "jj", "<Esc>")
```
