### ISSUE TITLE
autopairs not disabled on TelescopePrompt?

### ISSUE THREAD

**Issue by sbeyer** [AstroNvim/AstroNvim#1321]
### Question

In Commit cf5130947fbd1ca793813dcf935203cf9bfa6de9, the `TelescopePrompt` has been removed from the list of filetypes for which `autopairs` is disabled. This is in contradiction [to the documentation](https://astronvim.github.io/Configuration/plugin_defaults#autopairs).

Is the change intentional? If so, how can I get it back to disable autopairs on `TelescopePrompt` with my user configuration (maybe without copying the whole autopairs configuration -- I don't want to repeat; that would be maintenance hell)?

**Comment by mehalter** [comment]
Ah this is a mistake, that line should have been removed all together. We should just be using the default in this case which includes `TelescopePrompt`. I have fixed this in the latest `nightly`. This should get released sometime this week to stable!

**Comment by sbeyer** [comment]
Works like a charm again :)
