### ISSUE TITLE
What is vim.go?

### ISSUE THREAD

**Issue by trankchung** [AstroNvim/AstroNvim#1325]
### Question

What is this vim.go that you used in line below? I tried googling but it all sent me to golang related stuff.

What I’m trying to do is detect the color scheme and change the bufferline background highlight and I’m researching on how to do that.

 Thanks. 

https://github.com/AstroNvim/AstroNvim/blob/c32e0928714ce4e711d9245d33a663652536f469/lua/core/utils/ui.lua#L64

**Comment by mehalter** [comment]
https://github.com/nanotee/nvim-lua-guide#using-meta-accessors

**Comment by trankchung** [comment]
Never mind found the answer :P. It’s to set/get global options.
