### ISSUE TITLE
neo-tree update failed

### ISSUE THREAD

**Issue by As2aic** [AstroNvim/AstroNvim#1326]
### Question

Command: " :PackerSync "
Output:  ✗ Failed to update nvim-neo-tree/neo-tree.nvim/v2.x

**Comment by mehalter** [comment]
@As2aic did you try it multiple times? sometimes there is downtime in github and it might return an error like this

**Comment by As2aic** [comment]
@mehalter while trying to install nvim-tree i might have synced it multiple times.

**Comment by mehalter** [comment]
I'm  not sure, maybe just keep trying and see if it fixes itself? You might want to join the discord and ask if anyone else has had similar problems. This is definitely related to network connectivity and resolution with GitHub. Also could be that you have a faulty installation for some reason and you need to uninstall/reinstall it by deleting the folder in your `~/.local/share/nvim/site` folder
