### ISSUE TITLE
Add nvim-bqf

### ISSUE THREAD

**Issue by Cretezy** [AstroNvim/AstroNvim#1332]
### Is your feature related to a problem?

The quickfix list in Vim/Neovim is light on features by default. No way to open a fix + close, no preview, etc.

### Describe the new feature

Adding https://github.com/kevinhwang91/nvim-bqf would drastically improve the quickfix list in AstroNvim.

### Additional context

I've been personally using it with Astro without issues. Astro could possibly customize the binds a bit to bring it more inline with the Telescope scrolling for example, but defaults work well enough.

When using `gr`, it's _similar_ to the LSP references with Telescope (with `<leader>lR` by default), however quickfix is used is more places than just references.

**Comment by mehalter** [comment]
I've played around with this a bit and haven't found a set up that I think plays nicely with everything. Feel free to put it in your User config and let me know if you have a decent configuration and I can take a look at it and test it out.
