### ISSUE TITLE
How to display the curly line for diagnostics?

### ISSUE THREAD

**Issue by DeeGeeMan** [AstroNvim/AstroNvim#1336]
### Question

By default, all diagnostics are shown as underlined in the buffer.  How do I change it to be a curly line like the screenshot in your Git repo?

**Comment by mehalter** [comment]
Are you using a different theme? The default theme does this automatically. Another thing is to make sure that your terminal supports undercurl

**Comment by DeeGeeMan** [comment]
Yes, I am using the default theme. However, I am also using [Alacritty](URL) as my default terminal.  Which one are you using?

**Comment by mehalter** [comment]
@DeeGeeMan looks like alacritty added undercurl support in February: https://github.com/alacritty/alacritty/issues/1628

**Comment by mehalter** [comment]
I just installed Alacritty and I'm seeing undercurl with the default theme and a fresh installation:

![2022-11-16_14:58:20_screenshot](https://user-images.githubusercontent.com/1591837/202281688-6a9ef493-ae91-4835-bfe6-1113556a7a37.png)

**Comment by DeeGeeMan** [comment]
Awesome, I will install the latest and see if I can get it to show up.  Thanks!

**Comment by DeeGeeMan** [comment]
It might be my tmux config too.

**Comment by mehalter** [comment]
https://www.reddit.com/r/neovim/comments/thhw77/no_undercurls_in_tmux_help/

Ah yeah, that might be a limitation as well

**Comment by DeeGeeMan** [comment]
I got it to work by adding the following lines to my `tmux.config`

```
# Undercurl
set -g default-terminal "alacritty"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0
```

**Comment by mehalter** [comment]
Awesome, thanks for sharing! This will be useful for anyone else that needs it 😄
