### ISSUE TITLE
How to disable this feature?

### ISSUE THREAD

**Issue by ilaipi** [AstroNvim/AstroNvim#1343]
### Question

When save a buffer it will add a space between `{}` to be `{ }`, how to disable this?

**Comment by kabinspace** [comment]
Are you using any formatter?

**Comment by ilaipi** [comment]
nothing, I think. Here is my customize config: 

https://github.com/ilaipi/nvim-customize/blob/main/init.lua

**Comment by mehalter** [comment]
@ilaipi what file types is this happening for? some of the language servers are you using? Some will provide formatters. Also have you installed anything to be used with `null-ls` they could also be formatters. If you are getting formatting on save then you definitely have a formatter running

**Comment by mehalter** [comment]
Here is also documentation on disabling formatting on save: https://astronvim.github.io/Recipes/advanced_lsp#customizing-auto-format-on-save
