### ISSUE TITLE
How to install plugin nvim-dap, nvim-dap-go, 

### ISSUE THREAD

**Issue by kutzhang** [AstroNvim/AstroNvim#1346]
### Question

I need to use plugin DAP and DAP-GO to debug my Golang application, but I can't see any plugin by TSInstall for them. 
How can I do?

**Comment by Juniar-Rakhman** [comment]
@kutzhang you can use my config as a reference. I got Go debug working using DAP:
https://github.com/Juniar-Rakhman/astronvim_config

**Comment by mehalter** [comment]
@Juniar-Rakhman thanks for sharing your config!

@kutzhang you will need to set up a user configuration to add plugins. You will need to add and configure [nvim-dap](https://github.com/mfussenegger/nvim-dap)
