### ISSUE TITLE
Issue with function to load rand color scheme on startup.

### ISSUE THREAD

**Issue by Namefailed** [AstroNvim/AstroNvim#1349]
### Question

I have some code in my polish section that is meant to generate a random number and then select a color scheme from a table with that number on startup. For some reason, the function doesn't output error but is only ever selecting the last item in the list. any help would be so appricatied 

### User Configuration

polish = function()
    -- Set custom colorscheme
    local schemelist = {
      "tokyonight-moon",
      "tokyonight-night",
      "carbonfox",
    }
    local rancolorscheme = math.random(1, #schemelist)
    vim.cmd("colorscheme " .. schemelist[rancolorscheme])

    -- Set copilot accept suggestion mapping
    vim.api.nvim_set_keymap("i", "<C-l>", "copilot#Accept('<CR>')", { expr = true, silent = true })
    -- Configure dashboard to start when all buffers are closed
    local function dashboard_on_close(cmd)
      local bufs = vim.fn.getbufinfo { buflisted = true }
      local wins = vim.fn.winnr "$"
      if wins > 1 and not bufs[2] then
        vim.cmd(cmd)
        vim.cmd [[silent only]]
      else
        vim.cmd(cmd)
      end
      if require("core.utils").is_available "alpha-nvim" and not bufs[2] then require("alpha").start(true) end
    end

    vim.keymap.del("n", "<leader>x")
    if require("core.utils").is_available "bufdelete.nvim" then
      vim.keymap.set("n", "<leader>x", function() dashboard_on_close "Bdelete!" end, { desc = "Close buffer" })
    else
      vim.keymap.set("n", "<leader>x", function() dashboard_on_close "bdelete!" end, { desc = "Close buffer" })
    end
  end,

**Comment by mehalter** [comment]
I'm not sure, I did do some test where I run `:lua print(math.random(1, 3))` then restarted neovim and ran it again and always get `3`. This could be something about random seeds being the same when you start neovim so the value could always be the same

**Comment by Namefailed** [comment]
dang. hmm, if you have any solutions or other functions that would work, let me know! :) Thanks!

**Comment by Namefailed** [comment]
I did get this working eventually, for anyone trying to do so in the future.

If it would be appreciated I can make a pull request for the recipes section of the website and add this as one but I'll put here for now.

@mehalter 

I have this in my polish section. Our issue is that you have to seed the random number before you can use the math.random func.
```
    local colorschemelist = { -- List of favorite custom colorschemes
      "tokyonight-moon",
      "tokyonight-night",
      "catppuccin",
      "catppuccin-mocha",
      "catppuccin-macchiato",
      "carbonfox",
    }
    -- Set colorscheme on startup and notify user
    ---@diagnostic disable-next-line: unused-local
    local randomseed = math.randomseed(os.time()) -- Set random seed
    local randomnumber = math.random(#colorschemelist) -- Get random colorscheme
    local randomcolorscheme = colorschemelist[randomnumber] -- Get random colorscheme
    vim.cmd("colorscheme " .. randomcolorscheme) -- Set colorscheme
    vim.notify = require("notify") -- Set notify to use nvim-notify
    vim.notify("  " .. randomcolorscheme, vim.log.levels.INFO, { title = "Colorscheme" }) -- Notify colorscheme on startup

```
