### ISSUE TITLE
Syntax highlighting in .go files (missing).

### ISSUE THREAD

**Issue by goget-milk** [AstroNvim/AstroNvim#1350]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.7.4

### Neovim version (>= 0.8)

NVIM v0.8.0

### Operating system/version

ArchLinux

### Describe the bug

Hi all!
There is no syntax highlighting in **.go** files.

[![maingo.png](https://i.postimg.cc/m2dv0nqY/maingo.png)](https://postimg.cc/fJ9qd8My)

All plugins are installed.
In files **.js .ts .py .sql**  etc - highlighting works!
How to set up **AstroNvim** syntax highlighting?

### Steps to Reproduce

-

### Expected behavior

-

### Screenshots

[![lspinfo.png](https://i.postimg.cc/vHw0Bwg7/lspinfo.png)](https://postimg.cc/XXxfHhgX)

[![tsinstall.png](https://i.postimg.cc/CLwbXhn2/tsinstall.png)](https://postimg.cc/0rH6JqfG)

**Comment by mehalter** [comment]
Does your statusline indicate that treesitter is running? Have you run `:TSInstall go`?

**Comment by goget-milk** [comment]
@mehalter 
Yes! I run `TSInstall go`

[![statusline.png](https://i.postimg.cc/cJTQdVqm/statusline.png)](https://postimg.cc/4K7K52x7)

**Comment by mehalter** [comment]
What colorscheme are you using? It could also be poor treesitter support in your colorscheme

**Comment by goget-milk** [comment]
@mehalter 
I use "NordFox" colorsheme.
I tried with other color themes i get the same.
I noticed something....
If I first disable syntax highlighting by pressing `space -> u -> y`
and then turn it on with the same key combination - syntax highlighting appears...
How to understand this situation... What's wrong with .go files ?

[![maingo.png](https://i.postimg.cc/6Q5gYxBJ/maingo.png)](https://postimg.cc/9DKLQS4J)

**Comment by mehalter** [comment]
I'm not sure, can you please share your user configuration file?

**Comment by goget-milk** [comment]
@mehalter 
[init.lua](https://drive.google.com/file/d/1dC6reqqych09b-jOazFmakU4iynpkDdq/view?usp=share_link)
same repeat link
[init.lua](https://disk.yandex.ru/d/EFExs9_UAbyeyg)

**Comment by mehalter** [comment]
@goget-milk it looks like this is the offending plugin: https://github.com/olivercederborg/poimandres.nvim

When I remove it from your config the issue goes away

**Comment by goget-milk** [comment]
@mehalter 
Thanks a lot! You are a God!
Problem solved, I'm insanely happy again!
P.S. I couldn't think of a color scheme that wasn't used

With best regards!

[![maingo.png](https://i.postimg.cc/WbdzzzKC/maingo.png)](https://postimg.cc/TpXfHdTJ)
