### ISSUE TITLE
How do you change the order of completion sources?

### ISSUE THREAD

**Issue by TheButlah** [AstroNvim/AstroNvim#1351]
### Question

Right now, AstroNvim gives snippets before lsp completions (like functions). How do I put the functions first?
Also, is there a difference between snippets from the LSP and non-lsp snippets?

**Comment by Vermoot** [comment]
Here's the documentation page that talks about this:
https://astronvim.github.io/Recipes/cmp

**Comment by mehalter** [comment]
It's also important to note that some LSP servers provide snippets. I know `rust_analyzer` for example provides snippets from the server and they will always take presidence over LSP symbols for some reason. I think someone on the Discord server did this and resolved it. It's a good place to ask for questions

**Comment by TheButlah** [comment]
In my case I am using `rust_analyzer` so thats exactly what I'm curious about. I'll ask in the discord and update here if I find an answer.

**Comment by mehalter** [comment]
Oh wait actually @TheButlah it was #1225 not on discord!
