### ISSUE TITLE
Not able to update with AstroUpdate command

### ISSUE THREAD

**Issue by duytrung** [AstroNvim/AstroNvim#1353]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.7.4

### Neovim version (>= 0.8)

0.8

### Operating system/version

Windows 10

### Describe the bug

I have git installed and exist in the command path but when I use AstroUpdate it showed this message:
![image](https://user-images.githubusercontent.com/2046672/202835719-fd6c510a-2ea4-4691-88a1-c0150838b6fd.png)

Here is the git:

### Steps to Reproduce

1. Run "git --version"
![image](https://user-images.githubusercontent.com/2046672/202835791-4af646c6-e7be-424d-961b-a838d989c14d.png)

2. Run nvim
![image](https://user-images.githubusercontent.com/2046672/202835814-d9794eb3-c57d-4b09-8dd9-367e14c01e2e.png)

3. Run ":AstroUpdate"
![image](https://user-images.githubusercontent.com/2046672/202835846-1133566c-8878-4a13-b7e4-8afe9244cee7.png)

### Expected behavior

I have the Ubuntu and did the same thing but AstroUpdate works

### Screenshots

(None)

### Additional Context

PackerSync is not available. 
![image](https://user-images.githubusercontent.com/2046672/202835994-8ca207fe-91bd-4783-9e16-d459aaa1bf56.png)

Run "AstroVersion" also did not work, and did not show anything

Thanks for consider the issue :-)

**Comment by breenbo** [comment]
Same here: all packer commands are gone (update, compile, sync).
AstroNvim : 2.7.4.-5-g777e31b
Neovim: v0.8.0

Thx.

**Comment by mehalter** [comment]
@duytrung @breenbo please see the pinned issues #1294 for the packer issue. 

@duytrung for the original issue if you open a terminal in AstroNvim with like `:term` what do you get if you run `git`?

**Comment by duytrung** [comment]
@mehalter thanks for your suggestion, I ran the ":term" and then run "git". This is the result:
![image](https://user-images.githubusercontent.com/2046672/203290424-541ce802-7647-4f60-a734-349cc5b640ba.png)

**Comment by teklabania** [comment]
Hi, same here, there are no Packer... commands since v2.6.5. When I checkout back to v2.6.4 everything gets back to normal.
NVIM v0.8.0 on Manjaro Linux

**Comment by mehalter** [comment]
@duytrung could you check out `nightly` branch manually by `cd`ing into the `~/.config/nvim` folder and running

```sh
git pull
git checkout nightly
```

and then start `nvim` and see if `:AstroUpdate` works correctly? I changed the logic for how we are checking if `git` is available, and if should be alright now :D

**Comment by binarad** [comment]
How can i fix this? Someone pls help me im suck in astrovim
![photo_2023-12-12_17-19-01](https://github.com/AstroNvim/AstroNvim/assets/67160928/b88fcd31-6b3e-4082-a102-517925013274)

**Comment by mehalter** [comment]
@binarad when you go to your `~/.config/nvim` directory, if you run `git status` what do you get?
