### ISSUE TITLE
Show Current Mode in Statusbar with letters (not only colors)

### ISSUE THREAD

**Issue by p4nchit0z** [AstroNvim/AstroNvim#1355]
### Question

Hi, I was wondering if there is a way to show current mode in Astrovim at the bottom bar. For example, if I'm in normal mode there could be an "N" letter in the statusbar, if I then change mode and I'm in Visual mode a it shows a "V" and so on... 

By the way, I know that at the bottom left/right of AstroVim there's a rectangle that changes color with the mode, but I just wanted to know if there is a way to add the mode at the side of it with letters, so you can complement both features (using colors and/or letters to identify which mode I'm currently in).

I played a little bit in the `user/init.lua` file, specifically with the parameter `options.opt`, but nothing worked

Here's an example taken from [https://github.com/EdenEast/nightfox.nvim](https://github.com/EdenEast/nightfox.nvim)
![image](https://user-images.githubusercontent.com/31874167/202842412-805c152c-f169-452c-acbb-fd26c625d5b4.png)

Cheers

**Comment by mehalter** [comment]
https://astronvim.github.io/Recipes/status#default-statusline-with-mode-text
