### ISSUE TITLE
Please help to disable auto-indent

### ISSUE THREAD

**Issue by cherez0ff** [AstroNvim/AstroNvim#1356]
### Question

I have a solution for usual (n)vim, but not for Astro, since it uses Lua stuff I guess.
I want to have effect of auto-applied setting set indentexpr='' (empty string) by default

If I just override it in "local config = { .. options = {..  opt = { .." - then it will be overridden again by nvim when I open format specific file (for py for example it will be indentexpr=python#GetIndent(v:lnum))

This is killing me. Please help!
btw great work

### User Configuration

```lua
  options = {
    opt = {
      -- set to true or false etc.
      -- relativenumber = true, -- sets vim.opt.relativenumber
      -- number = true, -- sets vim.opt.number
      -- spell = false, -- sets vim.opt.spell
      -- signcolumn = "auto", -- sets vim.opt.signcolumn to auto
      timeoutlen=500,
      background='dark',
      termguicolors = true,
      --nobackup = true,
      --noswapfile = true,
      --nowritebackup = true,
      wrap = true,
      mouse='a',
      clipboard='unnamedplus',
      ignorecase = true,
      hlsearch = true,
      incsearch = true,
      cursorline = true,
      number = true,
      relativenumber = true,
      history=100,
      softtabstop=2,
      tabstop=2,
      shiftwidth=2,
      expandtab = true,
      wildmenu = true,
      colorcolumn='120',
      indentexpr='',
    },
```

**Comment by mehalter** [comment]
@cherez0ff you probably want to disable `indent-o-matic` plugin:

```lua
return {
  plugins = {
    init = {
      ["Darazaki/indent-o-matic"] = { disable = true },
    },
  },
}
```

**Comment by cherez0ff** [comment]
Nop, nothing has changed
Indent still works. Value of indentexpr still "GetYAMLIndent(v:lnum)". That's for for yaml file

new config part: 
```lua

  -- Configure plugins
  plugins = {
    init = {
      ["Darazaki/indent-o-matic"] = { disable = true },
      -- You can disable default plugins as follows:
      -- ["goolord/alpha-nvim"] = { disable = true },

      -- You can also add new plugins here as well:
      -- Add plugins, the packer syntax without the "use"
      -- { "andweeb/presence.nvim" },
      -- {
      --   "ray-x/lsp_signature.nvim",
      --   event = "BufRead",
      --   config = function()
      --     require("lsp_signature").setup()
      --   end,
      -- },

      -- We also support a key value style plugin definition similar to NvChad:
      -- ["ray-x/lsp_signature.nvim"] = {
      --   event = "BufRead",
      --   config = function()
      --     require("lsp_signature").setup()
      --   end,
      -- },
    },
    -- All other entries override the require("<key>").setup({...}) call for default plugins
    ["null-ls"] = function(config) -- overrides `require("null-ls").setup(config)`
      -- config variable is the default configuration table for the setup function call
      -- local null_ls = require "null-ls"

      -- Check supported formatters and linters
      -- https://github.com/jose-elias-alvarez/null-ls.nvim/tree/main/lua/null-ls/builtins/formatting
      -- https://github.com/jose-elias-alvarez/null-ls.nvim/tree/main/lua/null-ls/builtins/diagnostics
      config.sources = {
        -- Set a formatter
        -- null_ls.builtins.formatting.stylua,
        -- null_ls.builtins.formatting.prettier,
      }
      return config -- return final config table
    end,
    treesitter = { -- overrides `require("treesitter").setup(...)`
      -- ensure_installed = { "lua" },
    },
    -- use mason-lspconfig to configure LSP installations
    ["mason-lspconfig"] = { -- overrides `require("mason-lspconfig").setup(...)`
      -- ensure_installed = { "sumneko_lua" },
    },
    -- use mason-null-ls to configure Formatters/Linter installation for null-ls sources
    ["mason-null-ls"] = { -- overrides `require("mason-null-ls").setup(...)`
      -- ensure_installed = { "prettier", "stylua" },
    },
  },
```

**Comment by jayp0521** [comment]
mehalter@, knows better, but maybe try `user/lsp/formatting.lua` with

```
return {
  format_on_save = {
    enabled = false,
  }
}
```

**Comment by cherez0ff** [comment]
@jayp0521 Not sure I got what to do. If you mean I need to create file "/home/$USER/.config/nvim/lua/user/formatting.lua" with provided above content - I did that, nothing has changed, for example for yaml file I still got
```
:set indentexpr?
  indentexpr=GetYAMLIndent(v:lnum)
```

**Comment by mehalter** [comment]
@cherez0ff I was able to get around to investigating this. This is being set by the built in filetype stuff in Neovim. To fully disable this behavior you want to put `vim.cmd.filetype("indent off")` in your `polish` function in your user configuration. Here is a minimal `user/init.lua` file that disabled this:

```lua
return {
  polish = function() vim.cmd.filetype "indent off" end,
}
```

**Comment by mehalter** [comment]
You can find the docs for this with `:h filetype-indent-off`

**Comment by cherez0ff** [comment]
Thanks a lot!
For those who will have the same issue, TLDR:
open /home/$USER/.config/nvim/lua/user/init.lua
change
```
polish = function()
...
end,
```
to
```
polish = function() vim.cmd.filetype "indent off" end,
```

**Comment by chase-moskal** [comment]
for the benefit of anybody else searching,

i found the following configurations worked for me today, to achieve a simple and reliable indentation rule: the goal of this is to disable all "smart" indentation features, and leave only vim's basic `autoindent` which simply lets new lines inherit the same indentation as the current line -- no muss, no fuss!

- `~/.config/nvim/lua/plugins/astrocore.lua`  
  i set the following `opts`
  ```lua
  autoindent = true,
  smartindent = false,
  cindent = false,
  indentexpr = "",
  ```
  - i set `autoindent` to `true` because i like the indentation of new lines to match the indentation of the current line
- `~/.config/nvim/lua/plugins/custom.lua`  
  i added this new file in the plugins directory, disabling various things i think might cause any funky "smart" indenting.
  ```lua
  return {
    {
      "nvim-treesitter/nvim-treesitter",
      opts = {
        indent = {
          enable = false,
        },
      },
    },
    {
      "nmac427/guess-indent.nvim",
      enabled = false,
    },
    {
      "lukas-reineke/indent-blankline.nvim",
      enabled = false,
    },
  }
  ```
- `~/.config/nvim/lua/polish.lua`  
  finally, i **wholly replaced** the entirety of polish.lua with the following line
  ```lua
  vim.cmd.filetype "indent off"
  ```
