### ISSUE TITLE
Inspect NeoTree* highlights

### ISSUE THREAD

**Issue by trankchung** [AstroNvim/AstroNvim#1357]
### Question

Hi,

I'm trying to customize neo-tree `source_selector.highlight_tab_active` and I know I can use the predefined highlight names such as `NeoTreeTabActive` and `NeoTree*` highlight names. However, none of them have the color nor font style/weight I want. So, I'm trying set it to a table and define my own weight, color, etc. but I don't know the format of the table.

I was able to trace it down to this function: https://github.com/nvim-neo-tree/neo-tree.nvim/blob/v2.x/lua/neo-tree/ui/highlights.lua#L76 but I can't seem to figure out how to inspect the returned data.

Do you mind showing me how I can inspect those `NeoTree*` highlight names?

Thanks,

**Comment by mehalter** [comment]
Easiest way is probably `:Telescope highlight`

**Comment by trankchung** [comment]
Thanks @mehalter. I was able to figure it out after reading `highlight`.
