### ISSUE TITLE
jsx and tsx file can not indent correct

### ISSUE THREAD

**Issue by lancelock** [AstroNvim/AstroNvim#1359]
### Question

I have install the lsp servers: tsserver html cssls emmet-ls
and TSInstall javascript html typescript tsx and so on

When i edit a jsx file, the js blocks is right, but the html tags can not indent for a different level, they just at the start of the line,
like this:
<img width="309" alt="image" src="https://user-images.githubusercontent.com/13751352/202914846-a128e308-9e19-4aa0-a87f-240513765202.png">
and when i save files, it will autoformat to a corrent indent, like this:
<img width="294" alt="image" src="https://user-images.githubusercontent.com/13751352/202914877-10039397-2410-48c6-badd-f5ee39fd147d.png">
but it is so strange, how to fix it?

**Comment by goget-milk** [comment]
@lancelock 
I join! I have the same problem

**Comment by mehalter** [comment]
I would recommend enabling treesitter based indentation. This is an experimental treesitter feature and does have some instability for some languages which is why it is not enabled on core AstroNvim. Here is an example user configuration:

```lua
return {
  plugins = {
    treesitter = {
      indent = { enable = true },
    },
  },
}
```
