### ISSUE TITLE
How to split terminal

### ISSUE THREAD

**Issue by wtLau** [AstroNvim/AstroNvim#1362]
### Question

The key binding that toggles term uses arent applicable here. I am wondering how to split into the different terminal session.

**Comment by whoop-t** [comment]
`<leader>t` will show you all the toggle term options
https://astronvim.github.io/Basic%20Usage/mappings#toggle-terminal-mappings

**Comment by wtLau** [comment]
Yes but what I wanted to achieve is to have two terminal opened within the
toggleterm

**Comment by whoop-t** [comment]
Maybe relevant: [#619 ](https://github.com/AstroNvim/AstroNvim/issues/619)

**Comment by mehalter** [comment]
yeah the best way to achieve this with ToggleTerm is to change the location of splits by default as shown in that issue linked above (#619) and then you can use `<F7>` to open a toggle term and then `#<F7>` to open more. so like `<F7>` and `2<F7>` will open 2 toggle terms in splits if you have the split set to default. Outside of this you would need to add your own bindings for running `:terminal` and create the splits

**Comment by mehalter** [comment]
I personally use tmux ! I really like it for terminal multiplexing
