### ISSUE TITLE
How to set transparency to the background?

### ISSUE THREAD

**Issue by arewerage** [AstroNvim/AstroNvim#1363]
### Question

The astronvim theme has an opaque background by default. How can I fix it so that it's like in the Alacritty terminal?
![Снимок экрана от 2022-11-21 16-08-45](https://user-images.githubusercontent.com/69102503/202987218-231a2d84-a3d8-4b1c-ad1d-81b6e162452c.png)

My [init.lua](https://github.com/arewerage/dotfiles/blob/main/dot_config/nvim/lua/user/init.lua) file if needed.

**Comment by kabinspace** [comment]
Please check [this](https://github.com/AstroNvim/AstroNvim/issues/8#issuecomment-1276307330) out. It has been already discussed at #8

**Comment by arewerage** [comment]
Thank you very much!
