### ISSUE TITLE
Typescript + React.JS

### ISSUE THREAD

**Issue by IcyKit** [AstroNvim/AstroNvim#1364]
### Question

Are there any ways in default AstroVim to view this modal while editing ts or tsx file?
![Снимок экрана 2022-11-21 в 13 13 28](https://user-images.githubusercontent.com/84917134/203024886-1871395f-74fd-4cf6-ac6a-34faef800148.png)

**Comment by mehalter** [comment]
you could use `gI` to go to the implementation of the symbol I believe in this situation, and then `<C-o>` to go back to your previous mark

**Comment by IcyKit** [comment]
Unfortunately, it doesn't work :(

**Comment by mehalter** [comment]
I'm not sure then. Not all language servers support all functionality. You could also try using `gd` to go to definition. Might be worth asking on the discord or r/AstroNvim to see if other people have figured this out
