### ISSUE TITLE
Syntax Highlighting not working correctly

### ISSUE THREAD

**Issue by jacobabahn** [AstroNvim/AstroNvim#1366]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [x] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

Version: v2.8.0

### Neovim version (>= 0.8)

NVIM v0.8.0

### Operating system/version

macOS 13.1

### Describe the bug

The syntax highlighting doesn't completely work until I run a Mason command. For example, the screenshot below shows the syntax highlighting when I first open up a project. The highlighting is mostly working.

<img width="1106" alt="Screenshot 2022-11-21 at 10 22 08 AM" src="https://user-images.githubusercontent.com/64383055/203093618-d87d048d-0c1c-4d00-95a1-9a207a8326a8.png">

This screenshot shows how it looks after I run :Mason. You can see that some of the text is highlighted now when they weren't initially.

<img width="1099" alt="Screenshot 2022-11-21 at 10 22 31 AM" src="https://user-images.githubusercontent.com/64383055/203093766-1ecd7f5f-4a86-43dd-931b-1c2a2ec86078.png">

### Steps to Reproduce

1. open astrovim using the nvim command
2. open a .tsx file
3. run :Mason

### Expected behavior

The syntax highlighting should work on the initial open of a file.

**Comment by mehalter** [comment]
Hm it looks like treesitter isnt loading. When you first open up the file do you see `TS` in the statusline? And if you run `:PackerStatus` do you see `nvim-treesitter` loaded or not loaded?

**Comment by ng-tony** [comment]
I've ran into the a similar problem. TSInstall does not seem to work, any argument I pass to it just silently fails.

I do not see the TS in the statusline but I do see that nvim-treesitter is loaded. 

My current workaround is to configure treesitter in my user/init.lua 
```
    treesitter = { -- overrides `require("treesitter").setup(...)`
      ensure_installed = { "lua", "javascript", "typescript"  },
    },
```

**Comment by mehalter** [comment]
@ng-tony what error were you getting when running `:TSInstall`?

**Comment by ng-tony** [comment]
I'm not getting any errors, just nothing happens

**Comment by ng-tony** [comment]
Yep, everything is up to date. Not sure what's going on, I might nuke everything when I have time later.

**Comment by jacobabahn** [comment]
> Hm it looks like treesitter isnt loading. When you first open up the file do you see `TS` in the statusline? And if you run `:PackerStatus` do you see `nvim-treesitter` loaded or not loaded?

I don't see `TS` in the status line, but I see that `nvim-treesitter` is loaded.

**Comment by jacobabahn** [comment]
> I've ran into the a similar problem. TSInstall does not seem to work, any argument I pass to it just silently fails.
> 
> I do not see the TS in the statusline but I do see that nvim-treesitter is loaded.
> 
> My current workaround is to configure treesitter in my user/init.lua
> 
> ```
>     treesitter = { -- overrides `require("treesitter").setup(...)`
>       ensure_installed = { "lua", "javascript", "typescript"  },
>     },
> ```

I added this to my init.lua and I'm still having the same issue in the typescript project from the original post, which has the .tsx extension.

**Comment by mehalter** [comment]
@jacobabahn could you try the latest `nightly` and see if it resolves the issue?

**Comment by Noxdor** [comment]
I just ran into the same issue(s) on the stable branch.
For me it is like that: 
1. As far as I can see, JS, TS, HTML, MD and few others are working fine, but I just opened a few Rust projects and I get the following error flood:
![image](https://user-images.githubusercontent.com/64439978/203529141-8bc8289c-7917-4bc9-8bb4-959115ad3d09.png)
2. As for @ng-tony `TSInstall` fails silently
3. `nvim-treesitter` plugin is loaded
![image](https://user-images.githubusercontent.com/64439978/203529363-a0cd04a6-a6a0-4db9-a5c7-480b29526c03.png)

**Comment by mehalter** [comment]
@Noxdor the treesitter errors you are getting look like you need to reinstall the rust treesitter parsers. Could you try doing `:TSUninstall rust` and then `:TSInstall rust`

Also when you do `:TSInstall` and it fails silently, if you run `:messages` do you see anything?

**Comment by Noxdor** [comment]
Unfortunately I can't try that because `TSUninstall` fails silently as does `TSInstall`. `:messages` also doesn't output anything, neither before nor after running one of the `TS` commands :/

**Comment by mehalter** [comment]
Hm that's very strange @Noxdor are you running them on a freshly opened `nvim` editor or after you have opened a file and treesitter is supposedly loaded? Also what OS are you on?

**Comment by Noxdor** [comment]
I tried both, opening a fresh `nvim` instance in `~` and also opening a specific Rust project, open a .rs file and run the `TS` commands. Both same result: No result. I am on (Garuda) Linux.

**Comment by jacobabahn** [comment]
> @jacobabahn could you try the latest `nightly` and see if it resolves the issue?

Using the nightly build didn't resolve my issues. Highlighting for `.tsx` extensions still seem to not be loaded. I uninstalled and reinstalled typescript from the Treesitter, but that didn't correct anything.

**Comment by Noxdor** [comment]
Strangest thing today:
I ran `AstroUpdate` no update.
I ran `PackerSync` no update.
I ran `TSUninstall rust` still no reaction.
I ran `TSInstall rust` and it asks me if I want to reinstall it (which didn't work yesterday), I say yes and after a restart at least my Rust parsing is resolved as @mehalter suspected!
After the restart though, ALL tree-sitter commands don't work again! Event `TSInstall`! No idea what is going on, but at least it doesn't bother me anymore now :D Hope there will be a solution soon for everyone else :/

**Comment by mehalter** [comment]
@jacobabahn can you please share you user configuration to see if I can replicate it with your config? I cannot replicate this with a base installation of astronvim or with my own configuration.

**Comment by mehalter** [comment]
@Noxdor I found the issue with Packer !!! https://github.com/wbthomason/packer.nvim/issues/1143

**Comment by Noxdor** [comment]
@mehalter Awesome! I hope they can fix it soon :)

**Comment by mehalter** [comment]
@Noxdor now that I know the issue, I think I came up with a bandaid at least. Could you try the latest nightly?

**Comment by Noxdor** [comment]
It appears to work (in stable, as I understand you made the nightly a new stable version already, if not I can test it again on nightly) for me, I can run `TSUninstall` and `TSInstall` without issues as soon a I open a code file :)

**Comment by mehalter** [comment]
@Noxdor I went ahead and merged the fix ! :) Hopefully it gets merged fixed upstream in Packer soon. I put a little bandaid on the problem for now
