### ISSUE TITLE
List of default AstroNvim snippets?

### ISSUE THREAD

**Issue by k12ish** [AstroNvim/AstroNvim#1368]
### Question

I can see that AstroNvim uses [LuaSnip](https://github.com/L3MON4D3/LuaSnip), but I can't seem to find which snippets AstroNvim includes by default.

Most articles I find are geared towards modifying LuaSnip or AstroNvim, but I can't find any resource that tells me which snippets I already have.

**Comment by mehalter** [comment]
AstroNvim come with these snippets - https://github.com/rafamadriz/friendly-snippets
