### ISSUE TITLE
how can i set up astro vim for c/c++ develoment 

### ISSUE THREAD

**Issue by alavaelian** [AstroNvim/AstroNvim#1372]
### Question

how i can set up astro vim for c/c++ develoment in particular i want an option to compile the program without write in a shell g++ <file>.cpp

**Comment by whoop-t** [comment]
You can prolly set a key binding in your `user/init.lua` or look for a plugin to add

This may help: https://www.reddit.com/r/neovim/comments/nds7uj/how_to_build_and_run_a_c_program_without_quitting/

**Comment by mehalter** [comment]
AstroNvim doesn't come with any plugins specifically for running code and compilation. The link that @whoop-t provided is a pretty good start. r/neovim is a good resource in general to find plugins that might fit your needs
