### ISSUE TITLE
Will you add 'kshenoy/vim-signature' this plugin?

### ISSUE THREAD

**Issue by ilaipi** [AstroNvim/AstroNvim#1373]
### Describe the new feature

with this plugin, we can add mark to somelines, and go back to a specific line quckily.

Is there any replacement already exist in this config?

**Comment by mishagantz** [comment]
You can add this plugin yourself. Basic <C-o> and <C-i> do the trick for me, usually I don't need to jump around file in 5 or more different places.

**Comment by mehalter** [comment]
I don't think we necessarily need to add this to the core AstroNvim installation. But thanks for the recommendation and feel free to add it to your user configuration!
