### ISSUE TITLE
Error executing lua callback: attempt to call field 'format'

### ISSUE THREAD

**Issue by Mjb141** [AstroNvim/AstroNvim#1375]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.8.0

### Neovim version (>= 0.8)

Nvim 0.8.0

### Operating system/version

Ubuntu 20.04.5 LTS (WSLg)

### Describe the bug

Plugins updated: 
![image](https://user-images.githubusercontent.com/46346590/203859313-fd4a6157-665f-4383-b874-b0167a2b6e2a.png)

AstroNvim updated:
![image](https://user-images.githubusercontent.com/46346590/203859336-53d85190-3f15-4df6-ba9c-53920bd46223.png)

Neovim 0.8.0:
![image](https://user-images.githubusercontent.com/46346590/203859384-820ba5be-950a-417b-a8f2-66b91aa144e0.png)

Attempting to save any file results in:
`Error executing lua callback: /home/mb/.config/nvim/lua/core/utils/lsp.lua:114: attempt to call field 'format' (a nil value)`
But the file saves anyway. No formatting takes place when this error shows. Error occurs no matter what the file type is - rust, python, lua, js/ts, etc

File saved anyway:
![image](https://user-images.githubusercontent.com/46346590/203859552-eaf030a1-7868-4d3a-8d86-2dfb8a68c1a1.png)

### Steps to Reproduce

1. Write to a file

### Expected behavior

No error. Should formatting take place automatically? Is that the error?

**Comment by mehalter** [comment]
What do you get if you run `:lua =vim.lsp.format` ?

**Comment by Mjb141** [comment]
> What do you get if you run `:lua =vim.lsp.format` ?

`nil`

![image](https://user-images.githubusercontent.com/46346590/203971257-02a81d36-c460-4fb3-af11-a94e9b50cba7.png)

What should I get?

**Comment by mehalter** [comment]
Something must be super wrong with your Neovim installation o.O `vim.lsp.format` should be a built in function. You can run `:h vim.lsp.format`. This is a function that should be available in core Neovim without any plugins or anything.

**Comment by Mjb141** [comment]
`:h vim.lsp.format` works fine and displays the help for that function. Leaning towards a full removal + reinstall of Neovim + AstroNvim here.

**Comment by mehalter** [comment]
It shouldn't be. It seems like something is happening with your neovim installation where it is not having access to `vim.lsp.format`. Since this is separate from AstroNvim I am going to go ahead and close this. You also probably want to verify if you run like `vim -u NONE` and run `:lua =vim.lsp.format` to see that it isn't AstroNvim related.

This would be a good thing to probably investigate online to see if anyone else has issues with not having access to `lsp` functionality after installing Neovim
