### ISSUE TITLE
Plugin indent-o-matic does not take effect on startup

### ISSUE THREAD

**Issue by ZhaoZuohong** [AstroNvim/AstroNvim#1376]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.8.0

### Neovim version (>= 0.8)

NVIM v0.8.0-1210-gd367ed9b2

### Operating system/version

Linux Mint 21

### Describe the bug

When opening a file with neovim, for some files, indent detection is incorrect. However, invoke `:IndentOMatic` command manually works.

### Steps to Reproduce

1. save the code below;
2. open it, the indent detection does not work
3. invoke `:IndentOMatic` manually and it works now

```c
#include <stdio.h>

#define LEN 4
#define MIN 3
#define MAX 7
#define STEP 2
#define TARGET 16

int count = 0;

void calc(int sum, int i)
{
    for (int j = sum + MIN; j <= sum + MAX; j += STEP) {
        if (j > TARGET) {
            break;
        }
        if (i == LEN - 1) {
            if (j == TARGET) {
                count++;
            }
        } else {
            calc(j, i + 1);
        }
    }
}

int main()
{
    calc(0, 0);
    printf("%d\n", count);
}
```

### Expected behavior

Indent detection with indent-o-matic should work after opening a file.

### Screenshots

![image](https://user-images.githubusercontent.com/34163622/203930613-00943e81-079c-4f79-9e98-30e11858492e.png)

### Additional Context

I have tested this with default configuration, both with clangd installed/not installed, the results are the same.

**Comment by mehalter** [comment]
Thanks for reporting this! I have pushed a fix to `nightly`

**Comment by ZhaoZuohong** [comment]
I have confirmed that on nightly branch this problem is already gone. Thank you!
