### ISSUE TITLE
Additional better-escape mappings 

### ISSUE THREAD

**Issue by gzzinx** [AstroNvim/AstroNvim#1378]
### Question

How can I add more mappings, e.g. `{"jj", "jk", "kk"}` to better-escape plugin config via user/init.lua?

**Comment by whoop-t** [comment]
In you `user/init.lua`, in the `plugins` object you want something like this:
```    
better_escape = {
  mapping = {"ll"}
}
```

User better-escape docs for more options: https://github.com/max397574/better-escape.nvim

**Comment by gzzinx** [comment]
It doesn't work :(. I've tried different variants, considering their docs, and haven't find out working method

**Comment by whoop-t** [comment]
Can you post your user config?

I put this in my `user/init.lua` and it works

**Comment by mehalter** [comment]
Here is a minimal `user/init.lua` file that sets the additional mappings:

```lua
return {
  plugins = {
    better_escape = {
      mapping = { "jk", "jj", "kk" },
    },
  },
}
```
