### ISSUE TITLE
How to change background color

### ISSUE THREAD

**Issue by bmarvinb** [AstroNvim/AstroNvim#1379]
### Question

![CleanShot 2022-11-25 at 19 46 29@2x](https://user-images.githubusercontent.com/23120972/204035254-f592299e-1633-4b7c-855d-7933ff87a3eb.png)

How to change this dark color that?

**Comment by whoop-t** [comment]
I would try to find it using the `:highlight` command
I know ` NeoTreeTabInactive` will work for changing the inactive tab in Neotree

**Comment by whoop-t** [comment]
Found the one for the BufferLine, which is where your second arrow points:
` hi.BufferLine = {bg = "#ffffff"}`

If you dont know already, you add these to your `user/init.lua` in the `highlights = function(hi)...`

**Comment by trankchung** [comment]
@whoop-t is correct. Let's say your theme is `onedark` then you can create `highlights/onedark.lua` with content below and it'll work. Change to your colors of course.

```lua
return {
  NeoTreeTabActive    = { fg = "#ffd580", bold = true },
  NeoTreeTabInactive  = { fg = "#777777" },
}
```

If you want it to be the same for any theme then put that into `highlights/init.lua` instead.
