### ISSUE TITLE
heirline.colors overrides not working

### ISSUE THREAD

**Issue by trankchung** [AstroNvim/AstroNvim#1381]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.8.0

### Neovim version (>= 0.8)

v0.8.0

### Operating system/version

12.6.1

### Describe the bug

Heirline is spell wrong on this line: https://github.com/AstroNvim/AstroNvim/blob/v2.8.0/lua/configs/heirline.lua#L12

According to this line: https://github.com/AstroNvim/AstroNvim/blob/v2.8.0/lua/configs/heirline.lua#L25

I should be to return the table below in the `plugins/heirline.lua` file and it should overrides the colors but it didn't. I've reloaded and synced the plugins but still the same.

```
return {
  colors = {
    normal = "#ffd580",
    visual = "#00cc00",
  },
}
```

### Steps to Reproduce

1. Add a file in `plugins/heirline.lua`
2. Return a table with `colors` as key.

### Expected behavior

The colors for normal and visual should change.

**Comment by mehalter** [comment]
It should actually be the file `heirline/colors.lua` returning a table as indicated in the docs: https://astronvim.github.io/Configuration/config_options

`plugins/heirline.lua` only overrides the `require("heirline").setup` call

**Comment by mehalter** [comment]
Thanks for catching the typo! I will definitely push a fix soon to `nightly`

**Comment by mehalter** [comment]
Pushed a fix for this typo to `nightly`. Should make it to `stable` sometime next week. Thanks again!

**Comment by trankchung** [comment]
@mehalter Thanks it's working as expected.

**Comment by trankchung** [comment]
@mehalter My theme is `ayu` according to `vim.g.colors_name` so I created `highlights/ayu.lua` with content below and all those highlights work except for `HeirlineNormal` or `HeirlineVisual`. I am using `nightly` release and I have checked the `~/.config/nvim/lua/configs/heirline.lua` and it does have the changes you've made but it still doesn't work.

```
return {
    CursorLine = { bg = "#191e2a" },
    TypeDef        = { fg = "#00cc00" },

    NeoTreeCursorLine   = { bg = "#191e2a" },
    NeoTreeDotfile      = { fg = "#c6a766" },
    NeoTreeTabActive    = { fg = "#ffd580", bold = true },
    NeoTreeTabInactive  = { fg = "#777777" },
    NeoTreeWinSeparator = { fg = "#1f2430", bg = "#1f2430" },

    HeirlineNormal = { fg = "#ffd580" },
    HeirlineVisual = { fg = "#ffffff" },
  }
```
