### ISSUE TITLE
PackerSync no longer editor command

### ISSUE THREAD

**Issue by b1twe1ser** [AstroNvim/AstroNvim#1383]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.8.0

### Neovim version (>= 0.8)

0.8.1

### Operating system/version

macOS 13.1

### Describe the bug

:PackerSync and all other Packer commands are no longer recognised as editor commands :(

### Steps to Reproduce

Try running :PackerSync on new macOS version

### Expected behavior

Packer to sync all new packages 

### Additional Context

I think it might be due to the new OS, but I am not entirely sure why it behaves this way. And since packer doesn't work anymore AstroVim starts to be increasingly buggy as settings deprecate fast :( 

Oh and I had to check that I ran :PackerSync to submit the issue, bear this in mind

Thank you very much for your help :)

**Comment by paintmeyellow** [comment]
It's not OS problem. Same on linux

**Comment by mehalter** [comment]
Have you checked #1294

**Comment by paintmeyellow** [comment]
`rm -rf ~/.local/share/nvim` worked just fine!
