### ISSUE TITLE
Autocomplete 

### ISSUE THREAD

**Issue by willparsons** [AstroNvim/AstroNvim#1384]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.8.0

### Neovim version (>= 0.8)

NVIM v0.8.0-1210-gd367ed9b2

### Operating system/version

Win 11

### Describe the bug

The 'Hover Document' LSP action seems to show a black bar for a second then disappears again.

### Steps to Reproduce

1. Open a project that has an LSP setup for it
2. 'Hover Document' on a symbol
3. The window appears with a black bar for a second

### Expected behavior

No black bar.

### Screenshots

![image](https://user-images.githubusercontent.com/10012418/204098463-04407d63-34f8-4b12-97fb-c7ea372752bc.png)

**Comment by mehalter** [comment]
I am able to replicate this. It looks like sometimes the heirline resolution for whether or not a winbar is present can be laggy 🤔 I will investigate performance increase on this one

**Comment by mehalter** [comment]
@willparsons just pushed a commit to `nightly` that resolves this. Basically just adds an optimization to speed up the disabling of `winbar` by moving it to an `autocmd`
