### ISSUE TITLE
Want to change default c++ clangd version, can't find config.yaml for clangd

### ISSUE THREAD

**Issue by Azuneer** [AstroNvim/AstroNvim#1385]
### Question

I installed the clangd LSP Server via LspInstall. Though my code gives me an error for the std::size, which has been introduced in c++ 17. My g++ compiler doesn't see it as an error and i'm not having any problem to compile it when i point it towards a c++20 version. 

I want to change the clangd config file to point it through a c++20 version, how can i do that ? 

Thanks!

**Comment by whoop-t** [comment]
I dont work with c++ but it looks like you may need to add this to your .clangd config

In your .clangd
```CompileFlags:
  Add: [-std=c++20]```

https://neovim.discourse.group/t/how-to-setup-clangd-for-c-20/1744

**Comment by Azuneer** [comment]
thanks! but i don't know where my .clangd config file is.

**Comment by whoop-t** [comment]
config dotfiles normally go in the root of your project directory, so I would assume you create a `.clangd` file and add your config. This isnt Astronvim/neovim specific.

Sorry I am not more familiar with c++ and clangd. 

Maybe the clangd docs could help:
https://clangd.llvm.org/config#files

**Comment by whoop-t** [comment]
More references: https://github.com/llvm/clangd-www/blob/main/faq.md#can-you-give-an-example-configuration-file-for-clangd

**Comment by Azuneer** [comment]
Everything works perfectly ! Thanks for the help ^^
