### ISSUE TITLE
Support having multiple "user" configuration directories

### ISSUE THREAD

**Issue by jayp0521** [AstroNvim/AstroNvim#1388]
### Is your feature related to a problem?

Currently, I mainly have files spread across the `user` directory, which is great for my local setup. However, I also use my personal configuration at work, but my configuration needs to diverge from my personal setup, since some tools are internal. It would be nice if I could have a set of configs that astronvim loaded from like `lua/user, lua/work, lua/user1`.

### Describe the new feature

Be able to load an users configuration from multiple base directories such as `lua/user, lua/work`, etc.

**Comment by jayp0521** [comment]
I will create a PR that should resolve this

**Comment by jayp0521** [comment]
The problem is I have to do that for every single place astronvim calls `user_plugin_opts`. I chose to do it like this: https://github.com/jayp0521/dotfiles/commit/2834db8c9e62c071d20c0c2b096b7e62b168efa1. Most users probably won't use this, sure, but those that want to will have a very difficult time doing so. 

The solutions provided seems less straightforward than the PR I had opened, because it simply involves replicating `user` directory, which users are already familiar with.

**Comment by mehalter** [comment]
yeah iterating over the prefixes and merging them is going to be a non-trivial problem and I don't think I would put it in scope of AstroNvim at least right now. Maybe in the future this will be something we would look into but I don't think it is necessary at the moment. You only would need to do this in the cases where you want to make changes to your configuration so if you want to modify every single table then yeah you will need to add it. Another route is to use something like a dotfiles manager to deal with these diffs between machines and such.

**Comment by jayp0521** [comment]
> Another route is to use something like a dotfiles manager to deal with these diffs between machines and such

@mehalter, do you know of some dotfiles managers you can point me to? I just use `stow` right now, which is pretty simple and was working so far

**Comment by mehalter** [comment]
Yadm and Chezmoi are popular options that support multiple machines with different dotfiles
