### ISSUE TITLE
Unable to get cmp-nvim-lsp-signature-help working

### ISSUE THREAD

**Issue by jayp0521** [AstroNvim/AstroNvim#1390]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.8.1

### Neovim version (>= 0.8)

v0.8.0

### Operating system/version

wsl

### Describe the bug

Unsure if this is a bug or just my configuration.

Added

```
		["hrsh7th/cmp-nvim-lsp-signature-help"] = {
			after = "nvim-cmp",
			config = function()
				astronvim.add_user_cmp_source("nvim_lsp_signature_help")
			end,
		},

```

and

```
return {
  nvim_lsp_signature_help = 1000,
}
```

Signature does not show as shown in https://github.com/hrsh7th/cmp-nvim-lsp-signature-help/blob/main/README.md 

### Steps to Reproduce

as above

### Expected behavior

See signature when typing

### Screenshots

![image](https://user-images.githubusercontent.com/36803168/204439614-2e05be2f-c2c4-48d1-b1d5-7ac9791c1cdb.png)

this is shown for `golang`, but also doesn't work in lua

**Comment by mehalter** [comment]
From the screenshot it looks like it is showing the parameter, it's not automatically selecting the first entry because of the default `cmp` options we set so you don't get the preview. You could modify your `cmp` setup to automatically select the first entry though

**Comment by jayp0521** [comment]
I used https://github.com/ray-x/lsp_signature.nvim instead. working fine. `cmp-nvim-lsp-signature-help` is not autocomplete, it is supposed to show the method's signature as you type. Technically still an issue, but not for me

**Comment by mehalter** [comment]
It shows the method's signature if you select the item in the completion list. We don't do automatic selection when typing so it doesn't show the signature hint. The weirdness here is coming because you are right it is not autocomplete, but it is being represented in the autocomplete menu. So it plays by the exact same rules as every other `cmp` source. Hopefully that clears up your confusion.
