### ISSUE TITLE
Set smartcase to false

### ISSUE THREAD

**Issue by trankchung** [AstroNvim/AstroNvim#1395]
### Is your feature related to a problem?

You have both `ignorecase` and `smartcase` set to `true` in https://github.com/AstroNvim/AstroNvim/blob/main/lua/core/options.lua which makes case insensitive searching not working. Could we set `smartcase = false`?

### Describe the new feature

Insensitive case searching should work as expected.

**Comment by mehalter** [comment]
having `ignorecase` and `smartcase` set makes it a bit smarter. if you do something like `/hello` then it will search case insensitive and if you do `/Hello` with a capital then it will do case sensitive. Basically default to case insensitive unless cases are provided, then assume that the user wants case sensitive search. This is the default behavior that we would like AstroNvim to be I believe, feel free to set `smartcase = false` in your `user/init.lua` file with `options.opt` table if you would like to disable the smartcase features 😄

**Comment by trankchung** [comment]
Actually having both set to true doesn’t do camelCase search insensitively. For the words nodeSelector or labelSelector and etc. I did `/nodeselector` and `labelselector` and it didn’t find them. I had to turn smartcase off for it to match.

I know I can add the option into the config but I think it’s worth exploring this.

**Comment by mehalter** [comment]
Hm I can't replicate the behavior you are describing

**Comment by mehalter** [comment]
![2022-11-29_23:17:55_screenshot](https://user-images.githubusercontent.com/1591837/204706490-2b6d45be-7109-43d1-9ab1-5cd8829dc034.png)
![2022-11-29_23:18:02_screenshot](https://user-images.githubusercontent.com/1591837/204706499-03f773cd-64b3-4637-88d1-cd07d6343c7b.png)
![2022-11-29_23:18:08_screenshot](https://user-images.githubusercontent.com/1591837/204706507-1001a44f-a69b-4b68-9cdd-ede5b79e8b59.png)

**Comment by trankchung** [comment]
I’ll try again tomorrow and see. I had a whole k8s manifest and it didn’t work.

**Comment by trankchung** [comment]
Okay it's working as expected. Maybe I did something weird yesterday. Thanks.
