### ISSUE TITLE
Multi line editing doesn't work

### ISSUE THREAD

**Issue by bassamsdata** [AstroNvim/AstroNvim#1396]
### Question

Hey, a new vim user here, I really like Astrovim but I have a problem where i try to edit multi line at once but that doesn't work in AstroVim.
In vim (Vanilla one) it works as expected but it doesn't work in Astro. I searched a lot but all people use the same method which as follow:

_Put your cursor to where you want, press Ctrl-V, select all lines, then press I(capital i), and then type. Pressing Escape will repeat the operation on every line (sometimes pressing j will repeat that)_

But this method doesn't work in Astro, is there a solution?

**Comment by mehalter** [comment]
I can't replicate this behavior: https://asciinema.org/a/r7EJA3TYepmCWF5CDmnbb01P5

**Comment by bassamsdata** [comment]
My bad, sorry. I had a keybinding conflicting. I was actually pressing shift-V instead of C-V. Thanks a a lot 🙏
