### ISSUE TITLE
TS commands are not working.

### ISSUE THREAD

**Issue by A-Lamia** [AstroNvim/AstroNvim#1398]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

V2.6.2-3-ga04a401

### Neovim version (>= 0.8)

NVIM v0.8.1

### Operating system/version

Windows 10 x64

### Describe the bug

All TS commands silently fail, only `:TSInstallFromGrammer` and anything that uses NPM will just hang but other install fine.

I made a bug report on the nvim-treesitter repository but it seems that do not support anything having to do with Frameworks. https://github.com/nvim-treesitter/nvim-treesitter/issues/3897

### Steps to Reproduce

1. run any TS command.

### Expected behavior

Being able to run any of the TS commands.

### Additional Context

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (b268e412ad4848380166af153300464e5a1cf83f) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v19.2.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `clang` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: clang version 15.0.5
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "x86_64",
  release = "10.0.19045",
  sysname = "Windows_NT",
  version = "Windows 10 Pro"
}

## Parser/Features H L F I J
  - rust           ✓ ✓ ✓ ✓ ✓
  - python         ✓ ✓ ✓ ✓ ✓
  - javascript     ✓ ✓ ✓ ✓ ✓
  - lua            ✓ ✓ ✓ ✓ ✓
  - help           ✓ . . . ✓
  - cmake          ✓ . ✓ . .
  - c              ✓ ✓ ✓ ✓ ✓
  - gdscript       ✓ ✓ . ✓ ✓
  - json           ✓ ✓ ✓ ✓ .

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

**Comment by A-Lamia** [comment]
out of curiosity i decided to try `:lua require("nvim-treesitter").setup()` and everything worked. maybe something is going wrong with the lazy loading ?

**Comment by mehalter** [comment]
Can you please share your user config

**Comment by A-Lamia** [comment]
@mehalter any specific part of importance or should i upload the whole thing to git ?

**Comment by mehalter** [comment]
If you could upload the whole thing to git that would be ideal. I'm not sure which part would be relevant. I can't replicate this with my config or stock AstroNvim so I just wanted to see if I can by setting up your config

**Comment by A-Lamia** [comment]
@mehalter https://github.com/A-Lamia/nvim-conf here you go sorry if some parts are a little messy been working on some stuff 😅

**Comment by mehalter** [comment]
No problem! Let me pull this down today and see if I can replicate this behavior you are getting. Ill message back later today

**Comment by A-Lamia** [comment]
All good, i have a solution for now so no stress :D
