### ISSUE TITLE
Where to put IndentBlankLineDisable option

### ISSUE THREAD

**Issue by bmarvinb** [AstroNvim/AstroNvim#1401]
### Question

I'm new to nvim, I don't understand where I should put this, which file?

**Comment by mehalter** [comment]
I'm not sure I know what option you are talking about. Do you just want to fully disable indent blankline?

**Comment by bmarvinb** [comment]
Yes

**Comment by mehalter** [comment]
You will want to put the following line in your user configuration in the `plugins.init` table (either `user/init.lua` or `user/plugins/init.lua` if you are splitting up your config):

```lua
  ["lukas-reineke/indent-blankline.nvim"] = { disable = true }
```

just make sure to restart and run `:PackerSync` to have packer remove the plugin
