### ISSUE TITLE
:Telescope *command* not working

### ISSUE THREAD

**Issue by trankchung** [AstroNvim/AstroNvim#1402]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.8.1

### Neovim version (>= 0.8)

v0.8.0

### Operating system/version

12.6.1

### Describe the bug

When running `:Telescope *command*` such as `:Telescope highlights` or `:Telescope find_files` nothing happens. The lua method works though like `:lua require("telescope.builtin").highlights()`.

I have tested it with LunarVim and it works fine when doing `:Telescope highlights`.

### Steps to Reproduce

1. Start nvim
2. Execute `:Telescope highlights[CR]`
3. Nothing happens

### Expected behavior

Telescope should pop up with the proper things.

**Comment by mehalter** [comment]
Can you please share your user configuration

**Comment by trankchung** [comment]
I've found that `pwntester/octo.nvim` is causing this b/c in config is below.

```lua
{
    "pwntester/octo.nvim",
    requires = {
      "nvim-lua/plenary.nvim",
      "nvim-telescope/telescope.nvim",
      "kyazdani42/nvim-web-devicons",
    },
    config = function()
      require "user.plugins.octo"
    end,
  },
```

**Comment by mehalter** [comment]
@trankchung could you pull the latest from `nightly` and see if it resolves the issue?

**Comment by trankchung** [comment]
@mehalter Awesome. Nightly works.

**Comment by trankchung** [comment]
You're awesome. TYVM.
