### ISSUE TITLE
Briefly highlight text getting yanked by leveraging existing neovim support

### ISSUE THREAD

**Issue by robin-randhawa-sifive** [AstroNvim/AstroNvim#1406]
### Is your feature related to a problem?

Dark neovim themes, like the astronvim default theme, make it a bit hard to discern whether the visual-mode selected region needing yanking did in fact get yanked.

There's a little less cognitive load if the visual-mode selected region is briefly highlighted.

neovim supports this since: https://github.com/neovim/neovim/pull/12279

### Describe the new feature

It turns out that enabling this feature in astronvim is super simple! I just add that one line to my polish function within `user/init.lua`:

```
  -- This function is run last and is a good place to configuring
  -- augroups/autocommands and custom filetypes also this just pure lua so
  -- anything that doesn't fit in the normal config locations above can go here
  polish = function()
    -- Set up custom filetypes
    -- vim.filetype.add {
    --   extension = {
    --     foo = "fooscript",
    --   },
    --   filename = {
    --     ["Foofile"] = "fooscript",
    --   },
    --   pattern = {
    --     ["~/%.config/foo/.*"] = "fooscript",
    --   },
    -- }
    vim.cmd[[au TextYankPost * silent! lua vim.highlight.on_yank()]]
  end,
}
```

I think it is one of those quality of life config options that should be a default and wondered what others thought ? For me it's right up there with telescope's find word under cursor feature that astronvim supports with space-f-c.

Thanks

**Comment by mehalter** [comment]
Thanks for this request @robin-randhawa-sifive ! I didn't know about this feature, but I like it, I have pushed a commit to add this to  `nightly` and will be made to `stable` in the near future :)

**Comment by robin-randhawa-sifive** [comment]
Super! :) Thanks so much!

**Comment by mehalter** [comment]
Ended up moving this to the new nightly. A bug patch came up that I wanted to get into v2.8 before we do a new feature release. I'll keep an eye out on new features we want to add to try and bundle a few features before we push a new minor version release :) I'll go ahead and close this since it's in the new nightly ! Thanks again for recommending!
