### ISSUE TITLE
Go to definition(gd), Go to file under cursor(gf) commands don't work

### ISSUE THREAD

**Issue by devmartynov** [AstroNvim/AstroNvim#1412]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.8.4

### Neovim version (>= 0.8)

0.8.0

### Operating system/version

macOS 12.6.1

### Describe the bug

I try to use Go to definition(gd) and Go to file under cursor(gf) commands in PHP project. "Go to definition" command just highlights matches, "Go to file under cursor" throw error "Can't find file '{filNmae}' in path"

### Steps to Reproduce

1. Place cursor on type
2. Press "gd" to go to definition
3. Command highlights all word matches in file
4. Place cursor on type
5. Press "gf" to go file under cursor
6. Get error "Can't find file '{fileName}' in path"

### Expected behavior

1. Place cursor on type
2. Press "gd" to go to definition
3. **Moves to place with type definition**
4. Place cursor on type
5. Press "gf" to go file under cursor
6. **Opens file with type**

### Screenshots

https://user-images.githubusercontent.com/35950292/205154317-cc51528c-9248-4178-96fb-950831df5212.mov

**Comment by mehalter** [comment]
@devmartynov It doesn't look like you have any language servers running. Have you made sure to set up and install a language server?

**Comment by mehalter** [comment]
It also doesn't look like you have installed any treesitter parsers for syntax highlighting. You might also want to run `:TSInstall php` to enable that as well.

**Comment by devmartynov** [comment]
Oh..., my bad. You're right. Thank you!
