### ISSUE TITLE
A lot of errors when requesting help command

### ISSUE THREAD

**Issue by bassamsdata** [AstroNvim/AstroNvim#1414]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.8.1

### Neovim version (>= 0.8)

NVIM v0.8.1

### Operating system/version

macOS 12.6

### Describe the bug

Showing errors every time I type `:help` command and doesn't go away until I press multiple keys.

- attached video describing the issue.
- This happens everytime, whatever I write in the help command even with `:help` only.

even if I opened the txt file directly from the dashboard, it shows an error but then the error goes away if I cycled through the file. (screenshot attached shows that).

- This issues go crazy if I have multiple buffers (like whole screen errors and many many keys to show the help page)

video:
https://asciinema.org/a/iICXqCC2RL0eBvJtZDHsb8jii

### Steps to Reproduce

video attached

### Expected behavior

Show the help page with no errors

### Screenshots

<img width="1428" alt="Screen Shot 2022-12-01 at 5 14 31 PM" src="https://user-images.githubusercontent.com/105807570/205170673-7b964b17-1039-4f32-8eed-385a1509ac8c.png">

### Additional Context

I'm a new vim user 🫣

**Comment by mehalter** [comment]
You need to reinstall the `help` treesitter parsers. Please run `:TSInstall help` and reinstall it.

**Comment by bassamsdata** [comment]
Wow it worked. thank you 🙏
