### ISSUE TITLE
Incorrect number of search occurrences in status line

### ISSUE THREAD

**Issue by fayrushin** [AstroNvim/AstroNvim#1415]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.8.4

### Neovim version (>= 0.8)

NVIM v0.8.0

### Operating system/version

Pop!_OS 22.04

### Describe the bug

The status bar does not correctly display the number of words found, if the number is greater than 100.

### Steps to Reproduce

1. Create a file containing more than 100 identical words
2. Open this file
3. Search word
4. See incorrect number of occurrences

### Expected behavior

Expected to see correct number of occurrences

### Screenshots

![image](https://user-images.githubusercontent.com/13679399/205350017-de5bee2f-6195-4cf3-93eb-621d51e6bb27.png)

**Comment by mehalter** [comment]
By default Neovim's `searchcount` limits the search count to save processing time to `99`. I have opened a patch fix to improve this text:
![2022-12-02_12:56:39_screenshot](https://user-images.githubusercontent.com/1591837/205355664-f8ee5436-bff1-4d76-997a-2a9abb8411bd.png)

**Comment by mehalter** [comment]
@fayrushin if you want to increase the max count anyway, you can actually do this by configuring the `heirline` configuration with the `astronvim.status` API. Here is a minimal `user/init.lua` file (*Note:* the indexes were found by looking at the source code):

```lua
return {
  plugins = {
    heirline = function(config)
      config[1][7] = astronvim.status.component.cmd_info { search_count = { maxcount = 999 } }
      return config
    end,
  },
}
```
