### ISSUE TITLE
Text is being prepended to file on save

### ISSUE THREAD

**Issue by nvsd** [AstroNvim/AstroNvim#1419]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.8.5

### Neovim version (>= 0.8)

NVIM v0.8.1

### Operating system/version

macOS 13.0.1

### Describe the bug

On save, text is prepended to the file that I'm saving. 
Does not occur with plain nvim, is not dependent on the terminal, and tmux doesn't matter.

I've nuked nvim and astronvim and it keeps coming back.

### Steps to Reproduce

I don't know what triggers it to happen but once it's there it happens on every save.

### Expected behavior

On save nothing is prepended to the file.

### Screenshots

https://asciinema.org/a/BDGIwwiqkE1IKKq9sfHMrgCy0

**Comment by mehalter** [comment]
Can you share your user configuration? It looks like for some reason a formatting command is probably being called before saving so it's running on the unmodified file and overwriting the changes

**Comment by nvsd** [comment]
I've completely removed my nvim directory and re-cloned before creating the issue. I should have mentioned that.

<img width="885" alt="image" src="https://user-images.githubusercontent.com/7391612/205449699-ec70c7a0-16ad-4977-91c8-844baea8d25b.png">

**Comment by nvsd** [comment]
I've disabled autoformat and it fixed the issue so it's definitely related to that. I also found that it's only related to any ts or tsx file within that directory. This is weird I don't know where this is coming from.

**Comment by nvsd** [comment]
I downloaded vscode, installed prettier, and then turned on format on save and it doesn't happen there. I was thinking it might just be prettier related or something.

**Comment by mehalter** [comment]
Can you share your user configuration? Or provide some clear steps from installation to replication? You mentioned it was happening before treesitter and LSP, but without an LSP there is no auto formatting.

**Comment by mehalter** [comment]
I am unable to replicate this with treesitter or tsx with prettier. So I'll need some replication details

**Comment by mehalter** [comment]
Also you mentioned only in that directory? Is it not happening in other directories?

**Comment by nvsd** [comment]
My user configuration is default you can find that in the below gist.
https://gist.github.com/nvsd/278df2e8a14daaa3f8c5fcfc9da97681


As far as reproduction I follow the ["getting started" guide](https://astronvim.github.io/)

- Make a backup of your current nvim folder
-  `mv ~/.config/nvim ~/.config/nvim.bak`
- Clean old plugins (Optional but recommended)
- `mv ~/.local/share/nvim/site ~/.local/share/nvim/site.bak`
- Clone the repository
- `git clone https://github.com/AstroNvim/AstroNvim ~/.config/nvim`
- open typescript file
- save file
- observe the prepended text

**Comment by nvsd** [comment]
> Also you mentioned only in that directory? Is it not happening in other directories?

Yeah I have no idea what's special about that directory though. I've grepped for that text in that directory and the parent directory and can't find it anywhere.

**Comment by mehalter** [comment]
Could you share more details please? What language servers are you using, what commands (in Neovim) did you run to install things? Did you use mason, what did you installed, and what does the statusline say is running at the time. With just the default user configuration without doing anything there will be no formatting on save because no language servers will be installed or running

**Comment by mehalter** [comment]
Is there any way you can share the directory or - the project that it is happening with

**Comment by nvsd** [comment]
Ok I got it fixed.

I went ahead and nuked my nvim folders
```
rm -rf ~/.local/site/nvim
rm -rf ~/.local/share/nvim
rm -rf ~/.cache/nvim
```

Not a big deal as I just use the default astronvim configuration with no extras so not a big deal. It would have been nice to know where that's coming from though. 

Thanks for your help and your work on astronvim.

**Comment by mehalter** [comment]
You will have had to have some sort of extra added to get formatting on save working because out of the box we do not install any language servers or anything. Glad that refreshing the cache and everything fixed it though!
