### ISSUE TITLE
Lua error when configuring heirline

### ISSUE THREAD

**Issue by gwww** [AstroNvim/AstroNvim#1421]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.8.5

### Neovim version (>= 0.8)

NVIM 0.8.1

### Operating system/version

macOS 12.5

### Describe the bug

In my user/plugins config I have a `heirline.lua`.

With this in my config:
```
return {
    {
        astronvim.status.component.mode { mode_text = true },
    },
}
```

The above has removed everything possible to still see the error. In use I have more in the file. See here: https://github.com/gwww/dotfiles/blob/main/.config/astronvim/lua/user/plugins/heirline.lua

I get the following error:

```
Error detected while processing VimEnter Autocommands for "*":
Error loading file: /Users/glenn/.config/astronvim/lua/user/plugins/heirline.lua
Press ENTER or type command to continue
Error detected while processing VimEnter Autocommands for "*":
/Users/glenn/.config/nvim/lua/core/utils/status.lua:986: attempt to index local 'opts' (a boolean value)
Press ENTER or type command to continue
```

Setting `mode_text = false` removes the error.

### Steps to Reproduce

See above.

### Expected behavior

No lua error.

**Comment by mehalter** [comment]
You need to use `mode_text = {}` here
