### ISSUE TITLE
javascript fails to launch or attach into nvim-dapp

### ISSUE THREAD

**Issue by aligit** [AstroNvim/AstroNvim#1422]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.8.5-2-g7b38e4c

### Neovim version (>= 0.8)

NVIM v0.8.0-v0.8.0

### Operating system/version

Ubuntu 20.04

### Describe the bug

nvim-dap-vscode-js, a nvim-dap extension for javascript does not work with astrovim. Here is how I configured my init.lua:

```lua
{
       "mxsdev/nvim-dap-vscode-js",
        requires = {"mfussenegger/nvim-dap"},
        config = function()
          require('dap-vscode-js').setup {
            debugger_path = vim.fn.stdpath('data') .. '/mason/packages/js-debug-adapter',
            debugger_cmd = { 'js-debug-adapter' },
            node_path = "~/.config/nvm/versions/node/v16.17.1/bin/node",
            adapters = { 'pwa-node', 'pwa-chrome', 'pwa-msedge', 'node-terminal', 'pwa-extensionHost' },
          }
        end
}
```
And here I've dap.configurations:

```lua
  dap = {
    configurations = {
      javascript = {   
        {
          type = "pwa-node",
          request = "launch",
          name = "Launch file(pwa-node)",
          program = "${file}",
          cwd = "${workspaceFolder}",
        },
        {
          type = "pwa-node",
          request = "attach",
          name = "Attach(pwa-node)",
          processId = require 'dap.utils'.pick_process,
          cwd = "${workspaceFolder}",
        },
      },
    }
  },
```
When I run the command below:
```
:lua require'dap'.continue() 
```

Within the javascript file containing:
```javascript
exports.hexToRgb = function(hex) {
  var red = parseInt(hex.substring(0, 2), 16);
  var green = parseInt(hex.substring(2, 4), 16);
  return [red, green, blue];
};
```
I get the following error:
```
[dap-js] Error trying to launch JS debugger: ENOENT: no such file or directory
```

### Steps to Reproduce

1. Open a javascript file
2. Set a breakpoint
3. Run the lua command:  :lua require'dap'.continue() 

### Expected behavior

I expected that the debugger starts or attachs to a running debugger and nvim-dap-ui opens up

**Comment by mehalter** [comment]
It looks like there are a few places that could be improved. This is how I have `nvim-dap-vscode-js` configured:

```lua
return {
  dap = {
    configurations = {
      javascript = { -- set up javascript dap configuration
        {
          type = "pwa-node",
          request = "launch",
          name = "Launch file",
          program = "${file}",
          cwd = "${workspaceFolder}",
        },
        {
          type = "pwa-node",
          request = "attach",
          name = "Attach",
          processId = function(...) return require("dap.utils").pick_process(...) end, -- protect function
          cwd = "${workspaceFolder}",
        },
      },
    },
  },
  plugins = {
    init = {
      {
        "mxsdev/nvim-dap-vscode-js",
        after = "mason-nvim-dap.nvim", -- setup after mason which  installs the debugger
        config = function()
          require("dap-vscode-js").setup {
            debugger_cmd = { "js-debug-adapter" }, -- mason puts command in path
            adapters = { "pwa-node" }, -- choose adapter, only node is fully tested
          }
        end,
      },
    },
    ["mason-nvim-dap"] = {
      ensure_installed = { "js" }, -- auto install js-debug-adapter
    },
  },
}
```

**Comment by aligit** [comment]
Is this working for you?
I replaced my local user/init.lua and set it to nightly but still can't get nvim dap working properly. Here is what I get know:

> The selected configuration references adapter `pwa-node`, but dap.adapters.pwa-node is undefined

I guess pwa-node is used by js-debug-adapter. Maybe this has to do with my node version(v16.17.1)?

**Comment by mehalter** [comment]
maybe make sure that you have done a `:PackerSync` so that the plugin is running?

**Comment by aligit** [comment]
Yeah that made it. Microsoft was blocking my ip address indeed. I ran nvim with proxy and :PackerSync properly installed it.
Thank you

**Comment by PaulKushch** [comment]
@mehalter @aligit Hi! Trying to follow your configuration @aligit to make it work with `typescriptreact` files. But I get the error:
![image](https://user-images.githubusercontent.com/5386035/207179356-a160a3b4-415a-453e-8c80-922275bda920.png)

But `localhost:3000` is up and running. 
Any idea how it is possible to make it work with typescriptreact?

```
	dap = {
		configurations = {
			javascript = { -- set up javascript dap configuration
				{
					type = "pwa-node",
					request = "launch",
					name = "Launch file",
					program = "${file}",
					cwd = "${workspaceFolder}",
					sourceMaps = true,
					skipFiles = { "<node_internals>/**", "node_modules/**" },
				},
				{
					type = "pwa-node",
					request = "attach",
					name = "Attach",
					processId = function(...)
						return require("dap.utils").pick_process(...)
					end, -- protect function
					cwd = "${workspaceFolder}",
				},
			},
			typescript = { -- set up typescript dap configuration
				{
					type = "pwa-node",
					request = "launch",
					name = "Launch file",
					program = "${file}",
					cwd = "${workspaceFolder}",
					sourceMaps = true,
					skipFiles = { "<node_internals>/**", "node_modules/**" },
				},
				{
					type = "pwa-node",
					request = "attach",
					name = "Attach",
					processId = function(...)
						return require("dap.utils").pick_process(...)
					end, -- protect function
					cwd = "${workspaceFolder}",
				},
			},
			typescriptreact = { -- set up typescript dap configuration
				{
					type = "pwa-node",
					request = "launch",
					name = "Launch file",
					program = "${file}",
					cwd = "${workspaceFolder}",
					sourceMaps = true,
					skipFiles = { "<node_internals>/**", "node_modules/**" },
				},
				{
					type = "pwa-node",
					request = "attach",
					name = "Attach",
					processId = function(...)
						return require("dap.utils").pick_process(...)
					end, -- protect function
					cwd = "${workspaceFolder}",
					port = 3000,
				},
			},
		},
	}
```,

Best regards

**Comment by mehalter** [comment]
@PaulKushch typescript is a big funky because it needs to compile as well. You can check out what I have for typescript here: https://code.mehalter.com/AstroNvim_user/~files/master/dap/configurations.lua

It gets a bit funky for sure, not sure how to adapt this for react or if anything needs to change. Hopefully can point you in the right direction. I'm having it use `ts-node` to do a simple compile

**Comment by PaulKushch** [comment]
@mehalter Thanks for the suggestion, but it does not work for me. I get `[dap-js] JS Debugger stderr: grep: /usr/bin/X11: warning: recursive directory loop` error.

**Comment by Jayphen** [comment]
I'd love some updated instructions on this after the update to 3.0. I'd like to debug nodejs, but am a little lost at which DAP  adapter (js-debug-adapter or node-debug2-adapter) to install and how to configure them.

**Comment by mehalter** [comment]
@Jayphen you can look here for a reference on how to set up `nvim-dap` with javascript/typescript: https://github.com/AstroNvim/astrocommunity/blob/main/lua/astrocommunity/pack/typescript/typescript.lua

This would just go in your `plugins` specifications. Also if you want to just use these definitions, you can just use the AstroCommunity repository and add the entire typescript language pack! It also adds full support for javascript :)

https://github.com/AstroNvim/astrocommunity

**Comment by akiranguyenvni** [comment]
Hi @mehalter , I did try you suggestion, but It couldn't debug Js yet. Could you mind tell me how to fix?
I did try 2 ways:

- 1: define in user/init.lua
<img width="1883" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/105026206/ea7ea1d5-d62b-4167-8311-841d8f36dc81">

- 2: define in user/plugins/init.lua & user/plugins/mason.lua
<img width="1339" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/105026206/f108dcdc-320d-4914-8c14-43604bfc78de">

Be sure that already install js-debug-adapter
<img width="1021" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/105026206/9bfba27f-37e8-4e74-bcbf-ab381fa04d0b">
<img width="1021" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/105026206/009de0d8-393c-4543-bdc1-a1abf73c509c">

But it still display error that not recognize
<img width="1884" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/105026206/243c62ba-729a-409b-a23b-e5833b17c1e5">

**Comment by mehalter** [comment]
I'm not sure @akiranguyenvni I'm not sure, this is a good question for the Discord server. There are a lot more users on there that actually use DAP. I believe some things have changed since March so I wouldn't be surprised if the code I shared needs to be altered. I don't use it so I don't keep up with the configuring of these plugins outside of the bare minimum that AstroNvim provides. Sorry! Here is a link to the discord: https://discord.gg/AstroNvim

If you do get a good answer from there please make sure to come and put your solution here as well to help other users that might run into the same question :)

**Comment by akiranguyenvni** [comment]
I got it. Thank @mehalter for suggestion.

**Comment by mortang2410** [comment]
I got it running. In short, vscode changed their `vscode-js-debug`. Then Mason had to update, while the compatibility layer  `nvim-dap-vscode-js` became obsolete. See [this](https://github.com/williamboman/mason.nvim/issues/1250) and [this](https://github.com/mxsdev/nvim-dap-vscode-js/issues/42)  for more context. 

Anyway, install with `:Mason` the newest `js-debug-adapter` for `vscode-js-debug` (>1.77.0). In particular, I do not use  `nvim-dap-vscode-js` anymore.

This is what my `user/plugins/community.lua` looks like.
```lua
return {
  -- Add the community repository of plugin specifications
  "AstroNvim/astrocommunity",
  -- example of imporing a plugin, comment out to use it or add your own
  -- available plugins can be found at https://github.com/AstroNvim/astrocommunity

  -- { import = "astrocommunity.colorscheme.catppuccin" },
  { import = "astrocommunity.pack.typescript" },
}
```
And this is what my `user/plugins/dap.lua` looks like 
```lua
return {
  "mfussenegger/nvim-dap",
  dependencies = {
    { "theHamsta/nvim-dap-virtual-text", config = true },
  },
  config = function()
    local dap = require "dap"
    require("dap").adapters["pwa-node"] = {
      type = "server",
      host = "localhost",
      port = "${port}",
      executable = {
        command = "js-debug-adapter", -- As I'm using mason, this will be in the path
        args = { "${port}" },
      }
    }

    for _, language in ipairs { "typescript", "javascript" } do
      require("dap").configurations[language] = {
        {
          type = "pwa-node",
          request = "launch",
          name = "Launch file",
          program = "${file}",
          cwd = "${workspaceFolder}",
        },
      }
    end
  end,
}
```

**Comment by akiranguyenvni** [comment]
> I got it running. In short, vscode changed their `vscode-js-debug`. Then Mason had to update, while the compatibility layer `nvim-dap-vscode-js` became obsolete. See [this](https://github.com/williamboman/mason.nvim/issues/1250) and [this](https://github.com/mxsdev/nvim-dap-vscode-js/issues/42) for more context.
> 
> Anyway, install with `:Mason` the newest `js-debug-adapter` for `vscode-js-debug` (>1.77.0). In particular, I do not use `nvim-dap-vscode-js` anymore.
> 
> This is what my `user/plugins/community.lua` looks like.
> 
> ```lua
> return {
>   -- Add the community repository of plugin specifications
>   "AstroNvim/astrocommunity",
>   -- example of imporing a plugin, comment out to use it or add your own
>   -- available plugins can be found at https://github.com/AstroNvim/astrocommunity
> 
>   -- { import = "astrocommunity.colorscheme.catppuccin" },
>   { import = "astrocommunity.pack.typescript" },
> }
> ```
> 
> And this is what my `user/plugins/dap.lua` looks like
> 
> ```lua
> return {
>   "mfussenegger/nvim-dap",
>   dependencies = {
>     { "theHamsta/nvim-dap-virtual-text", config = true },
>   },
>   config = function()
>     local dap = require "dap"
>     require("dap").adapters["pwa-node"] = {
>       type = "server",
>       host = "localhost",
>       port = "${port}",
>       executable = {
>         command = "js-debug-adapter", -- As I'm using mason, this will be in the path
>         args = { "${port}" },
>       }
>     }
> 
>     for _, language in ipairs { "typescript", "javascript" } do
>       require("dap").configurations[language] = {
>         {
>           type = "pwa-node",
>           request = "launch",
>           name = "Launch file",
>           program = "${file}",
>           cwd = "${workspaceFolder}",
>         },
>       }
>     end
>   end,
> }
> ```

Yes! Worked like a charm. Thank @mortang2410 a lot.

@mehalter Solution of @mortang2410 works, I tried successfully already.
We need not to config in the file `user/init.lua` any more. Just make a `user/plugins/dap.lua` and add above codes. Then we can debug Js file. Hope it's useful for you to update the documents.

Thank you guys a lot.

**Comment by eagle-tex** [comment]
@mortang2410 Thanks for your solution but it does not work for TypeScript on my end. Does it work for you?
Did you add something to make it work for TypeScript ?
