### ISSUE TITLE
Blinking cursor issue in specific layout

### ISSUE THREAD

**Issue by bassamsdata** [AstroNvim/AstroNvim#1424]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.8.5

### Neovim version (>= 0.8)

NVIM v0.8.1

### Operating system/version

macOS 12.6

### Describe the bug

Blinking  cursor in the intersection of 3 windows split whenever you press any movement (j,k,l,h). I find it really annoying, but it becomes unusable in NeoVide.

Kitty:
https://asciinema.org/a/oq30TFsQi3hCPsfuGmco0O4ay

Alacritty: (It's showing black cursor in the video but it's actual white color in reality)
https://asciinema.org/a/n6ckNH95fX6fDjqmONkzB7ISp

### Steps to Reproduce

1. open any file with Astrovim
2. command :vs
3. command :split

now you have 3 windows: 1 on the left and 2 on the right (horizental)
try to move the cursor acrross the file and you'ss see blinking cursor on the intersection of the 3 splits.

### Expected behavior

No blinking cursor in the intersection

### Screenshots

video of neovide. it becoms here unusable at all.

![Video of v=nrovide](https://user-images.githubusercontent.com/105807570/205760445-ef0b757e-478e-46a4-970c-2b6f8247262e.mov)

### Additional Context

It's only happens with this layout.

**Comment by mehalter** [comment]
This looks to be related to the cursor jumping around when updating `winbar`. There have been similar Neovim bugs with cmdheight as well. I improved the refresh rate of the winbar to decrease this a lot. Could you try the latest nightly and see if you get better results?

**Comment by bassamsdata** [comment]
I have the same issue after the update, **maybe** it got a better a bit but yea the same issue.

My cursor now goes all the way to the left and stays there 🫣 if I scroll down or up quickly (which is not the normal behavior).

![cursor video](https://asciinema.org/a/QxGyGynbwfTaykmRfVO4izvV1)

**Comment by bassamsdata** [comment]
I revert back to the main branch, yea I noticed that the blinking cursor was worse. Also the behaviour of the cursor is good and doesn't go to left now.

**Comment by bassamsdata** [comment]
Ah perfect, not only the issue has been resolved but the performance improved with multiple windows even in different windows layout.
Thanks a lot.

**Comment by mehalter** [comment]
Awesome! Glad to hear it! Thanks for reporting this, definitely was a sneaky little performance issue

**Comment by bassamsdata** [comment]
@mehalter Actually I feel ashamed that I haven't tested the insert mode in the morning 😕 because it has the same issue. It works perfectly with the other modes. I'm not sure if you have the same and if the solution is applicable in the insert mode.

**Comment by mehalter** [comment]
I will still keep this in the front of my mind though and keep pondering it to see if I can come up with some way to combat this, but from my testing it seems like it may be deeper into the core code of Neovim

**Comment by bassamsdata** [comment]
Yea probably with neovim code itself. thanks a lot for your time, I really appreciate the solution you did, that helped me a lot. 🙏
