### ISSUE TITLE
Error checking out branch: origin/main while doing :AstroUpdate

### ISSUE THREAD

**Issue by Starlexxx** [AstroNvim/AstroNvim#1426]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.8.5

### Neovim version (>= 0.8)

NVIM v0.8.1

### Operating system/version

macOS v.12.6

### Describe the bug

Can't update AstroNvim via :AstroUpdate

### Steps to Reproduce

1. Open iterm2;
2. type nvim +AstroUpdate

### Expected behavior

AstroNvim update

### Screenshots

<img width="409" alt="image" src="https://user-images.githubusercontent.com/39801789/206152964-16d2a01d-3a87-45cb-8070-6b6d254df33c.png">

### Additional Context

But it'possible to update via
1. `cd ~/.config/nvim`
2. `git pull`
Output of
`git rev-parse --abbrev-ref HEAD`
main

**Comment by mehalter** [comment]
@Starlexxx what do you get if you run `:lua =require("core.utils.git").current_branch()` in AstroNvim?

**Comment by med-ridha** [comment]
i ran into the same problem. I changed the default shell back to bash and it worked fine. I was using fish shell with oh-my-posh and it kept putting random characters in the ":lua =require("core.utils.git").current_branch()" output

**Comment by mehalter** [comment]
@med-ridha ah this is something I definitely wasn't accounting for. I didn't realize ANSI escape codes for stuff like color might come into play here. Could you try the latest `nightly` and see if you are able to run `:AstroUpdate` now with `fish`? I added some sanitation to remove ANSI escape sequences.

@Starlexxx is this also the same problem you are running into? Could you also try the latest `nightly` and see if that resolves the issue?

**Comment by med-ridha** [comment]
> @med-ridha ah this is something I definitely wasn't accounting for. I didn't realize ANSI escape codes for stuff like color might come into play here. Could you try the latest `nightly` and see if you are able to run `:AstroUpdate` now with `fish`? I added some sanitation to remove ANSI escape sequences.
> 
> @Starlexxx is this also the same problem you are running into? Could you also try the latest `nightly` and see if that resolves the issue?

Yes now it works in ```nightly```
![outputnightly](https://user-images.githubusercontent.com/51748062/206473148-77435a37-196d-4430-ae60-2d9f845b2357.png)

**Comment by mehalter** [comment]
Awesome!

**Comment by sigaloid** [comment]
If anyone else runs into this issue, check if you edited your fish config - I added a bit to mine and apparently it caused the same issue.
