### ISSUE TITLE
Inconsistent behavior with "go to definition" with cssmodules_ls + Typescript

### ISSUE THREAD

**Issue by KhudhurM** [AstroNvim/AstroNvim#1427]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.8.5

### Neovim version (>= 0.8)

NVIM v0.8.0

### Operating system/version

macOS 13.0.1

### Describe the bug

Go to definition on CSSModules goes to type definitions sometimes instead of the CSS class and line.

### Steps to Reproduce

1. Install tsserver and cssmodules_ls with TSInstall.
2. Create a new CSSModule
```
.test {
  z-index:1
}
```
3. Create a new .tsx component
```
import styles from "./Test.module.css";

export function ExampleComponent() {
  return <div className={styles.test}>Example</div>;
}
```
4. Press "gd" on styles.test and it'll go to the typed definitions of CSSModules

### Expected behavior

It's expected that go to definition opens a new buffer in the CSS module file / line as in the [VSCode Extension](https://github.com/clinyong/vscode-css-modules) that cssmodules_ls intented to imitate.

### Screenshots

[A video of this behaviour](https://share.cleanshot.com/CyAXpp)

### Additional Context

I think the TSServer is clashing with cssmodules_ls for "go to definition". It's a known issue in [cssmodules_ls](https://github.com/antonk52/cssmodules-language-server) and the proposed workaround was to use "go to implementation" and disable the "go to definition" instead.

It might also be useful to add a part of this to the documentation.

PS: I'm still a beginner with NVim / AstroNvim, apologies for any oversights.

**Comment by mehalter** [comment]
We have go to implementation bound to `gI` if you want to use that instead. This is unrelated to AstroNvim and is a known issue with the language server itself so I will go ahead and close this.

**Comment by KhudhurM** [comment]
Will create a PR on cssmodules_ls, thanks!
