### ISSUE TITLE
DAP UI have missing icons

### ISSUE THREAD

**Issue by Juniar-Rakhman** [AstroNvim/AstroNvim#1433]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.9.1

### Neovim version (>= 0.8)

 v0.8.0

### Operating system/version

Pop OS 22.04

### Describe the bug

Some DAP UI icons are not displaying correctly. Other icons look fine though. 
are there additional icons I need to install? if so which one? can we just use existing icons defined in nerd_font.lua?

### Steps to Reproduce

1. Open astro-nvim
2. Toggle DAP-UI (<leader>DU)

### Expected behavior

DAP UI icons are displayed correctly

### Screenshots

![2022-12-09_09-32](https://user-images.githubusercontent.com/2460346/206611383-8c6f3a7b-3c7d-4fe6-8740-bc6ee6d9d533.png)

**Comment by mehalter** [comment]
Please make sure you have an up to date nerd font. That is what `nvim-dap-ui` relies on and the other icons as well
