### ISSUE TITLE
how to make configuration change effective?

### ISSUE THREAD

**Issue by fcangss** [AstroNvim/AstroNvim#1434]
### Is your feature related to a problem?
i installed symbols-outline, it works well,but i want to change some configurations in /usr/init.lua, like this:
{
      	"simrat39/symbols-outline.nvim",
      	config = function()
      	  require("symbols-outline").setup{
      	    relative_width = false, 
            position = 'left',
            width = 25
      	  }
      	end,
      },
it doesn't work, how could i get the configurations work?

_No response_

**Comment by mehalter** [comment]
The code looks fine, it seems like you probably haven't synced Packer if it's not working.

Also for future reference, this isn't a feature request. Please refer to the subreddit (r/AstroNvim) or the official discord for asking questions with the community.
