### ISSUE TITLE
`heirline.lua` in `user` folder doesnt work

### ISSUE THREAD

**Issue by ChrisMGeo** [AstroNvim/AstroNvim#1435]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.9.1

### Neovim version (>= 0.8)

NVIM v0.8.0-1210-gd367ed9b2

### Operating system/version

Windows 10

### Describe the bug

I want to change the seperators and colors for my `heirline` (`init.lua` > `config` > `heirline`), NOT the components and the layout (`init.lua` > `config` > `plugins` > `heirline`), so I assumed since I could split the config for the layout and components to `user/plugins/heirline.lua`, that I could do the same for the colors and seperators through `user/heirline.lua`, but this doesn't work. Is there a way to do this or must I do it in the `init.lua` 

### Steps to Reproduce

1. Create a `user/heirline.lua` file, and edit it like you would in your config file.
```lua
return {
  heirline = {colors={bg = "#121212", section_bg = "#121212"}, seperators={}},
  plugins = {
    heirline = {{}, {}}
  }
}
```

### Expected behavior

Be able to edit the seperators and colors of `heirline` through folder structure.

**Comment by mehalter** [comment]
Check out the documentation for the file names for table options: https://astronvim.github.io/Configuration/config_options
