### ISSUE TITLE
Error when processing BufReadPost Autocommands for "*"

### ISSUE THREAD

**Issue by sudoDavi** [AstroNvim/AstroNvim#1438]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

Version: v2.9.1

### Neovim version (>= 0.8)

NVIM v0.8.0-1210-gd367ed9b2

### Operating system/version

Debian GNU/Linux 11 (bullseye) x86_64

### Describe the bug

Whenever I open AstroNvim and open help with F1, the first time it opens it displays the following error message:
This is a fresh install of AstroNvim, I only have rust-analyzer and rustfmt installed on it, I've removed and reinstalled AstroNvim 2 times already.
After pressing OK on this error message it doesn't show up until the next time I open nvim again.
Also I've only noticed this now because I tried updating AstroNvim earlier today, I think I was in version 2.6 or 2.7, I don't remember right now, but the update failed completely and I had to reinstall, after installing the latest stable version (I just followed the guide on the github page), I've noticed this version is way less stable than the previous one I was using and I have this annoying error message each time I press F1, I get similar error messages if I do "SPC d" then the program just flies off the rails and shows error message after error message, the only escape is with a :q command
```
Erro detectado ao processar BufReadPost Autocommands for "*":
Error executing lua callback: /usr/share/nvim/runtime/filetype.lua:22: Error executing
 lua: /usr/share/nvim/runtime/filetype.lua:23: Vim(append):Error executing lua callbac
k: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type 
at position 14 for language help
stack traceback:
        [C]: in function '_ts_parse_query'
        /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219: in function 'get_que
ry'
        /usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:52: in function 'n
ew'
        /usr/share/nvim/runtime/lua/vim/treesitter.lua:45: in function '_create_parser
'
        /usr/share/nvim/runtime/lua/vim/treesitter.lua:96: in function 'get_parser'
        ...er/opt/nvim-treesitter/lua/nvim-treesitter/highlight.lua:34: in function 's
tart'
        ...er/opt/nvim-treesitter/lua/nvim-treesitter/highlight.lua:42: in function 'a
ttach'
        ...cker/opt/nvim-treesitter/lua/nvim-treesitter/configs.lua:505: in function '
attach_module'
        ...cker/opt/nvim-treesitter/lua/nvim-treesitter/configs.lua:528: in function '
reattach_module'
        ...cker/opt/nvim-treesitter/lua/nvim-treesitter/configs.lua:131: in function <
...cker/opt/nvim-treesitter/lua/nvim-treesitter/configs.lua:130>
        [C]: in function 'nvim_cmd'
        /usr/share/nvim/runtime/filetype.lua:23: in function </usr/share/nvim/runtime/
filetype.lua:22>
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:22: in function </usr/share/nvim/runtime/
filetype.lua:11>
stack traceback:
        [C]: in function 'nvim_cmd'
        /usr/share/nvim/runtime/filetype.lua:23: in function </usr/share/nvim/runtime/
filetype.lua:22>
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:22: in function </usr/share/nvim/runtime/
filetype.lua:11>
stack traceback:
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:22: in function </usr/share/nvim/runtime/
filetype.lua:11>
```

### Steps to Reproduce

1. Open nvim
2. Press F1 to open help
3. Error message is displayed

### Expected behavior

That the it doesn't show an error message when trying to open the help page.

**Comment by sudoDavi** [comment]
Also, I've tried installing tree-sitter-cli, since that's listed as a requirement and the error message is mentioning tree-sitter, but after installing it, the problem kept happening.

**Comment by mehalter** [comment]
Looks like you need to reinstalling the treesitter parser for `help`. Run `:TSInstall help`

**Comment by sudoDavi** [comment]
Ok, that did it, thanks.
