### ISSUE TITLE
Error showing up when update to AstroNvim 2.9.1

### ISSUE THREAD

**Issue by duytrung** [AstroNvim/AstroNvim#1439]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.9.1

### Neovim version (>= 0.8)

0.8.1

### Operating system/version

Windows 10

### Describe the bug

I'm not sure what type of bug is this. 

I used the command nvim to edit a file but the program showed a message 

```


Error detected while processing modelines[34069]..FileType Autocommands for "*":
Error executing lua callback: ...\release\share\nvim\runtime/lua\vim\treesitter\query.lua:219: query: invalid node type at position 14 for language help
stack traceback:
        [C]: in function '_ts_parse_query'
        ...\release\share\nvim\runtime/lua\vim\treesitter\query.lua:219: in function 'get_query'
        ...e\share\nvim\runtime/lua\vim\treesitter\languagetree.lua:52: in function 'new'
        ...NeoVim\release\share\nvim\runtime/lua\vim\treesitter.lua:45: in function '_create_parser'
        ...NeoVim\release\share\nvim\runtime/lua\vim\treesitter.lua:96: in function 'get_parser'
        ...er\opt\nvim-treesitter/lua\nvim-treesitter\highlight.lua:34: in function 'start'
        ...er\opt\nvim-treesitter/lua\nvim-treesitter\highlight.lua:42: in function 'attach'
        ...cker\opt\nvim-treesitter/lua\nvim-treesitter\configs.lua:505: in function 'attach_module'
        ...cker\opt\nvim-treesitter/lua\nvim-treesitter\configs.lua:528: in function 'reattach_module'
        ...cker\opt\nvim-treesitter/lua\nvim-treesitter\configs.lua:131: in function <...cker\opt\nvim-treesitter/lua\nvim-treesitter\configs.lua:130>
Press ENTER or type command to continue

```
This could be from the plugin. I'm not sure

Thanks for reviewing the issue

### Steps to Reproduce

1. Go to the folder using command line console.
2. Use 'dir' to list the available files.
3. Type "nvim file.txt" to edit the file.
4. The error showed up

### Expected behavior

Not showing up any error

### Screenshots

![image](https://user-images.githubusercontent.com/2046672/207317906-5b33fa3a-45a1-4dbf-ab2c-da0e7f685739.png)

**Comment by convers39** [comment]
I have the same issue, `:TSInstall help` also triggered the error, try to restart nvim and use `:TSInstallSync help` to solve my problem.
