### ISSUE TITLE
null-ls prettier formatting differently vs prettier command

### ISSUE THREAD

**Issue by tom-james-watson** [AstroNvim/AstroNvim#1440]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.9.1

### Neovim version (>= 0.8)

v0.8.0-1210-gd367ed9b2

### Operating system/version

Ubuntu 22.04

### Describe the bug

When I format a file with prettier, I get slightly different formatting vs using `prettier` via the command line. As far as I can tell, null-ls looks for a global `prettier` executable and uses that, so I would expect them to produce the same result.

This ends up with me constantly modifying the formatting of all files on format due to it having a different format vs what our CI enforces, even though I'm ostensibly using the same version.

### Steps to Reproduce

Add prettier to astronvim's null-ls config:

```
      config.sources = {
        null_ls.builtins.formatting.prettier,
      }
```

Globally install latest prettier (2.8.1): `npm i -g prettier@latest`.

Create a `test.ts` file:

```ts
type Example =
  | {
    foo: boolean;
  }
  | {
    bar: boolean;
  };

export { };
```

Open and run `:Format` and save.

On the cli, run `prettier -w test.ts` and see that the file updates to slightly different indentation.

### Expected behavior

A format with the prettier executable should work in the exact same way as a format via astronvim.

**Comment by mehalter** [comment]
Do you have prettier installed with Mason?

**Comment by tom-james-watson** [comment]
Just with an npm global install.

**Comment by mehalter** [comment]
Ah alright, I'm honestly not sure. It might be worth reaching out to the `null-ls` people to see how they are running prettier and see what's differing. We aren't handling any of that in AstroNvim and it's all done with null-ls

**Comment by mehalter** [comment]
Do you have any other language servers installed with typescript? Maybe `tsserver` that might also be formatting bad well

**Comment by tom-james-watson** [comment]
Yeah tsserver is installed, too. How would I check if that is happening? I would have thought if I haven't defined anything else in the formatters list then nothing else would be formatting.

**Comment by mehalter** [comment]
All language servers can support formatting, null-ls just adds LSP interface support to other tools that aren't language servers. Try disabling formatting from `tsserver` like shown here:

https://astronvim.github.io/Recipes/advanced_lsp#disabling-formatting-for-a-list-of-language-servers

**Comment by tom-james-watson** [comment]
That was it!! Explicitly disabling `tsserver` with

```
      filter = function(client)
        -- disable formatting for tsserver
        if client.name == "tsserver" then
          return false
        end

        -- enable all other clients
        return true
      end,
```

has fixed it. So yeh, was a clash between `tsserver` and `prettier`.

Thanks for your quick help, much appreciated. Keep up the good work :+1:

**Comment by mehalter** [comment]
No problem! And you can also use the `lsp.formatting.disabled` table as well to simplify your user configuration if you want
