### ISSUE TITLE
Poor syntax highlighting for typescript

### ISSUE THREAD

**Issue by sativ01** [AstroNvim/AstroNvim#1441]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

Version: v2.9.1

### Neovim version (>= 0.8)

NVIM v0.8.0

### Operating system/version

macOS 13.0.1

### Describe the bug

As the title says, here's comparison of AstroNvim vs LunarVim vs VS Code:
LunarVim:
![image](https://user-images.githubusercontent.com/25383282/207326357-183fba76-32fc-4155-9872-eb0be4022811.png)

VS Code 
![image](https://user-images.githubusercontent.com/25383282/207326413-08e1e320-8858-4d52-9652-ed9ec2434297.png)

AstroNvim:
![image](https://user-images.githubusercontent.com/25383282/207326604-6ad5ef34-e827-4076-a0bb-660e9feac7a9.png)

LunarVim and VS Code look identical, but AstroNvim is lacking some coloring. 
LSP works fine, I can navigate with "go to definition"
I have tree-sitter-cli installed globally

Seems like the problem is with tree-sitter, but I'm not sure how to debug and what to check

Would appreciate any tips on diagnostic and/or resolution. 
Thanks!

### Steps to Reproduce

1. start nvim
2. follow installation steps, update all deps
3. open typescript file
4. notice the lack of syntax highlighting in multiple locations

### Expected behavior

syntax highlighting same as in other editors

**Comment by mehalter** [comment]
Make sure you install the treesitter highlighter with `:TSInstall typescript`
