### ISSUE TITLE
Add CurSearch to default_theme

### ISSUE THREAD

**Issue by gwww** [AstroNvim/AstroNvim#1443]
### Describe the new feature

To help distinguish the current search item over the other matches, setting the highlight CurSearch helps. I'd submit as a PR except you know the color palette better than I do, although, looking through the colors, orange looked like it might be nice.

**Comment by mehalter** [comment]
Thanks for the suggestion! I just added a commit for this to the `nightly` channel. It is pretty standard to do the reverse of the search highlight group which is also what we use for `IncSearch`. I will go ahead and close this as this nightly will become stable sometime this week as I finish up some stuff.
