### ISSUE TITLE
Cannot run :DapInstall

### ISSUE THREAD

**Issue by Rawnly** [AstroNvim/AstroNvim#1444]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.9.1

### Neovim version (>= 0.8)

0.8.1

### Operating system/version

macOS 13.0

### Describe the bug

When I try to setup my config for `dap` I cannot run `DapInstall` or find any related shortcut. is there any lazy-load based on files or something?

### Steps to Reproduce

- Update from `2.8.1` to `2.9.1` (if this is relevant somehow)
- Run`:DapInstall` or search the command

### Expected behavior

I'd expect to be able to install debuggers 

### Screenshots

![CleanShot 2022-12-14 at 01 54 08@2x](https://user-images.githubusercontent.com/16429579/207478088-1f7ffb45-169a-4273-9d27-0c7a56503ab5.png)
> When searching 

![CleanShot 2022-12-14 at 02 00 10@2x](https://user-images.githubusercontent.com/16429579/207478543-fde13b77-f406-42dc-a6ef-d035fba18778.png)
> When trying to run

![CleanShot 2022-12-14 at 02 00 28@2x](https://user-images.githubusercontent.com/16429579/207478600-2a6007fb-3702-467a-9056-4f06e90efaf8.png)
> Keybindings

### Additional Context

My config: https://github.com/Rawnly/nvim-config

**Comment by mehalter** [comment]
I don't see the mappings in your which key for debugging. Please make sure you have run a packer sync and are indeed running the latest version. It seems like nvim-dap isn't installed or else the bindings would be there.

**Comment by Rawnly** [comment]
I just restarted it a few other times and now it is working lol maybe some issues with the latest sync
