### ISSUE TITLE
Windows bootstrap fails

### ISSUE THREAD

**Issue by rlkandela** [AstroNvim/AstroNvim#1445]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.9.1

### Neovim version (>= 0.8)

NVIM v0.8.1

### Operating system/version

Windows 10

### Describe the bug

When you clone the github repo (main branch) and use the default configs, just opening neovim starts the plugin installation.
When it seems to have finished, the message "All parsers are up-to-date!" appears at the bottom and all the plugins have a check ✓ but `telescope-fzf-native.nvim`, which has a ⟳ (my font doesn't seem to have an icon for it).
It also displays this message
![imagen](https://user-images.githubusercontent.com/28935609/207532572-574b79dc-5bf1-482c-bd9f-a6391430605c.png)

Now, if I close neovim and open it again, this error message pops up
```
Se ha detectado un error al procesar C:\Users\raul\AppData\Local\nvim\init.lua:
Failed to load core.bootstrap

...\site\pack\packer\start\impatient.nvim/lua/impatient.lua:95: Could not hash C:\Users\raul\AppData\Local\nvim-data/packer_compiled.lua
Pulse INTRO o escriba una orden para continuar
```
And indeed packer_compiled.lua does not exist on my nvim-data folder.

This also breaks my user configuration as I can't run `nvim --headles blah blah` because it will never end.

The only way I have found to go around this and use it is to:
1. Delete the just created `nvim-data` folder
2. Rerun nvim and wait untill all plugins are synchronized
3. Instead of closing neovim, run `:PackerCompile`
4. Now close neovim and it will be working

### Steps to Reproduce

1. Clear previous config and data
2. Clone repository
3. Run `nvim`
4. Close neovim when it "finishes"
5. Reopen `nvim`

### Expected behavior

To generate a packer_compiled.lua

**Comment by mehalter** [comment]
How long did you wait for it to install? `telescope-fzf-native` does run a compilation of its own binary which might take some time on a machine depending on the hardware, but I'm not sure. The error you took a screenshot of doesn't have much to work with, maybe it could also be something with your network not allowing something to download. I am not able to replicate this on my Windows virtual machine

**Comment by impeterk** [comment]
Same issue. I am waiting for about 15mins right now
![image](https://user-images.githubusercontent.com/15304930/208316094-a5417fd6-fa5f-418a-bc41-22fb4a13b0e2.png)

**Comment by mehalter** [comment]
@impeterk @rlkandela could you try on nightly? It looks like `telescope-fzf-native` recently pushed out a fix for windows installation which apparently was broken for a bit

**Comment by rlkandela** [comment]
> @impeterk @rlkandela could you try on nightly? It looks like `telescope-fzf-native` recently pushed out a fix for windows installation which apparently was broken for a bit

@mehalter I just tried it on nightly branch and it also freezes, I have been waiting for around 12 minutes
![imagen](https://user-images.githubusercontent.com/28935609/208428154-97976a7e-987d-4ba6-8389-7b7dbc5006f6.png)

**Comment by mehalter** [comment]
@rlkandela it's probably a good idea to not do this test headless just to make sure we know what's hanging

**Comment by mehalter** [comment]
@rlkandela @impeterk Could you try going to the folder where the repo was cloned, Should be something like `C:\Users\<REPLACE_WITH_USER>\AppData\Local\nvim-data\site\pack\packer\opt\telescope-fzf-native.nvim` make sure to pull the latest with `git pull` and then run `make` and see what it outputs

**Comment by rlkandela** [comment]
@mehalter This time when I cloned and started nvim without headless worked perfectly and also seted up my user config, I didn't realy changed anything from the last time I did it

**Comment by rlkandela** [comment]
> @mehalter This time when I cloned and started nvim without headless worked perfectly and also seted up my user config, I didn't realy changed anything from the last time I did it

I just noticed that there was a commit an hour ago in nightly branch that updates the commit reference of `telescope-fzf-native.nvim`, seems like that fixes this.

I guess the issue can be clossed and marked as completed.
