### ISSUE TITLE
How to use python virtual environment within DAP

### ISSUE THREAD

**Issue by gminorcoles** [AstroNvim/AstroNvim#1449]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.9.1

### Neovim version (>= 0.8)

0.8.1

### Operating system/version

ubuntu 20 lts

### Describe the bug

I am trying to use an existing python project not written by me as a test for neovim python workflow. I use pyenv to force the python version to 3.8.11. I installed the project using python3 setup.py install. This makes it possible to run some python files inside the project and imports resolve correctly, from to command line. In neovim I call :!python3 % and it also runs correctly. But when I try to run the same python file in dap, I get errors saying that a module in the project cannot be found. 

It seems that the python version I am using in pyenv is not getting picked up by neovim. I print out the executable path and form inside dap the path is some python down under Mason's directory tree. 

I would like to point neovim at the python executable which is found by running the shell command "pyenv which python3". I am new to Lua and I am not getting this to work yet using os.execute. I cant find any examples in AstroNvim config files of dynamically setting python3_prog_host based on the output of a shell command and I wonder if anyone can help. Sorry to spam this forum but this is not an easily google-able thing. 

### Steps to Reproduce

run python inside neovim and outside, get different results. 

### Expected behavior

python runs inside neovim with the same python path as outside neovim.

**Comment by ocarl** [comment]
You need to set your python binary explicitly for the dap in your init.lua. I have this set for mine for three different configurations:

```
local dap = require('dap')
dap.configurations.python = {
  {
    -- The first three options are required by nvim-dap
    type = 'python'; -- the type here established the link to the adapter definition: `dap.adapters.python`
    request = 'launch';
    name = "Test";

    -- Options below are for debugpy, see https://github.com/microsoft/debugpy/wiki/Debug-configuration-settings for supported options

    gevent = true;
    program = "setup.py";
    args = {"test", "-v"};
    pythonPath = function()
      -- debugpy supports launching an application with a different interpreter then the one used to launch debugpy itself.
      -- The code below looks for a `venv` or `.venv` folder in the current directly and uses the python within.
      -- You could adapt this - to for example use the `VIRTUAL_ENV` environment variable.
      local cwd = vim.fn.getcwd()
      if vim.fn.executable(cwd .. '/venv/bin/python') == 1 then
        return cwd .. '/venv/bin/python'
      elseif vim.fn.executable(cwd .. '/.venv/bin/python') == 1 then
        return cwd .. '/.venv/bin/python'
      else
        return '/usr/bin/python'
      end
    end;
  },
  {
    -- The first three options are required by nvim-dap
    type = 'python'; -- the type here established the link to the adapter definition: `dap.adapters.python`
    request = 'launch';
    name = "Flask run";

    -- Options below are for debugpy, see https://github.com/microsoft/debugpy/wiki/Debug-configuration-settings for supported options

    gevent = true;
    program = "debug.py";
    pythonPath = function()
      -- debugpy supports launching an application with a different interpreter then the one used to launch debugpy itself.
      -- The code below looks for a `venv` or `.venv` folder in the current directly and uses the python within.
      -- You could adapt this - to for example use the `VIRTUAL_ENV` environment variable.
      local cwd = vim.fn.getcwd()
      if vim.fn.executable(cwd .. '/venv/bin/python') == 1 then
        return cwd .. '/venv/bin/python'
      elseif vim.fn.executable(cwd .. '/.venv/bin/python') == 1 then
        return cwd .. '/.venv/bin/python'
      else
        return '/usr/bin/python'
      end
    end;
  },
  {
    -- The first three options are required by nvim-dap
    type = 'python'; -- the type here established the link to the adapter definition: `dap.adapters.python`
    request = 'launch';
    name = "Launch file";

    -- Options below are for debugpy, see https://github.com/microsoft/debugpy/wiki/Debug-configuration-settings for supported options

    gevent = true;
    program = "${file}"; -- This configuration will launch the current file if used.
    pythonPath = function()
      -- debugpy supports launching an application with a different interpreter then the one used to launch debugpy itself.
      -- The code below looks for a `venv` or `.venv` folder in the current directly and uses the python within.
      -- You could adapt this - to for example use the `VIRTUAL_ENV` environment variable.
      local cwd = vim.fn.getcwd()
      if vim.fn.executable(cwd .. '/venv/bin/python') == 1 then
        return cwd .. '/venv/bin/python'
      elseif vim.fn.executable(cwd .. '/.venv/bin/python') == 1 then
        return cwd .. '/.venv/bin/python'
      else
        return '/usr/bin/python'
      end
    end;
  },
}

```

**Comment by gminorcoles** [comment]
Ok many thanks for the detailed answer. May I ask out of curiosity why the python path in dap in my current config seems to default to this python nested within the Mason plugin? I dont have the exact path right now but it seems a bit weird. 

I need to learn some Lua but this gets me going in the correct direction.

**Comment by gminorcoles** [comment]
Ok I am a bit confused. I went through the steps in the documentation to copy an example init.lua into the user directory. I then pasted your code into that init.lua file. I looked at the very specific things you entered for the different configurations which address your needs, like flask, etc. I realized that I dont need at this point to reconfigure the dap python adapter, I just need to change one thing, the pythonPath. 

In the nvim-dap-python code there is an M.setup function which indeed takes the adapter_python_path as an argument. Later on, in the default configuration upon initialization of the adapter, there is a get_python_path() function which indeed uses VIRTUAL_ENV. to build the same path you are building by convention (in my case this env var points to the venv subdirectories in my project.)

I cannot find in the mason loading code or the AstroNvim code where the adapter_python_path is passed to the setup() function of the ivim-dap-python adapter, I havent found reference to that adapter because I guess Mason using a generic Api to load plugins. 

Is there a way to inject the python path from VIRTUAL_ENV without stepping on the entire dap python configuration? I dont have any evidence yet that I am unhappy with anything in dap except for the path. 

Sorry its hard to piece this together there is a lot of indirection in the lua code spread between different git projects.

**Comment by blankRiot96** [comment]
Hey, you can also just activate your venv before launching nvim and it uses the python in the venv 




https://user-images.githubusercontent.com/77634274/208261027-800986c2-0894-4690-8df2-73cad77c1986.mp4

**Comment by mehalter** [comment]
@blankRiot96 yeah this works for the LSP `pyright` but it doesn't quite work like this with the `debugpy` DAP installed with Mason and configuration from `mason-nvim-dap`. I'm working on a patch fix for this to mason-nvim-dap hopefully

**Comment by gminorcoles** [comment]
if I activate the venv in a directory called testnim, pip3 install pynvim, then run print(sys.executable) from a python file called test.py, this returns the correct path ~/src/testnvim/bin/python3. If I open nvim in this directory and run :!python3 %, if returns the correct value. Then I run this from the dap debugger and it returns the wrong value. 

I added code from the example above to my user directories in /dap/confgurations.lua. It does not work and the dap configuration is not right, or not the same as the default anyway.

**Comment by mehalter** [comment]
@gminorcoles I just opened a PR on mason-nvim-dap to upstream this code. This should make it work out of the box once this is merged and I update stable to use the new commit: https://github.com/jay-babu/mason-nvim-dap.nvim/pull/30

**Comment by gminorcoles** [comment]
> @gminorcoles I just opened a PR on mason-nvim-dap to upstream this code. This should make it work out of the box once this is merged and I update stable to use the new commit: [jay-babu/mason-nvim-dap.nvim#30](https://github.com/jay-babu/mason-nvim-dap.nvim/pull/30)

@mehalter - thanks for helping me with this. I have a question about the separation of powers in the chain from Mason to Dap to the various adapters like the piton one - it seems to me from perusing the code that Mason sets up a plugin once, upon installation. So if it picks up env vars from a local virtual environment, this might not be what the user expects when they open Neovim the next time once the plugin is already installed, from a different cwd. Do you think this concern is misplaced? That is why I put the code into the dap configuration lua instead of the mason-vim-dap one. 

Thanks again.

**Comment by mehalter** [comment]
Plugins are set up each time the plugin loaded when neovim is started up. So this will work if Neovim is opened after the environment is loaded. Also this PR got merged so I am making a patch update to just update the pinned commit so that this is on stable. You should be able to remove your custom configuration for python here :)
