### ISSUE TITLE
Custom theme color override syntax

### ISSUE THREAD

**Issue by Onefabis** [AstroNvim/AstroNvim#1451]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v.2.9.1

### Neovim version (>= 0.8)

NVIM v0.8.0

### Operating system/version

Windows 11

### Describe the bug

Can't figure out how to set the background color override rule for that theme [sonokai](https://github.com/sainnhe/sonokai)
The docs says that I can do that in init.vim that way:
`g:sonokai_colors_override~`

Override color palette. The available keys can be found in
'/path/to/sonokai/autoload/sonokai.vim'.

E.g.
`
    let g:sonokai_colors_override = {'bg0': ['#1e222a', '235'], 'bg2': ['#282c34', '236']}
    colorscheme sonokai
`
But I can't find a way to add that line in the user/init.lua in section like that:
`options = {
    g = {...`
As far as I know that variable should be set before colorscheme applied in the init file

### Steps to Reproduce

1. Open init.lua
2. Install theme in plugins section `'sainnhe/sonokai',`
3. Add `colorscheme = 'sonokai', `
4. Add the line in options section: `sonokai_colors_override = {"bg0":['#000000', '235']}, ` 
5. Restart Astronvim

### Expected behavior

Background should be black colored

**Comment by mehalter** [comment]
You can just put this in the beginning of your `user/init.lua` file before you define your config. This will be loaded immediately at the beginning:

```lua
vim.g.sonokai_colors_override = { bg0 = { "#1e222a", "235" }, bg2 = { "#282c34", "236" } }

return {
  colorscheme = "sonokai",
  plugins = {
    init = {
      ["sainnhe/sonokai"] = {},
    },
  },
}
```

Or you could set this in your plugin definition and set the colorscheme yourself, something like this:

```lua
return {
  plugins = {
    init = {
      ["sainnhe/sonokai"] = {
        config = function()
          vim.g.sonokai_colors_override = { bg0 = { "#1e222a", "235" }, bg2 = { "#282c34", "236" } }
          vim.cmd.colorscheme "sonokai"
        end,
      },
    },
  },
}
```

**Comment by Onefabis** [comment]
You rock. Thank you very much!
Cheers!
