### ISSUE TITLE
Rename default_theme to astronvim

### ISSUE THREAD

**Issue by gwww** [AstroNvim/AstroNvim#1454]
### Describe the new feature

This would make it clear that the colorscheme is by AstroNvim.

**Comment by mehalter** [comment]
This is a good idea, I think it would be better to just rename it to `astronvim`

**Comment by mehalter** [comment]
This will be a breaking change, so this will have to wait until v3 whenever that gets released. Probably with v0.10 of Neovim since it looks like v0.9 isn't going to have any breaking changes

**Comment by gwww** [comment]
Thanks!

**Comment by mehalter** [comment]
I'm going to go ahead and close this issue because it's not tracking anything super important and the Projects provides a better roadmap
