### ISSUE TITLE
Plugin Vimya doesn't work (python plugin, name *** is not defined

### ISSUE THREAD

**Issue by Onefabis** [AstroNvim/AstroNvim#1455]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v.2.9.1

### Neovim version (>= 0.8)

NVIM v0.8.0

### Operating system/version

Windows 11

### Describe the bug

When I try to install that plugin [Vimya](https://github.com/vim-scripts/Vimya) and start the :py vimyaRun (:py vimyaRun()) or :py3 vimyaRun it always say that the name 'vimyaRun' is not defined. I think there is something wrong with the load order, since if I create the ~/nvim/autoload/pytest.vim and put that code in it it works fine if I run `:call pytest#printYay()`
  
```
echo "Initializing autoload plugin"  
python3 << END  
import neovim
def printYay():
    print("yay!")
END
function! pytest#printYay() abort
  :py3 printYay()
endfunction
```
Btw I have passed OK with the :CheckHealth provider
![Neovim_2022-12-17_15_47_35](https://user-images.githubusercontent.com/13187447/208242561-aee4ff92-d110-4ca7-8de4-3d687d37b09e.png)

### Steps to Reproduce

1. Dowlnoal plugin https://github.com/vim-scripts/Vimya
2. Install the plugin
3. Reload Astronvim
4. Run command `:py vimyaRun` or `:py vimyaRun()` or `:py3 vimyaRun`

### Expected behavior

Script at least should be visible for python in Astronvim like the pytest.vim

### Screenshots

![Neovim_2022-12-17_15_51_39](https://user-images.githubusercontent.com/13187447/208242727-dfaa7ac2-efe9-4f39-83ad-5bdd19d9203d.png)

**Comment by mehalter** [comment]
Some this is not using anything from within AstroNvim and it's just using core Neovim functionality with autoloading files and legacy scripts this isn't a bug in AstroNvim. I've never used this plugin so I don't know how to properly use it. It might be best to ask this question about how to install and use it on r/vim or r/neovim
