### ISSUE TITLE
Can I show mode in Astronvim ?

### ISSUE THREAD

**Issue by RedRx** [AstroNvim/AstroNvim#1456]
### Is your feature related to a problem?

Please help me

I'm read the document of Astronvim can not understand how can I show mode text.

### Describe the new feature

Astronvim must a easy way to config it

example
vim.opt.showmode = true

**Comment by Rid1-fz-06** [comment]
@RedRx You should use ```vim.opt.showmode = true``` and ```vim.opt.cmdheight=1``` together. Otherwise, it will not do the job.

**Comment by mehalter** [comment]
Here is the documentation for this: https://astronvim.github.io/Recipes/status#default-statusline-with-mode-text

If you have more questions the best place for discussions is on the community Discord or the subreddit.
