### ISSUE TITLE
JDTLS not working out of the box

### ISSUE THREAD

**Issue by Freemason-12** [AstroNvim/AstroNvim#1461]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.10.1

### Neovim version (>= 0.8)

v0.8.1

### Operating system/version

KDE Neon 5.26

### Describe the bug

After installing AstroNvim config correctly and making `:LspInstall jdtls` it just does not work and shows an error in the notifier

### Steps to Reproduce

1) `:LspInstall jdtls`
2) Open any `.java` file
3) See an error show up in the notifier

### Expected behavior

No errors and LSP working nicely (as it was before)

### Additional Context

The only way i was able to fix this is by using `jdtls-launcher` and putting this into the config. Not so good at Neovim (newbie).

**Comment by mehalter** [comment]
Check out #1292 , jdtls can take some manual configuration because it relies on eclipse being installed I believe
