### ISSUE TITLE
mintlinux安装AstroNvim失败报错

### ISSUE THREAD

**Issue by luochen570** [AstroNvim/AstroNvim#1463]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

最新

### Neovim version (>= 0.8)

0.6.1

### Operating system/version

linux mint

### Describe the bug

这个问题在linuxmint虚拟机中安装AstroNvim时出现
依赖安装没有任何问题
同样的操作在我的Arch Linux上面没有任何问题
以至于我尝试替换/.config/nvim/init.lua 但文件是一样的替换并没有解决我的问题
尝试https://astronvim.github.io/#%EF%B8%8F-installation的安装方法没有任何用
也尝试过https://github.com/AstroNvim/AstroNvim/issues/1294#issuecomment-1312481405的解决办法还是没有用
当然可有可能是我的neovim版本过于低 ：0.6.1
希望大佬尝试适配该版本的neovim

错误日志输出为下：
                                                                                                                                                                                    
Error detected while processing /home/mint/.config/nvim/init.lua:
Failed to load core.utils
/home/mint/.config/nvim/lua/core/utils/init.lua:14: attempt to index field 'keymap' (a nil value)
Failed to load core.options
vim/shared.lua:201: func: expected callable, got nil
Failed to load core.bootstrap
/home/mint/.config/nvim/lua/core/bootstrap.lua:1: attempt to call field 'initialize_packer' (a nil value)
Failed to load core.diagnostics
/home/mint/.config/nvim/lua/core/diagnostics.lua:2: attempt to call field 'get_icon' (a nil value)
Failed to load core.autocmds
/home/mint/.config/nvim/lua/core/autocmds.lua:62: attempt to call local 'augroup' (a nil value)
Failed to load core.mappings
/home/mint/.config/nvim/lua/core/mappings.lua:34: attempt to call local 'is_available' (a nil value)
Failed to load configs.which-key-register
/home/mint/.config/nvim/lua/configs/which-key-register.lua:28: attempt to call local 'is_available' (a nil value)
E5113: Error while calling lua chunk: /home/mint/.config/nvim/init.lua:17: attempt to call field 'user_plugin_opts' (a nil value)
stack traceback:
        /home/mint/.config/nvim/init.lua:17: in main chunk
Press ENTER or type command to continue

### Steps to Reproduce

git clone https://github.com/AstroNvim/AstroNvim ~/.config/nvim
nvim

git clone https://github.com/AstroNvim/AstroNvim ~/.config/nvim
nvim +PackerSync

### Expected behavior

无法安装AstroNvim

### Screenshots

<img width="1280" alt="Screenshot_20221221_192058" src="https://user-images.githubusercontent.com/96155235/208893800-2723bffc-c985-4b31-85e1-17286c0ec029.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/96155235/208893912-b3c76c20-9cf6-444d-8821-c8083074403b.png">

**Comment by mehalter** [comment]
Please update Neovim to a supported version. AstroNvim requires v0.8

**Comment by bryant-the-coder** [comment]
> Please update Neovim to a supported version. AstroNvim requires v0.8
@mehalter ping me if u need chinese support :> i know chinese cuz i m a chinese myself :))

**Comment by mehalter** [comment]
> > Please update Neovim to a supported version. AstroNvim requires v0.8
> @mehalter ping me if u need chinese support :> i know chinese cuz i m a chinese myself :))
> 

謝謝 ! I'll definitely keep that in mind! My Mandarin reading/writing is extremely bad haha

**Comment by bryant-the-coder** [comment]
lol :) uk chinese too? not bad :)

**Comment by bryant-the-coder** [comment]
i just cant get chinese working on fedora
