### ISSUE TITLE
Switch to Lazy Package Manager

### ISSUE THREAD

**Issue by mehalter** [AstroNvim/AstroNvim#1465]
### Is your feature related to a problem?

Packer has a lot of weirdness and things we don't like when it comes to maintenance. (1) the lazy loading in Packer is a bit complicated and makes it hard to make sure we are lazily loading plugins "correctly" and (2) the compilation phase with Packer is a bit weird and leads to a lot of issues if you don't remember to recompile the packer configuration.

### Describe the new feature

Adopt [lazy.nvim](https://github.com/folke/lazy.nvim) which has a more modern approach and a much more sane description of Lazy

### Additional context

During investigation of this it has also exposed some poor abstractions we made when it comes to configuring `cmp` and `cmp` sources. We will have to remove this as well and update the documentation for adding and configuring `cmp` sources. This in the end will also be a lot more flexible and powerful in general.

**Comment by GersiD** [comment]
I am very excited to switch to the lazy plugin manager. So much so that I switched to the lazy branch. I am on windows and I am having some issues. For example when I try and load vimtex in my ftplugin/tex.lua file (require('lazy').load('vimtex') it doesnt work. There are a couple of other problems out of the box on windows. Maybe its just me but I will list them here.
1. Loading plugins when they are meant to be loaded is not intuitive, neither can I get it to work. (Maybe I am just missreading the help pages for lazy.nvim)
2. Failed to run 'config' for mason.nvim, attempt to index a inll value named '_'

Please note that when I run :Lazy load vimtex in the vim command line that it does indeed load vimtex. However the lua function in the ftplugin/tex.lua file does not. I really can't make heads or tails of this and thus the information I have provided may not be sufficient. Please let me know if I can provide any more to help.

These are the main issues I am running into so far. If anyone could join the discourse and add any experiences they have had with the lazy branch that would be awesome! Thank you!

**Comment by GersiD** [comment]
After looking into it a bit more I think the issue is how the user plugin.init table is setup. Consider this output from checkhealth.

  5 lazy: require("lazy.health").check()
  6 ========================================================================
  7 ## lazy.nvim
  8   - OK: no existing packages found by other package managers
  9   - OK: packer_compiled.lua not found
 10   - WARNING: {lualine.nvim}: unknown key <setup>
 11   - WARNING: {leap.nvim}: unknown key <setup>
 12   - WARNING: {grapple.nvim}: unknown key <setup>

Notice how lazy reports that the setup key is unknown. The current format usually uses a setup and config key for when a package is setup and when a package is ready for configuration. I don't think that lazy works in this way but I don't know for sure. I just thought this was something worth saying.

**Comment by mehalter** [comment]
@GersiD you need to rename those keys to `init` as per the lazy documentation

**Comment by GersiD** [comment]
I had a feeling

**Comment by GersiD** [comment]
Thank you so much for your response, I love AstroVim by the way! Its an awesome project!

**Comment by GersiD** [comment]
After switching all the keys to be consistent with the lazy.nvim documentation. The error with mason and vimtex still persists. Do you reckon this is an Astrovim issue? Atleast for the mason config, given that I haven't changed that from stock.

**Comment by GersiD** [comment]
For context on the Mason issue it occurs on line 116 of the loader.lua file in nvim-data/lazy/lazy.nvim/lua/lazy/core/loader.lua.

For ease of reading the error occurs on the line containing the if statement below.
```
  for _, plugin in pairs(plugins) do
    plugin = type(plugin) == "string" and Config.plugins[plugin] or plugin
    ---@cast plugin LazyPlugin

    if not plugin._.loaded then
```

**Comment by mehalter** [comment]
@GersiD check out this comment thread on this issue. You can't lazy load vimtex on filetype and Shou disable lazy loading because it needs to load stuff before the filetype autocmd event happens

**Comment by GersiD** [comment]
That is one big ooooof, how would I tell lazy that I need that file for when I open a .tex file :(

**Comment by GersiD** [comment]
You are so helpful that thread did solve my issue! Now vimtex just loads at startup which is very wholesome. :)

**Comment by GersiD** [comment]
I will say I am now starting to doubt how usefull this plugin (lazy.nvim) is if its not too smart at knowing when I need the plugins I want it to load.

**Comment by mehalter** [comment]
This is a limitation not the design of `vimtex` and not anything to do with lazy

**Comment by GersiD** [comment]
In defense of Vimtex and lazy.nvim it was my user error that lead to the issue. Lazy loading does indeed work. you need to use the ft = { FILETYPE } table when specifying the plugin in the plugins.init table. Then vimtex does indeed lazyload.

**Comment by GersiD** [comment]
What do you think about the mason issue @mehalter? Is that something you can repro on your end?

**Comment by mehalter** [comment]
@GersiD make sure you clear your cache and stuff like impatient stuff

**Comment by mehalter** [comment]
Also make sure you have the latest version of `lazy` branch which removes the impatient stuff

**Comment by mehalter** [comment]
@GersiD another user had a similar thing on the discord and it was not having the latest commits on the lazy branch as well as having lingering impatient cache laying around: https://discord.com/channels/939594913560031363/942007419050029086/1055849248484245535

**Comment by mehalter** [comment]
Also just a heads up @GersiD v3 is probably a few months out, probably coinciding with Neovim 0.10.0 release so hopefully the lazy branch stays up to date with patches that get made to nightly/stable, but I can't promise it will always be perfectly up to date

**Comment by GersiD** [comment]
I don't have access to that discord. I am just going to delete both the nvim and nvim-data folders and redownload nvim and then switch to the lazy branch again. Is there an easier way to clear the cache?

**Comment by mehalter** [comment]
You should make sure to delete the cache folder along with your data folder, you can find it by running `:lua =vim.fn.stdpath "cache"`

**Comment by GersiD** [comment]
Oh neovim doesnt need the nvim-data folder I can just straight up ice that folder? I didn't know that, thats sick.

**Comment by GersiD** [comment]
Big oof after clearing the cache and the nvim-data folder this is the first thing I see after installing all the packages

![image](https://user-images.githubusercontent.com/44039957/209456470-79bf5206-e3e9-435d-a806-6a4e84782f42.png)

This is so sad. All I want for christmas is for things to just work on windows, however the Mircosoft team will be here to ensure that wont happen. 😢

**Comment by GersiD** [comment]
So this the following code located at line 206 of the plugins.lua file in AstroVim is where Mason is loaded.
```
      ["williamboman/mason.nvim"] = {
        cmd = {
          "Mason",
          "MasonInstall",
          "MasonUninstall",
          "MasonUninstallAll",
          "MasonLog",
          "MasonUpdate", -- astronvim command
          "MasonUpdateAll", -- astronvim command
        },
        config = function()
          require "configs.mason"
          require("lazy").load { plugins = { "nvim-lspconfig", "null-ls.nvim", "nvim-dap" } }
        end,
      },
```
So the error is complaining about failing to run config for mason.nvim. Whats crazy is the fix that caused that error to dissapear but other errors to pop up.

add the key _="" to the table. 🤯

**Comment by mehalter** [comment]
Oh wait, i see what the issue is. I will fix this in the coming days

**Comment by GersiD** [comment]
Please note that whatever the issue is the following package definitions (and possibly more are affected). 
1. Mason-null-ls
2. mason-lspconfig
3. Possibly more those are just the ones I can confirm by doing the little _="" trick

Thank you!

**Comment by mehalter** [comment]
@GersiD could you try pulling the latest and see if it fixes your issue?

**Comment by GersiD** [comment]
Yes! It is now fixed! Thank you so much! Mapping the require function did fix it for me although I am not sure why we wouldn't just add the "nvim-lspconfig", "null-ls", "dap" to the dependencies key for lazyload to pickup later on.

**Comment by mehalter** [comment]
Cool beans, it was because on windows nvim-dap is disabled by default so it was failing when trying to load it. It was better to use the pcall require to load it if it exists but fail quietly if it doesn't

**Comment by matharman** [comment]
Hi,

I also tried out the `lazy` branch just to experiment.

I configure AstroNvim from the `~/.config/astronvim` directory. On the `lazy` branch, I noticed that modules under `~/.config/astronvim/lua` we're no longer in the RTP. 

I assume this has to do with lazy.nvim resetting the RTP from scratch, but I did not have time to tinker with adding it back to RTP via the Astro APIs.

Just wanted to point out a potential use case breakage in advance. I'll try to tinker with it if I have the time later.

**Comment by GersiD** [comment]
Wait that could be why Vimtex is no longer getting triggered when .tex files are opened! The Vimtex github page says this exact thing about the RTP but I have no idea what it is. How would one fix the RTP after switching to lazy? Do you know @matharman?. I really love the idea of lazy.nvim but recently it has been blowing up nvim haha, so many weird things are happening.

**Comment by jay-babu** [comment]
Looking forward to this !

**Comment by GersiD** [comment]
Are you having a similar issue @jay-babu? Can you please explain whats going on with your config? It sounds like we have both windows and linux users in this thread with issues on the lazy branch. Please note guys the lazy branch is behind so switch to v3 and see what happens.

**Comment by jay-babu** [comment]
> Are you having a similar issue @jay-babu? Can you please explain whats going on with your config? It sounds like we have both windows and linux users in this thread with issues on the lazy branch. Please note guys the lazy branch is behind so switch to v3 and see what happens.

No issues... Haven't tried it out since I've been without a laptop for a bit. Just looking for this to be released

**Comment by mehalter** [comment]
@matharman thanks for pointing out the `rtp` issue. I have fixed this on the `v3` branch. The `lazy` branch is no longer being developed on, I will go ahead and delete it. Just be careful using the `v3` because there are a significant significant amount of breaking changes and none of them are documented currently.

**Comment by GersiD** [comment]
Please note that I was over on the lazy.nvim github page (https://github.com/folke/lazy.nvim/issues/230) and Folke (who is really really nice!) was able to fix it for me on windows! Linux users please try again after updating the plugins! It was indeed an RTP issue but now Astrovim is currently in a working state for me on the v3 branch!

**Comment by mehalter** [comment]
This migration is basically finalized so I am going to go ahead and close this to attach more important issues to the PR
