### ISSUE TITLE
Improve working with LSP using `lspsaga`

### ISSUE THREAD

**Issue by IvanProg00** [AstroNvim/AstroNvim#1470]
### Describe the new feature

I would like to see this plugin [lspsaga.nvim](https://github.com/glepnir/lspsaga.nvim) preinstalled and configured in **AstroNvim**. In this plugin, I liked the feature that can be easily seen _References_ and _Definitions_.

**Comment by mehalter** [comment]
Thanks for the suggestion! I don't think we are looking at adding lspsaga for performance reasons and limiting preinstalled plugins in the bsae configuration. Feel free to add lspsaga in your user configuration though!
