### ISSUE TITLE
Ensure Treesitter has a help parser by default

### ISSUE THREAD

**Issue by GersiD** [AstroNvim/AstroNvim#1473]
### Is your feature related to a problem?

Yes! Recently I ran into the following issue that I was able to solve and I would like to ask permission to add the solution to AstroVim!

![image](https://user-images.githubusercontent.com/44039957/209599910-0c1f5ac0-278a-427b-8f47-708c3cf805ae.png)

The above issue states that there is an invalid tree sitter node when parsing the help language (which help pages are formatted in).
This issue pops up after taking any of the following actions.
1. :help ...
2. \<leader\>sh (search help)
3. Anything that has to do with loading a help page 

### Describe the new feature

I would like to see if we can ensure that treesitter has the help parser loaded by default. This could be accomplished in one of two ways (these are the only two obvious ways that come to mind immediatley)

1. Add help as an ensured parser is the user_example page
2. Add a default ensure_installed table to treesitter when AstroVim loads it.

To be blunt, this is a small fix but I think thats why I want to try and add it to the project. I also dont think that solution number 1 would work without trying to implement it.

### Additional context

Whaddaya think?

**Comment by mehalter** [comment]
This is super annoying and has to do with some versions (not all) of Neovim 0.8+ come with treesitter parsers for Lua, vim, and help preinstalled with the binary for a version that was present when the version was tagged. This nearly immediately gets outdated as the treesitter parsers get updates. I don't have a good general way to fix this for all cases in a nice way and is unrelated to what AstroNvim is doing in particular and more a greater issue with some stability things with Neovim trying to come packaged with treesitter parsers. Sorry, but I don't think there's anything really we can do with this :/

**Comment by GersiD** [comment]
Can we add a note to the website for users? Like maybe an FAQ page of frequently asked questions? I just feel like I was living with this issue for a good bit before it bugged me enough to look into it.
