### ISSUE TITLE
Duplicated 

### ISSUE THREAD

**Issue by patrickphat** [AstroNvim/AstroNvim#1474]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.10.2

### Neovim version (>= 0.8)

0.8.1

### Operating system/version

mac Ventura 

### Describe the bug

<img width="460" alt="image" src="https://user-images.githubusercontent.com/45748186/209607801-a080461f-1168-4d56-afc6-b09787a27e5d.png">
<img width="431" alt="image" src="https://user-images.githubusercontent.com/45748186/209607923-14792a5a-ce71-4b4a-8ae7-e86463f6545f.png">

### Steps to Reproduce

1. Turn on nvim
2. See 2-3 tsserver running
3. Does not get completion to suggest for "useState"

### Expected behavior

1. single tsserver
2. completion can suggest "useState"

**Comment by mehalter** [comment]
Can you please share your user configuration. I cannot replicate this

**Comment by GersiD** [comment]
@patrickphat did you solve this? I have the exact same issue and I think it has to do with how I tried to get cmp-omni to play with the integrated cmp module. What was your solution?
