### ISSUE TITLE
weird behaviour with some themes

### ISSUE THREAD

**Issue by Rawnly** [AstroNvim/AstroNvim#1475]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.10.2

### Neovim version (>= 0.8)

0.8.1

### Operating system/version

macOs 13

### Describe the bug

Weird colors for separators

![CleanShot 2022-12-27 at 15 00 40@2x](https://user-images.githubusercontent.com/16429579/209677802-1e97b8f2-fccb-4e2e-b151-2d13bd0d4dea.png)

### Steps to Reproduce

1. Install https://github.com/edeneast/nightfox.nvim

### Expected behavior

After running `:colo nightfox`  after startup it fixes everything.

This happens with other themes too (e.g. `rose-pine`, `tokyonight`)

![CleanShot 2022-12-27 at 15 00 49@2x](https://user-images.githubusercontent.com/16429579/209677694-550d4c30-2ad2-4457-bd1f-70e0f08c1e1a.png)

### Screenshots
![CleanShot 2022-12-27 at 15 09 25](https://user-images.githubusercontent.com/16429579/209678422-0dfcff56-d58f-4342-bc48-122dfbc6e6ad.gif)

_No response_

**Comment by mehalter** [comment]
I cannot replicate this with a minimal `user/init.lua` file. Could you share your user configuration?

```lua
return {
  colorscheme = "dawnfox",
  plugins = {
    init = {
      "EdenEast/nightfox.nvim",
    },
  },
}
```

**Comment by Rawnly** [comment]
Sure, this started to happen after 2.10 update, but I don't know if it's related somehow. 
Anyway if this could help, after moving (just for curiosity) to the lazy branch, it seems to not be happening anymore :/ 

here's the config: https://github.com/rawnly/nvim-config

**Comment by mehalter** [comment]
@Rawnly just took a look and it looks like the culprit is

```lua
  {
    "cranberry-clockworks/coal.nvim",
    config = function() require("coal").setup() end,
  },
```

causing weird conflicts when running the `setup` function there. You can fix this by adding lazy lodaing on the module:

```lua
  {
    "cranberry-clockworks/coal.nvim",
    module = "coal",
    config = function() require("coal").setup() end,
  },
```

this probably went away with lazy because it automatically sets up lazy loading on modules by default.

**Comment by Rawnly** [comment]
@mehalter thank you!
