### ISSUE TITLE
Neovim v0.7 Support (for Debian)

### ISSUE THREAD

**Issue by bestouff** [AstroNvim/AstroNvim#1478]
### Is your feature related to a problem?

Debian still doesn't support Neovim 0.8 (and will maybe be slow to do so).
That makes AstroNvim unisntallable on Debian, unless you count hacks like compiling its own Neovim.

### Describe the new feature

Have a tag with the last version installable on Nvim 0.7 publicized, even if no bugfix are accepted on it.

**Comment by mehalter** [comment]
Check out the discussions: https://github.com/AstroNvim/AstroNvim/discussions/1020

**Comment by mehalter** [comment]
Also you can install the official Neovim PPA on debian to install the latest stable Neovim with `apt` easily without doing a "hacky" solution

**Comment by aimerib** [comment]
Just a note on that, current stable PPA has version 0.7.2 available, but not 0.8.x so when you follow AstroVim's instructions and clone the repo into `~/.config/nvim` you are greeted with this error upon launch:
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/26142232/209967449-03dc0e30-face-47d4-8ba7-a641e525daa7.png">

Just figured this would be relevant information if the official answer is to use the PPA. Alternatively you could add version 0.9 (available in the unstable ppa) to the list of supported nvim versions.

**Comment by mehalter** [comment]
ah yeah thanks for pointing that out @aimerib! I'm surprised they let that get so out of date. I guess the best way to get it on Debian or Ubuntu would be to download the `.deb` from the releases (https://github.com/neovim/neovim/releases/tag/stable) and install it with `dpkg`

**Comment by aimerib** [comment]
That's what I ended up doing, although that makes me somewhat unhappy with life. The biggest downside of installing from the deb is that you get no updates. At some point (presumably) the versions on both stable and unstable get updated and users get the updates when they run their package manager updates. Installing from a deb file means that now the user is in charge of keeping up with myriad updates, but more than likely just the one application that is installed out-of-band and the user never really thinks about it ever again.

While not idea, wouldn't support version 0.9 be under the purview of the nightly branch? From what I could tell from testing it very lightly, things seemed to work out of the box except for the nagging message that my nvim version is unsupported upon startup

**Comment by bestouff** [comment]
Moreover the releases are only for x86 platforms. I have a mac M1 running debian and there's nowhere to find packages except in the official repo.
