### ISSUE TITLE
Telescope command broken after config reload

### ISSUE THREAD

**Issue by x3rAx** [AstroNvim/AstroNvim#1479]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.10.2

### Neovim version (>= 0.8)

NVIM v0.8.1

### Operating system/version

NixOS (unstable channel)

### Describe the bug

The command `:Telescope <picker>` is broken after running `:AstroReload` to reload the configuration. Also, the following custom mappings do not work anymore:

```
      ["<leader>fr"] = { "<cmd>Telescope resume<cr>", desc = "Open recent Telescope picker" },
      ["<leader>fR"] = { "<cmd>Telescope pickers<cr>", desc = "Select recent Telescope pickers" },
```

However, builtin mappings like `SPC f f` to open the file search with Telescope still work.

### Steps to Reproduce

1. Start `nvim`
2. Open a new file (`SPC f n`)
3. Run `:Telescope planets` (this works)
4. Close the window (`Esc`, `Esc`)
5. Run `:AstroReload` (green notification appears)
6. Run `:Telescope planets` again (this time it does not do anything)

### Expected behavior

The selected picker should open even after reloading the config.

### Additional Context

I just started using AstroNvim and have not added any additional plugins or changed any settings yet. The only thing I did was adding some mappings. Here's the diff to the example user configuration:

```diff
diff --git a/lua/user_example/init.lua b/lua/user/init.lua
index 41cccdc..857dd5c 100644
--- a/lua/user_example/init.lua
+++ b/lua/user/init.lua
@@ -208,6 +208,14 @@ local config = {
       ["<leader>bt"] = { "<cmd>BufferLineSortByTabs<cr>", desc = "Sort by tabs" },
       -- quick save
       -- ["<C-s>"] = { ":w!<cr>", desc = "Save File" },  -- change description but the same command
+
+      -- Astro menu
+      ["<leader>Ar"] = { "<cmd>AstroReload<cr>", desc = "Reload Configuration" },
+      ["<leader>Ac"] = { "<cmd>e " .. os.getenv("HOME") .. "/.config/nvim/lua/user/init.lua<cr>", desc = "Open user configuration" },
+
+      -- Open recent Telescope picker(s)
+      ["<leader>fr"] = { "<cmd>Telescope resume<cr>", desc = "Open recent Telescope picker" },
+      ["<leader>fR"] = { "<cmd>Telescope pickers<cr>", desc = "Select recent Telescope pickers" },
     },
     t = {
       -- setting a mapping to false will disable it
@@ -335,6 +343,7 @@ local config = {
         ["<leader>"] = {
           -- third key is the key to bring up next level and its displayed
           -- group name in which-key top level menu
+          ["A"] = { name = "Astro" },
           ["b"] = { name = "Buffer" },
         },
       },

```

**Comment by mehalter** [comment]
@x3rAx yeah hot reloading configuration is super buggy and experimental. There's no good way to get this working perfectly especially with plugins and we mostly only have that available to reload on updates to resync plugins. This command will be getting removed completely in `v3` as it doesn't work very well

**Comment by x3rAx** [comment]
Hello @mehalter, thanks for the clarification.
