### ISSUE TITLE
Delete in normal mode, the prompt appears on line

### ISSUE THREAD

**Issue by tinywaferShark** [AstroNvim/AstroNvim#1481]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.10.0

### Neovim version (>= 0.8)

NVIM v0.8.1

### Operating system/version

Linux VM-24-17-centos 3.10.0-1160.71.1.el7.x86_64

### Describe the bug

Whenever I delete it in normal mode, the prompt "Press Enter or type....." appears on line.

### Steps to Reproduce

1. Open any text
2. Delete one line using 'dd' (or delete one character using 'x')
3. There is a hint."Press Enter or type....."

### Expected behavior

I dont want to see the prompt "Press Enter or type....." 

### Screenshots

![图片](https://user-images.githubusercontent.com/97378664/209926060-8f6fdabd-313c-4a62-a208-f5f925c1842e.png)

**Comment by mehalter** [comment]
I can't replicate this. Can you replicate it without your user configuration?

**Comment by mehalter** [comment]
It looks like sometihng you have added to your user configuration or a plugin maybe is printing something and when `cmdheight=0` it doesn't have space to print it. (It looks like printing an empty string) You can definitely get rid of this by setting `vim.opt.cmdheight = 1`, but I would recommend finding what might be causing this.
