### ISSUE TITLE
Formatting issues for java files

### ISSUE THREAD

**Issue by Juniar-Rakhman** [AstroNvim/AstroNvim#1482]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.10.2

### Neovim version (>= 0.8)

 v0.8.0

### Operating system/version

Pop OS 22.04

### Describe the bug

I am trying to use AstroNvim as my primary editor for Java development. But this formatting issue is a major setback for me. 

Whenever I tried to format a Java file, sometimes it would work fine, and sometimes it would just set the indentation to a 4 or 8 spaces, see screenshot below:

![2022-12-29_23-20](https://user-images.githubusercontent.com/2460346/209983207-fa4e87b2-1705-4a5d-8a99-2ef015fd29cd.png)

Here's my formatting.lua config:
https://github.com/Juniar-Rakhman/astronvim_config/blob/373a22d545f2c55408b47ea27395372c0c713f8d/lsp/formatting.lua

My Java Configs:
https://github.com/Juniar-Rakhman/astronvim_config/blob/373a22d545f2c55408b47ea27395372c0c713f8d/autocmds/java.lua
https://github.com/Juniar-Rakhman/astronvim_config/blob/main/lsp/server-settings/jdtls.lua

I notice the same thing is happening for Lua files when I forgot to skip sumaneko_lua in formatting.lua config. So I figure it must be a conflict with null_ls formatting. I tried to skip "jdtls" but then the formating would turned off all together

I have google around a bit and found a solution for it in LunarVim using this configuration : 
```lua
-- if you don't want all the parsers change this to a table of the ones you want
lvim.builtin.treesitter.ensure_installed = {
  "java",
}

vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, { "jdtls" })

local formatters = require "lvim.lsp.null-ls.formatters"
formatters.setup {
  { command = "google_java_format", filetypes = { "java" } },
  { command = "stylua", filetypes = { "lua" } },
  { command = "shfmt", filetypes = { "sh", "zsh" } },
}
```
This seems to have solved the formatting issues in LunarVim. The question is how do I achieve the same thing using AstroNvim?

### Steps to Reproduce

1. Use AstroNvim config below:

Here's my formatting.lua config:
https://github.com/Juniar-Rakhman/astronvim_config/blob/373a22d545f2c55408b47ea27395372c0c713f8d/lsp/formatting.lua

My Java Configs:
https://github.com/Juniar-Rakhman/astronvim_config/blob/373a22d545f2c55408b47ea27395372c0c713f8d/autocmds/java.lua
https://github.com/Juniar-Rakhman/astronvim_config/blob/main/lsp/server-settings/jdtls.lua

2. Open a java project using AstroNvim
3. Edit the file and then format it.
4. The file formatted would randomly uses 4 or 8 spaces for indentation instead of the default 2 as defined in the style config file

### Expected behavior

The formatting for Java file would work just like any other files.

### Screenshots

![2022-12-29_23-20](https://user-images.githubusercontent.com/2460346/210029844-4650465d-0cbc-4dd2-984f-e477e8db8023.png)

### Additional Context

Feel free to use my config to replicate this issue:
https://github.com/Juniar-Rakhman/astronvim_config

**Comment by mehalter** [comment]
@Juniar-Rakhman you can add `google_java_format` to your `null-ls` configuration as a source and then disable the formatting with `jdtls`. Here is an example minimal `user/init.lua` file:

```lua
return {
  lsp = {
    formatting = {
      disabled = {
        "jdtls"
      }
    }
  },
  plugins = {
    ["null-ls"] = function(config) -- overrides `require("null-ls").setup(config)`
      -- config variable is the default configuration table for the setup function call
      local null_ls = require "null-ls"

      -- Check supported formatters and linters
      -- https://github.com/jose-elias-alvarez/null-ls.nvim/tree/main/lua/null-ls/builtins/formatting
      -- https://github.com/jose-elias-alvarez/null-ls.nvim/tree/main/lua/null-ls/builtins/diagnostics
      config.sources = {
        null_ls.builtins.formatting.google_java_format, -- requires `google_java_format` to be in your PATH
      }
      return config -- return final config table
    end,
  },
}
```

If you are splitting up your config which it looks like you are then you can just add `"jdtls"` to your `disabled` list in `user/lsp/formatting.lua` and then have the file `user/plugins/null-ls.lua` with this in it:

```lua
local null_ls = require "null-ls"

return {
  sources = {
    null_ls.builtins.formatting.google_java_format, -- requires `google_java_format` to be in your PATH
  },
}
```

**Comment by Juniar-Rakhman** [comment]
Thanks for looking into this. Turns out it's a workspace issue with jdtls.
Moved the workspace issue to my home directory and this solves formatting issues without changing my config
