### ISSUE TITLE
Cannot set new colorscheme

### ISSUE THREAD

**Issue by Abdullah-coder2013** [AstroNvim/AstroNvim#1483]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [x] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.10.2

### Neovim version (>= 0.8)

v0.8.1

### Operating system/version

Windows 11

### Describe the bug

If I follow the documentation and set a new colorscheme configured with global variables, the colorscheme does not change even after reloading.

### Steps to Reproduce

1. Go to user/init.lua file
2. Change the colorscheme configured with global variables
3. Save file
4. Reload Neovim
5. See that the colorscheme hasn't changed

### Expected behavior

I expected to see the colorscheme change to the colorscheme I preferred.

**Comment by Juniar-Rakhman** [comment]
I can change the colorscheme just fine. Can you confirm that the colorscheme you pick exists?
Can you type this into the vim command console and see if the colorscheme changes?
```
:colorscheme default
```

**Comment by mehalter** [comment]
@Abdullah-coder2013 you'll want to set it in your user configuration with the `colorscheme` option. Here is a minimal `user/init.lua`:

```lua
return {
  colorscheme = "defaut_theme",
}
```
