### ISSUE TITLE
"Nav" heirline component reports wrong info on multibyte-encoded files

### ISSUE THREAD

**Issue by art-solopov** [AstroNvim/AstroNvim#1487]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.11.0

### Neovim version (>= 0.8)

NVIM v0.8.1

### Operating system/version

Ubuntu 22.04.1 LTS

### Describe the bug

When I open a multibyte-encoded file (for example, in Russian) the column part of the "nav" component in heirline shows the byte number instead of a character number (so, for instance, moving one character forward increases the column count by 2 instead of 1).

The default ruler shows both the byte count and the character count.

### Steps to Reproduce

1. Make a file with multibyte characters and open it in AstroNvim
2. Navigate to a line with multibyte characters
3. Move the cursor left and right and see the column count change by 2

### Expected behavior

Either the column count would change by 1 or it'll match the standard Vim behaviour (with both byte and character values visible)

**Comment by mehalter** [comment]
@art-solopov could you try the latest nightly and see if that resolves it on your end?

**Comment by art-solopov** [comment]
Yeah, works fine, thank you.
