### ISSUE TITLE
tabs weird behaviour 

### ISSUE THREAD

**Issue by Rawnly** [AstroNvim/AstroNvim#1491]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.11.0

### Neovim version (>= 0.8)

v0.8.1

### Operating system/version

macOS 13.0

### Describe the bug

When I open a new file after closing another one, it isn't displayed as active tab.

### Steps to Reproduce

1. Open a file
2. Close it via `<leader>-c`
3. Open it again 
-- extra
5. Open a new file 

You should see that you can't change tab with the shortcut `S-l`/`S-h`

### Expected behavior

to see the active file in the tabs and be able to change tabs correctly

### Screenshots

[![asciicast](https://asciinema.org/a/95kIECXFggDzF6Wnx3E2OkQVP.svg)](https://asciinema.org/a/95kIECXFggDzF6Wnx3E2OkQVP)

### Additional Context

https://github.com/rawnly/nvim-config

**Comment by mehalter** [comment]
Ah thanks for reporting this, I can reproduce @Rawnly ! I will investigate and get a fix together :)

**Comment by mehalter** [comment]
@Rawnly could you try the latest nightly and see if that resolves things?

**Comment by Rawnly** [comment]
Sure

**Comment by Rawnly** [comment]
Ok seems to have somewhat fixed part of the problem. Now the only thing is that the `[No name]` tab remains open (but maybe is something wrong with my config)

**Comment by mehalter** [comment]
Yeah I think that would be a bug with `neo-tree` and not related to AstroNvim. It seems that when you close and reopen the file, neo-tree isn't deleting that other buffer. We aren't really handling that manually in AstroNvim. The tab line at least is appropriately showing all of the open buffers tho haha

**Comment by mehalter** [comment]
Just to be clear, I definitely can replicate the `no name` buffer remaining open, but I would need to open an issue with neo-tree and see why that is there since we aren't doing that
