### ISSUE TITLE
neo-tree options set by user are not accepted

### ISSUE THREAD

**Issue by kraxli** [AstroNvim/AstroNvim#1495]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.11.1

### Neovim version (>= 0.8)

Nvim v0.8.0

### Operating system/version

LinuxMint 21

### Describe the bug

According to the [astronvim configuration of neo-tree](https://astronvim.github.io/Configuration/plugin_defaults#neo-tree) I should be able to change my `neo-tree`  options.

In my `~/.config/astronvim/lua/user/plugins/neo-tree.lua` file I have

```lua
return {
  filesystem = {
    follow_current_file = false,
    hijack_netrw_behavior = "disabled", 
  },
  buffers = {
    follow_current_file = false, 
  },
}
```

However, `neo-tree` still follows the current file and `Netrw` is not available.

### Steps to Reproduce

put the above code snippet into your  `~/.config/astronvim/lua/user/plugins/neo-tree.lua` file

### Expected behavior

- `neo-tree` should not follow the current file
- `Netrw` should be availabe

**Comment by mehalter** [comment]
You will need to make sure to remove the global options that we set to re-enable all the `netrw` plugins. The `neo-tree` configuration does work in accepting options so I am going to go ahead and close this.

Here are in the options where we disable the `netrw` plugins: https://github.com/AstroNvim/AstroNvim/blob/8c9b14ffcbdfd51ba199fb3499b9c60d97250d5e/lua/core/options.lua#L49-L51

You will want to use the function override notation to remove those entries like this:

```lua
return {
  options = function(config)
    config.g.loaded_netrwFileHandlers = nil
    config.g.loaded_netrwPlugin = nil
    config.g.loaded_netrwSettngs = nil
    return config
  end
}
```

**Comment by kraxli** [comment]
Many thanks @mehalter ! I will try out to handle `Netrw` as you suggest. Why have you disabled `Netrw` that fundamentally? Does enabling `Netrw` mess-up `neo-tree` fundamentally?

How can I disable `follow_current_file (= false)` (please see my original message)? Do I need to disable it similarly to handling `Netrw`?

Remark: to me the  [astronvim configuration of neo-tree documentation](https://astronvim.github.io/Configuration/plugin_defaults#neo-tree) seems to be a bit misleading / incomplete. Maybe worth updating it with your suggestion for `Netrw`
