### ISSUE TITLE
Should Astrovim Use Impatient.nvim?

### ISSUE THREAD

**Issue by GersiD** [AstroNvim/AstroNvim#1496]
### Is your feature related to a problem?

Startup time optimization mainly.

### Describe the new feature

Add impatient.nvim to the default AstroNvim configuration.

### Additional context

This may not be needed since lazy.nvim is on its way but I was going to add impatient.nvim to my configuration but then I realized that I would need it to run before any of the other plugins are loaded so it seems like a good thing to be started by astrovim. This is not a strictly necessary feature but it seems like the community generally recognizes a 20-80ms startup time improvement. Just something that I thought I would bring up to the maintainers of this wonderful pre-build Nvim config.

**Comment by mehalter** [comment]
AstroNvim does currently have impatient. V3 will remove this because lazy

**Comment by GersiD** [comment]
🤦  I really should have looked lol sorry for the needless ping. Thank you for the quick response!
