### ISSUE TITLE
C:\Users\Bob\AppData\Local\nvim-data\sessions is not accessible by the current user!

### ISSUE THREAD

**Issue by TheButlah** [AstroNvim/AstroNvim#1502]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.11.4

### Neovim version (>= 0.8)

NVIM v0.8.0-1210-gd367ed9b2

### Operating system/version

windows 11 

### Describe the bug

When pressing `<SPACE>Sf` to go to session list, I get
> C:\Users\Bob\AppData\Local\nvim-data\sessions is not accessible by the current user!

### Steps to Reproduce

* Open `nvim`
* Press  `<SPACE>Sf`

### Expected behavior

Session list should pop up without any errors.

### Additional Context

I have already tried every combo of `:PackerSync`, `:AstroUpdate`, deleting the `nvim-data` folder, ensuring I'm on `stable` astro nvim, etc. I can't figure out what the issue is.

FWIW my `XDG_CONFIG_HOME` is at `D:\Bob\.config` which is a different drive from `nvim-data`.

When looking in the file exploerer, there is no `nvim-data\session` folder.

**Comment by TheButlah** [comment]
oh my god I am so dumb... If I have no sessions to begin with, of course that file is missing. Then I just need to save at least one session. I have been puzzling over this for hours 🥹

Perhaps this could be changed to a UX bug?

**Comment by mehalter** [comment]
This is coming from this plugin: https://github.com/Shatur/neovim-session-manager

We just set up mappings for it. I would recommend opening an issue on that repository about the user experience
