### ISSUE TITLE
Syntax highlighting not working for .tf files for v2.11.x

### ISSUE THREAD

**Issue by ckt114** [AstroNvim/AstroNvim#1505]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.11.4

### Neovim version (>= 0.8)

v0.8.0

### Operating system/version

12.6.2

### Describe the bug

Syntax highlight for terraform (`.tf`) files no longer work in v2.11.x. I've tested with v2.9.x and v2.10.x and they are working fine.

### Steps to Reproduce

1. Open a .tf file

### Expected behavior

Syntax highlighting should work.

### Screenshots

Before
![image](https://user-images.githubusercontent.com/573808/210415409-aeace30e-553a-47bc-9fa1-5ab160d66598.png)

After
![image](https://user-images.githubusercontent.com/573808/210415186-5d3d68e5-59c3-495a-b42b-f762fdbd5c5a.png)

**Comment by mehalter** [comment]
Make sure to install the terraform treesitter parser installed with `:TSInstall terraform` and then `tf` is not a default recognized filetype, so you will want to put this in your `polish` function in your `user/init.lua` file:

```lua
vim.filetype.add {
  extension = {
    tf = "terraform"
  }
}
```

**Comment by kjuulh** [comment]
For others, this may also have been because you've been using the HCL Treesitter module, now a terraform treesitter module exists as well.

https://github.com/nvim-treesitter/nvim-treesitter/commit/ee3e9f4dc0e5ee9e2bfb1ee47638375840b8fe0f

**Comment by ckt114** [comment]
@mehalter Having this issue again for v3 of AstroNvim. Treesitter for terraform is installed and I’ve tried adding it as extension in polish as well but no dice.

**Comment by luxus** [comment]
maybe join us on discord.gg/astronvim

**Comment by MartiniMoe** [comment]
Any solution to this? Also not having syntax highlighting for *.tf files with AstroNvim v3
