### ISSUE TITLE
Can't use function to configure null-ls

### ISSUE THREAD

**Issue by LandonSchropp** [AstroNvim/AstroNvim#1506]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

Version: v2.11.4

### Neovim version (>= 0.8)

NVIM v0.8.2

### Operating system/version

macOS 12.5

### Describe the bug

The [Basic Configuration](https://astronvim.github.io/Configuration/basic_configuration) documentation gives an example of configuring `null-ls` using a function. However, when this approach is _combined_

```
packer.nvim: Error running config for packer.nvim: ...are/nvim/site/pack/packer/opt/packer.nvim/lua/packer.lua:1026: /Users/landon/.config/nvim/lua/core/plugins.lua:341: attempt to index local 'plugin' (a function value)
```

Digging in a bit more, this seems to be a strange issue where my local `~/.config/nvim/lua/user/plugins/init.lua` file is loading and the config function is disabled, even thouch this file isn't references in my main config.

### Steps to Reproduce

The following script reliably reproduces the issue for me.

``` bash
#!/usr/bin/env bash

set -euo pipefail

# Ensure the latest version of Neovim in installed.
brew install neovim

# Uninstall the previously installed version of AstroNvim.
rm -rf ~/.config/nvim
rm -rf ~/.local/share/nvim
rm -rf ~/.cache/nvim

# Install AstroNvim.
git clone https://github.com/AstroNvim/AstroNvim ~/.config/nvim

# Set up a minimal reproduction of the issue.
mkdir -p ~/.config/nvim/lua/user/plugins

cat << LUA > ~/.config/nvim/lua/user/init.lua
return {}
LUA

cat << LUA > ~/.config/nvim/lua/user/plugins/init.lua
return {
  ["null-ls"] = function(config) 
    return config
  end,
}
LUA

# Initialize Neovim.
nvim  --headless -c 'autocmd User PackerComplete quitall'
```

### Expected behavior

The script should run without an error, and I should be able to start the editor with `nvim` without any errors.

**Comment by mehalter** [comment]
Could you share your user configuration. This seems like a separate error in your user configuration from the null-ls code you linked.

**Comment by mehalter** [comment]
Ah I see the code snippet you sent is a minimal configuration

**Comment by mehalter** [comment]
I'll run this and see if I can replicate it, but the error mentioned doesn't seem to relate 🤔

**Comment by LandonSchropp** [comment]
Hmm, maybe I messed something up on my end. I'll try a clean install and see if I can still replicate.

**Comment by LandonSchropp** [comment]
@mehalter I dug into this more, and you were right that the minimal config wasn't enough to reproduce the issue. It turns out that even though I was using the provided minimal config, some of my other configuration files were being loaded automatically by AstroNvim.

I've updated my original issue to include a script for reliably reproducing the issue. Could you please take a look at that?

Thanks for the help!

**Comment by mehalter** [comment]
Ah yeah I see, this doesn't go in the `plugins.init` table. You want the file `plugins/null-ls.lua` that returns the function

**Comment by LandonSchropp** [comment]
Are the `plugins.*` files loaded automatically by AstroNvim? Is that in the documentation?

**Comment by mehalter** [comment]
Yup :) this is described in the separated configuration documentation and the automatically loaded file locations are explicitly shown in the documentation page of the available user options

**Comment by LandonSchropp** [comment]
> These files will be automatically detected if the file location corresponds to the location in the init.lua table.

Ah, I totally missed that! That's funny—I've been using those file paths because it seemed like a logical way to organize them. I didn't realize that AstroNvim would pull them in automatically.

Thanks for the help!
