### ISSUE TITLE
can't initialize astronvim with user configuration

### ISSUE THREAD

**Issue by lazywhite** [AstroNvim/AstroNvim#1507]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.11.4

### Neovim version (>= 0.8)

nvim 0.8.2

### Operating system/version

ubuntu 22.10

### Describe the bug

follow this [official doc ](https://astronvim.github.io/Configuration/manage_user_config#setting-up-a-user-configuration)
step 5 command never returns

```
Initlialize AstroNvim (this example is using the unattended installation as described above)
nvim  --headless -c 'autocmd User PackerComplete quitall'
```

### Steps to Reproduce

follow official doc

### Expected behavior

command should execute successfully

**Comment by mehalter** [comment]
If you remove `--headless` what do you see?

**Comment by lazywhite** [comment]
> If you remove `--headless` what do you see?

entered nvim,  editing [No Name]

**Comment by mehalter** [comment]
Are you starting from a completely fresh system? Like deleted your data and cache folders? If it's not a fresh installation then there won't be a way to trigger the automatic setup

**Comment by lazywhite** [comment]
Is there a way to debug  that  command  or print  verbose log?

**Comment by lazywhite** [comment]
although that command never return, but after I changed lsp config of user/init.lua,  it worked.
but still don't know why that command can't return

**Comment by mehalter** [comment]
If you are running the command without `--headless` and it's just opening the editor, then you haven't deleted your data folder. This command only works on a fresh installation of AstroNvim, it cannot be run twice because it isn't performing an installation after the first time. You will need to delete your cache and data folders to do a new installation

**Comment by lazywhite** [comment]
so because I already executed [Setup part](https://astronvim.github.io/#-setup)  ,  that command not return is alright?
