### ISSUE TITLE
gq reformatting has stopped working

### ISSUE THREAD

**Issue by tom-james-watson** [AstroNvim/AstroNvim#1508]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.11.4

### Neovim version (>= 0.8)

v0.8.0-1210-gd367ed9b2

### Operating system/version

Ubuntu 22.04

### Describe the bug

In vim, I often want to reformat a very long comment to instead wrap at 80 columns. The way I would do that is to put the cursor on the relevant line and do `gql`.

At some point in the last few weeks this has stopped working when using AstroNvim.

### Steps to Reproduce

Create `repro.ts`:

```ts
// Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```

In normal mode, put the cursor on the first line and press `gql`.

### Expected behavior

File to reformat to:

```ts
// Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod 
// tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
// quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
// consequat.
```

**Comment by tom-james-watson** [comment]
Hmm actually there appears to be more to this, because with the minimal file this actually works fine. Will try debugging more and will reopen.

**Comment by jNaimXIII** [comment]
Hey, I'm having the same issue. Did you get yours fixed?

<img width="1630" alt="image" src="https://user-images.githubusercontent.com/115424698/230014748-ba6e8a62-068a-419b-a586-b4d57cf98736.png">

Pressing the `g` key, WhichKey doesn't even recognize `q` as a keybind. I don't know what might've overwritten this. Let me know if you've found anything.

**Comment by jNaimXIII** [comment]
Although I did find that `gw` does what I want for now. So, maybe try that?
