### ISSUE TITLE
Luasnip

### ISSUE THREAD

**Issue by zmd56** [AstroNvim/AstroNvim#1514]
### Is your feature related to a problem?

  paths = {
      "./UltiSnips/My_markdown.json",
    },

specified path is invalid

### Describe the new feature

  -- 扩展文件类型
  filetype_extend = {
    -- javascript = { "javascriptreact" },
    markdown = { "markdownreact" },
  },
  -- 配置luansip加载程序
  vscode = {
    -- 添加路径，以便在luansip中包含更多VS代码样式的片段
    paths = {
      "./UltiSnips/My_markdown.json",
    },
  },

### Additional context

OS:archlinux neovim:0.82 AstroNvim:2.11.6

**Comment by mehalter** [comment]
We are removing these options in the upcoming v3.0.0 release in an effort to remove abstractions and make things more clear.
