### ISSUE TITLE
Buffers opened from netrw mode of neo-tree don't respect `vim.opt.wrap` options

### ISSUE THREAD

**Issue by ZhaoZuohong** [AstroNvim/AstroNvim#1515]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.11.6

### Neovim version (>= 0.8)

NVIM v0.8.0-1210-gd367ed9b2

### Operating system/version

Linux Mint 21.1

### Describe the bug

When opening files from netrw mode of neo-tree, new buffers are always set to nowrap.

### Steps to Reproduce

1. Set `options.opt.wrap = true` in `user/init.lua`
2. Open directory with `nvim .`
3. Open file with neo-tree
4. Use `:set wrap?` to get wrap options

### Expected behavior

It is expected to output `wrap` instead of `nowrap`.

### Screenshots

https://asciinema.org/a/NO7LwzyOQuGSpjte8J78aksqM

**Comment by mehalter** [comment]
Opened a relevant issue with `neo-tree`: https://github.com/nvim-neo-tree/neo-tree.nvim/issues/684
