### ISSUE TITLE
`PackerSync` is hanging on `luarocks-hererocks: installing hererocks` 

### ISSUE THREAD

**Issue by kraxli** [AstroNvim/AstroNvim#1516]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.11.6

### Neovim version (>= 0.8)

Nvim v0.8.0

### Operating system/version

LinuxMint 21

### Describe the bug

`PackerSync` is hanging on `luarocks-hererocks: installing hererocks` 

### Steps to Reproduce

run `PackerSync`

### Expected behavior

installation of all packages

### Screenshots

`PackerSync` is hanging on `hererocks`
![image](https://user-images.githubusercontent.com/8371948/211217255-96a523ec-f849-48df-b39b-1c3efe6a481a.png)

even though  `luarocks`and `hererocks` are installed
![image](https://user-images.githubusercontent.com/8371948/211217276-62595cca-834e-4737-9f37-21ce64a8faf1.png)

**Comment by mehalter** [comment]
This would be related to packer since we don't handle anything related to how packer installs stuff. Also just a heads up we are deprecating packer support at the end of this month
