### ISSUE TITLE
When I switch to another session, lazygit still opens in a previous session directory

### ISSUE THREAD

**Issue by andrewozh** [AstroNvim/AstroNvim#1518]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.9.1

### Neovim version (>= 0.8)

v0.8.1

### Operating system/version

macOS 13.1

### Describe the bug

I use to use sessions to jump between many projects (<leader>Sf).
But Lazygit (<leader>gg) always opens in directory it been opened at first.

### Steps to Reproduce

1. When I open nvim & choose session (lets say session1) 
2. I open Lazygit (<leader>gg) and it opens in a correct directory
3. Then I use (<leader>Sf) to choose a different session (lets say session2)
4. After It I use (<leader>gg) to open Lazygit (it opens in session1 dir)

### Expected behavior

Expected: It opens in a directory of a project (session2)
Actual result: It opens in a directory of a project been opened first (session1)

**Comment by mehalter** [comment]
Thanks for reporting this @andrewozh ! I have made a fix for this on the `v3` branch that is coming out in the coming weeks

**Comment by mehalter** [comment]
Since this has been  resolved in the new AstroNvim v3.0 and it's available on `nightly` I'm going to go ahead and close this as completed! Thanks again for reporting 😄
