### ISSUE TITLE
Error when choosing a file

### ISSUE THREAD

**Issue by Luxvao** [AstroNvim/AstroNvim#1520]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

Version: v2.11.6

### Neovim version (>= 0.8)

NVIM v0.8.2

### Operating system/version

Windows 11

### Describe the bug

When I launch nvim and click select file, this error message:
`packer.nvim: Error running config for telescope-fzf-native.nvim: ...er\opt\telescope.nvim/lua/telescope/_extensions/init.lua:10: 'fzf' extension doesn't exist or isn't installed: ...ack\packer\opt\telescope-fzf-native.nvim/lua/fzf_lib.lua:11: cannot load module 'C:\Users\borgr\AppData\Local\nvim-data\site\pack\packer\opt\telescope-fzf-native.nvim/lua/../build/libfzf.dll': %1 is not a valid Win32 application.`

### Steps to Reproduce

1. Run nvim
2. Click select file
3. See the error

### Expected behavior

What is this error? Is it normal?

### Screenshots

![grafik](https://user-images.githubusercontent.com/95533447/211349984-1593905a-de66-4cad-84c8-04494a840eaa.png)

**Comment by mehalter** [comment]
It looks like `telescope-fzf-native.nvim` isn't built correctly. I would recommend deleting your `C:\Users\borgr\AppData\Local\nvim-data\site` folder and `C:\Users\borgr\AppData\Local\nvim-data\packer_compiled.lua` file and reinstalling your plugins

**Comment by Luxvao** [comment]
The solution you provided does not work.

**Comment by mehalter** [comment]
check out this issue, it might help: https://github.com/nvim-telescope/telescope-fzf-native.nvim/issues/29

**Comment by Luxvao** [comment]
Thanks! I uninstalled my whole build system (that I installed via MinGW) and reinstalled in in msys. It fixed the issue!
