### ISSUE TITLE
Breaking Change in Heirline

### ISSUE THREAD

**Issue by KyleKing** [AstroNvim/AstroNvim#1523]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.11.7

### Neovim version (>= 0.8)

0.8.2

### Operating system/version

macOS 13.0

### Describe the bug

I updated AstronVim and saw an error with the `heirline` configuration. I had `bufferline=false` and `heirline_bufferline = true`, but I don't otherwise have any custom configuration for heirline

### Steps to Reproduce

1. Run `:AstroUpdate` and install latest `heirline`
2. Launch nvim

### Expected behavior

No errors on startup

### Screenshots

On startup, I see this traceback:

```sh
Error detected while processing User Autocommands for "AstroColorScheme":
Error executing lua callback: ...ite/pack/packer/opt/heirline.nvim/lua/heirline/utils.lua:398: attempt to index field 'statusline' (a nil value)
stack traceback:
        ...ite/pack/packer/opt/heirline.nvim/lua/heirline/utils.lua:398: in function 'on_colorscheme'
        ~/.config/nvim/lua/configs/heirline.lua:292: in function <~/.config/nvim/lua/configs/heirline.lua:292>
        [C]: in function 'nvim_exec_autocmds'
        ~/.config/nvim/lua/core/utils/init.lua:162: in function <~/.config/nvim/lua/core/utils/init.lua:162>
```

From:

https://github.com/AstroNvim/AstroNvim/blob/feb332dfcb977fe5e76d496dae28dc35ae6688a3/lua/configs/heirline.lua#L287-L293

Then after hitting Enter twice, this UI Error appears that references the breaking change in heirline:

<img width="384" alt="Screenshot 2023-01-10 at 13 12 26" src="https://user-images.githubusercontent.com/3784339/211632174-e36f0900-dd9d-4885-9e15-eb2f75f5a115.png">

### Additional Context

See breaking change here: https://github.com/rebelot/heirline.nvim/issues/17#issuecomment-1377410379

I don't have a lot of time now, but I can provide more details in a few hours

**Comment by mehalter** [comment]
This has been resolved in the `v3` branch. And I will not be backporting a fix <v3.0.0 because this will be a breaking change as well for astronvim. Stable AstroNvim will remain using the old commit and if someone is using `nightly` astronvim they should pin the commit to `556666a`

**Comment by KyleKing** [comment]
Thanks for the quick reply! I'll pin `556666a` and keep trying out nightly releases

**Comment by mehalter** [comment]
Yeah I got lucky on this one because this breaking change was something I requested to Heirline for the upcoming v3 release 😅

**Comment by tom-james-watson** [comment]
It's not clear to me how I'm meant to resolve this - I have 2.11.8, which I assume is stable.

> Stable AstroNvim will remain using the old commit

Do you mean this will remain broken on stable?

**Comment by mehalter** [comment]
@tom-james-watson check your configuration and see if you are setting `updater` settings. Stable AstroNvim does not use the new commit so if you have issues then you are not using stable AstroNvim

**Comment by tom-james-watson** [comment]
Looks like you're right - was set to `nightly`! I didn't add that myself though so I'm not sure how it got into my config.

**Comment by i-am-the-slime** [comment]
I was on `nightly` and I don't know what settings to put into my config to go back now and then what to run. It doesn't seem to go back.

**Comment by i-am-the-slime** [comment]
```
  updater = {
    remote = "origin", -- remote to use
    channel = "nightly", -- "stable" or "nightly"
    version = "latest", -- "latest", tag name, or regex search like "v1.*" to only do updates before v2 (STABLE ONLY)
    branch = "main", -- branch name (NIGHTLY ONLY)
    commit = "556666a", -- commit hash (NIGHTLY ONLY)
    pin_plugins = nil, -- nil, true, false (nil will pin plugins on stable only)
    skip_prompts = false, -- skip prompts about breaking changes
    show_changelog = true, -- show the changelog after performing an update
    auto_reload = false, -- automatically reload and sync packer after a successful update
    auto_quit = false, -- automatically quit the current session after a successful update
    -- remotes = { -- easily add new remotes to track
    --   ["remote_name"] = "https://remote_url.come/repo.git", -- full remote url
    --   ["remote2"] = "github_user/repo", -- GitHub user/repo shortcut,
    --   ["remote3"] = "github_user", -- GitHub user assume AstroNvim fork
    -- },
  },
```

**Comment by mehalter** [comment]
Where it says "nightly" you want to change that to "stable" and then restart and run `:AstroUpdate` to move back to stable

**Comment by mehalter** [comment]
@i-am-the-slime

**Comment by mehalter** [comment]
You can also just delete your updater settings and use the defaults to get stable AstroNvim. The commit you put in your updater settings should go in the Heirline plugin definition override in your `plugins.init` table. It's a Heirline commit not AstroNvim.

**Comment by i-am-the-slime** [comment]
When I set `channel = stable` and the commit to `nil` restart and do `AstroUpdate` it says `No updates available`.

**Comment by i-am-the-slime** [comment]
Alright commenting out all the settings worked.

**Comment by mehalter** [comment]
That's probably because nightly and stable are in line right now, run `:PackerSync` to get the correct plugin versions

**Comment by alep** [comment]
Hi,

following documentation to install Astronvim gives this error. What should a new user do?

**Comment by VersBinarii** [comment]
@alep  Do you have `channel = 'stable'` in your config?

**Comment by JakubGluszek** [comment]
I by default had the channel set to "stable" on a clean installation yet the error persists. Not sure what to do

**Comment by mehalter** [comment]
@JakubGluszek what is in your `updater` settings in your user configuration

**Comment by caesarisme** [comment]
Still facing this error on startup

my updater configs:

```
updater = {
    remote = "origin",
    channel = "stable",
    version = "latest",
    branch = "main",
    commit = nil,
    pin_plugins = nil,
    skip_prompts = false,
    show_changelog = true,
    auto_reload = false,
    auto_quit = false,
  },
```

**Comment by mehalter** [comment]
@caesarisme make sure you have run `: AstroUpdate` and you have stable v2.11.8 when running `:AstroVersion`. Also make sure to run `:PackerSync` to get the pinned version of Heirline. If you are still running into issues I would recommend checking out the discord, there are a lot of community members there who can help you fix your issues.
