### ISSUE TITLE
Winbars missing when using nvim with -o or -O

### ISSUE THREAD

**Issue by sbeyer** [AstroNvim/AstroNvim#1526]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.11.8

### Neovim version (>= 0.8)

v.0.8.2

### Operating system/version

Debian GNU/Linux (sid)

### Describe the bug

Invoking `nvim -o file1 file2 file3` to open all provided files in a split (or `-O` for vsplits) has the effect that the winbar is missing for all files but `file1`.

It seems that this issue can already be found in `v2.0.0`. I also think I spotted this issue in an earlier AstroNvim version in another form: using `nvim -d file1 file2`, the `file2` window did not have a winbar; this seemed to be worked around in recent AstroNvim versions such that *none* of the files has a winbar in diff-mode (which is a pity btw, but that's another topic).

### Steps to Reproduce

Invoke `nvim -o file1 file2`

### Expected behavior

All windows should have a winbar.

### Screenshots

`nvim -O lua/configs/window-picker.lua lua/configs/heirline.lua`
![Screenshot](https://user-images.githubusercontent.com/143889/211714127-8b7c6d65-5693-4dd7-90c7-7892af7cd2a7.png)

**Comment by mehalter** [comment]
Oh man thanks for reporting! I can replicate this. I'll do some testing with some minimal Heirline configs to see if this is an upstream bug with Heirline and I'll report back here.

**Comment by mehalter** [comment]
@sbeyer I found the issue and will be putting together a fix for v3. I tried the fix for the Packer lazy manager as well and it's not behaving well probably due to poorly implemented lazy loading in the plugin manager. Thanks again for reporting this!

**Comment by mehalter** [comment]
Since this has been  resolved in the new AstroNvim v3.0 and it's available on `nightly` I'm going to go ahead and close this as completed! Thanks again for reporting 😄
