### ISSUE TITLE
Cannot require lspconfig in user init file

### ISSUE THREAD

**Issue by Bahnschrift** [AstroNvim/AstroNvim#1527]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.11.8

### Neovim version (>= 0.8)

NVIM v0.8.2

### Operating system/version

Windows 11 and Ubuntu 22.04

### Describe the bug

Adding `require('lspconfig')` at any point in `lua/user/init.lua` results in the following error message when starting neovim (and prevents the file from being loaded):
```
Error detected while processing C:\Users\username\AppData\Local\nvim\init.lua:
Error loading file: C:\Users\username\AppData\Local\nvim/lua/user/init.lua
C:\Users\username\AppData\Local\nvim/lua/user/init.lua:187: module 'lspconfig' not found:
^Ino field package.preload['lspconfig']
^Ino file '.\lspconfig.lua'
^Ino file 'C:\Program Files\Neovim\bin\lua\lspconfig.lua'
^Ino file 'C:\Program Files\Neovim\bin\lua\lspconfig\init.lua'
^Ino file '.\lspconfig.dll'
^Ino file 'C:\Program Files\Neovim\bin\lspconfig.dll'
^Ino file 'C:\Program Files\Neovim\bin\loadall.dll'
```

I'm trying to add this line so I can add a LSP for prolog, as per the instructions [here](https://astronvim.github.io/Recipes/advanced_lsp#custom-lsp-definition).

### Steps to Reproduce

1. Add the snippet from https://astronvim.github.io/Recipes/advanced_lsp#custom-lsp-definition to `lua/user/init.lua`, or add `require('lspconfig')` at some other place in the file.
2. Run neovim

### Expected behavior

`lspconfig` to be successfully loaded.

### Additional Context

Interestingly, this only seems to occur on some platforms. Everything works with no issues on WSL on my desktop and termux on my phone, but I get the error on Windows, my laptop running Ubuntu, and my Raspberry Pi. There doesn't seem to be a correlation with Neovim subversion.

I have tried removing the neovim cache directories and `.local/share/nvim` (and the windows equivalent), then re-running `PackerSync`, but it doesn't seem to help.

**Comment by PatMulligan** [comment]
Same issue here Pop!_OS 22.04

**Comment by mehalter** [comment]
Ah, I should fix this snippet. This should look like this:

```lua
return {
  lsp = {
    servers = {
      "prolog_lsp",
    },
    ["server-settings"] = {
      prolog_lsp = function()
        return {
          cmd = {
            "swipl",
            "-g",
            "use_module(library(lsp_server)).",
            "-g",
            "lsp_server:main",
            "-t",
            "halt",
            "--",
            "stdio",
          },
          filetypes = { "prolog" },
          root_dir = require("lspconfig.util").root_pattern "pack.pl",
        }
      end,
    },
  },
}
```
