### ISSUE TITLE
Error detected while processing VimEnter Autocommands for "*"

### ISSUE THREAD

**Issue by IcyKit** [AstroNvim/AstroNvim#1528]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.11.8

### Neovim version (>= 0.8)

v0.8.1

### Operating system/version

Arch Linux

### Describe the bug

After `:AstroUpdate` and `:PackerSync`, I see this problem, after pressing enter, I see another errors. Also bottom bar doesn't work.

### Steps to Reproduce

1. `:AstroUpdate`
2. `:PackerSync`
3. `nvim` command

### Expected behavior

Starting AstroNvim without errors

### Screenshots

![ksnip_20230111-163934](https://user-images.githubusercontent.com/84917134/211821626-7ebbaae3-bebf-4de5-a232-41dbdaeeb443.png)
![ksnip_20230111-164421](https://user-images.githubusercontent.com/84917134/211821844-4dfc509c-2314-46de-8420-6ba029ef8681.png)

**Comment by mehalter** [comment]
Heirline has had breaking changes. I would recommend using stable AstroNvim to avoid issues like this. You can also pin Heirline to an older commit if you still want to use nightly, but just remember that nightly is an unreleased and unsupported version and cannot guarantee stability.

**Comment by IcyKit** [comment]
So, I'm using stable version

**Comment by mehalter** [comment]
Please share your user configuration

**Comment by IcyKit** [comment]
Oh, I saw `user_example` folder, sorry, now it's working, thanks!
