### ISSUE TITLE
Configurable hlsearch option

### ISSUE THREAD

**Issue by ckt114** [AstroNvim/AstroNvim#1529]
### Is your feature related to a problem?
Not a problem but more of an annoyance.

### Describe the new feature

The code below removes hlsearch when any key other than the defined ones is pressed. This feature may not be wanted by everyone. Is it possible to make this feature optional?

https://github.com/AstroNvim/AstroNvim/blob/main/lua/core/autocmds.lua#L8-L13

The current work around is for me to define the same thing in `polish` but set `vim.opt.hlsearch = true` which is not that friendly.

A flag or something to enable/disable this feature.

**Comment by mehalter** [comment]
You can add the following in your `polish` function

```lua
vim.on_key(nil, vim.api.nvim_get_namespaces()["auto_hlsearch"])
```

**Comment by dvoytik** [comment]
@mehalter ,
I tried this option:
```lua
  polish = function()
    vim.on_key(nil, vim.api.nvim_get_namespaces()["auto_hlsearch"])
    -- Set up custom filetypes
    -- vim.filetype.add {
    --   extension = {
    --     foo = "fooscript",
    --   },
    --   filename = {
    --     ["Foofile"] = "fooscript",
    --   },
    --   pattern = {
    --     ["~/%.config/foo/.*"] = "fooscript",
    --   },
    -- }
  end,
```
And still `hlsearch` doesn't work as I got used to in the default neovim config.
I'm using AstroNvim `Version: v3.45.3`
```sh
nvim --version
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742
```
`:checkhealth` doesn't show anything serious.

**Comment by mehalter** [comment]
I'm sorry you are having trouble @dvoytik . I can verify that with a completely clean installation with this minimal `user/init.lua` file it works:

```lua
return {
  polish = function()
    vim.on_key(nil, vim.api.nvim_get_namespaces()["auto_hlsearch"])
  end,
}
```

If you have any other questions, the Discord channel is a great place to get help from other users with your configuration.

**Comment by dvoytik** [comment]
OK, found the problem. In the default color scheme
```
colorscheme = "astrodark",
```
the background color is too dark (I  guess for me), so I couldn't see the highlight.
I guess I need to change this somehow...
Thanks for checking this!

**Comment by jondkinney** [comment]
@mehalter I think something changed with v4 here. I had to add this as a plugin (no longer needed to do it in polish)

I called it `hlsearch_pls.lua` in my `~/.config/nvim/lua/plugins/` directory.

The functionality that I wanted was keep highlights after searching or pressing * on a word, even when navigating. But remove highlights (and don't make them come back) if `:noh` is called (I trigger it via <Leader>space). But if `n` is pressed, re-trigger the last search and highlight things again. 

Not sure if this ChatGPT 4o generated way is the best way, but it does work 🤷 

```lua
-- Additional configuration to handle :noh
vim.api.nvim_create_user_command("NoH", function() vim.opt.hlsearch = false end, {})

-- Set key mappings to use the custom NoH command
vim.api.nvim_set_keymap("n", ":noh", ":NoH<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", ":nohlsearch", ":NoH<CR>", { noremap = true, silent = true })

return {
  "AstroNvim/astrocore",
  ---@type AstroCoreOpts
  opts = {
    on_keys = {
      auto_hlsearch = {
        function(char)
          if vim.fn.mode() == "n" then
            local key = vim.fn.keytrans(char)
            if key == "n" then
              vim.opt.hlsearch = true -- Re-enable hlsearch when 'n' is pressed
            elseif key == "<Esc>" or key == "<C-c>" then
              vim.opt.hlsearch = false -- Optionally disable hlsearch on escape or interrupt
            end
          end
        end,
      },
    },
  },
}

```

**Comment by mehalter** [comment]
You just want to disable it, so you can do this:

```lua
return {
  "AstroNvim/astrocore",
  ---@type AstroCoreOpts
  opts = {
    on_keys = {
      auto_hlsearch = false,
    },
  },
}
```

**Comment by jondkinney** [comment]
Nice @mehalter, that definitely works and is more minimal than what I wound up with. I was just about to post this when I saw your comment.

Ended up with:

```lua
return {
  "AstroNvim/astrocore",
  ---@type AstroCoreOpts
  opts = {
    on_keys = {
      auto_hlsearch = {
        function(char)
          if vim.fn.mode() == "n" then
            local key = vim.fn.keytrans(char)
            if key == "n" then
              vim.opt.hlsearch = true -- Re-enable hlsearch when 'n' is pressed
            elseif key == "<Esc>" then
              vim.cmd ":noh" -- Disable hlsearch when 'Esc' is pressed
            end
          end
        end,
      },
    },
  },
}
```

Is there a simpler way to support esc also clearing the search highlight?

**Comment by mehalter** [comment]
No, that seems to be alright

**Comment by jondkinney** [comment]
I think we can simplify it a tiny bit since we're overriding the `auto_hlsearch` key in astrocore here, and rely on the default `hlsearch` functionality of neovim, i.e. we don't need to check for the `n` key being pressed or re-enable `hlsearch` if it's not being disabled by `auto_hlsearch` anymore.

I believe this covers my case of wanting to disable `auto_hlsearch` while also adding `<Esc>` as a way to clear the search highlights.

BTW, the reason I do this is to be able to easily scan a file for other instances of a variable or function definition, etc. And it works across multiple open buffers, too. So it's a quick easy way to orient yourself and get over to where you want to go in the same or another buffer. The default functionality of clearing the search on movement makes it a lot harder to use those highlights as a visual aid / navigation map for getting from point a to point b more quickly. And this is even, perhaps especially, if you don't just hold hjkl to get where you want to go. But it's nice for those that do that, too.

```lua
 return {
  "AstroNvim/astrocore",
  ---@type AstroCoreOpts
  opts = {
    on_keys = {
      auto_hlsearch = {
        function(char)
          if vim.fn.mode() == "n" then
            local key = vim.fn.keytrans(char)
            if key == "<Esc>" then
              vim.cmd ":noh" -- Disable search highlights when 'Esc' is pressed
            end
          end
        end,
      },
    },
  },
}
```

Furthermore, I change the default behavior of the `*` key so that when it's pressed on a keyword in my source code, it stays there and the cursor doesn't jump. I do that with this:

```lua
return {
  vim.keymap.set("n", "*", function()
    -- Store the current view
    local view = vim.fn.winsaveview()

    -- Perform the search
    vim.cmd "normal! *N"

    -- Restore the view (cursor position)
    vim.fn.winrestview(view)
  end, { noremap = true, desc = "Search word under cursor, highlight, but don't move" }),
}
```

The combination of these 2 techniques helps me quite a bit. Hope it's useful for someone else, too!
