### ISSUE TITLE
Missing some commands : E492: Not an editor command: PackerSync

### ISSUE THREAD

**Issue by MichaelBitard** [AstroNvim/AstroNvim#1531]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [ ] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.11.8

### Neovim version (>= 0.8)

v0.8.2

### Operating system/version

Fedora 36

### Describe the bug

I wanted to try the debugger through Dap and cannot find the :Dap* commands.

So I tried to update AstroNvim following the guide here: https://astronvim.github.io/#-setup but I found that I don't have :Packer* commands either.

I removed ~/.config/nvim and reinstalled everything from scratch but I think some conf is still installed somewhere because when I relaunch nvim I end up with the LSP servers already configured.
Is there a way to reset entirely my nvim config? I can't find where the mason/lsp stuff is kept.

### Steps to Reproduce

1. use an old version of astronvim
2. update astronvim to get access to :DapInstall
3. No :DapInstall

### Expected behavior

I would expect to be able to remove everything and start from scratch by just removing the ~/.config/nvim folder and re-cloning it

### Additional Context

Amazing project by the way, I am migrating from Idea and VsCode to astronvim and there a only a few things I'm missing

**Comment by mehalter** [comment]
See #1294
