### ISSUE TITLE
Setup called twice when disabling core plugin

### ISSUE THREAD

**Issue by DeeGeeMan** [AstroNvim/AstroNvim#1535]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.10.1

### Neovim version (>= 0.8)

NVIM v0.8.2

### Operating system/version

macOS 12.6

### Describe the bug

Disabling the core plugin displays an error message at startup.

Error:
Setup called twice
Press ENTER or type command to continue

### Steps to Reproduce

1. Add the `["rcarriga/nvim-notify"] = { disable = true }` to the init.lua file
2. run `nvim +PackerSync`
3. start `nvim` again

### Expected behavior

No error message

**Comment by DeeGeeMan** [comment]
Just verified the problem in **v2.11.8**

**Comment by mehalter** [comment]
Cannot replicate with a minimal config:

```lua
return {
  plugins = {
    init = {
      ["rcarriga/nvim-notify"] = { disable = true },
    },
  },
}
```

please share your entire user configuration and I can help you figure out what might be going wrong on your end.

**Comment by DeeGeeMan** [comment]
Here you go...
[user.zip](https://github.com/AstroNvim/AstroNvim/files/10418096/user.zip)

**Comment by mehalter** [comment]
Ok cool I'll take a look sometime next week

**Comment by mehalter** [comment]
@DeeGeeMan there is something wrong with your definition for `nvim-dap-vscode-js`. If you remove that plugin then the error goes away.

**Comment by DeeGeeMan** [comment]
Why would that trigger the **Setup called twice** error message?

**Comment by mehalter** [comment]
I'm not sure which plugin is getting set up twice. You'll need to see what plugins are having their setup called because of that plugin

**Comment by mehalter** [comment]
Sadly the error message is pretty poorly made so it doesn't specify which setup call it's referring to

**Comment by DeeGeeMan** [comment]
Ok, thanks for your help!
