### ISSUE TITLE
(Heirline) Error detected while processing User Autocommands for "AstroColorScheme"

### ISSUE THREAD

**Issue by natematykiewicz** [AstroNvim/AstroNvim#1538]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.11.8

### Neovim version (>= 0.8)

NVIM v0.8.2

### Operating system/version

macOS 12.5

### Describe the bug

I open any file and receive this message in the bottom:

```
Error detected while processing User Autocommands for "AstroColorScheme":
Error executing lua callback: ...ite/pack/packer/opt/heirline.nvim/lua/heirline/utils.lua:398: attempt to index field 'statusline' (a nil value)
stack traceback:
        ...ite/pack/packer/opt/heirline.nvim/lua/heirline/utils.lua:398: in function 'on_colorscheme'
        /Users/nate/.config/nvim/lua/configs/heirline.lua:292: in function </Users/nate/.config/nvim/lua/configs/heirline.lua:292>
        [C]: in function 'nvim_exec_autocmds'
        /Users/nate/.config/nvim/lua/core/utils/init.lua:162: in function </Users/nate/.config/nvim/lua/core/utils/init.lua:162>
```

When I dismiss it, I see a popup in the top right that says:
```
Heirline: setup() takes only one argument: config
example:
    require('heirline').setup({
        statusline = ...,
        winbar = ..,
        tabline = ...,
        statuscolumn = ...})
```

### Steps to Reproduce

Open any file, see error and notice that the tab bar at the top doesn't look right. (No tabs or anything)

### Expected behavior

No errors and a working tab bar

### Screenshots

<img width="1838" alt="Screen Shot 2023-01-14 at 10 36 42 PM" src="https://user-images.githubusercontent.com/5104186/212523139-e395f5a6-7191-49b9-b5bf-87adf8cb851e.png">
<img width="1838" alt="Screen Shot 2023-01-14 at 10 36 51 PM" src="https://user-images.githubusercontent.com/5104186/212523140-9ce2374b-93ed-4a56-85bc-2b035b15d4bd.png">

### Additional Context

I just did a PackerSync and AstroUpdate, which broke it. Things were working fine before that. I assume Heirline changed in the past few days.

**Comment by natematykiewicz** [comment]
Alright, I figured it out:

This commit in Hairline from 4 days ago broke it. https://github.com/rebelot/heirline.nvim/commit/7b57b27e9e4d1ffa4f3e149f8fdc927db18a850a

Which means this line:
https://github.com/AstroNvim/AstroNvim/blob/32a63a7ff10eea0ed927a5bef2ecf76fef6001b6/lua/configs/heirline.lua#L285

now needs to be:

```lua
heirline.setup { statusline = heirline_opts[1], winbar = heirline_opts[2], tabline = heirline_opts[3] }
```

I tried it locally and things work fine now:
<img width="1838" alt="Screen Shot 2023-01-14 at 10 45 42 PM" src="https://user-images.githubusercontent.com/5104186/212523364-8fc377b1-7e5c-46a9-82d9-cfa78e7f1155.png">

**Comment by mehalter** [comment]
Please see #1523

**Comment by natematykiewicz** [comment]
Oh shoot. I went on “nightly” a while back to test out a bug fix and totally forgot… You can even see it in the screenshot. 🤦🏻‍♂️ Thanks for the help!
