### ISSUE TITLE
Are there options to use the rolling version of Neovim?

### ISSUE THREAD

**Issue by duytrung** [AstroNvim/AstroNvim#1539]
### Is your feature related to a problem?

No it's not related to any problem.

### Describe the new feature

NeoVim has a development channel, releasing binary version every day. I'm wondering is there any "rolling version" of AstroNvim that accept the development channel of Neovim?

I acknowledge that there are many bugs and too much work for AstroNvim developers but I would like to see the sharp edges of the new releases :-)

Thanks 

### Additional context

(None)

**Comment by mehalter** [comment]
There isn't an official way to do this and it would be too much burden like you mentioned to do this reliably and to provide and guaranteed level of stability. You can definitely achieve something similar to this by manually modifying the core `init.lua` file to remove the check for nightly and not give the unsupported Neovim version. We aren't planning on making any rolling release features to give the facade that we can support nightly breaking changes on a daily basis. Hopefully this answers your question :)

**Comment by duytrung** [comment]
@mehalter  thank you :-)
