### ISSUE TITLE
Include the updater channel in the output of :AstroVersion

### ISSUE THREAD

**Issue by natematykiewicz** [AstroNvim/AstroNvim#1541]
### Is your feature related to a problem?

The breaking changes to Heirline caused [myself](https://github.com/AstroNvim/AstroNvim/issues/1538) as well as [others](https://github.com/AstroNvim/AstroNvim/issues/1523) to have errors with AstroNvim, but none of us realized we were even on the nightly channel.

I've been running `:AstroUpdate` and `:PackerSync` as long as I can remember, as if I were on the stable channel, even though I was apparently on the nightly channel. (I think I switched to test out some bug fix -- maybe the 2.6.5 changes?)

### Describe the new feature

In the output of `:AstroVersion`, mention the updater channel.

<img width="320" alt="Screen Shot 2023-01-16 at 9 46 17 AM" src="https://user-images.githubusercontent.com/5104186/212717991-2021d0af-1eaf-4572-ae8d-7b426fc7280c.png">

Maybe:

```
Version: v2.11.8 (nightly)
```

or

```
Version: nightly (4f4269d)
```

Something like this would have made it much more obvious to me that I was not on the stable channel.

### Additional context

It's also worth noting that [this section](https://astronvim.github.io/Configuration/basic_configuration#example-user-configuration) of the documentation has the updater channel as nightly. If people don't yet know how AstroNvim works (they are reading the Basic Configuration guide after all), they may be blindly copy/pasting this and opting into nightly updates when they really don't know what that even means. That may be why a few people don't know how this got into their configs.

**Comment by mehalter** [comment]
Thanks for the suggestion! I'll get this added to the v3 release that's coming in a couple weeks

**Comment by natematykiewicz** [comment]
Great!

**Comment by mehalter** [comment]
![2023-01-16_18:44:13_screenshot](https://user-images.githubusercontent.com/1591837/212781073-d3b02768-2332-4f1b-bf9d-4df907b47ba0.png)

What it looks like now on the upcoming v3.0.0 release

**Comment by natematykiewicz** [comment]
Awesome! This will be very helpful.

**Comment by natematykiewicz** [comment]
Sounds great, thanks!
