### ISSUE TITLE
Function to back to state before update AstroNvim

### ISSUE THREAD

**Issue by convers39** [AstroNvim/AstroNvim#1544]
### Is your feature related to a problem?

Every time when I update AstroNvim I got some issues and this is really frustrating. Hopefully, there is an easy way to go back to the version before the update.

### Describe the new feature

Add a command to restore the state before the last run of `AstroUpdate`

**Comment by mehalter** [comment]
Since this has been  resolved in the new AstroNvim v3.0 and it's available on `nightly` I'm going to go ahead and close this as completed! Thanks again for suggesting this feature! Let me know if you have any issues with is :D

**Comment by convers39** [comment]
@mehalter you are a start!! really appreciate your work!!
