### ISSUE TITLE
Error detected while processing User Autocommands for "AstroColorScheme"

### ISSUE THREAD

**Issue by abhijeetsrivastava** [AstroNvim/AstroNvim#1545]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.11.8

### Neovim version (>= 0.8)

NVIM v0.8.2

### Operating system/version

macOS and ubuntu wsl both

### Describe the bug

```
Error detected while processing User Autocommands for "AstroColorScheme":
Error executing lua callback: ...ite/pack/packer/opt/heirline.nvim/lua/heirline/utils.lua:398: attempt to index field 'statusline' (a nil value)
stack traceback:
        ...ite/pack/packer/opt/heirline.nvim/lua/heirline/utils.lua:398: in function 'on_colorscheme'
        /home/voijin/.config/nvim/lua/configs/heirline.lua:292: in function </home/voijin/.config/nvim/lua/configs/heirline.lua:292>
        [C]: in function 'nvim_exec_autocmds'
        /home/voijin/.config/nvim/lua/core/utils/init.lua:162: in function </home/voijin/.config/nvim/lua/core/utils/init.lua:162>
Error detected while processing User Autocommands for "AstroColorScheme":
Error executing lua callback: ...ite/pack/packer/opt/heirline.nvim/lua/heirline/utils.lua:398: attempt to index field 'statusline' (a nil value)
stack traceback:
        ...ite/pack/packer/opt/heirline.nvim/lua/heirline/utils.lua:398: in function 'on_colorscheme'
        /home/voijin/.config/nvim/lua/configs/heirline.lua:292: in function </home/voijin/.config/nvim/lua/configs/heirline.lua:292>
        [C]: in function 'nvim_exec_autocmds'
        /home/voijin/.config/nvim/lua/core/utils/init.lua:162: in function </home/voijin/.config/nvim/lua/core/utils/init.lua:162>
```

I dont have much in my personal config, I can share that too if that would help. This has been happening since last few days, during which I thought another AstroNvim update might help (no update happened after that).

### Steps to Reproduce

1. open nvim on any folder
2. error shows up

### Expected behavior

This error should not happen,

**Comment by i0n** [comment]
Getting the same issue as above also after updating to v2.11.8. Reverting back to v2.11.7 also does not fix the issue, presumably because of component updates that aren't also reverted?

**Comment by mehalter** [comment]
@i0n That's because you are not on stable AstroNvim and therefore plugins are updating freely
