### ISSUE TITLE
no guicursor in insert mode

### ISSUE THREAD

**Issue by victororlyk** [AstroNvim/AstroNvim#1547]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.11.8

### Neovim version (>= 0.8)

v.0.8.2

### Operating system/version

macos 13.1

### Describe the bug

I want to see cursor in indent mode and by using astroNvim i can only see it in normal mode, or when i set 
`guicursor=""` then it is always the same normal/visual/insert. 

### Steps to Reproduce

1. use my user config https://github.com/victororlyk/astronvim_config/blob/bug/guicursor/init.lua
2. try to go into insert mode

### Expected behavior

i can see cursor in indent mode 

https://user-images.githubusercontent.com/33072590/213674573-1eaa4c8d-bee2-4796-850f-a7b7aac625dc.mov

**Comment by mehalter** [comment]
By default AstroNvim use uses the default `guicursor` which I believe is a straight line style cursor. If this doesn't play nicely with your setup (maybe terminal or colorscheme limitation?) You can definitely adjust it as you mentioned by setting `guicursor`
