### ISSUE TITLE
heirline setup breaks after Packer sync

### ISSUE THREAD

**Issue by iamlamper** [AstroNvim/AstroNvim#1548]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

 v2.11.8

### Neovim version (>= 0.8)

NVIM v0.8.1

### Operating system/version

macOS 13.0

### Describe the bug

Once after Paker sync, everytime I run AstroVim, an error says: 
```
Error executing lua callback: ...ite/pack/packer/opt/heirline.nvim/lua/heirline/utils.lua:398: attempt to index field 'statusline' (a nil value
)
stack traceback:
        ...ite/pack/packer/opt/heirline.nvim/lua/heirline/utils.lua:398: in function 'on_colorscheme'
        /Users/Bin_1/.config/nvim/lua/configs/heirline.lua:292: in function </Users/Bin_1/.config/nvim/lua/configs/heirline.lua:292>
        [C]: in function 'nvim_exec_autocmds'
        /Users/Bin_1/.config/nvim/lua/core/utils/init.lua:162: in function </Users/Bin_1/.config/nvim/lua/core/utils/init.lua:162>
```

After some search, I believe this is caused by a break change of heirline, committed 2 weeks ago. 

https://github.com/rebelot/heirline.nvim/commit/7b57b27e9e4d1ffa4f3e149f8fdc927db18a850a

> change the function signature of setup(...) to setup(config).
> example:
>     require('heirline').setup({
>         statusline = ...,
>         winbar = ..,
>         tabline = ...,
>         statuscolumn = ...})
> 

This commit breaks  Astro's config,  will Astro make some change to embrace the new `setup()` signature?
```
 // this is breaked , du to change of setup()
heirline.setup(heirline_opts[1], heirline_opts[2], heirline_opts[3]) 
```
https://github.com/AstroNvim/AstroNvim/blame/4f4269d174d85df8b278a6e09d05daeef840df4a/lua/configs/heirline.lua#L285

### Steps to Reproduce

1. Run PakcerUpdate, Pakcersync
2. Restart AstronVim, and the error occurs

### Expected behavior

heirline should be setup properly

### Screenshots

![image](https://user-images.githubusercontent.com/933909/213874281-defa70ba-934d-4db5-9193-00cbc447357c.png)

**Comment by mehalter** [comment]
Please see #1523

**Comment by iamlamper** [comment]
> Please see #1523

Oh that's great!
thanks for your rapid reply.
