### ISSUE TITLE
heirline error on startup 

### ISSUE THREAD

**Issue by LeadFreeCandy** [AstroNvim/AstroNvim#1549]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.11.8

### Neovim version (>= 0.8)

0.8.2

### Operating system/version

mac os 12.4

### Describe the bug

Error detected while processing User Autocommands for "AstroColorScheme":
Error executing lua callback: ...ite/pack/packer/opt/heirline.nvim/lua/heirline/utils
.lua:398: attempt to index field 'statusline' (a nil value)
stack traceback:
        ...ite/pack/packer/opt/heirline.nvim/lua/heirline/utils.lua:398: in function 
'on_colorscheme'
        /Users/samir/.config/nvim/lua/configs/heirline.lua:118: in function </Users/s
amir/.config/nvim/lua/configs/heirline.lua:118>
        [C]: in function 'nvim_exec_autocmds'
        /Users/samir/.config/nvim/lua/core/utils/init.lua:167: in function </Users/sa
mir/.config/nvim/lua/core/utils/init.lua:167>

### Steps to Reproduce

start nvim

### Expected behavior

No errors

**Comment by mehalter** [comment]
Please see #1523
