### ISSUE TITLE
repl functionality

### ISSUE THREAD

**Issue by m-faith** [AstroNvim/AstroNvim#1553]
### Is your feature related to a problem?

REPL functionality is considered essential by some developers. Lua contrib space sorely lacks excellent repl functionality (`croissant` and `ilua` both leave much to be desired). Standalone repl isn't necessarily the best model anyway... integration into the IDE is perhaps optimal!

### Describe the new feature

AstroNvim could be the most-ultimate Nvim IDE. So far, it appears to be the only one with a debugger (neither LunarVim, Folke's new thing, or NVChad include a debugger). So what's missing, what's next?

REPL functionality!!!

- https://github.com/hkupty/iron.nvim
- https://github.com/rafcamlet/nvim-luapad
- https://github.com/bfredl/nvim-luadev

...are three plugins to consider integrating.

I would be so thrilled. Thanks for your efforts <3

**Comment by m-faith** [comment]
I'm super curious what you think of this feature.

It would certainly need care and intention to implement in a safe/sane way... for example nvim-luapad's warning sounds like it could have catastrophic effects if someone starts typing for example `os.execute('rm ...`.

**Comment by mehalter** [comment]
Hey, sorry for the lack of reply here. I have been pondering this a good bit and is a feature I would be interested in adding if we can find an elegant way to support many REPLs in a nice way. `iron.nvim` looks like a pretty good choice, but it will definitely take some time to make sure it's tightly integrated in a way  that can be easily used by users. I would want to stay away from stuff like `nvim-luapad` or `nvim-luadev` as they provide very language specific stuff and we have been staying away from that a bit.

**Comment by m-faith** [comment]
Nice! I agree on iron vs luapad/luadev.  REPLs came up on reddit (maybe just yesterday?) and I was surprised to see a bunch of people vote for https://github.com/jpalardy/vim-slime and not `iron.nvim`. Maybe just because it's what they're accustomed to? Do you have experience with Iron yourself? I've not yet tried it, as I'm quite slow in trying adopting new tools. Planning to make the jump from lunarvim-basic-ide to AstroNvim as my next step here! Then I'll give Iron a testdrive :)

**Comment by m-faith** [comment]
Aha, and another option is https://github.com/Olical/conjure. Are there more?

I did (*finally making the change from lunarvim-basic-ide to astronvim*) try the debugger's repl functionality. I failed to get it to do anything (which is why I'm slow to adopt new tooling, it's already installed and I still couldn't get it to work) but was very intrigued to see it there and I wonder what it's capable of and how it compares to other repls...?

**Comment by ahillio** [comment]
There *are* more... https://github.com/michaelb/sniprun.

**Comment by luxus** [comment]
i'm interested in fennel dev too :D 
sniprun is easy to make it working..

**Comment by convers39** [comment]
Interesting feature! 

> i'm interested in fennel dev too :D sniprun is easy to make it working..

Currently using sniprun which works well in most cases.

**Comment by luxus** [comment]
i guess i should give sniprun a closer look.
if you don't mind, maybe you can close the issue. and it would be nice to have you on https://discord.gg/astronvim

**Comment by m-faith** [comment]
I'm surprised by how minimal this is:

```

return {
  {
    "michaelb/sniprun",
    keys = {},
    opts = {},
    build = "bash ./install.sh 1",
    cmd = "SnipRun",
  },
```

Should there truly be nothing more than that?

Like... what about keybindings for `:SnipRun`, for example?

**Comment by Uzaaft** [comment]
Well thats for the user to config. Perhaps you want to use Ctrl + Enter? Or r+r etc etc. It should be left up to the user imho

**Comment by m-faith** [comment]
Ok, that makes sense.
