### ISSUE TITLE
color scheme selection is not visible

### ISSUE THREAD

**Issue by azinsharaf** [AstroNvim/AstroNvim#1554]
### Describe the new feature

That would be great if the selection would be visible. It is not clear which theme is selected.

https://user-images.githubusercontent.com/10101468/214725339-d3c9b287-3cbd-4a10-becc-18da34a16708.mov

```
maps.n["<leader>ft"] =
    { function() require("telescope.builtin").colorscheme { enable_preview = true } end, desc = "Find themes" }
```

**Comment by mehalter** [comment]
The default themes to not support Telescope so they do not provide ihghlight groups for it. This is not something to be fixed in core AstroNvim. You can notice that the `astrodark`/`astronvim` theme works perfectly. If you have other modern themes that support Telescope then they will also work
