### ISSUE TITLE
Problems with user settings after the update

### ISSUE THREAD

**Issue by Bugulman** [AstroNvim/AstroNvim#1555]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.11.7

### Neovim version (>= 0.8)

NVIM v0.8.2

### Operating system/version

Windows 10, kubuntu 22.4

### Describe the bug

After updating astrovim, the user settings do not work. Errors in plugins related to the telescope and cmp. 
There was no such problem in previous versions.
There is no telescope and cmp paths in the runtimepath either.
An example of my custom file in the main branch https://github.com/Bugulman/astrovim_userconf.

### Steps to Reproduce

1. Copy init.lua file in user folder form user_example
2. Set  {"ahmedkhalf/project.nvim"} , into plugins section in init.lua file
3. Copy to the bottom of the init.lua file in user foler
" --NOTE: project plugin
local status_ok, project = pcall(require, "project_nvim")
if not status_ok then
	return
end
project.setup({
	active = true,
	on_config_done = nil,
	manual_mode = false,
	detection_methods = { "pattern" },
	patterns = { ".git", "_darcs", ".hg", ".bzr", ".svn", "Makefile", "package.json" },
	show_hidden = false,
	silent_chdir = true,
	ignore_lsp = {},
  datapath = vim.fn.stdpath("data"),
})
local tele_status_ok, telescope = pcall(require, "telescope")
if not tele_status_ok then
	return
end
telescope.load_extension('projects')

### Expected behavior

Initialization errors

### Screenshots

![image](https://user-images.githubusercontent.com/42563286/214927316-746aade4-fc65-4a76-8445-5a40f12357cc.png)

**Comment by mehalter** [comment]
Looks like you have some errors in your `user/init.lua` file that are causing it to fail to be loaded. Check out the Discord if you have questions about your user configuration. I believe this is related to you trying to configure plugins outside of the appropriate locations and the plugins not existing when you try to configure them.

**Comment by Bugulman** [comment]
Good afternoon. I'm sure the file is ok. It worked on past versions of astrovim. The problem is in the paths, when reading the user config, why there are no telescope and cmp plugins in the paths. You can you verify this with the set at startup command *set runtimepath ?* . I moved the plugin files to the .config/astroneovim/lua folder and everything worked. So, there are some kind of problem in the paths.

**Comment by mehalter** [comment]
Here is a fixed version of your conifguration: https://gist.github.com/mehalter/42534db2131e2d4ebbf856e3fa069aaa

**Comment by mehalter** [comment]
This does have everything that you had in your original config, I did remove some redefined defaults that you probably got from the `user_example` that you don't need. So it is like ~300 lines smaller

**Comment by mehalter** [comment]
Basically what was happening was your configuration file was never completing. It would fail at some of the `require`s and just return nothing. So you were returning `nil` as your user configuration and we are expecting a table.
