### ISSUE TITLE
Heirline throws an error on start up

### ISSUE THREAD

**Issue by roerohan** [AstroNvim/AstroNvim#1557]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.11.8

### Neovim version (>= 0.8)

NVIM v0.8.2

### Operating system/version

5.19.17-2-MANJARO

### Describe the bug

Getting the following error upon running `nvim`.

```
Error detected while processing User Autocommands for "AstroColorScheme":
Error executing lua callback: ...ite/pack/packer/opt/heirline.nvim/lua/heirline/utils.lua:398: attempt to index field 'statusline' (a nil value)
stack traceback:
	...ite/pack/packer/opt/heirline.nvim/lua/heirline/utils.lua:398: in function 'on_colorscheme'
	/home/roerohan/.config/nvim/lua/configs/heirline.lua:292: in function </home/roerohan/.config/nvim/lua/configs/heirline.lua:292>
	[C]: in function 'nvim_exec_autocmds'
	/home/roerohan/.config/nvim/lua/core/utils/init.lua:162: in function </home/roerohan/.config/nvim/lua/core/utils/init.lua:162>
Error executing lua callback: ...ite/pack/packer/opt/heirline.nvim/lua/heirline/utils.lua:398: attempt to index field 'statusline' (a nil value)
stack traceback:
	...ite/pack/packer/opt/heirline.nvim/lua/heirline/utils.lua:398: in function 'on_colorscheme'
	/home/roerohan/.config/nvim/lua/configs/heirline.lua:292: in function </home/roerohan/.config/nvim/lua/configs/heirline.lua:292>
	[C]: in function 'nvim_exec_autocmds'
	/home/roerohan/.config/nvim/lua/core/utils/init.lua:162: in function </home/roerohan/.config/nvim/lua/core/utils/init.lua:162>
```

### Steps to Reproduce

1. Run `vim`.

### Expected behavior

This error should not occur.

### Screenshots

![image](https://user-images.githubusercontent.com/42958812/215399820-15d25133-8e67-4450-9747-d9b0ce99b281.png)
![image](https://user-images.githubusercontent.com/42958812/215400100-45243878-4c5b-4fcf-9284-5d1174a64024.png)

### Additional Context

None.

**Comment by JakubGluszek** [comment]
I'm experiencing the same issue, I also have a fresh install of astronvim.

**Comment by mehalter** [comment]
Please see #1523

**Comment by roerohan** [comment]
Thanks @mehalter 
I was on the nightly build, updated my config to use the `stable` release to fix the issue for now.
