### ISSUE TITLE
Lazy.nvim caching issues on AstroUpdate

### ISSUE THREAD

**Issue by gwww** [AstroNvim/AstroNvim#1559]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

Latest v3 branch

### Neovim version (>= 0.8)

NVIM 0.8.2

### Operating system/version

macOS 13.1

### Describe the bug

After doing a AstroNvim update sumneko_lua starts reporting the error `Undefined global: 'vim'`.

Ignore the checklist above. As you know this is a v3 nightly problem.

### Steps to Reproduce

Start with a totally clean system, no plugins installed. This is done by:
```
rm -rf ~/.config/astronvim ~/.local/share/nvim ~/.config/nvim ~/.cache/nvim ~/.local/state/nvim
```
Install AstroNvim version 3:
```
git clone -b v3 https://github.com/AstroNvim/AstroNvim.git ~/.config/nvim
```

Because I need to be able to perform an update with the updater, I delete the last AstroNvim commit using:
```
git reset --hard HEAD~1
```

Create a minimum config with just updater settings (needed because running on the nightly v3 branch). The user config is the one file `~/.config/astronvim/lua/user/init.lua` which contains:
```
return {
  updater = {
    channel = "nightly",
    branch = "v3",
    pin_plugins = nil,
  },
}
```
Start nvim. This installs plugins as expected. `lua-language-server` is required for this problem to occur so I manually install `lua-language-server` by using `:Mason` then install just `lua-language-server`.

Edit a file. The file should have something that uses `vim` global in it. For testing purposes I have been using `~/.config/nvim/lua/plugins/mason.lua` (I use that because it has `vim.api` calls and it shows up at the top of my telescope list.

Everything works as expected at this point.

Perform a update using the updater. I do this using the provided key mapping: `<leader>pA`.

At this point I often, but not always see a few plugins update. To be "safe", I quit nvim.

We are at the point where the problem occurs. I edit a file again by start nvim, using telescope to select the same `mason.lua` file reference above. 

I now receive errors from sumneko_lua saying `Undefined global: vim`

### Expected behavior

No error from sumneko_lua.

**Comment by mehalter** [comment]
I can replicate this with caching issues. But I cannot replicate this with issues for neodev. I am going to revise this error report to be more accurate

**Comment by gwww** [comment]
🥳 Glad that you can reproduce! Sad that there is a bug. Mad I didn't figure out a reproducible list sooner!

**Comment by gwww** [comment]
When you say caching issues, what does that look like on your system?

**Comment by mehalter** [comment]
Fixed in latest update :)
