### ISSUE TITLE
emmet takes over tsserver suggestions. 

### ISSUE THREAD

**Issue by kanishkaverma** [AstroNvim/AstroNvim#1560]
### Is your feature related to a problem?

Hey, 
so basically, in typescript react files, when typing in jsx suggestions from emmet show up over suggestions from tsserver. this can be quite frustrating as I have to press tab multiple times. let me compare to vscode. 
as you can see in vscode when just typing in an HTML attribute emmet works beautifully 
![image](https://user-images.githubusercontent.com/58015272/215991763-b25153c1-1824-4355-b9ab-383435c66328.png)
and then when typing in the function of a tsx function emmet doesn't even show up. 
![image](https://user-images.githubusercontent.com/58015272/215991921-2ee84b3b-3c92-465a-b63d-51645c48e3ff.png)

However, when doing the same in neovim. snippets from emmet are the first even though we are typing in javascript. 
![image](https://user-images.githubusercontent.com/58015272/215992268-c322f101-2b66-42f5-9122-b35ed11f5e4b.png)

I know how to have different source priority for cmp however, I amnot sure how to configure thepriority between tsserver and emmet

### Describe the new feature

something like vscode would be really nice. basically show emmet suggestions if we are typing on white space and show tsserver suggestions when typing inside the function component and or inside an element. Thanks for the time

**Comment by mehalter** [comment]
Check out this reddit thread: https://www.reddit.com/r/neovim/comments/woih9n/how_to_set_lsp_autocomplete_priority/

**Comment by gembancud** [comment]
Should be simple to most, but I felt really stupid not knowing how to do this. 
Quick answer for those not in the know

```
  plugins = {
    cmp = function(opts)
      local cmp = require "cmp"
      local types = require "cmp.types"

      local function deprioritize_snippet(entry1, entry2)
        if entry1:get_kind() == types.lsp.CompletionItemKind.Snippet then return false end
        if entry2:get_kind() == types.lsp.CompletionItemKind.Snippet then return true end
      end

      opts.sorting = {
        priority_weight = 2,
        comparators = {
          deprioritize_snippet,
          cmp.config.compare.offset,
          cmp.config.compare.exact,
          cmp.config.compare.scopes,
          cmp.config.compare.score,
          cmp.config.compare.recently_used,
          cmp.config.compare.locality,
          cmp.config.compare.kind,
          cmp.config.compare.sort_text,
          cmp.config.compare.length,
          cmp.config.compare.order,
        },
      }
      return opts
    end,
}

```

**Comment by kanishkaverma** [comment]
Thanks for this. I had figured out something similar to this. However, I would like to point out that this is  still not as good of a solution as vscode.  Vscode just doesn't show any emmett competitions  when it doesn't need to and only shows them when writing HTML. This shows them all the time. However, put them at the bottom of the list. This is definitely usable tho since Vscode is backed by a multi billion dollar company haha.
