### ISSUE TITLE
winbar not working/appearing when number of lines > 10K

### ISSUE THREAD

**Issue by emilsahakyan** [AstroNvim/AstroNvim#1563]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.11.8

### Neovim version (>= 0.8)

v0.8.2

### Operating system/version

Ubuntu 20.04

### Describe the bug

The winbar works fine when the file has <10K lines(is cpp file).
The winbar disappears when the file is >10K lines.

### Steps to Reproduce

1. open a file with <10K lines
2. increase the number of lines at least to10K + 1

### Expected behavior

The winbar should not depend on the number of lines in the file.

**Comment by luxus** [comment]
this is a upstream feature, not a issue with astronvim.
a quick websearch found this:
https://github.com/stevearc/aerial.nvim/issues/37#issuecomment-1003648224

**Comment by mehalter** [comment]
@emilsahakyan if you have the file open and run `:lua =require("aerial").get_location(true)` what sort of result do you get? This is where we are getting the winbar information

**Comment by emilsahakyan** [comment]
> @emilsahakyan if you have the file open and run
> 
> ```
> :lua =require("aerial").get_location(true)
> ```
> 
> what sort of result do you get? This is where we are getting the winbar information

The resut is `{}`

**Comment by mehalter** [comment]
Ah alright, so aerial isn't running. I checked the docs and there is a performance configuration for max number of lines: https://github.com/stevearc/aerial.nvim#options

You can change your aerial settings to support more lines
