### ISSUE TITLE
Use custom plugins configuration conflict with custom LSP config

### ISSUE THREAD

**Issue by willku1024** [AstroNvim/AstroNvim#1565]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.11.8

### Neovim version (>= 0.8)

v0.8.0

### Operating system/version

macOs 13.2

### Describe the bug

Use custom plugins configuration conflict with custom LSP config. `LspInfo` show no LSP-Client connected.

### Steps to Reproduce

custom plugins configuration [.config/nvim/lua/user/plugins/init.lua]:
```lua
return {
  ["p00f/clangd_extensions.nvim"] = {},
}
```

custom lsp configuration [.config/nvim/lua/user/init.lua]:
```lua
return {
  lsp = {
    skip_setup = { "clangd" },
    servers = {
      "clangd",
    },
    ["server-settings"] = {
      clangd = {
        capabilities = {
          offsetEncoding = "utf-8",
        },
      },
    },
  },
  plugins = {
    init = {
      {
        "p00f/clangd_extensions.nvim",
        after = "mason-lspconfig.nvim", -- make sure to load after mason-lspconfig
        config = function()
          require("clangd_extensions").setup {
            server = astronvim.lsp.server_settings "clangd",
          }
        end,
      },
    },
    ["mason-lspconfig"] = {
      ensure_installed = { "clangd" },
    },
  },
}
```
---
When i open a cpp project using configs above , clangd client can not work. But when i move content of plugins/init.lua to init.lua and then delete plugins directory,  clangd client work well.

### Expected behavior

Use my custom lsp-config work well.

**Comment by mehalter** [comment]
Ah your split configuration file takes precedence over your user configuration. So you have a `user/plugins/init.lua` file that adds `clangd_extentensions` but doesn't set it up and you have `clangd`'s setup being skipped. You can either move your full `clangd_extensions` definition to `user/plugins/init.lua` or you can just delete your `user/plugins` folder and just use the `user/init.lua` file that you have.
