### ISSUE TITLE
Errors after updating AstroNvim

### ISSUE THREAD

**Issue by ScopeSV** [AstroNvim/AstroNvim#1567]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.11.8

### Neovim version (>= 0.8)

NVIM v0.8.1

### Operating system/version

macOS ventura 13.1

### Describe the bug

Hi.
I just updated to 2.11.8. Getting an error on startup
Just wanted to let you know. 
```

Error executing lua callback: ...ite/pack/packer/opt/heirline.nvim/lua/heirline/utils.lua:399: attempt to index field 'statusline' (a nil value)
stack traceback:
        ...ite/pack/packer/opt/heirline.nvim/lua/heirline/utils.lua:399: in function 'on_colorscheme'
        /Users/stephan/.config/nvim/lua/configs/heirline.lua:292: in function </Users/stephan/.config/nvim/lua/configs/heirline.lua:292>
        [C]: in function 'nvim_exec_autocmds'
        /Users/stephan/.config/nvim/lua/core/utils/init.lua:162: in function </Users/stephan/.config/nvim/lua/core/utils/init.lua:162>
```

### Steps to Reproduce

update astro

### Expected behavior

No errors after update

**Comment by ScopeSV** [comment]
Upgraded nvim to v.0.8.3 and restarted terminal. Still error

**Comment by mehalter** [comment]
Please see #1523
