### ISSUE TITLE
v3 with utility lazy load breaks terminal lazygit

### ISSUE THREAD

**Issue by gwww** [AstroNvim/AstroNvim#1570]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

Latest v3 branch

### Neovim version (>= 0.8)

0.8.2

### Operating system/version

macOS 13.1

### Describe the bug

The refactor broke starting lazygit because `astrovim.user_terminals` is `nil`.

```
E5108: Error executing lua: /Users/glenn/.config/nvim/lua/core/utils/init.lua:97: attempt to index local 'terms' (a nil value)
stack traceback:
        /Users/glenn/.config/nvim/lua/core/utils/init.lua:97: in function 'toggle_term_cmd'
        /Users/glenn/.config/nvim/lua/core/mappings.lua:269: in function </Users/glenn/.config/nvim/lua/core/mappings.lua:269>
```

### Steps to Reproduce

`<leader>tl`

### Expected behavior

x

**Comment by gwww** [comment]
Actually `M.user_terminals` is nil

**Comment by mehalter** [comment]
Please comment this on the v3 PR. Thanks for reporting. I will look into this next week
