### ISSUE TITLE
Escape sequences `jk` & `jj` delete character before cursor on first use of sequence

### ISSUE THREAD

**Issue by sean-porras** [AstroNvim/AstroNvim#1571]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.11.8

### Neovim version (>= 0.8)

NVIM v0.8.0

### Operating system/version

macOS 12.5

### Describe the bug

The first time the escape sequence `jk` is used after opening a file with Astro from the command line without typing anything in insert mode, it will delete the character to the left of the cursor. After the first time, it will work as expected and won't do this.
It won't delete a character if you open another file (eg. in a split window, or in the same window) after already opening the first file. (Eg. if you simply split the window, creating 2 windows of the same file, `jk` will still delete a character if used)
If you type in insert mode after opening a file and then use `jk` to go back to normal mode, it will work as expected, not deleting any characters.
It will delete a newline created by `o` and any additional newlines created by pressing `<Enter>` afterwards (Clarification note: it will delete ONE newline, but will still delete one if you do `o<Enter><Enter>jk` for example).

### Steps to Reproduce

If you don't want to use a file of your own
1. Open up a new file with `nvim` then `<SPC f n>` OR `nvim nonexistentfilenamehere.txt`
2. Use `o<Enter Enter (Any number of Enters as you please)>`
3. Use `jk` or `jj` escape sequence
You should see one of the newlines created by either `o` or one of your `<Enter>`s was deleted by the sequence and you have one less newline than expected

To show this works with existing files and characters let's create a `test.txt` file containing
```
hello
world

```
1. Open up the testing file from the command line with `nvim test.txt`
2. You may navigate with HJKL however you may please to put your cursor on the "d" in "world"
3. `ijk` or `ijj` to enter insert mode and use the `jk` or `jj` escape sequence
4. You should see now the file appears as follows
```
hello
word

```
5. You can `:q!` and experiment with this as you would like, if the cursor is on the "w" of "world", you'll end up with
```
helloworld

```

### Expected behavior

All uses of the `jk` or `jj` escape sequences shouldn't delete any character beyond the first `j` which is typed from being in insert mode before the escape sequence is triggered.

**Comment by mehalter** [comment]
We don't handle this, this Should be reported to the plugin: https://github.com/max397574/better-escape.nvim

**Comment by sean-porras** [comment]
Alright, thanks!
