### ISSUE TITLE
lua-language-server and many plugins need to disable formatting on save features as installed

### ISSUE THREAD

**Issue by osamuaoki** [AstroNvim/AstroNvim#1572]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.11.8 and lazy_util HEAD

### Neovim version (>= 0.8)

NVIM 0.8.2

### Operating system/version

Linux

### Describe the bug

This is about shiftwidth drifting issue for LUA and thought on its root causes.

But the root cause fix from AstroNvim is disable "reformat on save changes" as its default installation state.

### Steps to Reproduce

When recent `lua-language-server` (2023-02-11) is installed via mason, nvim editor starts saving modified lua files after reformatting them under AstroNvim v2 or v3.  It's kind of nice but when you don't intend to change many lines, this is annoying.  Moreover, it changes some indent to 4.  This cause next loading to set sw=4 by the smart indent plugin.  Then the whole file becomes indented as sw=4 in next saving after modification.  This reformat event only happens if the file has some changes.   (I set default sw=2)

In `mason.nvim` dialog, categories for `lua-language-server` only included "LSP" and  not "Formatter".  But its web page claims "Code formatting" as its feature.  This menu description is a bit deceptive.  This description issue may be `mason.nvim` issue.

  https://github.com/LuaLS/lua-language-server#features

For now, I uninstalled `lua-language-server` (`sumneko_lua` in the status line) to regain sane state.

### Expected behavior

"Don't reformat upon saving changed file" should be the default installation state.  Such should be opt-in feature.

**Comment by mehalter** [comment]
I don't want AstroNvim to impose this sort of decisions to the user. But you can definitely control the auto formatting for AstroNvim in your user configuration to disable the auto formatting with Lua language server: https://astronvim.com/Recipes/advanced_lsp#disabling-formatting-for-a-list-of-language-servers

**Comment by osamuaoki** [comment]
If making formatting as an **opt-in** feature is non-trivial, I understand your decision.

Just FYI: I don't mean to impose decision for each plugin but the activation of formatting is better to be **opt-in**.  Currently it is **opt-out**.  That is my point.

#1450 seems to be similar situation since reporter experience similar issue after "Sometimes after loading / editing a file, these settings get modified to, ...".

**Comment by mehalter** [comment]
Ah I see what you mean, I think for our use case having auto formatting as opt out is alright. It is easy to disable the auto formatting on startup in a user configuration and still be able to toggle it on/off as well. Thanks for the input though!

**Comment by osamuaoki** [comment]
Auto formatting on/off for global editor session or per buffer is nice to have.  Please :-)

Come to think about this, it may be better to address this initial on/off state of auto-reformatting in mason.nvim menu for each tool entry.  A feature request to mason.nivm may be a good idea, too.  Then no need to dig into AstroNvim manual.

I envision mason.nvim selection has:
  * installed / uninstalled binary program package (current capability)
  * activated /deactivated formatting for installed case (wishlist item)

I will file a feature request.

**Comment by mehalter** [comment]
@osamuaoki you should probably close that open issue on mason. Mason has no relationship with setting up or configuring the applications it installs and has nothing to do with AstroNvim's auto formatting.

**Comment by mehalter** [comment]
Yeah we currently have everything you want with toggling specific tools, global enable/disable, global toggling. The only thing is per buffer formatting which I can add this upcoming week since it's super easy and straight forward

**Comment by mehalter** [comment]
@osamuaoki just pushed a commit to `v3` that adds `vim.b.autoformat_enabled` for per bufer auto formatting control and changed `<leader>uf` to be local and added `<leader>uF` to be global auto format toggling.

**Comment by osamuaoki** [comment]
Thanks

Sent from iPhone
