### ISSUE TITLE
Can't disable autopairs

### ISSUE THREAD

**Issue by oryband** [AstroNvim/AstroNvim#1574]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.11.8

### Neovim version (>= 0.8)

v0.8.2

### Operating system/version

Ubuntu 22.10

### Describe the bug

Disabling nvim-autopairs keeps on autocompleting closing parens. None of these seem to work:
```lua
local config = {
    plugins = {
        init = {
          ["nvim-autopairs"] = { disable = true },
          ["windwp/nvim-autopairs"] = { disable = true },
        },
        ["nvim-autopairs"] = { disable = true },
        ["windwp/nvim-autopairs"] = { disable = true },
        autopairs = { disable = true },
    },
}

return config
```

The method described here does work, but is not according to the manual https://github.com/AstroNvim/AstroNvim/issues/1007#issuecomment-1259890817

Possibly related to https://github.com/AstroNvim/AstroNvim/issues/1296 and https://github.com/AstroNvim/AstroNvim/issues/1007

### Steps to Reproduce

Create a `x.clj` file, go into insert mode and click `(`, you'll see a closing paren `)` being auto completed.

### Expected behavior

The plugin should not be available or enabled.

**Comment by oryband** [comment]
Possibly realted to https://github.com/AstroNvim/AstroNvim/issues/1296 and https://github.com/AstroNvim/AstroNvim/issues/1007

**Comment by mehalter** [comment]
```lua
local config = {
    plugins = {
        init = {
          ["windwp/nvim-autopairs"] = { disable = true },
        },
    },
}

return config
```

This is correct. Make sure you run `:PackerSync` on restart to remove the plugin.

**Comment by oryband** [comment]
is this mentioned in the readme? I didn't know I should run packer sync

**Comment by mehalter** [comment]
This is mentioned throughout the documentation

**Comment by oryband** [comment]
Re-opening, running `:AstroUpdatePackages` reinstalls autopairs!

**Comment by mehalter** [comment]
@oryband That shouldn't be happening, could you share your user configuration? I cannot replicate the behavior you are describing.

Also this issue will definitely go away in the upcoming release as we are moving away from Packer and there will no longer be any plugins compilation

**Comment by oryband** [comment]
@mehalter here's my configuration https://github.com/oryband/dotfiles/blob/aee18f7719c817e2e981da2e58ffd436818acf97/.config/nvim/lua/user/init.lua
```bash
# nvim --version
Alias tip: vi --version
NVIM v0.8.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/nvim/parts/nvim/build/build/cmake.config -I/build/nvim/parts/nvim/build/src -I/build/nvim/parts/nvim/build/.deps/usr/include -I/usr/include -I/build/nvim/parts/nvim/build/build/src/nvim/auto -I/build/nvim/parts/nvim/build/build/include
Compiled by root@lcy02-amd64-068

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.10
DISTRIB_CODENAME=kinetic
DISTRIB_DESCRIPTION="Ubuntu 22.10"
```
