### ISSUE TITLE
Vue files won't refresh Typescript types imported from `.ts` files

### ISSUE THREAD

**Issue by grech-ca** [AstroNvim/AstroNvim#1575]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.11.8

### Neovim version (>= 0.8)

v0.8.0

### Operating system/version

macOS 13.2

### Describe the bug

If I change `.ts` file's content in another buffer, currently opened `.vue` file won't refresh new typings

### Steps to Reproduce

1. Run `:LspInstall volar`
2. Create a new Vue project using e.g. `yarn create vue` — check the Typescript option to "yes"
3. Create a `example.ts` file inside `src/` folder with this code:
```ts
export const example = () => null;
```
4. Import this file in `App.vue`:
```vue
<script setup lang="ts">
import { example } from './example';
</script>
```
5. Rename example function:
```ts
export const renamedExample = () => null;
```
6. See that `App.vue` is not throwing any error that imported function "example" does not exist in "example.ts"
7. Run ":LspRestart"
8. See that now `App.vue` throws an error

### Expected behavior

Vue file should refresh Typescript types when they were changed in another buffer

### Screenshots

In this video the behavior is shown on the `getCoordinatesByCity` function

https://user-images.githubusercontent.com/54347665/218314314-cac6ee27-276d-47ff-a55e-ae8bcb3475ad.mp4

**Comment by mehalter** [comment]
This is unrelated to AstroNvim and would be a bug with the language server
