### ISSUE TITLE
If brackets don't match in a Lua file, all lines but the first are deleted at save.

### ISSUE THREAD

**Issue by danielrachi** [AstroNvim/AstroNvim#1577]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

Version: v2.11.8

### Neovim version (>= 0.8)

NVIM v0.8.3

### Operating system/version

Fedora Linux 37 (Workstation Edition)

### Describe the bug

When editing a Lua file, if there's an error with the matching of the brackets, all lines are deleted at save.

### Steps to Reproduce

1. Open a folder with a Lua file in it. `cd ~/.config/nvim && nvim`
2. Open a Lua file with Telescope `<Leader>ff` `init.lua`
3. Delete or add a bracket.
4. Save the file. `<Leader>w` or `:w`

### Expected behavior

I'm not sure about how this behavior is handled in Lua. I was expecting an error of some kind, not the file to be erased.

### Screenshots

https://asciinema.org/a/Zbm56YNGHI1NBcEtRCzydUXT2

**Comment by mehalter** [comment]
Looks like this is a bug in the Lua language server: https://github.com/LuaLS/lua-language-server/issues/1907

I would recommend disabling formatting with it until this issue is fixed
