### ISSUE TITLE
[Deno] mapping "gd" seems to have conflicts when trying to access the definition file

### ISSUE THREAD

**Issue by aichichang** [AstroNvim/AstroNvim#1578]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

V2.11.8

### Neovim version (>= 0.8)

v0.8.3

### Operating system/version

macOS12.5.1

### Describe the bug

I recently configured deno on AstroNvim and noticed this issue. 

It happens when using `Deno` + `Typescript` (works fine with `Node`), and **only on third party library's type definition**.

When trying to use the mapping `gd` to access the type definition file, it triggers an error with the message `Cursor position outside buffer` and shows an empty file (file name is correct but no content inside)...

Strangely it opens the type definition file fine if I move the cursor to the function and run `:lua vim.lsp.buf.definition()`, and once the file is open in the buffer, `gd` mapping would also work. 

### Steps to Reproduce

1. Set up [Deno](https://deno.land/) and [Denols](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#denols)
2. Import a `third party` library, e.g. data-fns
3. Move cursor to the import function and type `gd`
4. Observe the error occurs
![Screenshot 2023-02-14 at 16 49 19](https://user-images.githubusercontent.com/72026367/219026455-372f363c-bd5a-447c-91c1-3007448eea90.png)

### Expected behavior

Should jump to the definition file

### Screenshots

https://user-images.githubusercontent.com/72026367/219028935-f2240e49-74d4-449d-9f88-357aa0c1bb6a.mp4

### Additional Context

Comment out the `telescope's` gd mapping solves the issue, but I'm new to nvim so not sure if this may be replaced by any other mapping/command?

![image](https://user-images.githubusercontent.com/72026367/219026903-bfdd01cf-0e8d-49f3-9ae1-69199411819a.png)

**Comment by mehalter** [comment]
I can actually replicate the same error with `vim.lsp.buf.definition()` but not as consistently. Sometimes the `vim.lsp.buf.defnition()` call works and sometimes it gives the same error as the `telescope`. Because of this I don't think this is a problem with telescope's mapping. It appears that `denols` has some issues that need to be resolved.

Sadly this is out of the realm of AstroNvim and I don't have any ability to improve this. Might be a good question to ask on Reddit or the Discord to see if anyone else using Neovim has these issues with the deno language server.

**Comment by mehalter** [comment]
Basically you can replicate the issue just by running `:lua vim.lsp.buf.definition()` so it's unrelated to the mappings. It doesn't fail every time, but if you try it over and over you will encounter the same error. That leads me to believe it's an issue with denols or a bug in Neovims core LSP definition function.
