### ISSUE TITLE
Missing LSP related keymappings

### ISSUE THREAD

**Issue by dpriedel** [AstroNvim/AstroNvim#1580]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

V3

### Neovim version (>= 0.8)

NVIM V0.8.3

### Operating system/version

Manjaro Linux

### Describe the bug

For C++ development, I am trying to use clangd and clangd_extensions.nvim.

In my nvim/lua/user/init.lua, in the lsp section I have clangd configured as:

`clangd = {
        cmd = {
          "/usr/bin/clangd",
          "--all-scopes-completion",
          "--background-index",
          "--offset-encoding=utf-8",
          "-j=4",
          "--clang-tidy",
          "--enable-config",
        },
      },`

This works fine and everything is as expected including LSP related keymappings.

Next, in the plugins section I have clangd_extensions configured as:
e clangd_extensions configured as:

`{
    "p00f/clangd_extensions.nvim" ,
      dependencies = { "mason-lspconfig.nvim" },
      config = function()
        require("clangd_extensions").setup {
          server = { vim.lsp.clangd,
            cmd = {
              "/usr/bin/clangd",
              "--all-scopes-completion",
              "--background-index",
              "--offset-encoding=utf-8",
              "-j=4",
              "--clang-tidy",
              "--enable-config",
            },
          },
        }
      end,
      ft = { "c", "cpp" },
    },
`
This works fine and I see, for example, inlay hints.

However, I no longer have LSP related keymappings such as `gr` or `<leader>lR` to search references. Nor any other LSP mappings. None of these LSP mappings show up in WhichKey.

### Steps to Reproduce

1. configure AstroNvim with clangd and clangd_extensions
2. restart nvim
3. Let lazy install necessary files
4. restart nvim
5. edit any C++ source file
6. look for LSP keymaps in WhichKey

### Expected behavior

I expect the LSP related keymaps to be available with the clangd_extensions enabled.

**Comment by mehalter** [comment]
You need to correctly set up your LSP plugin according to the documentation: https://v3.astronvim.pages.dev/nightly/Recipes/advanced_lsp#cc-clangd_extensionsnvim
