### ISSUE TITLE
Checking for Colorschemes, should accept lazy.nvim style colorscheme loading

### ISSUE THREAD

**Issue by luxus** [AstroNvim/AstroNvim#1581]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v3

### Neovim version (>= 0.8)

0.9

### Operating system/version

macOS

### Describe the bug

When loading a color scheme like in this example from lazy.nvim
https://github.com/folke/lazy.nvim/blob/7339145a223dab7e7ddccf0986ffbf9d2cb804e8/lua/lazy/example.lua#L4-L11

It will not be loaded, except I add `colorscheme = tokyonight` to init.lua

If I remove the line, I get a notification produced from these lines:
https://github.com/AstroNvim/AstroNvim/blob/e97adb6c96a3cf06c65abb03e9edd5c7ce3910bb/init.lua#L14-L17
But the color scheme loads fine.

If I set it to `colorscheme = default,` it will get called at the end and set the scheme to default instead of setting it to default and getting overwritten by the plugin.

In my opinion, the check should detect if the colorscheme got set somewhere else and not notify about a problem with the colorscheme (even if the colorscheme is loaded)

### Steps to Reproduce

see above

### Expected behavior

no error message

**Comment by mehalter** [comment]
with the latest on `v3` you can now set `colorscheme = false` in your `user/init.lua` file or `return false` in your `user/colorscheme.lua` file to tell AstroNvim to not worry about setting up a colorscheme and leave it up to the user.
