### ISSUE TITLE
Unable to choose Copilote code suggestion 

### ISSUE THREAD

**Issue by tgh12** [AstroNvim/AstroNvim#1583]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.11.8

### Neovim version (>= 0.8)

NVIM 0.8.0

### Operating system/version

MAC OS 11.7.4

### Describe the bug

recently, I installed Copilot plugin successfully but when i open python file and appear code suggestion to write I am unable to choose these suggestion by pressing TAB button because appear menu of autocompletion code.
Any suggestion ?

### Steps to Reproduce

Open python file in Nvim
writing code
Press TAB key
Unable to choose suggestion code
instead it complete different code from auto complete menu
[bug] ?

### Expected behavior

choose suggestion code from copilot without autocomplete menu

**Comment by mehalter** [comment]
You will need to modify your CMP mappings in your user configuration. I can help you out in the coming days or a good resource for asking questions is the discord. A lot of users use Copilot and can share their configurations with you to help you out :)

**Comment by tgh12** [comment]
thank you for your help i find the line reponsible on the issue 
["<Tab>"] = cmp.mapping(function(fallback)
repace the <Tab> with <C-Space>

**Comment by divan** [comment]
@tgh12 can you show in more details how exactly you fixed this issue? I have a similar problem and can't find where to fix it :/

**Comment by CarolHsu** [comment]
same 🤚🏻

**Comment by divan** [comment]
For now I just gave up using the same key (TAB or Ctrl-J) as cmp, and use 'Ctrl-L' for copilot suggestions.
A bit of discussion here: https://github.com/AstroNvim/astrocommunity/issues/83
