### ISSUE TITLE
Delete all buffer except current

### ISSUE THREAD

**Issue by wtLau** [AstroNvim/AstroNvim#1586]
### Is your feature related to a problem?

Hi, I wanted to add a feature to delete all buffers except the current one. Not sure if this a good idea

### Describe the new feature

 I am thinking maybe something under `leader-b`, like

`maps.n["<leader>bc"] =  { function() astronvim.close_buf({1,100}) end, desc = "Close all buffer except current" }`

*Not sure how to capture the max buffer count

**Comment by mehalter** [comment]
Added a commit to implement this feature on the `v3` branch! I made `<leader>bc` close all except the current buffer and `<leader>bC` to close ALL buffers

**Comment by mehalter** [comment]
These bindings also will confirm to the user to save or discard changes for any modified buffers before deleting them. It will not force close them with unsaved changes :) Very much looking forward to the upcoming release!

**Comment by wtLau** [comment]
oh that's really awesome! I am glad we're on the same page.
| These bindings also will confirm to the user to save or discard changes for any modified buffers before deleting them
This is very considerate! 
Looking forward to V3

**Comment by mehalter** [comment]
No problem! I'm going to go ahead and close this since it's been finished up and will be made available when v3 comes out in the next week :)

**Comment by naknode** [comment]
@mehalter Do you have one that closes the current buffer? I know you have <leader>bd but that seems to act like <leader>bD and I have to pick to close -- everytime.  I am on 3.9.0

**Comment by mehalter** [comment]
Yup! @naknode `<leader>bC`

**Comment by naknode** [comment]
@mehalter I mean one that closes JUST the current buffer? But leaves the rest of the buffers alone?

**Comment by mehalter** [comment]
Oh yeah, `<leader>c`, that ones shorter because it happens much more frequently

**Comment by naknode** [comment]
Got it. Thanks! It seemed to not work at times but now it's working. Must be me doing something.
