### ISSUE TITLE
Disabled indent_blankline not working

### ISSUE THREAD

**Issue by nappalm** [AstroNvim/AstroNvim#1589]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.11.8

### Neovim version (>= 0.8)

0.8.8

### Operating system/version

Windows 11

### Describe the bug

I can't disable indent blankline at a general level.

I already tried in the plugins section to change it to false:
`indent_blankline = false`

but that doesn't work, the only way to do it in the current file is, manually executing `:IndentBlanklineDisable`

### Steps to Reproduce

Open nvim settings
Go to plugins section
Change indent_blankline to false

### Expected behavior

blank line disabled

**Comment by mehalter** [comment]
You want to add 

```lua
  ["lukas-reineke/indent-blankline.nvim"] = { disable = true }
```

To your `plugins.init` table and make sure to do a `:PackerSync` to remove the plugin.

Check out the documentation here: https://astronvim.com/Recipes/custom_plugins
