### ISSUE TITLE
Formatoptions not applied for first loaded file

### ISSUE THREAD

**Issue by letscho123** [AstroNvim/AstroNvim#1593]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.11.8

### Neovim version (>= 0.8)

0.8.3

### Operating system/version

Fedora 37 KDE

### Describe the bug

To set `formatoptions` I used:
```
vim.api.nvim_create_autocmd("BufEnter", {
       pattern = '*',
       command = [[set fo-=c fo-=r fo-=o]]
})
```
in the `polish()` function. This works well except for the first loaded file in neovim, independent of selecting a new file or loading a session. When loading the same file again, it works again.

### Steps to Reproduce

1. Add the autocommand from above to init.lua and exit.
2. Open neovim, load a file and check the current settings with `lua print(vim.bo.formatoptions)` or `set fo?`
3. Load another file and check again

### Expected behavior

The changed `formatoptions` are already applied for the first loaded file.

### Additional Context

Furthermore, adding `vim.opt.formatoptions:remove("r")` to the `polish()` function, but does not do anything.

**Comment by mehalter** [comment]
I just tested this block:

```lua
vim.api.nvim_create_autocmd("BufEnter", {
       pattern = '*',
       command = [[set fo-=c fo-=r fo-=o]]
})
```

in a `polish` function and get this when starting AstroNvim and running `set fo?` `formatoptions=tqj` which seem correct. Could you please share your user configuration (you could either link your repo if you are tracking it or share it with something like https://gist.github.com/ and I could help you debug what might be going on in your config

**Comment by letscho123** [comment]
To clarify my issue, when I start AstroNvim I also get `tqj`, but then for the first file I open I get `jcroql` (for lua files).
Could you try to open a lua file and check the output again?
When I open the same or another file within the same session, the `formatoptions` are correct.

**Comment by mehalter** [comment]
https://github.com/neovim/neovim/blob/master/runtime/ftplugin/lua.vim

It looks like this is being set by the `lua` filetype plugin that ships with Neovim core. You probably want to set up a `Filetype` autocmd for `lua` in particular to override this.
