### ISSUE TITLE
Bump mason.nvim version to fix Hashicorp releases move outside github

### ISSUE THREAD

**Issue by GregDuhamel** [AstroNvim/AstroNvim#1595]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.11.8

### Neovim version (>= 0.8)

NVIM v0.8.3

### Operating system/version

Fedora 37

### Describe the bug

Issue : Hashicorp decided to [move their releases outside of github](https://github.com/hashicorp/terraform-ls/releases/tag/v0.30.2) to their own infra : https://releases.hashicorp.com
Result : Failed to update terraform-ls in Mason Installer Menu.

Upstream mason.nvim repo was fixed in this [PR](https://github.com/williamboman/mason.nvim/pull/1002), we would need to bump mason.nvim to the latest version (if possible)

### Steps to Reproduce

Install or update terraform-ls fail.

### Expected behavior

Install or update terraform-ls should be ok.

### Screenshots

![image](https://user-images.githubusercontent.com/4357084/221514861-1c2f7283-de7e-4045-a4d4-edd15ea89844.png)

**Comment by GregDuhamel** [comment]
I'm not sure if only updating the commit_id in [packer_snapshot](https://github.com/AstroNvim/AstroNvim/blob/main/packer_snapshot) would be sufficien, or wise if mason.nvim version is tied up to other mason tools.

**Comment by mehalter** [comment]
We will be releasing v3 to `nightly` which will be fixing this and updating the plugins to the latest. In the mean time, you can add the following to your `plugins.init` table to tell AstroNvim stable to not track the `mason.nvim` plugin:

```lua
["williamboman/mason.nvim"] = {
  commit = false
}
```

Hopefully this helps! :D
