### ISSUE TITLE
AstroNvim is loading plugins twice

### ISSUE THREAD

**Issue by klmr** [AstroNvim/AstroNvim#1603]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

Version: v2.11.8

### Neovim version (>= 0.8)

NVIM v0.8.0

### Operating system/version

macos 12.6.3

### Describe the bug

AstroNvim loads some/all plugins repeatedly. This causes interference for the plugin in question (Nvim-R) and breaks it. This issue exists *only* with AstroNvim. For instance, when installing the plugin directly via vanilla packer.nvim without AstroNvim installation, Nvim-R is only loaded once and works impeccably.

Unfortunately I don’t know a good way of diagnosing the issue but when following the Steps to Reproduce, here’s what `:messages` shows in Nvim:

```
ERROR: R exit code = 1! Please, run :RDebugInfo for details.
ERROR: R exit code = 1! Please, run :RDebugInfo for details.
```

(Note that the message is shown *twice*.)

Running `:RDebugInfo` shows the following error message, which is further clear evidence that the plugin is running twice concurrently, and that the instances are interfering with each other (each is trying to install an R package and this causes a file-based lock to be triggered):

```
RInitOut
* checking for file ‘/Users/konrad/Library/nvim/site/pack/packer/start/Nvim-R/R/nvimcom/DESCRIPTION’ ...
 OK
* checking for file ‘/Users/konrad/Library/nvim/site/pack/packer/start/Nvim-R/R/nvimcom/DESCRIPTION’ ... OK
* preparing ‘nvimcom’: * checking DESCRIPTION meta-information ...
 OK * cleaning src
* preparing ‘nvimcom’: * checking DESCRIPTION meta-information ...
 OK * cleaning src
* checking for LF line-endings in source and make files and shell scripts
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘nvimcom_0.9-144.tar.gz’
* checking for empty or unneeded directories
* building ‘nvimcom_0.9-144.tar.gz’



Why build nvimcom
Nvimcom not installed

RInitErr

.build_packages() exit status 0

.build_packages() exit status 0
* installing to library ‘/Users/konrad/Library/R/arm64/4.2/library’
* installing *source* package ‘nvimcom’ ...
** using staged installation
* installing to library ‘/Users/konrad/Library/R/arm64/4.2/library’
ERROR: failed to lock directory ‘/Users/konrad/Library/R/arm64/4.2/library’ for modifying Try removing ‘/Users/konrad/Library/R/arm64/4.2/library/00LOCK-nvimcom’
Error in do_exit(status = 3) : .install_packages() exit status 3
Error in do_exit(status = status) : .install_packages() exit status 1 Execution halted
Warning in dir.create(outMetaDir) :   cannot create dir '/Users/konrad/Library/R/arm64/4.2/library/00LOCK-nvimcom/00new/nvimcom/Meta', reason 'No such file or directory'
Error in .install_package_description(".", instdir, built_stamp) :    cannot open directory '/Users/konrad/Library/R/arm64/4.2/library/00LOCK-nvimcom/00new/nvimcom/Meta'
ERROR: installing package DESCRIPTION failed for package ‘nvimcom’ * removing ‘/Users/konrad/Library/R/arm64/4.2/library/nvimcom’
Error in do_exit(status = status) : .install_packages() exit status 1
Error in do_exit(status = status) : .install_packages() exit status 1 Execution halted
```

### Steps to Reproduce

Starting with a clean install of Nvim,

1. `git clone https://github.com/AstroNvim/AstroNvim ~/Library/Preferences/nvim`
2. `mkdir -p ~/Library/Preferences/astronvim/lua`
3. `cp -R ~/Library/Preferences/nvim/lua/user_example ~/Library/Preferences/astronvim/lua/user`
4. Edit the user `init.lua` configuration by applying the patch pasted below
5. Inside Nvim, run `:PackerSync`, quit
6. Open an R file: `nvim test.r`

```diff
--- nvim/lua/user_example/init.lua	2023-03-04 14:01:40.000000000 +0100
+++ astronvim/lua/user/init.lua	2023-03-04 14:03:15.000000000 +0100
@@ -218,6 +218,7 @@
   -- Configure plugins
   plugins = {
     init = {
+      { "jalvesaq/Nvim-R" },
       -- You can disable default plugins as follows:
       -- ["goolord/alpha-nvim"] = { disable = true },
 ```

### Expected behavior

Each plugin should only be loaded once

### Additional Context

Issue originally reported at jalvesaq/Nvim-R#715.

This issue exists across operating systems. In addition to the macOS system for which the above Steps to Reproduce were created, I have also observed the issue on my work system, which runs on a RHEL-based cluster.

**Comment by mehalter** [comment]
There isn't anything in AstroNvim that changes how Packer is loading things or when plugins get loaded. If there are plugins loading multiple times this will be an upstream bug in Packer. I have also tested this and cannot get a plugin to load multiple times at all. Another thing is the next release of AstroNvim will not be using Packer and will be using Lazy. We are also removing a lot of abstractions from our user configuration. I would recommend trying to see if this issue exists in the current AstroNvim `nightly` release that will be the upcoming `v3` release.

I am going to go ahead and close this since we are not updating the current version of AstroNvim with Packer as we prepare for the v3 release that is happening soon. Let me know if you can replicate this on v3 and I can re-open this and look into it. Thanks for reporting!

**Comment by klmr** [comment]
Thanks for the reply. I'll keep investigating. I did try the `nightly` release and I am very impressed with it overall. Unfortunately I can't yet tell whether it solves this issue since the Nvim version it requires is unstable on my system and segfaults in the presence of the Nvim-R plugin (this has nothing to do with AstroNvim, of course).
