### ISSUE TITLE
Lsp.server in user/init.lua still running Mason installer

### ISSUE THREAD

**Issue by Kingsmanvn-Official** [AstroNvim/AstroNvim#1604]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

nightly (commit/41db48682757dc06b7ea07ab4e29664601a8d4e0)

### Neovim version (>= 0.8)

NVIM v0.9.0-dev

### Operating system/version

Android 13 (MIUI 14.0.2.0(TKTCNXM))

### Describe the bug

I have installed lua_ls externally and added it to Lsp.server to use without going through Mason, but when I launch Nvim, it still says to install lua_ls from Mason.

### Steps to Reproduce

1. add "lua_ls" to lsp.server.
2. restart nvim.
3. see error.

### Expected behavior

Mason will not reinstall unused configured lsp through Mason.

### Screenshots

![Screenshot_2023-03-05-12-29-37-733_com termux](https://user-images.githubusercontent.com/94727017/222949484-aad5183f-8f8b-4418-bb41-6b9dde1824cb.jpg)

**Comment by mehalter** [comment]
Can you share your user configuration please?

**Comment by mehalter** [comment]
I just tested this and I cannot replicate this bug. I would check to make sure you don't have something like automatic installation configured in `mason-lspconfig` or that it's not listed in your `ensure_installed` list still because that will make it automatically install.

**Comment by Kingsmanvn-Official** [comment]
> Can you share your user configuration please?


it's here bro
https://github.com/Kingsmanvn-Official/MyNvim/blob/nightly/lua/user/init.lua

**Comment by mehalter** [comment]
Ok I'll take a look today or tomorrow to see if I can see what's going on in your user configuration

**Comment by Kingsmanvn-Official** [comment]
> Ok I'll take a look today or tomorrow to see if I can see what's going on in your user configuration

thank you bro

**Comment by mehalter** [comment]
ah yeah @Kingsmanvn-Official you have `automatic_installation = true` in your `mason-lspconfig` options. If you don't want it to automatically install language servers then you should remove this.

**Comment by Kingsmanvn-Official** [comment]
> ah yeah @Kingsmanvn-Official you have `automatic_installation = true` in your `mason-lspconfig` options. If you don't want it to automatically install language servers then you should remove this.

so the `automatic install=true` function of `Mason-lspconfig` also installs all lsps in lsp.server bro

**Comment by Kingsmanvn-Official** [comment]
@mehalter By the way, I can't add the runtime path directory containing the fzf binary.
I try in lazy setup:
```lua
performance = {
  rtp = {
    paths = { "/data/data/com.termux/files/usr/bin/" },
  },
},
```
I try in lazy plugin:
```lua
{
  dir = "/data/data/com.termux/files/usr/bin/",
  config = function(plugin)
    vim.opt.rtp:append(plugin.dir .. "/data/data/com.termux/files/usr/bin/")
  end
},
```
I try in polish:
```lua
vim.opt.runtimepath:append("/data/data/com.termux/files/usr/bin/")
```
Do you have any suggestions to help me?

**Comment by mehalter** [comment]
I can help you tomorrow with the correct syntax for this :)

**Comment by mehalter** [comment]
@Kingsmanvn-Official because the `rtp` is a list like table, you can't do a simple merge. With lazy you will want to add the path in the lazy configuration but you will need to use our function override notation described in our docs: https://astronvim.com/nightly/Configuration/override_formats#override-function

This would look something like this:

```lua
  lazy = function(opts)
    -- add path to rtp
    table.insert(opts.perforamnce.rtp.paths, "/data/data/com.termux/files/usr/bin/")

    return opts
  end,
```

**Comment by Kingsmanvn-Official** [comment]
> @Kingsmanvn-Official because the `rtp` is a list like table, you can't do a simple merge. With lazy you will want to add the path in the lazy configuration but you will need to use our function override notation described in our docs: https://astronvim.com/nightly/Configuration/override_formats#override-function
> 
> This would look something like this:
> 
> ```lua
>   lazy = function(opts)
>     -- add path to rtp
>     table.insert(opts.perforamnce.rtp.paths, "/data/data/com.termux/files/usr/bin/")
> 
>     return opts
>   end,
> ```

I still can't run FZF, where should I add it exactly?

**Comment by Kingsmanvn-Official** [comment]
> @Kingsmanvn-Official because the `rtp` is a list like table, you can't do a simple merge. With lazy you will want to add the path in the lazy configuration but you will need to use our function override notation described in our docs: https://astronvim.com/nightly/Configuration/override_formats#override-function
> 
> This would look something like this:
> 
> ```lua
>   lazy = function(opts)
>     -- add path to rtp
>     table.insert(opts.perforamnce.rtp.paths, "/data/data/com.termux/files/usr/bin/")
> 
>     return opts
>   end,
> ```

@mehalter I still can't run FZF, where should I add it exactly?
