### ISSUE TITLE
Enable Windows Users to configure nvim-dap 

### ISSUE THREAD

**Issue by GersiD** [AstroNvim/AstroNvim#1605]
### Is your feature related to a problem?

I am trying to get nvim-dap to lazy load only on files for which I have it configured. I use the ft key in the lazy table to do this. However, nvim-dap is registered with Astronvim to lazy load on an event called AstroFile. Even after I set event=nil for the lazy table which defines nvim-dap it still is loaded on that event. 

Please note that in the lua\plugins\dap.lua file by default nvim-dap is disabled for windows machines. I was defining it in my plugins table.

### Describe the new feature

For windows machines allow users to fully manage the integration if it is off by default, or allow us to tap into the defaults set by Astronvim.

### Additional context

For context I am on the nightly branch.

For more context
NVIM v0.9.0-dev-1147+ge389b1890
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe /MD /Zi /O2 /Ob1  -W3 -wd4311 -wd4146 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_WIN32_WINNT=0x0602 -DMSWIN -DINCLUDE_GENERATED_DECLARATIONS -ID:/a/neovim/neovim/.deps/usr/include/luajit-2.1 -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include -ID:/a/neovim/neovim/build/cmake.config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

**Comment by mehalter** [comment]
This is described in the documentation: https://astronvim.com/nightly/Recipes/dap#enable-plugins-on-windows

**Comment by GersiD** [comment]
Omg thank you I should have looked in the documentation. 🤦

**Comment by mehalter** [comment]
Also just to give you more stuff you can look at, @A-Lamia probably has the single best example repository for getting `nvim-dap` working in AstroNvim for Windows: https://github.com/A-Lamia/AstroNvim-conf/blob/main/plugins/dap.lua

He has been using it with v3 for months and has really enjoyed it. The discord is also a great place to ask questions, there are other users doing similar things as well :)

**Comment by A-Lamia** [comment]
@GersiD if you want to change how lazy load i have update my config showing that where the event is disabled and it now loads only on keypress of `<leader>d`. :) 
https://github.com/A-Lamia/AstroNvim-conf/blob/main/plugins/dap.lua

**Comment by mehalter** [comment]
Yeah the only reason we have it load initially is to enable the automatic downloading of debuggers with `mason-nvim-dap`. Also configuring dap is extremely performant because all it does is set tables that are used when debugging is activated. It shouldn't actually take long when setting the configurations. So this might be some premature optimization depending on your architecture

**Comment by GersiD** [comment]
You have the premature optimization part right Haha; I am just going down the list in Lazy Profile and squashing anything I don't use every time I use nvim. Turns out nvim-dap was consistently taking a while (150ms) and I was only editing Latex. @A-Lamia Thank you! I will ping back here tomorrow-ish and let you know how that turned out. Thank you both for all the help!

**Comment by GersiD** [comment]
<img width="258" alt="image" src="https://user-images.githubusercontent.com/44039957/223613491-ed96b19a-4a48-4056-8df7-33d11c0e1beb.png">

Yep so I'm an idiot. Just as @mehalter said, mason.nvim asks mason-nvim-dap to start which asks nvim-dap to start all this in order for the automatic downloading of debuggers. So I cant optimize it anymore than this. I guess I am moving on to reducing my startup time. Thank you guys!

**Comment by A-Lamia** [comment]
you could probably lazy load the nvim-dap-ui seems to be the heaviest part if you really want to.

**Comment by GersiD** [comment]
The solution is to remove the following alter the following line in lua\plugins\mason.lua
'''lua
  for _, plugin in ipairs { "mason-lspconfig", "mason-null-ls", "mason-nvim-dap" } do
    pcall(require, plugin)
  end
'''
changed to ...
```lua
  for _, plugin in ipairs { "mason-lspconfig", "mason-null-ls" } do
    pcall(require, plugin)
  end
```
This keeps mason-nvim-dap from ever being spawned, and it only gets spawned when I want it to be.
