### ISSUE TITLE
Problems setting up jdtls

### ISSUE THREAD

**Issue by CMOISDEAD** [AstroNvim/AstroNvim#1606]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

nightly (v2.11.8-204-ge49b0e7)

### Neovim version (>= 0.8)

NVIM v0.8.3

### Operating system/version

arch linux

### Describe the bug

Following the configuration of the [link](https://astronvim.github.io/nightly/Recipes/advanced_lsp#java-nvim-jdtls), everything works fine except that jdtls tries to initialize each project as if it was the first time, i.e. it creates a directory in the worskpace_dir each time a project is opened, no matter if the project is java or not.

### Steps to Reproduce

1. follow https://astronvim.github.io/nightly/Recipes/advanced_lsp#java-nvim-jdtls instructions
2. open any project with neovim no matter the language
3. if it is the first time nothing will happen but if it is the second time it is opened an error will appear

### Expected behavior

jdtls is only activated when a java project is opened, and it detects if it has been previously initialized in the project.

### Screenshots

Opening a rust project
![rust file](https://user-images.githubusercontent.com/51010598/223558218-71d58146-5370-42bb-892c-a3879fdcbbb4.png)
Opening a java project previously initialized with jdtls
![java file](https://user-images.githubusercontent.com/51010598/223558220-d1ad2332-0311-45ee-8f64-75f11b17b19d.png)

**Comment by mehalter** [comment]
This is a good question to bring to the Discord group as a question. This is unrelated to AstroNvim's core code and it related to configuring `jdtls`. I don't use this language server, so I don't have any way to help configure it.
