### ISSUE TITLE
ChatGPT not working with Astronvim

### ISSUE THREAD

**Issue by PaulKushch** [AstroNvim/AstroNvim#1608]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.11.8

### Neovim version (>= 0.8)

0.8.0-1210-gd367ed9b2

### Operating system/version

Ubuntu

### Describe the bug

Seems like the prompt of https://github.com/jackMort/ChatGPT.nvim not working with Astronvim?
I can insert text but not submit text.
Seems like `prompt` not loading, cant see the `caret` and cannot submit text with `<C-Enter>` in `Insert` mode. 

My config is 

```
			{
				"jackMort/ChatGPT.nvim",
				requires = {
					"MunifTanjim/nui.nvim",
					"nvim-lua/plenary.nvim",
					"nvim-telescope/telescope.nvim",
				},
				config = function()
					require("chatgpt").setup({
					})
				end,
			},
```

### Steps to Reproduce

Install https://github.com/jackMort/ChatGPT.nvim and test if `prompt` is working.

### Expected behavior

Be able to submit text in prompt. 

### Screenshots

Seems like `prompt` not loading, cant see the `caret` and cannot submit text with `<C-Enter>` in `Insert` mode. 

![image](https://user-images.githubusercontent.com/5386035/224337558-8745a1f9-de81-4039-acdf-c2f8be64f836.png)

**Comment by mehalter** [comment]
Cannot replicate and I have verified that this ChatGPT plugin works as intended with inputting and sending text.. The discord is a good resource for asking questions regarding your user configuration and figuring out what might be going on in your setup.

**Comment by mehalter** [comment]
Link to the discord for questions: https://discord.gg/AstroNvim

**Comment by luxus** [comment]
i tried codegpt and it worked as well .. dunno if its better or worst
