### ISSUE TITLE
Module not found after update or first time load on new system

### ISSUE THREAD

**Issue by Grafcube** [AstroNvim/AstroNvim#1613]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Arch Linux

### Terminal/GUI

wezterm

### AstroNvim Health

astronvim: require("astronvim.health").check()
========================================================================
## AstroNvim
  - INFO: AstroNvim Version: v3.0.1
  - INFO: Neovim Version: v0.8.3
  - OK: Using stable Neovim >= 0.8.0
  - OK: `git` is installed: Used for core functionality such as updater and plugin management
  - OK: `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
  - OK: `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
  - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
  - WARNING: `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
  - WARNING: `btm` is not installed: Used for mappings to pull up system monitor (Optional)
  - OK: `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

I just ran `:AstroUpdate` and now my config isn't loading. I see this message everytime I open neovim:

```
Error detected while processing /home/kirthi/.config/nvim/init.lua:
Error loading file: /home/kirthi/.config/nvim/lua/user/init.lua
/home/kirthi/.config/nvim/lua/user/init.lua:208: module 'notify' not found:
^Ino field package.preload['notify']
^Ino file './notify.lua'
^Ino file '/usr/share/luajit-2.1.0-beta3/notify.lua'
^Ino file '/usr/local/share/lua/5.1/notify.lua'
^Ino file '/usr/local/share/lua/5.1/notify/init.lua'
^Ino file '/usr/share/lua/5.1/notify.lua'
^Ino file '/usr/share/lua/5.1/notify/init.lua'
^Ino file './notify.so'
^Ino file '/usr/local/lib/lua/5.1/notify.so'
^Ino file '/usr/lib/lua/5.1/notify.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
```

I deleted my `packer_compiled.lua` but that didn't fix the issue.

The line in question is [init.lua:208](https://gitlab.com/Grafcube/dotfiles/-/blob/b0fc4f286cbbbc2a5bbd4540746e421f163a2e7e/dot_config/nvim/lua/user/init.lua#L208):
```lua
-- snippet
    [","] = require("notify").dismiss,
-- snippet
```

It's not just notify though, I suspect it just shows notify because that's the first error encountered. Other plugins don't load either. When I try to run `:PackerSync` or `:PackerCompile` as a command rather than from `<leader>pS` I get this: `E492: Not an editor command: PackerCompile`

This also happened a few days back on a system I was setting up for the first time. I added my configs and installed all the plugins but the exact same error happened. It fixed itself after a while so I have no idea what happened there.

[Here's my full config](https://gitlab.com/Grafcube/dotfiles/-/tree/b0fc4f286cbbbc2a5bbd4540746e421f163a2e7e/dot_config/nvim/lua/user). I didn't change anything. It just works and then suddenly it doesn't after an update or fresh install. It's very unpredictable.

### Steps to Reproduce

1. Update Astronvim OR Set up new config.
2. Encounter error.

### Expected behavior

Works without errors.

**Comment by mehalter** [comment]
Yesterday we released AstroNvim v3. During the update process it prompts you that there are breaking changes and you will need to read the release notes and potentially update your user configuration.

Here are the release notes: https://github.com/AstroNvim/AstroNvim/releases/tag/v3.0.0

Here is the documentation for migrating your configuration: https://astronvim.com/Configuration/v3_migration

If you have troubles updating definitely check out the discord. Many users have done the update process and can provide guidance/help!
