### ISSUE TITLE
null-ls formatting not configure for auto formatting or as mapping

### ISSUE THREAD

**Issue by maxbrunet** [AstroNvim/AstroNvim#1614]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

NixOS 22.11

### Terminal/GUI

alacritty

### AstroNvim Health

Installed with Nix, not Git, and I do not set `astronvim_installation`, so version check fails I guess

```
astronvim: require("astronvim.health").check()
========================================================================
  - ERROR: Failed to run healthcheck for "astronvim" plugin. Exception:
    function health#check, line 20
    Vim(eval):E5108: Error executing lua /home/maxime/.config/nvim/lua/astronvim/health.lua:6: attempt to concatenate a nil value
    stack traceback:
    /home/maxime/.config/nvim/lua/astronvim/health.lua:6: in function 'check'
    [string "luaeval()"]:1: in main chunk

```

Might want to append an `or "unknown"` on this line

### Describe the bug

`null-ls` formatters are no longer configured for auto formatting or as mapping since v3.0.0

### Steps to Reproduce

1. Use this configuration

	```lua
	return {
	  plugins = {
	    { 
	      "jose-elias-alvarez/null-ls.nvim",
	      opts = function(opts)
	        local null_ls = require "null-ls"
	        opts.sources = {
	          null_ls.builtins.formatting.black,
	        }
	        return opts
	      end,
	    },
	  },
	  lsp = {
	    formatting = {
	      format_on_save = {
	        enabled = true,
	      },
	    },
	  },
	}
	```

2. Try `<Leader>lf` on a Python file (it won't work)
3. Try saving `:w` (it won't work)
4. Try `:lua vim.lsp.buf.format()` (it will work)

### Expected behavior

* `<Leader>lf` mapping is active with `null-ls` formatters
* Format on save works with `null-ls` formatters

### Screenshots

The `null-ls` formatter is active:

![image](https://user-images.githubusercontent.com/32458727/224470563-34119a51-1c50-49cc-ae7f-23642c65e852.png)

But the mapping is missing:

![image](https://user-images.githubusercontent.com/32458727/224470620-cf9aeeca-68b3-47a5-b74c-d1250efb20bc.png)

### Additional Context

AstroNvim v3.0.1

**Comment by mehalter** [comment]
Not sure what is causing this, I can take a deeper look early next week when I'm back at a computer. One thing I did notice is your `null-ls` plugin definition is wrong:

```lua
    { 
      "jose-elias-alvarez/null-ls.nvim",
      opts = function(opts)
        local null_ls = require "null-ls"
        opts.sources = {
          null_ls.builtins.formatting.black,
        }
        return opts
      end,
    },
```

Should be:

```lua
    { 
      "jose-elias-alvarez/null-ls.nvim",
      opts = function(_, opts)
        local null_ls = require "null-ls"
        opts.sources = {
          null_ls.builtins.formatting.black,
        }
        return opts
      end,
    },
```

Honestly not sure why black would be attaching anyway with that issue

**Comment by mehalter** [comment]
I can confirm that this minimal `user/init.lua` file is working or setting up formatting of `null-ls` sources and auto formatting:

```lua
return {
  plugins = {
    {
      "jose-elias-alvarez/null-ls.nvim",
      opts = function(_, opts)
        local null_ls = require "null-ls"
        opts.sources = {
          null_ls.builtins.formatting.black,
        }
        return opts
      end,
    },
  },
}
```

@maxbrunet could you share your user configuration and I can take a look to see what might be going on in it? The discord is also a good resource for asking questions

**Comment by maxbrunet** [comment]
Good catch @mehalter, thank you, I missed that in my migration. And congrats on the release of v3, amazing as always, absolutely loving it! :tada:
