### ISSUE TITLE
Error on attempt to update to v3.0.2

### ISSUE THREAD

**Issue by zalech** [AstroNvim/AstroNvim#1616]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

MacOS 11.7.4

### Terminal/GUI

alacritty

## AstroNvim
  - INFO: AstroNvim Version: v3.0.1
  - INFO: Neovim Version: v0.8.3
  - OK: Using stable Neovim >= 0.8.0
  - OK: `git` is installed: Used for core functionality such as updater and plugin management
  - OK: `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
  - OK: `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
  - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
  - WARNING: `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
  - WARNING: `btm` is not installed: Used for mappings to pull up system monitor (Optional)
  - OK: `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Getting this error message when trying to update to v3.0.2:

```
Error running command: git -C /Users/zalech/.config/nvim config branch.HEAD.remote
Error message:

Error executing Lua callback: /Users/zalech/.config/nvim/lua/astronvim/utils/git.lua:76: attempt to concatenate local 'remote' (a nil value)
stack traceback:
        /Users/zalech/.config/nvim/lua/astronvim/utils/git.lua:76: in function 'remote_url'
        /Users/zalech/.config/nvim/lua/astronvim/utils/updater.lua:121: in function 'create_rollback'
        /Users/zalech/.config/nvim/lua/astronvim/utils/updater.lua:249: in function 'update'
        /Users/zalech/.config/nvim/lua/astronvim/autocmds.lua:234: in function </Users/zalech/.config/nvim/lua/astronvim/autocmds.lua:234>
```

### Steps to Reproduce

`:AstroUpdate`

### Expected behavior

Update with no error message 

### Additional Context

In my /lua/user/init.lua:
```
  updater = {
    remote = "origin", -- remote to use
    channel = "stable", -- "stable" or "nightly"
    version = "latest", -- "latest", tag name, or regex search like "v1.*" to only do updates before v2 (STABLE ONLY)
    branch = "main", -- branch name (NIGHTLY ONLY)
    commit = nil, -- commit hash (NIGHTLY ONLY)
    pin_plugins = nil, -- nil, true, false (nil will pin plugins on stable only)
    skip_prompts = false, -- skip prompts about breaking changes
    show_changelog = true, -- show the changelog after performing an update
    auto_quit = false, -- automatically quit the current session after a successful update
  },
```

**Comment by mehalter** [comment]
Fixed in latest commit :) you might want to go to your `~/.config/nvim` folder manually and run `git fetch origin && git checkout v3.0.3` to pull the new version
