### ISSUE TITLE
Invalid plugin spec after update to 3.2.2

### ISSUE THREAD

**Issue by Gabryx64** [AstroNvim/AstroNvim#1619]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Arch Linux (Linux Zen 6.2.2)

### Terminal/GUI

kitty, neovide

## AstroNvim
  - INFO: AstroNvim Version: v3.0.3
  - INFO: Neovim Version: v0.8.3
  - OK: Using stable Neovim >= 0.8.0
  - OK: `git` is installed: Used for core functionality such as updater and plugin management
  - OK: `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
  - OK: `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
  - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
  - WARNING: `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
  - OK: `btm` is installed: Used for mappings to pull up system monitor (Optional)
  - OK: `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

After i updated to the latest AstroNVim version, i encountered this error:
```
Errore/i eseguendo /home/gabry/.config/nvim/init.lua:
Invalid plugin spec {
  init = { "ellisonleao/gruvbox.nvim", "alaviss/nim.nvim",
    ["ShinKage/idris2-nvim"] = {
      after = "mason-lspconfig.nvim",
      requires = { "MunifTanjim/nui.nvim" }
    },
    ["iamcco/markdown-preview.nvim"] = {
      ft = { "markdown" },
      run = "cd app && npm install",
      setup = <function 1>
    },
    ["ionide/Ionide-vim"] = {
      run = "make fsautocomplete"
    },
    ["nvim-treesitter/nvim-treesitter"] = {
      config = <function 2>
    },
    ["tzachar/cmp-tabnine"] = {
      after = "nvim-cmp",
      run = "./install.sh"
    }
  },
  ["mason-lspconfig"] = {},
  ["mason-null-ls"] = {},
  ["mason-nvim-dap"] = {},
  ["null-ls"] = <function 3>,
  treesitter = {}
}
```

(note i didn't actually run `:PackerSync` because it cannot find the command)

### Steps to Reproduce

1. Updated to latest AstroNVim commit through `:AstroUpdate`

### Expected behavior

To load the plugins normally

**Comment by Gabryx64** [comment]
On a side note i just noticed previously i was on AstroNVimv2 so it probably has to do with the new plugin system.

**Comment by luxus** [comment]
please follow the migration guide, if you need help you can ask the community in discord
https://discord.gg/astronvim

**Comment by mehalter** [comment]
Here is the migration guide: https://astronvim.com/Configuration/v3_migration
