### ISSUE TITLE
plugin.default_config(opts) throws nil value error

### ISSUE THREAD

**Issue by ckt114** [AstroNvim/AstroNvim#1622]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

13.2.1

### Terminal/GUI

wezterm

### AstroNvim Health

```
astronvim: require("astronvim.health").check()
========================================================================
## AstroNvim
  - INFO: AstroNvim Version: v3.0.1
  - INFO: Neovim Version: v0.8.2
  - OK: Using stable Neovim >= 0.8.0
  - OK: `git` is installed: Used for core functionality such as updater and plugin
  management
  - OK: `open` is installed: Used for `gx` mapping for opening files with system opener
  (Optional)
  - OK: `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
  - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
  - OK: `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
  - WARNING: `btm` is not installed: Used for mappings to pull up system monitor
  (Optional)
  - OK: `python3` is installed: Used for mappings to pull up python REPL (Optional)
 ```

### Describe the bug

Calling `plugin.default_config(opts)` in a plugin throws nil value error.

### Steps to Reproduce

File: `plugins/treesitter.lua`
```lua
return {
  "nvim-treesitter/nvim-treesitter",
  config = function(plugin, opts)
    plugin.default_config(opts)
  end
}
```

### Expected behavior

Should not throw error.

### Screenshots

![image](https://user-images.githubusercontent.com/573808/224518968-d005fc5d-526b-45f0-bed4-9f3fccdaf526.png)

**Comment by mehalter** [comment]
@ckt114 this is outdated syntax that is not in the v3 release. If you found this in the documentation somewhere please let me know so I can update it but I think I got all of it updated everywhere. Check the `user_example` that was released with the official stable release of v3 (https://github.com/AstroNvim/user_example) to see the most up to date syntax or follow the migration guide.

**Comment by ckt114** [comment]
@mehalter That user_example is where I get the syntax from. See this: https://github.com/AstroNvim/user_example/blob/main/plugins/core.lua#L68-L69

**Comment by ckt114** [comment]
How do I set additional configs? Do I just do like below?
```lua
config = function(plugin, opts)
  -- my settings goes here?
end
```

**Comment by mehalter** [comment]
ah thank you for pointing this out! I have fixed this in the latest commit: https://github.com/AstroNvim/user_example/blob/main/plugins/core.lua#L68-L69
