### ISSUE TITLE
Toggling dashboard closes windows

### ISSUE THREAD

**Issue by kiil** [AstroNvim/AstroNvim#1624]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

manjaro sway

### Terminal/GUI

foot

### AstroNvim Health

  3 ## AstroNvim
  4   - INFO: AstroNvim Version: nightly (v3.0.3)
  5   - INFO: Neovim Version: v0.8.3
  6   - OK: Using stable Neovim >= 0.8.0
  7   - OK: `git` is installed: Used for core functionality such as updater and plugin management
  8   - OK: `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
  9   - WARNING: `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
 10   - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
 11   - WARNING: `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
 12   - WARNING: `btm` is not installed: Used for mappings to pull up system monitor (Optional)
 13   - OK: `python` is installed: Used for mappings to pull up python REPL (Optional)
 14 

### Describe the bug

Minor annoyance:

When toggling dashboard with `leader + h` in a window, toggling back away from the home dashboard will also close the window unless there is only one window open.

My workaround so far is to use `leader + h` to open the dashboard in the selected window, and then using `ctrl + 6` (alternative file) to get back to the buffer I was working on in the same window, without closing my selected window.

### Steps to Reproduce

1. Open two buffers
2. Make a split
3. Place a buffer in each split
4. from either of the windows do `leader + h`
5. Then do `leader + h` again
6. The window will close, leaving only one window open

### Expected behavior

I would expect toggling the home dashboard to not close windows.

**Comment by mehalter** [comment]
Thanks for reporting! This seems to be a bug in Alpha, you can replicate it by simply running the `:Alpha` command. This should be opened on Alpha's repository: https://github.com/goolord/alpha-nvim/issues

I have also tested this without AstroNvim in a fresh installation and can replicate it.
