### ISSUE TITLE
rebinding arrow keys doesn't apply to neo tree

### ISSUE THREAD

**Issue by szechp** [AstroNvim/AstroNvim#1626]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

ubuntu 22.04

### Terminal/GUI

gnome

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: nightly (v3.0.3)
- Neovim Version: v0.9.0-dev-1086+gaa840ab56
- WARNING Neovim nightly is not officially supported and may have breaking changes
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

I rebound my arrow keys to move between windows using the mapping.lua in the user folder. It works, but once I enter the neo-tree buffer, the arrows default to their original behaviour, resizing the window. When I move away from neo-tree window with ctrl+l an enter a normal buffer, crtl+arrows will work again.

### Steps to Reproduce

1. Change to neo-tree buffer with remapped crtl+left arrow.
2. I need to leave the neo-tree buffer by any other means (either with the mouse, or by pressing the default mapping ctrl +l)

### Expected behavior

Keymappings should be consistent across buffers. (I know there's a special case concerning terminal buffers, but those don't concern me)

**Comment by mehalter** [comment]
Can you please share your user configuration.

**Comment by szechp** [comment]
https://github.com/szechp/astrovim-config

**Comment by szechp** [comment]
just pushed them :)

**Comment by mehalter** [comment]
Ok, so a couple things, one you will need to make sure that you match our casing for the keys to make sure you override them. Also you have a syntax error in the `ctrl-right` mapping where you are missing the closing `>`

```lua
    ["<C-Left>"] = { [[<C-W>h]] },
    ["<C-Down>"] = { [[<C-W>j]] },
    ["<C-Up>"] = { [[<C-W>k]] },
    ["<C-Right>"] = { [[<C-W>l]] },
```

this is what you want them to be
