### ISSUE TITLE
Multiple line commenting

### ISSUE THREAD

**Issue by dmayilyan** [AstroNvim/AstroNvim#1628]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

WSL  Ubuntu 22.04.2 LTS

### Terminal/GUI

Windows Terminal

### AstroNvim Health

`Number + leader + /`  doesn't comment multiple lines.

### Describe the bug

`Number + leader + /`  doesn't comment multiple lines.

### Steps to Reproduce

1. Open a multi line python code
2. Try to comment 5 lines lines in the **normal** mode `5+ leader + /`
3. Look at the result

### Expected behavior

Should've commented out 5 lines.

### Screenshots

![image](https://user-images.githubusercontent.com/6394434/224741694-d3bec49a-3318-4a5b-b787-0d1a383df876.png)

**Comment by mehalter** [comment]
@dmayilyan just made a push to `nightly` that resolves this, will release soon
