### ISSUE TITLE
Add an option to disable the default mappings

### ISSUE THREAD

**Issue by bryantchan** [AstroNvim/AstroNvim#1632]
### Describe the new feature

As an AstroNvim user, I have found the default mappings to be very useful in setting up the environment for new users. However, I have also noticed that some users may prefer to use their own custom mappings instead. It would be great if there was an option to disable the default mappings and use custom ones instead.

I believe that adding this feature would make AstroNvim more flexible and customizable, which would be beneficial for many users. I understand that this may take some time and effort to implement, but I believe it would be a valuable addition to the plugin.

Thank you for your hard work on this project, and I look forward to hearing your thoughts on my request.

**Comment by mehalter** [comment]
This is actually quite easy with the current implementation! Here is an example `user/init.lua` file:

```lua
return {
  mappings = function()
    return {
      -- fully custom mappings table
    }
  end,
}
```

This used the function notation here: https://astronvim.com/Configuration/override_formats#override-function
