### ISSUE TITLE
Impossible to move between tabs with ]t or Shift+L

### ISSUE THREAD

**Issue by marchellodev** [AstroNvim/AstroNvim#1634]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.2.1

### Terminal/GUI

WezTerm

### AstroNvim Health

```

astronvim: require("astronvim.health").check()
========================================================================
## AstroNvim
  - INFO: AstroNvim Version: v3.1.1
  - INFO: Neovim Version: v0.8.3
  - OK: Using stable Neovim >= 0.8.0
  - OK: `git` is installed: Used for core functionality such as updater and plugin management
  - OK: `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
  - OK: `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
  - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
  - WARNING: `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
  - OK: `btm` is installed: Used for mappings to pull up system monitor (Optional)
```

### Describe the bug

After upgrading to v3, it seems to be impossible to move between tabs. The only way which works is switching buffers (`[b` or `]b`).

### Steps to Reproduce

Try moving between tabs via ]t or Shift+L

### Expected behavior

Tab movements should work correctly

**Comment by mehalter** [comment]
I just verified that navigating between vim tabs does work with `[t` and `]t`. Also yes `[b` and `]b` are used for navigating between vim buffers which in AstroNvim are display in the tabline. In previous releases we did use `H` and `L` to navigate between buffers but we decided to change these bindings to `[b` and `]b` to not override core vim bindings. This is covered in the migration guide: https://astronvim.com/Configuration/v3_migration

**Comment by ZackGlenn** [comment]
I know this is closed, but navigation with [t and ]t doesn't work for me either.

**Comment by mehalter** [comment]
`]t` and `[t` are used to navigate between *real* vim tabs. So stuff created with `:tabnew`. You should check if you mean these types of tabs or buffers which we display in a tabular way in the tabline @ZackGlenn

**Comment by ZackGlenn** [comment]
Oh, I see. It works, but this system of tabs-that-aren't-actually-tabs is rather confusing. Was it always like this?

**Comment by mehalter** [comment]
Yeah it's always been like this @ZackGlenn

**Comment by inaciorafael** [comment]
I was already used to using Shift+l and Shift+h in the documentation itself there is an excerpt showing how to configure it your way - https://astronvim.com/Configuration/v3_migration

> nvim/astronvim/mappings.lua

```lua
-- Navigate tabs
maps.n["<S-l>"] = {
  function() require("astronvim.utils.buffer").nav(vim.v.count > 0 and vim.v.count or 1) end,
  desc = "Next buffer"
}
maps.n["<S-h>"] = {
  function() require("astronvim.utils.buffer").nav(-(vim.v.count > 0 and vim.v.count or 1)) end,
  desc = "Previous buffer"
}

```
