### ISSUE TITLE
Module 'lazy' not found

### ISSUE THREAD

**Issue by alex-belost** [AstroNvim/AstroNvim#1635]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS Ventura 13.2.1

### Terminal/GUI

iTerm2

### AstroNvim Health

astronvim: require("astronvim.health").check()
========================================================================
## AstroNvim
  - INFO: AstroNvim Version: v3.1.1
  - INFO: Neovim Version: v0.8.2
  - OK: Using stable Neovim >= 0.8.0
  - OK: `git` is installed: Used for core functionality such as updater and plugin management
  - OK: `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
  - OK: `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
  - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
  - OK: `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
  - OK: `btm` is installed: Used for mappings to pull up system monitor (Optional)
  - OK: `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Tried to install latest version of AstroNvim but got an error

```
Please wait while plugins are installed...
Error detected while processing /Users/alex/.config/nvim/init.lua:
Failed to load astronvim.lazy
/Users/alex/.config/nvim/lua/astronvim/lazy.lua:31: module 'lazy' not found:
^Ino field package.preload['lazy']
^Ino file './lazy.lua'
^Ino file '/usr/local/share/luajit-2.1.0-beta3/lazy.lua'
^Ino file '/usr/local/share/lua/5.1/lazy.lua'
^Ino file '/usr/local/share/lua/5.1/lazy/init.lua'
^Ino file './lazy.so'
^Ino file '/usr/local/lib/lua/5.1/lazy.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
```

### Steps to Reproduce

```
mv ~/.config/nvim ~/.config/nvim.bak
```

```
mv ~/.local/share/nvim ~/.local/share/nvim.bak
mv ~/.local/state/nvim ~/.local/state/nvim.bak
mv ~/.cache/nvim ~/.cache/nvim.bak
```

```
git clone --depth 1 https://github.com/AstroNvim/AstroNvim ~/.config/nvim
nvim
```

### Expected behavior

Everything works fine )

### Additional Context

I used to work with the previous version. Right now I use the LunarVim

**Comment by mehalter** [comment]
after you get the error what do you see in `~/.local/share/nvim/lazy/`

**Comment by alex-belost** [comment]
![image](https://user-images.githubusercontent.com/17066351/225098322-6d447994-5a8e-4373-bf33-a9f7f57b4617.png)

I haven't this folder at all

**Comment by mehalter** [comment]
and this is after you trying to run `nvim` and get this error?

**Comment by mehalter** [comment]
do you have `git` installed and available in your `PATH`?

**Comment by mehalter** [comment]
https://github.com/AstroNvim/AstroNvim/blob/814c512c0cb550178a44e1994f9275dc24d853f3/lua/astronvim/lazy.lua#L1-L19

it looks like for some reason your system is unable to clone lazy. If you start neovim and run `:lua =vim.fn.stdpath "data"` what do you get?

**Comment by alex-belost** [comment]
> and this is after you trying to run nvim and get this error?

Yes
![image](https://user-images.githubusercontent.com/17066351/225237711-5cc4b492-0d0f-46f7-9ae8-6a1b50e2ede9.png)
![image](https://user-images.githubusercontent.com/17066351/225237795-e2264bbc-ddab-4de3-b83f-b61b5aa26eaf.png)

> do you have git installed and available in your PATH?

Yep, works fine

![image](https://user-images.githubusercontent.com/17066351/225238292-14b31444-5516-44ac-bb69-c1afbb35ede5.png)

> f you start neovim and run :lua =vim.fn.stdpath "data" what do you get?

![image](https://user-images.githubusercontent.com/17066351/225238557-8aebf954-d3d2-4bd1-ac59-1b69d2620b19.png)

**Comment by mehalter** [comment]
@alex-belost could you add some print statements throughout these lines to start debugging where it is getting lost? 

https://github.com/AstroNvim/AstroNvim/blob/814c512c0cb550178a44e1994f9275dc24d853f3/lua/astronvim/lazy.lua#L1-L19

**Comment by alex-belost** [comment]
![image](https://user-images.githubusercontent.com/17066351/225269861-e846b328-9893-415f-aef3-9d74f5f6011b.png)
![image](https://user-images.githubusercontent.com/17066351/225270012-20fb3aaf-8a39-447b-a3ce-e5f3a59bd9eb.png)

**Comment by mehalter** [comment]
Thanks @alex-belost do you think you would be able to do a bit more in this case? I can't replicate this in any way so i need you to do a bit of debugging to figure out what the root cause is here. It looks like it's noticing that the file doesn't exist which is good, but idk why that fit clone isn't seeming to happen

**Comment by alex-belost** [comment]
Sure, I'm not so qualified, if you give some suggestions will be great

**Comment by alex-belost** [comment]
looks like autocmd won't work

**Comment by alex-belost** [comment]
![image](https://user-images.githubusercontent.com/17066351/225272612-3feb7406-d687-4d61-bb6d-88e31773adb0.png)

**Comment by mehalter** [comment]
Could you change line 4, the line that calls the git clone to these 2 lines:

```lua
local result = vim.fn.system { "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath }
vim.pretty_print(result)
```

Also yeah that autocmd will not run because it runs after lazy initializes and your system is never cloning it

**Comment by alex-belost** [comment]
![image](https://user-images.githubusercontent.com/17066351/225275709-7b0bde1a-48a8-4c07-a305-10042db0ab6b.png)

**Comment by mehalter** [comment]
What version of `got` do you have ?

**Comment by alex-belost** [comment]
2.15.0

**Comment by mehalter** [comment]
Ah this is quite an old version of `git`. Would you be able to update to at least version 2.17 and see if that resolves it?

**Comment by mehalter** [comment]
@alex-belost I have gone ahead and removed this `filter` flag on the `nightly` branch. If you want to check out the `nightly` branch with `git checkout nightly` and make sure you have pulled the latest and retry? I will release this as a patch to support older git clients

**Comment by alex-belost** [comment]
I updated to the latest git version. It works!!! Thanks a lot!!

**Comment by mehalter** [comment]
@KasparRosin no need to make a new issue. It's much better to keep the discussion localized. Have you been able not follow some of the previous discussion here to debug what's going on with your set-up? We are not relying on these new git features described here anymore. But I can't replicate this, so I will need your assistance to debug what the issue is and to identify the problem.

**Comment by KasparRosin** [comment]
Did some debugging. Seems the issue was still with git.
Rather the network/proxy restrictions I had.

Git clone was unsuccessful which caused this issue.
Fixed the issue on my side, now everything works.

I'm not sure whether it's possible to add some try/catch that would forward the git error, so we, users, could understand what caused the issue?

**Comment by mehalter** [comment]
Added this to nightly: 4d42b666634106f2f7d6fb92f1a9ff9403b10ec7

**Comment by alex1701c** [comment]
I ran into the same issue while using the stable version. Meaning having it in stable would be useful.

**Comment by JakWai01** [comment]
I am experiencing the same issue as well (version `v0.8.3`, git `2.39.2`).

**Comment by luxus** [comment]
have you tried 0.9? its now in the stable branch

**Comment by Kolkhis** [comment]
I'm experiencing this issue with Nvim `0.9.0`, and Git `2.39.2`

**Comment by jayvil** [comment]
I was getting the same error with
git: 2.34.1
