### ISSUE TITLE
Hot reloading for mappings.lua & highlights/*.lua

### ISSUE THREAD

**Issue by utkarshgupta137** [AstroNvim/AstroNvim#1643]
### Is your feature related to a problem?

Modifying mappings or highlights requires a restart every time, which is quite annoying.

### Describe the new feature

I know that hot reloading the whole config can lead to issues, but perhaps "simple" things like mappings & highlights could be reloaded without causing any issues. To be clear, hot-reloading will only take care of additions & modifications, not removals.

**Comment by mehalter** [comment]
@utkarshgupta137 I just put together a commit to take a stab at this :) Hard to guarantee it will be super stable, but it does basically a minimal amount of reloading. Covers `mappings`, `options`, and `highlights` for sure

**Comment by utkarshgupta137** [comment]
Awesome! Let me try it.

**Comment by mehalter** [comment]
It's currently just on `nightly` so please give that a try and let me know what you think 😅

**Comment by mehalter** [comment]
it's not currently reapplying the colorscheme because you might not necessarily know the name to call `colorscheme` on, but it should reload them that if you switch colorschemes and switch back it should work

**Comment by mehalter** [comment]
actually let me try something, maybe I can make that live reload in a relatively nice way

**Comment by mehalter** [comment]
Ok @utkarshgupta137 I actually did get a semi-decent way of doing highlight reloading in a partial manner live when you run `:AstroReload`. Basically it will re-run our highlight addition stuff but will not resource the current colorscheme because there's no way for us to know what to call `colorscheme` with. That means tweaking a highlight and adding highlights will work totally fine on reload. If you remove a highlight you will need to manually reload your colorscheme after you run `:AstroReload`.

**Comment by utkarshgupta137** [comment]
Thanks! The reload is affecting the bufline for some reason:

https://user-images.githubusercontent.com/5155100/235130950-8aff6e87-4107-4af6-9fda-9a689547c21a.mov

Notice also the cutoff error in NeoTree: `ufo: Error executing lua: ...`

**Comment by mehalter** [comment]
@utkarshgupta137 I don't think the video is working for me

**Comment by utkarshgupta137** [comment]
Try this: https://ezgif.com/video-to-gif/ezgif-5-1416709b32.mov?

**Comment by mehalter** [comment]
Doesn't seem like it @utkarshgupta137

**Comment by utkarshgupta137** [comment]
Screenshots it is:
Before:
<img width="1800" alt="image" src="https://user-images.githubusercontent.com/5155100/235135738-9640c4a4-c593-46a9-8a63-4610b417f433.png">

After AstroReload:
<img width="1800" alt="image" src="https://user-images.githubusercontent.com/5155100/235135809-fbff751e-76bb-4a3d-aae2-5728d37b47dd.png">

After entering insert mode:
<img width="1800" alt="image" src="https://user-images.githubusercontent.com/5155100/235135861-ea30abfa-9cd6-4beb-b971-756996b487af.png">

**Comment by mehalter** [comment]
Ok cool, I'll take a look and see if I can improve the stability. The bottom line will probably be something along the lines of this will never be completely stable because Lua module reloading is not stable with how they interact in Neovim and with everything 😂 I'll do my best

**Comment by mehalter** [comment]
@utkarshgupta137 resolved the tab stuff in v3.12.1. Not sure what the ufo error is. Might be something out of our control with reloading modules. I can't replicate it though

**Comment by utkarshgupta137** [comment]
Nice. Everything works perfectly now!
