### ISSUE TITLE
lsp signature has no border

### ISSUE THREAD

**Issue by nikolasetiawan** [AstroNvim/AstroNvim#1645]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 12.6.1

### Terminal/GUI

iTerm2

### AstroNvim Health

  - INFO: AstroNvim Version: v3.2.1
  - INFO: Neovim Version: v0.8.3
  - OK: Using stable Neovim >= 0.8.0
  - OK: `git` is installed: Used for core functionality such as updater and plugin management
  - OK: `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
  - OK: `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
  - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
  - WARNING: `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
  - WARNING: `btm` is not installed: Used for mappings to pull up system monitor (Optional)
  - OK: `python` is installed: Used for mappings to pull up python REPL (Optional)

## lsp signature border not present
![Screenshot 2023-03-15 at 16 02 21](https://user-images.githubusercontent.com/92424267/225305395-a98da292-9a53-4fea-a2ae-b7babde149cd.png)
even though in lspconfig.lua it is set to "rounded"
<img width="993" alt="Screenshot 2023-03-15 at 19 12 34" src="https://user-images.githubusercontent.com/92424267/225305606-76e6ff9a-9792-40ae-8fb6-70a9bdf35f61.png">

### Steps to Reproduce

1. open a file with an lsp attached
2. call a function to make lsp-signature pop out

### Expected behavior

lsp-signature floating window has border "rounded"

**Comment by mehalter** [comment]
can you share your user configuration? You probably have a plugin that is overriding the handler

**Comment by mehalter** [comment]
One plugin I know of off the top of my head that will override this is `noice`, do you happen to have that installed?

**Comment by nikolasetiawan** [comment]
yes, seems that noice is causing this and #1646. Will close this issue for now and investigate noice behavior.

Thank you
