### ISSUE TITLE
Issue with some keys re-mapping

### ISSUE THREAD

**Issue by Onefabis** [AstroNvim/AstroNvim#1649]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Windows 11

### Terminal/GUI

qt-nvim, cmd

### AstroNvim Health

astronvim: require("astronvim.health").check()
========================================================================
## AstroNvim
  - INFO: AstroNvim Version: v3.2.1
  - INFO: Neovim Version: v0.8.3
  - OK: Using stable Neovim >= 0.8.0
  - OK: `git` is installed: Used for core functionality such as updater and plugin management
  - OK: `explorer` is installed: Used for `gx` mapping for opening files with system opener (Optional)
  - WARNING: `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
  - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
  - WARNING: `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
  - WARNING: `btm` is not installed: Used for mappings to pull up system monitor (Optional)
  - OK: `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Some keys are not fully re-mapped in the mappings.lua file in user folder, like: "c", "a", "k". If I remap them for the left, right navigation and undo accordingly, they are not re-mapped even in astronvim/mappings.lua file as well. There wasn't any problem with the old init.lua in 2.10v with the same keys

### Steps to Reproduce

1. Install latest stable Astronvim 3.2.1
2. Install user folder structure described in the doc
3. Assign "c" key to the Move left cursor, "a" key to the Move right cursor
4. Try to use it

### Expected behavior

The cursor should move left-right in the normal mode over the text with that c and a keys

**Comment by mehalter** [comment]
I have just tested this with this minimal `user/init.lua` file:

```lua
return {
  mappings = {
    n = {
      c = "h",
      a = "l",
    },
  },
}
```

not sure what you mean, this seems to work alright

**Comment by mehalter** [comment]
Also tested with this in `user/mappings.lua`:

```lua
return {
  n = {
    c = "h",
    a = "l",
    k = "u",
  },
}
```

**Comment by Onefabis** [comment]
thanks, did re-installed the Astronvim and all is good now, except small delay in "c" key, looks like it's trying to show "whichkey" of the old mapping?

**Comment by mehalter** [comment]
Yeah I'm not sure the best way to get around that other than disabling the operators in `which-key` would be my guess. Maybe you can get around it with `nowait` on the mappings? Glad you got it working thought!

**Comment by Onefabis** [comment]
Not any of this was managed to work

```
require("which-key").setup({
  triggers_blacklist = {
  n = { "c", "y", "h" },
  },
})
```
	
```
local wk = require("which-key")
wk.register({ c = "which_key_ignore", y = "which_key_ignore" }, { mode = "n" })
```

`nowait` didn't help as well. If I hit "c" and "i" immediately for instance I'll see whick-key popup anyway.
So I think I'll switch it off. Just for inform to those who will get in the same problems. Strange that on the 2.10 Astronvim there was zero lag.

**Comment by mehalter** [comment]
Thanks for sharing a solution @Onefabis !
