### ISSUE TITLE
lazygit panel rendering error

### ISSUE THREAD

**Issue by Falldio** [AstroNvim/AstroNvim#1653]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Windows 11

### Terminal/GUI

Windows Terminal

### AstroNvim Health

astronvim: require("astronvim.health").check()
========================================================================
## AstroNvim
  - INFO: AstroNvim Version: v3.3.0
  - INFO: Neovim Version: v0.8.2
  - OK: Using stable Neovim >= 0.8.0
  - OK: `git` is installed: Used for core functionality such as updater and plugin management
  - OK: `explorer` is installed: Used for `gx` mapping for opening files with system opener (Optional)
  - OK: `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
  - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
  - WARNING: `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
  - OK: `btm` is installed: Used for mappings to pull up system monitor (Optional)
  - OK: `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

After open menu panel in lazygit, the lazygit pannel begins to render incorrectly. The content is just not in the right place.

The rendering error only occurs inside lazygit panel. It will not affect nvim rendering.

### Steps to Reproduce

1. Open a git repo with nvim
2. Press `<LEADER>gg` to toggle lazygit panel
3. Press `x` to open menu
4. The rendering error occurs.

### Expected behavior

The content of lazygit should be rendered correctly.

### Screenshots

The following two pics shows the rendering error.

![QQ截图20230316141805](https://user-images.githubusercontent.com/32453247/225532516-a78a470d-d6cd-45df-878e-7b69911a776a.png)
![QQ截图20230316142618](https://user-images.githubusercontent.com/32453247/225532886-91fd986e-6078-439a-9fe4-a391cf4bb617.png)

### Additional Context

I wonder if it has something to do with the Chinese font, but I'm not so sure and I don't know how to confirm😢

**Comment by mehalter** [comment]
AstroNvim doesn't do anything related to how things are rendered in the terminal. There are a few things that could be affecting this:

- could be your terminal not properly supporting font stuff
- could be your font messing up the rendering
- could be a bug in toggleterm itself

Hopefully that helps point you in the right direction!

If you find anything else or a solution please come back and share it for future users! Also please let me know if you deduce it down to where you think it is AstroNvim and I can look back into reopening this. 😄
