### ISSUE TITLE
Primary selection doesn't work as in vanilla neovim

### ISSUE THREAD

**Issue by tkopecek** [AstroNvim/AstroNvim#1654]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Fedora 37

### Terminal/GUI

kitty/nvim-qt/wayland

## AstroNvim
  - INFO: AstroNvim Version: v3.3.0
  - INFO: Neovim Version: v0.8.3
  - OK: Using stable Neovim >= 0.8.0

### Describe the bug

Visual selection doesn't get synchronized to '*' register, so primary selection is never updated. It works other way - content from other applications is being synchronized, so it can pasted in nvim. This work as expected in vanilla nvim. Is it intended and if yes, what is the motivation?

### Steps to Reproduce

enter visual mode, make any selection, check content of '*' register

### Expected behavior

visual selection should be immediately copied into '*'

**Comment by mehalter** [comment]
If you set `vim.opt.clipboard = ""` does this issue go away?

**Comment by tkopecek** [comment]
> If you set `vim.opt.clipboard = ""` does this issue go away?

No, it behaves same. I've tried it also with clean astronvim installation, so it shouldn't be tied to other plugins.

**Comment by mehalter** [comment]
Hm I think setting `vim.opt.clipboard` is the only thing we change in regards to how the yank registers work 🤔

**Comment by mehalter** [comment]
I just tested this and cannot replicate it. The `*` register seems to behave as normal in a clean installation

**Comment by mehalter** [comment]
I notice you said the visual selection is not syncing to the primary clipboard. I can replicate that behavior both in AstroNvim and in a clean/vanilla neovim instance @tkopecek
