### ISSUE TITLE
Problem with localization when the file is changed : Save changes ...? [Y]es, [N]o, [C]ancel

### ISSUE THREAD

**Issue by ucomru** [AstroNvim/AstroNvim#1662]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Mac OS 13.2.1

### Terminal/GUI

iTerm2

## AstroNvim
  - INFO: AstroNvim Version: v3.3.2
  - INFO: Neovim Version: v0.8.3
  - OK: Using stable Neovim >= 0.8.0
  - OK: `git` is installed: Used for core functionality such as updater and plugin management
  - OK: `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
  - OK: `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
  - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
  - OK: `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
  - OK: `btm` is installed: Used for mappings to pull up system monitor (Optional)
  - OK: `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

After update When I want to quit standard NeoVim (no plugins installed) ```:q``` with changed file, I’ll get 2 mistakes:
```
E37: No write since last change
E162: Not kept changes in the buffer …
Press ENTER or enter team for continuation
```

But, when I use AstroNvim, I’ll get the message:
```
Save changes ...?
[Y]es, [N]o, [C]ancel:
```

My problem that I use not standard locale (C.UTF-8 or en_US.UTF-8). Therefore: “Yes, Not and Cancel’’’ will be not in English.
That is instead of Y/N/C I need to replace keyboard layout.
As it is known Vim and NVim cope only English letters.

How to establish standard (English) localization for this question?

### Steps to Reproduce

1. Change file
2. :q
3. [Y]es, [N]o, [C]ancel

### Expected behavior

Get standard (English) localization when I quit the changed file

**Comment by mehalter** [comment]
We are using the built in `:confirm` command here. This will be a question for core Neovim as to fixing it to adhere to localization.

**Comment by ucomru** [comment]
Im sorry! It's stupid question.
I set:
'''
export LANG='C.UTF-8'
'''
and all OK
