### ISSUE TITLE
Incorrectly setting cwd when opening file in buffer

### ISSUE THREAD

**Issue by Subjective** [AstroNvim/AstroNvim#1667]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.2

### Terminal/GUI

iTerm2

### AstroNvim Health
```
astronvim: require("astronvim.health").check()
========================================================================
## AstroNvim
  - INFO: AstroNvim Version: nightly (v3.3.1-1-g952f61e)
  - INFO: Neovim Version: v0.8.3
  - OK: Using stable Neovim >= 0.8.0
  - OK: `git` is installed: Used for core functionality such as updater and plugin management
  - OK: `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
  - OK: `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
  - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
  - OK: `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
  - WARNING: `btm` is not installed: Used for mappings to pull up system monitor (Optional)
  - OK: `python3` is installed: Used for mappings to pull up python REPL (Optional)
```
### Describe the bug

For a while now, I've noticed this strange issue where viewing a file in a buffer causes the global working directory to change. It doesn't happen very often, but when it does, it's incredibly annoying.

When working on a project with multiple files, each file seems to have its own cwd associated with it, and viewing a file in a buffer automatically sets the global cwd to whatever cwd was previously associated with that file. This is somewhat annoying when you change the cwd in Neotree, only to have it switch back after toggling the focus back to the file's buffer.

### Steps to Reproduce

I'm not entirely sure how to replicate the issue, but it usually occurs when the same file has been opened in multiple sessions.

### Expected behavior

When launching neovim, I would expect the cwd to be set either to the directory of the parent shell when opening a single file, or to the directory of a session when opening a project.

### Screenshots

I've recorded a few gifs to illustrate what happens. Below you can see that I had Neotree set the cwd to "~/.config/nvim-profiles/astro3", but immediately after switching the focus back to the file buffer, the cwd reverts.

![Screen Recording 2023-03-17 at 5 40 44 PM](https://user-images.githubusercontent.com/56745535/226074948-a00084ea-fd32-4b0b-a3a8-851513417a30.gif)

Here, I opened the same file individually, with the cwd of the shell before entering neovim set to the home directory. Ideally, the file would open with the cwd of neovim set to home as well, but it uses the saved cwd associated with the file.

![Screen Recording 2023-03-17 at 5 44 10 PM](https://user-images.githubusercontent.com/56745535/226075173-a722eb45-ef03-4c35-ae2d-5dec713943f2.gif)

Manually setting the working directory in the buffer does change the global cwd, but switching to another buffer causes the cwd to revert back. So, to correctly set the working directory of a project with more than one file (without it changing randomly changing back), you must manually set the working directory of each file's buffer (that has a previous saved directory associated with it).

![Screen Recording 2023-03-17 at 6 14 44 PM](https://user-images.githubusercontent.com/56745535/226075532-87825bb4-8682-4f3d-841c-0bec1e40ecf7.gif)

After a bit of digging around, I think the problem has to do with astronvim's mkview autocommands. I've found that commenting out the following autocommand solves the issue:
```lua
-- astronvim/autocmds.lua
local view_group = augroup("auto_view", { clear = true })
autocmd("BufWinLeave", {
  desc = "Save view with mkview for real files",
  group = view_group,
  callback = function(event)
    if vim.b[event.buf].view_activated then vim.cmd.mkview { mods = { emsg_silent = true } } end
  end,
})
autocmd("BufWinEnter", {
  desc = "Try to load file view if available and enable view saving for real files",
  group = view_group,
  callback = function(event)
    if not vim.b[event.buf].view_activated then
      local filetype = vim.api.nvim_get_option_value("filetype", { buf = event.buf })
      local buftype = vim.api.nvim_get_option_value("buftype", { buf = event.buf })
      local ignore_filetypes = { "gitcommit", "gitrebase", "svg", "hgcommit" }
      if buftype == "" and filetype and filetype ~= "" and not vim.tbl_contains(ignore_filetypes, filetype) then
        vim.b[event.buf].view_activated = true
        vim.cmd.loadview { mods = { emsg_silent = true } }
      end
    end
  end,
})
```
One last thing to note is that opening a session causes the cwd to not be set to the correct cwd, if the mkview for one of the files in the session stored another directory. Here, I opened the session for `nvim-profiles/astro3`, but the session was set to `nvim-profiles/astro` instead. This issue was resolved after commenting the above out.

![Screen Recording 2023-03-17 at 6 36 02 PM](https://user-images.githubusercontent.com/56745535/226076435-36239d02-ab77-4899-817f-e4b5c8a55d00.gif)

### Additional Context

The gifs were recorded in neovim nightly, but I've confirmed that the same issue occurs in stable.

**Comment by mehalter** [comment]
I made a commit to fix this on `nightly`

**Comment by mehalter** [comment]
https://github.com/AstroNvim/AstroNvim/commit/0e8943c59b2755cfd070ec7052b3098845a4416e

**Comment by mehalter** [comment]
@Subjective if you have view files that are already saved with the current working directory, you might need to just refresh those files with something like `rm -rf ~/.local/state/nvim/view`
