### ISSUE TITLE
no syntax highlighting with *.lua files + treesitter error

### ISSUE THREAD

**Issue by ucomru** [AstroNvim/AstroNvim#1673]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Mac OS 13.2.1 

### Terminal/GUI

iterm2

### AstroNvim Health

  - INFO: AstroNvim Version: v3.4.1
  - INFO: Neovim Version: v0.8.3
  - OK: Using stable Neovim >= 0.8.0
  - OK: `git` is installed: Used for core functionality such as updater and plugin management
  - OK: `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
  - OK: `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
  - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
  - OK: `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
  - OK: `btm` is installed: Used for mappings to pull up system monitor (Optional)
  - OK: `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

1. No syntax highlighting with *.lua files
   + treesitter error on any lines (the error changes a place):
**treesitter/highlighter: Error executing lua: ...im/0.8.3/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type a...**
```
 init.lua

   11 ▏ ▏ virtual_text = true,·treesitter/highlighter: Error executing lua: ...im/0.8.3/share/nvim/runtime/lua/vim/treesitter/query.lua:219: qu
   10 ▏ ▏ underline = true,·
    9 ▏ },·
    8 ▏treesitter/highlighter: Error executing lua: ...im/0.8.3/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type a
    7 ▏ lsp = {·
    6 ▏ ▏ -- customize lsp formatting options·
    5 ▏ ▏ formatting = {·
```

2. The **treesister** mistake appears at the first AstroNvim launch when automatic installation of plugins is carried out.
```
remote: Enumerating objects: 82, done.
remote: Counting objects: 100% (82/82), done.
remote: Compressing objects: 100% (81/81), done.
remote: Total 82 (delta 0), reused 45 (delta 0), pack-reused 0
Receiving objects: 100% (82/82), 84.08 KiB | 797.00 KiB/s, done.

Error detected while processing command line:
Error executing vim.schedule lua callback: .../.local/share/nvim/lazy/lazy.nvim/lua/lazy/view/text.lua:78: Failed to delete line
stack traceback:
    [C]: in function 'nvim_buf_set_lines'
    .../.local/share/nvim/lazy/lazy.nvim/lua/lazy/view/text.lua:78: in function 'render'
    ...local/share/nvim/lazy/lazy.nvim/lua/lazy/view/render.lua:76: in function 'update'
    .../.local/share/nvim/lazy/lazy.nvim/lua/lazy/view/init.lua:142: in function 'fn'
    ...s/tim/.local/share/nvim/lazy/lazy.nvim/lua/lazy/util.lua:72: in function <...s/tim/.local/share/nvim/lazy/lazy.nvim/lua/lazy/util.lua:71>
```

### Steps to Reproduce

1. when first start of the astrovim

2. nvim file.lua

### Expected behavior

Syntax highlighting with *.lua files

### Screenshots

<img width="1440" alt="Screen" src="https://user-images.githubusercontent.com/101626426/226187162-36cd7381-2c73-467e-8776-70f1a0a079b5.png">

**Comment by mehalter** [comment]
You need to reinstall your `lua` treesitter parser with `:TSInstall lua`
