### ISSUE TITLE
multiple mappings.lua files

### ISSUE THREAD

**Issue by kraxli** [AstroNvim/AstroNvim#1679]
### Is your feature related to a problem?

No

### Describe the new feature

I have many mappings and would like to order them in multiple `mappings.lua`-files. 
E.g. 
```
~/.config/astronvim/lua/user/mappings_1.lua
~/.config/astronvim/lua/user/mappings_2.lua
```

or a folder `~/.config/astronvim/lua/user/mappings` with different files.

Could this be supported?

Thanks for the great work!

**Comment by mehalter** [comment]
You can do this with some amount of Lua programming with either `user/mappings.lua` paired with  files such as `user/mappings_1.lua`/`user/mappings_2.lua` or with `user/mappings.lua` pairs with files such as `user/mappings/mappings_1.lua`/`user/mappings/mappings_2.lua`

You will just need to make some sort of logic in your `user/mappings.lua` file to merge together your tables from the other files. But they can be accessed with `require("user.mappings_1")`/`require("user.mappings_2")` or `require("user.mappings.mappings_1")`/`require("user.mappings.mappings_2")`


If you put the files in `user/mappings/mappings_{1,2}.lua` this would be a simple example of what a `user/mappings.lua`  file could look like:

```lua
local mappings = {}

local extend_tbl = require("astronvim.utils").extend_tbl

local mapping_prefix = "user.mappings."

for _, file in ipairs {
  "mappings_1",
  "mappings_2",
} do
  mappings = extend_tbl(mappings, require(mapping_prefix .. file))
end

return mappings
```
