### ISSUE TITLE
Icons not working

### ISSUE THREAD

**Issue by thatsayon** [AstroNvim/AstroNvim#1685]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

kali linux 2023.1

### Terminal/GUI

zsh

## AstroNvim 
AstroNvim Version: v3.5.0
Neovim Version: v0.8.3

### Describe the bug

I installed astro nvim on my system. All things are working very well but the icons are not working. I tried to fix the problem but I failed. How can I fix that? 

### Steps to Reproduce

1. Open 'Astro Nvim'
2. Open a new project or folder 
3. Icons are not showing 

### Expected behavior

Icons should working properly

### Screenshots

![image](https://user-images.githubusercontent.com/75683770/226866529-ad2cdfa4-0c5e-4a2d-8a72-290757c82958.png)

**Comment by mehalter** [comment]
If you have questions about nerd fonts feel free to check out the Discord! https://discord.gg/astronvim
