### ISSUE TITLE
telescope-fzf-native requires manual build

### ISSUE THREAD

**Issue by willparsons** [AstroNvim/AstroNvim#1689]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Windows 11 22H2

### Terminal/GUI

Windows Terminal

## AstroNvim
  - INFO: AstroNvim Version: v3.5.1
  - INFO: Neovim Version: v0.8.3
  - OK: Using stable Neovim >= 0.8.0
  - OK: `git` is installed: Used for core functionality such as updater and plugin management
  - OK: `explorer` is installed: Used for `gx` mapping for opening files with system opener (Optional)
  - OK: `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
  - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
  - WARNING: `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
  - WARNING: `btm` is not installed: Used for mappings to pull up system monitor (Optional)
  - OK: `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

I installed AstroNvim before setting up make/gcc, so when it tried to build telescope-fzf-native it failed. Then when opening neovim it would always say that the configuration failed for telescope-fzf-native since it doesn't exist.

I then installed gcc and make but it still would not build telescope-fzf-native, so I had to manually delete the build folder and call make to fix it.

### Steps to Reproduce

1. Setup Neovim + AstroNvim before gcc and make
2. See that telescope-fzf-native configuration fails
3. Install gcc+make
4. See that telescope-fzf-native configuration still fails

### Expected behavior

After installing gcc and make it should be able to build itself.

**Comment by mehalter** [comment]
This is a limitation of the plugins ecosystem of Neovim and lazy. This could maybe be a feature request on lazy.nvim but idk how it would work for them or how viable it would be.
