### ISSUE TITLE
To suppress hit-enter prompt

### ISSUE THREAD

**Issue by daiyanze** [AstroNvim/AstroNvim#1692]
### Is your feature related to a problem?

I've been encountering hit-enter prompts frequently when

- opening up a new file that hasn't been opened for a while (maybe after OS restart?)
- toggle term horizontally / vertically with a new session

<img width="1915" alt="Screenshot 2023-03-24 at 10 34 32" src="https://user-images.githubusercontent.com/14920529/227407919-a4fe34cc-d49e-4748-a8c4-35ad2c4da1a0.png">

### Describe the new feature

Disable / suppress the hit-enter prompt.

**Comment by mehalter** [comment]
Can you replicate this without a user configuration? I'm guessing this is coming from some sort of plugin in your configuration that doesn't have good `cmdheight = 0` support. Or you are using a version of Neovim <0.8.3. What version of Neovim are you using?

**Comment by daiyanze** [comment]
@mehalter 
Oh, right... It's the version thing, my Neovim was 0.8.1. I upgraded to 0.8.3 and the issue was gone.
Thank you so much!!!
