### ISSUE TITLE
[feature-request] add plugin `folke/noice.nvim` on the next major release

### ISSUE THREAD

**Issue by Clumsy-Coder** [AstroNvim/AstroNvim#1696]
### Is your feature related to a problem?

Adding better ui libraries for neovim. Makes Neovim look more polished

![noice.nvim screenshot](https://user-images.githubusercontent.com/292349/193263220-791847b2-516c-4f23-9802-31dd6bec5f6a.png)

![noice.nvim cmdline](https://user-images.githubusercontent.com/292349/193823421-05ca391a-aa31-4ede-b3e0-f27bc74cec7e.png)

![noice.nvim dialog](https://user-images.githubusercontent.com/292349/197199576-ff8e94a8-9293-42e9-ae42-8288e9b690b4.png)

![image](https://user-images.githubusercontent.com/19594044/227748179-402e93ae-48c7-4361-9084-b7240e5e4e86.png)

check https://github.com/folke/noice.nvim

---

Better to add it on the next major release because there are some default configs from this plugin that will interfere with the current plugins installed on Astronvim v3 (Ex: lsp, statusline).

It will take some time to play with the configs that work well with Astronvim v3

### Describe the new feature

Add Neovim plugin `folke/noice.nvim` on the next major release

### Additional context

this is the current config I have currently to work with Astronvim v3

#### `./plugins/noice/init.lua`
```lua
return {
  "folke/noice.nvim",
  event = "VeryLazy",
  opts = {
    presets = {
      bottom_search = true,         -- use a classic bottom cmdline for search
      -- command_palette = true, -- position the cmdline and popupmenu together
      long_message_to_split = true, -- long messages will be sent to a split
    },
    cmdline = {
      enabled = true,
    },
    lsp = {
      progress = { enabled = false },
      hover = { enabled = false },
      signature = { enabled = false },
      message = { enabled = false },
      -- override markdown rendering so that **cmp** and other plugins use **Treesitter**
      override = {
        ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
        ["vim.lsp.util.stylize_markdown"] = true,
        ["cmp.entry.get_documentation"] = true,
      },
    },
    -- routes
    routes = {
      -- show recording messages
      -- obtained from
      --   https://github.com/folke/noice.nvim/wiki/Configuration-Recipes#show-recording-messages
      {
        view = "notify",
        filter = {
          event = "msg_showmode",
        },
      },
    },
    -- views
    views = {
      -- view cmdline and popupmenu together
      -- obtained from
      --   https://github.com/folke/noice.nvim/wiki/Configuration-Recipes#display-the-cmdline-and-popupmenu-together
      cmdline_popup = {
        position = {
          row = "50%",
          col = "50%",
        },
        size = {
          width = 60,
          height = "auto",
        },
      },
      popupmenu = {
        relative = "editor",
        position = {
          row = "66%",
          col = "50%",
        },
        size = {
          width = 60,
          height = 10,
        },
        border = {
          style = "rounded",
          padding = { 0, 1 },
        },
        win_options = {
          winhighlight = { Normal = "Normal", FloatBorder = "DiagnosticInfo" },
        },
      },
    },
  },
  config = function(_, opts)
    require("noice").setup(opts)
  end,
}

```

**Comment by mehalter** [comment]
This is not an aesthetic move at want to do, but feel free to add it to your config! It's also available in astrocommunity for easy addition

**Comment by Clumsy-Coder** [comment]
I didn't know you had it in AstroNvim/AstroCommunity repo. This makes it easier

Thanks
