### ISSUE TITLE
mason now uses "mason-org/mason-registry" to lookup Lsp packages, existing Lsp packages will fail to update on latest mason.nvim

### ISSUE THREAD

**Issue by Stephen-Seo** [AstroNvim/AstroNvim#1702]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

ArchLinux

### Terminal/GUI

Alacritty

### AstroNvim Health

    astronvim: require("astronvim.health").check()
    ========================================================================
    ## AstroNvim
      - INFO: AstroNvim Version: v3.5.3
      - INFO: Neovim Version: v0.8.3
      - OK: Using stable Neovim >= 0.8.0
      - OK: `git` is installed: Used for core functionality such as updater and plugin management
      - OK: `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
      - WARNING: `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
      - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
      - WARNING: `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
      - WARNING: `btm` is not installed: Used for mappings to pull up system monitor (Optional)
      - OK: `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Unable to update `rust-analyzer` Lsp server.

Upon some research, I've found that mason.nvim is migrating Lsp server registries to a separate plugin: https://github.com/williamboman/mason.nvim/commit/dee830887857a002681026e99ddf5a32751abd19#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R149

I think the fix would be to add the separate plugin as an additional mason dependency: https://github.com/mason-org/mason-registry

### Steps to Reproduce

1. :AstroUpdate
2. :AstroUpdatePackages

Lsp server `rust_analyzer` fails to update or isn't found by mason.

### Expected behavior

Lsp server `rust_analyzer` should be properly detected and updated by mason.nvim.

**Comment by mehalter** [comment]
https://github.com/AstroNvim/AstroNvim/commit/17e08b0441719accafd04ca2f2eabd266369ad13

This is actually handled.

**Comment by mehalter** [comment]
While this migration is happening, stable AstroNvim pins plugins to known working commits. After the migration they are going to switch mason to using semantic versioning. You can either use nightly AstroNvim or unpin the plugin of mason.nvim to make sure you get the latest updates from mason.nvim for now.

**Comment by Stephen-Seo** [comment]
Setting AstroNvim to use "nightly" didn't fix it for me, so I just downgraded the `mason.nvim` to the commit before it removed the `rust_analyzer` registry info as a workaround for now.
