### ISSUE TITLE
Document how to add null-ls formatting source

### ISSUE THREAD

**Issue by oryband** [AstroNvim/AstroNvim#1703]
### Is your feature related to a problem?

I'm trying to add a new null-ls formatter but it overrides the existing formatters and practically disables everything else. How can I just add this new formatter in addition to the existing ones?
```lua
plugins = {
  {
      "jose-elias-alvarez/null-ls.nvim",
      config = function(config)
        local null_ls = require "null-ls"
        config.sources = { null_ls.builtins.formatting.zprint }
        return config
      end,
   },
}
```

### Describe the new feature

Document how to do that.

**Comment by oryband** [comment]
> can you share your user configuration? How have you installed and set up black?

It's not just black - it's every formatter. For example I also have `jq` installed for JSON. I'm using the default configuration for all formatters (except for the custom one i'm trying to add called `zprint` for clojure): https://github.com/oryband/dotfiles/blob/76127e14e6838071c817f867500ae0ae38a5d53a/.config/nvim/lua/user/init.lua

**Comment by mehalter** [comment]
Ahhhhh I see what's going on here. You have not set up your plugin options correctly so `mason-null-ls` is not being set up to auto install formatters. You actually don't need to manually set up `zprint` in this case either if you jsut fix your plugin definitions. Here is a fix up version of your `mason-null-ls.nvim` specification:

```lua
    {
      "jay-babu/mason-null-ls.nvim",
      opts = {
        ensure_installed = { "black", "jq", "stylua", "zprint" },
      },
    },
```

you can go ahead and remove your `null-ls` configuration here.

**Comment by mehalter** [comment]
Also just to clarify for anyone else stumbling across this. `mason-null-ls` does not override the configuration table of `null-ls` so setting the configuration table in `null-ls` will not override things set up in `mason-null-ls`. `mason-null-ls` does not add sources through the setup function and rather through direct API calls.

**Comment by oryband** [comment]
Thank you, it works!
