### ISSUE TITLE
Telescope shows oldfiles that I didn't search

### ISSUE THREAD

**Issue by Ezaju** [AstroNvim/AstroNvim#1712]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.3

### Terminal/GUI

Alacritty 

## AstroNvim
​ ​  - INFO: AstroNvim Version: v3­.5.4
​  ​ - INFO: Neovim Version: v0.8.3
​ ​  - OK: Usi­ng stable Neovim >= 0.8.0
​ ​ ​ - OK: `gi­t` is installed: Used for core functiona­lity such as updater and plugin manageme­nt
​ ​ ​ - OK: `op­en` is installed: Us­ed for `gx` mapping for opening files wi­th system opener (Op­tional)
​ ​ ​ - WARNING: `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
​ ​ ​ - OK: `no­de` is installed: Us­ed for mappings to pull up node REPL (Op­tional)
​ ​ ​ - WARNING: `gdu` is not insta­lled: Used for mappi­ngs to pull up disk usage analyzer (Opti­onal)
​ ​ ​ - WARNING: `btm` is not insta­lled: Used for mappi­ngs to pull up system monitor (Optional)
​ ​ ​ - OK: `py­thon3` is installed: Used for mappings to pull up python REPL (Optional)
​

### Describe the bug

After I opened some files and worked there, in oldfiles (<leader> f o) I see files that I didn't search. 

### Steps to Reproduce

1. Open python file
2. Work there
3. <leader> f o
4. See files that I didn't search ( As I know they are documents of pyright lsp)

### Expected behavior

'<leader> f o' must show me files that I search

### Screenshots

<img width="666" alt="Issue_telescope" src="https://user-images.githubusercontent.com/129344418/228699646-d16ce020-902b-4a47-8c73-32ac9a44530f.png">

**Comment by mehalter** [comment]
This would be a bug in telescope

**Comment by Ezaju** [comment]
"This is certainly an AstroVim/configuration issue.
Recommend you open a ticket there."
Telescope developer said that this problem is AstroNvim configuration issue.
I can agree, because in NvChad I don't have this problem. But for me Astro is the best.

**Comment by mehalter** [comment]
Here is  a test session:

A fresh installation of AstroNvim cleaning `data`/`state`/`cache` files  and then running `<leader>fo`:
![2023-03-30_15:28:55_screenshot](https://user-images.githubusercontent.com/1591837/228943660-086fcfb3-93c9-4c7d-b985-7cd73a1a920f.png)

Opening a `test.py` file and running `<leader>fo`:

![2023-03-30_15:29:53_screenshot](https://user-images.githubusercontent.com/1591837/228943840-f8cbc49d-d4da-4355-a995-29f11dd2efee.png)

Quitting  the editor, just running `nvim` and doing `<leader>fo`:


![2023-03-30_15:30:44_screenshot](https://user-images.githubusercontent.com/1591837/228943958-a4f9b899-7ef4-4564-88d4-d7839be1a86f.png)

Quitting the editor, reopening it with a different file `hello.c`, and running `<leader>fo`:

![2023-03-30_15:31:25_screenshot](https://user-images.githubusercontent.com/1591837/228944079-cf27cb71-345c-46a7-bab8-7d0ae21331fb.png)

Quitting and re running `nvim` and doing `<leader>fo`:

![2023-03-30_15:31:56_screenshot](https://user-images.githubusercontent.com/1591837/228944194-4457ea7d-34ed-4648-83f1-25ff0efdf983.png)


Hopefully this shows that this isn't a bug in AstroNvim.

**Comment by mehalter** [comment]
I have also tested this with python language servers running and clangd running and do not see any artifacts coming from them either.

**Comment by mehalter** [comment]
Also @Ezaju this might be a misunderstanding of what the function `oldfiles` actually does. You mention that you think it's supposed to show you files that you previously searched for and opened, but this function actually shows you  all of the files you have opened previously. It could be that when you were developing you used the python language server to look at the definition of an internal method and it opened a file to show you the definition. This file would then show up in `oldfiles`. It has no dependency on things that you searched for with Telescope. Simply just all of the files previously opened.

**Comment by Ezaju** [comment]
Thanks. I understood.
