### ISSUE TITLE
Unable to install Python language parsing

### ISSUE THREAD

**Issue by sergeant-savage** [AstroNvim/AstroNvim#1713]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Fedora 37

### Terminal/GUI

gnome-terminal

## AstroNvim
 - INFO: AstroNvim Version: v3.5.4
 - INFO: Neovim Version: v0.8.3
 - OK: Using stable Neovim >= 0.8.0
 - OK: `git` is installed: Used for core functionality such as updater and plugin management
 - OK: `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
 - WARNING: `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
 - WARNING: `node` is not installed: Used for mappings to pull up node REPL (Optional)
 - WARNING: `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
 - WARNING: `btm` is not installed: Used for mappings to pull up system monitor (Optional)
 - OK: `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

A compilation error occurs when trying to install Python language parsing

### Steps to Reproduce

1.  Open AstroNvim
2. Run `:TSInstall python`

### Expected behavior

I expected Python language parsing to be installed without issue

### Screenshots

![image](https://user-images.githubusercontent.com/63070761/228715429-820d9475-acd0-43fb-a19c-88c538842e3e.png)

### Additional Context

This is after a clean install on Fedora 37

**Comment by mehalter** [comment]
Looks like it might require `cclplus` to be install on your machine. Not sure what that is, but this should be opened on Mason.nvim's repo and not here since we do not handle anything regarding package installation.

**Comment by sergeant-savage** [comment]
Ok, thank you for the assistance.
