### ISSUE TITLE
Failed Packages (Plenary & Promise-Async)

### ISSUE THREAD

**Issue by john-okeefe** [AstroNvim/AstroNvim#1716]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Arch Linux/WSL2 - Alpine/WSL1 - Alpine

### Terminal/GUI

wezterm/cmdr

### AstroNvim Health

astronvim: require("astronvim.health").check()
========================================================================
## AstroNvim
  - INFO: AstroNvim Version: v3.6.0
  - INFO: Neovim Version: v0.8.3
  - OK: Using stable Neovim >= 0.8.0
  - OK: `git` is installed: Used for core functionality such as updater and plugin management
  - OK: `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
  - OK: `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
  - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
  - OK: `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
  - OK: `btm` is installed: Used for mappings to pull up system monitor (Optional)
  - OK: `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

I've tried this on multiple Linux installs and different terminals. This is a fresh install of AstroNvim with clean nvim directories across the board. I've installed all dependencies including the optional ones and it looks like two packages are failing out of the gate. The first one is concerning being it's a dependency package for other packages included.

The screenshot below is after running :Lazy check. That's why the timing says Loaded and not Installed.

`
Failed (2)
    ○ plenary.nvim
        fatal: ambiguous argument '253d34830709d690f013daf2853a9d21ad7accab..^0.1': unknown revision or path not in the working tree.
        Use '--' to separate paths from revisions, like this:
        'git <command> [<revision>...] -- [<file>...]'
    ○ promise-async   nvim-ufo
        fatal: ambiguous argument '7fa127fa80e7d4d447e0e2c78e99af4355f4247b..^1': unknown revision or path not in the working tree.
        Use '--' to separate paths from revisions, like this:
        'git <command> [<revision>...] -- [<file>...]'
`

### Steps to Reproduce

1. Install all recommended and optional dependencies.
2. Follow instructions on Quick Start guide to clear out nvim folders and install Astrovim.
3. Start nvim and watch plugins get installed and see error message above.

### Expected behavior

Clean installs should not have errors out of the gate.

### Screenshots

![image](https://user-images.githubusercontent.com/5943635/228886223-9fe0db7a-2121-486f-8f98-e859ba427f06.png)

**Comment by IvanProg00** [comment]
Yeah, I have the same error.

**Comment by mehalter** [comment]
Sorry! Will fix soon!
