### ISSUE TITLE
Treesitter highlighter errors

### ISSUE THREAD

**Issue by DeeGeeMan** [AstroNvim/AstroNvim#1722]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

13.2.1

### Terminal/GUI

alacritty 0.12.0

### AstroNvim Health

astronvim: require("astronvim.health").check()
    2 ========================================================================
    3 ## AstroNvim
    4   - INFO: AstroNvim Version: v3.7.0
    5   - INFO: Neovim Version: v0.8.3
    6   - OK: Using stable Neovim >= 0.8.0
    7   - OK: `git` is installed: Used for core functionality such as updater and plugin management
    8   - OK: `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
    9   - OK: `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
   10   - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
   11   - OK: `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
   12   - OK: `btm` is installed: Used for mappings to pull up system monitor (Optional)
   13   - OK: `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Getting errors treesitter when opening the `~/.config/nvim/init.lua` on a clean macOS.  I also get an error when searching for a file from the main dashboard.

### Steps to Reproduce

Follow the steps in [Getting Started](https://astronvim.com/).

### Expected behavior

No errors and the correct color style is displayed.

### Screenshots

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/21670040/229370976-1214bcb6-e791-4e6b-ac79-8e65afb4d2ac.png">

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/21670040/229371351-69d794c5-15a0-45fe-a173-aa4d9f40f4cf.png">

### Additional Context

I've also verified the issue in a clean virtual machine using [Parallels](https://www.parallels.com/).

**Comment by mehalter** [comment]
Looks like you had issues building telescope fzf. Make sure you have a c compiler installed and make as these are requirements for AstroNvim. The first screenshot looks like you just need to reinstall your Lua treesitter parsers with `:TSInstall lua`

**Comment by DeeGeeMan** [comment]
Shouldn't it be listed as a requirement in the [Getting Started](https://astronvim.com/)?
