### ISSUE TITLE
Python Dap mappings conflict.

### ISSUE THREAD

**Issue by seancraven** [AstroNvim/AstroNvim#1725]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Ubuntu 22.04

### Terminal/GUI

bash

### AstroNvim Health

   - INFO: AstroNvim Version: v3.7.0
  5   - INFO: Neovim Version: v0.8.3
  6   - OK: Using stable Neovim >= 0.8.0
  7   - OK: `git` is installed: Used for core functionality such as updater and plugin management
  8   - OK: `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
  9   - WARNING: `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
 10   - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
 11   - OK: `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
 12   - OK: `btm` is installed: Used for mappings to pull up system monitor (Optional)
 13   - OK: `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Hi Astro Team,

I am a new user of Neovim and I don't know if this is my fault. 
I cloned the AstroNvim repo as detailed in the instructions and made my own user config, as shown in the docs. I have tried reinstalling all mason plugins and lazy plugins. 

I believe that there is some conflict with mapping in the default settings.

```bash
5108: Error executing lua: /home/sean/.local/share/nvim/lazy/nvim-dap/lua/dap.lua:484: ...sean/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1283: adapter.command must not be
 empty. Got: {
  command = "",
  type = "executable"
}
stack traceback:
        [C]: in function 'trigger_run'
        /home/sean/.local/share/nvim/lazy/nvim-dap/lua/dap.lua:484: in function 'run'
        /home/sean/.local/share/nvim/lazy/nvim-dap/lua/dap.lua:404: in function 'cb'
        /home/sean/.local/share/nvim/lazy/nvim-dap/lua/dap/ui.lua:34: in function 'pick_if_many'
        /home/sean/.local/share/nvim/lazy/nvim-dap/lua/dap.lua:398: in function 'select_config_and_run'
        /home/sean/.local/share/nvim/lazy/nvim-dap/lua/dap.lua:861: in function 'continue'  
        /home/sean/.config/nvim/lua/astronvim/mappings.lua:312: in function </home/sean/.config/nvim/lua/astronvim/mappings.lua:312>                
Press ENTER or type command to continue
```

my .config/lua/astronvim/mappings.lua lines 308::
```lua

if is_available "nvim-dap" then
  maps.n["<leader>d"] = sections.d
  -- modified function keys found with `showkey -a` in the terminal to get key code
  -- run `nvim -V3log +quit` and search through the "Terminal info" in the `log` file for the correct keyname
  maps.n["<F5>"] = { function() require("dap").continue() end, desc = "Debugger: Start" }
  maps.n["<F17>"] = { function() require("dap").terminate() end, desc = "Debugger: Stop" } -- Shift+F5
  maps.n["<F29>"] = { function() require("dap").restart_frame() end, desc = "Debugger: Restart" } -- Control+F5
  maps.n["<F6>"] = { function() require("dap").pause() end, desc = "Debugger: Pause" }
  maps.n["<F9>"] = { function() require("dap").toggle_breakpoint() end, desc = "Debugger: Toggle Breakpoint" }
  maps.n["<F10>"] = { function() require("dap").step_over() end, desc = "Debugger: Step Over" }
  maps.n["<F11>"] = { function() require("dap").step_into() end, desc = "Debugger: Step Into" }
  maps.n["<F23>"] = { function() require("dap").step_out() end, desc = "Debugger: Step Out" } -- Shift+F11
  maps.n["<leader>db"] = { function() require("dap").toggle_breakpoint() end, desc = "Toggle Breakpoint (F9)" }
  maps.n["<leader>dB"] = { function() require("dap").clear_breakpoints() end, desc = "Clear Breakpoints" }
  maps.n["<leader>dc"] = { function() require("dap").continue() end, desc = "Start/Continue (F5)" }
  maps.n["<leader>di"] = { function() require("dap").step_into() end, desc = "Step Into (F11)" }
  maps.n["<leader>do"] = { function() require("dap").step_over() end, desc = "Step Over (F10)" }
  maps.n["<leader>dO"] = { function() require("dap").step_out() end, desc = "Step Out (S-F11)" }
  maps.n["<leader>dq"] = { function() require("dap").close() end, desc = "Close Session" }
  maps.n["<leader>dQ"] = { function() require("dap").terminate() end, desc = "Terminate Session (S-F5)" }
  maps.n["<leader>dp"] = { function() require("dap").pause() end, desc = "Pause (F6)" }
  maps.n["<leader>dr"] = { function() require("dap").restart_frame() end, desc = "Restart (C-F5)" }
  maps.n["<leader>dR"] = { function() require("dap").repl.toggle() end, desc = "Toggle REPL" }
  if is_available "nvim-dap-ui" then
    maps.n["<leader>du"] = { function() require("dapui").toggle() end, desc = "Toggle Debugger UI" }
    maps.n["<leader>dh"] = { function() require("dap.ui.widgets").hover() end, desc = "Debugger Hover" }
  end
end
```

### Steps to Reproduce

1. Clone AstroNvim base repo. 
2. Clone lua/user template
3. In neovim :DapInstall python (I also installed pyright, pylint and black for python.)
5. press F9 in a python file to make a breakpoint
6. press F5 to start debugger
7. Error occurs. 

### Expected behavior

The debugger to launch.

### Additional Context

I have also added PATH="append" to user/plugins/mason.lua
like so:
```lua
  { "williamboman/mason.nvim", opts = { PATH = "append" } },
```

**Comment by mehalter** [comment]
Can you please share your user configuration and I can help you debug? There is no issue with the core mappings in this case. It looks like your DAP is misconfigured.

**Comment by seancraven** [comment]
Hi. 
Thanks so much for the help this: https://github.com/seancraven/astronvim, I have only made one commit past the cloning of the repo, and I have no git diff between me and the astrovim repo, outside of users.

**Comment by mehalter** [comment]
This is a bug in mason-registry. I have opened a fix for this: https://github.com/mason-org/mason-registry/pull/1056

**Comment by rafaelbdb** [comment]
A bit off-topic, but...:

"<F17>", "<F23>", "<F29>" ?? 
That's one of the weirdest things I ever saw...

It's almost impossible to guess that you have to use "<Shift>" with F-buttons to get such results (and the <SPACE> help doesn't mention it!), specially for noobs.

I recommend that to be changed to the respective <S-Fx>.

**Comment by mehalter** [comment]
@rafaelbdb you cannot use `S-Fx` to get these bindings. This is also why we describe the function notation in the other mapping text. Please be sure to read the comment in the code alongside those mappings that describes all of this. It's there to avoid the confusion you are having :)
