### ISSUE TITLE
Additional cmp Sources not working

### ISSUE THREAD

**Issue by lukeemhigh** [AstroNvim/AstroNvim#1732]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Ubuntu 22.04 (WSL2)

### Terminal/GUI

Windows terminal

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.7.2
- Neovim Version: v0.8.3
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

I added "Saecki/crates.nvim" to the cmp sources in my `user/plugins/user.lua` following the guidelines if found in the documentation here: https://astronvim.com/Recipes/cmp#add-more-sources

The resultiing code in my `user/plugins/user.lua` file looks like this:

```lua
return {
  {
    "hrsh7th/nvim-cmp",
    dependencies = {
      "Saecki/crates.nvim",
      after = { "nvim-cmp" },
      config = function()
        require("crates").setup {
          popup = {
            autofocus = true,
            border = "rounded",
          },
        }
      end,
    },
    opts = function(_, opts)
      local cmp = require "cmp"
      opts.sources = cmp.config.sources {
        { name = "nvim_lsp", priority = 1000 },
        { name = "luasnip", priority = 750 },
        { name = "buffer", priority = 500 },
        { name = "path", priority = 250 },
        { name = "crates", priority = 1100 },
      }
      return opts
    end,
  },
}
```
The plugin is working "per se", meaning that I can toggle on and off its functionalities outside of cmp and all are working properly, including the popup settings that I set up in the code above.
The only feature not behaving properly is cmp completion, meaning that the cmp completion window does not show any "crates" suggestion.

Here's a screenshot of cmp completion menu

![immagine](https://user-images.githubusercontent.com/113122350/229638761-fa6176eb-b919-447d-84f6-76fde293ae9b.png)

Here's some screenshots of the other plugin functionalities (working)

![immagine](https://user-images.githubusercontent.com/113122350/229639021-cf3b1c70-255d-4904-b290-1c6781276e24.png)

![immagine](https://user-images.githubusercontent.com/113122350/229639105-b66f123f-dcb4-4c28-9df5-80e6a9e4fdd6.png)

![immagine](https://user-images.githubusercontent.com/113122350/229639220-81a4e4c3-68cc-4561-8c87-e0f71fbaee44.png)

![immagine](https://user-images.githubusercontent.com/113122350/229639323-92ea6bed-72ea-4042-8789-49b6be075e8c.png)

### Steps to Reproduce

1. Install the plugin and add it to cmp sources
2. Open a Cargo.toml file and start typing

### Expected behavior

cmp completion should show "crates" suggestions when a Cargo.toml file is open.

### Additional Context

I suspect this depends on the function used to override default cmp config, but I may be completely off road.

**Comment by mehalter** [comment]
There is no `after` keyword. Take a look at the lazy docs and make sure the plugins are loaded in the appropriate order. Take a look at the rust pack in AstroCommunity to see the correct way to implement this.

**Comment by lukeemhigh** [comment]
I'm sorry for the bug report. It should have been a question from the start, really. 

I reconfigured the plugin following what I found in the AstroCommunity rust pack, but still, I don't get any cmp completion (at all this time) in a `Cargo.toml` file.

My `user/plugins/user.lua` file now looks like this

```lua
return {
  {
    "Saecki/crates.nvim",
    event = { "BufRead Cargo.toml" },
    opts = {
      null_ls = {
        enabled = true,
        name = "crates.nvim",
      },
      popup = {
        autofocus = true,
        border = "rounded",
      },
    },
    init = function()
      vim.api.nvim_create_autocmd("BufRead", {
        group = vim.api.nvim_create_augroup("CmpSourceCargo", { clear = true }),
        pattern = "Cargo.toml",
        callback = function()
          require("cmp").setup.buffer { sources = {{ name = "crates" }} }
          require "crates"
        end,
      })
    end,
  },
}
```
Do you have any other clue?

**Comment by mehalter** [comment]
You can use something like `:CmpStatus` to help you start debugging what might be going on. I would definitely recommend joining the Discord. I don't use rust so I haven't configured these plugins in depth, but there are a lot of community members there that use these things.
