### ISSUE TITLE
Unable to overwrite keymap group (<leader>u)

### ISSUE THREAD

**Issue by praveenperera** [AstroNvim/AstroNvim#1734]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.3

### Terminal/GUI

Alacritty

## AstroNvim
 INFO: AstroNvim Version: v3.2.1
 INFO: Neovim Version: v0.8.3
 OK: Using stable Neovim >= 0.8.0
 OK: `git` is installed: Used for core functionality such as updater and plugin management
 OK: `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
 OK: `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
 OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
 OK: `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
 OK: `btm` is installed: Used for mappings to pull up system monitor (Optional)
 OK: `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

I'm trying to overwrite `leader u` to toggle undo tree. Overwriting individual existing commands seems to work. But I can't seem to make `leader u` overwrite. I'm assuming this is because leader u is a prefix group and not a single command?

Linked below is my init.lua of what I've tried. I tried setting it again in the polish section too. That also did not work. 

https://github.com/praveenperera/dotfiles/commit/faaee11885ce61a28ac85dc8150af236754d236b

### Steps to Reproduce

Add `["<leader>u"] = { vim.cmd.UndotreeToggle, desc = "Undo tree" },` to keymap.

Or use my init.lua file: https://github.com/praveenperera/dotfiles/blob/faaee11885ce61a28ac85dc8150af236754d236b/nvim/init.lua

### Expected behavior

Leader u to toggle undo tree and not go to the UI section on which-key

**Comment by praveenperera** [comment]
Changed to: `			["<leader>u"] = { vim.cmd.UndotreeToggle, desc = "Undo tree", name = false },`

On load I get

```
Error detected while processing /Users/praveen/.config/nvim/init.lua:
Failed to load astronvim.mappings

vim/keymap.lua:0: invalid key: name
```

**Comment by mehalter** [comment]
ah yes, I see I remember now. I did improve this before to make this easier and I totally forgot how I did it :joy: the way you did it the first time definitely should work with the fix I did previously hehe

**Comment by praveenperera** [comment]
@mehalter I updated to 3.8 and tried it again but leader u still launches into the UI prefix group.

Interestingly, I think if I do `<leader>u` quickly it will bring up the undotree, but if wait for which-key to pop up it won't work. See video below.


https://user-images.githubusercontent.com/1775346/229856907-5a1dd4d6-32eb-4334-9e92-ed1fd1d8a89b.mov

**Comment by mehalter** [comment]
Yeah that will be normal which-key behavior. If you do the binding before the menu pops up then it will work. Once the menu pops up then it will navigate. You will need to unmap all of the UI mappings to achieve what you want.

**Comment by praveenperera** [comment]
Any ideas on a easy way to unset these from which-key?

**Comment by mehalter** [comment]
You just need to remove these mappings from your mapping table @praveenperera

**Comment by praveenperera** [comment]
In my mappings table there is nothing mapped  with `<leader>u`, I remapped all the UI ones to `<leader>U`, which key seems to be picking up the default mappings.

**Comment by mehalter** [comment]
I looked at your dotfiles and there is nowhere where you remove all of the `<leader>u` mappings. I see where you make your own new `<leader>U` mappings, but you never actually remove the original `<leader>u` mappings.

**Comment by praveenperera** [comment]
Ah i see what you mean, i mapped them all to `<nop>` works as I want now. Thanks!

**Comment by praveenperera** [comment]
@mehalter do you think it would be a good feature to add the ability to easily unmap default mappings?

https://www.lunarvim.org/docs/configuration/keybindings#removing-default-mappings

**Comment by mehalter** [comment]
I haven't seen that page before in the lunarvim docs! It's your lucky day though because that's exactly how it works in AstroNvim :) Just set the table entry to `false` and away you go :D !
