### ISSUE TITLE
LazyGit run in AstroNvim is not respecting the config file

### ISSUE THREAD

**Issue by dkvasnicka** [AstroNvim/AstroNvim#1738]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Linux 6.1.22-1-lts (EndeavourOS/Arch)

### Terminal/GUI

xfce4-terminal

### AstroNvim Health

```
astronvim: require("astronvim.health").check()
========================================================================
## AstroNvim
  - INFO: AstroNvim Version: v3.7.2
  - INFO: Neovim Version: v0.8.3
  - OK: Using stable Neovim >= 0.8.0
  - OK: `git` is installed: Used for core functionality such as updater and plugin management
  - OK: `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
  - OK: `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
  - WARNING: `node` is not installed: Used for mappings to pull up node REPL (Optional)
  - WARNING: `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
  - WARNING: `btm` is not installed: Used for mappings to pull up system monitor (Optional)
  - OK: `python` is installed: Used for mappings to pull up python REPL (Optional)
```

### Describe the bug

I have different colors defined in the official lazygit config file `~/.config/lazygit/config.yml`
When LG is run directly in terminal everything works, when it's invoked from inside AstroNvim the colors are not being observed.

```
cat ~/.config/lazygit/config.yml 

gui:
  theme:
    lightTheme: true
    activeBorderColor:
      - black
      - bold
    inactiveBorderColor:
      - black
    selectedLineBgColor:
      - default
    defaultFgColor:
      - black
```

### Steps to Reproduce

1. Use the above lazygit config
2. Open nvim in a git repo
3. Open LazyGit inside/outside nvim and compare

### Expected behavior

Colors are the same regardless of where lazygit is run.

**Comment by mehalter** [comment]
Lazygit actually is using the configuration function correctly. The difference is some themes (including Astrotheme) do set terminal colors to match the theme. So the colors could be different for sure. But I have tested this and the configuration file is being loaded correctly.

**Comment by dkvasnicka** [comment]
@nikolasetiawan Thanks for the tip. It's not solving the issue though, probably because it's pointing LG to a dir that's already default anyway.
As @mehalter suggests, color theme might be the issue here. I'm using `ishan9299/nvim-solarized-lua`. But with LG colors set explicitly to `black` in places I don't really know how text could end up very light gray on the yellow Solarized bg... :shrug:
