### ISSUE TITLE
Bugged Terminal Output: Extra spaces/tabs on every newline

### ISSUE THREAD

**Issue by 3chospirits** [AstroNvim/AstroNvim#1740]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.2.1

### Terminal/GUI

iTerm2

## AstroNvim
  - INFO: AstroNvim Version: v3.8.0
  - INFO: Neovim Version: v0.8.0
  - OK: Using stable Neovim >= 0.8.0
  - OK: `git` is installed: Used for core functionality such as updater and plugin management
  - OK: `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
  - WARNING: `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
  - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
  - WARNING: `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
  - WARNING: `btm` is not installed: Used for mappings to pull up system monitor (Optional)
  - OK: `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

terminal seems to be adding weird indentation on every newline.

### Steps to Reproduce

1. Open astrovim
2. Open horizontal or vertical terminal (`<leader>th` or `<leader>tv` as default mapping)
3. Run a command with outputs that have new lines. For example, `echo 1 & echo 2 & echo 3`
4. Observe bugged output

### Expected behavior

Output of example should look something like this in normal terminal
```sh
3cho@3cho ~ % echo 1 & echo 2 & echo 3
[1] 35546
1
[2] 35547
2
[1]  - done       echo 1
3
3cho@3cho ~ %
[2]  + done       echo 2
3cho@3cho ~ %
```

### Screenshots

Output looks like this for the given example of echos
```sh
3cho@3cho test % echo 1 & echo 2 & echo 3
[1] 35183
         1
          [2] 35184
                   2
                    [1]  - done       echo 1
                                            3
                                             %                                                                                                                                  
3cho@3cho test % 
[2]  + done       echo 2
                        3cho@3cho test % 
```

**Comment by mehalter** [comment]
This would be a bug with [toggelterm.nvim](https://github.com/akinsho/toggleterm.nvim) as we do not handle anything regarding the terminal itself.

**Comment by 3chospirits** [comment]
Just wanted to say, did a slight bit more digging around and found that the solution was something to do with how shell was configuered. For anyone that runs into this problem, Running `reset` in the shell fixed the issue.

But weird because this wasn't happening at all to me before and I never changed the shell behavior, seems like installation of astrovim or some plugin might've changed the shell configuration.
