### ISSUE TITLE
Improve code annotations format

### ISSUE THREAD

**Issue by logan-xyz** [AstroNvim/AstroNvim#1743]
### Is your feature related to a problem?

No

### Describe the new feature

The annotation format used in the AstronNvim codebase could be improved. For instance, the annotation for the `astronvim.utils.extend_tbs` function is currently as follows:

```lua
--- Merge extended options with a default table of options
-- @param default the default table that you want to merge into
-- @param opts the new options that should be merged with the default table
-- @return the merged table
function M.extend_tbl(default, opts)
  opts = opts or {}
  return default and vim.tbl_deep_extend("force", default, opts) or opts
end
```
The above annotation is not well formatted, which results in the argument type information being lost in the hover documentation.

<img width="1215" alt="Screen Shot 2023-04-06 at 10 16 24" src="https://user-images.githubusercontent.com/80801525/230256913-8d059444-3600-4e2d-bd5f-ea452ff5c6e8.png">

By comparison, the `vim.tbl_deep_extend` function is documented as follows:
```lua
--- Merges recursively two or more map-like tables.
---
---@see |vim.tbl_extend()|
---
---@param behavior string Decides what to do if a key is found in more than one map:
---      - "error": raise an error
---      - "keep":  use value from the leftmost map
---      - "force": use value from the rightmost map
---@param ... table Two or more map-like tables
---@return table Merged table
function vim.tbl_deep_extend(behavior, ...)
  return tbl_extend(behavior, true, ...)
end
```
<img width="1027" alt="Screen Shot 2023-04-06 at 10 24 50" src="https://user-images.githubusercontent.com/80801525/230256931-959e47b7-7588-4201-b24f-fedc20b85b1a.png">

### Additional context

related links
- [lua-lauanage-server Annotations](https://github.com/LuaLS/lua-language-server/wiki/Annotations)

**Comment by mehalter** [comment]
This is a great idea thanks! I'll definitely get around to doing this at some point unless someone opens a PR first!

**Comment by logan-xyz** [comment]
> This is a great idea thanks! I'll definitely get around to doing this at some point unless someone opens a PR first!

Ah, I would be happy to create a pull request for this later.

Thanks!

**Comment by mehalter** [comment]
Finished up in nightly @logan-xyz ! Thanks for helping get this ball rolling!
