### ISSUE TITLE
Go. Creating a new file. LSP server is not working.

### ISSUE THREAD

**Issue by jmoloko** [AstroNvim/AstroNvim#1744]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

6.2.8-1-MANJARO

### Terminal/GUI

alacritty

## AstroNvim
  - INFO: AstroNvim Version: nightly (v3.8.0)
  - INFO: Neovim Version: v0.8.3
  - OK: Using stable Neovim >= 0.8.0
  - OK: `git` is installed: Used for core functionality such as updater and plugin management
  - OK: `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
  - OK: `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
  - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
  - OK: `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
  - OK: `btm` is installed: Used for mappings to pull up system monitor (Optional)
  - OK: `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

When I create a new file in a project, the LSP server is not automatically connected. 
I need to restart **AstroNvim** for the language server to work.
I tried to create files through **neo-tree** and through the **console**
Fresh installation of **AstroNvim**

### Steps to Reproduce

1. Open project (file) - all works
2. Create some new file neo-tree. LSP - not work
3. Exit AstroNvim
4. Open project again -> all works

### Expected behavior

-

### Screenshots
[![lsp-work.png](https://i.postimg.cc/d395Y8Bc/lsp-work.png)](https://postimg.cc/QKHQgKwf)
[![lsp-not-Work.png](https://i.postimg.cc/BQ6Tb9ZK/lsp-not-Work.png)](https://postimg.cc/3Ws4fqv8)
[![nul-ls.png](https://i.postimg.cc/BvK9GV1W/nul-ls.png)](https://postimg.cc/Z94D8jcj)

**Comment by rozhelluk** [comment]
just use :e

**Comment by mehalter** [comment]
@jmoloko when you open the new file that you created, does it shos the LSP attached in the statusline? The screenshot you sent of the `:LspInfo` looks like it's attached

**Comment by jmoloko** [comment]
@mehalter  Yes!
[![line.png](https://i.postimg.cc/QCdbgJVM/line.png)](https://postimg.cc/DJRLnsrV)

**Comment by mehalter** [comment]
Ok, then sadly this would be a bug in the language server itself and not in AstroNvim. It could be the language servers being slow at picking up on things. All AstroNvim can provide is a way to make that connection happen and get the language servers running. If it's running, there's not really anything else we can do :/

**Comment by jmoloko** [comment]
@mehalter 
This is a very strange situation, because in my personal config, the LSP server (golps) is working fine.

**Comment by jmoloko** [comment]
@mehalter Will reinstalling AstroNvim help fix the situation?

**Comment by mehalter** [comment]
Yeah, I also see it working fine in my AstroNvim configuration. Can you also replicate this without any user configuration and just a stock/default AstroNvim where you install gopls through mason GUI?

**Comment by mehalter** [comment]
That might help, just clearing your cache/data/state folders and restarting. Also could try it without your user configuration

**Comment by jmoloko** [comment]
@mehalter 
I have a fresh install of AstroNvim. Only themes added
Ok I will try to reinstall again

**Comment by mehalter** [comment]
https://asciinema.org/a/GbWWebghYDOpNEoB5I9PKR1ib

seems to work fine on my end. This is a fresh installation with just `gopls` and `go` treesitter

**Comment by mehalter** [comment]
Here is recreating the two images originally shared in this issue:

File that exists:
![2023-04-06_07:44:57_screenshot](https://user-images.githubusercontent.com/1591837/230367310-1cbb3949-07bb-4755-a3ce-905979eb1e01.png)

Create new file in neo-tree and open it without restarting and adding content:
![2023-04-06_07:45:23_screenshot](https://user-images.githubusercontent.com/1591837/230367321-e9333a9f-e874-4895-93f7-88eb056f830e.png)

**Comment by jmoloko** [comment]
Fresh install!
![AstroNvim](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMGUzMjc2ZWFiOTY5MGU4YjhmZTU1YzdiYjk5NTdmMjVhNDFkZGM3ZiZjdD1n/CnO6Dx8uw7IhOf5w4r/giphy.gif)

**Comment by jmoloko** [comment]
Solved!
Reverted the previous configuration of AstroNvim.
I don't understand what happened, but it worked!

**Comment by mehalter** [comment]
That's great!
