### ISSUE TITLE
Git opens when i try to drag horizontal splits

### ISSUE THREAD

**Issue by DarkCat5501** [AstroNvim/AstroNvim#1748]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Ubuntu 22.10

### Terminal/GUI

alacritty

## AstroNvim
  - INFO: AstroNvim Version: v3.9.0
  - INFO: Neovim Version: v0.8.2
  - OK: Using stable Neovim >= 0.8.0
  - OK: `git` is installed: Used for core functionality such as updater and plugin management
  - OK: `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
  - OK: `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
  - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
  - WARNING: `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
  - WARNING: `btm` is not installed: Used for mappings to pull up system monitor (Optional)
  - OK: `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Whenever I try do drag the split to resize in the red area, it opens the git branches search box, as if i was clicking on the main statusbar

![image](https://user-images.githubusercontent.com/34375081/230451212-af278484-e063-4694-bcdd-c4800fbc3b7c.png)

### Steps to Reproduce

Open a project setup with git
Open 2 or more files as horizontal splits
 Try to resize them by dragging exactly above the git information in the statusbar

### Expected behavior

it will open the git branches search
![image](https://user-images.githubusercontent.com/34375081/230451980-3e65c5d9-89d5-410c-84d4-2b3953c00556.png)

**Comment by mehalter** [comment]
Are you saying that if you click and drag on the git branch it pulls up the git branch selection? I definitely wouldn't recommend doing that

**Comment by mehalter** [comment]
We don't have a way to identify with the neovim API whether or not the element is being clicked or dragged. This is a limitation of the neovim ecosystem and mouse support. There isn't much else we can do here. You could customize your heirline setup to remove all of the clickable elements (this would be fairly verbose), or not click/drag on the clickable elements themselves.
