### ISSUE TITLE
Since v3 circle symbol in which-key popup

### ISSUE THREAD

**Issue by letscho123** [AstroNvim/AstroNvim#1749]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Linux Fedora 37

### Terminal/GUI

kitty

### AstroNvim Health

```
## AstroNvim
  - INFO: AstroNvim Version: v3.9.0
  - INFO: Neovim Version: v0.8.3
  - OK: Using stable Neovim >= 0.8.0
  - OK: `git` is installed: Used for core functionality such as updater and plugin management
  - OK: `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
  - OK: `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
  - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
  - WARNING: `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
  - WARNING: `btm` is not installed: Used for mappings to pull up system monitor (Optional)
  - OK: `python` is installed: Used for mappings to pull up python REPL (Optional)
```

### Describe the bug

Since I installed version 3, there is a circle symbol after the keyboard shortcut in which-key:
![Screenshot from 2023-04-07 11-41-09](https://user-images.githubusercontent.com/78268466/230617952-88902153-0a82-4f27-861c-d2159f8f5f11.png)

This was not there in version 2.
Also some icons on the which-key popup (hit `space`) are not displayed correctly.
Nerdfonts (DejavuSansMono) is installed and all other icons for all other plugins are shown correctly.

### Steps to Reproduce

1. hit `space`
2. see the circles
3. some icons are not displayed correctly

### Expected behavior

1. hit `space`
2. don't see circles
3. all icons are working

**Comment by mehalter** [comment]
Make sure you have an up to date nerdfont installed :)

**Comment by letscho123** [comment]
Ok the updated nerdfont fixed the icon issue, but I still see the circles in the which-key popup.
Is there a way to remove it?

**Comment by mehalter** [comment]
You can modify the default `which-key` configuration in your `plugins`. Something like this:

```lua
{ "folke/which-key.nvim", opts = { icons = { separator = "➜" } } }
```

**Comment by letscho123** [comment]
Exactly what I was looking for!
Thanks a lot!

**Comment by luxus** [comment]
the size of the circles is related to a strange font.. they are much smaller try the font that have no Mono at the end (nearly all nerd fonts are still mono spaced)
