### ISSUE TITLE
Status `unique_path` not accurate if child file opened before parent

### ISSUE THREAD

**Issue by praveenperera** [AstroNvim/AstroNvim#1750]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.3.1

### Terminal/GUI

Alacritty 

### AstroNvim Health

1
  1 astronvim: require("astronvim.health").check()
  2 ========================================================================
  3 ## AstroNvim
  4   - INFO: AstroNvim Version: v3.8.0
  5   - INFO: Neovim Version: v0.8.3
  6   - OK: Using stable Neovim >= 0.8.0
  7   - OK: `git` is installed: Used for core functionality such as updater and plugin management
  8   - OK: `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
  9   - OK: `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
 10   - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
 11   - OK: `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
 12   - OK: `btm` is installed: Used for mappings to pull up system monitor (Optional)
 13   - OK: `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

I configured the status line as following: 

```lua
local M = {}

local function config(_, opts)
    local status = require("astronvim.utils.status")
    opts.statusline = {
        hl = { fg = "fg", bg = "bg" },
        status.component.mode({
            mode_text = { padding = { left = 1, right = 1 } },
        }), -- add the mode text
        status.component.git_branch(),
        status.component.file_info({
            unique_path = {},
        }),
        status.component.cmd_info(),
        status.component.git_diff(),
        status.component.diagnostics(),
        status.component.fill(),
        status.component.cmd_info(),
        status.component.fill(),
        status.component.lsp(),
        status.component.treesitter(),
        status.component.nav(),
        -- remove the 2nd mode indicator on the right
    }

    -- return the final configuration table
    return opts
end

M.config = config

return M
```

I have  multiple `init.lua` files.

If I open the parent init.lua file first and then the `config/init.lua` file, everything works as expected. The status line shows the `config/init.lua` and just `init.lua`.

But if I open `config/init.lua` file and then `init.lua` they both show just `init.lua`

However the tabline on top always shows the correct information.

### Steps to Reproduce

See description of bug and video below for reproduction 

https://user-images.githubusercontent.com/1775346/230785263-fe078229-855a-4d1c-83da-4f76d96136f2.mov

### Expected behavior

Show the unique path all the time

**Comment by praveenperera** [comment]
I asked GPT4 and it gave me a replacement function that fixed it:

```lua
function M.provider.unique_path(opts)
  opts = extend_tbl({
    buf_name = function(bufnr) return vim.fn.fnamemodify(vim.api.nvim_buf_get_name(bufnr), ":t") end,
    bufnr = 0,
    max_length = 16,
  }, opts)

  local function get_unique_path(bufnr)
    local name = opts.buf_name(bufnr)
    local unique_path = ""

    local same_name_buffers = {}
    for _, value in ipairs(vim.t.bufs) do
      if name == opts.buf_name(value) then
        table.insert(same_name_buffers, value)
      end
    end

    if #same_name_buffers == 1 then
      return unique_path
    end

    local function get_path_parts(path)
      local parts = {}
      for match in (path .. "/"):gmatch("(.-)" .. "/") do
        table.insert(parts, match)
      end
      return parts
    end

    local current = get_path_parts(vim.api.nvim_buf_get_name(bufnr))

    for _, other_bufnr in ipairs(same_name_buffers) do
      if other_bufnr ~= bufnr then
        local other = get_path_parts(vim.api.nvim_buf_get_name(other_bufnr))

        for i = #current - 1, 1, -1 do
          local value_current = current[i]
          local other_current = other[i]

          if value_current ~= other_current then
            unique_path = value_current .. "/"
            break
          end
        end
      end
    end

    return unique_path
  end

  return function(self)
    opts.bufnr = self and self.bufnr or opts.bufnr
    local unique_path = get_unique_path(opts.bufnr)

    return M.utils.stylize(
      (
        opts.max_length > 0
        and #unique_path > opts.max_length
        and string.sub(unique_path, 1, opts.max_length - 2) .. get_icon "Ellipsis" .. "/"
      ) or unique_path,
      opts
    )
  end
end
```

**Comment by mehalter** [comment]
Thanks for pointing this out. I have resolved this on nightly. A bit similar to how the ChatGPT code is doing it but improved the performance by like 2x in the calculation and fixed some other small issues it had.
