### ISSUE TITLE
Can not disable key mappings

### ISSUE THREAD

**Issue by pzzxqj** [AstroNvim/AstroNvim#1751]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

manjaro

### Terminal/GUI

wezterm

## AstroNvim
  - INFO: AstroNvim Version: v3.9.0
  - INFO: Neovim Version: v0.8.3
  - OK: Using stable Neovim >= 0.8.0
  - OK: `git` is installed: Used for core functionality such as updater and plugin management
  - OK: `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
  - WARNING: `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
  - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
  - WARNING: `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
  - OK: `btm` is installed: Used for mappings to pull up system monitor (Optional)
  - OK: `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Can not disable key mappings for C-h, C-j, C-k and C-l in Normal mode and terminal mode

### Steps to Reproduce

put below in `user/mappings.lua`, but don't work

```lua
return {
  n = {
    ["<C-h"] = false,
    ["<C-j"] = false,
    ["<C-k"] = false,
    ["<C-l"] = false,
  },
  t = {
    ["<C-h"] = false,
    ["<C-j"] = false,
    ["<C-k"] = false,
    ["<C-l"] = false,
  }
}
```

### Expected behavior

disable these key mappings.

**Comment by mehalter** [comment]
You have a typo and need to put the `>` at the end of the key.
