### ISSUE TITLE
snippets completion can not input `j`

### ISSUE THREAD

**Issue by wqk151** [AstroNvim/AstroNvim#1752]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Ubuntu20.04

### Terminal/GUI

gnome-terminal

### AstroNvim Health

```
    1 astronvim: require("astronvim.health").check()
    2 ========================================================================
    3 ## AstroNvim
    4   - INFO: AstroNvim Version: v3.9.0
    5   - INFO: Neovim Version: v0.8.3
    6   - OK: Using stable Neovim >= 0.8.0
    7   - OK: `git` is installed: Used for core functionality such as updater and plugin management
    8   - OK: `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
    9   - OK: `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
   10   - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
   11   - OK: `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
   12   - OK: `btm` is installed: Used for mappings to pull up system monitor (Optional)
   13   - OK: `python` is installed: Used for mappings to pull up python REPL (Optional)
```

### Describe the bug

I write python code, I want to import `json` module.When I input `im` and press `Tab`, then press `j`,will excape insert mode,instead of enter the visual mode.

### Steps to Reproduce

I have remove all my custom config

### Expected behavior

can input the word `json`,not enter a visual mode.

### Screenshots

![2023-04-10_15-07-06](https://user-images.githubusercontent.com/18275602/230847542-13ebf600-6dd6-4d0d-8e5e-776731337444.png)
![2023-04-10_14-56-32](https://user-images.githubusercontent.com/18275602/230847548-099141ec-493a-4b02-adde-5eb9482097c8.png)

**Comment by mehalter** [comment]
Fixed in nightly, will get new release tagged this afternoon. Thanks for reporting!
