### ISSUE TITLE
Insert mode mappings do not distinguish <C-i>/Tab and <C-m>/CR

### ISSUE THREAD

**Issue by JohnnyGoodNews** [AstroNvim/AstroNvim#1753]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.3.1

### Terminal/GUI

kitty

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: v3.9.0
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Insert mode mappings do not distinguish `<C-i>/<C-m>` from `<Tab>/<CR>` (even though the distinction works in normal mode).

### Steps to Reproduce

* Fresh AstroNvim installation with a starting point configuration from: https://github.com/AstroNvim/user_example
* Put normal/insert mode mappings into `init.lua`'s `polish` function:
```
    vim.keymap.set("i", "<C-i>", '<CMD>lua print([[ Ctr-i is pressed ]])<CR>')
    vim.keymap.set("i", "<Tab>", '<CMD>lua print([[ Tab is pressed ]])<CR>')
    vim.keymap.set("i", "<C-m>", '<CMD>lua print([[ C-m is pressed ]])<CR>')
    vim.keymap.set("i", "<CR>", '<CMD>lua print([[ CR is pressed ]])<CR>')

    vim.keymap.set("n", "<C-i>", '<CMD>lua print([[ Ctr-i is pressed ]])<CR>')
    vim.keymap.set("n", "<Tab>", '<CMD>lua print([[ Tab is pressed ]])<CR>')
    vim.keymap.set("n", "<C-m>", '<CMD>lua print([[ C-m is pressed ]])<CR>')
    vim.keymap.set("n", "<CR>", '<CMD>lua print([[ CR is pressed ]])<CR>')
```
* Press CR/Tab/C-m/C-i in normal mode and get appropriate messages
* Press CR in insert mode: "C-m is pressed"
* Press Tab in insert mode: "C-i is pressed"

### Expected behavior

Distinct mapping behavior in insert mode between the `Tab/C-i` and `CR/C-m` pairs.

**Comment by mehalter** [comment]
This is terminal limitations and completely separate from Neovim and in turn AstroNvim.

**Comment by JohnnyGoodNews** [comment]
How can this be a terminal issue if the distinction works in normal mode but not in insert mode?

It also does not seem to be a Terminal or Neovim issue because it correctly works when run as `nvim -u NORC`.

**Comment by mehalter** [comment]
@JohnnyGoodNews https://asciinema.org/a/ZNmHJW6G50CXSTBguqNqWPIqt

This is also described in the neovim documentation: `:h key-notation` if you look at the `equivalent` column.

```
					*key-notation* *key-codes* *keycodes*
These names for keys are used in the documentation.  They can also be used
with the ":map" command.

notation	meaning		    equivalent	decimal value(s)	 
-----------------------------------------------------------------------  
<Nul>		zero			CTRL-@	  0 (stored as 10) *<Nul>*
<BS>		backspace		CTRL-H	  8	*backspace*
<Tab>		tab			CTRL-I	  9	*tab* *Tab*
							*linefeed*
<NL>		linefeed		CTRL-J	 10 (used for <Nul>)
<CR>		carriage return		CTRL-M	 13	*carriage-return*
<Return>	same as <CR>				*<Return>*
```

**Comment by JohnnyGoodNews** [comment]
@mehalter It works in Neovim i.e. without AstroNvim in the described setup. (I'm absolutely not discounting mistakes on my side though)

**Comment by mehalter** [comment]
ah, the terminal session I sent you in that message also showed me verifying that the keys are communicated to neovim in the same manner even with `nvim -u NORC`

**Comment by JohnnyGoodNews** [comment]
Well in this case I am using kitty terminal which is not communicating C-i and Tab as the same key. This enables me to map them differently in neovim. I don't know why it is not working with AstroNvim specifically.

Which information would be helpful to find out why it is only working in plain neovim for me?

**Comment by mehalter** [comment]
@JohnnyGoodNews looks like this is an issue with `nvim-cmp`: https://github.com/hrsh7th/nvim-cmp/issues/1510

**Comment by mehalter** [comment]
@JohnnyGoodNews just a heads up that the linked issue on `nvim-cmp` seems to be quite close to a fix for this :)
