### ISSUE TITLE
`colors_name` being `nil` prevents heirline init

### ISSUE THREAD

**Issue by mkaito** [AstroNvim/AstroNvim#1757]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.3.1

### Terminal/GUI

iTerm 2

### AstroNvim Health

astronvim: require("astronvim.health").check()
   3
   4 AstroNvim
   5 - AstroNvim Version: v3.10.1
   6 - Neovim Version: v0.9.0
   7 - OK Using stable Neovim >= 0.8.0
   8 - OK git is installed: Used for core functionality such as updater and plugin management
   9 - OK open is installed: Used for gx mapping for opening files with system opener (Optional)
  10 - OK lazygit is installed: Used for mappings to pull up git TUI (Optional)
  11 - OK node is installed: Used for mappings to pull up node REPL (Optional)
  12 - OK gdu is installed: Used for mappings to pull up disk usage analyzer (Optional)
  13 - WARNING btm is not installed: Used for mappings to pull up system monitor (Optional)
  14 - OK python is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

`heirline` fails to initialize

### Steps to Reproduce

1. Start neovim
2. Observe error message

### Expected behavior

`heirline` should init

### Additional Context

I see that this was changed in 56dd4a365ca414a3ea73fe89f838b29744c02ec6. I think it should suffice to just revert to the fallback in `status.lua:153`.

Error message:
```
Failed to run `config` for heirline.nvim

/Users/mkaito/.config/nvim/lua/astronvim/utils/status.lua:153: attempt to concatenate field 'colors_name' (a nil value)

# stacktrace:
  - lua/astronvim/utils/status.lua:153 _in_ **lualine_mode**
  - lua/plugins/configs/heirline.lua:27 _in_ **setup_colors**
  - lua/plugins/configs/heirline.lua:109 _in_ **config**
```

**Comment by mehalter** [comment]
Thanks for catching this! I just tagged v3.10.2 which should resolve this :)
