### ISSUE TITLE
Folding indicators are missing when opening files via `nvim .`

### ISSUE THREAD

**Issue by 0xricksanchez** [AstroNvim/AstroNvim#1760]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.3.1

### Terminal/GUI

kitty

### AstroNvim Health

```

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.10.2
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)


```

### Describe the bug

As described on Discord, I just noticed a strange behavior again when it comes to folding indicators. I observed that:

- If I open a single file like `vi myFile.rs` I get the folding indicators as expected
- However, if I do `vi .` and open the same file via telescope search ( `<leader>ff` ) or just via `neotree` I don't get the folding indicators.
- If I open a single file, followed by a telescope file open I get the folding indicators for the file opened via telescopes as well!

This seems odd. My user config is very bare bones and I don't expect an error there that messes with the settings as it works just fine when opening a single file (first). Seems like whatever logic is necessary for those indicators to appear is not triggered when starting up `vi .` into neotree and opening a file from there via telescope. 

### Steps to Reproduce

see above

### Expected behavior

get folding indicators regardless of how I open my files.

**Comment by Uzaaft** [comment]
Was able to reproduce. I'll try and take a look, but mehalter would probably debug this faster than me

**Comment by mehalter** [comment]
This is an upstream bug in `neo-tree` I have opened a new issue there and also have opened a PR that resolves it. Hopefully this gets resolved upstream soon :)

Issue: https://github.com/nvim-neo-tree/neo-tree.nvim/issues/867
PR: https://github.com/nvim-neo-tree/neo-tree.nvim/pull/868
