### ISSUE TITLE
Please added lsp support for swift langauge

### ISSUE THREAD

**Issue by coderj001** [AstroNvim/AstroNvim#1762]
### Is your feature related to a problem?

AstroNvim don't provide lsp support for Swift, but [sourcekit-lsp](https://github.com/apple/sourcekit-lsp) is available. 
<img width="950" alt="Screenshot 2023-04-12 at 8 30 10 PM" src="https://user-images.githubusercontent.com/39460245/231498804-e7714f22-c725-4bb2-932e-86be5d1a74bc.png">

### Describe the new feature

Try integrated sourcekit-lsp, I have tried on my own nvim config and it work like to see, feature build on AstroNvim.

**Comment by mehalter** [comment]
This should be a request on mason to get it added to their registry: https://github.com/williamboman/mason.nvim

AstroNvim provides mason which can be used to install packages that it supports. You can also set up language servers you have installed locally with `lspconfig` directly: https://astronvim.com/Recipes/advanced_lsp#lsp-setup-without-installer

**Comment by mehalter** [comment]
Here is a link to the lspconfig page for `sourcekit` which it does support: https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#sourcekit

So if you have the language server installed you just need to add `"source kit"` to your `lsp.servers` table in your user configuration as shown in the AstroNvim docs I linked previously

**Comment by mehalter** [comment]
https://github.com/williamboman/mason.nvim/issues/208

Here is a relevant issue on Mason. Looks like they haven't added it because it comes bundled with `swift` anyway so it will be available for users that need it.
