### ISSUE TITLE
file explorer tabs disappeared

### ISSUE THREAD

**Issue by mvolkmann** [AstroNvim/AstroNvim#1763]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.2.1

### Terminal/GUI

warp

### AstroNvim Health

  1 astronvim: require("astronvim.health").check()
  2 ========================================================================
  3 ## AstroNvim
  4   - INFO: AstroNvim Version: v3.10.2
  5   - INFO: Neovim Version: v0.8.3
  6   - OK: Using stable Neovim >= 0.8.0
  7   - OK: `git` is installed: Used for core functionality such as updater and plugin management
  8   - OK: `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
  9   - OK: `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
 10   - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
 11   - OK: `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
 12   - OK: `btm` is installed: Used for mappings to pull up system monitor (Optional)
 13   - OK: `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

The "File", "Bufs", and "Git" tabs at the top of the file explorer disappeared after updating to the newest version of AstroNvim. They are present, but not visible.

### Steps to Reproduce

1. Update to the latest version of AstroNvim.
2. Start a new session.
3. Press `<leader>e` to display the file explorer.

### Expected behavior

I expected the File Explorer tabs to be visible.

### Screenshots

![Screenshot 2023-04-12 at 11 18 52 AM](https://user-images.githubusercontent.com/79312/231520821-d9bf8c42-0f9f-484a-857a-3e228cb0e4e8.png)

**Comment by mehalter** [comment]
can you share your user configuration? I cannot replicate this.

**Comment by mvolkmann** [comment]
I moved my `~/.config/nvim/lua/user` directory to another location so it wouldn't have any effect on this.
Then I restarted AstroNvim and still see the same thing.
Here is my `~/.config/nvim/init.lua` file which I don't think I have modified:

```lua
if vim.loader then vim.loader.enable() end -- enable vim.loader early if available

for _, source in ipairs {
  "astronvim.bootstrap",
  "astronvim.options",
  "astronvim.lazy",
  "astronvim.autocmds",
  "astronvim.mappings",
} do
  local status_ok, fault = pcall(require, source)
  if not status_ok then vim.api.nvim_err_writeln("Failed to load " .. source .. "\n\n" .. fault) end
end

if astronvim.default_colorscheme then
  if not pcall(vim.cmd.colorscheme, astronvim.default_colorscheme) then
    require("astronvim.utils").notify("Error setting up colorscheme: " .. astronvim.default_colorscheme, "error")
  end
end

require("astronvim.utils").conditional_func(astronvim.user_opts("polish", nil, false), true)
```

Please let me know what else you would like to see.

**Comment by mehalter** [comment]
@mvolkmann maybe try doing a fresh installation like clean your data/cache folders for Neovim and see if it still persists

**Comment by mvolkmann** [comment]
How can I determine where the data/cache folders reside?

**Comment by mehalter** [comment]
It should be something like this:

```sh
mv ~/.local/share/nvim ~/.local/share/nvim.bak
mv ~/.local/state/nvim ~/.local/state/nvim.bak
mv ~/.cache/nvim ~/.cache/nvim.bak
```

**Comment by mvolkmann** [comment]
I did what you suggested and restarted nvim.
That loaded lots of things on the first startup.
But my file explorer tabs are still not visible.

**Comment by mvolkmann** [comment]
After a lot of trial and error I isolated the problem. I have the file `~/.config/nvim/lua/user/plugins/neo-tree.lua` that contains the following:

```lua
return {
  "nvim-neo-tree/neo-tree.nvim"
  opts = function()
    return {
      filesystem = {
        filtered_items = {
          always_show = { "user" }
        }
      }
    }
  end
}
```

If I remove the `opts` key and value, the problem goes away. The purpose of that is to make is so my user directory is NOT hidden in the file explorer. That worked for me yesterday, but I did update neovim, AstroNvim, and all my plugins, so perhaps the way I specified that is no longer correct.

Do you see anything wrong with how I'm specifying that option?

**Comment by mehalter** [comment]
Ah this is extremely wrong. This code you sent basically overwrites our default neo-tree configuration completely. This should never have worked at all 😂

```lua
return {
  "nvim-neo-tree/neo-tree.nvim"
  opts = {
    filesystem = {
      filtered_items = {
        always_show = { "user" }
      }
    }
  }
}
```

**Comment by mehalter** [comment]
Take a look at the lazy documentation for how the overriding happens. You basically either want to use the function notation and the 2nd parameter of the function is the previously set (if any) options table and modify that. If there have been no previous options set, then it's just an empty table. This allows you to do modifications safely. Or you can just provide a table and it will do table merging. The function notation is basically only necessary if you are dealing with list like tables that cannot be merged or if you need to safely `require` something that the plugin itself provides

**Comment by mehalter** [comment]
Also completely off topic, but I saw on your website you run marathons! Congratulations on running Boston! Cool to see a runner around here!

**Comment by mehalter** [comment]
Also have spent a lot of time so far browsing your blog/wiki and love the content (especially the AstroNvim content). Would you mind if I shared some of the AstroNvim pages on the Discord?

**Comment by mvolkmann** [comment]
Thanks! I have a habit of documenting everything I learn in my blog. I'm still adding to the Lua and Neovim pages, but feel free to share them however you'd like. I'll keep improving them.

I'm trying to run a marathon in all 50 states. I have 9 to go, but it's getting harder due to age. I'm about to turn 62.

I ran Boston in 2005 and 2013 (the bombing year). My 2013 race was a good one ... 2:59:37. I've lost a fair amount of speed since then.

I found that I can get my `user` directory to appear if I delete the line `lua/user` from the nvim `.gitignore` file. Not sure if that's a good idea. Maybe it's okay since I won't be pushing anything to that repo.

**Comment by mvolkmann** [comment]
If you see anything in my blog pages that seems wrong or should be improved, don't hesitate to let me know and I'll fix it.

**Comment by mehalter** [comment]
Wow 2:59:37 is fantastic! 2013 was also the last time my dad was there, he was not nearly as quick though! His time that race was 3:12:08.

Yeah I'll finish taking a look through the pages and let you know if I see anything. It looks like some great resources for other users.

**Comment by mvolkmann** [comment]
I would love to be able to run a 3:12 marathon now! Best case scenario for me at the moment might be 3:30.

You said "Take a look at the lazy documentation for how the overriding happens." I've been searching for that and haven't found a page that describes all the options for configuring a plugin when using Lazy. Can you point me to a URL for that?
