### ISSUE TITLE
Request: Only show tab as active in tabline, if buffer is the currently selected split

### ISSUE THREAD

**Issue by praveenperera** [AstroNvim/AstroNvim#1767]
### Is your feature related to a problem?

I usually have to vertical splits open at all times. In the tab line both  open buffers have the active styling.  And I sometimes get confused which  file I'm currently focused on.

### Describe the new feature

Either:

1. Default to only showing active styling on tab in currently focused split
2. Keep current default but add easy config option to only apply the active styling to tab I'm currently focused on in a split
3. 3 states, `active`, `active-focused`, `inactive`

### Additional context

Only one tab should have active styling.

<img width="566" alt="Screenshot 2023-04-13 at 1 11 27 PM" src="https://user-images.githubusercontent.com/1775346/231847240-7c676bae-b9ea-465f-814b-3bb558076138.png">

**Comment by praveenperera** [comment]
Switched to JetBrains Mono, much better thank you!
<img width="199" alt="Screenshot 2023-04-14 at 9 59 05 AM" src="https://user-images.githubusercontent.com/1775346/232080357-d0dc1058-78d3-419b-a42f-88e8373877c5.png">

**Comment by praveenperera** [comment]
@mehalter was the italic for active tab remove? This is what i'm seeing below. Whats the easiest way of de-emphasizing the open but not currently active tab?
<img width="381" alt="Screenshot 2024-05-29 at 8 23 17 AM" src="https://github.com/AstroNvim/AstroNvim/assets/1775346/283e8356-f7c4-44c2-abad-560198f8142b">

**Comment by mehalter** [comment]
Nope, it's still there in a base installation. You must have something in your user configuration

![2024-05-29_09:41:38_screenshot](https://github.com/AstroNvim/AstroNvim/assets/1591837/53734dd7-cd02-4957-bba7-bc8cf743e94a)

**Comment by mehalter** [comment]
could also be if you changed terminals and it's not properly configured with italics

**Comment by mehalter** [comment]
For debugging purposes for your config, you can use the `plugin_opts` utility in AstroCore to check your config:

```
:lua =vim.tbl_get(require("astrocore").plugin_opts("astroui"), "status", "attributes", "buffer_active")
```

**Comment by praveenperera** [comment]
```
::lua =require("astrocore").plugin_opts("astroui").status.attributes.buffer_active
{
  bold = true,
  fg = "buffer_active_fg",
  italic = true
}
```

Also italic is working in my terminal I tested, see image

<img width="336" alt="Screenshot 2024-05-29 at 9 09 55 AM" src="https://github.com/AstroNvim/AstroNvim/assets/1775346/f1008d1d-ebcb-4d47-a352-6951d9c578f3">

**Comment by mehalter** [comment]
@praveenperera I loaded up your configuration that it located here: https://github.com/praveenperera/dotfiles/tree/master/nvim

and I am getting italics in my terminal

![2024-05-29_10:15:53_screenshot](https://github.com/AstroNvim/AstroNvim/assets/1591837/8912ea75-990f-455a-9c40-d45fe4644a05)

**Comment by praveenperera** [comment]
thats interesting, its weird that italics works with echo. Thanks for checking, I appreciate it, I'll try and figure it out.

**Comment by praveenperera** [comment]
Figured it out at some point TERM got set to `screen-256color`, changed it back to `xterm-256color` and its working again. Thanks for your help.

**Comment by mehalter** [comment]
that will do it!
