### ISSUE TITLE
Windows saved sessions cannot be loaded - due to / in shada paths?

### ISSUE THREAD

**Issue by Phil-T1** [AstroNvim/AstroNvim#1769]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Windows 11

### Terminal/GUI

CMD

### AstroNvim Health

   1 
   2   astronvim: require("astronvim.health").check()
   3
   4   AstroNvim
   5   - AstroNvim Version: unknown
   6   - Neovim Version: v0.9.0
   7   - OK Using stable Neovim >= 0.8.0
   8   - OK git is installed: Used for core functionality such as updater and plugin management
   9   - OK explorer is installed: Used for gx mapping for opening files with system opener (Optional)
  10   - WARNING lazygit is not installed: Used for mappings to pull up git TUI (Optional)
  11   - WARNING node is not installed: Used for mappings to pull up node REPL (Optional)
  12   - WARNING gdu is not installed: Used for mappings to pull up disk usage analyzer (Optional)
  13   - WARNING btm is not installed: Used for mappings to pull up system monitor (Optional)
  14   - OK python is installed: Used for mappings to pull up python REPL (Optional)
  15

### Describe the bug

Hi,
Astrovim appears to work very well in Windows 11, but the sessions cannot be loaded and the following error appears:
![image](https://user-images.githubusercontent.com/88270060/231996525-b8127287-e3aa-4a6f-9ca5-6c5a9fb43451.png)
This seems to indicate the it's due to Unix / paths being stored in the shada file instead of Windows \\\\:
(main.shada)
![image](https://user-images.githubusercontent.com/88270060/231996999-592c44cb-d37e-48c4-9cef-0a51f9991623.png)
Is there a setting or workaround to resolve this?

My setup is just installing Neovim, Astro, and then a Python lsp server. I haven't modified anything and this issue doesn't appear for me using this setup in Linux or within WSL Docker containers in Windows.

Thanks for the help!

Phil.

### Steps to Reproduce

(In Windows 11 having saved the last session before closing nvim)
nvim
SPACE S l

### Expected behavior

The session last saved should restore.

**Comment by mehalter** [comment]
@A-Lamia can you replicate this?

**Comment by A-Lamia** [comment]
@mehalter works fine have no issue though i am testing on windows 10 not 11.

**Comment by Phil-T1** [comment]
Hi,

Firstly, apologies, this issue is appearing for me in Windows 10, not Windows 11 - my bad.

On my Windows 11 machine Neovim session restore is working fine, and any paths listed in shada files there are also in the unix form of ~/... rather than ~\\... so that isn't the issue.

It seems like Neovim can't identify my home directory? It's looking at P:\AppData instead of C:\users\myusername\AppData?
![image](https://user-images.githubusercontent.com/88270060/232407184-890957a0-d88d-4c34-8853-f78f23640de3.png)

I've tried re-installing several times and there is no change. I've done literally zero config, and the following works for my Windows 11 machine:
winget neovim
git clone --depth 1 https://github.com/AstroNvim/AstroNvim $env:LOCALAPPDATA\nvim


Thanks again,

Phil.

**Comment by Phil-T1** [comment]
I'm not sure where that would be located, but I first deleted:
c:\Users\myusername\AppData\Local\nvim
and \nvim-data

**Comment by Phil-T1** [comment]
I'm not sure where that would be located, but I first deleted:
c:\Users\myusername\AppData\Local\nvim
and \nvim-data

I'm using Nvim here on my company laptop. It occurred to me that this could be a user profile issue and I tried editing files on a network drive, rather than in my user profile where I tend to develop, and the sessions restored without any issue.

Does this give any more ideas on a workaround?

Thanks again,

Phil.

**Comment by mehalter** [comment]
Hm I'm not sure @Phil-T1 sorry :/ This is probably a bug with either neovim for their shada generation or more likely neovim-session-manager. Could be a limitation with network drives being slow which is a common issue in the neovim community. Sadly generating these files are outside of what AstroNvim does with it's machinery and so this would be an upstream bug that we don't have any control over from our repo :/
