### ISSUE TITLE
Treesitter Disable for Large Files

### ISSUE THREAD

**Issue by Hacksore** [AstroNvim/AstroNvim#1770]
### Is your feature related to a problem?

Yes, for me I tend to need to open large files for dist'd output of JS. These files can either be:

- Long, 30k lines
- Huge, 50mb file size

By default treesitter will try to parse the whole AST which will bring your neovim to a halt 😅. 

### Describe the new feature

What I did as a fix was implement a sensible default for the plugin of only disabling treesitter when the file is bigger than 5mb.

```lua
-- fix bad perf with treesitter and large files
{
  "nvim-treesitter/nvim-treesitter",
  event = "User Astrofile",
  config = function()
    require("nvim-treesitter.configs").setup({
      highlight = {
        enable = true,
        disable = function(_, bufnr)
          -- neovim get size of buffer
          local file_size = vim.fn.getfsize(vim.fn.bufname(bufnr))
          return file_size > 5000
        end,
      },
    })
  end,
}

```

### Additional context

Is this something that should be enabled as a default in AstroNvim?

**Comment by Hacksore** [comment]
Linking the official [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter#modules) docs where the recommend something similar.

https://github.com/nvim-treesitter/nvim-treesitter#modules

**Comment by mehalter** [comment]
Thanks for the suggestion! I went ahead and added this with a max lines default of 10,000 lines. This aligns with the max length for Aerial as well so it seemed like a good default.

**Comment by Hacksore** [comment]
@mehalter good to hear that this acceptable as a default. 

I'll keep an eye on the releases so I can let AtroNvim defaults take over and remove patch.

**Comment by mehalter** [comment]
New release will be sometime early next week after I get some time to take a look at the other recent issues this week. Gonna go ahead and close this. Thanks again for the suggestion!
