### ISSUE TITLE
possible issue with AstroNvim configuration of Telescope

### ISSUE THREAD

**Issue by mvolkmann** [AstroNvim/AstroNvim#1771]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.2.1

### Terminal/GUI

warp

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: v3.10.2-1-gc8f74c3
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Sometimes the filter input in Telescope windows is at the bottom instead of the top.
Is this something that AstroNvim configures?
See the attached screenshot.

### Steps to Reproduce

Run any command that opens a Telescope window.

### Expected behavior

I expected the text input in all Telescope windows to always be in the upper-left.

### Screenshots

![Screenshot 2023-04-14 at 12 17 51 PM](https://user-images.githubusercontent.com/79312/232113740-d4ed1c09-6d15-471a-b8f5-fb034d23ed00.png)

**Comment by mehalter** [comment]
Can you give some more clear replication instructions? I can't replicate this at all. You mentioned sometimes, so I'm wondering if it's a specific picker or something that leads to this.

**Comment by mvolkmann** [comment]
The filter input is always at the bottom for me now. I can start from any directory, launch `nvim`, and press something like `<leader>ff` to find files. The filter input will be below the search results. I feel like there must be some setting that is causing this.

**Comment by mehalter** [comment]
Yeah it looks like you are probably overriding this somewhere from the default configuration

**Comment by mehalter** [comment]
The exact same problem you had here: https://github.com/AstroNvim/AstroNvim/issues/1763#issuecomment-1506156066

**Comment by mehalter** [comment]
```lua
return { 
   "nvim-telescope/telescope.nvim", 
   opts = function(_, opts) 
     local actions = require "telescope.actions" 

     opts.defaults.mappings.n["<Esc>"] = actions.close
   end 
 }
```

**Comment by mvolkmann** [comment]
Thanks so much @mehalter! That fixed it!

**Comment by mvolkmann** [comment]
Is it fair to say that any time I want to customize the configuration of a plugin that is also configured by AstroNvim, I should follow this pattern?

```lua
return { 
  "{plugin-name}", 
  opts = function(_, opts) 
    -- modify opts properties here
  end 
 }
```
