### ISSUE TITLE
Icons problem

### ISSUE THREAD

**Issue by fifty59nine** [AstroNvim/AstroNvim#1772]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Pop!_OS 22.04 LTS x86_64

### Terminal/GUI

gnome-terminal

## AstroNvim
    4   - INFO: AstroNvim Version: v3.10.3
    5   - INFO: Neovim Version: v0.8.3
    6   - OK: Using stable Neovim >= 0.8.0
    7   - OK: `git` is installed: Used for core functionality such as updater and plugin management
    8   - OK: `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
    9   - WARNING: `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
   10   - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
   11   - WARNING: `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
   12   - WARNING: `btm` is not installed: Used for mappings to pull up system monitor (Optional)
   13   - OK: `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Bad icon display(i have already installed 3 NerdFonts).
![image](https://user-images.githubusercontent.com/47134714/232227190-7bbcfeb7-3fda-4a1a-a3ab-b268442b8a41.png)

### Steps to Reproduce

1. cd word_dir
2. nvim .

### Expected behavior

Display correct icons

**Comment by mehalter** [comment]
One thing I would recommend is making sure after you install different nerd fonts that your terminal is being properly configured to use them. Also making sure you are getting a current version of nerd font as well. If you have questions about this process I would definitely recommend joining the discord as many people have had similar things when setting up nerd fonts.
