### ISSUE TITLE
Complete failure of setup instructions

### ISSUE THREAD

**Issue by vonschutter** [AstroNvim/AstroNvim#1776]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Ubuntu 22.04 LTS

### Terminal/GUI

bash/konsole

### AstroNvim Health

  1                                                                                                                                                     
  2 astronvim: require("astronvim.health").check()
  3 ========================================================================
  4   - ERROR: Failed to run healthcheck for "astronvim" plugin. Exception:
  5     function health#check, line 20
  6     Vim(eval):E5108: Error executing lua /home/stephans/.config/nvim/lua/astronvim/health.lua:4: attempt to index field 'health' (a nil value)
  7     stack traceback:
  8     /home/stephans/.config/nvim/lua/astronvim/health.lua:4: in function 'check'
  9     [string "luaeval()"]:1: in main chunk

### Describe the bug

Following the setup instructions does NOT result in a usable product. 

### Steps to Reproduce

Follow instructions on AstroNvim Github page.

### Expected behavior

Precisely what is shown on the screenshots and description. A working solution. 

### Screenshots

![Screenshot_20230416_111131](https://user-images.githubusercontent.com/34268921/232288868-e4bf7516-1727-42b4-a938-9640cc90af88.png)

### Additional Context

- The basic installation and setup should work. 
- It should work in all reasonable user contexts (with common distributions n -1)
- Preferably there should be a shell script that installs all the required components and configurations.
- The end result MUST be a working install

**Comment by mehalter** [comment]
Please make sure to refer to the installation requirements in the installation instructions. Things like the required Neovim version are very important aspects of the instruction.
