### ISSUE TITLE
Unreasonable requirement

### ISSUE THREAD

**Issue by vonschutter** [AstroNvim/AstroNvim#1777]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Ubuntu 22.04 LTS

### Terminal/GUI

bash/konsole

### AstroNvim Health

N/A

### Describe the bug

There is a requirement of nvim being of a version that almost nobody has in their repositories. Not USE Leap, not Ubuntu, not Debian, Not Pop! OS, etc. Please revise the requirement such that you are not depending on uncommon versions of software and/or development versions of software. 

### Steps to Reproduce

N/A

### Expected behavior

This requirements complicates the setup and configurations of the products such that very few will ever use the product. 

### Screenshots

n/a

### Additional Context

Please adjust the requirement or work with the maintainers to ensure that you have the correct version of nvim in the repositories.

**Comment by mehalter** [comment]
You are referring to a single package repository. Debians repository is the only one that I know of that is still on something like 0.4.4 or whatever it is. This would be an unreasonable requirement as that version was released several years ago and nearly 0% of the plugins that AstroNvim uses support it.

**Comment by vonschutter** [comment]
Perhaps a practical solution then? How about packaging the required version of Nvim + all the plugins in a Flatpack or Snap? The it would be accessible, controlled by you, and easy for all. -- What do you think about that?

**Comment by mehalter** [comment]
@vonschutter Neovim provides an Appimage for easy installation for this requirement and we are not looking to add neovim packaging at this moment.

Here is the neovim release page where you can download the AppImage: https://github.com/neovim/neovim//releases
