### ISSUE TITLE
User config can't correctly override astronvim defaults

### ISSUE THREAD

**Issue by rwijtvliet** [AstroNvim/AstroNvim#1779]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Pop Os 22.04

### Terminal/GUI

Gnome Terminal 3.44.0 for Gnome 42

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: v3.9.0
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- WARNING `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Custom user mappings, added to the table in `user/mappings.lua`, clash with those in `astronvim/mappings.lua`, causing an unexpected error. 

The error necessitates commenting out lines in `astronvim/mappings.lua` in order to get the user mappings to work correctly. 

By design, afaiu, this should not be necessary, and the mappings specified in `user/` should override those in `astronvim/`.

### Steps to Reproduce

Unexpected behavior:

1. Get a fresh user config by cloning Astronvim/user_config
2. Replace the contents of `lua/user/mappings.lua` with
   ```lua
   return {
     n = {
       ["k"] = {"t", desc = "Till", }, 
     },
   }
   ```
3. Start neovim and press `k`
4. Result: `E121: Undefined variable: t`

Solution:

1. In [`lua/astronvim/mappings.lua`](https://github.com/AstroNvim/AstroNvim/blob/main/lua/astronvim/mappings.lua), comment out line 23 and 24.
2. Repeat after every astronvim update.

### Expected behavior

"Till" behavior; move to just before next occurrence of [character that is pressed next] on the same line.

**Comment by mehalter** [comment]
In this case you are not overriding the fact that we use `expr = true`, so for that mapping just make sure to include `expr = false` because you need to override that default as well.

**Comment by rwijtvliet** [comment]
Ah, awesome, many thanks for clarifying! 

Is this documented somewhere; could I have known about this and/or read more about these options?

**Comment by rwijtvliet** [comment]
Ok, I think I commented too soon, @mehalter. 

> In this case you are not overriding the fact that we use `expr = true`, so for that mapping just make sure to include `expr = false` because you need to override that default as well.

Is there a reason the following `user/mappings.lua` config would not work, then:

```lua
return {
  [""] = {
    ["t"] = { "v:count == 0 || mode(1)[0:1] == 'no' ? 'k' : 'gk'", expr = true, desc = "Move cursor up" },
    ["k"] = { "t", expr=false, noremap=true, desc="Till"}
  },
}
```

More specifically, this is what I observe: when I open neovim, the `k` key *sometimes* moves the cursor up, and *sometimes* moves the cursor to the next occurrence of the character that is typed after it (=["till" behavior](https://unix.stackexchange.com/questions/146824/what-is-the-difference-between-find-and-till-in-vim)). 

Because I wouldn't believe it if I hadn't experienced it myself, I made a screenrecording, which you can see [here](https://imgur.com/a/QMrPfOi). You will see that I open the same file in neovim four times. The first and second time, the `k` key moves the cursor up. The third time, the `k` key has the "till" behavior. The fourth time, the `k` key moves the cursor up again.

I'm really puzzled, but maybe you have an idea?

**Comment by rwijtvliet** [comment]
I'm still suprised at what I wrote above, but it seems that restricting the `k` key remapping to normal mode resolves the issue:

```lua
return {
  [""] = {
    ["t"] = { "v:count == 0 || mode(1)[0:1] == 'no' ? 'k' : 'gk'", expr = true, desc = "Move cursor up" },
  },
  n = {
    ["k"] = { "t", expr=false, desc="Till"}
  },
}
```
Using this config, it seems I do not even need the `expr=false` option.
