### ISSUE TITLE
Lazy not loading plugins/user.lua

### ISSUE THREAD

**Issue by Theeoi** [AstroNvim/AstroNvim#1785]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Manjaro 22.1.0

### Terminal/GUI

Konsole 22.12.3

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.10.3
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

User plugins added as instructed by the [user_example repo](https://github.com/AstroNvim/user_example) are not loaded properly. The new plugins are installed by Lazy.nvim and can be viewed through `:Lazy`.

Have tried using two plugins with a plugins/user.lua file as:
```
return {
  {"lervag/vimtex"},
  {"ThePrimeagen/vim-be-good"},
}
```
neither plugin is loaded.

### Steps to Reproduce

1. Make a clean install of AstroNvim with a user config as the [user_example](https://github.com/AstroNvim/user_example).
2. Add a plugin in the plugins/user.lua file in the lazy syntax.
3. Reload AstroNvim and install the plugins `:Lazy install`

### Expected behavior

The plugins working.

For the two plugins in the example one would expect `:h vimtex` to display the proper documentation and `:VimBeGood` to start the game.

**Comment by mehalter** [comment]
You need to add `lazy = false` to plugins that you don't want to set up lazy loading for.

**Comment by mehalter** [comment]
Here are the relevant docs: https://astronvim.com/Recipes/custom_plugins

**Comment by Theeoi** [comment]
Can't believe I missed that.. 
Thank you!
