### ISSUE TITLE
Copilot suggestions don't work for me

### ISSUE THREAD

**Issue by dev-ardi** [AstroNvim/AstroNvim#1787]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Arch linux

### Terminal/GUI

Alacritty

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.10.3
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

copilot is enabled, panel works but doesn't suggest any code after installing astronvim.

This is my config code
```
  {
    "github/copilot.vim",
    event = "BufRead",
  }
  ```
Copilot status says it's online and enabled, and the panel works as expected. Just no code completion.

Used to work fine until I installed astronvim configuration.

### Steps to Reproduce

clone astronvim
install copilot plugin

### Expected behavior

suggestions, but they just don't show.

**Comment by mehalter** [comment]
I would recommend checking out the example configurations of it in AstroCommunity: https://github.com/AstroNvim/astrocommunity

Also questions are great on the official Discord where there are many users available to help that have done similar stuff.
