### ISSUE TITLE
Update nvim-treesitter to fix regression

### ISSUE THREAD

**Issue by kevinkirkup** [AstroNvim/AstroNvim#1789]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.3.1

### Terminal/GUI

kitty

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.10.3
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- WARNING `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Need to update the `nvim-treesitter` version to fix a bug in their repo:
https://github.com/nvim-treesitter/nvim-treesitter/commit/351e43d5ef9003c62068dc2f40a9772563355220

### Steps to Reproduce

1. Install default Astronvim
2. Use plugin that requires tree sitter
```
Error detected while processing CursorMoved Autocommands for "*"..function 3[3]..4[71]..matchup#delim#get_current[1]..<SNR>72_get_delim_multi[3]..matchup#ts_engine#get_delim[3]..<SNR>78_forward:
line    1:
E5108: Error executing lua ...vim/lazy/vim-matchup/lua/treesitter-matchup/internal.lua:158: attempt to call field 'get_node_text' (a nil value)
stack traceback:
        ...vim/lazy/vim-matchup/lua/treesitter-matchup/internal.lua:158: in function '_node_text'
        ...vim/lazy/vim-matchup/lua/treesitter-matchup/internal.lua:177: in function 'get_delim'
        [string "luaeval()"]:1: in main chunk
```

### Expected behavior

Should work as expected.

**Comment by mehalter** [comment]
Thanks for the heads up! This will be updated in the next release of AstroNvim :)

**Comment by mehalter** [comment]
Close with v3.11.0
