### ISSUE TITLE
Cannot change name of the default shortcut group

### ISSUE THREAD

**Issue by AsgrimS** [AstroNvim/AstroNvim#1791]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Arch Linux / 6.2.11-arch1-1

### Terminal/GUI

Alacritty

### AstroNvim Health

astronvim: require("astronvim.health").check()
```
AstroNvim ~
- AstroNvim Version: v3.10.3
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)
```

### Describe the bug

I can't change the default AstroNvim name of the keymap group which-key. In my case, I wanted to change the name for the `h` key. The default is "Home Screen".

### Steps to Reproduce

1. Go to `user/mappings.lua` dir in the `nvim/lua`. 
2. Add    `["<leader>h"] = { name = "Harpoon" },` under the `n` list

### Expected behaviour

I can overwrite default name so, entry in the which-key menu looks like this:
`h * Harpoon`

### Screenshots

![image](https://user-images.githubusercontent.com/32067841/233128193-9222bbec-9578-45ef-b87d-e3f8e656159e.png)
![image](https://user-images.githubusercontent.com/32067841/233128359-227b81e6-565f-45a6-acfa-18ffc80dbcdd.png)

### Additional Context

It works without a problem for a non-existing keybind like `["<leader>lP"] = { name = "Python" }`.
Setting  `["<leader>h"] = false` works as expected. Changes the name to a generic `prefix`
My full user config https://github.com/AsgrimS/astronvim-config

**Comment by mehalter** [comment]
You will want to use the function notation to remove the function of the key that is set as the behavior. Also instead of `name` you can just use `desc = "..."`

You would want it to be something like this as an example `user/init.lua` file:

```lua
return {
  mappings = function(maps)
    maps.n["<leader>h"] = { desc = "Harpoon" }
    return maps
  end
}
```

**Comment by AsgrimS** [comment]
I thought that the recommended way to manage mappings is via the `mappings.lua` file. Using the function notation inside `init.lua` seems to me like a workaround. 

I tried adding `["<leader>h"] = { desc = "Harpoon" }` inside `mappings.lua` but it just registered it as a normal shortcut and not a menu.
_shortcut_
![image](https://user-images.githubusercontent.com/32067841/233626847-7300b825-36a8-40c1-91a8-968f576d1a82.png)
vs 
_menu_
![image](https://user-images.githubusercontent.com/32067841/233626886-b53451f6-8f8b-4071-8962-131231559cab.png)

However, your proposition gave me an idea. By adding `name` as well as overwriting the `desc` value it is possible to get the desired effect without leaving `mappings.lua` file.
`["<leader>h"] = { name = "", desc = "Harpoon" }`
![image](https://user-images.githubusercontent.com/32067841/233628609-282a2ab1-c406-4f29-890f-52b463b2f642.png)

I might be wrong but it seems like, on my first attempt, accessing a default shortcut ( in my case leader + h ) only added the `name` parameter instead of overwriting the whole mapping for this combination and it looks like `which-key` uses name over the desc, so it registered it as a menu but still used "Homescreen" for the text.

It seems like the expected behaviour should be to overwrite any existing configuration for a given key combo with the configuration in `mappings.lua`, not extend it, as it leads to unexpected behaviour. It shouldn't be necessary to use function notation in the `init.lua` to configure mappings.

In my opinion, the current behaviour is a bug.

**Comment by AsgrimS** [comment]
I think it would be also nice to give an author of an issue time to respond before marking it as Closed :sweat_smile:
