### ISSUE TITLE
Heirline error on startup

### ISSUE THREAD

**Issue by shriharip** [AstroNvim/AstroNvim#1792]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macos 12.6

### Terminal/GUI

wezterm

### AstroNvim Health

  1 ──────────────────────────────────────────────────────────────────────────────
  2 astronvim: require("astronvim.health").check()
  3
  4 AstroNvim
  5 - AstroNvim Version: nightly (v3.1.1)
  6 - Neovim Version: v0.9.0-dev-1731+g1c4794944-dirty
  7 - WARNING Neovim nightly is not officially supported and may have breaking changes
  8 - OK git is installed: Used for core functionality such as updater and plugin management
  9 - OK open is installed: Used for gx mapping for opening files with system opener (Optional)
 10 - WARNING lazygit is not installed: Used for mappings to pull up git TUI (Optional)
 11 - OK node is installed: Used for mappings to pull up node REPL (Optional)
 12 - OK gdu is installed: Used for mappings to pull up disk usage analyzer (Optional)
 13 - WARNING btm is not installed: Used for mappings to pull up system monitor (Optional)
 14 - OK python3 is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Failed to run `config` for heirline.nvim

...ocal/share/nvim/lazy/heirline.nvim/lua/heirline/init.lua:95: Vim:E355: Unknown option: statuscolumn

# stacktrace:
  - /heirline.nvim/lua/heirline/init.lua:95 _in_ **setup**
  - .config/nvim/lua/plugins/configs/heirline.lua:110 _in_ **config**

### Steps to Reproduce

On opening the editor, I get the heirline issue

### Expected behavior

No errors on startup

**Comment by mehalter** [comment]
You need to make sure your version of Neovim matches the requirements and that you have updated to the latest version of Heirline in AstroNvim.

**Comment by bradrice** [comment]
This is happening for me on my Pop_OS! system, but not on my Mac. I have the exact same setup as far as I know.

**Comment by mehalter** [comment]
@bradrice as mentioned in my previous comment, make sure you have the correct version of Neovim installed. If you are getting this error this would mean that you have a nightly version of Neovim 0.9 installed that is before the statuscolumn option was added and you need to install the Neovim 0.9 stable version.

**Comment by zheneknew** [comment]
I'm here because I got an error about "Unknown option: statuscolumn" every time I called a terminal via space-t-f or space-t-h.
It turns out that I had a pretty old version of neovim - 0.8.3, and I did not install it from fedora's repo via dnf, but with some other method, because dnf had a version below 0.8 at that time.
Now I've installed neovim 0.9.4 from dnf and the status column problem is gone.
So even though my version 0.8.3 met the requirements, I had the problem.
**Maybe you should update the requirements.**
Hope this info can be useful.

**Comment by mehalter** [comment]
@zheneknew you might have a custom code that sets up statuscolumn. In our base code we check for the 0.9 and only enable it out of the box for 0.9. If you have your own code that doesn't do that then you will have broken then backwards compatibility

**Comment by zheneknew** [comment]
@mehalter I'm sure I didn't have, I installed a fresh astronvim installation after cleaning all folders in .config .cache. .local as it's recommended in your docs, after that I installed black, pyright, debugpy via Mason, and I had the problem after that without any line of custom code.

**Comment by mehalter** [comment]
Ok, well I cannot replicate this then @zheneknew . Testing a base installation with neovim 0.8 is working on my end :) Might want to take another look if you do want to use neovim 0.8. If not then you can just stick with your working set up on 0.9

**Comment by mehalter** [comment]
If you are curious, here is a recording of a fresh install with neovim 0.8: https://asciinema.org/a/qe6qajJO46G8PXMBLsIVSvdcj

**Comment by zheneknew** [comment]
@mehalter Sorry for spending your time, but I just reproduced it in a docker container. You didn't call a terminal in your video, I mentioned that error appears in this case.
Also I thought maybe it's because of my specific terminal(kitty) but it's reproduced in gnome-terminal too

record (error appears at 2:10 after I press space-t-f):
https://asciinema.org/a/TBEpXaywkTawEqJ2ZuUcUDAsN

Dockerfile:
```
FROM fedora:38
RUN echo fastestmirror=True >> /etc/dnf/dnf.conf 
RUN dnf install wget git -y
RUN wget https://github.com/neovim/neovim/releases/download/v0.8.3/nvim-linux64.tar.gz
RUN tar xf nvim-linux64.tar.gz 
RUN git clone --depth 1 https://github.com/AstroNvim/AstroNvim ~/.config/nvim
CMD sh
```
Or just commands you can type after `docker run --rm -ti fedora:38`:
```
echo fastestmirror=True >> /etc/dnf/dnf.conf 
dnf install wget git
wget https://github.com/neovim/neovim/releases/download/v0.8.3/nvim-linux64.tar.gz
tar xf nvim-linux64.tar.gz 
git clone --depth 1 https://github.com/AstroNvim/AstroNvim ~/.config/nvim
nvim-linux64/bin/nvim 
```

**Comment by mehalter** [comment]
ah I see! That makes sense! I will tag a quick release to patch this, there was a slightly malformed autocmd check 😄 thanks for explaining more!

**Comment by mehalter** [comment]
ok @zheneknew this is working now using the docker stuff in your previous comment :) thanks again!
