### ISSUE TITLE
Improve `nvim-autopairs` default behavior

### ISSUE THREAD

**Issue by goetzc** [AstroNvim/AstroNvim#1793]
### Describe the new feature

The _autopairs_ plugin ([`windwp/nvim-autopairs`](https://github.com/windwp/nvim-autopairs)) that is currently [being used](https://github.com/AstroNvim/AstroNvim/blob/cf624ae5870ea5fcf98ff1e2f6354f6a57df3f53/lua/plugins/core.lua#L14) in AstroNvim, provides the option to extend its behavior using rules. One of these rules is to automatically add missing spaces between parentheses whenever the user adds the first one of them.

This would improve usability when using `(` `)`, `[` `]`, or `{` `}`.

### Additional context

Better explained with the an tweaked diagram from the official [Wiki](https://github.com/windwp/nvim-autopairs/wiki/Custom-rules#add-spaces-between-parentheses) page: 

# Add spaces between parentheses

| When     | Insert    |  Currently | Proposed |
|----------|-----------|------------|----------|
| `(\|)`   | `<space>` | `( \|)`    | `( \| )` |
| `( \| )` | `)`       | `( )\| )`  | `(  )\|` |

The following configuration code provides this behavior:

```lua
return {
  "windwp/nvim-autopairs",
  config = function(_, opts)
    local npairs = require 'nvim-autopairs'
    local Rule   = require 'nvim-autopairs.rule'

    npairs.setup(opts)

    local brackets = { { '(', ')' }, { '[', ']' }, { '{', '}' } }
    npairs.add_rules {
      Rule(' ', ' ')
          :with_pair(function(opts)
            local pair = opts.line:sub(opts.col - 1, opts.col)
            return vim.tbl_contains({
              brackets[1][1] .. brackets[1][2],
              brackets[2][1] .. brackets[2][2],
              brackets[3][1] .. brackets[3][2],
            }, pair)
          end)
    }
    for _, bracket in pairs(brackets) do
      npairs.add_rules {
        Rule(bracket[1] .. ' ', ' ' .. bracket[2])
            :with_pair(function() return false end)
            :with_move(function(opts)
              return opts.prev_char:match('.%' .. bracket[2]) ~= nil
            end)
            :use_key(bracket[2])
      }
    end
  end
}
```

**Comment by mehalter** [comment]
Hm the unfortunate thing about this is that if we do that in the `setup` call and someone wants to keep adding rules, by adding a custom `setup` function it will override the default so you will lose that behavior. I think this could be formed as a request to the plugin itself as additional it as a default rule that they set up though!
