### ISSUE TITLE
Braces rare behaviour on strings with emoji

### ISSUE THREAD

**Issue by serranomorante** [AstroNvim/AstroNvim#1797]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Windows 10 Home (latest version) WSL2

### Terminal/GUI

wezterm

### AstroNvim Health

```bash
   2 astronvim: require("astronvim.health").check()
   3
   4 AstroNvim
   5 - AstroNvim Version: v3.10.3
   6 - Neovim Version: v0.9.0
   7 - OK Using stable Neovim >= 0.8.0
   8 - OK git is installed: Used for core functionality such as updater and plugin management
   9 - WARNING xdg-open/open/explorer is not installed: Used for gx mapping for opening files with system opener (Optional)
  10 - OK lazygit is installed: Used for mappings to pull up git TUI (Optional)
  11 - OK node is installed: Used for mappings to pull up node REPL (Optional)
  12 - OK gdu is installed: Used for mappings to pull up disk usage analyzer (Optional)
  13 - OK btm is installed: Used for mappings to pull up system monitor (Optional)
  14 - OK python3 is installed: Used for mappings to pull up python REPL (Optional)
```

### Describe the bug

![wezterm-gui_20230420_142434_748](https://user-images.githubusercontent.com/43413954/233367827-631eeecf-89cf-44e5-b8b3-26a737c57196.gif)

Braces behave strangely on large strings that have emojis on them.

### Steps to Reproduce

1. Try to edit the following text in astronvim
```javascript
export const test = {
  test: 'This is a test {{1}} and 👋🏻 the second part {{2}} and the rest is a very ✅ long string and the rest is a very long string and the rest is a very long string and the 😁 rest is a very long string and the rest is a very long string and the rest is a very long string and the rest is a very long string'
}
```
2. If you navigate character by character to the left, you will encounter the problem when you reach the second placeholder `{{2}}`

### Expected behavior

I should be able to navigate and edit the second placeholder `{{2}}` without problems.

**Comment by mehalter** [comment]
Huh, what language servers and stuff do you have showing as attached and what filetype is this? Also do you have treesitter attached as well? Just helpful in being able to try and replicate this.

**Comment by serranomorante** [comment]
> Huh, what language servers and stuff do you have showing as attached and what filetype is this? Also do you have treesitter attached as well? Just helpful in being able to try and replicate this.

Thank you!

Is a `javascript` file with `.js` extension. The buffer shows `prettierd` and `tsserver` at the bottom.

My user config is:
On `treesitter.lua` I only have this: `ensure_installed = { "lua", "javascript", "jsdoc", "tsx", "typescript" }`
On `mason.lua` I only have this: `ensure_installed = { "lua_ls", "tsserver" }` for LSP and `ensure_installed = { "prettierd", "stylua" },` for null-ls.

**Comment by serranomorante** [comment]
> Hm I cannot seem to replicate this 🤔

You're right. It seems not to be related to Astronvim but to vim in general. Apparently this behavior occurs due to a disagreement between the terminal and the editor on how wide emoji characters should be.

This is well explained on this [video](https://www.youtube.com/watch?v=F91VWOelFNE). The solution from that video didn't actually work for me.

I just tried different terminals: `cmd.exe`, `alacritty`, `windows terminal`, `iterm2`. I think they all worked but at the cost of not displaying the emoji.

It was a more difficult problem than I initially thought.

Thanks for your help!
