### ISSUE TITLE
hlslens support

### ISSUE THREAD

**Issue by kevinkirkup** [AstroNvim/AstroNvim#1798]
### Is your feature related to a problem?

No

### Describe the new feature

Include "kevinhwang91/nvim-hlslens" as part of the Astrovim bistro.

### Additional context

It looks like Astrovim includes a number of `kevinhwang91`'s nvim plugins.
I'm wondering if you would include this one as well.

I'm willing to contribute if needed.

**Comment by mehalter** [comment]
We show this information by default in the stratus line and this also conflicts with noice which a lot of people use. This would be a great contribution to AstroCommunity though please make a PR!
