### ISSUE TITLE
lsp can't auto-complete python import module

### ISSUE THREAD

**Issue by duanyuluo** [AstroNvim/AstroNvim#1799]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.4

### Terminal/GUI

iTerm

### AstroNvim Health

astronvim: require("astronvim.health").check()
========================================================================
## AstroNvim
  - INFO: AstroNvim Version: v3.10.3
  - INFO: Neovim Version: v0.8.3
  - OK: Using stable Neovim >= 0.8.0
  - OK: `git` is installed: Used for core functionality such as updater and plugin management
  - OK: `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
  - OK: `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
  - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
  - WARNING: `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
  - OK: `btm` is installed: Used for mappings to pull up system monitor (Optional)
  - OK: `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

install pyright and jedi lsp server
auto complete of current workspace is OK
auto complete of import 3rd can NOT work

### Steps to Reproduce

# pyright and jedi are working
import EV3Brick
ev3 = EV3Brick.hub
ev3.  #  <- can't auto complete or sugguestions

### Expected behavior

should popup the suggestions list of this module

### Screenshots

<img width="393" alt="Screenshot 2023-04-21 at 11 45 06" src="https://user-images.githubusercontent.com/4272707/233536112-ea17c75d-a677-47a2-9f1e-be8084ac3850.png">

**Comment by mehalter** [comment]
Make sure to activate your Virtual environment before opening AstroNvim. If you have any other questions regarding configuring Pyright or Jedi, I would recommend asking the discord as there are many helpful people who can help guide you.

Calculating the autocompletion comes from the language server and not AstroNvim, so this is not a bug in AstroNvim.
