### ISSUE TITLE
Copilot keymap don't work?

### ISSUE THREAD

**Issue by seriiserii825** [AstroNvim/AstroNvim#1800]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

ubuntu 22.04

### Terminal/GUI

xfce

### AstroNvim Health

   4 ## AstroNvim
    5   - INFO: AstroNvim Version: v3.10.3
    6   - INFO: Neovim Version: v0.8.1
    7   - OK: Using stable Neovim >= 0.8.0
    8   - OK: `git` is installed: Used for core functionality such as updater and plugin management
    9   - OK: `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
   10   - OK: `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
   11   - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
   12   - WARNING: `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
   13   - WARNING: `btm` is not installed: Used for mappings to pull up system monitor (Optional)
   14   - OK: `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

This keybinding for copilot doesn't work
```
return {
  n = {
    ["b"] = { "<Plug>Sneak_S", desc = "Sneak back" },
    ["<M-l>"] = { ":wa<CR>", desc = "close all" },
    ["<S-l>"] = {
      function() require("astronvim.utils.buffer").nav(vim.v.count > 0 and vim.v.count or 1) end,
      desc = "Next buffer",
    },
    ["<S-h>"] = {
      function() require("astronvim.utils.buffer").nav(-(vim.v.count > 0 and vim.v.count or 1)) end,
      desc = "Previous buffer",
    },
  },
  i = {
    ["<C-i>"] = { "<Plug>copilot#Accept('<CR>')" }
  }
}

```

### Steps to Reproduce

In documentation, or :Copilot help is an instruction
```
imap <silent><script><expr> <C-J> copilot#Accept("\<CR>")
let g:copilot_no_tab_map = v:true

```
The map i added
```
    ["<C-i"] = { "<Plug>copilot#Accept('<CR>')" }

```

And the option
```
was
let g:copilot_no_tab_map = v:true
    
local_vim.g['copilot_no_tab_map'] = "v:true"

```

### Expected behavior

To make copilot expand keybinding works

**Comment by mehalter** [comment]
There is a typo in your code `<C-i` should be `<C-i>`

**Comment by slowsage** [comment]
nvim-cmp has a conflict. This works for me (from [nvim-cmp](https://github.com/hrsh7th/nvim-cmp/blob/b16e5bcf1d8fd466c289eab2472d064bcd7bab5d/doc/cmp.txt#L830-L852)).
```
  plugins = {
   {
      "hrsh7th/nvim-cmp",
      opts = function(_, opts)
        local cmp = require "cmp"
        opts.mapping["<C-Right>"] = cmp.mapping(
          function(_)
            vim.api.nvim_feedkeys(
              vim.fn["copilot#Accept"](vim.api.nvim_replace_termcodes("<Tab>", true, true, true)),
              "n",
              true
            )
          end
        )
        opts.experimental = { ghost_text = false }
        return opts
      end,
    },
  }
```
