### ISSUE TITLE
neo-tree tabs (sources) are randomly ordered

### ISSUE THREAD

**Issue by karlivory** [AstroNvim/AstroNvim#1802]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Linux 5.19.0-40-generic #41~22.04.1-Ubuntu

### Terminal/GUI

st

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: v3.10.3
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- WARNING `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

For me, neo-tree tabs (sources: Git, File, Bufs) are randomly ordered. This happens with no custom neo-tree config.

### Steps to Reproduce

1. open nvim
2. run :Neotree
3. observe order of sources
4. close nvim
5. repeat

### Expected behavior

Deterministically ordered neo-tree sources (e.g. File, Git, Bufs)

### Screenshots

![2023-04-21_16-46](https://user-images.githubusercontent.com/5895483/233652766-5725f330-98b2-4bd3-8d2d-ab53df1054f8.png)
![2023-04-21_16-49](https://user-images.githubusercontent.com/5895483/233653116-5c9e3b53-5e81-44d7-9f45-ead18ac7044e.png)

**Comment by whoop-t** [comment]
This has been discussed here on discord:
https://discord.com/channels/939594913560031363/1097830839515090996

Looks like neotree made changes that altered things

**Comment by mehalter** [comment]
This will be resolved in v3.11.0 as the fix is in Nightly.

**Comment by shibotto** [comment]
How about a 3.10.4 pinning down neo-tree to the last working version in the meantime?

**Comment by mehalter** [comment]
The next release will be on Monday :) so no worries. I would definitely let the `neo-tree` people know that their minor release was breaking and didn't follow semantic versioning. Which is unrelated to version management in AstroNvim

**Comment by mehalter** [comment]
Closed with v3.11.0
