### ISSUE TITLE
how to manage each language null-ls in a single dict?

### ISSUE THREAD

**Issue by chaozwn** [AstroNvim/AstroNvim#1805]
### Is your feature related to a problem?

i think astronvim should like lunarvim, approve a ftpplugin dict for us to set up single language .

when i write react , it provide a eslint format , before i use prettier. so when i write tsx, i have two format file by two formatter.

### Describe the new feature

i want have a plugin to set language config in a single file.

**Comment by chaozwn** [comment]
> Can you please point me to like a LunarVim documentation page to help explain what you mean?

https://www.lunarvim.org/docs/configuration/ftplugin

**Comment by mehalter** [comment]
Ah I see, yeah `ftplugin` is actually a core feature of Neovim/Vim. You can definitely use this with AstroNvim if you prefer. You can just make an `after/` folder just like in that documentation page you linked and it will work as you expect.

We also have stuff like our formatting engine that lets you control when different formatters are used in different situations: https://astronvim.com/Recipes/advanced_lsp#controlling-formatting

These things can also be configured through null-ls or mason-null-ls or the language servers themselves directly.
