### ISSUE TITLE
Default install missing default mappings

### ISSUE THREAD

**Issue by engineersamuel** [AstroNvim/AstroNvim#1810]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 11.5

### Terminal/GUI

Alacritty

### AstroNvim Health

- AstroNvim Version: v3.10.3
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

I followed the standard install for AstroNvim, I used to be Lunarvim user where I could `gd` to jump to definition, i.e. if the function is defined in a separate file and and you `gd` you jump to that definition in that other file.  And AstroNvim shows this as an out of the box mapping:

![image](https://user-images.githubusercontent.com/2019830/234074652-84548f00-13ee-47dd-8f81-e8f439d44e68.png)

However, if I type `g` in AstoNvim I see:

  
![image](https://user-images.githubusercontent.com/2019830/234074781-35562ae3-5c83-46c2-8181-c7b130bfd84b.png)

which is missing the `d`, `D`, `T` and others.

And when I type `gd` on a function, it jumps to the import and not the definition.

### Steps to Reproduce

Default AstroNvim install and `gd` on a function, it jumps to import and not definition in a separate file.

### Expected behavior

`gd` should jump to the actual definition and not the import.

**Comment by engineersamuel** [comment]
Yep, that was it!  Thank you for the quick response, that makes 100% sense when you describe it but a bit confusing coming from other platforms, I wonder if this comment, which perfectly explained it, could be added to the docs?

**Comment by mehalter** [comment]
Yeah definitely, that would be a really good addition to the documentation!
