### ISSUE TITLE
Failed to load `user.plugins.treesitter`

### ISSUE THREAD

**Issue by hmajid2301** [AstroNvim/AstroNvim#1815]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macos 13.2.1

### Terminal/GUI

alacritty

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.10.2
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

When I open nvim I get the following error:

```
Error detected while processing /Users/haseeb/.config/nvim/init.lua:
Failed to load `user.plugins.treesitter`

...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/plugin.lua:271: module 'user.plugins.treesitter' not found:
^Ino field package.preload['user.plugins.treesitter']
cache_loader: module user.plugins.treesitter not found
cache_loader_lib: module user.plugins.treesitter not found
^Ino file './user/plugins/treesitter.lua'
^Ino file '/usr/local/share/luajit-2.1.0-beta3/user/plugins/treesitter.lua'
^Ino file '/usr/local/share/lua/5.1/user/plugins/treesitter.lua'
^Ino file '/usr/local/share/lua/5.1/user/plugins/treesitter/init.lua'
^Ino file './user/plugins/treesitter.so'
^Ino file '/usr/local/lib/lua/5.1/user/plugins/treesitter.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
^Ino file './user.so'
^Ino file '/usr/local/lib/lua/5.1/user.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'

# stacktrace:
  - .config/nvim/lua/astronvim/lazy.lua:33
  - .config/nvim/init.lua:10
```

### Steps to Reproduce

1. open alacritty
2. type `nvim`
3. There is pop up window with the above error

### Expected behavior

That there wouldn't be any errors

### Screenshots

![image](https://user-images.githubusercontent.com/998807/234236739-f7ed1b84-5aa7-4f10-9356-43efb7ea9816.png)

### Additional Context

Dotfiles: https://gitlab.com/hmajid2301/dotfiles/-/tree/main/nvim

Tree sitter is available as a binary on my system:

```
❯ which tree-sitter
/usr/local/bin/tree-sitter
```

Any help would be grealy appreciated thanks.

**Comment by mehalter** [comment]
Just did a fresh installation of your user configuration into a clean installation of AstroNvim and it seems to work aas intended. I noticed you are maintaining basically a full fork in your repo which is an unsupported method of doing things. It could be that your clone of AstroNvim is out of date or you just have some messed up cache files. I would recommend:

1. try a clean installation and clear out your data and cache folders
2. separate your user configuration from your astronvim installation to guarantee you aren't editing anything outside of the user configuration

**Comment by hmajid2301** [comment]
Okay thanks! Will try that.
