### ISSUE TITLE
Lost keyboard mapping configuration when using user config to configure nvim-cmp

### ISSUE THREAD

**Issue by vvtommy** [AstroNvim/AstroNvim#1817]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 11.5

### Terminal/GUI

wezterm

## AstroNvim
  - INFO: AstroNvim Version: v3.11.1
  - INFO: Neovim Version: v0.8.3
  - OK: Using stable Neovim >= 0.8.0
  - OK: `git` is installed: Used for core functionality such as updater and plugin management
  - OK: `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
  - OK: `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
  - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
  - WARNING: `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
  - WARNING: `btm` is not installed: Used for mappings to pull up system monitor (Optional)
  - OK: `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

When I configure nvim-cmp in `user/plugin/cmp.lua`, it fails to work after startup about 80% of the time. The same configuration works perfectly fine when directly modified in `<astromvim root>/plugins/cmp.lua`.

`user/plugin/cmp.lua` example:
```lua
return {
  "hrsh7th/nvim-cmp",
  event = "InsertEnter",
  opts = function(_, opts)
    local cmp = require("cmp")
    opts.mapping["<TAB>"] = cmp.mapping(function(_)
      vim.notify('<TAB> pressed')
    end, { "i", "s" })

    vim.notify('nvim-cmp user config loaded')
    return opts
  end,
}
```

### Steps to Reproduce

1. `git clone --depth 1 https://github.com/AstroNvim/user_example ~/.config/nvim/lua/user`
2. Create `user/plugins/cmp.lua` using the code above.
3. Reopen neovim, enter insert mode and press the <TAB> key. If a bug occurs (which does not happen 100% of the time): The above configuration will be ignored and tab characters will be inserted directly.

### Expected behavior

1. After entering Insert mode, you can see the notification "nvim-cmp user config loaded".
2. Pressing <TAB> will show the notification "TAB pressed".

**Comment by mehalter** [comment]
I cannot replicate this. following your steps it works every time. Also if this was a bug then this would be something in Lazy.nvim since that is the package manager that handles the overriding. Although, I would recommend you take a deep look at your user configuration and maybe ask on the Discord before you open up an issue on Lazy because I'm very certain they don't have any bugs in the overriding of the plugin configurations/options.
