### ISSUE TITLE
Find file whose name is the word under cursor

### ISSUE THREAD

**Issue by kaka-ruto** [AstroNvim/AstroNvim#1823]
### Is your feature related to a problem?

Whenever I have a class called from somewhere, and I need to find the class' file, I will copy the class name, open telescope and paste.

### Describe the new feature

It would be nice if, just like searching for a word under cursor, we could similarly have a mapping that finds a file whose name is the word under cursor

**Comment by mehalter** [comment]
Are you using a language server? This is typically handled by a language server and using bindings to search for references to that variable/class/type/etc. or bindings to go to definition/declaration/etc.

**Comment by mehalter** [comment]
I think for the general case of going to class files things such as language servers are a good option. I'm not sure if this feature exists in Telescope, but you could take a look at the Telescope documentation for adding a new binding to your user configuration: https://github.com/nvim-telescope/telescope.nvim

If you find some sort of really nice binding that fits in the methodology of AstroNvim, you could open up a PR and I could take a look and see how the utility is. But I don't think that this is a feature I necessarily see as needing to be added at the moment.
