### ISSUE TITLE
LSPs don't run on >=3.11.2

### ISSUE THREAD

**Issue by praveenperera** [AstroNvim/AstroNvim#1825]
### Describe the bug

On 3.11.1 the LSPs load fine no problems. 

After 3.11.2 LSPs do not load, and they are not listed in `:LspInfo`

My init.lua: https://github.com/praveenperera/dotfiles/blob/master/nvim/init.lua

Maybe its related to this commit: https://github.com/AstroNvim/AstroNvim/commit/fffc9e3bd742b5cf1533cfa9c5399fc790d7240b

**Comment by mehalter** [comment]
Make sure to update to 3.11.3 as this fixed 3.11.2 because the commit for mason lspconfig was updated

**Comment by praveenperera** [comment]
Hey I tried from master, 3.11.3, 3.11.2, 3.11.1, everything after 3.11.1 do not work.

**Comment by mehalter** [comment]
Did you make sure to update your plugins with Lazy to get the new pinned version of Mason Lspconfig?

**Comment by praveenperera** [comment]
Yes did "Update plugins and mason"

https://github.com/AstroNvim/AstroNvim/compare/v3.11.1...v3.11.3 shows the config is changed

**Comment by mehalter** [comment]
I see your error. Your `mason_lspconfig` function is not extending the base mason-lspconfig. You are completely replacing it. So you are removing the handlers. I would recommend taking a look at how the mason opts extension works and see if you are accidentally overwriting things that you aren't meaning to.

Here is what you want your `config/mason_lspconfig.lua` file to look like:

```lua
local default = {}

local function config(_, opts)
    opts.ensure_installed = {
        "rust_analyzer",
        "lua_ls",
        "tsserver",
        "tflint",
        "tailwindcss",
    }
end

default.config = config
return default
```

**Comment by praveenperera** [comment]
Ah I see my mistake, that fixed it. Thanks
