### ISSUE TITLE
Silence Repeated Errors

### ISSUE THREAD

**Issue by half-potato** [AstroNvim/AstroNvim#1827]
### Is your feature related to a problem?

Often, when something is wrong with how the file is being parsed, the same error will get spammed over and over again, filling my screen with garbage. One such error is this: https://github.com/jose-elias-alvarez/null-ls.nvim/issues/428

### Describe the new feature

There should be a way to detect that the same error has been emitted and silence it, so it is not repeated again.

**Comment by mehalter** [comment]
The linked issue is a result of a misconfiguration of your language server. I would definitely recommend you asking about specific errors on the discord and people can help you configure the language server. Any other errors are not things we are handling and are unrelated to the core AstroNvim code. We have recently done something similar related to all language server errors resulting from our own autocmds (v3.11.4) but outside of that we cannot control this.

**Comment by mehalter** [comment]
See #1822 for a similar issue

**Comment by mehalter** [comment]
#1013 is an example of fixing the offset error you linked.
