### ISSUE TITLE
error prompt can't show completely

### ISSUE THREAD

**Issue by lazywhite** [AstroNvim/AstroNvim#1828]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

ubuntu 22.10

### Terminal/GUI

terminator

## AstroNvim
  - INFO: AstroNvim Version: v3.11.4
  - INFO: Neovim Version: v0.8.2
  - OK: Using stable Neovim >= 0.8.0
  - OK: `git` is installed: Used for core functionality such as updater and plugin management
  - OK: `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
  - WARNING: `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
  - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
  - WARNING: `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
  - WARNING: `btm` is not installed: Used for mappings to pull up system monitor (Optional)
  - OK: `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

![Screenshot from 2023-04-27 11-33-57](https://user-images.githubusercontent.com/17612898/234753109-64109db5-d528-4161-9c7c-9d79a97dbb54.png)

as you can see, line 73 error prompt can't show completely, content jumped out of my LCD

## here is my source code
```
package main

import (
	"bufio"
	"context"
	"fmt"

	"github.com/docker/docker/api/types"
	"github.com/docker/docker/api/types/container"
	"github.com/docker/docker/api/types/mount"
	"github.com/docker/docker/api/types/network"
	"github.com/docker/docker/api/types/strslice"
	"github.com/docker/docker/client"
	"github.com/google/uuid"
)

func main() {
	cli, err := client.NewEnvClient()
	if err != nil {
		panic(err)
	}

	cnt, err := cli.ContainerCreate(
		context.Background(),
		&container.Config{
			Image:        "alpine:3.16",
			Entrypoint:   strslice.StrSlice{"sh", "-c", "echo done"},
			Tty:          true,
			AttachStdout: true,
			AttachStderr: true,
		},
		&container.HostConfig{
			Mounts: []mount.Mount{
				{
					Type:   mount.TypeBind,
					Source: "/tmp",
					Target: "/tmp",
				},
			},
		},
		&network.NetworkingConfig{},
		"sampctl-"+uuid.New().String())
	if err != nil {
		panic(err)
	}

	fmt.Println("Starting container...")
	err = cli.ContainerStart(context.Background(), cnt.ID, types.ContainerStartOptions{})
	if err != nil {
		panic(err)
	}

	fmt.Println("Warnings:", cnt.Warnings)
	go func() {
		reader, err := cli.ContainerLogs(context.Background(), cnt.ID, types.ContainerLogsOptions{
			ShowStdout: true,
			ShowStderr: true,
			Follow:     true,
			Timestamps: false,
		})
		if err != nil {
			panic(err)
		}
		defer reader.Close()

		scanner := bufio.NewScanner(reader)
		for scanner.Scan() {
			fmt.Println(scanner.Text())
		}
	}()

	// for now, we just wait for the app to exit and prints logs afterwards
	n, err := cli.ContainerWait(context.Background(), cnt.ID)
	fmt.Println("container exited:", n, err)

	return
}
```

### Expected behavior

error prompt shoud wrap correctly

**Comment by mehalter** [comment]
This is not a feature of Neovim. You can use a plugin such as lsp_lines.nvim (https://sr.ht/~whynothugo/lsp_lines.nvim/) to achieve this. Or you can use the diagnostic hover bindings in AstroNvim to read the entire diagnostic message
