### ISSUE TITLE
Indenting in visual mode doesn't stay in visual mode

### ISSUE THREAD

**Issue by minhd-vu** [AstroNvim/AstroNvim#1837]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.3.1

### Terminal/GUI

iTerm2

### AstroNvim Health

```
  2   astronvim: require("astronvim.health").check()
  3
  4   AstroNvim
  5   - AstroNvim Version: v3.12.1
  6   - Neovim Version: v0.9.0
  7   - OK Using stable Neovim >= 0.8.0
  8   - OK git is installed: Used for core functionality such as updater and plugin management
  9   - OK open is installed: Used for gx mapping for opening files with system opener (Optional)
 10   - OK lazygit is installed: Used for mappings to pull up git TUI (Optional)
 11   - OK node is installed: Used for mappings to pull up node REPL (Optional)
 12   - OK gdu is installed: Used for mappings to pull up disk usage analyzer (Optional)
 13   - WARNING btm is not installed: Used for mappings to pull up system monitor (Optional)
 14   - OK python is installed: Used for mappings to pull up python REPL (Optional)
```

### Describe the bug

When using the `<` and `>` in visual mode to indent blocks, it will exit visual mode and deselect after the first `>` or `<`. Historically, it would have kept the selection to allow you to press the `<` or `>` again.

### Steps to Reproduce

1. Visual select something (or visual block)
2. Use `<` or `>`

### Expected behavior

The visual selection would have been kept and not cleared.

**Comment by mehalter** [comment]
This is default Vim/Neovim behavior and not a bug. We have tab/shift-tab as bindings for doing this in visual mode. But just to let you know, this is completely standard and the tab/shift-tab bindings are not.
