### ISSUE TITLE
Relative line numbers repeat and inconsistent movement behavior when line wrap is enabled

### ISSUE THREAD

**Issue by Subjective** [AstroNvim/AstroNvim#1840]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.3

### Terminal/GUI

kitty

### AstroNvim Health

```
==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: nightly (v3.10.3-9-g1210b4a)
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)
```

### Describe the bug

When relativelinenumber and line wrapping is enabled, line numbers repeat. Additionally, when movement commands are combined with number modifiers (e.g. 5j), the cursor moves to the fifth line down, not the fifth wrapped line as one might assume from the indicated relative line numbers.

### Steps to Reproduce

1. `:set wrap`

### Expected behavior

For a wrapped line, I would expect the line number to appear only once instead of repeating for each line within the wrap. I would also expect movement modifiers to use the indicated relative line numbers while navigating through wrapped lines, instead of the visible lines in the editor.

### Screenshots

Current behavior:
![image](https://user-images.githubusercontent.com/56745535/235414586-53ab80c5-bbfc-40ea-aa32-2cc215f1a6fe.png)

Expected behavior:
![image](https://user-images.githubusercontent.com/56745535/235414634-b5e72752-5275-435d-b713-124f0557e9ae.png)

**Comment by mehalter** [comment]
The number stuff seems to be a limitation with the built in statusline components that neovim provides which is a shame. I have made a commit to `nightly` that just implements our own number calculation function by hand and also let us add in some more customization features as well.

Also thanks for catching the bug in our `j`/`k` mapping! I have resolved this as well on nightly. This new feature + bug fix will be released with v3.13.0
