### ISSUE TITLE
Heirline error when using Omnisharp lsp

### ISSUE THREAD

**Issue by awyl** [AstroNvim/AstroNvim#1847]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

linux

### Terminal/GUI

kitty

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.13.2
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- WARNING `python/python3` is not installed: Used for mappings to pull up python REPL (Optional)

==============================================================================
gitsigns: require("gitsigns.health").check()

- OK git version 2.39.2

==============================================================================
lazy: require("lazy.health").check()

lazy.nvim ~
- OK Git installed
- OK no existing packages found by other package managers
- OK packer_compiled.lua not found

==============================================================================
mason: require("mason.health").check()

mason.nvim ~
- OK mason.nvim version v1.0.1
- OK neovim version >= 0.7.0

mason.nvim [Registries] ~
- OK Registry `github.com/mason-org/mason-registry version: 2023-05-01-wiggly-buffer` is installed.

mason.nvim [Core utils] ~
- OK unzip: `UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send`
- WARNING wget: not available
  - ADVICE:
    - spawn: wget failed with exit code - and signal -. wget is not executable
- OK curl: `curl 8.0.1 (x86_64-pc-linux-gnu) libcurl/8.0.1 OpenSSL/3.0.8 zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 libidn2/2.3.4 libssh2/1.10.0 nghttp2/1.51.0`
- OK gzip: `gzip 1.12`
- OK tar: `tar (GNU tar) 1.34`
- OK bash: `GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu)`
- OK sh: `Ok`

mason.nvim [Languages] ~
- WARNING Go: not available
  - ADVICE:
    - spawn: go failed with exit code - and signal -. go is not executable
- WARNING Composer: not available
  - ADVICE:
    - spawn: composer failed with exit code - and signal -. composer is not executable
- WARNING PHP: not available
  - ADVICE:
    - spawn: php failed with exit code - and signal -. php is not executable
- WARNING luarocks: not available
  - ADVICE:
    - spawn: luarocks failed with exit code - and signal -. luarocks is not executable
- OK node: `v18.15.0`
- WARNING javac: not available
  - ADVICE:
    - spawn: javac failed with exit code - and signal -. javac is not executable
- WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. julia is not executable
- WARNING python3: not available
  - ADVICE:
    - spawn: python3 failed with exit code - and signal -. python3 is not executable
- OK cargo: `cargo 1.69.0 (6e9a83356 2023-04-12)`
- WARNING java: not available
  - ADVICE:
    - spawn: java failed with exit code - and signal -. java is not executable
- WARNING pip3: not available
  - ADVICE:
    - spawn: python3 failed with exit code - and signal -. python3 is not executable
- OK Ruby: `ruby 2.7.8p225 (2023-03-30 revision 1f4d455848) [x86_64-linux]`
- OK python3_host_prog: `Python 3.10.10`
- WARNING python3_host_prog pip: not available
  - ADVICE:
    - spawn: /nix/store/js5lvdxc7afj3qiknnjfqgagk62fpk80-neovim-0.9.0/bin/nvim-python3 failed with exit code 1 and signal 0. /nix/store/zg3qdm7pc9p1pq8kgsba9aplmy6a9hr8-python3-3.10.10-env/bin/python3.10: No module named pip

- OK RubyGem: `3.4.8`
- OK npm: `9.5.0`

mason.nvim [GitHub] ~
- OK GitHub API rate limit. Used: 2. Remaining: 58. Limit: 60. Reset: Mon 01 May 2023 06:49:31 PM EDT.
  Install and authenticate via gh-cli to increase rate limit.

==============================================================================
null-ls: require("null-ls.health").check()

- OK stylua: the command "stylua" is executable.
- OK prettierd: the command "prettierd" is executable.
- OK rustywind: the command "rustywind" is executable.

==============================================================================
nvim: require("nvim.health").check()

Configuration ~
- OK no issues found

Runtime ~
- OK $VIMRUNTIME: /nix/store/x55yfs57l7bm6ms0584lhwiz7h1zxr7n-neovim-unwrapped-0.9.0/share/nvim/runtime

Performance ~
- OK Build type: Release

Remote Plugins ~
- OK Up to date

terminal ~
- key_backspace (kbs) terminfo entry: `key_backspace=\177`
- key_dc (kdch1) terminfo entry: `key_dc=\E[3~`
- $TERM_PROGRAM="tmux"
- $COLORTERM="truecolor"
- $SSH_TTY="/dev/pts/1"

tmux ~
- OK escape-time: 0
- OK focus-events: on
- $TERM: tmux-256color

==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v18.15.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `gcc` executable found. Selected from { "gcc", "cc", "gcc", "clang", "cl", "zig" }
  Version: gcc (GCC) 12.2.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.2.12",
  sysname = "Linux",
  version = "#1-NixOS SMP PREEMPT_DYNAMIC Thu Apr 20 10:37:00 UTC 2023"
} ~

Parser/Features         H L F I J
  - c_sharp             ✓ ✓ ✓ . ✓
  - css                 ✓ . ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luap                ✓ . . . .
  - markdown            ✓ . ✓ . ✓
  - markdown_inline     ✓ . . . ✓
  - nix                 ✓ ✓ ✓ . ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

==============================================================================
provider: health#provider#check

Clipboard (optional) ~
- OK Clipboard tool found: xclip

Python 3 provider (optional) ~
- Using: g:python3_host_prog = "/nix/store/js5lvdxc7afj3qiknnjfqgagk62fpk80-neovim-0.9.0/bin/nvim-python3"
- Executable: /nix/store/js5lvdxc7afj3qiknnjfqgagk62fpk80-neovim-0.9.0/bin/nvim-python3
- Python version: 3.10.10
- pynvim version: 0.4.3
- OK Latest pynvim is installed.

Python virtualenv ~
- OK no $VIRTUAL_ENV

Ruby provider (optional) ~
- Ruby: ruby 2.7.8p225 (2023-03-30 revision 1f4d455848) [x86_64-linux]
- Host: /nix/store/js5lvdxc7afj3qiknnjfqgagk62fpk80-neovim-0.9.0/bin/nvim-ruby
- OK Latest "neovim" gem is installed: 0.9.0

Node.js provider (optional) ~
- Disabled (g:loaded_node_provider=0).

Perl provider (optional) ~
- WARNING "Neovim::Ext" cpan module is not installed
  - ADVICE:
    - See :help |provider-perl| for more information.
    - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.7.0

===== Installed extensions ===== ~

Telescope Extension: `aerial` ~
- No healthcheck provided

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured

Telescope Extension: `notify` ~
- No healthcheck provided

==============================================================================
vim.lsp: require("vim.lsp.health").check()

- LSP log level : WARN
- Log path: /home/awyl/.local/state/nvim/lsp.log
- Log size: 8276 KB

vim.lsp: Active Clients ~
- omnisharp (id=1, root_dir=/home/awyl/codebase/nyccom/nycweb2017)

==============================================================================
vim.treesitter: require("vim.treesitter.health").check()

- Nvim runtime ABI version: 14
- OK Parser: c_sharp    ABI: 14, path: /home/awyl/.local/share/nvim/lazy/nvim-treesitter/parser/c_sharp.so
- OK Parser: css        ABI: 13, path: /home/awyl/.local/share/nvim/lazy/nvim-treesitter/parser/css.so
- OK Parser: json       ABI: 14, path: /home/awyl/.local/share/nvim/lazy/nvim-treesitter/parser/json.so
- OK Parser: jsonc      ABI: 13, path: /home/awyl/.local/share/nvim/lazy/nvim-treesitter/parser/jsonc.so
- OK Parser: lua        ABI: 13, path: /home/awyl/.local/share/nvim/lazy/nvim-treesitter/parser/lua.so
- OK Parser: luap       ABI: 14, path: /home/awyl/.local/share/nvim/lazy/nvim-treesitter/parser/luap.so
- OK Parser: markdown   ABI: 13, path: /home/awyl/.local/share/nvim/lazy/nvim-treesitter/parser/markdown.so
- OK Parser: markdown_inline ABI: 13, path: /home/awyl/.local/share/nvim/lazy/nvim-treesitter/parser/markdown_inline.so
- OK Parser: nix        ABI: 13, path: /home/awyl/.local/share/nvim/lazy/nvim-treesitter/parser/nix.so
- OK Parser: rust       ABI: 14, path: /home/awyl/.local/share/nvim/lazy/nvim-treesitter/parser/rust.so
- OK Parser: toml       ABI: 13, path: /home/awyl/.local/share/nvim/lazy/nvim-treesitter/parser/toml.so

==============================================================================
which-key: require("which-key.health").check()

WhichKey: checking conflicting keymaps ~
- WARNING conflicting keymap exists for mode **"o"**, lhs: **"a"**
- rhs: `v:lua.MiniAi.expr_textobject('o', 'a')`
- WARNING conflicting keymap exists for mode **"o"**, lhs: **"i"**
- rhs: `v:lua.MiniAi.expr_textobject('o', 'i')`
- WARNING conflicting keymap exists for mode **"v"**, lhs: **"<leader>l"**
- rhs: ` `
- WARNING conflicting keymap exists for mode **"v"**, lhs: **"a"**
- rhs: `v:lua.MiniAi.expr_textobject('x', 'a')`
- WARNING conflicting keymap exists for mode **"v"**, lhs: **"i"**
- rhs: `v:lua.MiniAi.expr_textobject('x', 'i')`
- WARNING conflicting keymap exists for mode **"n"**, lhs: **" x"**
- rhs: ` `
- OK No conflicting keymaps found

### Describe the bug

When using `omnisharp` lsp, the error below is shown right after the lsp is loaded and whenever enter into insert mode.

### Steps to Reproduce

1. nvim
2. load a `.cs` file
3. wait until omnisharp loaded
4. press `i`, and enter some characters.

### Expected behavior

no error.

### Additional Context

Error shown on screen, when the error occurred.  

```
Error executing vim.schedule lua callback: /home/awyl/.config/nvim/lua/astronvim/utils/status.lua:1224: Vim:E5108: Error executing lua ...ocal/share/nvim/lazy/heirline.nvim/lua/heirl
ine/init.lua:134: Vim:E5108: Error executing lua vim/_meta.lua:0: Vim:E5108: Error executing lua vim/_meta.lua:0: Vim:E5108: Error executing lua vim/_meta.lua:0: Vim:E5108: Error exe
cuting lua vim/_meta.lua:0: Vim:E5108: Error executing lua vim/_meta.lua:0: Vim:E5108: Error executing lua vim/_meta.lua:0: Vim:E5108: Error executing lua vim/_meta.lua:0: Vim:E5108:
 Error executing lua vim/_meta.lua:0: Vim:E5108: Error executing lua vim/_meta.lua:0: Vim:E5108: Error executing lua vim/_meta.lua:0: Vim:E5108: Error executing lua vim/_meta.lua:0:
Vim:E5108: Error executing lua vim/_meta.lua:0: Vim:E5108: Error executing lua vim/_meta.lua:0: Vim:E5108: Error executing lua vim/_meta.lua:0: Vim:E5108: Error executing lua vim/_me
ta.lua:0: Vim:E5108: Error executing lua vim/_meta.lua:0: Vim:E5108: Error executing lua vim/_meta.lua:0: Vim:E5108: Error executing lua vim/_meta.lua:0: Vim:E5108: Error executing l
ua vim/_meta.lua:0: Vim:E5108: Error executing lua vim/_meta.lua:0: Vim:E5108: Error executing lua vim/_meta.lua:0: Vim:E5108: Error executing lua vim/_meta.lua:0: Vim:E5108: Error e
xecuting lua vim/_meta.lua:0: Vim:E5248: Invalid character in group name
stack traceback:
        [C]: in function 'nvim_get_option_value'
        vim/_meta.lua: in function '__index'
        /home/awyl/.config/nvim/lua/astronvim/utils/status.lua:924: in function 'condition'
        ...hare/nvim/lazy/heirline.nvim/lua/heirline/statusline.lua:284: in function '_eval'
        ...hare/nvim/lazy/heirline.nvim/lua/heirline/statusline.lua:365: in function '_eval'
        ...hare/nvim/lazy/heirline.nvim/lua/heirline/statusline.lua:440: in function <...hare/nvim/lazy/heirline.nvim/lua/heirline/statusline.lua:439>
        [C]: in function 'redrawstatus'
        /home/awyl/.config/nvim/lua/astronvim/utils/status.lua:1224: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by mehalter** [comment]
What do you get if you run `:lua =vim.opt.foldcolumn:get()`

**Comment by awyl** [comment]
It returns a `1`.

**Comment by mehalter** [comment]
hm, that is the command that is being run that is causing the error. It looks like the core neovim is failing to access that option according to the error message. I have tried and I cannot replicate this issue either. Can you try in a clean installation without your user configuration and just using `:LspInstall omnisharp` in a completely fresh install?

**Comment by awyl** [comment]
I just open up another project.  It works fine there.  It perhaps an issue with Omnisharp instead.

This is one of the repo I am working on that has this issue.  I am sure it worked a couple weeks ago.
https://github.com/awyl/Docker-OrchardCore

I tried a clean install and `LspInstall omnisharp`, same error.

**Comment by mehalter** [comment]
I can give it a try in the coming days with that project and report back

**Comment by mehalter** [comment]
@awyl I did some digging by googling "Neovim E5248" and the first result was actually this exact error 😂 https://github.com/LunarVim/LunarVim/issues/3716

This seems to be quite a well known bug where Omnisharp does not conform to LSP semantic token standards which causes issues in Neovim.

Here are some relevant links:

https://github.com/OmniSharp/omnisharp-roslyn/issues/2483

https://nicolaiarocci.com/making-csharp-and-omnisharp-play-well-with-neovim/

**Comment by awyl** [comment]
Thank you for looking into it.

**Comment by mehalter** [comment]
No problem! It looks like you just want to modifying the `on_attach` function for `omnisharp` in your `lsp.config` section of your user configuration. Either `lsp.config.omnisharp` table in your `user/init.lua` file or in the file `user/lsp/config/omnisharp.lua`

**Comment by mehalter** [comment]
For people running into this there are two solutions:

1. If you use a single configuration file `user/init.lua`:

```lua
return {
  lsp = {
    config = {
      omnisharp = {
        on_attach = function(client, bufnr)
          client.server_capabilities.semanticTokensProvider = {
            full = vim.empty_dict(),
            legend = {
              tokenModifiers = { "static_symbol" },
              tokenTypes = {
                "comment",
                "excluded_code",
                "identifier",
                "keyword",
                "keyword_control",
                "number",
                "operator",
                "operator_overloaded",
                "preprocessor_keyword",
                "string",
                "whitespace",
                "text",
                "static_symbol",
                "preprocessor_text",
                "punctuation",
                "string_verbatim",
                "string_escape_character",
                "class_name",
                "delegate_name",
                "enum_name",
                "interface_name",
                "module_name",
                "struct_name",
                "type_parameter_name",
                "field_name",
                "enum_member_name",
                "constant_name",
                "local_name",
                "parameter_name",
                "method_name",
                "extension_method_name",
                "property_name",
                "event_name",
                "namespace_name",
                "label_name",
                "xml_doc_comment_attribute_name",
                "xml_doc_comment_attribute_quotes",
                "xml_doc_comment_attribute_value",
                "xml_doc_comment_cdata_section",
                "xml_doc_comment_comment",
                "xml_doc_comment_delimiter",
                "xml_doc_comment_entity_reference",
                "xml_doc_comment_name",
                "xml_doc_comment_processing_instruction",
                "xml_doc_comment_text",
                "xml_literal_attribute_name",
                "xml_literal_attribute_quotes",
                "xml_literal_attribute_value",
                "xml_literal_cdata_section",
                "xml_literal_comment",
                "xml_literal_delimiter",
                "xml_literal_embedded_expression",
                "xml_literal_entity_reference",
                "xml_literal_name",
                "xml_literal_processing_instruction",
                "xml_literal_text",
                "regex_comment",
                "regex_character_class",
                "regex_anchor",
                "regex_quantifier",
                "regex_grouping",
                "regex_alternation",
                "regex_text",
                "regex_self_escaped_character",
                "regex_other_escape",
              },
            },
            range = true,
          }
        end,
      },
    },
  },
}
```

2. If you use a split up user configuration, you can put the following in `user/lsp/config/omnisharp.lua`:

```lua
return {
  on_attach = function(client, bufnr)
    client.server_capabilities.semanticTokensProvider = {
      full = vim.empty_dict(),
      legend = {
        tokenModifiers = { "static_symbol" },
        tokenTypes = {
          "comment",
          "excluded_code",
          "identifier",
          "keyword",
          "keyword_control",
          "number",
          "operator",
          "operator_overloaded",
          "preprocessor_keyword",
          "string",
          "whitespace",
          "text",
          "static_symbol",
          "preprocessor_text",
          "punctuation",
          "string_verbatim",
          "string_escape_character",
          "class_name",
          "delegate_name",
          "enum_name",
          "interface_name",
          "module_name",
          "struct_name",
          "type_parameter_name",
          "field_name",
          "enum_member_name",
          "constant_name",
          "local_name",
          "parameter_name",
          "method_name",
          "extension_method_name",
          "property_name",
          "event_name",
          "namespace_name",
          "label_name",
          "xml_doc_comment_attribute_name",
          "xml_doc_comment_attribute_quotes",
          "xml_doc_comment_attribute_value",
          "xml_doc_comment_cdata_section",
          "xml_doc_comment_comment",
          "xml_doc_comment_delimiter",
          "xml_doc_comment_entity_reference",
          "xml_doc_comment_name",
          "xml_doc_comment_processing_instruction",
          "xml_doc_comment_text",
          "xml_literal_attribute_name",
          "xml_literal_attribute_quotes",
          "xml_literal_attribute_value",
          "xml_literal_cdata_section",
          "xml_literal_comment",
          "xml_literal_delimiter",
          "xml_literal_embedded_expression",
          "xml_literal_entity_reference",
          "xml_literal_name",
          "xml_literal_processing_instruction",
          "xml_literal_text",
          "regex_comment",
          "regex_character_class",
          "regex_anchor",
          "regex_quantifier",
          "regex_grouping",
          "regex_alternation",
          "regex_text",
          "regex_self_escaped_character",
          "regex_other_escape",
        },
      },
      range = true,
    }
  end,
}
```
