### ISSUE TITLE
preserve buffer sort order in heirline

### ISSUE THREAD

**Issue by moonlitknight** [AstroNvim/AstroNvim#1849]
### Is your feature related to a problem?

Please see https://github.com/rebelot/heirline.nvim/issues/146

Is it possible to always have the buffers in heirline always in buffer number order? Currently if I :bdelete a buffer and then reoopen it, the newly reopened buffer appears on the right, even though its ordinal buffer number should see it placed in its original position.

Eg.
```
open A
open B
open C
:bdelete B
open B
```
results in a buffline of `A C B` whereas :buffers displays `1 A   2 B    3 C`

### Describe the new feature

Sort heirline buffer list by ascending buffer number

**Comment by mehalter** [comment]
You can use `<leader>bsi` to sort buffers by buffer number. The bufferline does not automatically preserve order which is by design. You can rearrange the buffers to your liking using `<b` and >b`. The `<leader>bs` menu allows you to sort by many different things.

**Comment by mehalter** [comment]
Also, you could set up an `autocmd` using the `User` events that we expose (as described here: https://astronvim.com/Configuration/autocmds) in your polish function to automatically sort the buffers:

```lua
return {
  polish = function()
    vim.api.nvim_create_autocmd("User", {
      -- on buffer list updated
      pattern = "AstroBufsUpdated",
      group = vim.api.nvim_create_augroup("auto_sort_tabline", { clear = true }),
      callback = function()
        -- sort buffers
        local bufs = vim.t.bufs
        table.sort(bufs, require("astronvim.utils.buffer").comparator.bufnr)
        vim.t.bufs = bufs
        -- redraw tabline
        vim.cmd.redrawtabline()
      end,
    })
  end,
}
```

**Comment by mehalter** [comment]
I actually have a feature addition to `nightly` that allows you to use:

```lua
return {
  polish = function()
    vim.api.nvim_create_autocmd("User", {
      pattern = "AstroBufsUpdated",
      group = vim.api.nvim_create_augroup("auto_sort_tabline", { clear = true }),
      callback = function() vim.g.buffers_sorted = require("astronvim.utils.buffer").sort("bufnr", true) end,
    })
  end,
}
```

This will be a viable option for automatic sorting on and after v3.14.0

**Comment by mehalter** [comment]
just a heads up @moonlitknight that v3.14.0 is out now and that simplified syntax can be used for automatically sorting your tabline
