### ISSUE TITLE
Can not adjust the signatureHelp position

### ISSUE THREAD

**Issue by chaozwn** [AstroNvim/AstroNvim#1853]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macos 13.3.1

### Terminal/GUI

item2

### AstroNvim Health

AstroNvim Version: v3.14.0
Neovim Version: v0.9.0
OK Using stable Neovim >= 0.8.0
OK git is installed: Used for core functionality such as updater and plugin management
OK open is installed: Used for gx mapping for opening files with system opener (Optional)
OK lazygit is installed: Used for mappings to pull up git TUI (Optional)
OK node is installed: Used for mappings to pull up node REPL (Optional)
OK gdu is installed: Used for mappings to pull up disk usage analyzer (Optional)
OK btm is installed: Used for mappings to pull up system monitor (Optional)
OK python is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

I didn't find anything to adjust the signatureHelp position. can you tell me how to adjust the signhelp window to the above method?

### Steps to Reproduce

<leader>lh

### Expected behavior

 the signhelp window to the above method.

### Screenshots

![image](https://user-images.githubusercontent.com/51357674/235980087-84ac94b4-16d3-4396-a923-6bb87fe4cc61.png)

![image](https://user-images.githubusercontent.com/51357674/235980449-6320d9ea-f6e6-414a-9f53-001e402c043b.png)

**Comment by mehalter** [comment]
I seems like you are probably using `lsp_signature.nvim` I would recommend checking out their documentation: https://github.com/ray-x/lsp_signature.nvim

I haven't used this plugin, but their documentation seems to have pretty good details for customizing the positioning.

**Comment by chaozwn** [comment]
> I seems like you are probably using `lsp_signature.nvim` I would recommend checking out their documentation: https://github.com/ray-x/lsp_signature.nvim
> 
> I haven't used this plugin, but their documentation seems to have pretty good details for customizing the positioning.

yes, i wan't to use it. but i don't know how to disable astronvim lsp_signature help.

**Comment by mehalter** [comment]
AstroNvim does not provide lsp signature help. You may be using Noice (https://github.com/folke/noice.nvim) which provides signature help and you can look into that documentation to how to configure or disable it. But this is *not* an AstroNvim thing

**Comment by chaozwn** [comment]
> AstroNvim does not provide lsp signature help. You may be using Noice (https://github.com/folke/noice.nvim) which provides signature help and you can look into that documentation to how to configure or disable it. But this is _not_ an AstroNvim thing

thank you very much really.
