### ISSUE TITLE
`x` not working in visual mode

### ISSUE THREAD

**Issue by karambaq** [AstroNvim/AstroNvim#1854]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.0

### Terminal/GUI

iterm-2

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.10.2
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

`x` (delete) not working in visual mode

### Steps to Reproduce

1) Open file with content
2) Press `v`
3) Move in any direction
4) Press 'x'
5) Nothing happend

### Expected behavior

1) Open file with content
2) Press `v`
3) Move in any direction
4) Press 'x'
5) Delete all selection

**Comment by Uzaaft** [comment]
@karambaq  What's your config? Are you using any type of config?

**Comment by mehalter** [comment]
@karambaq not sure what you have in your configuration! This is not an issue with core AstroNvim so you must have something that changes this behavior.

I would recommend testing out things on a fresh installation of AstroNvim before opening an issue just to verify if it happens without your user configuration. That way you will know if it is something you have added or not.

**Comment by karambaq** [comment]
Answered in discord. Thanks guys.
