### ISSUE TITLE
Astronvim Debugger add Parameter passing

### ISSUE THREAD

**Issue by chaozwn** [AstroNvim/AstroNvim#1855]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macos 13.3.1

### Terminal/GUI

item2

### AstroNvim Health

AstroNvim Version: v3.14.0
Neovim Version: v0.9.0
OK Using stable Neovim >= 0.8.0
OK git is installed: Used for core functionality such as updater and plugin management
OK open is installed: Used for gx mapping for opening files with system opener (Optional)
OK lazygit is installed: Used for mappings to pull up git TUI (Optional)
OK node is installed: Used for mappings to pull up node REPL (Optional)
OK gdu is installed: Used for mappings to pull up disk usage analyzer (Optional)
OK btm is installed: Used for mappings to pull up system monitor (Optional)
OK python is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

![image](https://user-images.githubusercontent.com/51357674/236200083-a43bedbf-eea9-4026-bc58-f16a67c85cd2.png)

### Steps to Reproduce

none

### Expected behavior

through cmdline pass parameters.

**Comment by mehalter** [comment]
Please make feature requests to the correct repository: https://github.com/mfussenegger/nvim-dap

This is typically done through proper configuration of DAP. This is pretty advanced and can be difficult to configure.

**Comment by chaozwn** [comment]
> Please make feature requests to the correct repository: https://github.com/mfussenegger/nvim-dap

I meant because adding command-line arguments is a very general instruction,can it be integrated into astronvim.

**Comment by mehalter** [comment]
Parameters are passed to DAP through properly configuring a `launch.json`. I would check out the `nvim-dap` documentation for how to do this. Dynamically figuring out how many parameters there are and prompting for them is not a feature of `nvim-dap` (at the moment at least) and so it is not going to be able to be in AstroNvim. I would recommend taking a look at the `nvim-dap` documentation and try to make some `launch.json` files for your projects :)

**Comment by chaozwn** [comment]
> 
nvim dap is still a pain to use. It doesn't seem to automatically generate such as.

**Comment by mehalter** [comment]
Yeah I agree it has a long way to go, but it's done some amazing things recently that have allowed us to put it in with AstroNvim for debugging. This allows us to provide some basic debugging support in AstroNvim, but having specific configurations and actually making it work is definitely outside of what I can feasibly provide to a wide user base. But for the basic case, `nvim-dap` has been a good base for this project :)

**Comment by chaozwn** [comment]
> Yeah I agree it has a long way to go, but it's done some amazing things recently that have allowed us to put it in with AstroNvim for debugging. This allows us to provide some basic debugging support in AstroNvim, but having specific configurations and actually making it work is definitely outside of what I can feasibly provide to a wide user base. But for the basic case, `nvim-dap` has been a good base for this project :)

i think astronvim code structure is very good. is it possible to publish a video of debug in each language? By the way, l like th nvchad ui, but the configuration of nvchad provided by the official website seems to be wrong. link: https://astronvim.com/Recipes/status#replicate-nvchad-statusline

**Comment by mehalter** [comment]
@chaozwn I just tested it and I believe it's working perfectly :)

**Comment by chaozwn** [comment]
> 

can you send me success screenshot and your config ? thanks.

**Comment by mehalter** [comment]
![2023-05-05_09:17:10_screenshot](https://user-images.githubusercontent.com/1591837/236467874-1a14b243-a2b0-4d8e-a106-d5371c8e59f6.png)

Here is the config: https://astronvim.com/Recipes/status#replicate-nvchad-statusline

**Comment by chaozwn** [comment]
> ![2023-05-05_09:17:10_screenshot](https://user-images.githubusercontent.com/1591837/236467874-1a14b243-a2b0-4d8e-a106-d5371c8e59f6.png)
> 
> Here is the config: https://astronvim.com/Recipes/status#replicate-nvchad-statusline

modify success，but without normal and insert.
![image](https://user-images.githubusercontent.com/51357674/236470814-235a885f-37e6-4aec-89f8-0dbf58f6d917.png)

**Comment by chaozwn** [comment]
> this is not the NvChad statusline at all, that is just our default statusline with stuff like separators changed. You are incorrectly placing that configuration with your own. If you have a separate `plugins/` folder then that will take precedence over your `user/init.lua` file. Split up files always take precedence. You need to just put the pieces of that example configuration in the correct place. But notice the elements inside of the statusline, that is our statusline and not NvChads

thanks bro. i got.
