### ISSUE TITLE
How can I configure htmldjango with nvim-ts-autotag

### ISSUE THREAD

**Issue by silentjay** [AstroNvim/AstroNvim#1864]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

endevourOS/Arch

### Terminal/GUI

xcfe terminal

### AstroNvim Health

 6 - AstroNvim Version: v3.14.0
   7 - Neovim Version: v0.9.0
   8 - OK Using stable Neovim >= 0.8.0
   9 - OK git is installed: Used for core functionality such as updater and plugin management
  10 - OK xdg-open is installed: Used for gx mapping for opening files with system opener (Optional)
  11 - WARNING lazygit is not installed: Used for mappings to pull up git TUI (Optional)
  12 - OK node is installed: Used for mappings to pull up node REPL (Optional)
  13 - WARNING gdu is not installed: Used for mappings to pull up disk usage analyzer (Optional)
  14 - WARNING btm is not installed: Used for mappings to pull up system monitor (Optional)
  15 - OK python is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

`nvim-ts-autotag` doesn't work out the box with with `htmldjango` filtypes, there is no auto-close/auto-rename of tags. This may require additional [configuration](https://github.com/windwp/nvim-ts-autotag/issues/48) but I still haven't been able to get it working with astronvim by changing the treesitter parser to parse `htmldjango` as `html`. Other filetypes work as expected. 

### Steps to Reproduce

Create new html tags or rename them.

### Expected behavior

`htmldjango` filetypes have auto-close/auto-rename just like regular `html` filetypes.

**Comment by mehalter** [comment]
Have you tried `:TSInstall htmldjango`?

**Comment by mehalter** [comment]
@silentjay I just looked into it and I do not believe `nvim-ts-autotag` has support for `htmldjango`'s new treesitter parser. There is a parser specific to `htmldjango` and I have it installed and tried setting it up with `nvim-ts-autotag` and didn't get any results. I would recommend reaching out on their repo to see how to configure it or if that feature needs to be added. Also the official Discord is a great place to ask questions and hear from many different AstroNvim users
