### ISSUE TITLE
How to config mason lsp config with condition

### ISSUE THREAD

**Issue by chaozwn** [AstroNvim/AstroNvim#1865]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macos 13.3.1

### Terminal/GUI

item2

### AstroNvim Health

...

### Describe the bug

I want to config mason lsp server with specified environment. such as open tailwindcss server with `tailwind.config.js` other wise not open it. how can i do it?

### Steps to Reproduce

..

### Expected behavior

I want to config mason lsp server with specified environment. such as open tailwindcss server with `tailwind.config.js` other wise not open it. how can i do it?

**Comment by mehalter** [comment]
You can configure the `root_dir` for a language server. Here is a simple example:

```lua
return {
  lsp = {
    config = {
      tailwindcss = {
        root_dir = function(fname)
          local util = require "lspconfig.util"
          return util.root_pattern("tailwind.config.js", "tailwind.config.ts")(fname)
        end,
      },
    },
  },
}
```

Also I would recommend checking out the AstroNvim discord for asking questions. We try to keep questions asked there because more people check that and are active than on the GitHub issues and then use Issues to track feature requests and bugs.

**Comment by chaozwn** [comment]
> 

yeah, i will do it next time.

**Comment by chaozwn** [comment]
o

> You can configure the `root_dir` for a language server. Here is a simple example:
> 
> ```lua
> return {
>   lsp = {
>     config = {
>       tailwindcss = {
>         root_dir = function(fname)
>           local util = require "lspconfig.util"
>           return util.root_pattern("tailwind.config.js", "tailwind.config.ts")(fname)
>         end,
>       },
>     },
>   },
> }
> ```
> 
> Also I would recommend checking out the AstroNvim discord for asking questions. We try to keep questions asked there because more people check that and are active than on the GitHub issues and then use Issues to track feature requests and bugs.

Hi, bro. i make a config like below. but it not works.
![image](https://user-images.githubusercontent.com/51357674/236628915-04048329-5e41-4a5f-9aa2-48e9947df9cd.png)
![image](https://user-images.githubusercontent.com/51357674/236628930-9db47169-eaa1-48ab-9d95-59c8fb32324f.png)

**Comment by mehalter** [comment]
Not sure, here is the default if you want to compare: https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/tailwindcss.lua

It might take some debugging and figuring out to get the root detection working how you want it

**Comment by chaozwn** [comment]
> 

root_dir is no way to cancel the configuration of lsp.

**Comment by mehalter** [comment]
Yes, but it disables it from getting attached which is the same. In the screenshot you sent for example the language server is not running because it didn't detect a root directory and therefore is not automatically starting.

**Comment by mehalter** [comment]
Also @chaozwn this is a great question to take to the discord :) many people have been doing lots of custom `root_dir` stuff to control what language servers attach in different situations. They can probably help you set it up the way you want it and can also help clear up the understanding of what `root_dir` does and how clients attach/get detected to run the LSP

**Comment by chaozwn** [comment]
> 

good idea. i add a question in help-forum already.

**Comment by chaozwn** [comment]
> Also @chaozwn this is a great question to take to the discord :) many people have been doing lots of custom `root_dir` stuff to control what language servers attach in different situations. They can probably help you set it up the way you want it and can also help clear up the understanding of what `root_dir` does and how clients attach/get detected to run the LSP

I finished reading astronvim's forum, a suitable plan was not found.Is it possible to let astronvim expand a interface to determine whether it needs to load plugins.
