### ISSUE TITLE
Status line is not shown after saving a file

### ISSUE THREAD

**Issue by rs-loves-bugs** [AstroNvim/AstroNvim#1866]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

arch

### Terminal/GUI

wezterm

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.15.1
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

The status line disapears after saving a file.

### Steps to Reproduce

1. create a directory `mkdir statusline_bug`
2. enter the directory `cd statusline_bug`
3. open neovim with a file name `nvim aa.txt`
4. `<leader>s` to save the file

### Expected behavior

The status line should not disapear after saving a file.

### Screenshots

Screen recording:

https://user-images.githubusercontent.com/104234283/236614672-00f8978b-9f0d-4490-8454-7ad1d0dce488.mp4

### Additional Context

I noticed that this bug can't be reproduced if there is a `.git` repo in the directory.

**Comment by mehalter** [comment]
This is a limitation of `cmdheight=0` and saving a file prints a single line message. If you want to avoid this behavior, you can set `cmdheight = 1` to give a permanent line under the statusline to display messages like that.
