### ISSUE TITLE
How can I configure plantuml snippet  with json file?

### ISSUE THREAD

**Issue by roderick-liu** [AstroNvim/AstroNvim#1867]
### Is your feature related to a problem?

hi :
   I want use plantuml in Astronvim.  How can I configure plantuml snippet  with json file?
  like: su --->@startuml
 

### Describe the new feature

Do you have some suggestion? thanks!

**Comment by mehalter** [comment]
Here is the documentation on custom snippets: https://astronvim.com/Recipes/snippets

Depending on the snippets, you also probably want to read the LuaSnip documentation on their repo as well, but our docs should be enough to get some basic stuff started. You can also probably find some PlantUML code snippets around the internet. LuaSnip supports VS Code style snippets so stuff like this you could probably get working: https://gist.github.com/fuhrmanator/793ea86cd3b3b0e9f655b11643de3910

**Comment by mehalter** [comment]
The Discord is also a great resource for asking questions and getting a lot more visibility and input from more users who may have done similar stuff or have similar questions
