### ISSUE TITLE
lspsaga can it be replaced lspconfig?

### ISSUE THREAD

**Issue by chaozwn** [AstroNvim/AstroNvim#1871]
### Is your feature related to a problem?

https://github.com/nvimdev/lspsaga.nvim

### Describe the new feature

https://github.com/nvimdev/lspsaga.nvim

**Comment by mehalter** [comment]
Yeah you can add it in your user configuration. Feel free to ask on the discord if people have done it before. If you have a good configuration you can also add it to AstroCommunity

**Comment by mehalter** [comment]
Also just to be clear, it wouldn't replace `lspconfig`. It would just be added into your configuration like any other plugin
