### ISSUE TITLE
Tabline is not shown and `alpha-nvim` is not hidden when opening files in a new session using `tab drop ...`

### ISSUE THREAD

**Issue by lougreenwood** [AstroNvim/AstroNvim#1876]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

MacOS 13.3.1

### Terminal/GUI

iTerm

### AstroNvim Health

astronvim: require("astronvim.health").check()
   3
   4   AstroNvim
   5   - AstroNvim Version: v3.15.1
   6   - Neovim Version: v0.9.0
   7   - OK Using stable Neovim >= 0.8.0
   8   - OK git is installed: Used for core functionality such as updater and plugin management
   9   - OK open is installed: Used for gx mapping for opening files with system opener (Optional)
  10   - OK lazygit is installed: Used for mappings to pull up git TUI (Optional)
  11   - OK node is installed: Used for mappings to pull up node REPL (Optional)
  12   - OK gdu is installed: Used for mappings to pull up disk usage analyzer (Optional)
  13   - WARNING btm is not installed: Used for mappings to pull up system monitor (Optional)
  14   - OK python is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

When opening the first file in a session, if the file is opened in a new tab using `:tab drop path-to-file` (so the `alpha-nvim` / splash screen is not destroyed) the tab bar will not be shown.

It seem that this is because of the [`autocmd`](https://github.com/AstroNvim/AstroNvim/blob/1d407a2a50554fa137e2e0f65e58d600dcdc3319/lua/astronvim/autocmds.lua#L143) which is designed to hide the tab bar when `alpha-nvim` splash screen is shown and then show the tab bar when the window containing the splash screen unloads `alpha-nvim` and replaces it with the buffer for the file.

### Steps to Reproduce

1. Open a new session using `nvim`
2. Open a file using `tab drop path-to-file`
3. See that the tabline is not shown
4. show the tab line using `<leader> u t`
5. See that the first tab still has the `alpha-nvim` buffer open

However, note that doing `:tabnew` will correctly close alpha & display the tabline.

### Expected behavior

Using `:tab drop` should behave the same as `tabnew` and close the tab / buffer containing `alpha-nvim` and also show the tabline.

**Comment by mehalter** [comment]
@lougreenwood I did a complete rewrite of this `autocmd` to be a bit smarter. Could you test out `nightly` and see how it is? I believe it should resolve this

**Comment by lougreenwood** [comment]
Thanks @mehalter looks good - thanks for the amazingly quick response!

However - 1 question, WDYT to closing the `alpha-nvim` buffer / tab in this auto-cmd if it's open? 

A side effect of working "buffer-first" is that `alpha-nvim` is closed when opening the first file (which also makes sense since `alpha-nvim` acts as a kind of "entrypoint" or "splash screen" and is implicitly temporary.

However when using `tab drop ...` the initial tab containing `alpha-nvim` remains and it breaks the implicit assumption that this is a temporary splash screen / entrypoint.

Curious to hear your thoughts on this... 🙂

**Comment by mehalter** [comment]
I think this makes sense @lougreenwood but I also think it makes sense to be something that ahould be contributed upstream rather than making it work that way in AstroNvim. It seems like this fits the methodology of Alpha and dashboard tools and I'm guessing they just never thought of the use case of tab changes.
