### ISSUE TITLE
Code Actions `Install '@types/mockjs'` not work.

### ISSUE THREAD

**Issue by chaozwn** [AstroNvim/AstroNvim#1877]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macos 13.3.1

### Terminal/GUI

item2

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~

AstroNvim Version: v3.15.0
Neovim Version: v0.9.0
OK Using stable Neovim >= 0.8.0
OK git is installed: Used for core functionality such as updater and plugin management
OK open is installed: Used for gx mapping for opening files with system opener (Optional)
OK lazygit is installed: Used for mappings to pull up git TUI (Optional)
OK node is installed: Used for mappings to pull up node REPL (Optional)
OK gdu is installed: Used for mappings to pull up disk usage analyzer (Optional)
OK btm is installed: Used for mappings to pull up system monitor (Optional)
OK python is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Code Actions `Install '@types/mockjs'` not work.

![image](https://user-images.githubusercontent.com/51357674/236874670-dc28b0ca-a5fa-4186-b778-4ce24fc0e28b.png)

nothing happend.

### Steps to Reproduce

...

### Expected behavior

i want it execute command `yarn add @types/mockjs -D` automatic.

**Comment by mehalter** [comment]
This is completely unrelated to AstroNvim and will be handled by the language server itself. Questions and not bug reports should be asked on the Discord server (https://discord.gg/astronvim). That is where you can find people who can help you fix or debug your setup :)
