### ISSUE TITLE
AstroNvim loading screen formatting error

### ISSUE THREAD

**Issue by jonathanforhan** [AstroNvim/AstroNvim#1886]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Arch

### Terminal/GUI

st

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: unknown
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

==============================================================================
lazy: require("lazy.health").check()

lazy.nvim ~
- OK Git installed
- OK no existing packages found by other package managers
- OK packer_compiled.lua not found

==============================================================================

Latest stable AstroNvim from website, main gitbranch

### Describe the bug

the 'LDR n' command for creating a new file is now offcenter since it has changed from 'LDR f n', 2 more spaces are needed

### Steps to Reproduce

I reproduced in a VM so I am sure it is problem with latest current stable version fresh install. Seems silly to contribute for 2 spaces so I'll leave it up to you, it's in the lua/plugins/alpha.lua file, change 'LDR n' -> 'LDR n  ' (2 spaces)

### Expected behavior

Properly spaced load screen 

### Screenshots

![image](https://github.com/AstroNvim/AstroNvim/assets/99012095/f515c523-f15f-4f27-9444-d6adc813735d)

### Additional Context

it was a VM so  not bothered to add nerdfont, the spacing is only issue

**Comment by mehalter** [comment]
Thanks for the recommendation! Resolved in the current nightly and will be merged in the next day or so with the next release of AstroNvim
