### ISSUE TITLE
NeoTree invalid mappings

### ISSUE THREAD

**Issue by goququ** [AstroNvim/AstroNvim#1889]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.3

### Terminal/GUI

iterm

### AstroNvim Health

astronvim: require("astronvim.health").check()
    2 ========================================================================
    3 ## AstroNvim
    4   - INFO: AstroNvim Version: v3.15.5
    5   - INFO: Neovim Version: v0.8.3
    6   - OK: Using stable Neovim >= 0.8.0
    7   - OK: `git` is installed: Used for core functionality such as updater and plugin management
    8   - OK: `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
    9   - WARNING: `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
   10   - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
   11   - WARNING: `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
   12   - WARNING: `btm` is not installed: Used for mappings to pull up system monitor (Optional)
   13   - OK: `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

While I open neotree, I see warnings on very top-right corner about invalid mappings. 
<img width="495" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/12967830/5c0d657d-f6e6-4e47-8ba1-d32758183ba3">

I have fixed it by comment this code:
<img width="1101" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/12967830/34d24827-2079-4a20-8947-abab13e361c9">

is It OK, or we can do something?

### Steps to Reproduce

1. setup astroNvim
2. press <Leader>e

### Expected behavior

No any warnings

**Comment by mehalter** [comment]
I cannot replicate this. Maybe it's possible you have a very outdated version of `neo-tree` have you made sure to run `:Lazy update` as well? What version does `neo-tree` show to be on in `Lazy`?

**Comment by goququ** [comment]
> I cannot replicate this. Maybe it's possible you have a very outdated version of `neo-tree` have you made sure to run `:Lazy update` as well? What version does `neo-tree` show to be on in `Lazy`?

Oh yeah, it's work for me now! Thanks a lot ;)
