### ISSUE TITLE
The tree sidebar looks weird

### ISSUE THREAD

**Issue by oneslash** [AstroNvim/AstroNvim#1893]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.3.1 (a) 

### Terminal/GUI

iTerm

### AstroNvim Health

astronvim: require("astronvim.health").check()

# AstroNvim ~

- AstroNvim Version: v3.15.5
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

The item in a sub-tree is aligned as it is on the same level

### Steps to Reproduce

Not sure

### Expected behavior

It should be rendered (main.tf) as it is inside a folder

### Screenshots

![image](https://github.com/AstroNvim/AstroNvim/assets/15870134/9bb24b86-7708-41bd-9609-a95e226d7261)

**Comment by mehalter** [comment]
The screenshot shows it nested. You can look at the neo tree documentation to see how to customize padding

**Comment by oneslash** [comment]
Thank you
Done: https://github.com/nvim-neo-tree/neo-tree.nvim/issues/924

**Comment by oneslash** [comment]
@mehalter hi, the bug has been fixed in the upstream https://github.com/nvim-neo-tree/neo-tree.nvim/pull/977
