### ISSUE TITLE
Facing issues when starting nvim.

### ISSUE THREAD

**Issue by Rid1-fz-06** [AstroNvim/AstroNvim#1895]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Fedora38

### Terminal/GUI

kitty

### AstroNvim Health

E484: Can't open file /home/rid1/.config/nvim/syntax/syntax.vim
Error detected while processing command line:
E5009: Invalid $VIMRUNTIME: /home/rid1/.config/nvim
E5108: Error executing lua vim/_init_packages.lua:0: module 'vim.diagnostic' not found:
	no field package.preload['vim.diagnostic']
cache_loader: module vim.diagnostic not found
cache_loader_lib: module vim.diagnostic not found
	no file './vim/diagnostic.lua'
	no file '/usr/share/luajit-2.1.0-beta3/vim/diagnostic.lua'
	no file '/usr/local/share/lua/5.1/vim/diagnostic.lua'
	no file '/usr/local/share/lua/5.1/vim/diagnostic/init.lua'
	no file '/usr/share/lua/5.1/vim/diagnostic.lua'
	no file '/usr/share/lua/5.1/vim/diagnostic/init.lua'
	no file './vim/diagnostic.so'
	no file '/usr/local/lib/lua/5.1/vim/diagnostic.so'
	no file '/usr/lib64/lua/5.1/vim/diagnostic.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './vim.so'
	no file '/usr/local/lib/lua/5.1/vim.so'
	no file '/usr/lib64/lua/5.1/vim.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	vim/_init_packages.lua: in function '__index'
	/home/rid1/.config/nvim/lua/astronvim/utils/status.lua:901: in function 'condition'
	...hare/nvim/lazy/heirline.nvim/lua/heirline/statusline.lua:284: in function '_eval'
	...hare/nvim/lazy/heirline.nvim/lua/heirline/statusline.lua:365: in function '_eval'
	...hare/nvim/lazy/heirline.nvim/lua/heirline/statusline.lua:440: in function 'eval'
	...ocal/share/nvim/lazy/heirline.nvim/lua/heirline/init.lua:109: in function <...ocal/share/nvim/lazy/heirline.nvim/lua/heirline/init.lua:104>
Error running notification service: vim/_init_packages.lua:0: module 'vim.treesitter' not found:
^Ino field package.preload['vim.treesitter']
cache_loader: module vim.treesitter not found
cache_loader_lib: module vim.treesitter not found
^Ino file './vim/treesitter.lua'
^Ino file '/usr/share/luajit-2.1.0-beta3/vim/treesitter.lua'
^Ino file '/usr/local/share/lua/5.1/vim/treesitter.lua'
^Ino file '/usr/local/share/lua/5.1/vim/treesitter/init.lua'
^Ino file '/usr/share/lua/5.1/vim/treesitter.lua'
^Ino file '/usr/share/lua/5.1/vim/treesitter/init.lua'
^Ino file './vim/treesitter.so'
^Ino file '/usr/local/lib/lua/5.1/vim/treesitter.so'
^Ino file '/usr/lib64/lua/5.1/vim/treesitter.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
^Ino file './vim.so'
^Ino file '/usr/local/lib/lua/5.1/vim.so'
^Ino file '/usr/lib64/lua/5.1/vim.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
Error executing vim.schedule lua callback: vim/_init_packages.lua:0: module 'vim.lsp' not found:
	no field package.preload['vim.lsp']
cache_loader: module vim.lsp not found
cache_loader_lib: module vim.lsp not found
	no file './vim/lsp.lua'
	no file '/usr/share/luajit-2.1.0-beta3/vim/lsp.lua'
	no file '/usr/local/share/lua/5.1/vim/lsp.lua'
	no file '/usr/local/share/lua/5.1/vim/lsp/init.lua'
	no file '/usr/share/lua/5.1/vim/lsp.lua'
	no file '/usr/share/lua/5.1/vim/lsp/init.lua'
	no file './vim/lsp.so'
	no file '/usr/local/lib/lua/5.1/vim/lsp.so'
	no file '/usr/lib64/lua/5.1/vim/lsp.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './vim.so'
	no file '/usr/local/lib/lua/5.1/vim.so'
	no file '/usr/lib64/lua/5.1/vim.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	vim/_init_packages.lua: in function '__index'
	...e/nvim/lazy/aerial.nvim/lua/aerial/backends/lsp/util.lua:18: in function 'get_client'
	...e/nvim/lazy/aerial.nvim/lua/aerial/backends/lsp/init.lua:106: in function 'is_supported'
	...share/nvim/lazy/aerial.nvim/lua/aerial/backends/init.lua:40: in function 'is_supported'
	...share/nvim/lazy/aerial.nvim/lua/aerial/backends/init.lua:73: in function 'get_best_backend'
	...share/nvim/lazy/aerial.nvim/lua/aerial/backends/init.lua:142: in function 'get'
	...share/nvim/lazy/aerial.nvim/lua/aerial/backends/init.lua:245: in function 'attach'
	.../share/nvim/lazy/aerial.nvim/lua/aerial/autocommands.lua:85: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>Error running notification service: vi...:0: module 'vim.treesitter' not found:^Ino field package.preload['vim.treesitter']cache_loader: module vim.treesitter not foundcache_loader_lib: module vim.treesitter not found^Ino file './vim/treesitter.lua'^Ino file '/usr/share/luajit-2.1.0-beta3/vim/treesitter.lua'^Ino file '/usr/local/share/lua/5.1/vim/treesitter.lua'^Ino file '/usr/local/share/lua/5.1/vim/treesitter/init.lua'^Ino file '/usr/share/lua/5.1/vim/treesitter.lua'^Ino file '/usr/share/lua/5.1/vim/treesitter/init.lua'^Ino file './vim/treesitter.so'^Ino file '/usr/local/lib/lua/5.1/vim/treesitter.so'^Ino file '/usr/lib64/lua/5.1/vim/treesitter.so'^Ino file '/usr/local/lib/lua/5.1/loadall.so'^Ino file './vim.so'^Ino file '/usr/local/lib/lua/5.1/vim.so'^Ino file '/usr/lib64/lua/5.1/vim.so'^Ino file '/usr/local/lib/lua/5.1/loadall.so'

### Describe the bug

For some sort of reasons, I am not being able to open nvim. So I ran the following command,

```bash
rm -rf .config/nvim/ .local/share/nvim/ .local/state/nvim/ .cache/nvim/
```
after that, I reinstalled Astronvim from the instructions given [here](https://astronvim.com/). I re-ran nvim, but the same problem. The log file of the errors is attached...

[nvim.log](https://github.com/AstroNvim/AstroNvim/files/11460090/nvim_install.log)

### Steps to Reproduce

1. Follow the installation instructions
2. Open nvim
3. See the errors

### Expected behavior

There should be no errors, and all of the config files should load properly.

**Comment by mehalter** [comment]
This looks like you have an incorrect version of Neovim. Please make sure to check the requirements for AstroNvim.
