### ISSUE TITLE
schedule.vim launch gitsigns fail.

### ISSUE THREAD

**Issue by duanyuluo** [AstroNvim/AstroNvim#1896]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.4

### Terminal/GUI

iTerm

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.15.6
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

==============================================================================
gitsigns: require("gitsigns.health").check()

- OK git version 2.40.1

==============================================================================
lazy: require("lazy.health").check()

lazy.nvim ~
- OK Git installed
- OK no existing packages found by other package managers
- OK packer_compiled.lua not found

==============================================================================
mason: require("mason.health").check()

mason.nvim ~
- OK mason.nvim version v1.0.1
- OK neovim version >= 0.7.0

mason.nvim [Registries] ~
- OK Registry `github.com/mason-org/mason-registry version: 2023-05-12-equal-lark` is installed.

mason.nvim [Core utils] ~
- OK unzip: `UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send`
- OK wget: `GNU Wget 1.21.3 built on darwin22.1.0.`
- OK curl: `curl 7.88.1 (x86_64-apple-darwin22.0) libcurl/7.88.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.51.0`
- OK gzip: `Apple gzip 403.100.6`
- OK tar: `bsdtar 3.5.3 - libarchive 3.5.3 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
- OK bash: `GNU bash, version 5.2.15(1)-release (aarch64-apple-darwin22.1.0)`
- OK sh: `Ok`

mason.nvim [Languages] ~
- WARNING Go: not available
  - ADVICE:
    - spawn: go failed with exit code - and signal -. go is not executable
- WARNING Composer: not available
  - ADVICE:
    - spawn: composer failed with exit code - and signal -. composer is not executable
- WARNING PHP: not available
  - ADVICE:
    - spawn: php failed with exit code - and signal -. php is not executable
- WARNING luarocks: not available
  - ADVICE:
    - spawn: luarocks failed with exit code - and signal -. luarocks is not executable
- OK Ruby: `ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin22]`
- WARNING javac: not available
  - ADVICE:
    - spawn: javac failed with exit code 1 and signal 0. The operation couldn’t be completed. Unable to locate a Java Runtime that supports javac.
      Please visit http://www.java.com for information on installing Java.

- OK cargo: `cargo 1.69.0 (6e9a83356 2023-04-12)`
- WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. julia is not executable
- OK python3: `Python 3.11.3`
- OK python3_host_prog: `Python 3.11.3`
- OK RubyGem: `3.0.3.1`
- OK node: `v20.1.0`
- OK python3_host_prog pip: `pip 23.1.2 from /opt/homebrew/lib/python3.11/site-packages/pip (python 3.11)`
- OK pip3: `pip 23.1.2 from /opt/homebrew/lib/python3.11/site-packages/pip (python 3.11)`
- OK npm: `9.6.4`
- OK java: `java version "1.8.0_361"`

mason.nvim [GitHub] ~
- OK GitHub API rate limit. Used: 0. Remaining: 5000. Limit: 5000. Reset: Fri May 12 16:24:27 2023.

==============================================================================
noice: require("noice.health").check()

noice.nvim ~
- OK **Neovim** >= 0.8.0
- OK Not running inside **Neovide**
- OK You're using a GUI that should work ok
- OK **vim.go.lazyredraw** is not enabled
- OK **nvim-notify** is installed
- OK **TreeSitter vim** parser is installed
- OK **TreeSitter regex** parser is installed
- OK **TreeSitter lua** parser is installed
- OK **TreeSitter bash** parser is installed
- OK **TreeSitter markdown** parser is installed
- OK **TreeSitter markdown_inline** parser is installed
- OK `vim.notify` is set to **Noice**
- OK `vim.lsp.handlers["textDocument/hover"]` is set to **Noice**
- OK `vim.lsp.handlers["textDocument/signatureHelp"]` is set to **Noice**
- OK `vim.lsp.handlers["window/showMessage"]` is set to **Noice**
- OK `vim.lsp.util.convert_input_to_markdown_lines` is set to **Noice**
- OK `vim.lsp.util.stylize_markdown` is set to **Noice**

==============================================================================
null-ls: require("null-ls.health").check()

- OK prettierd: the command "prettierd" is executable.
- OK stylua: the command "stylua" is executable.
- OK black: the command "black" is executable.
- OK rustywind: the command "rustywind" is executable.
- OK isort: the command "isort" is executable.

==============================================================================
nvim: require("nvim.health").check()

Configuration ~
- OK no issues found

Runtime ~
- OK $VIMRUNTIME: /opt/homebrew/Cellar/neovim/0.9.0/share/nvim/runtime

Performance ~
- OK Build type: Release

Remote Plugins ~
- OK Up to date

terminal ~
- key_backspace (kbs) terminfo entry: `key_backspace=^H`
- key_dc (kdch1) terminfo entry: `key_dc=\E[3~`
- $TERM_PROGRAM="iTerm.app"
- $COLORTERM="truecolor"

==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v20.1.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 14.0.3 (clang-1403.0.22.14.1)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "22.5.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:44 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T8103"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - comment             ✓ . . . .
  - css                 ✓ . ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - htmldjango          ✓ . ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ . ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - rust                ✓ ✓ ✓ ✓ ✓
  - sql                 ✓ . . . ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

==============================================================================
provider: health#provider#check

Clipboard (optional) ~
- OK Clipboard tool found: pbcopy

Python 3 provider (optional) ~
- Using: g:python3_host_prog = "/opt/homebrew/bin/python3"
- Executable: /opt/homebrew/bin/python3
- Python version: 3.11.3
- pynvim version: 0.4.3
- OK Latest pynvim is installed.

Python virtualenv ~
- OK no $VIRTUAL_ENV

Ruby provider (optional) ~
- Ruby: ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin22]
- WARNING `neovim-ruby-host` not found.
  - ADVICE:
    - Run `gem install neovim` to ensure the neovim RubyGem is installed.
    - Run `gem environment` to ensure the gem bin directory is in $PATH.
    - If you are using rvm/rbenv/chruby, try "rehashing".
    - See :help |g:ruby_host_prog| for non-standard gem installations.
    - You may disable this provider (and warning) by adding `let g:loaded_ruby_provider = 0` to your init.vim

Node.js provider (optional) ~
- Node.js: v20.1.0
- WARNING Missing "neovim" npm (or yarn, pnpm) package.
  - ADVICE:
    - Run in shell: npm install -g neovim
    - Run in shell (if you use yarn): yarn global add neovim
    - Run in shell (if you use pnpm): pnpm install -g neovim
    - You may disable this provider (and warning) by adding `let g:loaded_node_provider = 0` to your init.vim

Perl provider (optional) ~
- WARNING "Neovim::Ext" cpan module is not installed
  - ADVICE:
    - See :help |provider-perl| for more information.
    - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

==============================================================================
vim.lsp: require("vim.lsp.health").check()

- LSP log level : WARN
- Log path: /Users/lzcoder/.local/state/nvim/lsp.log
- Log size: 203 KB

vim.lsp: Active Clients ~
- rust_analyzer (id=1, root_dir=/Users/lzcoder/repos/local/hellorust)

==============================================================================
vim.treesitter: require("vim.treesitter.health").check()

- Nvim runtime ABI version: 14
- OK Parser: bash       ABI: 14, path: /Users/lzcoder/.local/share/nvim/lazy/nvim-treesitter/parser/bash.so
- OK Parser: comment    ABI: 13, path: /Users/lzcoder/.local/share/nvim/lazy/nvim-treesitter/parser/comment.so
- OK Parser: css        ABI: 13, path: /Users/lzcoder/.local/share/nvim/lazy/nvim-treesitter/parser/css.so
- OK Parser: html       ABI: 13, path: /Users/lzcoder/.local/share/nvim/lazy/nvim-treesitter/parser/html.so
- OK Parser: htmldjango ABI: 14, path: /Users/lzcoder/.local/share/nvim/lazy/nvim-treesitter/parser/htmldjango.so
- OK Parser: json       ABI: 14, path: /Users/lzcoder/.local/share/nvim/lazy/nvim-treesitter/parser/json.so
- OK Parser: lua        ABI: 13, path: /Users/lzcoder/.local/share/nvim/lazy/nvim-treesitter/parser/lua.so
- OK Parser: markdown   ABI: 13, path: /Users/lzcoder/.local/share/nvim/lazy/nvim-treesitter/parser/markdown.so
- OK Parser: markdown_inline ABI: 13, path: /Users/lzcoder/.local/share/nvim/lazy/nvim-treesitter/parser/markdown_inline.so
- OK Parser: python     ABI: 14, path: /Users/lzcoder/.local/share/nvim/lazy/nvim-treesitter/parser/python.so
- OK Parser: regex      ABI: 13, path: /Users/lzcoder/.local/share/nvim/lazy/nvim-treesitter/parser/regex.so
- OK Parser: rust       ABI: 14, path: /Users/lzcoder/.local/share/nvim/lazy/nvim-treesitter/parser/rust.so
- OK Parser: sql        ABI: 14, path: /Users/lzcoder/.local/share/nvim/lazy/nvim-treesitter/parser/sql.so
- OK Parser: toml       ABI: 13, path: /Users/lzcoder/.local/share/nvim/lazy/nvim-treesitter/parser/toml.so
- OK Parser: vim        ABI: 14, path: /Users/lzcoder/.local/share/nvim/lazy/nvim-treesitter/parser/vim.so
- OK Parser: c          ABI: 13, path: /opt/homebrew/Cellar/neovim/0.9.0/lib/nvim/parser/c.so
- OK Parser: lua        ABI: 13, path: /opt/homebrew/Cellar/neovim/0.9.0/lib/nvim/parser/lua.so
- OK Parser: query      ABI: 14, path: /opt/homebrew/Cellar/neovim/0.9.0/lib/nvim/parser/query.so
- OK Parser: vim        ABI: 14, path: /opt/homebrew/Cellar/neovim/0.9.0/lib/nvim/parser/vim.so
- OK Parser: vimdoc     ABI: 14, path: /opt/homebrew/Cellar/neovim/0.9.0/lib/nvim/parser/vimdoc.so

==============================================================================
which-key: require("which-key.health").check()

WhichKey: checking conflicting keymaps ~
- WARNING conflicting keymap exists for mode **"v"**, lhs: **"<leader>l"**
- rhs: ` `
- OK No conflicting keymaps found

### Describe the bug

   Error  15:21:01 msg_show.lua_error Error executing vim.schedule lua callback: ...hare/nvim/lazy/gitsigns.nvim/lua/gitsigns/subprocess.lua:82: Failed to spawn process: {
  _state = {
    pid = "EMFILE: too many open files",
    stderr = <userdata 1>,
    stderr_data = {},
    stdin = <userdata 2>,
    stdout = <userdata 3>,
    stdout_data = {}
  },

### Steps to Reproduce

1. open and edit any file in nvim.
2. wait 10-30mins
3. raise error(see describe above)
4. quite nvim and restart nvim, wait some time, error raise again.

### Expected behavior

no error raised. what's wrong with my nvim.

### Screenshots

This is error message:
<img width="1538" alt="Screenshot 2023-05-12 at 15 41 38" src="https://github.com/AstroNvim/AstroNvim/assets/4272707/2fe3c0ba-1397-4779-98f0-f0d1dfda0bad">

This is ps:
<img width="1109" alt="Screenshot 2023-05-12 at 15 46 08" src="https://github.com/AstroNvim/AstroNvim/assets/4272707/b415a2f2-b1a6-400b-9237-8cafad1ef1d7">

### Additional Context

I have try *.rs and *.py filetypes, both situations are same.

**Comment by mehalter** [comment]
Hm, this is a sort of operating system error that comes from having too many files open on the entire machine. This is not an error starting from within Neovim/AstroNvim. There are ways to resolve this like changing your `ulimit` or something. Sorry there isn't much I can do to help 😥 

Here is a similar issue from a completely separate project: https://github.com/serverless/serverless/issues/10944

**Comment by duanyuluo** [comment]
ulimit -a
...
-n file descriptors     256

it's so small! so i modify it by...
ulimit -n 10240

up to now, all are OK.
