### ISSUE TITLE
`vim.t[1]` contains the incorrect buffers when opening a new tab from the `alpha` splash screen

### ISSUE THREAD

**Issue by lougreenwood** [AstroNvim/AstroNvim#1898]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

MacOS 13.3.1

### Terminal/GUI

iterm

### AstroNvim Health

astronvim: require("astronvim.health").check()
   3
   4   AstroNvim
   5   - AstroNvim Version: v3.15.1-16-g3d02792
   6   - Neovim Version: v0.9.0
   7   - OK Using stable Neovim >= 0.8.0
   8   - OK git is installed: Used for core functionality such as updater and plugin management
   9   - OK open is installed: Used for gx mapping for opening files with system opener (Optional)
  10   - OK lazygit is installed: Used for mappings to pull up git TUI (Optional)
  11   - OK node is installed: Used for mappings to pull up node REPL (Optional)
  12   - OK gdu is installed: Used for mappings to pull up disk usage analyzer (Optional)
  13   - WARNING btm is not installed: Used for mappings to pull up system monitor (Optional)
  14   - OK python is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

This is a followup of https://github.com/AstroNvim/AstroNvim/issues/1876 and part of my effort to better support tabpage-based worfklows.

### Steps to Reproduce

See aboveIt seems that after opening nvim and seeing `alpha` and then opening a new file in a new tab, then the buffer for the new tab is added to the `vim.t[1].bufs` (aka `alpha`'s tab) as well as the `vim.t[2].bufs` (aka the new tab), which results in the tab which contains alpha displaying the wrong title in the tab bar.

Example: https://monosnap.com/file/vxCXJRC8sNMRGgfH0sZLTbuHxiJoaT

### Expected behavior

I'm only seeing this surface as a bug whilst https://github.com/goolord/alpha-nvim/issues/213 is unaddressed. However, perhaps the underlying cause of this bug might manifest in other ways, so it seems sensible to still address it.

**Comment by mehalter** [comment]
Ok there are a couple things happening here:

1. There is a bit of this coming from a side effect of Alpha not unloading. Basically if you run `:tabnew <file>` with alpha opened it will cause a bug. This is sadly something that is out of our control. This would require knowing the alpha buffer and unloading it ourselves which I would love to do but Alpha does not expose this information with their API and us figuring it out can end up being hacky and too much to maintain. This should be fixed upstream
2. `:tab drop <file>` causes this no matter what. And there are a few very key reasons as to why we can't resolve this sadly. It appears that `:tab drop <file>` does not trigger a `TabNewEntered` event when it ends up making a new tab (if the file isn't already opened). Why this is not emitting tab events I have absolutely no idea.

For those two pretty important reasons I'm going to close this as unplanned :/ This is a super super unfortunate case and I have spent the past several hours trying to figure out why the weirdness is happening with :tab drop and it just doesn't give me any indication it has ever run or anything. It's simply just the same as opening bufers from an autocmd standpoint. If you come up with anything definitely reach out to me here or on the Discord!

**Comment by lougreenwood** [comment]
Thanks for looking into this @mehalter!

Since the symptom of this that I experience when using it with alpha will hopefully be fixed by https://github.com/goolord/alpha-nvim/issues/213 then it's not a big problem that we can't fix here.

> It appears that :tab drop <file> does not trigger a TabNewEntered event when it ends up making a new tab (if the file isn't already opened). Why this is not emitting tab events I have absolutely no idea.

I guess I need to open an issue in the `neovim` repo for this, I'll ping you here with the link when it's done incase you want to chime in.

Thanks again!

**Comment by mehalter** [comment]
I would recommend doing some more investigating as well before opening a neovim bug report as well just to make sure it's a full report
