### ISSUE TITLE
Mousewheel breaks telescope

### ISSUE THREAD

**Issue by Zeioth** [AstroNvim/AstroNvim#1899]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Arch

### Terminal/GUI

foot

### AstroNvim Health

All OK

### Describe the bug

Scrolling up/down breaks several things

* On Telescope: It scrolls the background buffer instead of telescope.
* On Rnvimr: Scrolling makes the modal window irresponsive.

### Steps to Reproduce

* Install and run Rnvimr or lead+ff (to open telescope)
* Try to scroll down/up

### Expected behavior

The content of the modal window scrolls correctly

### Additional Context

Should I report this bug here, or upstream?

**Comment by mehalter** [comment]
These will be upstream issues in the plugins themselves since we don't do anything regarding how mouse events are handled for these plugins. Sorry!
