### ISSUE TITLE
The columns of the `toggleterm` does not match the actual width.

### ISSUE THREAD

**Issue by lonnywong** [AstroNvim/AstroNvim#1900]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Ubuntu 22.04

### Terminal/GUI

iTerm2

### AstroNvim Health

AstroNvim
- AstroNvim Version: unknown
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK git is installed: Used for core functionality such as updater and plugin management
- OK open is installed: Used for gx mapping for opening files with system opener (Optional)
- WARNING lazygit is not installed: Used for mappings to pull up git TUI (Optional)
- OK node is installed: Used for mappings to pull up node REPL (Optional)
- WARNING gdu is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING btm is not installed: Used for mappings to pull up system monitor (Optional)
- OK python is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

The columns of the `toggleterm` does not match the actual width.
It may be related to the `number` and `relativenumber` settings.

### Steps to Reproduce

1. `<leader>tv` or `<leader>th` open the terminal
2. execute `python3 -c 'import os; print("A" * (os.get_terminal_size().columns - 2) + "abcdef")'`

### Expected behavior

Should show `...AAAAAab` on the right, and `cdef` on the next line.

But the `b` is missing.

### Screenshots

![image](https://github.com/AstroNvim/AstroNvim/assets/20320324/18a70315-8169-4369-97c7-d35baa59bf19)

**Comment by mehalter** [comment]
This probably should be open with the toggleterm repository rather than here. Not sure if there is anything we or that plugin can do and is just a limitation of a Neovim terminal? Honestly not sure, but nothing in AstroNvim's codebase is handling anything that changes the behavior of terminal commands and their output. This would either just be a bug in Neovim, a bug in toggleterm, or a limitation of the system.

**Comment by lonnywong** [comment]
@mehalter [toggleterm.nvim](https://github.com/akinsho/toggleterm.nvim) works good not in `AstroNvim`.

Here is my `~/.config/nvim/init.lua` for test `toggleterm`:
```lua
vim.opt.number = true
vim.opt.relativenumber = true

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath, })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({ { "akinsho/toggleterm.nvim", version = "*", config = true } }, {})
```

### Test without `AstroNvim`:
1. `:ToggleTerm size=40 direction=horizontal` or `:ToggleTerm size=80 direction=vertical`
2. execute `python3 -c 'import os; print("A" * (os.get_terminal_size().columns - 2) + "abcdef")'`

![image](https://github.com/AstroNvim/AstroNvim/assets/20320324/50dae34f-5390-4087-98ec-137715942111)

### Test with `AstroNvim`:
![image](https://github.com/AstroNvim/AstroNvim/assets/20320324/c725c994-b772-415d-bfd7-bcd57f3a6bfb)

Don't know why there are some spaces on the left. May be related to the `number` and `relativenumber` settings.

**Comment by mehalter** [comment]
You are correct that stuff like the number column/fold column/signcolumn are messing up the terminal width calculation. Sadly this is something that is replicated in core neovim if you enable those features. I have gone ahead and tagged a new release that by default disables all the status column elements on open. But if you wanted something like line numbers and stuff at some point then your terminal  width calculation would become wrong again.

**Comment by lonnywong** [comment]
@mehalter It works. Thanks for your help.
