### ISSUE TITLE
utils.set_mappings can't reset mapping.

### ISSUE THREAD

**Issue by chaozwn** [AstroNvim/AstroNvim#1904]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macos 13.3.1

### Terminal/GUI

item2

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.15.7
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

i have change mappings, but it not completely cover.
![image](https://github.com/AstroNvim/AstroNvim/assets/51357674/e9946a52-fd7a-4d54-afe7-203cf5cdb921)
![image](https://github.com/AstroNvim/AstroNvim/assets/51357674/a6adfff1-12cd-4751-8572-1336f506ad5c)
![image](https://github.com/AstroNvim/AstroNvim/assets/51357674/2c8672b8-47c5-43b4-8a78-f225ddf4bfd6)

### Steps to Reproduce

maps.n["<leader>w"] = { desc = "󱂬 Window" }
add below config in your mapping.

### Expected behavior

![image](https://github.com/AstroNvim/AstroNvim/assets/51357674/a2000e86-2f17-46c7-a9be-e97bc051c523)
show blue color.

**Comment by mehalter** [comment]
You need to also remove the function that is bound to the key. In the example you shared you are only changing the description.

**Comment by chaozwn** [comment]
> You need to also remove the function that is bound to the key. In the example you shared you are only changing the description.

but the key is in astronvim mappings, not in my user mapping.

**Comment by chaozwn** [comment]
> You need to also remove the function that is bound to the key. In the example you shared you are only changing the description.

it means, i can't overwrite your mapping totally.

**Comment by mehalter** [comment]
You'll want to use the override function format for more control over the table that you don't get from just doing an override table. This is described here I'm the documentation: https://astronvim.com/Configuration/override_formats#override-function

If you have any other questions regarding this I would highly highly recommend joining the Discord as there are many users there who can help you out!
