### ISSUE TITLE
utils  /lsp.lua → <leader>ld only available when a formatter is used

### ISSUE THREAD

**Issue by Zeioth** [AstroNvim/AstroNvim#1911]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Arch

### Terminal/GUI

Foot

### AstroNvim Health

All ok

### Describe the bug

In the plugin null-ls, we have this line

    on_attach = require("base.utils.lsp").on_attach

Because we are loading LSP keybindings on  null-ls, they won't be available unless we have, and use and auto formatter.

No auto formatter present:
![screenshot_2023-05-18_16-30-46_162294428](https://github.com/AstroNvim/AstroNvim/assets/3357792/69870b86-c29c-4b37-8738-5249c2c0c50d)

Auto formatter present:
![screenshot_2023-05-18_16-28-37_154149958](https://github.com/AstroNvim/AstroNvim/assets/3357792/39fc5c50-9d28-44d5-be0a-f58919e035f9)

A possible solution would be to make it available on startup.

### Steps to Reproduce

* Without an auto formater enabled, use <lead>ld to show diagnostics.
* It won't be available untless we have an auto formater.

### Expected behavior

It should be always available.

**Comment by mehalter** [comment]
This is the same `on_attach` function that is used by the language servers as well and is not only used by `null-ls`. So any language server that attaches will have those bindings:
![2023-05-18_11:18:29_screenshot](https://github.com/AstroNvim/AstroNvim/assets/1591837/b9760fdd-7624-447e-b4ac-e8bc44de0229)

Notice here that I only have `jsonls` attached to the buffer. Could you share you user configuration and maybe I can help you debug what's going on in your configuration

**Comment by mehalter** [comment]
Also please share your `:checkhealth astronvim` it provides very useful information more than just "All OK"

**Comment by Zeioth** [comment]
Thank you so much for the hint!! I accidentally messed M.setup in lsp.lua while configuring.
