### ISSUE TITLE
Save session with vertical toggleterm window,  the layout is swapped after load it. 

### ISSUE THREAD

**Issue by lonnywong** [AstroNvim/AstroNvim#1913]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Ubuntu22.04

### Terminal/GUI

iTerm2

### AstroNvim Health

AstroNvim Version: unknown
Neovim Version: v0.9.0
OK Using stable Neovim >= 0.8.0
OK git is installed: Used for core functionality such as updater and plugin management
OK open is installed: Used for gx mapping for opening files with system opener (Optional)
WARNING lazygit is not installed: Used for mappings to pull up git TUI (Optional)
OK node is installed: Used for mappings to pull up node REPL (Optional)
WARNING gdu is not installed: Used for mappings to pull up disk usage analyzer (Optional)
WARNING btm is not installed: Used for mappings to pull up system monitor (Optional)
OK python is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Load a session with vertical toggleterm window, the toggleterm window is on the left.

### Steps to Reproduce

1. open some files.
2. `<leader>tv` open toggleterm.
3. `<leader>Ss` save session.
4. `<leader>q` quit nvim.
5. open nvim again.
6. `<leader>S.` load session.

### Expected behavior

The toggleterm window is on the right.

**Comment by mehalter** [comment]
Session saving and loading is handled by [neovim-session-manager](https://github.com/Shatur/neovim-session-manager). This sounds like it's probably a bug in their plugin and probably not a bug here. Please open an issue on that plugin's repository. If you hear back from them and it is indeed in AstroNvim I can reopen this and take a deeper look!

**Comment by lonnywong** [comment]
@mehalter Thanks. I'll try it first.
