### ISSUE TITLE
How to make work emmet in php files? 

### ISSUE THREAD

**Issue by seriiserii825** [AstroNvim/AstroNvim#1914]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

xubuntu 22.04

### Terminal/GUI

xfce4

### AstroNvim Health

astronvim: require("astronvim.health").check()
========================================================================
## AstroNvim
  - INFO: AstroNvim Version: v3.15.9
  - INFO: Neovim Version: v0.8.1
  - OK: Using stable Neovim >= 0.8.0
  - OK: `git` is installed: Used for core functionality such as updater and plugin management
  - OK: `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
  - OK: `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
  - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
  - WARNING: `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
  - WARNING: `btm` is not installed: Used for mappings to pull up system monitor (Optional)
  - OK: `python3` is installed: Used for mappings to pull up python REPL (Optional)

gitsigns: require("gitsigns.health").check()
========================================================================
  - OK: git version 2.34.1

lazy: require("lazy.health").check()
========================================================================
## lazy.nvim
  - OK: Git installed
  - OK: no existing packages found by other package managers
  - OK: packer_compiled.lua not found
  - WARNING: {LuaSnip}: overriding <config>

man: require("man.health").check()
========================================================================
  - OK: plugin/man.vim not in $VIMRUNTIME
  - OK: autoload/man.vim not in $VIMRUNTIME

mason: require("mason.health").check()
========================================================================
## mason.nvim
  - OK: mason.nvim version v1.1.0
  - OK: PATH: prepend
  - OK: Providers: 
    mason.providers.registry-api
    mason.providers.client
  - OK: neovim version >= 0.7.0

## mason.nvim [Registries]
  - OK: Registry `github.com/mason-org/mason-registry version: 2023-05-19-wooden-supply` is installed.

## mason.nvim [Core utils]
  - OK: unzip: `UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.`
  - OK: wget: `GNU Wget 1.21.2 built on linux-gnu.`
  - OK: curl: `curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.13`
  - OK: gzip: `gzip 1.10`
  - OK: tar: `tar (GNU tar) 1.34`
  - OK: bash: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: sh: `Ok`

## mason.nvim [Languages]
  - WARNING: Go: not available
    - ADVICE:
      - spawn: go failed with exit code - and signal -. go is not executable
  - WARNING: cargo: not available
    - ADVICE:
      - spawn: cargo failed with exit code - and signal -. cargo is not executable
  - WARNING: luarocks: not available
    - ADVICE:
      - spawn: luarocks failed with exit code - and signal -. luarocks is not executable
  - OK: PHP: `PHP 8.0.28 (cli) (built: Feb 14 2023 18:33:29) ( NTS )`
  - OK: node: `v16.19.0`
  - WARNING: javac: not available
    - ADVICE:
      - spawn: javac failed with exit code - and signal -. javac is not executable
  - WARNING: java: not available
    - ADVICE:
      - spawn: java failed with exit code - and signal -. java is not executable
  - WARNING: julia: not available
    - ADVICE:
      - spawn: julia failed with exit code - and signal -. julia is not executable
  - OK: python3: `Python 3.10.6`
  - OK: Ruby: `ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]`
  - WARNING: pip3: not available
    - ADVICE:
      - spawn: python3 failed with exit code 1 and signal 0. /usr/bin/python3: No module named pip

  - OK: Composer: `Composer version 2.4.4 2022-10-27 14:39:29`
  - OK: RubyGem: `3.3.5`
  - OK: npm: `8.19.3`

## mason.nvim [GitHub]
  - OK: GitHub API rate limit. Used: 0. Remaining: 60. Limit: 60. Reset: Fri 19 May 2023 07:09:19 PM EEST.
    Install and authenticate via gh-cli to increase rate limit.

null-ls: require("null-ls.health").check()
========================================================================
  - OK: prettier: the command "prettier" is executable.

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='6800'
  - INFO: $COLORTERM='truecolor'

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - ERROR: Nvim-treesitter requires Neovim 0.8.3+
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v16.19.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "x86_64",
  release = "5.15.0-72-generic",
  sysname = "Linux",
  version = "#79-Ubuntu SMP Wed Apr 19 08:22:18 UTC 2023"
}

## Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - vim                 x ✓ ✓ . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: vim(highlights): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim
    vim(highlights) is concatenated from the following files:
    | [ERROR]:"/home/serii/.local/share/nvim/lazy/nvim-treesitter/queries/vim/highlights.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python3
  - INFO: Other python executable: /bin/python3
  - INFO: Python version: 3.10.6
  - INFO: pynvim version: 0.4.2 (outdated; from /usr/lib/python3/dist-packages/neovim)
  - WARNING: Latest pynvim is NOT installed: 0.4.3

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.
      - You may disable this provider (and warning) by adding `let g:loaded_ruby_provider = 0` to your init.vim

## Node.js provider (optional)
  - INFO: Node.js: v16.19.0
  - WARNING: Missing "neovim" npm (or yarn, pnpm) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim
      - Run in shell (if you use pnpm): pnpm install -g neovim
      - You may disable this provider (and warning) by adding `let g:loaded_node_provider = 0` to your init.vim

## Perl provider (optional)
  - WARNING: "Neovim::Ext" cpan module is not installed
    - ADVICE:
      - See :help |provider-perl| for more information.
      - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /home/serii/.local/state/nvim/lsp.log
  - INFO: Log size: 20 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 14
  - OK: Loaded parser for lua: ABI version 14
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for help: ABI version 14
  - OK: Loaded parser for lua: ABI version 14
  - OK: Loaded parser for vim: ABI version 14

which-key: require("which-key.health").check()
========================================================================
## WhichKey: checking conflicting keymaps
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"\\"**
  - INFO: rhs: `<Cmd>split<CR>`
  - OK: No conflicting keymaps found

### Describe the bug

Emmet expand don't work in php files.

### Steps to Reproduce

In user folder init.lua file added options to set global emmet
```
  options = function(local_vim)
    local_vim.g['sneak#label'] = 1
    local_vim.g['copilot_no_tab_map'] = "v:true"
    local_vim.g['user_emmet_install_global'] = 1
    local_vim.opt.relativenumber = false
    local_vim.opt.scrolloff = 10
    return local_vim
  end,

```

### Expected behavior

On type view emmet suggestions

**Comment by mehalter** [comment]
You need to simply add `php` to the filetypes of the LSP configuration of `emmet_ls`. Here is a minimal `user/init.lua` file that just adds `php` to `emmet_ls`. I have verified it attaches but I'm not sure it does what you actually want since it's not a language server made for PHP:

```lua
return {
  lsp = {
    config = {
      emmet_ls = {
        filetypes = {
          "astro",
          "css",
          "eruby",
          "html",
          "htmldjango",
          "javascriptreact",
          "less",
          "php",
          "pug",
          "sass",
          "scss",
          "svelte",
          "typescriptreact",
          "vue",
        },
      },
    },
  },
}
```

**Comment by mehalter** [comment]
With the new v3.15.10 release I just tagged I actually improved this a bit and allows you do not have to redefine all of the filetypes again like you would have to do normally when configuring neovim:

```lua
return {
  lsp = {
    config = {
      emmet_ls = function(opts)
        opts.filetypes = require("astronvim.utils").list_insert_unique(opts.filetypes, "php")

        return opts
      end,
    },
  },
}
```
