### ISSUE TITLE
LSP format doesn't respect ident from options.lua and always formats with shiftwidth 2

### ISSUE THREAD

**Issue by rfcosta** [AstroNvim/AstroNvim#1916]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Ventura 13.4

### Terminal/GUI

warp

### AstroNvim Health

   1
   1   ──────────────────────────────────────────────────────────────────────────────
   2   astronvim: require("astronvim.health").check()
   3
   4   AstroNvim
   5   - AstroNvim Version: v3.15.9-2-g884122c
   6   - Neovim Version: v0.9.0
   7   - OK Using stable Neovim >= 0.8.0
   8   - OK git is installed: Used for core functionality such as updater and plugin management
   9   - OK open is installed: Used for gx mapping for opening files with system opener (Optional)
  10   - WARNING lazygit is not installed: Used for mappings to pull up git TUI (Optional)
  11   - OK node is installed: Used for mappings to pull up node REPL (Optional)
  12   - WARNING gdu is not installed: Used for mappings to pull up disk usage analyzer (Optional)
  13   - WARNING btm is not installed: Used for mappings to pull up system monitor (Optional)
  14   - OK python3 is installed: Used for mappings to pull up python REPL (Optional)
  15

### Describe the bug

[space]lf Format always format with indent = 2.
Options.lua with the modified indent:
cat ../options.lua
vim.opt.viewoptions
:remove "curdir" -- disable saving current directory with views
vim.opt.shortmess:append { s = true, I = true }   -- disable startup message
vim.opt.backspace:append { "nostop" }             -- Don't stop backspace at insert

if vim.fn.has "nvim-0.9" == 1 then
    vim.opt.diffopt:append "linematch:60"         -- enable linematch diff algorithm
end

local options = astronvim.user_opts("options", {
    opt = {
        breakindent = true,                       -- Wrap indent to match  line start
        clipboard = "unnamedplus",                -- Connection to the system clipboard
        cmdheight = 0,                            -- hide command line unless needed
        completeopt = { "menuone", "noselect" },  -- Options for insert mode completion
        copyindent = true,                        -- Copy the previous indentation on autoindenting
        cursorline = true,                        -- Highlight the text line of the cursor
        expandtab = true,                         -- Enable the use of space in tab
        fileencoding = "utf-8",                   -- File content encoding for the buffer
        fillchars = { eob = " " },                -- Disable `~` on nonexistent lines
        foldenable = true,                        -- enable fold for nvim-ufo
        foldlevel = 99,                           -- set high foldlevel for nvim-ufo
        foldlevelstart = 99,                      -- start with all code unfolded
        foldcolumn = vim.fn.has "nvim-0.9" == 1 and "1" or nil, -- show foldcolumn in nvim 0.9
        history = 100,                            -- Number of commands to remember in a history table
        ignorecase = true,                        -- Case insensitive searching
        infercase = true,                         -- Infer cases in keyword completion
        laststatus = 3,                           -- globalstatus
        linebreak = true,                         -- Wrap lines at 'breakat'
        mouse = "a",                              -- Enable mouse support
        number = true,                            -- Show numberline
        preserveindent = false,                   -- Preserve indent structure as much as possible (*)
        pumheight = 10,                           -- Height of the pop up menu
        relativenumber = true,                    -- Show relative numberline
        scrolloff = 8,                            -- Number of lines to keep above and below the cursor
        shiftwidth = 4,                           -- Number of space inserted for indentation
        showmode = false,                         -- Disable showing modes in command line
        showtabline = 2,                          -- always display tabline
        sidescrolloff = 8,                        -- Number of columns to keep at the sides of the cursor
        signcolumn = "yes",                       -- Always show the sign column
        smartcase = true,                         -- Case sensitivie searching
        smartindent = true,                       -- Smarter autoindentation
        splitbelow = true,                        -- Splitting a new window below the current one
        splitright = true,                        -- Splitting a new window at the right of the current one
        tabstop = 4,                              -- Number of space in a tab (*)
        termguicolors = true,                     -- Enable 24-bit RGB color in the TUI (*)
        timeoutlen = 500,                         -- Shorten key timeout length a little bit for which-key
        undofile = true,                          -- Enable persistent undo
        updatetime = 300,                         -- Length of time to wait before triggering the plugin
        virtualedit = "block",                    -- allow going past end of line in visual block mode
        wrap = false,                             -- Disable wrapping of lines longer than the width of window
        writebackup = false,                      -- Disable making a backup before overwriting a file
    },

    g = {
        highlighturl_enabled = true,              -- highlight URLs by default
        mapleader = " ",                          -- set leader key
        autoformat_enabled = true,                -- enable or disable auto formatting at start (lsp.formatting.format_on_save must be enabled)
        codelens_enabled = true,                  -- enable or disable automatic codelens refreshing for lsp that support it
        lsp_handlers_enabled = true,              -- enable or disable default vim.lsp.handlers (hover and signatureHelp)
        cmp_enabled = true,                       -- enable completion at start
        autopairs_enabled = true,                 -- enable autopairs at start
        diagnostics_mode = 3,                     -- set the visibility of diagnostics in the UI (0=off, 1=only show in status line, 2=virtual text off, 3=all on)
        icons_enabled = true,                     -- disable icons in the UI (disable if no nerd font is available)
        ui_notifications_enabled = true,          -- disable notifications when toggling UI elements
    },

    t = vim.t.bufs and vim.t.bufs or { bufs = vim.api.nvim_list_bufs() }, -- initialize buffers for the current tab
})

for scope, table in pairs(options) do
    for setting, value in pairs(table) do
        vim[scope][setting] = value
    end
end

### Steps to Reproduce

Change the tabstop and shiftwidth to 4.
Reformat a buffer that has indent 4 spaces.
It will reformat with 2 space instead of 4.

### Expected behavior

I expect the format to respect the desired indent value and/or the current indent of the file

### Screenshots

N/A

### Additional Context

I had to turn off auto format on save.
How to take control of this formatting process?

**Comment by mehalter** [comment]
It will be up to how to configure the formatter binaries that are used. It does not respect the native Neovim options. If you want to disable formatting you can check the docs here: https://astronvim.com/Recipes/advanced_lsp#customizing-auto-format-on-save
