### ISSUE TITLE
Theme colors are not set correctly when setting the theme from config.

### ISSUE THREAD

**Issue by mohad12211** [AstroNvim/AstroNvim#1918]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

archlinux

### Terminal/GUI

kitty

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.15.10
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

I'm using https://github.com/Shatur/neovim-ayu theme.
If I add `colorscheme = "ayu"` to the config files, some colors are weird.
However if I remove this line, and change the colorshcme manually, colors are shown properly

### Steps to Reproduce

1. add 
```lua 
plugins = {
    "Shatur/neovim-ayu"
 }
```
2. add `colorscheme = "ayu"`
3. open a file
4. wrong colors

### Expected behavior

correct colors

### Screenshots

setting it manually: 
![image](https://github.com/AstroNvim/AstroNvim/assets/51754973/558496fb-f5a2-40b6-b46a-71219481cc75)
setting it from config:
![image](https://github.com/AstroNvim/AstroNvim/assets/51754973/865ce7aa-f690-4e47-9793-7112ddc717a1)

**Comment by mehalter** [comment]
Can you please provide more succinct steps to reproduce this bug you are describing? I have tried many things and cannot replicate it. This would include (1) an example file, (2) your user configuration, (3) the language servers and null-ls sources showing as attached in the statusline, (4) the filetype that AstroNvim is detecting also showing in the statusline

**Comment by mohad12211** [comment]
reinstalling fixed it for me.
I have no idea why, since I literally had nothing other than the plugins line and the colorscheme line in my user config.
