### ISSUE TITLE
markdown-preview feature request

### ISSUE THREAD

**Issue by zhangboSJTU** [AstroNvim/AstroNvim#1921]
### Is your feature related to a problem?

I want to use markdown-preview in AstroNvim

### Describe the new feature

https://github.com/iamcco/markdown-preview.nvim
I want to use markdown-preview in AstroNvim

**Comment by mehalter** [comment]
You can add this in your user configuration: https://astronvim.com/Recipes/custom_plugins

This is not a plugin that we want to upstream into core AstroNvim, but feel free to add it to your own configuration using the documentation

**Comment by mehalter** [comment]
The best place to ask questions is on the discord server: https://discord.gg/AstroNvim

There are lots of great users who can help answer questions and also many questions you may have have probably already been answered there as well!
