### ISSUE TITLE
neo-tree window shark 

### ISSUE THREAD

**Issue by chaozwn** [AstroNvim/AstroNvim#1926]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macos 13.3.1

### Terminal/GUI

item2

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.15.11
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

neo-tree window shark.

https://github.com/AstroNvim/AstroNvim/assets/51357674/9daa5096-afa9-47cb-a46f-7b9e4dff2a13

### Steps to Reproduce

1. remove "astrocommunity.pack.typescript" from community.lua
2. ctrl + h and ctrl + l , swich buffer to neotree

### Expected behavior

window with out shark

**Comment by mehalter** [comment]
Can you please describe the bug more? I can't tell what's happening from this recording.

**Comment by chaozwn** [comment]
> 

Click or switch windows, neo-tree will shake left and right.
After adding event, he will be fine

**Comment by mehalter** [comment]
What do you mean by "after adding event"? Also can you replicate this with a base installation of AstroNvim, without your user configuration?

**Comment by chaozwn** [comment]
> What do you mean by "after adding event"? Also can you replicate this with a base installation of AstroNvim, without your user configuration?

you're right. the base config is ok. i will close this issue.
