### ISSUE TITLE
Luasnip completion priority does nothing

### ISSUE THREAD

**Issue by hatzz** [AstroNvim/AstroNvim#1930]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 12.1

### Terminal/GUI

alacritty

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: v3.15.11
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- WARNING `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Configuring cmp-sources and moving luasnip to the lowest priority i still get snippets before lsp completions. I have copilot completions which works with priority correctly. It seems like snippet completions are tied with nvim_lsp completions since they follow that priority.

I have also tried completely removing luasnip as a completion source which does not work.

You can see my current user config [here](https://github.com/hatzz/dotfiles/tree/main/.config/astronvim-user)

### Steps to Reproduce

Configure the cmp plugin:

```lua
return {
  {
    -- override nvim-cmp plugin
    "hrsh7th/nvim-cmp",
    dependencies = {
      "zbirenbaum/copilot-cmp", -- add cmp source as dependency of cmp
    },
    -- override the options table that is used in the `require("cmp").setup()` call
    opts = function(_, opts)
      -- opts parameter is the default options table
      -- the function is lazy loaded so cmp is able to be required
      local cmp = require "cmp"
      -- modify the sources part of the options table

      opts.sources = cmp.config.sources({
        { name = "copilot",  priority = 1100 },
        { name = "nvim_lsp", priority = 1000 },
        { name = "buffer",   priority = 500 },
        { name = "path",     priority = 250 },
        { name = "luasnip",  priority = 100 },
      })

      -- return the new table to be used
      return opts
    end,
  },
}
```

### Expected behavior

That the snippet completions have the lowest priority and end up last.

### Screenshots

Here we can see that the snippets are at the top:
<img width="889" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/48367822/b088fb96-e4db-45be-b517-638d838f0612">

Tabbing down we end up at lsp-completions:
<img width="834" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/48367822/89c02c35-3f8e-4328-ba44-c71e66aaf2b5">

**Comment by mehalter** [comment]
This would be a bug upstream with `cmp` if it's a bug. Also you should be sure that the snippets are coming from luasnip. I know that `rust_analyzer` provides snippets through the LSP which can cause them to still show up at the top because they are all actually LSP sources. So just make sure that's not the case before reporting a possible bug to `cmp`

**Comment by hatzz** [comment]
That makes sense, thanks for the quick response!

Love this project :)

**Comment by mehalter** [comment]
@hatzz also there has been discussion on the discord about reprioritizing these LSP provided snippets as well. I'm not sure how far that discussion got, but I know it was a relatively complicated setup. But it should be searchable on the help-forum channel.

**Comment by hatzz** [comment]
I joined the discord and found someone talking about the sorting in cmp being bad by default so I ended up fixing it by switching them around and finding configuration online this can be found in my dotfiles-repo :)
