### ISSUE TITLE
How to add coc-status to heirline replace status.component.lsp

### ISSUE THREAD

**Issue by chaozwn** [AstroNvim/AstroNvim#1933]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macos 13.3.1

### Terminal/GUI

item2

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: v3.15.11
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

add coc-status to heirline.

### Steps to Reproduce

 -- Add (Neo)Vim's native statusline support
-- NOTE: Please see `:h coc-status` for integrations with external plugins that
-- provide custom statusline: lightline.vim, vim-airline
vim.opt.statusline:prepend("%{coc#status()}%{get(b:,'coc_current_function','')}")

add it to replace heirline lsp status.

### Expected behavior

Hello, I reconfigured the lsp of astronvim so that it can switch between mason and coc at will, and the keys are consistent. At present, I still need to change the lsp information of statusline to lsp information of coc. I hope you can give some suggestions, thank you very much.

**Comment by chaozwn** [comment]
this is the way we get coc lsp status `vim.opt.statusline:prepend("%{coc#status()}%{get(b:,'coc_current_function','')}")`

**Comment by mehalter** [comment]
Here is the documentation for customizing the statusline with our API: https://astronvim.com/Recipes/status

Here is the documentation for Heirline: https://github.com/rebelot/heirline.nvim/blob/master/cookbook.md

If you have more detailed questions, feel free to join the Discord server as there are more places to ask questions and more users who can spend time on this than I can. Thanks!
