### ISSUE TITLE
hlsearch triggers when hitting "n" to jump to next leap location

### ISSUE THREAD

**Issue by Subjective** [AstroNvim/AstroNvim#1934]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.3

### Terminal/GUI

kitty

### AstroNvim Health

```
==============================================================================
nvim: require("nvim.health").check()

Configuration ~
- OK no issues found

Runtime ~
- OK $VIMRUNTIME: /Users/joshua/.local/share/bob/v0.9.0/nvim-macos/share/nvim/runtime

Performance ~
- OK Build type: Release

Remote Plugins ~
- OK Up to date

terminal ~
- key_backspace (kbs) terminfo entry: `key_backspace=\177`
- key_dc (kdch1) terminfo entry: `key_dc=\E[3~`
- $COLORTERM="truecolor"
```

### Describe the bug

When using leap, hitting "n" to select a jump location also highlights the next search occurrence. I've noticed this issue for quite some time now, but it wasn't really that pressing so I haven't gotten around to reporting it until now.

### Steps to Reproduce

```lua
  -- Minimal Config
  plugins = {
    "AstroNvim/astrocommunity",
    { import = "astrocommunity.motion.leap-nvim" },
  },
```
```txt
repeat text
repeat text
repeat text
repeat text
repeat text
repeat text
repeat text
repeat text
repeat text
repeat text
repeat text
repeat text
repeat text
repeat text
repeat text
repeat text
```
1. Copy the above text into an empty buffer
2. Hit / to enter a search pattern (e.g. re)
3. Hit escape to clear highlight
4. Hit "s" followed by two characters (e.g te) to leap to a location
5. Hit "n" to jump to the indicated location
6. The next occurrence in the previous search pattern gets highlighted

### Expected behavior

Originally, I assumed this was an issue with the leap plugin itself, but the issue seems to be related to astronvim, since the plugin works fine in conjunction with other configs.

### Screenshots

The first half of the demo is done on a minimal astronvim setup, while the second half is done on a minimal nvchad config.
![Screen Recording 2023-05-26 at 2 54 05 PM](https://github.com/AstroNvim/AstroNvim/assets/56745535/447381a1-2462-4872-8b2d-3620c5fc50ad)

**Comment by mehalter** [comment]
You can disable this functionality with the following code in your `polish` function 


```lua
    vim.on_key(function()
    end, vim.api.nvim_create_namespace "auto_hlsearch")
```
