### ISSUE TITLE
Kindly disable autoformat by default

### ISSUE THREAD

**Issue by emailstorbala** [AstroNvim/AstroNvim#1936]
### Is your feature related to a problem?

Whenever I am setting up astronvim, I will do certain changes to the options via 'lua/astronvim/options.lua'. During this period, my all other changes getting properly impacted except the 'autoformat' option since it is enabled by default. The first file which gets modified is the file 'lua/astronvim/options.lua'. If I want to revert the autoformat changes, I have to do a 'git restore' but my intended changes also goes away.

### Describe the new feature

Disable autoformat by default

**Comment by mehalter** [comment]
Aut formatting doesn't start until you install and/or configure a formatter. You can disable this in your user configuration (https://astronvim.com/Recipes/advanced_lsp#customizing-auto-format-on-save) if you would like but we are not planning on disabling this by default. If you have it enabled as well you can also use `<leader>uf` to disable not temporarily. Thanks for the recommendation!
