### ISSUE TITLE
Java language server and JDTLS do not recognize Lombok.

### ISSUE THREAD

**Issue by AthirsonSilva** [AstroNvim/AstroNvim#1937]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Garuda Linux

### Terminal/GUI

Konsole + fish shell

### AstroNvim Health

 astronvim: require("astronvim.health").check()
 
  AstroNvim
AstroNvim Version: v3.16.0
  Neovim Version: v0.9.0
 - OK Using stable Neovim >= 0.8.0
 - OK git is installed: Used for core functionality such as updater and plugin management
 - OK xdg-open is installed: Used for gx mapping for opening files with system opener (Optional)
 - WARNING lazygit is not installed: Used for mappings to pull up git TUI (Optional)
 - OK node is installed: Used for mappings to pull up node REPL (Optional)
 - WARNING gdu is not installed: Used for mappings to pull up disk usage analyzer (Optional)
 - WARNING btm is not installed: Used for mappings to pull up system monitor (Optional)
 - OK python is installed: Used for mappings to pull up python REPL (Optional)
   

### Describe the bug

I am trying to use AstroNvim as a Java IDE, and so far, the only thing i did after installing it was adding the necessary plugins for Java:

![Screenshot from 2023-05-28 11-22-55](https://github.com/AstroNvim/AstroNvim/assets/84593887/472f4f1b-137c-4890-b831-0e351a638381)

And it works pretty well with regular Java projects, but when i open one of my Spring Boot projects that are using Lombok, the LSP doesn't recognize anything related to Lombok.

The strange thing is that it only happens with NeoVim, i also tried other distros and even tried to configure it myself to no success. 

### Steps to Reproduce

1. Install Neovim + AstroNvim
2. Open Mason installer and install jdtls and java-language-server plugins
3. Open any project that is using Lombok as dependency

### Expected behavior

The editor should recognize Lombok and anything  related to it as any other GUI Java IDE.

### Screenshots

![Screenshot from 2023-05-28 11-18-52](https://github.com/AstroNvim/AstroNvim/assets/84593887/1b11fb5b-3ec5-4754-ab4d-b50aebce7bdf)
![Screenshot from 2023-05-28 11-28-10](https://github.com/AstroNvim/AstroNvim/assets/84593887/744931dc-6c17-424f-805d-68672d459f35)

**Comment by mehalter** [comment]
This is unrelated to AstroNvim and would be a bug with the language server or a misconfiguration. The discord is a good place to ask questions as well. Sorry I'm not much help!
