### ISSUE TITLE
Invalid buffer id when trying to autoload a session using resession and vim autocmd

### ISSUE THREAD

**Issue by Asylcreek** [AstroNvim/AstroNvim#1939]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macos 13.3.1

### Terminal/GUI

iTerm2

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.16.0
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

After enabling resession and using their autocmd suggestion on their Readme, whenever I relaunch nvim, I get an error message about an `invalid buffer id`.

But the saved session does get loaded up.

Is there something that I am doing wrong?

### Steps to Reproduce

1. Enable resession
2. Add the autocmd suggestion from their Readme file to your `polish` function
3. Exit neovim
4. Enter vim

### Expected behavior

There should not be any error logs

### Screenshots

<img width="1452" alt="Screenshot 2023-05-29 at 11 36 40" src="https://github.com/AstroNvim/AstroNvim/assets/54318933/08f8bdbe-3712-4102-a332-a0f8688da8d0">

**Comment by mehalter** [comment]
Awesome, thanks for reporting! It's good to figure out what's not working in this experimental feature. I'll take a look at it in the coming days/weeks to see if I can figure out what's the best way to resolve this type of issue. Also it's not really a problem with resession, this is a side effect of our internal logic for doing the statusline. This is just a great way to replicate the issue reliably. This is the same issue that I think users are getting in #1892

**Comment by mehalter** [comment]
@Asylcreek I'm currently working a bit on improving our buffer detection stuff still in our `status` module so this will get released in the next day or so while I finish some stuff up. But I have resolved this auto loading stuff on the latest AstroNvim nightly (and will release with v3.16.2). You basically just need to make sure to disable the alpha auto starting if you are restoring a previous session on startup. Something like this in your `polish` function:

```lua
    vim.api.nvim_del_augroup_by_name "alpha_autostart" -- disable alpha auto start
    vim.api.nvim_create_autocmd("VimEnter", {
      callback = function()
        -- Only load the session if nvim was started with no args
        if vim.fn.argc(-1) == 0 then
          -- Save these to a different directory, so our manual sessions don't get polluted
          require("resession").load(vim.fn.getcwd(), { dir = "dirsession", silence_errors = true })
        end
      end,
    })
```

**Comment by chaozwn** [comment]
> 

lspsaga looks work well, but ressesion may still have some problems. because when resession, lt always return a empty buffer.

**Comment by Asylcreek** [comment]
@mehalter I confirm that this solves the problem, but I would like to point out that it logs an error if `alpha` is disabled
<img width="1728" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/54318933/3453f8b5-7e2c-4e0c-acb3-bfc45ef6c7f3">

**Comment by mehalter** [comment]
Yes this is true @Asylcreek , if you do not have alpha enabled then that autocmd will not exist. It will be up to you as the user doing customization to not try to disable the autostarting of Alpha if you have removed alpha yourself.

**Comment by Asylcreek** [comment]
Alright then. That makes sense.

Thank you very much
