### ISSUE TITLE
Config falls apart once user mkdir-ed in lua directory

### ISSUE THREAD

**Issue by Gurmukh-Singh-4253** [AstroNvim/AstroNvim#1940]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.0

### Terminal/GUI

iTerm2

### AstroNvim Health

astronvim: require("astronvim.health").check()

- ERROR Failed to run healthcheck for "astronvim" plugin. Exception:
  function health#check, line 25
  Vim(eval):E5108: Error executing lua ...urmukhsingh/.config/nvim/lua/astronvim/utils/updater.lua:80: attempt to index field 'updater' (a nil value)
  stack traceback:
  ...urmukhsingh/.config/nvim/lua/astronvim/utils/updater.lua:80: in function 'version'
  /Users/gurmukhsingh/.config/nvim/lua/astronvim/health.lua:15: in function 'check'
  [string "luaeval()"]:1: in main chunk

### Describe the bug

as soon as i created the user directory under lua and asked it to load a colorscheme monokai-pro, AstroNvim stops working at all. the following message is displayed. 
<img width="1440" alt="Screenshot 2023-05-29 at 21 40 19" src="https://github.com/AstroNvim/AstroNvim/assets/111715777/8f9ae5cf-7829-463b-934c-9a5b4a166ffd">

### Steps to Reproduce

1. download astrovim by the git clone command
2. create directory ~/.config/nvim/lua/**user**
3. create an init.lua asking it to install a plugin colorscheme and use that.
4. try to call nvim again

### Expected behavior

AstroNvim loads with the desired colorscheme

### Screenshots

<img width="1440" alt="Screenshot 2023-05-29 at 22 01 10" src="https://github.com/AstroNvim/AstroNvim/assets/111715777/789e8bb1-8a40-43b3-aabf-a3827977fc91">
**~/.config/nvim/lua/user/init.lua**
<img width="1440" alt="Screenshot 2023-05-29 at 21 40 19" src="https://github.com/AstroNvim/AstroNvim/assets/111715777/b702157d-8b18-44b5-ae26-4a2ede2a6a86">
Error message when nvim called

### Additional Context
macOS 13.0
Mac M1
iTerm2 terminal
neovim version 0.9.0
AstroNvim 3.15.0ㅤ

**Comment by mehalter** [comment]
Please check your file for syntax errors. There are a lot of syntax errors here which is making your file fail to load.

**Comment by mehalter** [comment]
here is an example of what a `user/init.lua` file would look like:

```lua
return {
  colorscheme = "monokai-pro",
  plugins = {
    "loctvl842/monokai-pro.nvim",
  },
}
```

**Comment by Gurmukh-Singh-4253** [comment]
Thanks a lot sir.
