### ISSUE TITLE
Not sure the cause of this error

### ISSUE THREAD

**Issue by duytrung** [AstroNvim/AstroNvim#1946]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Windows 11

### Terminal/GUI

Windows Terminal

### AstroNvim Health

![image](https://github.com/AstroNvim/AstroNvim/assets/2046672/13bfb428-5d24-4193-abaf-bbf8cfabd845)
  2   astronvim: require("astronvim.health").check()
   3
   4   AstroNvim
   5   - AstroNvim Version: unknown
   6   - Neovim Version: v0.9.1
   7   - OK Using stable Neovim >= 0.8.0
   8   - ERROR git is not installed: Used for core functionality such as updater and plugin management
   9   - OK explorer is installed: Used for gx mapping for opening files with system opener (Optional)
  10   - WARNING lazygit is not installed: Used for mappings to pull up git TUI (Optional)
  11   - WARNING node is not installed: Used for mappings to pull up node REPL (Optional)
  12   - WARNING gdu is not installed: Used for mappings to pull up disk usage analyzer (Optional)
  13   - WARNING btm is not installed: Used for mappings to pull up system monitor (Optional)
  14   - WARNING python/python3 is not installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

I saw this message on starting Neovim:

Error detected while processing C:\Users\user\AppData\Local\nvim\init.lua:
No specs found for module astrocommunity.colorscheme.kanagawa
Press ENTER or type command to continue

### Steps to Reproduce

Start Neovim
The message shown up
Press any key to skip it

### Expected behavior

I didn't see such message when starting with non-nightly releases. As I have seen the programmed has update and remove a component "kanagawa"

### Screenshots

![image](https://github.com/AstroNvim/AstroNvim/assets/2046672/2ca2d07d-5b2f-4b48-8476-67e24d2d6ce0)

### Additional Context

Thanks for considering the issue :)

**Comment by mehalter** [comment]
This is because of a breaking change in AstroCommunity. I would take a look there :)

**Comment by amplexus** [comment]
I got this error too. Root cause was some of the Astronvim Community plugins were renamed by that team. Once I updated the references in my nvim conf to point at the new names, the errors went away.
