### ISSUE TITLE
run command `nvim .` the neotree width is not normal.

### ISSUE THREAD

**Issue by chaozwn** [AstroNvim/AstroNvim#1949]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macos 13.3.1

### Terminal/GUI

kitty

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: v3.16.2
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Can we keep it consistent so that it displays at full width both when no file is open and when there is a file?
![image](https://github.com/AstroNvim/AstroNvim/assets/51357674/ea9ccde4-513b-4168-977d-60e5b26be084)

![image](https://github.com/AstroNvim/AstroNvim/assets/51357674/5982a75f-4b10-4eca-b73a-1ce3873f2a94)

### Steps to Reproduce

1. run `nvim .`
2. checkout neo-tree.

### Expected behavior

neotree width is 30.

**Comment by mehalter** [comment]
This is a feature that has been built in particular to replicate basic `netrw` support. You can modify this by changing your `neo-tree` configuration. Here is an example `user/init.lua` file that does what you want:

```lua
return {
  plugins = {
    {
      "nvim-neo-tree/neo-tree.nvim",
      opts = {
        filesystem = {
          hijack_netrw_behavior = "open_default",
        },
      },
    },
  },
}
```

Be sure to check out the `neo-tree` documentation for all of the available options it has :)
