### ISSUE TITLE
yaml autocomplete not working on macos 13

### ISSUE THREAD

**Issue by szechp** [AstroNvim/AstroNvim#1952]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macos 13.3.1

### Terminal/GUI

iterm2

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.17.0
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

i moved my setup from ubuntu to neovim. yaml autocomplete and suggestion stopped working. to check if its my setup i testet it with a clean neovim setup. still no autocomplete or suggestions. 

example yaml that wont work:

```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/argoproj/argo-cd//manifests/cluster-install?ref=stable
- argocd-known-hosts.yaml

patches:
- path: argocd-known-hosts-mounts.yaml
```

i installed :LspInstall yamlls and :TSInstall yaml, nothing more

### Steps to Reproduce

start nvim.
install yaml lsp and ts
no autocomplete

### Expected behavior

i expected autocomplete for yamls

**Comment by mehalter** [comment]
You will need to make sure that your `yaml` file is recognized in a pattern that is recognizable by the schemas in schema store. I have tested this with a fresh install and simply running `:LspInstall yamlls` and then opening a file in the AstroNvim `.github/workflows` directory and it is working as intended. 

![2023-06-01_21:16:35_screenshot](https://github.com/AstroNvim/AstroNvim/assets/1591837/9bddfeae-e321-4638-b07b-9bba3301f659)

We also don't do anything in particular with any language servers, so if you are getting an issue with a language server it is probably coming from it being improperly configured in some way. The Discord server is a great place to ask questions as well and there are many great users who can provide guidance.

**Comment by szechp** [comment]
Okay that's weird, gitlab ci yamls work, but anything k8s related does not :/ (argocd, kustomize and kubernetes native)

**Comment by mehalter** [comment]
Please refer to my previous comment regarding making sure your files are recognizable by the patterns defined in SchemaStore

**Comment by szechp** [comment]
so i could not let this go, and dis some further research:

i used kubernetes schema from here: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.27.2/all.json. i had to change it a little bit, i used anyOf to get pattern matching to work. but i cant add this the way i'm used to:

```
    ["server-settings"] = {
      -- example for addings schemas to yamlls
      yamlls = { -- override table for require("lspconfig").yamlls.setup({...})
        settings = {
          yaml = {
            schemas = {
              ["/Users/myusername/k8s1.27.2.json"] = "/*.{yaml,yml}",
            },
          },
        },
      },
    },

```
this does nothing, i still get snippets suggested, but no autoindendation or autocompletion.

BUT when i do this convoluted way:

```
    local function yaml_ft(path, bufnr)
      -- get content of buffer as string
      local content = vim.filetype.getlines(bufnr)
      if type(content) == "table" then content = table.concat(content, "\n") end
      -- check if file is in roles, tasks, or handlers folder
      local path_regex = vim.regex "(tasks\\|roles\\|handlers)/"
      if path_regex and path_regex:match_str(path) then return "yaml.ansible" end
      -- check for known ansible playbook text and if found, return yaml.ansible
      local regex = vim.regex "hosts:\\|tasks:"
      if regex and regex:match_str(content) then return "yaml.ansible" end
      -- check for Kubernetes specific properties
      local k8s_regex = vim.regex "apiVersion:\\|kind:\\|metadata:\\|spec:"
      if k8s_regex and k8s_regex:match_str(content) then return "k8s.yaml" end
      -- return yaml if nothing else
      return "yaml"
    end

```
```
    function setup_k8s_lsp()
      require("lspconfig").yamlls.setup {
        cmd = { "/opt/homebrew/bin/node", "/Users/philipp/.local/share/nvim/mason/bin/yaml-language-server", "--stdio" },
        settings = {
          yaml = {
            schemas = {
              ["/Users/philipp/k8s1.27.2.json"] = "/*.{yaml,yml}",
            },
          },
        },
        filetypes = { "k8s.yaml" },
      }
    end



```
and an autocommand: `vim.cmd [[ autocmd FileType k8s.yaml lua setup_k8s_lsp() ]]`

it works, but
![Screenshot 2023-06-28 at 09 43 42](https://github.com/AstroNvim/AstroNvim/assets/4
 i get this error, and treesitter seems to be borked:
![Screenshot 2023-06-28 at 09 45 10](https://github.com/AstroNvim/AstroNvim/assets/45265588/0de5bb3d-041f-4e36-b859-d241f9264174)
5265588/e7ba92ac-55f6-47db-bc85-ae9d8ce7de48)

**Comment by szechp** [comment]
so changing from k8s.yaml to yaml.k8s as custom filetype brought back treesitter hls. and disabling ufo fixed the linefoldingonly error
