### ISSUE TITLE
"." is not working. 

### ISSUE THREAD

**Issue by alex-belost** [AstroNvim/AstroNvim#1955]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.3.1

### Terminal/GUI

iTerm2

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.17.0
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

The Vim key "." is not working. 
Found out on with nvim-surround plugin

### Steps to Reproduce

1. Clone clear AstroNvim package
2. Install all dependencies
3. Try to repeat any command by pressing the dot

### Expected behavior

Correctly working registers

### Additional Context
Tested on NvChad and clean nvim and with nvim-surround plugin

_No response_

**Comment by mehalter** [comment]
Tested with this minimal config:

```lua
return {
  plugins = {
    {
      "kylechui/nvim-surround",
      event = "VeryLazy",
      opts = {},
    },
  },
}
```

and it seems to be working as intended. It could be a poor interaction between plugins in your configuration or a bug in your user configuration

**Comment by mehalter** [comment]
Also @alex-belost I tested with your user configuration (https://github.com/alex-belost/astronvim-user/tree/main) and it also seems to be working in your configuration as well.

**Comment by alex-belost** [comment]
I reinstalled AstroNvim right now works great :) If I found out why it's happened I let you know
