### ISSUE TITLE
Error while CursorMoved Autocommands for "*"

### ISSUE THREAD

**Issue by rikusen0335** [AstroNvim/AstroNvim#1956]
### Checklist

- [x] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.3.1 M2 Mac

### Terminal/GUI

Warp

### AstroNvim Health

```
==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: nightly (v3.17.0)
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- WARNING `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)
```

### Describe the bug

I am getting error while using resession and patch this: #1939

```
CursorMoved Autocommands for "*" の処理中にエラーが検出されました:
Error executing lua callback: ....local/share/nvim/lazy/fsplash.nvim/lua/fsplash/init.lua:71: Invalid window id: 1002
stack traceback:
        [C]: in function 'nvim_win_close'
        ....local/share/nvim/lazy/fsplash.nvim/lua/fsplash/init.lua:71: in function <....local/share/nvim/lazy/fsplash.nvim/lua/fsplash/init.lua:69>
```

`CursorMoved Autocommands for "*" の処理中にエラーが検出されました:` means `Error occured while executing 'CursorMoved Autocommands for "*"'`

### Steps to Reproduce

I have no time to make a reproduce (which means you don't have to take a look at this issue), so let me leave my repo here: https://github.com/rikusen0335/.astronvim/tree/v2

### Expected behavior

Just no error and loads last session.

### Screenshots

![image](https://github.com/AstroNvim/AstroNvim/assets/19174234/1ec0a386-118c-4402-a524-24b9015bda7f)

**Comment by mehalter** [comment]
Please refer to the `fsplash` documentation. You probably need to enable the `resession` extension for `fsplash`.

**Comment by rikusen0335** [comment]
^ This was it.

Creating `plugins/resession.lua` and paste them: Will fix the problem
```lua
return {
  "stevearc/resession.nvim",
  opts = {
    extensions = {
      fsplash = {},
    },
  },
}
```
