### ISSUE TITLE
Keybinding not working

### ISSUE THREAD

**Issue by rastop123g** [AstroNvim/AstroNvim#1961]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Archlinux

### Terminal/GUI

alcritty

### AstroNvim Health

astronvim: require("astronvim.health").check()
   3
   4   AstroNvim
   5   - AstroNvim Version: v3.18.0
   6   - Neovim Version: v0.9.0
   7   - OK Using stable Neovim >= 0.8.0
   8   - OK git is installed: Used for core functionality such as updater and plugin management
   9   - OK xdg-open is installed: Used for gx mapping for opening files with system opener (Optional)
  10   - OK lazygit is installed: Used for mappings to pull up git TUI (Optional)
  11   - OK node is installed: Used for mappings to pull up node REPL (Optional)
  12   - WARNING gdu is not installed: Used for mappings to pull up disk usage analyzer (Optional)
  13   - OK btm is installed: Used for mappings to pull up system monitor (Optional)
  14   - OK python is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

I set in the user config file:
mappings = {
  n = {
    ["<S-h>"] = {
          function() require("astronvim.utils.buffer").nav(-(vim.v.count > 0 and vim.v.count or 1)) end,
             desc = "Previous buffer",
          }
  }
}

And it doesn't work for switching buffers by shift +[h,l], but other bindings work, I have to write S-h, S-l in the original mappings.lua file and then it works

### Steps to Reproduce

I set in the user config file:
mappings = {
  n = {
    ["<S-h>"] = {
          function() require("astronvim.utils.buffer").nav(-(vim.v.count > 0 and vim.v.count or 1)) end,
             desc = "Previous buffer",
          }
  }
}

And it doesn't work for switching buffers by shift +[h,l], but other bindings work, I have to write S-h, S-l in the original mappings.lua file and then it works

### Expected behavior

This should work

**Comment by rastop123g** [comment]
i set S-h in mappings.n, S-h not printed in the bug report into [""]

**Comment by mehalter** [comment]
It should be `"H"` or `<S-h>`

**Comment by rastop123g** [comment]
I set "H" and <S-h> and <S-H>, not working

**Comment by mehalter** [comment]
Do you have a `mappings.lua` file? That will take precedence over your `user/init.lua` file

**Comment by rastop123g** [comment]
I will try again

**Comment by mehalter** [comment]
If you can share your user configuration I can help you debug what might be going on

**Comment by rastop123g** [comment]
I'm sorry, I really made bindings in the init file, after transferring to mappings.lua everything started working
