### ISSUE TITLE
Use the cmp plug-in, switch the prompt through ctrl-j ctrl-k, and the status bar will flash

### ISSUE THREAD

**Issue by zhouchuanfu** [AstroNvim/AstroNvim#1962]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

uos 22.0

### Terminal/GUI

deepin-terminal

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: nightly (v3.18.0-4-g3fdb3aa)
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

==============================================================================
lazy: require("lazy.health").check()

lazy.nvim ~
- OK Git installed
- OK no existing packages found by other package managers
- OK packer_compiled.lua not found
- WARNING {lualine.nvim}: unknown key <optional>

==============================================================================
nvim: require("nvim.health").check()

Configuration ~
- OK no issues found

Runtime ~
- $VIMRUNTIME: /usr/share/nvim/runtime
- ERROR $VIMRUNTIME has files from an old installation (this can cause weird behavior):
  /usr/share/nvim/runtime/scripts.vim
  /usr/share/nvim/runtime/plugin/man.vim
  /usr/share/nvim/runtime/autoload/man.vim
  - ADVICE:
    - Delete $VIMRUNTIME (or uninstall Nvim), then reinstall Nvim.

Performance ~
- OK Build type: RelWithDebInfo

Remote Plugins ~
- OK Up to date

terminal ~
- key_backspace (kbs) terminfo entry: `key_backspace=\177`
- key_dc (kdch1) terminfo entry: `key_dc=\E[3~`
- $COLORTERM="truecolor"

==============================================================================
provider: health#provider#check

Clipboard (optional) ~
- OK Clipboard tool found: xclip

Python 3 provider (optional) ~
- `g:python3_host_prog` is not set.  Searching for python3 in the environment.
- Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
- Executable: /usr/bin/python3
- Other python executable: /bin/python3
- Python version: 3.7.3
- pynvim version: 0.4.3
- OK Latest pynvim is installed.

Python virtualenv ~
- OK no $VIRTUAL_ENV

Ruby provider (optional) ~
- Ruby: ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]
- WARNING `neovim-ruby-host` not found.
  - ADVICE:
    - Run `gem install neovim` to ensure the neovim RubyGem is installed.
    - Run `gem environment` to ensure the gem bin directory is in $PATH.
    - If you are using rvm/rbenv/chruby, try "rehashing".
    - See :help |g:ruby_host_prog| for non-standard gem installations.
    - You may disable this provider (and warning) by adding `let g:loaded_ruby_provider = 0` to your init.vim

Node.js provider (optional) ~
- Node.js: v16.20.0
- Nvim node.js host: /home/zcf/.config/nvm/versions/node/v16.20.0/lib/node_modules/neovim/bin/cli.js
- OK Latest "neovim" npm/yarn/pnpm package is installed: 4.10.1

Perl provider (optional) ~
- WARNING "Neovim::Ext" cpan module is not installed
  - ADVICE:
    - See :help |provider-perl| for more information.
    - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

==============================================================================
vim.lsp: require("vim.lsp.health").check()

- LSP log level : WARN
- Log path: /home/zcf/.local/state/nvim/lsp.log
- Log size: 0 KB

vim.lsp: Active Clients ~
- No active clients

==============================================================================
vim.treesitter: require("vim.treesitter.health").check()

- Nvim runtime ABI version: 14
- OK Parser: c          ABI: 13, path: /usr/lib/nvim/parser/c.so
- OK Parser: lua        ABI: 13, path: /usr/lib/nvim/parser/lua.so
- OK Parser: query      ABI: 14, path: /usr/lib/nvim/parser/query.so
- OK Parser: vim        ABI: 14, path: /usr/lib/nvim/parser/vim.so
- OK Parser: vimdoc     ABI: 14, path: /usr/lib/nvim/parser/vimdoc.so

==============================================================================
which-key: require("which-key.health").check()

WhichKey: checking conflicting keymaps ~
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"ys"**
- rhs: `<Plug>(nvim-surround-normal)`
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"yS"**
- rhs: `<Plug>(nvim-surround-normal-line)`

### Describe the bug

Like the screenshot below, as long as you switch the input content of the prompt, the status bar below will flash, I don't know what the reason is

### Steps to Reproduce

 non-essential

### Expected behavior

The status bar does not flash when switching

### Screenshots

![录屏_选择区域_20230603193533](https://github.com/AstroNvim/AstroNvim/assets/46174387/2eb45b9c-3438-4c19-96ba-807c2aee2929)

![图片](https://github.com/AstroNvim/AstroNvim/assets/46174387/39c20519-4b14-441c-868e-1e724b6809aa)
![图片](https://github.com/AstroNvim/AstroNvim/assets/46174387/ee2edec5-29d7-4569-896a-01f51557ace1)

**Comment by mehalter** [comment]
This is a known bug with `cmp` and `neovim`. You can resolve it by changing `cmdheight=1`

https://github.com/hrsh7th/nvim-cmp/issues/1396
https://github.com/hrsh7th/nvim-cmp/issues/1382
