### ISSUE TITLE
Ression load last session open last close tab default, not a empty tab.

### ISSUE THREAD

**Issue by chaozwn** [AstroNvim/AstroNvim#1967]
### Is your feature related to a problem?

this is my exit screen.
![image](https://github.com/AstroNvim/AstroNvim/assets/51357674/596588ce-1ab4-49cb-9fe7-84317b419c72)
this is open from resssion, which is last session.
![image](https://github.com/AstroNvim/AstroNvim/assets/51357674/64717e78-8564-4af8-bf82-30bb8befaba2)

### Describe the new feature

Ression load last session open last close tab default, not a empty tab.

**Comment by mehalter** [comment]
Are you actually using `resession` or the default session management?

**Comment by chaozwn** [comment]
> Are you actually using `resession` or the default session management?

i make sure, i'm use ression.
![image](https://github.com/AstroNvim/AstroNvim/assets/51357674/ef8f52a5-b512-4c2f-ac88-bfe1c1ea92f4)

**Comment by mehalter** [comment]
I cannot replicate this empty tab behavior. It works on my end as intended. Can you replicate without your user configuration?

**Comment by chaozwn** [comment]
> I cannot replicate this empty tab behavior. It works on my end as intended. Can you replicate without your user configuration?

sorry, it seems happened when use`nvim .` open project then `<leader>Sf` load a session.

**Comment by mehalter** [comment]
I was able to verify that this is happening with your user configuration and not without it. So something you are doing needs to be modified to play nicely with resession. Could be a plugin that doesn't have good support or something. If you look into it and can reduce it down to a minimal user configuration (or no user configuration) that demonstrates a bug then I can look into it. Sorry, but I don't have time to go through your lengthy user configuration and figure it out.
