### ISSUE TITLE
bug , 

### ISSUE THREAD

**Issue by newyorkthink** [AstroNvim/AstroNvim#1968]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

1

### Terminal/GUI

1

### AstroNvim Health

1

### Describe the bug

![image](https://github.com/AstroNvim/AstroNvim/assets/87791643/7fd16026-53a0-4601-8662-a1b9d9dabd9a)

### Steps to Reproduce

1

### Expected behavior

1

### Screenshots

![image](https://github.com/AstroNvim/AstroNvim/assets/87791643/a0303906-b0a0-4609-b0c5-3d0fa7f17959)

**Comment by luxus** [comment]
please fill out the fields. they are included for a reason.
you can reopened when you are done
