### ISSUE TITLE
Opt in feature: On Event: `LazySync` run `:AstroUpdate`

### ISSUE THREAD

**Issue by jay-babu** [AstroNvim/AstroNvim#1969]
### Is your feature related to a problem?

I and maybe most people are typically coupled to plugin managers and their conventions. To look at what plugins I have and other related data, I do `:Lazy` then `Sync`, which updates plugins perfectly fine. The problem it is, it does not update `AstroNvim`, which doesn't follow the conventions of plugins and being updated in that manner. This has led me to hours of debugging why something is broken, then eventually realizing `AstroNvim` is out of date.

### Describe the new feature

1. On `LazySync` and if some feature is enabled, then run `:AstroUpdate`
2. Maybe event `LazyPreSync` needs to exist before this can happen

**Comment by mehalter** [comment]
This is not something I want to do necessarily, one thing that does happen is if you run `:AstroUpdate` and there is an update then it does sync packages and plugins (mason and lazy). Maybe we can make it update lazy and mason even if there isn't an update available

**Comment by jay-babu** [comment]
yes, correct. I just prefer to be more coupled to the plugin manager and have it manage all dependencies. That is a good point about mason, though

**Comment by mehalter** [comment]
Yeah you can set up personal coupling. But this is not what we want to provide by default. Default behavior of commands and plugins should remain. We should modify our own command. You can use it or use something you make yourself. I'll add the feature you want later

**Comment by jay-babu** [comment]
https://github.com/AstroNvim/AstroNvim/blob/445a88397397e88fdb4587bd48a03f5053c04ef1/lua/astronvim/utils/updater.lua#L110

maybe this can change to run on `LazySync`. don't know your thoughts on that

**Comment by jay-babu** [comment]
Okay maybe I can reword my thoughts to make it less personal request.

The job of `:Lazy sync` is to update all plugins. It also provides the tooling needed to perform actions based on certain events around it (i.e. after a sync). Instead of astronvim utilizing that provided functionality, astronvim creates its own convention of `:AstroUpdate` to update itself, dependencies, and `mason`. This provides more friction for people migrating onto astronvim as they have to learn one more way to manage updates. In my personal experience, adding new conventions where there aren't needed leads to more OE work in the future and maintenance. Also, having multiple ways of doing one thing (dependencies updates) leads to confusion. Like `Lazy sync` is available and you can use, but that won't update astronvim, if you want that use `:AstroUpdate`

The argument of astronvim exists and is not a plugin, it is more a framework is valid and thus it should not utilize `Lazy sync` which is only meant for dependencies (plugins) however that one caveat pales (imo) to the added learnings for users and maintenance that comes from exposing a new way of updating

**Comment by mehalter** [comment]
This has been implemented and resolved on `nightly`
