### ISSUE TITLE
Feature request: Intelisense-liked command typing improvement

### ISSUE THREAD

**Issue by duytrung** [AstroNvim/AstroNvim#1972]
### Is your feature related to a problem?

Hello,

While typing the command such as "Lazy sync" by typing "L" and "Tab" then the dialog will pop up with a few options such as follows:
[1]
![image](https://github.com/AstroNvim/AstroNvim/assets/2046672/b0f6f7d8-fa44-4e63-a969-5930183025ae)

after that pressing "Tab" again will appear another dialog with possible options as follows:
[2]
![image](https://github.com/AstroNvim/AstroNvim/assets/2046672/e9c9346c-b08a-4d9c-8f79-9884598c7ed7)

The problem is if at first we did not choose "Lazy" then we have to press "backspace" and get another "hint" 

### Describe the new feature

How to _keep_ the popup dialog for awhile and implement a keyboard shortcut to quickly choose the option without having to **_retype_** the command? Such as in screenshot [1], we have the **L**azy and Lsp**I**nstall and Lsp**U**ninstall where we could choose the L, or I, or U just for closing the first pop up and second popup with similar options.

### Additional context

Thanks for considering the request

**Comment by mehalter** [comment]
Maybe what you want is `cmp-cmdline` which puts `cmp` in the command line. There is a snippet in the docs for setting this up, but it is relatively complicated: https://astronvim.com/Recipes/cmp#advanced-setup-for-filetype-and-cmdline

I have looked into putting this into AstroNvim core and there are some stability things and workflow stuff that keeps this off our roadmap. Hopefully this points you in the right direction though!
