### ISSUE TITLE
luasnip luasnip and store_selection_keys

### ISSUE THREAD

**Issue by tofulm** [AstroNvim/AstroNvim#1982]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Archlinux

### Terminal/GUI

Kitty

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.21.0-1-g400170a
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

==============================================================================
gitsigns: require("gitsigns.health").check()

- OK git version 2.41.0

==============================================================================
lazy: require("lazy.health").check()

lazy.nvim ~
- OK Git installed
- OK no existing packages found by other package managers
- OK packer_compiled.lua not found
- WARNING {LuaSnip}: overriding <config>

==============================================================================
mason: require("mason.health").check()

mason.nvim ~
- OK mason.nvim version v1.1.1
- OK PATH: prepend
- OK Providers: 
  mason.providers.registry-api
  mason.providers.client
- OK neovim version >= 0.7.0

mason.nvim [Registries] ~
- OK Registry `github.com/mason-org/mason-registry version: 2023-06-09-kindly-mile` is installed.

mason.nvim [Core utils] ~
- OK unzip: `UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send`
- OK wget: `GNU Wget 1.21.4 compilé sur linux-gnu.`
- OK curl: `curl 8.1.2 (x86_64-pc-linux-gnu) libcurl/8.1.2 OpenSSL/3.0.9 zlib/1.2.13 brotli/1.0.9 zstd/1.5.5 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.10.0 nghttp2/1.53.0`
- OK gzip: `gzip 1.12`
- OK tar: `tar (GNU tar) 1.34`
- OK bash: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
- OK sh: `Ok`

mason.nvim [Languages] ~
- WARNING Go: not available
  - ADVICE:
    - spawn: go failed with exit code - and signal -. go is not executable
- OK Ruby: `ruby 3.0.5p211 (2022-11-24 revision ba5cf0f7c5) [x86_64-linux]`
- OK cargo: `cargo 1.70.0`
- OK PHP: `PHP 8.2.6 (cli) (built: May  9 2023 16:47:59) (NTS)`
- OK node: `v16.20.0`
- WARNING javac: not available
  - ADVICE:
    - spawn: javac failed with exit code - and signal -. javac is not executable
- WARNING java: not available
  - ADVICE:
    - spawn: java failed with exit code - and signal -. java is not executable
- WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. julia is not executable
- OK python3: `Python 3.11.3`
- OK luarocks: `/usr/bin/luarocks 3.9.2`
- OK Composer: `Composer version 2.5.7 2023-05-24 15:00:39`
- OK RubyGem: `3.3.25`
- OK pip3: `pip 23.1.2 from /usr/lib/python3.11/site-packages/pip (python 3.11)`
- OK npm: `8.19.2`

mason.nvim [GitHub] ~
- OK GitHub API rate limit. Used: 0. Remaining: 60. Limit: 60. Reset: ven. 09 juin 2023 10:23:06.
  Install and authenticate via gh-cli to increase rate limit.

==============================================================================
null-ls: require("null-ls.health").check()

- no sources registered

==============================================================================
nvim: require("nvim.health").check()

Configuration ~
- OK no issues found

Runtime ~
- OK $VIMRUNTIME: /usr/share/nvim/runtime

Performance ~
- OK Build type: Release

Remote Plugins ~
- OK Up to date

terminal ~
- key_backspace (kbs) terminfo entry: `key_backspace=\177`
- key_dc (kdch1) terminfo entry: `key_dc=\E[3~`
- $COLORTERM="truecolor"

==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (0c49d6745b3fc4822ab02e0018770cd6383a779c) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v16.20.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 13.1.1 20230429
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.3.6-arch1-1",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Mon, 05 Jun 2023 15:12:57 +0000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - css                 ✓ . ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - php                 ✓ ✓ ✓ ✓ ✓
  - scss                ✓ . ✓ ✓ .
  - vue                 ✓ . ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

==============================================================================
provider: health#provider#check

Clipboard (optional) ~
- OK Clipboard tool found: wl-copy

Python 3 provider (optional) ~
- `g:python3_host_prog` is not set.  Searching for python3 in the environment.
- Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
- Executable: /usr/bin/python3
- Other python executable: /sbin/python3
- Python version: 3.11.3
- pynvim version: 0.4.3
- OK Latest pynvim is installed.

Python virtualenv ~
- OK no $VIRTUAL_ENV

Ruby provider (optional) ~
- Ruby: ruby 3.0.5p211 (2022-11-24 revision ba5cf0f7c5) [x86_64-linux]
- WARNING `neovim-ruby-host` not found.
  - ADVICE:
    - Run `gem install neovim` to ensure the neovim RubyGem is installed.
    - Run `gem environment` to ensure the gem bin directory is in $PATH.
    - If you are using rvm/rbenv/chruby, try "rehashing".
    - See :help |g:ruby_host_prog| for non-standard gem installations.
    - You may disable this provider (and warning) by adding `let g:loaded_ruby_provider = 0` to your init.vim

Node.js provider (optional) ~
- Node.js: v16.20.0
- Nvim node.js host: /home/tof/.npm-global/lib/node_modules/neovim/bin/cli.js
- OK Latest "neovim" npm/yarn/pnpm package is installed: 4.10.1

Perl provider (optional) ~
- WARNING "Neovim::Ext" cpan module is not installed
  - ADVICE:
    - See :help |provider-perl| for more information.
    - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

==============================================================================
vim.lsp: require("vim.lsp.health").check()

- LSP log level : WARN
- Log path: /home/tof/.local/state/nvim_astro/lsp.log
- Log size: 98 KB

vim.lsp: Active Clients ~
- emmet_ls (id=1, root_dir=/home/http/www/crfck.spip/plugins/gformation)
- html (id=2, root_dir=/home/http/www/crfck.spip/plugins/gformation)

==============================================================================
vim.treesitter: require("vim.treesitter.health").check()

- Nvim runtime ABI version: 14
- OK Parser: bash       ABI: 14, path: /home/tof/.local/share/nvim_astro/lazy/nvim-treesitter/parser/bash.so
- OK Parser: css        ABI: 13, path: /home/tof/.local/share/nvim_astro/lazy/nvim-treesitter/parser/css.so
- OK Parser: html       ABI: 13, path: /home/tof/.local/share/nvim_astro/lazy/nvim-treesitter/parser/html.so
- OK Parser: javascript ABI: 14, path: /home/tof/.local/share/nvim_astro/lazy/nvim-treesitter/parser/javascript.so
- OK Parser: php        ABI: 14, path: /home/tof/.local/share/nvim_astro/lazy/nvim-treesitter/parser/php.so
- OK Parser: scss       ABI: 13, path: /home/tof/.local/share/nvim_astro/lazy/nvim-treesitter/parser/scss.so
- OK Parser: vue        ABI: 13, path: /home/tof/.local/share/nvim_astro/lazy/nvim-treesitter/parser/vue.so

==============================================================================
which-key: require("which-key.health").check()

WhichKey: checking conflicting keymaps ~
- WARNING conflicting keymap exists for mode **"n"**, lhs: **" s"**
- rhs: ` `
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"ys"**
- rhs: `<Plug>(nvim-surround-normal)`
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"yS"**
- rhs: `<Plug>(nvim-surround-normal-line)`
- WARNING conflicting keymap exists for mode **"v"**, lhs: **" s"**
- rhs: ` `
- WARNING conflicting keymap exists for mode **"v"**, lhs: **"<leader>l"**
- rhs: ` `

### Describe the bug

With luasnip, TM_SELECTED_TEXT not working properly.
This line should be added for TM_SELECTED_TEXT to work correctly.
cf https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#variables
```diff
diff --git a/lua/plugins/configs/luasnip.lua b/lua/plugins/configs/luasnip.lua
index 3ab8be2..a78c576 100644
--- a/lua/plugins/configs/luasnip.lua
+++ b/lua/plugins/configs/luasnip.lua
@@ -1,5 +1,4 @@
 return function(_, opts)
   if opts then require("luasnip").config.setup(opts) end
-  require("luasnip").config.setup({store_selection_keys="<Tab>"})
   vim.tbl_map(function(type) require("luasnip.loaders.from_" .. type).lazy_load() end, { "vscode", "snipmate", "lua" })
 end
 ```

### Steps to Reproduce

snippet: 
```json
"aa": {
		"prefix": "aa",
		"body": [
			"[(${TM_SELECTED_TEXT})]"
		],
		"description": "[(...)]"
	}
```
if you select a text and press TAB, instead of launching the snippet, it makes a tab. 

### Expected behavior

this should erase the selection, then if we run the snippet `aa` it should wrap our text with [(...)].

**Comment by mehalter** [comment]
You can't to customize this by putting 

```
store_selection_keys="<Tab>"
```

Inside your `nvim-cmp` `opts` table rather than trying not overriding the `config` function. This is how you can make arbitrary customizations to your personal setup.

**Comment by mehalter** [comment]
I think actually we will probably want to add this but probably not with `tab` so it doesn't conflict with the normal tab behavior we have set up. We can add a separate binding though to enable this

**Comment by mehalter** [comment]
I'm out of town for the next week, so I can investigate which mapping would be good here and get it added sometime late next week

**Comment by mehalter** [comment]
I went ahead and added this to core AstroNvim on `nightly`. I will merge it after a few days of testing, but it will be added in v3.21.0 . I ended up going with `<C-x>` for the key for this

**Comment by tofulm** [comment]
it's perfect ! 
thanks
