### ISSUE TITLE
Change in neo-tree's behavior

### ISSUE THREAD

**Issue by pysan3** [AstroNvim/AstroNvim#1985]
### Is your feature related to a problem?

Hi, this is not a feature request but rather I just wanted to notify that there was a slight change in neo-tree's behavior.

It seems that the default config for neo-tree in astrovim sets `default_component_config.indent.indent_size` to `1`.

When this value is `1`, the output should have been that the indent consists of only the `indent_marker` (`│` or `└`), but had an additional space which made the indent width 2.

With PR https://github.com/nvim-neo-tree/neo-tree.nvim/pull/977 being merged, the output got fixed.

### Old Behavior

![image](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/41065736/3071df08-500d-4217-a419-2eec22c68cfa)

### New

![image](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/41065736/ee6ccf02-72a4-4ed4-adac-95e612d07b8f)

Please close this issue whenever you want ;)
If you have any questions, feel free to ping me.

---

### Main Issue

Closes https://github.com/nvim-neo-tree/neo-tree.nvim/issues/924

### Detailed Explanation

https://github.com/nvim-neo-tree/neo-tree.nvim/pull/864#issuecomment-1578027693

### Fix

https://github.com/nvim-neo-tree/neo-tree.nvim/pull/864#issuecomment-1579093376

### Describe the new feature

N/A

**Comment by mehalter** [comment]
Thanks for opening this issue and bringing it to my attention! What do you think the new config values should be?

**Comment by pysan3** [comment]
`2` is the default and I have no problem with it :)
And, I think `2` is the closest to the old behavior's look.

You can see screenshots of other values here https://github.com/nvim-neo-tree/neo-tree.nvim/pull/977 (except that `= 1` is the old behavior)

**Comment by mehalter** [comment]
Ok cool. I will go ahead and remove that line and just take the neo-tree default!

**Comment by mehalter** [comment]
@pysan3 I pushed this change to `nightly` AstroNvim. I will release v3.21.0 sometime later next week. I am out of town until Thursday so I won't want to do any releases until I'm back and ready to do damage control if I make any uh-ohs. Thanks again @pysan3 for this heads up and fixing this issue upstream!

**Comment by fynnfluegge** [comment]
Hey @mehalter how can I adjust the neo-tree config? I tried do it as described here  https://astronvim.com/Recipes/custom_plugins#extending-core-plugin-config-functions but it does not work since there is no neo-tree config in `lua/plugins/configs`. Any ideas?

**Comment by mehalter** [comment]
You want to run something more than just the `setup` function or you just want to modify the options that are passed to the `setup()` call? @fynnfluegge

**Comment by mehalter** [comment]
@fynnfluegge most of our plugins don't use the `config` function at all so you can just add one if that's what you want. You probably want to just modify the `opt` table though. Lazy.nvim automatically calls `setup()` with the table built by `opts` which makes it easiest to add to our default options without overriding them or losing them. Here is an example of where I am modifying the core `neo-tree` configuration in my config: https://code.mehalter.com/AstroNvim_user/~files/f5ea01016b3b43add1e6d249ac6e60d1afd11e2d/plugins/core.lua?position=source-30.3-53.5-1

**Comment by fynnfluegge** [comment]
@mehalter Thanks for the fast response, works! 👌
