### ISSUE TITLE
Some keys are "intercepted" in insert mode

### ISSUE THREAD

**Issue by edyu** [AstroNvim/AstroNvim#1987]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

WSL2 Ubuntu 22.04 LTS

### Terminal/GUI

Windows Terminal

### AstroNvim Health

   2 astronvim: require("astronvim.health").check()
   3
   4 AstroNvim
   5 - AstroNvim Version: v3.21.0
   6 - Neovim Version: v0.9.0
   7 - OK Using stable Neovim >= 0.8.0
   8 - OK git is installed: Used for core functionality such as updater and plugin management
   9 - OK xdg-open is installed: Used for gx mapping for opening files with system opener
     (Optional)
  10 - WARNING lazygit is not installed: Used for mappings to pull up git TUI (Optional)
  11 - OK node is installed: Used for mappings to pull up node REPL (Optional)
  12 - WARNING gdu is not installed: Used for mappings to pull up disk usage analyzer
     (Optional)
  13 - WARNING btm is not installed: Used for mappings to pull up system monitor (Optional)
  14 - OK python is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

In insert mode, g and u are somehow "intercepted" by something. So I cannot type u or g. 

### Steps to Reproduce

1. nvim
2. get to insert mode
3.  try to type u or g
4. I can replace any character with u or g so I can type iit and then go to the first i and replace it with g with 'r'

### Expected behavior

g or u should work.

### Additional Context

At first I thought maybe the lsp zls is causing the problem but the problem exists even when I don't load zig files.

**Comment by mehalter** [comment]
Can you replicate with no user configuration. I cannot replicate this at all

**Comment by edyu** [comment]
Without user config (I renamed the whole user directory. I don't see the problem. My user config is super simple though.

**Comment by edyu** [comment]
[user.diff.txt](https://github.com/AstroNvim/AstroNvim/files/11709296/user.diff.txt)

**Comment by mehalter** [comment]
What is this a diff against? The user example template repository?

**Comment by edyu** [comment]
Yes


> What is this a diff against? The user example template repository?

Yes

**Comment by mehalter** [comment]
You will want to debug your user configuration and figure out what is causing this. Given the issue goes away after you remove your user configuration it seems like it's definitely a problem in the user configuration rather than a bug in AstroNvim. The Discord server (https://discord.gg/AstroNvim) is a great place to ask questions and get help with configuration from other users.

If you do some more debugging and find that it is a bug in core AstroNvim with some more refined steps to replicate the bug then comment here and I can reopen this issue :)
