### ISSUE TITLE
(Nightly) BufDelete: Breaking changes

### ISSUE THREAD

**Issue by Zeioth** [AstroNvim/AstroNvim#1996]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

arch

### Terminal/GUI

foot

### AstroNvim Health

x

### Describe the bug

[The updates introduced today in bufdelete](https://github.com/famiu/bufdelete.nvim/commit/42ccf4f63310ddfe5f7572ae5a9ffdf5b7bee1c7) break AstroNvim in the next ways:

* Deleting a tab will space+c will cause an error.
* Closing a tab will pressing the X icon will cause an error.

There is currently an issue opened about it:
https://github.com/famiu/bufdelete.nvim/issues/44

You probably noticed, reporting just in case.
Cheers.

### Steps to Reproduce

x

### Expected behavior

x

**Comment by mehalter** [comment]
Interesting, I'll check this out later. I wonder if this is a new but in bufdelete. We aren't actually using the range feature that they removed. We are only deleting a single buffer at a time

**Comment by mehalter** [comment]
Ah, I am correct, this is a bug upstream and not a bug here: https://github.com/famiu/bufdelete.nvim/issues/44
