### ISSUE TITLE
Problem with telescope-fzf-native.nvim when using Telescope the first time.

### ISSUE THREAD

**Issue by tranmanhlt7a4** [AstroNvim/AstroNvim#2002]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Windows 11 Version 22H2 (OS Build 22631.1835)

### Terminal/GUI

Windows Terminal

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.23.0
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `explorer` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

My problem is the same with https://github.com/AstroNvim/AstroNvim/issues/58. I have tried all suggestions but there isn't anything that works for me. I am still stuck with that problem.
I have tried to run ```make clean & make```; go to all links and try any suggestions there, but nothing works. I also reinstall AstroNvim but the problem is still there.
The problem only happened the first time I used Telescope after starting Neovim. After that, I can use it normally without error.

### Steps to Reproduce

1. Open Neovim
2. Using Telescope (such as ```<leader>ff``` or ```<leader>fw```)
3. The error happened.

### Expected behavior

Run Telescope without error.

**Comment by mehalter** [comment]
How are you running `make`

**Comment by tranmanhlt7a4** [comment]
> How are you running `make`

I go to ```~\AppData\Local\nvim-data\lazy\telescope-fzf-native.nvim``` and run ```make``` and the output is ```make: Nothing to be done for `all'.```
Then I run ```make clean``` and the output is ```cmd /C rmdir /Q /S build```
Then I run ```make``` again and output is
```
cmd /C mkdir build
gcc -O3 -Wall -Werror -fpic -std=gnu99 -shared src/fzf.c -o build/libfzf.dll
````

But the error isn't fixed.

**Comment by mehalter** [comment]
Ah and you don't get any errors with the make I presume? Yeah I honestly have no idea, this Should be asked upstream to the `telescope-fzf-native` folks or you can just disable the plugin all together

**Comment by mehalter** [comment]
Sorry I'm not much help! Also the discord is a great place to ask other users who have similar tech stacks to you to see if they have run into similar issues on windows or something

**Comment by tranmanhlt7a4** [comment]
> 



> Ah and you don't get any errors with the make I presume? Yeah I honestly have no idea, this Should be asked upstream to the `telescope-fzf-native` folks or you can just disable the plugin all together

Oh, I see. I'll open an issue 

> Sorry I'm not much help! Also the discord is a great place to ask other users who have similar tech stacks to you to see if they have run into similar issues on windows or something

Oh, I see. Thank you very much for your help. 
I'll open an issue at Telescope.

**Comment by tranmanhlt7a4** [comment]
> Sorry I'm not much help! Also the discord is a great place to ask other users who have similar tech stacks to you to see if they have run into similar issues on windows or something

Oh, I see. Thank you very much for your help.
I'll open an issue at Telescope.
