### ISSUE TITLE
Disable Notifications not working

### ISSUE THREAD

**Issue by DarkCat5501** [AstroNvim/AstroNvim#2004]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Ubuntu 23.04

### Terminal/GUI

alacritty

### AstroNvim Health

AstroNvim↵
-.AstroNvim.Version:.v3.23.1↵
-.Neovim.Version:.v0.9.0↵
-.OK.Using.stable.Neovim.>=.0.8.0↵
-.OK.git.is.installed:.Used.for.core.functionality.such.as.updater.and.plugin.management↵
-.OK.xdg-open.is.installed:.Used.for.gx.mapping.for.opening.files.with.system.opener.(Optional)↵
-.OK.lazygit.is.installed:.Used.for.mappings.to.pull.up.git.TUI.(Optional)↵
-.OK.node.is.installed:.Used.for.mappings.to.pull.up.node.REPL.(Optional)↵
-.OK.gdu.is.installed:.Used.for.mappings.to.pull.up.disk.usage.analyzer.(Optional)↵
-.WARNING.btm.is.not.installed:.Used.for.mappings.to.pull.up.system.monitor.(Optional)↵
-.OK.python3.is.installed:.Used.for.mappings.to.pull.up.python.REPL.(Optional)↵

### Describe the bug

I can't disable notifications using the key binding leader uN, when i press it show a notification saying the notifications are on, then i do it again and it shows nothing, but trying to send a notification to check and it is still showing

### Steps to Reproduce

1 press default keybing to disable notifications leader uN
2 it will show a notification saying it is on 
3 try to send a notification with ":lua vim.notify("hello")" and it may show up
4 press key binding again to disable notifications
5 it shows nothing
6 but try again sending a notification and it will still show up

### Expected behavior

no notifications should be shown when disabled

### Screenshots

![image](https://github.com/AstroNvim/AstroNvim/assets/34375081/513d797c-a9ab-462c-95d9-f2e5292b5e35)

**Comment by mehalter** [comment]
Yeah this toggle actually only disables UI related notifications, like the notifications triggered by the UI toggle menu. I will convert this to a feature request and consider it. That seems like a better binding and more useful

**Comment by DarkCat5501** [comment]
is there a way of disabling all of them? 
but not always, sometimes i like them

**Comment by mehalter** [comment]
Not sure, Here are the docs for nvim-notify: https://github.com/rcarriga/nvim-notify

**Comment by DarkCat5501** [comment]
i found that i can do a key mapping and just set vim.notify = function(_,_,_) end to disable it

so i did it this way:
```lua
["<leader>uAn"] = { function()
        local notify = require "notify"
        local currNot = vim.notify
        if currNot == notify then
          vim.notify = function(_,_,_)
          
          end
          notify("All notifications disabled")
        else
          vim.notify = notify;
          notify("All notifications enabled")
        end
    end, desc="Disables all notifications"},
```
but the problem is that the notification while this is enabled are just vanished

**Comment by mehalter** [comment]
Thanks for looking into it. I'll investigate if there is a good possibility for this in core AstroNvim next week!

**Comment by mehalter** [comment]
@DarkCat5501 I just made a push to Nightly that improves `<leader>uN` to toggle all notifications while maintaining the ability to view the notification history with `<leader>fn`
