### ISSUE TITLE
Feat:  shortcuts to irb

### ISSUE THREAD

**Issue by 0123takaokeita** [AstroNvim/AstroNvim#2005]
### Is your feature related to a problem?

Since the shortcuts are Python and Node, why not add a Ruby interactive shell in the same way? 

### Describe the new feature

I want to be able to use irb in the same world as python and node.

```lua
-- Terminal
if is_available "toggleterm.nvim" then
  maps.n["<leader>t"] = sections.t
  if vim.fn.executable "lazygit" == 1 then
    maps.n["<leader>g"] = sections.g
    maps.n["<leader>gg"] = { function() utils.toggle_term_cmd "lazygit" end, desc = "ToggleTerm lazygit" }
    maps.n["<leader>tl"] = { function() utils.toggle_term_cmd "lazygit" end, desc = "ToggleTerm lazygit" }
  end
  if vim.fn.executable "node" == 1 then
    maps.n["<leader>tn"] = { function() utils.toggle_term_cmd "node" end, desc = "ToggleTerm node" }
  end
  if vim.fn.executable "ruby" == 1 then
    maps.n["<leader>tr"] = { function() utils.toggle_term_cmd "irb" end, desc = "ToggleTerm irb" }
  end
```

**Comment by mehalter** [comment]
I think python and node are more commonly used among our users. We can't feasibly add mappings out of the box for every type of REPL, but you can definitely add this to your user configuration with the `mappings` table to make AstroNvim fit your needs!

**Comment by 0123takaokeita** [comment]
> I think python and node are more commonly used among our users. We can't feasibly add mappings out of the box for every type of REPL, but you can definitely add this to your user configuration with the `mappings` table to make AstroNvim fit your needs!

I suggested it because it was easier to advertise if irb was set by default when introducing it to someone.

I respect your opinion and will try the user setting for the time being.
