### ISSUE TITLE
can switch our lsp config to folke/neoconf 

### ISSUE THREAD

**Issue by chaozwn** [AstroNvim/AstroNvim#2007]
### Is your feature related to a problem?

it's easy way to config our lsp config by json. but lt's hard to config. do we should support config global or local lsp config use neoconf.

### Describe the new feature

core module add neoconf

**Comment by chaozwn** [comment]
i hate to change each project lsp config by modify user/lsp/**.lua

**Comment by chaozwn** [comment]
below configuration is too basic.
https://github.com/AstroNvim/astrocommunity/tree/main/lua/astrocommunity/project/neoconf-nvim

**Comment by mehalter** [comment]
> below configuration is too basic.
> https://github.com/AstroNvim/astrocommunity/tree/main/lua/astrocommunity/project/neoconf-nvim

Why is this too basic?

**Comment by chaozwn** [comment]
> > below configuration is too basic.
> > https://github.com/AstroNvim/astrocommunity/tree/main/lua/astrocommunity/project/neoconf-nvim
> 
> Why is this too basic?
I cannot set neoconf separately because it initializes before the lsp server.
![image](https://github.com/AstroNvim/AstroNvim/assets/51357674/e94a4295-2972-4f83-ae51-5d9a60c83d6b)

**Comment by mehalter** [comment]
What do you mean? Neoconf is required to be set up before lspconfig is ever run. That's very important and that's what we are doing.

Also Neoconf does not support putting the `global_settings` in a different location. There are pieces of their codebase that (1) assumes that the string is the file name and not a path and (2) prepends the string with `vim.fn.stdpath("config")`.

**Comment by chaozwn** [comment]
> Hm, I did some testing with the directory stuff and it seems to work alright I think 🤔 I'll put it in there now

that's good. I will refer to your configuration and I'm looking forward to it. By the way, can you add a few key mappings?

**Comment by chaozwn** [comment]
> Hm, I did some testing with the directory stuff and it seems to work alright I think 🤔 I'll put it in there now

for example, 
![image](https://github.com/AstroNvim/AstroNvim/assets/51357674/45262d20-12df-48fd-8220-b98d8255c005)

**Comment by mehalter** [comment]
I will think about if there is a good place to put these. Chances are a very small fraction of the users will be using these features so decluttering the menu might take precedence over adding mappings for these especially when the commands are very short and easy and aren't going to be run all the time ideally if the editor is set up well.

Also just a heads up that the current configuration on nightly does not work

**Comment by chaozwn** [comment]
> I will think about if there is a good place to put these. Chances are a very small fraction of the users will be using these features so decluttering the menu might take precedence over adding mappings for these especially when the commands are very short and easy and aren't going to be run all the time ideally if the editor is set up well.
> 
> Also just a heads up that the current configuration on nightly does not work

yes, Indeed, making the configuration above is very simple, and you can also choose not to configure it and let us do it ourselves. However, switching configurations can be very common when writing Vue 🐶.

**Comment by mehalter** [comment]
I have also verified that the live setting reloading works as well without having to restart. It is all working perfectly :)

**Comment by chaozwn** [comment]
> I have also verified that the live setting reloading works as well without having to restart. It is all working perfectly :)
try this, i can't disabled lua_ls server.
```json
{
  "neoconf": {
    "plugins": {
      "lua_ls": {
        "enabled": false
      },
      "tsserver": {
        "enabled": false
      }
    }
  },
  "lspconfig": {
    "cssls": {
      "css.lint.unknownAtRules": "ignore",
      "less.lint.unknownAtRules": "ignore",
      "scss.lint.unknownAtRules": "ignore"
    },
    "tsserver": {
      "javascript.updateImportsOnFileMove.enabled": "always",
      "javascript.inlayHints.includeInlayEnumMemberValueHints": true,
      "javascript.inlayHints.includeInlayFunctionLikeReturnTypeHints": true,
      "javascript.inlayHints.includeInlayFunctionParameterTypeHints": true,
      "javascript.inlayHints.includeInlayParameterNameHints": "all",
      "javascript.inlayHints.includeInlayParameterNameHintsWhenArgumentMatchesName": true,
      "javascript.inlayHints.includeInlayPropertyDeclarationTypeHints": true,
      "javascript.inlayHints.includeInlayVariableTypeHints": true,
      "typescript.updateImportsOnFileMove.enabled": "always",
      "typescript.inlayHints.includeInlayEnumMemberValueHints": true,
      "typescript.inlayHints.includeInlayFunctionLikeReturnTypeHints": true,
      "typescript.inlayHints.includeInlayFunctionParameterTypeHints": true,
      "typescript.inlayHints.includeInlayParameterNameHints": "all",
      "typescript.inlayHints.includeInlayParameterNameHintsWhenArgumentMatchesName": true,
      "typescript.inlayHints.includeInlayPropertyDeclarationTypeHints": true,
      "typescript.inlayHints.includeInlayVariableTypeHints": true
    },
    "pylsp": {
      "pylsp.plugins.rope_autoimport.enabled": true,
      "pylsp.plugins.rope_autoimport.memory": true,
      "pylsp.plugins.rope_completion.enabled": true,
      "pylsp.plugins.rope_completion.eager": true
    },
    "pyright": {
      "python.pythonPath": "~/miniconda3/envs/python38/bin/python",
      "python.analysis.autoSearchPaths": true,
      "python.analysis.diagnosticMode": "workspace",
      "python.analysis.useLibraryCodeForTypes": true,
      "python.analysis.typeCheckingMode": "basic"
    },
    "tailwindcss": {
      "tailwindCSS.classAttributes": [
        "class",
        "className",
        "ngClass",
        "classList",
        "cva"
      ],
      "tailwindCSS.emmetCompletions": true,
      "tailwindCSS.lint.cssConflict": "warning",
      "tailwindCSS.lint.invalidApply": "error",
      "tailwindCSS.lint.invalidConfigPath": "error",
      "tailwindCSS.lint.invalidScreen": "error",
      "tailwindCSS.lint.invalidTailwindDirective": "error",
      "tailwindCSS.lint.invalidVariant": "error",
      "tailwindCSS.lint.recommendedVariantOrder": "warning",
      "tailwindCSS.validate": true
    }
  }
}
```

**Comment by mehalter** [comment]
Here is a demo @chaozwn : https://www.youtube.com/watch?v=N_E5bSC_3sQ


Sorry, but I don't have the capacity to debug your neoconf configuration for you, but I have validated that it is working at least. Good luck! There are much more people on the discord might have more time than me.

**Comment by chaozwn** [comment]
> Here is a demo @chaozwn : https://www.youtube.com/watch?v=N_E5bSC_3sQ
> 
> Sorry, but I don't have the capacity to debug your neoconf configuration for you, but I have validated that it is working at least. Good luck! There are much more people on the discord might have more time than me.

thanks a lot.

**Comment by chaozwn** [comment]
> Here is a demo @chaozwn : https://www.youtube.com/watch?v=N_E5bSC_3sQ
> 
> Sorry, but I don't have the capacity to debug your neoconf configuration for you, but I have validated that it is working at least. Good luck! There are much more people on the discord might have more time than me.

you're right. i found it can read coc-settings.json. so it really works well.
