### ISSUE TITLE
User mapping can completely override the mapping configuration of Astronvim?

### ISSUE THREAD

**Issue by chaozwn** [AstroNvim/AstroNvim#2016]
### Is your feature related to a problem?

my user mapping:
```lua
maps.n["<leader>w"] = { "<cmd><cr>", desc = "󱂬 Window" }
```
astronvim mapping:
```lua
maps.n["<leader>w"] = { "<cmd>w<cr>", desc = "Save" }
```
but which key show, i think `<leader>w` should be blue color.
![image](https://github.com/AstroNvim/AstroNvim/assets/51357674/ef3b6c77-d883-4158-b544-0d3a1abc8b42)

### Describe the new feature

User mapping can completely override the mapping configuration of Astronvim.
if user mapping only has desc, it can overwrite astronvim default mapping.

**Comment by mehalter** [comment]
It will become blue in which-key if it is a menu. If you don't have anything nested under it then which-key will not render it blue. Here is a basic `init.lua` file that shows an example of overriding a default mapping to a menu and then adding a mapping underneath it:

```lua
return {
  mappings = function(maps)
    local win_prefix = "<leader>w"
    maps.n[win_prefix] = { desc = "󱂬 Window" }
    maps.n[win_prefix .. "a"] = { "<cmd><cr>", desc = "EXAMPLE NESTED" }

    return maps
  end,
}
```

**Comment by chaozwn** [comment]
> It will become blue in which-key if it is a menu. If you don't have anything nested under it then which-key will not render it blue. Here is a basic `init.lua` file that shows an example of overriding a default mapping to a menu and then adding a mapping underneath it:
> 
> ```lua
> return {
>   mappings = function(maps)
>     local win_prefix = "<leader>w"
>     maps.n[win_prefix] = { desc = "󱂬 Window" }
>     maps.n[win_prefix .. "a"] = { "<cmd><cr>", desc = "EXAMPLE NESTED" }
> 
>     return maps
>   end,
> }
> ```

yes, i want to make `<leader>w` as a menu. but i can't delete `"<cmd>w<cr>"`, because new mapping can't remove this part.

**Comment by chaozwn** [comment]
I think that if I set it as a menu in user mapping, it should be displayed in blue, instead of not completely overriding the default configuration.

**Comment by mehalter** [comment]
If you have further questions regarding help configuring mappings and understanding how mappings work in Neovim and configuration is done in AstroNvim, the documentation does a good job at explaining methods of overriding (both table merging and full function overriding for more control <- this is what you want): https://astronvim.com/Configuration/override_formats#override-function

And then I cannot stress enough that the discord community is very helpful and engaging and is great to help you debug and build your configuration :)
