### ISSUE TITLE
Plugins loaded during the AstroFile event take significantly longer to load

### ISSUE THREAD

**Issue by Subjective** [AstroNvim/AstroNvim#2019]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.4

### Terminal/GUI

Kitty

### AstroNvim Health

```
AstroNvim ~
- AstroNvim Version: nightly (v3.25.0-4-gf1007af)
- Neovim Version: v0.10.0-dev-546+g3bf887f6e
- WARNING Neovim nightly is not officially supported and may have breaking changes
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)
```

### Describe the bug

After commit c0090e2, plugins that lazy load during the AstroFile event take significantly longer to load (from ~60 ms to >300 ms in my personal config). This is only an issue with recent versions of Neovim nightly that support the vim.system command, but I thought it might still be worth reporting.

### Steps to Reproduce

1. Use a recent version of Neovim nightly with the vim.system command
2. Open or create any file in neovim from the terminal: `nvim test.lua`

### Expected behavior

I would expect AstroNvim to load as quickly as before commit c0090e2.

### Screenshots

![Screen Recording 2023-06-21 at 12 56 38 PM](https://github.com/AstroNvim/AstroNvim/assets/56745535/2b6846db-1f63-4db2-91ad-04cd51d83088)

**Comment by mehalter** [comment]
Ah I am actually currently investigating this as well. Been looking at it all day. Not sure why it's taking so long

**Comment by mehalter** [comment]
I went ahead and reverted this behavior and am just going to have our stuff use `vim.fn.system` for now until `vim.system` gets improved a bit

**Comment by mehalter** [comment]
Thanks for reporting this. Let me know if you have any other issues with the current AstroNvim nightly @Subjective ! I am planning on merging it in tomorrow at some point

**Comment by Subjective** [comment]
Alright, thanks!

**Comment by mehalter** [comment]
@Subjective I am re-investigating `vim.system` to see if it has improved since it's release. It's highly recommended in the Neovim documentation to always prefer `vim.system` and other plugins are moving to it and showing high performance gains so I want to see if you are still getting really slow performance.

Could you try checking out the `vim_system` branch on AstroCore and see if you are still seeing this crazy slowdown on stable neovim 0.10.X?

You should be able to just add the following spec to your plugins and then run `:Lazy update`:

```lua
{ "AstroNvim/astrocore", branch = "vim_system", version = false }
```

**Comment by mehalter** [comment]
Hm, actually benchmarking shows a significant increase in execution time for `vim.system` 🤔 

`test.lua`:

```lua
local i = 0
local start_time = os.clock()
while i < 1000 do
  vim.system({ "git", "rev-parse" }, { text = true}):wait()
  i = i + 1
end
vim.print(("vim.system:    %f seconds"):format(os.clock() - start_time))

i = 0
start_time = os.clock()
while i < 1000 do
  vim.fn.system { "git", "rev-parse" }
  i = i + 1
end
vim.print(("vim.fn.system: %f seconds"):format(os.clock() - start_time))
```


```
:luafile test.lua                                                                                                 
vim.system:    0.728998 seconds                                                                                   
vim.fn.system: 0.531781 seconds  
```

**Comment by mehalter** [comment]
Welp the above benchmarks show it's just not a good use case for where we use `vim.fn.system` which is specifically synchronous command execution. I'll go ahead and delete the branch and ignore that new API
