### ISSUE TITLE
neotree delete a folder

### ISSUE THREAD

**Issue by ilaipi** [AstroNvim/AstroNvim#2025]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

windows11

### Terminal/GUI

windows terminal

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.23.1
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `explorer` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

==============================================================================
gitsigns: require("gitsigns.health").check()

- OK git version 2.39.1.windows.1

==============================================================================
lazy: require("lazy.health").check()

lazy.nvim ~
- OK Git installed
- OK no existing packages found by other package managers
- OK packer_compiled.lua not found

==============================================================================
mason: require("mason.health").check()

mason.nvim ~
- WARNING mason.nvim version v1.3.0
  - ADVICE:
    - The latest version of mason.nvim is: v1.4.0
- OK PATH: prepend
- OK Providers: 
  mason.providers.registry-api
  mason.providers.client
- OK neovim version >= 0.7.0

mason.nvim [Registries] ~
- OK Registry `github.com/mason-org/mason-registry version: 2023-06-19-hurt-barbel` is installed.

mason.nvim [Core utils] ~
- OK unzip: `UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send`
- WARNING wget: not available
  - ADVICE:
    - spawn: wget failed with exit code - and signal -. wget is not executable
- OK curl: `curl 7.87.0 (x86_64-w64-mingw32) libcurl/7.87.0 OpenSSL/1.1.1s (Schannel) zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.3 libpsl/0.21.1 (+libidn2/2.3.1) libssh2/1.10.0 nghttp2/1.51.0
`
- OK gzip: `gzip 1.12`
- OK tar: `tar (GNU tar) 1.34`
- ERROR pwsh: not available
  - ADVICE:
    - spawn: pwsh failed with exit code - and signal -. pwsh is not executable
- OK 7z: `7-Zip 22.01 (x64) : Copyright (c) 1999-2022 Igor Pavlov : 2022-07-15
`

mason.nvim [Languages] ~
- WARNING cargo: not available
  - ADVICE:
    - spawn: cargo failed with exit code - and signal -. cargo is not executable
- WARNING Composer: not available
  - ADVICE:
    - spawn: composer.bat failed with exit code - and signal -. composer.bat is not executable
- WARNING PHP: not available
  - ADVICE:
    - spawn: php failed with exit code - and signal -. php is not executable
- WARNING luarocks: not available
  - ADVICE:
    - spawn: luarocks failed with exit code - and signal -. luarocks is not executable
- WARNING Ruby: not available
  - ADVICE:
    - spawn: ruby failed with exit code - and signal -. ruby is not executable
- WARNING RubyGem: not available
  - ADVICE:
    - spawn: gem.cmd failed with exit code - and signal -. gem.cmd is not executable
- OK node: `v18.16.0
`
- WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. julia is not executable
- OK Go: `go version go1.20.4 windows/amd64`
- OK javac: `javac 11.0.16.1
`
- OK java: `openjdk version "11.0.16.1" 2022-08-12 LTS
`
- OK JAVA_HOME: `java version "1.8.0_202"
`
- WARNING python: not available
  - ADVICE:
    - spawn: python failed with exit code 9009 and signal 0. 
- WARNING pip: not available
  - ADVICE:
    - spawn: python failed with exit code 9009 and signal 0. 
- WARNING python venv: not available
  - ADVICE:
    - On Debian/Ubuntu systems, you need to install the python3-venv package using the following command:
      
      apt-get install python3-venv
- OK npm: `9.5.1`

mason.nvim [GitHub] ~
- OK GitHub API rate limit. Used: 21. Remaining: 39. Limit: 60. Reset: 2023/6/23 14:43:58.
  Install and authenticate via gh-cli to increase rate limit.

==============================================================================
null-ls: require("null-ls.health").check()

- no sources registered

==============================================================================
nvim: require("nvim.health").check()

Configuration ~
- OK no issues found

Runtime ~
- OK $VIMRUNTIME: C:\Users\Billy\scoop\apps\neovim\current\share\nvim\runtime

Performance ~
- OK Build type: RelWithDebInfo

Remote Plugins ~
- OK Up to date

terminal ~
- key_backspace (kbs) terminfo entry: `key_backspace=^H`
- key_dc (kdch1) terminfo entry: `key_dc=\E[3~`

==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (0c49d6745b3fc4822ab02e0018770cd6383a779c) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v18.16.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `gcc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: /usr/bin/bash: /s: No such file or directory
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "10.0.22621",
  sysname = "Windows_NT",
  version = "Windows 11 Pro"
} ~

Parser/Features         H L F I J
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

==============================================================================
provider: health#provider#check

- ERROR Failed to run healthcheck for "provider" plugin. Exception:
  function health#check[25]..health#provider#check[2]..<SNR>53_check_python[13]..<SNR>53_check_for_pyenv[12]..<SNR>53_system，第 11 行
  Vim(let):E903: 进程启动失败：no such file or directory："C:\Users\Billy\.pyenv\pyenv-win\bin\pyenv"

==============================================================================
vim.lsp: require("vim.lsp.health").check()

- LSP log level : WARN
- Log path: C:\Users\Billy\AppData\Local\nvim-data\lsp.log
- Log size: 6534 KB

vim.lsp: Active Clients ~
- tsserver (id=1, root_dir=D:/workspace/kelly/novita)
- eslint (id=2, root_dir=D:/workspace/kelly/novita)
- tsserver (id=3, root_dir=D:/workspace/peigen/dexfilter)
- tsserver (id=4, root_dir=D:/workspace/xiaoguai/ziggly)

==============================================================================
vim.treesitter: require("vim.treesitter.health").check()

- Nvim runtime ABI version: 14
- OK Parser: html       ABI: 13, path: C:\Users\Billy\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\html.so
- OK Parser: javascript ABI: 14, path: C:\Users\Billy\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\javascript.so
- OK Parser: typescript ABI: 14, path: C:\Users\Billy\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\typescript.so
- OK Parser: c          ABI: 13, path: C:\Users\Billy\scoop\apps\neovim\current\lib\nvim\parser\c.dll
- OK Parser: lua        ABI: 14, path: C:\Users\Billy\scoop\apps\neovim\current\lib\nvim\parser\lua.dll
- OK Parser: query      ABI: 14, path: C:\Users\Billy\scoop\apps\neovim\current\lib\nvim\parser\query.dll
- OK Parser: vim        ABI: 14, path: C:\Users\Billy\scoop\apps\neovim\current\lib\nvim\parser\vim.dll
- OK Parser: vimdoc     ABI: 14, path: C:\Users\Billy\scoop\apps\neovim\current\lib\nvim\parser\vimdoc.dll

==============================================================================
which-key: require("which-key.health").check()

WhichKey: checking conflicting keymaps ~
- WARNING conflicting keymap exists for mode **"v"**, lhs: **"<leader>l"**
- rhs: ` `
- WARNING conflicting keymap exists for mode **"v"**, lhs: **"<leader>l"**
- rhs: ` `
- WARNING conflicting keymap exists for mode **"v"**, lhs: **"<leader>l"**
- rhs: ` `
- WARNING conflicting keymap exists for mode **"v"**, lhs: **"<leader>l"**
- rhs: ` `

### Describe the bug

when I delete a dir from neotree, many 'errors' happend, need to wait a long time to restart nvim.

### Steps to Reproduce

1. 'leader e' open the neotree 
2. press d on a dir
3. enter 'y' and press enter

### Expected behavior

normally delete dir

### Screenshots

![image](https://github.com/AstroNvim/AstroNvim/assets/1689135/56cb5d84-209b-4ce6-b8cb-39936d58ca63)

**Comment by mehalter** [comment]
This should be reported upstream to neo-tree since we do not implement this functionality
