### ISSUE TITLE
LSP diagnostics on tsconfig.json files [similar to VSCode]

### ISSUE THREAD

**Issue by serranomorante** [AstroNvim/AstroNvim#2029]
### Is your feature related to a problem?

There's 1 LSP diagnostic (error hint) that VSCode is showing me but Neovim doesn't.

When I open `tests/tsconfig.json` from [this project](https://github.com/serranomorante/postman-quicktype), VSCode successfully shows me an error about my `tsconfig.json`. VSCode tells me that the property `composite: true` is missing and should be added. Neovim is not showing anything.

I know AstroNvim is going to use [SchemaStore.nvim](https://github.com/b0o/SchemaStore.nvim) whenever I add a `jsonls` server. That's why when I'm in the `tsconfig.json` file and press `shift+K`... I can actually see hints... descriptions of what each property from that file does. But there's no error diagnostics like the one VSCode shows.

This is very important because if I weren't using VSCode, how was I supposed to know about that missing property in my typescript config?

### Describe the new feature

Just being able to have typescript validation on `tsconfig.json` files so I know I'm not missing anything important.

### Additional context

To replicate the issue you'll need to open [this project](https://github.com/serranomorante/postman-quicktype) and more especifically this file: `tests/tsconfig.json` on both editors: Neovim (with AstroNvim) and VSCode. And see the difference.

Btw, please wait for a little bit in VSCode until the error hint appears.

**Comment by mehalter** [comment]
This is sadly a limitation of `jsonls` and the schemas that are in schema store. Sadly this is outside of the code we have and what we can fix. Please drop a comment here if you find a solution with some plugin or language server

**Comment by serranomorante** [comment]
> This is sadly a limitation of `jsonls` and the schemas that are in schema store. Sadly this is outside of the code we have and what we can fix. Please drop a comment here if you find a solution with some plugin or language server

Thank you so much for your response!!
