### ISSUE TITLE
treesitter keymaps conflict with nvim diff mappings

### ISSUE THREAD

**Issue by dpriedel** [AstroNvim/AstroNvim#2040]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Manjaro Linux

### Terminal/GUI

tilix

### AstroNvim Health

>
 astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: nightly (v3.27.1-2-ge702619)
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)
<

### Describe the bug

nvim -d <file a> <file b> uses ']c' and '[c' to move from diff to diff.

These keymaps have been taken over by the treesitter configuration move to next class start and next class end

### Steps to Reproduce

diff 2 files, for example:

nvim -d  user/init.lua user_example/init.lua

then type ']c' to go to the first diff (there are several in my files)

nothing happens since there are no class definitions in the files

### Expected behavior

I expect the cursor to move to the first line containing a diff

### Additional Context

This started recently.

**Comment by mehalter** [comment]
Thanks for reporting! I removed the conflicting mappings in v3.28.3 :)
