### ISSUE TITLE
expandtab = true even though the file uses tabs as indentation and user settings polish function also has expandtab = false

### ISSUE THREAD

**Issue by denppa** [AstroNvim/AstroNvim#2043]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

archlinux

### Terminal/GUI

kitty

### AstroNvim Health

vanilla astronvim that just got cloned from the repo

### Describe the bug

If the file uses tabs as its indentation, astronvim should set expandtab = false, or if `vim.opt_gloabl.expandtab = false` is set inside the `user/init.lua file`'s polish function, astronvim should not override this setting on a per file basis.

Though I would prefer if the auto tab expanding function of astronvim is working properly so I don't have to be forced to use tabs globally.

### Steps to Reproduce

1. Open a code file
2. Add an indent, indent is made using spaces
3. Also checked :set expandtab?, and it returns expandtabs

### Expected behavior

With this file content as the example, astronvim should set expandtab = false:
```python
msg = 'ok'
def main():
	print(msg)

if __name__ == '__main__':
	main()
```

### Additional Context
python lsp is pyright

**Comment by mehalter** [comment]
We have the plugin [guess-indent.nvim](https://github.com/NMAC427/guess-indent.nvim) which automatically detects and sets the indentation based on the file you open. You can disable this if you want to just have static settings.

**Comment by mehalter** [comment]
I also would recommend using the `options` table to set `expandtab` rather than putting it in your `polish` function if you do go the route of disabling the indentation detection.

**Comment by denppa** [comment]
Thank you so much for the quick response, I just found out about `user/options.lua`, I will shift the tab settings to over there.

Regarding the `guess-indent` plugin, is there a way for me to configure it? I have no idea why it is failing even for the simplest file I have pasted above.

**Comment by mehalter** [comment]
I found the root cause. This is because in the runtime of Neovim it automatically sets the indentation to `autoindent`: https://github.com/neovim/neovim/blob/master/runtime/indent/python.vim#L15

I'm not sure why this is there. You could probably make an `autocmd` to run on the python filetype to revert this.

**Comment by mehalter** [comment]
It could also be interactions coming from treesitter overriding indentation settings as well as a possibility

**Comment by denppa** [comment]
Okay, so I have to consider treesitter settings the indentation and also vim's builtin behavior.

For starters, what is the command that I have to run in order to disable neovim's built in `autoindent` function?

**Comment by denppa** [comment]
Author, with the tab indentation options set, opening an empty file and checking `:set expandtab?` yields `noexpandtab`, but as soon as I open the simple python file, `:set expandtab?` yields `expandtab`, even though tree-sitter interactions could be doing this, I am not sure if tree-sitter directly interfaces with the neovim apis.

**Comment by mehalter** [comment]
One useful command you can use is this: `:verbose set expandtab?`

This will basically tell you the last thing that set a given option. It looks like it's coming specification from: https://github.com/neovim/neovim/blob/master/runtime/ftplugin/python.vim#L119

I think the easiest way to get around this is to just set up an `autocmd` to re-run guess indent once a python file is loaded. You could put something like this in your `polish` function:

```lua
vim.api.nvim_create_autocmd("FileType", {
  desc = "python indentation detection",
  group = vim.api.nvim_create_augroup("python_autoindent", { clear = true }),
  pattern = "python",
  callback = function()
    vim.cmd.lua { args = { "require('guess-indent').set_from_buffer('auto_cmd')" }, mods = { silent = true } }
  end,
})
```

**Comment by denppa** [comment]
I will put that snippet in a minute for now, the other way, is to perhaps disable tree-sitter's attempt at indenting, I found this reddit post: https://www.reddit.com/r/neovim/comments/105cva2/turning_off_treesitter_indent_doesnt_seem_to_work/, but am not sure how to implement this in user settings.

**Comment by mehalter** [comment]
The indentation settings I actually confirmed are not coming from treesitter. They are originating from the runtime built in python filetype plugin. So you will need to wrangle in that core Neovim runtime vim script in some way. I tried some basic stuff and it doesn't seem to go well. The best solution I have found so far is the solution I shared. If you want to go through and continue debugging I would recommend checking out the command I shared previously as well as discussing on discord since there are many more people there who can help rather than just me :)

**Comment by denppa** [comment]
I reread your comment and saw my mistake. It seems like the autocmd is the best way to go. I would want to know why the people at neovim hard coded space indentation for python. Tree-sitter turned out to be innocent I guess.

I would like to thank you once again for the help and creating such an amazing terminal code editing experience.
