### ISSUE TITLE
Alpha Autocmd overrides the user set footer settings

### ISSUE THREAD

**Issue by cigh033** [AstroNvim/AstroNvim#2044]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Windows 11 / Arch

### Terminal/GUI

Windows Terminal / alacritty

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: unknown
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `explorer` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

The Autocommand (or to be more specific the "pcall(vim.cmd.AlphaRedraw)" at the end of lua/plugins/configs/alpha.lua) within astronvim alpha configuration disallows me from setting Alpha footer options myself (or overrides them with the redraw

### Steps to Reproduce

put this into your user config:

```lua
  {
    "goolord/alpha-nvim",
    opts = function(_, opts)
      opts.section.header.opts.hl = "DashboardFooter"
      opts.section.footer.val = { "YOLO" }
      return opts
    end,
  },
```

### Expected behavior

The Override from the user should work and instead of the "loaded plugins ..." string there should be "test" on your alpha dashboard footer

**Comment by mehalter** [comment]
You will want to override the `setup` function to remove this:

```lua
{
  "goolord/alpha-nvim",
  opts = function(_, opts)
    opts.section.header.opts.hl = "DashboardFooter"
    opts.section.footer.val = { "YOLO" }
    return opts
  end,
  config = function(_, opts) require("alpha").setup(opts.config) end,
},
```
