### ISSUE TITLE
Closing a modified buffer w/o saving disables winbar

### ISSUE THREAD

**Issue by Subjective** [AstroNvim/AstroNvim#2049]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.4

### Terminal/GUI

Kitty

### AstroNvim Health

```
AstroNvim ~
- AstroNvim Version: nightly (v3.29.1)
- Neovim Version: v0.10.0-dev-585+g2e055e49a
- WARNING Neovim nightly is not officially supported and may have breaking changes
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)
```

### Describe the bug

Closing a buffer that has been modified disables the winbar of the empty buffer created in its place. Furthermore, the user is able to close that empty buffer without confirmation, even if it has been modified. Very minor issue introduced by c741f15f and 877c2193.

### Steps to Reproduce

1. Create an empty buffer w/ `<leader>n`
2. Modify it
3. Close it with `<leader>c`
4. Hit `n` to ignore changes
5. The new buffer

### Expected behavior

I would expect the newly created empty buffer to still have a winbar and for there to be a confirmation prompt when attempting to close it after it has already been modified.

### Screenshots

![Screen Recording 2023-06-28 at 3 27 31 AM](https://github.com/AstroNvim/AstroNvim/assets/56745535/0580d4f3-f444-4fc0-9772-498485d47162)

**Comment by mehalter** [comment]
Yeah I've looked into this as well. This seems to be coming from `mini.bufremove`. I will report this upstream and see if they agree that this is a bug. Basically if you close the last real files the buffer that gets created is of `buftype = nofile` which we disable the `winbar` for `nofile` buffers

**Comment by mehalter** [comment]
Opened a PR for this: https://github.com/echasnovski/mini.nvim/pull/394

Will report back when I hear something. Closing this for now since this is a bug upstream and we can track the other PR

**Comment by mehalter** [comment]
My PR got merged in and this change is available on AstroNvim Nightly. I will tag a release later today to include this!

**Comment by Subjective** [comment]
Wow, that was fast! Thanks for all your hard work maintaining astronvnim and for the neovim community in general!
