### ISSUE TITLE
Neogit tab is broken on nightly

### ISSUE THREAD

**Issue by troglotit** [AstroNvim/AstroNvim#2051]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Windows 10 WSL 2 Ubuntu 22.04 LTS

### Terminal/GUI

Windows Terminal

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: nightly (v3.26.0)
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Calling `:Neogit`  breaks which then becomes unstable (sometimes usable, sometimes not). 

I've bisected to this commit. Previous commit hash works OK.
https://github.com/AstroNvim/AstroNvim/commit/52fcb15cb6e317699bb2772178f9ecd0ee8185be 

### Steps to Reproduce

1. Open nvim with `neogit` installed. Reproduces with community one too https://github.com/AstroNvim/astrocommunity/tree/main/lua/astrocommunity/git/neogit
2. Call `:Neogit`

### Expected behavior

`:Neogit` works

### Screenshots

![image](https://github.com/AstroNvim/AstroNvim/assets/10955264/0a15de37-d0a8-4959-9f50-e5b0a31d9fa7)

### Additional Context

Sorry for checking "I'm on stable branch" checkmark - don't know how to submit bugs in nightly

**Comment by mehalter** [comment]
Thanks for reporting! I have resolved this in v3.29.2
