### ISSUE TITLE
[LSP] Server does not support semantic tokens

### ISSUE THREAD

**Issue by chaozwn** [AstroNvim/AstroNvim#2054]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macos 13.3.1

### Terminal/GUI

alacritty

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: v3.29.2
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

[LSP] Server does not support semantic tokens
![image](https://github.com/AstroNvim/AstroNvim/assets/51357674/3e1f08aa-9333-4aaf-9254-e2baf786fbaf)

### Steps to Reproduce

1. community import `{ import = "astrocommunity.pack.vue" }`
2. open .vue file.

### Expected behavior

with out warning

**Comment by chaozwn** [comment]
may be link:https://github.com/AstroNvim/AstroNvim/commit/811afb208e04017a2bbd53271ca33971aeacf64c

**Comment by mehalter** [comment]
This is out of my control. The language server needs to appropriately (1) implement the LSP specification and (2) correctly report their capabilities. It looks like `volar` does not do this. Or this could be an upstream issue in Neovim for not supporting their lsp semantic token implementation. Sorry!

**Comment by mehalter** [comment]
Also just a heads up that I put a little improvement that will circumvent this error on opening a file, but the issue still does exist for volar not properly implementing the LSP specification. But this is at least improved a bit in v3.29.3+
