### ISSUE TITLE
Cannot make copilot.lua work alongside copilot-cmp.lua

### ISSUE THREAD

**Issue by datacubeR** [AstroNvim/AstroNvim#2059]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

PopOS  22.04 LTS

### Terminal/GUI

Gnome

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.27.1
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- WARNING `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

==============================================================================
gitsigns: require("gitsigns.health").check()

- OK git version 2.34.1

==============================================================================
lazy: require("lazy.health").check()

lazy.nvim ~
- OK Git installed
- OK no existing packages found by other package managers
- OK packer_compiled.lua not found

==============================================================================
mason: require("mason.health").check()

mason.nvim ~
- WARNING mason.nvim version v1.4.0
  - ADVICE:
    - The latest version of mason.nvim is: v1.5.0
- OK PATH: prepend
- OK Providers: 
  mason.providers.registry-api
  mason.providers.client
- OK neovim version >= 0.7.0

mason.nvim [Registries] ~
- OK Registry `github.com/mason-org/mason-registry version: 2023-06-28-afraid-image` is installed.

mason.nvim [Core utils] ~
- OK unzip: `UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.`
- OK wget: `GNU Wget 1.21.2 built on linux-gnu.`
- OK curl: `curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.14`
- OK gzip: `gzip 1.10`
- OK tar: `tar (GNU tar) 1.34`
- OK bash: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
- OK sh: `Ok`

mason.nvim [Languages] ~
- WARNING Go: not available
  - ADVICE:
    - spawn: go failed with exit code - and signal -. go is not executable
- WARNING cargo: not available
  - ADVICE:
    - spawn: cargo failed with exit code - and signal -. cargo is not executable
- WARNING luarocks: not available
  - ADVICE:
    - spawn: luarocks failed with exit code - and signal -. luarocks is not executable
- WARNING Composer: not available
  - ADVICE:
    - spawn: composer failed with exit code - and signal -. composer is not executable
- WARNING PHP: not available
  - ADVICE:
    - spawn: php failed with exit code - and signal -. php is not executable
- WARNING javac: not available
  - ADVICE:
    - spawn: javac failed with exit code - and signal -. javac is not executable
- WARNING java: not available
  - ADVICE:
    - spawn: java failed with exit code - and signal -. java is not executable
- WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. julia is not executable
- OK python: `Python 3.9.16`
- OK node: `v18.13.0`
- OK Ruby: `ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux]`
- OK RubyGem: `3.1.6`
- OK pip: `pip 23.0.1 from /home/datacuber/miniconda3/lib/python3.9/site-packages/pip (python 3.9)`
- OK python venv: `Ok`
- OK npm: `8.19.3`

mason.nvim [GitHub] ~
- OK GitHub API rate limit. Used: 0. Remaining: 60. Limit: 60. Reset: Wed 28 Jun 2023 06:11:34 PM -04.
  Install and authenticate via gh-cli to increase rate limit.

==============================================================================
neoconf: require("neoconf.health").check()

neoconf.nvim ~
- OK **treesitter-nvim** is installed
- WARNING **TreeSitter jsonc** parser is not installed. Highlighting of jsonc files might be broken
- OK **neodev.nvim** is installed
- OK **lspconfig** is installed
- WARNING **lspconfig jsonls** is not installed? You won't get any auto completion in your settings files
- OK **lspconfig lua_ls** is installed

==============================================================================
null-ls: require("null-ls.health").check()

- OK isort: the command "isort" is executable.
- OK black: the command "black" is executable.

==============================================================================
nvim: require("nvim.health").check()

Configuration ~
- OK no issues found

Runtime ~
- OK $VIMRUNTIME: /home/datacuber/.local/bin/nvim-linux64/share/nvim/runtime

Performance ~
- OK Build type: Release

Remote Plugins ~
- OK Up to date

terminal ~
- key_backspace (kbs) terminfo entry: `key_backspace=^H`
- key_dc (kdch1) terminfo entry: `key_dc=\E[3~`
- $VTE_VERSION="6800"
- $COLORTERM="truecolor"

==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (0c49d6745b3fc4822ab02e0018770cd6383a779c) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v18.13.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.2.6-76060206-generic",
  sysname = "Linux",
  version = "#202303130630~1685473338~22.04~995127e SMP PREEMPT_DYNAMIC Tue M"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

==============================================================================
provider: health#provider#check

Clipboard (optional) ~
- OK Clipboard tool found: xclip

Python 3 provider (optional) ~
- `g:python3_host_prog` is not set.  Searching for python3 in the environment.
- Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
- Executable: /home/datacuber/miniconda3/bin/python3
- Other python executable: /usr/bin/python3
- Other python executable: /bin/python3
- Python version: 3.9.16
- pynvim version: 0.4.3
- OK Latest pynvim is installed.

Python virtualenv ~
- OK no $VIRTUAL_ENV

Ruby provider (optional) ~
- Ruby: ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux]
- WARNING `neovim-ruby-host` not found.
  - ADVICE:
    - Run `gem install neovim` to ensure the neovim RubyGem is installed.
    - Run `gem environment` to ensure the gem bin directory is in $PATH.
    - If you are using rvm/rbenv/chruby, try "rehashing".
    - See :help |g:ruby_host_prog| for non-standard gem installations.
    - You may disable this provider (and warning) by adding `let g:loaded_ruby_provider = 0` to your init.vim

Node.js provider (optional) ~
- Node.js: v18.13.0
- Nvim node.js host: /home/datacuber/miniconda3/lib/node_modules/neovim/bin/cli.js
- OK Latest "neovim" npm/yarn/pnpm package is installed: 4.10.1

Perl provider (optional) ~
- WARNING "Neovim::Ext" cpan module is not installed
  - ADVICE:
    - See :help |provider-perl| for more information.
    - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

==============================================================================
targets: health#targets#check

- OK No conflicting mappings found

==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.3.1

===== Installed extensions ===== ~

Telescope Extension: `aerial` ~
- No healthcheck provided

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured

Telescope Extension: `notify` ~
- No healthcheck provided

==============================================================================
vim.lsp: require("vim.lsp.health").check()

- LSP log level : WARN
- Log path: /home/datacuber/.local/state/nvim/lsp.log
- Log size: 10 KB

vim.lsp: Active Clients ~
- pyright (id=1, root_dir=nil)
- ruff_lsp (id=2, root_dir=nil)
- null-ls (id=3, root_dir=/home/datacuber/.config/nvim/lua/user)
- copilot (id=4, root_dir=/home/datacuber/.config/nvim/lua/user)

==============================================================================
vim.treesitter: require("vim.treesitter.health").check()

- Nvim runtime ABI version: 14
- OK Parser: lua        ABI: 14, path: /home/datacuber/.local/share/nvim/lazy/nvim-treesitter/parser/lua.so
- OK Parser: markdown   ABI: 14, path: /home/datacuber/.local/share/nvim/lazy/nvim-treesitter/parser/markdown.so
- OK Parser: markdown_inline ABI: 14, path: /home/datacuber/.local/share/nvim/lazy/nvim-treesitter/parser/markdown_inline.so
- OK Parser: python     ABI: 14, path: /home/datacuber/.local/share/nvim/lazy/nvim-treesitter/parser/python.so
- OK Parser: toml       ABI: 13, path: /home/datacuber/.local/share/nvim/lazy/nvim-treesitter/parser/toml.so
- OK Parser: c          ABI: 13, path: /home/datacuber/.local/bin/nvim-linux64/lib/nvim/parser/c.so
- OK Parser: lua        ABI: 14, path: /home/datacuber/.local/bin/nvim-linux64/lib/nvim/parser/lua.so
- OK Parser: query      ABI: 14, path: /home/datacuber/.local/bin/nvim-linux64/lib/nvim/parser/query.so
- OK Parser: vim        ABI: 14, path: /home/datacuber/.local/bin/nvim-linux64/lib/nvim/parser/vim.so
- OK Parser: vimdoc     ABI: 14, path: /home/datacuber/.local/bin/nvim-linux64/lib/nvim/parser/vimdoc.so

==============================================================================
which-key: require("which-key.health").check()

WhichKey: checking conflicting keymaps ~
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"ys"**
- rhs: `<Plug>Ysurround`
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"yS"**
- rhs: `<Plug>YSurround`
- WARNING conflicting keymap exists for mode **"v"**, lhs: **"i"**
- rhs: `targets#e('o', 'i', 'i')`
- WARNING conflicting keymap exists for mode **"v"**, lhs: **"a"**
- rhs: `targets#e('o', 'a', 'a')`
- WARNING conflicting keymap exists for mode **"v"**, lhs: **"<leader>l"**
- rhs: ` `
- WARNING conflicting keymap exists for mode **"o"**, lhs: **"i"**
- rhs: `targets#e('o', 'i', 'i')`
- WARNING conflicting keymap exists for mode **"o"**, lhs: **"a"**
- rhs: `targets#e('o', 'a', 'a')`

### Describe the bug

Not have any on instructions on how to setup copilot.lua and copilot-cmp.lua in Astronvim. 
I have tried instructions detailed in here: 

https://github.com/zbirenbaum/copilot-cmp

And also suggested configurations in LunarVim repository found here: 

```lua
table.insert(lvim.plugins, {
  "zbirenbaum/copilot-cmp",
  event = "InsertEnter",
  dependencies = { "zbirenbaum/copilot.lua" },
  config = function()
    vim.defer_fn(function()
      require("copilot").setup() -- https://github.com/zbirenbaum/copilot.lua/blob/master/README.md#setup-and-configuration
      require("copilot_cmp").setup() -- https://github.com/zbirenbaum/copilot-cmp/blob/master/README.md#configuration
    end, 100)
  end,
})
```

When adding those configs into my lua files it just not triggering any suggestions into cmp.

### Steps to Reproduce

Add configs into `user.lua` using the AstroNvim pre-configuration repo. 

### Expected behavior

Show suggestions showing the are coming from Copilot. Only LSP configs are shown. 

### Additional Context

When trying it into LunarVim their suggested config works as a breeze. Also, `copilot.lua` works as expected when working alone.

**Comment by mehalter** [comment]
Looking at the docs it looks like it should be something closer to this:

```lua
{
  "hrsh7th/nvim-cmp",
  dependencies = {
    "zbirenbaum/copilot-cmp",
    name = "copilot_cmp",
    dependencies = { "zbirenbaum/copilot.lua", opts = {} },
    opts = {},
  },
  opts = function(_, opts) table.insert(opts.sources, { name = "copilot" }) end,
},
```

I haven't tested this so there may be some more debugging necessary to get this working. If you have more questions then the discord is probably the best place to ask since there are more people there than just me on this github repository to help you debug your user configuration. Sorry I'm not much more help! If you find a good configuration it would be super helpful to the community to contribute it to [AstroCommunity](https://github.com/AstroNvim/astrocommunity) as a plugin installable through a single line :)
