### ISSUE TITLE
Unable to create fallbackFlags for clangd lsp server

### ISSUE THREAD

**Issue by throwaway69420-69420** [AstroNvim/AstroNvim#2060]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Linux 6.3.9-zen1-1-zen

### Terminal/GUI

kitty

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.28.3
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

I am unable to find the settings for configuring the fallback flags of clangd lsp server for my c code

I have found this which shows how to do it in neovim (last code line): https://stackoverflow.com/questions/76547479/how-to-get-lsp-to-work-in-neovim-for-cclangd-and-python

I want to use `-std=c89` for myself

### Steps to Reproduce

my `lsp/config/clangd.lua`:

```lua
return {
  capabilities = { offsetEncoding = "utf-8" },
  fallbackFlags = { "-std=c89" },
  settings = {
    ["fallbackFlags"] = { "-std=c89" },
  },
}
```

### Expected behavior

the following c code should not have a red warning on line 7 (the one with `gets(text);`)

```c
#include <stdio.h>

int main() {
  char text[1000];
  char word[100];

  gets(text); // line 7

  for (int i = 0; text[i] != '\0'; i++) {
    for (int j = i + 1; text[j] != " "; j++) {
    }

    // substring from i to j of the string text
  }
}
```

line 7 has the following red warning/error: `clang: Call to undeclared function 'gets'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]`

**Comment by mehalter** [comment]
I'm not sure how to configure `clangd` in such detail. I think the standard way to do this is actually to add `-std=c89` as a line in your `compile_flags.txt` file in the project root. There might be some people on the Discord server who have done this and can help out.

Sorry I'm not much help in this case!
