### ISSUE TITLE
Add `queries` to .gitignore

### ISSUE THREAD

**Issue by fynnfluegge** [AstroNvim/AstroNvim#2061]
### Is your feature related to a problem?

I am using a local tree-sitter parser for specific filetypes with my own highlights.scm located in the default path `nvim/queries/<FILE_TYPE>/`. Git is marking these files as untracked, which is a bit annoying. Would be great if the queries path could be added to `.gitignore`.

### Describe the new feature

Add queries directory to `.gitignore` to let users create their own tree-sitter resources without getting bothered by untracked files.

**Comment by mehalter** [comment]
Thanks for this suggestion. I added this to nightly and will get this merged sometime today.
