### ISSUE TITLE
Neo-tree support undo modifications and trash instead of delete

### ISSUE THREAD

**Issue by chaozwn** [AstroNvim/AstroNvim#2072]
### Is your feature related to a problem?

1. Adding support for trash instead of rm would be awesome! Nvim-Tree does this with the `D` shortcut.
2. I think that since there is an option to perform some modifications in the filesystem source like: renaming,moving,deleting

### Describe the new feature

1. support undo modifications
2. trash instead of delete

**Comment by chaozwn** [comment]
link: 
1. https://github.com/nvim-neo-tree/neo-tree.nvim/issues/202
2. https://github.com/nvim-neo-tree/neo-tree.nvim/pull/473
3. https://github.com/nvim-neo-tree/neo-tree.nvim/issues/860

**Comment by mehalter** [comment]
Thanks for the heads up, I'm glad this is being worked on. Thanks for linking to the relevant issues. I'll go ahead and close this here since it's unrelated to AstroNvim and will be available once neo-tree adds this
