### ISSUE TITLE
telescope live grep is not working

### ISSUE THREAD

**Issue by memocusss** [AstroNvim/AstroNvim#2079]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

windows 10

### Terminal/GUI

neovide

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.30.2
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `explorer` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- WARNING `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

==============================================================================
lazy: require("lazy.health").check()

lazy.nvim ~
- OK Git installed
- OK no existing packages found by other package managers
- OK packer_compiled.lua not found

==============================================================================
nvim: require("nvim.health").check()

Configuration ~
- OK no issues found

Runtime ~
- OK $VIMRUNTIME: C:\Users\celem\scoop\apps\neovim\current\share\nvim\runtime

Performance ~
- OK Build type: RelWithDebInfo

Remote Plugins ~
- OK Up to date

terminal ~
- key_backspace (kbs) terminfo entry: `key_backspace=^H`
- key_dc (kdch1) terminfo entry: `key_dc=\E[3~`

==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (0c49d6745b3fc4822ab02e0018770cd6383a779c) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v18.14.2 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `gcc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: gcc (GCC) 11.2.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "10.0.19045",
  sysname = "Windows_NT",
  version = "Windows 10 Pro"
} ~

Parser/Features         H L F I J
  - python              ✓ ✓ ✓ ✓ ✓
  - sql                 ✓ . . ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

==============================================================================
provider: health#provider#check

Clipboard (optional) ~
- OK Clipboard tool found: win32yank

Python 3 provider (optional) ~
- WARNING No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
- WARNING Could not load Python 3:
  C:\Users\celem\scoop\shims\python3.EXE does not have the "neovim" module.
  python3.10 not found in search path or not executable.
  python3.9 not found in search path or not executable.
  python3.8 not found in search path or not executable.
  python3.7 not found in search path or not executable.
  C:\Users\celem\scoop\apps\python\current\python.EXE does not have the "neovim" module.
  - ADVICE:
    - See :help |provider-python| for more information.
    - You may disable this provider (and warning) by adding `let g:loaded_python3_provider = 0` to your init.vim
- Executable: Not found

Python virtualenv ~
- OK no $VIRTUAL_ENV

Ruby provider (optional) ~
- WARNING `ruby` and `gem` must be in $PATH.
  - ADVICE:
    - Install Ruby and verify that `ruby` and `gem` commands work.

Node.js provider (optional) ~
- Node.js: v18.14.2
- Nvim node.js host: C:\Users\celem\AppData\Roaming\npm\node_modules/neovim/bin/cli.js
- OK Latest "neovim" npm/yarn/pnpm package is installed: 4.10.1

Perl provider (optional) ~
- WARNING No usable perl executable found

==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- ERROR rg: not found. `live-grep` finder will not function without [BurntSushi/ripgrep](https://github.com/BurntSushi/ripgrep) installed.
- WARNING fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

===== Installed extensions ===== ~

Telescope Extension: `aerial` ~
- No healthcheck provided

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured

Telescope Extension: `notify` ~
- No healthcheck provided

==============================================================================
vim.lsp: require("vim.lsp.health").check()

- LSP log level : WARN
- Log path: C:\Users\celem\AppData\Local\nvim-data\lsp.log
- Log size: 54 KB

vim.lsp: Active Clients ~
- No active clients

==============================================================================
vim.treesitter: require("vim.treesitter.health").check()

- Nvim runtime ABI version: 14
- OK Parser: python     ABI: 14, path: C:\Users\celem\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\python.so
- OK Parser: sql        ABI: 14, path: C:\Users\celem\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\sql.so
- OK Parser: c          ABI: 13, path: C:\Users\celem\scoop\apps\neovim\current\lib\nvim\parser\c.dll
- OK Parser: lua        ABI: 14, path: C:\Users\celem\scoop\apps\neovim\current\lib\nvim\parser\lua.dll
- OK Parser: query      ABI: 14, path: C:\Users\celem\scoop\apps\neovim\current\lib\nvim\parser\query.dll
- OK Parser: vim        ABI: 14, path: C:\Users\celem\scoop\apps\neovim\current\lib\nvim\parser\vim.dll
- OK Parser: vimdoc     ABI: 14, path: C:\Users\celem\scoop\apps\neovim\current\lib\nvim\parser\vimdoc.dll

==============================================================================
which-key: require("which-key.health").check()

WhichKey: checking conflicting keymaps ~
- WARNING conflicting keymap exists for mode **"n"**, lhs: **" gn"**
- rhs: ` `

### Describe the bug

telescope live grep is not working

### Steps to Reproduce

<spc> f w then pressing any key

### Expected behavior

live grep working

### Screenshots

![resim](https://github.com/AstroNvim/AstroNvim/assets/17854703/9a64614c-48b3-4729-8485-21ad939ab76f)

**Comment by mehalter** [comment]
Check the AstroNvim requirements as listed in the documents and the repository README. The error message says that the command `rg` is not available, so it appears you do not have the optional requirement of `ripgrep` installed for live grep search.
