### ISSUE TITLE
Using the `custom_highlights` option for catppuccin significantly increases startup time

### ISSUE THREAD

**Issue by Subjective** [AstroNvim/AstroNvim#2099]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.4

### Terminal/GUI

Kitty

### AstroNvim Health

```
AstroNvim ~
- AstroNvim Version: nightly (v3.31.1-1-g0d91bac)
- Neovim Version: v0.10.0-dev-629+gb2e8c0df2
- WARNING Neovim nightly is not officially supported and may have breaking changes
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)
```

### Describe the bug

While this pertains to a specific colorscheme plugin, I noticed this only occurs with AstroNvim. Passing in any custom highlight into Catpuccin that uses the colors argument significantly increases the startup time of Catppuccin. On my machine, it increases from ~1 ms to ~15 ms. Previously, when I defined the custom highlight in the [suggested](https://astronvim.com/Configuration/config_options) file this didn't occur. However, I opted to use the config option that Catppuccin provides, as it felt cleaner than maintaining four separate files which contained the same highlight groups for all 4 catppuccin styles: `catppuccin-mocha.lua`, `catppuccin-frappe.lua`, etc. (Or is this not necessary?)

### Steps to Reproduce

Set any custom highlight group that uses a custom color from Catppuccin.
```lua
custom_highlights = function(colors)
  return {
     -- lightspeed-style highlighting for leap
    LeapMatch = { fg = colors.text, bold = true, nocombine = true },
    LeapLabelPrimary = { fg = colors.pink, bold = true, nocombine = true },
    LeapLabelSecondary = { fg = colors.blue, bold = true, nocombine = true },
  }
end,
```

### Expected behavior

I would expect Catppuccin's startup time to remain consistently fast at ~1 ms.

### Screenshots

<img width="972" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/56745535/3518b063-5b9b-48fc-a318-7507ae36cf1b">

### Additional Context

Surprisingly, this doesn't occur every time, just most of the time.

**Comment by mehalter** [comment]
This seems to just be an issue with catppuccin having some caching instability. I can replicate the behavior with a completely minimal `~/.config/nvim/init.lua` file that only sets up lazy.nvim and catppuccin with the `custom_highlights` function you provided:

![2023-07-07_06:22:12_screenshot](https://github.com/AstroNvim/AstroNvim/assets/1591837/03673667-7a0b-4e2f-af28-14df9e82e403)

The good news is that this won't affect your startup time because of lazy loading, the bad news is there's not much I can do. I personally use `catppuccin` but only use a custom highlights table and don't seem to get this issue, it seems to be specific to providing a function to `custom_highlights`.

**Comment by mehalter** [comment]
@Subjective after doing some investigation it appears to be specifically coming from the `nocombine` option. If you remove that then it goes back down. This may be an issue with the Catppuccin compiler

**Comment by Subjective** [comment]
Thanks, that fixed it for me :)
