### ISSUE TITLE
Config save for reinstall everything (delete nvim-data folder and reinstall user's LSP plugins)

### ISSUE THREAD

**Issue by duytrung** [AstroNvim/AstroNvim#2102]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Windows 10

### Terminal/GUI

Windows Terminal

### AstroNvim Health

![image](https://github.com/AstroNvim/AstroNvim/assets/2046672/47107e44-34cf-407b-82e6-85792da42780)

### Describe the bug

I would like to reinstall all of packages including LSP for python,...etc that I have previously installed but not really sure where my own config was saved. How to re-install all of my preferred plugins without having to reinstall those one by one by looking at the backup folder?
![image](https://github.com/AstroNvim/AstroNvim/assets/2046672/0a7554b1-7128-4cc7-97e0-8630c84d637a)

### Steps to Reproduce

Delete all of the nvim-data folder and reinstall.

### Expected behavior

Check whether user have install additional plugins and install those when user delete nvim-data folder and reinstall everything.

Thanks for consider the issue

**Comment by mehalter** [comment]
You want to make a user configuration and manage it: https://astronvim.com/Configuration/manage_user_config

You will need to use that to dictate your installations. If you are just installing things through the Mason UI for example that is not being saved anywhere. You will simply have to just remember. If you want it to be persistent, then making a user configuration is how you would do that.

I would recommend taking a deep look at the documentation as well as the [user_example](https://github.com/AstroNvim/user_example) to see how you would do this. 

Once you have a user configuration made then yeah, you can delete your data folder/cache folder/state folder/etc. and just have the config present and it will reinstall everything on open from plugins to mason packages to treesitter parsers. :)

**Comment by mehalter** [comment]
If you have any questions regarding the configuration process, the Discord community is extremely active and helpful and are there to help out much more than I can when it comes to tweaking user configurations.

Discord Server: https://discord.gg/AstroNvim

**Comment by duytrung** [comment]
Great! Thanks a lot @mehalter
