### ISSUE TITLE
Every time I open a new page (e.g. Telescope), Lsp reloads even though I have already executed `:LspStop`.

### ISSUE THREAD

**Issue by Squirre17** [AstroNvim/AstroNvim#2105]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

ubuntu2004

### Terminal/GUI

powershell

### AstroNvim Health

    1 astronvim: require("astronvim.health").check()
    2 ========================================================================
    3 ## AstroNvim
    4   - INFO: AstroNvim Version: v3.30.7
    5   - INFO: Neovim Version: v0.8.3
    6   - OK: Using stable Neovim >= 0.8.0
    7   - OK: `git` is installed: Used for core functionality such as updater and plugin management
    8   - OK: `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
    9   - WARNING: `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
   10   - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
   11   - WARNING: `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
   12   - WARNING: `btm` is not installed: Used for mappings to pull up system monitor (Optional)
   13   - OK: `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

I usually close lsp and switch to cscope when browsing large projects like Linux kernel source code etc bcoz lsp can't deal with such a big project and raises a bunch of error hints.

But every time I open a new buffer(e.g. by telescope), Lsp reloads even though I have already executed `:LspStop`. This very annoying to me.

### Steps to Reproduce

1. go to any file in linux and stop lsp
2. go to another file and found lsp will be reload again.

### Expected behavior

1. go to any file in linux and stop lsp
2. go to another file and found lsp still stop.

**Comment by mehalter** [comment]
This has to do with `lspconfig` and the core `:LspStop` Neovim command. You are basically only stopping nthe language servers that are currently running. They will still be listening on filetype and root detection to start back up on the next available file that they can.

**Comment by Squirre17** [comment]
> This has to do with `lspconfig` and the core `:LspStop` Neovim command. You are basically only stopping nthe language servers that are currently running. They will still be listening on filetype and root detection to start back up on the next available file that they can.

have some ways to close lsp completely in the abovementioned big project?

**Comment by mehalter** [comment]
Probably the easiest way is to configure the project with Neoconf (a default provided plugin for project  local LSP settings) to disable language servers for it specifically or change their root detection. I don't think there is a built in way to do this

**Comment by mehalter** [comment]
I'm going to go ahead and close this. @Squirre17 if you come up with a good solution that fits your needs it would definitely be helpful to leave a comment here :) Also if you have more questions or want to see if others have solved this in another way the [AstroNvim Discord](https://discord.gg/AstroNvim) is a great resource and the community is super warm, welcoming, and responsive :)
