### ISSUE TITLE
Cannot turn off search highlight toggling so I can use hlslens

### ISSUE THREAD

**Issue by UnsolvedCypher** [AstroNvim/AstroNvim#2109]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Ubuntu 20.04

### Terminal/GUI

Terminator

## AstroNvim
```
- AstroNvim Version: v3.31.2
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK git is installed: Used for core functionality such as updater and plugin management
- OK xdg-open is installed: Used for gx mapping for opening files with system opener (Optional)
- OK lazygit is installed: Used for mappings to pull up git TUI (Optional)
- OK node is installed: Used for mappings to pull up node REPL (Optional)
- WARNING gdu is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK btm is installed: Used for mappings to pull up system monitor (Optional)
- OK python is installed: Used for mappings to pull up python REPL (Optional)
```

### Describe the bug

The automatic search highlight toggling (introduced [here](https://github.com/AstroNvim/AstroNvim/commit/7cafd62d739075a8392b947984c37aa6f54d5e2f) cannot be turned off, and it causes plugins like `hlslens` not to work.

### Steps to Reproduce

1. Use `/` to start a search, and type your query
2. Move off of the match
3. Notice that the highlighting automatically turns off

### Expected behavior

I expect to be able to turn off this functionality so that plugins like `hlslens` can function correctly.

**Comment by mehalter** [comment]
You can put this in your `polish` function:

```lua
vim.on_key(nil, vim.api.nvim_get_namespaces()["auto_hlsearch"])
```
