### ISSUE TITLE
Can we please provide feature to move/pin buffers in the tabline (when using heirline)

### ISSUE THREAD

**Issue by krishnakumarg1984** [AstroNvim/AstroNvim#2111]
### Is your feature related to a problem?

There are no easy provisions to move or pin buffers shown on the tabline in AstroNvim.

### Describe the new feature

`bufferline.nvim` had the ability to configure moving buffers shown in the tabline to the right and left. Example bufferline keymaps to do that would be:

```lua
vim.keymap.set("n", "<leader>bM", "<Cmd>BufferLineMovePrev<CR>", { desc = "Reorder (move left)" })
vim.keymap.set("n", "<leader>bm", "<Cmd>BufferLineMoveNext<CR>", { desc = "Reorder (move right)" })
```
Similarly, one could pin a buffer in the tabline with the following keymap:

```lua
vim.keymap.set("n", "<leader>bp", "<Cmd>BufferLineTogglePin<CR>", { desc = "Pin buffer (toggle)" })
```

Can we please provide this functionality with AstroNVim (which currently uses `heirline` for the tabline)?

**Comment by mehalter** [comment]
`<b` and `>b` for moving

Pinning buffers we are leaving out of the scope of our implementation. Feel free to use Bufferline instead of our Heirline implementation if you want some super advanced features.
