### ISSUE TITLE
Add a UX toggle to toggle buffer numbers (and navigate to them) in AstroNvim's tabline

### ISSUE THREAD

**Issue by krishnakumarg1984** [AstroNvim/AstroNvim#2112]
### Is your feature related to a problem?

`bufferline` had an option to show buffer numbers on the tabline using the configuration table key.

``` lua
numbers = "ordinal",
```

AstroNvim currently does not have ths feature.

### Describe the new feature

Can we please provide a keymap to toggle buffer number from the buffer menu e.g. `<leader>bn` (and/or provide an option to set it permanently)? Additionally, it would be nice to be able to move to buffers by the buffer number. The current way of choosing buffer through a pop-up alphabetical menu is super slow. 

Something like `<leader>b1` through `<leader>b6` to quickly navigate between buffer numbers 1 through 6 shown on the tabline could be quite efficient.

**Comment by mehalter** [comment]
you can use `require("astronvim.utils.buffer").nav_to(num)` to set up your own custom bindings for something like `<leader>b1`-`<leader>bn`

Also for the statusline numbering we do not want to continue adding more complexities and abstractions to our APIs. Our approach is to keep them minimal and lean while also completely extendable. You can use our status API to implement this feature if you would like or you can switch to using a more full featured tabline/bufferline such as bufferline.nvim.

Here is a very crude example of adding buffer numbers to the tabline:

```lua
return {
  plugins = {
    {
      "rebelot/heirline.nvim",
      opts = function(_, opts)
        local status = require "astronvim.utils.status"

        opts.tabline[2] = status.heirline.make_buflist {
          { provider = function(self) return self.bufnr .. ". " end },
          status.component.tabline_file_info(), -- component for each buffer tab
        }
      end,
    },
  },
}
```

**Comment by krishnakumarg1984** [comment]
@mehalter Thank you. Is there a way to provide keymaps to quickly navigate to the numbered buffers?
