### ISSUE TITLE
`<C-u>` and `<C-d>` can not scrolling in signature help

### ISSUE THREAD

**Issue by chaozwn** [AstroNvim/AstroNvim#2113]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macos 13.3.1

### Terminal/GUI

alacritty

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: v3.31.2
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

<img width="1140" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/51357674/569849e8-7421-4f07-bed5-8406c5fa577c">

### Steps to Reproduce

1. open python project
2. import community pack python
3. `shift + k` show si.gnature help
4. `<C-u>` and `<C-d>` can not scrolling

### Expected behavior

`<C-u>` and `<C-d>` can scrolling.

**Comment by krishnakumarg1984** [comment]
I have exactly the same issue.

**Comment by mehalter** [comment]
This is not something that is an option with the built in neovim LSP. The best approach if you need to scroll @chaozwn is to press `K` twice to put your cursor in the help window and then you can scroll and read to your desire :)
