### ISSUE TITLE
Bug: Command "LspRestart" does not start the Lsp server again.

### ISSUE THREAD

**Issue by BoolPurist** [AstroNvim/AstroNvim#2115]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Fedora Linux 37 (Cinnamon) x86_64

### Terminal/GUI

Alacritty

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.32.0
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- WARNING `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Command "LspRestart" does not start the LSP Server, rust-analyzer, again.
When I however enter the command "LspStart" then the LSP server is active again.

### Steps to Reproduce

1. Go into a rust project
2. Open a buffer with content of rs file.
3. Switch to command mode and type LspRestart
4. Now the Lsp server should stop showing diagnostics to you for example

### Expected behavior

If the command "LspRestart" is entered, the Lsp server should be active again after a while.

### Additional Context

Output of LspInfo after the command LspRestart on a rs file:

```text
 Press q or <Esc> to close this window. Press <Tab> to view server doc.
 
 Language client log: /home/nice_graphic/.local/state/nvim/lsp.log
 Detected filetype:   rust
 
 0 client(s) attached to this buffer: 
 
 Other clients that match the filetype: rust
 
 Config: rust_analyzer
 	filetypes:         rust
 	root directory:    Asynchronous root_dir functions are not supported in :LspInfo
 	cmd:               /home/nice_graphic/.local/share/nvim/mason/bin/rust-analyzer
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   experimental/serverStatus
 
 Configured servers list: lua_ls, cssls, taplo, rust_analyzer

```

Usual output if LSP server is active on rs file:

```text
 Language client log: /home/nice_graphic/.local/state/nvim/lsp.log
 Detected filetype:   rust
 
 1 client(s) attached to this buffer: 
 
 Client: rust_analyzer (id: 2, bufnr: [4])
 	filetypes:       rust
 	autostart:       true
 	root directory:  /home/nice_graphic/Code/rust/tui/todo_with_ratatui
 	cmd:             /home/nice_graphic/.local/share/nvim/mason/bin/rust-analyzer
 
 Configured servers list: lua_ls, cssls, taplo, rust_analyzer

```

**Comment by mehalter** [comment]
This is outside of AstroNvim and is a larger issue with the connection between built in LSP and language servers themselves. You can easily test this by trying `:LspRestart` on the html language server, clangd language server, css language server, etc. all work. And many language servers improperly implement many LSP API specifications. I know `pyright`, `rust_analyzer`, `lua_language_server` all have issues with restarting themselves. This is present in core Neovim and not just AstroNvim. Sorry I can't be of much more help here!

**Comment by BoolPurist** [comment]
Thanks for the explanation.
