### ISSUE TITLE
showtabline option does not work in config

### ISSUE THREAD

**Issue by s1n7ax** [AstroNvim/AstroNvim#2122]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Linux Mint 21.1

### Terminal/GUI

Alacritty

### AstroNvim Health

```
- AstroNvim Version: v3.32.0
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- WARNING `node` is not installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)
```

### Describe the bug

I am following [this](https://astronvim.com/Recipes/disable_tabline) document to disable tabline. I have my user configuration at `/home/s1n7ax/.config/astronvim/lua/user/init.lua`. It looks like below.

```lua
return {
  lsp = {
    formatting = {
      format_on_save = true,
    },
  },
  options = {
    opt = {
      showtabline = 0,
    },
  }
}
``` 

### Steps to Reproduce

1. Add following to user configuration init file.

```lua
return {
  lsp = {
    formatting = {
      format_on_save = true,
    },
  },
  options = {
    opt = {
      showtabline = 0,
    },
  }
}
```
2. Fire up neovim
3. Open a file using `Telescope find_files`

### Expected behavior

Tab bar should not be visible

### Screenshots

![image](https://github.com/AstroNvim/AstroNvim/assets/18459807/47933e7c-f55d-4a18-8374-3ecbedd93f73)

**Comment by mehalter** [comment]
Using the provided `init.lua` file in step 1 of the reproduction steps it appears to work perfectly. It may be that in your user configuration you have an `user/options.lua` file separated out from the `user/init.lua` file that is taking precedence.

**Comment by s1n7ax** [comment]
Ah yes. I think I created that because it was in the source code. Totally disregarded that because [example file tree](https://astronvim.com/configuration/splitting_up#example-file-tree) doesn't have an `options.lua` that.
