### ISSUE TITLE
`K` no longer works with neovim 0.10

### ISSUE THREAD

**Issue by tomKPZ** [AstroNvim/AstroNvim#2129]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Arch Linux

### Terminal/GUI

kitty

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: nightly (v3.33.0)
- Neovim Version: v0.10.0-dev-661+gef94fb69c
- WARNING Neovim nightly is not officially supported and may have breaking changes
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Pressing `K` appears to check for man pages for the symbol under the cursor.  For example, I have a function `MaskContains` in a cpp project.  Pressing `K` on it gives a warning: `man.lua "no manual entry for "MaskContains"`.

Previously, `K` would pull up documentation from LSP.

### Steps to Reproduce

1. Press `K` on a symbol in a cpp or python project.

### Expected behavior

Help is obtained from LSP.

### Additional Context

I cannot submit the issue unless "Using a stable version of Neovim (i.e. not neovim nightly)" is checked.  However, I am using nightly.  I figure this issue should be reported either way.

**Comment by mehalter** [comment]
Make sure you have updated to the most recent Neovim nightly :)

**Comment by tomKPZ** [comment]
> Make sure you have updated to the most recent Neovim nightly :)

That fixed it, thanks!

**Comment by mehalter** [comment]
Yup just make sure to always stay up to date if you are attempting to use Neovim nightly. Also there is no guarantee it will work with AstroNvim since we do not officially support nightly Neovim in any way.
