### ISSUE TITLE
Updater not available for non-git installations

### ISSUE THREAD

**Issue by alex-belost** [AstroNvim/AstroNvim#2139]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Windows 10

### Terminal/GUI

Windows Terminal

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: unknown
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- ERROR git is not installed: Unable to validate git version
- OK explorer is installed: Used for gx mapping for opening files with system opener (Optional)
- OK lazygit is installed: Used for mappings to pull up git TUI (Optional)
- OK node is installed: Used for mappings to pull up node REPL (Optional)
- OK gdu is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK btm is installed: Used for mappings to pull up system monitor (Optional)
- OK python is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

All dependencies were installed and all functionality works well, except :AstroUpdate, when I trying to do it, I got an error message `Updater not available for non-git installations`

### Steps to Reproduce

It's first installation on Windows, so I follow the instruction and use my own user settings https://github.com/alex-belost/astronvim-user

### Expected behavior

Possibility to update

**Comment by mehalter** [comment]
If you go to the directory where you cloned the project in a terminal and run `git status` what do you get?

**Comment by mehalter** [comment]
I also see in the checkhealth that it's unable to verify that you have `git`. Another good check is to run AstroNvim and open a terminal inside of it and run `git` and see if it's available in your path

**Comment by alex-belost** [comment]
`If you go to the directory where you cloned the project in a terminal and run git status what do you get?`
works fine

`AstroNvim and open a terminal inside of it and run git and see if it's available in your path` 
terminal doesn't want to open at all, I mean, it starts opening and when I see a window, it immediately closes and writes `usr/bin/bash: \s: no such file or directory
PS. I do it in the bash shell 

I tried reinstalling Astronvim without my config and got the same result

and one more thing, I figured out I couldn't edit files, I got the same message `no such file or directory`
By other editors like VSCode, files were edited

**Comment by mehalter** [comment]
It looks like something is going on with how Neovim is calculating what shell to use. If you run just `nvim --clean` and run `:terminal` do you get the same error?

Try running `:set shell=/path/to/shell` and see if that makes things work afterwards

**Comment by alex-belost** [comment]
`:terminal do you get the same error?`
`E475: invalid value for argument cmd: 'C:Program FilesGitusr^Hin^Hash.exe' is not executable`

`:set shell=C:\Program\ Files\Git\bin\bash.exe`
`E475: Invalid value for argument cmd: 'C:Program' is not executable`

**Comment by mehalter** [comment]
Since this happens in a clean environment this is unrelated to AstroNvim. I don't use Windows so I honestly don't know the correct way to set the shell for Neovim there. I would recommend joining the Discord since there are windows users there who have these things working and know more than I do regarding this. Sorry!
