### ISSUE TITLE
Can not display mode text

### ISSUE THREAD

**Issue by Asthestarsfalll** [AstroNvim/AstroNvim#2143]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

manjaro

### Terminal/GUI

konsole

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: v3.33.3
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Following the  [doc](https://astronvim.com/Recipes/status#default-statusline-with-mode-text), but nothing changed

### Steps to Reproduce

just add the config to user/init.lua

### Expected behavior

Display mode text to  statusline.

**Comment by mehalter** [comment]
Do you have a `plugins/` folder? That will take precedence over your `init.lua`

**Comment by Asthestarsfalll** [comment]
> Do you have a `plugins/` folder? That will take precedence over your `init.lua`

It works after I move it to plugins/heirline.lua!

**Comment by mehalter** [comment]
Also just a heads up, this is also available in AstroCommunity :)

https://github.com/AstroNvim/astrocommunity

So if you are using AstroCommunity you can simply add to your `plugins/` folder:

`{ import = "astrocommunity.bars-and-lines.heirline-mode-text-statusline" }`

**Comment by Asthestarsfalll** [comment]
> Also just a heads up, this is also available in AstroCommunity :)
> 
> https://github.com/AstroNvim/astrocommunity
> 
> So if you are using AstroCommunity you can simply add to your `plugins/` folder:
> 
> `{ import = "astrocommunity.bars-and-lines.heirline-mode-text-statusline" }`

wow, that's really awesome. I think user config and astrocommunity is an excellent design, which can greatly help some rookies like me.
