### ISSUE TITLE
Varios bugs after updating astro

### ISSUE THREAD

**Issue by joetifa2003** [AstroNvim/AstroNvim#2146]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Mx linux

### Terminal/GUI

kitty

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: v3.33.4
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- WARNING `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

After updating Astro i have a lot of issues happening, i tried to update nvim, reinstalling packages and nothing works

### Steps to Reproduce

- <leader>gt - when selecting an option from the list it doesn't jump to correct line of code
- <leader>ls - on big golang files (more than 3000 lines) doesn't work and fail with an error and fials with `Aerial could find no supported backend`
- <leader>fw - or any thing else basically, after selecting an option from the list, it automatically swtiches to insert mode and it was not like that before.

### Expected behavior

Described above

### Screenshots

![image](https://github.com/AstroNvim/AstroNvim/assets/62658783/70406092-4c73-436a-9604-5b99ec65eea1)

You can see that the syntax highlighting here is broken for this big file and also <leader>ls fails/

![image](https://github.com/AstroNvim/AstroNvim/assets/62658783/1483d0c6-145c-4fc6-9e66-4fc0eb9ea42f)
![image](https://github.com/AstroNvim/AstroNvim/assets/62658783/be23f8e7-9ca0-4fce-9f29-be3f0efa9924)

After selecting an option from <leader>fw you can see it switched to insert mode automatically

![image](https://github.com/AstroNvim/AstroNvim/assets/62658783/23ab12fb-b622-4c9e-aeea-0a6ce6df7b3d)

After i select this it didn't jump to the correct hunk, which was working before

I don't know why all of these issues appeared out of nowhere, i really enjoy using astro

**Comment by mehalter** [comment]
Please share your user configuration as this this not enough information to replicate any of these.

**Comment by joetifa2003** [comment]
I rolledback to 3.30.0 and all of these are fixed, but the issue of automatically going to  insert mode is still there

**Comment by joetifa2003** [comment]
https://github.com/joetifa2003/astrovim-config
This is my user config, thanks for the fast response!

**Comment by joetifa2003** [comment]
https://github.com/AstroNvim/AstroNvim/assets/62658783/4473a8e8-4037-47a0-91d8-bc27d070d588

This is a video showing the issues

**Comment by mehalter** [comment]
I can't replicate any of the issues you have described with a fresh installation of your user configuration. The only one I can replicate is the insert after selecting a Telescope entry and that looks to be related to your codeium heirline component that you made. Basically the function that gets the status string is causing some asynchronous issues probably related to this: https://github.com/neovim/neovim/pull/22984

This is sadly outside of the scope of what I can fix

**Comment by mehalter** [comment]
As for the syntax issues. I would recommend doing a full cleaning of your data, cache, and state folders and see if a clean reinstallation fixes it. It could be update to treesitter and things that it just needs to rebuild:

```sh
mv ~/.local/share/nvim ~/.local/share/nvim.bak
mv ~/.local/state/nvim ~/.local/state/nvim.bak
mv ~/.cache/nvim ~/.cache/nvim.bak
nvim
```

**Comment by joetifa2003** [comment]
Oh thanks so much for your help, removing the codium component fixed the issue!

**Comment by joetifa2003** [comment]
The only thing remaining for me to fix is the git status not jumping correctly

**Comment by mehalter** [comment]
I don't think that this is actually a feature of Telescope's `git_status` picker at all. It is showing you the git status and is just opening the file with the changes. I don't believe telescope actually calculates where the diffs were especially because if there are multiple hunks it wouldn't have any idea which one to select.

**Comment by joetifa2003** [comment]
Found out why treesitter was not working for big files.

On the docs website it says that the default config for treesitter is this

```
opts = {
  autotag = { enable = true },
  context_commentstring = { enable = true, enable_autocmd = false },
  highlight = {
    enable = true,
    disable = function(_, bufnr) return vim.api.nvim_buf_line_count(bufnr) > 10000 end,
  },
  incremental_selection = { enable = true },
....
```

But it was actually this

```
highlight = {
        enable = true,
        disable = function(_, bufnr) return vim.b[bufnr].large_buf end,
      },
 ```
 
 So the docs need update. i changed that on my user config to be false and now treesitter works again fine!
