### ISSUE TITLE
<C-a> and <C-x> behaves strange when add or minus number

### ISSUE THREAD

**Issue by sidkang** [AstroNvim/AstroNvim#2148]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.4.1

### Terminal/GUI

iTerm2

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.33.3
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

When using <C-a> to a number, when the number is contained in the "", the number at the cursor will add 1, but when the number is in the document but not in "", the number will be minused 1

### Steps to Reproduce

```beancount
2023-07-18 * "AAAAA" "BBBBBBB" #ysf
    time: "20:55"
    Expenses:Transport:PublicTransit                            2.00 CNY
    Liabilities:Bank:CCB:7305
```

```
1. When I put the cursor at 18, press <C-a>, it will become 17;
2. When I put the cursor at 55, press <C-a>, it will become 56;
3. When I put the cursor at 18, press <C-x>, it will become 19;
4. When I put the cursor at 55, press <C-x>, it will become 54;
```

### Expected behavior

The <C-a> or <C-x> should behavior same and consistent wherever the number is.

**Comment by mehalter** [comment]
This is because the number is `-18` and not 18. This is default vim/Neovim behavior and not really a bug in AstroNvim sorry!
