### ISSUE TITLE
bug: incorrect hl group in cmp with tailwind colors

### ISSUE THREAD

**Issue by Subjective** [AstroNvim/AstroNvim#2149]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.4

### Terminal/GUI

kitty

### AstroNvim Health

```
AstroNvim
- AstroNvim Version: nightly (v3.33.1-1-gb58591b)
- Neovim Version: v0.10.0-dev-689+gab5cdbd16
- WARNING Neovim nightly is not officially supported and may have breaking changes
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)
```

### Describe the bug

Tailwind colors are not highlighted in the cmp menu for the selected entry. I bisected the issue to b58591b2.

### Steps to Reproduce

<details>
<summary>Minimal Config</summary>

```lua
{
  "hrsh7th/nvim-cmp",
  dependencies = {
    {
      "js-everts/cmp-tailwind-colors",
      opts = {
        format = function(itemColor)
          return {
            fg = itemColor,
            bg = itemColor,
            text = " ",
          }
        end,
      },
    },
  },
  opts = function(_, opts)
    local format_kinds = opts.formatting.format
    opts.formatting.format = function(entry, item)
      if item.kind == "Color" then
        item = require("cmp-tailwind-colors").format(entry, item)
        if item.kind == "Color" then return format_kinds(entry, item) end
        return item
      end
      return format_kinds(entry, item)
    end
  end,
},
```

</details>

1. Install the tailwindcss language server
2. Use the provided config for cmp
3. Select a color entry from the cmp menu; only the actively selected item is not properly colored

### Expected behavior

For the active selected tailwind cmp entry to be colored

### Screenshots

Before:
<img width="173" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/56745535/0bba4047-4def-4a52-8662-8c87b851c412">

Now:
<img width="176" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/56745535/55371af5-9ca4-4c2b-83d5-6477baef2e8a">

![Screen Recording 2023-07-19 at 11 34 55 PM](https://github.com/AstroNvim/AstroNvim/assets/56745535/5e87d3f1-f482-46de-a1ee-bdb200023208)

### Additional Context

I'm using Catppuccin, but for some reason this doesn't occur with the default astrodark colorscheme. I'm not too familiar with hl groups, so I decided to just report this as an issue as I'm not sure if the changes made in b58591b2 were intentional or not. Thanks.

**Comment by mehalter** [comment]
This linnked commit is actually a bug fix and not a bug. This is both the correct way to set the highlights and the correct highlights that we want to use. This appears to probably be a bug in the plugin you are using and how they are doing things not playing nicely with how `nvim-cmp` sets up their highlights. To work around this bug you can set your own `winhighlight` if you would like in your own `nvim-cmp` configuration or you can make a minimal neovim configuration with that `nvim-cmp` option set and tailwind css lsp set up and show that it is broken.

**Comment by Subjective** [comment]
Okay, the issue has to do with the fact that Catppuccin sets the fg color of the `PmenuSel` hl group while AstroTheme does not. Before https://github.com/AstroNvim/AstroNvim/commit/b58591b200e6731a488e9f547074cefa61dd03fd, the `PmenuSel` wasn't being set for cmp's menu, so I didn't notice this.

```lua
--- catppuccin
PmenuSel = { fg = C.text, bg = C.surface1, style = { "bold" } }
--- astrotheme
PmenuSel = { fg = C.none, bg = C.ui.current_line }
```

To fix this, I'll just override Catppuccin's default `PmenuSel` hl group.
