### ISSUE TITLE
cannot open  two instances at the same time

### ISSUE THREAD

**Issue by nbittich** [AstroNvim/AstroNvim#2150]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

POP OS 22

### Terminal/GUI

wezteerm

### AstroNvim Health

 AstroNvim
   - AstroNvim Version: v3.33.4
   - Neovim Version: v0.9.1
   - OK Using stable Neovim >= 0.8.0
   - OK git is installed: Used for core functionality such as updater and plugin management
   - OK xdg-open is installed: Used for gx mapping for opening files with system opener (Optional)
   - OK lazygit is installed: Used for mappings to pull up git TUI (Optional)
   - OK node is installed: Used for mappings to pull up node REPL (Optional)
   - OK gdu is installed: Used for mappings to pull up disk usage analyzer (Optional)
   - OK btm is installed: Used for mappings to pull up system monitor (Optional)
   - OK python is installed: Used for mappings to pull up python REPL (Optional)
  

### Describe the bug

If I open nvim in two different tabs, the new instance is opened in the same tab.
Regression after AstroUpdate.

### Steps to Reproduce

1. run nvim
2. run nvim again in a different tabs

### Expected behavior

two different nvim instances

### Screenshots

https://github.com/AstroNvim/AstroNvim/assets/3816305/cc04c9a7-a5dc-453c-83ca-5a4c2dc4d955

**Comment by mehalter** [comment]
I have absolutely no idea what is going on with your machine/terminal here 😅 this looks unrelated to AstroNvim though as opening two instances of Neovim would spin up two different processes and from within AstroNvim we don't have any power over this in any way. Sorry!
