### ISSUE TITLE
Toggle term node doesn't work

### ISSUE THREAD

**Issue by osenvosem** [AstroNvim/AstroNvim#2153]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 12.6

### Terminal/GUI

kitty

### AstroNvim Health

AstroNvim
AstroNvim Version: v3.33.4
Neovim Version: v0.9.1
OK Using stable Neovim >= 0.8.0
OK git is installed: Used for core functionality such as updater and plugin management
OK open is installed: Used for gx mapping for opening files with system opener (Optional)
OK lazygit is installed: Used for mappings to pull up git TUI (Optional)
OK node is installed: Used for mappings to pull up node REPL (Optional)
OK gdu is installed: Used for mappings to pull up disk usage analyzer (Optional)
OK btm is installed: Used for mappings to pull up system monitor (Optional)
OK python is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

After pressing `Space t n` terminal float window blinks and disappears 

### Steps to Reproduce

1. Press `Space t n`

### Expected behavior

Terminal is opened with node REPL

### Screenshots

https://github.com/AstroNvim/AstroNvim/assets/6762673/dad69643-d14f-4289-9069-4e24f620aa4f

**Comment by mehalter** [comment]
If you open a terminal simply with `:term` and then run `node`, what result do you get?

**Comment by osenvosem** [comment]
<img width="635" alt="Screenshot 2023-07-21 at 17 15 55" src="https://github.com/AstroNvim/AstroNvim/assets/6762673/34059d87-102c-4c4c-b6eb-5810ed5e3fea">

**Comment by mehalter** [comment]
Do the other terminals work? Like `<leader>tp`?

**Comment by osenvosem** [comment]
Yes, the other terminal work.

**Comment by mehalter** [comment]
fascinating 😅 do you happen to be using `nvm`?

**Comment by osenvosem** [comment]
I use fnm

**Comment by mehalter** [comment]
Hm I wonder if `fnm` uses shims and this could very well be a nasty interaction with shims

**Comment by osenvosem** [comment]
<img width="368" alt="Screenshot 2023-07-21 at 18 12 22" src="https://github.com/AstroNvim/AstroNvim/assets/6762673/b77dae35-3d24-42a9-a045-768fd011b523">

**Comment by osenvosem** [comment]
Maybe get the node path with `which node` in configuration?

**Comment by mehalter** [comment]
ah yeah this looks like this has to do with `fnm` using shims so that command is not actually found in your path! This is actually not supported by many things. This can cause issues in ToggleTerm and Mason. I would definitely recommend checking out solutions that don't use shims ([rtx](https://github.com/jdxcode/rtx) is a truly amazing one). Sadly this is out of scope of what I can do in AstroNvim since this is an upstream problem with not just ToggleTerm but other plugins as well. Sorry!

**Comment by mehalter** [comment]
If you run `which node` does it return?

**Comment by mehalter** [comment]
ah I see, so it's *not* using shims like I thought. It appears that something is going on with the loading of your stuff where that's not available on your shell startup. You probably need to force resolve the environment to have a global environment available on the initial running of zsh and before it processes some sort of location.

**Comment by mehalter** [comment]
for rtx this is done with `eval "$(rtx hook-env)"`, there should be something similar to `fnm` to properly set up the environment. Sadly this just boils down to improperly setting up the terminal environment and nothing with AstroNvim or ToggleTerm. If the command is not found then `which` is also not going to work there either. Sorry! Good luck!
