### ISSUE TITLE
Allow to ignore function keys

### ISSUE THREAD

**Issue by windowsrefund** [AstroNvim/AstroNvim#2160]
### Is your feature related to a problem?

While I understand the utility of mapping things to the F keys, i personally avoid using them as they're not much different than arrow keys in my opinion. That said, the [debugger mappings](https://astronvim.com/Basic%20Usage/mappings#debugger-mappings) almost advocate their use (or technically speaking, their available use) since they show up in the WhichKey menu.

For someone who has no intention of ever using them, the resulting Whichkey menu just looks more bloated than it needs to.

I know I can most likely clean up these mappings by way of [overriding](https://astronvim.com/Configuration/override_formats) but I thought I'd request a feature instead; something along the lines of a "Enable Function Keymaps" boolean that could easily be enabled/disabled according to a given user's work habits and preferences. 

### Describe the new feature

Already  mentioned but basically some kind of boolean which had the net effect of setting or clearing any  function key mappings. If disabled, the bindings would be cleared and Whichkey menu would not show them. When enabled, they would be mapped and Whichkey would show them (as it currently does by default).

**Comment by mehalter** [comment]
This is a level of abstraction we would like to stay away from. You can definitely instead go and reword thee messages in your user configuration.
