### ISSUE TITLE
Local path autocommplete causes neovim no responding in python file

### ISSUE THREAD

**Issue by Asthestarsfalll** [AstroNvim/AstroNvim#2171]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

manjaro

### Terminal/GUI

konsole

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: v3.33.5
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

When I enther a local path in a python file, it will cause the whole neovim no responding:
![2023-07-24_21-18](https://github.com/AstroNvim/AstroNvim/assets/72954905/9397a76b-28b1-4396-83cc-15af82b566fb)
and a high CPU occupation:
![2023-07-24_21-19](https://github.com/AstroNvim/AstroNvim/assets/72954905/8e5b00f2-6798-42e8-b2d5-380c968e3c8a)

### Steps to Reproduce

I haven't change any configurations about autocommplete

### Expected behavior

complete the local path as soon as possible

**Comment by Asthestarsfalll** [comment]
I find that it will always break down when I program in a python file:
![2023-07-24_21-37](https://github.com/AstroNvim/AstroNvim/assets/72954905/f344b6e7-c152-4433-98cf-a97ca426a1fb)

**Comment by mehalter** [comment]
I believe there are some pretty significant performance issues with pyright recently. I've run into some performance issues there granted not with the path cmp selector in particular. The discord is a good place to ask questions to see if others have come up with solutions nad things

**Comment by mehalter** [comment]
But we don't do anything about the performance of language servers so it's sadly outside of what we are able to improve. sorry!
