### ISSUE TITLE
Can't find "fold-delete-marker" in WhichKey

### ISSUE THREAD

**Issue by rozhelluk** [AstroNvim/AstroNvim#2174]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Arch Linux 

### Terminal/GUI

alacritty 

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: nightly (v3.34.0-1-gf6911bf)
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

There is no fold-delete-marker (:help fold-delete-marker) option in the which-key.nvim menu.

### Steps to Reproduce

just type "z"

### Expected behavior

It should be like this, but for deletion:
![image](https://github.com/AstroNvim/AstroNvim/assets/115512231/08bab139-b748-48fb-a467-9d874c51d003)

### Screenshots

![image](https://github.com/AstroNvim/AstroNvim/assets/115512231/bce17a55-63b6-4af3-9a70-d2dbe2fa7046)

**Comment by mehalter** [comment]
This is unrelated to AstroNvim. I went ahead and made a PR in the correct repository to resolve this: https://github.com/folke/which-key.nvim/pull/487
