### ISSUE TITLE
Why is everything purple

### ISSUE THREAD

**Issue by slater1** [AstroNvim/AstroNvim#2177]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.4.1

### Terminal/GUI

terminal

### AstroNvim Health

   2   astronvim: require("astronvim.health").check()
   3   
   4   AstroNvim
   5   - AstroNvim Version: v3.34.0
   6   - Neovim Version: v0.9.1
   7   - OK Using stable Neovim >= 0.8.0
   8   - OK git is installed: Used for core functionality such as updater and plugin management
   9   - OK open is installed: Used for gx mapping for opening files with system opener (Optional)
  10   - WARNING lazygit is not installed: Used for mappings to pull up git TUI (Optional)
  11   - WARNING node is not installed: Used for mappings to pull up node REPL (Optional)
  12   - WARNING gdu is not installed: Used for mappings to pull up disk usage analyzer (Optional)
  13   - WARNING btm is not installed: Used for mappings to pull up system monitor (Optional)
  14   - OK python3 is installed: Used for mappings to pull up python REPL (Optional)
  15   

### Describe the bug

Why is everything purple on a vanilla install? and the highlight line green? It's illegible.

### Steps to Reproduce

rm -rf everything nvim
clone the repo into ~/.config/nvim
nvim

### Expected behavior

The teal color scheme was nice.

### Screenshots

<img width="910" alt="Screenshot 2023-07-26 at 10 55 01 AM" src="https://github.com/AstroNvim/AstroNvim/assets/2089725/1b1c5f29-93af-4f79-8bd0-240a9a7e4a26">

**Comment by mehalter** [comment]
Check the requirements listed in the README and documentation. This is because you are not using a supported terminal emulator.

**Comment by slater1** [comment]
Thanks for the reply. 

I'll have to concede, I did get carried away with my assumption that the default macOS terminal would be supported, so I didn't check the README or docs.

I like AstronVim - it's on all my other devices (even Termux!). So I'll be installing another terminal emulator to make it work on macOS.

Thanks for a great nvim experience!
