### ISSUE TITLE
Format reloads the buffer on Lua files

### ISSUE THREAD

**Issue by s1n7ax** [AstroNvim/AstroNvim#2178]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Linux Mint 21.1

### Terminal/GUI

Alacritty

### AstroNvim Health

```
AstroNvim ~
- AstroNvim Version: v3.34.0
- Neovim Version: v0.10.0-dev-722+g7668f89d5
- WARNING Neovim nightly is not officially supported and may have breaking changes
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- WARNING `node` is not installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)
```

### Describe the bug

When running Format, it reloads the entire buffer making the current cursor position to change on all the windows that has the same buffer is opened.

### Steps to Reproduce

1. Run nvim
2. Create a new project by running, `mkdir test && cd test && git init && nvim test.lua`
3. Add some content to the file
4. Move the cursor to first line (<kbd>g</kbd><kbd>g</kbd>)
5. Run `:vsp` to make a another window of the same buffer
6. Move the cursor to the last line in the new window (<kbd>G</kbd>)
7. Jump to the first window (<kbd>Ctrl</kbd> + <kbd>w</kbd> - <kbd>h</kbd>)
8. Run `:Format` command

### Expected behavior

Expected:
- In the second window the cursor should be in the last line
- Diagnostic styles (underline and stuff) should be visible after format

Actual:
- In the second window the cursor position resets to the first line after `:Format`
- Diagnostic styles disappears after format

### Screenshots

https://github.com/AstroNvim/AstroNvim/assets/18459807/b0ff5402-7597-41d7-be20-bef248a3b44b

### Additional Context

This I believe is happening due to LSP format handler replacing the entire file text to the buffer (probably LS sends the formatted file content not just the part that should change). This is happening even if the code is already formatted. Only workaround I found was disabling `lua_ls` formatter and using `stylua` through `null-ls`

**Comment by mehalter** [comment]
I cannot replicate this with a stock installation of AstroNvim or my own installation of AstroNvim. I have set up with `lua_ls` and `stylua` and follow the steps and do not get the buffers reloading at all. Can you replicate it if you remove your user configuration?

**Comment by s1n7ax** [comment]
I deleted the entire user config I created at `~/.config/astronvim`. When I do the same inside `~/.config/nvim` formatting does not reset the file but on another location it does. I tried adding `.stylua.toml` in `~/.config/astronvim` to the new directory. No idea what's going on.


https://github.com/AstroNvim/AstroNvim/assets/18459807/45478960-ed22-4c2d-9448-98895d927014

**Comment by s1n7ax** [comment]
Yes, I have deleted the entire user config. Weirdly file will not reset if the location of the file is at `.config/nvim`. I have tried copying the `.stylua.toml` from the  `.config/nvim` to new dir as well.


https://github.com/AstroNvim/AstroNvim/assets/18459807/9268109d-9f19-4501-9090-661c4132a15c

**Comment by s1n7ax** [comment]
@mehalter It's the `.neoconf.json`. I copied it from `.config/nvim` to `~/test`. It is disabling the lua_ls formatter so null-ls takes over.

```
    "lua_ls": {
      "Lua.format.enable": true
    }
```

Not sure how `neoconf` supposed to work. But if the expected behavior is to fallback to `.config/nvim/.neoconf.json` when a local `.neoconf.json` is not present, then that's not the behavior right now. Otherwise I guess this can be closed.

**Comment by mehalter** [comment]
Ah yes, that file is not global settings. Global settings can be set in `.config/nvim/neoconf.json`

**Comment by s1n7ax** [comment]
I did `mv ~/.config/nvim/.neoconf.json ~/.config/nvim/neoconf.json`. It's not working as a global config.
