### ISSUE TITLE
Proposal: Moving `status` dir as a separated repo

### ISSUE THREAD

**Issue by Zeioth** [AstroNvim/AstroNvim#2181]
### Is your feature related to a problem?

As part of taking complexity out of the distro directory.

### Describe the new feature

`status` dir as a separated git repository, PR to the heirline project, or a combination of both.

### Additional context

I've seen you guys are in process of moving stuff out of the `astronvim` directory, which I think is a great idea! I just wrote [this ticket](https://github.com/rebelot/heirline.nvim/issues/162) on heirline and then I realized it might be of your interest, or maybe already in your plans.

Have you considered making `status` dir a separated repo like `AstroHeirlineComponents`, or PR the components that are distro independent into the heirline project? This would benefit all neovim users, not having to create their own components from scratch (unless they want to).

**Comment by mehalter** [comment]
https://github.com/AstroNvim/astroui

This is still reliant on [astrocore](https://github.com/AstroNvim/astrocore) which is out of scope of our project to support :)
