### ISSUE TITLE
Put the (vim-)detected filetype when quering for icon

### ISSUE THREAD

**Issue by Tal500** [AstroNvim/AstroNvim#2187]
### Is your feature related to a problem?

I use the details in https://neovim.io/doc/user/filetype.html for setting up custom filetypes in nvim configurations. For example, I have this following line in my `.vimrc`:
```{vimscript}
au! BufNewFile,BufRead * if expand('%:t') == '.bashrc_custom' | set ft=sh | endif
```
that basically says that every file with the name '.bashrc_custom' should be treated as filetype of "sh".

While syntax highlighting works, the automatic icon detection is not working.

Additionally, I think that the `null-ls` plugin doesn't process the custom file type given.

### Describe the new feature

In case that the filetype is detected in the buffer by neovim usual detection, give this filetype to the relevant plugins (`nvim-web-devicons`, `null-ls`, etc.).

For example, it can be easily given to `nvim-web-devicons` by using the function [`get_icon_by_filetype`](https://github.com/nvim-tree/nvim-web-devicons#getting-icons-by-filetype) instead(or in addition) to the one appears in https://github.com/AstroNvim/AstroNvim/blob/d749be33f6ba59c59c13f8b0d566c0ee8316ccc1/lua/astronvim/utils/status/provider.lua#L407C1-L410

**Comment by mehalter** [comment]
This is definitely a bug :) This is resolves on `nightly` now! Will be released tomorrow!

**Comment by Tal500** [comment]
> This is definitely a bug :) This is resolves on `nightly` now! Will be released tomorrow!

Thanks for the super quick reply!
I wonder also about the following corner case:
In your fix, you first look for result of "get_icon by filename", and as a fallback use the `get_icon_by_filetype`. It might be tricky a little bit, but shouldn't you prioritize filetype first? (I mean only in the case that the filetype isn't null) What I mean explicitly is that if the user configured one thing(i.e. `filetype` isn't empty), and "get_icon by filename" deciding otherwise, and `get_icon_by_filetype` supports icon of `filetype`, then the user configuration is prioritized over the filename.

**Comment by mehalter** [comment]
In this case the user will want to override the filename or extension. In this case we definitely want to move from more specific to less specific in the fallback order and in this case, an icon for a specific filename is more granular than the icon for the filetype. In the setup the user can configure icons for filetype, filename, and extension :)

**Comment by mehalter** [comment]
Just for anyone referencing back to this (mainly me probably) I did some looking around to see how other status line libraries do this and they seem to also fall into the same approach I described here:

Lualine: https://github.com/nvim-lualine/lualine.nvim/blob/master/lua/lualine/components/filetype.lua#L34C7-L37

Also I did a bit of optimization and code clean up that will be released in the next version. mainly just code cleanup and doesn't change any of the behavior
