### ISSUE TITLE
mason-lspconfig configuration for r_language_server is ignored

### ISSUE THREAD

**Issue by klmr** [AstroNvim/AstroNvim#2201]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Red Hat Enterprise Linux release 8.6 (Ootpa)

### Terminal/GUI

iTerm2 (connected via SSH)

## AstroNvim
  - INFO: AstroNvim Version: unknown
  - INFO: Neovim Version: v0.8.3
  - OK: Using stable Neovim >= 0.8.0
  - OK: `git` is installed: Used for core functionality such as updater and plugin management
  - OK: `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
  - WARNING: `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
  - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
  - WARNING: `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
  - OK: `btm` is installed: Used for mappings to pull up system monitor (Optional)
  - OK: `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

> ⚠️ **Note:** I have no idea why the AstroNvim version is shown as “unknown”. Before running the command `:checkhealth astronvim` I completely erased my AstroNvim installation and reinstalled it from scratch (today, 2023-08-03). I also deleted the ~/.local/share/nvim` folder and my custom settings. This is a fresh, vanilla AstroNvim setup.

Since recently<sup>1</sup>, when using AstroNvim, the R language server fails to start. By contrast, when using Mason + mason-lspconfig + lspconfig directly (instead of via AstroNvim), there’s no issue.

More specifically, the R language server fails to start because the launch command is not configured correctly; it is using the [default lspconfig configuration](https://github.com/neovim/nvim-lspconfig/blob/a59d74e12340242c0735666fb2e91afdbe6f2496/lua/lspconfig/server_configurations/r_language_server.lua#L5) rather than the (required) [mason-lspconfig configuration](https://github.com/williamboman/mason-lspconfig.nvim/blob/e86a4c84ff35240639643ffed56ee1c4d55f538e/lua/mason-lspconfig/server_configurations/r_language_server/init.lua), which redefines the `cmd` option of the language server.

In particular, plain lspconfig uses the command `{ 'R', '--slave', '-e', 'languageserver::run()' }` to run the language server, which fails as expected, since this requires the R package ‘languageserver’ to be installed globally (it isn’t, and there are reasons why this is not a good solution). By contrast, mason-lspconfig has a self-contained installation of the required package, and performs additional setup via a wrapper utility `r-languageserver`. This never gets called, which can be verified by editing it and adding debug output.

---

<sup>1</sup> I can’t recall when exactly the issue started or what might have caused it. All I can say is that this used to work, but now it doesn’t.

### Steps to Reproduce

1. [Install R](https://cloud.r-project.org/) (apologies!…)
2. Launch AstroNvim
3. `:LspInstall r_language_server`
4. `:e new.r`

This causes an error dialog with the following message to show:

> Client 2 quit with exit code 1 and signal 0

The LSP log contains the following entries:

```
[START][2023-08-03 16:47:55] LSP logging initiated
[ERROR][2023-08-03 16:47:55] .../vim/lsp/rpc.lua:733  "rpc" "/path/to/bin/R"  "stderr"  "Error in loadNamespace(x) : there is no package called ‘languageserver’\nCalls: loadNamespace -> withRestarts -> withOneRestart -> do
```

Restarting Nvim between steps 2, 3 and 4 doesn’t change the outcome. Nor does installing the language server via 

### Expected behavior

The R language server launches successfully and without error.

### Additional Context

After opening an R file, `:LspInfo` shows the following configuration:

```
Config: r_language_server
filetypes:         r, rmd
root directory:    /my/home/folder
cmd:               /path/to/bin/R --slave -e languageserver::run()
cmd is executable: true
autostart:         true
custom handlers:

Configured servers list: r_language_server
```

Based on the observed behaviour, my best guess for why this happens is that the plugins are initialised in the wrong order. However, `:Lazy profile` seems to indicate that the initialisation order is actually correct (mason.nvim › mason-lspconfig.nvim › nvim-lspconfig):

![lazy.nvim profile](https://github.com/AstroNvim/AstroNvim/assets/38931/2f61d102-4dd8-4ff1-8a89-73bc531c919e)

I can see that [the correct r-languageserver wrapper for mason](https://github.com/mason-org/r-languageserver) was installed in `~/.local/share/nvim/mason/packages`.

**Comment by mehalter** [comment]
Thanks for such a detailed report! This is some great information and I was able to find where we are accidentally overwriting this. I was trying to cleverly return all of the LSP details to the user but this does accidentally overwrite `mason-lspconfig` stuff inadvertently. I have pushed a fix for this on the nightly branch. Could you try out the `nightly` channel and see if that resolves the issue?

**Comment by klmr** [comment]
Brilliant, that fixes it! Thanks for this unexpectedly quick response.
