### ISSUE TITLE
After disabling Heirilne, related buffer keymaps are still registered

### ISSUE THREAD

**Issue by fynnfluegge** [AstroNvim/AstroNvim#2205]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

nacOS 13.4

### Terminal/GUI

Alacritty and iterm2

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: v3.35.0
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

When disabling the default plugin `heirline` in `user/plugins/core.lua` some `heirline` related keymappings are still registered and can be found in `which-key` and `Telescope`.

### Steps to Reproduce

1. Go to `user/plugins/core.lua` and insert  `{ "rebelot/heirline.nvim", enabled = false }`,
2. Hit `<Space>bd`
3.  Throws:
```lua
E5108: Error executing lua: ...ynn/.config/nvim/lua/astronvim/utils/status/heirline.lua:94: module 'heirline' not found:
        no field package.preload['heirline']
cache_loader: module heirline not found
cache_loader_lib: module heirline not found
        no file './heirline.lua'
        no file '/usr/local/share/luajit-2.1.0-beta3/heirline.lua'
        no file '/usr/local/share/lua/5.1/heirline.lua'
        no file '/usr/local/share/lua/5.1/heirline/init.lua'
        no file './heirline.so'
        no file '/usr/local/lib/lua/5.1/heirline.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
```

### Expected behavior

`heirline` related keymappings should be unmapped.

It would be great if the mappings registered in `lua/astronvim/mappings.lua` like
```lua
maps.n["<leader>bd"] = {
  function()
    require("astronvim.utils.status.heirline").buffer_picker(
      function(bufnr) require("astronvim.utils.buffer").close(bufnr) end
    )
  end,
  desc = "Close buffer from tabline",
}
```
could be unmapped, based on disabled plugins.

### Additional Context

I am facing this, since I have serious issues with `heirline`. Scrolling in buffers was getting unbearably laggy with `heirline`. I am curious if anyone else facing this issue. I consider to open a separate issue for this. I disabled any other custom plugin which could also cause this, but only `heirline` was the malefactor.
Currently I am using `bufferline` and `lualine` as a subsitute for `heirline` which works perfectly for me.

**Comment by mehalter** [comment]
This should be resolved in the nightly channel.

**Comment by mehalter** [comment]
Also related to your additional context I can't replicate the behavior you are describing. I have opened some pretty large files and haven't had any issues with lag related to heirline. My guess is this is also coming from the signcolumn and not the bufferline/statusline. So you could try just disabling our custom signcolumn and using the default as well and see if that works better on your machine.

Another good debug method is to run `:lua require("heirline").timeit()` to see how long each component takes to render. The statuscolumn should be quite fast. Even in a multi-thousand line file, I'm getting load times of <0.05ms but that could very much depend on machine I suppose

**Comment by fynnfluegge** [comment]
> Also related to your additional context I can't replicate the behavior you are describing. I have opened some pretty large files and haven't had any issues with lag related to heirline. My guess is this is also coming from the signcolumn and not the bufferline/statusline. So you could try just disabling our custom signcolumn and using the default as well and see if that works better on your machine.
> 
> Another good debug method is to run `:lua require("heirline").timeit()` to see how long each component takes to render. The statuscolumn should be quite fast. Even in a multi-thousand line file, I'm getting load times of <0.05ms but that could very much depend on machine I suppose

Thanks for the detailed explanation! I got also around 0.05ms for `heirline`. Will take a deeper look later, but however, currently I am also happy with `bufferline` and `lualine` and seems it is not a common issue
