### ISSUE TITLE
Cant override DAP settings

### ISSUE THREAD

**Issue by Ykrowa** [AstroNvim/AstroNvim#2210]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

ubuntu 20.04

### Terminal/GUI

terminal

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: v3.36.0
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

I have clone astronvim to ~/.config/nvim, made the folder "user", inside this folder i have placed "init.lua" file with:

```
return {
  dap = {
    adapters = {
      python = {
        type = "executable",
        command = "/usr/bin/python",
        args = { "-m", "debugpy.adapter" },
      },
    },
    configurations = {
      python = {
        {
          -- The first three options are required by nvim-dap
          type = "python", -- the type here established the link to the adapter definition: `dap.adapters.python`
          request = "launch",
          name = "Launch file",
          program = "${file}", -- This configuration will launch the current file if used.
          pythonPath = "/usr/bin/python",
        },
      },
    },
  },
}
```

but when i start debugging python files, then still see that DAP from init lua not used because sys.executable returns: /home/ykrowwa/.local/share/nvim/mason/packages/debugpy/venv/bin/python

### Steps to Reproduce

1. create user folder.
2. create init.lua
3. place content from description of the bug
4. start python script with F5 or <leader >dc
5. in debug console write import sys, sys.executable
6. see wrong python executable path

**Comment by mehalter** [comment]
Because you have `debugpy` installed through Mason, `mason-nvim-dap` is doing the setting up here. You can either (1) do your approach and not install `debugpy` from Mason or (2) configure how `mason-nvim-dap.nvim` sets up the deugger as is shown in their [Documentation](https://github.com/jay-babu/mason-nvim-dap.nvim#advanced-customization). Here is an example `user/init.lua` file that does what you want:

```lua
return {
  plugins = {
    {
      "jay-babu/mason-nvim-dap.nvim",
      opts = {
        handlers = {
          python = function(config)
            config.adapters = {
              type = "executable",
              command = "/usr/bin/python",
              args = {
                "-m",
                "debugpy.adapter",
              },
            }
            require("mason-nvim-dap").default_setup(config)
          end,
        },
      },
    },
  },
}
```

**Comment by eerison** [comment]
Hello @mehalter Sorry to raise up this.

But I am struggle to override the current configuration, in my case I want to overwrite php's config

I tried to do like it is described here: https://docs.astronvim.com/recipes/dap/ But it does not work :'(

now I am trying to do this

dap.lua

```lua
return {
  plugins = {
    {
      "jay-babu/mason-nvim-dap.nvim",
      opts = {
        handlers = {
          php = function(config)
            config.adapters = {
              type = "executable",
              command = "node",
              args = { os.getenv "HOME" .. "/Documents/projects/vscode-php-debug/out/phpDebug.js" },
            }

            -- config.configurations = {
            --   {
            --     type = "php",
            --     request = "launch",
            --     name = "Listen for Xdebug - Erison test",
            --     port = 9003,
            --     pathMappings = {
            --       ["/app"] = "${workspaceFolder}",
            --     },
            --   },
            -- }
            require("mason-nvim-dap").default_setup(config)
          end,
        },
      },
    },
  },
}
```

But I am getting this error
<img width="478" alt="Screenshot 2023-11-12 at 11 30 49" src="https://github.com/AstroNvim/AstroNvim/assets/6358755/9fd6a998-49c3-4519-b0e8-f25e720c1328">


I also tried to do like the example in description

```lua
return {
  dap = {
    adapters = {
      python = {
        type = "executable",
        command = "/usr/bin/python",
        args = { "-m", "debugpy.adapter" },
      },
    },
    configurations = {
      python = {
        {
          -- The first three options are required by nvim-dap
          type = "python", -- the type here established the link to the adapter definition: `dap.adapters.python`
          request = "launch",
          name = "Launch file",
          program = "${file}", -- This configuration will launch the current file if used.
          pythonPath = "/usr/bin/python",
        },
      },
    },
  },
}
```

Note: I changed for php configs ofc 😄 


But none of them worked :'(

**Comment by eerison** [comment]
if I copy and past the example here
https://docs.astronvim.com/recipes/dap/

I get this error 

<img width="1088" alt="Screenshot 2023-11-12 at 11 40 42" src="https://github.com/AstroNvim/AstroNvim/assets/6358755/8b2df197-94b4-48b4-895c-a5ea9f98eb1a">

**Comment by mehalter** [comment]
In your `plugins/dap.lua` file you simply need to put:

```lua
return {
      "jay-babu/mason-nvim-dap.nvim",
      opts = {
        handlers = {
          php = function(config)
            config.adapters = {
              type = "executable",
              command = "node",
              args = { os.getenv "HOME" .. "/Documents/projects/vscode-php-debug/out/phpDebug.js" },
            }

            -- config.configurations = {
            --   {
            --     type = "php",
            --     request = "launch",
            --     name = "Listen for Xdebug - Erison test",
            --     port = 9003,
            --     pathMappings = {
            --       ["/app"] = "${workspaceFolder}",
            --     },
            --   },
            -- }
            require("mason-nvim-dap").default_setup(config)
          end,
        },
      },
    }
```

**Comment by eerison** [comment]
> In your `plugins/dap.lua` file you simply need to put:
> 
> ```lua
> return {
>       "jay-babu/mason-nvim-dap.nvim",
>       opts = {
>         handlers = {
>           php = function(config)
>             config.adapters = {
>               type = "executable",
>               command = "node",
>               args = { os.getenv "HOME" .. "/Documents/projects/vscode-php-debug/out/phpDebug.js" },
>             }
> 
>             -- config.configurations = {
>             --   {
>             --     type = "php",
>             --     request = "launch",
>             --     name = "Listen for Xdebug - Erison test",
>             --     port = 9003,
>             --     pathMappings = {
>             --       ["/app"] = "${workspaceFolder}",
>             --     },
>             --   },
>             -- }
>             require("mason-nvim-dap").default_setup(config)
>           end,
>         },
>       },
>     }
> ```

thank you so much, it worked <3
