### ISSUE TITLE
Add key_group to replace or remove group of core mappings easly

### ISSUE THREAD

**Issue by t1gu1** [AstroNvim/AstroNvim#2211]
### Is your feature related to a problem?

*group = first key after the leader of a mapping.

If we want to remove a group of keys of the core mappings we have to do that:

```lua
    ["<leader>fw"] = false,
    ["<leader>fW"] = false,
    ["<leader>ff"] = false,
    ["<leader>fb"] = false,
    ["<leader>fh"] = false,
    ["<leader>fm"] = false,
    ["<leader>fo"] = false,
    ["<leader>fc"] = false,
    ["<leader>fF"] = false,
    ["<leader>fn"] = false,
    ["<leader>fk"] = false,
    ["<leader>fa"] = false,
    ["<leader>fr"] = false,
    ["<leader>ft"] = false,
    ["<leader>fC"] = false,
    ["<leader>f'"] = false,
    ["<leader>f<CR>"] = false,
```

If we want to replace a group of keys of the core mappings, we have to do the same thing of a loop like that in the user/mappings.lua:

P.S. Here I replace all `<leader>f something` by `<leader>s something`

```lua
return function(mappings)
  local new_mapping = {
    n = {...},
    t = {...},
    v = {...},
  }

  -- Disable all <leader>f... commands
for key, val in pairs(mappings.n) do
    if key:find "<leader>f" and key ~= "<leader>f" then
      local new_key = key:gsub("<leader>f", "<leader>s") -- REPLACE HERE
      new_mapping.n[new_key] = val
      new_mapping.n[key] = false
    end
  end

  -- Merge old mappings with the new mappings
  for _k, mode in pairs { "n", "t", "v" } do
    for key, val in pairs(new_mapping[mode]) do
      mappings[mode][key] = val
    end
  end

  return mappings
```

It's a lot for a small change for the desired result and it's not that much user friendly.

### Describe the new feature

The solution should consist to create key groups maybe in that file: https://github.com/AstroNvim/AstroNvim/blob/main/lua/astronvim/mappings.lua

Something like that:
```lua
keymap_group: {
  search = "f",
  packages = "p",
  lsp = "l",
  ui = "u",
  buffers = "b",
  -- ... etc
}
```

And replace this (In that file: https://github.com/AstroNvim/AstroNvim/blob/main/lua/astronvim/mappings.lua)

```lua
maps.n["<leader>fb"] = { function() require("telescope.builtin").buffers() end, desc = "Find buffers" }
maps.n["<leader>fc"] = { function() require("telescope.builtin").grep_string() end, desc = "Find word under cursor" }
maps.n["<leader>fC"] = { function() require("telescope.builtin").commands() end, desc = "Find commands" }
... -- <- Other keys in the group
```

By something like that:
```lua
if(keymap_group.search ~= false) then
  maps.n["<leader>"..keymap_group.search.."b"] = { function() require("telescope.builtin").buffers() end, desc =   "Find buffers" }
  maps.n["<leader>"..keymap_group.search.."c"] = { function() require("telescope.builtin").grep_string() end, desc = "Find word under cursor" }
  maps.n["<leader>"..keymap_group.search.."C"] = { function() require("telescope.builtin").commands() end, desc = "Find commands" }
... -- <- Other keys in the group
end
```

---

User should be able to modify the keymap_group values.

### Additional context

This will provide a fast way to remove a group of core mappings keys or change the "group/first key after the leader" of it.

**Comment by mehalter** [comment]
This approach has a couple concerns. First this adds a level of abstraction that I think AstroNvim would like to avoid. Also this does not fully generalize in a nice way to all parts of how the mapping table works. If the user adds oflther mappings or AstroCommunity adds more mappings this wouldn't take these into consideration.

I've thought about this a lot this weekend and I don't think we want to move towards this type of feature. The way you have it in the code you have linked is a very general approach that and will work for all mappings no matter how they are added before getting to your user configuration. It may not be as user friendly but I think that's alright in this case.

Thanks for the recommendation!

**Comment by mehalter** [comment]
I think the `for` loop approach is both succinct and very human readable and therefore doesn't need to be abstracted away. I do think you could simplify your approach a bit using an existing utility:

```lua
return function(mappings)
  -- convert `<leader>f` to `<leader>s`
  for key, val in pairs(mappings.n) do
    if key:gmatch "^<leader>f" then
      mappings.n[key] = false
      mappings.n[key:gsub("^<leader>f", "<leader>s")] = val
    end
  end

  return require("astronvim.utils").extend_tbl(mappings, {
    -- the rest of your mappings just go here like normal...
    n = {
      --- ...
    },
    t = {
      --- ...
    },
    v = {
      --- ...
    },
  })
end
```

This loop here for replacing the menu title is very use case specific and should be implemented in a user configuration without abstraction because the process of replacing 2 menu titles requires modifying the for loop itself to do both of them in the single pass. If we abstract this away there will be significant performance issues as well as this unnecessary abstraction. It's good for the user to have a decent understanding of the lua in this case so that they can do whatever they want rather than us locking them into some API that we decide to provide.

**Comment by t1gu1** [comment]
You make me learn things today. 💯 

Thanks mehalter Sensei!
