### ISSUE TITLE
C-n, C-p, C-j, C-k do not work on the telescope.

### ISSUE THREAD

**Issue by chillin2** [AstroNvim/AstroNvim#2212]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

WSL Ubuntu 22.04.2 LTS.

### Terminal/GUI

fish

### AstroNvim Health

 - AstroNvim Version: v3.36.0
 - Neovim Version: v0.9.0-dev-1047+gf0f27e9ae
 - WARNING Neovim nightly is not officially supported and may have breaking changes
 - OK git is installed: Used for core functionality such as updater and plugin management
 - WARNING xdg-open/open/explorer is not installed: Used for gx mapping for opening files with system opener (Optional)
 - WARNING lazygit is not installed: Used for mappings to pull up git TUI (Optional)
 - OK node is installed: Used for mappings to pull up node REPL (Optional)
 - WARNING gdu is not installed: Used for mappings to pull up disk usage analyzer (Optional)
 - WARNING btm is not installed: Used for mappings to pull up system monitor (Optional)
 - OK python3 is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

in telescope.lua 
        mappings = {
          i = {
            ["<C-n>"] = actions.cycle_history_next,
            ["<C-p>"] = actions.cycle_history_prev,
            ["<C-j>"] = actions.move_selection_next,
            ["<C-k>"] = actions.move_selection_previous,
          },

This code doesn't work. If I comment out this code, C-n, C-p works fine. My environment is Wsl Ubuntu 22.04.2 LTS.

### Steps to Reproduce

1. <leader>ff
2. C-n, C-p, C-j, C-k

### Expected behavior

scroll select

**Comment by mehalter** [comment]
I'm no sure what happened to you `telescope.lua` file but the code you pasted is not what's in AstroNvim

https://github.com/AstroNvim/AstroNvim/blob/main/lua/plugins/telescope.lua#L26-L29

You probably want to make sure you haven't accidentally changed the core code

**Comment by mehalter** [comment]
I just did some sanity checking and it appears these are working and something is going on in your configuration or local clone of the repository. Use `git status` to see what has happened and let me know if you can't figure it out. I can try to help as well.

I am going to go ahead and close this since it's not really a bug, but if you comment back here I will respond.

**Comment by chillin2** [comment]
It's weird on Github. My current code status is this, and only C-n and C-p work when I comment them out. Just check it out...

![telescope-lua](https://github.com/AstroNvim/AstroNvim/assets/19788387/056ee59a-0ae0-4409-89fc-b63ae470abcb)

Steps to Reproduce
1. leader +f + f
2. C-n, C-p, C-j, C-k

**Comment by mehalter** [comment]
In our default configuration `ctrl-n` and `ctrl-p` are used to cycle through history and not up/down the menu which is probably why you see the behavior changing when you comment them out. As for the `<C-j>` and `<C-k>` it could be that your terminal is overriding those bindings and they are never reaching neovim? If you open an empty buffer and go into insert mode and run `<c-v><c-k>` do you see `^K` get typed into the buffer? that could help debug if your terminal is eating those bindings

**Comment by chillin2** [comment]
@mehalter The problem was that it was assigned to the up and down scroll keys of the terminal. Thank you.
