### ISSUE TITLE
Plan moving forward with `null-ls` being archived

### ISSUE THREAD

**Issue by colorsakura** [AstroNvim/AstroNvim#2217]
### Describe the new feature

https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1621

**Comment by mehalter** [comment]
Thanks for opening an issue with this! This has been something on our radar for a few months. We don't have any immediate plans to migrate away from `null-ls` for at least some time. Feel free to not use `null-ls` if you want and set up something else in your configuration.

It might end up just being something we just remove in v4. But null-ls will continue working in the same manner for the time being

**Comment by mehalter** [comment]
This is the future proof method for what we want to move to: https://github.com/neovim/neovim/pull/24338

I'm leaning towards dropping out of the box linter/formatter that aren't LSP based from AstroNvim core until this is made.

**Comment by mehalter** [comment]
Ok here is the current tentative plan for v4 that is hopefully releasing along side Neovim v0.10:

1. If Neovim 0.10 has no API changes that break null-ls then we will keep `null-ls` and `mason-null-ls` for out of the box experience for v4 even though it is not actively maintained, it won't be getting worse. We don't officially support neovim nightly, so I'm not concerned if neovim v0.11 nightly messes up null-ls.
2. If Neovim 0.10 does have API changes that break null-ls, then we will look drop null-ls and provide no external linter/formatter support out of the box and users can look into configuring their own plugins to fit their needs.

**Comment by mehalter** [comment]
For now, I'm going to close this issue since there is no actionable items currently and I will pin it to the issues for people to easily find it.

**Comment by eagle-tex** [comment]
@mehalter 
How about this one?
https://github.com/nvimtools/none-ls.nvim

**Comment by mehalter** [comment]
@eagle-tex this is currently used in v4 :)

**Comment by fynnfluegge** [comment]
Hi @mehalter, Folke just moved in LazyVim distro to [conform](https://github.com/stevearc/conform.nvim) as a formatter and [nvim-lint](https://github.com/mfussenegger/nvim-lint) as a linter, maybe worth to consider also :)

**Comment by mehalter** [comment]
@fynnfluegge this is not a direction we want to go it, but it's great to see that LazyVim has done it! For now we will stick with `none-ls`
