### ISSUE TITLE
Error on force close last buffer using mapping "<leader>C"

### ISSUE THREAD

**Issue by RayJameson** [AstroNvim/AstroNvim#2219]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Linux alpine (Docker)

### Terminal/GUI

wezterm

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim
- AstroNvim Version: v3.36.1
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK git is installed: Used for core functionality such as updater and plugin management
- WARNING xdg-open/open/explorer is not installed: Used for gx mapping for opening files with system opener (Optional)
- OK lazygit is installed: Used for mappings to pull up git TUI (Optional)
- OK node is installed: Used for mappings to pull up node REPL (Optional)
- WARNING gdu is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK btm is installed: Used for mappings to pull up system monitor (Optional)
- OK python is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

I think there is a bug in this method, couldn't find where exactly

https://github.com/AstroNvim/AstroNvim/blob/26aedacec6a3d2aeba44c365360b3ba3637b20ca/lua/astronvim/utils/buffer.lua#L138-L161

### Steps to Reproduce
1. Open any file
2. press `<leader>C`
3. error

### Expected behavior

close buffer without error

### Screenshots

<img width="584" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/67468725/095b51c0-b703-433b-8342-c3155cde596b">

<img width="1728" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/67468725/c69ad839-551e-4a24-b367-623995f9fa3e">

### Additional Context

Original discussion https://discord.com/channels/939594913560031363/1141825733862375464

**Comment by mehalter** [comment]
Should be resolved in the current nightly! Thanks for reporting :)
