### ISSUE TITLE
Remove or change <C-x> mapping in visual mode

### ISSUE THREAD

**Issue by RayJameson** [AstroNvim/AstroNvim#2225]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

13.4.1 (22F82)

### Terminal/GUI

wezterm

### AstroNvim Health

very healthy

### Describe the bug

I think this line should be removed https://github.com/AstroNvim/AstroNvim/blob/bb7837f1cc379e9b3c9ddbceaa41e2fc3e9d8ea2/lua/plugins/cmp.lua#L12

Because this feature is very niche, here is an example in the plugin repo discussing this L3MON4D3/LuaSnip#884
Not a straightforward thing to do. I think if someone wants this feature - they should add it themself. That was a first argument, but not the reason I think it should be removed (or at least changed) - by default `<C-x>` in visual mode decrement numbers, and this config option remove this behavior.

### Steps to Reproduce

1. paste some lines of numbers
2. visual block mode over them
3. `<C-x>`
4. congrats, your numbers are gone

### Expected behavior

numbers not gone, but decremented

### Additional Context

discussions are locked and there are only two templates, blame it on uzaaft that I created it in bug template :D
https://discord.com/channels/939594913560031363/939857762043695165/1142560634312081549

**Comment by mehalter** [comment]
Im down for that! Want to open a PR?

**Comment by RayJameson** [comment]
sure!

**Comment by RayJameson** [comment]
Are you onboard with removing it or do you have some mapping in mind?

**Comment by mehalter** [comment]
I'm fine with just removing it.
