### ISSUE TITLE
Failed to run 'config' for mason-nvim-dap.nvim

### ISSUE THREAD

**Issue by Ma-Mo025** [AstroNvim/AstroNvim#2229]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Windows 11 Home 22621.1848

### Terminal/GUI

Powershell on Terminal

### AstroNvim Health

 astronvim: require("astronvim.health").check()
  
   AstroNvim
   - AstroNvim Version: v3.36.3
   - Neovim Version: v0.9.1
   - OK Using stable Neovim >= 0.8.0
   - OK git is installed: Used for core functionality such as updater and plugin management
   - OK explorer is installed: Used for gx mapping for opening files with system opener (Optional)
   - WARNING lazygit is not installed: Used for mappings to pull up git TUI (Optional)
  11   - OK node is installed: Used for mappings to pull up node REPL (Optional)
  12   - WARNING gdu is not installed: Used for mappings to pull up disk usage analyzer (Optional)
  13   - WARNING btm is not installed: Used for mappings to pull up system monitor (Optional)
  14   - OK python is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

After loading a file, this error message appears from lazy.nvim
```
Failed to run 'config' for mason-nvim-dap.nvim
...-dap.nvim/lua/mason-nvim-dap/mappings/configurations.lua:99: module 'dap.utils' not found:
    no field package.preload['dap.utils']
cache_loader: module dap.utils not found
cache_loader_lib: module dap.utils not found
    no file '.\dap\utils.lua'
    no file 'C:\Program Files\Neovim\bin\lua\dap\utils.lua'
    no file 'C:\Program Files\Neovim\bin\lua\dap\utils\init.lua'
    no file '.\dap\utils.dll'
    no file 'C:\Program Files\Neovim\bin\dap\utils.dll'
    no file 'C:\Program Files\Neovim\bin\loadall.dll'
    no file '.\dap.dll'
    no file 'C:\Program Files\Neovim\bin\dap.dll'
    no file 'C:\Program Files\Neovim\bin\loadall.dll'
  
# stacktrace:
- mason-nvim-dap.nvim\lua\mason-nvim-dap\mappings\configurations.lua:99
- mason-nvim-dap.nvim\lua\mason-nvim-dap\init.lua:45 in fn
- mason.nvim\lua\mason-core\optional.lua:101 in if_present
- mason-nvim-dap.nvim\lua\mason-nvim-dap\init.lua:41 in fn
- mason.nvim\lua\mason-core\functional\list.lua:98 in each
- mason-nvim-dap.nvim\lua\mason-nvim-dap\init.lua:61 in setup_handlers
- mason-nvim-dap.nvim\lua\mason-nvim-dap\init.lua:87 in setup
- ~/AppData/Local/nvim/lua/plugins/configs/mason.lua:24 in config
- mason-lspconfig.nvim\lua\mason-lspconfig\init.lua:1
- ~/AppData/Local/nvim/lua/plugins/configs/mason-lspconfig.lua:2 in config
- ~/AppData/Local/nvim/lua/astronvim/utils/init.lua:145
```

### Steps to Reproduce

1. Open a file

### Expected behavior

Clear load without the error showing up

### Screenshots

![Screenshot 2023-08-20 171406](https://github.com/AstroNvim/AstroNvim/assets/65283337/8302b37b-18c0-439b-a651-c1da78151351)

### Additional Context

Nvim is installed using winget (I don't know if this may be of help).
`~/AppData/Local/nvim/` is used as config dir

**Comment by mehalter** [comment]
Dap is not enabled by default for Windows. If you add it in your user configuration it will be up to you to maintain it.

**Comment by mehalter** [comment]
Here is documentation to enable it: https://astronvim.com/Recipes/dap#enable-plugins-on-windows

**Comment by XxiuNan** [comment]
but now the link is invalid

**Comment by mehalter** [comment]
@XxiuNan if you follow the link it describes how to go to the new link and also provides the link to it: https://docs.astronvim.com/Recipes/dap#enable-plugins-on-windows
