### ISSUE TITLE
Supply a function instead of table for user's `mappings` (inlc. lsp)

### ISSUE THREAD

**Issue by pavkam** [AstroNvim/AstroNvim#2235]
### Is your feature related to a problem?

I love AstroNvim, you did an amazing job! 

One thing that bothers my brain though is the key mappings. I need to remap some of them to something else. I did that using `mappings.lua`  (see https://github.com/pavkam/dotfiles/blob/main/.config/nvim/lua/user/mappings.lua) as an example. But it is very cumbersome.

What I want in may cases is to simply remap everything under `<leader>l...` to `<leader>s...`. The sample in the docs shows that: https://astronvim.com/Recipes/mappings#disable-telescope-lsp-mappings.

I want to do that in `lsp/mappings.lua` if possible, but **I cannot return a function**, it needs to be a table, which makes this impossible.

More, I tried to add a function into `init.lua`:
```
    lsp = {
        mappings = function(maps)
            maps.n["<leader>li"] = nil
        end,
   }
```

But get an error:
```
Error executing vim.schedule lua callback: /Users/alex/.config/nvim/lua/astronvim/utils/init.lua:290: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
	[C]: in function 'pairs'
	/Users/alex/.config/nvim/lua/astronvim/utils/init.lua:290: in function 'set_mappings'
	/Users/alex/.config/nvim/lua/astronvim/utils/lsp.lua:371: in function 'on_attach'
	...ocal/share/nvim/lazy/null-ls.nvim/lua/null-ls/client.lua:134: in function 'setup_buffer'
	...ocal/share/nvim/lazy/null-ls.nvim/lua/null-ls/client.lua:84: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

I added an empty `lsp/mapping.lua` file with an empty table, which makes it not complain, but the code in `init` does not run anymore.

Are the docs incorrect? And could we get back the ability to get a function? I would really love to be able to adjust mappings without having to rewrite them all by copy-pasting the same code from AstroNvim mappings but with different keys.

### Describe the new feature

- Add an ability to remap mappings that are supplied by AstroNvim to different keys (this would cover 90%) of my needs,
- Ideally, access to the map table before it is submitted to `nvim` would allow users to customize `desc`, `keys` and anything else (this would cover 100%).

### Additional context

Honestly, this is the biggest issue for me as my keybindings are very tuned to how I think (and probably not just me). I am anxious to learn bindings which could change under me so I need to be 100%, and that is only possible with my customizations.

**Comment by pavkam** [comment]
Looking at the lua code of AstroNvim, the `user_opts` supports a function but that doesn't seem to work for me so maybe there's an issue or am I doing something wrong?

Also, if I want to extend `lsp` mappings it would be beneficial to obtain the `buffer number` and `client` in my code so that I can conditionally attach mappings that I want. 

Otherwise, I have no idea if attaching "go to implementation" would work in a given buffer.

**Comment by mehalter** [comment]
This is supported, here is the documentation on the possible override formats: https://astronvim.com/Configuration/override_formats#override-table

**Comment by mehalter** [comment]
Also in v3 you can get access to the client and bufnr by overriding your on attach function either for all language servers or for each individual language server. Having access to this in the lsp mappings is actually a feature in the upcoming v4 release

**Comment by pavkam** [comment]
> Also in v3 you can get access to the client and bufnr by overriding your on attach function either for all language servers or for each individual language server. Having access to this in the lsp mappings is actually a feature in the upcoming v4 release

Thanks @mehalter, I was hoping there's a way for me to avoid doing that at lsp level. v4 seems promising, if all keymaps can be done in one place.

I will also try again by providing a function instead of a table, though I tried a few times and that did not work.
