### ISSUE TITLE
Automatically highlight all occurrences of the selected text in visual mode

### ISSUE THREAD

**Issue by TahaBinhuraib** [AstroNvim/AstroNvim#2240]
### Describe the new feature

Automatically highlight all occurrences of the selected text in visual mode. This feature is super in vscode, I was wondering if there is a similar plugin for neovim that could be added to Astrovim

**Comment by mehalter** [comment]
We currently do highlighting of the current symbol under the cursor when holding the cursor as provided by language servers. I don't think we want to make this the same for visual mode selections. I also haven't heard of any plugins to achieve this. Sorry! If you find a solution you like please feel free to share here for helping future users who may have the same question

**Comment by oryband** [comment]
On a side note - @mehalter Is there a way to turn this feature off? It intervenes with https://github.com/RRethy/vim-illuminate and astrocommunity's https://github.com/AstroNvim/astrocommunity/tree/main/lua/astrocommunity/bars-and-lines/vim-illuminate

**Comment by mehalter** [comment]
@oryband that is the simplest solution. I did comment an updated snippet for the `on_attach` function as it is a bit outdated.
