### ISSUE TITLE
Filetype based lazy loading not efficient

### ISSUE THREAD

**Issue by meijieru** [AstroNvim/AstroNvim#2242]
### Is your feature related to a problem?

Currently, the filetype based lazy loading slow up the start when directly open a file.

An example for `python`.
```lua
  { import = "astrocommunity.test.neotest" },
```
![image](https://github.com/AstroNvim/AstroNvim/assets/9511136/ffc4d489-cb16-4b97-93bb-0764aeb378a7)

### Describe the new feature

Postpone the handling of the file type until after the `UIEnter` event, similar to how the `AstroFile` event functions.

**Comment by mehalter** [comment]
This actually wouldn't improve the startup time, this would simply trick the startup time calculation in lazy to just not include it in the count. But it wouldn't change the functionality or performance of anything at all since the plugin does indeed get loaded on startup (before or after UIEnter)

**Comment by mehalter** [comment]
Also for further clarification. The neotest plugin in AstroCommunity doesn't load on AstroFile anyway, it is simply loaded on filetype so it is also unrelated to that autocmd performance.

**Comment by mehalter** [comment]
If filetype based lazy loading is slow, that would be something to take up with either Lazy who handles the lazy loading or the plugin itself to improve their performance
