### ISSUE TITLE
sometimes gd(show definition of current symbol) action just disappear for unknown reason.

### ISSUE THREAD

**Issue by rick-yao** [AstroNvim/AstroNvim#2248]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 14.0

### Terminal/GUI

kitty

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.36.6
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

sometimes gd(show definition of current symbol) action just disappear for unknown reason.

### Steps to Reproduce

1. neovim in a react project
2. move cursor to last session , enter
3. open a tsx file
4. enter g, sometimes I can see 'd' action , sometimes not

### Expected behavior

gd action should be working.

### Screenshots

first photo is what i encountered, my cursor is on 'pressable' and there is no option between 'c' and 'e'. when i enter gd, nothing will happen.
<img width="1545" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/59443488/2fd035ef-4071-467b-97ca-c28c6af0248c">
second photo is when things works normally. i can see 'd' option , also pressable is highlighted in the file , when i enter gd, nvim will jump to the definition file.
<img width="1545" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/59443488/31cd8f72-3bdc-4e11-9266-70ee7e391135">

### when gd option disappeared , lsp information shows below log.
 Press q or <Esc> to close this window. Press <Tab> to view server doc.
 
 Language client log: /Users/rick/.local/state/AstroNvim/lsp.log
 Detected filetype:   typescriptreact
 
 5 client(s) attached to this buffer: 
 
 Client: tsserver (id: 1, bufnr: [3])
 	filetypes:       javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx
 	autostart:       true
 	root directory:  /Users/rick/projects/ebike-app
 	cmd:             /Users/rick/.local/share/AstroNvim/mason/bin/typescript-language-server --stdio
 
 Client: tailwindcss (id: 2, bufnr: [3])
 	filetypes:       aspnetcorerazor, astro, astro-markdown, blade, clojure, django-html, htmldjango, edge, eelixir, elixir, ejs, erb, eruby, gohtml, haml, handlebars, hbs, html, html-eex, heex, jade, leaf, liquid, markdown, mdx, mustache, njk, nunjucks, php, razor, slim, twig, css, less, postcss, sass, scss, stylus, sugarss, javascript, javascriptreact, reason, rescript, typescript, typescriptreact, vue, svelte
 	autostart:       true
 	root directory:  /Users/rick/projects/ebike-app
 	cmd:             /Users/rick/.local/share/AstroNvim/mason/bin/tailwindcss-language-server --stdio
 
 Client: emmet_ls (id: 3, bufnr: [3])
 	filetypes:       astro, css, eruby, html, htmldjango, javascriptreact, less, pug, sass, scss, svelte, typescriptreact, vue
 	autostart:       true
 	root directory:  /Users/rick/projects/ebike-app
 	cmd:             /Users/rick/.local/share/AstroNvim/mason/bin/emmet-ls --stdio
 
 Client: null-ls (id: 4, bufnr: [3])
 	filetypes:       javascript, typescriptreact, typescript, javascriptreact
 	autostart:       false
 	root directory:  /Users/rick/projects/ebike-app
 	cmd:             <function>
 
 Client: copilot (id: 5, bufnr: [3])
 	filetypes:       
 	autostart:       false
 	root directory:  /Users/rick/projects/ebike-app
 	cmd:             node /Users/rick/.local/share/AstroNvim/lazy/copilot.lua/copilot/index.js
 
 Other clients that match the filetype: typescriptreact
 
 Config: eslint
 	filetypes:         javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx, vue, svelte, astro
 	root directory:    Not found.
 	cmd:               /Users/rick/.local/share/AstroNvim/mason/bin/vscode-eslint-language-server --stdio
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   eslint/confirmESLintExecution, eslint/openDoc, eslint/noLibrary, eslint/probeFailed
 
 Configured servers list: tsserver, lua_ls, cssls, emmet_ls, eslint, html, jsonls, tailwindcss

### when gd wroks , lsp information shows below log
 Press q or <Esc> to close this window. Press <Tab> to view server doc.
 
 Language client log: /Users/rick/.local/state/AstroNvim/lsp.log
 Detected filetype:   typescriptreact
 
 5 client(s) attached to this buffer: 
 
 Client: tsserver (id: 1, bufnr: [3])
 	filetypes:       javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx
 	autostart:       true
 	root directory:  /Users/rick/projects/ebike-app
 	cmd:             /Users/rick/.local/share/AstroNvim/mason/bin/typescript-language-server --stdio
 
 Client: copilot (id: 2, bufnr: [3])
 	filetypes:       
 	autostart:       false
 	root directory:  /Users/rick/projects/ebike-app
 	cmd:             node /Users/rick/.local/share/AstroNvim/lazy/copilot.lua/copilot/index.js
 
 Client: null-ls (id: 3, bufnr: [3])
 	filetypes:       javascript, javascriptreact, typescript, typescriptreact
 	autostart:       false
 	root directory:  /Users/rick/projects/ebike-app
 	cmd:             <function>
 
 Client: tailwindcss (id: 4, bufnr: [3])
 	filetypes:       aspnetcorerazor, astro, astro-markdown, blade, clojure, django-html, htmldjango, edge, eelixir, elixir, ejs, erb, eruby, gohtml, haml, handlebars, hbs, html, html-eex, heex, jade, leaf, liquid, markdown, mdx, mustache, njk, nunjucks, php, razor, slim, twig, css, less, postcss, sass, scss, stylus, sugarss, javascript, javascriptreact, reason, rescript, typescript, typescriptreact, vue, svelte
 	autostart:       true
 	root directory:  /Users/rick/projects/ebike-app
 	cmd:             /Users/rick/.local/share/AstroNvim/mason/bin/tailwindcss-language-server --stdio
 
 Client: emmet_ls (id: 5, bufnr: [3])
 	filetypes:       astro, css, eruby, html, htmldjango, javascriptreact, less, pug, sass, scss, svelte, typescriptreact, vue
 	autostart:       true
 	root directory:  /Users/rick/projects/ebike-app
 	cmd:             /Users/rick/.local/share/AstroNvim/mason/bin/emmet-ls --stdio
 
 Other clients that match the filetype: typescriptreact
 
 Config: eslint
 	filetypes:         javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx, vue, svelte, astro
 	root directory:    Not found.
 	cmd:               /Users/rick/.local/share/AstroNvim/mason/bin/vscode-eslint-language-server --stdio
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   eslint/confirmESLintExecution, eslint/openDoc, eslint/noLibrary, eslint/probeFailed
 
 Configured servers list: eslint, html, jsonls, tailwindcss, tsserver, lua_ls, cssls, emmet_ls

**when everything works , id of nullls and copilot are just higher. seems loading order affected the behavior**

**Comment by rick-yao** [comment]
@mehalter thanks for your quick reply, I think maybe this is my issue, but I don't konw how to fix it. i added a file named 'ts.lua' in user/plugins/ , and its content is listed below:
` 
return {

    "jose-elias-alvarez/typescript.nvim",
    config = function()
        require("typescript").setup({
            server = {
                init_options = {
                    preferences = {
                        importModuleSpecifierPreference = 'non-relative'
                    }
                }
            }
        })
    end
}
`
I removed the file then seems everything works fine. 
I added this file because I failed to implement the offcial doc instruction then I decided to implement it myself.
I read the astronvim doc https://astronvim.com/Recipes/advanced_lsp#typescript-typescriptnvim
but i failed to implemented it in my user/init.lua file because even though i add example content in init.lua i still get error.
could you please help with this ? thanks.
<img width="1310" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/59443488/e2f94b1b-453c-46e8-9457-6c33d29b3d58">
<img width="1039" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/59443488/cce1257c-a45f-4b06-b258-1edb62d1e423">

**Comment by rick-yao** [comment]
I think I figure it out. below is my solution.
in user/plugin folder , add typescript.lua with following code:
```lua
return {
  "jose-elias-alvarez/typescript.nvim", -- add lsp plugin
  {
    "williamboman/mason-lspconfig.nvim",
    opts = {
      ensure_installed = { "tsserver" }, -- automatically install lsp
    },
  },
}
```
then in user/init.lua, add setup_handlers in lsp section with following code:
```lua
    setup_handlers = {
      -- add custom handler
      tsserver = function(_, opts)
        local typescript_setup, typescript = pcall(require, "typescript")
        if not typescript_setup then return end
        typescript.setup {
          server = {
            capabilities = opts.capabilities,
            on_attach = opts.on_attach,
            init_options = {
              preferences = {
                importModuleSpecifierPreference = "non-relative",
              },
            },
          },
        }
      end,
    }
```
basically just pass init_options myself then pass capabilities & on_attach from opts
kind tough to a new guy to neovim.

**Comment by mehalter** [comment]
This is because you already have a `plugins/` folder and split up file locations take precedence over the `user/init.lua` file as described in the docs. Also your changes to the `setup_handlers` works, but the more correct and more "AstroNvim" way would be to keep the `setup_handlers` the same and then put the `init_options` in the lsp configuration table:

```lua
return {
  lsp = {
    config = {
      tsserver = {
        init_options = {
          preferences = {
            importModuleSpecifierPreference = "non-relative",
          },
        },
      },
    },
    setup_handlers = {
      tsserver = function(_, opts) require("typescript").setup { server = opts } end,
    },
  },
}
```
