### ISSUE TITLE
unable to temporarily close the line number through the command `set nonu`

### ISSUE THREAD

**Issue by Levstyle** [AstroNvim/AstroNvim#2249]
### Describe the new feature

Excellent job, thank you very much for your efforts. But I encountered a problem while using it. I was unable to temporarily close the line number through the command `set nonu`. I would not be very grateful if I could receive your help

**Comment by mehalter** [comment]
This works as intended. We have both relative numbers and numbers on. So you also need to do `:set norelativenumber`
