### ISSUE TITLE
Characters hidden on the left when scrolling to the right

### ISSUE THREAD

**Issue by nschloe** [AstroNvim/AstroNvim#2256]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

`Linux jannu 6.4.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 24 Aug 2023 00:38:14 +0000 x86_64 GNU/Linux`

### Terminal/GUI

kitty

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.36.6
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- WARNING `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

For a few weeks now, when I scroll far to the right in long lines, text on the left disappears for which there's actually still space. See `__init__` or `ed25519_hex` in this example:

![screenshot_2023-08-31-134830](https://github.com/AstroNvim/AstroNvim/assets/181628/e25daef1-5210-4531-92b5-0990cbe24581)

![screenshot_2023-08-31-134855](https://github.com/AstroNvim/AstroNvim/assets/181628/81755948-d311-431d-9215-6344abcc82ff)

### Steps to Reproduce

See above.

### Expected behavior

Show all characters for which there's space on screen.

### Screenshots

See above.

### Additional Context

This is with
```
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.1692616192

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by mehalter** [comment]
Could you try the latest commit on `nightly` and see if it resolves your issue?

Seeing the indentation markers still present it looks like a problem with indent blankline and then I found this issue on their repo: https://github.com/lukas-reineke/indent-blankline.nvim/issues/489

It seems to be exactly what you are describing and someone posted a workaround. I added this workaround to AstroNvim nightly and am curious if that solves it for you :D

**Comment by nschloe** [comment]
Sorry for the late response! I've wiped my config folder, reinstalled AstroNvim, and everything seems okay now.
