### ISSUE TITLE
Several critical errors on ubuntu server(tty)

### ISSUE THREAD

**Issue by Demiyanit** [AstroNvim/AstroNvim#2258]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Ubuntu 22.04.3 LTS

### Terminal/GUI

tty/none

### AstroNvim Health

.

### Describe the bug

throws several fatal errors

### Steps to Reproduce

just install atro nvim on ubuntu server(without any gui's) and try to launch it

### Expected behavior

i guess not throwing several fatal errors?

**Comment by Demiyanit** [comment]
oh yeah, instead of showing plugin installing screen it shows default nvim startup screen then throws another fatal on press of a button

**Comment by mehalter** [comment]
Please refer to the requirements of AstroNvim and check you Neovim version
