### ISSUE TITLE
WinScroller Auto-commands for "*":

### ISSUE THREAD

**Issue by nappalm** [AstroNvim/AstroNvim#2267]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Windows 11

### Terminal/GUI

PowerShell

## AstroNvim
    4   - INFO: AstroNvim Version: v3.36.7
    5   - INFO: Neovim Version: v0.8.0-1210-gd367ed9b2
    6   - OK: Using stable Neovim >= 0.8.0
    7   - OK: `git` is installed: Used for core functionality such as updater and plugin management
    8   - OK: `explorer` is installed: Used for `gx` mapping for opening files with system opener (Optional)
    9   - WARNING: `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
   10   - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
   11   - WARNING: `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
   12   - WARNING: `btm` is not installed: Used for mappings to pull up system monitor (Optional)
   13   - WARNING: `python/python3` is not installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

I have recently updated astronvim to its latest version. However I can't get rid of the following error:
![image](https://github.com/AstroNvim/AstroNvim/assets/35016608/7baaed51-af65-459e-bbd8-dcacfb6031d6)

### Steps to Reproduce

1. Download last astro version
2. After all the steps shown in the documentation, open nvim and see the error message

### Expected behavior

Have no bug

**Comment by Gadzhi07** [comment]
I think the error appeared after this issue https://github.com/AstroNvim/AstroNvim/issues/2256

To fix it, open the nvim/lua/astronvim/autocmds.lua
Comment out lines 215-223 like this:
```lua
--[=====[ 
if is_available "indent-blankline.nvim" then
  autocmd("WinScrolled", {
    desc = "Refresh indent blankline on window scroll",
    group = augroup("indent_blankline_refresh_scroll", { clear = true }),
    callback = function()
      if vim.v.event.all.leftcol ~= 0 then pcall(vim.cmd.IndentBlanklineRefresh) end
    end,
  })
end
--]=====]
```

**Comment by mehalter** [comment]
Thanks for reporting! I totally didn't realize the optimization I added for this uses a feature added in Neovim v0.9. I added a check for this in 

@Gadzhi07 @nappalm could you try the latest AstroNvim nightly and see if that resolves the issue for you?

**Comment by Gadzhi07** [comment]
Everything works
