### ISSUE TITLE
Blank line or file name / file path missing after tab buffer 

### ISSUE THREAD

**Issue by dmighty007** [AstroNvim/AstroNvim#2271]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

ArchCraft 6.4.12-arch1-1

### Terminal/GUI

kitty

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.36.8
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- WARNING `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
- WARNING `node` is not installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

There is a blank line just below the tab buffer and first line of any file which hurts the aesthetic point of view. Name of the file pops up when opening Lazy menu screen or toggle term but vanishes as soon as we close. 
Expected behavior:
File name or path just after tab buffer.
![Untitled presentation(1)](https://github.com/AstroNvim/AstroNvim/assets/60811558/ae8e2870-6fdd-4a1c-87d9-320477a6d9e6)
Currently getting a blank line which is hurting the aestheticism. 
![Untitled presentation(2)](https://github.com/AstroNvim/AstroNvim/assets/60811558/3eee6750-ea7a-443f-9ac0-9100c62e7960)

### Steps to Reproduce

Fresh astronvim installation. 
git clone --depth 1 https://github.com/AstroNvim/AstroNvim ~/.config/nvim
nvim

### Expected behavior

File name or path just after tab buffer.
![Untitled presentation(1)](https://github.com/AstroNvim/AstroNvim/assets/60811558/31cf84f4-4eda-4f97-b639-7764d95b1990)

### Additional Context

Just like the project man. Wanted to give it a shot, but those little things keeps hurting. This is my first time raising an issue. Do let me know what mistake I am doing while posting or what other information needed. Tried fresh installation on Hyprland(Arch linux) and ArchCraft.

**Comment by mehalter** [comment]
The current file is showing the treesitter or LSP breadcrumbs and not the filename or path. Also for the inactive windows it is showing unique path relative to the current working directory. If you want something closer to visual studio, check out the documentation: https://astronvim.com/Recipes/status#replicate-visual-studio-code-winbar
