### ISSUE TITLE
nvim treesitter error

### ISSUE THREAD

**Issue by pro465** [AstroNvim/AstroNvim#2275]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

windows 11

### Terminal/GUI

Windows Powershell

## AstroNvim
    - INFO: AstroNvim Version: v3.36.9
    - INFO: Neovim Version: v0.8.1
    - OK: Using stable Neovim >= 0.8.0
    - OK: `git` is installed: Used for core functionality such as updater and plugin management
    - OK: `explorer` is installed: Used for `gx` mapping for opening files with system opener (Optional)
    - WARNING: `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
    - WARNING: `node` is not installed: Used for mappings to pull up node REPL (Optional)
    - WARNING: `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
    - WARNING: `btm` is not installed: Used for mappings to pull up system monitor (Optional)
    - WARNING: `python/python3` is not installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

treesitter does not seem to be working.

It's showing this error:
```
Failed to run `config` for nvim-treesitter

Failed to load parser: uv_dlopen: C:\Users\proloy\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\rust.so is not a valid Win32 application.


# stacktrace:
  - C:/Program Files/Neovim/share/nvim/runtime/lua/vim/treesitter/language.lua:36 _in_ **require_language**
  - C:/Program Files/Neovim/share/nvim/runtime/lua/vim/treesitter/query.lua:213 _in_ **get_query**
  - ~/AppData/Local/nvim/lua/plugins/configs/nvim-treesitter.lua:1 _in_ **config**
  - ~/AppData/Local/nvim/lua/plugins/configs/nvim-autopairs.lua:3 _in_ **config**
  - ~/AppData/Local/nvim/lua/astronvim/utils/init.lua:145
```

### Steps to Reproduce

1. `nvim <any-rust-file>.rs`

### Expected behavior

treesitter should work.

### Additional Context

It happened after I updated the rust parser with `:TSInstall rust` and answering yes (`y`) when it asked whether to uninstall the old one.

**Comment by pro465** [comment]
btw, this machine is 64-bit, so it might be possible for `rust.so` to be a valid Win64 application but a not Win32 one. I don't know though

**Comment by mehalter** [comment]
You probably just need to reinstall the parser again with `:TSInstall rust`

**Comment by pro465** [comment]
Thanks or trying to help, but I had already tried. I also tried `:TSUninstall rust` and it errored out on this:
```
nvim-treesitter[rust]: Could not delete C:/Users/proloy/AppData/Local/nvim-data/lazy/nvim-treesitter\parser\rust.so
Invalid switch - "Users".^M
Press ENTER or type command to continue
```

unfortunately, I do not know what it means

**Comment by mehalter** [comment]
It looks like something pretty significant has gotten borked in your installation of Neovim. I would recommend clearing out your `nvim-data` folder and doing a full reinstallation to see if that resolves the issue.

Sadly, there isn't much else I can do/recommend since this is an issue with `nvim-treesitter` and Windows and not something within AstroNvim. If clearing out the `nvim-data` folder and reinstalling everything doesn't work, I would recommend checking out the Discord channel as there are a lot of users there who can help you and may have run into this issue before!

**Comment by pro465** [comment]
just so you know, I think I have found the [issue](https://github.com/tree-sitter/tree-sitter-rust/issues/189)

**Comment by pro465** [comment]
> If clearing out the nvim-data folder and reinstalling everything doesn't work, I would recommend checking out the Discord channel as there are a lot of users there who can help you and may have run into this issue before!

Unfortunately, I tried that. No luck. and I keep forgetting the password to discord 😆 . Any other way to connect to the community?

**Comment by pro465** [comment]
> btw, this machine is 64-bit, so it might be possible for `rust.so` to be a valid Win64 application but a not Win32 one. I don't know though

turns out I was correct in my hunch 🤣 . it got fixed by running it in "x64 Native Command Prompt for VS"
