### ISSUE TITLE
Scrolling down writes to the buffer

### ISSUE THREAD

**Issue by kaka-ruto** [AstroNvim/AstroNvim#2276]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

MacOS 13.5.1

### Terminal/GUI

iTerm

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.36.9
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

When I scroll down a file, at some point down the file, it prints a random line from my file to the first line of the buffer, eg, for this particular file, the following gets printed on the file, and it gets saved when I save the file. 
```
|  149 RSpec.describe Holdings::GetHoldingChangesSummary::EntryPoint do
```
I have found that this only happens on splits, vertical or horizontal, and not when I have one vim window.

And when I keep scrolling up and down, that line changes and a new things get's printed there, but still from the same file, eg, I'd find that now it has

```
2   11   let(:holdings_ledger_entry_7) do
```

The only way I have found to remove the lines is to manually remove them.

I didn't have this issue before, it started like a fortnight ago but not exactly sure when.

### Steps to Reproduce

1. Open two files in two splits
2. Scroll down one of them
3. Scroll back up
4. You may find that random lines from your buffers get written on the first line of that buffer, including the line number

### Expected behavior

Nothing should be writing to the buffer on scroll

**Comment by kaka-ruto** [comment]
Thanks @mehalter . I have autosave on, so when it puts content to the file, it get's autosaved. So it puts the content, and my autosave saves the file, all of this only on normal mode. The specific keypresses are CTRL + d, CTRL + e and j to scroll down on normal mode. It gets to a point that puts a line of code from that buffer onto the top of my file. I have tested with both `.rb` and `_spec.rb` files on splits. I can't replicate without them on splits.

And I found I can't undo with `u`, I have to manually delete the new line. 

I have tried disabling a few plugins I suspected but the issue persisted. I will try to replicate this more reliably outside my current setup then report back. Thank for helping take a look!

**Comment by mehalter** [comment]
Ok thanks, if you are able to post some specific steps that I can follow I can definitely try. With the given information I just don't have enough to replicate anything.

**Comment by jay-babu** [comment]
I also have this problem. I thought it was one of my plugins, so didn't report. Will try to send a recording of when it happens

**Comment by jay-babu** [comment]
https://github.com/AstroNvim/AstroNvim/assets/36803168/448959be-bbd2-4253-bfa7-bc669571c758

**Comment by mehalter** [comment]
@jay-babu are you able to replicate this with a specific set of steps that you can provide? I can't really do anything or debug something that I cannot replicate on my end.

**Comment by jay-babu** [comment]
Steps to Reproduce
1. Open two files in two splits
1. `Shift + g`
1. `gg`
1. I do it in a java file with `lsp` setup

**Comment by jay-babu** [comment]
I do not have autosave setup

**Comment by mehalter** [comment]
Is it only reproducible in your java files with the Java LSP? @jay-babu

**Comment by jay-babu** [comment]
I have had it happen with `tsx` project a couple of times but it is very rare (once every 2 weeks). In java, it happens very often

**Comment by mehalter** [comment]
I'm not sure @jay-babu any idea what is going on in your screenshot when you do `G` and then `gg`? It looks like a ton of flashing which is probably what is leading to the weirdness

**Comment by jay-babu** [comment]
https://github.com/AstroNvim/AstroNvim/assets/36803168/945b0779-f2b7-4750-ad1f-943d230756f3

I disabled the context plugin and the error remains there

**Comment by mehalter** [comment]
Can you replicate it with a minimal user configuration removing everything except adding the minimum necessary to get the java language server running @jay-babu ?

**Comment by jay-babu** [comment]
`	{ import = "astrocommunity.motion.vim-matchup" },`

seems to be the problem. I tested 3 times with and without it and the problem only happens when it is enabled

**Comment by mehalter** [comment]
awesome! Thanks so much for investigating into this!

**Comment by mehalter** [comment]
@jay-babu if you are interested, I'm nearly 100% certain that the reason for this is the `popup` method for displaying offscreen matchup:

https://github.com/AstroNvim/astrocommunity/blob/main/lua/astrocommunity/motion/vim-matchup/init.lua#L5

Not sure what a better default for this would be but it could be resolved through improvements to AstroCommunity if someone wants to investigate that.

Relevant issue: https://github.com/andymass/vim-matchup/issues/189

**Comment by kaka-ruto** [comment]
Confirmed that disabling `matchup_matchparen_deferred` by setting `vim.g.matchup_matchparen_deferred = 0` solves the issue. I can create a PR to address the issue.

Important to note that before and after this change, I still cannot achieve what the introducing PR aimed to achieve https://github.com/AstroNvim/astrocommunity/pull/474, my matches are still not highlighted

**Comment by kaka-ruto** [comment]
Here's a PR to remove the option https://github.com/AstroNvim/astrocommunity/pull/561
