### ISSUE TITLE
Unable to disable warning level virtual text only for files of a certain filetype

### ISSUE THREAD

**Issue by throwaway69420-69420** [AstroNvim/AstroNvim#2278]
### Is your feature related to a problem?

yes

### Describe the new feature

I want to disable warning level virtual text for R files

**Comment by mehalter** [comment]
This would be a feature request to the language server that you are interested in customizing. If you want a more general approach then a feature request to Neovim! Sorry I can't do anything here!

**Comment by throwaway69420-69420** [comment]
thanks a lot for the quick response. Best neovim distro as always

**Comment by throwaway69420-69420** [comment]
hello can you help me by guiding me how to set `r.lsp.diagnostics` to `false` as mentioned [here](https://github.com/REditorSupport/languageserver#settings). 

my config file structure is:
```
                                                                                                                                   │         
  ── lsp                                                                                                                                                   │         
     └── config                                                                                                                                            │         
         ├── clangd.lua                                                                                                                                    │         
         └── r-language-server.lua
```

**Comment by mehalter** [comment]
your `r-language-server.lua` file would look sometihng like this:

```lua
return {
  settings = {
    r = {
      lsp = {
        diagnostics = {
          false,
        },
      },
    },
  },
}
```

**Comment by throwaway69420-69420** [comment]
will this remove error and warnings both?

**Comment by mehalter** [comment]
I'm not sure, I haven't configured the R language server to that degree, so your guess is as good as mine 😅 It will just depend on what the language server does, it's not following some global rules or anything
