### ISSUE TITLE
nvim-cmp breaks one 3rd party plugin

### ISSUE THREAD

**Issue by throwaway69420-69420** [AstroNvim/AstroNvim#2282]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Linux 

### Terminal/GUI

kitty

### AstroNvim Health

```
==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.36.9
- Neovim Version: v0.9.2
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

```

### Describe the bug

[This](https://github.com/hrsh7th/nvim-cmp/commit/3b9f28061a67b19cadc13946de981426a6425e4a) commit of [nvim-cmp](https://github.com/hrsh7th/nvim-cmp/) breaks [codeium](https://github.com/jcdickinson/codeium.nvim/issues/80) (It is a type of code completion plugin. 

[Official website of codeium](https://codeium.com/). The plugin in question is the unofficial plugin because official one doesn't work with nvim-cmp

### Steps to Reproduce

1. Install https://github.com/jcdickinson/codeium.nvim/
2. make `jcdickinson/codeium.nvim` a dependency of `hrsh7th/nvim-cmp` and list codeium as one of its sources
3. Restart for changes to take place

### Expected behavior

Expected Behaviour: Codeium suggestions should come in suggestion window
Actual Behaviour: Codeium suggestions doesn't get suggested

### Additional Context

my cmp.lua file: https://gist.github.com/throwaway69420-69420/2397f8aa45e4f3dfcadf549eae5bfffc

It can be fixed by temporarily downgrading to [this](https://github.com/hrsh7th/nvim-cmp/commit/6c84bc75c64f778e9f1dcb798ed41c7fcb93b639) commit of nvim-cmp

**Comment by mehalter** [comment]
This sounds like a bug in `nvim-cmp` and not AstroNvim. Sorry!
