### ISSUE TITLE
vim.opt.wrap not set properly

### ISSUE THREAD

**Issue by thehunmonkgroup** [AstroNvim/AstroNvim#2284]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Pop!_OS 22.04 LTS

### Terminal/GUI

wezterm

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: v3.36.9
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- WARNING `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Despite have set `wrap = true` in my `options.lua`, `:se wrap?` is still showing `nowrap` after starting Neovim.

Here's my entire `options.lua`:

```lua
return {
  opt = {
    -- set to true or false etc.
    relativenumber = false, -- sets vim.opt.relativenumber
    number = true, -- sets vim.opt.number
    spell = false, -- sets vim.opt.spell
    signcolumn = "auto", -- sets vim.opt.signcolumn to auto
    wrap = true, -- sets vim.opt.wrap
    scrolloff = 8,
    undofile = false,
  },
  g = {
    mapleader = " ", -- sets vim.g.mapleader
    autoformat_enabled = false, -- enable or disable auto formatting at start (lsp.formatting.format_on_save must be enabled)
    cmp_enabled = true, -- enable completion at start
    autopairs_enabled = true, -- enable autopairs at start
    diagnostics_mode = 3, -- set the visibility of diagnostics in the UI (0=off, 1=only show in status line, 2=virtual text off, 3=all on)
    icons_enabled = true, -- disable icons in the UI (disable if no nerd font is available, requires :PackerSync after changing)
    ui_notifications_enabled = true, -- disable notifications when toggling UI elements
    resession_enabled = false, -- enable experimental resession.nvim session management (will be default in AstroNvim v4)
  },
  o = {
    autoindent = true,
    smartindent = true,
    background = "dark",
  },
  wo = {
    wrap = true
  }
}
```

I've also grepped for `vim.opt.wrap` and `vim.wo.wrap` in `~/.local/share/nvim`, thinking it might be some issue with a plugin, but I'm not seeing any issues there, either.

### Steps to Reproduce

1. Set `wrap = true` in `options.lua
2. Start Neovim

### Expected behavior

`:se wrap` should show `wrap`

**Comment by mehalter** [comment]
Just tested with a minimal setup and it seems to be working as intended. What filetype are you experiencing this in? It's probably being hard coded by the core Neovim runtime for the filetype you are interested in.

But if you have `wrap = true` in your `options.lua` file in the `opt` table then if you run `nvim` and then open a new file with `<space>n` from the homescreen then you will see that wrap is set correctly.

**Comment by mehalter** [comment]
Oh, maybe you are thinking of `wrap` on the alpha dashboard where Alpha sets `wrap = false` locally to the buffer. But once you open a file then it will be set to what you actually want it to be set to.

**Comment by thehunmonkgroup** [comment]
OK, I've been playing with this more, and it's possible I may be misunderstanding something but it *sure* seems like there's a bug here.

To your point, `wrap` is `false` on the dashboard, and I had not accounted for that before.

However, when I open Neotree and select a `.py` file from the *root* directory of my project, `wrap` is indeed `true`. *But*, when I then, from the same project, select another `.py` file from a *subdirectory*, `wrap` is again `false`, which makes no sense, because it's the same filetype.

Is there something I'm misunderstanding about how wrap should be set? I mean it really seems like for the same file type in the same project, it ought to be consistent ;)

**Comment by mehalter** [comment]
With a minimal example of a fresh installation that only has a `user/options.lua` file with `return { opt = { wrap = true } }`, I get `wrap` when running `:set wrap?` no matter how many python files I have open. You might have a plugin or something that is trying to set it. Unlikely, but it could also be a comment in the file that sets the option in vim

**Comment by mehalter** [comment]
@thehunmonkgroup I also just installed your user configuration on my machine in a fresh installation of AstroNvim and also get `wrap` when running `:set wrap?` when opening a ton of diferent python files in a single session. Haven't been able to replicate the issue you are describing where it changes to `nowrap`

**Comment by thehunmonkgroup** [comment]
Did you try a situation where some of the Python files are in a subdirectory of the main project root? Because I have no problem opening multiple `.py` files from the root of the project, only when they live in a subdirectory.

I will check my modelines for a wrap setting, but that would really surprise me -- I don't ever recall using that setting in a modeline.

**Comment by mehalter** [comment]
Yup, I haven't had any issues with the python files being in the root vs non-root with my configuration nor yours

**Comment by thehunmonkgroup** [comment]
OK, just a sanity check here: If `vim.opt.wrap = true`, then the *only* reason I'd be seeing `nowrap` when opening a file is because `vim.wo.wrap` was somehow set to `false` for that window, right?

If that's the case, where can I look in AstroNvim's code to throw some debug statements and track this weird behavior down?

**Comment by mehalter** [comment]
yeah when you run put `opt = { wrap = true }` we are just running `vim.opt.wrap = true` on startup. We aren't doing any funny business around that or anything funky with auto commands or whatnot. We also don't set any window options anywhere like that. So honestly I have no idea where you would look.

One option you could go down is using `:verbose` so something like `:verbose set wrap?` will show you the last place it was set. Granted sometimes this is useful and sometimes it just says "from Lua"

**Comment by thehunmonkgroup** [comment]
This is really weird:

```
:lua print(string.format("vim.opt.wrap: %s, vim.wo.wrap: %s", tostring(vim.opt.wrap._value), tostring(vim.wo.wrap)))
vim.opt.wrap: false, vim.wo.wrap: false
```

That's right after opening AstroNvim. Shouldn't `vim.opt.wrap` at least be true there??

**Comment by mehalter** [comment]
if you are on the alpha dashboard, this is almost certainly because alpha is setting `vim.opt_local.wrap` and that might be messing up the output look of `vim.opt.wrap` 😅

**Comment by thehunmonkgroup** [comment]
Thanks for the guidance so far. My instinct tells me it might be a plugin, so I'll start down that fun debugging road. If I figure it out I'll post my results here.
