### ISSUE TITLE
Resession extension breaks restoration of qf window

### ISSUE THREAD

**Issue by Subjective** [AstroNvim/AstroNvim#2290]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.4

### Terminal/GUI

kitty

### AstroNvim Health

```
AstroNvim ~
- AstroNvim Version: v3.36.9
- Neovim Version: v0.10.0-dev-a6e74c1
- WARNING Neovim nightly is not officially supported and may have breaking changes
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)
```

### Describe the bug

When the astronvim resession extension is enabled, restoring a session does not properly restore the quickfix window, instead replace it with normal buffer.

### Steps to Reproduce

1. Open a quickfix window `:copen`
2. Place the cursor in it
3. `:qa`
4. Reopen AstroNvim and hit `<leader>Sl` to restore the last session
5. A buffer is placed into the window where the quickfix items should be

### Expected behavior

For the quickfix window to be restored if the cursor was last in it.

### Screenshots

https://asciinema.org/a/lzkyNkDJ9TMcIzAZDKRHSePbE

**Comment by mehalter** [comment]
have you enabled the `quickfix` extension in resession?

**Comment by Subjective** [comment]
@mehalter Yeah, it's enabled by default too

**Comment by Subjective** [comment]
The window is restored if the cursor was not in the quickfix window upon saving. Doesn't seem to happen when the astronvim extension is disabled.

**Comment by Subjective** [comment]
Interestingly, it doesn't actually happen on v4 (which I still have not yet migrated to), but I do get this message:
<img width="926" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/56745535/b5abdf4d-32c7-4c99-a1d2-814f55985b4c">

**Comment by mehalter** [comment]
Yeah I have identified the issue and what's causing it. We will have to see if I can come up with a decent fix for this 🤔

**Comment by mehalter** [comment]
What's going on is definitely a bit hacky in the first place. So I'll be glad to rewrite the current recession extension. But it will take some time and thinking to figure out the best approach to capture the semantics of what it means to save and reload a session with some of the edge cases that exists here

**Comment by Subjective** [comment]
That sounds like a good idea, while it works fine most of the time, I've occasionally experienced issues with loading tabs, though it happens so rarely that I haven't bothered looking into it.

BTW there's now a new `on_pre_load` method in the extension API, which could be useful for certain things.

**Comment by Subjective** [comment]
Speaking about rewriting the tabline, what do you think about having a feature to disable/enable autohiding the tabline baked into AstroNvim by default? Before, when using neovim-session-manager, it was possible to accomplish this with an  [autocmd](https://astronvim.com/nightly/Configuration/autocmds#example-autocommand-usage). But after moving to resession, `showtabline = (vim.t.bufs and #vim.t.bufs > 1) and 2 or 1` is evaluated as 1 and so it takes some time after opening vim before the buffers and tabs are loaded. This causing some visual flicker as it takes some time before the tabline is finally shown. 

I was thinking that `showtabline` could be set in the astronvim's resession extension as an opt in feature that also creates the autocmd.

<details>
<summary>Example</summary>

```lua
M.on_load = function(data)
  -- create map from old buffer numbers to new buffer numbers
  local new_bufnrs = {}
  for _, bufnr in ipairs(vim.api.nvim_list_bufs()) do
    local bufname = vim.api.nvim_buf_get_name(bufnr)
    if bufname and data.bufnrs[bufname] then new_bufnrs[data.bufnrs[bufname]] = bufnr end
  end
  -- build new tab scoped buffer lists
  for tabpage, tabs in pairs(data.tabs) do
    vim.t[tabpage].bufs = vim.tbl_map(function(bufnr) return new_bufnrs[bufnr] end, tabs)
  end
  -- SET SHOWTABLINE
  if vim.g.astro_autohide_tabline then vim.opt.showtabline = (vim.t.bufs and #vim.t.bufs > 1) and 2 or 1 end

  local buf_utils = require "astronvim.utils.buffer"
  buf_utils.current_buf = new_bufnrs[data.current_buf]
  buf_utils.last_buf = new_bufnrs[data.last_buf]

  require("astronvim.utils").event "BufsUpdated"

  if vim.fn.bufnr() ~= buf_utils.current_buf then vim.cmd.b(buf_utils.current_buf) end
end
```

</details>

**Comment by mehalter** [comment]
To your latest comment, I don't think this is an abstraction we want to add to AstroNvim. It can be achieved like you mentioned by adding a `post_load` hook. Sure we can add this to the docs. Feel free to make a PR or I can get around to it at some point.

**Comment by mehalter** [comment]
This should be resolved on `nightly`. Didn't end up fully rewriting anything. There doesn't seem to be a good way to handle some of the edge cases better than how we currently are. But there is a good way to detect if the current buffer should be "wiped" on loading of the session. So hopefully that is a good enough approach!
