### ISSUE TITLE
Error finding version: latest - M2 Mac macOS Ventura 13.5.2 Neovim 0.9.2

### ISSUE THREAD

**Issue by marvel64** [AstroNvim/AstroNvim#2292]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.5.2

### Terminal/GUI

iTerm2

### AstroNvim Health

 2   astronvim: require("astronvim.health").check()
   3
   4   AstroNvim
   5   - AstroNvim Version: unknown
   6   - Neovim Version: v0.9.2
   7   - OK Using stable Neovim >= 0.8.0
   8   - OK git is installed: Used for core functionality such as updater and plugin management
   9   - OK open is installed: Used for gx mapping for opening files with system opener (Optional)
  10   - WARNING lazygit is not installed: Used for mappings to pull up git TUI (Optional)
  11   - OK node is installed: Used for mappings to pull up node REPL (Optional)
  12   - WARNING gdu is not installed: Used for mappings to pull up disk usage analyzer (Optional)
  13   - WARNING btm is not installed: Used for mappings to pull up system monitor (Optional)
  14   - OK python is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

On a new Mac with M2 Max processor, I installed Neovim 0.9.2 via Homebrew and AstroNvim via

`git clone --depth 1 https://github.com/AstroNvim/AstroNvim ~/.config/nvim`

The initial setup runs without issues. When I restart and try

`SPC -> p -> A` for `AstroNVim Update` I get: `Error finding version: latest`.

`:AstroVersion` returns `unknown`.

The `.config/nvim` directory shows commit `6d5750b`.

This setup works without issues on my Intel Mac with the same Neovim version on macOS 12.x.

Any help very much appreciated!

Thanks!
Marc

### Steps to Reproduce

1. Vanilla system with Neovim 0.9.2 via Homebrew (no .config/nvim or .local/share/nvim).
2. git clone --depth 1 https://github.com/AstroNvim/AstroNvim ~/.config/nvim
3. Start nvim, let setup finish.
4. Restart nvim and do update.

### Expected behavior

Pull information about updates.

**Comment by mehalter** [comment]
What do you get when you run `git status` in the terminal in the directory

**Comment by mehalter** [comment]
Also what shell are you using

**Comment by marvel64** [comment]
I use zsh (on all machines).

git status in .config/nvim returns:

```                                                                                                                                                                                                                  
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
```

**Comment by mehalter** [comment]
What happens if you run `git describe --tags`?

**Comment by marvel64** [comment]
`fatal: No names found, cannot describe anything.`

**Comment by mehalter** [comment]
Seems like something got borked. Could you try running `git fetch main` and see if that helps?

**Comment by marvel64** [comment]
```
fatal: 'main' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

No idea what could have happened. It is a new machine. I started to set it up yesterday. I installed it several times, each time removing `.local/share/nvim` and `.config/nvim`.

**Comment by mehalter** [comment]
Huh I'm not sure sorry 😅 seems like your repo hasn't been cloned properly

**Comment by marvel64** [comment]
No worries. Thanks for your time!

**Comment by marvel64** [comment]
That fixed it (quick Google search):

`git fetch --prune --unshallow`

**Comment by mehalter** [comment]
Awesome glad you got it!
