### ISSUE TITLE
Mason package problem

### ISSUE THREAD

**Issue by SmsS4** [AstroNvim/AstroNvim#2294]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Endevaouros

### Terminal/GUI

alacritty

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: unknown
- Neovim Version: v0.9.2
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- WARNING `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Hi
I can install plugins with mason but if I close my nvim and reopen none of my plugins loads and my installed plugins page is empty.
Any suggestion how to solve or find what is wrong?
Thanks

### Steps to Reproduce

I installed Endevaouros with i3 a week ago and installed my neovim with `yay -S neovim`

### Expected behavior

I expect packages to stay install after closing neovim

**Comment by mehalter** [comment]
Can you please provide more information to clarify what you are saying?

- What have you installed in mason, what is the exact behavior?
- Could you provide screenshots showing  what you mean?
- When you say plugins do you mean plugins in Lazy since Mason installs external tooling?
- Have you looked at the documentation to see how to use AstroNvim?

**Comment by SmsS4** [comment]
Looks like it's not astronvim problem since i have same issue with lazyvim
Thanks for reply
