### ISSUE TITLE
error tree sitter attempt to call field get_range nil value after updating from v3.9 to v3.36

### ISSUE THREAD

**Issue by ScopeSV** [AstroNvim/AstroNvim#2306]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.5.2

### Terminal/GUI

warp

## AstroNvim
  - INFO: AstroNvim Version: v3.36.12
  - INFO: Neovim Version: v0.8.3
  - OK: Using stable Neovim >= 0.8.0
  - OK: `git` is installed: Used for core functionality such as updater and plugin management
  - OK: `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
  - WARNING: `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
  - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
  - WARNING: `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
  - WARNING: `btm` is not installed: Used for mappings to pull up system monitor (Optional)
  - OK: `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

After updating to the lastest version of astro n vim, I get this error in my console:
```
Error executing vim.schedule lua callback: ...vim-treesitter-context/lua/treesitter-context/render.lua:143: attempt to call field 'get_range' (a
nil value)
stack traceback:
        ...vim-treesitter-context/lua/treesitter-context/render.lua:143: in function 'fn'
        ...3/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:210: in function 'for_each_tree'
        ...vim-treesitter-context/lua/treesitter-context/render.lua:128: in function 'highlight_contexts'
        ...vim-treesitter-context/lua/treesitter-context/render.lua:366: in function 'open'
        .../lazy/nvim-treesitter-context/lua/treesitter-context.lua:50: in function 'open'
        .../lazy/nvim-treesitter-context/lua/treesitter-context.lua:111: in function <.../lazy/nvim-treesitter-context/lua/treesitter-context.lua
:92>
```

Happens mostly when scrolling up and down. (ctrl+d/u)
I checked the version before updating and it said v3.9, which I found a bit odd. But after updating it now says v3.36.12

### Steps to Reproduce

1. Update from v3.9 to v.33
2. Get error

### Expected behavior

Not having this error message

**Comment by mehalter** [comment]
This looks to be something in [nvim-treesitter-context](https://github.com/nvim-treesitter/nvim-treesitter-context) and not AstroNvim. You updating AstroNvim is probably unrelated and more related to an update to that plugin. So you should check to see what's going on with how you configured that plugin and if there is some sort of breaking change that happened. Sorry I'm not much help!
