### ISSUE TITLE
Go to reference || Ctrl + click. don't works anymore since last AstroVim update

### ISSUE THREAD

**Issue by t1gu1** [AstroNvim/AstroNvim#2308]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

MacOS 13.4.1

### Terminal/GUI

kitty

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: v3.36.12
- Neovim Version: v0.9.2
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

When I try to go to a reference it show me an error. (Go see the screenshot)

Language: Typescript

### Steps to Reproduce

- Open a project
- find a method
- Ctrl + click to go to the reference
- You'll see the error

### Expected behavior

It should go to the reference

### Screenshots

![image](https://github.com/AstroNvim/AstroNvim/assets/12479055/38668caf-776d-451b-aa99-a3e20b8f8f86)

### Additional Context

Only happend since I update to the last version of AstroVim

**Comment by mehalter** [comment]
Where is this control+click functionality coming from? It doesn't seem related to core AstroNvim code

**Comment by mehalter** [comment]
ohh it's coming from tag files, like this is just a core neovim thing. It doesn't look like any of the errors are originating from AstroNvim in any way or touch the AstroNvim codebase. Can you provide some detailed steps to replicate the issue? Also have you verified that if you revert back to a previous version that the error goes away?

**Comment by mehalter** [comment]
oh I see, it looks like this is coming from a bug in the language server and not from Neovim or AstroNvim. Here is a relevant issue: https://github.com/neovim/neovim/issues/18223

**Comment by t1gu1** [comment]
I just test the Rollback with AstroRollback.
Sadly, it doesn't fix it as it was before.

It may updated a package or something else that doesn't rollback totally?

**Comment by mehalter** [comment]
Yeah that makes total sense if it's a bug in the language server. This also luckily confirms that it's not AstroNvim related. This will be originating from the language server itself. Either one that you have installed on your system or installed through Mason. You can use Mason to see if there are updates, see if you have updated it through your package manager outside of Neovim, etc. Sorry I don't have much guidance here 😓

**Comment by t1gu1** [comment]
Finally to fix my issue I simply make a `MasonUnistallAll`.
Then I close and reopen Nvim and make a `MasonInstall`.

After that things started to works as before.
