### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by shubhamku044** [AstroNvim/AstroNvim#2310]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 14

### Terminal/GUI

alacritty, kitty both

## AstroNvim
  - INFO: AstroNvim Version: unknown
  - INFO: Neovim Version: v0.8.2
  - OK: Using stable Neovim >= 0.8.0
  - OK: `git` is installed: Used for core functionality such as updater and plugin management
  - OK: `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
  - WARNING: `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
  - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
  - OK: `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
  - WARNING: `btm` is not installed: Used for mappings to pull up system monitor (Optional)
  - OK: `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

anytime when I am opening a file, getting this error
![image](https://github.com/AstroNvim/AstroNvim/assets/77788249/45a8b8c3-ea35-4075-ba0c-5013345ab2d0)

### Steps to Reproduce

1. open neovim in any director
2. Open any file inside neovim 

### Expected behavior

this is coming, and then going back suddenly

### Screenshots

![image](https://github.com/AstroNvim/AstroNvim/assets/77788249/9d0fa219-dc09-4213-b1a8-243761ed9de2)

**Comment by mehalter** [comment]
Can you please share the entire error? With like `:Telescope notifications`? It looks like a bug in the new indent blankline update

**Comment by mehalter** [comment]
Yeah it appears they are using an API only available in Neovim v0.9. The easiest way to avoid this is to either update to a newer version of Neovim or downgrade AstroNvim back to v3.36 for the time being until next week when I can contribute a fix upstream

**Comment by shubhamku044** [comment]
Ok, then I will update my neovim to v0.9

**Comment by mehalter** [comment]
Thanks for reporting! I have reported it upstream and hopefully it gets resolved. If it doesn't, I will at least be able to make a PR to their project to fix this myself.

I will go ahead and leave this open since this does break AstroNvim's official compatibility so I would still consider this a bug for us. Sadly I won't have time until after the weekend when I get in front of a computer again.

**Comment by mehalter** [comment]
https://github.com/lukas-reineke/indent-blankline.nvim/issues/658

Looks like we need to revert this change and downgrade to v2 since the maintainer is uninterested in supporting older versions

**Comment by mehalter** [comment]
This should be resolved in the newest release of indent-blankline.
