### ISSUE TITLE
symbols are truncated on the edge of the terminal

### ISSUE THREAD

**Issue by idavydov** [AstroNvim/AstroNvim#2315]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.5

### Terminal/GUI

iterm2

### AstroNvim Health

- AstroNvim Version: v3.37.0
- Neovim Version: v0.9.2
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- WARNING `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Terminal characters are truncated on the right when the number of lines in the terminal changes from 99 to 100.

### Steps to Reproduce

1. Run `nvim term://zsh`
2. Switch to the insert mode with `i`.
3. Run the following code:
  ```bash
  for i in $(seq 100); do echo; done
  for i in $(seq 10); do echo -n 1234567890; done; echo
  ```

### Expected behavior

All the digits are visible on the right side of the treminal.

### Screenshots

![2023-10-02_12-10-30 (1)](https://github.com/AstroNvim/AstroNvim/assets/671660/d2ed8140-4c87-458e-b442-a9931df4bfc3)

### Additional Context

I tracked this problem to heirline. If heirline is disabled, this bug doesn't reproduce.

Here's a minimal heirline config to reproduce a bug:
```lua
return {
  "rebelot/heirline.nvim",
  event = "BufEnter",
  opts = function()
    local status = require "astronvim.utils.status"
    return {
      statuscolumn = vim.fn.has "nvim-0.9" == 1 and {
        status.component.foldcolumn(),
        status.component.numbercolumn(),
      } or nil,
    }
  end,
  config = require "plugins.configs.heirline",
}
```

This was causing jalvesaq/Nvim-R#758

**Comment by mehalter** [comment]
I will keep monitoring this upstream, but sadly leaves nothing to be done in AstroNvim. I have also verified that I get the same bug in other plugins that configure statusline and everything. Sorry about this!

**Comment by idavydov** [comment]
Thanks a lot for opening an upstream report regarding this!

**Comment by mehalter** [comment]
No problem! This is definitely a funky one! I'll also think a bit about better workarounds in the meantime as well

**Comment by mehalter** [comment]
@idavydov Iput together a better workaroudn that can be made generally available to AstroNvim with a todo notice to be removed when the actual bug upstream gets fixed. Basically I am just disabling the custom `statuscolumn` for terminal buffers for now. I also added disabling the foldcolumn and signcolumn as well just because they are useless in terminal buffers anyway :) It will be made available in v3.37.1 ! Hopefully this is a bit of a better solution for you rather than disabling it all together

**Comment by idavydov** [comment]
great, thanks! I can confirm that it works now as expected. the original issue doesn't reproduce anymore as well (jalvesaq/Nvim-R#758)

**Comment by mehalter** [comment]
@idavydov Also a heads up a fix for this has been added into Neovim core and will be a part of the next maintenance release of Neovim, v0.9.3 ! I have updated the code so that our hacky workaround will not be applied when using Neovim v0.9.3+ so it will be ready for whenever that release is made :D

**Comment by mehalter** [comment]
Here is the relevant PR: https://github.com/neovim/neovim/pull/25480
