### ISSUE TITLE
Heirline/Statusline Error: symbol not found

### ISSUE THREAD

**Issue by CY83R14N** [AstroNvim/AstroNvim#2318]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 14.0 Sonoma

### Terminal/GUI

iTerm2

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.37.1
- Neovim Version: v0.9.2
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

```
E5108: Error executing lua ...ser/.config/nvim/lua/astronvim/utils/status/provider.lua:77: dlsym(RTLD_DEFAULT, compute_foldcolumn): symbol not found
stack traceback:
        [C]: in function '__index'
        ...ser/.config/nvim/lua/astronvim/utils/status/provider.lua:77: in function 'provider'
        ...hare/nvim/lazy/heirline.nvim/lua/heirline/statusline.lua:381: in function '_eval'
        ...hare/nvim/lazy/heirline.nvim/lua/heirline/statusline.lua:398: in function '_eval'
        ...hare/nvim/lazy/heirline.nvim/lua/heirline/statusline.lua:398: in function '_eval'
        ...hare/nvim/lazy/heirline.nvim/lua/heirline/statusline.lua:473: in function <...hare/nvim/lazy/heirline.nvim/lua/heirline/statusline.lua:472>
```

### Steps to Reproduce

1. git clone --depth 1 https://github.com/AstroNvim/AstroNvim ~/.config/nvim
2. nvim

### Expected behavior

-

### Additional Context

Nvim displays the error either after starting or after installing plugins

**Comment by mehalter** [comment]
Please see #2311
