### ISSUE TITLE
bug with indent-blankline

### ISSUE THREAD

**Issue by tofulm** [AstroNvim/AstroNvim#2320]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

archlinux

### Terminal/GUI

kitty

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.37.1
- Neovim Version: v0.10.0-dev-3af59a4
- WARNING Neovim nightly is not officially supported and may have breaking changes
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

==============================================================================
lazy: require("lazy.health").check()

lazy.nvim ~
- OK Git installed
- OK no existing packages found by other package managers
- OK packer_compiled.lua not found
- WARNING {LuaSnip}: overriding <config>
- WARNING {nvim-surround}: unknown key <disable>
- WARNING {nvim-surround}: unknown key <requires>

==============================================================================
nvim: require("nvim.health").check()

Configuration ~
- OK no issues found

Runtime ~
- OK $VIMRUNTIME: /home/tof/.local/share/bob/nightly/nvim-linux64/share/nvim/runtime

Performance ~
- OK Build type: RelWithDebInfo

Remote Plugins ~
- OK Up to date

terminal ~
- key_backspace (kbs) terminfo entry: `key_backspace=\177`
- key_dc (kdch1) terminfo entry: `key_dc=\E[3~`
- $COLORTERM="truecolor"

==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (0c49d6745b3fc4822ab02e0018770cd6383a779c) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v18.18.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 13.2.1 20230801
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.5.5-arch1-1",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Sat, 23 Sep 2023 22:55:13 +0000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luap                ✓ . . . .
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - php                 ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - scss                ✓ . ✓ ✓ .
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - vue                 ✓ . ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

==============================================================================
provider: require("provider.health").check()

Clipboard (optional) ~
- OK Clipboard tool found: wl-copy

Python 3 provider (optional) ~
- `g:python3_host_prog` is not set.  Searching for python3 in the environment.
- Executable: /usr/bin/python3
- Python version: 3.11.5
- pynvim version: 0.4.3
- OK Latest pynvim is installed.

Python virtualenv ~
- OK no $VIRTUAL_ENV

Ruby provider (optional) ~
- Ruby: ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x86_64-linux]
- Host: /home/tof/.local/share/gem/ruby/3.0.0/bin/neovim-ruby-host
- OK Latest "neovim" gem is installed: 0.9.1

Node.js provider (optional) ~
- Node.js: v18.18.0
- Nvim node.js host: /home/tof/.npm-global/lib/node_modules/neovim/bin/cli.js
- OK Latest "neovim" npm/yarn/pnpm package is installed: 4.10.1

Perl provider (optional) ~
- WARNING "Neovim::Ext" cpan module is not installed
  - ADVICE:
    - See :help |provider-perl| for more information.
    - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.7.0

===== Installed extensions ===== ~

Telescope Extension: `aerial` ~
- No healthcheck provided

Telescope Extension: `file_browser` ~
- No healthcheck provided

Telescope Extension: `fzy_native` ~
- No healthcheck provided

Telescope Extension: `hop` ~
- No healthcheck provided

Telescope Extension: `live_grep_args` ~
- No healthcheck provided

Telescope Extension: `neoclip` ~
- No healthcheck provided

Telescope Extension: `notify` ~
- No healthcheck provided

Telescope Extension: `projects` ~
- No healthcheck provided

==============================================================================
vim.lsp: require("vim.lsp.health").check()

- LSP log level : WARN
- Log path: /home/tof/.local/state/nvim_astro/lsp.log
- Log size: 10689 KB

vim.lsp: Active Clients ~
- No active clients

==============================================================================
vim.treesitter: require("vim.treesitter.health").check()

- Nvim runtime ABI version: 14
- OK Parser: bash       ABI: 14, path: /home/tof/.local/share/nvim_astro/lazy/nvim-treesitter/parser/bash.so
- OK Parser: css        ABI: 14, path: /home/tof/.local/share/nvim_astro/lazy/nvim-treesitter/parser/css.so
- OK Parser: html       ABI: 14, path: /home/tof/.local/share/nvim_astro/lazy/nvim-treesitter/parser/html.so
- OK Parser: javascript ABI: 14, path: /home/tof/.local/share/nvim_astro/lazy/nvim-treesitter/parser/javascript.so
- OK Parser: json       ABI: 14, path: /home/tof/.local/share/nvim_astro/lazy/nvim-treesitter/parser/json.so
- OK Parser: jsonc      ABI: 13, path: /home/tof/.local/share/nvim_astro/lazy/nvim-treesitter/parser/jsonc.so
- OK Parser: lua        ABI: 14, path: /home/tof/.local/share/nvim_astro/lazy/nvim-treesitter/parser/lua.so
- OK Parser: luap       ABI: 14, path: /home/tof/.local/share/nvim_astro/lazy/nvim-treesitter/parser/luap.so
- OK Parser: markdown   ABI: 14, path: /home/tof/.local/share/nvim_astro/lazy/nvim-treesitter/parser/markdown.so
- OK Parser: markdown_inline ABI: 14, path: /home/tof/.local/share/nvim_astro/lazy/nvim-treesitter/parser/markdown_inline.so
- OK Parser: php        ABI: 14, path: /home/tof/.local/share/nvim_astro/lazy/nvim-treesitter/parser/php.so
- OK Parser: regex      ABI: 14, path: /home/tof/.local/share/nvim_astro/lazy/nvim-treesitter/parser/regex.so
- OK Parser: scss       ABI: 13, path: /home/tof/.local/share/nvim_astro/lazy/nvim-treesitter/parser/scss.so
- OK Parser: tsx        ABI: 14, path: /home/tof/.local/share/nvim_astro/lazy/nvim-treesitter/parser/tsx.so
- OK Parser: typescript ABI: 14, path: /home/tof/.local/share/nvim_astro/lazy/nvim-treesitter/parser/typescript.so
- OK Parser: vim        ABI: 14, path: /home/tof/.local/share/nvim_astro/lazy/nvim-treesitter/parser/vim.so
- OK Parser: vue        ABI: 13, path: /home/tof/.local/share/nvim_astro/lazy/nvim-treesitter/parser/vue.so
- OK Parser: bash       ABI: 14, path: /home/tof/.local/share/bob/nightly/nvim-linux64/lib/nvim/parser/bash.so
- OK Parser: c          ABI: 14, path: /home/tof/.local/share/bob/nightly/nvim-linux64/lib/nvim/parser/c.so
- OK Parser: lua        ABI: 14, path: /home/tof/.local/share/bob/nightly/nvim-linux64/lib/nvim/parser/lua.so
- OK Parser: markdown   ABI: 14, path: /home/tof/.local/share/bob/nightly/nvim-linux64/lib/nvim/parser/markdown.so
- OK Parser: markdown_inline ABI: 14, path: /home/tof/.local/share/bob/nightly/nvim-linux64/lib/nvim/parser/markdown_inline.so
- OK Parser: python     ABI: 14, path: /home/tof/.local/share/bob/nightly/nvim-linux64/lib/nvim/parser/python.so
- OK Parser: query      ABI: 14, path: /home/tof/.local/share/bob/nightly/nvim-linux64/lib/nvim/parser/query.so
- OK Parser: vim        ABI: 14, path: /home/tof/.local/share/bob/nightly/nvim-linux64/lib/nvim/parser/vim.so
- OK Parser: vimdoc     ABI: 14, path: /home/tof/.local/share/bob/nightly/nvim-linux64/lib/nvim/parser/vimdoc.so

==============================================================================
which-key: require("which-key.health").check()

WhichKey: checking conflicting keymaps ~
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"t"**
- rhs: ` `
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"ys"**
- rhs: `<Plug>(nvim-surround-normal)`
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"yS"**
- rhs: `<Plug>(nvim-surround-normal-line)`
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"\\"**
- rhs: `<Cmd>split<CR>`

### Describe the bug

with : 
channel = "stable" 
branch = "nightly"
nvim = 0.9.2 or 0.10

If I open un file (php / html), I get an error with indent-blankline plugin

### Steps to Reproduce

Open a php file (or html ...)

### Expected behavior

no error 

### Screenshots

![astronvim](https://github.com/AstroNvim/AstroNvim/assets/2989137/c21e05f4-025e-4df8-899d-10cadbfeb62b)

**Comment by mehalter** [comment]
indent blankline has been updated to v3 which has a change in their interface. You just need to update your configuration to the new setup.
