### ISSUE TITLE
Indent-blanklines plugin is missed

### ISSUE THREAD

**Issue by kobzar** [AstroNvim/AstroNvim#2324]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Any

### Terminal/GUI

Any

### AstroNvim Health

NO Aastronvim problem
3.37.2 Version

### Describe the bug

```lua
Failed to run `config` for indent-blankline.nvim                                                        .../nvim/lazy/indent-blankline.nvim/lua/ibl/inlay_hints.lua:42: attempt to index field 'Methods' (a nil value)
# stacktrace:                                                                                              - /indent-blankline.nvim/lua/ibl/inlay_hints.lua:42 in setup                                            - /indent-blankline.nvim/lua/ibl/init.lua:43 in setup                                                   - /indent-blankline.nvim/lua/ibl/init.lua:59 in setup                                                   - ~/.config/nvim/lua/astronvim/utils/init.lua:145
```

This issue is open on plugin page
https://github.com/lukas-reineke/indent-blankline.nvim/issues/710
Error in indent-blanklines plugin

But in AstroNvim is still older version 
```
        version 3.2.6
        tag     v3.2.6
        branch  master
        commit  84022cc
        readme  README.md
        help    |indent-blankline.txt|
        event    AstroFile 
```

 

### Steps to Reproduce

Just open file (python for example)

### Expected behavior

*

**Comment by chaozwn** [comment]
me too

**Comment by mehalter** [comment]
This is a bug in indent blankline as mentioned in the issue. It is resolved on their master branch and will be resolved once they tag a new release! Thanks for reporting, but I'll go ahead and close this since it doesn't require any action in the AstroNvim code.

**Comment by mehalter** [comment]
For anyone that runs into this, a new version of `indent-blankline` has been tagged.
