### ISSUE TITLE
Fresh install, module 'lazy' not found

### ISSUE THREAD

**Issue by randunel** [AstroNvim/AstroNvim#2343]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Ubuntu 22.04.3 LTS

### Terminal/GUI

GNOME Terminal 3.44.0 using VTE 0.68.0 +BIDI +GNUTLS +ICU +SYSTEMD

### AstroNvim Health

     2 astronvim: require("astronvim.health").check()
     3 
     4 AstroNvim
     5 - AstroNvim Version: v3.37.7
     6 - Neovim Version: v0.9.1
     7 - OK Using stable Neovim >= 0.8.0
     8 - OK git is installed: Used for core functionality such as updater and plugin management
     9 - OK xdg-open is installed: Used for gx mapping for opening files with system opener (Optional)
    10 - WARNING lazygit is not installed: Used for mappings to pull up git TUI (Optional)
    11 - OK node is installed: Used for mappings to pull up node REPL (Optional)
    12 - WARNING gdu is not installed: Used for mappings to pull up disk usage analyzer (Optional)
    13 - WARNING btm is not installed: Used for mappings to pull up system monitor (Optional)
    14 - OK python3 is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Fresh install of Ubuntu 22.04.3 LTS, the very first things I installed were regolith-desktop and deps, nodejs via n, neovim 0.9.1 and astronvim. When starting up:

```
Error detected while processing /home/mihai/.config/nvim/init.lua:
Failed to load astronvim.lazy

/home/mihai/.config/nvim/lua/astronvim/lazy.lua:43: module 'lazy' not found:
^Ino field package.preload['lazy']
cache_loader: module lazy not found
cache_loader_lib: module lazy not found
^Ino file './lazy.lua'
^Ino file '/build/nvim/parts/nvim/build/.deps/usr/share/luajit-2.1.0-beta3/lazy.lua'
^Ino file '/usr/local/share/lua/5.1/lazy.lua'
^Ino file '/usr/local/share/lua/5.1/lazy/init.lua'
^Ino file '/build/nvim/parts/nvim/build/.deps/usr/share/lua/5.1/lazy.lua'
^Ino file '/build/nvim/parts/nvim/build/.deps/usr/share/lua/5.1/lazy/init.lua'
^Ino file './lazy.so'
^Ino file '/usr/local/lib/lua/5.1/lazy.so'
^Ino file '/build/nvim/parts/nvim/build/.deps/usr/lib/lua/5.1/lazy.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
```

### Steps to Reproduce

1. Install Ubuntu 22.04.3 LTS from scratch
2. Install regolith desktop, nodejs and neovim 0.9.1
3. Install astronvim by cloning `git clone --depth 1 https://github.com/AstroNvim/AstroNvim ~/.config/nvim`

### Expected behavior

Astronvim to work, quoted error to not exist

**Comment by mehalter** [comment]
Do you see na successful clone of lazy.nvim at `~/.local/share/nvim/lazy/lazy.nvim`?

**Comment by randunel** [comment]
```
ls -alh ~/.local/share/nvim/lazy/lazy.nvim/
total 12K
drwxrwxr-x 3 mihai mihai 4,0K oct 19 21:14 .
drwxrwxr-x 3 mihai mihai 4,0K oct 19 21:14 ..
drwxrwxr-x 8 mihai mihai 4,0K oct 19 21:14 .git
```

and 


```
ls -alh ~/.local/share/nvim/lazy/lazy.nvim/.git/
total 56K
drwxrwxr-x 8 mihai mihai 4,0K oct 19 21:14 .
drwxrwxr-x 3 mihai mihai 4,0K oct 19 21:14 ..
drwxrwxr-x 2 mihai mihai 4,0K oct 19 21:14 branches
-rw-rw-r-- 1 mihai mihai  250 oct 19 21:14 config
-rw-rw-r-- 1 mihai mihai   73 oct 19 21:14 description
-rw-rw-r-- 1 mihai mihai   41 oct 19 21:14 HEAD
drwxrwxr-x 2 mihai mihai 4,0K oct 19 21:14 hooks
drwxrwxr-x 2 mihai mihai 4,0K oct 19 21:14 info
drwxrwxr-x 3 mihai mihai 4,0K oct 19 21:14 logs
drwxrwxr-x 4 mihai mihai 4,0K oct 19 21:14 objects
-rw-rw-r-- 1 mihai mihai 8,3K oct 19 21:14 packed-refs
drwxrwxr-x 5 mihai mihai 4,0K oct 19 21:14 refs
```

but the contents of the repo appear to have been deleted:

```
git status
Not currently on any branch.
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	deleted:    .github/ISSUE_TEMPLATE/bug_report.yml
	deleted:    .github/ISSUE_TEMPLATE/feature_request.yml
	deleted:    .github/workflows/ci.yml
	deleted:    .gitignore
	deleted:    .markdownlint.yaml
	deleted:    .neoconf.json
	deleted:    CHANGELOG.md
	deleted:    LICENSE
	deleted:    README.md
	deleted:    TODO.md
```

Did a `git reset --hard` in there and it now works. I wonder what caused the deletion, it must be some sort of PEBKAC. Thank you!

**Comment by ChillFire22** [comment]
Same problem happened to me while trying to install lazy.nvim
Difference for my machine is that I had it previously and deleted everything following the uninstall guide before restarting

**Comment by aep** [comment]
had the same issue because when i first opened nvim it was blank, so i quit it.
but actually you just need to wait a few seconds before it starts installing
