### ISSUE TITLE
LSP Diagnostics cause the code to jump 

### ISSUE THREAD

**Issue by kurosh-z** [AstroNvim/AstroNvim#2344]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOs

### Terminal/GUI

alacritty

### AstroNvim Health

astronvim: require("astronvim.health").check()
AstroNvim ~
- AstroNvim Version: v3.37.7
- Neovim Version: v0.9.4
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- WARNING `lazygit` is not installed:

### Describe the bug

There appears to be an issue with the padding or margin settings of the diagnostics icon, causing the code to shift to the side to accommodate the icon. Is there a way to prevent this behaviour?

### Steps to Reproduce

open a file and type something.

### Expected behavior

The code should stay where it is. 

### Screenshots

![jumping](https://github.com/AstroNvim/AstroNvim/assets/32224317/911f3bf1-5576-4368-9602-a1edab5869d8)

**Comment by mehalter** [comment]
It looks like you are setting `signcolumn=auto` somewhere in your configuration which causes this behavior. You should look to see where/why this is getting set. In core AstroNvim we set `signcolumn=yes`

**Comment by mehalter** [comment]
`:h signcolumn` for details on what the available options are
