### ISSUE TITLE
Change only the desc field in maps

### ISSUE THREAD

**Issue by MOldtime** [AstroNvim/AstroNvim#2345]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Windows 11

### Terminal/GUI

Neovide

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.37.7
- Neovim Version: v0.9.4
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `explorer` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

path: `lua/user/mappings.lua`
```lua
return function(tables) {
 tables.n["<leader>l"].desc = "test"
}
```
This is an error, very strange
>  attempt to index field '<leader>l' (a nil value)

How should I write it? I just want to change the default `desc` and leave everything else unchanged.

### Steps to Reproduce

nil

### Expected behavior

nil

**Comment by mehalter** [comment]
You just need to remember to return the table at the end of the function. Other than that it looks alright!

**Comment by MOldtime** [comment]
But when I used this function, I found that it was executed twice
For example:
```lua
return function(tables) {
print("test")
return tables
}
```
Is this expected behavior?
![图片](https://github.com/AstroNvim/AstroNvim/assets/38435967/c609eaf1-4d15-43b4-b9a2-12b06feb8ee7)

**Comment by mehalter** [comment]
I cannot replicate this with a stock AstroNvim installation. You might have a lingering test print somewhere else

**Comment by MOldtime** [comment]
I cleared my configuration. It seems to be caused by other places. Sorry for causing trouble to you.

**Comment by MOldtime** [comment]
The problem disappeared, I used empty_map_table() which caused the problem
