### ISSUE TITLE
E5108: Error executing lua .../0x/.config/nvim/lua/astronvim/utils/status/provider.lua:82: dlsym(RTLD_DEFAULT, compute_foldcolumn): symbol not found

### ISSUE THREAD

**Issue by 0xUgochukwu** [AstroNvim/AstroNvim#2347]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

MacOS Sonoma

### Terminal/GUI

Wezterm/iTerm2

### AstroNvim Health

<img width="664" alt="Screenshot 2023-10-27 at 09 48 49" src="https://github.com/AstroNvim/AstroNvim/assets/106848093/e0b3595d-0b29-4a9d-bfdc-178ec788e0fe">

### Describe the bug

I just installed Astronvim and 
<img width="1104" alt="Screenshot 2023-10-26 at 22 42 00" src="https://github.com/AstroNvim/AstroNvim/assets/106848093/93e75641-374e-4a8d-a2e7-03a3b0dd2d35">
I get this error when I launch nvim I think it's related to heirline but I am not sure what is causing it

### Steps to Reproduce

1. Install Astronvim on new machine running MacOS Sonoma
2. Run `nvim` and let the packages and plugins instal
3. Close it and run`nvim` again

### Expected behavior

You should get this error:

<img width="1104" alt="Screenshot 2023-10-26 at 22 42 00" src="https://github.com/AstroNvim/AstroNvim/assets/106848093/c7bc7207-4b78-4048-a27c-571653d16c31">

### Screenshots

<img width="1104" alt="Screenshot 2023-10-26 at 22 42 00" src="https://github.com/AstroNvim/AstroNvim/assets/106848093/9248a3de-6ae2-43da-bb5f-d0001f06e6ed">
<img width="1440" alt="Screenshot 2023-10-27 at 09 52 35" src="https://github.com/AstroNvim/AstroNvim/assets/106848093/b3d17461-2a87-40a9-8522-4e02aa433061">

**Comment by 0xUgochukwu** [comment]
Installed the `--HEAD` version of Neovim and the errors have disappeared

**Comment by mehalter** [comment]
Duplicate of #2311
