### ISSUE TITLE
Slow directory opening in file explorer when using 'o' key

### ISSUE THREAD

**Issue by bcdnko** [AstroNvim/AstroNvim#2351]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Ubuntu 22.04

### Terminal/GUI

Gnome Terminal 3.44

### AstroNvim Health

astronvim: require("astronvim.health").check()
========================================================================
## AstroNvim
  - INFO: AstroNvim Version: v3.37.8
  - INFO: Neovim Version: v0.8.3
  - OK: Using stable Neovim >= 0.8.0
  - OK: `git` is installed: Used for core functionality such as updater and plugin management
  - OK: `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
  - OK: `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
  - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
  - OK: `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
  - WARNING: `btm` is not installed: Used for mappings to pull up system monitor (Optional)
  - OK: `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

When I try to open any directory in the file explorer with 'o' key it takes approximately 1 second to do. It doesn't matter whether there are many files or just a few. It started to happen after I did a fresh install (previously I used some old version and I don't remember which). And it still works fast if I use enter instead.

### Steps to Reproduce

1. make fresh install (following https://docs.astronvim.com/)
2. open nvim
3. open file explorer <leader>e
4. open any directory with o

### Expected behavior

Should open lightning fast :)

**Comment by mehalter** [comment]
This is because there are bindings that start with `o` now. I will remove the `o` mapping in v4 and that will resolve it. Then you can just open the files with enter

**Comment by bcdnko** [comment]
please don't remove it =( it's very common to many file trees in vim and vim-like editors and it's so convenient

**Comment by mehalter** [comment]
It's better for us to not change a ton of defaults. To confuse users less. The only other solution is to completely remove the order by mappings in neo-tree. It's better for the neo tree docs to be as close as possible to our configuration so users know what to expect when they look at the docs

**Comment by mehalter** [comment]
If you like `o` then you can definitely go into your configuration and remove the order by mappings and add in the open mapping

**Comment by mehalter** [comment]
AstroNvim's main goal is to supplement and improve these plugins defaults rather than directly go against them

**Comment by mehalter** [comment]
Actually it does look like I have already removed the `o` mapping in v4 for this reason! I went ahead and also made shift+enter do system open file
