### ISSUE TITLE
Neoconf setup is not ran when setup_handlers is overrdden

### ISSUE THREAD

**Issue by s1n7ax** [AstroNvim/AstroNvim#2352]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

NixOs 23

### Terminal/GUI

Alacritty

### AstroNvim Health

```

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: unknown
- Neovim Version: v0.9.4
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)
```

### Describe the bug

I'm trying to fix https://github.com/AstroNvim/docs/issues/128 the best way possible. In the process I noticed that when a `setup_handlers` is set, Neoconf configuration stops working.

### Steps to Reproduce

1. Add following to user config

```lua
-- ~/.config/astronvim/user/lua/init.lua

return {
	colorscheme = 'catppuccin-mocha',
	lazy = {
		change_detection = {
			notify = false,
		},
	},

	lsp = {
		setup_handlers = {
			jdtls = function(_, opts)
				vim.api.nvim_create_autocmd('Filetype', {
					pattern = 'java',
					callback = function()
						if opts.root_dir and opts.root_dir ~= '' then
							require('jdtls').start_or_attach(opts)
						end
					end,
				})
			end,
		},
	},
}
```

2. Create a java project
3. Add . neoconf.json file in the project

```json
{
	"lspconfig": {
		"jdtls": {
			"java.configuration.runtimes": [
				{ "name":"JavaSE-17", "path": "/root/.sdkman/candidates/java/17.0.9-tem" },
			]
		}
	}
}
```
4. Run neovim
5. Open a .java file
6. Run `Neoconf lsp`

### Expected behavior

Configuration added in the `.neoconf` should be present in the floating window but it's empty.

neoconf setup call cannot be added in the setup handler since it should be called before any lspconfig setup calls.

```lua
	lsp = {
		setup_handlers = {
			jdtls = function(_, opts)
				require('neoconf').setup({})
                                -- ^^^^^^^^^^^^^^^^^^^^^^^

				vim.api.nvim_create_autocmd('Filetype', {
					pattern = 'java',
					callback = function()
						if opts.root_dir and opts.root_dir ~= '' then
							require('jdtls').start_or_attach(opts)
						end
					end,
				})
			end,
		},
	}
```

Above would produce following error

```
Setup `require("neoconf").setup()` should be run **BEFORE** setting up any lsp server with lspconfig
```

### Screenshots

When no `setup_handlers` present 

![image](https://github.com/AstroNvim/AstroNvim/assets/18459807/b3e1ddda-2971-4bb9-bfc7-1bba675f1b08)

When `jdtls` is overridden in `setup_handlers`

![image](https://github.com/AstroNvim/AstroNvim/assets/18459807/55bb8bcd-0793-4a2a-887b-fdc2d1c1dfa2)

**Comment by mehalter** [comment]
Neoconf has a plugin for `lspconfig` you are not using lspconfig to start the Java language server. So that is out of scope of that plugin and out of the control of AstroNvim since it's upstream

**Comment by mehalter** [comment]
You could try to make a feature request upstream to neoconf, but there's basically no way to generalize that since the jdtls plugin handles everything.
