### ISSUE TITLE
Can't remap control-hjkl in normal mode

### ISSUE THREAD

**Issue by awarebayes** [AstroNvim/AstroNvim#2353]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Ubuntu 20.04

### Terminal/GUI

kitty

### AstroNvim Health

   2   astronvim: require("astronvim.health").check()
   3
   4   AstroNvim
   5   - AstroNvim Version: v3.36.12
   6   - Neovim Version: v0.9.2
   7   - OK Using stable Neovim >= 0.8.0
   8   - OK git is installed: Used for core functionality such as updater and plugin management
   9   - OK xdg-open is installed: Used for gx mapping for opening files with system opener (Optional)
  10   - OK lazygit is installed: Used for mappings to pull up git TUI (Optional)
  11   - OK node is installed: Used for mappings to pull up node REPL (Optional)
  12   - OK gdu is installed: Used for mappings to pull up disk usage analyzer (Optional)
  13   - WARNING btm is not installed: Used for mappings to pull up system monitor (Optional)
  14   - OK python is installed: Used for mappings to pull up python REPL (Optional)
  15

### Describe the bug

I have installed tmux navigator and try to remap Control-hjkl to navigate between buffers and tmux. The problem is that sometimes the bindings work, sometimes they do not. Randomly. Some keybindings may work, others may not. When I explicitly run commands in the vim command line, they work flawlessly. 

Here is a fragment from my user/mappings.lua for normal mod
```
    ["<c-l>"] = { "<cmd>TmuxNavigateLeft<CR>", noremap = true },
    ["<c-h>"] = { "<cmd>TmuxNavigateRight<CR>", noremap = true },
    ["<c-k>"] = { "<cmd>TmuxNavigateUp<CR>", noremap = true },
    ["<c-j>"] = { "<cmd>TmuxNavigateDown<CR>", noremap = true },
```

This I believe can be done without tmux-navigator. Any plugin will work, just cant remap the keys themselves

### Steps to Reproduce

1. Go to mappings.lua
2.  Try to remap c-hjkl to anything
3. They will only work some of the time upon launching

### Expected behavior

They should remap successfully

### Additional Context

None

**Comment by mehalter** [comment]
The key needs to match what we use in our table or else there is a race condition. We standardize on capital modifiers. so `<C-h>` for example

**Comment by mehalter** [comment]
Also just a heads up, this plugin you are setting up is probably unnecessary. We use [smart-splits.nvim](https://github.com/mrjones2014/smart-splits.nvim) by default which supports tmux out of the box :) you can look at the docs on the plugin for how to further integrate it with your multiplexer of choice.

**Comment by awarebayes** [comment]
I copied the keybinds from smart-splits into my tmux.conf.
Deleted all traces if TmuxNavigator from both tmux and neovim, relaunched, did Lazy update and clean, AstroUpdate.
It navigates from tmux to tmux and from tmux to nvim. But I cannot navigate from nvim to tmux. It also navigates inside vim buffers. The previous one I could debug by typing console command with :, but I dont know how to approach debugging why this does not work nvim -> tmux, because it launches lua code. Maybe `if is_available "smart-splits.nvim" then` does not execute? I search my lazy and it's of course installed, maybe not lazily loaded?

Is there some other way I have to set it up manually?

**Comment by mehalter** [comment]
When you navigate between the windows within nvim, do you see in `:Lazy` that the `smart-splits` plugin has been loaded?

**Comment by mehalter** [comment]
![2023-10-31_12:21:31_screenshot](https://github.com/AstroNvim/AstroNvim/assets/1591837/2e0ac11f-d53b-4944-a54d-7a4b8125088e)

should be like this

**Comment by mehalter** [comment]
I just tested it with a fresh AstroNvim installation and it seems to work out of the box moving within vim panels and tmux panels together

Also once I added in the integration code to my `tmux.conf` then I was able to move between tmux windows and from tmux to neovim

**Comment by mehalter** [comment]
Here is an example of me navigating around with `<C-{h,j,k,l}>` in a tmux session with splits in both neovim and tmux:

https://asciinema.org/a/tNSgvfMYmyMbWmNE7y2s6oG9e

**Comment by awarebayes** [comment]
I just deleted my ~/.config/nvim and ~/.local/share/nvim, reinstalled astro, didnt make any modifications. Nothing, sticking to nvim tmux navigator
