### ISSUE TITLE
Add a control variable to automatically close the DAP UI after it finishes running.

### ISSUE THREAD

**Issue by chaozwn** [AstroNvim/AstroNvim#2357]
### Is your feature related to a problem?

 Most of the time, when debugging, I don't want the program to exit the DAP interface after it finishes running.

### Describe the new feature

Add a control variable to automatically close the DAP UI after it finishes running.
link to file: lua/plugins/configs/nvim-dap-ui.lua

**Comment by mehalter** [comment]
This is already set up as described by dap uis documentation: https://github.com/AstroNvim/AstroNvim/blob/main/lua/plugins/configs/nvim-dap-ui.lua

I have found it's not the most stable in closing at the end. Not sure why, but unrelated to AstroNvim.

You can also extend the plugin configuration functions to add more hooks to nvim-dap as you like

**Comment by mehalter** [comment]
If you don't want it to terminate you can simply remove the `dap_ui` hook from the desired events in dap

**Comment by chaozwn** [comment]
> This is already set up as described by dap uis documentation: https://github.com/AstroNvim/AstroNvim/blob/main/lua/plugins/configs/nvim-dap-ui.lua
> 
> I have found it's not the most stable in closing at the end. Not sure why, but unrelated to AstroNvim.
> 
> You can also extend the plugin configuration functions to add or remove hooks to nvim-dap as you like

I tried to override this configuration, but it didn't take effect when debugging Python.
![image](https://github.com/AstroNvim/AstroNvim/assets/51357674/04154dda-cb41-443c-938c-e9a11576b70c)

**Comment by mehalter** [comment]
You need to override the `config` function. Not the `opts`

**Comment by mehalter** [comment]
You can also just delete lines 35 and 36 in that screenshot as well as changing `opts` to `config`

**Comment by chaozwn** [comment]
> You can also just delete lines 35 and 36 in that screenshot as well as changing `opts` to `config`
 Thank you! It's working perfectly fine. Here's a configuration diagram for reference, which can be helpful for others.

![image](https://github.com/AstroNvim/AstroNvim/assets/51357674/aab4cd70-490b-4f54-be4c-9de0b28a91c6)
