### ISSUE TITLE
My autocomplete is not working in astronvim

### ISSUE THREAD

**Issue by pujiragil** [AstroNvim/AstroNvim#2367]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Archcraft x86_64

### Terminal/GUI

alacritty

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.37.12
- Neovim Version: v0.9.4
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Sorry, everyone. I am new to Neovim and Astronvim. I attempted to use Astronvim for a simple Express.js project, but I encountered an issue with autocompletion. I tried installing @types/express in the package.json file, but the problem persists. Perhaps I made a mistake. Please help me correct it.

### Steps to Reproduce

1. I have installed tsserver
2. also install @types/express

### Expected behavior

autocompletion should work properly but I don't know why it's not working

### Screenshots

**post.js**

![Screenshot-15_11_2023-08-54-55](https://github.com/AstroNvim/AstroNvim/assets/72433552/ea14f2ff-bdc4-4a33-ad46-6938ba4cba0c)

**package.json**

![Screenshot-15_11_2023-08-57-02](https://github.com/AstroNvim/AstroNvim/assets/72433552/3ec8defa-0bb2-4b08-8b20-9eb85340ee35)

**Comment by mehalter** [comment]
I cannot replicate this following your instructions. I am starting with a completely fresh AstroNvim installation, installing `prettier`, `jsonls`, and `tsserver` through Mason, running `npm install @types/express` in an empty folder and then start editing a `post.js` file in that folder:

![2023-11-15_15:49:53_screenshot](https://github.com/AstroNvim/AstroNvim/assets/1591837/b65c88d6-0752-4930-8d20-db7e8d5c5f69)

Then I edited the `package.json` and tried adding a field:

![2023-11-15_15:50:50_screenshot](https://github.com/AstroNvim/AstroNvim/assets/1591837/f97b54bd-518c-4727-8a4e-52ccb5b3f094)

You probably have something in your user configuration breaking the auto completion. Can you replicate on a fresh installation without your `user/` folder?

**Comment by pujiragil** [comment]
> I cannot replicate this following your instructions. I am starting with a completely fresh AstroNvim installation, installing `prettier`, `jsonls`, and `tsserver` through Mason, running `npm install @types/express` in an empty folder and then start editing a `post.js` file in that folder:
> 
> ![2023-11-15_15:49:53_screenshot](https://user-images.githubusercontent.com/1591837/283244774-b65c88d6-0752-4930-8d20-db7e8d5c5f69.png)
> 
> Then I edited the `package.json` and tried adding a field:
> 
> ![2023-11-15_15:50:50_screenshot](https://user-images.githubusercontent.com/1591837/283244694-f97b54bd-518c-4727-8a4e-52ccb5b3f094.png)
> 
> You probably have something in your user configuration breaking the auto completion. Can you replicate on a fresh installation without your `user/` folder?

I apologize if there was any confusion, but after reinstalling astronvim and this project, the Express application is running normally. I don't know what caused this to happen, but I appreciate your help

**Comment by mehalter** [comment]
why was this reopened?

**Comment by pujiragil** [comment]
![Screenshot-22_11_2023-10-26-20](https://github.com/AstroNvim/AstroNvim/assets/72433552/d0fbfbfc-f2d6-4b1a-bcf5-da92dd619999)

I apologize for reopening the issue. I just want to ask if autocomplete is indeed like that by default? I have tried it on .js, .jsx, .tsx files, and the results are all the same.

**Comment by mehalter** [comment]
as I stated before I cannot replicate this. Can you try without your `user/` folder. You probably have something in there that is breaking it. If you share your user configuration with me (maybe a link to a github repo you push it to?) I can test it out and maybe help you find your error

**Comment by mehalter** [comment]
I cannot replicate the issue with your configuration from the repo you have here: https://github.com/pujiragil/astronvim_config
![2023-11-22_10:56:13_screenshot](https://github.com/AstroNvim/AstroNvim/assets/1591837/33f31401-fc89-4231-9d23-2e8d3c634bec)

**Comment by pujiragil** [comment]
> as I stated before I cannot replicate this. Can you try without your `user/` folder. You probably have something in there that is breaking it. If you share your user configuration with me (maybe a link to a github repo you push it to?) I can test it out and maybe help you find your error

I have installed AstroNvim without the /user folder, and the result is still the same. I only installed a few packages as follows.

without /user folder
![Screenshot-23_11_2023-06-19-49](https://github.com/AstroNvim/AstroNvim/assets/72433552/47f26730-96c7-466b-bae9-a89a7d71a050)

mason
![Screenshot-23_11_2023-06-19-56](https://github.com/AstroNvim/AstroNvim/assets/72433552/d5c4bfd4-c374-48a9-b8db-4ca612918781)

treesitter
![Screenshot-23_11_2023-06-20-12](https://github.com/AstroNvim/AstroNvim/assets/72433552/8dd3f41a-1a97-4906-ad0d-93444f67062e)

I don't know why this is still not working in my case. I have also deleted the directories .config/nvim, .local/share/nvim, .local/state/nvim, .cache/nvim before reinstalling AstroNvim.

**Comment by mehalter** [comment]
In all of your screenshots you are not in insert mode. Maybe a screen recording using something like asciinema?

**Comment by pujiragil** [comment]
![Screenshot-23_11_2023-06-38-28](https://github.com/AstroNvim/AstroNvim/assets/72433552/422f7f22-ceef-49a0-94b0-604b05d12220)

![Screenshot-23_11_2023-06-39-05](https://github.com/AstroNvim/AstroNvim/assets/72433552/a98c6718-9e78-434c-b78d-75556b169857)

![Screenshot-23_11_2023-06-39-23](https://github.com/AstroNvim/AstroNvim/assets/72433552/3e10f8b0-dd8e-4bb1-8d94-fc0b1cf34fe1)

Actually, autocomplete works, but when I press enter, the component becomes a function. Then, when I remove the parentheses () and replace them with /, a div appears behind it

**Comment by mehalter** [comment]
Ah glad to see the original issue is alright. This will need to be resolved in how you configure the auto tag plugin to meet your needs

**Comment by mehalter** [comment]
Basically `nvim-ts-autotag` is trying to close the tag that is open and not correctly identifying this pattern. My guess is it's base rules don't handle this type of react code

**Comment by pujiragil** [comment]
So I just need to disable it?

**Comment by mehalter** [comment]
You can disable it for sure as an easy fix or you can look into configuring it more closely. We are simply providing it with it's defaults

**Comment by pujiragil** [comment]
I found the same issue https://github.com/windwp/nvim-ts-autotag/issues/151 . Thank you for helping me. May God bless you.

**Comment by mehalter** [comment]
@pujiragil this is resolved on AstroNvim nightly

**Comment by pujiragil** [comment]
yep this works great

**Comment by pujiragil** [comment]
Hi @mehalter , can you tell me how to configure typescript.preferences.importModuleSpecifier in AstroNvim? I'm using the absolute import feature from Next.js default configuration and it works fine, but the issue is when I import a component, auto import provides an incorrect path.

![Screenshot-27_11_2023-04-25-28](https://github.com/AstroNvim/AstroNvim/assets/72433552/24dece25-93ee-4e7a-bf1d-ac38f04c4b65)

tsconfig.json
![Screenshot-27_11_2023-04-32-28](https://github.com/AstroNvim/AstroNvim/assets/72433552/a8bc759d-fe10-4cd5-b556-c81c216d441f)

Then I tried it on VSCode, and it also applies to VSCode, but after I changed typescript.preferences.importModuleSpecifier to 'non-relative', it works fine on VSCode.

settings
![Screenshot-27_11_2023-04-23-14](https://github.com/AstroNvim/AstroNvim/assets/72433552/89b56126-870e-45c2-b5f8-a3847dbca067)

result
![Screenshot-27_11_2023-04-24-10](https://github.com/AstroNvim/AstroNvim/assets/72433552/8f6e500a-6f19-4ce3-8e15-38dce1d34992)
