### ISSUE TITLE
setting `cmp.source.entry_filter` has not effect

### ISSUE THREAD

**Issue by 1538379200** [AstroNvim/AstroNvim#2370]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

windows 11

### Terminal/GUI

PowerShell7/neovide

### AstroNvim Health

![image](https://github.com/AstroNvim/AstroNvim/assets/42434762/5e164a38-ff4d-41e9-9e1a-6e96c404b643)

### Describe the bug

The text filtering function is not functioning properly despite adding the entry_filter setting to cmp.
![image](https://github.com/AstroNvim/AstroNvim/assets/42434762/5608f499-4df9-4429-b2db-a5f719052c1a)

in nvim:
![image](https://github.com/AstroNvim/AstroNvim/assets/42434762/2b98b939-1d82-413c-9b6d-71e52044f62c)

### Steps to Reproduce

1. go to cmp config file
2. add entry_filter 

### Expected behavior

The filtering operation can be done without any issues.

**Comment by mehalter** [comment]
Can you please provide the full `cmp` plugin specification text you are trying

**Comment by mehalter** [comment]
Oh wait I see, you are pointing out buffer provided entries and not lsp provided entries which are what you are filtering

**Comment by 1538379200** [comment]
@mehalter The appropriate course of action eludes me at present, I found this

https://github.com/hrsh7th/cmp-nvim-lsp/issues/20
