### ISSUE TITLE
Typo in foldcolumn function for heirline config causing problems for code folding

### ISSUE THREAD

**Issue by PyDev19** [AstroNvim/AstroNvim#2374]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Windows 10

### Terminal/GUI

Neovide

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.38.0
- Neovim Version: v0.9.4
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `explorer` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- WARNING `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Typo in the file [astronvim.utils.status.component](https://github.com/AstroNvim/AstroNvim/blob/main/lua/astronvim/utils/status/component.lua) at function `M.foldcolumn`, instead of `fillchars.foldcolse` it should be `fillchars.foldclose` this was causing problems in opening a closed code fold. I don't think this requires a pull request as it is a very small issue.

### Steps to Reproduce

1. Fresh install of AstroVim
2. Open the config
3. Go to `lua/astronvim/utils/status/component.lua`
4. Go to function `M.foldcolumn`
5. Check the function for this typo

### Expected behavior

I was clicking on the folded code to open it back and it wasn't doing anything when it should have been opening the folded code.

**Comment by mehalter** [comment]
Thanks for reporting this! I'll get right on it when I get back to a computer :)

**Comment by mehalter** [comment]
@PyDev19 just pushed a commit to AstroNvim nightly. Could you please give it a test to see if it resolves everything and then I can make a release later today :)

**Comment by PyDev19** [comment]
@mehalter I am so sorry for responding now but yea thank you for fixing it!
