### ISSUE TITLE
Cannot move around using `C-hjkl`

### ISSUE THREAD

**Issue by rawnly** [AstroNvim/AstroNvim#2377]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macos 13.0

### Terminal/GUI

wezterm - kitty - alacritty

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.38.0
- Neovim Version: v0.9.4
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

I cannot move around split-views / windows using `C-h/j/k/l`

### Steps to Reproduce

Open a split view, try to focus it.

### Expected behavior

I'd expect to be able to move

### Additional Context

> [!IMPORTANT]
> It works using `<C-w> h/j/k/l`

**Comment by rawnly** [comment]
Link to my config here: https://github.com/rawnly/nvim-config

**Comment by rawnly** [comment]
Looks like the problem was caused by [fig](https://fig.io) uninstalling it fixed the problem. Is this issue related to it or neovim?

**Comment by mehalter** [comment]
This is unrelated to Neovim. If your terminal has its own bindings for those keys then you need to disable them or make new ones
