### ISSUE TITLE
Re-session doesn't trigger `User Astrofile` event when restoring a session from git branch

### ISSUE THREAD

**Issue by lougreenwood** [AstroNvim/AstroNvim#2378]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Latest=

### Terminal/GUI

iterm

### AstroNvim Health

```
AstroNvim Version: v3.38.0-35-gbd03fc3f
Neovim Version: v0.9.4
OK Using stable Neovim >= 0.8.0
OK git is installed: Used for core functionality such as updater and plugin management
OK open is installed: Used for gx mapping for opening files with system opener (Optional)
OK lazygit is installed: Used for mappings to pull up git TUI (Optional)
OK node is installed: Used for mappings to pull up node REPL (Optional)
OK gdu is installed: Used for mappings to pull up disk usage analyzer (Optional)
WARNING btm is not installed: Used for mappings to pull up system monitor (Optional)
OK python is installed: Used for mappings to pull up python REPL (Optional)
```

### Describe the bug

I'm using resession with the "[Create one session per git branch](https://github.com/stevearc/resession.nvim?tab=readme-ov-file#create-one-session-per-git-branch)" feature.

I have it setup like this in my `polish.lua` file:

```
return function()
  local resession = require "resession"

  local function get_session_name()
    local name = vim.fn.getcwd()
    local branch = vim.trim(vim.fn.system "git branch --show-current")
    if vim.v.shell_error == 0 then
      return name .. branch
    else
      return name
    end
  end

  vim.api.nvim_create_autocmd("VimEnter", {
    callback = function()
      -- Only load the session if nvim was started with no args
      if vim.fn.argc(-1) == 0 then resession.load(get_session_name(), { dir = "dirsession", silence_errors = true }) end
    end,
  })

  vim.api.nvim_create_autocmd("VimLeavePre", {
    callback = function() resession.save(get_session_name(), { dir = "dirsession", notify = false }) end,
  })
end
```

I'm additionally using [`tint.nvim`](https://github.com/levouh/tint.nvim) (config below), and I noticed that when a session is restored upon opening nvim in a dir which has a pre-saved session for a git branch that tint isn't applied until I move between splits.

```
  {
    "levouh/tint.nvim",
    event = "User AstroFile",
    config = function()
      require("tint").setup {
        tint = -40,                                                            -- Darken colors, use a positive value to brighten
        saturation = 0.10,                                                     -- Saturation to preserve
        transforms = {
          require("tint.transforms").tint_with_threshold(-80, "#1C1C1C", 150), -- Try to tint by `-100`, but keep all colors at least `150` away from `#1C1C1C`
          require("tint.transforms").saturate(0.3),
        },
      }
    end,
  },
```

Finally, I've also disabled `alpha.nvim`, not sure whether this would implicitly hide this bug by showing / closing a file and triggering the event.

What I did find is that if I remove the event for `tint.nvim` in it's lazy config and change it to `lazy = false` then the tinting is applied when nvim is opened and the session is restored automatically.

#### ℹ️  **NOTE**
I'm not sure if this is expected behaviour at all. I took a look in the `astronvim` codebase to see if it does anything specific with re-session to hook it into the `User AstroFile` event but I didn't see anything.

### Steps to Reproduce

- enable re-session in config
- use the above snippet to enable sessions for git branches
- enable tint.nvim using the above config
- disable `alpha.nvim`
- open nvim in a a dir with a git branch so that re-sesson saves a session for it and open some splits
- close nvim
- open it again and see that tint isn't tinting the in-active splits
- move between the splits or open a new split
- see that tint kicks in
- change the lazy config for `tint.nvim` so that it has `lazy = false` and the `event` field is commented out
- close nvim and re-open it in the same dir with the git branch and a saved session
- see that the tinting is immediately applied to the in-active windows

### Expected behavior

Using the re-session auto-load session for current git branch feature should somehow trigger the `Astro UserFile` event.

**Comment by mehalter** [comment]
Looks like you are missing a small change for making sure this plays nicely with lazy loading and asynchronicity. You basically just need to schedule the session loading on `VimEnter` so that it happens in the next part of the main event-loop rather than immediately.

```lua
    vim.api.nvim_create_autocmd("VimEnter", {
      callback = vim.schedule_wrap(function()
        -- Only load the session if nvim was started with no args
        if vim.fn.argc(-1) == 0 then
          require("resession").load(get_session_name(), { dir = "dirsession", silence_errors = true })
        end
      end),
    })
```

I tested this with the following minimal `user/init.lua` file:

```lua
return {
  options = {
    g = {
      resession_enabled = true,
    },
  },
  plugins = {
    { "goolord/alpha-nvim", enabled = false },
    {
      "levouh/tint.nvim",
      event = "User AstroFile",
      opts = function()
        return {
          tint = -40, -- Darken colors, use a positive value to brighten
          saturation = 0.10, -- Saturation to preserve
          transforms = {
            require("tint.transforms").tint_with_threshold(-80, "#1C1C1C", 150), -- Try to tint by `-100`, but keep all colors at least `150` away from `#1C1C1C`
            require("tint.transforms").saturate(0.3),
          },
        }
      end,
    },
  },
  polish = function()
    local function get_session_name()
      local name = vim.fn.getcwd()
      local branch = vim.trim(vim.fn.system "git branch --show-current")
      if vim.v.shell_error == 0 then
        return name .. branch
      else
        return name
      end
    end

    vim.api.nvim_create_autocmd("VimEnter", {
      callback = vim.schedule_wrap(function()
        -- Only load the session if nvim was started with no args
        if vim.fn.argc(-1) == 0 then
          require("resession").load(get_session_name(), { dir = "dirsession", silence_errors = true })
        end
      end),
    })

    vim.api.nvim_create_autocmd("VimLeavePre", {
      callback = function() require("resession").save(get_session_name(), { dir = "dirsession", notify = false }) end,
    })
  end,
}
```

**Comment by lougreenwood** [comment]
Amazing, thank you @mehalter, I'm going to submit a PR upstream to fix this in the docs for `resession` 🙇 .

**Comment by mehalter** [comment]
well upstream I would consider this a bug and I have opened up an issue there to hopefully get this resolved.

**Comment by mehalter** [comment]
@lougreenwood someone else on the AstroNvim discord got this working. Basically working around the resession issue. On `VimEnter` after you call `load` you can call `vim.cmd.doautoall "BufReadPost"` to trigger `BufReadPost` on all of the loaded buffers :)

**Comment by mehalter** [comment]
Just a follow up as this has been resolved upstream. This problem doesn't actually stem from within resession but actually in the auto command definition. By default there is a `nested` option for auto commands in neovim that is set to `false`. This option tells an auto command if it's execution is allowed to spin off other auto commands. Rather than calling `doautoall BufReadPost` we can simply add `nested = true` to the `VimEnter` auto command:

```lua
vim.api.nvim_create_autocmd("VimEnter", {
  nested = true, -- allow triggering other auto commands
  callback = function()
    -- Only load the session if nvim was started with no args
    if vim.fn.argc(-1) == 0 then
      require("resession").load(get_session_name(), { dir = "dirsession", silence_errors = true })
    end
  end,
})
```
