### ISSUE TITLE
Save state of picker between pickers on switch 

### ISSUE THREAD

**Issue by vtvz** [AstroNvim/AstroNvim#2379]
### Is your feature related to a problem?

Sometimes I open "Find words" picker with the intent to search for files. 

### Describe the new feature

The ability to save text between pickers would be nice 

### Additional context

This thing works for me. Can it be implemented in neovim somehow?
- https://github.com/vtvz/astronvim/blob/dc44d46bcfdeeef67068fdf5fefef2fc0f1fbbc1/user/init.lua#L3-L9
- https://github.com/vtvz/astronvim/blob/dc44d46bcfdeeef67068fdf5fefef2fc0f1fbbc1/user/init.lua#L45-L75

**Comment by mehalter** [comment]
I think this is a great solution and I think is probably the best way to do it. I don't see anything in the telescope docs about doing it any other way.

I'm not sure if I want to add this to core AstroNvim, but I can leave it open and see if other people want this added.

**Comment by mehalter** [comment]
Another way we could do this is we could make an AstroCommunity plugin for enabling this type of feature. It would be a good way to enable/disable features such as this without having to add them to the default configuration
