### ISSUE TITLE
mason ensure_installed not working

### ISSUE THREAD

**Issue by rick-yao** [AstroNvim/AstroNvim#2388]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 14.1.1 (23B81)

### Terminal/GUI

kitty

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.38.2
- Neovim Version: v0.9.4
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

in AstroNvim/lua/user/plugins/mason.lua, I filled some config in ensured_installed part, but when mason does not install these components automatically.
my config:
<img width="1292" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/59443488/98e2dbff-88f6-4d8b-8e20-b020123a3275">

### Steps to Reproduce

1. delete ~/.local/share/nvim folder
2. delete ~/.local/state/nvim folder -- till now i think all nvim related things are cleared
3. execute nvim command -- astronvim will automatically install everything.
4. only three components are installed automatically via mason -- see below pic
<img width="717" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/59443488/9c4f22ec-4c82-4a92-99a2-40daee395567">
among there three components , codelldb is from   "astrocommunity.pack.rust"  mason-nvim-dap's ensure_installed part, prettier is from mason-null-ls part i configured , for tsserver , not sure, but maybe from below
<img width="886" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/59443488/e38f5383-6eef-47a9-a147-63f9e917d6de">
5. all other components is not installed.

### Expected behavior

mason should install the components i configured.

### Screenshots

all possible config that may be related to this:
1. init.lua
<img width="1069" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/59443488/edbbdfe9-9e9d-464a-9c30-f5ede1e2a9b4">
2. in plugins/typescript.lua
<img width="961" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/59443488/c68ca3ea-0779-4acc-8fba-85096e53a1b6">
3. in plugins/tailwind.lua
<img width="1428" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/59443488/ef114516-e22e-4c92-917b-b0b1c904e56d">

### Additional Context

my mason log :
[INFO  Tue Nov 28 10:01:43 2023] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:184: Executing installer for Package(name=prettier) {}
[INFO  Tue Nov 28 10:01:43 2023] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:184: Executing installer for Package(name=typescript-language-server) {}
[INFO  Tue Nov 28 10:01:43 2023] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:184: Executing installer for Package(name=codelldb) {}
[INFO  Tue Nov 28 10:01:45 2023] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:245: Installation succeeded for Package(name=prettier)
[INFO  Tue Nov 28 10:01:48 2023] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:245: Installation succeeded for Package(name=codelldb)
[INFO  Tue Nov 28 10:01:48 2023] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:245: Installation succeeded for Package(name=typescript-language-server)

**Comment by mehalter** [comment]
Your typescript.lua file is probably overwriting the list. Table merging does not play well with list like tables. Which is why in the other examples we do list extensions with the function notation.

**Comment by rick-yao** [comment]
Thanks for your quick reply! But even though i modified typescript.lua into function call or just deleted the file, mason still only installed 3 component listed above.

**Comment by mehalter** [comment]
If you share your config I can take a look at what error might be in your user configuration tomorrow.

**Comment by rick-yao** [comment]
I just find out this is purely my fault because i use alias to control user config , but alias is wrong. All changes i made just didn't take effect..You are right. the typescript.lua should use function call instead of pure table. Once i solved alias and function call in typescript.lua , it works. Thanks!
