### ISSUE TITLE
Why the prettier-plugin-tailwindcss package doesn't  work with AstroNvim?

### ISSUE THREAD

**Issue by pujiragil** [AstroNvim/AstroNvim#2389]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Archcraft x86_64

### Terminal/GUI

Alacritty

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: nightly (v3.38.2-2-g63feec7)
- Neovim Version: v0.9.4
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

I want to use the prettier-plugin-tailwindcss package in my project to automatically sort Tailwind CSS class names. I have also installed the Tailwind CSS language server and prettier. Here are the issues I am experiencing.

![Screenshot-28_11_2023-10-29-27](https://github.com/AstroNvim/AstroNvim/assets/72433552/387796f8-922f-4501-966c-d2385b4258a7)

Every time I save the file, a notification of 'lsp timeout' appears, and formatting doesn't work properly when there is a prettier.config.js file

![Screenshot-28_11_2023-10-31-20](https://github.com/AstroNvim/AstroNvim/assets/72433552/ee7c76e1-f41a-4d86-a766-829418528ea0)

package.json

![Screenshot-28_11_2023-10-46-27](https://github.com/AstroNvim/AstroNvim/assets/72433552/af42dab3-ed45-460e-b491-c0e09b7e4cd6)

And when I delete the prettier.config.js file, Prettier formatting works normally, as follows. But still the auto sort class doesn't work

![Screenshot-28_11_2023-10-38-37](https://github.com/AstroNvim/AstroNvim/assets/72433552/5fae8a32-cfa8-409f-a83e-43b31d9c3db2)

My AstroNvim configuration is as follows [https://github.com/pujiragil/astronvim_config](url)

### Steps to Reproduce

...

### Expected behavior

It should work well after I install the prettier package and prettier-plugin-tailwindcss, then create the prettier config file. Sorting class names in Tailwind CSS runs smoothly

**Comment by mehalter** [comment]
Here are the docs on configuring your lsp format timeout: https://docs.astronvim.com/recipes/advanced_lsp/#configure-other-formatting-options

**Comment by pujiragil** [comment]
actually that's not the problem. It's like prettier can't read the configuration from the prettier.config.js file so the tailwindcss classnames can't be sorted in the proper order.

**Comment by mehalter** [comment]
I tested and can replicate the timeout and then when bumping up the timeout to something like 5000 it works great :)

**Comment by mehalter** [comment]
if the behavior changes when you create the file then it does appear that the file is being read... Also the timeout error is saying that the formatting never finished and it's execution was being cut off :)

**Comment by pujiragil** [comment]
This works very well @mehalter after I changed the timeout option, thank you for your assistance. I apologize for contradicting the statement you provided. I truly appreciate your help : )

**Comment by mehalter** [comment]
No problem! Glad it helped!
