### ISSUE TITLE
Headless Mode Install Fails (Buffer Issue)

### ISSUE THREAD

**Issue by c3rb3ru5d3d53c** [AstroNvim/AstroNvim#2391]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Linux

### Terminal/GUI

Gnome Terminal

### AstroNvim Health

```text
E5113: Error while calling lua chunk: /home/user/.config/nvim/init.lua:15: attempt to index field 'cmd' (a function value)
stack traceback:
        /home/user/.config/nvim/init.lua:15: in main chunkError detected while processing BufWinEnter Autocommands for "*":
Error executing lua callback: /home/user/.config/nvim/lua/astronvim/autocmds.lua:111: invalid key: buf
```

### Describe the bug

It appears that a buffer is checked to see if it exists, as a result of being installed in headless mode it is likely for some reason it cannot be found.

### Steps to Reproduce

```bash
sudo add-apt-repository ppa:neovim-ppa/stable
sudo apt update
sudo apt install -y nvim
git clone --depth 1 https://github.com/AstroNvim/AstroNvim ~/.config/nvim
nvim --headless
```

### Expected behavior

It would be expected after install in headless mode that nvim exits normally.

### Screenshots

![image](https://github.com/AstroNvim/AstroNvim/assets/79795199/67bd9b54-0245-41c9-92e9-97f7089951d3)

### Additional Context

This would be useful for scripted installs :smile: 

Version:
```text
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by mehalter** [comment]
Please check the requirements of AstroNvim. Your Neovim version is very out of date

**Comment by c3rb3ru5d3d53c** [comment]
It also fails on
```text
NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info
```

**Comment by c3rb3ru5d3d53c** [comment]
Same failure on:
```text
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1692716794

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by c3rb3ru5d3d53c** [comment]
This issue is actually with `+q` if not provided the failure occurs

**Comment by mehalter** [comment]
Ok glad you were able to figure it out! The `+q` is definitely important to getting the headless installation to terminate

**Comment by c3rb3ru5d3d53c** [comment]
Thanks a lot though, very helpful, I'll see if I can contribute to the docs if that's okay! :)

**Comment by mehalter** [comment]
Yeah definitely! The docs do have the `+q` in the recipe for how to do headless installations
