### ISSUE TITLE
jedi-language-server shows error on empty lines

### ISSUE THREAD

**Issue by alexveden** [AstroNvim/AstroNvim#2392]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Debian 12

### Terminal/GUI

alacritty

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.39.0
- Neovim Version: v0.9.4
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

I'm experiencing weird behavior of the jedi lsp server after OS upgrade. This message shows up in Neovim when I move cursor at empty line of a python file.

The behaviour is weird because I have another almost identical machine, with the same version of the jedi lsp installed via Mason. So that other machine worked fine, until I upgraded AstronVim to version 3.39 (was 3.37). However, downgading back doesn't help, so I stuck with this issue on both machines.

I've tried different Python versions (3.9, 3.10, 3.11), also nvim versions 0.9.2 / 0.9.4, also different jedi-lsp servers 0.39, 0.40, 0.41.2. In all of these the issue remains the same.

Are there any moving parts I'm missing? As I noticed, during the upgrade the AstronVim also compiles TreeSitter, can this be a reason?

### Steps to Reproduce

1. Install `jedi-language-server` via Mason
2. Create simple python file
```
import enum

import warnings
```
3. Place cursor on empty line between imports
4. (get full in `:messages` output)

```
lsp_signatur handler RPC[Error] code_name = InternalError, message = "ValueError: `column` parameter (1) is not in a valid range (0-0) for line 14 ('\n')." data = {
  traceback = { '  File "/home/user/.local/share/nvim/mason/packages/jedi-language-server/venv/lib/python3.11/site-packages/pygls/protocol/json_rpc.py", line 266, in _h
andle_request
    self._execute_request(msg_id, handler, params)
', '  File "/home/user/.local/share/nvim/mason/packages/jedi-language-server/venv/lib/python3.11/site
-packages/pygls/protocol/json_rpc.py", line 188, in _execute_request
    self._send_response(msg_id, handler(params))
                                ^^^^^^^^^^^^^^^
', '
 File "/home/user/.local/share/nvim/mason/packages/jedi-language-server/venv/lib/python3.11/site-packages/jedi_language_server/server.py", line 277, in signature_help

    signatures_jedi = jedi_script.get_signatures(*jedi_lines)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
', "  File "/home/user/.local/share/nvim/
mason/packages/jedi-language-server/venv/lib/python3.11/site-packages/jedi/api/helpers.py", line 484, in wrapper
    raise ValueError('`column` parameter (%d) is not in a v
alid range '

" }
```

### Expected behavior

no error

### Additional Context

I've tried multiple python versions, nvim versions, and jedi-language-server versions via Mason. None of them didn't help to fix  broken machine. However, machine with working jedi lsp, got broken immediately after I ran `:AstroUpdate`.

I've tried to roll back to the previous Astronvim version which used to work (3.37), but no luck, the problem remains persistent. 
Cleaning neovim folders, didn't help also.
```
mv ~/.local/share/nvim ~/.local/share/nvim.bak
mv ~/.local/state/nvim ~/.local/state/nvim.bak
mv ~/.cache/nvim ~/.cache/nvim.bak
```

**Comment by mehalter** [comment]
Looks unrelated to AstroNvim. Looking at the repository for `jedi-language-sever` I quickly found a lot of issues referring to this error message coming from `pygls` so looks like this is both common and upstream.
