### ISSUE TITLE
Lazy problem 

### ISSUE THREAD

**Issue by EsamLasheen** [AstroNvim/AstroNvim#2396]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

linux_arch 

### Terminal/GUI

kitty 

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.40.0
- Neovim Version: v0.9.4
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- WARNING `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Failed to source `/usr/share/nvim/runtime/plugin/astronvim.vim`

vim/_editor.lua:0: /home/la4een/.config/nvim/init.lua..nvim_exec2() called at /home/la4een/.config/nvim/init.lua:0../usr/share/nvim/runtime/plugin/astronvim.vim, line 3: Vim(luafile):Failed to load astronvim.lazy

# stacktrace:
  - vim/_editor.lua:0 _in_ **cmd**
  - .config/nvim/lua/astronvim/lazy.lua:43
  - .config/nvim/init.lua:10

### Steps to Reproduce

just open nvim and this happend

### Expected behavior

open easy 

### Screenshots

![image](https://github.com/AstroNvim/AstroNvim/assets/55217611/3951956d-c950-4e5a-93f4-084789a9984d)

**Comment by mehalter** [comment]
Please share your configuration to help us replicate the issue

**Comment by mehalter** [comment]
Also how did you install AstroNvim? Did you install it through AUR?

**Comment by mehalter** [comment]
It looks like you are trying to install through the AUR which honestly was just a straight up failed experiment 😅 Especially with the direction that AstroNvim v4 is moving towards will support this approach even less. So this is something that we haven't officially supported so far and won't be supporting in the future. I will start looking now to get that package fully removed from the AUR. Sorry for the confusion! Check out the documentation for the officially supported installation instructions: https://docs.astronvim.com/#%EF%B8%8F-installation

**Comment by mehalter** [comment]
Thanks for bringing back to my attention the fact that these packages do exist and should no longer 😅  I have go ahead and submitted those deletion requests to AUR maintainers. Hopefully they are removed very soon!

**Comment by EsamLasheen** [comment]
Hi mehalter,

I wanted to thank you for your help with removing the AstroNvim packages from the AUR. I really appreciate you taking the time to do this, as it will help prevent others from encountering the same issue I did.

Your efforts are greatly appreciated!

Best regards,

Esam
