### ISSUE TITLE
Indentation error during line breaks, after formatting

### ISSUE THREAD

**Issue by CnsMaple** [AstroNvim/AstroNvim#2406]
### Checklist

- [x] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Windows11

### Terminal/GUI

powershell

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.40.3
- Neovim Version: v0.10.0-dev-1938+g242261d4e
- WARNING Neovim nightly is not officially supported and may have breaking changes
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `explorer` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- WARNING `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

normal:

https://github.com/AstroNvim/AstroNvim/assets/92523839/14f7a9ed-4b1e-4520-b661-2e1661e22a30

have error:

https://github.com/AstroNvim/AstroNvim/assets/92523839/f32322d0-499e-4101-80a4-54a2b904ba2b

### Steps to Reproduce

1. format
2. wrap

### Expected behavior

Indent with the current line

**Comment by mehalter** [comment]
You probably need to rerun `:GuessIndent` if you change the indentation mid editor session

**Comment by CnsMaple** [comment]
Sorry, this issue has not been resolved 

https://github.com/AstroNvim/AstroNvim/assets/92523839/6375a37d-77c9-4721-a720-34ab00b10da4

**Comment by CnsMaple** [comment]
I checked it, when i run ":TSInstall cpp",and open cpp file(.h), The problem will reappear.

**Comment by CnsMaple** [comment]
The number of indentations is indeed correct for the default code format, but my code has been formatted and is no longer the default indented position.

**Comment by mehalter** [comment]
This second video looks like there is probably just a bug in the C treesitter parser causing bad indentation level calculation. You could try configuring treesitter to disable treesitter indentation module for C files if that gets you better results. Sorry!

**Comment by CnsMaple** [comment]
i found it,is my problem.sorry.
