### ISSUE TITLE
`powershell_es` does not attach to `ps1` file buffers post `LspInstall`

### ISSUE THREAD

**Issue by terminal-root** [AstroNvim/AstroNvim#2408]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Windows 10 Enterprise x86_64

### Terminal/GUI

Windows Terminal

### AstroNvim Health

```
==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.40.3
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `explorer` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

```

### Describe the bug

After installing `powershell_es` with `:LspInstall`, `powershell_es` does not attach upon opening `ps1` files.

### Steps to Reproduce

1. Run `:LspInstall powershell_es`
2. Close Neovim
3. Open a `ps1` file with Neovim

### Expected behavior

`powershell_es` attaches to the buffer and relevant functionality is available/works.

### Screenshots

![image](https://github.com/AstroNvim/AstroNvim/assets/24536673/fa0f833a-e34b-43c5-b8fd-817b8e05f46a)

**Comment by mehalter** [comment]
You need to make sure that the root directory is able to be detected for auto starting or you should start it manually. You can also customize the root detection if you want or try to enable single file mode

**Comment by mehalter** [comment]
Oh wait actually single file mode is enabled by default. It looks like the `cmd` is not found. This Shou probably be reported to mason-lspconfig

**Comment by mehalter** [comment]
Also I can help you investigate this in a couple weeks when I'm back in front of a computer

**Comment by terminal-root** [comment]
Thanks for your responses, @mehalter :)
