### ISSUE TITLE
Nothing happend with code_runner install

### ISSUE THREAD

**Issue by Uttah** [AstroNvim/AstroNvim#2409]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.6.1

### Terminal/GUI

iTerm

### AstroNvim Health

   4   AstroNvim
   5   - AstroNvim Version: v3.40.3
   6   - Neovim Version: v0.9.4
   7   - OK Using stable Neovim >= 0.8.0
   8   - OK git is installed: Used for core functionality such as updater and plugin management
   9   - OK open is installed: Used for gx mapping for opening files with system opener (Optional)
  10   - OK lazygit is installed: Used for mappings to pull up git TUI (Optional)
  11   - OK node is installed: Used for mappings to pull up node REPL (Optional)
  12   - OK gdu is installed: Used for mappings to pull up disk usage analyzer (Optional)
  13   - OK btm is installed: Used for mappings to pull up system monitor (Optional)
  14   - OK python is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

I created user/plugins/code_runner.lua file with

```
return {
    { "CRAG666/code_runner.nvim", config = true },
}
```

But nothing happened. I used Lazy with `:Lazy` command and saw that code_runner installed, but `:RunCode` does not work.

### Steps to Reproduce

1. Go to https://docs.astronvim.com
2. cd ~/.config
3. `git clone --depth 1 https://github.com/AstroNvim/AstroNvim ~/.config/nvim nvim`
4. mkdir -p nvim/lua/user/plugins
5. touch nvim/lua/user/plugins/code_runner.lua
6. insert into it - ```return {
    { "CRAG666/code_runner.nvim", config = true },
}```
7. start nvim and type - `:RunCode`
8. as a result - E492: Not an editor command: RunCode

### Expected behavior

I expect that :RunCode command will work)

### Screenshots

![Screenshot 2024-01-03 at 16 35 18](https://github.com/AstroNvim/AstroNvim/assets/31721839/30684f99-d2df-4435-a226-f17d88013600)

### Additional Context

I dont know what i should write here

**Comment by mehalter** [comment]
You need to configure lazy loading by the command or disable lazy loading. Here are the docs: https://docs.astronvim.com/recipes/custom_plugins/#defining-plugins
