### ISSUE TITLE
Toggling line comment isn't a repeatable action with `<space>/` mapping

### ISSUE THREAD

**Issue by catlee** [AstroNvim/AstroNvim#2410]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 14.2.1

### Terminal/GUI

kitty

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.40.3
- Neovim Version: v0.9.4
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

In normal mode, if I use `gcc` to toggle line comments, I can repeat this command with `.`.

However, if I use `<space>/` to toggle the line comments, I can't repeat with `.`. Whatever my previous command was gets repeated instead.

### Steps to Reproduce

1. Open a file with commenting support comment.nvim
2. Type `oHello World<esc>` to add a new line with "Hello world" on it.
3. In normal mode, type `<space>/` to comment out this line
4. Type `.` to repeat the command

The result is a new line with `# Hello world`

### Expected behavior

I expect `.` to repeat the line toggle

### Screenshots

https://github.com/AstroNvim/AstroNvim/assets/54458/ea9b06d3-2e7b-4795-a73f-6136565e48ae

**Comment by mehalter** [comment]
This is unrelated to AstroNvim. You can request new features for a plugin in the plugin repository itself: https://github.com/numToStr/Comment.nvim

**Comment by catlee** [comment]
In case someone else comes across this, I tracked this down to AstroNvim's mapping here:

https://github.com/AstroNvim/AstroNvim/blob/main/lua/astronvim/plugins/comment.lua#L9

I've replaced this in my own configs with
```lua
vim.keymap.set("n", "<leader>/", require("Comment.api").call("toggle.linewise.current", "g@$"), { expr = true })
```

**Comment by mehalter** [comment]
Thanks for digging into this! I was able to dig into the source code with this information and understand the implementation as well as some of the issues they have closed. Only some of the mappings are not dot repeatable and they way they recommend to use the API for creating mappings doesn't respect the dot repeatability. Thanks again for continuing to look into this, I have updated the AstroNvim default mapping to be similar but also take into account `v:count` so you can do something like `2<Leader>/` as well

**Comment by mehalter** [comment]
Looks like the real secret they hide behind a private function that is not officially part of the "public API". Honestly not sure what the reasoning is behind that but really appreciate you leading the way!

**Comment by catlee** [comment]
Thanks for fixing this up!

I couldn't figure out how to get `<leader>/` working with a count, so I'm glad you did!
