### ISSUE TITLE
After writing code in the project for a while, the tsserver stops working.

### ISSUE THREAD

**Issue by chaozwn** [AstroNvim/AstroNvim#2411]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macos 13.3.1

### Terminal/GUI

kitty

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.40.3
- Neovim Version: v0.9.4
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

I have been using AstroNvim for quite some time for development, but recently I've encountered an issue. After working on my TypeScript project for a while, tsserver stops being effective. I am not sure if this is a bug, and I wonder if anyone else has experienced the same problem.
<img width="1415" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/51357674/a3d83941-e723-4f8c-98bf-b0e5a815d531">

### Steps to Reproduce

1. open in some big project with typescript.

### Expected behavior

Able to run stable.

**Comment by mehalter** [comment]
This would be an issue with the language server and not AstroNvim. I would recommend the discord for investigating stuff like this.

**Comment by chaozwn** [comment]
> This would be an issue with the language server and not AstroNvim. I would recommend the discord for investigating stuff like this.

I have discovered a method to reproduce the fault.
1.  make sure you have tsserver
2. run `yarn create vite`
3. create a react typescript project
4. run `yarn`
5. run `git init`
6. run `<leader>tl` for first commit, commit all files
7.  delete `App.tsx` on line 7, `const [count, setCount] = useState(0)`, then we found tsserver error hint.
8. save file
9. run `<leader>tl` rollback change, hint not disappear.

**Comment by chaozwn** [comment]
https://github.com/AstroNvim/AstroNvim/assets/51357674/d823dfb4-670c-49a8-bf6a-b1a0502e7005

**Comment by chaozwn** [comment]
> > This would be an issue with the language server and not AstroNvim. I would recommend the discord for investigating stuff like this.
> 
> I have discovered a method to reproduce the fault.
> 
> 1. make sure you have tsserver
> 2. run `yarn create vite`
> 3. create a react typescript project
> 4. run `yarn`
> 5. run `git init`
> 6. run `<leader>tl` for first commit, commit all files
> 7. delete `App.tsx` on line 7, `const [count, setCount] = useState(0)`, then we found tsserver error hint.
> 8. save file
> 9. run `<leader>tl` rollback change, hint not disappear.

In fact, this file will never work properly again, and I don't know if Astronvim can coordinate this part of the functionality.
