### ISSUE TITLE
Unify "show hidden files" telescope searching somehow, instead of splitting by a by capital letter keys

### ISSUE THREAD

**Issue by Tal500** [AstroNvim/AstroNvim#2423]
### Describe the new feature

It would be nice in my opinion if we wouldn't have a separation of `<leader>f[(w/W)/(f/F)]`, meaning, to have only `<leader>f[w/f]`, and the ability to toggle "show hidden files" kinda like a gui checkbox, but as a Telescope action (via pressing `Ctrl+h` maybe?).

The benefit is obvious - no need to exit the search and reenter the search words in a different telescope dialog.

**Comment by mehalter** [comment]
This should be requested upstream. Telescope does not currently support this, so this would be a new feature for them to have an action to toggle the results in the files as hidden or not

**Comment by Tal500** [comment]
> This should be requested upstream. Telescope does not currently support this, so this would be a new feature for them to have an action to toggle the results in the files as hidden or not

Thanks!

**Comment by mehalter** [comment]
Also just a heads up @Tal500 chances are they won't see this as a bug given your issue is basically a duplicate of: https://github.com/nvim-telescope/telescope.nvim/issues/628
