### ISSUE TITLE
BUG: cursor jump to selected item when opening folder

### ISSUE THREAD

**Issue by rick-yao** [AstroNvim/AstroNvim#2424]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macos 14.2.1

### Terminal/GUI

kitty

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.41.2
- Neovim Version: v0.9.5
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu-go` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

some times when opening folder, cursor will jump to a random item rather than stay at the foler.
some times it jump to opened file ,sometimes it jump to item in the folder. i couldn't get exact clue.

### Steps to Reproduce

1. open the file with neotree
2. focus on neotree
3. selecte a folder , press l to open
4. the cursor jump to opened item , not stay at the folder

### Expected behavior

the cursor should stay at the folder item.

### Screenshots

[video](https://1drv.ms/v/s!Aul7Mp-RSA34gfxgj6FKIE1ps0TmPg?e=IeXjS9)

### Additional Context

Though recently both neotree and astronvim updated ,I thought this was caused by neotree. So i opened an issue at [neotree](https://github.com/nvim-neo-tree/neo-tree.nvim/issues/1310),but neotree said it may be caused by astronvim so I open an issue here.

**Comment by mehalter** [comment]
Cannot replicate. Can you replicate with a base installation of AstroNvim without your user config?

**Comment by mehalter** [comment]
Easiest way would be to just use the docker command and test:

```sh
docker run -w /root -it --rm alpine:edge sh -uelic '
  apk add bash git lua nodejs npm lazygit bottom python3 go neovim ripgrep alpine-sdk --update
  git clone --depth 1 https://github.com/AstroNvim/AstroNvim ~/.config/nvim
  nvim
'
```

Here is a recording of me showing that a completely fresh install has no issue: https://asciinema.org/a/R5Ri6bpb8IrxdaTUjjgacGtKQ

This is only using `h`, `j`, `k`, `l`, in neo-tree and `<leader>e` to open and `<leader>o` to focus

**Comment by rick-yao** [comment]
`h, j, k, l` `<leader>e <leader>o` are the only commands i used, just like you said.

**Comment by mehalter** [comment]
To be safe you should clear your data/state/cache folders and make sure it's clean. Or you can use the docker method

**Comment by mehalter** [comment]
Here is a recording of pure docker install completely fresh: https://asciinema.org/a/Cpjw9nuEjHJ5WjN8GBnjf1VQQ

**Comment by rick-yao** [comment]
I just deleted:
1. ~/.local/state/nvim
2. ~/.local/share/nvim
3. ~/.cache/nvim

and exec nvim then nvim started installation from lazy. Still encounter the issue.

**Comment by mehalter** [comment]
You said that it works if you downgrade to v3.14 of neo-tree? Can you run a `git bisect` in neo-tree folder in `~/.local/share/nvim/lazy/neo-tree.nvim` to identify the offending commit?

**Comment by mehalter** [comment]
I cannot replicate this issue for the life of me :joy: similar to the neo-tree maintainer

**Comment by rick-yao** [comment]
Someone else said rollback to 3.14 solved the issue, and the issue was gone when I fallback to 3.14.
Like i said this is totally random...

**Comment by mehalter** [comment]
Ok, can you do a git bisect like I described above to find the offending commit. Just bisect between 3.14 and 3.15

**Comment by rick-yao** [comment]
yes, but this till take some time.. I need to lean bisect command first...

**Comment by mehalter** [comment]
I ran the `git bisect` and found the offending commit actually

**Comment by mehalter** [comment]
We'll see if there is a good resolution. I might just remove this custom code and remove the `l` and `h` navigation in neo-tree :)

**Comment by mehalter** [comment]
I was able to replicate, but it is not very stable or regular. It does happen relatively randomly, but frequently enough to identify it.

**Comment by rick-yao** [comment]
after bisect , the issue occured from https://github.com/nvim-neo-tree/neo-tree.nvim/commit/1122b2056325a782821b9ea37467acf35a7e7806

**Comment by mehalter** [comment]
Bug is identified upstream and is being investigated. Closing here
