### ISSUE TITLE
Cannot spell check using another dictionary 

### ISSUE THREAD

**Issue by Enrico68** [AstroNvim/AstroNvim#2427]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

OSX 13.6.1

### Terminal/GUI

Iterm2

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: v3.41.2
- Neovim Version: v0.9.5
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu-go` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Cannot find the way to install another dictionary for spell checking 

### Steps to Reproduce

change the local spell with setlocal spellang=it 
Tried to install downloaded *.spl file in user/config/spell with no succes 

### Expected behavior

Cannot spell check correctly with another language except english

**Comment by mehalter** [comment]
You will need to put it in your `~/.config/nvim` folder. Or we also allow you to use `~/.config/astronvim` to not conflict with the core AstroNvim install. Also for reference, this is all changing in v4 since we will no longer have a `user/` folder. You will manage your config directly in `~/.config/nvim`

**Comment by mehalter** [comment]
You can just set your spell file directly. Here is an example:

Repo with a spell folder and spell file: https://code.mehalter.com/AstroNvim_user
Look at line 8 in the `options.lua` file: https://code.mehalter.com/AstroNvim_user/~files/master/options.lua

**Comment by mehalter** [comment]
The best approach before v4 would be to put your config in `~/.config/astronvim` so for instance you would have a structure like so:

```
~/.config/astronvim
├── lua/
│   └── user/
└── spell/
```

If you have questions about this, the official AstroNvim Discord is a great place to ask

**Comment by Enrico68** [comment]
Thanks for the suggestion, @mehalter ! I will definitely join Discord, as I've recently started my journey with Neovim.
