### ISSUE TITLE
copy selections in WSL normal mode and paste to win 11 system

### ISSUE THREAD

**Issue by Chuanhuan** [AstroNvim/AstroNvim#2430]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Win11 WSL

### Terminal/GUI

Terminal

### AstroNvim Health

``` 
provider: health#provider#check                                                       1
 Clipboard (optional)
   - OK Clipboard tool found: xclip
 ```

### Describe the bug

I use ArchWSL and try to copy lines in windows Terminal. It didn't copy when I paste to windows 11 system.

### Steps to Reproduce

I put `win32yank.exe` to `/usr/local/bin/win32yank.exe` and set ` opt={clipboard = "unnamedplus"}` in my `user/init.lua`
I pass `"*y` is can't not copy. then I add 
```
g={
clipboard = {
  name = "win32yank-wsl",
  copy = {
    ["+"] = "win32yank.exe -i --crlf",
    ["*"] = "win32yank.exe -i --crlf",
  },
  paste = {
    ["+"] = "win32yank.exe -o --lf",
    ["*"] = "win32yank.exe -o --lf",
  },
  cache_enabled = 0,
}
},
```
it's not working.
I `:checkhelthy` still `Clipboard tool found: xclip`

### Expected behavior

It's any way to copy in WSL and paste to windows system.

**Comment by mehalter** [comment]
Hey! I'm not sure the correct way to configure clipboard in WSL and this is not really related to anything AstroNvim specific. Check out the discord for asking questions to users as they will be able to help out much more with questions like these. We try to limit the GitHub issues to things specifically related to the AstroNvim codebase. Good luck! If you do find a good answer, please feel free to drop a comment here with your solution as that's very helpful if someone else stumbles across this post.

**Comment by mehalter** [comment]
Also by the way `unnamedplus` is the default clipboard in AstroNvim. So you don't have to set it explicitly yourself 😃

**Comment by Chuanhuan** [comment]
ok, the below work in neovim and I don't know how to transfer to lua file in astronvim

```
-- for copy and pates between WSL and windows
vim.opt.clipboard = "unnamedplus"
if vim.fn.has("wsl") == 1 then
  vim.api.nvim_create_autocmd("TextYankPost", {
    group = vim.api.nvim_create_augroup("Yank", { clear = true }),
    callback = function()
      vim.fn.system("clip.exe", vim.fn.getreg('"'))
    end,
  })
end

```
