### ISSUE TITLE
AstroNvim's default keymapping of zR, zM, zr, and zm to functions in the nvim-ufo result in the loss of the ability to do "partial" folding or unfolding. 

### ISSUE THREAD

**Issue by jasonsydes** [AstroNvim/AstroNvim#2432]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 14.2.1

### Terminal/GUI

iTerm

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.42.0
- Neovim Version: v0.9.5
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- WARNING `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu-go` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

AstroNvim's default keymapping of zR, zM, zr, and zm to functions in the nvim-ufo result in the loss of the ability to do "partial" folding or unfolding. 

I'm not sure if there's a way to "turn off" those keymappings.

### Steps to Reproduce

1. With a default AstroNVim setup, In a file with indented Lua or Python code (those are the only two languages I tested), experiment with typing multiple occurrences of zr and zm. I call this behavior "good looking nvim-ufo with broken partial folding"
2. Comment out lines 418 - 424 in ~/.config/nvim/lua/astronvim/mappings.lua (for example, this is one of the lines to be commented out: maps.n["zR"] = { function() require("ufo").openAllFolds() end, desc = "Open all folds" }).
3. Restart AstroNVim, and then repeat step 1. I call this behavior "good looking nvim-ufo with working partial folding" 
4. Uninstall nvim-ufo, and then repeat step1. I call this behavior "default / non-nvim-ufo old school styling with working partial folding".

### Expected behavior

Hopefully AstroNvim can support nvim-ufo, but without those zm, zr, zM, zR keymappings to nvim-ufo functions. nvim-ufo does indeed look better than the default nvim folding, but those keymappings appear to break proper partial folding.

### Good looking, but broken partial folding
Default AstroNvim behavior:
![giphy-installed-enabled](https://github.com/AstroNvim/AstroNvim/assets/182702/b26a1678-c00c-4f50-a3b6-b9a77e738cda)

### Good looking AND working partial folding
nvim-ufo still installed, but zr, zm, zR, zM keymapping manually disabled by commenting out several lines in ~/.config/nvim/lua/astronvim/mappings.lua
![giphy-installed-disabled](https://github.com/AstroNvim/AstroNvim/assets/182702/a1ac4fc5-500c-471d-9241-dce7a7a27545)

### Not that great looking, but does has working partial folding
nvim-ufo uninstalled
![giphy-uninstalled](https://github.com/AstroNvim/AstroNvim/assets/182702/650749fb-f73f-42b3-88b8-e0328e806656)

**Comment by mehalter** [comment]
Thanks for reporting! This should be reported upstream with the `nvim-ufo` devs though since there isn't anything for me to do here in this repo. Put together a minimal configuration and report to them what issues you have. If you don't like the UFO stuff feel free to disable it in your user configuration until they get it fixed to your liking.

Thanks again!

**Comment by mehalter** [comment]
https://github.com/kevinhwang91/nvim-ufo/issues/161

upstream issue
