### ISSUE TITLE
Multiple formatters and lsp try to override each other and work simultaniously 

### ISSUE THREAD

**Issue by Krr0ptioN** [AstroNvim/AstroNvim#2436]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Archlinux / Kernel 6.1.55-1-lts 

### Terminal/GUI

st

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.42.0
- Neovim Version: v0.9.2
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

==============================================================================
lazy: require("lazy.health").check()

lazy.nvim ~
- OK Git installed
- OK no existing packages found by other package managers
- OK packer_compiled.lua not found
- WARNING {LuaSnip}: overriding <config>
- WARNING {todo-comments.nvim}: unknown key <requires>
- WARNING {nvim-notify}: overriding <config>

==============================================================================
mason: require("mason.health").check()

mason.nvim ~
- WARNING mason.nvim version v1.9.0
  - ADVICE:
    - The latest version of mason.nvim is: v1.10.0
- OK PATH: prepend
- OK Providers: 
  mason.providers.registry-api
  mason.providers.client
- OK neovim version >= 0.7.0

mason.nvim [Registries] ~
- OK Registry `github.com/mason-org/mason-registry version: 2024-01-29-funny-kidney` is installed.

mason.nvim [Core utils] ~
- OK unzip: `UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send`
- OK wget: `GNU Wget 1.21.4 built on linux-gnu.`
- OK curl: `curl 8.3.0 (x86_64-pc-linux-gnu) libcurl/8.3.0 OpenSSL/3.1.3 zlib/1.3 brotli/1.1.0 zstd/1.5.5 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.11.0 nghttp2/1.56.0`
- OK gzip: `gzip 1.13`
- OK tar: `tar (GNU tar) 1.35`
- OK bash: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
- OK sh: `Ok`

mason.nvim [Languages] ~
- OK Ruby: `ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x86_64-linux]`
- OK Go: `go version go1.21.1 linux/amd64`
- OK PHP: `PHP 8.2.10 (cli) (built: Sep  1 2023 11:07:36) (NTS)`
- OK luarocks: `/usr/bin/luarocks 3.9.2`
- OK node: `v18.16.1`
- OK cargo: `cargo 1.68.2 (6feb7c9cf 2023-03-26)`
- OK Composer: `Composer version 2.6.3 2023-09-15 09:38:21`
- WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. julia is not executable
- OK python: `Python 3.11.6`
- OK RubyGem: `3.3.25`
- OK JAVA_HOME: `openjdk version "17.0.7" 2023-04-18`
- OK java: `openjdk version "17.0.7" 2023-04-18`
- OK javac: `javac 17.0.7`
- OK npm: `9.5.1`
- OK pip: `pip 23.2.1 from /usr/lib/python3.11/site-packages/pip (python 3.11)`
- OK python venv: `Ok`

mason.nvim [GitHub] ~
- OK GitHub API rate limit. Used: 0. Remaining: 5000. Limit: 5000. Reset: Mon 29 Jan 2024 12:48:08 PM +03.

==============================================================================
neoconf: require("neoconf.health").check()

neoconf.nvim ~
- OK **treesitter-nvim** is installed
- OK **TreeSitter jsonc** parser is installed
- OK **neodev.nvim** is installed
- OK **lspconfig** is installed
- OK **lspconfig jsonls** is installed
- WARNING **lspconfig lua_ls** is not installed? You won't get any auto completion in your lua settings files

==============================================================================
noice: require("noice.health").check()

noice.nvim ~
- OK **Neovim** >= 0.8.0
- OK You're using a GUI that should work ok
- OK **vim.go.lazyredraw** is not enabled
- OK **nvim-notify** is installed
- OK **TreeSitter vim** parser is installed
- OK **TreeSitter regex** parser is installed
- OK **TreeSitter lua** parser is installed
- OK **TreeSitter bash** parser is installed
- OK **TreeSitter markdown** parser is installed
- OK **TreeSitter markdown_inline** parser is installed
- OK `vim.notify` is set to **Noice**
- WARNING `vim.lsp.handlers["textDocument/hover"]` is not configured to be handled by **Noice**
- WARNING `vim.lsp.handlers["textDocument/signatureHelp"]` is not configured to be handled by **Noice**
- OK `vim.lsp.handlers["window/showMessage"]` is set to **Noice**
- OK `vim.lsp.util.convert_input_to_markdown_lines` is set to **Noice**
- OK `vim.lsp.util.stylize_markdown` is set to **Noice**
- OK `cmp.entry.get_documentation` is set to **Noice**

==============================================================================
null-ls: require("null-ls.health").check()

- OK beautysh: the command "beautysh" is executable.
- OK cpplint: the command "cpplint" is executable.
- OK jsonlint: the command "jsonlint" is executable.
- OK rustywind: the command "rustywind" is executable.
- OK hadolint: the command "hadolint" is executable.
- OK phpcsfixer: the command "php-cs-fixer" is executable.
- OK black: the command "black" is executable.
- OK isort: the command "isort" is executable.
- OK actionlint: the command "actionlint" is executable.
- OK vale: the command "vale" is executable.
- OK latexindent: the command "latexindent" is executable.
- OK sqlfluff: the command "sqlfluff" is executable.
- OK sqlfluff: the command "sqlfluff" is executable.
- OK lua_format: the command "lua-format" is executable.
- OK write_good: the command "write-good" is executable.
- OK eslint_d: the command "eslint_d" is executable.
- OK eslint_d: the command "eslint_d" is executable.
- OK eslint_d: the command "eslint_d" is executable.
- OK pylint: the command "pylint" is executable.
- OK shellcheck: the command "shellcheck" is executable.
- OK shellcheck: the command "shellcheck" is executable.
- OK sqlfmt: the command "sqlfmt" is executable.
- OK fixjson: the command "fixjson" is executable.
- OK phpstan: the command "phpstan" is executable.

==============================================================================
nvim: require("nvim.health").check()

Configuration ~
- OK no issues found

Runtime ~
- OK $VIMRUNTIME: /usr/share/nvim/runtime

Performance ~
- OK Build type: Release

Remote Plugins ~
- OK Up to date

terminal ~
- key_backspace (kbs) terminfo entry: `key_backspace=\177`
- key_dc (kdch1) terminfo entry: `key_dc=\E[3~`
- $TERM_PROGRAM="tmux"

tmux ~
- OK escape-time: 10
- OK focus-events: on
- $TERM: screen-256color
- WARNING Neither Tc nor RGB capability set. True colors are disabled. |'termguicolors'| won't work properly.
  - ADVICE:
    - Put this in your ~/.tmux.conf and replace XXX by your $TERM outside of tmux:
      set-option -sa terminal-features ',XXX:RGB'
    - For older tmux versions use this instead:
      set-option -ga terminal-overrides ',XXX:Tc'

==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v18.16.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 13.2.1 20230801
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.1.55-1-lts",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Sat, 23 Sep 2023 16:57:15 +0000"
} ~

Parser/Features         H L F I J
  - awk                 ✓ . . . ✓
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - clojure             ✓ ✓ ✓ . ✓
  - cmake               ✓ . ✓ ✓ .
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - diff                ✓ . . . .
  - dockerfile          ✓ . . . ✓
  - git_config          ✓ . ✓ . ✓
  - git_rebase          ✓ . . . ✓
  - gitcommit           ✓ . . . ✓
  - gitignore           ✓ . . . .
  - graphql             ✓ . . ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - http                ✓ . . . ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - jsdoc               x . . . .
  - json                ✓ ✓ ✓ ✓ .
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - latex               ✓ . ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - php                 ✓ ✓ ✓ ✓ ✓
  - prisma              ✓ . ✓ . .
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - rust                ✓ ✓ ✓ ✓ ✓
  - scss                ✓ . ✓ ✓ .
  - sql                 ✓ . . ✓ ✓
  - sxhkdrc             ✓ . ✓ . ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

The following errors have been detected: ~
- ERROR jsdoc(highlights): Failed to load parser for language 'jsdoc': uv_dlopen: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/jsdoc.so: undefined symbol: tree_sitter_jsdoc_external_scanner_create
  jsdoc(highlights) is concatenated from the following files:
  | [ERROR]:"/home/username/.local/share/nvim/lazy/nvim-treesitter/queries/jsdoc/highlights.scm", failed to load: Failed to load parser for language 'jsdoc': uv_dlopen: /home/master/.local/share/nvim/lazy/nvim-treesitter/parser/jsdoc.so: undefined symbol: tree_sitter_jsdoc_external_scanner_create

==============================================================================
provider: health#provider#check

Clipboard (optional) ~
- OK Clipboard tool found: xsel

Python 3 provider (optional) ~
- `g:python3_host_prog` is not set.  Searching for python3 in the environment.
- Executable: /usr/bin/python3
- Python version: 3.11.6
- pynvim version: 0.4.3 (outdated; from ~/.local/lib/python3.11/site-packages/neovim)
- WARNING Latest pynvim is NOT installed: 0.5.0

Python virtualenv ~
- OK no $VIRTUAL_ENV

Ruby provider (optional) ~
- Ruby: ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x86_64-linux]
- WARNING `neovim-ruby-host` not found.
  - ADVICE:
    - Run `gem install neovim` to ensure the neovim RubyGem is installed.
    - Run `gem environment` to ensure the gem bin directory is in $PATH.
    - If you are using rvm/rbenv/chruby, try "rehashing".
    - See :help |g:ruby_host_prog| for non-standard gem installations.
    - You may disable this provider (and warning) by adding `let g:loaded_ruby_provider = 0` to your init.vim

Node.js provider (optional) ~
- Node.js: v18.16.1
- WARNING Missing "neovim" npm (or yarn, pnpm) package.
  - ADVICE:
    - Run in shell: npm install -g neovim
    - Run in shell (if you use yarn): yarn global add neovim
    - Run in shell (if you use pnpm): pnpm install -g neovim
    - You may disable this provider (and warning) by adding `let g:loaded_node_provider = 0` to your init.vim

Perl provider (optional) ~
- WARNING "Neovim::Ext" cpan module is not installed
  - ADVICE:
    - See :help |provider-perl| for more information.
    - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

==============================================================================
sniprun: health#sniprun#check

Installation ~
- OK Rust toolchain found
- OK sniprun binary found at /usr/share/nvim/runtime/target/release/sniprun
- OK sniprun binary runs correctly

==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.7.0

===== Installed extensions ===== ~

Telescope Extension: `aerial` ~
- No healthcheck provided

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured

Telescope Extension: `notify` ~
- No healthcheck provided

Telescope Extension: `projects` ~
- No healthcheck provided

==============================================================================
vim.lsp: require("vim.lsp.health").check()

- LSP log level : WARN
- Log path: /home/username/.local/state/nvim/lsp.log
- Log size: 28122 KB

vim.lsp: Active Clients ~
- diagnosticls (id=1, root_dir=/home/username/.config/nvim/lua/user)
- null-ls (id=2, root_dir=/home/username/.config/nvim/lua/user)
- custom_elements_ls (id=3, root_dir=/home/username/.config/nvim/lua/user)

==============================================================================
vim.treesitter: require("vim.treesitter.health").check()

- Nvim runtime ABI version: 14
- OK Parser: awk        ABI: 14, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/awk.so
- OK Parser: bash       ABI: 14, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/bash.so
- OK Parser: c          ABI: 14, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/c.so
- OK Parser: clojure    ABI: 13, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/clojure.so
- OK Parser: cmake      ABI: 14, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/cmake.so
- OK Parser: cpp        ABI: 14, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/cpp.so
- OK Parser: css        ABI: 14, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/css.so
- OK Parser: diff       ABI: 14, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/diff.so
- OK Parser: dockerfile ABI: 14, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/dockerfile.so
- OK Parser: git_config ABI: 13, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/git_config.so
- OK Parser: git_rebase ABI: 14, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/git_rebase.so
- OK Parser: gitcommit  ABI: 14, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/gitcommit.so
- OK Parser: gitignore  ABI: 13, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/gitignore.so
- OK Parser: graphql    ABI: 13, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/graphql.so
- OK Parser: html       ABI: 14, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/html.so
- OK Parser: http       ABI: 14, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/http.so
- OK Parser: javascript ABI: 14, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/javascript.so
- ERROR Parser "jsdoc" failed to load (path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/jsdoc.so): Failed to load parser for language 'jsdoc': uv_dlopen: /home/master/.local/share/nvim/lazy/nvim-treesitter/parser/jsdoc.so: undefined symbol: tree_sitter_jsdoc_external_scanner_create
- OK Parser: json       ABI: 14, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/json.so
- OK Parser: jsonc      ABI: 13, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/jsonc.so
- OK Parser: latex      ABI: 14, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/latex.so
- OK Parser: lua        ABI: 14, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/lua.so
- OK Parser: markdown   ABI: 14, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/markdown.so
- OK Parser: markdown_inline ABI: 14, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/markdown_inline.so
- OK Parser: php        ABI: 14, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/php.so
- OK Parser: prisma     ABI: 13, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/prisma.so
- OK Parser: python     ABI: 14, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/python.so
- OK Parser: query      ABI: 14, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/query.so
- OK Parser: regex      ABI: 14, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/regex.so
- OK Parser: rust       ABI: 14, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/rust.so
- OK Parser: scss       ABI: 13, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/scss.so
- OK Parser: sql        ABI: 14, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/sql.so
- OK Parser: sxhkdrc    ABI: 13, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/sxhkdrc.so
- OK Parser: toml       ABI: 13, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/toml.so
- OK Parser: tsx        ABI: 14, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/tsx.so
- OK Parser: typescript ABI: 14, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/typescript.so
- OK Parser: vim        ABI: 14, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/vim.so
- OK Parser: vimdoc     ABI: 14, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/vimdoc.so
- OK Parser: yaml       ABI: 13, path: /home/username/.local/share/nvim/lazy/nvim-treesitter/parser/yaml.so

==============================================================================
vimtex: health#vimtex#check

VimTeX ~
- OK Vim version should have full support!
- OK General viewer should work properly!
- OK Compiler should work!

==============================================================================
which-key: require("which-key.health").check()

WhichKey: checking conflicting keymaps ~
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"gc"**
- rhs: `<Plug>(comment_toggle_linewise)`
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"gb"**
- rhs: `<Plug>(comment_toggle_blockwise)`
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"yS"**
- rhs: `<Plug>(nvim-surround-normal-line)`
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"ys"**
- rhs: `<Plug>(nvim-surround-normal)`

### Describe the bug

While I am developing and coding in Typescript, Javascript codebase, the formatters, lsp, ... are going crazy and there are multiple formatters trying to override each other. I add the packs related to javascript, typescript from community config and this resulted in multiple formatters and lsp with different configurations trying to lint the code. E.g. `eslint` format the code base on editor and neovim configuration while the eslint_d and tries to use the local eslint config of the project (`.eslintrc.js`) and or prettier, ... 

This behavior causes CPU  and RAM usage to sky rocket to 100% usage.

There is also duplicate notifications and warnings in diagnostics messages as these LSP work independently.

### Steps to Reproduce

1. Install of the below community plugins I provided
2. Open Neovim in a Typescript project (you might want to change some of the existing local configuration such as tab if you want to spice thing up)
3. Edit and some code around the comments and save the change to see the fireworks

### Expected behavior

A mechanism which provide options or conditional rules that regulates the activation of these plugin. 

### Community Packages

I don't have any custom configuration for lsp, formatters, ... other than the community packages.

```lua
return {
    "AstroNvim/astrocommunity",
    {import = "astrocommunity.diagnostics.trouble-nvim"},
    {import = "astrocommunity.code-runner.sniprun"},
    {import = "astrocommunity.git.git-blame-nvim"},
    {import = "astrocommunity.git.octo-nvim"},
    {import = "astrocommunity.motion.nvim-surround"},
    {import = "astrocommunity.editing-support.hypersonic-nvim"},
    {import = "astrocommunity.editing-support.neogen"},
    {import = "astrocommunity.editing-support.nvim-devdocs"},
    {import = "astrocommunity.pack.typescript"},
    {import = "astrocommunity.pack.prisma"},
    {import = "astrocommunity.pack.docker"},
    {import = "astrocommunity.pack.markdown"},
    {import = "astrocommunity.pack.tailwindcss"},
    {import = "astrocommunity.pack.clojure"},
    {import = "astrocommunity.pack.html-css"},
    {import = "astrocommunity.pack.yaml"},
    {import = "astrocommunity.pack.cmake"},
    {import = "astrocommunity.pack.json"}, {import = "astrocommunity.pack.php"},
    {import = "astrocommunity.pack.python"},
    {import = "astrocommunity.pack.rust"},
    {import = "astrocommunity.completion.tabnine-nvim"},
    {import = "astrocommunity.markdown-and-latex.glow-nvim"},
    {import = "astrocommunity.markdown-and-latex.markdown-preview-nvim"},
    {import = "astrocommunity/markdown-and-latex/vimtex"},
    {import = "astrocommunity.project.project-nvim"}
}
```

**Comment by mehalter** [comment]
If you want to decrease things that packs install you can customize them from your user configuration or make PRs to AstroCommunity. I don't maintain anything over there since it's only community driven. 

Here are the docs for customizing formatting in your user configuration as well: https://docs.astronvim.com/recipes/advanced_lsp/#controlling-formatting

**Comment by mehalter** [comment]
If you have any more questions about configuring language servers or formatters the discord is a great place to ask other users as well
