### ISSUE TITLE
TS highlighter works in preview, but not in the file (latex).

### ISSUE THREAD

**Issue by maxgeraldist** [AstroNvim/AstroNvim#2437]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Windows 10

### Terminal/GUI

cmd, qt

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: v3.42.0
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0

### Describe the bug

After re-installing Treesitter for latex, it now does not provide highlights, except in the preview of the files when in the "Recents" menu, and only immediately upon :TSInstall latex - if I then close and open nvim again, highlights disappear from the preview, too.

### Steps to Reproduce

1) Open a latex file
2) run :TSInstall latex
3) See no highlights

### Expected behavior

LaTeX file is highlighted the same way as on the preview.

### Screenshots

![image](https://github.com/AstroNvim/AstroNvim/assets/78108298/4798fa1f-4e8d-459d-8cff-70c31ecbf8db)
![image](https://github.com/AstroNvim/AstroNvim/assets/78108298/966be501-6cb9-43d3-a3dc-af23e26242d7)

### Additional Context

Treesitter showing latex as installed with highlights available in :checkhealth
LSP running vimtex, copilot and latexindent from null-ls, seemingly with no issues
no errors are shown on startup
Neovim QT or CMD run in administrator mode or normal mode

TSUninstal doesn't work - "Invalid switch - Users" - I had to manually delete nvim-data\lazy\nvim-treesitter to try and install it "fresh". This could be the source of the issue, as highlights used to work before.

**Comment by mehalter** [comment]
Please provide a link to your config to see if I can replicate this.

**Comment by maxgeraldist** [comment]
https://github.com/maxgeraldist/astrovim

**Comment by mehalter** [comment]
I just did a clean install of your configuration and cannot replicate the described issue. I also cannot replicate with a minimal installation. Maybe try doing a fresh install.

**Comment by maxgeraldist** [comment]
Just reinstalled it, same exact issue

**Comment by mehalter** [comment]
Sadly I can't replicate locally so there isn't much much else I can do. I can just leave this open just in case someone else can confirm this

**Comment by maxgeraldist** [comment]
Thank you for your time. I think it might be some windows issue, especially since :TSUninstall errors with "Invalid switch - 'Users'". I will update it if I fix the issue

**Comment by mehalter** [comment]
@maxgeraldist I just released v3.42.1. This includes updating treesitter to the latest commit on the stable releases. It could be a bug in treesitter that has been fixed. Want to try updating and see if your issue is resolved?

**Comment by mehalter** [comment]
Ok glad you got past it! I'm going to go ahead and close this since there isn't anything to do on the AstroNvim end. If there is an issue it would be upstream rather than in our codebase.
