### ISSUE TITLE
What is this symbols showing in the bottom bar?

### ISSUE THREAD

**Issue by Lesnock** [AstroNvim/AstroNvim#2445]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Windows 10 WSL - Ubuntu 22.04.2 LTS

### Terminal/GUI

Windows Terminal

### AstroNvim Health

astronvim: require("astronvim.health").check()
  3
  4 AstroNvim
  5 - AstroNvim Version: v3.42.2
  6 - Neovim Version: v0.9.1
  7 - OK Using stable Neovim >= 0.8.0
  8 - OK git is installed: Used for core functionality such as updater and plugin management
  9 - OK open is installed: Used for gx mapping for opening files with system opener (Optional)
 10 - WARNING lazygit is not installed: Used for mappings to pull up git TUI (Optional)
 11 - OK node is installed: Used for mappings to pull up node REPL (Optional)
 12 - WARNING gdu is not installed: Used for mappings to pull up disk usage analyzer (Optional)
 13 - WARNING btm is not installed: Used for mappings to pull up system monitor (Optional)
 14 - OK python3 is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Sometimes this symbols appear. I couldn't associate with a specific event.

### Steps to Reproduce

Just use astronvim, and this appears many times.

### Expected behavior

Not show this symbols

### Screenshots

![image](https://github.com/AstroNvim/AstroNvim/assets/19783675/66a90d34-2f36-4e90-998a-2ff118a2629a)

**Comment by Lesnock** [comment]
My updated config is in this repository:
https://github.com/Lesnock/astronvim-user-config

For I can tell, there is no specific steps that cause this...
Sometimes, when I open nvim, this symbols just show, and sometimes when I'm typing, or moving...

I guess this could be some Telescope problem, because sometimes it shows "Telescopeprompt" word before this symbolss

**Comment by mehalter** [comment]
`telescopeprompt` would be shown when you have telescope open because that's the filetype of the prompt buffer. I cannot replicate this. I also looked at the codebase and we don't even have a `^` character in anything that touches the heirline configuration.

I loaded up your configuration to take a look and the colors and things seems super off. I can't even read the statusline like it seems like you can:

![2024-02-02_07:39:04_screenshot](https://github.com/AstroNvim/AstroNvim/assets/1591837/6856510b-45b9-49b3-9d43-f3d057a26e14)

Are you using a terminal or are you using some neovim GUI application?

**Comment by Lesnock** [comment]
I'm using Windows Terminal with WSL.
Look, I tried to search for a file with Telescope and this appeared:

![image](https://github.com/AstroNvim/AstroNvim/assets/19783675/69a87b5e-1508-4da0-b8ec-61564f8f5a78)

**Comment by mehalter** [comment]
What do you get when you run `:set fillchars?`

**Comment by Lesnock** [comment]
Oh, I think I got a hint.
I changed the theme to astrodark, and now it's working ok.
I was using the ```nobbmaestro/nvim-andromeda``` before

![image](https://github.com/AstroNvim/AstroNvim/assets/19783675/fce1505a-14db-40af-9149-5c654dbb0c4f)

**Comment by mehalter** [comment]
What do you get when you run `:set fillchars?`

**Comment by Lesnock** [comment]
![image](https://github.com/AstroNvim/AstroNvim/assets/19783675/3277976b-bd9a-451d-b7c1-8e124c161b7f)

**Comment by mehalter** [comment]
Can you run that command when you are seeing the `^` across the statusline? It seems like you are getting `stl:^` at some point.

**Comment by Lesnock** [comment]
![image](https://github.com/AstroNvim/AstroNvim/assets/19783675/972c8f1e-5881-4cb3-9260-d65cdfb30e6c)

**Comment by mehalter** [comment]
Could you try updating to the newer bug fix patched of Neovim? Maybe 0.9.5. Sorry, there's not much else I can do here 😅

**Comment by mehalter** [comment]
Relevant upstream issue: https://github.com/neovim/neovim/pull/25267

**Comment by Lesnock** [comment]
I updated to Neovim 0.9.5, but same results when using andromeda theme... ☹

**Comment by mehalter** [comment]
Yeah, looks like this will be fixed in 0.10
