### ISSUE TITLE
mason-nvim-dap not working as expected

### ISSUE THREAD

**Issue by 8FordPrefect8** [AstroNvim/AstroNvim#2449]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

arch linux

### Terminal/GUI

foot

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.42.3
- Neovim Version: v0.9.5
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- WARNING `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

nvim-dap is not working for me. My understanding is that installing debuggers with mason-nvim-dap should make them work without further configuration.
I installed astrocommunity pack/python. I also run `:DapInstall python`
When I open a python file hit F9 I set a breakpoint. When I hit F5 I shortly see the UI, but it closes directly again.

The very same happens with rust.

### Steps to Reproduce

Open python file.
Set breakpoint with F9
Start debugger with F5
See UI opening and closing again.

### Expected behavior

Seeing the UI opened and code stop at break point.

### Additional Context

I also tried to manually configure nvim-dap. But I couldn't sort out a working user/plugins/nvim-dap.lua yet from the nvim-dap pages and the astronvim docs.

**Comment by mehalter** [comment]
Check the dap logs to see what might be happening. This should be looked into at the plugin rather than here. Check out the discord for the help forums to ask questions!

**Comment by brokoli18** [comment]
@frere-jacques In case someone comes across the exact same issue here, the problem might simply be that you did not compile your binary with the -g flag. That was the problem for me.
https://github.com/jay-babu/mason-nvim-dap.nvim/issues/98

**Comment by frere-jacques** [comment]
Actually, I was just using it wrong.
