### ISSUE TITLE
Allow language servers to be run on buffer only if a predicate condition meets

### ISSUE THREAD

**Issue by Tal500** [AstroNvim/AstroNvim#2458]
### Is your feature related to a problem?

In my work, we use a python-like file for our specific domains (say, config, say with filename extension `.x`). I have configured its extension to be mapped as a python filetype in nvim. This gives me nice auto-recognition like treesitter and so on, but I would like to shut down `pylsp` language server on this specific extension `.x`. My motivation is to disable stupid code warnings that have no reason in this domain specific python-like language.

### Describe the new feature

In the custom lsp config section, have an option predicate function field taking the buffer, that given the buffer it returns a boolean value indicating whether to enable or disable the language server for this buffer.

**Comment by mehalter** [comment]
You can configure this by configuring `lspconfig` with `autostart = false` that way it won't attach by default, and then adding your own autocommand for launching it. Here is a basic example to do this in a similar situation you described:

```lua
return {
  lsp = {
    config = {
      pylsp = {
        autostart = false, -- disable autostart
      },
    },
  },
  polish = function()
    -- add a custom python filetype
    vim.filetype.add {
      pattern = {
        [".*%.py%.x"] = "python",
      },
    }

    -- add custom attachement of `pylsp`
    vim.api.nvim_create_autocmd("FileType", {
      pattern = "python",
      callback = function(opt)
        if not vim.api.nvim_buf_is_valid(opt.buf) then return end
        local bufname = vim.api.nvim_buf_get_name(opt.buf)

        if not bufname:match "%.x$" then
          local server = "pylsp"
          local running_client
          for _, client in ipairs(vim.lsp.get_active_clients()) do
            if client.name == server then
              running_client = client
              break
            end
          end
          if running_client then
            vim.lsp.buf_attach_client(opt.buf, running_client)
          else
            require("lspconfig.configs")[server].launch()
          end
        end
      end,
    })
  end,
}
```

I'm not sure if you need more conditions for the root detection check or if it does that automatically with the `lspconfig` `launch` function. Good luck!

**Comment by mehalter** [comment]
Maybe the better approach here would be to use a different filetype altogether rather than hacking it into this model. Here is a different approach that might do what you want:

```lua
return {
  polish = function()
    vim.filetype.add {
      pattern = {
        -- add a custom python sub-filetype
        [".*%.py%.x"] = "python.x",
      },
    }
  end,
}
```

This will set up a sub-filetype for python. It will still get snippets and treesitter, but the language servers won't attach. Might be closer to the behavior you are looking for really without muddling up semantics of the `python` filetype.

**Comment by Tal500** [comment]
> You can configure this by configuring `lspconfig` with `autostart = false` that way it won't attach by default, and then adding your own autocommand for launching it. Here is a basic example `user/init.lua` to do this in a similar situation you described:
> 
> ```lua
> return {
>   lsp = {
>     config = {
>       pylsp = {
>         autostart = false, -- disable autostart
>       },
>     },
>   },
>   polish = function()
>     -- add a custom python filetype
>     vim.filetype.add {
>       pattern = {
>         [".*%.py%.x"] = "python",
>       },
>     }
> 
>     -- add custom attachement of `pylsp`
>     vim.api.nvim_create_autocmd("FileType", {
>       pattern = "python",
>       callback = function(opt)
>         if not vim.api.nvim_buf_is_valid(opt.buf) then return end
>         local bufname = vim.api.nvim_buf_get_name(opt.buf)
> 
>         if not bufname:match "%.x$" then
>           local server = "pylsp"
>           local running_client
>           for _, client in ipairs(vim.lsp.get_active_clients()) do
>             if client.name == server then
>               running_client = client
>               break
>             end
>           end
>           if running_client then
>             vim.lsp.buf_attach_client(opt.buf, running_client)
>           else
>             require("lspconfig.configs")[server].launch()
>           end
>         end
>       end,
>     })
>   end,
> }
> ```
> 
> I'm not sure if you need more conditions for the root detection check or if it does that automatically with the `lspconfig` `launch` function. Good luck!

I have a small issue here - I get an error  `attempt to index a nil value` in the line `require("lspconfig.configs")[server].launch()`. However
