### ISSUE TITLE
Failed to run `config` for indent-blankline.nvim

### ISSUE THREAD

**Issue by tehrelt** [AstroNvim/AstroNvim#2462]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Windows 10, WSL 2 (Ubuntu)

### Terminal/GUI

Terminal

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.43.3
- Neovim Version: v0.10.0-dev-1745+g988b472d9
- WARNING Neovim nightly is not officially supported and may have breaking changes
- OK `git` is installed: Used for core functionality such as updater and plugin management
- WARNING `wslview/xdg-open/rundll32/explorer/open` is not installed: Used for `gx` mapping for opening files with system opener (Optional)
- WARNING `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
- WARNING `node` is not installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

When i try to move cursor, i get this exception:

```
Error detected while processing CursorMoved Autocommands for "*":
Error executing lua callback: ...l/share/nvim/lazy/indent-blankline.nvim/lua/ibl/init.lua:478: invalid key: virt_text_repeat_linebreak
stack traceback:
        [C]: in function 'nvim_buf_set_extmark'
        ...l/share/nvim/lazy/indent-blankline.nvim/lua/ibl/init.lua:478: in function 'refresh'
        ...l/share/nvim/lazy/indent-blankline.nvim/lua/ibl/init.lua:128: in function 'debounced_refresh'
        ...l/share/nvim/lazy/indent-blankline.nvim/lua/ibl/init.lua:144: in function 'debounced_refresh'
        ...are/nvim/lazy/indent-blankline.nvim/lua/ibl/autocmds.lua:27: in function <...are/nvim/lazy/indent-blankline.nvim/lua/ibl/autocmds.lua:26>
        [C]: in function 'nvim_exec_autocmds'
        /home/relt/.config/nvim/lua/astronvim/autocmds.lua:357: in function </home/relt/.config/nvim/lua/astronvim/autocmds.lua:357>
```
                     

### Steps to Reproduce

1. Open a directory in nvim
2. Create a *.c or *.h file
3. Write any code with indents

### Expected behavior

Successfully moved cursor without error

### Screenshots
It appears when i open a file with indents
![WindowsTerminal_siWzVCwCyB](https://github.com/AstroNvim/AstroNvim/assets/51410636/e72bdedf-85c8-4740-9707-d02f977ef67b)

It appears every time when i try to move cursor
![WindowsTerminal_LNuD6nZQYi](https://github.com/AstroNvim/AstroNvim/assets/51410636/8cc97e0e-05f3-42de-8b4d-1379e8de08f2)

### Additional Context

It appeared after i updated astrovim to 3.43.3

**Comment by mehalter** [comment]
Neovim nightly is not officially supported and it is up to you to keep up to date with news and neovim development to maintain a stable editor.

For this case in particular you are just running an out of date version of neovim nightly and need to update it. There are breaking changes and developers develop for the release of neovim v0.10. They do not maintain any support for arbitrarily old nightly builds.

Also for these types of upstream issues, please be sure to look at the plugin repository and search their issues before opening something here: [indent-blankline.nvim Issues](https://github.com/lukas-reineke/indent-blankline.nvim/issues?q=virt_text_repeat_linebreak)
