### ISSUE TITLE
Not getting a return from user command

### ISSUE THREAD

**Issue by Bitals** [AstroNvim/AstroNvim#2468]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

ArchLinux

### Terminal/GUI

Alacritty

### AstroNvim Health

   4   AstroNvim
   5   - AstroNvim Version: v3.43.4
   6   - Neovim Version: v0.9.5
   7   - OK Using stable Neovim >= 0.8.0
   8   - OK git is installed: Used for core functionality such as updater and plugin management
   9   - OK xdg-open is installed: Used for gx mapping for opening files with system opener (Optional)
  10   - OK lazygit is installed: Used for mappings to pull up git TUI (Optional)
  11   - OK node is installed: Used for mappings to pull up node REPL (Optional)
  12   - WARNING gdu is not installed: Used for mappings to pull up disk usage analyzer (Optional)
  13   - WARNING btm is not installed: Used for mappings to pull up system monitor (Optional)
  14   - OK python is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

I try to print the output of the user command as a test in user/init.lua:

```
  require("astronvim.utils").notify("Outsider:  "..vim.cmd.NotifyOS("test")),
```
Which always gets back `nil`. I also try to execute it while defining a variable to avoid any problems another plugin in the chain might introduce, but to no avail (available at user/utils/updater.lua, too long to post here I think), also gets back `nil`.

Why is this? Or is output/return not supported from user commands? I wasn't able to find such statement in neither AstroNvim Docs nor NeoVim wiki.

### Steps to Reproduce

I defined a function in user/utils/notifier.lua:

```
return{
  notify = function(opts)
    local content = opts.fargs[1]
    local replace = opts.fargs[2]
    if (replace == nil) then
      replace = ""
    else
      replace = tostring("-r "..replace)
    end
    -- debug
    require("astronvim.utils").notify("Replacer: "..replace)
    local id = tostring(io.popen("notify-send -t 10000 -a Neovim -i nvim -e -p \'"..content.."\' "..replace):read("a"))
    -- debug
    require("astronvim.utils").notify("Insider: "..id)
    return id
  end
}
```

It calls the `notify-send` system utility with the `-p` argument, which returns a notification ID to `STDOUT`. This works. Value is read inside the function, debug with `notify` nvim plugin prints it out fine.

It is wrapped inside a user command in user/init.lua:

```
  vim.api.nvim_create_user_command(
    "NotifyOS",
    function(opts)
        return require("user.utils.notifier").notify(opts)
    end,
    {
      nargs = "*",
      desc = "Send desktop notification",
      bang = true
    }
  ),
```
Which also works fine. If I replace `return` with `print(require...)`, it prints the returned notification ID no problem.

I try to print the output of the user command as a test later in user/init.lua:

```
  require("astronvim.utils").notify("Outsider:  "..vim.cmd.NotifyOS("test")),
```
Which always gets back `nil`. I also try to execute it while defining a variable to avoid any problems another plugin in the chain might introduce, but to no avail (available at user/utils/updater.lua, too long to post here I think), also gets back `nil`.

Why is this? Or is output/return not supported from user commands? I wasn't able to find such statement in neither AstroNvim Docs nor NeoVim wiki.

### Expected behavior

User commands successfully return their output.

### Screenshots

![image](https://github.com/AstroNvim/AstroNvim/assets/11341915/289cb441-cf5e-4300-b9a2-cac188c8abdd)

### Additional Context

https://github.com/Bitals/astronvim/tree/broken
`broken` branch.

**Comment by Bitals** [comment]
Much simpler test inside user/init.lua:

```
  vim.api.nvim_create_user_command(
    "TestF",
    function()
      local i = "fgdgvgf"
      -- return "kljugb"
      return i
      -- print("icfobyhb")
    end,
  {}),

  require("astronvim.utils").notify(vim.cmd.TestF()),
```
Result:
![image](https://github.com/AstroNvim/AstroNvim/assets/11341915/64f6f852-2962-4beb-9eca-4bcf58f34fa1)

**Comment by mehalter** [comment]
Thanks for reporting! This is a core Neovim function and unrelated to AstroNvim. This would be a feature request to be made upstream, but I think this is just a misunderstanding of what a user command is in vim/Neovim and the behavior is intended. I believe what you want is just a function in Lua and not a user command. Hope that helps! If you have further questions, check out the official Discord! There are lots of users that can help answer questions about vim/Neovim in general and AstroNvim.

**Comment by Bitals** [comment]
>I believe what you want is just a function in Lua and not a user command.

Thanks for your input.
I thought about this, but can't seem to grasp the syntax:
```
98  require("astronvim.utils").notify(require("user.utils.notifier"){"test", "352"}),
```
Gives:
```
/home/bitals/.config/nvim/lua/user/init.lua:98: attempt to call a table value
```
Result is the same no matter how I pass the arguments, `{"1", "2"}`, `{1}`, `("1")`, `("1", "2")`

**Comment by Bitals** [comment]
> I believe what you want is just a function in Lua and not a user command.

Thanks for you input.
I thought about this, ~~but can't grasp the syntax~~ I did, the problem was me.
