### ISSUE TITLE
Open toggleterm  in Neotree at current cursor 

### ISSUE THREAD

**Issue by WikiLiu** [AstroNvim/AstroNvim#2469]
### Is your feature related to a problem?

I open toggleterm then local at root-dir everytime, then i need "cd linux-6.5.2...etc", or input toggleterm with parameter of directory  . But like vscode, can open terminal in current directory or file`s parent directory, very convenient. 

### Describe the new feature

case 1(current cursor in neo-tree and in folder):  push a key(such as T), then open toggleterm  in current folder/directory
case 2(current cursor in neo-tree and in file):  push a key(such as T), then open toggleterm  in parent folder/directory

### Additional context

Im not good at lua, so i try to change user/plugin/neotree.lua, and add a command in opts. i dont know how to pass node:get_id() to toggleterm

**Comment by WikiLiu** [comment]
open_terminal = function(state)
	  local node = state.tree:get_node()
          local path = node:get_id()
	path = node.type == "directory" and path or vim.fn.fnamemodify(path, ":h")
	local myCommand = "ToggleTerm dir=" .. path
	local commandString = "vim.cmd[[" .. myCommand .. "]]"
	load(commandString)()
        end,

**Comment by WikiLiu** [comment]
but only once work，due to toggleterm not auto-close.


	 open_terminal = function(state)
	  local node = state.tree:get_node()
          local path = node:get_id()
	path = node.type == "directory" and path or vim.fn.fnamemodify(path, ":h")
	local myCommand = "ToggleTerm  dir=" .. path
	local register = '*'
	vim.cmd('let @' .. register .. ' = ' .. vim.fn.string(path))
	local commandString = "vim.cmd[[" .. myCommand .. "]]"
	load(commandString)()
        end,

**Comment by mehalter** [comment]
Thanks for the recommendation! I have implemented a version of this on AstroNvim nightly! If you can give it a test and see what you think that would be amazing 😄

**Comment by mehalter** [comment]
Awesome, thanks for testing it out! I'll get that tagged and released tomorrow!
