### ISSUE TITLE
Neotree moving in project

### ISSUE THREAD

**Issue by korchizhinskiy** [AstroNvim/AstroNvim#2471]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Manjaro Linux 23.1

### Terminal/GUI

alacritty

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: v3.43.4
- Neovim Version: v0.9.5
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

When I move from an open file to the neotree window, and try to open a folder, I am thrown to another directory or file, I suspect randomly.
There were cases that gave me the opinion that it would jump to the folder of the same name in the project, but I couldn't repeat this case again.

For open directory/file I am using "w" or "l" ( <- L lower)

### Steps to Reproduce

1. Open neotree bar
2. Open some file
3. Go to neotree by "C-l or C-h"
4. go to another directory
5. open by "w" or "l"

https://github.com/AstroNvim/AstroNvim/assets/100942887/117f4037-a72c-400b-9185-1961ee4506af

### Expected behavior

Сursor stay on opening directory

**Comment by mehalter** [comment]
Duplicate #2424
