### ISSUE TITLE
Multiple toggleterm sessions doesn't work with v3.43.4

### ISSUE THREAD

**Issue by vtvz** [AstroNvim/AstroNvim#2473]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Manjaro Linux 23.1.3

### Terminal/GUI

kitty

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: v3.43.4
- Neovim Version: v0.9.5
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

In the previous version, I could use `n<C-\>` keystroke where `n` is a number to open multiple terminal sessions. Now this functionality broke. `n<C-'>` open the same session

The same as #1055

### Steps to Reproduce

1. Open neovim with astronvim v2
2. Press `Ctrl+'`
3. Write something
4. Press `2` `Ctrl+'`
5. See your writings

### Expected behavior

Have a different terminal session

### Screenshots

https://asciinema.org/a/WS9cFjXKaa802o0XlwvPFat3N
In the right corner, you can see the printed number

### Additional Context

With this config works as expected:
```lua
  -- in plugins
  {
    "akinsho/toggleterm.nvim",
    opts = {
      open_mapping = [[<c-'>]],
    },
  },
  -- in mappings 
  [ [[<c-'>]] ] = false,
```

---

I use this setup in my personal config and it works as a charm

**Comment by mehalter** [comment]
As mentioned here this is a duplicate. We need to localize discussion rather than making new issues to make it easier for other users to follow. We can always reopen issues

Discussion continues at #1055
