### ISSUE TITLE
How to configure code_runner

### ISSUE THREAD

**Issue by xuesj1** [AstroNvim/AstroNvim#2481]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

archlinux

### Terminal/GUI

konsole

### AstroNvim Health

AstroNvim Version: v3.44.0
Neovim Version: v0.9.5
OK Using stable Neovim >= 0.8.0

### Describe the bug

I successfully installed [code_runner](https://github.com/CRAG666/code_runner.nvim) and tried to configure it to run my cpp program better, I checked the plugin's literature and it only mentions the lua code needed to configure it, but I don't know where to put it in AstroNvim to use it!

### Steps to Reproduce

1. Created the ~/.config/nvim/lua/user folder and created the init.lua file.
2. put the following code into the file in order to install code_runner
``--- user/init.lua
return {
  plugins = {
    { "CRAG666/code_runner.nvim",
      config = true,
      lazy=false,
    }
}
``
4. After successful installation tried to configure the plugin, but didn't know how to do it

### Expected behavior

Was able to successfully configure the code_runner plugin to run my cpp program

### Additional Context

Finally, I apologize for my terrible English, I used DeepL translator for the above text!

**Comment by mehalter** [comment]
You can use the `opts` table or the `config` function in `lazy.nvim` to configure the `setup` call for the plugin which is how you typically configure plugins. Check out the documentation here for doing the `setup` call: https://docs.astronvim.com/recipes/custom_plugins/#full-example

If you have any further questions, check out the help forum in the official discord which has many more contributors and users who can help provide guidance for configuration.
