### ISSUE TITLE
Error while editing

### ISSUE THREAD

**Issue by eagle-tex** [AstroNvim/AstroNvim#2486]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Linux Ubuntu

### Terminal/GUI

Gnome

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.44.1
- Neovim Version: v0.9.5
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

The error message occurs when calling a function.
For example `console.log(`   // as soon as the parenthesis is open, the error appears

### Steps to Reproduce

1. Open a javascript file (or maybe another programming language, I haven't tested with another language)
2. Call a function and notice if there's any error in the command area below when the parenthesis to call the function is open.

### Expected behavior

Nothing should be happening while calling a function. That's how it was going before the latest update (to v3.44.1)

### Screenshots

![2024-03-08 Astronvim error on function call](https://github.com/AstroNvim/AstroNvim/assets/70228400/e644aa56-37e2-4f98-8a16-e42d094d1798)

**Comment by mehalter** [comment]
As mentioned in the error, this is coming from the `lsp_signature` plugin and is completely unrelated to AstroNvim. It looks like from the error messages it is trying to call `get_clients` which is a new function in Neovim 0.10+ (currently nightly) which deprecates an old function. This Should be reported to that plugin rather than here.

**Comment by mehalter** [comment]
Actually, I searched their issues and this is already fixed upstream: https://github.com/ray-x/lsp_signature.nvim/issues/311

You just need to update the plugin in lazy
