### ISSUE TITLE
ToggleTerm does not remember latest open terminal

### ISSUE THREAD

**Issue by vtvz** [AstroNvim/AstroNvim#2489]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

ManjaroLinux 23.1.3

### Terminal/GUI

kitty

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.44.2
- Neovim Version: v0.9.5
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Previously when you open a "numbered" terminal (like `2<F7>` / `2<c-'>`), hide it and reopen it without the number you'll land on the previously opened one. Now it opens only the first which is really inconvenient in fluent work

> 

### Steps to Reproduce

1. Open terminal (`<F7> / <C-'>`)
2. Hide current terminal (`<F7> / <C-'>`)
3. Open another terminal (`2<F7> / 2<C-'>`)
4. Hide it 
5. Open terminal (`<F7> / <C-'>`)
6. The first terminal will be opened

### Expected behavior

The previously opened terminal should be opened (2'nd in this case)

### Screenshots

https://asciinema.org/a/bJ3XkOJuvcLhmZvNplmeWoBEt

`// sorry for typo`

**Comment by mehalter** [comment]
Thanks for reporting! This should be resolved in v3.45.0 :)
