### ISSUE TITLE
subsititute command with 'n' flag to calc number of matches, the number reported is hidden

### ISSUE THREAD

**Issue by Etavioxy** [AstroNvim/AstroNvim#2494]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 11.5

### Terminal/GUI

alacritty

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.44.2
- Neovim Version: v0.9.5
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu-go` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

the number reported is hidden by the neovim plugin UI, i am using astrodark theme and the default plugins.

### Steps to Reproduce

new file
type
```
123451234512345
1234512345
123451234512345
1234512345
```
run`:%s/123//gn`, press enter
couldn't see the result

### Expected behavior

.

**Comment by mehalter** [comment]
We hide the command line bar by default. You can disable it in your configuration if you use it in your user configuration: https://docs.astronvim.com/recipes/cmdheight/
