### ISSUE TITLE
When finallshell is used, there is a bug and a wrong line

### ISSUE THREAD

**Issue by class-g** [AstroNvim/AstroNvim#2502]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

centos7.9 and finalshell4.3.10

### Terminal/GUI

finalshell4.3.10

### AstroNvim Health

astronvim: require("astronvim.health").check()
   3   
   4   AstroNvim
   5   - AstroNvim Version: v3.45.3
   6   - Neovim Version: v0.9.4
   7   - OK Using stable Neovim >= 0.8.0
   8   - OK git is installed: Used for core functionality such as updater and          plugin management
   9   - OK open is installed: Used for gx mapping for opening files with              system opener (Optional)
  10   - WARNING lazygit is not installed: Used for mappings to pull up git            TUI (Optional)
  11   - WARNING node is not installed: Used for mappings to pull up node              REPL (Optional)
  12   - WARNING gdu is not installed: Used for mappings to pull up disk               usage analyzer (Optional)
  13   - WARNING btm is not installed: Used for mappings to pull up system             monitor (Optional)
  14   - OK python is installed: Used for mappings to pull up python REPL              (Optional)

### Describe the bug

When finallshell is used, there is a bug, the wrong line, and there will be a wrong line or a new line all the time, I hope it can be optimized, I like to use it, there is no such problem when using vi or vim, please fix it

### Steps to Reproduce

When finallshell is used, there is a bug, the wrong line, and there will be a wrong line or a new line all the time, I hope it can be optimized, I like to use it, there is no such problem when using vi or vim, please fix it

### Expected behavior

When finallshell is used, there is a bug, the wrong line, and there will be a wrong line or a new line all the time, I hope it can be optimized, I like to use it, there is no such problem when using vi or vim, please fix it

**Comment by class-g** [comment]
Hope to get a reply

**Comment by mehalter** [comment]
Can you please succinctly describe the bug and steps to achieve it. I cannot understand what was described in the issue text

**Comment by class-g** [comment]
1. The latest version of finalshell
2. I will first set up the environment for Centos7
3. I will download and install NVIM first
4. At this point, use Astronvim to download the latest version, and then it will automatically download the plugin
5. At this point, everything is complete. When using NVIM to open a file, there may be errors, confusion, and misalignment

**Comment by class-g** [comment]
That's roughly the situation. If you try it on your end, this situation will appear. It's strange

**Comment by class-g** [comment]
Could you please take a look at what the problem is? I won't encounter this problem using normal NVIM. I will use other lunarvim and lazyvim
I have tried all of them, but there is no such situation, and the default one is also not. The plugin is also normal, and I really like using Astrovim. I hope you can help solve this problem

**Comment by class-g** [comment]
I think Astrovim is very strong and great. Come on, and many of them are reasonable. However, this problem is very troubling and uncomfortable for me. I can't understand it, so I can only ask you to handle it. Thank you, come on

**Comment by class-g** [comment]
![Uploading image.png…]()
The operation steps are as I said, as shown in the picture, they are disorderly

**Comment by class-g** [comment]
![Uploading PixPin_2024-03-27_21-47-50.png…]()
![image](https://github.com/AstroNvim/AstroNvim/assets/76509232/96da4471-dd38-4262-91b5-d269757dcbc9)

**Comment by class-g** [comment]
:q exit is also abnormal, and it is also disorderly and misplaced
Also, there is an extra line above, which is very strange

**Comment by class-g** [comment]
![Uploading PixPin_2024-03-27_21-47-50.png…]()

**Comment by class-g** [comment]
![PixPin_2024-03-27_21-47-50](https://github.com/AstroNvim/AstroNvim/assets/76509232/62e1d6f5-9fee-4148-a2cf-f7e6c7efea1e)

**Comment by mehalter** [comment]
Thanks for explaning. The images are quite helpful. It looks like the `statusline` and `tabline` are having issues rendering inside of FinalShell. Absolutely no idea what could be causing this, but seems deeper than just AstroNvim. I have tried to install FinalShell and cannot get it running locally without getting lots of errors so I cannot replicate this. I'll leave this issue open and hopefully someone comes along that can debug this and try to help!

Sorry I can't do much about this 😞

**Comment by peniar** [comment]
I'm using Alacritty on macOS. I had a similar issue. It was a hard time finding the problem, but solved it.

`:lua vim.o.title=false`

**Comment by mehalter** [comment]
@class-g could you see if setting `vim.opt.title = false` fixes your issue?

**Comment by class-g** [comment]
@peniar @mehalter I couldn't find this configuration, and even though I tried it, it didn't seem to work. I'm not sure if the configuration was incorrect

**Comment by class-g** [comment]
I found that entering him is normal, but when you use `:q` and then press ESC, and then use `jkjk` again, he will encounter this problem

**Comment by class-g** [comment]
Or you can use edit mode and then press `ESC.` When using `jkjk,` this problem will occur all the time. I have reinstalled it many times and it still remains the same. Currently, I cannot find a solution, which is very troublesome

**Comment by peniar** [comment]
@class-g  It could be another issue. My problem was [this](https://asciinema.org/a/nXNRvg1tyQxyfTXhhaRil8NGQ)

**Comment by mehalter** [comment]
@class-g try adding this to the file `~/.config/nvim/lua/plugins/disable_title.lua`:

```lua
return {
  "AstroNvim/astrocore",
  opts = { options = { opt = { title = false } } },
}
```

And see if it works, this is how to apply what the other user recommended.

**Comment by class-g** [comment]
I have already set it up, but it has not had much effect. Will this issue not occur when you use the final shell

**Comment by class-g** [comment]
I have already set it up, but it has no effect. You should also have problems using the final shell. I have tried this problem many times, but it still exists and cannot be solved at the moment

**Comment by class-g** [comment]
I used the latest version of "AstroNvim", and now everything is normal and there are no issues. The previous version may have issues
