### ISSUE TITLE
Cpplint Cannot Work Effectively

### ISSUE THREAD

**Issue by OMObuan** [AstroNvim/AstroNvim#2521]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Archlinux

### Terminal/GUI

fish

### Describe the bug

I have installed "cpplint" in the mason, but it cannot work effectively in a cpp file. I have checked "LspInfo" and it did not displayed "cpplint" in its output.
![Picture1](https://github.com/AstroNvim/AstroNvim/assets/150120115/a6864cce-90fd-4801-a3fb-d602ba3e0c15)
![Picture2](https://github.com/AstroNvim/AstroNvim/assets/150120115/a9714ff2-81db-45b6-8a71-6c65ce1bfaf6)

### Steps to Reproduce

1. git clone the template
2. opened mason and installed cpplint
3. opened a cpp file
4. found that it did not display in "LspInfo"

### Expected behavior

LspInfo displays cpplint's information and it can work correctly.

### Screenshots

![Picture1](https://github.com/AstroNvim/AstroNvim/assets/150120115/a3291d3c-be64-433f-a58d-251c846e6dab)
![Picture2](https://github.com/AstroNvim/AstroNvim/assets/150120115/686a63d5-a278-479b-b9a1-e7b4307ce322)

### Additional Context

I have both tried it in two different computers (they have the same system) and they both didn't work.

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", branch = "v4", import = "astronvim.plugins" },

  -- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by mehalter** [comment]
`cpplint` was deprecated from `none-ls` built ins a couple months ago. This was in order to decrease maintenance burden and is a bit unfortunate to say the least. You will need to configure the linter with `none-ls` manually. Sorry!

Source: https://github.com/nvimtools/none-ls.nvim/discussions/81

**Comment by OMObuan** [comment]
> `cpplint` was deprecated from `none-ls` built ins a couple months ago. This was in order to decrease maintenance burden and is a bit unfortunate to say the least. You will need to configure the linter with `none-ls` manually. Sorry!
> 
> Source: [nvimtools/none-ls.nvim#81](https://github.com/nvimtools/none-ls.nvim/discussions/81)

Thank you very much! I have solved it.
