### ISSUE TITLE
`g.icons_enabled = false` does not disable icons

### ISSUE THREAD

**Issue by cactusbento** [AstroNvim/AstroNvim#2527]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5 Release

### Operating system/version

Arch Linux KDE / pacman -Syu as of post date

### Terminal/GUI

konsole

### Describe the bug

While `g.icons_enabled = false` disable icons for some UI elements, it will not disable all UI elements.

https://docs.astronvim.com/recipes/icons was followed to disable icons.

### Steps to Reproduce

1. Set `g.icons_enabled = false` like:
```lua
  {
  "AstroNvim/astrocore",
    opts = {
      options = {
        g = {
          icons_enabled = false,
        },
      },
    },
  },
```
2. Open file (lsp preferred for more attempts to display icons when not allowed to)

### Expected behavior

All icons to be replaced by plain text, ASCII equivalents, or no characters at all.

### Screenshots

![icons_enabled_not_respected](https://github.com/AstroNvim/AstroNvim/assets/14164311/b0299f6d-c0b1-4b8c-832d-d8651191ea78)

### Additional Context

This happens in the `cmp` menu too.

I'm using the [cozette](https://github.com/slavfox/Cozette) font `v.1.23.2`.

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", tag = "v4.1.7", import = "astronvim.plugins" },
  -- add any other plugins/customizations here
  {
  "AstroNvim/astrocore",
    opts = {
      options = {
        g = {
          icons_enabled = false,
        },
      },
    },
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by mehalter** [comment]
Ah yes, thanks for pointing this out! The documentation page there was out of date. It was covered in the migration guide after this was changed but forgot to populate the original page. I have updated it now: https://docs.astronvim.com/recipes/icons#disable-icons

It needs to be set in the `AstroNvim/AstroNvim` `opts` and not in AstroCore.
