### ISSUE TITLE
nvim-treesitter[javascript]: Could not create tree-sitter-javascript-tmp

### ISSUE THREAD

**Issue by eagle-tex** [AstroNvim/AstroNvim#2528]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Zorin OS (based on Ubuntu)

### Terminal/GUI

Gnome

### Describe the bug

After a fresh install of AstroNvim v4 (in the folder `astronvim_v4`), I opened a React project and tried to open a Javascript file. Here is the error I got (one of many)

[nvim-treesitter] [9/11] Extracting tree-sitter-javascript...
nvim-treesitter[javascript]: Could not create tree-sitter-javascript-tmp
mkdir: cannot create directory ‘tree-sitter-javascript-tmp’: File exists

Press ENTER or type command to continue

![20240406 AstroNvim_v4 treesitter error](https://github.com/AstroNvim/AstroNvim/assets/70228400/5c8ae297-7caf-47fc-aead-ab77907b6bb7)

I have AstroNvim v3 installed in its own directory (AstroNvim), which is still working perfectly.
I'm trying to migrate to v4, but it's not that easy, lots of bugs.

### Steps to Reproduce

Install AstroNvim v4 in the folder `astronvim_v4`)
Open a React project
Open a .js / .jsx / .cjs file

### Expected behavior

Not to have any errors

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", branch = "v4", import = "astronvim.plugins" },

  -- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by mehalter** [comment]
You can retrigger the install by re running `:TSInstall`, sometimes treesitter messes itself up 😅
