### ISSUE TITLE
quit sometimes is very slow

### ISSUE THREAD

**Issue by QianChenglong** [AstroNvim/AstroNvim#2531]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

macOS 13.5.2

### Terminal/GUI

iterm2

### Describe the bug

quit sometimes is very slow

### Steps to Reproduce

1. open file
2. :q

### Expected behavior

quit should quickly

### Screenshots

<img width="1713" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/1881126/ec1c3269-f860-4ffd-b3d2-f22059cac801">
<img width="1713" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/1881126/30301a8e-aa37-40bd-a2c0-0d53a11292fd">
<img width="543" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/1881126/8f65ab79-d76f-4690-b13c-d453619cc0a5">

### Repro

```Lua
~/.config/nvim  main ?1                                                                                                                                                                        ⎈ cls  21:02:24
❯ g lg -n1
* commit a703cdbe01c145e299a1722e51be6bc641b02d88 (HEAD -> main, origin/main, origin/HEAD)
| Author: Micah Halter <micah@mehalter.com>
| Date:   Sat Apr 6 08:09:53 2024 -0400
|
|     chore(astrocore): simplify `L` and `H` example mappings
```

**Comment by mehalter** [comment]
Sadly I cannot replicate this and need some more details into how to diagnose. I'll just leave this open for now and if you notice anything more concrete definitely follow up. Maybe someone else who also experiences this can also provide information

**Comment by QianChenglong** [comment]
> Also please share your configuration to help with diagnosis and debugging

Thank you for your reply. This situation started to occur when I migrated from v3 version to v4. Now I have simplified it to only using the recommended template initial configuration (https://github.com/AstroNvim/template/commit/a703cdbe01c145e299a1722e51be6bc641b02d88), and it still happens like this question.

**Comment by QianChenglong** [comment]
> Sadly I cannot replicate this and need some more details into how to diagnose. I'll just leave this open for now and if you notice anything more concrete definitely follow up. Maybe someone else who also experiences this can also provide information

Sometimes it is very slow and you can exit, but sometimes it is stuck and cannot respond to any operations.Can only forcefully close the terminal. I have tried starting it without any configuration, and nvim is normal.

**Comment by natematykiewicz** [comment]
Just chiming to say that I also experience this occasionally. I use neovim all day and experience it a few times a week ever since upgrading to v4. I'm on the latest stable Neovim.

I don't know what it is. Sometimes, a `:q` will hang for like 30 seconds before it closes. It eventually closes, but it takes forever.

**Comment by natematykiewicz** [comment]
To add more details:

macOS 14.3.1
neovim 0.9.5
iTerm2

**Comment by niflostancu** [comment]
Hello, I've encountered a similar problem, too, but the slowdown happened at neovim **startup only** (it doesn't take any input/command for 30s-1min).

In my case, I figured it out:
I use Lazy's subdirectory import feature, e.g. `{ import = "plugins" }` as to split plugin-specific configuration into `plugins/*.lua` files.

The slowdown problem appears whenever I have an empty `.lua` file (or one with invalid syntax) in an imported path: neovim will temporarily block at startup.

It is easily reproducible this way: simply `touch test.lua` inside an imported dir and see if you get it.
Then fill it with `return {}` and the problem should disappear.
I think it's a Lazy bug, hope I'll find some time to reproduce it on a clean config and report it.

I don't know if this is the same as the bug you're experiencing, but I felt like sharing my experience.

**Comment by mehalter** [comment]
Thanks @natematykiewicz for giving your 2 cents as well. I will continue to leave this open until someone can provide details that can lead to reproducing. The only thing we do on close is save the session with `resession`. That could be a place to start investigating.

@niflostancu thanks for sharing your experience as well. This is unrelated to this issue since it's a delay on startup where the people on this issue are reporting delay on close. Also as you noticed that this bug is a `lazy.nvim` and not part of AstroNvim.

**Comment by mehalter** [comment]
Actually what this probably is @QianChenglong @natematykiewicz is resulting from language servers shutting down. There is a `VimLeavePre` autocommand to safely close language server clients. This very much could cause issues if it takes a while for the clients to close.

**Comment by natematykiewicz** [comment]
I'll try to pay attention if the problem seems isolated to a certain type of file.

**Comment by QianChenglong** [comment]
> Actually what this probably is @QianChenglong @natematykiewicz is resulting from language servers shutting down. There is a `VimLeavePre` autocommand to safely close language server clients. This very much could cause issues if it takes a while for the clients to close.
> 
> Neovim source code: https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp.lua#L786-L833

It's probably related to this. Later I suspected it was related to macos. After restarting the operating system, it didn't appear again.
