### ISSUE TITLE
Error detected while processing WinClosed Autocommands for "*"

### ISSUE THREAD

**Issue by EsharkyTheGreat** [AstroNvim/AstroNvim#2532]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1 release

### Operating system/version

WSL2 Windows

### Terminal/GUI

Windows Terminal Preview

### Describe the bug

Getting this error when trying to open any file using <leader>ff

![image](https://github.com/AstroNvim/AstroNvim/assets/75795114/fdccdf9c-719a-49ff-8c7d-1856d5e47f3c)

### Steps to Reproduce

1. <leader>ff
2. Chose any file

### Expected behavior

File should open when selecting through this, error should not be thrown when closing these types of floating windows

### Screenshots

![image](https://github.com/AstroNvim/AstroNvim/assets/75795114/27de9185-dc56-42f5-baca-bbef37609211)

### Additional Context

I followed the installation steps to setup a fresh instance of AstroVim but I'm not able to use the file select feature thorugh <leader>ff
even after opening a terminal and closing it, same error is thrown

Error detected while processing WinClosed Autocommands for "*":
Error executing lua callback: ...ky/.local/share/nvim/lazy/nvim-ufo/lua/ufo/decorator.lua:378: table index is nil
stack traceback:
        ...ky/.local/share/nvim/lazy/nvim-ufo/lua/ufo/decorator.lua:378: in function 'listener'
        ...ky/.local/share/nvim/lazy/nvim-ufo/lua/ufo/lib/event.lua:54: in function 'emit'
        ...esharky/.local/share/nvim/lazy/nvim-ufo/lua/ufo/main.lua:31: in function <...esharky/.local/share/nvim/lazy/nvim-ufo/lua/ufo/main.lua:30>
        [C]: in function 'nvim_buf_delete'
        ...l/share/nvim/lazy/telescope.nvim/lua/telescope/utils.lua:346: in function 'buf_delete'
        ...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:351: in function '_teardown_func'
        ...zy/telescope.nvim/lua/telescope/previewers/previewer.lua:78: in function 'teardown'
        ...share/nvim/lazy/telescope.nvim/lua/telescope/pickers.lua:1492: in function 'on_close_prompt'
        ...e/nvim/lazy/telescope.nvim/lua/telescope/actions/set.lua:134: in function 'run_replace_or_original'
        ...re/nvim/lazy/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'run_replace_or_original'
        ...re/nvim/lazy/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'run_replace_or_original'
        ...re/nvim/lazy/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
        ...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:253: in function <...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:252>

### Repro

```Lua
running `nvim -u repro.lua` throws error in neovim that
Error detected while processing /home/esharky/repro.lua:
No specs found for module astronvim.plugins
Plugin AstroNvim is not installed

 Cloning into '/home/esharky/.repro/plugins/AstroNvim'...
        fatal: Remote branch v4 not found in upstream origin
```

**Comment by mehalter** [comment]
This has come up previously, I believe this is a bug in early releases of 0.9 that was fixed in newer patch releases. Try upgrading to 0.9.5 and see if it resolves :)

**Comment by EsharkyTheGreat** [comment]
Updating to latest release of Neovim fixed the problem. Thanks 👍
