### ISSUE TITLE
Resort autocompletion (python)

### ISSUE THREAD

**Issue by pigasus55** [AstroNvim/AstroNvim#2538]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.5

### Operating system/version

debian 12

### Terminal/GUI

konsole

### Describe the bug

Autocompletion of pyright is chaotic by default. It is discomfort and difficult to understand unfamiliar libraries.
I think, correct order is sort by: 1) public/privacy(begins from «_») 2) category (properties, methods, …) 3) alphabet.

### Steps to Reproduce

1) install astronvim
2) install pyright or astrocommunity.pack.python

Test code:
```
class TST:
    abc = 0
    zzz = 0

    def __init__(self):
        pass

    def Run_1(self):
        pass

    def Run(self):
        pass

    def Run_QQQ(self):
        pass

    def Run_z(self):
        pass

    def Run_long(self):
        pass

    def Run_a(self):
        pass

    sss = 0

t = TST()
t.
```

Current autocompletion
![1](https://github.com/AstroNvim/AstroNvim/assets/128574753/2156d3dc-2b90-44e1-a04e-fe52a7b34a79)
![2](https://github.com/AstroNvim/AstroNvim/assets/128574753/aa860630-ac7d-43de-ab41-87da9b1367a7)

### Expected behavior

I want to get a list of complete:
```
var abc
var sss
var zzz
method Run
method Run_1
method Run_a
method Run_long
method Run_QQQ
method Run_z
method __init__
method _otherPrivacyMethods
```

### Additional Context

I found https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt   sorting.comparators
But unfortunally, i am 0 in lua.

### Repro

```Lua
https://docs.astronvim.com/#-installation
```

**Comment by mehalter** [comment]
You can configure this by configuring `cmp`. Here is an example of changing sorting in my own dotfiles: https://code.mehalter.com/AstroNvim_user/~files/master/lua/plugins/cmp.lua

If you have any other questions please reach out on the discord help forum as there are many more users available to provide assistance.
