### ISSUE TITLE
Recurring error with HTML file

### ISSUE THREAD

**Issue by eagle-tex** [AstroNvim/AstroNvim#2547]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

ZorinOS (Ubuntu based)

### Terminal/GUI

Gnome

### Describe the bug

When I save an HTML file after editing it, I get the following error 

Error detected while processing BufWritePre Autocommands for "<buffer=9>":
Error executing lua callback: ...t_nvimiRqGrD/usr/share/nvim/runtime/lua/vim/lsp/util.lua:501: Vim:Error executing lua callback: ...t_nvimiRqGrD/usr/share/nvim/runtime/lua/v
im/lsp/sync.lua:248: attempt to get length of local 'prev_line' (a nil value)
stack traceback:
        ...t_nvimiRqGrD/usr/share/nvim/runtime/lua/vim/lsp/sync.lua:248: in function 'compute_end_range'
        ...t_nvimiRqGrD/usr/share/nvim/runtime/lua/vim/lsp/sync.lua:419: in function 'compute_diff'
        ....mount_nvimiRqGrD/usr/share/nvim/runtime/lua/vim/lsp.lua:446: in function 'incremental_changes'
        ....mount_nvimiRqGrD/usr/share/nvim/runtime/lua/vim/lsp.lua:639: in function 'send_changes'
        ....mount_nvimiRqGrD/usr/share/nvim/runtime/lua/vim/lsp.lua:1576: in function <....mount_nvimiRqGrD/usr/share/nvim/runtime/lua/vim/lsp.lua:1563>
        [C]: in function 'nvim_buf_set_text'
        ...t_nvimiRqGrD/usr/share/nvim/runtime/lua/vim/lsp/util.lua:501: in function 'apply_text_edits'
        ...nt_nvimiRqGrD/usr/share/nvim/runtime/lua/vim/lsp/buf.lua:252: in function 'format'
        ...y/AstroNvim/lua/astronvim/plugins/_astrolsp_autocmds.lua:41: in function 'callback_func'
        ...l/share/astronvim_v4/lazy/astrolsp/lua/astrolsp/init.lua:132: in function <...l/share/astronvim_v4/lazy/astrolsp/lua/astrolsp/init.lua:124>
stack traceback:
        [C]: in function 'nvim_buf_set_text'
        ...t_nvimiRqGrD/usr/share/nvim/runtime/lua/vim/lsp/util.lua:501: in function 'apply_text_edits'
        ...nt_nvimiRqGrD/usr/share/nvim/runtime/lua/vim/lsp/buf.lua:252: in function 'format'
        ...y/AstroNvim/lua/astronvim/plugins/_astrolsp_autocmds.lua:41: in function 'callback_func'
"src/index.html" 83L, 2990B written
Press ENTER or type command to continue

### Steps to Reproduce

---

### Expected behavior

I expect the formatting to be "silent" with no error.

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", branch = "v4", import = "astronvim.plugins" },

  -- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by mehalter** [comment]
Please provide more information and your configuration. Please provide steps to reproduce the error, the language servers you have installed and are attached to the buffer, how you are formatting, an example file to format, and your configuration

**Comment by eagle-tex** [comment]
Here are the files

1. **My AstroNvim v4 config**

[20240421-astronvim_v4-CONFIG.zip](https://github.com/AstroNvim/AstroNvim/files/15051016/20240421-astronvim_v4-CONFIG.zip)

Note for the emmet language server, both **emmet_ls** and **emmet_language_server** were installed. I added the 2nd one (emmet_language_server) and I would like to uninstall the 1st one, but as soon as I uninstall it and reopen AstroNvim, it reinstalls itself. Where can I disable emmet_ls installation?
Maybe part of the problem is that both emmet_ls and emmet_language_server trying to format the same file. I don't know.

Is there a way to avoid a language server attaching itself to a filetype? Is it done through the _ignore_filetypes_ option?


2.  **The project I'm having the problem on. See the _index.html_ file in _src/_ folder. Add some tags here and there and save the file many times.

[20240421-tailwind-css-v3-PROJECT.zip](https://github.com/AstroNvim/AstroNvim/files/15051026/20240421-tailwind-css-v3-PROJECT.zip)

3. I am formatting through FORMAT_ON_SAVE. I just save the file and prettier does it thing. Or I run the _prettier:fix_ script from package.json


4. ** The language server attached to the file (as of 30 minutes ago)**
![2024-04-21 08-51-02 language servers attached to html file](https://github.com/AstroNvim/AstroNvim/assets/70228400/806128b2-de7c-42f9-9111-60e8aa964275)
![2024-04-21 08-52-14 language servers attached to html file - part2](https://github.com/AstroNvim/AstroNvim/assets/70228400/84a956db-c6c8-4d0d-b750-fc52af65c490)


I hope I've provided you with all the information needed. Do not hesitate if you need more info, I'd be happy to provide them. 

Thank you for your time. I know I've already said it on another issue, but again, thank you very much.

**Comment by eagle-tex** [comment]
And I need to say it again.
Thank you for your time. 
I know I've already said it to you on another issue/post, but again, thank you very much for all the work you do, your quick response time, for developping/maintaining/keeping this project up. You're probably not in the military but if you ever dreamed of someone saying it to you, here it is _**THANK YOU FOR YOUR SERVICE, SIR**_.

**Comment by mehalter** [comment]
I have installed your configuration fully and added the second `emmet_language_server` and have everything attached and pulled up that exact project you shared and cannot replicate your issue sadly:

https://asciinema.org/a/Yt7zeBWWHjjQcBEJgamrTaNIm

As for your question, `emmet_ls` is provided in the html pack which is also included in the tailwindcss pack. So it is getting added to your `ensure_installed` table for `mason-lspconfig`. You can add a line like this to your `mason-lspconfig` configuration to remove it:

```lua
      -- remove `emmet_ls` that is in the community pack
      opts.ensure_installed = vim.tbl_filter(function(server) return server ~= "emmet_ls" end, opts.ensure_installed)
```

Also if there is a reason to use `emmet_language_server` over `emmet_ls` then feel free to open a PR to AstroCommunity to improve the defaults.

I did a google of the error message and did find an open issue on core Neovim so that seems pretty related (also unable to be replicated upstream so far it seems. Looking at the error message and where it's originating from it doesn't appear to be an AstroNvim related problem so I don't think there is much more for me to do. Hopefully decreasing the number of language servers help mitigate the upstream bug. If you keep running into this the Discord is probably a great place to ask if other users have also experienced this and have found a way to mitigate it.

**Comment by icholy** [comment]
The workaround is to disable incremental sync for all LSPs.

**Comment by eagle-tex** [comment]
@icholy 

1. What is "incremental sync for LSPs"?
2. and How does one disable incremental sync for all LSPs?

Thank you
