### ISSUE TITLE
Tab character work as spaces

### ISSUE THREAD

**Issue by Mahmoud-Abdelraouf** [AstroNvim/AstroNvim#2549]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.4

### Operating system/version

ubuntu 22.04

### Terminal/GUI

QTerminal

### Issue Description

When editing Makefile files in AstronVim, pressing the tab key inserts spaces instead of tab characters, causing indentation errors when running `make`. Despite setting `expandtab` to false in the `astrocore.lua` configuration file, the problem persists.

### Steps to Reproduce

1. Open a Makefile in AstronVim.
2. Press the tab key to indent lines.
3. Save the file and attempt to run `make`.
4. Encounter indentation errors or unexpected behavior.

### Expected Behavior

Pressing the tab key should insert a tab character, and the Makefile should be formatted correctly. Running `make` should execute without indentation errors.

### Additional Information

- Editing the Makefile in other editors like gedit shows that the tab characters inserted by AstronVim are actually spaces.
- Setting `expandtab` to false in the `astrocore.lua` configuration file did not resolve the issue.
- Even explicitly setting `expandtab` to true does not change the behavior.

### Steps to Reproduce

1. Open a Makefile in AstronVim.
2. Press the tab key to indent lines.
3. Save the file.
4. Open the Makefile in another text editor such as gedit.
5. Observe that the tab characters inserted by AstronVim are interpreted as spaces in the other text editor.
6. Attempt to run `make` in the terminal.
7. Encounter indentation errors or unexpected behavior due to the incorrect interpretation of tab characters.

These steps outline the sequence of actions that lead to the issue of tab characters being misinterpreted when editing Makefile files in AstronVim.

### Expected Behavior

When editing Makefile files in AstronVim:

1. Pressing the tab key should insert a tab character.
2. Tab characters should be recognized as such and not converted to spaces.
3. The Makefile should be formatted correctly with tab characters for indentation.
4. Running `make` should execute without indentation errors or unexpected behavior.

Ensuring that tab characters are inserted correctly and recognized as such is essential for maintaining proper indentation and formatting in Makefile files.

### Screenshots

![Screenshot from 2024-04-22 20-50-05](https://github.com/AstroNvim/AstroNvim/assets/90259729/36c833ab-d5cb-4389-a484-f8bdf801b1e0)

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", branch = "v4", import = "astronvim.plugins" },

  -- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by mehalter** [comment]
Please share your configuration and I can take a look. I cannot replicate given a base installation of AstroNvim

**Comment by mehalter** [comment]
opening or creating a Makefile with a base, clean installation of AstroNvim: https://asciinema.org/a/S8ut0d16BLKk6LRyHeuxc0rUx

**Comment by Mahmoud-Abdelraouf** [comment]
this is the last update of my config, please check it:
https://github.com/Mahmoud-Abdelraouf/astronvim_config

**Comment by mehalter** [comment]
@Mahmoud-Abdelraouf cannot replicate with the latest code: https://asciinema.org/a/MgtNfJf35Nd9bccSROLBSHTEp

**Comment by mehalter** [comment]
Here is a recording of me making new files, saving and reopening the `Makefile`: https://asciinema.org/a/CYllnRtGqMN4zgKA5MwZXb5gd

**Comment by mehalter** [comment]
Please provide some clear steps to reproduce the issue for it to be able to be debugged or identified. Something like:

1. `nvim Makefile`
2. .... do something
3. `:q`
4. `nvim Makefile`
5. `:set expandtab?`, see error

Without something in a reproducible fashion we are unable to validate that the bug actually exists

**Comment by Mahmoud-Abdelraouf** [comment]
https://youtu.be/tA06px7buTg

**Comment by Mahmoud-Abdelraouf** [comment]
okay i will provide these things

**Comment by mehalter** [comment]
Can you share the exact Makefile you are using

**Comment by mehalter** [comment]
Also do you happen to have a `.editorconfig` file in that folder as well?

**Comment by Mahmoud-Abdelraouf** [comment]
> Also do you happen to have a `.editorconfig` file in that folder as well?
No, I don't have any `.editorconfig` file in that folder.

**Comment by Mahmoud-Abdelraouf** [comment]
> Also do you happen to have a `.editorconfig` file in that folder as well?

cc = gcc
CFLAGS = -Wall -Wextra 

#List of Source files
SRC = datatype_size_lookup.c \
      glthread.c \
      memory_manager.c \
      memory_manager_test.c \
      parse_datatype.c \

# List of header files
HDR = colors.h \
      datatype_size_lookup.h \
      glthread.h \
      memory_manager.h \
      memory_manager_api.h \
      parse_datatype.h \
      memory_manager_api.h

# List of object files
OBJ = $(SRC:.c=.o)

# Name of the executable
TARGET = exe

# Command to remove files
RM = rm -f

# Default target
all: $(TARGET)

# Rules to link object files and create the executable
$(TARGET): $(OBJ)
	$(CC) $(CFLAGS) -o $@ $^
	
# Rule to compile C source files object files
%.o: %.c $(HDR)
	$(CC) $(CFLAGS) -c $< -o $@
	
# Clean target
clean:
	$(RM) $(OBJ) $(TARGET)

**Comment by mehalter** [comment]
Yeah this is the problem I describe in the comment above: https://github.com/AstroNvim/AstroNvim/issues/2549#issuecomment-2070997779

Hopefully one of those courses of actions fit your needs! I would definitely recommend going the route of not mixing space and tabs

**Comment by Mahmoud-Abdelraouf** [comment]
> My guess to what is happening here is you have a `Makefile` that is mixing both spaces and tabs (at least it appears so in the video). AstroNvim uses [guess-indent.nvim](https://github.com/NMAC427/guess-indent.nvim) to calculate what the indentation used in a file that is opened to set it in a smart manner. This is probably what is messing things up. I would recommend avoiding mixing spaces and tabs for alignment in programming as this can cause a lot of confusion. You can either:
> 
>     * unmix the tab/spaces from your `Makefile`
> 
>     * remove the `guess-indent.nvim` plugin
> 
>     * further configure the `guess-indent.nvim` plugin to fit your needs (such as exclude `Makefile` filetype)
> 
>     * Set up an `.editorconfig` to manually specify that `Makefile`s in the project should be indented with tabs (https://editorconfig.org/)

I will review this solution and provide feedback.
