### ISSUE TITLE
How to update core plugin pin commit?

### ISSUE THREAD

**Issue by jeeeem** [AstroNvim/AstroNvim#2555]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2930+g47ba96a6b

### Operating system/version

Windows 11

### Terminal/GUI

Wezterm

### Describe the bug

I am encountering this error when I'm trying to go-to definition in JDTLS LSP

![image](https://github.com/AstroNvim/AstroNvim/assets/51053482/c15f491b-64a0-44a9-b85e-d53d6e23b8f0)

This is a bug within the [telescope.nvim ](https://github.com/mfussenegger/nvim-jdtls/issues/589#issuecomment-1821361157) that can be fix with updating the telescope.nvim plugin to latest commit (im not sure what specific commit that will fix this but I wanted to try to pin the latest commit), as of the moment the currently using telescope.nvim plugin release is before the [fix](https://github.com/nvim-telescope/telescope.nvim/issues/2898#issuecomment-1987343706)

### Steps to Reproduce

Assuming already installed the JDTLS LSP

- Open a java file and try going to the definition of tha symbol.

### Expected behavior

Should be able to use "gd" to go-to the definition of the symbol

### Additional Context

I am a newbie user of Astronvim, I may have missed some documentation regarding this.

**Comment by jeeeem** [comment]
@mehalter thanks for the quick response, and also thanks for giving me tips regarding the best way to use this nvim distro. Maybe I will try first the stable one before proceeding to nightly version.

**Comment by mehalter** [comment]
@jeeeem yeah we pin telescope to their latest version. This is also the recommended installation path on their readme. They say _explicitly_ that it's not recommended to use the master branch

**Comment by jeeeem** [comment]
> @jeeeem yeah we pin telescope to their latest version. This is also the recommended installation path on their readme. They say _explicitly_ that it's not recommended to use the master branch

yes. And after a few days, telescope already release their new version [0.1.7](https://github.com/nvim-telescope/telescope.nvim/releases/tag/0.1.7)
