### ISSUE TITLE
Error on `AstroFile` upon fresh installation

### ISSUE THREAD

**Issue by Marin-Kitagawa** [AstroNvim/AstroNvim#2557]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Windows 11 (10.0.22631.3527)

### Terminal/GUI

Windows Terminal

### Describe the bug

Whenever I open a file in Neovim with Astronvim setup according to the docs, I get the following error

```
Error detected while processing User Autocommands for "AstroFile":
No C compiler found! "cc", "gcc", "clang", "cl", "zig" are not executable.
```

### Steps to Reproduce

1. Install Neovim
2. Install Astronvim
3. Open any file

### Expected behavior

The error must not be thrown

### Screenshots

![image](https://github.com/AstroNvim/AstroNvim/assets/49131888/c06a3c33-a3e8-4468-8dfd-18206b9b0197)

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", branch = "v4", import = "astronvim.plugins" },

  -- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by mehalter** [comment]
Please share your configuration

**Comment by mehalter** [comment]
Ah I see the error message. A c compiler is a requirement for treesitter. Please install one as the message indicates
