### ISSUE TITLE
Anoying behavior when completing a code snippet with TAB

### ISSUE THREAD

**Issue by lexrupy** [AstroNvim/AstroNvim#2558]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

linux/debian12

### Terminal/GUI

alacritty

### Describe the bug

AstroNvim documentation says

![image](https://github.com/AstroNvim/AstroNvim/assets/16597/bd7fd720-e79a-46bf-9b86-8fa4b325afe3)

The problem is when you are inside a snippet expansion, and type something in any placeholder, eventualy the completion is triggered again, and the only way to exit this is pressing Ctrl-e, but this is very anoying since it triggers almost for every word you type in placeholders

### Steps to Reproduce

Open a python file and consider the following content:

```
def test(myparam):
    print(myparam)
```

now lets say you want to add a second function called test2 with a parameter called my

```
def test2(my):
    print(my)
```

when you type the parameter "my" you are stuck on second completion menu and have to press Ctrl-e to cancel it.

this just occurs on every function you will have "self" as parameter for example, and as you code grows a bit, it try to complete almost everithing you type.

I sugest remove Tab and Shift-Tab from completion synce almos all vim user are confortable with Ctrl-n Ctrl+p, and also have the option to use Ctrl+j and Ctrl+k

### Expected behavior

When you press Tab inside a Snippet Completion it should go to next placeholder even if a new completion is triggered.

### Screenshots

![image](https://github.com/AstroNvim/AstroNvim/assets/16597/63a1543f-3ca4-4356-a775-b01db6772c3b)

![image](https://github.com/AstroNvim/AstroNvim/assets/16597/e4273315-947b-421e-aed1-a10cc338985d)

### Additional Context

Here I am using a python Django project.

### Repro

```Lua
-- This file simply bootstraps the installation of Lazy.nvim and then calls other files for execution
-- This file doesn't necessarily need to be touched, BE CAUTIOUS editing this file and proceed at your own risk.
local lazypath = vim.env.LAZY or vim.fn.stdpath "data" .. "/lazy/lazy.nvim"
if not (vim.env.LAZY or (vim.uv or vim.loop).fs_stat(lazypath)) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(lazypath)

-- validate that lazy is available
if not pcall(require, "lazy") then
  -- stylua: ignore
  vim.api.nvim_echo({ { ("Unable to load lazy from: %s\n"):format(lazypath), "ErrorMsg" }, { "Press any key to exit...", "MoreMsg" } }, true, {})
  vim.fn.getchar()
  vim.cmd.quit()
end

require "lazy_setup"
require "polish"
```

**Comment by mehalter** [comment]
Thanks for the recommendation! I'm sorry you aren't a fan of the default tab behavior. This is behavior we have investigated greatly and there are many approaches to it. I also personally am not a fan of this "super-tab" behavior it is referred to and I remap tab in my own personal configuration. I would recommend remapping it if you disagree as well. This is the tab behavior many (most) of our users desire and is the recommended "super tab" behavior described in the nvim-cmp docs. We have gone through several different options over the past 2+ years and always get shoved back. Definitely part of maintaining something for the masses.

Sorry this isn't really the best news but hope it can at least shine some light into why this decision is the way it is!

Here are the docs for remapping cmp mappings: https://docs.astronvim.com/recipes/cmp/#customize-keybindings

**Comment by lexrupy** [comment]
I tryed the remappings as of documentation, but I realy and up with the old mapping plus the new mapping.

as the same example of docs:

`
 opts = function(_, opts)
    -- opts parameter is the default options table

    -- the function is lazy loaded so cmp is able to be required

    local cmp = require("cmp")

    -- modify the mapping part of the table

    opts.mapping["<C-x>"] = cmp.mapping.select_next_item()

  end,
`
As I not know much about lua, the documentation is not clear to me how to delete a default mapping.

**Comment by lexrupy** [comment]
I dont know if there is a better way, but I endend up with this code:


```lua

  {
    "hrsh7th/nvim-cmp",
    opts = function(_, opts)
      local luasnip, cmp = require "luasnip", require "cmp"

      local function has_words_before()
        local line, col = (unpack or table.unpack)(vim.api.nvim_win_get_cursor(0))
        return col ~= 0 and vim.api.nvim_buf_get_lines(0, line - 1, line, true)[1]:sub(col, col):match "%s" == nil
      end

      if not opts.mappings then opts.mappings = {} end
      opts.mapping["<Tab>"] = cmp.mapping(function(fallback)
        if luasnip.expand_or_locally_jumpable() then
          luasnip.expand_or_jump()
        elseif has_words_before() then
          cmp.complete()
        else
          fallback()
        end
      end, { "i", "s" })
      opts.mapping["<S-Tab>"] = cmp.mapping(function(fallback)
        if luasnip.jumpable(-1) then
          luasnip.jump(-1)
        else
          fallback()
        end
      end, { "i", "s" })
    end,
  },

```
