### ISSUE TITLE
AstroNvim 4.0 version, shellcheck not displayed and not working

### ISSUE THREAD

**Issue by QianSong1** [AstroNvim/AstroNvim#2563]
![image](https://github.com/AstroNvim/AstroNvim/assets/101644710/4d5e2f09-53d7-401f-94ee-ec88593c3fc3)
![image](https://github.com/AstroNvim/AstroNvim/assets/101644710/02f7fa16-549d-4a70-9cda-09ff3e877e53)
My configuration
![image](https://github.com/AstroNvim/AstroNvim/assets/101644710/3cc555f8-5510-4f32-825a-8789b2e9a581)

**Comment by mehalter** [comment]
None-ls deprecated many built-ins a couple months ago: https://github.com/nvimtools/none-ls.nvim/discussions/81

You will need to add it back yourself

**Comment by QianSong1** [comment]
I have reviewed the link you sent and copied the configuration inside. Is this correct? It works, but I'm not sure if modifying AstroNvim like this is correct or not. Sorry, I'm completely new and I just want a user-friendly editor
![image](https://github.com/AstroNvim/AstroNvim/assets/101644710/38ce10d6-0dea-4e3b-89eb-64d6aed00316)

Now it has appeared
![image](https://github.com/AstroNvim/AstroNvim/assets/101644710/e480cc7d-6226-4c9f-812c-33f6650c40ec)

**Comment by mehalter** [comment]
Yup looks great!
