### ISSUE TITLE
Disable breadcrumbs?

### ISSUE THREAD

**Issue by 1-800-jono** [AstroNvim/AstroNvim#2568]
Been searching for a while now and I think breadcrumbs are coming from `nvim-navic` -> `heirline`. Is there a simple way of disabling the breadcrumbs?

**Comment by mehalter** [comment]
It's actually just heirline using Aerial.nvim for collecting the symbol information. Here are the docs: https://docs.astronvim.com/recipes/disable_winbar/

If you have any other questions feel free to check out the Discord server!
