### ISSUE TITLE
Multiple model bindings

### ISSUE THREAD

**Issue by maobai405** [AstroNvim/AstroNvim#2571]
How do mappings in AstroNvim/astrocore bind mappings to multiple model simultaneously without vim.keymap.set? If every model needs to be rewritten, it's too cumbersome.

Or did I miss a part of the document? But I really didn't find it, so I came to ask questions, hoping to help me

<img width="648" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/121467933/68c79f98-5e9c-49a6-a867-2c1ea7001bef">

**Comment by mehalter** [comment]
This is a limitation of our table based notation that you cannot do this. One thing you can do is just leverage the Lua programming language like this:

```lua
{
  "AstroNvim/astrocore",
  opts = function(_, opts)
    local maps = opts.mappings

    maps.n["<Leader>h"] = "^"
    maps.v["<Leader>h"] = maps.n["<Leader>h"]
  end,
}
```

Or use a for loop or something. Whatever your preference is.

If you have any more questions, a great place to go is the official discord. There are a lot of very active users who can help out!
