### ISSUE TITLE
Bug when closing the toggleterm terminal

### ISSUE THREAD

**Issue by Vitalya-code** [AstroNvim/AstroNvim#2572]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue
- [X] I have run `:Lazy update` and are on the latest version of AstroNvim
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Neovim version (nvim -v)

0.9.1 

### Operating system/version

pop os 20.04

### Terminal/GUI

gnome terminal

### Describe the bug

When I open and then close the terminal by pressing F7 I'm getting an error. When I edit .txt files everything is fine, but when I edit .rs files I get an error

[error.txt](https://github.com/AstroNvim/AstroNvim/files/15209507/error.txt)

### Steps to Reproduce

1. Open any .rs file with rust-analyzer enabled in Mason
2. Open the terminal by pressing F7
3. Get an error(see file attached)

### Expected behavior

I should not get an error after closing the terminal by pressing F7 again

### Screenshots

![Screenshot from 2024-05-04 12-24-03](https://github.com/AstroNvim/AstroNvim/assets/58048618/224fdb9f-29e9-489e-9a8e-1da665d20ee1)

### Additional Context

When I run checkhealth in nvim it says this "ERROR Nvim-treesitter requires Nvim 0.9.2 or newer" so I think it may not work because my Nvim version is 0.9.1

I can't reproduse the issue with repro.lua

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", import = "astronvim.plugins" },

  -- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by Vitalya-code** [comment]
No, I actually can reproduce the error with repro.lua

**Comment by mehalter** [comment]
This is a bug in neovim that is fixed in newer stable releases. Update to something like neovim 0.9.5 and try it :)

**Comment by Vitalya-code** [comment]
Ok, thanks
