### ISSUE TITLE
`<Leader>gg` and `<Leader>tl` always map to the same command

### ISSUE THREAD

**Issue by LeitMoth** [AstroNvim/AstroNvim#2574]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue
- [X] I have run `:Lazy update` and are on the latest version of AstroNvim
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Neovim version (nvim -v)

0.9.5 release

### Operating system/version

Linux 6.8.8-zen (Garuda)

### Terminal/GUI

Alacritty

### Describe the bug

Assigning a command to either `mappings.n["<Leader>tl"]` or `mappings.n["<Leader>gg"]` assigns the command to both.

### Steps to Reproduce

`nvim -u repro.lua`
Then press `<Leader>gg`
A message will appear, despite not having rebound `<Leader>gg` in repro.lua

### Expected behavior

`<Leader>gg` should continue to bring up lazygit.
In repro.lua, I only bound `<Leader>tl`, this should not have affected `<Leader>gg`.

### Additional Context

I am very inexperienced with lua, but I believe I have found the problem:
https://github.com/AstroNvim/AstroNvim/blob/f3dbb860e76b5a2de2a301fc7b7ad1cc3b590150/lua/astronvim/plugins/toggleterm.lua#L22
My theory:
This line of code ends up making these two keybinds reference the exact same table (i.e., store the same pointer, or the equivalent of that in lua terms). Lazy.nvim's method of merging the `opts` tables likely preserves this aliasing, leading to the behavior above.

If that is correct, this may be an issue with lazy itself. But the fix here should be very simple, just replacing the line above with however you copy a table in lua, instead of directly assigning.

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	-- stylua: ignore
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable",
		lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
	{ "AstroNvim/AstroNvim", import = "astronvim.plugins" },
	{
		"AstroNvim/astrocore",
		dependecies = { "rcarriga/nvim-notify" },
		opts = {
			mappings = {
				n = {
					["<Leader>tl"] = {
						function()
							require("notify")("This should only appear when pressing SPACE t l")
						end,
						desc = "Should only be bound to SPACE t l",
					},
				},
			},
		},
	},

	-- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by mehalter** [comment]
This is sorta by design. We can not reuse mappings and just duplicate it to have more separation between mappings

**Comment by LeitMoth** [comment]
Thank you for such a quick fix!
