### ISSUE TITLE
plugin `nvim-metals` doesn't work in Astronvim

### ISSUE THREAD

**Issue by FrankOu2001** [AstroNvim/AstroNvim#2579]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue
- [X] I have run `:Lazy update` and are on the latest version of AstroNvim
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Operating system/version

macOS Sonoma 14.4.1 arm64, Debian 12.5

### Terminal/GUI

iTerm2

### AstroNvim Health

Mac:
==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v4.6.2
- Neovim Version: v0.9.5
- OK Using stable Neovim >= 0.9.5
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- WARNING `rg` is not installed: Used for Telescope `live_grep` picker, `<Leader>fw` and `<Leader>fW` by default (Optional)
- WARNING `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu-go` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

Debian12:

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v4.6.2
- Neovim Version: v0.9.5
- OK Using stable Neovim >= 0.9.5
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- WARNING `rg` is not installed: Used for Telescope `live_grep` picker, `<Leader>fw` and `<Leader>fW` by default (Optional)
- WARNING `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

I installed the plugin [nvim-metals](https://github.com/scalameta/nvim-metals) and opened an existing Scala file. However, nvim did not respond (typing any key had no effect), and the CPU usage was at 100%, while the memory usage was increasing.

### Steps to Reproduce

1. create file in `~/.config/nvim/lua/plugins/overriden.lua` with content:
```lua
return {
  {
    "scalameta/nvim-metals",
    dependencies = {
      "nvim-lua/plenary.nvim",
    },
    ft = { "scala", "sbt", "java" },
    opts = function()
      local metals_config = require("metals").bare_config()
      metals_config.on_attach = function(client, bufnr)
        -- your on_attach function
      end

      return metals_config
    end,
    config = function(self, metals_config)
      local nvim_metals_group = vim.api.nvim_create_augroup("nvim-metals", { clear = true })
      vim.api.nvim_create_autocmd("FileType", {
        pattern = self.ft,
        callback = function()
          require("metals").initialize_or_attach(metals_config)
        end,
        group = nvim_metals_group,
      })
    end
  }
}
```
2. open astronvim to install the plugin, then quit.
3. create a scala file `a.scala`: `touch a.scala`.
4. open the file: `nvim a.scala`.

### Expected behavior

`nvim-metals` can work well.

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", import = "astronvim.plugins" },
  {
    "scalameta/nvim-metals",
    dependencies = {
      "nvim-lua/plenary.nvim",
    },
    ft = { "scala", "sbt", "java" },
    opts = function()
      local metals_config = require("metals").bare_config()
      metals_config.on_attach = function(client, bufnr)
        -- your on_attach function
      end

      return metals_config
    end,
    config = function(self, metals_config)
      local nvim_metals_group = vim.api.nvim_create_augroup("nvim-metals", { clear = true })
      vim.api.nvim_create_autocmd("FileType", {
        pattern = self.ft,
        callback = function()
          require("metals").initialize_or_attach(metals_config)
        end,
        group = nvim_metals_group,
      })
    end
  }
  -- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by mehalter** [comment]
Not sure what's going on really but I think it is a bit safer to schedule the `initialize_or_attach` call to avoid textlocking. Something like this which seems to work perfectly:

```lua
return {
  {
    "scalameta/nvim-metals",
    dependencies = {
      "nvim-lua/plenary.nvim",
    },
    ft = { "scala", "sbt", "java" },
    opts = function()
      local metals_config = require("metals").bare_config()
      metals_config.on_attach = function(client, bufnr)
        -- your on_attach function
      end

      return metals_config
    end,
    config = function(self, metals_config)
      local nvim_metals_group = vim.api.nvim_create_augroup("nvim-metals", { clear = true })
      vim.api.nvim_create_autocmd("FileType", {
        pattern = self.ft,
        callback = vim.schedule_wrap(function() require("metals").initialize_or_attach(metals_config) end),
        group = nvim_metals_group,
      })
    end,
  },
}
```

Also this is not super complete with AstroNvim because you would want to interface it with our AstroLSP plugin. The [AstroCommunity Scala Pack](https://github.com/AstroNvim/astrocommunity/blob/main/lua/astrocommunity/pack/scala/init.lua) provides a good approach for this. Could also be a good approach to just use the AstroCommunity pack to avoid issues. Here is an example that interfaces with AstroLSP:

```lua
return {
  {
    "scalameta/nvim-metals",
    ft = { "scala", "sbt", "java" },
    opts = function()
      local metals = require "metals"
      local astrolsp_avail, astrolsp = pcall(require, "astrolsp")
      local user_config = astrolsp_avail and astrolsp.lsp_opts "metals" or {}
      if require("astrocore").is_available "nvim-dap" then
        local on_attach = user_config.on_attach
        user_config.on_attach = function(...)
          if type(on_attach) == "function" then on_attach(...) end
          metals.setup_dap()
        end
      end
      return require("astrocore").extend_tbl(metals.bare_config(), user_config)
    end,
    config = function(self, opts)
      vim.api.nvim_create_autocmd("FileType", {
        pattern = self.ft,
        group = vim.api.nvim_create_augroup("nvim-metals", { clear = true }),
        desc = "Initialize and attach nvim-metals",
        callback = vim.schedule_wrap(function() require("metals").initialize_or_attach(opts) end),
      })
    end,
  },
}
```

**Comment by mehalter** [comment]
I have dug into this to see why `schedule_wrap` fixes this and found the root issue. Investigating and will close this for reals once it's truly fixed

**Comment by mehalter** [comment]
Resolved in latest commit. I will get a release tagged soon but GitHub is currently broken

**Comment by FrankOu2001** [comment]
Thank you very much! It works now.

**Comment by i-am-the-slime** [comment]
Can this be installed via `LspInstall` somehow?
