### ISSUE TITLE
Can't use astrotheme if nvim starts with a different theme

### ISSUE THREAD

**Issue by lfilho** [AstroNvim/AstroNvim#2584]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue
- [X] I have run `:Lazy update` and are on the latest version of AstroNvim
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Operating system/version

macOS 14

### Terminal/GUI

iTerm2

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v4.6.4
- Neovim Version: v0.9.5
- OK Using stable Neovim >= 0.9.5
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `rg` is installed: Used for Telescope `live_grep` picker, `<Leader>fw` and `<Leader>fW` by default (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu-go` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

I have installed a handful of other colorschemes but if I start nvim with one of them (not Astro's), astro's ones won't show up in the `:colorscheme` list to be chosen. All built-in themes and the other custom ones I've installed are there, but not astro's.

But if let Astro's be the default/active one and restart nvim, then it works, and i can also choose from my other colorschemes accordingly.

### Steps to Reproduce

See repro.lua below

1. Install a 3rd party colorscheme
2. Make it the default/active one
3. Restart nvim
4. Try selecting Astro's theme and see it not's there as an option

### Expected behavior

So the expectation is there is that upon starting nvim with a non-astro colorscheme, I should still be able to choose Astro's them without having to edit my config file and restaring nvim for that.

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable",
    lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", import = "astronvim.plugins" },

  { "projekt0n/github-nvim-theme" },
  {
    "AstroNvim/astroui",
    opts = {
      colorscheme = "github_dark",
    },
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

**Comment by mehalter** [comment]
By default, AstroTheme is lazy loaded. It will automatically load itself if you run `:colorscheme astrodark` or `:colorscheme astrotheme`. You can customize the lazy loading if you want to change this behavior but it is available if you run `:colorscheme astrodark`

**Comment by lfilho** [comment]
Oh interesting. That's a bit surprising since that's not how other colorschemes work, but good to know.

**Comment by mehalter** [comment]
The core plugins AstroNvim sets up focuses on maximizing lazy loading to improve startup time. Default colorschemes core to neovim don't need to be loaded and stuff in AstroCommunity or plugins you added leaves the lazy loading up to you to decide how much performance you want to squeak out

**Comment by lfilho** [comment]
Yeap, specially with plugins in mind, it makes sense. But for colorschemes i feel it's a bit different because we're removing the discoverability aspect of them. By only lazy loading them, it would mean i'd have to memorize their exact name (and some have some weird, hard-to-memorize names), then everytime i wanted to switch or test a new colorscheme i'd have to open up my astro/nvim config just to fetch their names so i can type `:colorscheme <name>`.

But yeah, tough trade-off for performance.

**Comment by mehalter** [comment]
Yeah makes sense, feel free to disable the lazy loading in your configuration
