### ISSUE TITLE
gdu not detected for windows/powershell

### ISSUE THREAD

**Issue by snkkid99** [AstroNvim/AstroNvim#2585]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue
- [X] I have run `:Lazy update` and are on the latest version of AstroNvim
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Operating system/version

Windows 11 23H2

### Terminal/GUI

PowerShell 7.4.2

### AstroNvim Health

AstroNvim 4.6.5
Nvim 0.9.5

### Describe the bug

Gdu is not detected in :checkhealth

### Steps to Reproduce

Powershell:
winget install gdu
Set-Alias -Name gdu -Value gdu_windows_amd64

nvim:
:checkhealth

### Expected behavior

Use \<leader\>tu in nvim

### Screenshots

:checkhealth

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v4.6.5
- Neovim Version: v0.9.5
- OK Using stable Neovim >= 0.9.5
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `rundll32` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `rg` is installed: Used for Telescope `live_grep` picker, `<Leader>fw` and `<Leader>fW` by default (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
**- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)**
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", import = "astronvim.plugins" },

  -- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by mehalter** [comment]
I just pushed a commit to AstroNvim that should add this missing potential path executable name for windows. The way we detect executables is with the built in `vim.fn.executable` function which looks for things in the `PATH` so it won't include things aliased or not real binaries. THis is a core neovim limitation and out of scope to support here. I did add the official binary name that gets installed with `winget`, `"gdu_windows_amd64.exe"`.

Could you disabling the version pinning in your AstroNvim configuration and run `:Lazy update` to test out the unreleased/unstable version?

**Comment by snkkid99** [comment]
This is a quick answer. Thank you.

but could you help me with "disabling the version pinning in your AstroNvim configuration"
I searched the doc to do it but ....

**Comment by mehalter** [comment]
You can just comment out this line if you are using the AstroNvim template:

https://github.com/AstroNvim/template/blob/main/lua/lazy_setup.lua#L4

**Comment by mehalter** [comment]
We should add this to the docs for sure! Thanks for pointing that out. I'll find a good place for that today 😄

**Comment by snkkid99** [comment]
It work.
\<leader\>tu too
ty

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v4.6.5-dev-1-gcb24728
- Neovim Version: v0.9.5
- OK Using stable Neovim >= 0.9.5
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `rundll32` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `rg` is installed: Used for Telescope `live_grep` picker, `<Leader>fw` and `<Leader>fW` by default (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu_windows_amd64.exe` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

**Comment by mehalter** [comment]
Awesome, thanks! I'll get that new release tagged soon :)

**Comment by mehalter** [comment]
Added details for contributing and testing nightly/unstable AstroNvim here! Thanks again for pointing out that issue in the docs ❤️ 

https://docs.astronvim.com/reference/contributing/
