### ISSUE TITLE
Failed to run `init` for **nvim-treesitter**

### ISSUE THREAD

**Issue by Evangelista-cpp** [AstroNvim/AstroNvim#2590]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue
- [X] I have run `:Lazy update` and are on the latest version of AstroNvim
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Operating system/version

Ubuntu 22.04.4 LTS

### Terminal/GUI

GTerminal

### AstroNvim Health

astronvim: require("astronvim.health").check()
   3   
   4   AstroNvim
   5   - AstroNvim Version: v4.6.7
   6   - Neovim Version: v0.10.0-dev-2501+gdbf6be296
   7   - WARNING Neovim nightly is not officially supported and may have breaking changes
   8   - OK git is installed: Used for core functionality such as updater and plugin management
   9   - OK xdg-open is installed: Used for gx mapping for opening files with system opener (Optional)
  10   - OK rg is installed: Used for Telescope live_grep picker, <Leader>fw and <Leader>fW by default (Optional)
  11   - OK lazygit is installed: Used for mappings to pull up git TUI (Optional)
  12   - OK node is installed: Used for mappings to pull up node REPL (Optional)
  13   - OK gdu is installed: Used for mappings to pull up disk usage analyzer (Optional)
  14   - OK btm is installed: Used for mappings to pull up system monitor (Optional)
  15   - OK python3 is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Failed to load plugin nvim-treesitter on install

### Steps to Reproduce

rm -rf .local/share/nvim/
rm -rf .local/state/nvim/
rm -rf .cache/nvim/
rm -rf ~/.config/nvim
git clone https://github.com/AstroNvim/template.git ~/.config/nvim
nvim

### Expected behavior

Install nvim without erros 

### Screenshots

![image](https://github.com/AstroNvim/AstroNvim/assets/135093794/77d0c72b-5265-455d-a5a5-31a6a30f6fdc)

### Additional Context

![image](https://github.com/AstroNvim/AstroNvim/assets/135093794/ce3cc3ae-071f-40be-b0a2-1d338ad1bf01)

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", import = "astronvim.plugins" },

  -- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by mehalter** [comment]
This would be unrelated to AstroNvim and looks to be related to lazy.nvim. Although from the looks at it, it could be a networking issue.

Also worth noting that unstable neovim is not supported officially as well
