### ISSUE TITLE
Empty lines trigger popup with logs

### ISSUE THREAD

**Issue by ASoldo** [AstroNvim/AstroNvim#2594]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue
- [X] I have run `:Lazy update` and are on the latest version of AstroNvim
- [ ] I can replicate the bug with the minimal `repro.lua` provided below

### Operating system/version

Arch Linux x86_64

### Terminal/GUI

gnome-terminal

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: v4.7.0
- Neovim Version: v0.9.5
- OK Using stable Neovim >= 0.9.5
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `rg` is installed: Used for Telescope `live_grep` picker, `<Leader>fw` and `<Leader>fW` by default (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

When I open typescript project and switch between 2 files and i land caret on empty line i get this popup with the following content:
![image](https://github.com/AstroNvim/AstroNvim/assets/1175537/af899ce5-bd3a-45dd-9578-879b22b75cac)

I need to press escape and move from that line in order to stop this from popping. 

### Steps to Reproduce

1. Open typescript project
2. Open first typescript file
3. Open second typescript file and go to empty line in that file.

### Expected behavior

Not to have this popup triggering on empty line.

### Screenshots

![image](https://github.com/AstroNvim/AstroNvim/assets/1175537/af899ce5-bd3a-45dd-9578-879b22b75cac)

### Additional Context

This has never happened before so I'm not sure why this happens now.

**Comment by mehalter** [comment]
This is unrelated to AstroNvim and is coming from the language server. It should be diagnosed and reported upstream as we don't have any responsibility over `tsserver`

**Comment by mehalter** [comment]
Also worth noting I cannot replicate this on a base installation of AstroNvim with `tsserver` installed

**Comment by ASoldo** [comment]
No problem, I was not sure what it was so just wanted to check. Tnx!
