### ISSUE TITLE
large file makes it unusable

### ISSUE THREAD

**Issue by nbittich** [AstroNvim/AstroNvim#2613]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue
- [X] I have run `:Lazy update` and are on the latest version of AstroNvim
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Operating system/version

pop os

### Terminal/GUI

default terminal

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: v4.8.1
- Neovim Version: v0.10.0
- WARNING Neovim nightly is not officially supported and may have breaking changes
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `rg` is installed: Used for Telescope `live_grep` picker, `<Leader>fw` and `<Leader>fW` by default (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

When opening a minified javascript file (https://unpkg.com/html5-qrcode@2.3.8/html5-qrcode.min.js) , nvim becomes unusable (see video below). I tried to add the following in my astrocore.lua, the problem still remains. Note that if I run neovim without any plugins, the problem doesn't occur. I also reduced the large_file option to 256kb (which is smaller than the file I try to open).

https://github.com/AstroNvim/AstroNvim/assets/3816305/ee134451-bf51-482c-8cfb-f4f44c4262c0

```lua
   autocmds = {
      BigFileDisable = {
        {
          event = "User",
          pattern = { "AstroLargeBuf" },
          desc = "Disable TS & LSP for large buf",
          group = "BigFileDisable",
          callback = function()
            vim.cmd "TSBufDisable autotag"
            vim.cmd "TSBufDisable highlight"
            vim.cmd "TSBufDisable incremental_selection"
            vim.cmd "TSBufDisable indent"
            vim.cmd "TSBufDisable playground"
            vim.cmd "TSBufDisable query_linter"
            vim.cmd "TSBufDisable rainbow"
            vim.cmd "TSBufDisable refactor.highlight_definitions"
            vim.cmd "TSBufDisable refactor.navigation"
            vim.cmd "TSBufDisable refactor.smart_rename"
            vim.cmd "TSBufDisable refactor.highlight_current_scope"
            vim.cmd "TSBufDisable textobjects.swap"
            vim.cmd "TSBufDisable textobjects.move"
            vim.cmd "TSBufDisable textobjects.lsp_interop"
            vim.cmd "TSBufDisable textobjects.select"
            vim.cmd "LspStop"
          end,
        },
      },
    },
```

### Steps to Reproduce

- open a large file

### Expected behavior

I should be able to navigate smoothly into the file. Plugins should be disabled 

### Repro

```Lua
https://github.com/nbittich/astronvim4
```

**Comment by mehalter** [comment]
This is a limitation of neovim and long lines. If you unminimize the file (making it even larger) it will perform better.

Also the built in large file detection is already disabling all treesitter modules out of the box so it makes sense your auto command didn't change anything.
