### ISSUE TITLE
Video course on Youtube for people who are interested in mastering AstroNvim or Neovim made by AstroNvim team

### ISSUE THREAD

**Issue by duytrung** [AstroNvim/AstroNvim#2630]
### Is your feature related to a problem?

No, it's not.

### Describe the new feature

I think that AstroNvim should have a Youtube channel that teach people to use AstroNvim, just like the online course for people to learn to use Microsoft Word, Excel...etc...
I found many people interested in mastering Neovim/Vim. I'm still learn some of its advanced features and eager to learn new skills.

**Comment by mehalter** [comment]
I agree! I think that would be awesome to have! Now we just need someone to want to make videos! If you or anyone you know wants to give it a try let us know!
