### ISSUE TITLE
How to set the format style of clangd to WebKit in astrolsp.lua

### ISSUE THREAD

**Issue by jiale-gdyd** [AstroNvim/AstroNvim#2634]
### Describe the new feature

How to set the format style of clangd to WebKit in astrolsp.lua

**Comment by mehalter** [comment]
This is not something you would configure in AstroLSP I don't think. `clangd` simply uses `clang-format` under the hood so you just need to configure that in your project. Here is a link to documentation on configuring `clang-format` which is probably a good place for you to start: https://clang.llvm.org/docs/ClangFormatStyleOptions.html

Looks like it's configured with a `.clang-format` file in the root of the project. Here is the one in the WebKit project which is probably a good reference: https://github.com/WebKit/WebKit/blob/main/.clang-format

If you have any more questions, the AstroNvim Discord is a good place to ask as there are many users who can answer the questions with more experiences than I do.
