### ISSUE TITLE
Color scheme is different on a second startup after clean install on macOS

### ISSUE THREAD

**Issue by mekedron** [AstroNvim/AstroNvim#2639]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue
- [X] I have run `:Lazy update` and are on the latest version of AstroNvim
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Operating system/version

macOS Sonoma 14.3.1

### Terminal/GUI

alacritty

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v4.12.1
- Neovim Version: v0.10.0
- WARNING Neovim nightly is not officially supported and may have breaking changes
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `rg` is installed: Used for Telescope `live_grep` picker, `<Leader>fw` and `<Leader>fW` by default (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu-go/gdu_windows_amd64.exe` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

After I clear all nvim directories:
```
$ rm -rf ~/.config/nvim
$ rm -rf ~/.local/share/nvim
$ rm -rf ~/.local/state/nvim
$ rm -rf ~/.cache/nvim
```
And follow the rest installation steps described in [README.md file](https://github.com/AstroNvim/AstroNvim?tab=readme-ov-file#%EF%B8%8F-installation), nvim installs astronvim and uses **astrodark** theme by default, and on the **next launch** it switches to **astrolight**

### Steps to Reproduce

1. Remove nvim directories
2. Clone template repo
3. Launch nvim
4. Wait till all the plugins are installed
5. Ensure color scheme is astrodark
6. Exit nvim
7. Launch it again
8. Color scheme is astrolight now

### Expected behavior

On the second startup the colorscheme should be as after initial install

### Screenshots

https://github.com/AstroNvim/AstroNvim/assets/2446589/58080782-9ab0-4ddd-9bd3-d1168452439c

### Additional Context

I'm using macOS light color scheme by the way

### Repro

```Lua
-- This file simply bootstraps the installation of Lazy.nvim and then calls other files for execution
-- This file doesn't necessarily need to be touched, BE CAUTIOUS editing this file and proceed at your own risk.
local lazypath = vim.env.LAZY or vim.fn.stdpath "data" .. "/lazy/lazy.nvim"
if not (vim.env.LAZY or (vim.uv or vim.loop).fs_stat(lazypath)) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(lazypath)

-- validate that lazy is available
if not pcall(require, "lazy") then
  -- stylua: ignore
  vim.api.nvim_echo({ { ("Unable to load lazy from: %s\n"):format(lazypath), "ErrorMsg" }, { "Press any key to exit...", "MoreMsg" } }, true, {})
  vim.fn.getchar()
  vim.cmd.quit()
end

require "lazy_setup"
require "polish"
```

**Comment by mehalter** [comment]
run `:set backgroun?` My guess is it's set to `light`. The colorscheme on the second startup is correct.

**Comment by mehalter** [comment]
I suppose it not being light on the startup is a bug so I made it so the initial installation respects the `light` background. So it should be the same on first installation and second startup and both times it will be `light`

**Comment by mekedron** [comment]
@mehalter true, `:set background` is `light`. And when I switch it to `dark` then color scheme is set to the dark one, so it seems it works fine

Yeah and because color scheme was not light on the startup I thought something goes wrong here and my installation does not work properly. So it was just a bit unclear on a second launch why it's different from the first initial one

Thanks for quick reply!
Have a good day
