### ISSUE TITLE
feature: set which key to color, make it more fancy.

### ISSUE THREAD

**Issue by chaozwn** [AstroNvim/AstroNvim#2660]
### Is your feature related to a problem?

<img width="875" alt="image" src="https://github.com/user-attachments/assets/4840d563-8f8b-4bc3-ac89-66db908a140c">

### Describe the new feature

set which key to color.

**Comment by mehalter** [comment]
This is not a look we like. It is overwhelming and cluttered. Feel free to implement in your own configuration!
