### ISSUE TITLE
Cannot escape into normal mode on dressing/nui inputs

### ISSUE THREAD

**Issue by Raekh** [AstroNvim/AstroNvim#2662]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue
- [X] I have run `:Lazy update` and are on the latest version of AstroNvim
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Operating system/version

Ubuntu 24.04

### Terminal/GUI

kitty

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v4.20.1
- Neovim Version: v0.10.0
- WARNING Neovim nightly is not officially supported and may have breaking changes
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `rg` is installed: Used for Telescope `live_grep` picker, `<Leader>fw` and `<Leader>fW` by default (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu/gdu_windows_amd64.exe` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

==============================================================================
dap: require("dap.health").check()

dap: Adapters ~

dap: Sessions ~
- OK No active sessions

==============================================================================
diffview: require("diffview.health").check()

Checking plugin dependencies ~
- OK nvim-web-devicons installed.

Checking VCS tools ~
- The plugin requires at least one of the supported VCS tools to be valid.
- OK Git found.
- OK Git is up-to-date. (2.43.0)
- WARNING Configured `hg_cmd` is not executable: 'hg'

==============================================================================
lazy: require("lazy.health").check()

lazy.nvim ~
- {lazy.nvim} version `11.13.1`
- OK {git} `version 2.43.0`
- OK no existing packages found by other package managers
- OK packer_compiled.lua not found

luarocks ~
- checking `luarocks` installation
- OK no plugins require `luarocks`, so you can ignore any warnings below
- OK {luarocks} `/usr/bin/luarocks 3.8.0`
- OK {lua5.1} `Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio`

==============================================================================
luarocks-nvim: require("luarocks-nvim.health").check()

luarocks.nvim ~
- luarocks system is not prepared
- OK git is installed
- OK lua is installed
- OK make is installed

==============================================================================
luasnip: require("luasnip.health").check()

luasnip ~
- WARNING             For Variable/Placeholder-transformations, luasnip requires
              the jsregexp library. See `:help |luasnip-lsp-snippets-transformations`| for advice
          

==============================================================================
mason: require("mason.health").check()

mason.nvim ~
- OK mason.nvim version v1.10.0
- OK PATH: prepend
- OK Providers: 
    mason.providers.registry-api
    mason.providers.client
- OK neovim version >= 0.7.0

mason.nvim [Registries] ~
- OK Registry `github.com/mason-org/mason-registry version: 2024-07-19-exact-phlox` is installed.

mason.nvim [Core utils] ~
- OK unzip: `UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.`
- OK wget: `GNU Wget 1.21.4 built on linux-gnu.`
- OK curl: `curl 8.5.0 (x86_64-pc-linux-gnu) libcurl/8.5.0 OpenSSL/3.0.13 zlib/1.3 brotli/1.1.0 zstd/1.5.5 libidn2/2.3.7 libpsl/0.21.2 (+libidn2/2.3.7) libssh/0.10.6/openssl/zlib nghttp2/1.59.0 librtmp/2.3 OpenLDAP/2.6.7`
- OK gzip: `gzip 1.12`
- OK tar: `tar (GNU tar) 1.35`
- OK bash: `GNU bash, version 5.2.21(1)-release (x86_64-pc-linux-gnu)`
- OK sh: `Ok`

mason.nvim [Languages] ~
- OK Go: `go version go1.22.2 linux/amd64`
- WARNING Composer: not available
  - ADVICE:
    - spawn: composer failed with exit code - and signal -. composer is not executable
- WARNING PHP: not available
  - ADVICE:
    - spawn: php failed with exit code - and signal -. php is not executable
- OK Ruby: `ruby 3.2.3 (2024-01-18 revision 52bb2ac0a6) [x86_64-linux-gnu]`
- OK node: `v20.12.0`
- OK luarocks: `/usr/bin/luarocks 3.8.0`
- OK cargo: `cargo 1.78.0 (54d8815d0 2024-03-26)`
- WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. julia is not executable
- OK python: `Python 3.12.3`
- OK java: `openjdk version "21.0.3" 2024-04-16`
- OK RubyGem: `3.4.20`
- OK javac: `javac 21.0.3`
- OK npm: `10.5.0`
- OK pip: `pip 24.0 from /usr/lib/python3/dist-packages/pip (python 3.12)`
- OK python venv: `Ok`

mason.nvim [GitHub] ~
- OK GitHub API rate limit. Used: 0. Remaining: 5000. Limit: 5000. Reset: Fri 19 Jul 2024 04:39:10 PM CEST.

==============================================================================
neoconf: require("neoconf.health").check()

neoconf.nvim ~
- WARNING **jsonc** parser for tree-sitter is not installed. Jsonc highlighting might be broken
- OK **neodev.nvim** is installed
- OK **lspconfig** is installed
- OK **lspconfig jsonls** is installed
- OK **lspconfig lua_ls** is installed

==============================================================================
neorg: require("neorg.health").check()

Neorg Configuration ~
- Checking `load` table...
- OK Module declaration for `core.export.markdown` is well-formed
- OK Module declaration for `core.export` is well-formed
- OK Module declaration for `core.completion` is well-formed
- OK Module declaration for `core.dirman` is well-formed
- OK Module declaration for `core.summary` is well-formed
- OK Module declaration for `core.concealer` is well-formed
- OK Module declaration for `core.defaults` is well-formed
- OK Module declaration for `core.autocommands` is well-formed
- OK Module declaration for `core.integrations.telescope` is well-formed
- OK Module declaration for `core.integrations.treesitter` is well-formed
- OK Module declaration for `core.ui` is well-formed
- OK Module declaration for `core.syntax` is well-formed
- OK Module declaration for `core.tempus` is well-formed
- OK Module declaration for `core.neorgcmd` is well-formed
- OK Module declaration for `core.ui.calendar` is well-formed
- OK Module declaration for `core.text-objects` is well-formed
- OK Module declaration for `core.presenter` is well-formed
- OK Module declaration for `core.latex.renderer` is well-formed
- OK Module declaration for `core.highlights` is well-formed
- OK Default configuration for logger provided, Neorg will not output debug info.

Neorg Dependencies ~
- OK `luarocks` is installed.

Neorg Keybinds ~
- Neorg is configured to use keybind preset `neorg`
- WARNING Key `<` conflicts with a key bound by the user. Neorg will not bind this key.
  - ADVICE:
    - consider mapping `<Plug>(neorg.promo.demote.range)` to a different key than the one bound by Neorg.
- WARNING Key `<,` conflicts with a key bound by the user. Neorg will not bind this key.
  - ADVICE:
    - consider mapping `<Plug>(neorg.promo.demote)` to a different key than the one bound by Neorg.
- WARNING Key `<<` conflicts with a key bound by the user. Neorg will not bind this key.
  - ADVICE:
    - consider mapping `<Plug>(neorg.promo.demote.nested)` to a different key than the one bound by Neorg.
- WARNING Key `<C-d>` conflicts with a key bound by the user. Neorg will not bind this key.
  - ADVICE:
    - consider mapping `<Plug>(neorg.promo.demote)` to a different key than the one bound by Neorg.
- WARNING Key `<LocalLeader>id` conflicts with a key bound by the user. Neorg will not bind this key.
  - ADVICE:
    - consider mapping `<Plug>(neorg.tempus.insert-date)` to a different key than the one bound by Neorg.
- WARNING Key `<LocalLeader>li` conflicts with a key bound by the user. Neorg will not bind this key.
  - ADVICE:
    - consider mapping `<Plug>(neorg.pivot.list.invert)` to a different key than the one bound by Neorg.
- WARNING Key `<LocalLeader>lt` conflicts with a key bound by the user. Neorg will not bind this key.
  - ADVICE:
    - consider mapping `<Plug>(neorg.pivot.list.toggle)` to a different key than the one bound by Neorg.
- WARNING Key `<LocalLeader>nn` conflicts with a key bound by the user. Neorg will not bind this key.
  - ADVICE:
    - consider mapping `<Plug>(neorg.dirman.new-note)` to a different key than the one bound by Neorg.
- WARNING Key `<LocalLeader>ta` conflicts with a key bound by the user. Neorg will not bind this key.
  - ADVICE:
    - consider mapping `<Plug>(neorg.qol.todo-items.todo.task-ambiguous)` to a different key than the one bound by Neorg.
- WARNING Key `<LocalLeader>tc` conflicts with a key bound by the user. Neorg will not bind this key.
  - ADVICE:
    - consider mapping `<Plug>(neorg.qol.todo-items.todo.task-cancelled)` to a different key than the one bound by Neorg.
- WARNING Key `<LocalLeader>td` conflicts with a key bound by the user. Neorg will not bind this key.
  - ADVICE:
    - consider mapping `<Plug>(neorg.qol.todo-items.todo.task-done)` to a different key than the one bound by Neorg.
- WARNING Key `<LocalLeader>th` conflicts with a key bound by the user. Neorg will not bind this key.
  - ADVICE:
    - consider mapping `<Plug>(neorg.qol.todo-items.todo.task-on-hold)` to a different key than the one bound by Neorg.
- WARNING Key `<LocalLeader>ti` conflicts with a key bound by the user. Neorg will not bind this key.
  - ADVICE:
    - consider mapping `<Plug>(neorg.qol.todo-items.todo.task-important)` to a different key than the one bound by Neorg.
- WARNING Key `<LocalLeader>tp` conflicts with a key bound by the user. Neorg will not bind this key.
  - ADVICE:
    - consider mapping `<Plug>(neorg.qol.todo-items.todo.task-pending)` to a different key than the one bound by Neorg.
- WARNING Key `<LocalLeader>tr` conflicts with a key bound by the user. Neorg will not bind this key.
  - ADVICE:
    - consider mapping `<Plug>(neorg.qol.todo-items.todo.task-recurring)` to a different key than the one bound by Neorg.
- WARNING Key `<LocalLeader>tu` conflicts with a key bound by the user. Neorg will not bind this key.
  - ADVICE:
    - consider mapping `<Plug>(neorg.qol.todo-items.todo.task-undone)` to a different key than the one bound by Neorg.
- WARNING Key `>` conflicts with a key bound by the user. Neorg will not bind this key.
  - ADVICE:
    - consider mapping `<Plug>(neorg.promo.promote.range)` to a different key than the one bound by Neorg.
- WARNING Key `>.` conflicts with a key bound by the user. Neorg will not bind this key.
  - ADVICE:
    - consider mapping `<Plug>(neorg.promo.promote)` to a different key than the one bound by Neorg.
- WARNING Key `>>` conflicts with a key bound by the user. Neorg will not bind this key.
  - ADVICE:
    - consider mapping `<Plug>(neorg.promo.promote.nested)` to a different key than the one bound by Neorg.

==============================================================================
null-ls: require("null-ls.health").check()

- OK selene: the command "selene" is executable.
- OK stylua: the command "stylua" is executable.

==============================================================================
nvim: require("nvim.health").check()

Configuration ~
- OK no issues found

Runtime ~
- OK $VIMRUNTIME: /home/raekh/.local/share/bob/v0.10.0/nvim-linux64/share/nvim/runtime

Performance ~
- OK Build type: Release

Remote Plugins ~
- OK Up to date

terminal ~
- key_backspace (kbs) terminfo entry: `key_backspace=\177`
- key_dc (kdch1) terminfo entry: `key_dc=\E[3~`
- $COLORTERM="truecolor"

External Tools ~
- OK ripgrep 14.1.0 (/usr/bin/rg)

==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v20.12.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 13.2.0-23ubuntu4) 13.2.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.8.0-38-generic",
  sysname = "Linux",
  version = "#38-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun  7 15:25:01 UTC 2024"
} ~

Parser/Features         H L F I J
  - angular             ✓ ✓ ✓ ✓ ✓
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - dockerfile          ✓ . . . ✓
  - gitignore           ✓ . . . ✓
  - graphql             ✓ . . ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - http                ✓ . . . ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - norg                ✓ . ✓ . ✓
  - norg_meta           ✓ . . ✓ .
  - prisma              ✓ . ✓ . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - sql                 ✓ . . ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

==============================================================================
provider.clipboard: require("provider.clipboard.health").check()

Clipboard (optional) ~
- OK Clipboard tool found: wl-copy

==============================================================================
provider.node: require("provider.node.health").check()

Node.js provider (optional) ~
- Node.js: v20.12.0
  
- WARNING Missing "neovim" npm (or yarn, pnpm) package.
  - ADVICE:
    - Run in shell: npm install -g neovim
    - Run in shell (if you use yarn): yarn global add neovim
    - Run in shell (if you use pnpm): pnpm install -g neovim
    - You may disable this provider (and warning) by adding `let g:loaded_node_provider = 0` to your init.vim

==============================================================================
provider.perl: require("provider.perl.health").check()

Perl provider (optional) ~
- WARNING "Neovim::Ext" cpan module is not installed
  - ADVICE:
    - See :help |provider-perl| for more information.
    - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim
- WARNING No usable perl executable found

==============================================================================
provider.python: require("provider.python.health").check()

Python 3 provider (optional) ~
- WARNING No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
- WARNING Could not load Python :
  /usr/bin/python3 does not have the "neovim" module.
  /usr/bin/python3.12 does not have the "neovim" module.
  python3.11 not found in search path or not executable.
  python3.10 not found in search path or not executable.
  python3.9 not found in search path or not executable.
  python3.8 not found in search path or not executable.
  python3.7 not found in search path or not executable.
  /usr/bin/python does not have the "neovim" module.
  - ADVICE:
    - See :help |provider-python| for more information.
    - You may disable this provider (and warning) by adding `let g:loaded_python3_provider = 0` to your init.vim
- Executable: Not found

Python virtualenv ~
- OK no $VIRTUAL_ENV

==============================================================================
provider.ruby: require("provider.ruby.health").check()

Ruby provider (optional) ~
- Ruby: ruby 3.2.3 (2024-01-18 revision 52bb2ac0a6) [x86_64-linux-gnu]
- WARNING `neovim-ruby-host` not found.
  - ADVICE:
    - Run `gem install neovim` to ensure the neovim RubyGem is installed.
    - Run `gem environment` to ensure the gem bin directory is in $PATH.
    - If you are using rvm/rbenv/chruby, try "rehashing".
    - See :help |g:ruby_host_prog| for non-standard gem installations.
    - You may disable this provider (and warning) by adding `let g:loaded_ruby_provider = 0` to your init.vim

==============================================================================
render-markdown: require("render-markdown.health").check()

markdown.nvim [neovim version] ~
- OK Version >= 0.10

markdown.nvim [configuration] ~
- OK valid

markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown_inline: parser installed
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }
- OK highlights enabled

markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 14.1.0
- WARNING fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

===== Installed extensions ===== ~

Telescope Extension: `aerial` ~
- No healthcheck provided

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured

Telescope Extension: `neorg` ~
- No healthcheck provided

Telescope Extension: `notify` ~
- No healthcheck provided

==============================================================================
vim.lsp: require("vim.lsp.health").check()

- LSP log level : WARN
- Log path: /home/raekh/.local/state/nvim/lsp.log
- Log size: 2207 KB

vim.lsp: Active Clients ~
- No active clients

vim.lsp: File watcher ~
- file watching "(workspace/didChangeWatchedFiles)" disabled on all clients

==============================================================================
vim.treesitter: require("vim.treesitter.health").check()

- Nvim runtime ABI version: 14
- OK Parser: angular              ABI: 14, path: /home/raekh/.local/share/nvim/lazy/nvim-treesitter/parser/angular.so
- OK Parser: bash                 ABI: 14, path: /home/raekh/.local/share/nvim/lazy/nvim-treesitter/parser/bash.so
- OK Parser: css                  ABI: 14, path: /home/raekh/.local/share/nvim/lazy/nvim-treesitter/parser/css.so
- OK Parser: dockerfile           ABI: 14, path: /home/raekh/.local/share/nvim/lazy/nvim-treesitter/parser/dockerfile.so
- OK Parser: gitignore            ABI: 13, path: /home/raekh/.local/share/nvim/lazy/nvim-treesitter/parser/gitignore.so
- OK Parser: graphql              ABI: 13, path: /home/raekh/.local/share/nvim/lazy/nvim-treesitter/parser/graphql.so
- OK Parser: html                 ABI: 14, path: /home/raekh/.local/share/nvim/lazy/nvim-treesitter/parser/html.so
- OK Parser: http                 ABI: 14, path: /home/raekh/.local/share/nvim/lazy/nvim-treesitter/parser/http.so
- OK Parser: javascript           ABI: 14, path: /home/raekh/.local/share/nvim/lazy/nvim-treesitter/parser/javascript.so
- OK Parser: json                 ABI: 14, path: /home/raekh/.local/share/nvim/lazy/nvim-treesitter/parser/json.so
- OK Parser: lua                  ABI: 14, path: /home/raekh/.local/share/nvim/lazy/nvim-treesitter/parser/lua.so
- OK Parser: markdown             ABI: 14, path: /home/raekh/.local/share/nvim/lazy/nvim-treesitter/parser/markdown.so
- OK Parser: markdown_inline      ABI: 14, path: /home/raekh/.local/share/nvim/lazy/nvim-treesitter/parser/markdown_inline.so
- OK Parser: norg                 ABI: 14, path: /home/raekh/.local/share/nvim/lazy/nvim-treesitter/parser/norg.so
- OK Parser: norg_meta            ABI: 14, path: /home/raekh/.local/share/nvim/lazy/nvim-treesitter/parser/norg_meta.so
- OK Parser: prisma               ABI: 13, path: /home/raekh/.local/share/nvim/lazy/nvim-treesitter/parser/prisma.so
- OK Parser: query                ABI: 14, path: /home/raekh/.local/share/nvim/lazy/nvim-treesitter/parser/query.so
- OK Parser: sql                  ABI: 14, path: /home/raekh/.local/share/nvim/lazy/nvim-treesitter/parser/sql.so
- OK Parser: tsx                  ABI: 14, path: /home/raekh/.local/share/nvim/lazy/nvim-treesitter/parser/tsx.so
- OK Parser: typescript           ABI: 14, path: /home/raekh/.local/share/nvim/lazy/nvim-treesitter/parser/typescript.so
- OK Parser: vim                  ABI: 14, path: /home/raekh/.local/share/nvim/lazy/nvim-treesitter/parser/vim.so
- OK Parser: vimdoc               ABI: 14, path: /home/raekh/.local/share/nvim/lazy/nvim-treesitter/parser/vimdoc.so
- OK Parser: yaml                 ABI: 14, path: /home/raekh/.local/share/nvim/lazy/nvim-treesitter/parser/yaml.so
- OK Parser: bash                 ABI: 14, path: /home/raekh/.local/share/bob/v0.10.0/nvim-linux64/lib/nvim/parser/bash.so
- OK Parser: c                    ABI: 14, path: /home/raekh/.local/share/bob/v0.10.0/nvim-linux64/lib/nvim/parser/c.so
- OK Parser: lua                  ABI: 14, path: /home/raekh/.local/share/bob/v0.10.0/nvim-linux64/lib/nvim/parser/lua.so
- OK Parser: markdown             ABI: 14, path: /home/raekh/.local/share/bob/v0.10.0/nvim-linux64/lib/nvim/parser/markdown.so
- OK Parser: markdown_inline      ABI: 14, path: /home/raekh/.local/share/bob/v0.10.0/nvim-linux64/lib/nvim/parser/markdown_inline.so
- OK Parser: python               ABI: 14, path: /home/raekh/.local/share/bob/v0.10.0/nvim-linux64/lib/nvim/parser/python.so
- OK Parser: query                ABI: 14, path: /home/raekh/.local/share/bob/v0.10.0/nvim-linux64/lib/nvim/parser/query.so
- OK Parser: vim                  ABI: 14, path: /home/raekh/.local/share/bob/v0.10.0/nvim-linux64/lib/nvim/parser/vim.so

==============================================================================
which-key: require("which-key.health").check()

- OK Most of these checks are for informational purposes only.
  WARNINGS should be treated as a warning, and don't necessarily indicate a problem with your config.
  Please |DON't| report these warnings as an issue.

Checking your config ~
- OK |mini.icons| is installed
- OK |nvim-web-devicons| is installed

Checking for issues with your mappings ~
- OK No issues reported

checking for overlapping keymaps ~
- WARNING In mode `n`, <yS> overlaps with <ySS>:
  - <yS>: Add a surrounding pair around a motion, on new lines (normal mode)
  - <ySS>: Add a surrounding pair around the current line, on new lines (normal mode)
- WARNING In mode `n`, <ys> overlaps with <yss>:
  - <ys>: Add a surrounding pair around a motion (normal mode)
  - <yss>: Add a surrounding pair around the current line (normal mode)
- WARNING In mode `n`, <gc> overlaps with <gcA>, <gcc>, <gcO>, <gco>:
  - <gc>: Comment toggle linewise
  - <gcA>: Comment insert end of line
  - <gcc>: Comment toggle current line
  - <gcO>: Comment insert above
  - <gco>: Comment insert below
- WARNING In mode `n`, <gb> overlaps with <gbc>:
  - <gb>: Comment toggle blockwise
  - <gbc>: Comment toggle current block
- OK Overlapping keymaps are only reported for informational purposes.
  This doesn't necessarily mean there is a problem with your config.

Checking for duplicate mappings ~
- OK No duplicate mappings found

### Describe the bug

Since one of the latest updates, it is no longer possible to escape from inputs, whether the nui ones from neo-tree nor the Dressing ones from the regular buffers. Dressing  even removed a config option to be insert only.
Before, it was possible to escape to normal mode with `jk` or `jj`, but it's not the case anymore.

### Steps to Reproduce

1. Either go to a neo-tree entry or a buffer symbol
2. Perform an action that uses the `vim.ui.input` api
3. Try to escape to normal mode using `jj` or `jk`
4. The input closes

### Expected behavior

The input should not close and should go into normal mode

### Repro

```Lua
-- default AstroNvim installation
```

**Comment by mehalter** [comment]
Here are the docs for configuring dressing: https://github.com/stevearc/dressing.nvim/tree/v2.2.2?tab=readme-ov-file#configuration

Once Aerial v3 is released soon that default will change

**Comment by Raekh** [comment]
I suspect you barely read the description.
Both dressing AND nui inputs started behaving this way. This would indicate something changed here and not inside those plugins.

**Comment by mehalter** [comment]
Ok, sorry. I should have explained more.

So `vim.ui.input` is provided by [dressing.nvim](https://github.com/stevearc/dressing.nvim/tree/v2.2.2?tab=readme-ov-file#configuration). By default there is an option called `insert_only` set to `true`. So if you set that to false in your user configuration you will be able to go into normal mode. Something like this:

```lua
return {
  "stevearc/dressing.nvim",
  opts = {
    input = { insert_only = false },
  },
}
```

Neo-tree uses [nui.nvim](https://github.com/MunifTanjim/nui.nvim) for showing things like input boxes and confirmation boxes. It is a very general purpose library for building UI components. By default they have escape close the prompt which therefore removes the ability to go into normal mode. You can reconfigure this by adding an event handler (code found from searching through the neo-tree issues https://github.com/nvim-neo-tree/neo-tree.nvim/issues/1396):

```lua
return {
  "nvim-neo-tree/neo-tree.nvim",
  opts = function(_, opts)
    opts.event_handlers = opts.event_handlers or {}
    table.insert(opts.event_handlers, {
      event = "neo_tree_popup_input_ready",
      ---@param args { bufnr: integer, winid: integer }
      handler = function(args)
        -- map <esc> to enter normal mode (by default closes prompt)
        -- don't forget `opts.buffer` to specify the buffer of the popup.
        vim.keymap.set("i", "<esc>", vim.cmd.stopinsert, { noremap = true, buffer = args.bufnr })
      end,
    })
  end,
}
```

These defaults have always been used and nothing in AstroNvim has changed the default behavior of these plugins at all. Hopefully this helps!

**Comment by Raekh** [comment]
Both of these snippets when added to the config perfectly solved the problems for both libraries.
That was blazingly fast ! Thank you very much.
