### ISSUE TITLE
Add support for open multiple terminals side-by-side for toggleterm.nvim

### ISSUE THREAD

**Issue by fky2015** [AstroNvim/AstroNvim#2667]
### Is your feature related to a problem?

First of all, thanks for your continuous hard work on this wonderful projects!

toggleterm.nvim has a nice feature that can allow us to type `<Number><C-\>` to open multiple terminal side-by-side, which is very useful when we want to run multiple commands or compare some outputs.

### Describe the new feature

It's a default feature yield by toggleterm.nvim:

https://github.com/akinsho/toggleterm.nvim?tab=readme-ov-file#open-multiple-terminals-side-by-side

Maybe Astronvim can further make `<|>` and `</>` to bind with this feature?

**Comment by mehalter** [comment]
I took a look and it doesn't seem like that's something we need to add support for as it's already supported by toggleterm. You just need to have the default direction configured to be one that is supported. So adding something like this:

```lua
return {
  "akinsho/toggleterm.nvim",
  opts = {
    direction = "horizontal",
  },
}
```

and then you can use the toggle term bindings `<F7>` (or `<C-'>` if your terminal supports the binding) as described with `<F7>` and `2<F7>`
