### ISSUE TITLE
#!/usr/bin/env pypy3 is not detected as filetype python

### ISSUE THREAD

**Issue by dstromberg** [AstroNvim/AstroNvim#2674]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue
- [X] I have run `:Lazy update` and are on the latest version of AstroNvim
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Operating system/version

Debian GNU/Linux 12 (bookworm)

### Terminal/GUI

wezterm

### AstroNvim Health

   1   ──────────────────────────────────────────────────────────────────────────────
   2   astronvim: require("astronvim.health").check()
   3
   4   AstroNvim
   5   - AstroNvim Version: v4.23.1
   6   - Neovim Version: v0.10.0
   7   - WARNING Neovim nightly is not officially supported and may have breaking changes
   8   - OK git is installed: Used for core functionality such as updater and plugin management
   9   - OK xdg-open is installed: Used for gx mapping for opening files with system opener (Optional)
  10   - OK rg is installed: Used for Telescope live_grep picker, <Leader>fw and <Leader>fW by default (Optional)
  11   - OK lazygit is installed: Used for mappings to pull up git TUI (Optional)
  12   - OK node is installed: Used for mappings to pull up node REPL (Optional)
  13   - WARNING gdu/gdu_windows_amd64.exe is not installed: Used for mappings to pull up disk usage analyzer (Optional)
  14   - WARNING btm is not installed: Used for mappings to pull up system monitor (Optional)
  15   - OK python3 is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

#!/usr/bin/env pypy3 is detected as filetype "conf", not "python".

### Steps to Reproduce

Create this small test script named ./t, and edit it:
#!/usr/bin/env pypy3

print("hi")

In the lower left corner, you see filetype "conf", not "python".

### Expected behavior

 It should be detected as filetype python.

### Repro

```Lua
-- This file simply bootstraps the installation of Lazy.nvim and then calls other files for execution
-- This file doesn't necessarily need to be touched, BE CAUTIOUS editing this file and proceed at your own risk.
local lazypath = vim.env.LAZY or vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.env.LAZY or (vim.uv or vim.loop).fs_stat(lazypath)) then
        -- stylua: ignore
        vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable",
                lazypath })
end
vim.opt.rtp:prepend(lazypath)
--
-- validate that lazy is available
if not pcall(require, "lazy") then
        -- stylua: ignore
        vim.api.nvim_echo(
                { { ("Unable to load lazy from: %s\n"):format(lazypath), "ErrorMsg" }, { "Press any key to exit...", "MoreMsg" } },
                true, {})
        vim.fn.getchar()
        vim.cmd.quit()
end
--
require("lazy_setup")
require("polish")

-- Initialize AstroNvim configuration
-- local astro_utils = require("astronvim.utils")

-- Tell Neovim that pypy is python
vim.api.nvim_create_autocmd({ "BufEnter" }, {
        pattern = "*",
        callback = function()
                if vim.fn.getline(1):match("^#!.*pypy.*$") then
                        vim.bo.filetype = "python"
                end
        end,
})
```

**Comment by mehalter** [comment]
This is the same in `nvim --clean`. AstroNvim doesn't provide anything that changes the filetype detection. Sorry!

**Comment by mehalter** [comment]
I also noticed that you are trying to do an autocommand with `BufEnter`. This doesn't really integrate with the build in filetype detection. Here is the Lua you probably want to use:

```lua
vim.filetype.add {
  pattern = {
    [".*"] = function(_, bufnr)
      local first_line = vim.api.nvim_buf_get_lines(bufnr, 0, 1, false)[1] or ""
      if first_line:match "^#!.*pypy.*$" then return "python" end
      -- if nothing is returned, it uses the default filetype
    end,
  },
}
```

This could go in your `polish.lua`
