### ISSUE TITLE
Latest updates causing extremely slow UI.

### ISSUE THREAD

**Issue by kevinkirkup** [AstroNvim/AstroNvim#2676]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue
- [X] I have run `:Lazy update` and are on the latest version of AstroNvim
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Operating system/version

macOS 14.5

### Terminal/GUI

kitty

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v4.23.2
- Neovim Version: v0.10.1
- OK Using stable Neovim >= 0.9.5
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `rg` is installed: Used for Telescope `live_grep` picker, `<Leader>fw` and `<Leader>fW` by default (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu-go` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

After launch nVIM, the use is fine but slow gets slower and slower.
Updating Astro doesn't fix the issue and perhaps, makes it worse.
The only solution to to restart the entire nVim instance.

### Steps to Reproduce

1. Open nVIM with Astro
2. Open 20 files
3. Close 19 files
4. Update Astro `:AstroUpdate`
5. Repeat

### Expected behavior

nVim should be snappy

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", import = "astronvim.plugins" },

  -- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by mehalter** [comment]
Given then information I cannot replicate. I have opened 100 files and don't have any significant slowdown. This could be related to plugins that you have or even things like language servers doing a lot of work or something.

One note is running `:AstroUpdate` or `:Lazy update` without a restart will definitely not improve performance at all. It's very much recommended to restart entirely after update.

**Comment by jsco2t** [comment]
I'm seeing the same issue on my install. Attempting to edit:

- Yaml
- Golang
- Lua

Results in a UI which is incredibly slow to navigate. Everything seems to grind to a halt. Scrolling/Navigating up and down a screen of code is particularity slow and laggy. Watching `btop` I can see a significant (significant being contextual to the hardware being used) spike in CPU usage. 

My `nvim version` info is:

```
NVIM v0.10.1-dev-101+g18a9ae169
Build type: RelWithDebInfo
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```

What's the best way to turn this issue report into something actionable? Is there any sort of telemetry/profiling/observability tooling that can be run which will help pin-point the problem?

A couple more items of note:

1. I didn't make any changes to my setup *other* than running `:AstroUpdate`. 
2. I always close and re-open nvim after updating plugins

Lastly - I'm wondering if the hardware being used may contribute to how observable this issue is? I have my nvim setup in a VM (been this way for a while) and it's setup to use 2 virtual CPU's. Previously this hasn't been an issue. 

I'm a huge fan of the work that the AstroNvim team (and Neovim team) does - so if there is something I can do to help investigate please let me know.

**Comment by mehalter** [comment]
I'm honestly not sure. All of my performance testing involves throttling my CPU and testing on extremely low power and decreased cores just so I can emulate low resource and/or older hardware. Not sure the best way of debugging this outside of maybe bisecting the AstroNvim repo to see if you can pin point a commit where the performance gets worse

**Comment by mehalter** [comment]
Nice. Yeah it is possible that it's language server related and if that's the case it's sorta out of scope from us to be able to fix in any way

**Comment by jsco2t** [comment]
Totally get that. 

For `Go` I think something else is in the mix. As I wait for `gopls` to go idle before attempting to use things and the editing experience is _"not great"_.

**Comment by kevinkirkup** [comment]
Just a heads up:
 Noticed these messages may be related:
`No LSP client found that supports symbols in buffer 31`

**Comment by mehalter** [comment]
@kevinkirkup nearly 100% isn't related. That is an Aerial bug: https://github.com/stevearc/aerial.nvim/issues/393

But shouldn't be causing any performance issues.

**Comment by kevinkirkup** [comment]
@mehalter Is `aerial` being pulled in by Astro?
It's not a plugin that I've included in my config.

**Comment by mehalter** [comment]
yeah it's a default plugin: https://docs.astronvim.com/reference/default_plugins/

**Comment by jsco2t** [comment]
@mehalter, @kevinkirkup  

`tl;dr` In **my** `astronvim` install I have found the following two plugins appear to be having a significant impact on CPU:

```lua
return {
  { "rebelot/heirline.nvim", enabled = false },
  { "lukas-reineke/indent-blankline.nvim", enabled = false },
}
```  

Read below for the details:

---

Before I discuss my results - let me discuss my methodology as I don't have concrete proof other than observed impact on CPU.

My methodology:

1. Have `btop` running in a terminal window - leave this window open, but make sure it's visible.
2. In a **new** terminal window: open a go source file which is part of a golang project in Astronvim
3. Wait for `gopls` and it's peers to run and go idle before continuing. In other words: Wait for the CPU to idle.
4. Scroll up and down repeatedly in `Astronvim` using the up/down arrow keys (or the j/k keys). 
5. Observe the CPU impact (specifically how much CPU `nvim` consumes)
6. Observe (subjective) how badly the UI stutters.

Where I started today:
- My baseline config: CPU usage while scrolling would hover around 20% to 30% across two cores running at 2.3ghz. The UI would visibly stutter (repeatedly)

- Running `nvim` with all plugins disabled: CPU usage while scrolling would sit around 1% to 3% (tested with: `nvim --clean /some/file/name.go`). The UI seemed smooth while scrolling.

How I _"debugged"_:

I would go through and shut off options in _Astrovim_ and eventually I disabled plugins entirely until I got my CPU usage down to (close) to the numbers I observed when `nvim` was running with 0 plugins. 

What I found was that the following two plugins seemed to be having an outsized impact on my CPU usage:

- "rebelot/heirline.nvim"
- "lukas-reineke/indent-blankline.nvim"

Tested by adding a file named `disabled.lua` into my `lua/plugins` folder with the following content:

```lua
return {
  { "rebelot/heirline.nvim", enabled = false },
  { "lukas-reineke/indent-blankline.nvim", enabled = false },
}
```  

I understand `heirline` is a pretty critical part of the default `Astronvim` experience. For me - I am likely to need to find an alternate status line configuration. `indent-blankline` is very helpful to me - but I can probably live without it.

**Comment by jsco2t** [comment]
My configuration can be found here (the config I was using to test with) should that be helpful:

https://github.com/jsco2t/dotfiles/tree/av-perf-investigation/.config/nvim

**Comment by jsco2t** [comment]
@mehalter 

As it happens I played a lot with this last night. I ended up using `heirline` but customized it slightly to remove some of the components that were updated on cursor movement. The performance is now completely acceptable (as long as I also leave `indent-blankline.nvim` disabled).

Here is a copy of the configuration I used for `heirline` (it's based on what's in the Astronvim Docs - amazing work whoever put those together): https://github.com/jsco2t/dotfiles/blob/main/.config/nvim/lua/plugins/statusline.lua

**Comment by 8tomat8** [comment]
@jsco2t This solved it for me. Thanks!
Initially I was blaming the poor performance on neo-tree plugin as with open file tree I would get extremely bad performance (e.g. easily 5sec switching between buffers) and practically stopped using the tree.
With the updated heirline config the UI is snappy as it should be. ❤️
