### ISSUE TITLE
Can't disable auto formatting

### ISSUE THREAD

**Issue by s1nistr4** [AstroNvim/AstroNvim#2681]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue
- [X] I have run `:Lazy update` and are on the latest version of AstroNvim
- [ ] I can replicate the bug with the minimal `repro.lua` provided below

### Operating system/version

Debian

### Terminal/GUI

wezterm

### AstroNvim Health

.

### Describe the bug

```
      format_on_save = {
        enabled = false, -- enable or disable format on save globally
        allow_filetypes = { -- enable format on save for specified filetypes only
          -- "go",
        },
        ignore_filetypes = { -- disable format on save for specified filetypes
          -- "python",
        },
```

Adding this to astrolsp does not disable autoformatting on startup, it instead just uses it regardless.
The source of the code snippet is in the official docs on disabling autoformatting https://docs.astronvim.com/recipes/advanced_lsp/#:~:text=%7D-,Disabling%20formatting%20for%20a%20list%20of%20language%20servers,lf%20%2C%20or%20with%20%3AFormat%20.

### Steps to Reproduce

.

### Expected behavior

.

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")
.
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", import = "astronvim.plugins" },

  -- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by mehalter** [comment]
Please follow the required checklist and make sure you have correctly made a `repro.lua` file in the template. Let me know when you have fixed the `repro.lua` and validated the replication with it, and i can reopen this! Thanks!
