### ISSUE TITLE
Show LSP references with telescope

### ISSUE THREAD

**Issue by Dinistro** [AstroNvim/AstroNvim#2694]
### Describe the new feature

I recently migrated to version 4, and was surprised that LSP references are no longer shown with telescope. This feature was exceptionally helpful when attempting to rewrite code as one could easily navigate all usages. Currently, the references are shown in a normal buffer, which lacks larger context, nor is it closed automatically when selecting one of the usages.

Is there a fundamental reason why this is no longer supported, or was this an oversight during the migration?

**Comment by mehalter** [comment]
The implementation with telescope is broken and doesn't support all language servers. This was removed by design. Here are docs if you want to add it back: https://docs.astronvim.com/recipes/mappings/#enable-telescope-lsp-mappings

**Comment by Dinistro** [comment]
Oh, I did not spot this in the documentation. Sorry for the noise and thanks for pointing this out.
