### ISSUE TITLE
Macro incorrectly applied

### ISSUE THREAD

**Issue by phylome** [AstroNvim/AstroNvim#2706]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue
- [X] I have run `:Lazy update` and are on the latest version of AstroNvim
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Operating system/version

Linux Mint 21.3 virginia

### Terminal/GUI

kitty, Gnome Terminal, Tilix, WezTerm, ...

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v4.26.2
- Neovim Version: v0.11.0-dev
- WARNING Neovim nightly is not officially supported and may have breaking changes
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `rg` is installed: Used for Telescope `live_grep` picker, `<Leader>fw` and `<Leader>fW` by default (Optional)
- WARNING `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu/gdu_windows_amd64.exe` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

A macro that uses 'gUl' to make a single letter uppercase is incorrectly recorded and causes the whole line to be uppercase.

### Steps to Reproduce

1. Type some lines of text into an empty buffer:
```
foo
bar
```
3. Switch to normal mode and place the cursor in the first line on the first column: `gg0`
4. Record the following macro into register `q` with `qqgUlq`
5. Check the register `q` with `:reg q` and observe its content to be `gUgUl`
6. Apply the macro in register `q` to the second line with `j0@q` and observe the entire line to be uppercase

### Expected behavior

1. The content of register `q` shall be `gUl`
2. When applying the macro to the second line, only the first letter shall be uppercase

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", import = "astronvim.plugins" },

  -- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by mehalter** [comment]
This is fixed upstream now, `:Lazy update` will get the fix
