### ISSUE TITLE
Treesitter-textobjects very slow when opening dart files

### ISSUE THREAD

**Issue by meisocafe** [AstroNvim/AstroNvim#2707]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue
- [X] I have run `:Lazy update` and are on the latest version of AstroNvim
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Operating system/version

macOS 14.4

### Terminal/GUI

wezterm

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: v4.26.1
- Neovim Version: v0.10.0
- WARNING Neovim nightly is not officially supported and may have breaking changes
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `rg` is installed: Used for Telescope `live_grep` picker, `<Leader>fw` and `<Leader>fW` by default (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu-go/gdu_windows_amd64.exe` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug
Opening a .dart file neovim freezes 3-4 seconds (specifically it's two consecutive freezes). The cause is treesitter-textobjects plugin and has been discussed [here](https://github.com/nvim-treesitter/nvim-treesitter/issues/2126). The problem seems to be in the dart parser.

While this is not a bug directly with Astronvim's config, it provides a bad experience as it takes time for the users to find the root cause and fix it. It would be a better experience to disable the textobjects feature for dart files by default until this is resolved in treesitter or dart.

### Steps to Reproduce

1. Create a folder with a file foo.dart
2. Open the file with nvim `nvim foo.dart`
3. Neovim freezes for a few seconds, input and movement are delayed.

### Expected behavior

Neovim should respond instantly or near-instantly when opening a file.

### Additional Context

Solution could be adding the disable line to treesitter's textobjects config function.
`    
textobjects = {
    -- Other config
    disable = { "dart" },
}
`

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", import = "astronvim.plugins" },

  -- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by mehalter** [comment]
Thanks for the recommendation! We don't do anything in core AstroNvim that is language specific for a lot of specific design reasons and to make it very understandable what is running. This ideally will get fixed upstream in the dart parser which will trickle down into making the behavior better in AstroNvim.

There is a snippet that can be added into your `plugins/` directory to resolve this:

```lua
return {
  "nvim-treesitter/nvim-treesitter",
  opts = function(_, opts)
    local select = vim.tbl_get(opts, "textobjects", "select")
    if select then select.disable = require("astrocore").list_insert_unique(select.disable, { "dart" }) end
  end,
}
```

Also [AstroCommunity](https://github.com/AstroNvim/astrocommunity) is the main place where language specific recommendations can go. I will go ahead and add this to the Dart pack: https://github.com/AstroNvim/astrocommunity/pull/1211
