### ISSUE TITLE
Unexpected option type "main" in diagnostic.lua line 503

### ISSUE THREAD

**Issue by Cyliann** [AstroNvim/AstroNvim#2708]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue
- [X] I have run `:Lazy update` and are on the latest version of AstroNvim
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Operating system/version

NixOS unstable

### Terminal/GUI

kitty/Neovide

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v4.26.2
- Neovim Version: v0.10.1
- OK Using stable Neovim >= 0.9.5
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `rg` is installed: Used for Telescope `live_grep` picker, `<Leader>fw` and `<Leader>fW` by default (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- WARNING `node` is not installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu/gdu_windows_amd64.exe` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

If an LSP (eg. basedpyright, nixd) is installed after every letter I type or undo an error message in nvim (not a notification) appears, saying:
```
Error executing vim.schedule lua callback: ...wrapped-0.10.1/share/nvim/runtime/lua/vim/diagnostic.lua:503: Unexpected option type: "main"
stack traceback:
	[C]: in function 'error'
	...wrapped-0.10.1/share/nvim/runtime/lua/vim/diagnostic.lua:503: in function 'resolve_optional_value'
	...wrapped-0.10.1/share/nvim/runtime/lua/vim/diagnostic.lua:516: in function 'get_resolved_options'
	...wrapped-0.10.1/share/nvim/runtime/lua/vim/diagnostic.lua:1658: in function 'show'
	...wrapped-0.10.1/share/nvim/runtime/lua/vim/diagnostic.lua:1031: in function 'set'
	...ped-0.10.1/share/nvim/runtime/lua/vim/lsp/diagnostic.lua:260: in function 'handle_diagnostics'
	...ped-0.10.1/share/nvim/runtime/lua/vim/lsp/diagnostic.lua:293: in function 'old_callback'
	...e/nvim/lazy/aerial.nvim/lua/aerial/backends/lsp/init.lua:15: in function 'handler'
	...wrapped-0.10.1/share/nvim/runtime/lua/vim/lsp/client.lua:1007: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Steps to Reproduce

1. Use Nixos
2. Install an LSP through nixpkgs (doesn't work with mason, cause mason required dynamically linked librares, which Nixos doesn't support)
3. Source LSP in astrolsp.lua using:
 ```lua
servers = { "basedpyright"},
```
4. Open a file with LSP support.
5. Type anything

### Expected behavior

Functioning LSP.

### Screenshots

![image](https://github.com/user-attachments/assets/b12faaaf-eff9-4016-b5e4-93563263cc5d)

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
{ "AstroNvim/AstroNvim", import = "astronvim.plugins" },
{
  "AstroNvim/astrolsp",
  opts = {
    servers = {
      "basedpyright",
    },
  },
},
{
  "AstroNvim/astrocore",
  opts = {
    diagnostics = {
      nagaVersion = "main",
    },
  },
},
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by mehalter** [comment]
This makes sense, `nagaVersion = "main"` is not a valid option in `vim.diagnostic.config`

**Comment by Cyliann** [comment]
Thanks. I had to accidentally copy it during migration from v3.
