### ISSUE TITLE
Mason installed twig-cs-fixer does not work

### ISSUE THREAD

**Issue by haivala** [AstroNvim/AstroNvim#2712]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue
- [X] I have run `:Lazy update` and are on the latest version of AstroNvim
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Operating system/version

Arch

### Terminal/GUI

alacritty

### AstroNvim Health

# AstroNvim ~
- AstroNvim Version: v4.26.5
- Neovim Version: v0.10.1
- OK Using stable Neovim >= 0.9.5
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `rg` is installed: Used for Telescope `live_grep` picker, `<Leader>fw` and `<Leader>fW` by default (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Mason installed twig formatter twig-cs-fixer is not available on twig files. Executable is installed and usable by calling it but not found usable in LSP menu or on save.

### Steps to Reproduce

1. install neovim and install astrovim
1. Open Mason
2. install twig-cs-fixer
3. open twig file
4. LSP formatting option is not available

### Expected behavior

twig formatting on save

### Repro

```Lua
Is this really needed?
```

**Comment by mehalter** [comment]
If you get a good configuration built out, then it could also be a good idea to open up a PR to none-ls to add it in as a formatter and then support would work for others out of the box :)

**Comment by panda-67** [comment]
add new file 

> lua/user/plugins/null-ls/djlint.lua

```
local h = require("null-ls.helpers")
local methods = require("null-ls.methods")

local FORMATTING = methods.internal.FORMATTING

return h.make_builtin({
    name = "djlint",
    meta = {
        url = "https://github.com/Riverside-Healthcare/djLint",
        description = "✨ 📜 🪄 ✨ HTML Template Linter and Formatter.",
    },
    method = FORMATTING,
    filetypes = { "twig", "django", "jinja.html", "htmldjango" },
    generator_opts = {
        command = "djlint",
        args = { "--reformat", "-" },
        to_stdin = true,
    },
    factory = h.formatter_factory,
})
```

and edit file

> lua/plugins/none-ls.lua

```

return {
  "nvimtools/none-ls.nvim",
  opts = function(_, opts)
    local djlint = require("user.plugins.null-ls.djlint")
    opts.sources = opts.sources or {}
    table.insert(opts.sources, djlint)
  end,
}
```
