### ISSUE TITLE
find words in all file

### ISSUE THREAD

**Issue by itpofy2024o** [AstroNvim/AstroNvim#2715]
### Is your feature related to a problem?

i found out when i pressed space + f it only gave me an option to find words in current buffer. but i want to search a value across all files. how can i achieve that?

### Describe the new feature

able to find a word across all files

**Comment by mehalter** [comment]
`<Leader>fw` will search for words across all files (non-hidden), `<Leader>fW` will search across all files including hidden

**Comment by itpofy2024o** [comment]
Dear AstroNvim

I only have / as find words in current buffer. There is no w in find
command.  There is no find words across all buffer or all files

**Comment by itpofy2024o** [comment]
Do you mean install ripgrep on my Mac or inside the neovim system?

**Comment by mehalter** [comment]
On your Mac. Check the requirements in the AstroNvim documentation and README
