### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by assyrus-favolo** [AstroNvim/AstroNvim#2718]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue
- [ ] I have run `:Lazy update` and are on the latest version of AstroNvim
- [ ] I can replicate the bug with the minimal `repro.lua` provided below

### Operating system/version

Ubuntu 24.04

### Terminal/GUI

Windows terminal

### AstroNvim Health

NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377

### Describe the bug

```
Error detected while processing /root/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /root/.config/nvim/init.lua:7: attempt to index field 'uv' (a nil value)
stack traceback:
        /root/.config/nvim/init.lua:7: in main chunk
```

### Steps to Reproduce

install nvim, install Astronvim, run nvim

### Expected behavior

It should start without errors because the docs say that the version of Neovim 0.9.5 is supported

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", import = "astronvim.plugins" },

  -- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**I can start with the minimal init script, but not the one that came with the repository**

**Comment by mehalter** [comment]
I cannot replicate with the `repro.lua` file. It looks to be a problem with your user configuration and not in AstroNvim. I would recommend taking a look at the template we provide for getting started: https://github.com/AstroNvim/template

My guess is in the beginning when you are going to bootstrap the Lazy.nvim plugin manager you have a call to `vim.uv` which is a new name in Neovim v0.10 (previously `vim.loop` in Neovim <0.10). You probably want that to be `(vim.uv or vim.loop)` wherever you use it. Here is how we recommend you do it in the AstroNvim template: https://github.com/AstroNvim/template/blob/main/init.lua#L4

**Comment by assyrus-favolo** [comment]
So should I just drop that version of `init.lua` in place of the current default one?

**Comment by mehalter** [comment]
sure :) or just fix the bug in your user configuration. I'm not sure what else you are doing in your `init.lua` file. The template is not part of the AstroNvim source code. It's a recommended starting point. All of the code inside of your `~/.config/nvim` folder is considered yours. You also don't have to start with the template at all and could just make your own Neovim configuration with the lazy.nvim plugin manager and add/import the AstroNvim plugin.

**Comment by assyrus-favolo** [comment]
Oh, my bad, I had a holdover configuration from another installation, it wasn't the AstroNvim one, scratch all that

**Comment by assyrus-favolo** [comment]
Thanks for pointing me in the right track!
