### ISSUE TITLE
something new do not happen to cmp

### ISSUE THREAD

**Issue by Tzlzl12** [AstroNvim/AstroNvim#2719]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue
- [X] I have run `:Lazy update` and are on the latest version of AstroNvim
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Operating system/version

wsl2

### Terminal/GUI

wezterm

### AstroNvim Health

![Snipaste_2024-10-20_22-45-30](https://github.com/user-attachments/assets/b23f6dcf-3ed7-4288-85bc-f8c00b455a90)
Sorry, I don't know how to copy the content on wsl2

### Describe the bug

The window size and fields position of cmp cannot be changed

### Steps to Reproduce

![Snipaste_2024-10-20_22-47-20](https://github.com/user-attachments/assets/e04277de-57cd-416d-8b48-e5585f9d1437)
This is the beginning, showing 1 2 3

### Expected behavior

Now I want it to be displayed as **2 1 3**
My code is as follows
``` lua
{
    "hrsh7th/nvim-cmp",
    dependencies = {
      "hrsh7th/cmp-emoji",
      "onsails/lspkind.nvim",
      -- "hrsh7th/cmp-cmdline",
    },

    opts = {
      
      window = {
        completion = {
          -- require("cmp").config.window.bordered(),
          -- border = "rounded",
          winhighlight = "Normal:Pmenu,FloatBorder:Pmenu,Search:None",
          -- border = borderMenu "CmpBorder",
          border = "rounded",
          scrollbar = true,
          scrolloff = 1,
          col_offset = 1,
          side_padding = 1,
          -- pumwidth = 30,
          -- pumheight = 20,
          -- maxwidth = 30,
          -- maxheight = 20,
        },
        
        formatting = {
          fields = { "abbr", "kind", "menu" },
          format = function(_, item)
            -- local icons = require("mini.icons").opts
            -- local icon = icons[item.kind] or ""
            -- item.kind = string.format("%s %s ", icon, trim(item.kind))
            -- item.abbr = getMethodName(trim(item.abbr))
            -- item.abbr = string.sub(item.abbr, 1, 20)
            -- item.menu = truncateString(trim(item.menu), 30)
            local widths = {
              abbr = 30,
              menu = 20,
            }

            for key, width in pairs(widths) do
              -- item[key] = truncateString(trim(item[key]), width) .. "…"
              if item[key] and vim.fn.strdisplaywidth(item[key]) > width then
                item[key] = string.sub(item[key], 1, width - 1) .. "…"
              end
            end
            return item
          end,
        },
      },
    },
```
But there is no change
*Still display according to 1 2 3*

I have found the code to control the window size,
but it seems that only the ***formatting field*** does not work.
I tried changing the **appearance of the window**, which worked.

### Repro

```Lua
1
```

**Comment by mehalter** [comment]
You are inccorectly building your `nvim-cmp` `opts`. You put the `formatting` field into the `window` field. Here is one that is correct and it works:

```lua
return {
  "hrsh7th/nvim-cmp",
  opts = {
    formatting = {
      fields = { "abbr", "kind", "menu" },
    },
  },
}
```
