### ISSUE TITLE
Rename a default mapping to "Menu name"

### ISSUE THREAD

**Issue by alr86** [AstroNvim/AstroNvim#2721]
### Is your feature related to a problem?

When I want to change `<Leader>C` to a menu name, I must use this custom mapping:
```lua
opts = {
  mappings = {
    n = {
      ["<Leader>C"] = { desc = "Custom" },
    }                   ^^^^
  }
}
```

### Describe the new feature

Use the "name" attribute instead of "desc"

**Comment by mehalter** [comment]
This is how you would do it. You basically need to make sure you _remove_ the function that is bound to the `<Leader>C` key.


```lua
return {
  "AstroNvim/astrocore",
  opts = function(_, opts)
    opts.mappings.n["<Leader>C"] = { desc = "Custom" }
    opts.mappings.n["<Leader>Cn"] = { function() print "TEST MAPPING" end, desc = "test mapping" }
  end,
}
```
