### ISSUE TITLE
Disable modelines by default

### ISSUE THREAD

**Issue by LandonSchropp** [AstroNvim/AstroNvim#2725]
### Is your feature related to a problem?

I just discovered the `modeline` option in Neovim after it caused an error when trying to parse a YAML file. This option seems to be _mostly_ pointless, and given that it can cause some strange and unexpected errors, the general advice seems to be to disable it.

### Describe the new feature

I'm disabling `modeline` in my personal config, but I thought I'd mention it here as well since turning it off seems to be a good default for everyone that'll avoid unexpected errors.

``` lua
vim.o.modeline = false
```

### Additional context

Here are a few examples issues I ran across when trying to debug my problem:

- [How aren't modelines breaking everything??](https://www.reddit.com/r/neovim/comments/15qm1zf/how_arent_modelines_breaking_everything/)
- ["Error detected while processing modelines" when opening text file](https://github.com/neovim/neovim/issues/8906)
- [vim e518: unknown option:](https://stackoverflow.com/questions/8583028/vim-e518-unknown-option)

**Comment by mehalter** [comment]
This is an extremely core vim feature and we want it left on by default. Feel free to disable in your configuration!
