### ISSUE TITLE
remapping a default mapping

### ISSUE THREAD

**Issue by karlivory** [AstroNvim/AstroNvim#2726]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue
- [ ] I have run `:Lazy update` and are on the latest version of AstroNvim
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Operating system/version

ubuntu 24.04

### Terminal/GUI

st

### AstroNvim Health

- AstroNvim Version: v4.27.1
- Neovim Version: v0.10.1
- OK Using stable Neovim >= 0.9.5
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `rg` is installed: Used for Telescope `live_grep` picker, `<Leader>fw` and `<Leader>fW` by default (Optional)
- WARNING `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu/gdu_windows_amd64.exe` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

I wanted to remap ctrl-q. 

```
["<C-q>"] = { "<cmd> Telescope find_files hidden=true<CR>", desc = "find files" },
```

causes c-q to be mapped randomly (sometimes default, sometimes user).

```
["<C-Q>"] = { "<cmd> Telescope find_files hidden=true<CR>", desc = "find files" },
```

works fine.

### Steps to Reproduce

Run `nvim -u repro.lua` multiple times, press c-q.

### Expected behavior

It should either work or not. No random mapping

Maybe astronvim should normalize the user-defined C-_ mappings to uppercase or something?

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable",
    lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
	{ "AstroNvim/AstroNvim", import = "astronvim.plugins" },

	-- add any other plugins/customizations here
	{
		"AstroNvim/astrocore",
		---@type AstroCoreOpts
		opts = {
			mappings = {
				-- NORMAL MODE
				n = {
					["<C-q>"] = { "<cmd> Telescope find_files hidden=true<CR>", desc = "find files" },
				},
			},
		},
	},
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by mehalter** [comment]
This is a limitation in the table structure. Keys need to match to override. Iteration over tables is not a fixed sort which leads to the unpredictable behavior. Newer versions of AstroNvim will report this in checkhealth. I would recommend updating to help debug and identify these issues. There has been a lot of discussion over the years to improve this and time and time again we have found normalization is not any more stable. 

For now I will choose this as not planned, sorry!
