### ISSUE TITLE
AstroNvim crashes when attempting to type an empty Python format string

### ISSUE THREAD

**Issue by kvpeab** [AstroNvim/AstroNvim#2730]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue
- [X] I have run `:Lazy update` and are on the latest version of AstroNvim
- [ ] I can replicate the bug with the minimal `repro.lua` provided below

### Operating system/version

macOS Ventura 13.7

### Terminal/GUI

kitty

### AstroNvim Health

```
==============================================================================
astronvim: require("astronvim.health").check()

Checking requirements ~
- AstroNvim Version: v4.28.0
- Neovim Version: v0.10.2
- OK Using stable Neovim >= 0.9.5
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `rg` is installed: Used for Telescope `live_grep` picker, `<Leader>fw` and `<Leader>fW` by default (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu-go/gdu_windows_amd64.exe` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)
```

### Describe the bug

When trying to type a format string in a Python file, AstroNvim hard-freezes, accepting no inputs at all and requiring me to quit the terminal program to exit. This does not occur in unmodified Nvim or in other distros, but does seem to happen even in a completely fresh install of AstroNvim.

### Steps to Reproduce

1. Install AstroNvim fresh after cleaning/backing up config, local share/state, & cache.
2. Open any Python file, existing or new (i.e. `nvim demo.py`) and enter insert mode.
3. Type `f` followed by `"`, which should autocomplete to `""`
4. Type `{`
5. Nvim will autocomplete the `{` to `{}` and then (for me) instantly freeze. It will accept no inputs, forcing me to quit the terminal in order to exit.

### Expected behavior

Nvim should not freeze.

### Screenshots

<img width="198" alt="Screenshot 2024-11-18 at 4 07 17 PM" src="https://github.com/user-attachments/assets/336222b6-f40d-4dc1-8112-0cd694798ef2">

### Additional Context

Curiously, this seems to be a fundamental problem with Python format strings -- this problem doesn't happen in files that don't end in `.py`. It doesn't even occur if typing `"{}"`; however, if I type this out, add an `f` to the front of the line, and then return to the brackets and try to enter insert mode between then, I get the same freezing behavior.

### Repro

```Lua
-- This file simply bootstraps the installation of Lazy.nvim and then calls other files for execution
-- This file doesn't necessarily need to be touched, BE CAUTIOUS editing this file and proceed at your own risk.
local lazypath = vim.env.LAZY or vim.fn.stdpath "data" .. "/lazy/lazy.nvim"
if not (vim.env.LAZY or (vim.uv or vim.loop).fs_stat(lazypath)) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(lazypath)

-- validate that lazy is available
if not pcall(require, "lazy") then
  -- stylua: ignore
  vim.api.nvim_echo({ { ("Unable to load lazy from: %s\n"):format(lazypath), "ErrorMsg" }, { "Press any key to exit...", "MoreMsg" } }, true, {})
  vim.fn.getchar()
  vim.cmd.quit()
end

require "lazy_setup"
require "polish"
```

**Comment by mehalter** [comment]
I am unable to replicate this. Can you please share your configuration or provide a minimal `init.lua` file that can reproduce the bug

**Comment by kvpeab** [comment]
This problem occurs for me using the default template configuration found at `https://github.com/AstroNvim/template/tree/main`. I've tried to remove as much of its `init.lua` as I can that still causes the bug for me:

```
local lazypath = vim.env.LAZY or vim.fn.stdpath "data" .. "/lazy/lazy.nvim"
vim.opt.rtp:prepend(lazypath)
require "lazy_setup"
```

but seeing as the lines I've cut mostly seem to double-check for the presence of lazy and install it if it's missing, I don't know if it will be meaningfully different. Removing more lines than this does seem to "fix" the bug by simply not loading any of AstroNvim whatsoever.

Is it possible that a prior AstroNvim configuration of mine could somehow be influencing a completely fresh install? I've tried to remove all the folders where it could store information:
```
rm -rf ~/.local/state/nvim
rm -rf ~/.local/share/nvim
rm -rf ~/.cache/nvim
```
before installing again, but the bug still occurs in AstroNvim.

**Comment by mehalter** [comment]
I'm not sure, I cannot replicate the bug sadly with my configuration or a fresh installation of the template

**Comment by greggthomason** [comment]
I am having the same problem. It started occuring a few days ago after I did `:Lazy update`.

**Comment by mehalter** [comment]
Can you provide steps to reproduce it @greggthomason ?

**Comment by greggthomason** [comment]
<img width="1840" alt="Screenshot 2024-11-21 at 3 08 37 PM" src="https://github.com/user-attachments/assets/0df7771a-b666-49f5-a432-7405db4391f5">
This image shows the crash. I typed it by hand. As soon as I typed the `{` it locks.

**Comment by greggthomason** [comment]
repro'd with full reinstall.

**Comment by mehalter** [comment]
What version of treesitter do you have installed? Looks like it is probably a mac bug with treesitter:

https://github.com/tree-sitter/tree-sitter/issues/3930#issuecomment-2469987957

https://github.com/neovim/neovim/issues/31163#issuecomment-2469978909

**Comment by kvpeab** [comment]
Reinstalling tree-sitter (`brew reinstall tree-sitter`) fixed the bug for me; thank you!

**Comment by greggthomason** [comment]
Same! Thanks for the catch.
