### ISSUE TITLE
Remove "Find" from "<Leader>f" section?

### ISSUE THREAD

**Issue by RayJameson** [AstroNvim/AstroNvim#2734]
### Is your feature related to a problem?

No

### Describe the new feature

I believe it's redundant to repeat "Find" under "Find" section, I made these changes in my config, I think it look cleaner, but it's opinionated, so I started with an issue

### Additional context

![image](https://github.com/user-attachments/assets/39a8c8f2-3f5e-4409-be08-2936b5be7638)

**Comment by mehalter** [comment]
Thanks for the suggestion! We don't want this change. All keymap descriptions should be fully self contained for stuff like pickers
