### ISSUE TITLE
Cannot  open the correct file useTelescope's Find File<space+ff> 

### ISSUE THREAD

**Issue by wqk151** [AstroNvim/AstroNvim#2736]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue
- [X] I have run `:Lazy update` and are on the latest version of AstroNvim
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Operating system/version

ubuntu20.04

### Terminal/GUI

kitty

### AstroNvim Health

       astronvim: require("astronvim.health").check()
   3   
   4   Checking requirements
   5   - AstroNvim Version: v4.29.0
   6   - Neovim Version: v0.10.2
   7   - OK Using stable Neovim >= 0.9.5
   8   - OK git is installed: Used for core functionality such as updater and plugin management
   9   - WARNING xdg-open/rundll32/explorer.exe/open is not installed: Used for gx mapping for opening files with system opener (Optional)
  10   - OK rg is installed: Used for Telescope live_grep picker, <Leader>fw and <Leader>fW by default (Optional)
  11   - WARNING lazygit is not installed: Used for mappings to pull up git TUI (Optional)
  12   - WARNING node is not installed: Used for mappings to pull up node REPL (Optional)
  13   - WARNING gdu/gdu_windows_amd64.exe is not installed: Used for mappings to pull up disk usage analyzer (Optional)
  14   - WARNING btm is not installed: Used for mappings to pull up system monitor (Optional)
  15   - OK python3 is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

I've tried many times to migrate from v3 to v4, but <space+ff> can't open the selected file, I tested on debian12 and ubuntu20.04, and also used docker to install a clean environment to test, but it didn't work

### Steps to Reproduce

1. Go to the ~/.config/nvim/lua directory 
2. Run the nvim command,and run <space+ff>
3. Input 'as' and select astrolsp.lua
4. but open the astroui.lua file
5. also ,select astrocore.lua,will open astrolsp.lua

### Expected behavior

Open the correct file

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", import = "astronvim.plugins" },

  -- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)




Can reproduce the same problem
```

**Comment by mehalter** [comment]
I cannot replicate this at all given the provided steps. Please provide clearer instructions as to how you are selecting files. My guess is you are using the `<Tab>` key to navigate the list which by default in telescope is used for multi-selection and not navigation.

**Comment by wqk151** [comment]
Yes, I used`<Tab>`to select up and down, and just tested using`<Tab>`, which caused the above problem. Using`<Ctrl+n>`can work normally, but v3 use `<Tab>` can work well.

**Comment by mehalter** [comment]
Yeah that would be the reason. The tab key is used for multi-selection. We fixed it to where the multi-selection is actually respected when pressing enter rather than it being ignored. I would recommend remapping the key to not be the default multi-selection or use the default mappings for moving up and down the list like `ctrl+j`/`ctrl+n` and `ctrl+k`/`ctrl+p`
