### ISSUE TITLE
Code Lines Disorder

### ISSUE THREAD

**Issue by DevAbdelkader** [AstroNvim/AstroNvim#2740]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue
- [X] I have run `:Lazy update` and are on the latest version of AstroNvim
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Operating system/version

Fedora 39

### Terminal/GUI

Gnome Terminal

### AstroNvim Health

- AstroNvim Version: v4.29.0
- Neovim Version: v0.10.3
- OK Using stable Neovim >= 0.9.5
- OK git is installed: Used for core functionality such as updater and plugin management
- OK xdg-open is installed: Used for gx mapping for opening files with system opener (Optional)
- WARNING rg is not installed: Used for Telescope live_grep picker, <Leader>fw and <Leader>fW by default (Optional)
- WARNING lazygit is not installed: Used for mappings to pull up git TUI (Optional)
- OK node is installed: Used for mappings to pull up node REPL (Optional)
- WARNING gdu/gdu_windows_amd64.exe is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING btm is not installed: Used for mappings to pull up system monitor (Optional)
- OK python is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Incorrect order of code lines during file browsing, even on opening the file.

### Steps to Reproduce

1. Start Nvim
2. Open File
3. Lines Disorder

### Expected behavior

It should be ordered.

### Screenshots

![Screenshot from 2024-12-24 14-16-09](https://github.com/user-attachments/assets/fdad33f4-910a-4027-a385-b2ca66908bdf)

### Additional Context

No Plugins are used.

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", import = "astronvim.plugins" },

  -- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by mehalter** [comment]
These are relative line numbers which are enabled by default (`:h relativenumber`). You can adjust this setting in your configuration
