### ISSUE TITLE
Is there a way to remap a <leader>xx sequence?

### ISSUE THREAD

**Issue by Tyrn** [AstroNvim/AstroNvim#2741]
### Is your feature related to a problem?

It's all about using normal mode with different keyboard layouts.

### Describe the new feature

I can't tell whether it's a feature. Maybe there's already a way to do such a thing, maybe it's impossible. The "remapping" I need would look like this:
```
<leader>гц => <leader>uw
```
Cyrillic to Latin, so the physical key remain the same, regardless of the keyboard layout.

**Comment by mehalter** [comment]
It sounds like what you want is a core, built in feature to Vim called `langmap`. Check out `:h langmap` and read about it online. Checkout the Discord as well for a great place to ask many users questions about vim and AstroNvim:)

**Comment by Tyrn** [comment]
I understand this isn't a place to discuss the issue in any depth.

`langmap` is less than perfect solution, trust me :)
