### ISSUE TITLE
problem on new install

### ISSUE THREAD

**Issue by adrien-barret** [AstroNvim/AstroNvim#313]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [X] `:PackerSync`
- [can't do it] `:AstroUpdate`

**Describe the bug**

I tried a fresh install but have a error which give me problems to follow the differents steps
```
                    Error detected while processing /home/user/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/user/.config/nvim/init.lua:25: Failed to load core.autocmds

/home/user/.config/nvim/lua/core/autocmds.lua:9: attempt to call local 'augroup' (a nil value)
stack traceback:
        [C]: in function 'error'
        /home/user/.config/nvim/init.lua:25: in main chunk
```

I tried to remove nvim with that, but same problem:
rm -rf ~/.config/nvim
rm -rf ~/.local/share/nvim
rm -rf ~/.cache/nvim

*** version:
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

any ideas? 

ty

**Comment by mehalter** [comment]
AstroNvim no longer supports Neovim v0.6 as we are utilizing many new Lua APIs that were added in version 0.7. We have made a tag for the last commit before this migration. This is documented in the README as well as the documentation website as well as the command to checkout the neovim 0.6 supported commit `git checkout neovim-0.6` in your `~/.config/nvim` directory

**Comment by adrien-barret** [comment]
sorry, missed that !

**Comment by mehalter** [comment]
No problem! I will warn you that I think come plugins have also started dropping support for neovim 0.6 as well. I know the comment plugin for sure has and it's pretty unfortunate since neovim 0.7 isn't available across all package managers yet. I would recommend updating though if you are able to!
