### ISSUE TITLE
Virtual text in Dartls LSP

### ISSUE THREAD

**Issue by Olavq** [AstroNvim/AstroNvim#315]
Hello,
I have problem with configuration virtual text to show ended of widget in Dartls LSP extension.

```
local config = {

  -- Set colorscheme
  colorscheme = "default_theme",

  -- Default theme configuration
  default_theme = {
    diagnostics_style = "none",
    -- Modify the color table
    colors = {
      fg = "#abb2bf",
    },
    -- Modify the highlight groups
    highlights = function(highlights)
      local C = require "default_theme.colors"

      highlights.Normal = { fg = C.fg, bg = C.bg }
      return highlights
    end,
  },

  -- Configure plugins
  plugins = {
    -- Add plugins, the packer syntax without the "use"
    init = {
      -- { "andweeb/presence.nvim" },
      -- {
      --   "ray-x/lsp_signature.nvim",
      --   event = "BufRead",
      --   config = function()
      --     require("lsp_signature").setup()
      --   end,
      -- },
    },
    -- All other entries override the setup() call for default plugins
    telescope= {
      pickers = {
        find_files = {
          hidden = true
        }
      }
    },
    treesitter = {
      ensure_installed = { "lua" },
    },
    packer = {
      compile_path = vim.fn.stdpath "config" .. "/lua/packer_compiled.lua",
    },
  },

  -- Add paths for including more VS Code style snippets in luasnip
  luasnip = {
    vscode_snippet_paths = {},
  },

  -- Diagnostics configuration (for vim.diagnostics.config({}))
  diagnostics = {
    virtual_text = true,
    underline = true,
  },

  -- null-ls configuration
  ["null-ls"] = function()
    local status_ok, null_ls = pcall(require, "null-ls")
    if status_ok then
      null_ls.setup {
        debug = false,
        sources = {
          null_ls.builtins.formatting.prettier,
          null_ls.builtins.diagnostics.eslint,
        },
        on_attach = function(client)
          if client.resolved_capabilities.document_formatting then
            vim.cmd "autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()"
          end
        end,
      }
    end
  end,
  -- This function is run last
  -- good place to configure mappings and vim options
  polish = function()
    local opts = { noremap = true, silent = true }
    local map = vim.api.nvim_set_keymap
    local set = vim.opt
    -- Set options
    set.relativenumber = true

    -- Set key bindings
    map("n", "<C-s>", ":w!<CR>", opts)

    -- Set autocommands
    vim.cmd [[
      augroup packer_conf
        autocmd!
        autocmd bufwritepost plugins.lua source <afile> | PackerSync
      augroup end
    ]]
  end,
}

return config

```

Here is my user/init.lua config. I delete from here my tries to configure this.

Virtual text is used to show the end of the widget, something like at the picture.
![image](https://user-images.githubusercontent.com/91425380/164048290-30ef539d-f832-46c5-93b3-aa1ee6490c8c.png)

**Comment by hunger** [comment]
Sorry, I do not know Dart... what do you expect this to look like? How does this look in another editor that has the expected level of support?

Nvim can not do "inlay hints" (virtual text within one line) and will shownall of thatvtext at the end of the line instead. Maybe that's whats causing the unexpected rendering?

**Comment by hunger** [comment]
Neovim can do that virtual text, too and does so when installing e.g. rust-tools.nvim. So it is probably "just" a question of hoe to set this up.

Checking what exactly coc-flutter does in comparison to rust-tools.nvim might be one way to get started here.

Or you could check github for nvim-specific flutter plugins like e.g. https://github.com/akinsho/flutter-tools.nvim

**Comment by mehalter** [comment]
I think the `flutter-tools.nvim` plugin that @hunger linked is the missing piece to the puzzle for getting those flutter specific tools set up to show correctly with the NeoVim LSP. That should be able to extend the built in LSP capabilities to do stuff like the closing tags and such since those are very dart language server specific.

**Comment by Olavq** [comment]
Thank you very much, it works! I don't found it before.

**Comment by bryant-the-coder** [comment]
> Hello, I have problem with configuration virtual text to show ended of widget in Dartls LSP extension.
> 
> ```
> local config = {
> 
>   -- Set colorscheme
>   colorscheme = "default_theme",
> 
>   -- Default theme configuration
>   default_theme = {
>     diagnostics_style = "none",
>     -- Modify the color table
>     colors = {
>       fg = "#abb2bf",
>     },
>     -- Modify the highlight groups
>     highlights = function(highlights)
>       local C = require "default_theme.colors"
> 
>       highlights.Normal = { fg = C.fg, bg = C.bg }
>       return highlights
>     end,
>   },
> 
>   -- Configure plugins
>   plugins = {
>     -- Add plugins, the packer syntax without the "use"
>     init = {
>       -- { "andweeb/presence.nvim" },
>       -- {
>       --   "ray-x/lsp_signature.nvim",
>       --   event = "BufRead",
>       --   config = function()
>       --     require("lsp_signature").setup()
>       --   end,
>       -- },
>     },
>     -- All other entries override the setup() call for default plugins
>     telescope= {
>       pickers = {
>         find_files = {
>           hidden = true
>         }
>       }
>     },
>     treesitter = {
>       ensure_installed = { "lua" },
>     },
>     packer = {
>       compile_path = vim.fn.stdpath "config" .. "/lua/packer_compiled.lua",
>     },
>   },
> 
>   -- Add paths for including more VS Code style snippets in luasnip
>   luasnip = {
>     vscode_snippet_paths = {},
>   },
> 
>   -- Diagnostics configuration (for vim.diagnostics.config({}))
>   diagnostics = {
>     virtual_text = true,
>     underline = true,
>   },
> 
>   -- null-ls configuration
>   ["null-ls"] = function()
>     local status_ok, null_ls = pcall(require, "null-ls")
>     if status_ok then
>       null_ls.setup {
>         debug = false,
>         sources = {
>           null_ls.builtins.formatting.prettier,
>           null_ls.builtins.diagnostics.eslint,
>         },
>         on_attach = function(client)
>           if client.resolved_capabilities.document_formatting then
>             vim.cmd "autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()"
>           end
>         end,
>       }
>     end
>   end,
>   -- This function is run last
>   -- good place to configure mappings and vim options
>   polish = function()
>     local opts = { noremap = true, silent = true }
>     local map = vim.api.nvim_set_keymap
>     local set = vim.opt
>     -- Set options
>     set.relativenumber = true
> 
>     -- Set key bindings
>     map("n", "<C-s>", ":w!<CR>", opts)
> 
>     -- Set autocommands
>     vim.cmd [[
>       augroup packer_conf
>         autocmd!
>         autocmd bufwritepost plugins.lua source <afile> | PackerSync
>       augroup end
>     ]]
>   end,
> }
> 
> return config
> ```
> 
> Here is my user/init.lua config. I delete from here my tries to configure this.
> 
> Virtual text is used to show the end of the widget, something like at the picture. ![image](https://user-images.githubusercontent.com/91425380/164048290-30ef539d-f832-46c5-93b3-aa1ee6490c8c.png)

font>
