### ISSUE TITLE
laststatus=2

### ISSUE THREAD

**Issue by sbeyer** [AstroNvim/AstroNvim#322]
Hi,

I wanted to set `laststatus` to 2 because that's the mode I prefer. My journey: Adding `vim.o.laststatus = 2` to my `lua/user/init.lua` did not help. I checked the [new documentation](https://astronvim.github.io/recipes/globalstatus) (thank you for that!) -- and it said to use the `globalstatus = false` setting for lualine but that does not help (and was already contained in my custom `lua/user/plugins/lualine.lua`).

The reason seems to be [that `laststatus = 3` is set on `BufWinLeave`](https://github.com/AstroNvim/AstroNvim/blob/main/lua/core/autocmds.lua#L55). Changing the value there, makes it work, of course.

So is this a bug or do I miss something obvious?

**Comment by mehalter** [comment]
This is something that can be configured in the `user/init.lua` `polish` function. I am hoping that `bufferline` will get better support soon that will make this easier. But I would recommend deleting the `dashboard_settings` autocommand group and redefining your own. I should update this in the website documentation as well. When we first created it we didn't realize that the dashboard didn't understand the idea of globalstatus yet.

For now, the best way to do this is to put the following code in your `polish()` function to delete the autogroup and then redefine it with your `laststatus=2`. Sorry this is so ugly :joy: we need to find a better solution...

```lua
vim.api.nvim_del_augroup_by_name "dashboard_settings"
vim.api.nvim_create_augroup("dashboard_settings", {})
if utils.is_available "bufferline.nvim" then
  vim.api.nvim_create_autocmd("FileType", {
    desc = "Disable tabline for dashboard",
    group = "dashboard_settings",
    pattern = "dashboard",
    command = "set showtabline=0",
  })
  vim.api.nvim_create_autocmd("BufWinLeave", {
    desc = "Reenable tabline when leaving dashboard",
    group = "dashboard_settings",
    pattern = "<buffer>",
    command = "set showtabline=2",
  })
end
vim.api.nvim_create_autocmd("FileType", {
  desc = "Disable statusline for dashboard",
  group = "dashboard_settings",
  pattern = "dashboard",
  command = "set laststatus=0",
})
vim.api.nvim_create_autocmd("BufWinLeave", {
  desc = "Reenable statusline when leaving dashboard",
  group = "dashboard_settings",
  pattern = "<buffer>",
  command = "set laststatus=2",
})
vim.api.nvim_create_autocmd("BufEnter", {
  desc = "No cursorline on dashboard",
  group = "dashboard_settings",
  pattern = "*",
  command = "if &ft is 'dashboard' | set nocursorline | endif",
})
  ```

**Comment by mehalter** [comment]
Although given Dashboard.nvim hasn't been updated in over a year.... I'm not very confident a new update will come out :( I think @kabinspace was discussing moving to a different dashboard plugin that is more updated and maintained, but that is not confirmed yet.

**Comment by mehalter** [comment]
@sbeyer I just pushed a quick update to the documentation for the recipe for disabling `globalstatus`. Let me know if this does not resolve your problem or if you find any bugs in this code block! Thanks for reporting!

**Comment by sbeyer** [comment]
Wow, @mehalter ... you're always replying within seconds, how do you do that? :D
Thanks for your help! If I wasn't choosing AstroVim (or AstroNvim now) because of its basic feature set and philosphy, I would have chosen it for the quick an open help on GitHub.

Now to the topic again: I chose to add
```lua
vim.api.nvim_del_augroup_by_name("dashboard_settings")
```
only to my polish function, but not all the copy-and-pasted code with the changed `laststatus` setting. The only downside with my config is an empty grey-ish statusline on the dashboard (as can be seen in the screenshot). I really don't care about that.

![image](https://user-images.githubusercontent.com/143889/164331038-3637858e-cd92-40f0-917a-6b695029e85c.png)

**Comment by mehalter** [comment]
Awesome! Glad that was able to help!
