### ISSUE TITLE
Fail to load core.autocmds

### ISSUE THREAD

**Issue by ransomsec** [AstroNvim/AstroNvim#323]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [ ] `:PackerSync`

- [ ] `:AstroUpdate`

**Describe the bug**
I am opening AstroNvim, then they give a fail to load error, on init.lua package:25 "Failed to load core.autocmds"

**To Reproduce**
1. Open AstroNvim
2. See error

**Expected behavior**
Simle Open AstroNvim dashboard, but it's not.

**Screenshots**
If applicable, add screenshots or recording ([Asciinema](asciinema.org)) to help explain your problem.

**Additional context**

**See ScreenShot**
![nvim-error](https://user-images.githubusercontent.com/83533000/164364774-84a4f773-2356-421a-9ab3-1f29365df677.jpg)

**Comment by mehalter** [comment]
I looks like you are using Neovim <0.7. Currently AstroNvim only supports version 0.7+. Please see the README and Documentation for more information

**Comment by mehalter** [comment]
Duplicate of #313
