### ISSUE TITLE
Occasional problems running :PackerSync

### ISSUE THREAD

**Issue by Chaz6** [AstroNvim/AstroNvim#324]
As I understand it, to keep AstroNvim up to date, I should regularly run `:AstroUpdate` and `:PackerSync`. I have not modified my installation in any way aside from installing lsp providers. Every now and then there will be an error running `:PackerSync` which does not go away, for example:-

```
✗ Failed to update nvim-neo-tree/neo-tree.nvim
 Errors:
   fatal: Not possible to fast-forward, aborting.
   ada6a3d
```

What can I do when this happens?

**Comment by mehalter** [comment]
Hopefully we have fixed this with this commit recently: https://github.com/AstroNvim/AstroNvim/commit/ae8fe46d5854c2dc9ebb3192328aa6ea6a80e976

Basically sometimes the neo-tree developers do rebasing on the repo to keep things clean but it means doing `git pull` won't work. If you run into this you can `cd` to the neo-tree installation folder. By default it should be something like

```
cd ~/.local/share/nvim/site/packer/pack/opt/neo-tree.nvim
```
or something like that. Once you have located that folder you can run `git pull --rebase` to make git pull the changes.

**Comment by mehalter** [comment]
Oh actually, maybe we need to remove the `--ff-only` flag from the git pull..... Sorry 😅

**Comment by Chaz6** [comment]
Great thank you!

**Comment by itschip** [comment]
Current behavior:
![WindowsTerminal_xzDoTR2Tv6](https://user-images.githubusercontent.com/59088889/164478859-f78dc739-3d1f-419e-b3d3-7568984b2e64.png)

Should I just locate neo-tree as state above and yeet it?

**Comment by mehalter** [comment]
@itschip it looks like packer got into a really weird situation. I would locate those plugins in your `~/.local/share/nvim/site` folder and then do `git reset --hard origin/master` to get them back on track. Let me know if this sort of behavior persists :(

**Comment by itschip** [comment]
@mehalter it seems like astrovim tries to pull 'master', but its been renamed to 'main'

**Comment by itschip** [comment]
Alright, I just deleted both toggleterm and bufferline completely, and ran PackerSync, that did the trick, weird but ok

**Comment by mehalter** [comment]
sorry for the confusion!

**Comment by itschip** [comment]
> sorry for the confusion!

No worries :) Thanks
