### ISSUE TITLE
Remapping Keybinds in AstroVim

### ISSUE THREAD

**Issue by Korokoukousei** [AstroNvim/AstroNvim#331]
I would like to change 2 keybinds in my init file.
noremap <C-C> "+y
noremap <C-V> "+p
I could not find the init.vim file and I do not know what to put in my init.lua file.

**Comment by mehalter** [comment]
could you describe clearer what you are looking for?  what do you want the bindings to do? Are you trying to remap a binding that already exists or just create a new binding?

**Comment by Korokoukousei** [comment]
@mehalter I use a nvim client called NeoVide, It does not support keybinds like Ctrl + Shift + V to paste and the respective copy command for most terminals.
I want to remap Ctrl + V to paste and Ctrl + C to copy.
(The nvim commands to copy and paste from system keyboard are +y and +p respectively right?)

**Comment by mehalter** [comment]
AstroVim is currently set up to join the yank clipboard and the system clipboard. Could you please try copying something for instance in the browser with highlight + ctrl-c, then go to AstroVim and just do `p` and see if it pastes what you copied. Also vice versa, try yanking something with `yy` and then go somewhere else and do ctrl-p and see if it pastes. @Korokoukousei

**Comment by Korokoukousei** [comment]
Nope this does not work, it may be because im using NeoVide as my nvim client. Copying something from somewhere and hitting p does not paste from the system clipboard.
