### ISSUE TITLE
error on find words

### ISSUE THREAD

**Issue by convers39** [AstroNvim/AstroNvim#332]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x] `:PackerSync`
- [x] `:AstroUpdate`

**Describe the bug**

The search words function is not working, when I try to search a word via space -> f -> w and enter something, it shows an error message on the status bar, and nothing on the search results. 

**To Reproduce**
1. Go to anyfile
2. Click on space -> f -> w
3. See error on status bar

**Expected behavior**
Search words properly

**Screenshots**
<img width="1620" alt="image" src="https://user-images.githubusercontent.com/42597395/164729410-786f34fd-0842-4766-bb29-294067d9b482.png">

**Additional context**

**Comment by mehalter** [comment]
@convers39 can you please run `:messages` to see what the error is?

**Comment by mehalter** [comment]
Also what operating system are you on?

**Comment by convers39** [comment]
@mehalter thanks for following up

Im using macOS 12.2.1.

Here are the messages:

```
[telescope] [WARN  23:51:40] ...pack/packer/opt/telescope.nvim/lua/telescope/pickers.lua:483: Finder failed with msg:  .../site/pack/packer/opt/telescope.nvim/lua/telescope/_.lua:295: rg: Executable n
ot found
[telescope] stack traceback:
[telescope] ^I.../site/pack/packer/opt/telescope.nvim/lua/telescope/_.lua:295: in function 'convert_opts'
[telescope] ^I.../site/pack/packer/opt/telescope.nvim/lua/telescope/_.lua:17: in function 'new'
[telescope] ^I.../site/pack/packer/opt/telescope.nvim/lua/telescope/_.lua:64: in function 'spawn'
[telescope] ^I...elescope.nvim/lua/telescope/finders/async_job_finder.lua:49: in function 'finder'
[telescope] ^I...pack/packer/opt/telescope.nvim/lua/telescope/pickers.lua:479: in function <...pack/packer/opt/telescope.nvim/lua/telescope/pickers.lua:478>
[telescope] ^I[C]: in function 'pcall'
[telescope] ^I...pack/packer/opt/telescope.nvim/lua/telescope/pickers.lua:478: in function <...pack/packer/opt/telescope.nvim/lua/telescope/pickers.lua:428>
```

**Comment by mehalter** [comment]
Ah thanks for this, I completely miswrote the docs :joy: [ripgrep](https://github.com/BurntSushi/ripgrep) is a necessary dependency for live_grep with Telescope: https://github.com/nvim-telescope/telescope.nvim#suggested-dependencies

I put the wrong thing in the documentation.... sorry. I'll update the README now!

That's why it was saying the command `rg` was not found on the system.
