### ISSUE TITLE
Specifying `let` and autocmd in init.lua

### ISSUE THREAD

**Issue by trankchung** [AstroNvim/AstroNvim#338]
How do I make these settings happen in `init.lua`?

```
autocmd BufRead,BufNewFile *.hcl set filetype=terraform
let g:terraform_align=1
let g:terraform_fmt_on_save=1
```

Thanks

**Comment by mehalter** [comment]
There is an autocommand example in the [user_example](https://github.com/AstroNvim/AstroNvim/blob/f7d87bf55afaacc0a187b14da5b85d5da79d82be/lua/user_example/init.lua#L180)

Examples of setting global variables can be found in this Lua guide: https://github.com/nanotee/nvim-lua-guide#using-meta-accessors-1

All of this should go in the polish function
