### ISSUE TITLE
Why the search icon is a unreadable code?

### ISSUE THREAD

**Issue by LittleSheep2Code** [AstroNvim/AstroNvim#340]
I use fresh install for AstroNvim. When I open the dashboard or telescope, the all icon is good, but the search icon just like a "question"

I use JetBrains Mono Nerd Font and iTerm + Tmux

How did I can fix this?

<img width="907" alt="Dashboard" src="https://user-images.githubusercontent.com/56875315/164874855-ec63a2b5-84bc-491d-8597-d433ffc500a3.png">

**Comment by bryant-the-coder** [comment]
Change your font

**Comment by LittleSheep2Code** [comment]
Change font to what? I already use Nerd Font

**Comment by kabinspace** [comment]
Can you try changing your terminal? We don't recommend iterm for using AstroNvim as it is mentioned in the requirement section. How about trying it with something like iterm2 or a different terminal

**Comment by LittleSheep2Code** [comment]
emmm, it works in Alacitty... Ok, it fine.
