### ISSUE TITLE
Adding already installed LSP to lspconfig required list

### ISSUE THREAD

**Issue by Multichaos** [AstroNvim/AstroNvim#343]
Hi everyone,

Sorry if this was a dumb question, but I couldn't find anything in the documentation about it. I already have pyright and clangd installed on my system and I just wanted to add this to the cmp configuration like in their documentation:

require('lspconfig')['<YOUR_LSP_SERVER>'].setup {
    capabilities = capabilities
  }
  
Is there a way to do this? If I install through :LSPInstall will it override my current versions?
  
Thank you in advance!

**Comment by datamonsterr** [comment]
I believe in in lsp section inside `user/init.lua`
```lua
["server-settings"] = {
      clangd = {
      },
      pyright = {
      }
}
```

**Comment by mehalter** [comment]
@Multichaos thanks for this question! I don't think there is an easy way to do this and still get access to the `on_attach` function we are creating as well as the `capabilities` that we set up. I opened a PR that adds this feature!

**Comment by mehalter** [comment]
With the new PR you could set this up like I described in the PR itself. In your case if you aren't customizing anything in particular in each server you can also do something like this to easily add both `pyright` and `clangd` with the built in `on_attach` function and `capabilities`:

```lua
return {
  lsp = {
    setup = function(on_attach, capabilities)
      for _, lsp in pairs { "pyright", "clangd" } do
        require("lspconfig")[lsp].setup {
          on_attach = on_attach,
          capabilities = capabilities,
        }
      end
    end,
  },
}
```

**Comment by Multichaos** [comment]
Wow thank you all for the quick replies and PRs! I'll test it tonight when I get a chance will let you know how it goes!

**Comment by Multichaos** [comment]
Sorry didn't mean to close! Thank you everyone for the quick replies and PRs! I'll make sure to test tonight and will post any issues. Thank you again!

**Comment by mehalter** [comment]
@Multichaos I just realized while evaluating my new PR that this functionality is actually already available without the PR. You can actually just as easily configure the LSP config stuff from the `polish function. Instead of the `init.lua` code I sent before could you try doing this instead:

```lua
return {
  polish = function()
    local lsp_avail, lspconfig = pcall(require, "lspconfig")
    if lsp_avail then
      local handlers = require "configs.lsp.handlers"
      for _, lsp in pairs { "pyright", "clangd" } do
        lspconfig[lsp].setup {
        on_attach = handlers.on_attach,
        capabilities = handlers.capabilities,
        }
      end
    end
  end,
}
```

**Comment by mehalter** [comment]
I do need to add an example of this in the documentation though

**Comment by mehalter** [comment]
@Multichaos I just updated the docs with this information: https://astronvim.github.io/recipes/manual_lsp

**Comment by mehalter** [comment]
@Multichaos some recent changes to `nvim-lsp-installer` have forced us to reconsider the way we set up our lsp configuration stuff and this has actually made it exponentially easier for you to set up LSP servers without installing them with `nvim-lsp-installer`! Check out the link I sent above for a detailed explanation of these. Basically instead of the code I sent before you can just run

```lua
return {
  lsp = {
    servers = {
      "pyright",
      "clangd"
    }
  }
}
```
