### ISSUE TITLE
Show Neotree on startup

### ISSUE THREAD

**Issue by trankchung** [AstroNvim/AstroNvim#344]
Hi,

How do I tell AstroNvim to show Neotree on startup?

Thanks,

**Comment by datamonsterr** [comment]
create an autocommand in the polish function inside `user/init.lua`

**Comment by kabinspace** [comment]
@trankchung For that you need to put the given autocommands in your `nvim/lua/user.init.lua` inside polish function which is located [here](https://github.com/AstroNvim/AstroNvim/blob/e0dbb02b42ef91e533597d64ec833f2c692bf6f2/lua/user_example/init.lua#L187)
```lua
    vim.api.nvim_create_autocmd("VimEnter", {
      command = "set nornu nonu | Neotree toggle",
    })
    vim.api.nvim_create_autocmd("BufEnter", {
      command = "set rnu nu",
    })
```

**Comment by trankchung** [comment]
@kabinspace Thank you very much.

**Comment by trankchung** [comment]
@kabinspace Would you able to show me how to do the below in Lua? I've tried for several days but unable to get it to work. Thanks in advance.

`autocmd VimEnter * if argc() == 0 && !exists('s:std_in') | Neotree toggle | endif`

**Comment by mehalter** [comment]
@trankchung you can do something like this:

```lua
    vim.api.nvim_create_augroup("neotree", {})
    vim.api.nvim_create_autocmd("VimEnter", {
      desc = "Open Neotree automatically",
      group = "neotree",
      callback = function()
        if vim.fn.argc() == 0 and not vim.fn.exists "s:std_in" then
          vim.cmd "Neotree toggle"
        end
      end,
    })
```

**Comment by trankchung** [comment]
@mehalter Thank you very much.

**Comment by CaptainJack42** [comment]
This doesn't work for me at all when using `VimEnter`. When using `UiEnter` it does work, however i had to omit `and not vim.fn.exists "s:std_in"`.

Just leaving this here in case anyone stumbles upon the same issue.

Here's what i used to make it work:

```lua
    vim.api.nvim_create_augroup("neotree", {})
    vim.api.nvim_create_autocmd("UiEnter", {
      desc = "Open Neotree automatically",
      group = "neotree",
      callback = function()
        if vim.fn.argc() == 0 then
          vim.cmd "Neotree toggle"
        end
      end,
    })
```

**Comment by mehalter** [comment]
Very interesting @CaptainJack42 couple you please describe your set-up? What version of Neovim are you using? Are you using a terminal or an GUI program? What operation system? I ask because when I look at the list of available events `UIEnter` is not an option so I'm curious where this is coming from 🤔

**Comment by CaptainJack42** [comment]
@mehalter 
I found `UiEnter` [here](https://neovim.io/doc/user/autocmd.html#UIEnter) (the official nvim documentation for autocmd)

For my setup:
OS: Arch with i3 as wm
nvim: version 0.7.2
I'm currently transitioning to [neovide](https://github.com/neovide/neovide), but had the same problem when running inside a Terminal (Alacritty in my case)

**Comment by mehalter** [comment]
Ah I see I definitely had it in my head that that list was alphabetical smh that's a really annoying thing about the docs haha thanks for the link!

**Comment by mehalter** [comment]
@CaptainJack42 could you explain what issue you were having before as well with VimEnter?

**Comment by CaptainJack42** [comment]
> @CaptainJack42 could you explain what issue you were having before as well with VimEnter?

Well it just didn't do anything^^

**Comment by mehalter** [comment]
Interesting. Do you get the same results with stable AstroNvim? I wonder if it's a breaking change with Neotree causing this. I'll look into what issues could be happening and trying to replicate it early next week. UiEnter looks like a better option anyway.

**Comment by CaptainJack42** [comment]
> Interesting. Do you get the same results with stable AstroNvim? I wonder if it's a breaking change with Neotree causing this. I'll look into what issues could be happening and trying to replicate it early next week. UiEnter looks like a better option anyway.

Yep, same result. `UiEnter` works, but `VimEnter` doesn't.

**Comment by mehalter** [comment]
oh @CaptainJack42 I believe it should be BufEnter. That's what we have in AstroNvim by default. Not VimEnter.

**Comment by mehalter** [comment]
So is the default behavior not working for you?

**Comment by mehalter** [comment]
Here is the `autocmd` that is included by default with AstroNvim. It is a bit different than what is on this issue: 

https://github.com/AstroNvim/AstroNvim/blob/d32306034a0f351b564d180242c5091d77307170/lua/core/autocmds.lua#L89-L99

**Comment by CaptainJack42** [comment]
I'll check tomorrow, and also try the `BufEnter` event. 

I have however since than discovered the session manager and decided I like it better than going through neotree to my projects and since neotree blocks hotkeys while active I've disabled the autocmd again ^^. So there's no need for you to waste time with this because of me, it also worked perfectly when using the `UiEnter` event.

However I'm happy to help out if you want to figure this out.

**Comment by mehalter** [comment]
Yeah I guess the main thing @CaptainJack42 is that this autocommand is built in. So you shouldn't have to do or add anything 😅 hopefully you can report back some more details as to what might be going on. Are you adding these autocommands to your config? If so there might be conflicts with the default behavior which is causing weirdness

**Comment by mehalter** [comment]
So what version of AstroNvim are you using?

**Comment by CaptainJack42** [comment]
Ah now i see and i think i also see the misunderstanding.

When starting nvim with `nvim /path/to/some/dir` neotree opens on startup, but i guess i rarely did that. I either opened a file directly or just `cd` somewhere and than open nvim with just `nvim`, or now when using neovide, just open it in my home directory and load a session or open neotree from the landing page (that's what i was trying to automate with the autocmd, hence the `if vim.fn.argc() == 0` made sense to me, although i have no idea if that even corresponds to the arg count nvim was invoked with, i just assumed it would).

Yes i'm adding these autocmds to the `lua/user/init.lua` inside the `polish` function. I'm using AstroNvim v1.8.1-15-gd323060 .

On another note, i just noticed some weird behavior here, when opening nvim with `nvim /path/to/some/dir`. At first it's pretty normal i get neotree in fullscreen, once i choose to open a file and swap back to neotree (or in that case i'd expect it to open as a sidebar), with either `Space-e` or `:NeoTree [toggle]` it opens in fullscreen again and when trying to open a file with `o` it says `E21: Cannot make changes, 'modifiable' is off` and when trying to toggle a node with `Space` it says:

```
E5108: Error executing lua ...te/pack/packer/opt/which-key.nvim/lua/which-key/view.lua:52: Window was closed immediately
stack traceback:
        [C]: in function 'nvim_open_win'
        ...te/pack/packer/opt/which-key.nvim/lua/which-key/view.lua:52: in function 'show'
        ...te/pack/packer/opt/which-key.nvim/lua/which-key/view.lua:262: in function 'on_keys'
        ...te/pack/packer/opt/which-key.nvim/lua/which-key/view.lua:226: in function 'open'
        ...te/pack/packer/opt/which-key.nvim/lua/which-key/init.lua:48: in function 'show'
        /home/rick/.config/nvim/lua/configs/which-key.lua:7: in function 'show'
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue
```

**Comment by mehalter** [comment]
@CaptainJack42 yeah the last paragraph is a known bug currently opened in the issues. That one is not present in AstroNvim stable luckily because it is because of some recent code I pushed that is a little buggy it looks like.

I understand now where the confusion is with your original comment. Thanks for explaining and dropping a better autocommand for people who want this behavior !
