### ISSUE TITLE
user_example | Mapping key bindings inside the polish function have no effect?

### ISSUE THREAD

**Issue by GiorgosXou** [AstroNvim/AstroNvim#349]
*why this:*
https://github.com/AstroNvim/AstroNvim/blob/e5f407a8a68671791bf4dab97e90f4a06590cb41/lua/user_example/init.lua#L177
*when already:*
https://github.com/AstroNvim/AstroNvim/blob/e5f407a8a68671791bf4dab97e90f4a06590cb41/lua/core/mappings.lua#L75

**Also**, it seems  as if no `map(...)` works inside the [`polish`](https://github.com/AstroNvim/AstroNvim/blob/e5f407a8a68671791bf4dab97e90f4a06590cb41/lua/user_example/init.lua#L170) function *(or something i'm doing wrong)*

***PS.** I just want to add my custom keybindings like i did in previous versions *(before the rebranding)**

**Comment by GiorgosXou** [comment]
Am I not supposed to add my custom key-bindings there?

**Comment by mehalter** [comment]
That is there in the `user_example/init.lua` just to act as an example on how to set a key mapping. You can remove it if you do not want to use it. We didn't want the default bindings to change on the act of creating a user configuration file with the example. Also setting bindings in the `polish` function should be working. Could you please link or provide your current `init.lua` and I can take a look?

**Comment by GiorgosXou** [comment]
It is the same `user_example/init.lua` file just like it is in the repo, the only difference is that i've added *(just like I had in the previous version [before the rebranding])* 2 extra keybindings inside the polish: ` map("i", "<C-s>", "<ESC>:w!<CR>i")` and `map("i", "<C-w>", "<ESC>bd<CR>")` *(which they where in the form of  `map("i", .., .., opts)` before the update)*

* [`user_example/init.lua`](https://pastebin.com/7Wcpbvrb)

**Comment by mehalter** [comment]
Did you create a `user` folder and put your `init.lua` file there or are you editing the file in the `user_example` folder?

**Comment by GiorgosXou** [comment]
just edited

**Comment by mehalter** [comment]
Ah, I see. By default AstroNvim doesn't come with a user configuration folder so that it doesn't create merge conflicts in your clone. So the `user_example` folder is just an example, it is not used or sourced at all. Please follow the documentation for setting up a user configuration folder: https://astronvim.github.io/configuration/manage_user_config
