### ISSUE TITLE
Show full info in hover (definition hover)

### ISSUE THREAD

**Issue by grech-ca** [AstroNvim/AstroNvim#350]
Is it possible to show the contents of interface and other things?

<img width="515" alt="Screenshot 2022-04-25 at 15 33 19" src="https://user-images.githubusercontent.com/54347665/165089723-5c07899b-0ca5-4185-8361-8e4492cfc931.png">

**Comment by convers39** [comment]
That would be a nice feature. BTW how do you show the tooltip manually?

**Comment by mehalter** [comment]
@grech-ca the information provided to the hover box is given by the language server. There isn't anything on the AstroNvim side that can help improve this. I would look into if there are any features to the language server you are using to improve this or check out other language servers. You can do `gi` to go to the implementation or `gd` to go to the definition (lsp bindings) and then use `ctrl-o` to quickly go back to our last location before moving (normal standard vim binding)

@convers39 if you are asking how to open the hover it is done here with `K`. This is meant to extend the default `K` functionality of vim which by default just searches `man` pages so it's natural in the LSP stuff to use it to get more information on a variable or symbol

**Comment by grech-ca** [comment]
> @grech-ca the information provided to the hover box is given by the language server. There isn't anything on the AstroNvim side that can help improve this. I would look into if there are any features to the language server you are using to improve this or check out other language servers. You can do `gi` to go to the implementation or `gd` to go to the definition (lsp bindings) and then use `ctrl-o` to quickly go back to our last location before moving (normal standard vim binding)
> 
> @convers39 if you are asking how to open the hover it is done here with `K`. This is meant to extend the default `K` functionality of vim which by default just searches `man` pages so it's natural in the LSP stuff to use it to get more information on a variable or symbol 

Got it, thank you!

**Comment by lcoder** [comment]
> That would be a nice feature. BTW how do you show the tooltip manually?

`<K>`

**Comment by ersinakinci** [comment]
> > That would be a nice feature. BTW how do you show the tooltip manually?
> 
> `<K>` Hover symbol details
> 
> <img alt="image" width="1414" src="https://private-user-images.githubusercontent.com/5225853/239458693-6a772d28-8889-4650-8e09-4dbfb9631c22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4MTI2NTgsIm5iZiI6MTcwODgxMjM1OCwicGF0aCI6Ii81MjI1ODUzLzIzOTQ1ODY5My02YTc3MmQyOC04ODg5LTQ2NTAtOGUwOS00ZGJmYjk2MzFjMjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjRUMjIwNTU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmFmNTM1MmM4ZmE2ZjkyZGRmOTk1MmI0OTQ5OGQ3MjVhNWI1NjhkOTRhNjc4NzczZjEzYmQ5OGUzNzA0NzJjYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8pzfmeUmeXY460rmFmUaLhBzMG6vVf0-l3SGFZqiZ9k">

For anyone wondering how to pull up that amazing key maps search, it's `<Space>fk`
