### ISSUE TITLE
Would it be possible to introduce a Neovim-Version awareness?

### ISSUE THREAD

**Issue by florianb** [AstroNvim/AstroNvim#357]
Hello and thank you very much for this project, i recently migrated my former Ale based configuration to AstroNvim and it was a pleasure to use it.

Unfortunately since the last update it's broken because the Neovim update to 7 hasn't shipped yet to Ubuntu and as you can see it may pass a while until it will come: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1010158

I wonder if it would be possible to ship AstroNvim in a Neovim version aware manner? I wouldn't mind if i am not using the latest AstroNvim as long as Neovim just doesn't throw dozens of errors at me and i wouldn't have to patch the update process.

**Comment by mehalter** [comment]
@florianb we have tagged a version of AstroNvim before we made the v0.7 changes. So you can run the following command:

```
git -C ~/.config/nvim checkout nvim-0.6
```

The problem with this is the plugins that we are using have also begun dropping <0.7.0 support and we have not tagged them to be pinned so you will need to do this if you want to use it before 0.7. this managing of multiple versions of plugins is the reason we are not supporting a multiple version AstroNvim at least while Neovim is still in beta.

**Comment by florianb** [comment]
Thanks a lot @mehalter  - that's absolutely understandable. Sorry for the noise. :cookie:
