### ISSUE TITLE
Problem installing language server for JS/TS

### ISSUE THREAD

**Issue by Korokoukousei** [AstroNvim/AstroNvim#363]
![image](https://user-images.githubusercontent.com/70006643/165567301-b53b02bc-1d97-457d-bc9c-06e405e50cbc.png)
![image](https://user-images.githubusercontent.com/70006643/165567457-771eb0df-6846-446c-8e19-cf9e4825c5ef.png)

This is the traceback and an error notif
I need help to install language servers for typescript/javascript, but it throws an error (I also need help picking which, Im working in node)

**Comment by mehalter** [comment]
Please update AstroNvim to the latest version and restart

**Comment by Korokoukousei** [comment]
Update failed, please try pulling manually.
I dont know much of github, how do i pull without losing my configs?

**Comment by mehalter** [comment]
Have you made changes to the base installation outside of the `user/` folder? If so could you please let us know what you needed to change. This shouldn't be necessary with our configuration options

**Comment by mehalter** [comment]
What changes did you make to the dashboard? These changes should be able to be done in your user folder

**Comment by Korokoukousei** [comment]
I changed the dashboard to be this as a quick hack fix
![image](https://user-images.githubusercontent.com/70006643/165576919-9ec8e5e8-afc9-4d6d-9eb0-d5c9b8c2e203.png)

**Comment by mehalter** [comment]
You can move the setting of `vim.g.dashboard_custom_header` in your user/init.lua` file in the `polish` function

**Comment by Korokoukousei** [comment]
Got it, ill yank lines from here and put them there. How do I update manually?

**Comment by mehalter** [comment]
Once you have moved all of the changes that you have made to the core files to your user folder. You can run `git reset --hard origin/main` to reset it and be able to pull again. We don't track the `user/` at all so it won't overwrite anything in the user folder
