### ISSUE TITLE
Using AstroNVim on Windows, font errors

### ISSUE THREAD

**Issue by aneeshbhave** [AstroNvim/AstroNvim#365]
I'm using the JetBrains Mono Nerd-Compatible font. It works just fine in Windows Terminal (the new preview one) but somehow all text becomes italics when neovim is launched. How do I fix this?

**Comment by aneeshbhave** [comment]
SideNote: The same happens on my Linux nvim instance as well.

**Comment by aneeshbhave** [comment]
The terminal does not use an italic font by default. Im using the windows terminal (new windows 11 one) and the default terminal on Ubuntu

**Comment by kabinspace** [comment]
Can you show me how they look at your current terminal?

**Comment by aneeshbhave** [comment]
![image](https://user-images.githubusercontent.com/104488537/166160043-e32250aa-b074-434a-8526-af6cd8a86042.png)
A basic hello world script, many variable names as well as the file name is capitalized, It should not be this way.

**Comment by aneeshbhave** [comment]
(Used none to show you params and variable names are italicized too, ik its a syntax error)

**Comment by mehalter** [comment]
@aneeshbhave what colorscheme are you using? This is probably something set by the colorscheme
