### ISSUE TITLE
How to enable tabnine in autocompletions

### ISSUE THREAD

**Issue by MisterBianco** [AstroNvim/AstroNvim#367]
I am working to get [tabnine](https://github.com/tzachar/cmp-tabnine) configured in astrovim and have gotten the plugin installed and the install script executed.

I added this line after getting the plugin installed in: lua/core/plugins.lua

```
...
{
      'tzachar/cmp-tabnine',
      requires = 'hrsh7th/nvim-cmp',
      config = function()
        require("configs.tabnine").config()
      end,
    },
...
```

lua/configs/cmp.lua
```
cmp.setup(require("core.utils").user_plugin_opts("plugins.cmp", {
      preselect = cmp.PreselectMode.None,
      ...
      sources = {
        { name = "cmp_tabnine" },
      },
      ...
````

I also added a config file that should be read:

lua/configs/tabnine.lua
```
local M = {}

function M.config()
    local status_ok, npairs = pcall(require, "nvim-autopairs")
    if status_ok then
        local tabnine = require('cmp_tabnine.config')
        tabnine:setup({
	        max_lines = 1000;
        	max_num_results = 20;
	        sort = true;
	        run_on_every_keystroke = true;
	        snippet_placeholder = '..';
	        ignored_file_types = { -- default is not to ignore
		        -- uncomment to ignore in lua:
		        -- lua = true
	        };
	        show_prediction_strength = false;
        })
    end
end

return M
```

I performed the signin using the :CmpTabnineHub command but am unsure if I am missing something else as my completions have not changed.

**Comment by mehalter** [comment]
Please checkout the documentation for adding sources to `cmp`: https://astronvim.github.io/recipes/cmp#add-more-sources

You can add the source in the configuration function of the `cmp-tabnine` plugin with a helper function we have in the core utilities. This also lets you set priority of the completion compared to the other sources.

**Comment by mehalter** [comment]
This is instead of modifying the `cmp` setup call like you showed in `user/configs/cmp.lua`

**Comment by mehalter** [comment]
also wait are you doing this by modifying the source code or in a user/ folder?

**Comment by mehalter** [comment]
@MisterBianco this should be a complete `user/init.lua` file for setting up the tabnine plugin as well as the cmp source:

```lua
return {
  plugins = {
    init = {
      {
        "tzachar/cmp-tabnine",
        requires = "hrsh7th/nvim-cmp",
        run = "./install.sh",
        config = function()
          local tabnine = require "cmp_tabnine.config"
          tabnine:setup {
            max_lines = 1000,
            max_num_results = 20,
            sort = true,
            run_on_every_keystroke = true,
            snippet_placeholder = "..",
            ignored_file_types = {},
            show_prediction_strength = false,
          }
          require("core.utils").add_cmp_source("cmp_tabnine", 1000)
        end,
      },
    },
  },
}
```

**Comment by MisterBianco** [comment]
I am a goof ball and should have done more reading to understand the architecture of the plugin system. the user folder with all its entrypoints is a fantastic design. Appreciate the init file I can riff off that. 👍🏼
