### ISSUE TITLE
Lazy loading plugins

### ISSUE THREAD

**Issue by Johnsiras** [AstroNvim/AstroNvim#369]
Hello! Just switched from nvchad to astronvim cause nvchad causes more problems.. anyways this was an awesome repo!

I just started to configure the config and install some plugins, the problem is when i install a new plugin it increases my startup time and i want my plugins to be lazy loaded...

Is there anyway to lazy load or how i can lazy load it? Thx in advance, beginner here.

**Comment by Johnsiras** [comment]
![image](https://user-images.githubusercontent.com/102006493/165660975-c870dd1b-2fb1-473f-a3a0-31e22f37af30.png)

**Comment by mehalter** [comment]
Take a look at the Packer documentation: https://github.com/wbthomason/packer.nvim for how to configure lazy loading. If you want to see examples you can check out the plugins that are configured in AstroNvim and how we do the lazy loading of our plugins: https://github.com/AstroNvim/AstroNvim/blob/main/lua/core/plugins.lua

I also do some lazy loading for most of the plugins in my own personal configuration and you can check that out as well as help guidance: https://git.mehalter.com/mehalter/AstroNvim_user/src/branch/master/plugins/init.lua

**Comment by mehalter** [comment]
basically the parts that say `module`, `command`, `event` are all part of when to lazy load the plugins

**Comment by Johnsiras** [comment]
Thx!
