### ISSUE TITLE
Anyway to disable Friendly Snippets and Schemastore plugins?

### ISSUE THREAD

**Issue by shripadk** [AstroNvim/AstroNvim#379]
I am currently disabling Friendly Snippets from the `core/plugins.lua` file, but would prefer to disable it from user config file. The reason being that it is currently buggy when it comes to Typescript JSX. Closing a JSX tag triggers a `foreach` snippet and messes up the code.

Also, I am noticing considerable slowness in Nvim ever since Friendly Snippets was added in v1.0. However, I still would like to use Lua Snip for custom snippets.

Just wanted an option to disable Friendly Snippets.

Also would like an option to disable Schemastore plugin.

Is it possible to disable these plugins without modifying the core plugins.lua file?

**Comment by mehalter** [comment]
This is possible but it is a little bit more advanced of a configuration than the basic adding of plugins since you also need to adjust the lazy loading of `LuaSnip` as well. The easiest way to do this is something like this in your `user/init.lua`:

```lua
return {
  plugins = {
    init = function(default_plugins)
      -- A table for your own plugins to load
      local my_plugins = {
        -- { "andweeb/presence.nvim" },
      }

      -- The default plugin table is indexable by the package github username/repository
      -- You can directly modify the default table
      default_plugins["rafamadriz/friendly-snippets"] = nil
      default_plugins["b0o/SchemaStore.nvim"] = nil
      default_plugins["L3MON4D3/LuaSnip"].after = "nvim-cmp"

      -- Finally  you will want to add the my_plugins table to the default table and return it
      return vim.tbl_deep_extend("force", default_plugins, my_plugins)
    end,
  },
}
```

**Comment by shripadk** [comment]
@mehalter Thank you so much!
