### ISSUE TITLE
formater for codes

### ISSUE THREAD

**Issue by mafakheri** [AstroNvim/AstroNvim#387]
hello.
editor is grater. tnx 
it's will be good if in the feature we have some formater for codes. some thing like perettier
thanks .

**Comment by mehalter** [comment]
This is actually already a feature and can be done with a user configuration! :)

Check out the documentation on how to set up a user configuration: https://astronvim.github.io/configuration/manage_user_config

Here is a minimal `user/init.lua` file that sets up just `prettier`:

```lua
return {
  ["null-ls"] = function()
    local status_ok, null_ls = pcall(require, "null-ls")
    if status_ok then
      local builtins = null_ls.builtins

      null_ls.setup {
        debug = false,
        sources = {
          builtins.formatting.prettier
        },
        on_attach = function(client)
          if client.resolved_capabilities.document_formatting then
            vim.api.nvim_create_autocmd("BufWritePre", {
              desc = "Auto format before save",
              pattern = "<buffer>",
              callback = vim.lsp.buf.formatting_sync,
            })
          end
        end,
      }
    end
  end,
}
```

**Comment by mehalter** [comment]
Here is a direct link to the documented section of the provided example user configuration in the repo: https://github.com/AstroNvim/AstroNvim/blob/362e4ae292b8bdb69802727345ea325c5758444d/lua/user_example/init.lua#L144-L180

**Comment by mafakheri** [comment]
thank you. I am new neovim user and honestly my first lang is not english :)) some times cant understand guide in document then i come here and ask Q.
sorry for silly Q.
