### ISSUE TITLE
Move to Alpha.nvim

### ISSUE THREAD

**Issue by mehalter** [AstroNvim/AstroNvim#388]
**Is your feature request related to a problem? Please describe.**
Dashboard.nvim is not actively developed, is slow on start up and it is also written in VimScript instead of Lua.

**Describe the solution you'd like**
We should move to [Alpha.nvim](https://github.com/goolord/alpha-nvim) as a more future proof solution and faster start up times.

**Additional context**
We will also need to update the autocommands for disabling the tabline and statusline when the "alpha" (dashboard) is open.

**Comment by ajboni** [comment]
Consider also adding https://github.com/Shatur/neovim-session-manager as suggested by Alpha readme

**Comment by mehalter** [comment]
Oh this is a great idea @ajboni since alpha has no concept of sessions and that plugin is probably better than the dashboards rudimentary idea of "sessions"

**Comment by mehalter** [comment]
I'll add this to #394
