### ISSUE TITLE
Disabling cursorline

### ISSUE THREAD

**Issue by elshize** [AstroNvim/AstroNvim#389]
Hi, great work on putting AstroNvim together!

I'd like to disable `cursorline`, which I'm doing now in `polish` function with:

```lua
set.cursorline = false
```

It works initially, but it switches right back on once I use telescope (which uses cursorline). I was wondering if there's a way around this?

If I can't easily configure it, is it possible to configure telescope to not use it either? I couldn't find a way to configure it, but I'm assuming there must be, though not sure if I can use it in the user config or would I need to modify the core astronvim code.

Any advice would be greatly appreciated. Thanks.

**Comment by mehalter** [comment]
We have some autocommands to control the `cursorline`: https://github.com/AstroNvim/AstroNvim/blob/362e4ae292b8bdb69802727345ea325c5758444d/lua/core/autocmds.lua#L9-L19

You can add this to your `polish` function to disable these commands:

```lua
vim.api.nvim_del_augroup_by_name "cursor_off"
```

**Comment by elshize** [comment]
Thanks a lot @mehalter!
