### ISSUE TITLE
SessionLoad does not restore buffers

### ISSUE THREAD

**Issue by ajboni** [AstroNvim/AstroNvim#395]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x ] `:PackerSync`
- [ x] `:AstroUpdate`
- [ x] restarted AstroNvim
- [ x] Neovim version >= 0.7.0

Problem: Session restores but buffers do not open. As  #394  exists maybe this is not worth exploring. 

To reproduce: 
1.Open a bunch of buffers,
2.`Leader` `Ss` 
3. restart nvim
4. `leader` `sl`

Notice no buffers were restored.

**Comment by mehalter** [comment]
Yeah we are going to replace this functionality with the new Alpha PR. I'll add the session manager you linked before and hopefully not will be more reliable. I'm going to go ahead and close this. I added a Todo to the new PR to add the session manager

**Comment by mehalter** [comment]
Actually I'm going to leave this open as it is a bug that still exists, but I'll mark the PR as fixing this.
