### ISSUE TITLE
Consider evaluating the inclusion of stickybuf.nvim

### ISSUE THREAD

**Issue by krishnakumarg1984** [AstroNvim/AstroNvim#404]
**Is your feature request related to a problem? Please describe.**
There is a small possibility of inadvertently opening a regular file in small windows such as the symbol-tree explorer `aerial.nvim`, which can appear squished.

**Describe the solution you'd like**
Consider using [`stickybuf.nvim`](https://github.com/stevearc/stickybuf.nvim) which is a companion plugin to `aerial.nvim` by the same author, to locking buffers to windows.

**Comment by mehalter** [comment]
I tested this and it does not seem to work as reliably as I would like to get it added as well as adding a decent amount of start up time for taking care of a very small possibility. I think for now I will keep `stickybuf` on my radar and keep up with their updates but not add it to AstroNvim. Thanks for the recommendation though!
