### ISSUE TITLE
In AstroNvim, how to prevent the auto-hiding of toggleterm terminal window upon leaving insert mode?

### ISSUE THREAD

**Issue by krishnakumarg1984** [AstroNvim/AstroNvim#405]
Let's say if we open a new toggle term floating terminal and run a bash command. When I leave the insert mode (using `<esc>, <C-C> or <C-[> ` with the intention of copying some output from the previous shell command, it automatically hides the terminal window!

How can we suppress this behaviour? I'd like to hide the terminal window only with an explicit call to ToggleTerm (e.g. with `C-\`).

**Comment by mehalter** [comment]
Please see #356

**Comment by krishnakumarg1984** [comment]
Ooh. That disables a lot of nice terminal mappings. Is there a way to just get rid of the hiding on insertleave mapping?

**Comment by mehalter** [comment]
You can just redefine the terminal mappings yourself in your `init.lua` function

```lua
return {
  polish = function()
    vim.api.nvim_del_augroup_by_name "TermMappings"
    vim.api.nvim_create_augroup("TermMappings", {})
    vim.api.nvim_create_autocmd("TermOpen", {
      desc = "Set terminal keymaps",
      group = "TermMappings",
      callback = function()
        vim.api.nvim_buf_set_keymap(0, "t", "jk", [[<C-\><C-n>]], { desc = "Terminal normal mode" })
        vim.api.nvim_buf_set_keymap(0, "t", "<C-h>", [[<C-\><C-n><C-W>h]], { desc = "Terminal left window navigation" })
        vim.api.nvim_buf_set_keymap(0, "t", "<C-j>", [[<C-\><C-n><C-W>j]], { desc = "Terminal down window navigation" })
        vim.api.nvim_buf_set_keymap(0, "t", "<C-k>", [[<C-\><C-n><C-W>k]], { desc = "Terminal up window navigation" })
        vim.api.nvim_buf_set_keymap(0, "t", "<C-l>", [[<C-\><C-n><C-W>l]], { desc = "Terminal right window naviation" })
      end,
    })
  end,
}
```

**Comment by krishnakumarg1984** [comment]
Yay! That works. Thank you so much for your support.

**Comment by krishnakumarg1984** [comment]
@mehalter This stopped working now. `<Esc>` does not take me back into the normal mode. At least, it does not hide the terminal. In short, `<Esc>` does nothing.

**Comment by mehalter** [comment]
You probably have something overriding something or changing something. I can confirm that on my configuration and a fresh installation with just the above code works accordingly.

**Comment by mehalter** [comment]
I would probably update this to use the new neovim 0.7 APIs. I think this is shorter and easier to read (inside the `polish` function):

```lua
    vim.api.nvim_create_augroup("TermMappings", { clear = true })
    vim.api.nvim_create_autocmd("TermOpen", {
      desc = "Set terminal keymaps",
      group = "TermMappings",
      callback = function()
        vim.keymap.set("t", "jk", [[<C-\><C-n>]], { desc = "Terminal normal mode", buffer = 0 })
        vim.keymap.set("t", "<C-h>", [[<C-\><C-n><C-W>h]], { desc = "Terminal left window navigation", buffer = 0 })
        vim.keymap.set("t", "<C-j>", [[<C-\><C-n><C-W>j]], { desc = "Terminal down window navigation", buffer = 0 })
        vim.keymap.set("t", "<C-k>", [[<C-\><C-n><C-W>k]], { desc = "Terminal up window navigation", buffer = 0 })
        vim.keymap.set("t", "<C-l>", [[<C-\><C-n><C-W>l]], { desc = "Terminal right window naviation", buffer = 0 })
      end,
    })
```

**Comment by mehalter** [comment]
Also you can just not put this in an autocommand and just do this:

```lua
    vim.api.nvim_del_augroup_by_name "TermMappings"
    vim.keymap.set("t", "jk", [[<C-\><C-n>]], { desc = "Terminal normal mode" })
    vim.keymap.set("t", "<C-h>", [[<C-\><C-n><C-W>h]], { desc = "Terminal left window navigation" })
    vim.keymap.set("t", "<C-j>", [[<C-\><C-n><C-W>j]], { desc = "Terminal down window navigation" })
    vim.keymap.set("t", "<C-k>", [[<C-\><C-n><C-W>k]], { desc = "Terminal up window navigation" })
    vim.keymap.set("t", "<C-l>", [[<C-\><C-n><C-W>l]], { desc = "Terminal right window naviation" })
```

**Comment by mehalter** [comment]
Honestly, I feel like we should just move these bindings outside of the autocommand and make it to where you can just delete specific bindings. That seems like it would be much easier and better.

**Comment by mehalter** [comment]
@krishnakumarg1984 I have a PR open (#462) so instead of all this code, just do `vim.keymap.del("t", "<esc>")` in your `polish` function.

**Comment by krishnakumarg1984** [comment]
Yup. That works.

Now, one important problem I have is the following. Consider this scenario:

 - Let's say in a floating terminal we switch to normal mode, scroll up a few screens to read a lengthy output from a command (say a LaTeX build output with 15 errors). 
 - After scrolling to the top of the build output, we notice three unrelated errors in the source code that need to be fixed in the first few lines of output. We decide to address the first error, and toggle the floating terminal to edit the LaTeX source code to fix it.
 - Now, we decide to fix the second issue, which is a warning from the compiler, and I wish to refer to the warning message now. Since the cursor was in normal mode near the first error, it is only a small jump from there, and I expect the toggling of terminal to take me very close to where I wish to be
 - However, the terminal toggle reveals that I am back in insert mode at the bottom i.e. the current shell prompt, and I have to annoyingly scroll screenfuls of content just to get back to the second issue. It becomes tedious to repeat this dance ad-infinitum.

Notice that, I do want to be in insert mode when opening toggle-term. However, I wish to respect my last mode that I left toggleterm when opening it up again. Any suggestions? Should I make a new issue for this?

**Comment by mehalter** [comment]
This is part of the `toggleterm` config:

```lua
return {
  plugins = {
    toggleterm = {
      start_in_insert = false
    }
  }
}
```

**Comment by krishnakumarg1984** [comment]
Ah no.
>Notice that, I **do want to be in insert mode** when opening toggle-term. However, I wish to **respect my last mode that I left** toggleterm when opening it up again.

**Comment by mehalter** [comment]
You should open an issue  with `toggleterm` and see if that is a feature. This is unrelated to AstroNvim as a whole.

**Comment by krishnakumarg1984** [comment]
Hmm,

I raised an issue on the [toggleterm github page](https://github.com/akinsho/toggleterm.nvim/issues/222). Looks like there was an already existing request for this. The author does not want to make the code for ToggleTerm complex by including state-preserving behavior.

Might be worth looking into [numToStr/FTerm](https://github.com/numToStr/FTerm.nvim) as an alternative,

**Comment by akinsho** [comment]
@krishnakumarg1984 this isn't really an accurate description of what I said in the issue. What I in fact said was that I maintain several plugins, so cannot jump on every feature request. If you or anyone else wants to help implement this feature since presumably you need it more than I do, please feel free to contribute
