### ISSUE TITLE
Do not hardcode SPC in the alpha dashboard textual descriptions 

### ISSUE THREAD

**Issue by krishnakumarg1984** [AstroNvim/AstroNvim#407]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0

**Describe the bug**
Currently, the alpha dashboard starter screen show mappings with descriptions hard-coded to `SPC`.

This shall be inconsistent with the actual mappings for those who have remapped their `<leader>` key to `,`, or back to `\` etc., and hence confuse them a lot.

**To Reproduce**
1. In the custom user file, set `vim.g.mapleader = "\\`.
2. Open nvim. The starter screen shows hardcoded mappings with SPC for telescope etc, which is inconsistent with the actual mappings used. 

**Expected behavior**
- Ideally, parse the current map leader and then convert this to string to display in alpha's start screen, or 
- maybe just display `leader` in lieu of `SPC`. (simpler)

**Comment by krishnakumarg1984** [comment]
@mehalter This is broken again today after pulling in the latest commits.

![image](https://user-images.githubusercontent.com/15239509/166492221-2aff9551-d38a-4d4c-9f70-2558171a4e20.png)

**Comment by mehalter** [comment]
@krishnakumarg1984  Ah sorry, I meant to comment back on this git issue to let you know. We have added a new, cleaner way to set vim options like `vim.opt.X` and `vim.g.X` in the `init.lua` file. If you use this method for setting your leader, then the dashboard is able to pick up on this when it generates and make those messages fit your exact configuration! Please check it out and see what you think!

Also this was mentioned in the new Announcements issue that I made today to make it easier for users to get these updates: https://github.com/AstroNvim/AstroNvim/issues/427#issuecomment-1116199769

Feel free to subscribe to this issue or check back on it every now and again!

**Comment by mehalter** [comment]
This is not considered a breaking change because it does not affect the functionality of the editor in any way. It is just a non-breaking improvement. Thanks for populating this issue though in case other users run into this :)
