### ISSUE TITLE
Do not set smartindent

### ISSUE THREAD

**Issue by krishnakumarg1984** [AstroNvim/AstroNvim#410]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0

**Describe the bug**
I am not a vim expert, but from the last 7 years of using it, I have come to understand that `smartindent` uses an old method for detecting the auto-indents (i.e. it was smart when circa vim 6 was released).  In the case of AstroNvim, I think the usage of the indent heuristic indent-o-matic plugin saves users, but those who disable it might feel the pain.

As a related issue, I have `set preserveindent` in my config, based on the advice (with cogent explanation that I have now forgotten) by some elder vimmer. Worth looking into?

These are my current indent settings for reference:
```
set.smartindent = false
set.autoindent = true
set.copyindent = true -- Copy the previous indentation on autoindenting
set.preserveindent = true
```

**Comment by mehalter** [comment]
I think for our given purposes with providing a default indent detection leaving `smartindent` is fine for users and users that encounter issues can easily modify the settings with their user config as you have done. Thanks for the suggestion though!

**Comment by krishnakumarg1984** [comment]
Hmm.. Normally (like in other cases), I'd absolutely agree that it's fine to let users tweak the config themselves in their own `init.lua`.

However, in this case, I'd respectfully disagree a bit strongly. First of all, `smartindent` is not set by default in either vim or neovim. I think it actively harms the indent patterns of non-C languages (perhaps saved here by indent-o-matic, but what if someone disables it?). 

In the case of AstroNvim, the config can be in an entirely different folder (`~/.config/astronvim/lua/user/init.lua`) vs rest of the default config code, and that can hamper visibility in understanding that a rogue setting was responsible for messed up indents. 

Any reasonable "nvim-distro" shouldn't encourage anti-patterns such as this. I shall try and dig up a reasonable source if you still feel that it should still be in the project's default. Once again, let me reiterate that I am respectfully disagreeing only on this minor point, while admiring the effort you've put in to get us this polished infrastructure framework.

**Comment by mehalter** [comment]
Okie doke, this is pretty sound. I will add the preserveindent and copyindent options since autoindent is default to true. See #414

**Comment by krishnakumarg1984** [comment]
Sorry that I was a bit pedantic on this one. But thank you so much for considering this! I won't push other minor fixes, I promise.

**Comment by krishnakumarg1984** [comment]
[Idiomatic vimrc tips: Do not use smartindent](https://www.reddit.com/r/vim/wiki/vimrctips#wiki_do_not_use_smartindent=)
>

> smartindent is an old script that was meant, when it was written, to be a "smart" complement to autoindent. Since then, most languages have either specific indentation functions or use cindent with specific options.
> 
> Generally, smartindent should not be used at all.
> 
> The following lines are usually enough to deal with indentation:
> 
> set autoindent
> filetype plugin indent on
> 
> autoindent is not strictly necessary but it's good to have it when working with plain text.

Some further links for posterity reference:

- https://stackoverflow.com/a/17105016
- https://stackoverflow.com/a/18415867
