### ISSUE TITLE
Auto install LSP on file type

### ISSUE THREAD

**Issue by trankchung** [AstroNvim/AstroNvim#412]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Currently I have to run `:LspInstall <server>` for each language that I want to have LSP supported. It would be nice if this is implemented so that it detects the file type and install the respective LSP.

**Additional context**
N/A

**Comment by trankchung** [comment]
@mehalter Do I have to specify all the LSP servers that I want in that `ensure_installed` table?

**Comment by mehalter** [comment]
Yes, automatically detecting based on filetype is not a good general approach because some people might not want LSP for all file types. Also in the cases where there are 2-3 language servers for a file type there is no way to make an intelligent decision on which one to install. For now we are just supporting more explicit definition in the configuration.

**Comment by trankchung** [comment]
I tried what you suggested above but it doesn't work. I read the repo's configuration and I added `automatic_installation = true` as well but still no dice. Any suggestion? Thanks a bunch.

**Comment by mehalter** [comment]
Have you updated to the latest code on AstroNvim? This is a new feature that's as added in the last week

**Comment by trankchung** [comment]
Yes. I did `:AstroUpdate` as well as removing `~/.config/nvim` and cloned it again.

```
$ git log
commit db1b310f9afd28670f61bf2c160165ffa12763f0 (HEAD -> main, tag: v1.2.0, origin/main, origin/HEAD)
Author: Micah Halter <micah@balena.io>
Date:   Mon May 2 10:59:03 2022 -0400
```

**Comment by mehalter** [comment]
`automatic_installation = true` automatically installs language servers that you have set up with `lspconfig`. What language servers have you added to your `ensure_installed`? Also just to check, have you made sure to update the plugins as well with `:PackerSync`?

**Comment by trankchung** [comment]
Yes. I did packer sync, packer update, all that. Sorry to bother. Below is what I have in my `ensure_installed`.

```
 ensure_installed = {
    "bash",
    "css",
    "dockerfile",
    "go",
    "hcl",
    "javascript",
    "json",
    "lua",
    "make",
    "markdown",
    "php",
    "python",
    "rego",
    "ruby",
    "sumneko_lua",
    "toml",
    "typescript",
    "vue",
    "yaml",
  },
```

**Comment by mehalter** [comment]
is this in your `treesitter.ensure_installed`? These are file types and not language servers. This should look something like:

```lua
 ensure_installed = {
    "bashls",
    "cssls",
    "dockerls",
    "gopls",
    "hcl", -- not sure about this one
    "eslint", -- there are a couple different options javascript, pick which one you want
    "jsonls",
    "cmake", -- not sure if this is what you want, not sure if there is another lsp for makefile
    "markdown", -- there isn't a very good lsp for markdown
    "phpactor", -- there is also psalm as an option for php not sure which is better
    "pyright", -- there is also pylsp for python, not sure which one you want
    "rego", -- not sure about this one
    "ruby", -- there is solargraph and sorbet, you will need to pick
    "sumneko_lua",
    "taplo",
    "tsserver", -- this also will service javascript so you probably don't need eslint and tsserver
    "volar",
    "yamlls",
  },
```

**Comment by mehalter** [comment]
I tried to fill each one out that you probably want, but you will need to make some decisions since there are so many LSP options (which is why selecting based on filetype is not a valid option)

**Comment by mehalter** [comment]
The available LSPs for installation with `nvim-lsp-installer` can be found here for reference: https://github.com/williamboman/nvim-lsp-installer#available-lsps

**Comment by trankchung** [comment]
Thanks for that @mehalter. I apologize for being dumb.
