### ISSUE TITLE
Change <leader>lS mapping

### ISSUE THREAD

**Issue by tomKPZ** [AstroNvim/AstroNvim#419]
With the switch to `aerial`, treesitter is now used for the symbols outline, so the binding should no longer reside in the LSP menu.

**Comment by mehalter** [comment]
Do you have any recommendations for a new place for this binding to live? I think we are trying to not deprecate old bindings for users that have developed muscle memory for where things live. It is still displaying symbols so I think `<leader>lS` is still a pretty good binding.

**Comment by tomKPZ** [comment]
Ok, makes sense to me.  In that case, lets stick with the `<leader>lS` binding.

**Comment by krishnakumarg1984** [comment]
I am happy with `leader ls` as well
