### ISSUE TITLE
Adding Paths to luansip

### ISSUE THREAD

**Issue by lawrencet149** [AstroNvim/AstroNvim#420]
Hi, 

I am trying to add custom snippets, but adding a path to the init.lua in luasnip section makes the snippets functionality stop working. I've followed the instructions/example in the recipe section of the documentation, but not having any success. 

Thank you,
Tony

**Comment by mehalter** [comment]
I have just tested this and it seems to be working. Did  you make sure to add the `package.json` file for enabling the snippets? Could you share your `init.lua` file and we can take a closer look?

**Comment by lawrencet149** [comment]
Thank you for the quick reply. Yes I added the package.json. init.lua contents below. For some reason I cannot attach it.

local fh = io.popen("hostname -s")
if fh ~= nil then
    vim.g.hostname = fh:read("*a")
    fh:close()
end
vim.g.vim_homedir = os.getenv("MYHOME")
print(vim.g.vim_homedir)

local options = {
    backup = false, -- creates a backup file
    cmdheight = 1, -- more space in the neovim command line for displaying messages
    completeopt = { "menuone", "noselect" }, -- mostly just for cmp
    conceallevel = 0, -- so that `` is visible in markdown files
    fileencoding = "utf-8", -- the encoding written to a file
    hlsearch = true, -- highlight all matches on previous search pattern
    ignorecase = true, -- ignore case in search patterns
    mouse = "", -- allow the mouse to be used in neovim
    pumheight = 10, -- pop up menu height
    showmode = false, -- we don't need to see things like -- INSERT -- anymore
    showtabline = 2, -- always show tabs
    smartcase = true, -- smart case
    smartindent = true, -- make indenting smarter again
    splitbelow = true, -- force all horizontal splits to go below current window
    splitright = true, -- force all vertical splits to go to the right of current window
    swapfile = false, -- creates a swapfile
    termguicolors = true, -- set term gui colors (most terminals support this)
    timeoutlen = 100, -- time to wait for a mapped sequence to complete (in milliseconds)
    undofile = true, -- enable persistent undo
    updatetime = 300, -- faster completion (4000ms default)
    writebackup = false, -- if a file is being edited by another program (or was written to file while editing with another program), it is not allowed to be edited
    expandtab = true, -- convert tabs to spaces
    shiftwidth = 4, -- the number of spaces inserted for each indentation
    tabstop = 4, -- insert 2 spaces for a tab
    cursorline = true, -- highlight the current line
    number = true, -- set numbered lines
    relativenumber = true, -- set relative numbered lines
    numberwidth = 4, -- set number column width to 2 {default 4}
    signcolumn = "yes", -- always show the sign column, otherwise it would shift the text each time
    wrap = false, -- display lines as one long line
    scrolloff = 8, -- is one of my fav
    sidescrolloff = 8,
    guifont = "monospace:h17", -- the font used in graphical neovim applications
    pyxversion = 3,
    list = true,
    smarttab = true,
    shiftround = true,
    softtabstop = 4,
    undodir = os.getenv("HOME") .. "/.cache/nvim/undodir/",
    history = 10000,
    undolevels = 10000,
    incsearch = true,
    autoindent = true,
    pastetoggle = "<F2>",
}

local colorscheme = "default_theme"
local theme_installed, _ = pcall(require, "darkplus")
if theme_installed then
    colorscheme = "darkplus"
end

local config = {
    -- Set colorscheme
    colorscheme = colorscheme,

    -- Default theme configuration
    default_theme = {
        diagnostics_style = { italic = true },
        -- Modify the color table
        colors = {
            fg = "#abb2bf",
        },
        -- Modify the highlight groups
        highlights = function(highlights)
            local C = require("default_theme.colors")

            highlights.Normal = { fg = C.fg, bg = C.bg }
            return highlights
        end,
    },

    -- Disable default plugins
    enabled = {
        bufferline = true,
        neo_tree = true,
        lualine = true,
        gitsigns = true,
        colorizer = true,
        toggle_term = true,
        comment = true,
        symbols_outline = true,
        indent_blankline = true,
        dashboard = true,
        which_key = true,
        neoscroll = true,
        ts_rainbow = true,
        ts_autotag = true,
    },

    -- Disable AstroNvim ui features
    ui = {
        nui_input = true,
        telescope_select = true,
    },

    -- Configure plugins
    plugins = {
        -- Add plugins, the packer syntax without the "use"
        init = {
            -- Colorschemes
            { "lunarvim/darkplus.nvim" },

            -- Vim and Tmux Navigator
            { "christoomey/vim-tmux-navigator" },

            -- Undo tree
            {
                "mbbill/undotree",
                config = [[vim.g.undotree_SetFocusWhenToggle = 1]],
            },

            --- Signatures
            -- {
            --     "ray-x/lsp_signature.nvim",
            --     event = "BufRead",
            --     config = function()
            --         require("lsp_signature").setup()
            --     end,
            -- },

            -- { "hrsh7th/cmp-nvim-lsp-signature-help" },

            --- HTML Helper
            {
                "mattn/emmet-vim",
            },

            -- VimWiki
            {
                "vimwiki/vimwiki",
            },

            -- CSV Viewer
            -- {
            --     "chrisbra/csv.vim",
            -- },

            -- Jupyter Ascending (vim to jupyter integration)
            { "untitled-ai/jupyter_ascending.vim" },

            -- Julia vim
            { "JuliaEditorSupport/julia-vim" },

            -- Completions
            -- {
            --     "andersevenrud/cmp-tmux",
            --     after = "nvim-cmp",
            --     config = function()
            --         require("core.utils").add_user_cmp_source("tmux")
            --     end,
            -- },
            {
                "hrsh7th/cmp-cmdline",
                after = "nvim-cmp",
                config = function()
                    require("core.utils").add_user_cmp_source("cmdline")
                end,
            },
            {
                "hrsh7th/cmp-nvim-lua",
                after = "nvim-cmp",
                config = function()
                    require("core.utils").add_user_cmp_source("nvim_lua")
                end,
            },
            {
                "quangnguyen30192/cmp-nvim-ultisnips",
                after = "nvim-cmp",
                config = function()
                    require("core.utils").add_user_cmp_source("ultisnips")
                end,
            },

            {
                "s1n7ax/nvim-window-picker",
                tag = "v1.*",
                config = function()
                    require("window-picker").setup()
                end,
            },

            {
                "SirVer/ultisnips",
                requires = "honza/vim-snippets",
                config = function()
                    vim.g.UltiSnipsRemoveSelectModeMappings = 0
                end,
            },

            -- Python indenting support
            {
                "Vimjas/vim-python-pep8-indent",
            },

            -- { "andweeb/presence.nvim" },
        },
        -- All other entries override the setup() call for default plugins
        treesitter = {
            ensure_installed = { "lua" },
        },

        packer = {
            compile_path = vim.fn.stdpath("config") .. "/lua/packer_compiled.lua",
        },
        cmp = function(opts)
            -- opts parameter is the default options table
            -- the function is lazy loaded so cmp is able to be required
            local cmp = require("cmp")
            -- modify the mapping part of the table
            opts.mapping["<C-l>"] = cmp.mapping.confirm({ select = true })
            -- return the new table to be used
            return opts
        end,
    },

    -- Add paths for including more VS Code style snippets in luasnip
    luasnip = {
        vscode_snippet_paths = {
            "./lua/user/snippets",
        },
    },

    -- Modify which-key registration
    ["which-key"] = {
        -- Add bindings
        register_mappings = {
            -- first key is the mode, n == normal mode
            n = {
                -- second key is the prefix, <leader> prefixes
                -- name = "Execute Code",
                ["<leader>"] = {
                    -- which-key registration table for normal mode, leader prefix
                    -- ["N"] = { "<cmd>tabnew<cr>", "New Buffer" },
                    ["u"] = { "<cmd>UndotreeToggle<CR>", "Undotree" },
                    ["<space>"] = {
                        name = "Execute Code",
                        x = { "<cmd>call jupyter_ascending#execute()<CR>", "Execute single cell" },
                        X = {
                            "<cmd>call jupyter_ascending#execute_all()<CR>",
                            "Execute all cells",
                        },
                        s = { "<Plug>NormalModeSendToTmux", "Send Selection to Tmux" },
                        t = { "<Plug>SetTmuxVars", "Set Tmux Vars" },
                        c = { "<cmd>Tmux clear<CR>", "Clear console" },
                        a = { "ggVG<Plug>SendSelectionToTmux", "Send Selection to Tmux" },
                        r = {
                            name = "REPL",
                            p = { "<cmd>Tmux ipython<CR>", "IPython" },
                        },
                    },
                },
            },
            -- first key is the mode, v == visual mode
            v = {
                -- second key is the prefix, <leader> prefixes
                -- name = "Execute Code",
                ["<leader>"] = {
                    -- which-key registration table for normal mode, leader prefix
                    -- ["N"] = { "<cmd>tabnew<cr>", "New Buffer" },
                    ["<space>"] = {
                        name = "Execute Code",
                        s = { "<Plug>SendSelectionToTmux", "Send Selection to Tmux" },
                    },
                },
            },
        },
    },

    -- CMP Source Priorities
    -- modify here the priorities of default cmp sources
    -- higher value == higher priority
    -- The value can also be set to a boolean for disabling default sources:
    -- false == disabled
    -- true == 1000
    cmp = {
        source_priority = {
            -- tmux = 500,
            nvim_lsp = 1000,
            luasnip = 750,
            buffer = 500,
            path = 250,
        },
    },

    -- Extend LSP configuration
    lsp = {
        -- add to the server on_attach function
        -- on_attach = function(client, bufnr)
        -- end,

        -- override the lsp installer server-registration function
        -- server_registration = function(server, opts)
        --   server:setup(opts)
        -- end

        -- Add overrides for LSP server settings, the keys are the name of the server
        ["server-settings"] = {
            -- example for addings schemas to yamlls
            -- yamlls = {
            --   settings = {
            --     yaml = {
            --       schemas = {
            --         ["http://json.schemastore.org/github-workflow"] = ".github/workflows/*.{yml,yaml}",
            --         ["http://json.schemastore.org/github-action"] = ".github/action.{yml,yaml}",
            --         ["http://json.schemastore.org/ansible-stable-2.9"] = "roles/tasks/*.{yml,yaml}",
            --       },
            --     },
            --   },
            -- },
        },
    },

    -- Diagnostics configuration (for vim.diagnostics.config({}))
    diagnostics = {
        virtual_text = true,
        underline = true,
    },

    -- null-ls configuration
    ["null-ls"] = function()
        -- Formatting and linting
        -- https://github.com/jose-elias-alvarez/null-ls.nvim
        local status_ok, null_ls = pcall(require, "null-ls")
        if not status_ok then
            return
        end

        -- Check supported formatters
        -- https://github.com/jose-elias-alvarez/null-ls.nvim/tree/main/lua/null-ls/builtins/formatting
        local formatting = null_ls.builtins.formatting

        -- Check supported linters
        -- https://github.com/jose-elias-alvarez/null-ls.nvim/tree/main/lua/null-ls/builtins/diagnostics
        local diagnostics = null_ls.builtins.diagnostics

        null_ls.setup({
            debug = false,
            sources = {
                -- Set a formatter
                formatting.autopep8.with({ filetypes = { "python" } }),
                formatting.black.with({ extra_args = { "--fast" } }),
                formatting.prettier.with({
                    extra_args = { "--no-semi", "--single-quote", "--jsx-single-quote" },
                }),
                -- formatting.reorder_python_imports.with({ filetypes = { "python" } }),
                -- formatting.isort.with({ filetypes = { "python" }, extra_args = { "-sl" } }),
                formatting.isort.with({ filetypes = { "python" }, extra_args = {} }),
                formatting.stylua.with({ filetypes = { "lua" }, extra_args = { "--indent-type", "Spaces" } }),

                -- Set a linter
                diagnostics.flake8.with({ filetypes = { "python" } }),
                diagnostics.mypy.with({ filetypes = { "python" } }),
                diagnostics.pylint.with({ filetypes = { "python" } }),
                diagnostics.markdownlint.with({ filetypes = { "markdown", "vimwiki.markdown" } }),
            },
            -- NOTE: You can remove this on attach function to disable format on save
            on_attach = function(client)
                if client.resolved_capabilities.document_formatting then
                    vim.api.nvim_create_autocmd("BufWritePre", {
                        desc = "Auto format before save",
                        pattern = "<buffer>",
                        callback = vim.lsp.buf.formatting_sync,
                    })
                end
            end,
        })
    end,

    -- This function is run last
    -- good place to configure mappings and vim options
    polish = function()
        local map = vim.keymap.set
        local set = vim.opt
        -- Set options
        set.relativenumber = true

        -- Set key bindings
        map("n", "<C-s>", ":w!<CR>")

        -- Set autocommands
        vim.api.nvim_create_augroup("packer_conf", {})
        vim.api.nvim_create_autocmd("BufWritePost", {
            desc = "Sync packer after modifying plugins.lua",
            group = "packer_conf",
            pattern = "plugins.lua",
            command = "source <afile> | PackerSync",
        })

        -- Set up custom filetypes
        -- vim.filetype.add {
        --   extension = {
        --     foo = "fooscript",
        --   },
        --   filename = {
        --     ["Foofile"] = "fooscript",
        --   },
        --   pattern = {
        --     ["~/%.config/foo/.*"] = "fooscript",
        --   },
        -- }

        -- Source Abbreviations
        vim.cmd([[source ~/.config/astronvim/viml/abbreviations.vim]])

        -- Source vimtmux
        vim.cmd([[source ~/.config/astronvim/viml/vimtux.vim]])

        -- BufOnly
        vim.cmd([[source ~/.config/astronvim/viml/bufonly.vim]])

        -- setting.vim
        vim.cmd([[source ~/.config/astronvim/viml/options.vim]])

        vim.cmd([[source ~/.config/astronvim/viml/autoread.vim]])

        -- Custom indenting
        vim.cmd(
            [[autocmd FileType htmldjango,html,javascript,lua,yaml,yml setlocal tabstop=2 shiftwidth=2 softtabstop=2 expandtab]]
        )
        vim.cmd([[autocmd FileType rst setlocal tabstop=3 shiftwidth=3 softtabstop=3 expandtab]])

        for k, v in pairs(options) do
            vim.opt[k] = v
        end
    end,
}

-- print(vim.inspect(config.luasnip))
print(vim.inspect(vim.opt.rtp))
return config

**Comment by lawrencet149** [comment]
Directory structure: 
![screenshot](https://user-images.githubusercontent.com/25508683/166299228-a92a766b-a206-4da1-8339-fdbc7ea3e704.png)

**Comment by lawrencet149** [comment]
Are you able to share your init.lua? I am pretty sure I am missing something in my config. Trying to see if your init.lua would work on my system.

**Comment by lawrencet149** [comment]
I removed .config/astronvim directory and did fresh install of AstroNvim and snippets are working now. I will re-add my init.lua a section at a time to see what was causing my issue. Thank you for you help.

**Comment by mehalter** [comment]
No problem. Also make sure you update the `package.json` with the snippet files that you add for each language just a heads up :)
