### ISSUE TITLE
New user options table does not support (errors out) the "append, remove"-style config allowed by the nvim lua API

### ISSUE THREAD

**Issue by krishnakumarg1984** [AstroNvim/AstroNvim#428]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0

**Describe the bug**
The newly introduced user_config options table in AstroNvim does not support compound "append", "remove" etc style setting, and errors out.

See https://neovim.io/doc/user/lua.html

> To replicate the behavior of |[:set+=](https://neovim.io/doc/user/options.html#:set+=)|, use:
> 
>         -- vim.opt supports appending options via the "+" operator
>         vim.opt.wildignore = vim.opt.wildignore + { "*.pyc", "node_modules" }
> 
>         -- or using the `:append(...)` method
>         vim.opt.wildignore:append { "*.pyc", "node_modules" }

> To replicate the behavior of |[:set-=](https://neovim.io/doc/user/options.html#:set-=)|, use:
> 
>         -- vim.opt supports removing options via the "-" operator
>         vim.opt.wildignore = vim.opt.wildignore - { "node_modules" }
> 
>         -- or using the `:remove(...)` method
>         vim.opt.wildignore:remove { "node_modules" }

**To Reproduce** 

In the user's `init.lua`, use the following table 
  -- set vim options here (vim.<first_key>.<second_key> =  value)
  options = {
    opt = {
      backupdir:remove { "." },
    },
  },

**Comment by mehalter** [comment]
The table is simply a structure for holding data so it will not be able to support this type of syntax and therefore is out of the scope and not a bug. This can be achieved though with simple lua:

```lua
options = {
  opt = {
    backupdir = vim.opt.backupdir - { "." },
    shortmess = vim.opt.shortmess + { I = true },
  },
},
```

**Comment by krishnakumarg1984** [comment]
Hi @mehalter, err  `vim.opt.backupdir:remove { "." }` works well in a standard neovim `init.lua` config file. Are you saying that this shorthand notation cannot be supported in AstroNvim?

**Comment by mehalter** [comment]
Not in a table format since a table is a dictionary and those functions work in place on a variable. You could put that notation in your `polish` function or just somewhere as normal `lua`. But those are not valid values to go inside of a dictionary.

**Comment by mehalter** [comment]
If you want all of these options in the same place and use that shorthand syntax instead of split between `options` and `polish`, you could utilize our other override format that gives a little bit more control over the default table as well as gives you a function block to work in and it look something like this:

```lua
return {
  options = function(defaults)
    defaults.opt.conceallevel = 2 -- enable conceal
    defaults.opt.foldenable = false
    defaults.opt.foldexpr = "nvim_treesitter#foldexpr()" -- set Treesitter based folding
    defaults.opt.foldmethod = "expr"
    defaults.opt.linebreak = true -- linebreak soft wrap at words
    defaults.opt.list = true -- show whitespace characters
    defaults.opt.listchars = { tab = "│→", extends = "⟩", precedes = "⟨", trail = "·", nbsp = "␣" }
    defaults.opt.shortmess = vim.opt.shortmess + { I = true }
    defaults.opt.showbreak = "↪ "
    defaults.opt.spellfile = "~/.config/nvim/lua/user/spell/en.utf-8.add"
    defaults.opt.thesaurus = "~/.config/nvim/lua/user/spell/mthesaur.txt"
    defaults.opt.wrap = true -- soft wrap lines

    vim.opt.backupdir:append { "." }

    return defaults
  end,
}
```

But this approach is definitely quite verbose. Another shorthand you could do would be:

```lua
return {
  options = function(defaults)
    vim.tbl_deep_extend("force", defaults.opt, {
      conceallevel = 2, -- enable conceal
      foldenable = false,
      foldexpr = "nvim_treesitter#foldexpr()", -- set Treesitter based folding
      foldmethod = "expr",
      linebreak = true, -- linebreak soft wrap at words
      list = true, -- show whitespace characters
      listchars = { tab = "│→", extends = "⟩", precedes = "⟨", trail = "·", nbsp = "␣" },
      shortmess = vim.opt.shortmess + { I = true },
      showbreak = "↪ ",
      spellfile = "~/.config/nvim/lua/user/spell/en.utf-8.add",
      thesaurus = "~/.config/nvim/lua/user/spell/mthesaur.txt",
      wrap = true, -- soft wrap lines
    })

    vim.opt.backupdir:append { "." }

    return defaults
  end,
}
```

**Comment by mehalter** [comment]
For further information about this `function` approach rather than just an override table is documented here: https://astronvim.github.io/configuration/override_formats#override-function

**Comment by krishnakumarg1984** [comment]
Thank you so much!
