### ISSUE TITLE
Do not disable netrwPlugin (messes up spellfile download capability built into neovim)

### ISSUE THREAD

**Issue by krishnakumarg1984** [AstroNvim/AstroNvim#430]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0

**Describe the bug**
`lua/core/utils.lua` currently sets `g.loaded_netrwPlugin = false`.  This optimisation interferes with neovim's built-in ability to download spellfiles for languages on the go based on a modeline setting for `spelllang`. This is invaluable for those who write prose (such as LaTeX documentation or even a Markdown file in other languages).

Vim's [help](https://vimhelp.appspot.com/spell.txt.html#spellfile.vim) states that:

> The plugin has a default place where to look for spell files, on the Vim ftp
> server.  If you want to use another location or another protocol, set the
> g:spellfile_URL variable to the directory that holds the spell files.  The
> netrw plugin is used for getting the file, look there for the specific
> syntax of the URL.  Example: 
>     let g:spellfile_URL = 'http://ftp.vim.org/vim/runtime/spell'
> You may need to escape special characters.

This is also applicable to neovim. 
For further reference, see [this](https://vi.stackexchange.com/questions/5651/how-can-i-make-vim-download-spell-files) question on stackexchange.

The plugin will only ask about downloading a language once.  If you want to
try again anyway restart Vim, or set g:spellfile_URL to another value (e.g.,
prepend a space).

Normally, I'd aim to quickly override this in the user config. However, once disabled, it appears that setting `loaded_netrwPlugin = true,` under the option `g` in the user options table does not work in this case.

**To Reproduce**
1. Set `spell = true` in `init.lua` (or an autocommand to enable spell checking only for certain filetypes such as markdown or text)
2. Edit a file, say `hola.txt` with a modeline at the top e.g. `vim: spell:spelllang=es` and put some lines of text inside the file, e.g "Estoy bien" (which means, "I am fine").
3. Close and reopen the file `hola.txt` in neovim
4. There will be a message that pops up `Warning: Cannot find word list "es.utf-8.spl" or "es.ascii.spl"`
5. Spell checking is therefore not available :(
6. Now, comment out the line `g.loaded_netrwPlugin = false` in `lua/core/utils.lua` and then try reopening `hola.txt` in neovim. Neovim offers a dialog to download the spellfile. After accepting with 'yes', spell-check in Spanish is now available in the file.

**Comment by mehalter** [comment]
@krishnakumarg1984 This is a default I think we want to stick with to save time on loading for most users. The issue you are running into is because a lot of these legacy plugins were written for `vim` and not a language like `lua`. So instead of checking for a specific value, they are just looking for if a value exists. This can be achieved in something like the answer I gave you on your previous question:


```lua
return {
  options = function(defaults)
    defaults.g.loaded_netrwPlugin = nil

    return vim.tbl_deep_extend("force", defaults, {
      opt = {
        conceallevel = 2, -- enable conceal
        foldenable = false,
        foldexpr = "nvim_treesitter#foldexpr()", -- set Treesitter based folding
        foldmethod = "expr",
        linebreak = true, -- linebreak soft wrap at words
        list = true, -- show whitespace characters
        listchars = { tab = "│→", extends = "⟩", precedes = "⟨", trail = "·", nbsp = "␣" },
        shortmess = vim.opt.shortmess + { I = true },
        showbreak = "↪ ",
        spellfile = "~/.config/nvim/lua/user/spell/en.utf-8.add",
        thesaurus = "~/.config/nvim/lua/user/spell/mthesaur.txt",
        wrap = true, -- soft wrap lines
      },
    })
  end,
}
```

**Comment by mehalter** [comment]
Notice here I am setting the `netrwPlugin` to nil before returning. The override function in `neovim` sees this nil and takes the other tables value. So it needs to be hot wired in as follows.

**Comment by krishnakumarg1984** [comment]
Setting `defaults.g.loaded_netrwPlugin = nil` as per above did not work for me.  I think something else is needed for facilitating download of spell files.

**Comment by mehalter** [comment]
Did it give you access to the `:Explore` command? You might need to do something similar with the other netrw plugins that we disable

**Comment by krishnakumarg1984** [comment]
>Did it give you access to the :Explore command?

No. But when I comment out just the single line, `g.loaded_netrwPlugin = false` in `lua/core/utils.lua`, I get the `:Explore` command, and the spellfile downloading works fine.

**Comment by mehalter** [comment]
I would investigate the code that I sent you to see if I made an error. I am not at a computer currently, but using that method I was able to get the netrw plugin loaded without editing core. Also make sure to pull the latest code :) and remember it has to be in the function method and not with the table override.

**Comment by mehalter** [comment]
I can investigate more and help you out later

**Comment by krishnakumarg1984** [comment]
>Also make sure to pull the latest code :)

Ah. That was it. The spell-file thing and `:Explore` work now with the function method. Thanks a lot for your kind help on this.

**Comment by rami3l** [comment]
One downside about this decision is that it has broken potential `spellfile` downloading mechanism in ":set spell", which can be triggered by `spelllang=fr` for example.

**Comment by mehalter** [comment]
> One downside about this decision is that it has broken potential `spellfile` downloading mechanism in ":set spell", which can be triggered by `spelllang=fr` for example. It took me quite a while to find this thread :'|

This is no longer a decision being made by AstroNvim and is entirely up to the user. Please look at your own configuration and remove where you disable netrw

**Comment by rami3l** [comment]
> This is no longer a decision being made by AstroNvim and is entirely up to the user. Please look at your own configuration and remove where you disable netrw

@mehalter Thanks for the reply!

Although it originated from copying the official template verbatim without knowing its actual meaning, I fully recognize that I am responsible for my own configuration.

Thus, I posted the comment simply wanting to provide more info for those who are clueless about why it has broken.
