### ISSUE TITLE
How to remap the telescope keymapping

### ISSUE THREAD

**Issue by convers39** [AstroNvim/AstroNvim#442]
I am trying to use the quickfix + cfdo for replacement in multiple files, here is the flow:

1. `<leader> f w` -> open keyword grep window
2. search for keyword, e.g. astro
3. tab to select files
4. send ONLY SELECTED files to qflist
5. `:cfdo %s/astro/AstroNvim/gc | :w`  to replace and save in selected files

Now according to the [doc](https://astronvim.github.io/configuration/plugin_defaults), the default key mapping for sending selected files to qlfist is `M-q`

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/42597395/166694593-15d0fcef-4cd9-45bf-8dc8-1e1b6487b8fb.png">

I am not sure what is `M-q` so after [some research](https://gist.github.com/awidegreen/3854277), it seems to be `Alt + q`. I am using mac so assume it should be `option + q`, while not working.

So I tried to remap the key bindings, however, I got this error that says `undefined global actions`.

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/42597395/166695445-f711790e-2415-4c56-9262-3af566d3edbd.png">

So my questions are, 
- how to trigger `M-q` here?
- Or how to resolve the undefined global actions error..

**Comment by mehalter** [comment]
You can actually do this easier like this:

```lua
return {
  plugins = {
    telescope = function(config)
      config.defaults.mappings.i["<C-q>"] = config.defaults.mappings.i["<M-q>"]
      return config
    end,
  },
}
```

or you can do this:

```lua
return {
  plugins = {
    telescope = function(config)
      local actions = require "telescope.actions"
      config.defaults.mappings.i["<C-q>"] = actions.send_selected_to_qflist + actions.open_qflist
      return config
    end,
  },
}
```

**Comment by mehalter** [comment]
This override method with a function rather than a table is described here in the documentation: https://astronvim.github.io/configuration/override_formats#override-function
