### ISSUE TITLE
Seeking explanation on load_black = false, -- disable black 

### ISSUE THREAD

**Issue by krishnakumarg1984** [AstroNvim/AstroNvim#443]
In the default built-in plugins that are disabled in `lua/core/options.lua` for startup speed, there is a curious entry, `load_black = false,    -- disable black`.

I was curious what does this do? I couldn't find any relevant reference in neovim's built-in help documentation. Secondly, while other built-in plugins are disabled with `loaded_`, here we disable it with `load_`. Is this a typo?

**Comment by mehalter** [comment]
This is a plugin provided by the `black` package in Python. It is not always available if users don't use Python, but the plugin adds a decent amount of start up time. We can probably remove this, but it doesn't add any processing time/slow down to set it. It is not a typo here, that is just the decision the `black` devs landed on (for whatever reason).

**Comment by mehalter** [comment]
No
