### ISSUE TITLE
In AstroNvim, how to enable the "Add space between parenthesis" rule of autopairs.nvim

### ISSUE THREAD

**Issue by krishnakumarg1984** [AstroNvim/AstroNvim#444]
`autopairs.nvim` wiki lists with a useful rule/recipe called ["Add space between parenthesis"](https://github.com/windwp/nvim-autopairs/wiki/Custom-rules#add-spaces-between-parentheses)

This is super useful e.g. when editing lua tables for neovim config (among other filetypes). There is almost never an occasion where I need just a leading space between text inside any kind of brackets. 

How can I include this in my user `init.lua`? Is it worth including this recipe in the distribution.? If any user insists on having asymmetric spacing (but why?), they can always just delete the extra space in the normal model

**Comment by mehalter** [comment]
You can just put this put this in the `polish` function.

**Comment by krishnakumarg1984** [comment]
Hmm. In the polish section, I now have the code:

```lua
    local npairs = require'nvim-autopairs'
    local Rule   = require'nvim-autopairs.rule'

    npairs.add_rules {
      Rule(' ', ' ')
        :with_pair(function (opts)
          local pair = opts.line:sub(opts.col - 1, opts.col)
          return vim.tbl_contains({ '()', '[]', '{}' }, pair)
        end),
      Rule('( ', ' )')
        :with_pair(function() return false end)
        :with_move(function(opts)
          return opts.prev_char:match('.%)') ~= nil
        end)
        :use_key(')'),
    }
```
which gives me the following error:

> Error detected while processing /home/.config/nvim/init.lua:
> E5113: Error while calling lua chunk: ...te/pack/packer/opt/nvim-autopairs/lua/nvim-autopairs.lua:110: attempt to index field 'config' (a nil value)
> stack traceback:
> 	...te/pack/packer/opt/nvim-autopairs/lua/nvim-autopairs.lua:110: in function 'add_rules'
> 	.../.config/nvim/../astronvim/lua/user/init.lua:1341: in function 'polish'
> 	/home/.config/nvim/init.lua:40: in main chunk

**Comment by krishnakumarg1984** [comment]
@mehalter This works absolutely fine when I added to `lua/configs/autopairs.lua` inside the function `M.config()`. I just pasted the function towards the end of the current chunk of code therein.

Can you please point how to integrate this snippet of code into my `init.lua` since I'd really appreciate this functionality?

**Comment by mehalter** [comment]
Ah I see now what's going on. They do some weird stuff with how their api is set up and it doesn't maintain the config on multiple imports. I will investigate this in the coming days and get back to you.

**Comment by mehalter** [comment]
Opened a new PR that allows you to interface easily with this `add_rules` function like this:

```lua
return {
  ["nvim-autopairs"] = {
    add_rules = function()
      local Rule = require "nvim-autopairs.rule"

      return {
        Rule(" ", " "):with_pair(function(opts)
          local pair = opts.line:sub(opts.col - 1, opts.col)
          return vim.tbl_contains({ "()", "[]", "{}" }, pair)
        end),
        Rule("( ", " )")
          :with_pair(function()
            return false
          end)
          :with_move(function(opts)
            return opts.prev_char:match ".%)" ~= nil
          end)
          :use_key ")",
        Rule("{ ", " }")
          :with_pair(function()
            return false
          end)
          :with_move(function(opts)
            return opts.prev_char:match ".%}" ~= nil
          end)
          :use_key "}",
        Rule("[ ", " ]")
          :with_pair(function()
            return false
          end)
          :with_move(function(opts)
            return opts.prev_char:match ".%]" ~= nil
          end)
          :use_key "]",
      }
    end,
  },
}
```

**Comment by mehalter** [comment]
You just need to return a table with all of the rules that you want to add and it will make a single `add_rules` call. Some of the examples call `add_rules` multiple times, but that seems to not be necessary. Also the function does get passed the original `npairs` variable. So if you want to clear the rules initially before adding the new rules you are returning you can do this:

```lua
return {
  ["nvim-autopairs"] = {
    add_rules = function(npairs)
      local Rule = require "nvim-autopairs.rule"
      npairs.clear_rules()

      return {
        Rule(" ", " "):with_pair(function(opts)
          local pair = opts.line:sub(opts.col - 1, opts.col)
          return vim.tbl_contains({ "()", "[]", "{}" }, pair)
        end),
        Rule("( ", " )")
          :with_pair(function()
            return false
          end)
          :with_move(function(opts)
            return opts.prev_char:match ".%)" ~= nil
          end)
          :use_key ")",
        Rule("{ ", " }")
          :with_pair(function()
            return false
          end)
          :with_move(function(opts)
            return opts.prev_char:match ".%}" ~= nil
          end)
          :use_key "}",
        Rule("[ ", " ]")
          :with_pair(function()
            return false
          end)
          :with_move(function(opts)
            return opts.prev_char:match ".%]" ~= nil
          end)
          :use_key "]",
      }
    end,
  },
}
```

**Comment by krishnakumarg1984** [comment]
@mehalter No. This does not work for me after updating AstroNvim, including this in my user config and restarting the editor.

**Comment by mehalter** [comment]
Can you be more specific? I cannot recreate on my end with a base installation nor in my config? Also please note that this does not go in the `plugins` table. The examples I provided above are complete `user/init.lua` examples. So it should be a top level property in the table.

**Comment by mehalter** [comment]
Ah yes, I see. Please check my previous examples and my previous comment about the entry being a top level field. You have placed the `add_rules` code inside of the `plugins` table. So you are providing the `add_rules` entry to the `require("nvim-autopairs").setup({...})` call. The plugins table is specifically reserved for setup function. This should go as a top level key. My example code previously are *complete* `init.lua` examples. Please note that there is no `plugins = { ... }` in them.

**Comment by mehalter** [comment]
If you want to verify that it is something in your config. Please try using one of the above comment code blocks as a minimal `user/init.lua` file and test to see if that works.

**Comment by krishnakumarg1984** [comment]
Yay. That was exactly the issue. It's now done! Thanks a lot for helping with this new clean API for autopairs rules!
