### ISSUE TITLE
Two plugins from akinsho(bufferline and toggleterm) not updating

### ISSUE THREAD

**Issue by sharkby7e** [AstroNvim/AstroNvim#446]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [ x] `:PackerSync`
- [ x] `:AstroUpdate`
- [ x] restarted AstroNvim
- [x ] Neovim version >= 0.7.0

**Describe the bug**
Failed to update two plugins from akinsho. 

"Your configuration specifies to merge with the ref 'refs/heads/master' from the remote but no such ref was fetched"

**To Reproduce**
`:PackerSync`

**Expected behavior**
Expect to be able to update

**Additional context**
Went into the repos, and akinsho appears to have renamed master to main, so this ref just needs to be changes. I would definitely like to try and solve this, but need a little guidance

**Comment by mehalter** [comment]
This developer changed the name of the `master` branch on all of his repos to `main` a month or 2 ago so the `master` branch no longer exists. You will need to go to your plugins folder, typically something like `~/.local/share/nvim/site` and locate those folders and reset them to the new `main` branch. Or you can just delete them and let Packer redownload them.

Sorry for this inconvenience, but sadly this is out of the scope of what we can control as a custom configuration.
