### ISSUE TITLE
how to customize language server startup?

### ISSUE THREAD

**Issue by dpriedel** [AstroNvim/AstroNvim#457]
Hi

I am trying to pass some arguments to the clangd language server for startup.

I can't find how/where to do that.

I have a .config/nvim/lua/init.lua file where I have successfully added some functions. I thought that might be the place but I don't see anywhere that looks correct.

Thanks

**Comment by mehalter** [comment]
The way to configure `clangd` traditionally with `lspconfig` is to have a `require'lspconfig'.clangd.setup({...})` call where the parameter table are the available options as shown here: https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#clangd

For AstroNvim, we provide a simple way to provide these settins to `lspconfig` like the following `init.lua` file:

```lua
return {
  lsp = {
    server_settings = {
      clangd = {
        -- This table is the input to the require("lspconfig").clangd.setup call
        capabilities = { -- example setting capabilities like offset encoding
          offsetEncoding = "utf-8",
        },
        cmd = { "clangd" } -- supply more arguments in this cmd list
      }
    }
  }
}
```

**Comment by dpriedel** [comment]
That is the answer I was looking for.

Thanks for the quick response.

**Comment by krishnakumarg1984** [comment]
> ```lua
> return {
>   lsp = {
>     server_settings = {
>       clangd = {
>         -- This table is the input to the require("lspconfig").clangd.setup call
>         capabilities = { -- example setting capabilities like offset encoding
>           offsetEncoding = "utf-8",
>         },
>         cmd = { "clangd" } -- supply more arguments in this cmd list
>       }
>     }
>   }
> }
> ```

This does not work for me. `:LspInfo` shows that no extra arguments were passed to `clangd`.

**Comment by mehalter** [comment]
Ah there is a typo in my response, this should be `["server-settings"]` and not `server_settings`

**Comment by mehalter** [comment]
@krishnakumarg1984
