### ISSUE TITLE
Servers that are installed with nvim-lsp-installer are not automatically enabled/attached when opening a relevant filetype

### ISSUE THREAD

**Issue by krishnakumarg1984** [AstroNvim/AstroNvim#466]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0

**Describe the bug**
In the provideed `lua/user_example/init.lua`, populating the template table provided:
```lua
    ["nvim-lsp-installer"] = {
      ensure_installed = {
        "sumneko_lua",
        "clangd",
      },
    },`
```
installs the relevant servers, but does not enable them i.e. attach to LSPs when opening the relevant filetype.

It requires a further setting in the `lsp` table e.g.:
```lua
 -- enable servers that you already have installed without lsp-installer
servers = {
      "sumneko_lua",
      "clangd",

    },
```
The comment there in the template is misleading i.e. it suggests that only servers manually installed needs to be enabled explicitly.  

IMO, it is redundant to have the same set of servers listed in two places. It is tedious to install and enable for more LSPs. It would be great if the `nvim-lsp-installer` servers are automatically enabled without further config from the user's part.

**Comment by mehalter** [comment]
This enabling should not be a problem I will check this out later.

**Comment by mehalter** [comment]
@krishnakumarg1984 I can confirm that I cannot replicate this bug on my end or in a clean install of AstroNvim

**Comment by mehalter** [comment]
If it is a fresh install you may have to restart neovim so that it knows the lsp is installed, but once it is installed we are able to tell the server is available. Having 2 lists is important for people who want to install some language servers but not all servers they want to enable

**Comment by mehalter** [comment]
I have done more testing. The `nvim-lsp-installer` does not even require configuration at all. If you don't have a `user/` folder and just install language servers manually from the interface or commands and restart the language servers are available automatically without populating either lsp servers list.

**Comment by krishnakumarg1984** [comment]
Strange.
- Perhaps this bug only occurs in the case where the user's config is in `~/.config/astronvim/lua/user/init.lua`?
- Secondly, while I agree that having independent control of installing vs enabling is important, writing duplicated long list of LSP server names in two locations within the same file is a sub-optimal way of doing things that violates the DRY principle in coding. It would be better if you could modify the key to accept `enable = all | {} | {table/list of servers}`, and `disable =  all | {} | {list of servers}`. The `all` and `{}` settings in the `enable` table would cater to those who want to attach everything installed or nothing installed. The manual list of servers will help those who want fine-grained control. If people want to attach the majority of servers barring one or two, the `disable` key would be helpful. This is exactly how the treesitter plugin allows for user control.

**Comment by mehalter** [comment]
Like I said before, these lists should not contain duplicates. You can supply just servers in one or the other. You can also set `automatic_installation = true` in your `nvim-lsp-installer` override table and then just maintain the list in `lsp.servers` if you would prefer. And LSP installer will just try to install all of the ones that they can.

Also I cannot replicate the bug you are describing.

**Comment by krishnakumarg1984** [comment]
Ah. That makes sense. My `init.lua` had an issue wherein the `["nvim-lsp-installer"]` was in the plugins table.

But this is how you have it in the project's `lua/user_example/init.lua`. (line 59)

**Comment by mehalter** [comment]
Yeah, as it shows in the `user_example/init.lua` the `["nvim-lsp-installer"]` should be in the plugins table. As you can see here:

https://github.com/AstroNvim/AstroNvim/blob/d4d46260c062f4b0103783c3542f49efc1453b38/lua/configs/nvim-lsp-installer.lua#L6

**Comment by krishnakumarg1984** [comment]
I'll debug this sometime in the coming days and let you know. Thanks a lot for your amazing help thus far!

**Comment by tomKPZ** [comment]
I'm facing this issue on Arch Linux.  It also occurs when there's no user `init.lua`.

`git bisect` points to this commit: cd7dbab708a8b5e61f79167ca015445467d2bbaa
Can we reopen this issue?

**Comment by mehalter** [comment]
The commit you linked definitely will not work because it was in the middle of the new `nvim-lsp-installer` API and there were a lot of rapid changes over the days. We are currently checking for `nvim-lsp-installer` language servers with the `get_installed_server()` method that they provide. We are not getting them from the configuration files at all which is why it should work if you have installed language servers from the user interface, but will also require a restart after the installation.

Could you please do a test for me @tomKPZ and run:

```
:lua vim.pretty_print(require("nvim-lsp-installer").get_installed_servers())
```

and reply back with the output (probably easiest to do a screenshot like above)? Is this an empty list or does it show something like this:

![2022-05-07_17:18:38_screenshot](https://user-images.githubusercontent.com/1591837/167271986-265f033c-fcd6-4dab-b2be-48d737b108a8.png)

Also for this to work you will need to make sure that you have the most up to date `nvim-lsp-installer` plugin as well as AstroNvim after commit: 362e4ae292b8bdb69802727345ea325c5758444d

**Comment by tomKPZ** [comment]
<img width="1080" alt="lsp" src="https://user-images.githubusercontent.com/9124077/167272218-d30ab876-5ec2-4e3c-ab1a-4e662cda55f1.png">
I'm at commit 9ad4e14b and I've run `:PackerSync` and restarted neovim.  The LSP works if I manually do `:LspStart`, but it doesn't start automatically.

**Comment by tomKPZ** [comment]
@mehalter  sorry I forgot to @ you in my reply above.

**Comment by mehalter** [comment]
That screenshot looks perfect and exactly what it should be. Also it's good that `:LspStart` is working which means the `lspconfig.____.setup` is being called correctly which is all we do with our LSP setup.

Which language server are you trying to use that isn't automatically starting? That seems to be separate from the `lsp.setup` calls at least so it should be something separate. It may be the automatic LSP starting requirements for the server you are using.

**Comment by mehalter** [comment]
@tomKPZ (i forgot to @ as well...)

**Comment by tomKPZ** [comment]
@mehalter I'm using `clangd` and `sumneko_lua` LSPs.  Manual `:LspStart` is required for C++ and Lua.  I also tried at commit https://github.com/AstroNvim/AstroNvim/commit/362e4ae292b8bdb69802727345ea325c5758444d and I see the same issue.  Is there any other info I can provide that may be helpful?

**Comment by mehalter** [comment]
Have you checked the `root_dir` requirements for these servers. If you edit the files in core AstroNvim (outside of your user/ directory) does `sumneko_lua` start automatically? `clangd` also looks for the following files for autostarting:

```
local root_files = {
  '.clangd',
  '.clang-tidy',
  '.clang-format',
  'compile_commands.json',
  'compile_flags.txt',
  'configure.ac', -- AutoTools
}
```

**Comment by mehalter** [comment]
@tomKPZ (gdi)

**Comment by krishnakumarg1984** [comment]
I still have this problem with autostarting. Clangd didn't have this requirement for auto starting before?

**Comment by tomKPZ** [comment]
@mehalter `sumneko_lua` doesn't automatically start if I edit eg `.config/nvim/lua/core/ui.lua`.  For my C++ project, I have a `compile_commands.json` at the project root.

**Comment by mehalter** [comment]
@tomKPZ could you please try to see if you can replicate this with a fresh neovim installation?

Try the following commands:

```sh
mv ~/.config/nvim/user ~/.config/nvim/user.bak
mv ~/.local/share/nvim/site ~/.local/share/nvim/site.bak
nvim +PackerSync
```

Then restart AstroNvim. Once you restart if you do `nvim ~/.config/nvim/lua/core/ui.lua` does it automatically start `sumneko_lua`? These commands shouldn't uninstall your language servers that you previously installed and it should start up automatically with out a `user/` folder because it will be detected as installed.

I have tried everything I can think of and I cannot for the life of me replicate this issue :joy: Makes it really hard to debug especially when you can run `:LspStart` so our commands for running the setup for lspconfig is indeed working in your installation, and we don't do anything else on top of that. sorry is this is not super helpful!

**Comment by mehalter** [comment]
@krishnakumarg1984 if you remove `sumneko_lua` from both the `lsp.servers` table and the `plugins.nvim-lsp-installer.ensure_installed` table in your `user/init.lua` file (or wherever you have them) and make sure `sumneko_lua` is installed with `:LspInstall sumneko_lua` does it start automatically if you run `nvim ~/.config/nvim/init.lua` ?

**Comment by tomKPZ** [comment]
@mehalter Still no luck.  I'm also hitting the same issue on a fresh install of AstroNvim in Ubuntu WSL (autostart does not work but `:LspStart` does).

**Comment by tomKPZ** [comment]
I should also point out that simply going into insert mode will start the LSP server.

**Comment by tomKPZ** [comment]
The issue is now fixed for me.

**Comment by krishnakumarg1984** [comment]
Fixed for me too.
