### ISSUE TITLE
Investigate the move from neoscroll to cinnamon.nvim

### ISSUE THREAD

**Issue by krishnakumarg1984** [AstroNvim/AstroNvim#467]
[cinnamon.nvim](https://github.com/declancm/cinnamon.nvim) looks like a superior smooth scrolling alternative, especially with the ability to scroll over folds.

Is LSP aware (i.e doesn't jarringly snap to the definition with gd, but smoothly scrolls to it if in the same buffer). and as per their README, horizontal scrolling should be a better experience.

Would the devs evaluate cinnamon.nvim to replace neoscroll?

**Comment by mehalter** [comment]
I opened up a PR for this. It seems alright to switch. I don't think we will enable the LSP awareness by default, but it's easy to include it in the `init.lua` on the `lsp.on_attach` override. For the most part from my experience definitions are too far away to smooth scroll anyway so it doesn't add a lot and does add a decent amount of complexity to the configuration when you take into account that people might disable the plugin (like me). But I think switching to this and adding all the extended bindings is probably fine.

**Comment by mehalter** [comment]
I'll let @kabinspace investigate this more and test out the PR as I don't use smooth scrolling plugins so I am just going to disable it after it gets merged anyway.
