### ISSUE TITLE
How to enable built-in plugins for only certain filetypes?

### ISSUE THREAD

**Issue by krishnakumarg1984** [AstroNvim/AstroNvim#472]
I intend to retain one of AstroNvim's plugins, but only intend to have it loaded for certain filetypes. How can one achieve this in user `init.lua`?

**Comment by mehalter** [comment]
https://github.com/wbthomason/packer.nvim#specifying-plugins

Please check  the `packer.nvim` documentation for configuration options when specifying plugins. The `plugin.init` table is just a entries for the `packer.use` call.

**Comment by mehalter** [comment]
I believe the option you are looking for is the `ft` field. The usage of this is documented in the Packer repo
