### ISSUE TITLE
Is it worth configuring the colorizer plugin for all filetypes (Especially since it creates a bunch of autocommands?)

### ISSUE THREAD

**Issue by krishnakumarg1984** [AstroNvim/AstroNvim#474]
Can we please consider  `colorizer` only for certain filetypes. I know about the `ft` option for `packer`, but in the case of `colorizer`, this is less effective, because colorizer already sets up a global autocommand for all filetypes (*) when it is configured by AstroNvim first. This autocmd persists even if colorizer itself is disabled.

Do we really need colorizer on that C++ scientific code, or that python data science file we are editing? Can we perhaps consider restricting its setup() table just for html, css, javascript etc? Even their example is:

```lua
require 'colorizer'.setup {
  'css';
  'javascript';
  html = {
    mode = 'foreground';
  }
}
```

**Comment by mehalter** [comment]
I think for the base installation the current set up is alright, but this is easily configurable for any user in the `plugins` user override table. Feel free to add your own personal preferences there :)

**Comment by krishnakumarg1984** [comment]
I did try before raising it here. I get the following error:

![image](https://user-images.githubusercontent.com/15239509/167164296-272a09f4-51a9-406f-a8c8-cb17cbd55d4b.png)

```
    ["colorizer"] = {
      'css';
      'javascript';
      html = {
        mode = 'foreground';
      },
    },
```
is what I used within the `plugins` table in my `init.lua`.  I tried removing the square-brackets and quotes as well, but to no avail. Same error.

**Comment by mehalter** [comment]
For our config, the colorizer plugin has 2 parameters, so you need to include that. Can you try (this will just take the default 2nd parameter that we provide):

```lua
return {
  plugins = {
    colorizer = {
      {
        "css",
        "javascript",
        html = {
          mode = "foreground",
        },
      },
      {},
    },
  },
}
```

**Comment by mehalter** [comment]
You could also do it like this:

```lua
return {
  plugins = {
    colorizer = function(config)
      config[1] = {
        "css",
        "javascript",
        html = { mode = "foreground" },
      }
      return config
    end,
  },
}
```
