### ISSUE TITLE
Is the project using `schemestore`?

### ISSUE THREAD

**Issue by krishnakumarg1984** [AstroNvim/AstroNvim#475]
I see that `schemastore.nvim` is always loaded. Is AstroNvim using it? I don't see it configured in `lua/configs/`?

**Comment by mehalter** [comment]
Yes this is happening here:

https://github.com/AstroNvim/AstroNvim/blob/598a54362cca2d739521015a21c168733e449c23/lua/configs/lsp/server-settings/jsonls.lua#L4

**Comment by krishnakumarg1984** [comment]
Ah. So this is used for `jsonls`? I am asking because it is one of the non-lazy loaded plugins. Can the project defer its loading until a json buffer is opened and attached to its language server?  Why load it needlessly?

**Comment by mehalter** [comment]
This plugin loads in <0.0001ms to load so we are worrying about unnecessary optimization in this case. You can check `:PackerProfile` to see how long plugins take to load and we have the threshold currently set to 0.0001ms so if a plugin doesn't show up there, then it loaded in <0.0001ms. In this case I believe this is a non-issue.

**Comment by krishnakumarg1984** [comment]
This is not on a modern fast local laptop, but on an underpowered single-core remote server with home drive on an NFS served over a poor network, and a few MB of RAM.  Barebones neovim zips. AstroNvim manages decently well, but I intend to eke out the max juice. 

Anyway, no worries.
