### ISSUE TITLE
Lazy load several other plugins

### ISSUE THREAD

**Issue by krishnakumarg1984** [AstroNvim/AstroNvim#477]
I am looking at the load times on a remote server with networked file system and  AstroNvim's default config. It is reasonably snappy. But I am greedy and would like to get as close to barebones as possible for the loading time, to run `neovim` on an underpowered 20 year old linux desktop with a spinning drive.

Here are some things that a first glance finds.

1. Why load `smart-splits` when there are literally no splits in firing up with just `nvim`?
2. `nvim-lspconfig` and `nvim-lsp-installer` are loaded when opening an empty buffer?
3. Can we defer loading `lualine` until we are past the `alpha` screen?
4. Again, `Indent-blankline` does not server much purpose in the alpha screen

**Comment by mehalter** [comment]
1. `smart-splits` is lazy loaded completely and does not load until a split is tried to navigate in between. Even the creation of splits does not load the plugin. If you simply open and close splits, this plugin will not load until you resize/move between them
2. lsp-installer loads in <0.0001ms and lspconfig loads in <0.01ms so this is considered premature optimization in my eyes
3. indent blankline and lualine would be great to load after the `alpha` screen if you can figure it out a PR would be welcome. I have taken a stab at this in the past and can't figure out a good/intelligent way to do this with packer that would make it worth while.

**Comment by krishnakumarg1984** [comment]
Yup. Lualine is very expensive at nearly 5ms for me. `indent_blankline` isn't cheap to load either.  

Has the project evaluated  `feline.nvim` (by the respected neovim contributor `famiu`)? This is what `nvchad` uses for its status line

 `:PackerProfile` gives me the following. 
```
  Config for lualine.nvim took 4.902222ms
  Sequenced loading took 1.911275ms
  Config for nvim-notify took 0.575697ms
  Config for nvim-web-devicons took 0.320103ms
  Config for indent-blankline.nvim took 0.270078ms
  Defining lazy-load commands took 0.248598ms
  Defining lazy-load filetype autocommands took 0.067964ms
  Defining lazy-load keymaps took 0.056466ms
  Defining packer_plugins took 0.018804ms
  Defining lazy-load event autocommands took 0.018303ms
  Setup for gitsigns.nvim took 0.012718ms
  Setup for nvim-lspconfig took 0.003737ms
  Luarocks path setup took 0.001298ms
  try_loadstring definition took 0.000122ms
```

**Comment by mehalter** [comment]
Yeah I have seen `feline` and I think it would be great to migrate to at some point. idk if I have the bandwidth to dive into that given how much more general and powerful feline is compared to lualine. If you can put together a PR to match the same format as the lualine that would be much  appreciated.
