### ISSUE TITLE
Replace `lualine` with `feline.nvim`

### ISSUE THREAD

**Issue by krishnakumarg1984** [AstroNvim/AstroNvim#478]
`Lualine` is somwhat (in relative terms) expensive for me at nearly 5ms (on an ultrafast modern laptop with an SSD, tons of RAM, 16 cpu cores and loads of cache). 

Can the project evaluate [`feline.nvim`](https://github.com/feline-nvim/feline.nvim) (by the respected neovim contributor `famiu`)? This is what `nvchad` uses for its status line.

 `:PackerProfile` gives me the following. 
```
  Config for lualine.nvim took 4.902222ms
  Sequenced loading took 1.911275ms
  Config for nvim-notify took 0.575697ms
  Config for nvim-web-devicons took 0.320103ms
  Config for indent-blankline.nvim took 0.270078ms
  Defining lazy-load commands took 0.248598ms
  Defining lazy-load filetype autocommands took 0.067964ms
  Defining lazy-load keymaps took 0.056466ms
  Defining packer_plugins took 0.018804ms
  Defining lazy-load event autocommands took 0.018303ms
  Setup for gitsigns.nvim took 0.012718ms
  Setup for nvim-lspconfig took 0.003737ms
  Luarocks path setup took 0.001298ms
  try_loadstring definition took 0.000122ms
```

**Comment by mehalter** [comment]
I think this is a great request. We have discussed this on the discord in depth. I am not sure when I will get the bandwidth to convert our lualine config to feline, but if you can put together a PR feel free.

**Comment by novito** [comment]
@krishnakumarg1984 @mehalter I would love to give this a try if I get some type of guidance on where to get started.

**Comment by mehalter** [comment]
@novito if you cd to your `nvim` folder with `cd ~/.config/nvim`, run `git checkout dev` and then `git pull` just to make sure you are up to date with the latest code. Once you do that open up nvim and run `:PackerSync` to refresh your plugins. This will set up the new feline stuff as well as the changes to `null-ls` that are described in the latest announcement.

**Comment by novito** [comment]
Oh cool @mehalter - so the changes are already done!

**Comment by mehalter** [comment]
Yeah @novito it's been done for a couple days, I have a bug fix opened on `nvim-web-devicons` that I'm waiting to get merged to put the PR through which is why it hasn't been merged yet. But it is stable and ready other than that
