### ISSUE TITLE
Allow for smart-splits.nvim mappings to be user-changeable while preserving lazy loading

### ISSUE THREAD

**Issue by krishnakumarg1984** [AstroNvim/AstroNvim#482]
I see that AstroNvim has lazy loading for `smart-splits.nvim`. 

However, I set up the mapping in `init.lua` which means `smart-splits.nvim` is loaded:

```lua
local smart_splits_status_ok, smart_splits = pcall(require, "smart-splits")
if smart_splits_status_ok then
  vim.keymap.set('n', '<A-h>', smart_splits.resize_left)
  vim.keymap.set('n', '<A-j>', smart_splits.resize_down)
  vim.keymap.set('n', '<A-k>', smart_splits.resize_up)
  vim.keymap.set('n', '<A-l>', smart_splits.resize_right)
end
```

The question is, how to change AstroNvim's mappings conditionally depending on availability of smart-splits in the user's config without affecting its lazy loading?

Obviously blindly remapping will be bad since we will get a bunch of errors if we decide to disable `smart-splits.nvim` in the future.

**Comment by mehalter** [comment]
You can look at how we bind them in core AstroNvim for reference if you would like

https://github.com/AstroNvim/AstroNvim/blob/cc9d12f0af024aadbb866d05f9532718da1f48a1/lua/core/mappings.lua#L125

You can check if the plugin is recognized for packer and then wrap the binding actions in anonymous functions.

**Comment by mehalter** [comment]
I noticed you have opened a lot of questions issues recently (~15% of our issues) have you considered joining the discord channel? You can get questions answered from more users there since it is more active than the GitHub issues

**Comment by krishnakumarg1984** [comment]
Ah. Didn't know there was discord channel. I think that works better for me as well. I am going to sign off for the day though.

>wrap the binding actions in anonymous functions.
I have copied the project's `lua/core/utils.lua` to my custom config directory, and then I am a bit confused about the wrapping the bind actions in anomymous functions.

It would be great if you could help me tonight here (since we are already part-way through the answer), and in the future, I shall use discord.

**Comment by mehalter** [comment]
I'm away from a computer so I will be unable to help tonight. But if you follow the link I provided and look at the source code for when we set the mappings. You can see how we set the bindings and you can copy it in your polish function.

**Comment by krishnakumarg1984** [comment]
Hmm.. I've joined the discord channel. I see a bunch fo `require(smart-splits)` in the project's mapping file. However, that will load the plugin right? It is no different than my `pcall` in my initial post here?

``` lua
  -- Better window navigation
  map("n", "<C-h>", function()
    require("smart-splits").move_cursor_left()
  end, { desc = "Move to left split" })
  map("n", "<C-j>", function()
    require("smart-splits").move_cursor_down()
  end, { desc = "Move to below split" })
  map("n", "<C-k>", function()
    require("smart-splits").move_cursor_up()
  end, { desc = "Move to above split" })
  map("n", "<C-l>", function()
    require("smart-splits").move_cursor_right()
  end, { desc = "Move to right split" })
```

**Comment by krishnakumarg1984** [comment]
As discussed in discord, the below snippet works inside the user's `init.lua`  `polish()` function 

```lua
    if require("core.utils").is_available "smart-splits.nvim" then
      vim.keymap.set("n", "<A-h>", function()
        require("smart-splits").move_cursor_left()
      end, { desc = "Move to left split" })
      vim.keymap.set("n", "<A-j>", function()
        require("smart-splits").move_cursor_down()
      end, { desc = "Move to below split" })
      vim.keymap.set("n", "<A-k>", function()
        require("smart-splits").move_cursor_up()
      end, { desc = "Move to above split" })
      vim.keymap.set("n", "<A-l>", function()
        require("smart-splits").move_cursor_right()
      end, { desc = "Move to right split" })
    end
```

**Comment by krishnakumarg1984** [comment]
The below stopped working for me :(

```lua
if require("core.utils").is_available "smart-splits.nvim" then
  vim.keymap.set("n", "<A-h>", function()
    require("smart-splits").move_cursor_left()
  end, { desc = "Move to left split" })
  vim.keymap.set("n", "<A-j>", function()
    require("smart-splits").move_cursor_down()
  end, { desc = "Move to below split" })
  vim.keymap.set("n", "<A-k>", function()
    require("smart-splits").move_cursor_up()
  end, { desc = "Move to above split" })
  vim.keymap.set("n", "<A-l>", function()
    require("smart-splits").move_cursor_right()
  end, { desc = "Move to right split" })
end
```
