### ISSUE TITLE
guide of leader key is gone

### ISSUE THREAD

**Issue by mafakheri** [AstroNvim/AstroNvim#483]
hello.
i update astronvim and run the packersync
after that the guide is gone. look screen shot .it will explain better than word
![Screenshot from 2022-05-07 03-02-47](https://user-images.githubusercontent.com/100694455/167224255-2556bad2-85dc-4f9d-a2ad-13516f6ac38c.png)

![Screenshot from 2022-05-07 02-59-12](https://user-images.githubusercontent.com/100694455/167224172-70ba028b-1a69-4e80-a9fc-a13fb20dc6c3.png)

**Comment by mehalter** [comment]
Could you share your user config?

**Comment by mafakheri** [comment]
yes .but i remove astronvim and reintall by the same config that i have. now every thing work fine.
i  think problem was by my machine. tnx
