### ISSUE TITLE
Plugin request: vim-surround

### ISSUE THREAD

**Issue by DeanMoser** [AstroNvim/AstroNvim#486]
The majority of AstroNvim is very similar to my personal config that I had been hacking together over the years so I decided to give it a go. There is one thing that I am missing and that is functionality ala [vim-surround](https://github.com/tpope/vim-surround)

Could this or an alternative be considered for AstroNvim? Thanks

**Comment by DeanMoser** [comment]
... oh it's all in vimscript ... know of any alternatives?

**Comment by mehalter** [comment]
I think making significant additions to the actual editing bindings and experience part of vim is something we want to stay away from as it will be 1. hard for users to know all of the editing additions and 2. give people more of a chance to add their own bindings for their own workflow which also helps with remembering bindings. This being very specific to the actual "editing" experience and not additions to other things around editing text that we have added (lsp, file tree, status bar, etc.)

I would recommend adding one to your own personal user configuration. I would recommend checking out https://github.com/echasnovski/mini.nvim which includes a pure lua implementation of `vim-surround`. It is quite fast and reliable and is what I use in my own personal configuration.

**Comment by windowsrefund** [comment]
I'd be really interested in seeing your setup with regard to mini.nvim if you wouldn't mind. I can't seem to find any reference in your [astronvim repo ](https://github.com/mehalter/astrovim)and your [personal git](https://git.mehalter.com/mehalter) seems to be down.

mini.nvim looks really interesting but given how many plugins it appears to replace, moving to it seems like it would take up a good amount of time.

**Comment by pkazmier** [comment]
> I'd be really interested in seeing your setup with regard to mini.nvim if you wouldn't mind. I can't seem to find any reference in your [astronvim repo ](https://github.com/mehalter/astrovim)and your [personal git](https://git.mehalter.com/mehalter) seems to be down.

You can find his config here:

https://code.mehalter.com/projects/68/files
