### ISSUE TITLE
Keybindings conflicting with fzf.vim

### ISSUE THREAD

**Issue by leojplin** [AstroNvim/AstroNvim#490]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0

**Describe the bug**
Even though the included Telescope has find files, but it seems to be a bit slow when used in the codebase I am working on. I installed fzf.vim because it can search my codebase without any slowdown. However, key bindings like C-j, C-k don't work when fzf is opened. I suspect it is the default terminal bindings. When I removed these bindings, everything works as expected. Is there a way to mitigate this without commenting the key bindings out? Thanks!

-- Improved Terminal Mappings
-- map("t", "<esc>", "<C-\\><C-n>", { desc = "Terminal normal mode" })
-- map("t", "jk", "<C-\\><C-n>", { desc = "Terminal normal mode" })
-- map("t", "<C-h>", "<c-\\><c-n><c-w>h", { desc = "Terminal left window navigation" })
-- map("t", "<C-j>", "<c-\\><c-n><c-w>j", { desc = "Terminal down window navigation" })
-- map("t", "<C-k>", "<c-\\><c-n><c-w>k", { desc = "Terminal up window navigation" })
-- map("t", "<C-l>", "<c-\\><c-n><c-w>l", { desc = "Terminal right window naviation" })

**To Reproduce**
1. Install fzf.vim
2. :Files
3. C-k doesn't work

**Expected behavior**
C-j C-k should navigate the search list without exiting insert mode. 

**Screenshots**
If applicable, add screenshots or recording ([Asciinema](asciinema.org)) to help explain your problem.

**Additional context**

**Comment by mehalter** [comment]
You can put something like this in your `user/init.lua` file in your `polish` function:

```lua
vim.keymap.del("t", "<c-j>")
vim.keymap.del("t", "<c-k>")
```
