### ISSUE TITLE
nvim-notify now supports treesitter highlighting with opacity changes

### ISSUE THREAD

**Issue by krishnakumarg1984** [AstroNvim/AstroNvim#498]
See [this](https://www.reddit.com/r/neovim/comments/ucycnk/nvimnotify_now_supports_treesitter_highlighting/)  top-rated post on `r/neovim` (~300 upvotes). There are usage examples in the project's README.md as well on their GitHub wiki.

Would be nice if AstroNvim pulls in some of the recent niceties into its base config.

**Comment by mehalter** [comment]
I don't think any of the notifications that show up in AstroNvim follow markdown syntax so treesitter highlighting doesn't really apply to anything we are using. These features are cool and interesting but definitely more geared towards people who are making their own notifications which we aren't doing.
