### ISSUE TITLE
jk, kj, jj, kk usage in lazygit 

### ISSUE THREAD

**Issue by rafaelderolez** [AstroNvim/AstroNvim#513]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0

**Describe the bug**
Navigating through Files, Branches, Commits can be quite slow in lazygit. I _think_ it's because of `jdhao/better-escape.vim`.

**To Reproduce**
1. Open lazygit
2. Press `jk`, `kj`
3. `Couldn't find a terminal to close` is printed.

AND

1. Open lazygit
2. Press `jj`, `kk`
3. Timeout
4. Motion eventually goes through.

**Expected behavior**
I would expect lazygit to be as responsive inside of AstroNvim as it is out of the box.
Could better-escape be disabled when lazygit is open?

**Screenshots**
Don't have any software record + showing keypresses right now but can provide it if necessary.

**Additional context**
N/A

**Comment by AXGKl** [comment]
In case @rafaelderolez  is right and the better escape mappings are to blame:

The mapping of all 4 quick escape combinations does also cause another problem:

With those enabled you can not quickly type single words ending with a "k" - it will be removed when you quick escape using jk.   

Here a recording:

<details><summary>recording</summary>
<a href="https://asciinema.org/a/KPcWaRHXJVTwyia8A4fdhIgz9" target="_blank"><img src="https://asciinema.org/a/KPcWaRHXJVTwyia8A4fdhIgz9.svg" /></a>
</details>

I would not have created an issue but run that diff, so that the problem goes away, but maybe configurable mappings would solve *both* problems:

```diff
diff --git a/lua/configs/better_escape.lua b/lua/configs/better_escape.lua
index 91d129c..396acea 100644
--- a/lua/configs/better_escape.lua
+++ b/lua/configs/better_escape.lua
@@ -4,7 +4,7 @@ function M.config()
   local present, better_escape = pcall(require, "better_escape")
   if present then
     better_escape.setup(require("core.utils").user_plugin_opts("plugins.better_escape", {
-      mapping = { "ii", "jj", "jk", "kj" },
+      mapping = { "jk"},
     }))
   end
 end
~/.config/nvim main ⇣2
```

**Comment by mehalter** [comment]
@AXGKl please check out the latest version of AstroNvim as this has been addressed. We are not setting these extra bindings anymore and just taking the default `better-escape` bindings which are `jk` and `jj`. If these don't meet your needs feel free to add an override to your user config

@rafaelderolez I don't think better-escape actually integrates with the terminal insert mode but I will need to verify this. We do have default mappings in the terminal mode that you can delete and see if it improves your user config in your `polish` function:

```lua
vim.keymap.del("t', "<esc>")
vim.keymap.del("t", "jk")
```

**Comment by mehalter** [comment]
https://github.com/max397574/better-escape.nvim/issues/23

Ah this verifies that better-escape does not affect terminals

**Comment by mehalter** [comment]
I'll discuss with @kabinspace some more about these default terminal bindings. It's one of the first things I disabled as well moving to AstroNvim and I think it would be a good idea to remove them or change them

**Comment by AXGKl** [comment]
@mehalter works perfectly out of the box now. also the terminal mode.

@rafaelderolez   An asciinema recording would be nice indeed - could not reproduce any slowness in lazygit - this is with current version (1fe1a5f7c478f9e82de8bfe8df8b424a109b3ce4) of AstroVim: 

https://asciinema.org/a/98t5epiaqbwXS18rEo47TYBBS
