### ISSUE TITLE
can not change fontsize

### ISSUE THREAD

**Issue by roverway** [AstroNvim/AstroNvim#521]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0

all above has been done.

**Describe the bug**
I use neovide, my init.lua like this, font type has been changed but font size not
![图片](https://user-images.githubusercontent.com/657850/167985990-b595c6af-e031-4e2e-a632-3fb01598197e.png)

**Comment by mehalter** [comment]
What terminal are you using? This might be a setting you need to change with your terminal instead of inside of neovim

**Comment by roverway** [comment]
> 

I'm using windows terminal preview in Windows 11, I can change font type and size in terminal's config menu.
What confused me is the font size can not be changed when I use neovim's gui (double click neovide.exe).
I have tried NvChad, `vim.opt.guifont = "FiraCode_Nerd_Font_Mono:h12"` worked in neovide.exe。
I like AstroNvim's keybings, but I'm not a programmer, I have no idea to fix this by myself.

**Comment by roverway** [comment]
I tried type the vim command in command line, it works.
May be something wrong when processing `usr/init.lua` file
![图片](https://user-images.githubusercontent.com/657850/168031810-6495051c-92b9-415d-99e8-40347bda6f95.png)

**Comment by roverway** [comment]
Fixed.
When I put the font-related lines out of the `local config = {}`, it OK now.
Hope the information is useful, thank you~
![图片](https://user-images.githubusercontent.com/657850/168033445-25080dab-0880-4840-8634-ae4fbe24d4cc.png)

**Comment by mehalter** [comment]
@roverway those can be set in the original place you had them, but you were seeing them to the incorrect string. The screenshot you sent shows the correct format

**Comment by roverway** [comment]
> 

Got it, Thank you!
