### ISSUE TITLE
Issue with Comment.api after fresh start

### ISSUE THREAD

**Issue by novito** [AstroNvim/AstroNvim#527]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0

**Describe the bug**
When trying to comment a line by doing `Space + /` I get an error `E5108: Error executing lua: /Users/novito/.config/nvim/lua/core/mappings.lua:51: module 'Comment.api' not found`.

**To Reproduce**
Open any type of file (I've tried with `.ts`, `.html` and `.txt`) and trying to comment on a line by doing `Space +/`, I see this error:

```
E5108: Error executing lua: /Users/novito/.config/nvim/lua/core/mappings.lua:51: module 'Comment.api' not found:
        no field package.preload['Comment.api']
        no file './Comment/api.lua'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20220411/share/luajit-2.1.0-beta3/Comment/api.lua'
        no file '/usr/local/share/lua/5.1/Comment/api.lua'
        no file '/usr/local/share/lua/5.1/Comment/api/init.lua'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20220411/share/lua/5.1/Comment/api.lua'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20220411/share/lua/5.1/Comment/api/init.lua'
        no file '/Users/novito/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/Comment/api.lua'
        no file '/Users/novito/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/Comment/api/init.lua'
        no file '/Users/novito/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/Comment/api.lua'
        no file '/Users/novito/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/Comment/api/init.lua'
        no file './Comment/api.so'
        no file '/usr/local/lib/lua/5.1/Comment/api.so'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20220411/lib/lua/5.1/Comment/api.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/Users/novito/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/Comment/api.so'
        no file './Comment.so'
        no file '/usr/local/lib/lua/5.1/Comment.so'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20220411/lib/lua/5.1/Comment.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/Users/novito/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/Comment.so'
stack traceback:
        [C]: in function 'require'
        /Users/novito/.config/nvim/lua/core/mappings.lua:51: in function </Users/novito/.config/nvim/lua/core/mappings.lua:50>
```        
**Expected behavior**
I would expect to be able to comment on my code.

**Screenshots**
If applicable, add screenshots or recording ([Asciinema](asciinema.org)) to help explain your problem.

**Additional context**

**Comment by mehalter** [comment]
Ah thank you so much for reporting! We recently added some lazy loading for Comment and this slipped through the cracks.

**Comment by novito** [comment]
@mehalter even after running `AstroUpdate` and `PackerSync`, I still get the same error. Thoughts?

**Comment by mehalter** [comment]
Did you make sure to restart in-between running each command? Restart after the AstroUpdate then restart after PackerSync

**Comment by novito** [comment]
@mehalter what do you mean by restart?

**Comment by mehalter** [comment]
`:q` and then running `nvim`, like restart neovim

**Comment by novito** [comment]
@mehalter working now :) I restarted after the two commands, not in between!
