### ISSUE TITLE
Opening path of a directory opens an empty file with the same path of the directory.

### ISSUE THREAD

**Issue by zoritle** [AstroNvim/AstroNvim#530]
**Checklist**
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0

**Describe the bug**
Opening path of a directory opens an empty file with the same path of the directory.

**To Reproduce**
open any directory
```
nvim .config/nvim
:wq
```

**Expected behavior**
Open that directory

**Screenshots**
![clip](https://user-images.githubusercontent.com/66551926/168322223-cb22eaa0-9b32-4502-a896-141b0a7c9938.png)

**Additional context**
BTW, could you please provide a default theme for white background terminal,or a theme that use terminal provided color to adopt terminal color scheme?

**Comment by zoritle** [comment]
Another question, press SPC+e will open file explorer in $PWD, how to open parent directory of the currently opened file?

**Comment by mehalter** [comment]
@zoritle this is not actually a bug, but is due to us lazy loading `neo-tree` to improve the startup time. You can disable this lazy loading by adding this to your `user/init.lua`:

```lua
return {
  plugins = {
    init = {
      ["nvim-neo-tree/neo-tree.nvim"] = { module = "", cmd = "" },
    },
  },
}
```

Also for your background question, the `default_theme` has the ability to arbitrarily override the provided highlights. You can use this to get the behavior you are looking for adding something like this to your `user/init.lua`:

```lua
return {
  default_theme = {
    highlights = function(hi)
      local C = require "default_theme.colors"
      hi.Normal = { bg = C.none, ctermbg = C.none }
      hi.CursorColumn = { cterm = {}, ctermbg = C.none, ctermfg = C.none }
      hi.CursorLine = { cterm = {}, ctermbg = C.none, ctermfg = C.none }
      hi.CursorLineNr = { cterm = {}, ctermbg = C.none, ctermfg = C.none }
      hi.LineNr = {}
      hi.SignColumn = {}
      hi.StatusLine = {}
      return hi
    end,
  },
}
```

**Comment by abalmos** [comment]
> @zoritle this is not actually a bug, but is due to us lazy loading `neo-tree` to improve the startup time.

For what it is worth, it really feels like a bug to me. I have be wondering why everything glitches so much when I open a folder.

**Comment by mehalter** [comment]
I'm going to go ahead and reopen this as I'm going to work on getting a proper fix  here put together that respects the lazy loading.
