### ISSUE TITLE
LSP hover window

### ISSUE THREAD

**Issue by auser** [AstroNvim/AstroNvim#531]
Hi AstroVim team,

I have a curious "issue" where whenever I have any customization, e.g. `lua/user/init.lua`, the ability for me to use the LSP hover window disappears. When I remove the user directory, however it's available. 

Where might this functionality from the LSP be getting lost?

**Comment by mehalter** [comment]
Could you share your `user/init.lua`? A link to a repo if you have one or just paste it here preferably as minimal as you can to replicate the behavior.

**Comment by auser** [comment]
This is my minimal `user/init.lua`:

```lua
local config = {

  -- Set colorscheme
  colorscheme = "default_theme",

  -- set vim options here (vim.<first_key>.<second_key> =  value)
  options = {
    opt = {
    },
    g = {
      mapleader = " ", -- sets vim.g.mapleader
    },
  },

  -- Configure plugins
  plugins = {
    init = {
      {"simrat39/rust-tools.nvim"},
    },
    telescope = {
      defaults = {
        file_ignore_patterns = {
          "node_modules",
          "**/target/**"
        }
      }
    }
  },
}

return config
```

Also, the `file_ignore_patterns` in `telescope` isn't filtering out the "target"

**Comment by mehalter** [comment]
I think you need to use `lua` regex patterns for this: https://github.com/nvim-telescope/telescope.nvim/blob/39b12d84e86f5054e2ed98829b367598ae53ab41/doc/telescope.txt#L652

Please check out the `telescope` docs.
