### ISSUE TITLE
Create `/user` folder when explaining how to create user configuration (in documentation)

### ISSUE THREAD

**Issue by novito** [AstroNvim/AstroNvim#532]
**Is your feature request related to a problem? Please describe.**
The Managing User Configuration documentation could be more explicit on one of the commands. 

When we say `Copy the example init.lua file provided with AstroNvim to your user directory:`, if the `/user/` directory doesn't exist in ` ~/.config/nvim/lua`, the command `cp ~/.config/nvim/lua/user_example/init.lua ~/.config/nvim/lua/user/init.lua` will fail.

**Describe the solution you'd like**

The command could be `mkdir ~/.config/nvim/lua/user && cp ~/.config/nvim/lua/user_example/init.lua ~/.config/nvim/lua/user/init.lua` so we create the directory if it doesn't exist (by default when AstroVim is cloned, we don't create the `/user` directory).

**Additional context**

**Comment by mehalter** [comment]
Thanks for pointing this out! Will definitely fix this

**Comment by mehalter** [comment]
@novito resolved with https://github.com/AstroNvim/astronvim.github.io/commit/f487d9a07a0d6fbeb756753c05fa71a6c983e37a
