### ISSUE TITLE
Treesitter Folding

### ISSUE THREAD

**Issue by jayp0521** [AstroNvim/AstroNvim#533]
Hello,

I was wondering if you had an easy way to enable [Treesitter Folding](https://github.com/nvim-treesitter/nvim-treesitter#folding)

I ran the commands in neovim manually and they worked fine.

I tried adding it to the config and couldn't get it to work

**Comment by mehalter** [comment]
Hey, here is a minimal `user/init.lua` file:

```lua
return {
  options = {
    opt = {
       foldexpr = "nvim_treesitter#foldexpr,
       foldmethod = "expr",
    },
  },
}
```

**Comment by CrowderSoup** [comment]
I know this issue is closed but I've tried the suggested config here and treesitter folding doesn't seem to be working _at all_. I'm not sure if this is an issue with my own setup, AstroVim, or Treesitter itself.

**Comment by mehalter** [comment]
@CrowderSoup could you please share you user config either just paste it in here or share a link to your user config repo (if you have one) and I can take a look

**Comment by CrowderSoup** [comment]
Here's my config:

```lua
local config = {

  -- Configure AstroNvim updates
  updater = {
    remote = "origin", -- remote to use
    channel = "stable", -- "stable" or "nightly"
    version = "latest", -- "latest", tag name, or regex search like "v1.*" to only do updates before v2 (STABLE ONLY)
    pin_plugins = nil, -- nil, true, false (nil will pin plugins on stable only)
    skip_prompts = false, -- skip prompts about breaking changes
    show_changelog = true, -- show the changelog after performing an update
  },

  -- Set colorscheme
  colorscheme = "default_theme",

  options = {
    opt = {
      relativenumber = false, -- sets vim.opt.relativenumber
      foldmethod = "expr",
      foldexpr = "nvim_treesitter#foldexpr()",
    },
  },
}

return config
```

I tried with and without the `()` on the `foldexpr` as I was seeing other sources showing it with them. I left `relativenumber` just to see if it was something with the config but that setting worked. So I'm not sure why the folding ones aren't. I did verify that they are being set correctly when nvim loads as well.

**Comment by mehalter** [comment]
@CrowderSoup  Have you installed any treesitter parsers? and can you verify that treesitter is running in the files you have opened? You should see something like this in the bottom right with the `TS`:
![2022-06-13_15:06:26_screenshot](https://user-images.githubusercontent.com/1591837/173426554-ffc0062c-c761-44f0-b932-08f0d4cd03da.png)

**Comment by xiaojia21190** [comment]
foldmethod = "expr",
doesn't work
will revert to foldmethod="manual"
