### ISSUE TITLE
Column-number indicator  on the feline status line annoyingly shifts when moving cursor

### ISSUE THREAD

**Issue by krishnakumarg1984** [AstroNvim/AstroNvim#535]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0

**Describe the bug**
The padding/right alignment of the column-number indicator in the status line (feline) annoyingly shifts when moving the cursor. This is leading to a flickering experience. It would be best to allocate 3 digits to the column number indicator and right align it (and left pad with blanks appropriately).

**Screenshots**

Look at the wobbly status line in the screen recording (link below):

https://asciinema.org/a/o7slP5C1DU2osqslaOCsy6VEF

**Comment by mehalter** [comment]
I don't really think I consider this a bug or an issue so I'm going to mark this as "wontfix" and leave it open for a bit if a bunch of people fine this to be a problem and want to open a PR

**Comment by mehalter** [comment]
I am going to go ahead and close this. If anything I think this should be resolved upstream with Feline as a "bug fix" in their default provider.
