### ISSUE TITLE
Prompt on closing unsaved buffers with `<leader>c`

### ISSUE THREAD

**Issue by cshuaimin** [AstroNvim/AstroNvim#536]
**Is your feature request related to a problem? Please describe.**
I accidentally closed an unsaved buffer with `<leader>c` and then I lost all the code I just wrote without warning. Fortunately, that's not a lot. I believe it's much better to show a prompt asking the user if they want to close without saving.

**Describe the solution you'd like**
Show a prompt or just remove `!` from `bdelete!`.

**Comment by mehalter** [comment]
Thanks for pointing this out! I would definitely consider this a bug. I have opened a PR to resolve this. Thanks again!
