### ISSUE TITLE
Telescope-fzf-native specified module not found

### ISSUE THREAD

**Issue by Johnsiras** [AstroNvim/AstroNvim#543]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0

**Describe the bug**
When trying to search with `telescope fzy native` it throws the following error:
```
Error running config for telescope-fzf-native.nvim: ...er\opt\telescope.nvim/lua/telescope/_extensions/init.l
ua:10: 'fzf' extension doesn't exist or isn't installed: ...ack\packer\opt\telescope-fzf-native.nvim/lua/fzf_lib.lua:11: cannot load module 'C:\Users
\xxxx\AppData\Local\nvim-data\site\pack\packer\opt\telescope-fzf-native.nvim/lua/../build/libfzf.dll': The specified module could not be found.
```
Is there anyway to reinstall it?

**To Reproduce**
1. Launch nvim
2. Do some `Spc f o` or any mapping that finds a file

**Expected behavior**
Search a file without any error

**Screenshots**
![alacritty_jbyK4byA81](https://user-images.githubusercontent.com/102006493/168942339-71770ebf-0d40-4b54-bdeb-83c1662e38df.gif)

**Comment by Johnsiras** [comment]
I think this is not a bug but rather a missing file problem or smth.

**Comment by roverway** [comment]
> **Checklist** Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
> 
>     * [x]  `:PackerSync`
> 
>     * [x]  `:AstroUpdate`
> 
>     * [x]  restarted AstroNvim
> 
>     * [x]  Neovim version >= 0.7.0
> 
> 
> **Describe the bug** When trying to search with `telescope fzy native` it throws the following error:
> 
> ```
> Error running config for telescope-fzf-native.nvim: ...er\opt\telescope.nvim/lua/telescope/_extensions/init.l
> ua:10: 'fzf' extension doesn't exist or isn't installed: ...ack\packer\opt\telescope-fzf-native.nvim/lua/fzf_lib.lua:11: cannot load module 'C:\Users
> \xxxx\AppData\Local\nvim-data\site\pack\packer\opt\telescope-fzf-native.nvim/lua/../build/libfzf.dll': The specified module could not be found.
> ```
> 
> Is there anyway to reinstall it?
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Launch nvim
> 
>     2. Do some `Spc f o` or any mapping that finds a file
> 
> 
> **Expected behavior** Search a file without any error
> 
> **Screenshots** ![alacritty_jbyK4byA81](https://user-images.githubusercontent.com/102006493/168942339-71770ebf-0d40-4b54-bdeb-83c1662e38df.gif)

I had the same problem

**Comment by mehalter** [comment]
@Johnsiras @roverway could you please check out the PR #545 and see if that resolves the issue on Windows?

**Comment by koslak** [comment]
Hi, for those who are facing this issue on Windows, what is happening is that the _telescope-fzf-native.nvim_ plugin is not being built. You can check this by doing this:

1. Open a CMD window and go to the plugin's folder:

`> cd %AppData%\..\Local\nvim-data\site\pack\packer\opt\telescope-fzf-native.nvim`

2. Go to the `build` folder and then you will see that is empty. 

**The following are the steps that I did to make it work:** 

1. Open a CMD window and go to the plugin's folder:

`> cd %AppData%\..\Local\nvim-data\site\pack\packer\opt\telescope-fzf-native.nvim`

2. Run the following command (make sure you have the dependencies installed (like cmake) to build this plugin):

`> cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release && cmake --build build --config Release && cmake --install build --prefix build`

**Note:** The instruction above is from the Github repository: [telescope-fzf-native.nvim github](https://github.com/nvim-telescope/telescope-fzf-native.nvim#cmake-windows-linux-macos).

3. Make sure the plugin was built. Go to the folder:

`> cd %AppData%\..\Local\nvim-data\site\pack\packer\opt\telescope-fzf-native.nvim\build\Release`
`> dir`

and now you should see the following files: 

```
24-Feb-23  11:27 PM    <DIR>          .
24-Feb-23  11:27 PM    <DIR>          ..
24-Feb-23  11:27 PM             2,796 fzf.exp
24-Feb-23  11:27 PM             4,620 fzf.lib
24-Feb-23  11:27 PM            22,016 libfzf.dll
               3 File(s)         29,432 bytes
```

4. Now open Nvim and run the command `:PackerSync`
