### ISSUE TITLE
Snippets not working with setup as shown on the AstroNvim website

### ISSUE THREAD

**Issue by Noxdor** [AstroNvim/AstroNvim#547]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0

**Describe the bug**
Since a while, snippets aren't working for me anymore, though I changed nothing about my user config. I looked into the config again and searched for something I did wrong, but it is exactly configured as described [here](https://astronvim.github.io/recipes/snippets).

**To Reproduce**
1. Setup an example snippet like on the link above (in my case a vue snippet) for vs-code-templating.
2. Create a package.json and reference the snippet file there.
3. Load the package.json / the snippets folder with your `lua/user/init.lua` file.
4. Open a fitting file (again, in my case vue) and type to see if the snippet shows.
5. It doesn't, at least for me.

**Expected behavior**
Snippet being shown to select it and insert it into the file.

**Setup**
*lua/user/init.lua*
```lua
return {
  luasnip = {
    vscode_snippet_paths = {
      "./lua/user/snippets",
    },
  },
}

```

*lua/user/snippets/package.json*
```json
{
  "name": "personal snippets",
  "engines": {
    "vscode": "^1.11.0"
  },
  "contributes": {
    "snippets": [ 
      {
        "language": "vue",
        "path": "./vue.json"
      },
      {
        "language": "vue",
        "path": "./quasar.json"
      }, 
    ]
  }
}
```

*lua/user/snippets/vue.json*
```json
{
  "setup": {
		"prefix": ["setup", "template"],
		"body": ["<template>",
				"\t$1",
				"</template>",
				"",
				"<script lang=\"ts\" setup>",
				"\t$2",
				"</script>",
				"",
				"<style lang=\"sass\" scoped>",
				"\t$3",
				"</style>",
				""
		],
		"description": "My standard setup Vue3 + TS"
	} 
}
```

**Additional context**
I freshly installed AstroNvim after the rebranding from AstroVim.

**Comment by mehalter** [comment]
@Noxdor I cannot recreate this bug. Does `quasar.json` exist on your system? If that file does not exist then the snippets will not be loaded and you didn't include that file in your description of the environment.

I just tested the exact code you sent (with the addition of the prefix "TEST" in the `vue.json` for the `setup` snippet) with a fresh installation of AstroNvim in a clean environment to guarantee no lingering files or anything along with the following file

*lua/user/snippets/quasar.json*

```lua
{
  "setup": {
    "prefix": ["TEST2"],
    "body": [
      "<template>",
      "\t$1",
      "</template>",
      "",
      "<script lang=\"ts\" setup>",
      "\t$2",
      "</script>",
      "",
      "<style lang=\"sass\">",
      "\t$3",
      "</style>",
      ""
    ],
    "description": "My standard setup Vue3 + TS"
  }
}
```

![2022-05-18_10:25:29_screenshot](https://user-images.githubusercontent.com/1591837/169065302-470e07db-4562-4aed-8212-5339cce2e9c5.png)

**Comment by Noxdor** [comment]
The file `quasar.json` exists and is at the right location. I left it out, because it is very long, I should have mentioned it anyway, sorry!
I tried it with removing it from the `package.json`, I tried it with adding an extra *TEST* prefix to the vue setup example like you did, nothing. It is very strange since this used to work without problems for me. I will try it tomorrow or so with a fresh install. Only way I can explain this to myself is that some dependency change broke it, but I am not deep enough into nvim nor the details of this project to verify that.
Anyway, let's see how it goes with a fresh install :)

**Comment by mehalter** [comment]
There could be some other type of syntax error in your snippets files somewhere. If there is any error in them, they just won't load. But I triple checked today and I'm sure the AstroNvim integration is working. I would recommend trying with a fresh user folder with a minimal setup and see if it works then. They report back for sure if for some reason it's not working :)

**Comment by mehalter** [comment]
@Noxdor any luck on this?

**Comment by Noxdor** [comment]
Nope, it is still not working. I tried it with a fresh install and a minimal setup, it is still not working. I thought there might be some cached resource that is causing the problem, I found a folder in .local/share called nvim that seems to save lsps etc. I backed that one up and tried it again, the language servers where gone and I had to run PackerSync again. Still, snippets are not working for me 🤔 Is there any other folder that caches resources for nvim or astronvim? Anything else I can try?

**Comment by mehalter** [comment]
Hm, this is quite strange as I can't replicate the issue. There shouldn't be anything getting cached with this that are interfering. You could try deleting `~/.cache/nvim` and see if that fixes anything. Are you using neovim 0.7 stable or nightly? Also what operating system are you using?

**Comment by mehalter** [comment]
oops, didn't mean to close this yet. I went ahead and merged that cmp lazy loading  change as it's definitely how we should be doing the lazy loading. I'm curious to see if it has an effect on your snippet issue

**Comment by Noxdor** [comment]
I tried deleting `~/.cache/nvim` but it didn't help. I am on Garuda Linux (Arch) running the Linux Zen Kernel (5.17.9-zen1-1-zen). I am running the stable 0.7 version of nvim.
```
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
```

I ran :AstroUpdate and :PackerSync (since you wrote you merged the changes into main), restarted nvim, still not working. I tried it in a different vue project with different setup, nothing. I am starting to really feel stupid, I can't think what is causing this 😂

**Comment by mehalter** [comment]
Hm...... I'm starting to feel stupid about it too :joy: I have no idea what could be causing this ://///

**Comment by mehalter** [comment]
It looks like this is a problem that is just plaguing users of `luasnip`: https://github.com/L3MON4D3/LuaSnip/issues/281

**Comment by mehalter** [comment]
For now, do you think you could just try adding this to your `init.lua` instead of using that one options section?

```lua
return {
  plugins = {
    init = {
      ["L3MON4D3/LuaSnip"] = { module = "" },
    },
  },
  polish = function()
    require("luasnip/loaders/from_vscode").load { paths = { "./lua/user/snippets" } }
  end,
}
```

**Comment by mehalter** [comment]
Actually @Noxdor could you try this? and see if it works?

```lua
return {
  plugins = {
    init = {
      ["L3MON4D3/LuaSnip"] = { module = "" },
    },

    luasnip = {
      vscode_snippet_paths = {
        "./lua/user/snippets",
      },
    },
  },
}
```

This is a shot in the dark and if this works I will be next level confused :joy: but the previous one I sent I believe should 1000000% fix it

**Comment by mehalter** [comment]
@Noxdor any luck with the latest code snippets?

**Comment by mehalter** [comment]
I'm going to close this as stale as I can't seem to replicate the issues and users with a similar problem can search and comment if they run into similar problems and we can reopen it.

**Comment by Johnsiras** [comment]
I have the same problem too, doing this solution
```lua
return {
  plugins = {
    init = {
      ["L3MON4D3/LuaSnip"] = { module = "" },
    },
  },
  polish = function()
    require("luasnip/loaders/from_vscode").load { paths = { "./lua/user/snippets" } }
  end,
}
```
doesn't even work it just throws `Undefined Variable`

**Comment by mehalter** [comment]
@Johnsiras did you run a `:PackerSync` that error looks like an issue with an out dated packer compile file.

**Comment by Johnsiras** [comment]
Hey @mehalter will you be able to fix this? I can't find any solution to fix it using your solution just throws an error

**Comment by mehalter** [comment]
I'll look back at the code I sent as a work around. I have been unable to replicate this issue on my end sadly after a lot of attempts and work on it. But I can keep investigating as I get time

**Comment by mehalter** [comment]
@Johnsiras I'm wondering if this is some bug upstream with luasnip since they have had a lot of bug reports from various users about custom snippet loading just not working in random cases like the issue I linked before. Hard to investigate and identify a problem to something I can't seem to recreate :( sorry!

**Comment by Noxdor** [comment]
Hey @mehalter, I was in holidays, will try your workaround soon, thanks! But if it is an upstream bug, there is not much you can do of course. Great also, that it appears to be kind of random and not able to replicate, gotta love those bugs! 😂

**Comment by mehalter** [comment]
Yeah the random nature of this issue also makes me think that it is something upstream since we aren't doing anything complicated or fancy here, just running the line of code they say we need to load custom snippets :(

**Comment by mehalter** [comment]
@Johnsiras I can see the error you are getting. It is due to you not doing a packer sync before putting the luasnip require in your polish function. If you just do a packer sync and restart it will work appropriately.

**Comment by mehalter** [comment]
Before you `:PackerSync` to remove the lazy loading of LuaSnip, you will not be able to require it from your polish function because it won't exist as a plugin until it is loaded. I have verified this with both stable and nightly neovim. Please try again with a `:PackerSync`

**Comment by mehalter** [comment]
Also the safer option here would be to try this code snippet: https://github.com/AstroNvim/AstroNvim/issues/547#issuecomment-1142566602 (the second one I linked. I am pretty sure that should work as well. If neither of those are working I am definitely going to say this is some weird upstream problem with LuaSnip.

**Comment by Johnsiras** [comment]
> Before you `:PackerSync` to remove the lazy loading of LuaSnip, you will not be able to require it from your polish function because it won't exist as a plugin until it is loaded. I have verified this with both stable and nightly neovim. Please try again with a `:PackerSync`

Yeah i'll try that

**Comment by Johnsiras** [comment]
@mehalter no it's still the same error i didn't put the code yet instead after i did `["L3MON4D3/LuaSnip"] = { module = "" }` and packer sync it just throws the same error even tho i didn't even defined the luasnip path :/

**Comment by mehalter** [comment]
I cannot recreate this behavior on stable or nightly. There must be some syntax error in your user configuration. Sorry :/

**Comment by mehalter** [comment]
@Johnsiras Have you tried with a minimal `user/init.lua` file:

```lua
return {
  plugins = {
    init = {
      ["L3MON4D3/LuaSnip"] = { module = "" },
    },
  },
}
```

**Comment by mehalter** [comment]
It's a good way to debug if it's truly a problem neither AstroNvim or your own user configuration

**Comment by Johnsiras** [comment]
> @Johnsiras Have you tried with a minimal `user/init.lua` file:
> 
> ```lua
> return {
>   plugins = {
>     init = {
>       ["L3MON4D3/LuaSnip"] = { module = "" },
>     },
>   },
> }
> ```

sure i'll try that, even tho i passed the plugin to my `user/plugins/init.lua`

**Comment by Johnsiras** [comment]
@mehalter so i just try the solution, the error was gone when i passed `plugins = {
    init = {
      ["L3MON4D3/LuaSnip"] = { module = "" },
    },` to my init.lua file and did `  luasnip = {
    vscode_snippet_paths = {
      "./lua/user/snippets",
    },
  },
` in my init.lua too but my custom snippets are not showing there's no errors?

**Comment by mehalter** [comment]
@Johnsiras did you add the snippets to your `lua/user/snippets` folder with the appropriate `package.json` and `json` files with the vs code style snippets?

**Comment by Johnsiras** [comment]
> @Johnsiras did you add the snippets to your `lua/user/snippets` folder with the appropriate `package.json` and `json` files with the vs code style snippets?

Yes

**Comment by mehalter** [comment]
Could you try the other code snippet where you put the loader in the `polish` function?

**Comment by Johnsiras** [comment]
> Could you try the other code snippet where you put the loader in the `polish` function?

Just tryed that earlier btw, and it seems it's throwing the same error.

**Comment by mehalter** [comment]
You tried it now? Or you just tried it earlier? That error should not be there if you have appropriately done packer sync after that luasnip like in your plugins init table

**Comment by Johnsiras** [comment]
> 

After i did the first code snippet i tryed after that, yea it's still the same.

**Comment by mehalter** [comment]
Quite strange. I can't replicate that behavior, but I can't take another look over the next few days

**Comment by mehalter** [comment]
I wonder if that error is coming from syntax errors in your snippet file definitions.

**Comment by mehalter** [comment]
Either syntax error in your snippet json files or referencing files that don't exist in the `package.json`

**Comment by Johnsiras** [comment]
> I wonder if that error is coming from syntax errors in your snippet file definitions.

no it isn't....

**Comment by Noxdor** [comment]
@mehalter Neither of the two suggested solutions are working for me :( And yes, I PackerSynced the hell out of my Nvim in between :p Other than @Johnsiras I am also not getting any error message trying your suggested solutions. I also read the thread over at LuaSnip, I guess this issue is simply gonna resolve after a while once they found the bug upstream.

**Comment by mehalter** [comment]
Glad to hear the snippets don't cause any errors. Sad to hear they aren't fixing anything :( this is most certainly a bug upstream which is unfortunate :/ hopefully it gets fixed one day

**Comment by Johnsiras** [comment]
> @mehalter Neither of the two suggested solutions are working for me :( And yes, I PackerSynced the hell out of my Nvim in between :p Other than @Johnsiras I am also not getting any error message trying your suggested solutions. I also read the thread over at LuaSnip, I guess this issue is simply gonna resolve after a while once they found the bug upstream.

that's so weird i literally tryed it with neovim 0.7.1 and 0.7.0 but i causes the same error

**Comment by Noxdor** [comment]
Wow I hate my life. I just figured out what was the problem all the long time ago and wanted to share for anyone running into the same problem.
What was the issue for me? A comma. To be precise, a dangling comma. JSON doesn't allow dangling commata.

So my `package.json` file was:
```json
{
  "name": "user snippets",
  "engines": {
    "vscode": "^1.11.0"
  },
  "contributes": {
    "snippets": [ 
      {
        "language": "vue",
        "path": "./vue.json"
      },
    ]
  }
}
```

but should have been
```json
{
  "name": "user snippets",
  "engines": {
    "vscode": "^1.11.0"
  },
  "contributes": {
    "snippets": [
      {
        "language": "vue",
        "path": "./vue.json"
      }
    ]
  }
}
```

Can you spot it? Anyway, snippets are working like a charm and I got a piece of my sanity back!

**Comment by mehalter** [comment]
Ohhhhhh, so it was a syntax error in the `package.json` :joy: I am so glad I wasn't going crazy! I'm glad you found the issue! I guess I never ran into that copying/pasting your code because I had LSP stuff running that would fix those formatting and small syntax errors haha

**Comment by Noxdor** [comment]
@mehalter I should definitely get that going for myself as well 😂

**Comment by johnsiras** [comment]
Hey @Noxdor are you on linux right? Even tho i **look** at my `package.json` *5* times there's no syntax errors at all and i'm going crazy about it of why i'm still not getting any snippets :/

**Comment by Noxdor** [comment]
Hey @johnsiras yes I am on Arch (Garuda) Linux.

My 2 suggestions:
1. I can see you set tried mehalters solution with polish etc., that wasn't it for me, so maybe just revert it to "clean" way I posted in the first post / you can find in the AstroNvim docs
2. I also **looked** at my package.json like 100 times or more! I would have never found this if I didn't copy it from the docs again, just to check my sanity. Maybe you just try that and maybe you also try it with a clean snippets file that someone else created and is proven. If that still doesn't solve it, idk man! I think some error messages in the direction of "your snippet/package file has a syntax error" would be amazing, but that has to happen in LuaSnip.

**Comment by johnsiras** [comment]
> Hey @johnsiras yes I am on Arch (Garuda) Linux.
> 
> My 2 suggestions:
> 
> 1. I can see you set tried mehalters solution with polish etc., that wasn't it for me, so maybe just revert it to "clean" way I posted in the first post / you can find in the AstroNvim docs
> 2. I also **looked** at my package.json like 100 times or more! I would have never found this if I didn't copy it from the docs again, just to check my sanity. Maybe you just try that and maybe you also try it with a clean snippets file that someone else created and is proven. If that still doesn't solve it, idk man! I think some error messages in the direction of "your snippet/package file has a syntax error" would be amazing, but that has to happen in LuaSnip.

Hi! Thanks for replying that fast, yes i tried mehalter's solutions but that didn't worked for me and i reverted it again on my "clean" way that you're saying... And **ALL** of my snippets/package file has no syntax errors! As i have a formatter that already formats the code and i still don't know why it doesn't work!

This is still going me crazy :/

**Comment by Noxdor** [comment]
Well, that really sucks! Maximum you could do is try it with a fresh install and confirm it works with the smallest possible setup. Then slowly add snippets and see if it breaks somewhere. I know you have a formatter, but you know, they're wrote by humans too, you never know! Maybe something is throwing off LuaSnip. I really don't know, it sounds too strange that with everything you're mentioning it isn't working 😬 I would try it with a clean setup and add more content to it step by step until it breaks (or doesn't and you can be happy / even more confused).

**Comment by johnsiras** [comment]
> Well, that really sucks! Maximum you could do is try it with a fresh install and confirm it works with the smallest possible setup. Then slowly add snippets and see if it breaks somewhere. I know you have a formatter, but you know, they're wrote by humans too, you never know! Maybe something is throwing off LuaSnip. I really don't know, it sounds too strange that with everything you're mentioning it isn't working 😬 I would try it with a clean setup and add more content to it step by step until it breaks (or doesn't and you can be happy / even more confused).

Welp, i already **did** a fresh install and just like you said... I still don't know **WHERE** and **WHAT** is causing the snippets to not be working.

**Comment by mehalter** [comment]
@johnsiras I would definitely recommend trying to show a minimal setup that demonstrates the bug. That at least gives me something to go off of. Remove all of your own custom plugins and show it doesn't work with a minimum number of snippets and stuff and we can start figuring out if there is a bug here or something else is going on.

**Comment by johnsiras** [comment]
> @johnsiras I would definitely recommend trying to show a minimal setup that demonstrates the bug. That at least gives me something to go off of. Remove all of your own custom plugins and show it doesn't work with a minimum number of snippets and stuff and we can start figuring out if there is a bug here or something else is going on.

I'll do that tommorow as it's already late here for me. I'll try to remove my custom plugins first then show you :)

**Comment by johnsiras** [comment]
Hey @mehalter! I was able to test without the custom plugins or has **AND** the issue was... path was not added!!!

I was so so so **SO** stupid and blind that i didn't even set that with my clean way... but for some reason i setted that on my `user/init.lua` so i messes with clean way.

I'm so so so sorry @mehalter for making this discussion to be long and please forgive me :(
