### ISSUE TITLE
Set default formatter

### ISSUE THREAD

**Issue by yofriadi** [AstroNvim/AstroNvim#551]
Hi, how to set default formatter for a specific file type?
so I don't have to choose evertime I saving a file

![Screen Shot 2022-05-22 at 12 12 30](https://user-images.githubusercontent.com/24536844/169679870-8199dcd3-ec30-449e-8c9b-05de92b8cd27.png)

**Comment by mehalter** [comment]
You can do something like the following in your `user/init.lua` file to disable document formatting capabilities for specific clients. The following example would disable formatting for `gopls` and therefore always select `null-ls` by default:

```lua
return {
  lsp = {
    on_attach = function(client, bufnr)
      if client.name == "gopls" then
        client.resolved_capabilities.document_formatting = false
      end
    end,
  }
}
```
