### ISSUE TITLE
[QUESTION] change color scheme?

### ISSUE THREAD

**Issue by Kindlewing** [AstroNvim/AstroNvim#552]
Maybe I missed this in the docs, but how do I change the colorscheme from default to something else?

**Comment by alepop** [comment]
@Kindlewing you can see it in the recipes section https://astronvim.github.io/recipes/colorscheme

**Comment by adsick** [comment]
Hi, I tried that official recipe, but the colorscheme is still set to default, I feel frustrated...
![image](https://user-images.githubusercontent.com/24528839/183081375-d9ae4a90-7029-4d68-afb6-f0fd5465cad2.png)
![image](https://user-images.githubusercontent.com/24528839/183081439-f1dfa345-9b20-4b80-876c-0b2b5a533a17.png)
![image](https://user-images.githubusercontent.com/24528839/183081533-28e89044-3167-4580-830f-2d8ee50bf04e.png)

**Comment by mehalter** [comment]
@adsick have you run a `:PackerSync` to install catppuccin and then restart?

**Comment by adsick** [comment]
catpuccin is installed, I doublechecked that. The issue is that for some reason 'colorscheme' variable is set to default_theme regardless.

**Comment by adsick** [comment]
I can manually set colorscheme to catpuccin and it will work, but I don't get why it doesn't set by the user/init.lua script

**Comment by mehalter** [comment]
In your screenshot you have mispelled `catppuccin` could that be the issue? @adsick

**Comment by adsick** [comment]
@mehalter thanks a lot, now it works!
