### ISSUE TITLE
Feline user config is ignored after update to the latest (791c4b2) commit

### ISSUE THREAD

**Issue by dragosboca** [AstroNvim/AstroNvim#555]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0

**Describe the bug**
After upgrading to the latest feline version the status bar config defaults to the package config ignoring my customizations or AstroNvim defaults.

**To Reproduce**
Steps to reproduce the behaviour:
1. Sync packages
2. Restart nvim 

**Expected behavior**
The status bar should remain unchanged

**Screenshots**
If applicable, add screenshots or recording ([Asciinema](asciinema.org)) to help explain your problem.

**Additional context**

**Comment by mehalter** [comment]
@dragosboca I cannot recreate this on my end. Could you please explain this bug more or try again?

**Comment by dragosboca** [comment]
Sorry, it was the classic issue between monitor and chair. In my config, I was calling `feline.setup` one more time hence the behaviour I reported. Once I eliminated the call, everything worked fine.
