### ISSUE TITLE
null-ls prettier formatter stoped working after update

### ISSUE THREAD

**Issue by convers39** [AstroNvim/AstroNvim#558]
After the recent update with `:AstroUpdate` command a few days (about 1 week) ago, I found that the formatter does not work suddenly.

This happened just after I run the update, I used to have ls show as `tsserver, prettier, cspell, eslint` at the bottom status bar, but now only get `tsserver, eslint`. So `cspell` is actually not working either.

<img width="471" alt="image" src="https://user-images.githubusercontent.com/42597395/170190703-a210d4aa-2afb-48ce-8ffe-9092311f7971.png">

Another interesting issue after the update is that the floating terminal via `space t f` cannot be existed by pressing `esc`, I have to click with the mouse cursor somewhere in the background to hide the terminal.

Since I didn't change any setting before this update so really not sure about the reason... Here is my custom config.

Maybe just need a reinstallation?

https://github.com/convers39/astro-nvim-config/blob/master/init.lua

```lua
-- null-ls configuration
  ["null-ls"] = function()
    -- Formatting and linting
    -- https://github.com/jose-elias-alvarez/null-ls.nvim
    local status_ok, null_ls = pcall(require, "null-ls")
    if not status_ok then
      return
    end

    -- Check supported formatters
    -- https://github.com/jose-elias-alvarez/null-ls.nvim/tree/main/lua/null-ls/builtins/formatting
    local formatting = null_ls.builtins.formatting

    -- Check supported linters
    -- https://github.com/jose-elias-alvarez/null-ls.nvim/tree/main/lua/null-ls/builtins/diagnostics
    local diagnostics = null_ls.builtins.diagnostics
    local code_actions = null_ls.builtins.code_actions
    local completion = null_ls.builtins.completion

    null_ls.setup {
      debug = false,
      sources = {
        -- Set a formatter
        formatting.prettierd,
        formatting.rustfmt,
        formatting.lua_format,
        formatting.autopep8,
        -- formatting.black,
        -- Set a linter
        diagnostics.flake8,
        diagnostics.mypy,
        diagnostics.cspell,
        diagnostics.eslint,
        code_actions.refactoring,
        code_actions.eslint,
        code_actions.gitsigns,
        completion.spell
      },
      -- NOTE: You can remove this on attach function to disable format on save
      on_attach = function(client)
        if client.resolved_capabilities.document_formatting then
          vim.api.nvim_create_autocmd("BufWritePre", {
            desc = "Auto format before save",
            pattern = "<buffer>",
            callback = vim.lsp.buf.formatting_sync,
          })
        end
      end,
    }
```

**Comment by mehalter** [comment]
@convers39 We recently did a refactor on AstroNvim to clean up this plugin so it's not so special. Please check out the announcement thread for how to change this in your user config. I would also recommend subscribing to this issue so you can get notified of upcoming changes (breaking and non-breaking). Sorry for the inconvenience!

https://github.com/AstroNvim/AstroNvim/issues/427#issuecomment-1123959483
