### ISSUE TITLE
Weird things about autocompletion while using the snippet

### ISSUE THREAD

**Issue by RutaTang** [AstroNvim/AstroNvim#564]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0

**Describe the bug**
When I use autocompletion to generate snippet and delete the snippet before I fill the snippet placeholaders, while I then type some letters and presse \<ESC\>, the duplicates of what I have typed are generated, which is weird.

**To Reproduce**
1. Reinstall [AstroNvim](https://github.com/AstroNvim/AstroNvim) without any user customized config
2. Create a index.js file
3. In the index.js file: 
    (1): Enter insert mode: press Enter(\<CR\>) button 3 times (so that there are 4 lines)
    (2): Move to line 2
    (3): Enter insert mode: type `wid`,  then you will see `wid~` in autocompletion popmenu, and press Enter(\<CR\>)
    (4): It will generate
    ```
    let arrayIndex = array.length
    while (arrayIndex--) {
      
    }
    ```
   (5): Then, delete these codes by typing `d3j` in Normal Mode
   (6): Enter Insert mode: type anything, for example, typing `random`
   (7): Then, press \<ESC\>
   (8): **Weird things happend**: it will generate `randomrandomrandomrandom`

**Screenshots**

https://user-images.githubusercontent.com/24973657/170621500-029c2ad2-8817-4592-bc47-2b7427780f97.mp4

**Comment by mehalter** [comment]
@RutaTang could you check out the `cmp_cr` branch and see if you experience the same behavior?

**Comment by RutaTang** [comment]
> @RutaTang could you check out the `cmp_cr` branch and see if you experience the same behavior? (PR #563)

Hi @mehalter, It seems not. The #563 helps disable automatically selecting the autocompletion, while the weird thing I encounter is that  when I press \<ESC\>, it will weirdly duplicated what I have typed (I think it might be possibly related to nvim-cmp and snippet plugin). The whole steps to reproduce this behavior are all shown in the video.

**Comment by mehalter** [comment]
@RutaTang This seems to be a bug upstream either in luasnip or cmp or something. I have tested this with other neovim configs with cmp and luasnip and I get similar results:

https://asciinema.org/a/OMx5jhiZBqIN3BjSwtIBnT2QN

**Comment by mehalter** [comment]
I can definitely replicate this bug. It's weird though, it doesn't happen with every snippet and I can only seem to find snippets in Javascript that cause this behavior. It also is prevalent in a base neovim installation with just luasnip/cmp/friendly snippets installed so it's definitely not an AstroNvim bug and is upstream somewhere with one of those 3 plugins. @RutaTang I'm not sure the best way to debug this one on your end to identify which of those 3 plugins could be causing it. My gut instinct says that `LuaSnip` is causing it, but I'm not sure.

**Comment by RutaTang** [comment]
> it doesn't happen with every snippet and I can only seem to find snippets in Javascript that cause this behavior.

Yes, it seems that the issue even just followes with some of javascript snippets but not all of them, like `wid~` and `for~` but not `im~`.
