### ISSUE TITLE
Unable to change config for onedark theme

### ISSUE THREAD

**Issue by krshrimali** [AstroNvim/AstroNvim#565]
Hi, I'm trying to set up [one dark theme](https://github.com/navarasu/onedark.nvim) by navarasu, but I fail to use their styles. Here is how the file in `lua/user/init.lua` look like:

```lua
local config = {
  colorscheme = "onedark",

  plugins = {
      -- Add plugins, the packer syntax without the "use"
      init = {
        {
          "navarasu/onedark.nvim",
          config = function()
            -- vim.g.onedark_config.style = "light", (tried this as well)
            require('onedark').setup({style = 'deep'})
            require('onedark').load()
          end,
        },
        -- ... (and everything else)
  }
  -- (and everything else)
}
```

Can anyone please help with this? I'm not sure what's going wrong here.

**Comment by mehalter** [comment]
I tested it with this and it seems to be working as you would expect. Did you make sure to do a `:PackerSync` after editing the `config` function?

```lua
local config = {
  colorscheme = "onedark",

  plugins = {
      -- Add plugins, the packer syntax without the "use"
      init = {
        {
          "navarasu/onedark.nvim",
          config = function()
            require('onedark').setup({style = 'deep'})
            require('onedark').load()
          end,
        },
        -- ... (and everything else)
  }
  -- (and everything else)
}
```

**Comment by krshrimali** [comment]
> I tested it with this and it seems to be working as you would expect. Did you make sure to do a `:PackerSync` after editing the `config` function?
> 
> ```lua
> local config = {
>   colorscheme = "onedark",
> 
>   plugins = {
>       -- Add plugins, the packer syntax without the "use"
>       init = {
>         {
>           "navarasu/onedark.nvim",
>           config = function()
>             require('onedark').setup({style = 'deep'})
>             require('onedark').load()
>           end,
>         },
>         -- ... (and everything else)
>   }
>   -- (and everything else)
> }
> ```

Ah yes, you are absolutely right! I forgot to do `nvim +PackerSync`. My bad! Thank you so much, @mehalter - I'll close this issue now.
