### ISSUE TITLE
Neo-tree config does not match AstroNvim's documentation

### ISSUE THREAD

**Issue by Bear-03** [AstroNvim/AstroNvim#567]
I can see [here](https://astronvim.github.io/configuration/plugin_defaults#neo-tree) that `close_if_last_window` is supposed to be set to `true`, so AstroNvim should close automatically if neo-tree is the last window. However, this does not happen.

Looking further into [`lua/configs/neo-tree.lua`](https://github.com/AstroNvim/AstroNvim/blob/main/lua/configs/neo-tree.lua), `close_if_last_window` is never set to `true`, not matching what the docs say.

**Comment by mehalter** [comment]
Ah thanks for pointing this out!

**Comment by Bear-03** [comment]
Thanks for the fix!
