### ISSUE TITLE
Unable to remove default mapping

### ISSUE THREAD

**Issue by abshekh** [AstroNvim/AstroNvim#569]
Hi, I am trying to remove the following default mapping: 
```
Escape key | jj, jk
```

When trying to delete the keymap, I get an error.

Command to delete the keymap: 
```
:lua vim.keymap.del("i", "jk")
```

Error:
```
E5108: Error executing lua vim/keymap.lua:0: E31: No such mapping     
stack traceback:
        [C]: in function 'nvim_del_keymap'
        vim/keymap.lua: in function 'del'
        [string ":lua"]:1: in main chunk
```

However, when I press `jj` or `jk` in insert mode, it goes to normal mode.

Is there something I'm doing wrong?

**Comment by mehalter** [comment]
This is done by the plugin `better-escape`. You need to add something like this to your `user/init.lua`:

```lua
return {
  plugins = {
    init = {
      ["max397574/better-escape.nvim"] = { disable = true },
    },
  },
}
```
