### ISSUE TITLE
emmet for other filestypes than html

### ISSUE THREAD

**Issue by JavierDamico** [AstroNvim/AstroNvim#570]
Hi, how can I add emmet support for javascript, typescript, css, etc?. I've looked into the emmet-ls github but the config is too different and I don't understand how to add this feature.

**Comment by mehalter** [comment]
Can you do `:LspInstall emmet_ls`?

**Comment by JavierDamico** [comment]
I've already done that, but its working only for .html files. I want to make it work with other extensions like .js .jsx .css .ts .tsx.
That's what I was asking for, sorry if I didn't express myself clearly.

**Comment by mehalter** [comment]
ohhhh I see, you should be able to do something like this in your `user/init.lua`:

```lua
return {
  lsp = {
    server_settings = {
      emmet_ls {
        filetypes = {
          "html",
          "css",
          "javascript",
          "tsx",
          -- etc
        }
      }
    }
  }
}
```
