### ISSUE TITLE
Can't disable plugins for pyslp (language server)

### ISSUE THREAD

**Issue by krshrimali** [AstroNvim/AstroNvim#571]
Hi,

I'm using `pylsp` as my language server for Python extensions, and I want to get rid of some of the linting extensions, as it's too strict. I tried configuring it like below in `~/.config/nvim/init.lua`:

```lua
local lsp = require'lspconfig'

lsp.pylsp.setup {
  settings = {
    pylsp = {
      plugins = {
        pycodestyle = { enabled = false },
        pyflakes = { enabled = false },
        pylint = { enabled = false },
      }
    }
  }
}
```

The config below does not work (that is: it still shows "Expected 2 blank lines after class" like warnings in the code), is there a different place where it should be configured while using AstroNvim? Or is the config wrong? I'll appreciate any help on this.

**Comment by mehalter** [comment]
This has a specific section it should go in in the `user/init.lua` file. Here is a minimal example:

```lua
return {
  lsp = {
    server_settings = {
      pylsp = {
        settings = {
          pylsp = {
            plugins = {
              pycodestyle = { enabled = false },
              pyflakes = { enabled = false },
              pylint = { enabled = false },
            }
          }
        }
      }
    }
  }
}
```

**Comment by mehalter** [comment]
This has a specific section it should go in in the `user/init.lua` file. Here is a minimal example:

```lua
return {
  lsp = {
    server_settings = {
      pylsp = {
        settings = {
          pylsp = {
            plugins = {
              pycodestyle = { enabled = false },
              pyflakes = { enabled = false },
              pylint = { enabled = false },
            }
          }
        }
      }
    }
  }
}
```

Here is the example described in the provided `user_example/init.lua`: https://github.com/AstroNvim/AstroNvim/blob/91b94d2000802728d4009feb2c77fd835f04d9a6/lua/user_example/init.lua#L166

**Comment by krshrimali** [comment]
> This has a specific section it should go in in the `user/init.lua` file. Here is a minimal example:
> 
> ```lua
> return {
>   lsp = {
>     ["server-settings"] = {
>       pylsp = {
>         settings = {
>           pylsp = {
>             plugins = {
>               pycodestyle = { enabled = false },
>               pyflakes = { enabled = false },
>               pylint = { enabled = false },
>             }
>           }
>         }
>       }
>     }
>   }
> }
> ```
> 
> Here is the example described in the provided `user_example/init.lua`:
> 
> https://github.com/AstroNvim/AstroNvim/blob/91b94d2000802728d4009feb2c77fd835f04d9a6/lua/user_example/init.lua#L166

There's one thing I want to say: AstroNvim is surely great. And there might be other configs which are good as well, but the way you help people and keep the repository alive is admiring! Hopefully, I'll be able to step in at some point of time to help answer issues as well :)

Thanks, @mehalter for your help again, I can confirm that it works. 🎉 Closing this issue!

**Comment by roks0n** [comment]
Did this change recently? I can't seem to get it to work. I tested by replacing my existing `~/.config/nvim/lua/user/init.lua` file with the following example:

```lua
return {
  lsp = {
    ["server-settings"] = {
      pylsp = {
        settings = {
          pylsp = {
            plugins = {
              pycodestyle = { enabled = false },
              pyflakes = { enabled = false },
              pylint = { enabled = false },
            }
          }
        }
      }
    }
  }
}
```

And when opening a python file I still get the pylint error.

**Comment by mehalter** [comment]
@roks0n yeah v3 of AstroNvim brought many breaking changes. Here is the docs for migration: https://astronvim.com/Configuration/v3_migration

**Comment by roks0n** [comment]
Thank you. Wasn't aware this issue was opened prior to v3.

For anyone else that might be in similar position as myself - The following section of the v3_migration docs helped fix the issue:

> lsp.server-settings has been renamed to lsp.config. If you have the ["server-settings"] table in your user/init.lua file, just rename it to config. If you have the folder user/lsp/server-settings, just rename the folder to user/lsp/config.
