### ISSUE TITLE
How to get webstorm-like tooltips on keybind press?

### ISSUE THREAD

**Issue by spacegoldminer** [AstroNvim/AstroNvim#572]
I need to replicate this feature with all this useful information from webstorm in nvim.

Is it possible? (i have enabled css, typescript lsp servers)

https://user-images.githubusercontent.com/106533249/170996703-44010d0a-0c47-4030-9f45-7d81a683c6d8.mp4

**Comment by mehalter** [comment]
Is the `K` keybinding for hovering what you are looking for? (https://astronvim.github.io/usage/mappings#lsp-mappings)

https://asciinema.org/a/ybyTEiuoc1WrLqLkRHJzVElaA
