### ISSUE TITLE
how to remove notifications 

### ISSUE THREAD

**Issue by Devarth123** [AstroNvim/AstroNvim#577]
how to remove notifications ?
![1654080153](https://user-images.githubusercontent.com/95016816/171388379-c482538e-b910-4977-b26d-b311fc75c02b.png)

**Comment by mehalter** [comment]
What lsp are you trying to use? It seems like it's not getting properly configured so you might want to try and figure out why. I had a similar problem with `clangd`. Also if you do want to fully disable the notification engine you can do something like this in your `user/init.lua` file:

```lua
return {
  plugins = {
    init = {
      ["rcarriga/nvim-notify"] = { disable = true }
    }
  }
}
```

But fair warning it won't get rid of those messages entirely, it will just move them to the status bar at the bottom.

**Comment by Devarth123** [comment]
i am trying to use clangd and by `user/init.lua`  do u mean`~/.config/nvim/init.lua` ?

**Comment by mehalter** [comment]
I mean `lua/user/init.lua`. That is where you would provide your own user configuration for AstroNvim. You should never have to edit a file that is provided from the GitHub as this will allow you to maintain the ability to accept updates without messing up your user settings. I would highly recommend checking out the documentation as this explains this process, all of the user options, and has examples:
 https://astronvim.github.io/configuration/manage_user_config 

To fix this for clangd, this is a minimal `lua/user/init.lua` file that will remove that warning:

```lua
return {
  lsp = {
    ["server-settings"] = {
      clangd = {
        capabilities = {
          offsetEncoding = "utf-8"
        }
      }
    }
  }
}
```
