### ISSUE TITLE
How do I prevent the indent line from shifting?

### ISSUE THREAD

**Issue by cusxio** [AstroNvim/AstroNvim#580]
As you can see in the _.gif_ below, the indent line shifts when it's active. Is there a way I can remove that behaviour, and just show the highlighted state when it's active?

![CleanShot 2022-06-02 at 11 43 44](https://user-images.githubusercontent.com/6487613/171548752-d9acdd2f-04ee-41a8-89a8-affe602a23e1.gif)

**Comment by mehalter** [comment]
I might be misunderstanding, but do you mean to ask just how to remove the indent blankline plugin? If so, this is how you can remove it from your `user/init.lua` file:

```lua
return {
  plugins = {
    init = {
      ["lukas-reineke/indent-blankline.nvim"] = { disable = true }
    }
  }
}
```

If you mean that you have a specific configuration in mind for the indent blankline plugin, then you should look athtbr indent blankline repository to see what options can be provided to it's `setup()` function and use the following to set custom options for the plugin from your `user/init.lua` file:

```lua
return {
  plugins = {
    indent_blankline = {
      show_current_context = true,
      show_current_context_start = false,
    }
  }
}
```

I would recommend checking out the extensive documentation for AstroNvim which describes all of this as well and tells you what other options are available, what default setup options we provide for the plugins, and examples for common asked questions:

https://astronvim.github.io/

**Comment by cusxio** [comment]
Here's a _.gif_ from vscode, you can see that when the indent line is active, it doesn't move to the right like what `indent-blankline.nvim` does. Compare it with the _.gif_ above, where the indent line moves left and right.


![CleanShot 2022-06-02 at 18 57 53](https://user-images.githubusercontent.com/6487613/171615134-acf890b5-0290-4566-aa0e-262687949317.gif)

I can't figure out if it's a plugin property that needs to be changed, or a `nvim` setting.

Here's a more detailed explanation of the problem

Inactive indent line alignment,

![CleanShot 2022-06-02 at 19 03 00](https://user-images.githubusercontent.com/6487613/171616017-225ea475-296f-4a6f-8fcb-da89012392da.png)

Active indent line alignment,

![CleanShot 2022-06-02 at 19 04 43](https://user-images.githubusercontent.com/6487613/171616185-8c9798ae-754b-45b9-84a7-ba2a0ea0340d.png)

You can see that in the inactive state, the indent line aligns on the **beginning** of the text, but on the active state, the indent line aligns on the **middle** of the text.

Hope this make things clearer.

**Comment by mehalter** [comment]
Ah I see what you mean now, I was misunderstanding before. What terminal are you using and font @cusxio ? I cannot recreate this on my machine. Mine shows it aligning at  the beginning of the text every time

**Comment by cusxio** [comment]
I'm using JetBrainsMono Nerd Fonts + Kitty Terminal

![CleanShot 2022-06-03 at 08 32 06](https://user-images.githubusercontent.com/6487613/171762044-9b0a103f-c18d-40fd-ab76-4fb231cd9f1a.gif)

I've manage to figure it out, for some reason the [`context_char`](https://github.com/lukas-reineke/indent-blankline.nvim/blob/6177a59552e35dfb69e1493fd68194e673dc3ee2/lua/indent_blankline/init.lua#L37-L41) in `AstroNvim` is **not obtained** from the `char`. I had to explicitly specify it to be the same as `char` in `user/init.lua`.

e.g.
```lua
    ["indent_blankline"] = {
      show_first_indent_level = false,
      char = "▏",
      context_char = "▏", -- explicit
    },
```

Feel free to close this issue if you think there's nothing wrong with AstroNvim configurations.

**Comment by mehalter** [comment]
Ah interesting, thanks for investigating this @cusxio ! I will merge a fix for this first thing tomorrow. I'll leave this issue open until then. Thanks again!
