### ISSUE TITLE
Version/Git hash via command and on `:AstroUpdate`

### ISSUE THREAD

**Issue by thepauljones** [AstroNvim/AstroNvim#584]
Since the updates are coming thick and fast :) I find myself wanting to double check I've got the latest version and running `:AstroUpdate` only says "Update complete" without a version or a git hash

**Describe the solution you'd like**
To have a hash or version in the notification after an `:AstroUpdate` and/or an `:AstroVersion` command which displays the current one

**Comment by thepauljones** [comment]
Super cool - Just ran update and version and worked beautifully. 🥇

**Comment by mehalter** [comment]
@thepauljones just heads up I've slowly started working on the new updater on PR #590 . It will most likely take me a bit of time. But this will split off the stable and nightly channels and also provide ways to pin to a specific commit/check out a differrrent branch/etc. quite easily. While stable will track only tagged releases and will manage provided packer plugin versions automatically as well to guarantee that while on the stable branch the core provided plugins and configurations do not break. This will also include showing (or skipping) the changelog between updates.

**Comment by mehalter** [comment]
@thepauljones new updater has been merged, hopefully this meets your needs with the original question you had here! Check out the announcements for a full description of the features :)
