### ISSUE TITLE
Why my row counter is mixed up?

### ISSUE THREAD

**Issue by 000000armor** [AstroNvim/AstroNvim#588]
Hello guys! New vimer here 😅.
So I noticed that row counter works fine for current row but it messes up other numbers related to each row. How to fix it to have all row numbers stay at the same position and just highlight current row? Thank you.
<img width="58" alt="Screenshot 2022-06-03 at 09 32 43" src="https://user-images.githubusercontent.com/25207729/171800437-780abc01-6ebb-4f29-b502-f73183158ed0.png">

**Comment by cusxio** [comment]
It's not mixed up, it's using [`relativenumber`](https://neovim.io/doc/user/options.html#'relativenumber').

You can turn off `relativenumber` via `user/init.lua`. See https://astronvim.github.io/configuration/basic_configuration

```lua
local config = {
  options = {
    opt = {
      relativenumber = false
    }
  }
}

return config

```

**Comment by 000000armor** [comment]
Thanks! Got it.
