### ISSUE TITLE
How to properly install plugin?

### ISSUE THREAD

**Issue by 000000armor** [AstroNvim/AstroNvim#589]
Hello there, I want to install prettier plugin but I have no Idea how to do it within `.lua` files. Maybe you have guide on this in Astro documentation? Thank you.

**Comment by mehalter** [comment]
I would recommend starting with this page: https://astronvim.github.io/configuration/manage_user_config 

On setting up a user configuration file and then taking a look at the provided example as it is heavily commented: https://astronvim.github.io/configuration/basic_configuration
