### ISSUE TITLE
Is it possible to make use of all Luasnip options?

### ISSUE THREAD

**Issue by windowsrefund** [AstroNvim/AstroNvim#592]
Thank you for this really well put together framework.

Being quite new to lua, I'm not sure if I'd be able to to add any and all valid [config options](https://github.com/L3MON4D3/LuaSnip#config) into the _luasnip_ key within my _init.lua_ file?

For example, if I wanted to play around with [ext_opts](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#ext_opts), I'm not sure how this would work since I don't see where _luasnip.util.types_ is being required.

**Comment by mehalter** [comment]
You can do complete extension of the `luasnip` configuration by overriding the `config` function of the plugin table like this inside of your `user/init.lua` file:

```lua
return {
  plugins = {
    init = {
      ["L3MON4D3/LuaSnip"] = {
        config = function()
          -- first require the default luasnip setup from base AstroNvim
          require("configs.luasnip").config()
          -- add arbitrary user luasnip config here
          local ls = require "luasnip"
          ls.config.setup {
            ext_opts = {},
          }
        end,
      },
    },
  },
}
```

**Comment by mehalter** [comment]
Just make sure you run a `:PackerSync` just like after editing any entry to the `plugins.init` table and restarting.

**Comment by windowsrefund** [comment]
Thank you so much.
