### ISSUE TITLE
Treesitter doesn't work

### ISSUE THREAD

**Issue by trickster** [AstroNvim/AstroNvim#595]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0

**Describe the bug**

Treesitter doesn't work 

```
 fn main() { treesitter/highlighter: Error executing lua: ...im/0.7.0/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at p
    1 ▏   println!("Hello, world!"); treesitter/highlighter: Error executing lua: ...im/0.7.0/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: inv
```

**To Reproduce**
1. Create a rust project and open `src/main.rs`

**Expected behavior**

Tree sitter will work correctly.

**Screenshots**
If applicable, add screenshots or recording ([Asciinema](asciinema.org)) to help explain your problem.

**Additional context**
Add any other context about the problem
<img width="1071" alt="Screen Shot 2022-06-06 at 17 35 21" src="https://user-images.githubusercontent.com/1740785/172126043-f054df77-f401-46ad-a32e-a0720d5fad5b.png">
 here.

**Comment by mehalter** [comment]
Have you tried reinstalling the treesitter parser? I think it's `TSUninstall` and then `TSInstall` again

**Comment by mehalter** [comment]
This seems to be an error with the treesitter parser and not with anything AstroNvim is doing.

**Comment by mehalter** [comment]
I'm going to go ahead and close this as it doesn't seem to be a bug related to AstroNvim in particular.
