### ISSUE TITLE
iTerm colors

### ISSUE THREAD

**Issue by rbutera** [AstroNvim/AstroNvim#597]
Any chance you can share the iTerm color scheme for the version of One Dark that you used to design astronvim?

Astro's colors are slightly different than any of the one dark themes I've tried

**Comment by mehalter** [comment]
Not sure what goes into an iTerm color scheme, but you can check out all of the colors here: https://github.com/AstroNvim/AstroNvim/blob/main/lua/default_theme/colors.lua
