### ISSUE TITLE
Control space not working for `cmp`

### ISSUE THREAD

**Issue by jayp0521** [AstroNvim/AstroNvim#601]
https://github.com/AstroNvim/AstroNvim/blob/bdddd84a7d835e1bd0aecb7e82a0bd804e75ba45/lua/configs/cmp.lua#L80

nothing happens when I press `Ctrl + Space`. the other bindings work. I did not test them all

**Comment by jayp0521** [comment]
https://github.com/jayp0521/dotfiles/tree/main/nvim/.config/nvim/lua/user

**Comment by mehalter** [comment]
`<c-space>` here is triggering the `complete()` function. Basically this is used to open the completion menu if it is not available (to my knowledge). So it might not be doing what you think if you are picturing it doing "selection". 

An example of this is here:  https://asciinema.org/a/dinLAO4CjcdXWKWjObFdsIglJ

When there is no completion menu available, if I press `<c-space>` then it will open the completion menu appropriately

**Comment by jayp0521** [comment]
Correct that is not happening. I can send a video later. I can try with vanilla AstroNvim however I don't really see anything conflicting

**Comment by mehalter** [comment]
Could it be because there is nothing matching the completion? The easiest way to test this is to start typing something where the menu is open automatically and then use `<c-e>` to close it and then immediately do `<c-space>` and see if it reopens.

**Comment by Johnsiras** [comment]
> Could it be because there is nothing matching the completion? The easiest way to test this is to start typing something where the menu is open automatically and then use `<c-e>` to close it and then immediately do `<c-space>` and see if it reopens.

I have the same issue too, doing `<c-e>` after that doing `<c-space>` doesn't work

**Comment by mehalter** [comment]
@Johnsiras could you share your user configuration? Also what terminal and operating system are you on?

**Comment by Johnsiras** [comment]
> 

I still don't have my nvim user config repo yet, but my terminal is wezterm both wezterm, terminal, and alacritty doesn't work.
Operating system is windows

**Comment by mehalter** [comment]
@Johnsiras @jayp0521 this appears to be a big upstream: https://github.com/neovim/neovim/issues/8435

**Comment by Johnsiras** [comment]
> @Johnsiras @jayp0521 this appears to be a bug upstream for Neovim on windows: [neovim/neovim#8435](https://github.com/neovim/neovim/issues/8435)

Btw, `<c-space>` but doing `<tab>` it works??
I pressed `<c-e>` then tab works only space doesn't work that's so weird....

And it's annoying too when using tab ik it's for indentation not for cmp completion

https://user-images.githubusercontent.com/102006493/172763525-931b4c35-d3b0-4c1b-b4cf-b4d1a7e8ef06.mp4

**Comment by mehalter** [comment]
Since this is an upstream bug affecting windows users and not related to AstroNvim in particular, I'm going to go ahead and close this and leave the issue searchable for anyone else who may have the same problem/question.

**Comment by georgewheatcroft** [comment]
For anyone who has a similar issue (ctrl-space not working when trying to trigger completion) I would recommend checking that your keyboard/terminal app/whatever in the input chain to vim is actually sending the input (ctrl-space) you think it is - particularly if you're on MacOs!

I questioned if my terminal app (iterm2) wasn't sending ctrl-Space through properly, so on iterm2 I turned on raw key reporting mode:
image

that showed me that space bar wouldn't register any input when ctrl was pressed at the same time

I then stumbled across this article which says that apparently a default system shortcut was made a while ago in macos that uses the ctrl-space combination

https://apple.stackexchange.com/a/351058

deselecting this shortcut like so solved my problem:
Screenshot 2023-03-16 at 22 34 38

**Comment by WiL-dev** [comment]
To add to @IvanXh0 [answer](https://github.com/neovim/neovim/issues/8435#issuecomment-2119332145), in Windows Terminal go to Settings > Open JSON  file and adjust it as follows:

```
    ...
    "actions":
    [
        {
            "command":
            {
                "action": "sendInput",
                "input": "\u001b[32;5u"
            },
            "id": "Terminal.CtrlSpaceWorkaround"
        }
    ],
    ...
    "keybindings":
    [
        {
            "id": "Terminal.CtrlSpaceWorkaround",
            "keys": "ctrl+space"
        },
    ...
```
