### ISSUE TITLE
how to replace feline?

### ISSUE THREAD

**Issue by Rochan2001** [AstroNvim/AstroNvim#618]
I wanted to use lualine instead of feline as feline does not support gruvbox theme and i tried disabling feline using disable = true option in the plugins.init table . But still feline is appearing.

**Comment by Rochan2001** [comment]
![Screenshot from 2022-06-10 23-35-09](https://user-images.githubusercontent.com/51673392/173125268-ea939cdf-9753-40f8-9d06-5a687baac96d.png)

**Comment by mehalter** [comment]
@Rochan2001 make sure to do a `:PackerSync` since you have modified the packer plugin table. This will cause Feline to be uninstalled completely. Also I just want to give a warning that we are pulling the colors from lualine themes if they are available for good theme compatibility since that isn't built into feline itself. Another user on the Discord on our discord has run into this (https://github.com/ellisonleao/gruvbox.nvim/issues/119) It seems that the default statusline highlight group in `gruvbox.nvim` is the inverse of the normal mode which is why it appears light like that.

**Comment by mehalter** [comment]
```lua
return {
  plugins = {
    init = {
      ["feline-nvim/feline.nvim"] = { disable = true },
    },
  },
}
```

Here is an example `user/init.lua` file that simply disables feline

**Comment by Rochan2001** [comment]
Thank you for the quick response. If that's the case then I'll stick with feline. The things gruvbox is making me do XD

**Comment by Rochan2001** [comment]
Can you help me change the highlight group? I'm new to this and finding it hard to pinpoint the exact location for changing the colors.

**Comment by mehalter** [comment]
`gruvbox.nvim` is pretty poorly written to be extended as in it doesn't provide any API to do this at all for the user. I believe the easiest way would be to set up an autocommand to run on the colorscheme changing and setting new highlight groups if the colorscheme is changed to gruvbox. Here is an example:

```lua
vim.api.nvim_create_autocmd("ColorScheme", {
  desc = "Set custom highlight groups",
  callback = function()
    if vim.g.colors_name == "gruvbox" then
      -- set your colors here...
      vim.api.nvim_set_hl(0, "Normal", { fg = "#FFFFFF", bg = "#000000" })
    end
  end,
})
```

**Comment by alexander-born** [comment]
> ```lua
> return {
>   plugins = {
>     init = {
>       ["feline-nvim/feline.nvim"] = { disable = true },
>     },
>   },
> }
> ```
> 
> Here is an example `user/init.lua` file that simply disables feline

Even with this feline still can't be disabled.

**Comment by ellisonleao** [comment]
@mehalter @Rochan2001 custom config for overriding hightlights are coming in https://github.com/ellisonleao/gruvbox.nvim/issues/96 . In the meantime you can use the suggestion from @Rochan2001 but be aware that using `nvim_set_hl` for `Normal` highlight has some [issues](https://github.com/akinsho/bufferline.nvim/issues/386#issuecomment-1103849289) and you should probably just use a normal `vim.cmd([[hi Normal fg=#fffff bg=#000000]])` call
