### ISSUE TITLE
Is toggleterm multiple side-by-side terminals available? How to configure?

### ISSUE THREAD

**Issue by jdix531** [AstroNvim/AstroNvim#619]
Hi there! I'm new to lua powered config and AstroNvim so I have some work before I can work on the config easily myself - sorry for that! That said, this project is definitely going to be my introduction to them and I'm loving it so far. Anyways!...

So, I am trying to get multiple vertically split toggle terms but I think something is catching the hotkeys that would normally go to toggle term and remapping them differently - or I can't otherwise explain toggleterms behavior compared to their documentation.

What I expect to have happen for this is: If I first configure default toggle term direction to vertical or horizontal, then press the toggle key combo of '<C-\>', then exit with the same, then type '2<C-\>', for there to be two terminals adjacent. Instead the second terminal does open but it is always a new floating terminal.

Any easy changes to make to enable this, perhaps I'm just missing the intended method of doing this, or is this not super compatible with AstroNvim? (it isn't going to stop me from using the project for sure)

Thanks, Josh

**Comment by bhruszka** [comment]
I have the same issue and I was able to kind of solve it. 

In `lua/user/init.py` I modified toggleterm default direction to `horizontal`. It seems that the problem is that by default direction is set to `float` and for some reason this brakes spiting terminal. 

```
local config = {
  ...
 plugins = {
    ...
    toggleterm = {
      direction = "horizontal",
    }
    ...
  }
  ...
}
```

**Comment by mehalter** [comment]
@bhruszka's recommendation is the correct approach. The default terminal location is floating and by changing the configuration to `horizontal` they both should be split instead of one be flowing.
