### ISSUE TITLE
How to set wrap and :set norelative number permanently

### ISSUE THREAD

**Issue by bihari123** [AstroNvim/AstroNvim#622]
I have to :set wrap and :set norelativenumber every time i open nvim. Can someone plz tell me how to set my preference permanently?

**Comment by mehalter** [comment]
Take a look here for how to correctly set up your user configuration: https://astronvim.github.io/configuration/manage_user_config

An example minimal `user/init.lua` file to do what you want would be

```lua
return {
  options = {
    opt = {
      wrap = true,
      relativenumber = false,
    }
  }
}
```
