### ISSUE TITLE
Move from bufferline.nvim to nvim-cokeline

### ISSUE THREAD

**Issue by jayp0521** [AstroNvim/AstroNvim#629]
**Is your feature request related to a problem? Please describe.**
Not a problem. I was wondering what are your thoughts on moving to `nvim-cokeline`.

**Describe the solution you'd like**
Migrate to nvim-cokeline

**Additional context**
I don't have a problem with bufferline. cokeline seems to be more customizable

**Comment by mehalter** [comment]
What features does it have that bufferline doesn't? We probably aren't going to be changing the plugins without some significant performance increase (as per the contribution guidelines)  I took a look at the README and I couldn't see any features that it has that bufferline doesn't have but I might be missing something
