### ISSUE TITLE
How to show hidden files in file tree

### ISSUE THREAD

**Issue by eagle-tex** [AstroNvim/AstroNvim#631]
I'm having trouble finding how to show hidden files or folders in the file tree.

What file(s), which option(s) should I edit and what should I change to be able to see files such as .prettierrc, .gitignore, .eslintrc, etc.

What about folders? (.git for example). Can I show hidden files without showing hidden folders?

**Comment by eagle-tex** [comment]
I think I found the answer
I changed the "hide_dotfiles = true" line  to "hide_dotfiles = false" in the ~/.config/nvim/lua/neo-tree.lua file.
It was line 41 in my file.

```
    filesystem = {
      filtered_items = {
        visible = false,
        hide_dotfiles = false,                       **// <-- THIS LINE**
        hide_gitignored = false,
        hide_by_name = {
          ".DS_Store",
          "thumbs.db",
          "node_modules",
          "__pycache__",
        },
      },

```

**Comment by mehalter** [comment]
That is the best option to change. You will want to change this in your `user/` folder in your user configuration so that you do not break receiving updates. All changes to the config should be in the `user/` folder and not in the base files.

**Comment by mehalter** [comment]
Also the binding I'm `neo-tree` is `H` for toggling hidden files. Which can be used whenever you want if you prefer them being hidden most of the time until you need to access them.

**Comment by eagle-tex** [comment]
My bad.
Thanks for your reply.
I guess I should just revert the changes in the file I changed (nvim/lua/neo-tree.lua) and change just that line in the user/init.lua

**Comment by mehalter** [comment]
No problem, here's an example `user/init.lua` with the change:

```lua
return {
  plugins = {
    ["neo-tree"] = {
      hide_dotfiles = false,
    }
  }
}
```

**Comment by eagle-tex** [comment]
I've seen that return pattern in many places in the documentation and I don't understand it.
I guess it doesn't mean I should delete everything in the file and place the snippet in the file.
I don't know where to put that return statement in the file.
My user/init.lua is one big object (236 lines long). It looks like this

```
local config = {
-- Configure AstroNvim updates
  updater = {
    ...
  }
  many other lines
}

Where do I put the return snippet, please?

return config
```

**Comment by mehalter** [comment]
The return snippet is the same as 

```lua
local config = { ... }
return config
```

You would just add those sections to the object. Your config should all be captured in that single object. Each code snippet in the documentation is a complete `user/init.lua` file with the minimal additions to that object that are necessary.

**Comment by eagle-tex** [comment]
I think I'm starting to undersand.
But there is one more thing. In my user/init.lua, under the "plugins" section, I already have a line with the following
["neo-tree"] = true,

When I try to add the snippet you gave me earlier
["neo-tree"] = {
  hide_dotfiles = false,
}

I got an error stating that ["neo-tree"] already exists. So I commented out the line with ["neo-tree"] = true and I kept only the modifications you suggested. But but, it is not working.
Do I need to close all terminal windows with AstroNvim and restart?

**Comment by eagle-tex** [comment]
Anyway, thanks a lot for your time sir.
Very much appreciated!

**Comment by iam-amiya** [comment]
@mehalter  I am not able to find this file 
`~/.config/nvim/lua/neo-tree.lua file.`
can you please guide me through the process about how to show the hidden files.

**Comment by mehalter** [comment]
this is old information. AstroNvim v4 is structured very differently. Everything is managed with `lazy.nvim`. I would recommend reading the [AstroNvim Documentation](https://docs.astronvim.com/) on how to configure it and modify plugins.

For this, you simply want to use the following plugin spec:

```lua
return {
  "nvim-neo-tree/neo-tree.nvim",
  opts = {
    filesystem = {
      filtered_items = {
        hide_dotfiles = false,
      },
    },
  },
}
```
