### ISSUE TITLE
How to setup linters and formatters?

### ISSUE THREAD

**Issue by eagle-tex** [AstroNvim/AstroNvim#632]
Hello,
I followed the basics steps from the documentation. I ran :LspInstall pyright and :TSInstall python but for some reason unknown to me, I can't format or lint python files.
When I run "space l f" to format code, I get the notification

"[LSP] Format request failed, no matching language servers."

In the same vein, I can format Javascript or Typescript file (although when I have 10 empty lines, they don't get scrubbed down to 1 empty line, they way it's done in VSCode for example) but I don't get any linting capabilities. I get the following notification

"[lspconfig] Unable to find ESLint library."

I read the documentation but it isn't clear to me how to setup the linters and formatters properly (maybe I'm stoooopid!!!). In which files do I write/copy the code provided. How do I setup prettier and eslint for Javascript for example?
Will the linter and formatter use my .prettierrc and .eslintrc files?

Can you please help and/or point to a detailed and easy way to setup linters and formatters? Please don't assume any knowledge of lua or nvim configuration.

I'm new to Vim/Neovim (coming from VSCode but got hooked by Vim editing capabilities) and I discovered your AstronNvim project which looks very cool and well polished.

**Comment by mehalter** [comment]
These are configured inside of your `~/.config/nvim/lua/user/init.lua` file. This file does not come with AstroNvim by default, but the creation of this is described in the docs here: https://astronvim.github.io/configuration/manage_user_config

This goes through creating a `user/init.lua` file by copying the provided example that comes with AstroNvim. Once this is copied there is a section in this file's table `plugins.null-ls`: https://github.com/AstroNvim/AstroNvim/blob/7363a43f0168c4d6eede8fafae07bc1f3e997f98/lua/user_example/init.lua#L92-L115

Here is where you will configure linters and formatters. The commented links show where you can check the supported built ins such as `prettier` and `eslint`. These should automatically load your `.prettierrc` and `.eslintrc` files that are in the roots of your projects.

Also `pyright` does not provide a formatter, so you will need to use something such as `black` for formatting and make sure that you have it installed on your machine and accessible.

Throughout the docs there are lots of code snippets, these for the most part are complete `user/init.lua` files with the minimal options necessary for doing the thing that they describe. So for example, if you just wanted to configure prettier, eslint, and black, this would be the minimal `user/init.lua` file that would achieve this (as in if you copied and pasted the entire thing as the contents of the file):

```lua
return { -- return table for user configuration
  plugins = { -- table for plugin configuration (addition and setup calls)
    ["null-ls"] = function(config) -- this configures the table for `require("null-ls").setup({...})`
      local null_ls = require "null-ls" -- load null-ls
      config.sources = { -- set null-ls sources
        null_ls.builtins.formatting.eslint, -- add eslint formatter
        null_ls.builtins.formatting.prettier, -- add prettier formatter
        null_ls.builtins.formatting.black, -- add black formatter
      }
      config.on_attach = function(client) -- this function is run when a null-ls source is attached
        -- NOTE: You can remove this on attach function to disable format on save
        if client.resolved_capabilities.document_formatting then
          vim.api.nvim_create_autocmd("BufWritePre", {
            desc = "Auto format before save",
            pattern = "<buffer>",
            callback = vim.lsp.buf.formatting_sync,
          })
        end
      end
      return config -- return final config table
    end,
  },
}
```
