### ISSUE TITLE
Include a light theme

### ISSUE THREAD

**Issue by 2brownc** [AstroNvim/AstroNvim#633]
**Is your feature request related to a problem? Please describe.**
A nice dark theme is inlcuded by default but not even one light theme. 

**Describe the solution you'd like**
Please include a light theme. 

**Additional context**
I propose this light theme to be included by default:

https://github.com/projekt0n/github-nvim-theme

**Comment by 2brownc** [comment]
> it would be nice to add a separate color palette for our built in theme

This would be great too!

For anyone who want this theme on their AstroVim use this [config](https://astronvim.github.io/configuration/manage_user_config):

```
return {
  colorscheme = "github_light_default",
  plugins = {
    init = {
      {
        "projekt0n/github-nvim-theme",
        config = function()
          require("github-theme").setup {
          }
        end,
      },
    },
  },
}
```

**Comment by i-am-the-slime** [comment]
How do you set two themes, one dark and one light in the config? I always either have a working dark theme that gets inverted weirdly when changing to light or vice versa
