### ISSUE TITLE
Don't touch the default nvim installation; use a seperate config directory.

### ISSUE THREAD

**Issue by 2brownc** [AstroNvim/AstroNvim#634]
**Is your feature request related to a problem? Please describe.**
Currently recommended installation method makes AstroNvim take over the `nvim` command. 

**Describe the solution you'd like**
Use `avim` instead of taking over `nvim`. It's better if the default nvim installtion is left as it is while AstroVim has it's own runtime, config and cache directories.  

Lunar Vim does exactly this. So even when AstroVim is installed it runs with no issue. Example script for Lunar Vim which is invoked by `lvim`:

```
#!/bin/sh

export LUNARVIM_RUNTIME_DIR="${LUNARVIM_RUNTIME_DIR:-"~/.local/share/lunarvim"}"
export LUNARVIM_CONFIG_DIR="${LUNARVIM_CONFIG_DIR:-"~/.config/lvim"}"
export LUNARVIM_CACHE_DIR="${LUNARVIM_CACHE_DIR:-"~/.cache/lvim"}"

exec nvim -u "$LUNARVIM_RUNTIME_DIR/lvim/init.lua" "$@"
```

**Additional context**
A different config directory is useful because some guis Neovim require config files in nvim directory. So if AstroVim has a different directory it can be updates without any extra steps as in recopying the file afterwards.

**Comment by mehalter** [comment]
This adds a layer of complexity to setting up AstroNvim for most users for a case I don't think is generally needed. I will definitely add this to the documentation though in the recipes section with detailed instructions on how to set this up and an example `avim` script that users can copy/paste and set up themselves. What do you think? As for the GUI compatibility, I think most users who use AstroNvim as well as a GUI based Neovim client want to use AstroNvim with their GUI client. Maybe we can add common GUI config files to our gitignore to help with this compatibility with the updater. Do you have any examples and I can add those files to not be tracked

**Comment by 2brownc** [comment]
> I will definitely add this to the documentation though in the recipes section with detailed instructions on how to set this up and an example `avim` script that users can copy/paste and set up themselves. 

That's great!

> Maybe we can add common GUI config files to our gitignore to help with this compatibility with the updater. Do you have any examples and I can add those files to not be tracked.

Good idea!

I use [Neovim-qt](https://github.com/equalsraf/neovim-qt) and it uses the file `ginti.vim`.

**Comment by mehalter** [comment]
Awesome thanks, I'll take a look into this this upcoming week and check out some other GUI applications to get a decent list together. Thanks for the recommendation!
