### ISSUE TITLE
Change highlights and colors based on it's colorscheme

### ISSUE THREAD

**Issue by Johnsiras** [AstroNvim/AstroNvim#635]
Not a bug, but how do you change it's colors and highlights (for example telescope colors) based on it's colorscheme? maybe dracula then change it's highlights and colors

(EDIT: i accidentally used the bug question instead of a general question sorry about that)

**Comment by kabinspace** [comment]
What colorscheme are you using? Dracula or the default one that comes with AstroNvim?

**Comment by Johnsiras** [comment]
> What colorscheme are you using? Dracula or the default one that comes with AstroNvim?

it's dracula

**Comment by mehalter** [comment]
@Johnsiras it looks like dracula doesn't really have a good API in place to easily change highlight groups. You can do something like this though:

```lua
vim.api.nvim_create_autocmd("ColorScheme", {
  desc = "Set custom dracula highlights",
  callback = function()
    if vim.g.colors_name == "dracula" then
      local colors = require("dracula").colors()
      -- set your colors here...
      vim.api.nvim_set_hl(0, "Normal", { fg = colors.fg, bg = colors.bg })
    end
  end,
})
```

This will make an autocommand to run every time the colorscheme is changed, and if it is changed to dracula, then it loads the dracula color palette to a variable and you can just set highlights there for whatever you want. Then it won't interfere with the default theme if you plan on switching back and forth.
