### ISSUE TITLE
Issues with telescope-fzf-native on fresh macos monterey install

### ISSUE THREAD

**Issue by oddnugget** [AstroNvim/AstroNvim#636]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0

**Describe the bug**
Telescope is throwing errors when attempting to find files or words. It seems that the binary for fzf-native is not compiled properly since it is not present in `local/share/nvim`. 

```
packer.nvim: Error running config for telescope-fzf-native.nvim: ...er/opt/telescope.nvim/lua/telescope/_extensions/init.lua:10: 'fzf' extension doesn't exist or isn't installed: ...ack/packer/opt/telescope-fzf-native.nvim/lua/fzf_lib.lua:11
```

Trying to reinstall fzf-native also throws error. 

**To Reproduce**
Run the installer on macos monterey. Completely clean nvim install as well

**Expected behavior**
Should work without errors

**Additional context**
AstroVim seems great, im excited to get it working!

**Comment by mehalter** [comment]
Do you have `make` or `cmake` available on your system?

**Comment by mehalter** [comment]
@oddnugget have you had any luck with this?

**Comment by krshrimali** [comment]
Hi, @mehalter - I've had this issue as well. And I can confirm that I had `telescope-fzf-native.nvim` folder in `~/.local/share/nvim/site/pack/packer/opt`.

What I did to resolve this: (I just tried things for 5-10 mins, I'll report if it's a false alarm of a solution)

```
cd ~/.local/share/nvim/site/pack/packer/opt/telescope-fzf-native.nvim && mkdir -p build && cd build
cmake .. && make
sudo cp libfzf.so /usr/local/lib
```

And once done, I had to make sure that I've `export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH` in my bash config (I've zsh, so I added it in my `.zshrc` file).

And the error doesn't come up again. Not sure if it's the right solution, but I hope this helps debug this?

**Comment by mehalter** [comment]
Thank you for commenting your work around @krshrimali !  That will help users that run into this issue down the line. This type of issue is out of the hands of AstroNvim though since we don't handle the installation code for this plugin.

**Comment by krshrimali** [comment]
> Thank you for commenting your work around @krshrimali ! That will help users that run into this issue down the line. This type of issue is out of the hands of AstroNvim though since we don't handle the installation code for this plugin.

I agree @mehalter - I think it has been solved though, never faced this issue again. Thank you for your response! :D
