### ISSUE TITLE
Lazygit Esc does not work when using lazygit in the Astronvim context

### ISSUE THREAD

**Issue by whoop-t** [AstroNvim/AstroNvim#641]
Describe the bug
Using Astronvim
When in commit message prompt(or any menu in Lazygit in the context of Astronvim), esc just takes you out of insert mode. Cant exit any prompt in lazygit

To Reproduce

Clone Astronvim
brew install jesseduffield/lazygit/lazygit
make change to file, open lazygit (leader + gg)
Open commit prompt, press esc

Expected behavior:
Close commit message window

Current behavior:
Cursor leaves insert mode and you just move around the lazygit terminal till you press i again. Cant exit menus with esc

Screenshots
![Screen Shot 2022-06-13 at 4 41 36 PM](https://user-images.githubusercontent.com/52976607/173464861-e8b659d0-d389-47b0-9c04-ff2684c178d7.png)

Desktop (please complete the following information):
OS: macOS Monterey
Latest

**Comment by mehalter** [comment]
Please see #356, #627
