### ISSUE TITLE
Open neo-tree by default when vim opens

### ISSUE THREAD

**Issue by vamsikrishnav** [AstroNvim/AstroNvim#648]
I want to know if there is a way to open the neo-tree on starting vim. If there is how do I enable it from the config?

**Comment by mehalter** [comment]
We currently have `neo-tree` starting automatically if you open Neovim with a directory. For example `nvim .` or `nvim some/folder/path` but opening it on open is tricky. Just to clarify, you want it to open automatically when the first buffer attaches?

**Comment by mehalter** [comment]
You could try an autocmd similar to this in your `polish` function:

```lua
vim.api.nvim_create_augroup("neotree_autoopen", { clear = true })
vim.api.nvim_create_autocmd("BufWinEnter", {
  desc = "Open neo-tree on enter",
  group = "neotree_autoopen",
  callback = function()
    if not vim.g.neotree_opened then
      vim.cmd "Neotree show"
      vim.g.neotree_opened = true
    end
  end,
})
```

It does get a little funky if you do open Neovim with a folder like `nvim .`

**Comment by vamsikrishnav** [comment]
> > ```lua
> > vim.api.nvim_create_autocmd("BufWinEnter", {
> > ```
> 
> This line could be modified to:
> 
> ```lua
> vim.api.nvim_create_autocmd("BufReadPre", {
> ```
> 
> Which should solve the file/folder issue specified above.

thanks so much @TheStutterNerd @mehalter now it works flawlessly.

**Comment by TheStutterNerd** [comment]
Yeah ironically, one of the latest neotree plugin updates seemed to have cause this to stop working (was the one released the same day as I posted this reply I think). What I did was, update to the new nightly AstroVim (also with latest plugin updates) and it worked fine again.

Just change your channel to "nightly" in your init.lua file then run ":AstroUpdate" and hopefully that should solve it for you for now. It should hopefully make its way into stable release soon then you can switch back. @vamsikrishnav

**Comment by VicMCA** [comment]
Just chiming in, I could get it to work without setting the channel to `nightly` (although at this date I don't even know if it's necessary anymore) by using the following config:
``` lua
vim.api.nvim_create_augroup("neotree_autoopen", { clear = true })
vim.api.nvim_create_autocmd("BufRead", { -- Changed from BufReadPre
  desc = "Open neo-tree on enter",
  group = "neotree_autoopen",
  once = true,
  callback = function()
    if not vim.g.neotree_opened then
      vim.cmd "Neotree show"
      vim.g.neotree_opened = true
    end
  end,
})
```

Setting to `BufReadPre` still triggers the `E201: *ReadPre autocommands must not change current buffer`, but not with `BufRead`, and as far as I could try it out, it works as usual.
