### ISSUE TITLE
Telescope fzf is not working.

### ISSUE THREAD

**Issue by Rid1-fz-06** [AstroNvim/AstroNvim#657]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0

**Describe the bug**
I recently re-installed neovim and AstroNvim. After installation, I've renamed the folder ~/.config/nvim/lua/user_example to ~/.config/nvim/lus/user, added an autocmd, some lines from the website of astronvim. Then when I tried to use fzf, it is not being able to search anything. It's showing no file in the list, even when I'm typing the file name.

**To Reproduce**
1. Press \<leader\>ff
2. Type any file's name in current directory
3. See error

**Expected behavior**
There should be a list of files from current directory and sub-directories from where I can choose one to open.

**Comment by Rid1-fz-06** [comment]
It turns out to be problem of my system as it was not being able to load neovim correctly.

**Comment by koslak** [comment]
Hi, for those who are facing this issue on Windows, what is happening is that the _telescope-fzf-native.nvim_ plugin is not being built. You can check this by doing this:

1. Open a CMD window and go to the plugin's folder:

`> cd %AppData%\..\Local\nvim-data\site\pack\packer\opt\telescope-fzf-native.nvim`

2. Go to the `build` folder and then you will see that is empty. 

**The following are the steps that I did to make it work:** 

1. Open a CMD window and go to the plugin's folder:

`> cd %AppData%\..\Local\nvim-data\site\pack\packer\opt\telescope-fzf-native.nvim`

2. Run the following command (make sure you have the dependencies installed (like cmake) to build this plugin):

`> cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release && cmake --build build --config Release && cmake --install build --prefix build`

**Note:** The instruction above is from the Github repository: [telescope-fzf-native.nvim github](https://github.com/nvim-telescope/telescope-fzf-native.nvim#cmake-windows-linux-macos).

3. Make sure the plugin was built. Go to the folder:

`> cd %AppData%\..\Local\nvim-data\site\pack\packer\opt\telescope-fzf-native.nvim\build\Release`
`> dir`

and now you should see the following files: 

```
24-Feb-23  11:27 PM    <DIR>          .
24-Feb-23  11:27 PM    <DIR>          ..
24-Feb-23  11:27 PM             2,796 fzf.exp
24-Feb-23  11:27 PM             4,620 fzf.lib
24-Feb-23  11:27 PM            22,016 libfzf.dll
               3 File(s)         29,432 bytes
```

4. Now open Nvim and run the command `:PackerSync`
