### ISSUE TITLE
Ident not right when new line

### ISSUE THREAD

**Issue by ying234** [AstroNvim/AstroNvim#659]
Ident not right when create a new line:
![image](https://user-images.githubusercontent.com/59452354/174348386-02d6202c-769c-4ebb-b899-eb99da26ed2b.png)

Expected:
![image](https://user-images.githubusercontent.com/59452354/174348319-291422a6-1045-4590-8e0e-ba1a849ecb90.png)

**Comment by mehalter** [comment]
Can you please provide some more information to help us reproduce this? (This is why the template we made for reporting a bug is useful as it walks you through this request). What file type is this? What language servers/treesitter parsers are you using? etc.

**Comment by ying234** [comment]
It's .tsx. Here's the LSP information:

 _Detected filetype:   typescriptreact
 
 3 client(s) attached to this buffer: 
 
 Client: null-ls (id: 2, pid: 5001, bufnr: [27, 25, 16])
 	filetypes:       lua, sh, css, markdown, typescript, javascript, javascriptreact, scss, html, json, yaml, typescriptreact, vue, gitrebase, text
 	autostart:       false
 	root directory:  C:\Users\xxxx
 	cmd:             nvim
 
 Client: tsserver (id: 3, pid: 18164, bufnr: [25, 27])
 	filetypes:       javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx
 	autostart:       true
 	root directory:  C:/Users/xxx
 	cmd:             cmd.exe /C typescript-language-server --stdio
 
 Client: eslint (id: 4, pid: 6840, bufnr: [25, 27])
 	filetypes:       javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx, vue
 	autostart:       true
 	root directory:  C:/Users/xxx
 	cmd:             cmd.exe /C vscode-eslint-language-server --stdio
 
 1 active client(s) not attached to this buffer: 
 
 Client: sumneko_lua (id: 1, pid: 32316, bufnr: [16])
 	filetypes:       lua
 	autostart:       true
 	root directory:  C:/Users/xxx
 	cmd:             lua-language-server
 
 Configured servers list: grammarly, eslint, tsserver, sumneko_lua, html_

**Comment by mehalter** [comment]
I think this is best resolved with enabling the treesitter based indentation. This is a pretty experimental feature and doesn't perform well on all languages. You can do this in your `user/init.lua` file:

```lua
return {
  plugins = {
    treesitter = {
      indent = { enable = true },
    },
  },
}
```

**Comment by mehalter** [comment]
I believe the only language I have experienced super bad indnetation issues with is `python`. So you probably want to make it `indent = { enable = true, disable = { "python" } },`
