### ISSUE TITLE
Solution for toggleterm shortcuts

### ISSUE THREAD

**Issue by TestProgger** [AstroNvim/AstroNvim#666]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0

**Bug**
Shortcuts for ToggleTerm do not work

**Solution**
Overwrite nvim-toggleterm.lua with toggleterm.nvim in the :

1. ~/.config/nvim/lua/core/mappings.lua 
2. ~/.config/nvim/lua/configs/which-key-register.lua

**Comment by mehalter** [comment]
This has been resolved with #665
