### ISSUE TITLE
Deprecated options/parameters notifications

### ISSUE THREAD

**Issue by eagle-tex** [AstroNvim/AstroNvim#667]
I get the following notifications, depending on the type of file I open (python files or json, javascript) and when I try to format my code:

_LSP] Accessing client.resolved_capabilities is deprecated, update your plugins or configuration to access client.server_capabilities instead.The new key/value pairs in server_capabilities directly match those defined in the language server protocol_

_vim.lsp.buf.formatting_sync is deprecated. Use vim.lsp.buf.format instead_

I found those entries in my user/init.lua file and changed them according to the notification messages, but I still get the notifications. 
The entries are also in ~/.config/nvim/configs/lsp/handlers.lua but I'm not supposed to touch those, right?

My question is: What do I add/change in my user/init.lua to get those notifications to go away?

**Comment by mehalter** [comment]
This is because you are using nightly vim which is not officially supported by Neovim as it has constant breaking changes. You can test out our `neovim-0.8` branch but it is very untested and cannot be guaranteed to work with all nightly versions.

**Comment by mehalter** [comment]
Please see #391 and #422. But I would highly recommend just using stable Neovim with stable AstroNvim as this is the only way to guarantee it will work as much as possible.

**Comment by eagle-tex** [comment]
That means I should uninstall AstroNvim and reinstall the stable version, right?
Or just uninstall Neovim and install v0.7 instead of v0.8?

**Comment by mehalter** [comment]
I mean uninstall the Neovim nightly (0.8) and install Neovim 0.7. You do not need to reinstall AstroNvim. If you want to use the new `stable` channel of AstroNvim branch you can put this in your user configuration and run `AstroUpdate`:

```lua
updater = { channel = "stable" }
```

**Comment by mehalter** [comment]
When we release AstroNvim v2.0.0 (probably when Neovim 0.8 is released) we will be making the stable channel the default update path :)

**Comment by eagle-tex** [comment]
Thanks a lot for your time, dedication and patience.

**Comment by flamendless** [comment]
I did this, but i get `vim/_init_packages.lua: cannot load incompatible bytecode` error with `neovim-0.7.0-3` from the AUR

**Comment by mehalter** [comment]
I'm not sure what this error means or what file you are referring to here.

**Comment by mehalter** [comment]
@flamendless

**Comment by flamendless** [comment]
Oh, i meant i reverted back to `neovim-0.7.0-3` from nightly to use stable, but it's okay now i'll just use `neovim-git` as that works.

**Comment by mehalter** [comment]
@flamendless you probably need to uninstall and rebuild all of your treesitter parsers. As the byte code will change and the compiled parsers are incompatible. At least, that's my intuition with you moving between stable and nightly.

**Comment by flamendless** [comment]
I do still get `[LSP] Accessing client.resolved_capabilities is deprecated,` after i switched to `stable` and ran `PackerSync`

**Comment by mehalter** [comment]
This is only a problem on nightly. Not stable. If you are using `neovim-git`. This will be building the latest code on `git` which is indeed nightly.

**Comment by flamendless** [comment]
> This is only a problem on nightly. Not stable. If you are using `neovim-git`. This will be building the latest code on `git` which is indeed nightly.

I see, thank you. i'll use then AstroVim nightly

**Comment by mehalter** [comment]
@flamendless I would recommend you switch to Neovim stable with AstroNvim stable and refresh your environment. You probably have some dangling files. Try deleting `~/.local/share/nvim/site` and `~/.cache/nvim` and then rerunning `nvim +PackerSync`
