### ISSUE TITLE
How to setup codeaction to build and run project

### ISSUE THREAD

**Issue by Rishikesh01** [AstroNvim/AstroNvim#670]
i am trying to setup codeaction to build and run golang project and I cant find any tutorial in documentation

**Comment by vladdoster** [comment]
That’s because Astronvim isn’t the place to look for that. 

Its documented by the go LSP

https://github.com/golang/tools/blob/master/gopls/doc/vim.md#neovim

**Comment by vladdoster** [comment]
I googled neovim go codeaction and there are plenty of articles on it...
