### ISSUE TITLE
Filetype not working anymore

### ISSUE THREAD

**Issue by flamendless** [AstroNvim/AstroNvim#672]
Hi, previous I have this in my config:
```lua
		filetype = {
			overrides = {
				-- extensions = { lua2p = "lua", },
				function_extensions = {
					lua = function()
						vim.bo.filetype = "lua"
						require("user.love").SetLove()
					end,
					lua2p = function()
						require("user.love").SetLua2p()
					end
				}
			},
		},
```
which adds syntax highlighting to my custom extension, but after updating to the latest astrovim config it does not work anymore, I also tried moving that to the `polish` function and:
```lua
    --also in polish
    vim.filetype.add = {
      extensions = {
        lua = function()
          vim.bo.filetype = "lua"
          require("user.love").SetLove()
        end,
        lua2p = function()
          require("user.love").SetLua2p()
        end
      }
    }
```

**Comment by mehalter** [comment]
Do you happen to have vim polyglot installed?

**Comment by flamendless** [comment]
No, i only have these additional plugins:
```lua
      {"gpanders/editorconfig.nvim"},
      {"f-person/git-blame.nvim"},
      {"simnalamburt/vim-mundo"},
      {"bkad/CamelCaseMotion"},
      {"dewyze/vim-tada"},

```

**Comment by mehalter** [comment]
Are you using nightly still? Or have you moved to using stable AstroNvim/Neovim? Also can you provide a link/paste your user config and I can try to take a look. I can't replicate on a base AstroNvim installation or my own configuration.

**Comment by flamendless** [comment]
> Are you using nightly still? Or have you moved to using stable AstroNvim/Neovim? Also can you provide a link/paste your user config and I can try to take a look. I can't replicate on a base AstroNvim installation or my own configuration.

Didn't work for stable and nightly. Now im using nightly. Here's the link to my config https://github.com/flamendless/AstroVim/tree/main/lua/user the `init_backup.lua` is the previous config that works before me updating

**Comment by mehalter** [comment]
According to `:help vim.filetype.add()` it looks like a function should return the string that it should set as the filetype. So I think it should be something like this:

```lua
    --also in polish
    vim.filetype.add = {
      extensions = {
        lua = function()
          require("user.love").SetLove()
          return "lua"
        end,
        lua2p = function()
          require("user.love").SetLua2p()
          return "lua"
        end
      }
    }
```

Have you checked the docs and tried something like this to follow what they describe?

> The filetype can be either a string (in which case it is used as the filetype directly) or a function. If a function, it takes the full path and buffer number of the file as arguments (along with captures from the matched pattern, if any) and should return a string that will be used as the buffer's filetype.

**Comment by mehalter** [comment]
It should go in the `polish` function since neovim 0.7 has moved `filetype.lua` to core Neovim. So this is no longer a plugin. I also just noticed your blunder in your `polish` function. Give this a try:

```lua
    --also in polish
    vim.filetype.add {
      extensions = {
        lua = function()
          require("user.love").SetLove()
          return "lua"
        end,
        lua2p = function()
          require("user.love").SetLua2p()
          return "lua"
        end
      }
    }
```

**Comment by flamendless** [comment]
Awesome. works now. now i need to turn off lua lsp for lua2p files

**Comment by mehalter** [comment]
do you just want to not change the filetype to `lua` like you had before? Just return `lua2p` or something instead of `lua`

**Comment by flamendless** [comment]
if i do that i dont get any syntax highlighting anymore

**Comment by mehalter** [comment]
Interesting, good luck haha I'm not sure of a good way to do that.

**Comment by flamendless** [comment]
Hmm calling `:set syntax=lua` manually works. i dont think that the `vim.cmd[[set syntax=lua]]` in the function is working. maybe theres a setup that loads after the buffer/file is loaded?

**Comment by flamendless** [comment]
Finally figured it out by accident, i removed the `return "lua"` and `return "lua2p"` and it works
