### ISSUE TITLE
How to change the colorscheme?

### ISSUE THREAD

**Issue by Javets70** [AstroNvim/AstroNvim#673]
https://astronvim.github.io/recipes/colorscheme
I tried the sonokai example given in this guide

From what I can understand , just adding the given code in `user/init.lua` should enable the colorscheme
But nothing happens when I do the changes in `init.lua` file.

I dont have much understanding of how neovim works , please try to make your answer as simple as possible.

Thanks

**Comment by mehalter** [comment]
Have you run a `:PackerSync` to install the new colorscheme?

**Comment by Javets70** [comment]
I did do that after writing the code in `init.lua` and saving it.

**Comment by mehalter** [comment]
Did you restart  after saving before the packer sync call? To load the new files

**Comment by Javets70** [comment]
Yes.

**Comment by Javets70** [comment]
I also tried the catpuccin example , which didnt work out very well.

```
Error detected while processing /home/javetsm/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/javetsm/.config/nvim/init.lua:25: Failed to load core.options

/home/javetsm/.config/nvim/lua/core/options.lua:9: Vim(colorscheme):E185: Cannot find color scheme 'catppuccin'
stack traceback:
        [C]: in function 'error'
        /home/javetsm/.config/nvim/init.lua:25: in main chunk
```
I got this error 

I did initiate the `:PackerSync` command after saving the changes and restart neovim.

**Comment by mehalter** [comment]
What version of AstroNvim do you have (if you run `:AstroVersion`

**Comment by mehalter** [comment]
Could you share your entire user configuration? The code provided on the website is an example minimal `user/init.lua`

**Comment by Javets70** [comment]
> What version of AstroNvim do you have (if you run `:AstroVersion`
 I tried to run the `:AstroVersion` command and it didnt work . I got an error `Not an editor command: AstroVersion`.

> Could you share your entire user configuration? The code provided on the website is an example minimal `user/init.lua`
 I havent made any specific changes of my own in `user/init.lua` . I copied the code from the guide as it is .

**Comment by Javets70** [comment]
So I removed the previous configuration and cloned the repository again.
Now am able to use `AstroVersion` command and it gives the output `Version: v1.4.4-8-g416736f`

I made the `user/init.lua` and copied the code from the guide for _sonokai_ example.

```
Error detected while processing /home/javetsm/.config/nvim/init.lua:
Failed to load core.utils
/home/javetsm/.config/nvim/lua/core/utils/init.lua:23: attempt to call field 'notify' (a nil value)
Failed to load core.options
/home/javetsm/.config/nvim/lua/core/options.lua:1: attempt to call field 'user_plugin_opts' (a nil value)
Failed to load core.plugins
/home/javetsm/.config/nvim/lua/core/plugins.lua:314: attempt to index field 'updater' (a nil value)
Failed to load core.autocmds
/home/javetsm/.config/nvim/lua/core/autocmds.lua:16: attempt to call local 'is_available' (a nil value)
Failed to load core.mappings
/home/javetsm/.config/nvim/lua/core/mappings.lua:30: attempt to call local 'is_available' (a nil value)
Failed to load core.ui
/home/javetsm/.config/nvim/lua/core/ui.lua:141: attempt to call field 'user_plugin_opts' (a nil value)
Failed to load configs.which-key-register
.../javetsm/.config/nvim/lua/configs/which-key-register.lua:28: attempt to call local 'is_available' (a nil value)
E5113: Error while calling lua chunk: /home/javetsm/.config/nvim/init.lua:23: attempt to call field 'user_plugin_opts' (a nil value)
stack traceback:
        /home/javetsm/.config/nvim/init.lua:23: in main chunk
Error detected while processing BufEnter Autocommands for "*":
Error executing lua callback: /home/javetsm/.config/nvim/lua/core/autocmds.lua:12: attempt to call field 'set_url_match' (a nil value)
stack traceback:
        /home/javetsm/.config/nvim/lua/core/autocmds.lua:12: in function </home/javetsm/.config/nvim/lua/core/autocmds.lua:11>
Error detected while processing VimEnter Autocommands for "*":
Error executing lua callback: /home/javetsm/.config/nvim/lua/core/autocmds.lua:12: attempt to call field 'set_url_match' (a nil value)
stack traceback:
        /home/javetsm/.config/nvim/lua/core/autocmds.lua:12: in function </home/javetsm/.config/nvim/lua/core/autocmds.lua:11>
```
I ran `neovim` after that which showed me this error.

**Comment by mehalter** [comment]
Do you get errors without a user config? These are very strange errors that don't seem related to your config. Could you try completely refreshing your installation?

Delete `~/.local/share/nvim/site` and `~/.cache/nvim` and then run `nvim +PackerSync`

**Comment by mehalter** [comment]
@Javets70 I did just notice that there is a missing comma in the documentation for the example sonokai snippet. I have updated this snippet on the docs. I can confirm that copy/paste of these (with the added missing comma) works.

```lua
return {
  colorscheme = "sonokai",
  options = {
    g = {
      sonokai_style = "shusia",
    },
  },
  plugins = {
    init = {
      { "sainnhe/sonokai" },
    },
  },
}
```

**Comment by Javets70** [comment]
I just checked both the examples and they work absolutely fine.
Thanks for the support.
