### ISSUE TITLE
Search icon is not displayed

### ISSUE THREAD

**Issue by Starlexxx** [AstroNvim/AstroNvim#677]
<img width="711" alt="image" src="https://user-images.githubusercontent.com/39801789/174769940-a7e589a1-2c1f-4216-a5a8-e304f07acac1.png">
Hi! I search icon is replaced with question mark. What can I do with it?

**Comment by Starlexxx** [comment]
I'm using Hack Nerd font btw

**Comment by Starlexxx** [comment]
I've also tried FiraCode Nerd Font and it didn't help. I'm using iTerm2. Can u recommend any other fonts, which works correct?

**Comment by kabinspace** [comment]
Can you try JetBrains Mono Nerd Font? FiraCode should have worked, can you try it in a different terminal like kitty?

**Comment by Starlexxx** [comment]
Thank u! All the problem was about terminal app)
