### ISSUE TITLE
using square bracket in keymap

### ISSUE THREAD

**Issue by dpriedel** [AstroNvim/AstroNvim#680]
Hi

I have several keymappings in my init.lua polish function which work fine.

However, when I try something like this:

`vim.keymap.set("n", "<]q>", ":cnext<CR>`

it has no effect.

I know the square bracket is set as a leader key so I assume I'm not doing this setting properly.

Thanks for your help.

**Comment by mehalter** [comment]
@dpriedel the leader key is not `]` base AstroNvim sets it as `<space>`

**Comment by mehalter** [comment]
I think what you want is: `vim.keymap.set("n", "]q", ":cnext<CR>")`

**Comment by mehalter** [comment]
is it because you need to do `<cmd>` instead of `:`? It probably needs to be `vim.keymap.set("n", "]q", "<cmd>cnext<CR>")`

**Comment by dpriedel** [comment]
Thanks ... that works !!


I thought I had read somewhere that ':' and <cmd> were equivalent.  I 
guess not.
