### ISSUE TITLE
Lazygit bug

### ISSUE THREAD

**Issue by afdallah** [AstroNvim/AstroNvim#687]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [ x ] `:PackerSync`
- [ x ] `:AstroUpdate`
- [ x ] restarted AstroNvim
- [ x ] Neovim version >= 0.7.0

**Describe the bug**
Lazygit navigation breaks, pressing any lazygit shortcut won't run the action. The cursor turns into vim cursor

**To Reproduce**
1. Open lazy git `<leader> gg`
2. Open lazygit shortcut list `<shift> ?`
3. Press `J` continuously and then press any lazygit shortcut

**Expected behavior**
Navigation and shortcut should work normally

**Screenshots**
[Video](https://asciinema.org/a/N56XQKbjujGy619NSzGRuSeai)

**Comment by mehalter** [comment]
I think keeping the discussion here is a good idea rather than segmenting it across issues. On the same note, thank you so much in advanced for searching through the issues and keeping the discussion localized ❤️ 

Maybe @afdallah can comment what they did with this.

**Comment by mehalter** [comment]
Also @julientaq I cannot replicate an issue like this. It could be a conflict in a mapping you have. If you move your user folder to a different location and try with just a default configuration can you replicate it? That could help figure out if it's coming from maybe a plugin setting up a mapping or something.

You can do something like 

```sh
mv ~/.config/nvim/lua/user ~/.config/nvim/lua/user_backup
```

and then open neovim

**Comment by julientaq** [comment]
Yeah, i’m workin on open source stuff, i got educated on how to try to not steal too much time to people who help you for free :D

i’m gonna check it i can see what happens. 

also, thank you for all the work you’re doing, really appreciaite astronvim 👍
