### ISSUE TITLE
Storing init.lua file in own dotfiles repository.

### ISSUE THREAD

**Issue by mtshrmn** [AstroNvim/AstroNvim#689]
I've encountered a problem, which I think a lot of other people have encountered/solved.
I want to store the lua/user/init.lua` file in my own reposity, but at the same time keep the ability to pull from this repo for the rest of the files.

How would I go on about doing it? 

P.S. Thank you for this amazing project, it really is wonderful.

**Comment by mehalter** [comment]
Check out the documentation: https://astronvim.github.io/configuration/manage_user_config

**Comment by mehalter** [comment]
The repository has the user folder in it's gitignore. So there won't be any conflicts with it existing. You can either do the method we describe with a dedicated repo. Or if you want to keep it with your other dotfiles just make a symlink to wherever your user folder is in your dotfiles repo

**Comment by mtshrmn** [comment]
Thank you for your quick answer. This was exactly what I was looking for.

(I can't believe I missed this section in the wiki...)
