### ISSUE TITLE
Disabling mappings in new key mapping setup

### ISSUE THREAD

**Issue by dpriedel** [AstroNvim/AstroNvim#691]
Hi
In the new user key mapping setup code (very nice, thanks), what is the proper way to disable mappings?

Specifically, disable some of the bufferline  mappings such as `<s-h>` and `<s-l>` .  Previously, this was done by :
`vim.keymap.del("n", "<s-h>")`
in the polish function.

A comment in the new example user init.lua says:

`      -- setting a mapping to false will disable it
      -- ["<esc>"] = false,
`

but this doesn't seem to work.

**Comment by mehalter** [comment]
This is a limitation of the API that we are doing. You still can use the `vim.keymap.del` if you would like in your polish function. For the API that we implemented to work properly you need to match the key to  what we have it defined as in the file. So we always capitalize `C` and `S` for ctrl/shift so could you try

```lua
return {
  mappings = {
    n = {
      ["<S-h>"] = false
      ["<S-l>"] = false
    },
  },
}
```

**Comment by mehalter** [comment]
You can browse the source code to see the exact keys for the mappings: https://github.com/AstroNvim/AstroNvim/blob/main/lua/core/mappings.lua

Sorry about this limitation :/

**Comment by dpriedel** [comment]
It's not a problem.  I just wanted to be sure I had not made an error 
somewhere..


I am a long-time vim user who is converting over to nvim, largely due to 
efforts such as yours in AtroNvim.


Thanks !!
