### ISSUE TITLE
Recording macro not showing in statusline

### ISSUE THREAD

**Issue by flamendless** [AstroNvim/AstroNvim#692]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0

**Describe the bug**

**To Reproduce**
1. Press macro key `q` + another key `w`
2. Look at statusline

**Expected behavior**
An indicator should show about macro being recorded

**Comment by mehalter** [comment]
@flamendless are you using nightly with the command line height equal to 0?

**Comment by flamendless** [comment]
> @flamendless are you using nightly with the command line height equal to 0?

I am using `nightly` the `0.8` one. Oh yeah i have height = 0 in option.lua

**Comment by flamendless** [comment]
Setting it to `1` fixes it. Thanks

**Comment by mehalter** [comment]
Yeah there are a lot of problems with that upstream that will be fixed before the official release of 0.8: https://github.com/neovim/neovim/pull/18961

The `neovim-0.8` branch is considered unstable and not fully functional at all times.

**Comment by flamendless** [comment]
I see, i just really need the breadcrumbs for easier work haha
