### ISSUE TITLE
can't delete key mapping

### ISSUE THREAD

**Issue by nasnoisaac** [AstroNvim/AstroNvim#693]
I want to change `gr` to telescope builtin reference. I try to delete it in `polish` function: 
```lua
vim.api.nvim_del_keymap('n', 'gr')
```
It doesn't work.
Error:
> E31: No such mapping

And I also add:
```lua
vim.keymap.set("n", "gr", function()
   require("telescope.builtin").lsp_references()
end
```
But it can't override it.

How can I do that?

**Comment by mehalter** [comment]
these mappings are handled by the LSP `on_attach` function. So you can do this like this in your  `user/init.lua` file:

```lua
return {
  lsp = {
    mappings = {
      n = {
        gr = {
          function()
            require("telescope.builtin").lsp_references()
          end,
        },
      },
    },
  },
}
```
