### ISSUE TITLE
How to remap copilot#Accept() to play nicely with copilot.vim

### ISSUE THREAD

**Issue by n15e** [AstroNvim/AstroNvim#701]
Trying out https://github.com/github/copilot.vim however it always ends up breaking and producing the following error message.

`copilot tab map has been disabled or is claimed by another plugin`

a bit of googling says its because of `nvim-cmp` and I have no idea how to fix this. I am new to neovim and astrovim and not really sure how to go about making the changes suggested in any of these places[1][2], would really appreciate if someone could tell me how they were able to fix this issue.

I followed https://astronvim.github.io/configuration/manage_user_config and made a custom user config init.lua file and then I tried defining a function inside the init.lua file and mapping it to the <Tab> key by doing

```
testFunc = function(fallback)  
▏ if cmp.visible() then
▏ ▏ cmp.select_next_item()                              
▏ else                                                   
▏ ▏ local copilot_keys = vim.fn["copilot#Accept"]()
▏ ▏ if copilot_keys ~= "" then                           
▏ ▏ ▏ vim.api.nvim_feedkeys(copilot_keys, "i", true)     
▏ ▏ else                                                 
▏ ▏ ▏ fallback()                                         
▏ ▏ end                                                  
▏ end                                                    
end,      
```                                               

and then in the `mappings`section I added

 ` ["<Tab>"] = { "testFunc", desc = "test" }`

and nothing happened. Sorry, I have no idea what I am doing.

[1]https://www.reddit.com/r/neovim/comments/sk70rk/using_github_copilot_in_neovim_tab_map_has_been/
[2]https://github.com/LunarVim/LunarVim/issues/1856#issuecomment-954224770

**Comment by n15e** [comment]
> 

Hey, thanks for the response. I just tried your suggestion, and it doesn't seem to fix the issue.

This is what I did.

In the options section in the user settings section I added 
```I did the following
options = {                                              
▏ opt = {                                                
▏ ▏ relativenumber = true, -- sets vim.opt.relativenumber
▏ },                                                     
▏ g = {                                                  
▏ ▏ mapleader = " ", -- sets vim.g.mapleader             
▏ ▏ copilot_no_tab_map = true, --vim.g.copilot_no_tab_map      <<<<<-------Added this
▏ },                                                     
},                                                       

```

and then in the mapping section of the file I added 

 ```
                                                                                        
 mappings = {                                                                            
 ▏ -- first key is the mode                                                              
 ▏ n = {                                                                                 
 ▏ ▏ -- second key is the lefthand side of the map                                       
 ▏ ▏ ["<C-s>"] = { ":w!<cr>", desc = "Save File" },                                      
 ▏ ▏ ["<C-J>"] = { "copilot#Accept(<Tab>)", silent = true, expr = true, script = true },    <<<<<-------Added this
 ▏ },                                                                                    
 ▏ t = {                                                                                 
 ▏ ▏ -- setting a mapping to false will disable it                                       
 ▏ ▏ -- ["<esc>"] = false,                                                               
 ▏ },                                                                                    
 },                                                                                      
                                                                                         
```

Now copilot doesn't even run. Running 

`:Copilot status`

gives the following message

`Copilot: <Tab> map has been disabled or is claimed by another plugin`

**Comment by Johnsiras** [comment]
> > 
> 
> Hey, thanks for the response. I just tried your suggestion, and it doesn't seem to fix the issue.
> 
> This is what I did.
> 
> In the options section in the user settings section I added
> 
> ```assembly
> options = {                                              
> ▏ opt = {                                                
> ▏ ▏ relativenumber = true, -- sets vim.opt.relativenumber
> ▏ },                                                     
> ▏ g = {                                                  
> ▏ ▏ mapleader = " ", -- sets vim.g.mapleader             
> ▏ ▏ copilot_no_tab_map = true, --vim.g.copilot_no_tab_map      <<<<<-------Added this
> ▏ },                                                     
> },                                                       
> ```
> 
> and then in the mapping section of the file I added
> 
> ```
>                                                                                        
> mappings = {                                                                            
> ▏ -- first key is the mode                                                              
> ▏ n = {                                                                                 
> ▏ ▏ -- second key is the lefthand side of the map                                       
> ▏ ▏ ["<C-s>"] = { ":w!<cr>", desc = "Save File" },                                      
> ▏ ▏ ["<C-J>"] = { "copilot#Accept(<Tab>)", silent = true, expr = true, script = true },    <<<<<-------Added this
> ▏ },                                                                                    
> ▏ t = {                                                                                 
> ▏ ▏ -- setting a mapping to false will disable it                                       
> ▏ ▏ -- ["<esc>"] = false,                                                               
> ▏ },                                                                                    
> },                                                                                      
>                                                                                         
> ```
> 
> Now copilot doesn't even run. Running
> 
> `:Copilot status`
> 
> gives the following message
> 
> `Copilot: <Tab> map has been disabled or is claimed by another plugin`

It suppose to be in the `i` mode not in the `n` mode?????

**Comment by n15e** [comment]
> > > 
> > 
> > 
> > Hey, thanks for the response. I just tried your suggestion, and it doesn't seem to fix the issue.
> > This is what I did.
> > In the options section in the user settings section I added
> > ```assembly
> > options = {                                              
> > ▏ opt = {                                                
> > ▏ ▏ relativenumber = true, -- sets vim.opt.relativenumber
> > ▏ },                                                     
> > ▏ g = {                                                  
> > ▏ ▏ mapleader = " ", -- sets vim.g.mapleader             
> > ▏ ▏ copilot_no_tab_map = true, --vim.g.copilot_no_tab_map      <<<<<-------Added this
> > ▏ },                                                     
> > },                                                       
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and then in the mapping section of the file I added
> > ```
> >                                                                                        
> > mappings = {                                                                            
> > ▏ -- first key is the mode                                                              
> > ▏ n = {                                                                                 
> > ▏ ▏ -- second key is the lefthand side of the map                                       
> > ▏ ▏ ["<C-s>"] = { ":w!<cr>", desc = "Save File" },                                      
> > ▏ ▏ ["<C-J>"] = { "copilot#Accept(<Tab>)", silent = true, expr = true, script = true },    <<<<<-------Added this
> > ▏ },                                                                                    
> > ▏ t = {                                                                                 
> > ▏ ▏ -- setting a mapping to false will disable it                                       
> > ▏ ▏ -- ["<esc>"] = false,                                                               
> > ▏ },                                                                                    
> > },                                                                                      
> >                                                                                         
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Now copilot doesn't even run. Running
> > `:Copilot status`
> > gives the following message
> > `Copilot: <Tab> map has been disabled or is claimed by another plugin`
> 
> It suppose to be in the `i` mode not in the `n` mode?????

Zoink! that was the issue. Thanks a lot, really appreciate it.
