### ISSUE TITLE
omnisharp and ionide

### ISSUE THREAD

**Issue by WillEhrendreich** [AstroNvim/AstroNvim#702]
I have been trying FOR DAYS to get this config to work with omnisharp and ionide, I'm a .net dev, and I really like the idea of using nvim for everything. 

first i tried it with the normal, basic config for astronvim. then i downloaded the one from @mehalter , and then tried to use this as a jumping off point. 

absolutely no luck. omnisharp will not attach to a buffer. I'm legit at my wit's end, lol. 

I'm baffled by lua, for sure, and i'm pretty sure someone who actually understands it would be able to point out what's going on in a heartbeat, but I'm just not sure what to do to wrestle this to the ground. 

omnisharp doesn't give a Cmd by default, because lspconfig doesn't do any work to figure out where it's installed. if you get that part solved, which i think i have, i cannot for the life of me get it to grab on to a proper project root. I keep getting it to telling me it can't find it when i run LspInfo when ive loaded a .cs file. 

Can someone get this silly thing working with their config and then link it or something?

**Comment by mehalter** [comment]
https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#omnisharp

Looking at the documentation for `omnisharp` you do need to set the `cmd` which  can be done like this:

```lua
return {
  lsp = {
    ["server-settings"] = {
      omnisharp = {
        cmd = { "/path/to/omnisharp-repo/run", "--languageserver", "--hostPID", tostring(vim.fn.getpid()) }
      }
    }
  }
}
```

Once this code is in place in your `user/init.lua` it looks for the either a `.sln` file or `.csproj` file for identifying the root. So you will want to make sure at least one of those types of files are present or the root will not be detected.

**Comment by mehalter** [comment]
It does also look like `nvim-lsp-installer` supports `omnisharp` so instead of installing omnisharp yourself and setting the `cmd` you can just us `nvim-lsp-installer`:

```lua
return {
  plugins = {
    ["nvim-lsp-installer"] = {
      ensure_installed = {
        "omnisharp",
      },
    },
  },
}
```

And once the installer installs the language server, it will handle setting the `cmd` appropriately and you don't need to set it manually. Then you just need to worry about the `.sln` and `.csproj` files being present in the project root.

**Comment by WillEhrendreich** [comment]
Ok, thank you, you did give me the breadcrumbs to follow that lead home. hahaha. 

One big consideration, and the reason i have to modify the cmd that's being passed in, is that my project structure shouldn't go off of the .csproj or the .fsproj files. that stops it from finding the root, it's always at the .sln file level. 

I got that working now, however.  

For those interested, the relevant code snippets are below. 

In my user.lsp.lua : 
```
--first off, up above the "return" table
  local getDotNetRoot = function(filepath)
    local lsp = require 'lspconfig'
    local root = lsp.util.find_git_ancestor(filepath)
    return root
  end

--Thanks @mehalter for this bit especially I never would have 
--been able to guess that I could set this information here. 
--How could I have figured out that you could set plugins here? 
--What calls this so that I can tell it to do this?   
plugins = {
    ["nvim-lsp-installer"] = {
      ensure_installed = {
        "omnisharp",
        "fsautocomplete",
      },
    },
  },

--important to skip fsautocomplete's setup here, if including ionide, 
--as it will spawn both servers on fsharp files if you don't. 
  skip_setup = { "tsserver", "clangd","fsautocomplete" }, 

    omnisharp = {
      root_dir = getDotNetRoot,
     },

    ionide = {
        root_dir = getDotNetRoot,
    },
```

My next issue with getting this squared away is I'm getting this: 
![image](https://user-images.githubusercontent.com/55286472/176952409-64c28545-6cdb-414c-9c82-901b993478cf.png)


I think, and correct me if I'm wrong,  this has to do with the server capabilities that are being assigned handlers? 

the error pops up specifically when I'm not on a word or symbol, which.. yeah.. of course there wouldn't be symbol information for white-space.. but.. like.. that's pretty annoying to have it spam messages every time my cursor is moving.. 

is there a way I can get it to shut up about it when it's not finding symbol information ? 

this only happens in from ionide or fsautocomplete from an fsharp file. 

also for some reason, and this might be unrelated, instead of the comment shortcut getting the proper "//" for fsharp, it gives me a "*/   [insert commented line]  /*" 

those work fine for csharp, which it also does the multiline for and it's not what I prefer, but fsharp multi line comments are (* and *)

**Comment by WillEhrendreich** [comment]
oh and the reference count is always zero.. even in the same file when it clearly has references. 

like this:
![image](https://user-images.githubusercontent.com/55286472/176954745-724973cb-1cec-480c-af1b-bf70eadb2fde.png)

**Comment by mehalter** [comment]
I'm not sure as I don't use these language servers and have never configured them before. I have run into similar stuff with LSP like `clangd` and have had to set custom capabilities. You can set server specific settings and capabilities with the `lsp.server-settings`. If you are able to find the correct settings that resolve your issue please comment back here just in case anyone else runs into this issue!

here is an example file for modifying `clangd` capabilities:

```lua
return {
  lsp = {
    ["server-settings"] = {
      clangd = {
        capabilities = {
          offsetEncoding = "utf-8",
        },
      },
    },
  },
}
```
