### ISSUE TITLE
cursor-style issue

### ISSUE THREAD

**Issue by remo7777** [AstroNvim/AstroNvim#703]
Hello i m using termux,
My default terminal-cursor-style=underline
After using nvim its 
terminal-cursor-style=bar
Why ??
How can i fix it ?
![IMG_20220625_113238](https://user-images.githubusercontent.com/28594846/175760475-d214c5d9-e01d-44c7-9d09-4864429221a5.jpg)

![IMG_20220625_113357](https://user-images.githubusercontent.com/28594846/175760515-dd18b0ad-8c32-46c5-a386-0296d63c1926.jpg)

**Comment by mehalter** [comment]
When you are running termux, what do you get when you run `echo $TERM`

**Comment by remo7777** [comment]
xterm-256color

**Comment by remo7777** [comment]
> When you are running termux, what do you get when you run `echo $TERM` (at the command line not in Neovim)

xterm-256color
