### ISSUE TITLE
Prettier is not working for me with React / React tsx

### ISSUE THREAD

**Issue by nappalm** [AstroNvim/AstroNvim#704]
I'm new to using `null-ls`, I understand it's for formatting.

My main problem is that it doesn't format my code using react, I have my `prettier.config.js` 
file in each of my projects, and I would like it to take that setting for formatting.

In the `user_example/init.lua` file I have added this:
```
["null-ls"] = function(config)
      local null_ls = require "null-ls"
      config.sources = {
        null_ls.builtins.formatting.prettier,
        null_ls.builtins.diagnostics.eslint,
      }
      config.on_attach = function(client)
        if client.resolved_capabilities.document_formatting then
          vim.api.nvim_create_autocmd("BufWritePre", {
            desc = "Auto format before save",
            pattern = "<buffer>",
            callback = vim.lsp.buf.formatting_sync,
          })
        end
      end
      return config -- return final config table
    end,
```

I still don't understand how I can make my code format work 🥲
Any suggestion?

**Comment by sharkby7e** [comment]
Did you install the prettier global npm package?

**Comment by nappalm** [comment]
> Did you install the prettier global npm package?

Yes, i found out it was problem because of my file name `user_example` to `user` that solved it.

And then I ran into another problem when saving...
Pressing `:w` brings up a notification saying:

`vin_lsp_formatting_sync: timeout
`

**Comment by mehalter** [comment]
Check out #529 for the timeout issue
