### ISSUE TITLE
Scrolling speed with Ctrl-f and Ctrl-b

### ISSUE THREAD

**Issue by pkazmier** [AstroNvim/AstroNvim#705]
I'm trying to determine if the scrolling speed I am seeing is intended or not. Attached is a video where I compare Astrovim scrolling speed with NeoVim started with `-u NORC` flag:

https://user-images.githubusercontent.com/747855/175786702-180eee6f-3d7a-4b44-be5d-dc3cd802ca7c.mov

Is this by design? Is there an option I can disable?  I'm on Mac OS X 12.3 using Kitty terminal (0.19..3) with NeoVim (0.7.0).

**Comment by pkazmier** [comment]
I figured this one out on my own after trying to disable each plug-in one at a time to find the offender, which was cinnamon. I tried to disable the plug-in via my user config per the comments in the file, but it had no effect. Did I configure this correctly?

```lua
  -- Configure plugins
  plugins = {
    -- Add plugins, the packer syntax without the "use"
    init = {
      -- You can disable default plugins as follows:
      -- ["goolord/alpha-nvim"] = { disable = true },
      ["declancm/cinnamon.nvim"] = { disable = true },
```

As a workaround, I configured the cinnamon plug-in with a `scroll_limit` of `0`, which fixed my problem. I would like, however, to disable the plug-in entirely.

```lua
    -- Disable smooth scrolling as it makes nvim feel so slow (might as well be using emacs)
    cinnamon = function(config)
      config.scroll_limit = 0
      return config
    end,

```

On a side note, I'm surprised that people actually like this plug-in. One of the best advantages to vim/neovim is the lightning-fast responsiveness. In my opinion, this is one of the major factors as to why it is better than emacs, vscode, etc .. It seems so odd to me that folks would want to intentionally slow it down. To each their own I suppose. 🤷

**Comment by half-potato** [comment]
In the polish section of user.lua, I put:
```
require('cinnamon').setup {
  scroll_limit = 0,
}
```

The plugin hurts my eyes and gives me a headache. I don't understand it.

**Comment by dohsimpson** [comment]
> I figured this one out on my own after trying to disable each plug-in one at a time to find the offender, which was cinnamon. I tried to disable the plug-in via my user config per the comments in the file, but it had no effect. Did I configure this correctly?
> 
> ```lua
>   -- Configure plugins
>   plugins = {
>     -- Add plugins, the packer syntax without the "use"
>     init = {
>       -- You can disable default plugins as follows:
>       -- ["goolord/alpha-nvim"] = { disable = true },
>       ["declancm/cinnamon.nvim"] = { disable = true },
> ```
> 
> As a workaround, I configured the cinnamon plug-in with a `scroll_limit` of `0`, which fixed my problem. I would like, however, to disable the plug-in entirely.
> 
> ```lua
>     -- Disable smooth scrolling as it makes nvim feel so slow (might as well be using emacs)
>     cinnamon = function(config)
>       config.scroll_limit = 0
>       return config
>     end,
> ```
> 
> On a side note, I'm surprised that people actually like this plug-in. One of the best advantages to vim/neovim is the lightning-fast responsiveness. In my opinion, this is one of the major factors as to why it is better than emacs, vscode, etc .. It seems so odd to me that folks would want to intentionally slow it down. To each their own I suppose. 🤷

I had the same issue and I figured out how to disable the plugin completely. Put `["declancm/cinnamon.nvim"] = { disable = true },` and then run a `:PackerSync`, it would prompt you to remove the cinnamon plugin. After removing, restart nvim and it is now gone.
