### ISSUE TITLE
When opening a file with neovim through a file manager, some errors appear.

### ISSUE THREAD

**Issue by Hexavall** [AstroNvim/AstroNvim#710]
**Checklist**
- [DONE] `:PackerSync`
- [DONE] `:AstroUpdate`
- [DONE] restarted AstroNvim
- [DONE] Neovim version >= 0.7.0

**Describe the bug**
When I open a file with Neovim through a file manager (PCManFM / Vifm / Ranger), an error appears (first screenshot). Also, when I type, another error appears (second screenshot).

**To Reproduce**
Steps to reproduce the behavior on PCManFM:
1. Open PCManFM
2. Go to the file you want to open, right click it and select 'neovim'
3. You'll get those errors

Steps to reproduce the behavior on Vifm / Ranger:
1. Open Vifm / Ranger
2. Using vim keys or arrow keys, go to the file you want to open
3. Press L or right arrow to open it with vim/nvim
4. You'll get those errors

**Expected behavior**
The expected behavior is to have no errors, as when I use the console.

**Screenshots**
![2022-06-26_18-40](https://user-images.githubusercontent.com/75350161/175835076-c83ce1ec-f23f-45d2-ae2d-e0d3406cd28f.png)
![2022-06-26_18-41](https://user-images.githubusercontent.com/75350161/175835087-5e7dd502-92d4-44ef-aa0c-42972d41de89.png)

**Comment by mehalter** [comment]
This appears to be an issue with one of your language servers. You should look at LSP logs to try and debug what is going on and why it's not running. I believe this will most likely be separate from AstroNvim's base code.
