### ISSUE TITLE
custom setting like in a vimrc

### ISSUE THREAD

**Issue by xApologize** [AstroNvim/AstroNvim#713]
Hello!

I'm trying out astrovim instead of using vim. I have a couple of setting I like to have in my .vimrc, like disabling the arrow key. I was wondering how can I set those up with astrovim? When I try to set them in user/init.lua using vim.cmd([[]]) it gives me error.

**Comment by pkazmier** [comment]
In your `user/init.lua` file, you'll see a `mappings` section around line 211 (there are three mapping sections in the file, so make sure you find the correct one) if you copied the one from `user_example`. You can add the following:

```lua
mappings = {
    -- first key is the mode
    n = {
      -- second key is the lefthand side of the map
      ["<Up>"] = { function() end },
      ["<Down>"] = { function() end },
    },
```

I think you should just be able to do the following, but for some reason it did not work for me:

```lua
mappings = {
    -- first key is the mode
    n = {
      -- second key is the lefthand side of the map
      ["<Up>"] = false,
      ["<Down>"] = false,
    },
```

**Comment by xApologize** [comment]
thanks for your help, unfortunately I tried both of them and it does not work for me. I made myself a init.lua in `~.config/nvim/lua/user` and this is what I have in it:
![init](https://user-images.githubusercontent.com/104783397/176016150-7a422ab5-2a25-40da-a642-80a5a176ac4e.PNG)
I am most likely doing something wrong! it is the first time that I am trying it out!

**Comment by pkazmier** [comment]
You need to move `colorscheme`, `options`, and `plugins` into your `config` table above. Then you need to `return config` at the end of the file.

```lua
local config = {
  mappings = { ... },
  colorscheme = ...,
  options = { ... },
  plugins = { ... },
}
return config
```

**Comment by xApologize** [comment]
insane! thank you so much! one last thing and I'm not sure if you will be able to help but l'll give it a shot. In my .vimrc i have setting that show the tabs with |\\\ :
![exemple](https://user-images.githubusercontent.com/104783397/176026236-13064112-613e-4e4f-9887-f92e27e2473a.PNG)
is it possible to add that to astronvim?

the setting I use in my vimrc is  set list lcs=tab:\|\

**Comment by pkazmier** [comment]
You can set options in the `options` block. For example:

```lua
local config = {
  options = {
    opt = {
      listchars = { tab = "│→", extends = "⟩", precedes = "⟨", trail = "·", nbsp = "␣" },
    },
    g = { ... },
  }
  mappings = { ... },
  colorscheme = ...,
  plugins = { ... },
}
```

I've just discovered AstroVim yesterday, so I'm bumbling around as well, but a great help for me was reviewing the @mehalter's personal [configuration](https://code.mehalter.com/projects/68/files/master). In fact, I like most of his settings and plug-ins save for a few minor keybindings (they really should be the default imo). He breaks his configuration into multiple files, but it's still a great resource once you wrap your head around the fact that each table in the single file can be its own file.
