### ISSUE TITLE
Quick-scope for easier horizontal navigation

### ISSUE THREAD

**Issue by Stianhn** [AstroNvim/AstroNvim#714]
Have you considered adding quick-scope to the project? I find it really helpful for speeding up my horizontal navigation.

https://github.com/unblevable/quick-scope

**Comment by mehalter** [comment]
There are a lot of plugins that achieve this and picking one will not satisfy the needs of everyone necessarily. I think the default f/F/t/T functionality in vim covers 99% of cases for most people and this doesn't improve it enough to add as a default plugin.
