### ISSUE TITLE
Make the :LspInfo popup disappear by pressing 'q' rather than issuing ':qa'.

### ISSUE THREAD

**Issue by raw-bin** [AstroNvim/AstroNvim#716]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0

**Describe the bug**
Disclosure: This is firmly in the 'first world problems' bucket but I do think hits productivity. I mean: AstoNvim makes you get used to nice snappy feel so anything that gets in the way really stands out!

So basically the window that pops in response to invoking ':LspInfo' won't close on 'q' keypress. Needs ':qa' command line invocation or pressing the 'Esc' key. I also think that vim tends to always support C-g as an alternative to any situation where an 'Esc' is needed. That would be OK too.

For me, this hits the nice interactive and snappy flow that one generally experiences with AstroNvim. 'q' is easily accessible from the home row but esc is a mile away. Is there a way to fix this ?

**To Reproduce**
Issue ':LspInfo' in the nvim command line with any buffer open. Try pressing just 'q' in response to the resulting pop-up. I often press q twice when the window doesn't disappear which then incorrectly starts a macro recording.

**Expected behavior**
The pop-up should disappear in response to q.

**Comment by mehalter** [comment]
I think this is a feature request that should be made upstream with https://github.com/neovim/nvim-lspconfig
