### ISSUE TITLE
Add support for 'Search word under cursor'

### ISSUE THREAD

**Issue by raw-bin** [AstroNvim/AstroNvim#717]
**Is your feature request related to a problem? Please describe.**
I think grepping for the word under the cursor in the active buffer is a powerful and common action. At present, I have to redundantly type in the word after invoking Telescope using 'SPC-f-w'.

**Describe the solution you'd like**
I think an alternative 'Search word under cursor' AstroNvim option would be a better way.

I make it work like so by modding my user/init.lua but was hoping this became an official feature instead:
```
  polish = function()
    -- Set key bindings
    .
    .
    vim.keymap.set("n", "<leader>fc", function()
      require("telescope.builtin").grep_string()
    end, { desc = "Search word under cursor" })
    .
    .
  )
```

**Comment by raw-bin** [comment]
You guys Rock!!! :) Thanks!

**Comment by flamendless** [comment]
I also have this, i use `leader + g`
