### ISSUE TITLE
Trying to remap jj

### ISSUE THREAD

**Issue by windowsrefund** [AstroNvim/AstroNvim#720]
Hello,
I'm trying to remap jj to \<C-o>o so I can quickly move to a new line while in insert mode. I intend to use the mapping when autocomplete has completed the current line to my satisfaction. I've added the following to my ~/.config/astronvim/lua/user/init.lua file but it's having no effect.

```
local config  = {
  mappings = {
    i = {
      ["jj"] = { "<C-o>o", desc = "Skip to a newline while in insert mode" },
    }
  },
}

return config
```

**Comment by mehalter** [comment]
This mapping of `jj` is being set by `better-escape`. You can either disable this plugin all together, or if you like the `jk` mapping for escape you can jus disable the `jj` mapping in the configuration. Here are a couple options for `user/init.lua`

Disable `better-escape`:

```lua
return {
  plugins = {
    init = {
      ["max397574/better-escape.nvim"] = { disable = true },
    },
  },
}
```

Disable `jj` mapping:

```lua
return {
  plugins = {
    better_escape = {
      mapping = { "jk" },
    },
  },
}
```
