### ISSUE TITLE
Feat: Include projects button on alpha dashboard by default

### ISSUE THREAD

**Issue by Ya-suke** [AstroNvim/AstroNvim#723]
A `projects` button showing recent projects would be really useful.
The current alternative, `recents` button is useful but not as productive as a `projects` button could be.

**Comment by mehalter** [comment]
Neovim and AstroNvim do not really have a concept of "Projects" in the core setup so this doesn't necessarily align with the standard "vim" way of viewing things. I'm not sure of a good way to do this that would be nicely generalizable and it's not very standard. For now I am going to close this as unplanned, but if someone comes along with a good idea of how to implement this in a nice way then I will reopen it.
