### ISSUE TITLE
Deprecated LSP Plugin methods

### ISSUE THREAD

**Issue by SamuelWK** [AstroNvim/AstroNvim#724]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [ x] `:PackerSync`
- [ x] `:AstroUpdate`
- [ x] restarted AstroNvim
- [ x] Neovim version >= 0.7.0

**Describe the bug**
There is an error/warning when you are tryng to use lsp plugin in HTML files and others.
Error 1
![image](https://user-images.githubusercontent.com/100521346/177008894-53703d8b-f08a-4112-9ff8-c6f0b7187c2a.png)
Error 2
![image](https://user-images.githubusercontent.com/100521346/177008882-eb66fd00-8bfd-4cd6-ab47-7d1685fac653.png)
**To Reproduce**
To reproduce fhe first error, just go to any html file.

To reproduce the second error:
1. Go to any html file
2. Launh (SPACE + l + f)

Solution (Proposal)
I find this related issue
https://github.com/neovim/nvim-lspconfig/issues/1891

And this changes works for me.
https://github.com/SamuelWK/AstroNvim-custom/pull/2

**Comment by mehalter** [comment]
@SamuelWK could you please edit this issue to fill out the form? I'm not sure what bug you are trying to report.

**Comment by SamuelWK** [comment]
Sorry, miss click, the issue is already filled

**Comment by mehalter** [comment]
@SamuelWK it appears you are using Neovim nightly (0.8). AstroNvim does not officially support nightly or these breaking changes. If you want, you can try the `v2` branch which takes these into account. This is extremely experimental and not considered at all stable and under active development. We would recommend using AstroNvim with *stable* Neovim for a consistent and stable experience as well as being able for us to provide support.

**Comment by mehalter** [comment]
https://github.com/AstroNvim/AstroNvim/pull/715
