### ISSUE TITLE
Add the ability to disable code snippets (but leave other auto-completion features)?

### ISSUE THREAD

**Issue by leebeydoun** [AstroNvim/AstroNvim#725]
Hello, 

I am new to `vim` and `astro vim`. I was wondering if there is a way to disable code snippets in astro vim, and if not, can we add that feature?

Looking through the `lua` code, I found: `luasnip.lua` in the configs. It has the following content:

```lua
local user_settings = astronvim.user_plugin_opts "luasnip"

-- When I disable this plugin, I don't see snippets but get the remaining auto-completion behaviour I expect.
local loader_avail, loader = pcall(require, "luasnip/loaders/from_vscode")
if loader_avail then
  if user_settings.vscode_snippet_paths ~= nil then
    loader.lazy_load { paths = user_settings.vscode_snippet_paths }
  end
  loader.lazy_load()
end

local luasnip_avail, luasnip = pcall(require, "luasnip")
...
end
```

We always load the plugin from `luasnip/loaders/from_vscode`. May we add an option to disable this from ever being loaded? 

The issue I am seeing is that snippets will come up at the wrong time, or are just not that helpful for me. I've attached an example screenshot: 
![image](https://user-images.githubusercontent.com/56801187/177014045-0838718d-1509-40ae-8d01-825cb5c7f4d1.png)

**Comment by mehalter** [comment]
I believe you could do this in your `user/init.lua` file:

```lua
return {
  plugins = {
    init = {
      ["rafamadriz/friendly-snippets"] = { disable = true },
      ["L3MON4D3/LuaSnip"] = { wants = false },
    },
  },
}
```

**Comment by leebeydoun** [comment]
It's fine to close this issue as I am working around if for now (until I get a better understanding of vim config), but worth noting the above did not work for me. I still get all the snippets.

**Comment by mehalter** [comment]
Once you add the code snippet I provided, did you restart and run `:PackerSync`. I have fully tested the code I linked, it does cause friendly snippets to be fully removed and therefore no snippets will be available.

**Comment by leebeydoun** [comment]
Yup, my bad you are right. That above snippet does work after restarting and running `:PackerSync`. Amazing, thank you!
