### ISSUE TITLE
Neo-tree close if last window ignoring Aerial.nvim

### ISSUE THREAD

**Issue by jayp0521** [AstroNvim/AstroNvim#733]
**Is your feature request related to a problem? Please describe.**

I don't know if this belongs here. Doing `:q` with neotree (`close_if_last_window=true`) and aerial.nvim open should exit neovim

**Describe the solution you'd like**
It would be nice if there was an easy wait to quit nvim if after `:q` while neotree and aerial.nvim are open

**Additional context**
https://github.com/jayp0521/dotfiles/tree/main/nvim/.config/nvim/lua/user

**Comment by jayp0521** [comment]
Thanks for this!

**Comment by mehalter** [comment]
@jayp0521 no problem! This has introduced a small bug on AstroNvim nightly. Hopefully I can get it resolved alright: #886
