### ISSUE TITLE
Error with default_theme in `v2`

### ISSUE THREAD

**Issue by abalmos** [AstroNvim/AstroNvim#737]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0

**Describe the bug**
I have this error

```
Error detected while processing /home/abalmos/.config/nvim/init.lua:
Failed to load core.bootstrap
/home/abalmos/.config/nvim/lua/core/bootstrap.lua:4: Vim(colorscheme):E5113: Error while calling lua chunk: /home/abalmos/.config/nvim/lua/default_theme/init.lua:43: invalid key: style
stack traceback:
^I[C]: in function 'nvim_set_hl'
^I/home/abalmos/.config/nvim/lua/default_theme/init.lua:43: in main chunk
^I[C]: in function 'require'
^I/home/abalmos/.config/nvim/colors/default_theme.lua:9: in main chunk
^I[C]: in function 'nvim_command'
^I/home/abalmos/.config/nvim/lua/core/bootstrap.lua:4: in main chunk
^I[C]: at 0x007f4870
^I[C]: in function 'pcall'
^I/home/abalmos/.config/nvim/init.lua:14: in main chunk
```

with branch `v2` after pulling this morning. It appears to be caused by this commit: https://github.com/AstroNvim/AstroNvim/commit/e1785b8a62e2f0c666de53036e5ec2de5bac5ae0

While familiar with lua configs, I never really got into themeing. I am unsure what this change was trying to do to fix it.

**To Reproduce**
1. Checkout `v2`

**Expected behavior**
No error

**Screenshots**

**Additional context**
I am running neovim built from `master` just about an hour ago.

**Comment by mehalter** [comment]
This has been resolved with the latest push.

**Comment by abalmos** [comment]
Thanks, @mehalter. Seems obvious now :)

I'm not sure where else to put this. Let me know if there is a good place.

A plugin to watch: https://github.com/williamboman/mason.nvim

Written by the same author as `nvim-lsp-installer` but also manages DAP, linters, and formaters. The author felt it deviated from `nvim-lsp-installer` enough that it should be a [new plugin](https://github.com/williamboman/nvim-lsp-installer/issues/95#issuecomment-1176925455)

**Comment by mehalter** [comment]
Thanks for the heads up we've been discussing this on the discord today

**Comment by abalmos** [comment]
Is that public?

**Comment by mehalter** [comment]
Yeah it's on the README. Feel free to join! It's a great place to ask questions. I would also prefer bug reports on the v2 branch be reported on there if possible. Since it doesn't pertain to supported AstroNvim.

**Comment by abalmos** [comment]
Hmm, I don't see anything.. Searching for "Discord" doesn't bring anything up either. I don't use Discord, so I'm unsure what I should be looking for. I'm likely just blind :)
