### ISSUE TITLE
What is this menu and how can I disable it?

### ISSUE THREAD

**Issue by tpolito** [AstroNvim/AstroNvim#738]
This menu appears when the leader key is pressed, and I would like to remove it. I wasn't able to find the mapping in `mappings.lua`
![image](https://user-images.githubusercontent.com/29431348/177872809-fccfff4d-6743-4b12-8716-62c594dc5a65.png)

**Comment by Johnsiras** [comment]
> This menu appears when the leader key is pressed, and I would like to remove it. I wasn't able to find the mapping in `mappings.lua` ![image](https://user-images.githubusercontent.com/29431348/177872809-fccfff4d-6743-4b12-8716-62c594dc5a65.png)

It's basically the https://github.com/folke/which-key.nvim plugin which open a popup with suggestions for keybindings.
To disable it you can use 

```lua
["folke/which-key.nvim"] = { disable = true }

-- OR

{ "folke/which-key.nvim", disable = true }
```

**Comment by tpolito** [comment]
Awesome, thanks for the info.
