### ISSUE TITLE
After breaking changes in neovim file type detection doesnt work in current neovim  version

### ISSUE THREAD

**Issue by kmiasko** [AstroNvim/AstroNvim#739]
**Checklist**

- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0 (v0.8.0-dev+578-gca64b589cd)

**Describe the bug**

As described here: https://github.com/neovim/neovim/issues/14090#issuecomment-1177933661

Astrovim sets those variables in default config so filetype detection doesn't work properly.

temporary solution is to unlet those variables in polish section

`vim.cmd[[unlet g:do_filetype_lua]]`
`vim.cmd[[unlet g:did_load_filetypes]]`

**Comment by mehalter** [comment]
Fixed in latest commit
