### ISSUE TITLE
Unable to scroll LSP documentation

### ISSUE THREAD

**Issue by windowsrefund** [AstroNvim/AstroNvim#746]
Hello,
I've got the latest pyright working but noticed that I am unable to scroll LSP's documentation. I do believe there is more information available which I am not able to access. According to the [default configuration](https://astronvim.github.io/configuration/plugin_defaults#cmp), I believe I should be able to scroll down with C-d. Nothing is happening though. Do I first need to focus on it somehow?
![cmp-scroll](https://user-images.githubusercontent.com/512222/178124055-4b67ff0c-110a-48e3-95a5-591b25a9d08d.png)

**Comment by mehalter** [comment]
It is actually `C-f` that would scroll down and `C-d` scrolls up according to the default bindings. Also this documentation does not have anything to scroll, you are viewing the entire thing.

Here's an example of something with a scroll bar (you can see it on the right side:


![2022-07-10_10:11:59_screenshot](https://user-images.githubusercontent.com/1591837/178148587-ce0323a1-2f36-424f-964b-4739a56de3cc.png)

**Comment by windowsrefund** [comment]
Thank you for the feedback. Originally, I had been comparing my experience with that of someone on Discord who it turns out, is using pylance rather than pyright. I'm going to look into moving over to it as it seems like it may be more helpful to me at this stage.
