### ISSUE TITLE
Where can I add this configuration in my init.lua?

### ISSUE THREAD

**Issue by CMOISDEAD** [AstroNvim/AstroNvim#748]
I want to add this configuration to lspconfig in my user/init.lua but I don't know exactly where to add it

```lua
require("lspconfig").volar.setup({
    on_attach = function(client)
        client.resolved_capabilities.document_formatting = false
        client.resolved_capabilities.document_range_formatting = false
    end,
})
```
Thanks for the help 😄

**Comment by Clumsy-Coder** [comment]
There's two options
- adding to `Astronvim-repo/lua/user/init.lua` (i'm guessing the user configs will be located in `Astronvim-repo/lua/user/`)
- Splitting user configs from `init.lua` to it's own file in a modular form

## Adding to `user/init.lua`

You can try the following in `init.lua`

```lua
return {
  -- Astronvim configs ...

  -- LSP configs
  lsp = {
    ["server-settings"] = {
      volar = {
        on_attach = function(client)
          client.resolved_capabilities.document_formatting = false
          client.resolved_capabilities.document_range_formatting = false
        end,
      }
    }
  }
}
```

Also check
- https://github.com/AstroNvim/AstroNvim/blob/67c0c1e1b2cc0cdd2bd2bff4a20336587befd7b4/lua/user_example/init.lua#L173-L209
- https://astronvim.github.io/recipes/advanced_lsp

## Splitting AstroNvim configs

You can split LSP configs from `init.lua` to it's modular file structure.

### file structure

```
Astronvim-repo/lua/user/
├── lsp
│   ├── server-settings
│   │   └── volar.lua                 # volar LSP config
│   └── servers.lua                   # LSP servers to use
├── plugins                           # where to put plugin configs
│   ├── treesitter.lua                # configs for https://github.com/nvim-treesitter/nvim-treesitter
│   └── init.lua                      # additional plugins to install, enable or disable
└── init.lua                          # astronvim configs

```

### Astronvim-repo/lua/user/lsp/servers.lua
```lua
return {
  "volar"
}
```

### Astronvim-repo/lua/user/lsp/server-settings/volar.lua

```lua
return {
  on_attach = function(client)
    client.resolved_capabilities.document_formatting = false
    client.resolved_capabilities.document_range_formatting = false
  end,
}
```

Read about spliting configs
- https://astronvim.github.io/configuration/splitting_up
- https://astronvim.github.io/recipes/advanced_lsp

---

Personally I prefer splitting `user/init.lua` in a modular file structure. 

It's easier to manage, and `user/init.lua` is not a huge file.

Recommend checking these repos for inspiration on modularizing Astronvim configs
- https://code.mehalter.com/projects/68/files
- https://github.com/datamonsterr/astronvim_config

**Comment by CMOISDEAD** [comment]
thank you, you have helped me a lot 😀

**Comment by mehalter** [comment]
Thanks souch @Clumsy-Coder for helping out and providing such a detailed answer!
