### ISSUE TITLE
getting proper lsp when loading modules from Astronvim user configs

### ISSUE THREAD

**Issue by Clumsy-Coder** [AstroNvim/AstroNvim#749]
I'm currently trying to figure out how to get lsp suggestions when accessing a member of a loaded file for Astronvim user configs

Ex:
viewing cmp contents of `~/.config/nvim/lua/user/icons.lua` using LSP `sumneko_lua`

## using require("user.icons")
![image](https://user-images.githubusercontent.com/19594044/178163552-e01cfc52-c995-458e-9b6a-6e725c34252a.png)

## using require("astronvim.icons")
![image](https://user-images.githubusercontent.com/19594044/178163625-dec43d19-c6e1-445b-9519-ab29209e99d2.png)

I prefer to get suggestions when using `require("astronvim.icons")`

But, it gives errors, saying `astronvim` cannot be found (I'm using cmp-git to prove a point)
![image](https://user-images.githubusercontent.com/19594044/178163769-06cbc921-c312-46c2-9cca-d8a6d1a9428c.png)

<details>
<summary>
~/.config/nvim/lua/user/icons.lua
</summary>

```lua
-- Icons to be used by plugins
--
-- obtained from:
--    https://github.com/datamonsterr/astronvim_config/blob/main/icons.lua
--    https://github.com/AstroNvim/AstroNvim/blob/0fee587489/lua/configs/cmp.lua
--
-- https://github.com/microsoft/vscode/blob/main/src/vs/base/common/codicons.ts
-- go to the above and then enter <c-v>u<unicode> and the symbold should appear
-- or go here and upload the font file: https://mathew-kurian.github.io/CharacterMap/
-- find more here: https://www.nerdfonts.com/cheat-sheet
--   פּ ﯟ   蘒練 some other good icons

return {
  kind = {
    Array             = "",
    Boolean           = "⊨",
    Class             = "",
    Color             = "",
    Constant          = "",
    Constructor       = "",
    Enum              = "",
    EnumMember        = "",
    Event             = "",
    Field             = "ﰠ",
    File              = "",
    Folder            = "",
    Function          = "",
    Interface         = "",
    Key               = "",
    Keyword           = "",
    Method            = "",
    Misc              = " ",
    Module            = "",
    Namespace         = "",
    Null              = "NULL",
    Number            = "#",
    Object            = "⦿",
    Operator          = "",
    Package           = "",
    Property          = "",
    Reference         = "",
    String            = "𝓐",
    Struct            = "פּ",
    Snippet           = "",
    Text              = "",
    TypeParameter     = "",
    Unit              = "",
    Value             = "",
    Variable          = "",
  },
  type = {
    Array             = " ",
    Number            = " ",
    String            = " ",
    Boolean           = " ",
    Object            = " ",
  },
  documents = {
    File              = " ",
    Files             = " ",
    Folder            = " ",
    OpenFolder        = " ",
  },
  git = {
    Branch            = " ",
    Add               = " ",
    Modify            = " ",
    Remove            = " ",
    Ignore            = " ",
    Rename            = " ",
    Diff              = " ",
    Repo              = " ",
    -- Add               = " ",
    -- Modify            = " ",
    -- Remove            = " ",
  },
  ui = {
    Lock              = " ",
    Circle            = " ",
    BigCircle         = " ",
    BigUnfilledCircle = " ",
    Close             = " ",
    NewFile           = " ",
    Search            = " ",
    Lightbulb         = " ",
    Project           = " ",
    Dashboard         = " ",
    History           = " ",
    Comment           = " ",
    Bug               = " ",
    Code              = " ",
    Telescope         = " ",
    -- Gear              = " ",
    Gear              = "  ",
    Package           = " ",
    List              = " ",
    SignIn            = " ",
    Check             = " ",
    Fire              = " ",
    Note              = " ",
    BookMark          = " ",
    Pencil            = " ",
    ChevronRight      = "",
    Table             = " ",
    Calendar          = " ",
  },
  diagnostics = {
    Error             = " ",
    Warning           = " ",
    Information       = " ",
    Question          = " ",
    Hint              = " ",
  },
  misc = {
    Robot             = " ",
    Squirrel          = " ",
    Tag               = " ",
    Watch             = " ",
  },
}
```

</details>

# question
How do I get suggestions like using the `require("astronvim.icons")` without resulting in errors.
What settings I need to have in `~/.config/nvim/lua/user/lsp/server-settings/sumneko_lua.lua`

---

Astronvim version: latest
Git branch: `main`
commit ID: 67c0c1e1b2cc0cdd2bd2bff4a20336587befd7b4

<details>
<summary>
Astronvim user configs structure
</summary>

- Astronvim location: `~/.config/nvim`
- Astronvim user location: `~/.config/nvim/lua/user/`
```
~/.config/nvim/lua/user
├── cmp
│   └── source_priority.lua
├── icons.lua
├── lsp
│   ├── server-settings
│   │   ├── jsonls.lua
│   │   ├── sumneko_lua.lua
│   │   └── yamlls.lua
│   └── servers.lua
├── plugins
│   ├── cmp-git.lua
│   ├── cmp.lua
│   ├── nvim-lsp-installer.lua
├── polish.lua
└── updater.lua
```
</details>

<details>
<summary>
~/.config/nvim/lua/user/lsp/server-settings/sumneko_lua.lua
</summary>

```lua
-- lsp config for sumneko_lua
--
-- obtained from
-- https://github.com/hunger/AstroVim/blob/my_config/lua/configs/lsp/server-settings/sumneko_lua.lua
--
-- check sumneko_lua config
--    https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#sumneko_lua

require("notify")("loading sumneko")

return {
  on_attach = astronvim.lsp.disable_formatting,
  settings = {
    Lua = {
      runtime = {
        -- Tell the language server which version of Lua you're using (most likely LuaJIT in the case of Neovim)
        version = 'LuaJIT',
      },
      diagnostics = {
        -- Get the language server to recognize the `vim` global
        globals = { "vim" },
        enable = true
      },
      workspace = {
        -- Make the server aware of Neovim runtime files
        library = {
          [vim.fn.expand "$VIMRUNTIME/lua"]   = true,
          [astronvim.install.home .. "/lua"]  = true,     -- AstroNvim repo and custom configs
                                                          -- NOTE: when loading files in $NVIM_CONFIG_DIR_PATH/lua/user/ folder,
                                                          --       load with the prefix 'astronvim'
                                                          --       Ex: require("astronvim.icons")
                                                          --           This loads file $NVIM_CONFIG_DIR_PATH/lua/user/icons.lua
        },
      },
    },
  },
}

```
</details>

**Comment by mehalter** [comment]
Hm, could you try replicating this issue on a fresh AstroNvim installation with no user configuration outside of `user/icons.lua`? I can't seem to recreate this bug on a fresh installation, my installation, or a fresh installation with your changes to `sumneko_lua` server settings.
![2022-07-11_08:53:08_screenshot](https://user-images.githubusercontent.com/1591837/178269860-84dca0e6-1263-4936-a4e8-6235505d11c5.png)

**Comment by Clumsy-Coder** [comment]
I think I figured out the issue.

So I keep the Astronvim repo in `~/.config/nvim/`

And **symbolic link** the Astronvim user folder from my dotfiles (`dotfiles/tools/astronvim`) to Astronvim user folder

Resulting in
`~/.config/nvim/lua/user/ -> ~/dotfiles/tools/astronvim/`

---

# Testing scenarios

I will be testing the Astronvim user configs by

- Copying user configs to `~/.config/nvim/lua/user`
- Symbolic linking `~/dotfiles/tools/astronvim/` to `~/.config/nvim/lua/user/`

## Files

[astronvim.zip](https://github.com/AstroNvim/AstroNvim/files/9096775/astronvim.zip)

---

## copying Astronvim user configs to `~/.config/nvim/lua/user/`

The Astronvim user configs are **COPIED** to `~/.config/nvim/lua/user/`

Now if I add `local icons = require("user.icons")` to a file in the Astronvim user config folder, then the CMP and LSP works as intended.

Such as 
![2022-07-11_08:53:08_screenshot](https://user-images.githubusercontent.com/1591837/178269860-84dca0e6-1263-4936-a4e8-6235505d11c5.png)

## Symlinking `~/dotfiles/tools/astronvim/` to `~/.config/nvim/lua/user/`

The Astronvim user configs are **SYMBOLIC LINKED** from `~/dotfiles/tools/astronvim/` to `~/.config/nvim/lua/user/`

Resulting in
`~/.config/nvim/lua/user/ -> ~/dotfiles/tools/astronvim/`

Now if I add `local icons = require("astronvim.icons")` to a file in Astronvim user config folder, the CMP and LSP works in terms of autosuggest 
**BUT** the error still persists when saving and reopening the file because `astronvim.icons` doesn't exist.

---

## Diagnosis

My guess is `sumneko_lua` is using the original Astronvim config folder that was symlinked (named `astronvim`) instead of using the Astronvim foldername `user`

## Question

Is there a way to deal with this odd effect/bug?

**Comment by mehalter** [comment]
This is a very very odd behavior, thank you so much for reporting this and getting it in the issues! I'm not sure what the best way to approach this is... It could very  well be that the best answer is to open a bug report on `sumneko_lua` since this is not related to how AstroNvim configures things but a limitation of the language server itself. If you do have any luck or find a fix please comment back to help out any other users who run into this.
