### ISSUE TITLE
How would you specify which python version astrovim uses?

### ISSUE THREAD

**Issue by zicraftian** [AstroNvim/AstroNvim#750]
When I run :checkhealth neovim tells me that my python version is 3.8 when I would like it to use 3.10 instead. How would you specify which version astrovim uses? I am very new to the entire neovim community, and I am sorry if this is a dumb question.

**Comment by mehalter** [comment]
I believe the easiest way is to set the `g:python3_host_prog` variable to the path to your python binary in your `user/init.lua` file to point to the correct version. This will change which Python neovim is using. Here is an example:

```lua
return {
  options = {
    g = {
      python3_host_prog = "/usr/bin/python3.10",
    },
  },
}
```

**Comment by zicraftian** [comment]
> return {
>   options = {
>     g = {
>       python3_host_prog = "/usr/bin/python3.10",
>     },
>   },
> }

where should I put this as I have tried in my user/init.lua and nothing has changed

**Comment by mehalter** [comment]
Where did you put it?

**Comment by zicraftian** [comment]
Near the bottom. Sorry if I didn't do it right I know nothing of lua/vim

**Comment by zicraftian** [comment]
> Near the bottom. Sorry if I didn't do it right I know nothing of lua/vim
in  my lua/user init.lua file

**Comment by mehalter** [comment]
Are you using the provided example as a template? Here is a link to the section in the provided skeleton where you would put it: https://github.com/AstroNvim/AstroNvim/blob/main/lua/user_example/init.lua#L36-L44

The code snippet that I sent is an *entire* minimal `user/init.lua` file. Also you might need to modify the string that you set it to to point to where your python 3.10 binary is. But that is system specific.
