### ISSUE TITLE
Rebinding using Comment.nvim is difficult

### ISSUE THREAD

**Issue by half-potato** [AstroNvim/AstroNvim#754]
**Is your feature request related to a problem? Please describe.**
There is no clear way to rebind the custom commenter system.

**Describe the solution you'd like**
I would like documentation on a method for rebinding the comment key. Specifically, I want to bind it to <C-_>

**Comment by half-potato** [comment]
So it turns out I need to map both <C-_> and <C-/> to comment depending on the terminal being used.

**Comment by half-potato** [comment]
Also, this doesn't work anymore.

**Comment by half-potato** [comment]
aa768d177a3faf7444472791c9a8ef2a93ee9c89

**Comment by mehalter** [comment]
@half-potato have you updated comment.nvim? There were recent breaking changes that this fixed
