### ISSUE TITLE
E492: Not an editor command: PackerSync .

### ISSUE THREAD

**Issue by bouakram** [AstroNvim/AstroNvim#755]
os : windows 11
NVIM v0.7.2

bug is :
so, i'm trying to install astrovim , i run the clone command after that i run nvim +PackerSync command it show this error :  E492: Not an editor command: PackerSync .

![hghgh](https://user-images.githubusercontent.com/75098963/178622187-4ed78260-43e8-4eb5-96b9-82e288541df0.png)

**Comment by x-ray-s** [comment]
in nvim, run command
```
:echo stdpath('config')
```

```
git clone https://github.com/AstroNvim/AstroNvim YOUR_CONFIGURE_DIR
```

**Comment by bouakram** [comment]
after echo command this is the path :
![newconf](https://user-images.githubusercontent.com/75098963/178737145-3683f345-b3bb-458a-9a19-63e3fac0759c.png)
so i fond that i can't reach the path , after that i activate show hidden items and i find this files inside nvim-data : 
![new1](https://user-images.githubusercontent.com/75098963/178737682-3ac4cc56-bfd8-4f1e-aca2-477e5448b2bf.png)
so , do i need to create .conf file or just clone it directly here !


'in the first time i've create nvim file inside .config file and i've run the clone command there'

**Comment by bouakram** [comment]
hey @x-ray-s  thank you it's work fine now 🙏💕
