### ISSUE TITLE
How to set filetype for `.lagda.md`?

### ISSUE THREAD

**Issue by Eloitor** [AstroNvim/AstroNvim#759]
I would like to add `autocmd BufNewFile,BufRead *.lagda.md set filetype=agda`  in my config,

I tried:
``` lua
vim.api.nvim_create_autocmd("BufNewFile,BufRead", {
   desc = "Set agda.md filetype",
   -- I don't know how to continue
 }
```

How can I do it?

**Comment by Eloitor** [comment]
I also tried

```
    vim.filetype.add {
       extension = {
         foo = "fooscript",
       },
       pattern = {
         ["*.lagda.md"] = "agda",
     },
    }
```
But in this way, the .md extension seems to have precedence

**Comment by Rid1-fz-06** [comment]
@Eloitor first create an cmd group. Then try to create autocmd.

```lua
vim.api.nvim_create_augroup("autosave", { clear = true })
    vim.api.nvim_create_autocmd("CursorHold", {
      desc = "Automatically saves buffer when cursor is not moving",
      group = "autosave",
      pattern = "*",
      command = ":silent! update!"
    })
```

**Comment by Eloitor** [comment]
Thank you,

I managed to get this
```
    vim.api.nvim_create_augroup("filetypes", { clear = true })
    vim.api.nvim_create_autocmd("BufNewFile,BufRead", {
      desc = "Set agda.md filetype",
      group = "filetypes",
      pattern = "*.lagda.md",
      command = ":set filetype=agda"
    })
```

But files with the extension `.lagda.md` keep apearing as markdown files... How can I solve this?

I'm writing this configuration in `user/init.lua` inside the function `polish`....

**Comment by Rid1-fz-06** [comment]
@Eloitor you can add a new filetype using the following code segment...

https://github.com/AstroNvim/AstroNvim/blob/7b8315dd7c9f344b70a5c103394c74408c6c7430/lua/user_example/init.lua#L242-L253

**Comment by Eloitor** [comment]
I tried this, but no luck:
```
    vim.filetype.add {
      extension = {
        [ "lagda.md" ] = "agda",
        md = "markdown" -- this takes precedence
      },
      pattern = {
        [ "*.lagda.md" ] = "agda",
        [ "*.md" ] = "markdown",
      }
    }
```

**Comment by Eloitor** [comment]
I found a solution reading nvim's documentation https://neovim.io/doc/user/filetype.html. I created the file `~/.config/astronvim/ftdetect/lagda.md.vim` with the content:

```
au BufRead,BufNewFile *.lagda.md		set filetype=agda
```

And it worked! Not it detects the agda file (it doesn't show "agda" in the status line) and it also recognizes markdown files. I would like this to be better integrated in astrovim.

**Comment by mehalter** [comment]
@Eloitor do you happen to have `vim-polyglot` installed? I know that that plugin in particular completely breaks Neovim 0.7s filetype API which would explain why you needed to do the ftplugin file

**Comment by Eloitor** [comment]
No...

**Comment by mehalter** [comment]
Ah, I just took a look at this and I see where your problem is that you did not provide a proper regular expression to the `vim.filetype.add` block. Could you try this:

```lua
  vim.filetype.add {
    pattern = {
      [".*%.lagda%.md"] = "agda",
    },
  }
```

@Eloitor I have just tested this and it is working perfectly :) Notice that `.` is a special character in regex for "any character" so `.*` is any number of "any character" and then `%` is a way to escape special characters, so `%.` means the literal character `.`

So all together this is "any number of any characters followed by `.lagda.md`".

**Comment by Eloitor** [comment]
Thank you! This works :)
