### ISSUE TITLE
Implementing mason.nvim with nvim-lspconfig

### ISSUE THREAD

**Issue by Johnsiras** [AstroNvim/AstroNvim#760]
Hello, how i implement mason.nvim with nvim-lspconfig on astronvim? I tried the following snippets

## Snippets
1. Since the nvim-lspconfig was lazy loaded i tried to not load the plugin and add the mason.nvim plugin
```lua
return {
  ["neovim/nvim-lspconfig"] = {},
  ["williamboman/mason.nvim"] = {
    branch = "alpha",
    config = function()
      require("mason").setup()
      require("mason-lspconfig").setup()
    end,
  },

  -- And so on...
}
```
**Issue**: That didn't work. After installing a server it was not restarting/starting automatically the server.

---

2. Same to no. 1 but i removed the nvim-lspconfig plugin to not be loaded and just let the plugin to be lazy loaded, next i added the mason.nvim plugin but i lazy loaded it after nvim-lspconfig

```lua
return {
  -- Just let the plugin lazy loaded
  -- ["neovim/nvim-lspconfig"] = {},
  ["williamboman/mason.nvim"] = {
    -- lazy load after nvim-lspconfig
    after = "nvim-lspconfig",
    branch = "alpha",
    config = function()
      require("mason").setup()
      require("mason-lspconfig").setup()
    end,
  },

  -- And so on...
}
```

**Issue**: same to no. 1

---

3. Same to no.2 but i removed the lazy loading and still let the nvim-lspconfig be lazy loaded.

**Issue**: Welp, same to no. 1

---

How do i implement this?

**Comment by Johnsiras** [comment]
Btw this was in my `user/plugins/init.lua`

**Comment by mehalter** [comment]
@Johnsiras This has been implemented upstream so I am going to go ahead and close this. Here is the relevant announcement: https://github.com/AstroNvim/AstroNvim/discussions/820
