### ISSUE TITLE
How to gracefully fold the code in astroNvim

### ISSUE THREAD

**Issue by you-bowen** [AstroNvim/AstroNvim#761]
I'm the beginner of the vim, and I wonder is there a graceful way of folding my code so that code will be more neat.
I know that there is a nvim-plugin can do similar thing:
- [anuvyklack/pretty-fold](https://github.com/anuvyklack/pretty-fold.nvim)

but I don't know whether I can do folding in origin astroNvim.

**Comment by you-bowen** [comment]
finally find the solution: ^_^

edit `/Users/flag/.config/nvim/lua/user/init.lua`
```lua
  options = {
    opt = {
      foldmethod = "expr",
      foldexpr = "nvim_treesitter#foldexpr()",
      foldlevel = 99,
      foldenable = false,
      relativenumber = true, -- sets vim.opt.relativenumber
    },
```

but I wonder why it's not the default behaviour of my favourite astroNvim.

**Comment by pkazmier** [comment]
I'm curious how many people use folding. It is obviously important to you, but in my 30+ years of coding, I've never used folding in any editor.

I wonder if I'm the exception or the norm. Generally, if I'm looking for an overview of the code, I'll open the LSP symbol panel `<space>-l S` and navigate with aerial bindings.

I may have to give your settings a try, maybe I've been missing out on something for years. Thanks for sharing the resolution of your question.

**Comment by windowsrefund** [comment]
> but I wonder why it's not the default behaviour of my favourite astroNvim.

Not a complete answer to your original question but I figured it's worth pointing out that relativenumber is already enabled. One less line to maintain in your config :)
