### ISSUE TITLE
i don't know how to add colorschemes and plugin 

### ISSUE THREAD

**Issue by bouakram** [AstroNvim/AstroNvim#770]
hello i tried to add a colorscheme Tokyo Night but i dont know how , and there is a good plugin ( emmet plugin ) for web dev it is super helpful  i need it .. but the probleme is i dont know how to add theme , i used theme in vim before but i dont know how to add theme in astronvim ?

**Comment by mehalter** [comment]
#758 is also relevant for the colorscheme you asked about specifically. This is also covered in the documentation: 

https://astronvim.github.io/configuration/manage_user_config
https://astronvim.github.io/recipes/colorscheme
