### ISSUE TITLE
Docs on "available user options" suggests configuring the "lualine" plugin instead of "feline"

### ISSUE THREAD

**Issue by Jarmos-san** [AstroNvim/AstroNvim#772]
## Description of the Issue

It appears the documentations on "[available user options](https://astronvim.github.io/configuration/config_options)" still suggests configuring [`nvim-lualine/lualine.nvim`](https://github.com/nvim-lualine/lualine.nvim) instead of [`feline-nvim/feline.nvim`](https://github.com/feline-nvim/feline.nvim). See screenshot below for reference:

![image](https://user-images.githubusercontent.com/31373860/179809366-3c59ed73-414c-4b28-bfd1-922b6aced30d.png)

Is this intentional? As far as I can, there's no mention of configuring `lualine` instead of `feline` anywhere else except this one place.

**Comment by Jarmos-san** [comment]
@mehalter looks like you missed it in a couple more places! :sweat_smile: 

![image](https://user-images.githubusercontent.com/31373860/179814400-60516b72-7406-418a-ab09-3a2941251056.png)

**Comment by mehalter** [comment]
Ah, thanks for catching that too :joy: fixed haha
