### ISSUE TITLE
Jenkinsfile linting and syntax highlighting

### ISSUE THREAD

**Issue by a-marr** [AstroNvim/AstroNvim#773]
I'm not a lua programmer so having to translate the several vimscript solutions for this into lua is confusing me, especially with specific user configurations recommended in the astrovim docs. 

It would be nice to have built-in way to identify when a Jenkinsfile is opened and set the linting and syntax highlighting to the "groovy" filetype. This is probably similar to detecting a Dockerfile buffer being opened and setting the appropriate syntax highlighting.

Great nvim configuration so far!

**Comment by mehalter** [comment]
You can achieve this by defining a custom filetype in your `user/init.lua` file.

Here is an example complete `user/init.lua` file that sets this up:

```lua
return {
  polish = function()
    vim.filetype.add {
      filename = {
        Jenkinsfile = "groovy",
      },
    }
  end,
}
```
