### ISSUE TITLE
Pathway for integrating coc.nvim / swapping native LSP for coc.nvim?

### ISSUE THREAD

**Issue by rbutera** [AstroNvim/AstroNvim#774]
AstroNvim is awesome, it is my entrypoint to neovim as someone trying to migrate from vscode + vim.

There are some features from vscode I miss, and I want to see if `coc.nvim` can fill those gaps.

I want to see what `coc.nvim` is like with the rest of AstroNvim.

Is there a recommended pathway for using `coc.nvim` instead of native LSP? Can they be used together?

**Comment by mehalter** [comment]
@rbutera I'm not sure if there is a good way to use `coc.nvim` and native LSP in tandem. I will say the native LSP does have some pretty tight coupling with the base installation. I believe the following `user/init.lua` file would completely disable the native LSP and everything we do to configure it and completions, but I'm not sure if this will affect stuff in other places. But it is a good place to start:

```lua
return {
  plugins = {
    init = {
      ["williamboman/nvim-lsp-installer"] = { disable = true },
      ["neovim/nvim-lspconfig"] = { disable = true },
      ["hrsh7th/cmp-nvim-lsp"] = { disable = true },
    },
  },
}
```
