### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by V0idMatr1x** [AstroNvim/AstroNvim#779]
I have the necessary language servers, and grammars installed for syntax highlighting. However, it is only working in "File Preview" window in nvim. When I open the file in the editor, it has no syntax highlighting. How do I resolve this? Thanks in advance!

**Comment by resqiar** [comment]
Did you fix it? I have the same problem

**Comment by V0idMatr1x** [comment]
> Did you fix it? I have the same problem

Yes, I am using Arch, and for some reason it was because I was building from source & not using the AUR pkg of NeoVim to integrate with AstroVim. Your problem might be different, I am not sure.

**Comment by audacioustux** [comment]
> > Did you fix it? I have the same problem
> 
> Yes, I am using Arch, and for some reason it was because I was building from source & not using the AUR pkg of NeoVim to integrate with AstroNvim. Your problem might be different, I am not sure.

are you using neovim version 8+?

**Comment by Ish-Anji2022** [comment]
> are you using neovim version 8+?

I'm having same problem and I'm using neovim 8+, built from source. 
is it relatable?

**Comment by mehalter** [comment]
@Ish-Anji2022 Neovim nightly is not supported by AstroNvim. Please switch to a stable and officially released version of Neovim
