### ISSUE TITLE
How to add a simple plugin (example code_runner)

### ISSUE THREAD

**Issue by youcef4k** [AstroNvim/AstroNvim#784]
Hello,
I just installed Astronvim and I like everything about it for now. However, once I wanted to add a new plugin that supports Packer I got lost in the configuration.
This is the plugin I want to add:
https://github.com/CRAG666/code_runner.nvim

The GitHub contains all the necessary settings, but I couldn't figure out where to put them in my nvim/lua/user/init.lua file.
I put this line in the plugins init section and I could install the plugin with PackerSync:
`{ 'CRAG666/code_runner.nvim', requires = 'nvim-lua/plenary.nvim' }`

However, once installed I couldn't run the commands mentioned like RunCode and RunFile, it seems nvim doesn't recognize them as if the plugin is not enabled.

Also I couldn't figure out where to put the other settings like mappings and all.

`
vim.keymap.set('n', '<leader>r', ':RunCode<CR>', { noremap = true, silent = false })
vim.keymap.set('n', '<leader>rf', ':RunFile<CR>', { noremap = true, silent = false })
vim.keymap.set('n', '<leader>rft', ':RunFile tab<CR>', { noremap = true, silent = false }}
vim.keymap.set('n', '<leader>rp', ':RunProject<CR>', { noremap = true, silent = false })
vim.keymap.set('n', '<leader>rc', ':RunClose<CR>', { noremap = true, silent = false })
vim.keymap.set('n', '<leader>crf', ':CRFiletype<CR>', { noremap = true, silent = false })
vim.keymap.set('n', '<leader>crp', ':CRProjects<CR>', { noremap = true, silent = false })
`

and language settings: 
`
require('code_runner').setup({
  -- put here the commands by filetype
  filetype = {
		java = "cd $dir && javac $fileName && java $fileNameWithoutExt",
		python = "python3 -u",
		typescript = "deno run",
		rust = "cd $dir && rustc $fileName && $dir/$fileNameWithoutExt"
	},
})
`

I read the doc, but the part about user settings is not clear for a newbie, since there is only the example script without much explanation of what to go where.

Thank you for any help and also for this terrific plugin.

**Comment by mehalter** [comment]
@youcef4k are you  calling the `.setup` call described in the plugin documentation?

```lua
require('code_runner').setup({
  -- put here the commands by filetype
  filetype = {
		java = "cd $dir && javac $fileName && java $fileNameWithoutExt",
		python = "python3 -u",
		typescript = "deno run",
		rust = "cd $dir && rustc $fileName && $dir/$fileNameWithoutExt"
	},
})
```

Looks like this is the provided example. You can put this in the `packer` definition like this:

```lua
{
  "CRAG666/code_runner.nvim",
  requires = "nvim-lua/plenary.nvim",
  config = function()
    require("code_runner").setup {
      -- put here the commands by filetype
      filetype = {
        java = "cd $dir && javac $fileName && java $fileNameWithoutExt",
        python = "python3 -u",
        typescript = "deno run",
        rust = "cd $dir && rustc $fileName && $dir/$fileNameWithoutExt",
      },
    }
  end,
}
```

or you can just put it in the `polish` function in your `user/init.lua` file. I haven't used this plugin, but my guess is this plugin will not load without the `setup` call being made and the strings to define how to run different types of files are provided.

**Comment by youcef4k** [comment]
Thanks for your answers, I installed [SnipRun ](https://github.com/michaelb/sniprun)instead, it comes preconfigured, I added only keyboard mappings, and it works wonders.
