### ISSUE TITLE
Unable to use paredit

### ISSUE THREAD

**Issue by ledbruno** [AstroNvim/AstroNvim#785]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0

**Describe the bug**
Added       { "vim-scripts/paredit.vim"}
to my init.lua and it does not work. It does with regular nvim configuration using Plug. If that nos compatible, please ignore it. But i would like to know a way to enable paredit on Astrovim

**To Reproduce**
1. Install Nvim
2. Install Astrovim
3. Create your own init.lua file (under user folder)
4. Add  { "vim-scripts/paredit.vim"}   to your init.lua
Will look like this:  
```
 plugins = {
    -- Add plugins, the packer syntax without the "use"
    init = {
      -- You can disable default plugins as follows:
      -- ["goolord/alpha-nvim"] = { disable = true },

      -- You can also add new plugins here as well:
      { "Olical/conjure" },
      { "vim-scripts/paredit.vim"}
      -- { "andweeb/presence.nvim" },
      -- {
      --   "ray-x/lsp_signature.nvim",
      --   event = "BufRead",
      --   config = function()
      --     require("lsp_signature").setup()
      --   end,
      -- },
    },
```

5. Run PackerSync, it seems installed sucessfully
```
 paredit.vim
   url: "https://github.com/vim-scripts/paredit.vim"
   path: 
   "~/.local/share/nvim/site/pack/packer/start/paredit.vim"

```

6. Open a clojure file, and if you press down, will add () to the header of your file

**Expected behavior**
Regular usage of paredit, with LOCAL-LEADER UP/DOWN/LEFT/RIGHT moving parenthesis (barfing/slurping)

### More details
nvim --version
NVIM v0.8.0-dev+476-g3a4fa22ba
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

**Comment by ledbruno** [comment]
Same problem with LunarVim as well.
It seems related to this mapping
https://github.com/vim-scripts/paredit.vim/blob/master/plugin/paredit.vim#L150

If i remove it, it seems to work. But did not get, why does it conflict with astro/lunar ony. Vanilla nvim works fine with it

**Comment by mehalter** [comment]
I cannot replicated @ledbruno are you sure you are using the correct leader key for the bindings? It looks like according to the changelog (https://www.vim.org/scripts/script.php?script_id=3998) that they moved to using `<leader>` instead of `localleader` back in 2017 so maybe that could be it?

**Comment by ledbruno** [comment]
Hello, i did not press any of the leaders. Just pressed down, and it included ().

I found https://github.com/guns/vim-sexp today, maybe is a good alternative to paredit.vim

**Comment by ledbruno** [comment]
Open a regular clojure file
<img width="709" alt="image" src="https://user-images.githubusercontent.com/916289/180901115-fc8394cc-8e7c-48df-952b-e48afa0f3965.png">

Press down
<img width="250" alt="image" src="https://user-images.githubusercontent.com/916289/180901217-9daeba38-2f1d-48b2-b085-439088edcf40.png">

Just noticed that there is a NULL on the header (left)

**Comment by mehalter** [comment]
@ledbruno I just noticed that you are using Neovim 0.8. This is an unsupported and unreleased version of Neovim.

**Comment by mehalter** [comment]
I would recommend you use a stable version of Neovim as this error is most likely coming from some broken and unsupported change upstream
