### ISSUE TITLE
How can I see the full signature when autocompleting?

### ISSUE THREAD

**Issue by windowsrefund** [AstroNvim/AstroNvim#786]
Looking at the video on the [nvim-cmp](https://github.com/hrsh7th/nvim-cmp) site, I see this should be possible:

![cmp-want](https://user-images.githubusercontent.com/512222/180662866-9100a45c-faa3-4f33-ace8-c757686e1007.png)

And yet, here's what I'm working with:
![cmp-have](https://user-images.githubusercontent.com/512222/180664400-fcd91f2c-979c-4a97-a7b6-b613b4189d3a.png)

As per the advice given [here](https://github.com/hrsh7th/nvim-cmp/discussions/1069), I've installed [ray-x/lsp_signature.nvim](https://github.com/ray-x/lsp_signature.nvim) and enabled cmp's experimental ghost_text feature via my user/init.lua

**Comment by windowsrefund** [comment]
Just a note to mention I've tried various combinations of `completeopt` with no success.

**Comment by jayp0521** [comment]
https://github.com/jayp0521/dotfiles/commit/a96f99c68805804240ba92ff6df9880f2b42a896

I also tried, commit above. Unable it to get it working as well

**Comment by Rid1-fz-06** [comment]
@mehalter adding this feature will be very helpful whilst calling any function or instantiating any object. Can you please add this.

**Comment by mehalter** [comment]
@Rid1-fz-06 I don't think we want to leverage the experimental Ghost Text feature in `cmp` until it's known as stable

@windowsrefund I have also tried doing this as `cmp` describes in their repo and I can't get the entire signature either to show up. I have absolutely no idea how they did that or if this is just a bug in the `ghost_text` feature? 

I have been able to get the `lsp_signature` pop up to show up by just adding it and calling setup in my `user/init.lua` file but it's kinda big and in the way and I'm not sure if that's a good fit for the base installation of AstroNvim. I am going to drop the code here for just getting `lsp_signature` working and able to be configured, but I don't think we want to merge that into mainline AstroNvim. If someone is able to decipher how to get the entire signature in the virutal text that would be pretty cool and if we can show it's stable i would love to merge it. For now, I don't think there's much else I can do to get it working :(

```lua
return {
  plugins = {
    init = {
      { "ray-x/lsp_signature.nvim", config = function() require("lsp_signature").setup {} end },
    },
  },
}
```

This above will at least get a pop up when you start writing a function

![2022-08-11_11:51:50_screenshot](https://user-images.githubusercontent.com/1591837/184176033-f9cd9043-333e-4ed4-9e9e-dd92faf96b59.png)

![2022-08-11_11:52:14_screenshot](https://user-images.githubusercontent.com/1591837/184176036-36908c47-64bd-41ca-a48d-8c3af6e77e13.png)

**Comment by windowsrefund** [comment]
Thank you. I'll share any updates I come across.

**Comment by windowsrefund** [comment]
@mehalter I may have made some progress using [cmp-nvim-lsp-signature](https://github.com/hrsh7th/cmp-nvim-lsp-signature-help). First, I removed ray-x/lsp_signature.nvim as that wasn't getting me anywhere. Next, I added the following:

lua/user/plugins/init.lua
```
return {
  ["hrsh7th/cmp-nvim-lsp-signature-help"] = { config = require "user.plugins.cmp-nvim-lsp-signature-help" },
}
```
lua/user/plugins/cmp-nvim-lsp-signature-help.lua
```
return function ()
  require("cmp").setup {
    sources = {
      { name = 'nvim_lsp_signature_help' }
    }
  }
end
```
Now I write a small python file consisting of 2 methods with different signature styles. 
```
def foo(name: str):
    return name

def bar(age=20):
    return age
```
![foo](https://user-images.githubusercontent.com/512222/184796168-f61b4374-259f-425b-a6a6-2c572e4dfa63.png)
![bar](https://user-images.githubusercontent.com/512222/184796192-f2f0e667-5139-4b2e-a7f9-e2f35e5a8a7f.png)

Of course, the signature still isn't appearing on the same line like in the original comment/example so maybe this isn't actually "doing" what I think it is or should be. Not sure...

Also, I still can't improve what I see with anything lua (the table.insert example from my original post). All in all, this update may not be as informative as I had originally hoped but I'll leave everything for 2 reasons: 1) maybe that cmp source holds the key? and 2) this attempt to "do a thing" can probably serve as an excellent example of how confusing this stuff is for a non neovim Jedi :)

**Comment by abalmos** [comment]
@windowsrefund a caution that I only briefly looked over the issue, but I believe the feature you are asking for is called ghost text and in my experience it does not work well (yet).

https://github.com/hrsh7th/nvim-cmp/blob/b1ebdb0a17daaad13606b802780313a32e59781b/doc/cmp.txt#L594
