### ISSUE TITLE
Migrate from nvim-lsp-installer to mason.nvim

### ISSUE THREAD

**Issue by Jarmos-san** [AstroNvim/AstroNvim#787]
The author of [`nvim-lsp-installer`](https://github.com/williamboman/nvim-lsp-installer) released an announcement ([see discussion thread](https://github.com/williamboman/nvim-lsp-installer/discussions/876)) about deprecating the plugin in favour of the more powerful & full-featured [`mason.nvim`](https://github.com/williamboman/mason.nvim). So, are there any plans to migrate to the latter plugin in the near future (_perhaps from AstroNvim v0.9 onwards or something_)?

P.S: It appears to me, `mason.nvim` is still in its early stages of development so it might in the best interest of everyone to wait a while before jumping ship.

**Comment by mehalter** [comment]
Yes, we have been following.the mason development over the past couple weeks and have plans to move to it. We are planning to include this in the AstroNvim v2.0 release alongside Neovim 0.8 release which is probably going to be around October timeline.

**Comment by Johnsiras** [comment]
> Yes, we have been following.the mason development over the past couple weeks and have plans to move to it. We are planning to include this in the AstroNvim v2.0 release alongside Neovim 0.8 release which is probably going to be around October timeline.

Not related, but how about the snippets issue? Will it be fixed or not?

**Comment by mehalter** [comment]
@Johnsiras if I can get a way to replicate the issue then I would love to try and fix it. All indications point to that being an upstream bug with luasnip itself. People on LunarVim/NvChad/vanilla Neovim/AstroNvim have all experienced this issue for a long time in a random, nondeterministic, and non repeatable way and I have found issues all over the place referring to similar behavior you have mentioned. I haven't been able to replicate the issue after hours of attempts. If you can find a way to replicate it and identify the bug truly being an AstroNvim issue then I would really like to fix it.

**Comment by mehalter** [comment]
@Jarmos-san I am going to go ahead and rename this issue and use this as the main issue for tracking this improvement
