### ISSUE TITLE
files icons don't work

### ISSUE THREAD

**Issue by MedLabs** [AstroNvim/AstroNvim#791]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.2

**Describe the bug**
I've installed AstroNvim 0.7.2 and it works fine, but files icons don't show up in neo-tree, instead there are some kinda ASCI icons for every type of file. I don't know how to check if the icons plgin is correctly installed by default (I'm a beginner)

**To Reproduce**
1- install AstroNvim on fedora
2- open the silesystem explorer neo-tree

**Expected behavior**
custom icons should appear for every file type

**Comment by MedLabs** [comment]
I'm sorry I didn't install NerdFonts, I think it's related to this.

**Comment by mehalter** [comment]
@MedLabs yeah, you are required to have a NerdFonts compatible font to get the nice looking icons.

**Comment by zenVentzi** [comment]
Windows user here. From the nerd-fonts download [link](https://www.nerdfonts.com/font-downloads), should I download each and every font package listed on the page? I've currently installed the first one but absolutely no icons show up in the editor. I've tried both Windows Terminal and the default Command prompt.
