### ISSUE TITLE
Wrap error messages?

### ISSUE THREAD

**Issue by sharkby7e** [AstroNvim/AstroNvim#794]
![Screen Shot 2022-07-26 at 7 15 32 PM](https://user-images.githubusercontent.com/37809009/181145881-c97c9640-7059-4faa-9370-5464cbdbeeeb.png)

Is there a way to wrap the error messages that we get?

Would love help customizing this option from anyone who can!

**Comment by mehalter** [comment]
@sharkby7e you can use the binding `gl` to hover the line diagnostics and read the entire thing. This can also be done with `<leader>ld` for "LSP diagnostic"
