### ISSUE TITLE
Replace ncdu and htop with cross-platfom equivalents for Windows

### ISSUE THREAD

**Issue by sitiom** [AstroNvim/AstroNvim#795]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/56180050/181226415-dd9c0792-8a2f-443b-a78c-8c7addad806a.png)
Most of the optional requirements almost work in Windows, except for `ncdu` and `htop`. I would like to be able to replace both of them with cross-platform equivalents that work with Windows.

**Describe the solution you'd like**
For `ncdu`, [gdu](https://github.com/dundee/gdu) seems to be the best choice. It looks and functions like ncdu:
![image](https://user-images.githubusercontent.com/56180050/181227426-33f99a1a-17e9-48b6-ae37-ca18b6aec9c3.png)

For htop, I'm not sure. I personally use https://github.com/ClementTsang/bottom, but there are many other options as well.

**Additional context**

**Comment by mehalter** [comment]
Thanks for the recommendation! I'll throw another rec out to replace `htop` as well : https://github.com/xxxserxxx/gotop

**Comment by sitiom** [comment]
> Thanks for the recommendation! I'll throw another rec out to replace `htop` as well : [xxxserxxx/gotop](https://github.com/xxxserxxx/gotop)

Looks similar to bottom; which one to use (rust vs go) 🤔

**Comment by windowsrefund** [comment]
Honestly, I don't see why any of these tools should be supported. Get the user to a shell if need be and call it a day.

**Comment by sitiom** [comment]
> Honestly, I don't see why any of these tools should be supported. Get the user to a shell if need be and call it a day.

You can say that AstroNvim is a bit opinionated.

**Comment by mehalter** [comment]
I'm going to go ahead and close this since it's implemented and waiting until the v2.0.0 release
