### ISSUE TITLE
Remap SPC g g from lazygit

### ISSUE THREAD

**Issue by 0atman** [AstroNvim/AstroNvim#796]
Hi folks, I'm looking to remap `SPC g g` to a different git tool, I find `gitui` faster than `lazygit`, so I just want to swap it out.

Thanks!

**Comment by mehalter** [comment]
Here is a minimal `user/init.lua` file that just changes the `<leader>gg` binding to `gitui` instead of `lazygit`

```lua
return {
  mappings = {
    n = {
      ["<leader>gg"] = { function() astronvim.toggle_term_cmd "gitui" end, desc = "ToggleTerm gitui" },
    },
  },
}
```

**Comment by 0atman** [comment]
thank you so much! putting that at the end of my existing init.lua (a copy of the example one) doesn't seem to work (the init.lua holds an object that should have object['mappings'] right?)

Could you help me write it in this format?

```lua
  -- Modify which-key registration
  ["which-key"] = {
    -- Add bindings
    register_mappings = {
      -- first key is the mode, n == normal mode
      n = {
        -- second key is the prefix, <leader> prefixes
        ["<leader>"] = {
          -- which-key registration table for normal mode, leader prefix
          -- ["N"] = { "<cmd>tabnew<cr>", "New Buffer" },
        },
      },
    },
  },
```

**Comment by mehalter** [comment]
You will want to put it in the proper `mappings` table so that it overrides the default keybinding. This is here in the provided example:

https://github.com/AstroNvim/AstroNvim/blob/ba775276324b75e4f703cd63fea3cfe7726514de/lua/user_example/init.lua#L217-L227
