### ISSUE TITLE
Memory consumption rises endlessly until crash during long use

### ISSUE THREAD

**Issue by Noxdor** [AstroNvim/AstroNvim#797]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0

**Describe the bug**
I already am noticing this since long and I was always to lazy to open up an htop and investigate. Today I did and my nvim is hogging *6.8GB* of RAM after a few hours of constant use (no closing the instance). As I said, this happens to me often. First I feel the lags and that nvim is getting slower. Then, if it becomes to much, my OS kills it. Was just wondering if anyone else ever run into this, specially since I have not much in my user config;

```
return {
  luasnip = {
    vscode_snippet_paths = {
      "./lua/user/snippets",
    },
  },
  plugins = {
    init = {
      {
        "IndianBoy42/tree-sitter-just",
        config = function()
          require("tree-sitter-just").setup{}
        end
      },
    },
  },
}
```

**To Reproduce**
1. Use Nvim (with AstroNvim config) over a long period
2. Watch the memory usage go up, feel the lags
3. Watch it die

**Screenshots**
![screenshot_memory_nvim](https://user-images.githubusercontent.com/64439978/181277560-9cdd0d63-e988-40f1-abf3-ccc35a395a79.png)

**Additional context**
This is for sure not an issue with AstroNvim itself, but if it is an upstream issue in one of it's plugins, I thought it would be worth mentioning. Now that I wrote this, I realised it might be caused by "IndianBoy42/tree-sitter-just", but on this project, there is no issue mentioning this. So it might, it might not, I will uninstall the plugin and test it without. I don't think it is that though, because it is only the tree-sitter-syntax for just files, which I use rarely (and didn't use at all today).

**Comment by mehalter** [comment]
Hm, I haven't seen this and I don't think any plugins should be consuming a bunch of memory. I guess I would think the only culprit could be some language servers? But they should theoretically be in their own processes. I'm not sure if they get spun up under the `nvim` process for some reason

**Comment by mehalter** [comment]
When you experience this @Noxdor do you have any language servers running in particular?

**Comment by mehalter** [comment]
It could be Neovim LSP caching information that it has gathered by the given language server actually

**Comment by Noxdor** [comment]
Yes, the LSP instance stays separate of the nvim instance, but Neovim LSP caching information from the respective LSP makes very much sense to me!
So I was now programming a while in Rust to see if it's language server is also causing my neovim instance to skyrocket in memory use. It didn't! So clearly it is one of the LSPs I am using most of the times for work, which are `eslint-lsp` and `vue-language-server`. I found a similar issue in the `eslint-lsp` project but it was fixed and merged into master, so it can't be that I guess.

Anyway, this is clearly not a problem with AstroNvim or any of it's plugins, so I am closing this issue. Thank you for pointing me in the right direction!

**Comment by mehalter** [comment]
No problem! Thanks for putting such a detailed report :) that will be super useful if anyone has similar issues down the line!

**Comment by leoriohub** [comment]
I Expirience the same problem but in my case astrovim doesn't need to stay opened for a long period of time. 

**Context**:
I just installed astrovim to try it so I ran PackerSync and proceed to test Nvimtree which works for a period of 5-10 seconds until astrovim starts using all the (8GB) system ram.

**Note**:  *I come from my own lua configuration of nvim and I don't have any problem with nvim or Nvimtree.*

**Evidences**: I add an screenshot to show the skyrocket ram (and CPU) usage.

![Screenshot from 2022-11-30 19-43-48](https://user-images.githubusercontent.com/81123199/204925283-e6f6decf-e706-4220-99a2-bc42c532596a.png)

**Please let me know what else can do in order to hand you any other information needed.**
