### ISSUE TITLE
Make Telescope show hidden files

### ISSUE THREAD

**Issue by pratik-chakravorty** [AstroNvim/AstroNvim#799]
Hello,
I was working on a project that required me to view hidden files but currently any hidden file/folder are not searchable in Telescope. I tried to change the plugins config in user/init.lua to the following -

```
telescope = {
 pickers = {
   find_files {
  hidden=true

    }
 }
}
```
but that did not work. Any suggestions on how to make it show hidden files or folders starting with dot?

**Comment by mehalter** [comment]
@pratik-chakravorty here is an example `user/init.lua` file that does what you are describing. I'm not sure if you just had a copy/paste error but there were syntax errors in the code block you send. Just note that this block of code is an *entire* `user/init.lua` file so you will need to migrate the pieces that I have included into the `plugins` table in your own config:

```lua
return {
  plugins = {
    telescope = {
      pickers = {
        find_files = {
          hidden = true,
        },
      },
    },
  },
}
```

Also just to note, we do have the binding `<leader>fF` which searches through *all* files as as the `<leader>ff` which only searches non-hidden files
