### ISSUE TITLE
plugins section of user/init.lua seems to never get used.

### ISSUE THREAD

**Issue by CaptainJack42** [AstroNvim/AstroNvim#800]
I'm currently trying to customize my AstroNvim setup, which includes adding some plugins and customizing some plugins.

I copied the `init.lua` file from `lua/user_example` to `lua/user/init.lua` and it generally seems to work (e.g. when i set `relativenumber` in `options` to false it works, but adding plugins into the plugin section just doesn't do anything, for example when i add `["feline-nvim/feline.nvim"] = { disable = true }` to the `init{}` section of `plugins{}` it isn't disabled. 

I also tried adding the [nvim-window-picker](https://github.com/s1n7ax/nvim-window-picker) into the `plugin{}` and the `init{}` section, but neither one got recognized by packer. If i add it to `core/plugins.lua` it works however, but than i obviously can't update AstroNvim anymore.

Another thing i'd like to to is modify my [feline](https://github.com/feline-nvim/feline.nvim) config, which also worked by just changing the `feline.setup` in `lua/configs/feline.lua`. Is there any way i can just copy this file into my user folder and than call that file as setup for my feline config?

**Comment by Wanbicoi** [comment]
I met the same problem ;(

**Comment by mehalter** [comment]
@CaptainJack42 can you please share your entire current `user/init.lua` file and I can't take a look? You probably have a syntax error somewhere causing things to not be loaded.

**Comment by CaptainJack42** [comment]
> @CaptainJack42 can you please share your entire current `user/init.lua` file and I can't take a look? You probably have a syntax error somewhere causing things to not be loaded.

You can find my `user/init.lua` [here](https://pastebin.com/t3D3GmB4). Feline works now somehow (i honestly have no idea how since i didn't change anything afaik), but nvim-window-picker still isn't installed when runnying `:PackerSync` or `:PackerCompile`.

**Comment by mehalter** [comment]
Yeah this won't work, you have these in the wrong section and not in the `plugins.init` section of the file. One sec let me see the best way to send you a fixed version

**Comment by mehalter** [comment]
@CaptainJack42 here is a version where I moved the plugin definitions to the correct section: https://pastebin.com/xqay7nxY

I am on my phone trying to do this so apologies if its not formatted correctly

**Comment by CaptainJack42** [comment]
> @CaptainJack42 here is a version where I moved the plugin definitions to the correct section: https://pastebin.com/xqay7nxY
> 
> I am on my phone trying to do this so apologies if its not formatted correctly

Thank a lot this works!
