### ISSUE TITLE
using multiple spell-files

### ISSUE THREAD

**Issue by kraxli** [AstroNvim/AstroNvim#802]
Hi thanks a lot another time for the great config! 

I write in English and German. So I would like to have for both languages a spell file. However, I have failed to set a spell file for each of the languages. What I have tried in `lua/user/options.lua` is
```
    spellfile = {"~/.config/nvim/lua/user/spell/en.utf-8.add", "~/.config/nvim/lua/user/spell/de.utf-8.add"},
```
which is not working. What is the way to use multiple spell files?

**Comment by mehalter** [comment]
I'm not sure, but a quick Google search got me to here: https://vi.stackexchange.com/questions/3068/how-to-make-spellfile-work-for-multiple-languages

Maybe it can point you in the right direction :)

**Comment by kraxli** [comment]
@mehalter  thanks for your investigation which let me to got down the old Vim way :-)
Adding `~/.config/nvim/lua/user` to the `runtimepath`, e.g. in the `user\init.lua` file
```
vim.cmd [[set runtimepath+=~/.config/nvim/lua/user]]
```
let's Vim search for a `spell` directory in there. Additionally I don't set `-- spellfile`. With this set-up, a language specific `*.utf-8.add` file is set in the `spell` directory. Which of the `*.utf-8.add` files is used (filled by e.g. `zg`) depends on the language set.

Any improvements to this set-up (e.g. more in a `nvim/lua` way) are very welcome!

Thanks

**Comment by mehalter** [comment]
@kraxli I believe you can do this in a `lua` way with

```lua
vim.opt.rtp:append("~/.config/nvim/lua/user")
```

**Comment by mehalter** [comment]
also hm I am a little worried that there is going to be a fair amount of conflict when it comes to module name conflicts.... so idk if that is the best method. Maybe in this case it would make more sense to move your config to `~/.config/astronvim`? You can just move your `user/` folder to `~/.config/astronvim/lua/user/init.lua` and then have a spell folder in `~/.config/astronvim/spell/`

**Comment by kraxli** [comment]
> @kraxli I believe you can do this in a `lua` way with
> 
> ```lua
> vim.opt.rtp:append("~/.config/nvim/lua/user")
> ```

Thanks! Will try it out :-)

**Comment by kraxli** [comment]
> also hm I am a little worried that there is going to be a fair amount of conflict when it comes to module name conflicts.... so idk if that is the best method. Maybe in this case it would make more sense to move your config to `~/.config/astronvim`? You can just move your `user/` folder to `~/.config/astronvim/lua/user/init.lua` and then have a spell folder in `~/.config/astronvim/spell/`

Will `~/.config/astronvim/` be searched by astronvim any way or would I need to give a additional instruction? Would it also work on Windows OS?
Otherwise I have thought to move the spell-directory to a complete separate directory

**Comment by mehalter** [comment]
The `astronvim` directory is added to the runtime path automatically for some users who want to separate the installation with their config files completely. For windows it will be wherever your `nvim` folder is because we just use the building in `stdpath` functions to get the config folder

**Comment by kraxli** [comment]
great stuff! many thanks :-)
