### ISSUE TITLE
go doesn't use tabs

### ISSUE THREAD

**Issue by w1kee** [AstroNvim/AstroNvim#804]
hey, i code in go, which traditionally uses 8 wide tab indent
how can i setup tab indentation, and 8 wide tabs just for `.go` files?

**Comment by queue-tip** [comment]
user/polish.lua should include a call to autocmds. Mine looks like this:

    return {
      require "user.autocmds"
    }

user/autocmds.lua should have an autocmd like this:

    vim.api.nvim_create_autocmd("FileType", {
      pattern = "go",
      callback = function()
        vim.bo.tabstop = 8
        vim.bo.softtabstop = 8
        vim.bo.shiftwidth = 8
      end,
      desc = "Set tabs to 8 chars in Go files",
    })

**Comment by mehalter** [comment]
@queue-tip This is a great answer, thank you for helping out!

**Comment by aep** [comment]
gopls also doesnt work for me, oddly. something always forces shiftwidth=2 and i cant figure out what

```
:verbose set shiftwidth?                                                                                                                                                      
  shiftwidth=2
        Last set from Lua
```

but your autocmd tip helped, thanks!
