### ISSUE TITLE
Add vim-prettier plugin or update the documentation on how to install and configure addition plugins

### ISSUE THREAD

**Issue by tarunchhabriya06** [AstroNvim/AstroNvim#809]
**_Is your feature request related to a problem? Please describe._**

Hello,

I wanted to install the vim-prettier plugin and add some of my own configs but was not able to find any Documentation on the AstroVim repo for adding and configuring more plugins

**_Describe the solution you'd like_**

Please add the vim-prettier plugin for autoformatting code on the Buffer Write or add a section in the documentation for adding and configuring more plugins

**Comment by mehalter** [comment]
We would recommend using `null-ls` for formatting since it is included in AstroNvim. You can check out the user configuration for an example of configuring this: https://github.com/AstroNvim/AstroNvim/blob/ba775276324b75e4f703cd63fea3cfe7726514de/lua/user_example/init.lua#L98-L121

Here is a minimal `user/init.lua` file that just configures prettier with formatting on save:

```lua
return {
  plugins = {
    ["null-ls"] = function()
      local null_ls = require "null-ls"
      return {
        sources = {
          null_ls.builtins.formatting.prettier,
        },
        on_attach = function(client)
          if client.resolved_capabilities.document_formatting then
            vim.api.nvim_create_autocmd("BufWritePre", {
              desc = "Auto format before save",
              pattern = "<buffer>",
              callback = function() vim.lsp.buf.formatting_sync() end,
            })
          end
        end,
      }
    end,
  },
}
```

As for installing a plugin you can do this in the `plugins.init` table in the `user/init.lua` file with a structure like this:

```lua
return {
  plugins = {
    init = {
      { "repo_owner/repo_name",
        config = function()
          require("plugin_name").setup({})
        end
      }
    }
  }
}
```

**Comment by tarunchhabriya06** [comment]
Hi,

I tried using the default config for null-ls but that is not working on code save 
is there any step i need to do ?

**Comment by mehalter** [comment]
Did you add prettier to the list of formatters? It's not in the default config

**Comment by tarunchhabriya06** [comment]
yeah, I did...but that did not work so I reverted back to the default one rufo but that is also not working

**Comment by mehalter** [comment]
What files are you opening and are they supported by prettier? Do you have prettier installed on your machine? And when you open them does it show prettier as attached in the status bar bottom right?

**Comment by tarunchhabriya06** [comment]
1. I am opening javascript files and that is supported by prettier 
2. I installed prettier as a plugin through the plugin.init section. not sure if I can install prettier on a global level other than this method
3. yes prettier is showing in the status bar 
<img width="174" alt="image" src="https://user-images.githubusercontent.com/66588897/181920824-d27e1359-b5c1-4e66-98f9-ac49965f630f.png">

**Comment by mehalter** [comment]
Prettier is an external application outside of Neovim. If you just go to a terminal and run `prettier` does it run or do you get something like `command not found`. You will probably need to install it. It looks like you have correctly configured null-ls at least.

**Comment by tarunchhabriya06** [comment]
yeah okay will try
