### ISSUE TITLE
Theme color is off

### ISSUE THREAD

**Issue by b93rn** [AstroNvim/AstroNvim#814]
Hey guys,

I just started using AstroNvim and i think it's great! 
Currently only a minor thing puts me off a bit. I tried a bunch of different color schemes. They all look correct except for the curly and normal brackets which appear in red (see picture below). The picture was taken with the color theme Dracula (Mofiqul/dracula.nvim) and the installed Treesitter configuration is TSX (TypescriptReact). The same problem appears in different languages.

Since i'm new here i created this issue as a question, since it's probably some configuration mistake of mine. But it would be great if you guys could help me out!

![image](https://user-images.githubusercontent.com/13122883/182106580-bea49f89-6575-4f1f-aa6f-90947f6ff11a.png)

**Comment by mehalter** [comment]
This is coming from a plugin that we have `p00f/nvim-ts-rainbow` and the themes you are trying probably do not support it. You can either look for a theme that supports it, add the necessary highlight groups to your own personal configuration, or you can just disable this behavior. Here is a minimal `user/init.lua` file that simply disables the bracket/parentheses rainbow colors:

```lua
return {
  plugins = {
    treesitter = {
      rainbow = { enable = false },
    },
  },
}
```

*Note:* This is a full `init.lua` file. You will want to put the necessary line into your config in the `plugins.treesitter` table.

**Comment by b93rn** [comment]
Thanks a lot! I did not know about this plugin. Disabled it for now, but will definitely look in to it later on since the plugin actually makes a lot of sense after you mentioned it.
