### ISSUE TITLE
Treesitter works for js, ts, and jsx but not tsx

### ISSUE THREAD

**Issue by DylanSimowitz** [AstroNvim/AstroNvim#821]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0

**Describe the bug**
Treesitter is not being enabled for tsx files. I've tested on a fresh install of AstroNvim + `:TSInstall javascript typescript`. I'm not sure if this is an upstream issue or with AstroNvim.

**To Reproduce**
1. Install AstroNvim
2. Run `:TSInstall javascript typescript`
3. Open a .tsx file
4. No syntax highlighting and treesitter feline indicator not present

**Comment by mehalter** [comment]
Could you try running `:TSInstall tsx` as it has it's own treesitter parser. (https://github.com/nvim-treesitter/nvim-treesitter#supported-languages)
