### ISSUE TITLE
Rust does not have proper syntax highlighting

### ISSUE THREAD

**Issue by RockyGitHub** [AstroNvim/AstroNvim#825]
**Checklist**
- [x ] `:PackerSync`
- [x ] `:AstroUpdate`
- [x ] restarted AstroNvim
- [x ] Neovim version >= 0.7.0

**Describe the bug**
Rust does not have good syntax highlighting.  Many different syntax types are the exact same color which becomes very confusing.  It's the same issue for C# but I wanted to keep this issue to one language for now.
For example, functions are the same color as Types.
If/else/fn/match, etc are the same color as crates
and so on.

**To Reproduce**
1. Install the latest Neovim
2. Install the latest AstroNvim
3. Open a rust file with nvim

**Expected behavior**
I expect clear distinction of colors between syntax types, just like you would find in VSCode or CLion

**Screenshots**
![image](https://user-images.githubusercontent.com/10507443/182911322-cc2b9830-3624-4678-80db-30171e9ad955.png)
![image](https://user-images.githubusercontent.com/10507443/182911263-f9d83634-641d-4f2f-82ad-71ae871c4360.png)

**Additional context**
Screenshots are taken from rustlings's src/main.rs
--

**Comment by mehalter** [comment]
@kabinspace could you improve the syntax highlighting for the treesitter in the default theme? 

Probably something as colorful as what I get on Nightfox:
![2022-08-04_16:42:32_screenshot](https://user-images.githubusercontent.com/1591837/182948869-e83d989e-4aa2-4814-aa7b-474f5beae592.png)
