### ISSUE TITLE
Custom footer

### ISSUE THREAD

**Issue by CaitlinDavitt** [AstroNvim/AstroNvim#827]
**Is your feature request related to a problem? Please describe.**
I would like to have a custom footer in the dashboard, but I have not found a good way to do that yet.

**Describe the solution you'd like**
I would like to be able to add a custom footer to the dashboard in user/init.lua with the same syntax as a custom header

(Love your project BTW. I was having a lot of issues getting nvim set up properly from scratch and this has been a lot of help)

**Comment by mehalter** [comment]
@CaitlinDavitt this can be achieved with overriding the `alpha` config from the `plugins.alpha` table to override the `setup` function:

```lua
return {
  plugins = {
    alpha = function(config)
      config.layout[#config.layout + 1] = {
        type = "text",
        val = {
          "FOOTER HERE", -- put your footer here
        },
        opts = { position = "center", hl = "DashboardFooter" },
      }

      return config
    end,
  },
}
```
