### ISSUE TITLE
Inlay hints

### ISSUE THREAD

**Issue by b1twe1ser** [AstroNvim/AstroNvim#828]
Hello lovely people ! 
Is there a way we can enable inlay hints ?

**Comment by mehalter** [comment]
What language server are you trying to enable inlay hints for?

**Comment by mehalter** [comment]
My guess is this is a duplicate of #823 (This  includes code for setting up `rust-tools` for `rust_analyzer`

Neovim LSP does not have built in support for Inlay hints and it requires language specific plugins to add that functionality:

Relevant documentation: https://astronvim.github.io/recipes/advanced_lsp#lsp-specific-plugins

**Comment by b1twe1ser** [comment]
Thank you very much for your help, everything works like a charm now 💪🏼
