### ISSUE TITLE
there's no highlighting for Svelte

### ISSUE THREAD

**Issue by Huansock** [AstroNvim/AstroNvim#830]
i'can not set the highlighting for svelte is there a way for that..?

**Comment by mehalter** [comment]
Have you tried installing the appropriate highlighter? `:TSInstall svelte`

You can also install the appropriate LSP as well with `:LspInstall svelte`

**Comment by Huansock** [comment]
yep the problem was Tsinstall 
it was not automatically intalled.. 
thx btw!

**Comment by mehalter** [comment]
Yeah, we do not install treesitter parsers automatically. You can add the treesitter parsers that you want to install automatically in a `user/init.lua` file
