### ISSUE TITLE
No highlighting but highlighting in preview

### ISSUE THREAD

**Issue by HummingBird24** [AstroNvim/AstroNvim#832]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] restarted AstroNvim
- [X] Neovim version >= 0.7.0

**Describe the bug**

I'm not getting any highlighting at all but I can see highlighting in the file preview window.

I've TSInstalled typescript, tsx, and javascript and can see them installed under TSInstallInfo.

Neovim version: v0.8.0-dev-779-g7ebcb9b33

MacOS: 12.5

**To Reproduce**
I performed a clean install before installing Astro

1. sudo rm -rf ~/.config/nvim
2. rm -rf ~/.local/share/nvim
3. rm -rf ~/.cache/nvim
4. git clone https://github.com/AstroNvim/AstroNvim ~/.config/nvim
3. nvim +PackerSync
4. :q
5. vim
6. :LspInstall tsserver
7. :LspInstall tailwindcss
8. :TSInstall typescript
9. :TSInstall tsx
10. :TSInstall javascript
12. :PackerSync
13. :AstroUpdate
14. :q
15. close kitty terminal
16. open kitty terminal
17. nvim

**Expected behavior**
Syntax highlighting as shown in the README

**Screenshots**

No highlighting
<img width="1440" alt="Screen Shot 2022-08-05 at 10 51 10 AM" src="https://user-images.githubusercontent.com/16395981/183133986-5273066b-9883-401c-b38e-1d7ea8031ea9.png">

File preview
<img width="1241" alt="Screen Shot 2022-08-05 at 10 51 34 AM" src="https://user-images.githubusercontent.com/16395981/183134033-f26b1e42-7cda-4a37-894d-2aa39c62c559.png">

TSInstallInfo
<img width="344" alt="Screen Shot 2022-08-05 at 10 51 51 AM" src="https://user-images.githubusercontent.com/16395981/183133903-c84d736e-fb5b-4113-802e-28f41174249a.png">

**Comment by kabinspace** [comment]
@HummingBird24 Please use neovim version 0.7 for now, 0.8 is still unstable.

**Comment by HummingBird24** [comment]
@kabinspace That was it! thanks for the quick response

**Comment by earlyaugust2** [comment]
@vicentematus if you're using a mac, you can run `brew uninstall neovim && brew install neovim` that'll install the latest stable version which is v0.7.2

**Comment by vicentematus** [comment]
> @vicentematus if you're using a mac, you can run `brew uninstall neovim && brew install neovim` that'll install the latest stable version which is v0.7.2

Oh nice, my bad. I followed some YouTube tutorials on which they installed neovim nightly.

 Anyways i uninstalled neovim package and installed specifying the version now it seems to be working.

**Comment by earlyaugust2** [comment]
@vicentematus Perfect! Enjoy!
