### ISSUE TITLE
Format file on save

### ISSUE THREAD

**Issue by bramvbilsen** [AstroNvim/AstroNvim#835]
Is there a way to automatically format a file when it is saved?  
For example, I am building a project in Go and would like to use `gofmt`. Up until now, I've been using the cli commands to format manually, but ideally, it'd be possible to format automatically when saving a file. Or having a shortcut to formatting in general (not just a single language) would also be great!

_Sorry if this is trivial. I'm completely new to vim and there's tons of things to figure out!_

Thanks for this amazing config! :)

**Comment by mehalter** [comment]
@bramvbilsen 

Here is an example minimal `user/init.lua` file for achieving this with `gofmt` with automatic formatting on save:

```lua
return {
  plugins = {
    ["null-ls"] = function(config)
      local null_ls = require "null-ls"

      config.sources = {
        null_ls.builtins.formatting.gofmt,
        -- add more sources here for null-ls
      }
      config.on_attach = function(client)
        if client.resolved_capabilities.document_formatting then
          vim.api.nvim_create_autocmd("BufWritePre", {
            desc = "Auto format before save",
            pattern = "<buffer>",
            callback = function() vim.lsp.buf.formatting_sync() end,
          })
        end
        return config
      end
    end,
  },
}
```

This is using `null-ls` which is provided by the default configuration. This would go here in the provided example:

https://github.com/AstroNvim/AstroNvim/blob/3299c18961023837c295459d8b1dcec7cd4d299f/lua/user_example/init.lua#L98-L120

You can find a complete list of supported `null-ls` sources here: https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md

**Comment by bramvbilsen** [comment]
Hi, thanks for the help!
I'm not getting the expected result. I created a new folder called `user` with a new `init.lua` file. The path for this is as follows:
```
/Users/bramvanbilsen/.config/nvim/lua/user/init.lua
```
The `init.lua` file contains the following:
```lua
return {
  plugins = {
    ["null-ls"] = function(config)
      local null_ls = require "null-ls"

      config.sources = {
        null_ls.builtins.formatting.gofmt,
        -- add more sources here for null-ls
      }
      config.on_attach = function(client)
        if client.resolved_capabilities.document_formatting then
          vim.api.nvim_create_autocmd("BufWritePre", {
            desc = "Auto format before save",
            pattern = "<buffer>",
            callback = function() vim.lsp.buf.formatting_sync() end,
          })
        end
        return config
      end
    end,
  },
}
```
When saving a `.go` file, it does not get formatted. Is something wrong with my configuration?

**Comment by mehalter** [comment]
What version of `neovim` are you using. Also have you install `gofmt` to your system?

**Comment by bramvbilsen** [comment]
I can confirm I have `gofmt` on my system as I am able to use it from the command line.  
This is my `nvim -v` output:
```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
```

**Comment by mehalter** [comment]
Oh wait I see where the problem is in your config

```lua
return {
  plugins = {
    ["null-ls"] = function(config)
      local null_ls = require "null-ls"

      config.sources = {
        null_ls.builtins.formatting.gofmt,
        -- add more sources here for null-ls
      }
      config.on_attach = function(client)
        if client.resolved_capabilities.document_formatting then
          vim.api.nvim_create_autocmd("BufWritePre", {
            desc = "Auto format before save",
            pattern = "<buffer>",
            callback = function() vim.lsp.buf.formatting_sync() end,
          })
        end
      end
      return config
    end,
  },
}
```

You were returning config inside of the `on_attach` function that you were writing

**Comment by mehalter** [comment]
I had a typo in my previous code. Sorry about that!

**Comment by bramvbilsen** [comment]
Aha thanks 😊 
Upon saving now, I'm getting asked the question to choose between an LSP: `gopls` or `null-ls`. I've been using `gopls` as my LSP. Should I used `null-ls` to make `gofmt` on save work? Will this change anything to my config while editing? Or is it just for when files are being saved?

**Comment by mehalter** [comment]
This is just asking you which formatter to use at the current moment. `null-ls` is what you will want to use `gofmt`. This will become a pretty big nuisance because it will ask literally every time you want to format :joy: You can disable the formatting of `gopls` by changing the `on_attach` function specific for `gopls`. So your config would look something like this all together:

```lua
return {
  lsp = {
    ["server-settings"] = {
      gopls = {
        on_attach = function(client, bufnr) client.resolved_capabilities.document_formatting = false end,
      },
    },
  },
  plugins = {
    ["null-ls"] = function(config)
      local null_ls = require "null-ls"

      config.sources = {
        null_ls.builtins.formatting.gofmt,
        -- add more sources here for null-ls
      }
      config.on_attach = function(client)
        if client.resolved_capabilities.document_formatting then
          vim.api.nvim_create_autocmd("BufWritePre", {
            desc = "Auto format before save",
            pattern = "<buffer>",
            callback = function() vim.lsp.buf.formatting_sync() end,
          })
        end
      end
      return config
    end,
  },
}
```

**Comment by bramvbilsen** [comment]
This did the trick, thanks!!
If I understand this correctly, `gopls` will also try to format the file and we are disabling that in the `lsp` config. Is this correct?  
For future reference, to enable this feature in other languages I have to:
1. Add the formatting tool in `config.sources` of `["null-ls"]`
2. Disable document formatting in the lsp server settings

**Comment by mehalter** [comment]
Yup! Not all language servers will have a formatter so you won't necessarily have to disable formatting for every language server.

**Comment by bramvbilsen** [comment]
Awesome, thank you so much for getting me through my setup. Been loving AstroVim!

**Comment by mehalter** [comment]
Awesome! I'm glad you are enjoying it 🤗

**Comment by odecay** [comment]
Is this the same procedure we should go through for enabling format on save in Rust? Setup rustfmt as null-ls source, then disable something in rust-analyzer? Getting the same "chose a lsp" message.

Tried to find other issues referencing similar, I've set up rust-tools as well so I'm unsure if that complicates things further.

**Comment by mehalter** [comment]
do you want to use `rustfmt` or `rust-analyzer`? If you want to use `rustfmt` then the process is the exact same, you just want to disable the document formatting for the server settings of `rust_analyzer` in the on_attach function. All together would look something like

```lua
return {
  lsp = {
    skip_setup = { "rust_analyzer" },
    ["server-settings"] = {
      rust_analyzer = {
        on_attach = function(client, bufnr) client.resolved_capabilities.document_formatting = false end,
      },
    },
  },
  plugins = {
    init = {
      {
        "simrat39/rust-tools.nvim",
        after = "mason-lspconfig.nvim", -- make sure to load after mason-lspconfig
        config = function()
          require("rust-tools").setup {
            server = astronvim.lsp.server_settings "rust_analyzer", -- get the server settings and built in capabilities/on_attach
          }
        end,
      },
    },
    ["mason-lspconfig"] = {
      ensure_installed = { "rust_analyzer" }, -- install rust_analyzer
    },
    ["null-ls"] = function(config)
      local null_ls = require "null-ls"

      config.sources = {
        null_ls.builtins.formatting.rustfmt,
        -- add more sources here for null-ls
      }
      config.on_attach = function(client)
        if client.resolved_capabilities.document_formatting then
          vim.api.nvim_create_autocmd("BufWritePre", {
            desc = "Auto format before save",
            pattern = "<buffer>",
            callback = function() vim.lsp.buf.formatting_sync() end,
          })
        end
      end
      return config
    end,
  },
}
```

**Comment by mehalter** [comment]
@odecay just in case that didn't send you a notification

**Comment by odecay** [comment]
Thanks, it turned out I did want rust-analyzer formatting so your response in #823 was helpful.
