### ISSUE TITLE
Unable to get plugin configs to work.

### ISSUE THREAD

**Issue by A-Lamia** [AstroNvim/AstroNvim#836]
Was setting up some plugins  and they install and run fine but the configs are not working wandering if I'm doing something wrong.

```lua
-- neovide Settings.
vim.g.neovide_cursor_vfx_mode = "railgun"
vim.g.neovide_cursor_vfx_particle_lifetime = 1.5
vim.g.neovide_cursor_vfx_particle_density = 10
vim.g.neovide_transparency = 0.9
vim.opt.guifont = "VictorMono_NF:h14"

-- Tokyonight Settings, (must be set before colorscheme).
vim.g.tokyonight_style = "night"
if vim.g.neovide then
  vim.g.tokyonight_transparent = false
else
  vim.g.tokyonight_transpasent = true
end
vim.g.tokyonight_sidebars = { "qf", "vista_kind", "terminal", "packer" }

-- Local configuration
vim.o.autoread = true;

local config = {

  -- Configure AstroNvim updates
  updater = {
    remote = "origin", -- remote to use
    channel = "nightly", -- "stable" or "nightly"
    version = "la", -- "la", tag name, or regex search like "v1.*" to only do updates before v2 (STABLE ONLY)
    branch = "main", -- branch name (NIGHTLY ONLY)
    commit = nil, -- commit hash (NIGHTLY ONLY)
    pin_plugins = nil, -- nil, true, false (nil will pin plugins on stable only)
    skip_prompts = false, -- skip prompts about breaking changes
    show_changelog = true, -- show the changelog after performing an update
    -- remotes = { -- easily add new remotes to track
    --   ["remote_name"] = "https://remote_url.come/repo.git", -- full remote url
    --   ["remote2"] = "github_user/repo", -- GitHub user/repo shortcut,
    --   ["remote3"] = "github_user", -- GitHub user assume AstroNvim fork
    -- },
  },

  -- Set colorscheme
  colorscheme = "tokyonight",
  -- icons = require "nvim-nonicons",

  -- Add and configure plugins.
  plugins = {

    -- Add plugins
    init = {
      -- Tokyonight Theme.
      {"folke/tokyonight.nvim"},
      -- {"yamatsum/nvim-nonicons"},

      {"wsdjeg/vim-fetch"},

      -- Tagbar, needs ctags to work.
      {"preservim/tagbar"},
      {"folke/trouble.nvim"},

      {
        "Pocco81/true-zen.nvim",
        config = function()
          require("true-zen").setup {
            modes = {
              narrow = {
                folds_style = "invisible",
              },
              integrations = {
                twilight = true,
              }
            }
          }
          end,
      },
      {
        "folke/twilight.nvim",
        config = function()
          require("twilight").setup {
            context = 20
          }
        end,
      },

      {"RishabhRD/popfix"},
      {"RishabhRD/nvim-cheat.sh"},

      {"windwp/nvim-spectre"},

      {
      "phaazon/hop.nvim",
      branch = 'v1',
      config = function()
        require'hop'.setup { keys = 'etovxqpdygfblzhckisuran' }
      end
      },

      --- Language ---
      -- GLSL
      {'tikhomirov/vim-glsl'},
      -- Godot
      {"habamax/vim-godot"}
    },

    -- Plugin Configuration.
    packer = {
      compile_path = vim.fn.stdpath "data" .. "/packer_compiled.lua",
    }

  },
}

require'lspconfig'.gdscript.setup{capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())}


return config
```

**Comment by mehalter** [comment]
@A-Lamia I don't see any issues with how you are configuring your plugins. I did notice that you had some typos when it came to setting the `tokyonight_transparent` varaible. Also I have a few recommendations to help clean things up. Mainly with the `gdscript` setup call and the setting the Neovim options. You can rewrite all of this like this:

```lua
local config = {
  options = {
    g = {
      neovide_cursor_vfx_mode = "railgun",
      neovide_cursor_vfx_particle_lifetime = 1.5,
      neovide_cursor_vfx_particle_density = 10,
      neovide_transparency = 0.9,
      tokyonight_style = "night",
      tokyonight_transparent = vim.g.neovide == nil,
      tokyonight_sidebars = { "qf", "vista_kind", "terminal", "packer" },
    },
    opt = {
      guifont = "VictorMono_NF:h14",
    },
    o = {
      autoread = true,
    },
  },

  -- Configure AstroNvim updates
  updater = {
    remote = "origin", -- remote to use
    channel = "nightly", -- "stable" or "nightly"
    version = "latest", -- "latest", tag name, or regex search like "v1.*" to only do updates before v2 (STABLE ONLY)
    branch = "main", -- branch name (NIGHTLY ONLY)
    commit = nil, -- commit hash (NIGHTLY ONLY)
    pin_plugins = nil, -- nil, true, false (nil will pin plugins on stable only)
    skip_prompts = false, -- skip prompts about breaking changes
    show_changelog = true, -- show the changelog after performing an update
    -- remotes = { -- easily add new remotes to track
    --   ["remote_name"] = "https://remote_url.come/repo.git", -- full remote url
    --   ["remote2"] = "github_user/repo", -- GitHub user/repo shortcut,
    --   ["remote3"] = "github_user", -- GitHub user assume AstroNvim fork
    -- },
  },

  -- Set colorscheme
  colorscheme = "tokyonight",
  -- icons = require "nvim-nonicons",

  -- ONLY NECESSARY IF NOT INSTALLING WITH MASON
  lsp = {
    servers = {
      "gdscript",
    },
  },

  -- Add and configure plugins.
  plugins = {

    -- Add plugins
    init = {
      -- Tokyonight Theme.
      { "folke/tokyonight.nvim" },
      -- {"yamatsum/nvim-nonicons"},

      { "wsdjeg/vim-fetch" },

      -- Tagbar, needs ctags to work.
      { "preservim/tagbar" },
      { "folke/trouble.nvim" },

      {
        "Pocco81/true-zen.nvim",
        config = function()
          require("true-zen").setup {
            modes = {
              narrow = {
                folds_style = "invisible",
              },
              integrations = {
                twilight = true,
              },
            },
          }
        end,
      },
      {
        "folke/twilight.nvim",
        config = function()
          require("twilight").setup {
            context = 20,
          }
        end,
      },

      { "RishabhRD/popfix" },
      { "RishabhRD/nvim-cheat.sh" },

      { "windwp/nvim-spectre" },

      {
        "phaazon/hop.nvim",
        branch = "v1",
        config = function() require("hop").setup { keys = "etovxqpdygfblzhckisuran" } end,
      },

      --- Language ---
      -- GLSL
      { "tikhomirov/vim-glsl" },
      -- Godot
      { "habamax/vim-godot" },
    },

    -- Plugin Configuration.
    packer = {
      compile_path = vim.fn.stdpath "data" .. "/packer_compiled.lua",
    },
  },
}

return config
```

Our default capabilities already use the `cmp_nvim_lsp` capabilities so no need to call those, you can just add it to the `lsp.servers` table to make sure the `setup` function is called. This is also only necessary if you have already installed the `gdscript` LSP manually. If you have installed it with Mason then you don't need this `lsp` table at all.

For the `vim` options, we have a nice table for defining these that make it a little easier and in the case of the `transparent` option for tokyonight you can just set it to a boolean value that gets evaluated on if `vim.g.neovide` is `nil` or not.

With all of these changes that moves your config entirely into the configuration table 😄 


Another thing to note is that you will need to do a `:PackerSync` every time you modify the `plugins.init` table since that all gets compiled to the `packer_compiled.lua` file. So it's typically better to put the config codes into other files and then calling them with `require` so that they are lazy loaded.

Also I just tested this and the configurations for the plugins are working correctly.

**Comment by A-Lamia** [comment]
Thanks! would i just place plugins in to separate file then require it in local config ?

**Comment by A-Lamia** [comment]
@mehalter and the current version of astronvim im using is still on nvim-lsp-installer

**Comment by mehalter** [comment]
and easy example would be like this in your `user/init.lua` `plugins.init` table

```lua
      {
        "Pocco81/true-zen.nvim",
        config = function() require "user.plugins.true-zen" end,
      },
```

Then make a `plugins` folder in your `user` folder and have `user/plugins/true-zen.lua` with

```lua
require("true-zen").setup {
  modes = {
    narrow = {
      folds_style = "invisible",
    },
    integrations = {
      twilight = true,
    },
  },
}
```

**Comment by mehalter** [comment]
Ok, this config will still work since there were no breaking changes between us having `nvim-lsp-installer` and now having `mason`. So none of this config breaks :)

**Comment by A-Lamia** [comment]
@mehalter awesome thanks soo much! is nightly currently ok on stability ?

**Comment by mehalter** [comment]
It's pretty decent. If you are using `stable` I would recommend staying with stable. Also if you want the Mason change, it will be tagged Monday morning as `v1.8.0` :)

**Comment by A-Lamia** [comment]
@mehalter oh gonna wait then, thanks for all the help :D

**Comment by mehalter** [comment]
`nightly` definitely has bugs every once in a while and definitely should be expected to have bugs. I will merge stuff when I think it's bug free, but then bugs inevitably show up as more users use it. Also `nightly` doesn't pin plugins to specific versions so any breaking change in a plugin will in turn break AstroNvim `nightly` after a `:PackerSync`. We haven't had much changes recently and I try to tag new stable versions whenever a new feature is pretty heavily tested and then also tagging new patch releases as soon as bugs are fix. AstroNvim development has just been pretty smooth sailing recently so no big updates until the Mason stuff that happened this week. Now I'm just waiting on a few days to pass just in case more bugs come up.

**Comment by A-Lamia** [comment]
@mehalter might finish setting up and give it a try, thanks for the info ;)

**Comment by A-Lamia** [comment]
Ok all seems to be working think true-zen is the issue thanks again! :)

**Comment by A-Lamia** [comment]
@mehalter Hey i was looking around but couldn't find how to disable plugins, i use neovide and want to disable cinnamon when im using it.

**Comment by pkazmier** [comment]
If you want to disable a plug-in unconditionally, you can disable them in the `init` table of the `plugins` table. Don't forget to do a `PackerSync` afterwards. Here is a full sample config for your reference.

```lua
return {
  plugins = {
    init = {
      ["declancm/cinnamon.nvim"] = { disable = true },
    },
  },
}
```

**Comment by A-Lamia** [comment]
@pkazmier thanks man worked great, yeah smooth scrolling is very strange for the most part.

**Comment by A-Lamia** [comment]
might be a dumb question but is there a way to pass arguments to local functions in keymap commands eg `["j"] = {KeySet(arg1,arg2,arg3)},` ?
