### ISSUE TITLE
Changing lsp settings for tailwindcss not working?

### ISSUE THREAD

**Issue by HummingBird24** [AstroNvim/AstroNvim#837]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] restarted AstroNvim
- [X] Neovim version >= 0.7.0

**Describe the bug**
Maybe I didn't do it correctly but I added this to my server settings inside ~/.config/nvim/lua/user/init.lua it doesn't seem to have an effect
Autocomplete still works for `class="w- "` as would be expected with the default settings but not `tw="w- " `
```
lsp = {
 ["server-settings"] = {
      tailwindCSS = {
        experimental = {
          classRegex = {
            "tw`([^`]*)",
            'tw="([^"]*)',
            'tw={"([^"}]*)',
            "tw\\.\\w+`([^`]*)",
            "tw\\(.*?\\)`([^`]*)",
          },
        },
      },
    },
}
```
This is how I got it working in LunarVim if that helps at all

```
require("lvim.lsp.manager").setup("tailwindcss", {
  settings = {
    tailwindCSS = {
      experimental = {
        classRegex = {
          'tw`([^`]*)',
          'tw="([^"]*)',
          'tw={"([^"}]*)',
          'tw\\.\\w+`([^`]*)',
          'tw\\(.*?\\)`([^`]*)',
        },
      },
    },
  },

})   
```
**To Reproduce**
1. If you don't already have a user configuration cp -r ~/.config/nvim/lua/user_example/ ~/.config/nvim/lua/user/
2. :LspInstall tailwindcss
3. Add this to `["server-settings"]` under lsp: 
```
tailwindCSS = {
        experimental = {
          classRegex = {
            "tw`([^`]*)",
            'tw="([^"]*)',
            'tw={"([^"}]*)',
            "tw\\.\\w+`([^`]*)",
            "tw\\(.*?\\)`([^`]*)",
          },
        },
      },
```
4. :PackerSync
5. :AstroUpdate
6. restart AstroNvim
7. try seeing if you get autocomplete when writing `tw="w- "` in a `.tsx` file
Example text.tsx
```
export default function(){
return <div tw="w- " class="w-">

    </div>
}

```

**Expected behavior**

Auto suggestion/complete when using `tw=` for tailwind

**Screenshots**
No suggestion with tw
<img width="459" alt="Screen Shot 2022-08-05 at 1 37 19 PM" src="https://user-images.githubusercontent.com/16395981/183159270-20a6cea1-f361-4696-994e-04009a45c3c6.png">

suggestion with class
<img width="603" alt="Screen Shot 2022-08-05 at 1 37 06 PM" src="https://user-images.githubusercontent.com/16395981/183159376-9bc1b8e9-2fef-4e11-bbba-1420d6db6edf.png">

**Additional context**

**Comment by mehalter** [comment]
```lua
return {
  lsp = {
    ["server-settings"] = {
      tailwindcss = { -- modifying `require("lspconfgi").tailwindcss.setup({...})`
        settings = { -- "settings table"
          tailwindCSS = { -- gotten from the lspconfig docs
            experimental = {
              classRegex = {
                "tw`([^`]*)",
                'tw="([^"]*)',
                'tw={"([^"}]*)',
                "tw\\.\\w+`([^`]*)",
                "tw\\(.*?\\)`([^`]*)",
              },
            },
          },
        },
      },
    },
  },
}
```

The syntax is slightly off. Here is the correct notation.

**Comment by HummingBird24** [comment]
@mehalter Ahh makes total sense now. Thanks a ton!

**Comment by maeertin** [comment]
Hi there @stoickeyboard, did you actually get the tailwind `classRegex` to work? Have you perhaps changed the config with later Astronvim versions? I've been pulling my hair out on why it does not work for me. I pretty much copy pasted the suggested answer above into my init.lua, [link to my astronvim config](https://github.com/maeertin/dotfiles/blob/5c9cc19b931e66b0b6ae76d4ab330b9eb506adfb/.config/astronvim/lua/user/init.lua#L53-L74), but can't get autocomplete to work for a custom attribute like `tw="..."` but works just fine for `className="..."`.

Also tried updating Astronvim to v3.36.11 (currently latest) but to no avail.

<img width="560" alt="Screenshot 2023-09-19 at 22 58 10" src="https://github.com/AstroNvim/AstroNvim/assets/557486/7e9f35ef-4a3c-4ec7-8e5b-e272495244d6">

Works just fine for `className`

<img width="592" alt="Screenshot 2023-09-19 at 22 58 24" src="https://github.com/AstroNvim/AstroNvim/assets/557486/3a413672-91f7-44a1-9a51-042376d82a32">

Does not work for `tw`
