### ISSUE TITLE
Can't get needed fonts

### ISSUE THREAD

**Issue by cyberloh** [AstroNvim/AstroNvim#838]
Can you please provide an exact font list used in Astro Nvim? i tried this [2Gb nerd fonts pack](https://aur.archlinux.org/packages/nerd-fonts-complete), but still  a lot of icons missing in file menu for example.

**Comment by zenVentzi** [comment]
Windows user here. From the nerd-fonts donwload [link](https://www.nerdfonts.com/font-downloads), should I download each and every font package listed on the page? I've currently installed the first one but absolutely no icons show up in the editor. I've tried both Windows Terminal and the default Command prompt.

**Comment by kabinspace** [comment]
@cyberloh You can use any nerd fonts from [here](https://www.nerdfonts.com/font-downloads). The one shown in AstroNvim's preview image is called JetBrainsMono Nerd Font.

**Comment by zenVentzi** [comment]
In case Windows users read this:

1. Download JetBrainsMono Nerd Font from [here](https://www.nerdfonts.com/font-downloads).
2. Extract into a folder
3. Select all fonts and right-click "Install for all users"
4. In Windows Terminal open Settings
5. Under "Profiles" select the profile you use to open AstroNvim with
6. Additional Settings > Appearance > Font Face > JetBrainsMono Nerd Font

Open a new tab with the profile you just edited and open AstroNvim again. Icons should appear properly. (haven't tested for all icons, but most seem to appear fine)

**Comment by koutoftimer** [comment]
I've tried JetBrainsMono Nerd Font  but some symbols still not recognized: " 1  1  1    2  10" and bunch of others.

```
~ $ nvim --version
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3

~/.config/nvim $ git log
commit bc33207244189b2ad9f8f8c534c4915abc706e8a (HEAD -> main, tag: v2.5.0, origin/main, origin/HEAD)
Author: Micah Halter <micah@balena.io>
Date:   Mon Oct 31 14:14:50 2022 -0400

    chore(snapshot): update packer_snapshot
```

I have also tried nerd font patcher but it added only directory and language icons, not symbols from the example above.
