### ISSUE TITLE
How to disable Tab mappings for cmp

### ISSUE THREAD

**Issue by hismailbulut** [AstroNvim/AstroNvim#839]
I want to disable Tab and S-Tab insert mode mappings for cmp and I want to add new mappings with these keys for another plugin. How can I achieve this?

**Comment by mehalter** [comment]
You can modify the `cmp.setup({...})` call to remove those mappings from `cmp`. Here is an example `user/init.lua` file that just removes Tab/S-Tab from the `cmp` bindings:

```lua
return {
  plugins = {
    cmp = function(config)
      config.mapping["<Tab>"] = nil
      config.mapping["<S-Tab>"] = nil
      return config
    end
  },
}
```

You can then add mappings for those in your config using the `mappings` table, something like this:

```lua
return {
  plugins = {
    cmp = function(config)
      config.mapping["<Tab>"] = nil
      config.mapping["<S-Tab>"] = nil
      return config
    end,
  },
  mappings = {
    i = {
      ["<Tab>"] = { function() vim.notify "Pressed Tab" end, desc = "Tab in Insert mode" },
      ["<S-Tab>"] = { function() vim.notify "Pressed Shift Tab" end, desc = "Shift Tab in Insert mode" },
    },
  },
}
```

**Comment by hismailbulut** [comment]
That's working. Thank you so much :)
