### ISSUE TITLE
How to enable Nerd Fonts on a WSL envirement with neovide to see the icons

### ISSUE THREAD

**Issue by Fapuu** [AstroNvim/AstroNvim#840]
Just to be clear I'm a noob in neovim and I really want to give it a try to make it my main IDE.

My current workspace is a laptop with Windows 11 installed and I'm using WSL as my developing system. I followed the instalation guide and installed everyting that is needed. To use neovim I'm also using Neovide with the commend `neovide --wsl`. So the setup looks like this.

WSL:
 - Neovim
 - Astrovim (with the necessary dependencies)
 
 Windows 11:
 - Neovide
 
 Rigth now everything works fine but I can't see the icons. Soooo how can I change the font in astrovim?
 
 ![image](https://user-images.githubusercontent.com/39151576/183252026-f4c90e6e-176a-4975-9ae8-af02f343b9f9.png)

**Comment by maixnor** [comment]
Fonts on Windows are a complex topic. Btw, nerdfonts need to be installed first (on windows and linux)

Neovide running "on windows" might need the nerdfonts to be installed on linux AND windows as the client (console host) rendering the image onto the screen is running on windows in your specific setup.

But before trying it in neovide, try it with just the basics - the terminal.
I'd suggest you try it first in the windows terminal (awesome app btw) on the wsl box directly.
After it works on WSL directly you can try the neovide on windows approach.

**Comment by zenVentzi** [comment]
@Fapuu my solution might not work by default but if you run wsl from within WIndows Terminal, [this](https://github.com/AstroNvim/AstroNvim/issues/838#issuecomment-1207193089)(re-quote below) could help

In case Windows users read this:

1. Download JetBrainsMono Nerd Font from [here](https://www.nerdfonts.com/font-downloads).
2. Extract into a folder
3. Select all fonts and right-click "Install for all users"
4. In Windows Terminal open Settings
5. Under "Profiles" select the profile you use to open AstroNvim with
6. Additional Settings > Appearance > Font Face > JetBrainsMono Nerd Font

Open a new tab with the profile you just edited and open AstroNvim again. Icons should appear properly. (haven't tested for all icons, but most seem to appear fine)

**Comment by Fapuu** [comment]
@maixnor and @zenVentzi thank you very much the help, now I know that this is a question I should add to the Neovide and not on AstroNvim. Everythink works in the terminal and once again thank you for helping me :3
