### ISSUE TITLE
Recover normal braces keys behavior

### ISSUE THREAD

**Issue by PolSust** [AstroNvim/AstroNvim#845]
What do I have to modify to make the braces {} haver their default (jumping between chuncks of code) behaviour

**Comment by mehalter** [comment]
```lua
return {
  plugins = {
    aerial = {
      on_attach = function() end,
    },
  },
}
```

You can disable the aerial `on_attach` function

This is a pretty highly requested change. I am thinking we might remove this in `v2.0.0`

**Comment by PolSust** [comment]
I don't think it's a bad feature, I just dislike that it replaces the default behaviour

**Comment by mehalter** [comment]
Yeah, I guess "remove" is a bad way to say it. Replace it with something more "vim-like" and also not replace default behavior. Probably adding onto the `]` and `[` motions. so like `[y`/`]y`/`[Y`/`]Y` are ones I'm thinking about for `sYmbol` since `s` is used for mispelled words
