### ISSUE TITLE
Recent update broke all tree-sitter/lsp functionality

### ISSUE THREAD

**Issue by MichaelBrown08** [AstroNvim/AstroNvim#857]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] restarted AstroNvim
- [X] Neovim version >= 0.7.0

![image](https://user-images.githubusercontent.com/46346590/183502081-17ba0f41-c675-4edb-82e1-0f185c6ba1f4.png)

![image](https://user-images.githubusercontent.com/46346590/183502119-d6a8b7a8-f91a-447d-9d7d-97f102df1c16.png)

PackerSync fully updated
![image](https://user-images.githubusercontent.com/46346590/183502163-7ceb0409-6999-451b-9cb9-e62e23626dac.png)

AstroNvim fully updated
![image](https://user-images.githubusercontent.com/46346590/183502201-402c8907-233f-4b05-a7e0-d9d3bceb1d22.png)

**Describe the bug**
All TS/LSP functionality has stopped working, despite languages and language servers being installed:

Rust code, lsp/ts not working
![image](https://user-images.githubusercontent.com/46346590/183502373-02968f09-e32d-45f3-b35d-f5c187c56a94.png)

Rust :TSInstallInfo showing installed
![image](https://user-images.githubusercontent.com/46346590/183502801-1d5a873f-f076-42f4-b255-c28be20f40c7.png)

Python
![image](https://user-images.githubusercontent.com/46346590/183502456-3f904475-636a-4baf-8b0b-72291280515d.png)

Python :TSInstallInfo showing installed
![image](https://user-images.githubusercontent.com/46346590/183503001-9de6ea54-be78-4a1b-9e54-8f6eec634745.png)

:LspInstall is now not working:
![image](https://user-images.githubusercontent.com/46346590/183503114-aae09a1a-6399-4b12-9475-62ecb6a37003.png)

Installed language servers:
![image](https://user-images.githubusercontent.com/46346590/183503221-baf9dc43-b01f-40f0-93ce-e2efd510cee9.png)

All filetypes appear to be missing in the statusline (python file open):
![image](https://user-images.githubusercontent.com/46346590/183503791-42d07833-430a-4229-9355-fac1ef0fa12a.png)

**To Reproduce**
1. I have absolutely no idea, this was working fine before system + astronvim updates earlier today.

**Tried**
1. Removing all plugins, removing all AstroNvim files, removed user config file, re-download from git clone - **didn't work**
2. Rolling back latest apt upgraded packages - **didn't work**

**Expected behavior**
TS functionality works, LSPs detect file types and work.

**Comment by mehalter** [comment]
You are using an unsupported version of Neovim and AstroNvim is not currently compatible with it for either treesitter or LSP

**Comment by MichaelBrown08** [comment]
Thanks! I had long since forgotten I was using the unstable neovim ppa. Replaced with stable and all is working as expected.
