### ISSUE TITLE
PackerSync install of neovim/nvim-lspconfig failed

### ISSUE THREAD

**Issue by jefiedler** [AstroNvim/AstroNvim#859]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0

**Describe the bug**
After installing the latest NeoVim (v0.7.2) version, I installed Astrovim as recommended here in the repo. 
Then I ran nvim +PackerSync and it showed that the installation of neovim/nvim-lspconfig failed. After I restarted the terminal and NeoVim and run nvim I get the error:
```bash
Error in packer_compiled: /home/jefiedler/.local/share/nvim/packer_compiled.lua:521: Vim(if):E15: Invalid expression: ex
ists('g:lspconfig')^M
Please check your config for correctness
Error detected while processing /home/jefiedler/.local/share/nvim/site/pack/packer/start/nvim-lspconfig/plugin/lspconfig
.vim:
line    1:
E15: Invalid expression: exists('g:lspconfig')^M
line   17:
E171: Missing :endif
line    1:
E15: Invalid expression: exists('g:lspconfig')^M
line   17:
E171: Missing :endif
```

**To Reproduce**
1. Install NeoVim from official NeoVim repo.
2. Install AstroVim from official repo
3. Execute `nvim +PackerSync`
4. Get in `PackerSync` window the message that the installation of `neovim/nvim-lspconfig` is failed
5. Close `PackerSync` window, and restart Terminal and `nvim`
6. After restart and executing of `nvim` gives the error

**Expected behavior**
`nvim` starts with the AstroVim start screen

**Screenshots**
![image](https://user-images.githubusercontent.com/68224198/183638418-78549e26-5405-4231-b0a0-cb6c3cf6ecb7.png)

**Additional context**
I use Ubuntu 20.04.4 LTS with WSL on Windows 11. Yesterday, the repo from `neovim/nvim-lspconfig` was updated. Can this be the cause of the error?

**Comment by jefiedler** [comment]
I have tried it, but it doesn't work. 

Here is a screenshot from the `PackerSync`:
![image](https://user-images.githubusercontent.com/68224198/183751345-f6b3749d-700c-4743-a941-2a403e04d891.png)

And here the `~/.loacl/share/ folder`:
![image](https://user-images.githubusercontent.com/68224198/183752287-3856fe76-45d2-4c86-9824-390886322538.png)

**Comment by mehalter** [comment]
I'm honestly not sure. I haven't heard of any other WSL users running into this problem . I would probably try a couple more times to see if it's a one off problem. Also looks like a couple other people are having this issue as well: https://github.com/wbthomason/packer.nvim/issues/677

**Comment by jefiedler** [comment]
Thank you for your patience. 

Thanks for your help. I'll take a look at packer's post.

**Comment by k12ish** [comment]
If its any consolation, I'm having the issue with nvim 0.7.2, Ubuntu 20.04 LTS after following all of your suggestions:
![image](https://user-images.githubusercontent.com/45272873/184539085-58d960ba-d27e-4b00-8765-6a63f09e84a0.png)

**Comment by mehalter** [comment]
I wonder if this has to do with the `^M` indicating that like ends with Windows carriage return character.... I will ask on the packer repo

**Comment by mehalter** [comment]
@k12ish is your Ubuntu install also in WSL?

**Comment by k12ish** [comment]
> @k12ish is your Ubuntu install also in WSL?

I'm dual-booting Ubuntu, so it should just act like any standard Ubuntu install.

> I wonder if this has to do with the `^M` indicating that like ends with Windows carriage return character.... I will ask on the packer repo

You're right!!

I converted all of `~/.local/shared/nvim` into unix line endings like this:

```bash
$ cd ~/.local/share/nvim
$ find . -type f -exec dos2unix {} \;
```

This appears to have the side effect of breaking `:PackerSync` :sweat_smile: 

![image](https://user-images.githubusercontent.com/45272873/184539950-95941cd3-fb36-4562-a7f7-874313c31306.png)

**Comment by mehalter** [comment]
Oh interestingggggg that's quite strange @k12ish 😂 I have no idea how packer works or why that would be a thing haha
