### ISSUE TITLE
:LspInstall for rust failing on raspberry pi

### ISSUE THREAD

**Issue by imnotgreatatusernames** [AstroNvim/AstroNvim#866]
I'm trying to code, explore linux, and learn rust on my little raspberry pi.  This is proving to be comically difficult.  "sudo apt install" did not get me a new enough version of neovim so i had to compile it myself (v0.7.2) and then I installed Astronvim like it says on https://astronvim.github.io/  .  

After successfully installing it, I was able to use " :TSInstall " to get a rust parser (I think that's what it's called) but " :LspInstall " won't download the rust analyzer.  I'm pretty sure it's because i'm on raspberry pi (arm7 ?) and they can't fetch the downloads, but I compiled the rust-analyzer from source so I have the binary on my machine I just can't get Astronvim to see that I have it.

![image](https://user-images.githubusercontent.com/110946843/183782330-6ab0285a-73fa-48ba-953d-2e8f96c3a88b.png)  

![image](https://user-images.githubusercontent.com/110946843/183782436-274d2197-5d24-4d70-9027-bd02db9b4710.png)

I know there are solutions out there to host your own LSP server on your machine but everything I find tends to be lua code without telling me what file it needs to be in and where that file should go.  I'm really new to programming and linux and things and have no idea what to do to solve this issue.  Please help, I just want to write silly little programs in Rust!

**Comment by mehalter** [comment]
This looks like a limitation of Mason.nvim. So I would recommend opening up an issue that they do not support Arm compilation in their installer.

On the other hand, if you have installed the binary yourself and have it available. Make sure that the binary is added to your path so you can run `rust-analyzer` anywhere on your system and you can add `rust_analyzer` to your `lsp.servers` table to tell AstroNvim that it is installed externally and not with `mason`

Here is a complete `user/init.lua` file that sets up an externally installed `rust-analyzer` binary:

```lua
return {
  lsp = {
    servers = {
      "rust_analyzer",
    },
  },
}
```

This is documented here: https://astronvim.github.io/Recipes/advanced_lsp#lsp-setup-without-installer
