### ISSUE TITLE
Statusline configuration

### ISSUE THREAD

**Issue by alex289** [AstroNvim/AstroNvim#867]
Hey, Im new to AstroNvim and I wanted to show the current mode (insert/normal) in the statusline. I mean the word and not only the color. Is there any way to configure this easily? 😅

**Comment by Joxtacy** [comment]
Not the prettiest solution, but it works. 

Add a file in your user config `plugins` folder called `feline.lua`. In it you can return a function that takes in the settings table for feline. You can then modify this to your liking.
In this case I have added, first a spacer, and then the current vi mode as separate sections to the statusline.

I am also fairly new to neovim, Astrovim, and lua, so I'm sure there are better and/or more intuitive ways of doing this.

```lua
-- user/plugins/feline.lua
local hl = require("core.status").hl
local provider = require("core.status").provider
local vi_mode_utils = require('feline.providers.vi_mode')

local function TableConcat(t1,t2)
  for i=1,#t2 do
    t1[#t1+1] = t2[i]
  end
  return t1
end

return function(leTable)
  local original_active = leTable.components.active[1]
  local spacer_and_mode = {
    { provider = provider.spacer(), hl = hl.mode() },
    {
      provider = function()
        return vi_mode_utils.get_vim_mode()
      end,
      hl = hl.mode()
    }
  }


  local new_active = TableConcat(spacer_and_mode, original_active)
  leTable.components.active[1] = new_active

  return leTable
end

```

**Comment by mehalter** [comment]
@Joxtacy thanks for providing a great  answer! You can simplify this a little bit by using the built in `vim.list_extend` function in the Neovim API:

```lua
return function(config)
  local hl = require("core.status").hl
  local provider = require("core.status").provider
  local vi_mode_utils = require "feline.providers.vi_mode"

  -- new beginning of the statusline
  local new_left = {
    { provider = provider.spacer(), hl = hl.mode() },
    {
      provider = function() return vi_mode_utils.get_vim_mode() end,
      hl = hl.mode(),
    },
  }

  -- extend the new left with the old left component
  vim.list_extend(new_left, config.components.active[1])
  -- set the new left as the  active component
  config.components.active[1] = new_left

  return config
end
```

This can be found in the Neovim docs here (search for `vim.list_extend`): https://neovim.io/doc/user/lua.html

**Comment by Joxtacy** [comment]
> @Joxtacy thanks for providing a great answer! You can simplify this a little bit by using the built in `vim.list_extend` function in the Neovim API:
> 
> ...
> 
> This can be found in the Neovim docs here (search for `vim.list_extend`): https://neovim.io/doc/user/lua.html

That is perfect! Thank you! 😄 I'll be sure to check out more of the Neovim APIs.
