### ISSUE TITLE
Default_theme no color everything is gray in color even with terminator true color support

### ISSUE THREAD

**Issue by BL4CK-R34P3R** [AstroNvim/AstroNvim#870]
Default theme has no color even if the terminal support true color, everything is gray in color

**Comment by mehalter** [comment]
Can you please provide some more information? What version of AstroNvim are you using (output of `:AstroVersion`) and what version of Neovim are you using (`nvim --version`)?

Do you get any errors or anything? Could you provide a screenshot?

**Comment by BL4CK-R34P3R** [comment]
its working now, it was a problem with nvim nightly version,
