### ISSUE TITLE
Full screen header for the home page

### ISSUE THREAD

**Issue by ChrisMGeo** [AstroNvim/AstroNvim#871]
Sometimes I want to keep larger ASCII art as the header on the home page, but due to how the header is just on top of the options like new file, recents, etc. It doesn't look as good as I'd want it to. 
A solution to this would be to render the header on the entire full page and not on top of the options and render the options over it and make this an additional feature to enable in the user/init.lua and not a default.

**Comment by mehalter** [comment]
Hm, this is an interesting request. I believe we are at a limitation of the library we are using for building the dashboard. If you would like a feature like this I would recommend opening a feature request on `alpha-nvim` to add this ability to their plugin: https://github.com/goolord/alpha-nvim
