### ISSUE TITLE
How to search and replace in multiple files?

### ISSUE THREAD

**Issue by Stianhn** [AstroNvim/AstroNvim#876]
Let's say I want to replace the word `string` with `number` in all my files in my current folder and all sub folders. Is there an easy way to achieve this?

**Comment by mehalter** [comment]
There is not a super easy way to do this in Neovim. This blog post has a pretty good description of a couple ways to do this: 
https://jdhao.github.io/2020/03/14/nvim_search_replace_multiple_file/

Hopefully this helps answer your question :)
