### ISSUE TITLE
Trying to use Astronvim with master branch of neovim

### ISSUE THREAD

**Issue by Eloitor** [AstroNvim/AstroNvim#877]
I compiled `neovim` from source, and tried to use astrovim's default configuration.
Syntax higlighting of a file does not work by default, for example when opening `init.lua` I need to run `:setfiletype lua` manually.

Moreover I get this error message:

```
packer.nvim: Error running setup for neo-tree.nvim: attempt to call a nil value
packer.nvim: Error running config for mason.nvim: attempt to call a nil value
packer.nvim: Error running config for mason-lspconfig.nvim: attempt to call a nil value
packer.nvim: Error running config for mason-tool-installer.nvim: attempt to call a nil value
packer.nvim: Error running config for which-key.nvim: attempt to call a nil value
packer.nvim: Error running config for indent-o-matic: attempt to call a nil value
packer.nvim: Error running config for FixCursorHold.nvim: attempt to call a nil value
packer.nvim: Error running config for indent-blankline.nvim: attempt to call a nil value
packer.nvim: Error running config for cinnamon.nvim: attempt to call a nil value
packer.nvim: Error running config for nvim-colorizer.lua: attempt to call a nil value
packer.nvim: Error running config for nvim-treesitter: attempt to call a nil value
packer.nvim: Error running config for null-ls.nvim: attempt to call a nil value
packer.nvim: Error running config for gitsigns.nvim: attempt to call a nil value
packer.nvim: Error running config for nvim-web-devicons: attempt to call a nil value
packer.nvim: Error running config for bufferline.nvim: attempt to call a nil value
packer.nvim: Error running config for feline.nvim: attempt to call a nil value
packer.nvim: Error running config for dressing.nvim: attempt to call a nil value
packer.nvim: Error running config for nvim-notify: attempt to call a nil value
packer.nvim: Error running config for alpha-nvim: attempt to call a nil value
```

Is this a problem with packer or with astronvim? Is there any workarround?

**Comment by mehalter** [comment]
AstroNvim does not support unreleased versions of Neovim. Please use a stable and released version.

**Comment by mehalter** [comment]
There are a lot of breaking changes with neovim 0.8 and AstroNvim does not adhere to these new changes. There is the `v2` branch that may or may not be working. It's a work in progress getting ready for the Neovim 0.8 release. There are a lot of breaking changes as well that do not align with the documentation. This branch is basically untested and is not guaranteed to work with the latest releases of nightly as new breaking changes happen.

Also it should be noted that currently Neovim nightly is extremely broken when it comes to using `winbar` which AstroNvim v2.0 does use. So the `:split` functionality is completely borked and makes the editor pretty much unusable: https://github.com/neovim/neovim/issues/19458

We would highly recommend using stable releases of Neovim.

**Comment by Eloitor** [comment]
Thank you, I'm trying to preview latex formulas, which I think is only possible in the `master` branch:  https://github.com/yatli/gui-widgets.nvim/issues/2#issuecomment-1210579757

I tried the `v2` branch and I had no problems. Since the `master` branch of neovim is not supported by AstroNvim, from now on if I have some similar problem I'll try to fix it myself, I'll consider using the released version of neovim instead, or I'll configure neovim myself.
