### ISSUE TITLE
How can I use the installed DAP plugin to debug my cpp code?

### ISSUE THREAD

**Issue by s1nisteR** [AstroNvim/AstroNvim#880]
I have installed cpptools.

**Comment by mehalter** [comment]
Could you please explain more? Have you installed [`nvim-dap`](https://github.com/mfussenegger/nvim-dap)? How did you install the debugger? Did you install the debugger with Mason?

Honestly I'm not sure what the process is for setting up a debugger that was installed with Mason, so if you did install it with Mason then this would be a good question for that repo. If you did not install it with Mason, then the `nvim-dap` documentation on their repo is a good starting point.

**Comment by s1nisteR** [comment]
I went through the LspInstall menu and it shows me categories for all the plugins, namely LSP, DAP, Linter/Formatter and so on.
From there I selected the DAP category and installed cpptools. Now I have no idea how to use it.

**Comment by mehalter** [comment]
This is a great question for: https://github.com/williamboman/mason.nvim

If you get a good idea of how to get this set up please feel free to comment back the solution for future users who run into this issue.

**Comment by mehalter** [comment]
Also @s1nisteR I just saw your edit. DAP does not come with AstroNvim by default. This menu is fully managed by the Mason package installer. It has the ability to install those binaries, but we do not ship or promot `nvim-dap` in any way given it's extremely unstable current state. The project is very young and still going through lots of rapid development and breaking changes which makes it too unstable to include in AstroNvim. Feel free to add it yourself to your configuration. Also there is no way for us to disable the DAP installer menu in Mason.

**Comment by s1nisteR** [comment]
Thank you so much for the swift responses.
