### ISSUE TITLE
Having Problems configuring neo-tree from user/init.lua

### ISSUE THREAD

**Issue by CaptainJack42** [AstroNvim/AstroNvim#881]
I'm currently trying to adjust some things in the neo-tree plugin, mainly i want to adjust the *filtered_items*. From the [documentation](https://astronvim.github.io/Configuration/override_formats) it sounds like i can just put my custom config table (or rather my changes to the default table *"This is done by simply providing a new table and we merge the table with the default table where the user table takes precedence."*) inside the `user/init.lua/plugins.init` table.

Problem is: i tried doing that and it also sort of works (`hide_gitignored = true` is recognized and works, but `hide_dotfiles = false` doesn't and it seems like the rest of the config isn't merged either).

I've added it like this to `user/init.lua`:

```lua
plugins = {
        init = {
		  { "neo-tree",
		    filesystem = {
		      filtered_items = {
		        hide_gitignored = true,
		        hide_dotfiles = false,
		      },
		    },
		    config = function()
		      require("neo-tree").setup()
		    end,
		  }
        }
}
```

This also leads to ` ✗ Failed to install neo-tree` when running `:PackerSync`

Any help here would be appreciated

Cheers

**Comment by mehalter** [comment]
You want to you `plugins.X` to override the setup call for a plugin where `X` is the plugin name used for `require("X").setup` as mentioned on that documentation page. Here is what your code should look like:

```lua
plugins = {
  ["neo-tree"] = {
    filesystem = {
      filtered_items = {
        hide_gitignored = true,
		     hide_dotfiles = false,
      },
    },
  },
}
```

**Comment by mehalter** [comment]
The `plugind.init` table is just for modifying the `packer` plugin table. So you can use that to override what plugins are installed by default and uninstalling them or you can adding new ones
