### ISSUE TITLE
How to configure null-ls to increase the timeout limits?

### ISSUE THREAD

**Issue by galexbh** [AstroNvim/AstroNvim#883]
I find myself using prettier in my astrovim user configuration but it always throws a "vim.lsp.buf.formatting_sync: timeout" error so I can't format it.

**Comment by mehalter** [comment]
Please see: https://github.com/AstroNvim/AstroNvim/issues/529

**Comment by galexbh** [comment]
Thank you very much, I have already solved the problem.
