### ISSUE TITLE
Neo-tree "Toggle Explorer" with `<leader> e` breaks when entering neovim via directory

### ISSUE THREAD

**Issue by toakleaf** [AstroNvim/AstroNvim#886]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0

**Describe the bug**
When entering neovim via directory `nvim .` you skip the splash page and open directly to Neo-tree.  If you then select a file it will open it as normal. However, if you want to later toggle open Neo-tree again, instead of opening up an isolated side buffer it will close out the current buffer and load Neo-tree within it.  From this buffer you will no longer be able to navigate to a new buffer, and the toggle keybinding `<leader> e` will also stop working.

**To Reproduce**
1. This can be seen if you first fire up the docker image:
``` 
docker run -w /root -it --rm alpine:edge sh -uelic '                                                                                                                            INT ✘  9m 6s  2.7.4   NORMAL  05:09:05 PM
  apk add git nodejs lazygit ncdu htop python3 neovim ripgrep alpine-sdk --update
  git clone https://github.com/AstroNvim/AstroNvim ~/.config/nvim
  # Uncomment the line below and replace the link with your user config repo to load a user config
  # git clone https://github.com/username/AstroNvim_user ~/.config/nvim/lua/user
  nvim --headless -c "autocmd User PackerComplete quitall" -c "PackerSync"
  touch hello.txt
  sh
'
```
2. Now that you're in the shell, run command `nvim .`
3. With keyboard navigate to file `hello.txt` and hit `enter` key to open it up
4. Now try to toggle Neo-tree back open with `<leader> e`
5. Now you're stuck.  Try navigating back to `hello.txt` entry and hitting `enter` on your keyboard.  Try toggling back out of Neo-tree explorer with `<leader e>`. Neither should work.

**Expected behavior**
When entering Neovim via directory like `nvim .` you should be able to navigate and have whatever you navigate and toggle the file explorer as you would when entering via the home splash screen with simple `nvim` command.

**Comment by trevor-atlas** [comment]
also seeing this FWIW

**Comment by mehalter** [comment]
ah thanks for opening this. I will try to improve this implementation and get a fix in before a new release is tagged on AstroNvim stable!
