### ISSUE TITLE
Terminal Uses Default Colors

### ISSUE THREAD

**Issue by zedgamer9128** [AstroNvim/AstroNvim#893]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0

**Describe the bug**
Neovide Terminal Shows Default Colors Rather Than Fish shell Nord Themes Colors

**To Reproduce**
1. Open Neovide
2. Open terminal by spc t h
3. Uses Default Colors rather than the theme colors

**Expected behavior**
Uses Fish Shell Nord theme colors in Neovide Terminal

**Screenshots**
Neofetch colors in Konsole
![image](https://user-images.githubusercontent.com/33319711/184634268-7d5ea774-9abc-4246-9c07-247d09a29620.png)

Neofetch colors in Neovide
![image](https://user-images.githubusercontent.com/33319711/184634351-d770dc34-c600-4a3f-9801-c27a88ccb2f2.png)

**Additional context**

**Comment by MultisampledNight** [comment]
(also see https://github.com/neovide/neovide/issues/1398)

**Comment by mehalter** [comment]
This probably has to do with the TERM variable setting capabilities. When you open a terminal in Neovide what do you get when you run `echo $TERM`

**Comment by zedgamer9128** [comment]
xterm-256color
same in konsole and neovide

**Comment by mehalter** [comment]
Ah I just saw the linked issue. I'll take a look at that as well

**Comment by mehalter** [comment]
Ah @zedgamer9128 @MultisampledNight so our colorscheme can set the base 16 colors for Neovide terminals? Just to be clear?

@zedgamer9128 just to make sure this is what you are looking for because it would not make it use your konsole colors. They would be AstroNvims colors right?

**Comment by MultisampledNight** [comment]
> so our colorscheme can set the base 16 colors for Neovide terminals? Just to be clear?

Yeah, it can and it should, imo. At least that's what all the base16 templates and some from-scratch schemes seem to do.

**Comment by zedgamer9128** [comment]
yeah  i think

**Comment by zedgamer9128** [comment]
i installed plugin [Nord](https://github.com/shaunsingh/nord.nvim ) and it looks similar to what i had in konsole so im closing this

**Comment by mehalter** [comment]
@zedgamer9128 could you try out PR #894 and see if it sets the Neovide colors correctly for the default theme? :)

**Comment by mehalter** [comment]
I just tested it @zedgamer9128 and it should be working. I'm going to add darker/lighter colors which it currently doesn't do ye
![2022-08-15_11:10:07_screenshot](https://user-images.githubusercontent.com/1591837/184662058-ca306a85-4712-40ba-8720-ada56a36b3ea.png)
t

**Comment by zedgamer9128** [comment]
Its working now Thanks 
well sidenote:- I downloaded nord.nvim and then set the colorscheme to nord then back to default_theme and it was also worked back then but now i dont need to do anything and it is working again Thanks

**Comment by mehalter** [comment]
Ah yeah, with the current AstroNvim we don't set those variables or overwrite them. So if you have the `nord` theme enabled and swtich to the `default_theme` then those variables will still be set from before. The new PR that I have open will actually set those variables to AstroNvim colors now. But it isn't merged yet into `main`

**Comment by mehalter** [comment]
![2022-08-15_12:29:13_screenshot](https://user-images.githubusercontent.com/1591837/184675725-41c9055a-bfcc-4575-bab7-9da4f9b27afe.png)


@zedgamer9128 here is the final color scheme that we set with the new update. I'm going to merge the PR now. So if you do `:AstroUpdate` and restart, then try our the `default_theme` you will see the colors match and change when you switch themes :)

**Comment by zedgamer9128** [comment]
so i can turn the branch to main right?

**Comment by mehalter** [comment]
Yup!
