### ISSUE TITLE
Multiple file selection in Telesocope doesn't open selected files

### ISSUE THREAD

**Issue by teklabania** [AstroNvim/AstroNvim#897]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0

**Describe the bug**
Multiple selection in Telesocope doesn't open selected files. Only the last (highlighted) file is opened with ENTER.

**To Reproduce**
1. Open Telescope
2. Mark desired files with TAB
3. Press ENTER
4. Only the file under highlight is opened

**Expected behavior**
All files marked as selected (with +) are opened in new buffers.

**Screenshots**
<img width="1525" alt="Zrzut ekranu 2022-08-17 o 14 22 57" src="https://user-images.githubusercontent.com/111071705/185120190-29b3b26f-c46f-4faf-99eb-ad17166c0d2d.png">

In the example above, only `file_05.txt` will be opened after pressing ENTER.

**Comment by mehalter** [comment]
This is a known limitation with Telescope. Feel free to discuss on that repository: https://github.com/nvim-telescope/telescope.nvim/issues/1048

**Comment by AXGKl** [comment]
@teklabania 
Throw this into your plugins folder and it will open all selected files plus the one you've hit `enter` on:

```lua
~/.config/pds/setup/astro master !2 ?1 ❯ cat plugins/telescope.lua
local actions = require("telescope.actions")
local action_state = require("telescope.actions.state")

local mm = { -- my mappings
  ["<CR>"] = function(pb)
    local picker = action_state.get_current_picker(pb) 
    local multi = picker:get_multi_selection()
    actions.select_default(pb) -- the normal enter behaviour
    for _, j in pairs(multi) do
      if j.path ~= nil then -- is it a file -> open it as well:
        vim.cmd(string.format("%s %s", "edit", j.path))
      end
    end
  end,
}

return { defaults = { mappings = { i = mm,  n = mm },  }, }
```


[![asciicast](https://asciinema.org/a/aHDxXHIR2BtVFcurBXnOQa4x2.svg)](https://asciinema.org/a/aHDxXHIR2BtVFcurBXnOQa4x2)

**Comment by teklabania** [comment]
Works like a charm, thanks @AXGKl!

**Comment by AXGKl** [comment]
Glad to be a help ;-)
