### ISSUE TITLE
Visual Indent

### ISSUE THREAD

**Issue by zedgamer9128** [AstroNvim/AstroNvim#898]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0

**Describe the bug**
I want to visually indent lines and i tried selecting the lines by v and then pressing tab, right arrow and nothing worked
**To Reproduce**
1. Visually Select multiple lines 
3. Click on tab or right arrow
4. Does not indent

**Expected behavior**
Indent Lines

**Comment by mehalter** [comment]
The described behavior is not normal vim behavior. I believe the binding you are looking for is `>` and `<` for indent and unindent

**Comment by zedgamer9128** [comment]
im so stupid i was thinking > referred to the arrow key

**Comment by mehalter** [comment]
Are you using a user configuration? Can you replicate the issue without your `user/` folder? What version of Neovim are you using? What version of AstroNvim are you using?

**Comment by mehalter** [comment]
Ah I see I see, no worries!
