### ISSUE TITLE
Cutted Icon on Bottom bar

### ISSUE THREAD

**Issue by enzonun** [AstroNvim/AstroNvim#902]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

Version: v1.8.1-19-g8782b1a

### Neovim version (>= 0.7)

NVIM v0.7.2 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3

### Operating system/version

Linux fedora 5.18.16-200.fc36.x86_64 

### Describe the bug

the icons in the bottom bar look cut off/sketchy

( Using Konsole KDE )

### Steps to Reproduce

1. Open AstroVim 
2. See Icon on Bottom bar

### Expected behavior

No Cutted Icon

### Screenshots

![image](https://user-images.githubusercontent.com/35570456/185470517-35726cbe-ad2d-41ac-946b-64671a9811e1.png)

**Comment by mehalter** [comment]
Looks like Konsole has a limitation supporting full-width glyphs for fonts (https://www.reddit.com/r/kde/comments/amuspg/konsole_broke_multiwidth_glyphs/)

**Comment by enzonun** [comment]
> Looks like Konsole has a limitation supporting full-width glyphs for fonts (https://www.reddit.com/r/kde/comments/amuspg/konsole_broke_multiwidth_glyphs/)

thanks! good to know!
