### ISSUE TITLE
How to change cursor type when going to INSERT mode

### ISSUE THREAD

**Issue by Clumsy-Coder** [AstroNvim/AstroNvim#903]
### Question

Currently when in NORMAL mode, the cursor is in block format.

But when it goes to INSERT mode, it goes to 'line' cursor style.

How do I change the cursor style to be always using the 'block' style cursor?

---

Cursor in NORMAL mode
![image](https://user-images.githubusercontent.com/19594044/185472211-f2abfac4-63c7-4cfa-ae10-54f0f18ebb1c.png)

Cursor in Insert mode
![image](https://user-images.githubusercontent.com/19594044/185472271-b95cac66-751e-4298-9518-37f54b5c46d1.png)

### User Configuration

[astronvim.zip](https://github.com/AstroNvim/AstroNvim/files/9376706/astronvim.zip)

tree structure
```
./astronvim
├── README.md
├── cmp
│   ├── README.md
│   └── source_priority.lua
├── extras
│   ├── README.md
│   ├── autocmds.lua
│   ├── filetypes.lua
│   └── icons.lua
├── lsp
│   ├── README.md
│   ├── server-settings
│   │   ├── README.md
│   │   ├── jsonls.lua
│   │   ├── sumneko_lua.lua
│   │   └── yamlls.lua
│   └── servers.lua
├── plugins
│   ├── README.md
│   ├── cmp-git.lua
│   ├── cmp.lua
│   ├── feline.lua
│   ├── indent_blankline.lua
│   ├── init.lua
│   ├── neo-tree.lua
│   ├── nvim-lsp-installer.lua
│   └── treesitter.lua
├── polish.lua
└── updater.lua

5 directories, 24 files

```

**Comment by mehalter** [comment]
You can set this in the `options` table

```lua
return {
  options = {
    opt = {
      guicursor = "n-v-c-i:block"
    }
  }
}
```

or put this in a `user/options.lua` file with the contents:

```lua
return {
  opt = {
    guicursor = "n-v-c-i:block"
  }
}
```
