### ISSUE TITLE
How to modify the lspKind(cmp) format?

### ISSUE THREAD

**Issue by LintaoAmons** [AstroNvim/AstroNvim#907]
### Question

- The current default format is like:
    - ![image](https://user-images.githubusercontent.com/95092244/185726953-b275cdc8-d48f-45b8-adf2-a72ca2c12284.png)

- I want it be like:
    - ![image](https://user-images.githubusercontent.com/95092244/185726955-8858abab-bab6-4edb-ba49-10aad3bf8005.png)

- I've read the doc about `cmp`, but didn't found how to change this~

- I tried to overwrite the table, by:
    - ![image](https://user-images.githubusercontent.com/95092244/185726959-22443aa7-6447-41a4-85ad-0a61cc391411.png)
    - This is not working

### User Configuration

- init.lua
```lua
{
  ["cmp"] = require "user.plugin-customise.cmp", -- I prefer to require it explicitly
}
```
- user.plugin-customise.cmp
```lua
return function(config)
  local cmp = require "cmp"
  config.mapping["<CR>"] = cmp.mapping.confirm { select = true }
  config.formatting.fields = { "menu", "kind", "abbr" }
  return config
end
```

**Comment by mehalter** [comment]
You can do this by changing the mode of `lspkind`

so these files:

`init.lua`:

```lua
return {
  plugins = {
    cmp = require "user.plugin-customise.cmp",
    lspkind = require "user.plugin-customise.lspkind",
  },
}
```

`user/plugin-customise/cmp.lua`:

```lua
return function(config)
  local cmp = require "cmp"
  config.mapping["<CR>"] = cmp.mapping.confirm { select = true }
  config.formatting.fields = { "abbr", "kind" }
  return config
end
```

`user/plugin-customise/lspkind.lua`:

```lua
return function(config)
  config.mode = "symbol_text"
  return config
end

```
