### ISSUE TITLE
[null-ls]: vim.lsp.buf.formatting_sync: timeout on format

### ISSUE THREAD

**Issue by johnsiras** [AstroNvim/AstroNvim#908]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

1.9.0

### Neovim version (>= 0.7)

0.7.2

### Operating system/version

Windows 10

### Describe the bug

Hello! So i'm trying to format my code (ts) and was just getting an error `vim.lsp.buf.formatting_sync: timeout` when format on save or even in a keybind `SPC l f`, i've already passed an ms on the formatting_sync 2nd argument of that and still doesn't work. Isn't that a problem on the plugin itself?

### Steps to Reproduce

1. If you already have the null-ls setup just go to 2
2. Now format the code by saving a file or formatting manually
3. `vim.lsp.buf.formatting_sync: timeout` error will show on the notification

### Expected behavior

Format the code without gettting that kind of error

### Screenshots

![image](https://user-images.githubusercontent.com/102006493/185793094-3a6050ea-7d05-41f2-82a0-22fd399395c5.png)

**Comment by mehalter** [comment]
See #529

**Comment by johnsiras** [comment]
> See #529

@mehalter as i just said i already have put that solution no ms or have, still doesn't work
![image](https://user-images.githubusercontent.com/102006493/185793467-dad6661e-0a9c-41fc-b15d-cd1ff1388a21.png)

**Comment by mehalter** [comment]
Ok, could we please keep the discussion limited to a single issue so people who have similar questions know where to look?

**Comment by johnsiras** [comment]
> Ok, could we please keep the discussion limited to a single issue so people who have similar questions know where to look?

sure.
