### ISSUE TITLE
YAML Block Scalar Highlighting issue (when line ended in single quote)

### ISSUE THREAD

**Issue by jdix531** [AstroNvim/AstroNvim#912]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

Version: v1.4.3-39-g4ecc89d

### Neovim version (>= 0.7)

0.7.2

### Operating system/version

wsl 20.04 on windows 10

### Describe the bug

improper syntax highlighing for yaml block scalar which should probably be fully ignored for anything in a block scalar. Once a line is found that ends in a single quote (perhaps with other restrictions so specific example provided below) all other lines fail highlighting as they become part of a multi line single quote.

### Steps to Reproduce

```yaml
- name: "zsh: apply distribution specific config"
▏block:

▏ ▏ - name: "zsh: standard full linux config"
▏ ▏ ▏ blockinfile:
▏ ▏ ▏ ▏ path: "/tmp/base-tmux.conf"
▏ ▏ ▏ ▏ marker: "# ANSIBLE BLOCK {mark}: DIST-ZSH"
▏ ▏ ▏ ▏ block: |
▏ ▏ ▏ ▏ ▏ # kde only?
▏ ▏ ▏ ▏ ▏ alias av='aws-vault --backend=kwallet --keychain="aws-vault" exec -- '
▏ ▏ ▏ when: ansible_facts.system == "Linux" and not is_wsl

▏ ▏ - name: "zsh: wsl config"
▏ ▏ ▏ blockinfile:
▏ ▏ ▏ ▏ path: "/tmp/base-tmux.conf"
▏ ▏ ▏ ▏ marker: "# ANSIBLE BLOCK {mark}: DIST-ZSH"
▏ ▏ ▏ ▏ block: |
▏ ▏ ▏ ▏ ▏ # wsl linux zshrc block
▏ ▏ ▏ when: ansible_facts.system == "Linux" and is_wsl
```

### Expected behavior

A block scalar with a line ending in a single quote breaks syntax highlighting for yaml files

`alias av='aws-vault --backend=kwallet --keychain="aws-vault" exec -- '`

### Screenshots

![highlighting-issue-astronvim](https://user-images.githubusercontent.com/5290156/186022192-c3bdfade-7724-4b8c-a680-6c3c35faab79.png)

**Comment by mehalter** [comment]
It looks like you are not using the `yaml` treesitter. I would recommend running `:TSInstall yaml` or add `yaml` to your list of `ensure_installed` treesitter parsers in your user configuration. This is a limitation of the regular expression based highlighting of yaml and not a bug in AstroNvim. Here are examples:

Without treesitter (regular expression based highlighting):
![2022-08-24_11:37:31_screenshot](https://user-images.githubusercontent.com/1591837/186461505-be53884c-2007-4184-9c53-fd781b88bce3.png)

With treesitter:
![2022-08-24_11:36:59_screenshot](https://user-images.githubusercontent.com/1591837/186461555-551cb76b-018e-4c1a-8e53-aaf9e56c1722.png)
