### ISSUE TITLE
Broken toggle line comment mapping

### ISSUE THREAD

**Issue by dtetruash** [AstroNvim/AstroNvim#914]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

Version: v1.9.0

### Neovim version (>= 0.7)

NVIM v0.7.2

### Operating system/version

Manjaro Linux

### Describe the bug

After recent `:PackerSync` the default mapping for line comment toggle (`<leader> + /`) via `Comment.nvim` seems to be broken, while the default commands `gb` and `gc` do still work.

When attempted, the following error occurs:
```
E5108: Error executing lua: ~/.config/nvim/lua/core/mappings.lua:49: attempt to index field 'toggle' (a nil value)   
stack traceback:
        ~/.config/nvim/lua/core/mappings.lua:49: in function </home/dtetruash/.config/nvim/lua/core/mappings.lua:49>
```

Looks like `toggle` is no longer a valid token in the API? A quick skim through `Comment.nvim` README.me gives a mention of `toggler` instead.

### Steps to Reproduce

1. Open a file
2. Use the `<leader> + /` mapping on a selected line

### Expected behavior

The line under the cursor is toggled to be (un)commented.

### Screenshots

![Screenshot](https://user-images.githubusercontent.com/7673161/186164948-61374a7c-59fb-43f6-be2e-4a47f769fe7b.png)

**Comment by mehalter** [comment]
Can you please verify that you have done a `:PackerSync` to get the latest version of Comment.nvim and restarted? There were recent breaking changes that moved to the new `.toggle` API. This is shown as the current API here: https://github.com/numToStr/Comment.nvim/blob/ba5903b88c0a43fdc94abe79ade2b8291ff661ed/doc/Comment.txt#L311-L372

I cannot replicate on a fresh installation of AstroNvim on both the `stable` and `nightly` channel

**Comment by nonzer0** [comment]
Sometimes I need to pull latest `main` before running `:PackerSync`. That fixed it for me in this instance.

**Comment by mehalter** [comment]
I'm going to go ahead and close this because I'm sure it's due to missing updates/`:PackerSync`. To seriously avoid these issues with breaking plugin changes. I would recommend using the `stable` AstroNvim update channel which pins the provided plugins to avoid these issues.
