### ISSUE TITLE
omnisharp-mono in lsp servers list.

### ISSUE THREAD

**Issue by YangtseSu** [AstroNvim/AstroNvim#916]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

1.9.0 git

### Neovim version (>= 0.7)

NVIM v0.7.2

### Operating system/version

debian/10

### Describe the bug

LspInfo show omnisharp-mono in "Configured servers list".

### Steps to Reproduce

1.Install nvim and AstroNvim step by step.
2. Create user init.lua by copy the "user_example"
3. Run nvim.

### Expected behavior

Omnisharp-mono should not been there.

### Screenshots

![2022-08-24_09-50-52](https://user-images.githubusercontent.com/650328/186300114-e79f924f-b1b2-4673-ab5d-f3fa1dd2d1d7.png)

### Additional Context
Full user/init.lua:
[init.lua](https://gist.github.com/YangtseSu/12ca4c88567e8e64173db883b4423e8f)

**Comment by mehalter** [comment]
LOL that's so wild. I can totally replicate this :joy: I will need to see what's going on here because that's definitely not something we have configured at all in any way. I've never even heard of "omnisharp_mono"

**Comment by mehalter** [comment]
Wait, I actually have no idea where this is coming from haha `omnisharp_mono` isn't even a language server in `lspconfig`.... o.O

**Comment by mehalter** [comment]
My guess is that `omnisharp_mono` must come preconfigured with `lspconfig` or is some bug upstream potentially. I have debugged this extensively and this is not a bug with AstroNvim. Below is a screenshot of me adding a print statement to every time a server is set up in AstroNvim and it is not in the list so it cannot be coming from us (this list is my personal config)
![2022-08-24_11:32:46_screenshot](https://user-images.githubusercontent.com/1591837/186460553-bd95f668-ee1a-4612-b5dd-e8e8dfc95dd7.png)

**Comment by younger-1** [comment]
I have this problem with my own nvim configuration.  I think it may be from mason or mason_lspconfig

**Comment by mehalter** [comment]
@younger-1 is this a problem? This is definitely completely repeatable. But I don't think it does anything

**Comment by mehalter** [comment]
@younger-1 @YangtseSu this has been resolved in the latest version of `lspconfig`.
