### ISSUE TITLE
How to tell `rust_analyzer` to enable all cargo features

### ISSUE THREAD

**Issue by jcornaz** [AstroNvim/AstroNvim#917]
### Question

Hi, I am trying to configure the `rust_analyzer` to use all cargo feature flags. But for some reason, it doesn't work.

Any idea of what I am missing?

Thanks in advance for your help.

### User Configuration

```lua
return {
    lsp = {
        servers = { "rust_analyzer" },
        ["server-settings"] = {
            rust_analyzer = {
                cargo = {
                    loadOutDirsFromCheck = true,
                    features = "all",
                },
                checkOnSave = {
                    command = "clippy",
                },
                procMacro = {
                    enable = true,
                },
                experimental = {
                    procAttrMacros = true,
                },
            },
        },
    },
}
```

**Comment by mehalter** [comment]
These `server-settings` tables are the tables that are passed into the `rust_analyzer` setup call. So it looks like you just have these settings in the wrong nested place:

```lua
return {
  lsp = {
    servers = { "rust_analyzer" },
    ["server-settings"] = {
      rust_analyzer = {
        settings = {
          ["rust-analyzer"] = {
            cargo = {
              loadOutDirsFromCheck = true,
              features = "all",
            },
            checkOnSave = {
              command = "clippy",
            },
            procMacro = {
              enable = true,
            },
            experimental = {
              procAttrMacros = true,
            },
          },
        },
      },
    },
  },
}
```

Give this a try and see if it works

**Comment by jcornaz** [comment]
Thank you so much. It does the trick.

**Comment by erichulburd** [comment]
@mehalter that worked for me as well.

Is there a way to set per-project lsp settings? I was looking at this [rust analyzer example](https://github.com/tamago324/nlsp-settings.nvim/blob/main/examples/rust_analyzer.json) from [tamago324/nlsp-settings.nvim](https://github.com/tamago324/nlsp-settings.nvim). I tried adding this to my init.lua:

```lua
local config = {
        -- ...
        plugins = {
                init = {
                        ["tamago324/nlsp-settings.nvim"] = {
                                config = function()
                                        require("nlsp-settings").setup({
                                                config_home = vim.fn.stdpath('config') .. '/nlsp-settings',
                                                local_settings_dir = ".nlsp-settings",
                                                local_settings_root_markers_fallback = { '.git' },
                                                append_default_schemas = true,
                                                loader = 'json'
                                        })
                                end
                        }
                },
                -- ...
        }
        -- ...
}
```

I then put that exact example in `project-root/.nlsp-settings/rust_analyzer.json`:

```json
{
  "rust-analyzer.cargo.features": "all"
}
```

but that doesn't seem to work.

Is there an issue with how I am setting up nlsp-settings plugin? Or is that plugin incompatible with AstroNvim setup?

**Comment by mehalter** [comment]
@erichulburd you basically want to run this code before `lspconfig` is loaded and sets up any language servers. The best way to do this is to actually modify the `lspconfig` config function to set up `nlspsettings` before it:

```lua
return {
  plugins = {
    init = {
      ["tamago324/nlsp-settings.nvim"] = { module = "nlspsettings" }, -- lazy load on module
      ["neovim/nvim-lspconfig"] = {
        config = function()
          require("nlspsettings").setup { -- set up nlspsettings before lspconfig
            config_home = vim.fn.stdpath "config" .. "/nlsp-settings",
            local_settings_dir = ".nlsp-settings",
            local_settings_root_markers_fallback = { ".git" },
            append_default_schemas = true,
            loader = "json",
          }
          require "configs.lspconfig" -- use our lspconfig setup after setting up nlspsettings
        end,
      },
    },
  },
}
```

**Comment by mehalter** [comment]
@erichulburd I have come up with a cleaner solution to do this. I am updating the snippet above.

For `v3` which is coming out soon just to future proof this message, this is the same modification but for `v3`:

```lua
return {
  lsp = {
    setup_handlers = function(server, opts) -- handler for setting up servers
      require "nlspsettings" -- load nlspsettings if it hasn't been loaded
      require("lspconfig")[server].setup(opts) -- setup the server
    end,
  },
  plugins = {
    init = {
      ["tamago324/nlsp-settings.nvim"] = { -- add the nlsp setting plugin
        config = { -- set the config table for the `setup()` call
          config_home = vim.fn.stdpath "config" .. "/nlsp-settings",
          local_settings_dir = ".nlsp-settings",
          local_settings_root_markers_fallback = { ".git" },
          append_default_schemas = true,
          loader = "json",
        },
      },
    },
  },
}
```

**Comment by erichulburd** [comment]
@mehalter thanks. The first suggestion failed saying `require "nlspsettings"` module could not be found.

The second setup doesn't show an error, but doesn't seem to be reading the file either. Issuing the `:LspSettings rust_analyzer` the command says the command `LspSettings` does not exist, so I must not be properly installing the plugin still.

**Comment by mehalter** [comment]
@erichulburd I have updated the snippet to protect the `pcall`. Basically you need to do a `:PackerSync` to get the plugins to update and install and whatnot.

Also just to be clear, the second snippet is *only* for `v3` which is unreleased. I simply put it there as a reference for future users that might look through this ticket. It *will not* work on `v2`

**Comment by erichulburd** [comment]
Ahh, future proofing the _message_. This is working as you specified above for v2.

Really appreciate your help here as well as the larger effort. I've dabbled in `nvim` before, but `AstroNvim` has been a huge step forward for my productivity with it. Well done.
