### ISSUE TITLE
Treesitter highlight error

### ISSUE THREAD

**Issue by Pritep** [AstroNvim/AstroNvim#918]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

1.9.0

### Neovim version (>= 0.7)

0.7.2

### Operating system/version

Linux Zorin Os 15

### Describe the bug

Sorry for to report this as bug,
Is a error on the config of plugin treesitter, and that to produce highlight be desactive
```
highlight = {
   code...
   enable = true, -- this should be "enabled" not "enable"
   code...
}
```

sorry for my English 😅 

### Steps to Reproduce

Use the plugin treesitter

### Expected behavior

```
{
   enabled = true
}
```

**Comment by mehalter** [comment]
It should be `enable`: https://github.com/nvim-treesitter/nvim-treesitter#available-modules
