### ISSUE TITLE
Mappings should be silent by default

### ISSUE THREAD

**Issue by windowsrefund** [AstroNvim/AstroNvim#920]
### Is your feature related to a problem?

I have noticed mappings are echoed to the command line. While experimenting with my own mappings.lua file, I realized I could add `silent=true` in order to overcome this. I tend to think this attribute should be set by default.

### Describe the new feature

All mappings would use silent=true by default.

**Comment by mehalter** [comment]
For continuity sake with default Neovim we are going to keep the default mapping flags to the same as Neovim. This will help behavior stay predictable to people who have configured Neovim previously
