### ISSUE TITLE
How to disable highlighting of keyword under cursor?

### ISSUE THREAD

**Issue by delinx** [AstroNvim/AstroNvim#924]
### Question

Hey, the default behaviour is to highlight the keyword under the cursor through the document while the cursor is on it, could anyone let me know how to disable that? Really struggling to find the responsible plugin or the name of the feature. I believe it is done by LSP, but how do I disable that without breaking anything else?

**Comment by mehalter** [comment]
You can do this in your `lsp.on_attach` function. We are setting up an autocommand that can be removed:

```lua
return {
  lsp = {
    on_attach = function(client, bufnr)
      if client.resolved_capabilities.document_highlight then
        vim.api.nvim_del_augroup_by_name "lsp_document_highlight"
      end
    end,
  },
}```

Here is an example `user/init.lua` file that does this.

**Comment by bonvee-99** [comment]
For anyone where the above doesn't work. Try doing:
```
        on_attach = function(client, bufnr)
            if client.server_capabilities.documentHighlightProvider then
              local highlight_name = vim.fn.printf("lsp_document_highlight_%d", bufnr)
              vim.api.nvim_del_augroup_by_name(highlight_name)
            end
        end,
```

**Comment by mehalter** [comment]
Here is an updated snippet as we do not put the `bufnr` in the `augroup`. Also `client.supports_method` should be used as it works with dynamic client capability registration:

```lua
on_attach = function(client, bufnr)
  if client.supports_method "textDocument/documentHighlight" then
    vim.api.nvim_del_augroup_by_name "lsp_document_highlight"
  end
end
```
