### ISSUE TITLE
How to edit and navigate within snippets?

### ISSUE THREAD

**Issue by windowsrefund** [AstroNvim/AstroNvim#925]
### Question

Using the stock cmp config, I am unable to move between snippet elements when working with a snippet. Instead, auto-complete is taking over.
  
How to reproduce:

Start a simple for loop in a .py file.
```for```

The autocomplete menu pops up. Press <TAB> twice to select the for snippet and press <CR>

The following snippet is rendered:
```
for value in iterable:
     pass
```

Focus is on the value element already and we are in insert mode so we can start typing any string in order to rename our loop iterator. At that point, autocomplete starts trying to autocomplete whatever we type and the <TAB> key can not be used to move to the next snippet element.

**Comment by mehalter** [comment]
@windowsrefund you can use `tab`/`shift-tab` to move throughout the snippet locations. If the auto complete menu is currently open you can do `ctrl-e` to close the auto complete menu without accepting anything.

**Comment by windowsrefund** [comment]
There's got to be a better way though right? I can't believe people are going out of their way to use `C-e` (so disruptive) when they're editing code that's been rendered by a snippet.

**Comment by mehalter** [comment]
Yeah I agree, I personally use a redefinition of `Tab` bindings because I hate this "super tab" behavior. It is very disruptive to my workflow. If you want you can redefine your own as well that doesn't do this.

here is an example of what I use for my `cmp` configuration:

```lua
local cmp = require "cmp"
local luasnip = require "luasnip"
return {
  mapping = {
    ["<Tab>"] = cmp.mapping(function(fallback)
      if luasnip.expandable() then
        luasnip.expand()
      elseif luasnip.expand_or_jumpable() then
        luasnip.expand_or_jump()
      else
        fallback()
      end
    end, { "i", "s" }),
    ["<S-Tab>"] = cmp.mapping(function(fallback)
      if luasnip.jumpable(-1) then
        luasnip.jump(-1)
      else
        fallback()
      end
    end, { "i", "s" }),
  },
}
```

**Comment by windowsrefund** [comment]
I really appreciate you sharing this and am going to re-examine my use of <Tab> as well. Thanks again.
