### ISSUE TITLE
When prompted to chose server, focus is outside.

### ISSUE THREAD

**Issue by Lcarv20** [AstroNvim/AstroNvim#930]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v1.9.0-3-g8581efa

### Neovim version (>= 0.7)

0.7.2

### Operating system/version

macOS monterrey 12.5.1 

### Describe the bug

On write I am prompted which server to use, ex: `null-lsp` or `rust_analyzer`. however the prompt cursor goes into insert mode inside the file itself and not the prompt. I didn't manage to focus the prompt. Current solution is to disable the formatting capabilities of, for ex, `rust_analyzer` in `lsp.server-settings`, which was not needed previously.

### Steps to Reproduce

1: open Mason and install rust_analyzer
2: create rust project and try to save.i

### Expected behavior

Prompt should be focused by default. Or at least able to focus it.

### Screenshots

The Problem I am having
https://user-images.githubusercontent.com/42584819/187334312-b58039b5-47d3-46b3-85fe-f87c6c14b948.mov

My solution so far
<img width="1064" alt="Screenshot 2022-08-30 at 04 23 25" src="https://user-images.githubusercontent.com/42584819/187334460-62b9701f-27f2-4bc0-80b7-c7122139086c.png">

### Additional Context

I would like to thanks in advance for any effort.

**Comment by mehalter** [comment]
I have been able to replicate this issue. I have opened an issue in the relevant plugins: https://github.com/stevearc/dressing.nvim/issues/59

**Comment by mehalter** [comment]
This has been fixed in the latest version of dressing
