### ISSUE TITLE
Incorrect icon background color for inactive tabs with default theme

### ISSUE THREAD

**Issue by tomKPZ** [AstroNvim/AstroNvim#931]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v1.9.0-3-g851efa

### Neovim version (>= 0.7)

NVIM v0.7.2

### Operating system/version

Arch Linux

### Describe the bug

Observe that the background color for the icon on the inactive tab is using the active tab background color.

### Steps to Reproduce

1. Use default theme
2. Open multiple buffers to be shown in the bufferline

### Expected behavior

The background color for the icon should be the inactive tab background color.

### Screenshots

![Screenshot 2022-08-29 204452](https://user-images.githubusercontent.com/9124077/187344808-aa32329b-79d5-4290-85ec-e1fbc8a637a6.png)

**Comment by mehalter** [comment]
Dang, it looks like Bufferline had a recent change that broke our highlight groups and they are not open to fixing it :/ I have opened a PR to change the highlight groups and fix this, but @kabinspace is going to investigate more and approve it or propose a different fix.

**Comment by tomKPZ** [comment]
Thanks for the investigation and fix!

**Comment by mehalter** [comment]
@tomKPZ no problem! This does introduce a new highlight issue :( I'll fix it tomorrow though!

**Comment by mehalter** [comment]
@tomKPZ I just resolved that commit and fixed the new highlighting issue !
