### ISSUE TITLE
tabstop and shiftwidth options being reset when editing C/Cpp files

### ISSUE THREAD

**Issue by nmandrus1** [AstroNvim/AstroNvim#935]
### Question

When I open a C or Cpp file the tabstop and shiftwidth values have both been set to 2 and I would tabstop to be 4 and shiftwidth to be 0. 

Any Ideas?

Love the project by the way keep up the good work!

**Comment by mehalter** [comment]
You can put an auto command in your `polish` function in your `user/init.lua` file that sets shiftwidth and tabstop for `c` and `cpp` filetypes. Here are a couple example `user/init.lua` files that do this. One uses the default neovim API and the other uses a helper function we have for easily setting options. *Note:* these are complete minimal `user/init.lua` files that just set the options I am describing, you will have to move these entries to the correct place in your own `user/init.lua` file.

Default `vim` lua API:

```lua
return {
  polish = function()
    vim.api.nvim_create_autocmd("FileType", {
      desc = "C/C++ tabbing",
      pattern = { "c", "cpp" },
      callback = function()
        vim.opt.shiftwidth = 0
        vim.opt.tabstop = 4
      end,
    })
  end,
}
```

Using `astronvim.vim_opts` helper function:

```lua
return {
  polish = function()
    vim.api.nvim_create_autocmd("FileType", {
      desc = "C/C++ tabbing",
      pattern = { "c", "cpp" },
      callback = function() astronvim.vim_opts { opt = { shiftwidth = 0, tabstop = 4 } } end,
    })
  end,
}
```

This will work if you open a new file, but we use a plugin for automatically detecting the indentation of the currently opened file and setting it accordingly. So if you open an existing file this auto detection will override these default behaviors. If you want to *always* set the tabstop and shiftwidth to be what you mentioned before you will need to disable that functionality for the filetypes as well by overriding the `indent-o-matic` setup call in your `plugins` table:

```lua
return {
  plugins = {
    ["indent-o-matic"] = {
      filetype_c = { max_lines = 0 },
      filetype_cpp = { max_lines = 0 },
    },
  },
  polish = function()
    vim.api.nvim_create_autocmd("FileType", {
      desc = "C/C++ tabbing",
      pattern = { "c", "cpp" },
      callback = function() astronvim.vim_opts { opt = { shiftwidth = 0, tabstop = 4 } } end,
    })
  end,
}
```

Let me know if you have any other questions about this!
