### ISSUE TITLE
Cmp doesn't work in Rust files

### ISSUE THREAD

**Issue by lokicalmito** [AstroNvim/AstroNvim#939]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

Version: v1.9.0-5-g09c5d47

### Neovim version (>= 0.7)

NVIM v0.7.2

### Operating system/version

Fedora 35

### Describe the bug

First, I would like to say that I'm a beginner so I apologize if this is something on my end.

I can't use any of the cmp mappings in Rust files. I tested in a Python file and there it works.
For example I can't use Control+j/k to navigate the completions (Control+j creates a new line) and when I press enter it just makes a new line.
The only mappings that work are Control+n/p to navigate the completions, but completions are different when using those mappings for some reason.

There is an error every time I specifically open a Rust file

### Steps to Reproduce

Don't know what are the steps to reproduce.

### Expected behavior

For cmp to work in Rust files

### Screenshots

![image](https://user-images.githubusercontent.com/107685698/188142562-47a39596-8c30-4890-a12f-e1ab04a825e4.png)
This appears every time I open a Rust file

![image](https://user-images.githubusercontent.com/107685698/188142823-19ecea8e-b545-4d1a-9bf6-3d53945bc616.png)
I have libstdc++ installed

### Additional Context

I also updated Rust with `rustup update` and I still get the error

**Comment by mehalter** [comment]
@hunger do you have any ideas about this?

**Comment by hunger** [comment]
That huge red area suggests that your treesitter parser for rust is broken. You should be able to rebuild that: `:TSInstall rust` in neovim.

That is the first thing I would try to fix this issue.

Cmp does seem to work for me in rust:-)

**Comment by lokicalmito** [comment]
I get the following after I run `:TSInstall rust`
![image](https://user-images.githubusercontent.com/107685698/188150346-c55865f4-d7da-4843-9a8b-01a887c691cb.png)

**Comment by hunger** [comment]
So it managed to build the rust tree-sitter plugin and then fails to find a library? That is surprising:-) It should either work or fail to build.

Do you have libstdc++ installed somewhere? Which version?

**Comment by lokicalmito** [comment]
> Do you have libstdc++ installed somewhere? Which version?

Yes, please see the original post. I posted a screenshot.

**Comment by hunger** [comment]
Check the filesystem: What is the name of the file and the soversion backed into the binary? The soversion is what is actually used to do the lookup.

Looks like the libstdc++ you have installed is too new for the binary that fails to load.

Typically that is a prebuild binary that has these problems... Something like rust-analyzer (which IIRC does not use any C++, so it is probably not that) or something you installed via Mason. Try running `ldd` on those binaries and check whether all libs are found.

This is definitely not a astronvim issue by the way: That does not include any C++ code that might need this library:-)

**Comment by hunger** [comment]
Also look for symlinks, not just the proper file itself:-)

They should be in /lib* or /usr/lib*

**Comment by lokicalmito** [comment]
Ok so it seems that I had to install `clangStdenv` and/or `gccStdenv` from the NixOs packages. (This might have happened because I installed neovim trough the NixOs package manager, but I'm not sure)
Sorry for wasting your time and for the off-topic issue. :)
Have a great day!
