### ISSUE TITLE
When changing user_example errors appears.

### ISSUE THREAD

**Issue by joaquincorradi** [AstroNvim/AstroNvim#941]
User directory comes with the default name "user_example", when it's changed the following error appears:
`[mason-tool-installer] prettier: failed to install`

**Comment by Rid1-fz-06** [comment]
@joaquincorradi comment out the following lines

https://github.com/AstroNvim/AstroNvim/blob/1a2999090e1ba19fdacab71d964eb4bca93d7082/lua/user_example/init.lua#L237

https://github.com/AstroNvim/AstroNvim/blob/1a2999090e1ba19fdacab71d964eb4bca93d7082/lua/user_example/init.lua#L241

**Comment by mehalter** [comment]
@joaquincorradi if you want to use Mason to install language servers and stuff and are running into issues. Run `:Mason` to see what the error is that it's running into. My guess is it's something like `npm`not being installed
