### ISSUE TITLE
Colorizer error showing up on bottom when opening a file

### ISSUE THREAD

**Issue by sravanpannala** [AstroNvim/AstroNvim#942]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v1.9.0-6-g1a29990

### Neovim version (>= 0.7)

NVIM v0.7.2

### Operating system/version

Arch Linux

### Describe the bug

After the most recent update whenever I open any file this error shows up on the command bar.
> colorizer: Invalid type for filetypes "*"

I don't think it hinders any functionality.

### Steps to Reproduce

1. Open any file
2. Look at the bottom of the window
3. Find the error

### Expected behavior

There should be no error on the command bar. Most of the time its empty.

### Screenshots

![2022-09-04_17-22](https://user-images.githubusercontent.com/57152030/188334101-04daaf05-76c1-4eec-acab-feeb958308d9.png)

**Comment by mehalter** [comment]
Please pull the latest with AstroUpdate. This has been fixed in the latest commit.

**Comment by sravanpannala** [comment]
Thank you for the quick response!! I love AstroNvim and have recommended it to many people already. You've made my experience using and learning nvim/vim much better.

**Comment by mehalter** [comment]
That's awesome to hear! I love that the community is enjoying it and the hard work that has gone into it 😀 shout-out to @kabinspace for creating it 🎉
