### ISSUE TITLE
AstroNvim integration with WhichKey not working anymore

### ISSUE THREAD

**Issue by Kaporos** [AstroNvim/AstroNvim#943]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [x] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v1.9.0-7-gaf1d706

### Neovim version (>= 0.7)

NVIM v0.7.2

### Operating system/version

Linux 21b1f1d1dee6 5.17.7-arch1-1 (ArchLinux)

### Describe the bug

WhichKey probably made a breaking change, and it's not working with your config anymore, it's throwing an error just by taping space and waiting

### Steps to Reproduce

1. Just install a fresh AstroNvim config (I tried inside a docker)
2. Launch it, type space and wait

### Expected behavior

It should open WhichKey menu instead of an error 

### Screenshots

![image](https://user-images.githubusercontent.com/34960023/188422714-fe69ee69-4307-49d2-9469-c43760745661.png)

**Comment by avnigo** [comment]
Can confirm that it's commit folke/which-key.nvim@9c190ea that causes the error. Rolling back https://github.com/folke/which-key.nvim/commit/9c190ea91939eba8c2d45660127e0403a5300b5a#diff-3f61266f94afed6ca9a59bcff0a37a47448eec58c68bac28a93d0844ca3623a1L58-R58 fixes it for now.

**Comment by mehalter** [comment]
https://github.com/folke/which-key.nvim/issues/330


This is a known upstream bug. Hopefully it gets fixed soon. In the mean time users can pin their which key commit or use AstroNvim stable which will not have this issue :)

**Comment by mehalter** [comment]
I will keep this open until the upstream bug is resolved

**Comment by mehalter** [comment]
Looks like a fix should be pushed in the next hour or so: https://github.com/folke/which-key.nvim/issues/329#issuecomment-1237010286

**Comment by Kaporos** [comment]
Fixed by which-key dev !
