### ISSUE TITLE
can't format javascript and typescript code using eslint-lsp.

### ISSUE THREAD

**Issue by TickHeart** [AstroNvim/AstroNvim#949]
### Question

I still don't have the function of formatting code after I execute `: LspInstall eslint.

I am a novice, and I hope to get your help.

### User Configuration

// init.lua

local impatient_ok, impatient = pcall(require, "impatient")
if impatient_ok then impatient.enable_profile() end

for _, source in ipairs {
  "core.utils",
  "core.options",
  "core.bootstrap",
  "core.plugins",
  "core.autocmds",
  "core.mappings",
  "configs.which-key-register",
} do
  local status_ok, fault = pcall(require, source)
  if not status_ok then vim.api.nvim_err_writeln("Failed to load " .. source .. "\n\n" .. fault) end
end

astronvim.conditional_func(astronvim.user_plugin_opts("polish", nil, false))

**Comment by jondwoo** [comment]
you will need to edit your user config init.lua `(.config/nvim/lua/user/init.lua)` and not the init.lua you have pasted.

if you do not have a user folder, you can make a default user config `cp -r ~/.config/nvim/lua/user_example/ ~/.config/nvim/lua/user/`

from there you can define any formatter/linter under the `null-ls` override section. for example here is my setup:
```
["null-ls"] = function(config)
      local null_ls = require "null-ls"
      config.sources = {
        -- Set a formatter
        null_ls.builtins.formatting.eslint_d,
        null_ls.builtins.formatting.fixjson,
        null_ls.builtins.formatting.prismaFmt,
        -- Set a linter
        null_ls.builtins.diagnostics.eslint_d,
        null_ls.builtins.diagnostics.jsonlint,
        -- Set code actions
        null_ls.builtins.code_actions.eslint_d,
      }
      -- set up null-ls's on_attach function
      config.on_attach = function(client)
        -- NOTE: You can remove this on attach function to disable format on save
        if client.resolved_capabilities.document_formatting then
          vim.api.nvim_create_autocmd("BufWritePre", {
            desc = "Auto format before save",
            pattern = "<buffer>",
            callback = vim.lsp.buf.formatting_sync,
          })
        end
      end
      return config -- return final config table
    end,
```

you will also need to install eslint globally

**Comment by TickHeart** [comment]
> 

Thank you, I'll have a try.

**Comment by TickHeart** [comment]
> you will need to edit your user config init.lua `(.config/nvim/lua/user/init.lua)` and not the init.lua you have pasted.
> 
> if you do not have a user folder, you can make a default user config `cp -r ~/.config/nvim/lua/user_example/ ~/.config/nvim/lua/user/`
> 
> from there you can define any [formatter/linter](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#formatting) under the `null-ls` override section. for example here is my setup:
> 
> ```
> ["null-ls"] = function(config)
>       local null_ls = require "null-ls"
>       config.sources = {
>         -- Set a formatter
>         null_ls.builtins.formatting.eslint_d,
>         null_ls.builtins.formatting.fixjson,
>         null_ls.builtins.formatting.prismaFmt,
>         -- Set a linter
>         null_ls.builtins.diagnostics.eslint_d,
>         null_ls.builtins.diagnostics.jsonlint,
>         -- Set code actions
>         null_ls.builtins.code_actions.eslint_d,
>       }
>       -- set up null-ls's on_attach function
>       config.on_attach = function(client)
>         -- NOTE: You can remove this on attach function to disable format on save
>         if client.resolved_capabilities.document_formatting then
>           vim.api.nvim_create_autocmd("BufWritePre", {
>             desc = "Auto format before save",
>             pattern = "<buffer>",
>             callback = vim.lsp.buf.formatting_sync,
>           })
>         end
>       end
>       return config -- return final config table
>     end,
> ```
> 
> you will also need to install eslint globally

@jondwoo Thank you . My problem has been solved.
