### ISSUE TITLE
Returning a Lua table in `lsp/mappings.lua` results in `keymap` error when opening any LSP-enabled buffer after the first one

### ISSUE THREAD

**Issue by yehorb** [AstroNvim/AstroNvim#952]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v1.9.1-1-gf896f2b

### Neovim version (>= 0.7)

NVIM v0.7.2

### Operating system/version

Windows 10 Pro, 21H2, 19044.1889

### Describe the bug

In User Configuration, returning a Lua table in `lsp/mappings.lua` results in `keymap` error when opening any LSP-enabled buffer after the first one.

```lua
Error executing vim.schedule lua callback: vim/keymap.lua:52: rhs: expected string|function, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua:662: in function 'validate'
        vim/keymap.lua:52: in function 'map'
        C:\Users\yehorb\AppData\Local\nvim/lua\core\utils\init.lua:396: in function 'set_mappings'
        ...s\yehorb\AppData\Local\nvim/lua\configs\lsp\handlers.lua:20: in function 'on_attach'
        ...s\yehorb\AppData\Local\nvim/lua\configs\lsp\handlers.lua:109: in function '_on_attach'
        ...ck\packer\start\nvim-lspconfig/lua\lspconfig\configs.lua:288: in function '_setup_buffer'
        ...ck\packer\start\nvim-lspconfig/lua\lspconfig\configs.lua:191: in function 'cb'
        vim/_editor.lua:256: in function <vim/_editor.lua:256>
```

### Steps to Reproduce

1. Install `AstroNvim`.
3. Enter `nvim`, install Lua LSP: `:LspInstall sumneko_lua`, exit `nvim`.
4. Create `~/.config/astronvim/lua/user/lsp/mappings.lua` file with the following content:
```lua
return {
  n = {
    ["<C-]>"] = { function() vim.lsp.buf.definition() end, desc = "Show the definition of current symbol" },
    ["gh"] = { function() vim.lsp.buf.hover() end, desc = "Hover symbol details" },
  },
}
```
5. Edit FIRST Lua file: `cd ~/.config/nvim && nvim init.lua` - no error.
6. Edit SECOND Lua file: `:e lua/config/core/utils/init.lua` - error.

### Expected behavior

Either returning Lua table should not cause the `keymap` error, or documentation should explicitly state that `lsp/mappings.lua` should only use the `function(table) ... end` format.

### Additional Context

Looks like the cause for the issue is two-fold:
1. https://github.com/AstroNvim/AstroNvim/blob/main/lua/core/utils/init.lua#L391 sets `options[1] = nil`, where `options[1]` is the `rhs`.
2. `lsp/mappings.lua` is required more than once during an editing session.

During AstroNvim operation:

* The first time `lsp/mappings.lua` is loaded by AstroNvim, the returned table is cached by Lua's `require`.
* `astronvim.set_mappings` sets `options[1] = nil` for every entry in the table, that is now cached.
* The next time `lsp/mappings.lua` is loaded by AstroNvim, the cached table is used, where `rhs` is `nil` now (and forever).

Even format like this did not work for me, as maps `mappings.n["<C-]>"]` and `mappings.n["gh"]`  remained mutated after the first loaded buffer.

```lua
local mappings = {
  n = {
    ["<C-]>"] = { function() vim.lsp.buf.definition() end, desc = "Show the definition of current symbol" },
    ["gh"] = { function() vim.lsp.buf.hover() end, desc = "Hover symbol details" },
  },
}

return function(default)
  default.n = vim.tbl_extend("force", default.n, mappings.n)
  return default
end
```

The solution is to use the `function(table) ... end` format in `lsp/mappings.lua`, build user mappings INSIDE the function body, and manually `deep_extend` the default table:

```lua
return function(default)
  default = vim.tbl_extend("force", default, {
    n = {
      ["<C-]>"] = { function() vim.lsp.buf.definition() end, desc = "Show the definition of current symbol" },
      ["gh"] = { function() vim.lsp.buf.hover() end, desc = "Hover symbol details" },
    },
  })
  return default
end
```

This way user mappings will be created anew every time, and will not be broken by `set_mappings`.

I did not post the PR with the fix, because I do not understand the function of `options[1] = nil`. Just removing it may be undesirable. If that is the case, documentation should explicitly mention that `lsp.mappings` options will be loaded more than once, and it WILL BE MUTATED, so users clearly understand that `function(table) ... end` format is desirable for the option.

**Comment by mehalter** [comment]
Thanks so much for this detailed response @yehorb ! I have updated the code to fix this issue. Could you give the new branch a try to verify if it resolves your issue? There are instructions on the PR to test it.

**Comment by yehorb** [comment]
I checked the new branch, it looks like `set_mappings` no longer mutates `lsp.mappings`. I am able to revert to plain table return.
