### ISSUE TITLE
Move line config

### ISSUE THREAD

**Issue by nhanguyen101299** [AstroNvim/AstroNvim#956]
### Is your feature related to a problem?

move line when code

### Describe the new feature

move line

### Additional context

move line

**Comment by mehalter** [comment]
Can you please add more details describing what you mean with this feature request

**Comment by LoneExile** [comment]
Is this what you mean?

1. Enter visual line mode
2. Alt+ j , Alt+k move line

```lua
local opts = { noremap = true, silent = true }
local keymap = vim.api.nvim_set_keymap
keymap("v", "<A-j>", ":m .+1<CR>==", opts)
keymap("v", "<A-k>", ":m .-2<CR>==", opts)
keymap("v", "p", '"_dP', opts)

keymap("x", "<A-j>", ":move '>+1<CR>gv-gv", opts)
keymap("x", "<A-k>", ":move '<-2<CR>gv-gv", opts)

```

**Comment by mehalter** [comment]
@nhanguyen101299 This is a rather user specific request that doesn't fit into everyone's workflow. @LoneExile has provided a few great example key mappings that can be added to your `user/init.lua` file to add these mappings.

**Comment by airtonix** [comment]
This is relevant to my needs. I'm completely and utterly a noob when it comes to vim. to the point it causes me frustrations. so i want my keyboard mappings to be the same as what I'm used to every where else.

In my `user/init.lua`

```lua
...
i = {
      -- Moving Lines
      ["<C-S-up"] = { "<cmd>MoveLine(-1)<cr>", desc = "Move line up" },
      ["<C-S-Down>"] = { "<cmd>MoveLine(1)<cr>", desc = "Move line down" },
}
```

Only `ctrl` + `shift` + `down` moves the line down.
`ctrl` + `shift` + `up` does nothing.

i even tried: `alt` + `up`... still nothing.

I tried the same thing in normal vim, it works: 

```
inoremap <C-S-Down> <Esc>:m+<CR>i
inoremap <C-S-Up> <Esc>:m-2<CR>i
```

but not in astrovim. so confused.

**Comment by airtonix** [comment]
very odd, no idea what's going on here but if i modify the root `init.lua` and dump in something like: 

```lua

local opts = { noremap = true, silent = true }
local keymap = vim.api.nvim_set_keymap
keymap("i", "<C-S-Down>", "<cmd>:MoveLine(1)<cr>", opts)
keymap("i", "<C-S-Up>", "<cmd>:MoveLine(-1)<cr>", opts)
```
then it does what i expect. (I'm using `fedepujol/move.nvim` btw)

**Comment by PaulKushch** [comment]
@airtonix can you please paste your config if you solved it?
I have trouble to make `move.nvim` work in visual line mode. Same with @LoneExile config provided above. 
Best regards

**Comment by mehalter** [comment]
@PaulKushch you shouldn't have `:` after `<cmd>`

**Comment by PaulKushch** [comment]
@mehalter Ah ok thanks, but the problem still persists, It only moves the top line up/down selected in visual line mode, not all the lines. 
[Screencast from 2022-11-25 19:05:24.webm](https://user-images.githubusercontent.com/5386035/204037552-d0d7a7a1-d972-409b-81cd-83231a2a93db.webm)

**Comment by PaulKushch** [comment]
@mehalter It is strange that running commands by itself works but not the mappings. Any idea why?

**Comment by mehalter** [comment]
Probably because you are running `:` commands and not ranged commands like `:'<,'>`. When you do `:` in visual mode it automatically fills in `:'<,'>`. So you are not actually running the same command. I would recommend googling around for making bindings in visual mode

**Comment by PaulKushch** [comment]
@mehalter But I did remove : after <cmd>, it is still the same behavior as I showed in video above:/

**Comment by mehalter** [comment]
`<cmd>` is basically saying `:`, `:` puts you in command mode, `<cmd>` is passing to command mode. You need to pass the selection range to the command. Typically this is done with `'<,'>` you can see this by pressing `:` in visual mode and see that it takes you to command mode and types in `'<,'>`. In your binding you are not passing a selection range to the command so it's running the same thing that it would in normal mode.

**Comment by LoneExile** [comment]
@PaulKushch  Here's how I set up my [keymap](https://github.com/LoneExile/nvim/blob/main/lua/user/core/keymaps.lua).

Try to search "vscode" in the file.

**Comment by PaulKushch** [comment]
@LoneExile @mehalter I updated according to your comments:
```
x = {
   ["<A-k>"] = { "<cmd>'<,'>m '<-2<CR>gv-gv", desc = "Move block up" }, 
   ["<A-j>"] = { "<cmd>'<,'>m '>+1<CR>gv-gv", desc = "Move block down" },
},
```
But when I press Alt + k in visual line mode I get:

![image](https://user-images.githubusercontent.com/5386035/204275380-b6c0ceb7-7f8c-4e9a-9e99-c853c0625195.png)

So I need to press `gv` to select selection again, then it works. **But** only 1 time. So I basically can only move visual selection 1 time and not several rows. It seems that selection is dropped. See video below:
[Screencast from 2022-11-28 13:18:03.webm](https://user-images.githubusercontent.com/5386035/204276036-b3b2bcef-7592-4688-818a-6a28c3ad85a7.webm)

**Comment by PaulKushch** [comment]
I solved it by using [gomove](https://github.com/booperlv/nvim-gomove)
