### ISSUE TITLE
Telescope ignore build folders

### ISSUE THREAD

**Issue by dakata1337** [AstroNvim/AstroNvim#958]
### Question

How can I tell Telescope (Find Files) to ignore Rust build folder `target`?

**Comment by mehalter** [comment]
Telescope by default ignores hidden files as well as respects `gitignore`, you can use `<leader>fF` to search all files.

**Comment by dakata1337** [comment]
Is there a way to ignore folders which aren't in `.gitignore`?

**Comment by LoneExile** [comment]
https://github.com/nvim-telescope/telescope.nvim/blob/master/doc/telescope.txt#L605

OR

> Like other tools specialized to code search, ripgrep defaults to recursive directory search and won't search files 
ignored by your `.gitignore`/`.ignore`/`.rgignore` files. It also ignores hidden and binary files by

https://github.com/BurntSushi/ripgrep#why-should-i-use-ripgrep

**Comment by dakata1337** [comment]
> https://github.com/nvim-telescope/telescope.nvim/blob/master/doc/telescope.txt#L605
> 
> OR
> 
> > Like other tools specialized to code search, ripgrep defaults to recursive directory search and won't search files
> > ignored by your `.gitignore`/`.ignore`/`.rgignore` files. It also ignores hidden and binary files by
> 
> https://github.com/BurntSushi/ripgrep#why-should-i-use-ripgrep

Thank you.

**Comment by M-Xue** [comment]
Telescope seems to still be including the Rust build folder `target` for me. I have version 0.1.0. This is my config. Is anyone else having this issue?

![image](https://user-images.githubusercontent.com/96305124/230616412-124ea990-c50a-457b-8470-a0483476ecc7.png)
