### ISSUE TITLE
Treesitter not working fresh install

### ISSUE THREAD

**Issue by LoneExile** [AstroNvim/AstroNvim#960]
### Question

```bash
rm -rf ~/.local/share/nvim/site ./nvim
git clone https://github.com/AstroNvim/AstroNvim ~/.config/nvim
nvim +PackerSync
```
```lua
:TSInstall lua
:TSEnable lua
```

https://user-images.githubusercontent.com/82561297/189512241-37e50525-f5cf-4945-a75b-a645378b7249.mp4

**Comment by mehalter** [comment]
Are you using Neovim nightly or Neovim stable? What is the output of `nvim --version`

**Comment by LoneExile** [comment]
version : `NVIM v0.8.0-dev-1070-g9b4cab012`

**Comment by mehalter** [comment]
Please use a stable version of Neovim. Unstable and nightly releases are unsupported.
