### ISSUE TITLE
Trying to use treesitter foldmethod

### ISSUE THREAD

**Issue by almcr** [AstroNvim/AstroNvim#961]
### Question

Hi,
I'm trying to use treesitter for code folding as showed in this [blog](https://www.jmaguire.tech/posts/treesitter_folding/), i added these options in my `user/init.lua` (I'm using a fresh install of Astronvim and installed treesiter parsers)
```lua
foldmethod = "expr",
foldexpr = "nvim_treesitter#foldexpr()"
```

### The behavior
If i open neovim in a root dir using `nvim .` and then, open a file with neotree, the code is not folded, same also by opening any file with telescope. 

If i open a file directly with neovim `nvim path/to/somefile.lua` the code is actually folded. Also i added an autocmd inside `polish` section, to unfold the code on buffer enter, but it doesn't kick in.
```lua
vim.api.nvim_create_autocmd("BufReadPost,FileReadPost", {
  pattern = "*",
  callback = function()
    vim.api.nvim_command "normal zR"
  end,
})
```
### questions
Why does the folding not working when opening nvim in root dir.
Why the autocmd doesn't kick in when the actuall code is folded.

**Comment by mehalter** [comment]
@almcr I would Also recommend setting `foldenable = false` in your `options.opt` table. This will disable the automatic complete folding when you open the file rather than using an autocmd

```
return {
  options = {
    opt = {
      foldenable = false,
      foldexpr = "nvim_treesitter#foldexpr()", -- set Treesitter based folding
      foldmethod = "expr",
    }
  }
}
```
