### ISSUE TITLE
Lsp document highlight stop working with gopls

### ISSUE THREAD

**Issue by almcr** [AstroNvim/AstroNvim#962]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

1.9.2

### Neovim version (>= 0.7)

NVIM 0.7.2

### Operating system/version

Popos 22.04

### Describe the bug

Using gopls, when i go to definition of some type or struct member, and jump back `Ctrl-O`, word highlighting freezes on the original file. Doing `:e` on the file will clear the highlights and starts working properly again.

### Steps to Reproduce

fresh install of Astronvim
install TS parser for go
install gopls with Mason
do a go to definition and go back with `Ctrl-O`

### Expected behavior

Word highlighting should be working correctly when jumping back to a previous file.

### Screenshots

[Screencast from 09-11-2022 05:56:11 PM.webm](https://user-images.githubusercontent.com/6459586/189537534-9d459607-6a63-4dd9-9d9d-a2ee95978c23.webm)

### Additional Context

I checked lsp handlers on core configs and saw there is an autocmd definition for `CursorHold` and `CursorMoved`, it seems the callbacks aren't triggering after the jump back ??.

**Comment by Juniar-Rakhman** [comment]
I cannot replicate this issue using the latest Astronvim.
I code in go extensively and found no problems whatsoever.
Feel free to tryout my config here:
https://github.com/Juniar-Rakhman/astronvim_config

**Comment by almcr** [comment]
@Juniar-Rakhman I'll give it a shot !

**Comment by mehalter** [comment]
Hm, I can replicate this it seems with a base installation of AstroNvim and minimal config. I can also replicate without AstroNvim. I think this might be an upstream issue with the `CursorHold` and `CursorMoved` autocommand events :/

**Comment by mehalter** [comment]
Especially since that autocommand is exactly what is recommended to do this behavior in the official Neovim documentation

**Comment by mehalter** [comment]
@cannonpalms @almcr I was able to investigate this deeper and found the issue and have a fix in AstroNvim nightly :) It will hit the stable release on friday !

**Comment by mehalter** [comment]
This has been resolved on stable
