### ISSUE TITLE
Icons aren't setup automatically in wsl2?

### ISSUE THREAD

**Issue by snk-js** [AstroNvim/AstroNvim#963]
### Question

Every time I install from astrovim on wsl2 it comes with no icons 
![image](https://user-images.githubusercontent.com/34718184/189549154-9d0f0883-c1b1-4d09-a13e-e373dfcdac5b.png)

am I missing something?

default configs.

**Comment by Fau818** [comment]
I have the same issue in iTerm2.

**Comment by mehalter** [comment]
There is a requirement that you need to install and use a Nerd Font to get the icons

**Comment by Fau818** [comment]
Thanks. It works perfectly!

**Comment by Fau818** [comment]
> There is a requirement that you need to install and use a Nerd Font to get the icons

Thanks. It works perfectly!
