### ISSUE TITLE
How to yank a buffer and paste into the python repl (invoked by <leader>tp)

### ISSUE THREAD

**Issue by aphsa** [AstroNvim/AstroNvim#964]
### Question

How to yank a buffer and paste into the python repl (which was invoked by <leader>tp)?

I am using the default configuration  as provided by this GitHub site and didn't make any updates.

**Comment by mehalter** [comment]
AstroNvim works by linking the default yank buffer to the system clipboard. So if you have yanked something and open the python REPL then you simply just need to do a normal paste. Here is an example with a stock AstroNvim without any user configuration: https://asciinema.org/a/pQ3S315gFY4yU9rwfynkvfVjR
