### ISSUE TITLE
Ballerina programming language support

### ISSUE THREAD

**Issue by bihari123** [AstroNvim/AstroNvim#968]
### Describe the new feature

Plz add a support for ballerina programmming language:   https://github.com/ballerina-attic/plugin-vim

**Comment by mehalter** [comment]
This can be done by adding the plugin to your `user/init.lua` file as shown in the provided `user_example/init.lua` as well as described in the documentation at astronvim.github.io. This is very user specific so we do not want to upstream this to AstroNvim.
