### ISSUE TITLE
Autopairs not enabled by default

### ISSUE THREAD

**Issue by BrandonBlankerLim-it** [AstroNvim/AstroNvim#971]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

Version: v1.9.1-112-g39b30e9

### Neovim version (>= 0.7)

NVIM v0.8.0-dev-1070-g9b4cab012

### Operating system/version

Arch Linux on Windows 10 x86_64

### Describe the bug

Autopairs, according to the files, should be enabled by default.

However, launching astrovim, it is not working. One needs to toggle it with `<leader>ua` for it to work properly.

I already have `autopairs_enabled = true` in the config

### Steps to Reproduce

1. Open astrovim
2. Type `"` (only one appears)
3. `<leader>ua` 
4. Type `"` (two appear)

### Expected behavior

1. Open astrovim
2. Type `"` (two appear)

**Comment by mehalter** [comment]
I have fixed this in the latest push to the `v2` branch.
