### ISSUE TITLE
auto_quit autocmd produces undesired behavior

### ISSUE THREAD

**Issue by stevearc** [AstroNvim/AstroNvim#975]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v1.9.2

### Neovim version (>= 0.7)

v0.7.2

### Operating system/version

Linux

### Describe the bug

I got a bug report on aerial here https://github.com/stevearc/aerial.nvim/issues/151 that I traced back to the auto_quit autocmd.
https://github.com/AstroNvim/AstroNvim/blob/9badfdd8f2e472fc79dd666679df9ed6237240a8/lua/core/autocmds.lua#L20-L27

My interpretation of this code is: "quit the current window if the total number of (visible or hidden) aerial and neo-tree buffers is equal to the number of total windows across all tabs, and that number is > 1". I don't think that makes much sense.

I was going to take a crack at fixing it, but I don't think I have a good idea of what desired behavior is. Is the intent: "close visible aerial windows in the current tab if the only other windows are neo-tree"? The original PR #869 mentions "auto close AstroNvim if a window is closed and only Aerial and Neo-tree are opened." Is that actually what you want to have happen? I don't know what the general workflow with neo-tree looks like, but as a user I feel like I might expect to be able to have a single-window file browsing experience without auto-quitting. Either way, I'm happy to make the changes if you can clarify the intent.

### Steps to Reproduce

1. `nvim .`
2. open a file
3. `:AerialToggle`

See error; aerial is not open.

### Expected behavior

No error

**Comment by mehalter** [comment]
@stevearc it's the same idea of "auto close if aerial is the last window" since it's a sidebar. Most people also use autoclose if neotree or nvim tree is the last window because it's just a sidebar. If I close my last buffer that isn't a sidebar, it should respect the auto close behavior of each being set instead of being left with 2 sidebars and no content.

**Comment by mehalter** [comment]
The > 1 case is because both aerial and the tree handle the 1 case so I don't want to worry about the edge cases here.

**Comment by stevearc** [comment]
Gotcha, I'll put together a PR
