### ISSUE TITLE
Shift width formatting

### ISSUE THREAD

**Issue by b1twe1ser** [AstroNvim/AstroNvim#977]
Hello 👋🏼 I have changed 'shiftwidth = 4' in my init.lua and it works fine until I format my code, then it jumps back to 2, and sets the shift width automatically for this file ? How may I change it, so that it formats code with a shift width of 4 ? Thanks for the help ! ✨

**Comment by dpriedel** [comment]
I have noticed a recent change (a few days ago, not sure exactly when it started) in tabstop, shiftwidth, etc settings from those set in my init.lua.

I am using nvim 0.8 and AstroNVim 2.2.0

For example, I have following in my init.lua

 -- set vim options here (vim.<first_key>.<second_key> =  value)
  options = {
    opt = {
      -- set to true or false etc.
      relativenumber = false, -- sets vim.opt.relativenumber
      number = true, -- sets vim.opt.number
      spell = true, -- sets vim.opt.spell
      signcolumn = "auto", -- sets vim.opt.signcolumn to auto
      wrap = false, -- sets vim.opt.wrap
      tabstop = 4,
      shiftwidth = 4,
      softtabstop = 4,
      expandtab = true,
      cmdheight = 1,
    },


This works fine when I edit a Python file but when I edit a C++ file, my tabstop is somewhere set to 8 and the related setting change too.

I am using clangd as LSP server for C++.

I have searched through the various settings files but have not found anything that looks like the source of this.

**Comment by mehalter** [comment]
We are using a plugin called [indent-o-matic](https://github.com/Darazaki/indent-o-matic) that should be calculating and setting the tabstop/indent size based on the file that is currently open. Is there a chance you are opening a file that might be making the editor think that the files should be indented in a different way? If you want to disable this then you could try disabling that plugin:

```lua
return {
  plugins = {
    init = {
      ["Darazaki/indent-o-matic"] = { disable = true },
    },
  },
}
```

and see if that gives you the behavior that you want.

Also some language servers like `clangd` in particular have formatters that will change indent settings when you format. I am pretty sure `clangd` prefers 2 spaces as indentation level, but I'm not completely sure. Hopefully this can give some insight into what's happening.

I would definitely recommend that if you want to force the editor to use a specific indent style all the time to just disable `indent-o-matic`. Just make sure to do a `:PackerSync` after changing the `plugins.init` table and restarting to make sure the plugin gets removed

**Comment by dpriedel** [comment]
I disabled the indent-o-matic plugin as you suggested and all is back to 
the way it was.

Just a note: I have been using clangd with nvim/astronvim for a while 
and have had no problems with clangd overriding my tabsettings.

Thanks for your quick response !!
