### ISSUE TITLE
Add new luasnip

### ISSUE THREAD

**Issue by LintaoAmons** [AstroNvim/AstroNvim#979]
### Question

I'm learning to add new snippet.

I tried to put my code inside a new file `user.my-snip.all.lua` and require it inside `init.polish` table

```lua
local _, ls = pcall(require, "luasnip")
if not _ then
  vim.notify "Load luasnip failed"
  return
end

local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

ls.add_snippets("all", {
  s("ternary", {
    -- equivalent to "${1:cond} ? ${2:then} : ${3:else}"
    i(1, "cond"),
    t " ? ",
    i(2, "then"),
    t " : ",
    i(3, "else"),
  }),
})
```

But it tell me that `Load luasnip failed`

**Comment by LintaoAmons** [comment]
The reason I want to write lua code to add snippet instead of use vscode-style, is that I want to add my postfix snippet. 

So I have to add it this way, as far as I know.

**Comment by mehalter** [comment]
In our setup luasnip is lazy loaded. So it is not necessarily loaded when the `polish` function runs. An easy way to do this would be to override the configuration function in theplugin set up. Just make sure to load our config first. So it would look something like this (this is a minimal `user/init.lua` file:

```lua
return {
  plugins = {
    ["L3MON4D3/LuaSnip"] = {
      config = function()
        require "configs.luasnip"
        -- don't need to check because we are guaranteed to have luasnip
        local ls = require("luasnip")

        local s = ls.snippet
        local t = ls.text_node
        local i = ls.insert_node

        ls.add_snippets("all", {
          s("ternary", {
            -- equivalent to "${1:cond} ? ${2:then} : ${3:else}"
            i(1, "cond"),
            t " ? ",
            i(2, "then"),
            t " : ",
            i(3, "else"),
          }),
        })
      end,
    },
  },
}
```

**Comment by mehalter** [comment]
Just make sure to do a `:PackerSync` after you make changes to the `plugins.init` table
