### ISSUE TITLE
Undefined variable when loading packer_compiled

### ISSUE THREAD

**Issue by convers39** [AstroNvim/AstroNvim#982]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

 v1.9.2-1-g9059299

### Neovim version (>= 0.7)

0.7.2

### Operating system/version

macOS 12.4

### Describe the bug

I got this error when loading with this config file [here](https://github.com/convers39/astro-nvim-config/blob/master/init.lua).

<img width="923" alt="image" src="https://user-images.githubusercontent.com/42597395/191007544-8c881a9b-243d-4010-9a9f-39fa5c298f71.png">

And the color theme is broken
<img width="1727" alt="image" src="https://user-images.githubusercontent.com/42597395/191008695-26119826-0f4d-4c63-bfae-c11b2a298b56.png">

When I do `AstroReload` it seems to fix the color theme, but it shows a message as below

<img width="590" alt="image" src="https://user-images.githubusercontent.com/42597395/191008596-8b5ad95f-03ad-49f8-9e39-60ce932d167b.png">

And the issue still exists when I restart neovim.

I have tried to reinstall astro vim with commands below, but with no luck

```bash
rm -rf ~/.config/nvim
rm -rf ~/.cache/nvim
rm -rf ~/.local/share/nvim
```

### Steps to Reproduce

1. Use the config file
2. start neovim

### Expected behavior

no error when starting astrovim

**Comment by mehalter** [comment]
Can you share your user configuration either a link to a repository if you have one or just paste your `user/init.lua` file into a comment? It seems like you probably have an error in your packer configuration that is messing things up.

**Comment by convers39** [comment]
@mehalter Hi! Sure here is the config file link:

https://github.com/convers39/astro-nvim-config/blob/master/init.lua

**Comment by mehalter** [comment]
I see the issue, it's with your `vim-bookmarks` definition in your `plugins.init` table. You are not telling the plugin to load after Telescope, so you are unable to load Telescope and that variable is undefinied.


```lua
      {
        "MattesGroeger/vim-bookmarks",
        after = "telescope.nvim",
        config = function() require("telescope").load_extension "vim_bookmarks" end,
      },
```

you need to fix it to this

**Comment by convers39** [comment]
@mehalter you are a star!!!!
