### ISSUE TITLE
How to customize cmp lspkind format

### ISSUE THREAD

**Issue by convers39** [AstroNvim/AstroNvim#983]
### Question

Here is my config which is not working

https://github.com/convers39/astro-nvim-config/blob/master/cmp.lua

I have read the docs 
https://github.com/onsails/lspkind.nvim

And copy from 
https://github.com/datamonsterr/astronvim_config/blob/main/plugins/cmp.lua

Neither the mode (text + symbol) nor the symbols changed, not sure how to configure this properly.
<img width="640" alt="image" src="https://user-images.githubusercontent.com/42597395/191039652-fe68106b-a2ec-46ca-8414-c23f2ae17ad6.png">

What I was trying to do is formating the autocomplete like nvchad...

<img width="641" alt="image" src="https://user-images.githubusercontent.com/42597395/191038618-d0830037-95cf-4c54-b232-f9bc2b9fbf65.png">

### User Configuration

```lua
-- cmp.lua

local kind_icons = {
  Text = "",
  Method = "",
  Function = "",
  Constructor = "",
  Field = "ﰠ",
  Variable = "",
  Class = "",
  Interface = "",
  Module = "",
  Property = "",
  Unit = "",
  Value = "",
  Enum = "",
  Keyword = "",
  Snippet = "",
  Color = "",
  File = "",
  Reference = "",
  Folder = "",
  EnumMember = "",
  Constant = "",
  Struct = "פּ",
  Event = "",
  Operator = "",
  TypeParameter = "",
}
local lspkind = require "lspkind"
return function(config)
  config.source_priority = {
    nvim_lsp = 1000,
    cmp_tabnine = 900,
    nvim_lua = 800,
    luasnip = 700,
    buffer = 500,
    path = 250,
  }
  config.formatting = {
    fields = { "abbr", "kind", "menu" },
    format = lspkind.cmp_format {
      mode = "text_symbol", -- show only symbol annotations
      maxwidth = 50, -- prevent the popup from showing more than provided characters (e.g 50 will not show more than 50 characters)
      -- The function below will be called before any actual modifications from lspkind
      -- so that you can provide more controls on popup customization. (See [#30](https://github.com/onsails/lspkind-nvim/pull/30))
      before = function(entry, vim_item)
        local shorten_abbr = string.sub(vim_item.abbr, 1, 30)
        if shorten_abbr ~= vim_item.abbr then vim_item.abbr = shorten_abbr .. "..." end
        -- Kind icons
        vim_item.kind = string.format("%s %s", kind_icons[vim_item.kind], vim_item.kind)
        -- Source
        vim_item.menu = ({
          buffer = "[Buf]",
          nvim_lsp = "[LSP]",
          luasnip = "[LuaSnip]",
          nvim_lua = "[API]",
          -- latex_symbols = "[LaTeX]",
          cmp_tabnine = "[Tabnine]",
          path = "[Path]",
          -- emoji = "[Emoji]",
        })[entry.source.name]
        return vim_item
      end,
    },
  }
  return config
end
```

**Comment by AllenCortuna** [comment]
Customised the lspkind plugin in 
`user/plugins/lspkind.lua`
```lua
return {
  mode = "symbol",
  symbol_map = {
    -- Array = "",
    -- Boolean = "⊨",
    -- Class = "",
    -- Constructor = "",
    -- Key = "",
    -- Namespace = "",
    -- Null = "NULL",
    -- Number = "#",
    -- Object = "⦿",
    -- Package = "",
    -- Property = "",
    -- Reference = "",
    -- Snippet = "",
    -- String = "𝓐",
    -- TypeParameter = "",
    -- Unit = "",

                Text = "", --
                Method = "", --
                Function = "", --
                Constructor = "",
                Field = "",
                Variable = "",
                Class = "", --
                Interface = "", --
                Module = "", --
                Property = "",
                Unit = "",
                Value = "",
                Enum = "",
                Keyword = "",
                Snippet = "",
                Color = "",
                File = "",
                Reference = "",
                Folder = "",
                EnumMember = "",
                Constant = "",
                Struct = "פּ",
                Event = "", --
                Operator = "",
                TypeParameter = "",
  }}
```

**Comment by convers39** [comment]
> Customised the lspkind plugin in `user/plugins/lspkind.lua`
> 
> ```lua
> return {
>   mode = "symbol",
>   symbol_map = {
>     -- Array = "",
>     -- Boolean = "⊨",
>     -- Class = "",
>     -- Constructor = "",
>     -- Key = "",
>     -- Namespace = "",
>     -- Null = "NULL",
>     -- Number = "#",
>     -- Object = "⦿",
>     -- Package = "",
>     -- Property = "",
>     -- Reference = "",
>     -- Snippet = "",
>     -- String = "𝓐",
>     -- TypeParameter = "",
>     -- Unit = "",
> 
>                 Text = "", --
>                 Method = "", --
>                 Function = "", --
>                 Constructor = "",
>                 Field = "",
>                 Variable = "",
>                 Class = "", --
>                 Interface = "", --
>                 Module = "", --
>                 Property = "",
>                 Unit = "",
>                 Value = "",
>                 Enum = "",
>                 Keyword = "",
>                 Snippet = "",
>                 Color = "",
>                 File = "",
>                 Reference = "",
>                 Folder = "",
>                 EnumMember = "",
>                 Constant = "",
>                 Struct = "פּ",
>                 Event = "", --
>                 Operator = "",
>                 TypeParameter = "",
>   }}
> ```

Thank you!
This worked! 

Do you have any ideas on how to do the formatting?

**Comment by mehalter** [comment]
You can use the `stylua` source in `null-ls` for formatting @convers39

**Comment by convers39** [comment]
> You can use the `stylua` source in `null-ls` for formatting @convers39

@mehalter Hi! Actually I was trying to change the format of cmp autocompletion:

<img width="827" alt="image" src="https://user-images.githubusercontent.com/42597395/192660475-38ea2141-51a4-47e0-9bae-fcf22ce50f17.png">

The setting in `lspkind.lua` does change the mode (text, text_symbol, symbol_text, symbol) and icons, but cannot do further formatting, such as adding a custom icon for cmp_tabnine source (currently just shown as text).

<img width="484" alt="image" src="https://user-images.githubusercontent.com/42597395/192660657-b2fc0fb3-2472-4ec4-a84c-483b22222cf1.png">
