### ISSUE TITLE
pyright does not work while other LSPs work

### ISSUE THREAD

**Issue by kraxli** [AstroNvim/AstroNvim#984]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v1.9.2-1-g9059299

### Neovim version (>= 0.7)

NVIM v0.7.2

### Operating system/version

Linux Mint 20

### Describe the bug

I am using AstroNvim with @mehalter 's setup (https://code.mehalter.com/projects/68) which I have in ~/.config/astronvim/lua/user. 

Generally, LSP servers work, e.g. on Lua-files. However, when I open I python file I neither get LSP information like warnings and errors nor auto-completion even thought pyright seems to run:

I use Python 3.8.10.

Any idea what is could go wrong?

LSP-log messages:

```
[WARN][2022-09-19 22:05:06] ...lsp/handlers.lua:110	"The language server pyright triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[WARN][2022-09-19 22:10:58] ...lsp/handlers.lua:457	"stubPath /home/dave/typings is not a valid directory."
[ERROR][2022-09-19 22:10:58] ...lsp/handlers.lua:455	'Enumeration of workspace source files is taking longer than 10 seconds.\nThis may be because:\n* You have opened your home directory or entire hard drive as a workspace\n* Your workspace contains a very large number of directories and files\n* Your workspace contains a symlink to a directory with many files\n* Your workspace is remote, and file enumeration is slow\nTo reduce this time, open a workspace directory with fewer files or add a pyrightconfig.json configuration file with an "exclude" section to exclude subdirectories from your workspace. For more details, refer to https://github.com/microsoft/pyright/blob/main/docs/configuration.md.'
```

### Steps to Reproduce

I don't think this is sth to reproduce

### Expected behavior

LSP information displayed and auto-completion working.

### Screenshots

![lspInfo](https://user-images.githubusercontent.com/8371948/191109715-be632865-2777-464a-abfd-c4080434f44c.png)

**Comment by azinsharaf** [comment]
same issue here.

WSL 1 (Ubuntu 20.04)
AstroNvim: 1.9.2-4
Neovim: 0.8.0-dev

**Comment by mehalter** [comment]
I haven't had a chance to dive into this. One thing @azinsharaf is that AstroNvim does not officially support Neovim nightly and any unstable/unreleased version of Neovim.

**Comment by azinsharaf** [comment]
Thanks for the info. That was the only version that works with luajit. I built it from neovim source. I would check how i can build a stable version from source.

**Comment by mehalter** [comment]
Yeah, you will just want to make sure that you get the source for the latest tagged release rather than master. There are a lot of breaking changes in Neovim 0.8 and they are not accounted for in the latest release of AstroNvim. This will be getting resolved in the next 2 weeks.

**Comment by kraxli** [comment]
after reinstalling my whole OS, thinks work fine again. So probably not worth spending time on this issue!
