### ISSUE TITLE
How to completely change colour scheme

### ISSUE THREAD

**Issue by ayush-india** [AstroNvim/AstroNvim#990]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v1.9.2-1-g9059299

### Neovim version (>= 0.7)

NVIM v0.8.0

### Operating system/version

lubuntu 20.04 (is a fork of ubuntu )

### Describe the bug

I just wanted to know that how can i compeletly change my colour scheme to tokoyonight.
Now when ever i try to do it ed: change the colorschme setting in user_example/init.lua it defaults back to the default colour scheme provide by AstroNvim

### Steps to Reproduce

change the colorscheme option to "tokyonight" in user_example/init.lua

### Expected behavior

To completely chane my colour scheme to tokyo night

### Screenshots

![screen](https://user-images.githubusercontent.com/99461867/191314630-294972e5-6748-47c0-8c04-fe00bfe067ec.png)

**Comment by makon** [comment]
The `user_example/init.lua` is  just an example of configurations possibilities. If you want to change anything you need to add it to `lua/user/init.lua`. Take a look at the great documentation at: https://astronvim.github.io/Configuration/manage_user_config

Just to be clear you also need to add the plugin first, before you can use tokyonight as colorscheme:
```lua
local config = {
  colorscheme = "tokyonight-night",

  -- Configure plugins
  plugins = {
    init = {
      {"folke/tokyonight.nvim"},
    },
  },
}

return config
```

I hope this helps
