### ISSUE TITLE
nvim-cmp source_priority not respected

### ISSUE THREAD

**Issue by rafaelderolez** [AstroNvim/AstroNvim#995]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

Version: v1.9.2

### Neovim version (>= 0.7)

NVIM v0.7.2

### Operating system/version

macos 12.4

### Describe the bug

I've added 
```lua
return {
  source_priority = {
    copilot = 1000,
    nvim_lsp = 900,
    luasnip = 800,
    path = 700,
    buffer = false,
  }
}
```
to `user.plugins.cmp` but I don't feel like it's working the way it should? See screenshot down below. The order in which the autocompletions show up is all over the place. I'm not sure if it's a nvim-cmp thing or if I just misconfigured it on my end.

I would also like to limit the amount of suggestions but I suppose that's another discussion.

### Steps to Reproduce

https://github.com/rafaelderolez/astronvim/blob/main/plugins/nvim-cmp.lua

### Expected behavior

1. Copilot suggestions to come first in the dropdown.
2. Suggestion sources should be sorted properly and not mixed. 

### Screenshots

<img width="657" alt="image" src="https://user-images.githubusercontent.com/6158959/191696060-4181edc4-3c10-4ab6-a7f9-3d40581628e0.png">

<img width="512" alt="image" src="https://user-images.githubusercontent.com/6158959/191698124-75d50478-99e8-452c-893f-8ef55eabd45f.png">

<img width="524" alt="image" src="https://user-images.githubusercontent.com/6158959/191698177-729a73fc-2f46-46a7-8899-ec8e6e1ad598.png">

**Comment by mehalter** [comment]
@rafaelderolez check the documentation for where this should go. This is not part of the `require("cmp").setup({...})` call so it does not go in the `plugins` table. Here in the documentation you can see where every option should live: https://astronvim.github.io/Configuration/config_options

`cmp.source_priority` is the table in `user/init.lua` file (notice how it doesn't start with `plugins.`. Or you can put it in `user/cmp/source_priority.lua` file with the contents:

```lua
return {
  copilot = 1000,
  nvim_lsp = 900,
  luasnip = 800,
  path = 700,
  buffer = false,
}
```

**Comment by rafaelderolez** [comment]
Hey @mehalter looks like I was confused with the two entry points. Thanks for pointing it out ✌️
